### ISSUE TITLE
The clife_ prefix to the repo name is no longer required

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes-sigs/cluster-api#1]
Feel free to rename the repo.

**Comment by roberthbailey** [comment]
Looks like the repository has been renamed. Closing this issue.

**Comment by kris-nova** [comment]
TLDR; I think you have to be either 1) a repository owner or 2) a member of the `kubernetes-sigs` org in order to use the bots. 

I am going to add an agenda item for us on Wed to figure out who should be in this list.
