### ISSUE TITLE
Improve `Generate weekly PR updates to post in Slack` docs/process

### ISSUE THREAD

**Issue by cahillsf** [kubernetes-sigs/cluster-api#10008]
Currently the release documentation for [Generate weekly PR updates to post in Slack](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#generate-weekly-pr-updates-to-post-in-slack) and help from the tool does not specify what the `milestone` option should correspond to

Based on the current behavior, the `milestone` should correspond to the branch the user has checked out if working off a previous release branch or the upcoming milestone if generating from `main`, because we are using [the command](https://github.com/kubernetes-sigs/cluster-api/blob/9b340b3a86a809cab05e7b830a8920fc9d60d417/hack/tools/release/weekly/main.go#L93C137-L93C137): `git rev-list HEAD` to retrieve the commits. 

 Since `HEAD` refers to the currently checked-out branch's latest commit, it is either:
- retrieving all of the commits that have been cherry-picked to a previous release's branch (will correspond to that specific release milestone)
- retrieving all of the commits to main (will correspond to upcoming release milestone)

Currently the tool just uses the `milestone` to generate the link, but does not incorporate it when retrieving the commits, which has led to some inaccurate use of the tool

To improve this situation, we should do one or more of the following:
- update the documentation/help text to specify how the `milestone` option should be used
- improve the tool to work off 1 input to retrieve the commits and generate the milestone

/area release

**Comment by cahillsf** [comment]
see this issue for context: https://github.com/kubernetes-sigs/cluster-api/pull/9918#issuecomment-1892746418

if takes [this issue](https://github.com/kubernetes-sigs/cluster-api/issues/9982), they should be sure to solve for this as well, but the scope for the current issue is smaller and could be a quicker short term change

**Comment by typeid** [comment]
I have tried addressing this in https://github.com/kubernetes-sigs/cluster-api/pull/10092. Let me know what you think! :)
