### ISSUE TITLE
error with helm parsing double curly braces within 3 strings in `cluster-api-components.yaml`

### ISSUE THREAD

**Issue by Menosc** [kubernetes-sigs/cluster-api#10019]
### What steps did you take and what happened?

I encountered a Helm template parsing issue in the `cluster-api-components.yaml`  file with the following error message:

```yaml
[ERROR] templates/: template: cluster-api-components.yaml:1505:77: executing "cluster-api-components.yaml" at <.cluster.name>: nil pointer evaluating interface {}.name
```
the same error was in lines 1216:80: and 619:55

### What did you expect to happen?

I expected Helm to gracefully handle situations where double curly braces are used within quoted YAML strings in the cluster-api-components.yaml file without causing nil pointer errors. 

### Cluster API version

v1.6.1

### Kubernetes version

1.27

### Anything else you would like to add?

I found a workaround for this issue by using the `{{ "*/}}" }}` syntax to avoid parsing problems. Could you update your template?

### Label(s) to be applied

/kind bug
/area provider/core
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
This sounds like an issue for the Helm repo? :)
