### ISSUE TITLE
Rolling update on machine delition

### ISSUE THREAD

**Issue by nabokihms** [kubernetes-sigs/cluster-api#10027]
### What would you like to be added (User Story)?

We want to have a +1 node in the cluster on machine deletion to be able to migrate our workloads to a brand-new node. Yet, we do not want to trigger the rolling update for the whole machine deployment, only for a single node. 

This can be solved by deploying a dedicated machine deployment with one replica for each node, but this is not convenient. 

### Detailed Description

When a machine is deleted by executing the `kubectl delete machine` command, I want a new node to be added to the cluster. Then, I'd like the capi-controller to drain the node I deleted by draining all workloads from the deleted node and placing them in the ordered node. After that, I want to have the old node deleted.

### Anything else you would like to add?

Nothing, just the initial feature.

### Label(s) to be applied

/kind feature
/area machine

**Comment by nabokihms** [comment]
Probably for both requests, implementation can be the same. If the idea seems ok to maintainers, we are ready to contribute.

**Comment by fabriziopandini** [comment]
> Probably for both requests, implementation can be the same. 

/triage duplicate
Can we dedup closing this issue and moving the discussion on https://github.com/kubernetes-sigs/cluster-api/issues/9992?

> If the idea seems ok to maintainers, we are ready to contribute

That's great to hear!
Let's shape out details a little bit more first in the issue, so we have an idea/initial agreement on how this could fit in into how MachineSet and Machines are currently managed

**Comment by nabokihms** [comment]
@fabriziopandini ok, it makes sense. I will move the proposal solution from this issue to #9992
