### ISSUE TITLE
Bump github.com/docker/docker from 24.0.7+incompatible to 25.0.1+incompatible in /test

### ISSUE THREAD

**Issue by mboukhalfa** [kubernetes-sigs/cluster-api#10072]
### What would you like to be added (User Story)?

As a developer using capi test module I would like to bump `github.com/docker/docker `and fix incompatibility issue when using this module in capi test.

### Detailed Description

when trying to bump github.com/docker/docker to 25.0.1 got an error `sigs.k8s.io/cluster-api/test@v1.6.1/infrastructure/container/docker.go:408:54: cannot use restartPolicy (variable of type string) as "github.com/docker/docker/api/types/container".RestartPolicyMode value in struct literal` The type was changed in this PR https://github.com/moby/moby/pull/44704 but capi is still using the type string https://github.com/kubernetes-sigs/cluster-api/blob/a150f715f5a607ef172dbe96615ffdf1d51220b3/test/infrastructure/container/docker.go#L408.

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by chrischdi** [comment]
Wasn't this done in: https://github.com/kubernetes-sigs/cluster-api/pull/10057 ?

**Comment by chrischdi** [comment]
(ah this is not on release-1.6)

**Comment by mboukhalfa** [comment]
> (ah this is not on release-1.6)

If we can backport it to v1.6 that will unlock our docker module uplfit from the next capi patch else we wait for v1.7

**Comment by killianmuldoon** [comment]
The general policy is to not backport dependency bumps unless there's a good reason - is there something which makes the docker bump a requirement on your side? v1.7 is due for release in mid-April.

**Comment by mboukhalfa** [comment]
> The general policy is to not backport dependency bumps unless there's a good reason - is there something which makes the docker bump a requirement on your side? v1.7 is due for release in mid-April.

No requirement for now we can hold our uplift until 1.7 release.
Ok to close this issue

**Comment by killianmuldoon** [comment]
Thanks for clarifying. Let's close this.

/close
