### ISSUE TITLE
ClusterNetwork should be optional

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1009]
/kind bug

**What steps did you take and what happened:**
ClusterNetwork on v1a1.Cluster object is required but nothing else is. Is there a reason this is required and not defaulted? kubeadm can probably provide some sane defaults for these values.

**What did you expect to happen:**
defaulting the cluster network fields.

**Anything else you would like to add:**

**Comment by detiber** [comment]
I see no issues with providing defaulting for this, the question would be how to do it. There are potentially 2 different ways:
- webhook
  - this would require no changes to the types themselves
  - adding the default would not trigger an additional reconciliation
- updating the types to allow for omitempty
  - could add the default in the cluster controller, this would trigger an additional reconciliation
  - could allow to remain empty, but would require any places that would consume this value to know handle applying a default.

**Comment by davidewatson** [comment]
I think `kubeadm` does default these values. I put up a PR a while back to make this field optional: https://github.com/kubernetes-sigs/cluster-api/pull/919

**Comment by detiber** [comment]
`kubeadm` does indeed default these values. That said, this goes a bit beyond just bootstrapping, as it would also impact the CNI configuration as well.

**Comment by vincepri** [comment]
Closing now that https://github.com/kubernetes-sigs/cluster-api/pull/919 has been merged
