### ISSUE TITLE
Quick start instructions for Proxmox provider result in error

### ISSUE THREAD

**Issue by stmcginnis** [kubernetes-sigs/cluster-api#10107]
### What steps did you take and what happened?

Following the quick start guide to set up a cluster using the Proxmox provider, the `clusterctl init` command fails with an invalid version message.

```
$ clusterctl init --infrastructure proxmox --ipam in-cluster
Fetching providers
Skipping installing cert-manager as it is already installed
Installing Provider="cluster-api" Version="v1.6.1" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v1.6.1" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v1.6.1" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-proxmox" Version="v0.2.0" TargetNamespace="capmox-system"
Error: action failed after 10 attempts: failed to patch provider object: CustomResourceDefinition.apiextensions.k8s.io "proxmoxclusters.infrastructure.cluster.x-k8s.io" is invalid: status.storedVersions[0]: Invalid value: "v1beta1": must appear in spec.versions
```

It looks like the provider it installs is an older release that I am assuming is no longer valid.

There are [instructions in the Proxmox provider repo](https://github.com/k8s-proxmox/cluster-api-provider-proxmox?tab=readme-ov-file#quick-start) that use a newer version, but the instructions differ enough between the two that it isn't clear how the CAPI book docs should be updated.

It is also slightly confusing that there are instructions for adding the IPAM provider, but there is no context or instructions on why this is needed and what, if anything, needs to be configured with the IPAM provider other than just including it in the `init` command.

### What did you expect to happen?

Quick start instructions should work without errors and result in a working CAPI deployment.

### Cluster API version

```
$ clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"a150f715f5a607ef172dbe96615ffdf1d51220b3", GitTreeState:"clean", BuildDate:"2024-01-16T17:57:59Z", GoVersion:"go1.20.12", Compiler:"gc", Platform:"linux/amd64"}
```

### Kubernetes version

```
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1
```

### Label(s) to be applied

/kind bug
/area documentation

**Comment by mcbenjemaa** [comment]
Yeah. I was looking to fix this issue, 
But didn't get time yet.

**Comment by mcbenjemaa** [comment]
when merged the PR, i adjusted the table so it can hold more tabs. 

I think in some PRs someone has mixed up the tabs. 
I will try to fix it if it's still not fixed.

**Comment by mcbenjemaa** [comment]
@stmcginnis 

You're using a different proxmox provider. https://github.com/k8s-proxmox/cluster-api-provider-proxmox?tab=readme-ov-file#quick-start

But the clusterctl tries to install this provider https://github.com/ionos-cloud/cluster-api-provider-proxmox

The docs in the Quickstart are OK regarding the provider I mentioned.

You will need to adjust your clusterctl config to include https://github.com/k8s-proxmox/cluster-api-provider-proxmox

Or you can follow our [quickstart docs](https://github.com/ionos-cloud/cluster-api-provider-proxmox/blob/main/docs/Usage.md#quick-start)

**Comment by stmcginnis** [comment]
Thanks, I did realize much later that there were actually two different providers involved here, adding to the confusion. I still think it would be good to add a little more context on the IPAM requirement, but the main issue was resolved by recreating my test cluster. It appears something was left behind from earlier attempts using the other provider.

**Comment by mcbenjemaa** [comment]
You're right. It's not documented why we need IPAM,
but it's usually necessary to reserve IP addresses for the machines.

I will document that, thanks.
