### ISSUE TITLE
CAPI unable to delete node: cluster is being deleted

### ISSUE THREAD

**Issue by CharlieR-o-o-t** [kubernetes-sigs/cluster-api#10129]
### What steps did you take and what happened?

Cluster stuck in deleting process, got this error in cluster-api logs:

`
I0209 10:43:46.536685       1 machine_controller.go:340] "Deleting Kubernetes Node associated with Machine is not allowed" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" Machine="system-clusters/vsphere-eu-rasiukevich2-m87jt-455fj" namespace="system-clusters" name="vsphere-eu-rasiukevich2-m87jt-455fj" reconcileID=2b7cf402-8a9d-4d66-a6a1-82fe026472d9 KubeadmControlPlane="system-clusters/vsphere-eu-rasiukevich2-m87jt" Cluster="system-clusters/vsphere-eu-rasiukevich2" Node="" cause="cluster is being deleted"
`

So, node can't be deleted because cluster in "delete" state. 
Can't clearly understand logic of the following check in cluster-api . For what purpose "errClusterIsBeingDeleted" is here? 

./internal/controllers/machine/machine_controller.go
`
func (r *Reconciler) reconcileDelete(ctx context.Context, cluster *clusterv1.Cluster, m *clusterv1.Machine) (ctrl.Result, error) { //nolint:gocyclo
	log := ctrl.LoggerFrom(ctx)

	err := r.isDeleteNodeAllowed(ctx, cluster, m)
	isDeleteNodeAllowed := err == nil
	if err != nil {
		switch err {
		case errNoControlPlaneNodes, errLastControlPlaneNode, errNilNodeRef, errClusterIsBeingDeleted, errControlPlaneIsBeingDeleted:
			var nodeName = ""
			if m.Status.NodeRef != nil {
				nodeName = m.Status.NodeRef.Name
			}
			log.Info("Deleting Kubernetes Node associated with Machine is not allowed", "Node", klog.KRef("", nodeName), "cause", err.Error())
		default:
			return ctrl.Result{}, errors.Wrapf(err, "failed to check if Kubernetes Node deletion is allowed")
		}
`

Thank you in advance. 

### What did you expect to happen?
machine deleted. 

### Cluster API version
v1.5.1

### Kubernetes version
v1.24.15

/kind bug

**Comment by schrej** [comment]
That's not an error, it's just an info log. The reason is that there is no need to delete the Node resource from the tenant cluster when the entire cluster will be gone soon anyway. If the ControlPlane is already cleaned up, it won't even be possible to delete the node resource.

If your Machine deletion is stuck, it should be caused by something else.

**Comment by CharlieR-o-o-t** [comment]
Oh, yes, my bad. 
I think that it's clear enough, since this is Info log level.

I'll close this issue.
