### ISSUE TITLE
Allow MachinePools without MachinePoolMachines to exist in workload cluster for clusterctl upgrade e2e test

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api#10134]
### What would you like to be added (User Story)?

As an infrastructure provider, I want to leverage CAPI's clusterctl upgrade e2e test to test upgrades of my provider while it is managing MachinePools without MachinePoolMachines.

### Detailed Description

While #9892 enables MachinePools in workload clusters for this test, it still assumes that Machines exist to represent the instances. The test should lift its assumption that a Machine exists for each MachinePool replica to enable testing implementations like CAPZ's AzureManagedMachinePool.

### Label(s) to be applied

/kind feature
/area testing

**Comment by sbueringer** [comment]
Sounds good!

/triage accepted

**Comment by sbueringer** [comment]
Absolutely makes sense, @nojnhuh feel free to open a PR

/triage accepted
