### ISSUE TITLE
Cluster API Kind discussion

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1015]
# Background

In the development of https://github.com/vmware/cluster-api-upgrade-tool we found we needed a testing Cluster API provider. I built a provider with Kind as the backend. It could be very useful for testing Cluster API itself.

## Where is it

It's closed at the moment until it finds a home.

## Steps

- [ ] sig adoption
- [ ] put the code somewhere

I think the sig has to adopt it, I'd need someone from outside VMware that is willing to sponsor it as well, but @timothysc can confirm. This probably doesn't need to happen if it lives in *this* repo, because it won't be its own separate project but a part of Cluster API.

I think it makes the most sense to keep it outside of Cluster API because we can move it in if we end up adopting it as a framework. It would be a huge hassle if we drag it into Cluster API, figure out multi-projectness without go mod and then end up not using it. If we want to move it in at some point, I think that would be fine to do later. But definitely open to other thoughts!

**Comment by ncdc** [comment]
@chuckha do you anticipate the kind provider needing a different set of dependency versions compared to those needed by cluster-api proper?

**Comment by chuckha** [comment]
No. Like all providers it is strongly bound to cluster-api dependencies and cannot have a different set of dependency versions.

**Comment by ncdc** [comment]
Ok, maybe I misinterpreted what you meant by
>  It would be a huge hassle if we drag it into Cluster API, figure out multi-projectness without go mod and then end up not using it.

What is the multi-projectness issue?

**Comment by timothysc** [comment]
I'm a +1 for in-tree to serve as reference and for faster turn-key testing, in the fullness of time we could always move it out as well.

**Comment by chuckha** [comment]
@ncdc It has its own Dockerfile, set of binaries and libraries and additional dependencies on top of Cluster API.

If we merge the projects together, cluster api adopts all of these dependencies as well as additional binaries to produce and container images to build. I'm not sure what that would look like if we merged them all together. 

The multiproject bit I was talking about was thinking about how to organize these two projects in the same repository. For example, maybe it looks like cluster-api/capk which is the root of the capk project and cluster-api/capi is the root of the capi project?

**Comment by detiber** [comment]
I'm in favor of out-of-tree for a few different reasons:
- It avoids any accidental tight coupling with cluster-api
- It avoids vendoring the kubeadm types into the cluster-api repo (at least for v1alpha1)
- Standalone provides a better example to users for how to implement a provider
- It keeps the cluster-api repo proper cleaner and avoids developer confusion around what cluster-api is/isn't

**Comment by ncdc** [comment]
To give an example from another project, Velero has multiple Dockerfiles that produce different container images with different executables and/or purposes. I'm not super worried about a single GitHub repository producing multiple executables and container images, FWIW.

From Jason:
> It avoids vendoring the kubeadm types into the cluster-api repo (at least for v1alpha1)

This would be a nice thing to avoid.

**Comment by vincepri** [comment]
I'm also in favor of keeping providers out-of-tree for the time being

**Comment by neolit123** [comment]
cc @fabriziopandini

**Comment by chuckha** [comment]
I'm considering putting this on my personal GitHub for a temporary public home so that people can look at it and have a better idea of what would be merging into this repo.

here is the go.mod file 

```
module gitlab.com/chuckh/cluster-api-provider-kind

go 1.12

require (
	github.com/appscode/jsonpatch v0.0.0-20190108182946-7c0e3b262f30 // indirect
	github.com/go-logr/logr v0.1.0 // indirect
	github.com/go-logr/zapr v0.1.1 // indirect
	github.com/golang/groupcache v0.0.0-20190129154638-5b532d6fd5ef // indirect
	github.com/google/btree v1.0.0 // indirect
	github.com/gregjones/httpcache v0.0.0-20190212212710-3befbb6ad0cc // indirect
	github.com/hashicorp/golang-lru v0.5.1 // indirect
	github.com/imdario/mergo v0.3.7 // indirect
	github.com/pborman/uuid v1.2.0 // indirect
	github.com/peterbourgon/diskv v2.0.1+incompatible // indirect
	github.com/pkg/errors v0.8.0
	github.com/prometheus/client_golang v0.9.4 // indirect
	go.uber.org/atomic v1.4.0 // indirect
	go.uber.org/multierr v1.1.0 // indirect
	go.uber.org/zap v1.10.0 // indirect
	golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45 // indirect
	golang.org/x/time v0.0.0-20190308202827-9d24e82272b4 // indirect
	k8s.io/api v0.0.0-20181213150558-05914d821849
	k8s.io/apiextensions-apiserver v0.0.0-20181213153335-0fe22c71c476 // indirect
	k8s.io/apimachinery v0.0.0-20181127025237-2b1284ed4c93
	k8s.io/client-go v10.0.0+incompatible
	k8s.io/cluster-bootstrap v0.0.0-20181213155137-5f9271efc2e7 // indirect
	k8s.io/kubernetes v1.13.1
	sigs.k8s.io/cluster-api v0.0.0-20190607141803-aacb0c613ffb
	sigs.k8s.io/controller-runtime v0.1.10
	sigs.k8s.io/kind v0.2.1
	sigs.k8s.io/testing_frameworks v0.1.1 // indirect
)

replace sigs.k8s.io/kind => github.com/chuckha/kind v0.0.0-20190609180745-73d145437758
```

**Comment by timothysc** [comment]
> It avoids any accidental tight coupling with cluster-api

I actually want this ... for now.  My primary concern at this point is project velocity

> It avoids vendoring the kubeadm types into the cluster-api repo (at least for v1alpha1)

We're working on making sure the factoring is cleaner and scoped, but that is orthogonal imo. 

> Standalone provides a better example to users for how to implement a provider

But it also requires separate maintenance and vendoring back<>forth will be an issue. 

> It keeps the cluster-api repo proper cleaner and avoids developer confusion around what cluster-api is/isn't

I'm not concerned with it at this time, my primary concern is developer productivity and project velocity.  

History has also taught me federated repositories becomes terribly complicated for users to make sense of.

**Comment by chuckha** [comment]
Here it is https://github.com/chuckha/cluster-api-provider-kind

**Comment by chuckha** [comment]
Final call, in the June 19th meeting, we're keeping this external:

I will figure out how to get a kubernetes-sigs repo named `cluster-api-provider-docker` instead of kind as kind is only a small part of the implementation and the provider is really docker.

**Comment by chuckha** [comment]
thanks for all the input!
