### ISSUE TITLE
Wrong urls for clusterawsadm file for both Linux and MacOs in the quick start

### ISSUE THREAD

**Issue by salehsedghpour** [kubernetes-sigs/cluster-api#10169]
### What steps did you take and what happened?

For Linux I followed the instruction:
```
curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v2.3.1/clusterawsadm-linux-amd64 -o clusterawsadm
```
For MacOS:
```
# Intel
curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v2.3.1/clusterawsadm-darwin-amd64 -o clusterawsadm

#ARM
curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v2.3.1/clusterawsadm-darwin-arm64 -o clusterawsadm
```

In all cases, when I investigated the content of downloaded file, I only saw `Not Found`
```
$ cat clusterawsadm 
Not Found
```

### What did you expect to happen?

I expected to download the the actual CLI and just noticed that the URL is wrong and I needed to use the following url in all commands:
```
# Linux
https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v2.3.1/clusterawsadm-linux-amd64

# MacOS Intel
https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v2.3.1/clusterawsadm-darwin-amd64

# MacOS ARM
https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v2.3.1/clusterawsadm-darwin-arm64
```

### Cluster API version

v1.6 (v1beta1)

### Kubernetes version

1.29

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by chrischdi** [comment]
I think its getting worked on this at https://github.com/kubernetes-sigs/cluster-api/pull/9870 but seems to be stale currently.

**Comment by salehsedghpour** [comment]
I was wondering if that PR is only targeting Windows environments.

**Comment by chrischdi** [comment]
Ah I think you're right. We just identified the url is wrong also for windows there 👍

**Comment by bigfish24** [comment]
This has reoccurred. 

Quick start: curl -L https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v2.5.2/clusterawsadm-linux-amd64 -o clusterawsadm

Expected: https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v2.5.2/clusterawsadm_v2.5.2_linux_amd64

**Comment by sbueringer** [comment]
Yeah looks like CAPA changed the name of the binary with v2.5.0. If that was an intended change the CAPI book should be updated accordingly (we should probably confirm)

**Comment by sbueringer** [comment]
@nrb @vincepri @dlipovetsky Looking for confirmation that the new binary name was intentional, then we would update the docs in core CAPI.

**Comment by dlipovetsky** [comment]
Thanks for the ping. Following up.

**Comment by nrb** [comment]
This has been fixed for the affected releases. I have also made a [PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5055) to fix it going forward.
