### ISSUE TITLE
Code walkthrough

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api#1017]
Per-discussions during grooming, we are going todo a code walkthrough or audit.  

The purposes of code walkthroughs is both to inform, but to also open issues on longstanding bugs, warts, etc in the code. 

If folks have proposed times, please add them below otherwise I will send out a doodle.

**Comment by dhellmann** [comment]
It would be great to put together some sort of rough agenda or ordering, so new folks like me can read ahead in an order that would be helpful.

**Comment by ncdc** [comment]
Monday or Tuesday next week is probably better for me than the other days, although I can probably make anything work.

**Comment by timothysc** [comment]
> It would be great to put together some sort of rough agenda or ordering, so new folks like me can read ahead in an order that would be helpful. 

Code walkthroughs are pretty ad hoc conversations where you have someone driving the code and others asking questions about why.

**Comment by dlipovetsky** [comment]
I propose the Implementers Office Hours time slots _as options_. I see no reason to exclude them.

Tue 12pm PT
Wed 6am PT (15:00 CET)

**Comment by dhellmann** [comment]
> > It would be great to put together some sort of rough agenda or ordering, so new folks like me can read ahead in an order that would be helpful.
> 
> Code walkthroughs are pretty ad hoc conversations where you have someone driving the code and others asking questions about why.

Presumably we wouldn't do that by picking files at random, though, right?

**Comment by ncdc** [comment]
I would start by explaining the overall structure of the repo, in terms of API types, controllers, etc. I'd talk about the Manager first, then work my way into each controller.

**Comment by dhellmann** [comment]
> I would start by explaining the overall structure of the repo, in terms of API types, controllers, etc. I'd talk about the Manager first, then work my way into each controller.

That's the sort of thing I'm looking for. But with some filenames for us n00bs. :-)

**Comment by timothysc** [comment]
Folks want to add to the open capi-agenda a Code-Walkthrough section and we can use that as our guide?

**Comment by timothysc** [comment]
@vincepri when you send out the invite feel free to close with deets.

**Comment by vincepri** [comment]
Invite sent!

/close
