### ISSUE TITLE
add default worker-machine-count in clusterctl 

### ISSUE THREAD

**Issue by kranurag7** [kubernetes-sigs/cluster-api#10173]
### What would you like to be added (User Story)?

`clusterctl generate cluster demo-cluster --kubernetes-version 1.27.7 > new-cluster.yaml` 

When I invoked the above command, I got `1` controlplane and `0` machinedeployment out of the box. 

Upon checking the help message, I found the following. 

```bash
$ clusterctl generate cluster -h
--control-plane-machine-count int    The number of control plane machines for the workload cluster. (default 1)
--worker-machine-count int           The number of worker machines for the workload cluster.
```

### Detailed Description

Looking at this for the first time, it's not clear to me that `--worker-machine-count` default to zero. I think it would be good if we add the `(default 0)` message next to `--worker-machine-count` flag as well. 

The flag default to zero.
https://github.com/kubernetes-sigs/cluster-api/blob/323f8bb1d734b05d65c7b65963d0addf64c3358c/cmd/clusterctl/cmd/generate_cluster.go#L119-L120

### Label(s) to be applied

/kind feature
/area clusterctl

**Comment by fabriziopandini** [comment]
Default is usually added by cobra, which omits this field when the default is the zero value for the flag type like in this case.
However, if this can help users, I'm not opposed to being more explicit in clusterctl and adding it manually.

/triage accepted
/good-first-issue
