### ISSUE TITLE
Check Kubetest parameters

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#10171]
### What steps did you take and what happened?

I was checking a test running conformance on https://github.com/kubernetes-sigs/cluster-api/pull/10166 and I noticed those logs entries

```
  You're using deprecated Ginkgo functionality:
  =============================================
    --ginkgo.flakeAttempts is deprecated, use --ginkgo.flake-attempts instead
    Learn more at: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed-command-line-flags
    --ginkgo.progress is deprecated .  The functionality provided by --progress was confusing and is no longer needed.  Use --show-node-events instead to see node entry and exit events included in the timeline of failed and verbose specs.  Or you can run with -vv to always see all node events.  Lastly, --poll-progress-after and the PollProgressAfter decorator now provide a better mechanism for debugging specs that tend to get stuck.
    --ginkgo.slowSpecThreshold is deprecated use --slow-spec-threshold instead and pass in a duration string (e.g. '5s', not '5.0')
    Learn more at: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed--slowspecthreshold
```

It would be great to check if we have the same issue on the more recent branches (main, 1.6., 1.%) and eventually fix it

cc @kubernetes-sigs/cluster-api-release-team 

### What did you expect to happen?

Our tests to not use deprecated flags

### Cluster API version

1.4.x

### Label(s) to be applied

/kind bug
/area ci

**Comment by adilGhaffarDev** [comment]
We see these deprecation warnings in main, 1.6, and 1.5 too. I will open a PR with the fix. /assign
