### ISSUE TITLE
Manual remediation of Machines

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#10197]
### What would you like to be added (User Story)?

As an operator, I would like to be able to recreate single machines in a controlled way

### Detailed Description

The traditional way to re-create a single Machine is to delete it manually.

However, directly deleting a machine has some well-known downsides:
- Once the operation is done, it cannot be reverted
- The operation is "low level", it skips several system safeguards and this can be risky especially when you delete control plane nodes (see discussion in https://github.com/kubernetes-sigs/cluster-api/issues/9919). More speifically
  - With manual deletion, all the checks about [max unhealthy](https://github.com/kubernetes-sigs/cluster-api/blob/0f47a19e038ee6b0d3b1e7675a62cdaf84face8c/api/v1beta1/machinehealthcheck_types.go#L53-L65), are implicitly skipped
  - With manual deletion, all the checks about the fact the machine can be [safely remediated](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20191017-kubeadm-based-control-plane.md#remediation-using-delete-and-recreate), are implicitly skipped
  
This proposal is about introducing a new annotation (name TBD) to be applied to a machine that the operator wants to safely delete (and thus to leave "low level" deletion only as the ultimate escape patch).

This annotation will be processed by the MHC controller in [healthCheckTargets](https://github.com/kubernetes-sigs/cluster-api/blob/0f47a19e038ee6b0d3b1e7675a62cdaf84face8c/internal/controllers/machinehealthcheck/machinehealthcheck_targets.go#L283), and this the machine will be included in the pool of machines to be considered for remediation.
 
MHC, will then determine if there are the conditions to remediate such a machine, and the remediation with then be taken charge of by the owning controller or by the external remediation tool.

The remediation owner will then perform another round of checks, and finally transform the manual remediation in an actual machine deletion.
 
 

### Anything else you would like to add?

Once this is in place, we can eventually think of strategies to give higher priority for deletion to machines being remediated/manually remediated, in case more machines are being deleted at the same time.
However this is less important than providing a safe path to deletion (and thus IMO not blocking for a first iteration)

### Label(s) to be applied

/kind feature
/area machinehealthcheck
/triage accepted

**Comment by Levi080513** [comment]
Nice idea!!!
It would be better if we could support this feature in clusterctl, like `kubectl drain`.

**Comment by sbueringer** [comment]
I think you can already do it. You just also have to set conditions on the machine like the mhc controller
