### ISSUE TITLE
Does KubeadmConfigTemplate support kubeproxy configuration

### ISSUE THREAD

**Issue by xagent003** [kubernetes-sigs/cluster-api#10237]
### What steps did you take and what happened?

KudeAdm supports various configuration resources: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#customizing-kube-proxy

> Customizing kube-proxy
> To customize kube-proxy you can pass a KubeProxyConfiguration next your ClusterConfiguration or InitConfiguration to kubeadm init separated by ---.

You can see there is a InitConfiguration, ClusterCOnfiguration, Join Configuration, as well as a KubeletConfiguration and KubeProxyConfiguration: https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/

But when I look at the definition for KubeadmConfigTemplate, only Init/Join/Cluster Configuration is supported: https://github.com/kubernetes-sigs/cluster-api/blob/22ec35e088d39a55e75953ef158bae493003b325/bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go#L53

How do we go about configuring kube-proxy with CAPI?

### What did you expect to happen?

Allow specifying KubeProxyConfiguration in the KubeadmConfigTemplate

### Cluster API version

1.5.3

### Kubernetes version

1.26

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by neolit123** [comment]
/remove-kind bug
/kind support
kubelet and kube-proxy config are not supported by CAPI.

https://github.com/kubernetes-sigs/cluster-api/issues/1584

i think the suggested approach is to skip kubeproxy as a kubeadm addon and manage it yourself.

https://github.com/kubernetes-sigs/cluster-api/issues/3700
https://github.com/kubernetes-sigs/cluster-api/issues/4512

i think there was a way to skip the kubeadm addons with an annotation, but i can't find where are the docs for that.

**Comment by chrischdi** [comment]
There is: `controlplane.cluster.x-k8s.io/skip-kube-proxy` which can be set at the KubeadmControlPlane object.

see: https://cluster-api.sigs.k8s.io/reference/labels_and_annotations

**Comment by chrischdi** [comment]
xref: https://github.com/kubernetes-sigs/cluster-api/issues/3700#issuecomment-1267101382

The annotation only makes capi not handle upgrades for kube-proxy anymore. You would still need to configure kubeadm to skip deploying it or use preKubeadmCommands to adjust things to make the kubeadm way of adding the additional configuration (which I think is very hacky).

Other previous issues about this topic:

- https://github.com/kubernetes-sigs/cluster-api/issues/4512
- https://github.com/kubernetes-sigs/cluster-api/issues/3700

**Comment by fabriziopandini** [comment]
/close

Answer have been provided, no further feedback

**Comment by xagent003** [comment]
> There is: `controlplane.cluster.x-k8s.io/skip-kube-proxy` which can be set at the KubeadmControlPlane object.
> 
> see: https://cluster-api.sigs.k8s.io/reference/labels_and_annotations

I don't want to skip kube-proxy configuration. I want to be able to configure it. KubeAdm allows it. So why doesn't CAPI which uses kubeadm do the same?

**Comment by chrischdi** [comment]
Hacky but works:

You could add the kube-proxy config as a file, e.g.:

```
---
THE CONFIG
```

And have a pre-kubeadmcommand adding it to the kubeadm config file for `kubeadm init`: 
```
test -e "/run/kubeadm/kubeadm.yaml" && cat /the/config-file >> /run/kubeadm/kubeadm.yaml
```

**Comment by jfpucheu** [comment]
This solution works, tanks @chrischdi but it seems impossible to change it automatically during a rollout because the cluster has already been initialized with kubeadm. I don’t understand why the issue was closed.
