### ISSUE TITLE
use new EventRecorder to emit v1beta1 Events

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api#1023]
/kind feature

**Describe the solution you'd like**  use the new eventRecorder that will be available on client-go to emit Events the under the new API ref kubernetes/enhancements#383

cc @detiber @timothysc 

/assign
/priority backlog

**Comment by detiber** [comment]
There are three main blockers to this at the moment:
- The version of kubernetes that is vendored through transitive dependencies from controller-runtime and controller-tools
- The event recorder is initialized by the controller-runtime manager
- Supported management clusters would be required to be >= v1.15

/milestone Next

**Comment by yastij** [comment]
> * The version of kubernetes that is vendored through transitive dependencies from controller-runtime and controller-tools

I agree, but the event logic lives under client-go so we'd need to bump only client-go (which depends on the compatibility matrix)

> * Supported management clusters would be required to be >= v1.15

the API exists in kubernetes since 1.9 (ref kubernetes/kubernetes#49112)

**Comment by vincepri** [comment]
Closing this as we're using the controller-runtime client everywhere

/close
