### ISSUE TITLE
Add info to contributing doc about how to join the Kubernetes org

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1024]
/kind feature

**Describe the solution you'd like**
Add info to contributing doc about how to join the Kubernetes org so people can be assigned issues, etc.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jaypipes** [comment]
The kubernetes-sigs org is the one that you need to belong to, correct?

**Comment by detiber** [comment]
Yes, `kubernetes-sigs` is indeed the org in question

**Comment by jaypipes** [comment]
Roger. I'll push up a PR with a doc shortly. :)

**Comment by vincepri** [comment]
Closing now that #1030 has been merged.

/close
