### ISSUE TITLE
Overriding cluster-api-controller image version

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes-sigs/cluster-api#1033]
/kind feature

**Describe the solution you'd like**
From the perspective of cluster API providers, the cluster API CRD + controller specs are pulled in from `vendor/sigs.k8s.io/cluster-api` as part of `generate-yaml.sh`. This is not ideal in cases where I want to pin the cluster-api-controller statefulset to a specific version, the latest version of `sigs.k8s.io/cluster-api` points to `latest`. 

The work around at the moment would be to copy the `kustomization.yaml` in `config/default/kustomization.yaml` into the provider repo and then add my own patch file for the controller image. However, this still seems error prone and may lead to the kustomization.yaml config file deviating. Not sure what the best approach is here but wanted to open an issue in case other folks have ideas or better solutions.  

**Anything else you would like to add:**
See https://github.com/akutz/cluster-api-provider-vsphere/pull/4 for an example of copying the `kustomization.yaml` file to override only the manager patch image.

**Comment by akutz** [comment]
Also, we advise against pulling “latest” and recommend specifying an explicit tag when possible.

**Comment by vincepri** [comment]
Are you vendoring master instead of the `release-X` branch?

**Comment by andrewsykim** [comment]
/close

Updating to the latest version of release-0.1 fixed this. Thanks!
