### ISSUE TITLE
Unit test failure in CAPZ w/ CAPI v1.7.0-beta.1

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api#10331]
### Which jobs are failing?

N/A

### Which tests are failing?

The `TestASOSecretReconcile` unit test in CAPZ is failing on the branch that's integrating CAPZ v1.7.0-beta.1. See kubernetes-sigs/cluster-api-provider-azure#4646 and [this comment](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4646#issuecomment-1995511466) in particular.

### Since when has it been failing?

Since trying to integrate CAPI v1.7.0-beta.0.

### Reason for failure (if possible)

The reason seems to be that `.GetObjectKind()` returns a partially empty object.

### Label(s) to be applied

/kind failing-test

**Comment by mboersma** [comment]
This seems very likely related to kubernetes-sigs/cluster-api#9956

**Comment by mboersma** [comment]
/close

This change in controller-runtime is probably what caused the unit test to fail: kubernetes-sigs/controller-runtime#2633

Fixed in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4646/commits/d787ca4433248a13db27ca5a8163c57f5bd2bcc0 by not relying on the GVK having `TypeMeta` populated. See also #9956.

**Comment by sbueringer** [comment]
Makes sense!
