### ISSUE TITLE
Weekly markdown link check tests are failing

### ISSUE THREAD

**Issue by Sunnatillo** [kubernetes-sigs/cluster-api#10333]
### Which jobs are failing?

Weekly markdown link check github action tests

### Which tests are failing?

[weekly-md-link-check.yaml ](https://github.com/kubernetes-sigs/cluster-api/actions/workflows/weekly-md-link-check.yaml)

### Since when has it been failing?

last week

### Reason for failure (if possible)

The [Google doc](https://github.com/kubernetes-sigs/cluster-api/blob/f830e0a4f0501f797ea87fdd397e3110fe5a54ef/docs/proposals/20200511-clusterctl-extensible-template-processing.md?plain=1#L283) mentioned in the docs/proposals/20200511-clusterctl-extensible-template-processing.md does not exist anymore.

**Comment by Sunnatillo** [comment]
@fabriziopandini CAEP Google doc does not exist anymore? Is there someone who have the saved to the doc? Should I remove the mention or keep the mention without link?

**Comment by sbueringer** [comment]
@Sunnatillo It's fine to just drop the link and leave it as
```md
- 04/27/2020: Compile a CAEP Google Doc following the CAEP template
```
