### ISSUE TITLE
switch from k8s.io/code-generator to controller-gen for all clients

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api#1034]
/kind feature

**Describe the solution you'd like**
This project is pulling all the controller runtime goodies and already uses controller-gen as part of make manifests. This issue is about refactoring to shift dependencies on the clientset in clusterctl and manager to use the controller-runtime provided clients instead. 

**Anything else you would like to add:**
~This could either be done similar to currently, newing up a new client for each request, or reshuffling a bit and we can use `manager.GetClient()`.~ Not about newing up individual clients, but about removing boilerplate once the client used is the same everywhere (not a client per typed/method/namespace).

**Comment by vincepri** [comment]
I think we can safely close this now that v1alpha2 isn’t shipping clientsets anymore

/close
