### ISSUE TITLE
Restructure release docs stack

### ISSUE THREAD

**Issue by cahillsf** [kubernetes-sigs/cluster-api#10354]
here is the kubernetes release example: https://github.com/kubernetes/sig-release/tree/master/release-team

the idea is to split some of these lengthier docs (i.e. https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md) so they are broken up by team.  this makes them easier to consume and improves the organization of the release docs

/area release

**Comment by dhij** [comment]
I can take this one.
