### ISSUE TITLE
Release notes generation documentation and `make` target don't work for release candidates

### ISSUE THREAD

**Issue by typeid** [kubernetes-sigs/cluster-api#10396]
The [release note generation documentation](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#create-pr-for-release-notes) does not work for release candidates. 

```
RELEASE_TAG=v1.7.0-rc.1 make release-notes 
go build -C hack/tools -o /home/kubernetes/cluster-api/bin/notes -tags tools sigs.k8s.io/cluster-api/hack/tools/release/notes
./bin/notes --release v1.7.0-rc.1 > CHANGELOG/v1.7.0-rc.1.md
2024/04/08 16:13:48 --previous-release-version need to be set with RELEASE CANDIDATE/BETA RELEASE tag
make: *** [Makefile:1169: release-notes] Error 1
```

The make target `make release-notes` does not allow providing this parameter:
```
.PHONY: release-notes
release-notes: release-notes-tool
	./bin/notes --release $(RELEASE_TAG) --previous-release-version rc/v1.7.0-rc.0 > CHANGELOG/$(RELEASE_TAG).md
```

For rc/beta, we need to pass `--previous-release-version` to the the release notes generation tooling. 

Correct call of the release note generation tooling for v1.7.0-rc.1:
```
./bin/notes --release v1.7.0-rc.1 --previous-release-version rc/v1.7.0-rc.0 > CHANGELOG/v1.7.0-rc.1.md
```

We should fix this issue and document the usage of `make release-notes` for release candidates.

**Comment by chandankumar4** [comment]
I'll work on this issue, as it looks to be happening after my previous PR https://github.com/kubernetes-sigs/cluster-api/pull/10091 
/assign
