### ISSUE TITLE
Kubeadm Bootstrapper

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1039]
/kind feature
/area machine
/area control-plane
/milestone v1alpha2

**Describe the solution you'd like**
This issue is to track the development towards v1alpha2, including [Machine States & Preboot Bootstrap Proposal](https://github.com/kubernetes-sigs/cluster-api/pull/997).

- [ ] Create provider repository `sigs/cluster-api-provider-kubeadm` @chuckha 
- [ ] Create API types
- [ ] Create controllers
- [ ] Design configuration types and their initial functionality

Most of this work has been done in the [v1alpha1 AWS Infrastructure Provider](https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/release-0.3) and should/can be used as a reference.

**Comment by chuckha** [comment]
This will live external to this repository. I will figure out the steps to create a repo for it.

**Comment by chuckha** [comment]
watch me flail wildly with kubernetes process: https://github.com/kubernetes/community/pull/3818

**Comment by chuckha** [comment]
more wild flailing: https://github.com/kubernetes/org/issues/937

**Comment by vincepri** [comment]
@chuckha Can you add also myself and @detiber to owners and maintainers?

**Comment by chuckha** [comment]
yeah, y'all are added, it's a subproject of capi so it's same permissions as here + me as I'm the only author right now

**Comment by vincepri** [comment]
Closing this given that the development is happening out of tree.

/close

**Comment by detiber** [comment]
Repo is here: https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm
