### ISSUE TITLE
Should the CI be using the kustomize binary?

### ISSUE THREAD

**Issue by tariq1890** [kubernetes-sigs/cluster-api#1046]
I see that kustomize is being installed [here](https://github.com/kubernetes-sigs/cluster-api/blob/master/scripts/ci-integration.sh#L35).

If I am not mistaken, the latest kubectls have `kustomize` built-in and we could use `apply -k` instead?

**Comment by detiber** [comment]
@tariq1890 I have no objections to switching to the built-in kustomize

**Comment by ncdc** [comment]
Is this related to #859?

**Comment by tariq1890** [comment]
Yes it is! This can be closed I guess.
