### ISSUE TITLE
Deprecate KCP.Available condition

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#10532]
### What would you like to be added (User Story)?

As a user I would like clear observability signals.

### Detailed Description

As per https://github.com/kubernetes-sigs/cluster-api/issues/3779 discussion:

> WRT to Initialized vs Available:
>
> - As of today Cluster.ControlPlaneInitialized is used everywhere.
> - Cluster.ControlPlaneInitialized derives from ControlPlane.status.initialized, and it is up to the control plane provider to determine when to set it to true (KCP currently assumes the control plane is initialized when there is a kubeadm-config map in the workload cluster, and this imply that there is a working LB and API server for the workload cluster).
> - Available condition exists only in KCP, and it has the very same meaning of KCP.status.initialized
>
> Considered that IMO the most practical way forwards is
>
> - To close this issue because we don't need to change the contract, ControlPlane.status.initialized is already documented
> - To open a new issue to drop KCP.Available, or to replace it with KCP.Initialized to get rid of the less used noun

This issue is about the last point.
My preference goes to introduce a KCP.Initialized condition (that mirrors ControlPlane.status.initialized)

### Label(s) to be applied

/kind cleanup
/kind api-change
/area control-plane
/priority important-longterm

**Comment by sbueringer** [comment]
I guess we can already work on deprecating the current Available condition and adding the new one? (then we only have to drop the old one with the next apiversion)

**Comment by fabriziopandini** [comment]
> I guess we can already work on deprecating the current Available condition and adding the new one?

That's correct

**Comment by sbueringer** [comment]
This will be adressed by #10897, please take a look at the proposal for more details

/close
