### ISSUE TITLE
Controller should wait for cache sync before starting working

### ISSUE THREAD

**Issue by mvladev** [kubernetes-sigs/cluster-api#106]
From [writing controllers guide](https://github.com/kubernetes/community/blob/master/contributors/devel/controllers.md):

> Wait for your secondary caches. Many controllers have primary and secondary resources. Primary resources are the resources that you'll be updating Status for. Secondary resources are resources that you'll be managing (creating/deleting) or using for lookups.
>
> Use the framework.WaitForCacheSync function to wait for your secondary caches before starting your primary sync functions. This will make sure that things like a Pod count for a ReplicaSet isn't working off of known out of date information that results in thrashing.

Controllers should wait for:

- `Machine` controller - `Machine` and `Node`
- `MachineSet` controller - `MachineSet`, `Machine` and? `Node`
- `MachineDeployment` controller - `MachineDeployment`, `MachineSet`, `Machine` and? `Node`

to sync.

The sync should happen, before we [start the worker threads](https://github.com/kubernetes/sample-controller/blob/9b81532a606166870df632aa9501b312845edea7/controller.go#L165-L167).

This depends on #74 and possibly should extend to `MachineSet` and `MachineDeployment`

**Comment by k4leung4** [comment]
This has been added to MachineSets in PR #186 
Still working on adding it to Machine and MachineDeployment controllers.

**Comment by roberthbailey** [comment]
@mvladev - Is this still an issue that needs to be tracked now that we are using kubebuilder to handle the caches for us?

**Comment by mvladev** [comment]
@roberthbailey kube builder handles that already https://github.com/kubernetes-sigs/controller-runtime/blob/53fc44b56078cd095b11bd44cfa0288ee4cf718f/pkg/cache/internal/deleg_map.go#L66-L72
