### ISSUE TITLE
Exporting ControlPlaneInitMutex

### ISSUE THREAD

**Issue by nasusoba** [kubernetes-sigs/cluster-api#10603]
### What would you like to be added (User Story)?

As a developer for other bootstrap provider, I would like to have `ControlPlaneInitMutex` ([ref](https://github.com/kubernetes-sigs/cluster-api/blob/main/bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go)) exported, so that I do not have to duplicate the code in elsewhere.

### Detailed Description

`ControlPlaneInitMutex` ([control_plane_init_mutex.go](https://github.com/kubernetes-sigs/cluster-api/blob/main/bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go)) is providing functionality for the first and only control plane node to run init. It is not specific to `kubeadm provider`. For other bootstrap providers like `capi k3s`/ `capi rke2` /`etcdadm-bootstrap-provider`, we also need it. But we need to copy this file, because `control_plane_init_mutex.go` is put inside an internal folder.

### Anything else you would like to add?

Could I move this file to [cluster-api](https://github.com/kubernetes-sigs/cluster-api/tree/main)/[util](https://github.com/kubernetes-sigs/cluster-api/tree/main/util), e.g., `cluster-api/util/locking`, so that it could be reused by other bootstrap providers?

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by neolit123** [comment]
> etcdadm-bootstrap-provider

there is a CAPI provider for etcdadm??

note that we have a plane to archive etcdadm.
https://github.com/kubernetes-sigs/etcdadm
https://github.com/kubernetes-sigs/etcdadm/issues/395

> ControlPlaneInitMutex ([control_plane_init_mutex.go](https://github.com/kubernetes-sigs/cluster-api/blob/main/bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go)) is providing functionality for the first and only control plane node to run init

i agree that the concept of "init"/"join" is not unique to kubeadm.
