### ISSUE TITLE
Support anyOf/oneOf/allOf/not schema constraints for ClusterClass variables

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes-sigs/cluster-api#10636]
### What would you like to be added (User Story)?

As a ClusterClass developer, I would like to make use of anyOf/oneOf/allOf/not schema constraints for ClusterClass variables in order to describe more complex variable schema definitions.

### Detailed Description

In order to support objects, lists and maps that can support only certain combinations of properties, it would be very useful to support anyOf/oneOf/allOf/not schema constraints. This enables describing which property combinations are valid, which are mutually exclusive, etc.

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by fabriziopandini** [comment]
We already added features to the initial implementation of cluster class variables, this one adds to list
/priority important-longterm

/triage accepted
given that there is already a PR for it
