### ISSUE TITLE
Failed to create bootstrap cluster using alpha phases

### ISSUE THREAD

**Issue by posox** [kubernetes-sigs/cluster-api#1063]
/kind bug

Steps to reproduce:

Create a bootstrap cluster:

```
$ ./bin/clusterctl alpha phases create-bootstrap-cluster --bootstrap-type kind
Error: unknown flag: --bootstrap-type
Usage:
  clusterctl alpha phases create-bootstrap-cluster [flags]
```

**Environment:**

- Cluster-api version: master
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by timothysc** [comment]
This is still open, but it looks like the PR has been merged.
