### ISSUE TITLE
Support for Specifying Non-Default Networks in CAPD

### ISSUE THREAD

**Issue by kahirokunn** [kubernetes-sigs/cluster-api#10669]
### What would you like to be added (User Story)?

As a user of Cluster API Provider Docker (CAPD), I would like to have the ability to specify networks other than the default "kind" network. This feature will allow me to use networks such as k3d or any other custom networks, providing greater flexibility and compatibility with various setups.

### Detailed Description

Currently, CAPD defaults to using the "kind" network as specified in the [kind_manager.go](https://github.com/capi-samples/cluster-api-provider-docker/blob/4e910c1e9e10642fc06590014e43e70f457e63df/pkg/docker/kind_manager.go#L184). This limitation restricts users to a single network configuration. To enhance CAPD's versatility, I propose adding a feature that allows users to specify the network name during the cluster creation process. This could be achieved by introducing an additional configuration parameter or an environment variable that sets the desired network.

### Anything else you would like to add?

Implementing this feature would significantly improve CAPD's usability in diverse environments and use cases. It would also align CAPD with the needs of users who leverage different networking solutions, such as k3d.

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by killianmuldoon** [comment]
Thanks for opening this - there's a PR to add this feature that was closed recently - https://github.com/kubernetes-sigs/cluster-api/pull/10078 which has some useful discussion

**Comment by kahirokunn** [comment]
understand. thx.
