### ISSUE TITLE
Allow variables overrides for control plane

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#10665]
### What would you like to be added (User Story)?

As a user, I would like to set overrides for variables that apply to the control plane only

### Detailed Description

Cluster topology allows defining a sort of hierarchical set of variables, where there are global variables and overrides for specific objects, like MP and MD.

We should introduce a similar concept for CP too, thus allowing use cases like e.g. I set the size of my machines with a global variable, but I override it for the CP to use different machines
 

### Label(s) to be applied

/kind feature
/area clusterclass
/priority important-longterm
/triage accepted
/help

**Comment by sbueringer** [comment]
Makes sense!

/assign
