### ISSUE TITLE
Publish a plantuml image owned by CAPI

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#1070]
In https://github.com/kubernetes-sigs/cluster-api/pull/1058, I use the PlantUML CLI to generate sequence diagrams for proposals and docs. It needs the Java runtime and some fonts, so it is run in a container with those dependencies provided. The container is [currently published on docker hub](https://hub.docker.com/r/dpf9/plantuml). Let's publish it using the official k8s channels.

**Comment by timothysc** [comment]
@justinsb we should sync with @dims && k8s-infra on how we manage shared infra containers. 
/cc @spiffxp

**Comment by dlipovetsky** [comment]
I'll PR the Dockerfile to this repo as a first step

**Comment by dims** [comment]
@dlipovetsky @timothysc i've got the ball rolling by notifying kubernetes-dev on the steps we support [1]

[1] https://groups.google.com/d/msg/kubernetes-dev/ZqdjjDIAISY/n5USEpPBCgAJ

**Comment by detiber** [comment]
@dims is use of the image-promoter now allowed?

**Comment by dims** [comment]
@detiber yes, please try it

**Comment by detiber** [comment]
Request for promotion for an initial image for this is here: https://github.com/kubernetes/k8s.io/pull/322
