### ISSUE TITLE
[Doc] Update glossary doc with terminology

### ISSUE THREAD

**Issue by ashish-amarnath** [kubernetes-sigs/cluster-api#1071]
/kind feature

**Describe the solution you'd like**
The glossary doc needs to define terms like:
* pivot
* bootstrap cluster
* target/ workload cluster

 **Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by ashish-amarnath** [comment]
https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/GLOSSARY.md

**Comment by timothysc** [comment]
We should also add node pools to that list: 
A node pool is a group of nodes within a cluster that all have the same configuration.

**Comment by wanghh2000** [comment]
If I am right, I guess the following link described the `target/workload cluster` above.
https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/GLOSSARY.md#workload-cluster
Or is it another concept?
- Thanks.

**Comment by prankul88** [comment]
Hi @ashish-amarnath @timothysc , I am new to this project and would love to contribute.
If you guys say I can take up this issue.
Thanks

**Comment by ashish-amarnath** [comment]
@prankul88 Welcome to the project! Yes, you can absolutely work on this issue :)

**Comment by ashish-amarnath** [comment]
Setting lifecycle status as @prankul88 will be working on it
/lifecycle active

**Comment by ncdc** [comment]
This is done.
/close
