### ISSUE TITLE
E2E Test fails because ConfigMap metadata.annotations is too big

### ISSUE THREAD

**Issue by gfariasalves-ionos** [kubernetes-sigs/cluster-api#10724]
### What steps did you take and what happened?

When running the [E2E Specs](https://github.com/kubernetes-sigs/cluster-api/tree/main/test/e2e), depending on the choice of CNI (in my case Calico v3.28: https://github.com/projectcalico/calico/blob/release-v3.28/manifests/calico.yaml) , the tests fail with the following error (in this case I used the QuickStartSpec):

```
The ConfigMap "cni-quick-start-b11txq-crs-0" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

The problem won't happen if you use the argument `--server-side` for `kube apply`. `sigs.k8s.io/cluster-api/test/framework/clusterctl.ApplyClusterTemplateAndWaitInput{}` has a field to add these args, but the Spec inputs do not, and therefore they're also not applied.

As I reuse the Specs for my provider, I'd like to be able to choose arguments for `kube apply`  in the Spec input and/or at least expect that ClusterResourceSets somehow can be applied server-side avoiding the error above.

### What did you expect to happen?

ConfigMap is created and test proceeds

### Cluster API version

v1.7.2

### Kubernetes version

v1.29.2

### Anything else you would like to add?

I'd like to implement the fix or solution, if possible.

### Label(s) to be applied

/kind bug
/area e2e-testing

**Comment by fabriziopandini** [comment]
I think that https://github.com/kubernetes-sigs/cluster-api/issues/9696 is going to fix this without using SSA
