### ISSUE TITLE
Bump cert-manager to v1.15.0

### ISSUE THREAD

**Issue by troy0820** [kubernetes-sigs/cluster-api#10726]
A new [cert-manager release v1.15.0](https://github.com/cert-manager/cert-manager/releases/tag/v1.15.0) has been published, and CAPI tries to stay up-to-date with cert-manager.

Prior bump PR: https://github.com/kubernetes-sigs/cluster-api/pull/10514

/kind feature

/assign @troy0820

**Comment by sbueringer** [comment]
Thx for keeping an eye on taht!

/triage accepted
