### ISSUE TITLE
clusterctl: Support autocompletion for the fish shell

### ISSUE THREAD

**Issue by guettli** [kubernetes-sigs/cluster-api#10723]
### What would you like to be added (User Story)?

As an operator, if would like to have shell autocompletion for `clusterctl` because this is convenient.

### Detailed Description

In bash (configured via [docs about completion](https://cluster-api.sigs.k8s.io/clusterctl/commands/completion.html)) `clusterctl get kubeTABTAB` will autocomplete to `clusterctl get kubeconfig`.

It would be nice to have this for the `fish` shell, too.

According to the source `fish` is already suported. But I guess it is not provided via homebrew.

Here my fish completions:

```
❯ find .linuxbrew/share/fish/
.linuxbrew/share/fish/
.linuxbrew/share/fish/vendor_completions.d
.linuxbrew/share/fish/vendor_completions.d/atuin.fish
.linuxbrew/share/fish/vendor_completions.d/delta.fish
.linuxbrew/share/fish/vendor_completions.d/hcloud.fish
.linuxbrew/share/fish/vendor_completions.d/k9s.fish
.linuxbrew/share/fish/vendor_completions.d/golangci-lint.fish
.linuxbrew/share/fish/vendor_completions.d/kubectl.fish
.linuxbrew/share/fish/vendor_completions.d/chezmoi.fish
.linuxbrew/share/fish/vendor_completions.d/oras.fish
.linuxbrew/share/fish/vendor_completions.d/rg.fish
.linuxbrew/share/fish/vendor_completions.d/gh.fish
.linuxbrew/share/fish/vendor_completions.d/yq.fish
.linuxbrew/share/fish/vendor_completions.d/starship.fish
.linuxbrew/share/fish/vendor_completions.d/helm.fish
.linuxbrew/share/fish/vendor_completions.d/tilt.fish
.linuxbrew/share/fish/vendor_completions.d/fd.fish
.linuxbrew/share/fish/vendor_completions.d/stern.fish
.linuxbrew/share/fish/vendor_completions.d/kind.fish
.linuxbrew/share/fish/vendor_completions.d/brew.fish
.linuxbrew/share/fish/vendor_conf.d
.linuxbrew/share/fish/vendor_conf.d/direnv.fish
```

### Anything else you would like to add?

I can have a look at this, too, and create a PR. Just tell me.

### Label(s) to be applied

/kind feature

/area clusterctl

**Comment by chrischdi** [comment]
> I can have a look at this, too, and create a PR. Just tell me.

@guettli : feel free to assign to yourself and go ahead.

**Comment by kranurag7** [comment]
this was done here via this patch https://github.com/kubernetes-sigs/cluster-api/pull/9950 I am using clusterctl 1.7.2 version and the completion is there. (missing in 1.6 series as it was not cherry-picked)

You can use fish completion using `clusterctl completion fish | source` 

To have completion for every shell environment, you'll have to save it on your `~/.config/fish/config.fish` you can use the following: 
```fish
if command -v clusterctl &> /dev/null
    clusterctl completion fish | source
end
```

**Comment by kranurag7** [comment]
I created a patch in homebrew repo to have completion enabled by default for fish shell as well when you use `brew install clusterctl` 

ref: https://github.com/Homebrew/homebrew-core/pull/174030

**Comment by guettli** [comment]
@kranurag7 thank you very much. After install `clusterctl` via brew again, it worked out of the box. No need to configure autocomplete manually.

```
❯ find /home/linuxbrew/.linuxbrew/share/fish/| grep clusterctl
/home/linuxbrew/.linuxbrew/share/fish/vendor_completions.d/clusterctl.fish
```

issue is solved.

**Comment by sbueringer** [comment]
Nice! Thx @kranurag7
