### ISSUE TITLE
Come up with globally valid API groups

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#1073]
/kind bug

https://github.com/kubernetes-sigs/cluster-api/blob/814130408c655984e6b2b10d698243aa226fb43f/pkg/apis/cluster/v1alpha1/cluster_types.go#L26

The API group `.k8s.io` should not be used by anything other than core Kubernetes.

**Comment by ncdc** [comment]
Do we want separate issues for the other places we'll need to change (all label keys, all finalizers, the API group itself)? Or lump them all here?

**Comment by dlipovetsky** [comment]
@ncdc We can lump them all here. I'll update the issue. Can we enumerate the "bad" groups?

`cluster.k8s.io`
`machines.k8s.io`

**Comment by ncdc** [comment]
Anything `.k8s.io` used as an API group name, label key, finalizer key. That's a good start. We can add more if we find them in the code.

**Comment by dlipovetsky** [comment]
Got it.

Might providers be using these, too? I realize they'll define their own groups, but if they're using `.k8s.io` groups anywhere (like labels), we should let them know.

**Comment by ncdc** [comment]
It's certainly possible. We could check all the CAP* repos in kubernetes-sigs.

**Comment by detiber** [comment]
sigs.k8s.io is the official alias for kubernetes-sigs projects, so should likely use subdomains of that.
`cluster.cluster-api.sigs.k8s.io` for example.

Providers could use similar naming as well (assuming they are hosted under kubernetes-sigs):
`<something>.cluster-api-provider-aws.sigs.k8s.io`

**Comment by vincepri** [comment]
/assign

Would this break v1alpha1 compatibility if we switch?

**Comment by vincepri** [comment]
I can switch in #1035, if we find consensus

**Comment by detiber** [comment]
It will break v1alpha1 compatibility, we should only change for v1alpha2+

**Comment by ncdc** [comment]
The only way to preserve v1alpha1 compatibility is to not change it, which means keeping v1alpha1 at the old group name, and changing the name for v1alpha2. At that point, we wouldn't have CRD multi-versioning because it'd be 2 different API groups.

**Comment by vincepri** [comment]
I don't think we can, given that multi-version support requires the same APIGroup :/

**Comment by ncdc** [comment]
We'd create 2 different API groups

**Comment by detiber** [comment]
We're going to need an external migration anyway since we are breaking out the embedded types and introducing the bootstrapping types.

**Comment by vincepri** [comment]
Doesn't that mean no webhook conversion though?

**Comment by vincepri** [comment]
In that case, I'd prefer to keep them under the new type and let the external migration tool handle the change, wdyt?

**Comment by ncdc** [comment]
I'm not sure conversion webhooks were really on the table given how much of a change this is, and the split from RawExtension to full CRDs will require custom logic per provider.

**Comment by ncdc** [comment]
> keep them under the new type

What do you mean?

**Comment by vincepri** [comment]
I mean just use the new APIGroup for v1alpha1 and v1alpha2 and let the external tool to change the APIGroup as well

**Comment by ncdc** [comment]
We have to keep v1alpha1 using the old api group

**Comment by detiber** [comment]
Yes, we can't change the api group otherwise we lose the connection to the underlying object storage in etcd

**Comment by timothysc** [comment]
the blessed namespace is `x-k8s.io`  
Documentation has been updated and guidelines are also coming from sig-arch 
https://github.com/kubernetes/community/blob/master/sig-architecture/api-review-process.md
