### ISSUE TITLE
Umbrella issue: Make end-user experience transparent (Taints & Labels)

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#1074]
An end user can use CAPI types to configure clusters and machines. It is up to each CAPI infra or bootstrap provider to respect, ignore, or override this configuration. The providers may have good reasons for doing so, but the end user has no clue what configuration a provider respects, and what it ignores, or overrides.

For example, an end user can set `Machine.Spec.Taints[]`. Some CAPI providers respect this field, others do not. The end user may not know whether the taints are applied until after the machine is created and the node joins the cluster.

TODOs
- [ ] Remove Taints and Labels from Machine spec. This configuration will be handled by bootstrap controllers.

**Comment by dlipovetsky** [comment]
There was a comment during the code walkthrough that it is confusing that the v1alpha1 `Machine.Spec` includes `Taints`, but does not include `Labels`. In this case, and others, the split between the v1alpha1 CAPI types and the Provider types is not clear.

**Comment by ncdc** [comment]
I'd like to remove `Machine.Spec.Taints` and make it the responsibility of the bootstrap provider you choose to support setting initial taints for a node. And the bootstrap provider should do the same thing for `Labels`.

**Comment by detiber** [comment]
I think prior to the concept of having common bootstrapping it made more sense to make these fields on the Machine. With v1alpha2 introducing common bootstrapping logic, I think the value of having these fields attached to the Machine go away.

**Comment by dlipovetsky** [comment]
Agreed, the `Machine.Spec.Taints` field can be removed.

In general, in v1alpha2, most of the power (to be opinionated) and responsibility (to provide a transparent experience) goes to the infra/bootstrap providers.

CAPI should use the "default" providers to set an example of transparent user experience.

**Comment by ncdc** [comment]
I believe we have completed the work here. Reopen if needed.
/close
