### ISSUE TITLE
NodeDeletionTimeout should align behaviour with NodeVolumeDetachTimeout and NodeDrainTimeout for 0

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#10783]
### What steps did you take and what happened?

NodeDeletionTimeout should align behaviour with NodeVolumeDetachTimeout and NodeDrainTimeout for 0.
We are giving different meaning to the same input https://github.com/kubernetes-sigs/cluster-api/blob/main/api/v1beta1/machine_types.go#L118-L134

### What did you expect to happen?

As an API consumer I'd expect all timeout fields to behave similarly for input 0

### Cluster API version

latest

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
Sorry, not sure what I'm missing. Aren't we - for all 3 timeouts - retrying indefinitely?

**Comment by enxebre** [comment]
you're right, I got confused while reading the docs :)
