### ISSUE TITLE
machine-controller problem self-detection

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes-sigs/cluster-api#1078]
/kind feature

**Describe the solution you'd like**
In v1alpha1, as well as v1alpha2, the machine-controller can get 'stuck' in a variety of states.  For instance, the state of a machine might never progress past "creating" (or as in v1alpha1, each reconcile loop always results in calling the Create() function of the actuator interface) state.  The reasons for this can vary, but we don't currently have any way to track things that are 'stuck'.

We should implement functionality in the various controllers that can smartly detect when a state has not progressed after a certain configurable interval of time (or other specific condition) has passed.  We should implement a method of notifying users of this condition.

Since kubernetes does not have any built-in alarming functionality, one way we could notify users is with labels.  We could add specific labels to machine-objects (or other cluster-api objects) as a primary indication of a problem.  The reason we might use labels instead of a status field or annotation is because they are easy to filter for the end-user (someone can write a script to filter for just problematic objects, or collect metrics and set an alarm for # of objects with the label).  Unfortunately, CRDs do not support filtering as deeply as native kubernetes objects: https://github.com/kubernetes/kubernetes/issues/53459

**Anything else you would like to add:**
This logic probably best belongs inside the machine-controller (or other respective controller) because that controller knows the most about any given machine-object at any given time.  We already have a reconcile loop that periodically updates machines, so there's not a great reason to re-invent this inspection elsewhere.  On especially busy clusters that frequently scale up and down machines, users need a quick way to determine if there are any problems and where those problems are.

**Comment by ncdc** [comment]
Ditto. I'd like to try to enumerate specific places in the overall workflow that can get stuck. Once we have an initial list, we can try to decide how to surface this information.

**Comment by michaelgugino** [comment]
> Overall, I'm a big +1 on adding this type of functionality. I do believe that using labels as the primary mechanism for this seems like a bit of an anti-pattern. I'm not against using it as a secondary mechanism for filtering, but the primary mechanism should likely be some type of a field, maybe similar to Conditions.

@detiber Labels are used primarily for grouping things.  In this case 'broken machines' would be a group.  We are, IMO, primarily concerned with raising this data to the user/admin or another 3rd party component.  While we could set this data as a field somewhere, we'd then require *something else* to make the labels or otherwise have to query for all objects and filter.

I would prefer labels, but in any case, we should collect and record these states.

**Comment by sethp-nr** [comment]
For cross-referencing purposes: this would greatly ease the implementation of #969 (being able to tell the "resizing" case apart from the "error" case, anyway).

**Comment by ncdc** [comment]
This sounds like an older version of the machine healthcheck proposal #1684 
/close

reopen if I'm off base
