### ISSUE TITLE
Namespace defaulting missing for MachineHealtcheck's RemediationTemplate reference in ClusterClass

### ISSUE THREAD

**Issue by chess-knight** [kubernetes-sigs/cluster-api#10805]
### What steps did you take and what happened?

This is similar to #4943 but for MHC in ClusterClass. E.g. see Hetzner provider ClusterClass https://github.com/syself/cluster-api-provider-hetzner/blob/main/templates/cluster-templates/cluster-class.yaml#L70-L74. When I omit namespace for the remediationTemplate, validation webhook complains about it. AFAIK there is a defaulting in the MHC webhook, but it is not a case in the clusterclass webhook.

### What did you expect to happen?

I want to create a ClusterClass with remediationTemplate without specifying a namespace.

### Cluster API version

v1.7.3

### Label(s) to be applied

/kind bug
/area api
/area clusterclass

**Comment by sbueringer** [comment]
Makes sense.

We are missing defaulting for ClusterClass & Cluster.spec.topology.

Feel free to open a PR

/triage accepted

/area machinehealthcheck
/area clusterclass
