### ISSUE TITLE
Improve ClusterCacheTracker TryLock behavior

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#10819]
ClusterCacheTracker today allows only one controller worker at a time to retrieve a client. If a second controller worker tries it at the same time, it will get an `ErrClusterLocked` error. This usually leads to a log like this `"Requeuing because another worker has the lock on the ClusterCacheTracker"` (log level 5) and a requeue.

This was introduced for the case where a workload cluster is not reachable. In that case, when we try to create a client with the CCT the client creation times out after 10 seconds. In this scenario we wanted to block at most one worker and not deadlock entire controllers.

I think the current behavior is not ideal in so far that TryLock just immediately fails/returns. Ideally we would try get the lock for a small period of time so we end up with the following results:

Happy path (cluster is reachable, we can create a client):
* 1st controller creates the client
* all other controllers retry TryLock for a few ms and eventually everyone gets a client without an entire requeue (the requeue is done today via RequeueAfter 1m)

Un-happy path (cluster is not reachable, client creation times out after 10s):
* 1st controller tries to create a client and times out after 10s
* all other controllers retry TryLock for a few ms, but eventually give up (ideally in this scenario over time the duration of our retry goes down so that the average reconcile duration of our controller doesn't degrade too much)

Or maybe we should re-think the whole mechanism and come up with something different :)

**Comment by fabriziopandini** [comment]
/assign

added to my pipeline, please reach out if someone wants to give a try before I get to it.

**Comment by sbueringer** [comment]
Absolutely in favor!

**Comment by sbueringer** [comment]
/close

in favor of https://github.com/kubernetes-sigs/cluster-api/issues/11272
