### ISSUE TITLE
Make Cluster UID available within Cluster Builtins

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api#10823]
### What would you like to be added (User Story)?

As a runtime extension developer, I'd like to be able to set the Cluster object as the owner reference for any external resources.  

### Detailed Description

As part of the patch generation within runtime extensions, we want to create certain external resources, say `Secret` objects. To ensure that these resources get garbage collected during Cluster deletion, we want to set the Cluster as the owner of these resources. Since UID is a mandatory field when setting an owner reference, it'd be great if we could have the Cluster object's UID present in the Cluster builtins available during patch gen.

### Label(s) to be applied

/kind feature

**Comment by sbueringer** [comment]
Sounds good!

/triage accepted
/area clusterclass
