### ISSUE TITLE
Cluster API Operator - Manage lifecycle across providers 

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api#1085]
**Basic User Story**
As a Cluster API user I would like to be able to apply a single manifest for a given version (e.g. v1alpha2) and have it deploy and manage the lifecycle of the supported providers that are specified.  

**Example use case:**
New user comes to the cluster api repo wanting to kick the tires and give it a whirl. 
User goes to the getting started guide. 
Preconditions (some initial cluster...) 
Step 1: Determine which providers they wish to support 
Step 2: Modify some yaml.template 
Step 3: Apply FilledInOperatorTemplate.yaml 
... 
Operator is deployed
Controllers are installed 
User is now able to just use kubectl apply for a specific provider

**NOTES**
Obviously, this requires more details and a proposal, but this should be the start of a conversion.  

xref: https://github.com/kubernetes-sigs/cluster-api/issues/1065 
/kind feature

**Comment by rudoi** [comment]
+1 for this. 

Assuming this Operator would complete pivoting, it would provide a great way to keep a catalog of created clusters, even when those clusters have pivoted and are managing themselves. I believe there's a small gap today where I have no way to keep track of clusters that have pivoted without keeping all their kubeconfigs somewhere or something of that sort.

**Comment by fabriziopandini** [comment]
@timothysc @ncdc 
The way forward for clusterctl currently under discussion does not include an operator, so IMO we can close this issue and eventually reiterate/re-open if necessary
