### ISSUE TITLE
Diagnostics endpoint/address ignores TLS options

### ISSUE THREAD

**Issue by awprice** [kubernetes-sigs/cluster-api#10882]
### What steps did you take and what happened?

We configured the TLS options (`--tls-cipher-suites` and `--tls-min-version`) on the cluster-api manager and found that the diagnostics endpoint/address does not use this TLS options and there is no way to change what TLS options it uses.

### What did you expect to happen?

For the provided TLS options to apply to both the webhook server and diagnostics server.

### Cluster API version

v1.6.1

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by chrischdi** [comment]
Thanks for reporting!

/triage accepted
