### ISSUE TITLE
Change type of Machine.Roles

### ISSUE THREAD

**Issue by karan** [kubernetes-sigs/cluster-api#109]
Since a machine can only be either a Master or a Node, we should change it from a list of strings to an enum.

**Comment by roberthbailey** [comment]
Machine role isn't expected to be a single value. Look at the table in the [documentation for the type](https://github.com/kubernetes-sigs/cluster-api/blob/011bb82049bfe9278ef91744b8e89c6355ed750f/pkg/apis/cluster/common/consts.go#L88-L112) to see the intent of setting both master and node on a machine.
