### ISSUE TITLE
TestServerSideApplyWithDefaulting/no-op_if_neither_is_defaulted is flaky

### ISSUE THREAD

**Issue by Sunnatillo** [kubernetes-sigs/cluster-api#10902]
### Which jobs are failing?

periodic-cluster-api-test-mink8s-main
periodic-cluster-api-test-release-1-6
periodic-cluster-api-test-main
periodic-cluster-api-test-mink8s-release-1-6
periodic-cluster-api-test-mink8s-release-1-7	

### Which tests are failing?

TestServerSideApplyWithDefaulting/no-op_if_neither_is_defaulted is flaky

### Since when has it been failing?

07/09

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-mink8s-main/1813627869608284160

### Label(s) to be applied

/kind flake
/area ci

/assign @Sunnatillo

**Comment by sbueringer** [comment]
I think it's "just" flaky and not failing 100% of the time, correct?

**Comment by Sunnatillo** [comment]
yes, I made the issue from wrong template

**Comment by fabriziopandini** [comment]
This is tricky to reproduce locally, but I have a theory about why ti might fail in CI and created https://github.com/kubernetes-sigs/cluster-api/pull/10905 to see if it solves the issue.

Note: the PR above also improve error message in case the same error happens again

**Comment by Sunnatillo** [comment]
Thank you @fabriziopandini taking care of it. Indeed it was tricky to reproduce it locally.
