### ISSUE TITLE
Update provider implementation guide to Kubebuilder 2.0

### ISSUE THREAD

**Issue by pablochacin** [kubernetes-sigs/cluster-api#1090]
/kind bug

**What steps did you take and what happened:**

Following the instructions in the provider implementation documentation when building the project, the following errors/inconsistencies occurs:

***Makefile patch***

Instructions for building the project include a patch for the `Makefile` which includes this   change:
```
 manifests:
 	go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go all
+	sed -i'' -e 's@^- manager_auth_proxy_patch.yaml.*@#&@' config/default/kustomization.yaml
+	kustomize build config/default/ > provider-components.yaml
+	echo "---" >> provider-components.yaml
+	kustomize build vendor/sigs.k8s.io/cluster-api/config/default/ >> provider-components.yaml
```

However, the actual Makefile looks as follows:
```
manifests: controller-gen
        $(CONTROLLER_GEN) $(CRD_OPTIONS) rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
```  

***API package locatiion***
Building the project fails due to a missing reference to `apis` package:
```
make 
/home/pchacin/workspace/go/bin/controller-gen object:headerFile=./hack/boilerplate.go.txt paths=./api/...
go fmt ./...
build sigs.k8s.io/cluster-api-provider-solas/cmd/manager: cannot load sigs.k8s.io/cluster-api-provider-solas/pkg/apis: cannot find module providing package sigs.k8s.io/cluster-api-provider-solas/pkg/apis
make: *** [Makefile:46: fmt] Error 1
```

The problem is because the api is created under `sigs.k8s.io/cluster-api-provider-solas/api/v1alpha1`

This issue is related to #1075 

**Note**

**Environment:**

 Cluster-api version: 0.1.4
- Minikube/KIND version: n/a
- Kubernetes version: (use `kubectl version`): 1.4.1
- OS (e.g. from `/etc/os-release`): openSUSE Leap 15.0

**Comment by randomvariable** [comment]
Related to providing an implementer guide as well https://github.com/kubernetes-sigs/cluster-api/issues/778

/assign

**Comment by randomvariable** [comment]
CC @thebsdbox
