### ISSUE TITLE
Add way to set the value of the time for requeue

### ISSUE THREAD

**Issue by sivchari** [kubernetes-sigs/cluster-api#10916]
Currently, the time for requeue is hard-coded for each controllers. So developer can't control it. Ideally, I think that these variables should be mutable for each users.
Since I know that there are several places that is hard-coded, we should manage the some flags if we consider this issue. So I want to discuss the better way to handle the value for requeue.

**Comment by sbueringer** [comment]
Why should we allow our users to configure our requeue intervals?

**Comment by sivchari** [comment]
I thought that if the interval can be configured, we can adjust the time for next reconciliation. For instance, in our team, it takes little bit of times to pass preflight check for control plane. So I want to make the RequeueAfter longer than 15 seconds, but I can't do it because the time is fixed.
Although I thought as above, this case might not be general case. In additional, I'm starting to think that this configuration might not be good changes for Cluster API.
I'm sorry to take your time.

**Comment by sbueringer** [comment]
No worries. I think in general how often we requeue should be an implementation detail.

If there are cases where CAPI doesn't react to something we should take a closer look and check if this can be solved by having a watch.

In a lot of cases we are watching all relevant related objects, so that if any of them changes we rerun our reconcile logic

**Comment by sbueringer** [comment]
Overall my goal would be that CAPI "just work" out-of-the-box and it's not necessary for folks to fine-tune requeue durations

**Comment by sivchari** [comment]
> Overall my goal would be that CAPI "just works" out-of-the-box and it's not necessary for folks to fine-tune requeue durations

Thank you for commenting. I change my thought and agree with your comment.
First of all, I'd track the logs and resources that CAPI manages.

/close
