### ISSUE TITLE
Deprecate pkg/errors

### ISSUE THREAD

**Issue by sivchari** [kubernetes-sigs/cluster-api#10920]
Cluster API uses [pkg/errors](https://github.com/pkg/errors), but this package has beed deprecated and archived since 2021.
So let's migrate from it to something to maintain easily for the future.
There are many libraries to deal with the error and each library has the pros/cons. Thus I want to discuss which library is prefer for Cluster API.

**Comment by stmcginnis** [comment]
/triage duplicate

This is already being tracked in #6688

**Comment by sbueringer** [comment]
^^
/close 

We can continue the conversion in #6688
