### ISSUE TITLE
Replace kubebuilder-release-tools action

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#10925]
Sooner or later the kubebuilder-release-tools actions will have to either migrate to the community-registry or be deprecated (https://github.com/kubernetes-sigs/kubebuilder-release-tools/issues/60#issuecomment-2236068489).

While thinking about this, I was wondering if we actually need the kubebuilder-release-tools action in Cluster API.
Especially considering how much effort it took the last time to get a change implemented in kubebuilder-release-tools and the action correctly published and bumped.

I took a closer look and it looks like we use it only to verify PR titles in the following way:
* to check for icons (while ignoring e.g. WIP): https://github.com/kubernetes-sigs/kubebuilder-release-tools/blob/master/verify/type.go
* to check if there is an issue referenced in the PR title: https://github.com/kubernetes-sigs/kubebuilder-release-tools/blob/master/verify/issue.go

I think we can replace the usage of kubebuilder-release-tools with a small GitHub action that just runs some local code (e.g. bash) to achieve the same goal.

Once implemented, let's make sure we surface this alternative implementation at the kubebuilder-release-tools issue (https://github.com/kubernetes-sigs/kubebuilder-release-tools/issues/60)

**Comment by sivchari** [comment]
I work on it.
/assign

**Comment by sbueringer** [comment]
One quick comment. Would be nice if it's just one self-contained action YAML. So it's easy to copy / sync to other projects
