### ISSUE TITLE
Cleanup the hard coded String

### ISSUE THREAD

**Issue by sivchari** [kubernetes-sigs/cluster-api#10929]
Currently, some codes are hard coded as String.
For instance, The Kind of Cluster is like following.

```go
GroupVersion: clusterv1.GroupVersion.String(),
Kind: "Cluster"
Name: cluster.Name,
UID: cluster.UID,
```

I think it's better to use cluster.Kind than to write it hard coded.
There are many codes like above, so let's clean up these to make maintenance more easier.

In additional, Cluster has the const that's called ClusterKind, but other resource doesn't have it.
Which prefer do we need to define new constant and to use these constants for representing Kind or to deprecate ClusterKind const and not to use it.

**Comment by sbueringer** [comment]
To be honest, I'm not sure if this is worth the huge amount of churn and review effort.

Please note that in some cases we cannot use cluster.Kind because Kind is not set by controller-runtime (so this would have a huge potential to introduce bugs)

**Comment by sivchari** [comment]
> we only have very limited review bandwith at the moment

> It's not clear to me how this reduces maintenance effort. We are never changing the existing hard-coded strings, there is no maintenance effort around keep them as they are

Thank you for commenting.
Surely, it's not worth and just increase review efforts.
Sorry, I close this issue.

/close

**Comment by sbueringer** [comment]
No worries! Feel free to bring up ideas like this :)
