### ISSUE TITLE
Test framework: clusterProxy.CreateOrUpdate does not accept namespace argument

### ISSUE THREAD

**Issue by Sunnatillo** [kubernetes-sigs/cluster-api#10928]
### What steps did you take and what happened?

In recent v1.8.0-beta.0 release `clusterProxy.CreateOrUpdate`  replaced `clusterProxy.Apply`.  `CreateOrUpdate` only accepts label selector as a parameter. 
In Metal3 provider we use namespace when moving crds from one namespace to another in clusterctl upgrade tests using clusterProxy.Apply. 

### Cluster API version

v1.8.0-beta.0

### Anything else you would like to add?

I want to add namespace as a parameter to clusterProxy.CreateOrUpdate if maintainer as fine with the change. 

### Label(s) to be applied

/kind bug
/area e2e-testing

**Comment by Sunnatillo** [comment]
> Isn't it enough to have the namespace set on the objects you pass in?
> 
> The code reads it from the resources which gets passed in.

This is baremetal host related crds and they are not managed by CAPI/CAPM3 stack. We apply them from yaml file. And use same yaml files when for example pivoting.

**Comment by chrischdi** [comment]
It should be easy to add a `WithNamespace` option, or at the other hand, on your side use something like:

```go
objs, err := yaml.ToUnstructured(resources)
if err != nil {
	return err
}
for i, obj := range objs {
  obj.Namespace = "my-namespace"
  objs[i] = obj // not sure if we even need this
}
resources, err := yaml.FromUnstructured(objs)
if err != nil {
	return err
}
```

I'm also okay with adding the option, but the above may be good enough if there's only this single usage where a namespace overwrite is needed.

**Comment by sbueringer** [comment]
The main reason we changed this is because we wanted to stop supporting os exec to `kubectl apply`. In general we should find a balance between supporting the main use cases and too many edge cases.

Today the ClusterProxy also has the following methods that allow you to do whatever you want :)

GetClient() client.Client
GetClientSet() *kubernetes.Clientset
GetRESTConfig() *rest.Config

So I'm really hesitant to reimplement a client within the CreateOrUpdate func when we already provide so much alternatives

**Comment by sbueringer** [comment]
Please note that controller-runtime also provides util funcs like controllerutil.CreateOrUpdate / CreateOrPatch

**Comment by fabriziopandini** [comment]
If we find a small change/easy to maintain to make it possible, I'm ok
Otherwise, the intent of CreateOrUpdate is not to be a full replacement of kubectl apply

**Comment by fabriziopandini** [comment]
Discussed with @sbueringer and @chrischdi 
The snippet in https://github.com/kubernetes-sigs/cluster-api/issues/10928#issuecomment-2245636890 can easily solve the issue, without us getting into the business to mimic kubectl apply
/close
