### ISSUE TITLE
Release notes should not include the detail about release PR

### ISSUE THREAD

**Issue by chandankumar4** [kubernetes-sigs/cluster-api#10931]
### What steps did you take and what happened?

While generating the release notes, it should filter out the Release notes PR from it.

For example: [This](https://github.com/kubernetes-sigs/cluster-api/pull/10864/files#diff-ef6ca3983888d8572716a9b0184cf6f11d2d2a1c448fb7c74236a9b93c75a507R180) PR should not be a part of release notes.

### What did you expect to happen?

It should filter out the release notes PR

### Cluster API version

v1.8.0-beta.0

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by rajankumary2k** [comment]
Can I work on this Issue?

**Comment by chandankumar4** [comment]
sure, Thanks 
/assign @rajankumary2k

**Comment by chandankumar4** [comment]
Feel free to ping me on slack or here if you need any more detail.

**Comment by rajankumary2k** [comment]
Sure, Thanks!

**Comment by fabriziopandini** [comment]
Orthogonal consideration: Let's make sure to keep improving also documentation and test coverage for the release tool because those are super valuable for the next release team that will take a look at it

**Comment by chandankumar4** [comment]
This issue got resolved itself, after updating the PR title from ":seedling:" to ":rocket:" for these three PRs [10440](https://github.com/kubernetes-sigs/cluster-api/pull/10440) [10438](https://github.com/kubernetes-sigs/cluster-api/pull/10438) [10439](https://github.com/kubernetes-sigs/cluster-api/pull/10439)

**Comment by chandankumar4** [comment]
> Orthogonal consideration: Let's make sure to keep improving also documentation and test coverage for the release tool because those are super valuable for the next release team that will take a look at it

@fabriziopandini I Have opened up another issue for improving the test coverage.

**Comment by sbueringer** [comment]
@chandankumar4 so everything should work as expected now, correct?

**Comment by sbueringer** [comment]
Thx!

/close
