### ISSUE TITLE
kube-apiserver does not gracefully terminate when a control plane machine is scaled down

### ISSUE THREAD

**Issue by kdw174** [kubernetes-sigs/cluster-api#10934]
### What steps did you take and what happened?

When a control plane machine is scaled down, the ectd leader is moved if it is on the control plane machine, and the etcd member is [removed from the cluster](https://github.com/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/internal/controllers/scale.go#L119). This happens before the [machine object is deleted](https://github.com/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/internal/controllers/scale.go#L136) and handled by the infrastructure provider.

When the etcd member is removed, the kube-apiserver pod on that control plane node can no longer serve requests since it can't access etcd. 
```
{
  "level": "warn",
  "ts": "2024-07-24T17:17:12.462Z",
  "logger": "etcd-client",
  "caller": "v3/retry_interceptor.go:62",
  "msg": "retrying of unary invoker failed",
  "target": "etcd-endpoints://0xc000c44700/127.0.0.1:2379",
  "attempt": 0,
  "error": "rpc error: code = Unavailable desc = error reading from server: read tcp 127.0.0.1:32866->127.0.0.1:2379: read: connection reset by peer"
}
```
etcd stops when it is removed from the cluster and the pod ends up in a crashloopbackoff. 

Since the apiserver wont get a sigterm until after etcd has been removed from the cluster, it makes the `--shutdown-delay-duration` apiserver flag useless for existing connections. They will fail and have to be retried. There will be a brief period of time until the infrastructure provider removes the apiserver from the loadbalancer or healthchecks fail where requests will be routed to the apiserver that can't fulfill requests.

I've seen this mentioned in several past issues, but they have all been closed without resolution. https://github.com/kubernetes-sigs/cluster-api/issues/2652 best describes the issue that still exists today. 

It seems this is just accepted today and is handled with lb healthchecks and removing the instance from load balancer backends as fast as possible. Am I missing something with the configuration to make this scale down in a more graceful manner? 

### What did you expect to happen?

I would expect there to be no period of time where existing connections to a kube-apiserver fail during a standard KCP upgrade. It would also be nice to not have etcd in a crashloopbackoff for alerting purposes.

### Cluster API version

1.4.3 though I would expect this to happen on latest

### Kubernetes version

1.25

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by fabriziopandini** [comment]
I think the cleanest way to fix this is to use pre-deletion hooks at take the CP machine out of the control plane load balancer (a CP instance stop receiving requests).

However, I agree that it will be also interesting to look into KCP and see if there are ways to minimize impacts of the deletion workflow, even if the loadbalancer or healthchecks are out of reach from KCP

**Comment by fabriziopandini** [comment]
I just noticed this is about CAPI 1.4.3, which is out of support since some time now. Please consider upgrade.

Most recent release have better handling on the deletion sequence, and KCP keeps the API server and etcd active longer (see https://github.com/kubernetes-sigs/cluster-api/pull/11137)

Another option, depending on the load balancer you are using, is to start draining traffic from a CP machine as soon as deletion start (without waiting for the the deletion process to get to the point where API server becomes unavailable), see e.g. https://github.com/kubernetes-sigs/cluster-api/pull/11430

/close
