### ISSUE TITLE
Add new feature to renew certification

### ISSUE THREAD

**Issue by sivchari** [kubernetes-sigs/cluster-api#10948]
### What would you like to be added (User Story)?

As a operator, I'd like to add new feature to renew certification automatically. 

### Detailed Description

Currently, we should exec `kubeadm certs renew` to  update certification manually to workload cluster. 
Cluster API defines the `machine.cluster.x-k8s.io/certificates-expiry` annotation that we can check expiry. So, at this time, we can use this annotation to alert the expiration and renew certification manually, or each one should make something to renew certification automatically. 
So I think it's good expansion to provide the feature to do above.
I'd discuss this proposal. Thanks.

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
What about https://cluster-api.sigs.k8s.io/tasks/certs/auto-rotate-certificates-in-kcp?

**Comment by sivchari** [comment]
@sbueringer  
I'm sorry. I totally overlooked it you mentioned.
The feature I want is alreay existing.
Thank you for teaching me.
/close
