### ISSUE TITLE
Add constraint type for developer makes provider

### ISSUE THREAD

**Issue by sivchari** [kubernetes-sigs/cluster-api#10944]
### What would you like to be added (User Story)?

As a developer, I'd add the constraint type to understand the required field more easier.

### Detailed Description

Currently, developer that makes any provider doesn't understand until running controllers or suite tests what kind of fields does developer is requested by Cluster API. Of course, it's possible to understand specification by reading [The Cluster API Book](https://cluster-api.sigs.k8s.io/developer/architecture/controllers), but, ideally I think that it sounds so good to understand to read codebases. Then I think it would be easy for developers to debug that the build was failed because some fields or methods are missing.
So I propose to add any constraints. This constraints is just helper type , so backward compatibility is okay.

For instance

```go
type ClusterSpecConstraint interface {
    ControlPlaneEndpoint() APIEndpoint
}

type Ready bool

type ClusterStatusConstraint interface {
    Ready() Ready
}
```

Thanks.

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by fabriziopandini** [comment]
I'm leaning towards -1 to the proposed approach
Implementing an interface just give a signal method exists, while the CAPI contract makes assumption on a field and more specifically on how a field is serialized.

I'm happy to reconsider if we find other ways to help providers to validate their objects.
e.g. Time ago we started encoding contract assumption in the contract package; this might evolve in something that can be used by providers to validate.

As intermediate step, it will be great to improve our contract documentation
/close
