### ISSUE TITLE
Improve validation during upgrade e2e tests

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#10956]
We recently found an issue in KCP upgrades. This only lead to failures in self-hosted tests, but in general KCP was upgrading through the entire control plane and only static pods came up (kube-proxy, CNI did not). Also the Nodes weren't ready during the upgrade.

I think we should improve our e2e test coverage to detect if the control plane is in a state like this during upgrades.

This should be either additional validation while the upgrade is running or potentially we can e.g. deploy a StatefulSet with PDBs that runs on CP nodes. In this case the test would have failed with the issue from https://github.com/kubernetes-sigs/cluster-api/pull/10947

Bonus: Potentially the Statefulset with PDBs we deploy could also use volumes for some bonus test coverage for "wait for volume detach" but it's unclear if we have a CSI implementation for CAPD that would work for that (maybe the provisioner that comes with kind out-of-the-box)

**Comment by chrischdi** [comment]
Should be done via:

- #11145

**Comment by chrischdi** [comment]
cc @sbueringer 

/close

**Comment by sbueringer** [comment]
All good, thx for working on it!
