### ISSUE TITLE
CAPI cluster stuck in failed after infrastructure cluster has failureMessage

### ISSUE THREAD

**Issue by cwrau** [kubernetes-sigs/cluster-api#10991]
### What steps did you take and what happened?

As seen in https://github.com/kubernetes-sigs/cluster-api/blob/4a0900c5e7ec1ddfb7a96562e034120b7694f424/internal/controllers/cluster/cluster_controller_phases.go#L135-L144, when the referenced infrastructure cluster has any error, this gets copied onto the CAPI cluster, then in https://github.com/kubernetes-sigs/cluster-api/blob/4a0900c5e7ec1ddfb7a96562e034120b7694f424/internal/controllers/cluster/cluster_controller_phases.go#L59-L61 this is used to set the phase to `failed`

But I can't find any line that sets the `failureMessage` and `failureReason` to nil again.

### What did you expect to happen?

That the `failureMessage` and `failureReason` get's reset at some point

### Cluster API version

1.6.3, but the same code is in main as well

### Kubernetes version

Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.14

### Anything else you would like to add?

If no one objects, I'd open a PR with the following changes;

```patch
diff --git a/internal/controllers/cluster/cluster_controller_phases.go b/internal/controllers/cluster/cluster_controller_phases.go
index 4afa3976f..df0335218 100644
--- a/internal/controllers/cluster/cluster_controller_phases.go
+++ b/internal/controllers/cluster/cluster_controller_phases.go
@@ -135,12 +135,16 @@ func (r *Reconciler) reconcileExternal(ctx context.Context, cluster *clusterv1.C
 	if failureReason != "" {
 		clusterStatusError := capierrors.ClusterStatusError(failureReason)
 		cluster.Status.FailureReason = &clusterStatusError
+	} else {
+		cluster.Status.FailureReason = nil
 	}
 	if failureMessage != "" {
 		cluster.Status.FailureMessage = ptr.To(
 			fmt.Sprintf("Failure detected from referenced resource %v with name %q: %s",
 				obj.GroupVersionKind(), obj.GetName(), failureMessage),
 		)
+	} else {
+		cluster.Status.FailureMessage = nil
 	}
 
 	return external.ReconcileOutput{Result: obj}, nil
```

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
failureMessage / failureReason are supposed to be used to signal terminal failures. Terminal in a sense of that they cannot be recovered from. That is why there are no code paths to unset them again

**Comment by cwrau** [comment]
> failureMessage / failureReason are supposed to be used to signal terminal failures. Terminal in a sense of that they cannot be recovered from. That is why there are no code paths to unset them again

Ok, so this is an issue with cluster API provider OpenStack (with which this is happening)? They shouldn't set these fields if it's not a terminal failure then?

**Comment by sbueringer** [comment]
Correct!

**Comment by sbueringer** [comment]
(manual workaround is ~ kubectl edit --subresource=status)

**Comment by fabriziopandini** [comment]
Looking forward to get https://github.com/kubernetes-sigs/cluster-api/pull/10997 implemented and get rid of failureMessage / failureReason

/close 
(based on comments above)
