### ISSUE TITLE
create integration test for machine controller.

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#11]
_From @medinatiger on January 8, 2018 19:46_

We need to have integration test to test machine controller. The following scenario is interested.

1. Basic create/update/delete through API
2. Scale up
3. Scale down
4. Stress test with combination of ScaleUp/ScaleDown
5. Upgrade.
6. Mixed upgrade and scale operation simultaneously 

_Copied from original issue: kubernetes/kube-deploy#476_

**Comment by rsdcastro** [comment]
_From @k-turowski on January 17, 2018 15:55_

I can take this.

**Comment by rsdcastro** [comment]
This is currently unassigned.

**Comment by spew** [comment]
Think #4 and #6 are out of scope for alpha. Those require significantly more effort and probably are not as critical as basic functionality at this point.

**Comment by roberthbailey** [comment]
@enxebre - we should have a conformance-style test that each provider can run to verify that they work "correctly". It may be worthwhile to create an actuator stub in this repository so that we can put the test code here (and run it) once all of the provider code has been migrated out.

**Comment by figo** [comment]
looks like no one is working on this, plan to take on this issue and assign to myself, let me know if any objection.

**Comment by vincepri** [comment]
@figo Go for it! You can mark the issue with `/lifecycle active` to mark it as taken.

**Comment by pablochacin** [comment]
@figo I was about to pick it! :running_man: :smile: 
Please let me know if you want some help from me.

**Comment by figo** [comment]
@pablochacin i have a WIP PR to create a simple mock up provider and integration with Prow. i definitely welcome cooperations.

**Comment by pablochacin** [comment]
@figo I kind reminder to share with me the repository fork on which you are working you PR.

**Comment by figo** [comment]
@pablochacin will share with you soon, thank you

**Comment by figo** [comment]
@pablochacin let me know if you want to have some discussion around this, here is the branch: https://github.com/figo/cluster-api/tree/integration

**Comment by pablochacin** [comment]
@figo  I just saw your PR. I'll comment there. Thanks
