### ISSUE TITLE
Scale down specific node is not working

### ISSUE THREAD

**Issue by rajgani** [kubernetes-sigs/cluster-api#11026]
I have a Cluster created with ByoH Provider and have the Worker node pool deployed as a machine deployment.
I are trying to scale down a specific node from the worker node pool, I have tried by annotating `machineset.clusters.k8s.io/delete-me=yes` specific machine (as per the PR below) which has to be deleted, but its still picking the Random node when scaling down the Machine Deployment.

https://github.com/kubernetes-sigs/cluster-api/pull/726

**Comment by sbueringer** [comment]
@rajgani I think this was never implemented with this annotation name. It only shows up in the PR description there.

In general I would also recommend checking our current API vs old PRs for things that were added 5 years ago in our v1alpha1 API.

Anyway, this is how it should work today: (from our v1beta1 API)
```go
	// DeleteMachineAnnotation marks control plane and worker nodes that will be given priority for deletion
	// when KCP or a machineset scales down. This annotation is given top priority on all delete policies.
	DeleteMachineAnnotation = "cluster.x-k8s.io/delete-machine"
```
https://github.com/kubernetes-sigs/cluster-api/blob/e2bf2b7d108ecd51bf7b23bf50e2432e82d8f2fe/api/v1beta1/common_types.go#L116-L118
