### ISSUE TITLE
conditions Utility to let specify the entire condition

### ISSUE THREAD

**Issue by srirammageswaran8** [kubernetes-sigs/cluster-api#11033]
### What would you like to be added (User Story)?

A new conditions utility to upsert conditions with the given LastTransistionTime and state fields.

### Detailed Description

The LastTransistionTime definition Says

```
Last time the condition transitioned from one status to another.
This should be when the underlying condition changed. If that is not known, then using the time when
the API field changed is acceptable.
```

Would be better to have a utility in conditions to let it specify the entire condition and upsert the condition when the condition type already exists. The Utility should add / update the condition with the given state fields which include

- Type
- Status
- Reason
- Severity
- Message

And the LastTransistionTime specified in the new condition to add.

### Anything else you would like to add?

The Utility may be used to track the transition of the state in any cloud provider / any other resources.

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
@srirammageswaran8 Would conditions.Set work for your use case? (https://github.com/kubernetes-sigs/cluster-api/blob/4f1637e59c48528f7a5c1a3116054dbc96216f8c/util/conditions/setter.go#L41)

**Comment by srirammageswaran8** [comment]
@sbueringer , Thanks for the followup. 

The`Set` function does not let update the LastTransistionTime if the condition already exists. If the condition exists and the state changed it updates LastTransistionTime with the current time if the state does not change it updates LastTransistionTime with the existing condition's LastTransistionTime.

**Comment by sbueringer** [comment]
What is your use case for changing LastTransistionTime in a case where it shouldn't be changed?

**Comment by vincepri** [comment]
Chatted with @srirammageswaran8 offline, the main use cases we've chatted about, which might or might not be a fit for conditions, is when a transition is known to be happened at a different time and the condition is observing when the state has changed. 

For example, say "ec2 instance created" the timestamp can be gathered from the APIs

**Comment by srirammageswaran8** [comment]
Thanks @vincepri . Instead of using the observed value of the resource I was trying to get the actual time of the transition of the resource to the conditions.

**Comment by sbueringer** [comment]
Ah now I got it. I think that makes sense based on the godoc

**Comment by sbueringer** [comment]
Would be good to hear @fabriziopandini's opinion

**Comment by sbueringer** [comment]
Maybe we can just change the existing Set function to always "accept" the LastTransitionTime when it is set on the condition that is passed in

**Comment by srirammageswaran8** [comment]
@sbueringer and @fabriziopandini , A gentle follow up.

**Comment by fabriziopandini** [comment]
If I can give my two cents, changing the LastTransitionTime could be surprising for users, and in fact the definition of this field explicitly call out that using then using the time when the API field changed is acceptable. 

In fact, by a quick check, api machinery [condition utils](https://github.com/kubernetes/apimachinery/blob/a8a2284d318b9213fca20b0058e969941ce1c90b/pkg/api/meta/conditions.go#L31-L68) do not allow changing last transition time too (but it seems they do allow changes of reason, message and observed generation 🤔).

Considering that the [new Cluster API condition utils](https://github.com/kubernetes-sigs/cluster-api/pull/10997) I'm working  on are going to relies on upstream condition utils and thus do not allow changing last transition time, frankly speaking I don't think we should make it possible to change lasttransition time in existing CAPI condition utils.

**Comment by sbueringer** [comment]
I think then we should fix our godoc. It seems to clearly state that it's preferred that the lastTransitionTime "should be when the underlying condition changed"

**Comment by fabriziopandini** [comment]
To me the godoc make sense. I read it as:

> When you set a condition (or transition it from one state to another), if you know when the underlying "element" changed use this info. Otherwise, use the time when your controller detects the underlying "element" is changed (time.now)

**Comment by sbueringer** [comment]
I'm reading

> This should be when the underlying condition changed

as the lastTranistionTime should be the time when "whatever is underlying this condition" (e.g. some change in the infrastructure) changes

**Comment by fabriziopandini** [comment]
I took some additional time to compare existing conditions utils and to be/upstream aligned conditions utils

Those are the diffs:
1. existing conditions utils only allow to set lastTranistionTime to an arbitrary value only when a condition does not exists but not when a condition already exists, while be/upstream aligned conditions utils always allow this (both on new and existing conditions)
2. existing conditions utils changes lastTranistionTime whenever something changes in the condition, while be/upstream aligned changes only when status change

Both seems bug to me, and by just fixing 1 also this issue should be addressed (but I would fix both)
@sbueringer opinions

**Comment by sbueringer** [comment]
Sounds good to me. I would also fix both

**Comment by sbueringer** [comment]
cc @srirammageswaran8  @vincepri ^^ (in case you are interested to implement it)

**Comment by Karthik-K-N** [comment]
So the fix for this issue would be updating the Set() method 

> I took some additional time to compare existing conditions utils and future/upstream aligned conditions utils
> 
> Those are the diffs:
> 
>     1. existing conditions utils only allow to set lastTranistionTime to an arbitrary value only when a condition does not exists but not when a condition already exists, while future/upstream aligned conditions utils always allow this (both on new and existing conditions)
> 
>     2. existing conditions utils changes lastTranistionTime whenever something changes in the condition, while future/upstream aligned  conditions utils are changing lastTranistionTime only when status change
> 
> 
> Both seems bug to me, and by just fixing 1 also this issue should be addressed (but I would fix both) @sbueringer opinions

So fix for this issue is to fix these two in existing condition utility or are you looking for something else as well.

**Comment by fabriziopandini** [comment]
Both changes should be implemented in https://github.com/fabriziopandini/cluster-api/blob/a8ae016c1800887ecd0683ac2e4720e6f9626d73/util/conditions/setter.go#L41-L78

**Comment by Karthik-K-N** [comment]
> Both changes should be implemented in https://github.com/fabriziopandini/cluster-api/blob/a8ae016c1800887ecd0683ac2e4720e6f9626d73/util/conditions/setter.go#L41-L78

Thank you, Will try to submit a PR with change
