### ISSUE TITLE
Consider filtering out finalizer warnings in controller logs

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#11065]
Context:
* Since Kubernetes 1.29 (afaik) we are getting warnings when setting finalizers (see https://github.com/kubernetes-sigs/cluster-api/issues/10914 for details).
* Since CR v0.19 it is possible to filter out warnings by setting a WarningHandler via rest.Config (https://github.com/kubernetes-sigs/controller-runtime/pull/2903)

The warnings we get today in our controllers look like this:

> {"ts":1724055396150.5093,"logger":"KubeAPIWarningLogger","caller":"log/warning_handler.go:65","msg":"metadata.finalizers: \"addons.cluster.x-k8s.io\": prefer a domain-qualified finalizer name to avoid accidental conflicts with other finalizer writers","v":0}

As we are aware of the "problem" and it will take us a while to migrate away from our current finalizers, I think we should consider to filter out the warnings in our controller logs.

Today logging the warnings produces a lot of spam and nobody that is running Cluster API can do anything about it.

**Comment by Karthik-K-N** [comment]
@sbueringer whats expected from this issue, If you can provide some info, I can try working on it.

**Comment by fabriziopandini** [comment]
+1 to implement this while we figure it out the transition to fully compliant finalizers tracked in https://github.com/kubernetes-sigs/cluster-api/issues/10914

**Comment by sbueringer** [comment]
@Karthik-K-N Sorry just noticed that this might have a big overlap with this: https://github.com/kubernetes-sigs/cluster-api/pull/11149#issuecomment-2334771970

Let's see how the other PR goes first. Potentially we can just use the same implementation

**Comment by Karthik-K-N** [comment]
> @Karthik-K-N Sorry just noticed that this might have a big overlap with this: [#11149 (comment)](https://github.com/kubernetes-sigs/cluster-api/pull/11149#issuecomment-2334771970)
> 
> Let's see how the other PR goes first. Potentially we can just use the same implementation
Sure, will wait Thank you.

**Comment by dlipovetsky** [comment]
I missed the tag earlier.

I think this is separate from the change in clusterctl (https://github.com/kubernetes-sigs/cluster-api/pull/11149), but the implementation should be similar.

We may want to hide specific warnings (e.g. only warnings related to Cluster API finalizers) in controllers and clusterctl. In that case, we'll need to implement a warning handler, and we can use that in both places. Is that something we want? If so, I can file a PR for that handler.

I have a draft PR for hiding all warnings in clusterctl (https://github.com/kubernetes-sigs/cluster-api/pull/11173).

**Comment by sbueringer** [comment]
> We may want to hide specific warnings (e.g. only warnings related to Cluster API finalizers) in controllers and clusterctl. In that case, we'll need to implement a warning handler, and we can use that in both places. Is that something we want? If so, I can file a PR for that handler.

Yeah I was thinking that the PR you wanted to open might lead to that, but I was waiting to see how that goes :)

**Comment by sbueringer** [comment]
I'm not sure if we should just ignore all warnings in clusterctl. Mostly because I don't know what other warnings might be, so I thought it's maybe better to ignore what we know is absolutely safe to ignore (the finalizer warning)
