### ISSUE TITLE
CAPI controllers fail to set ownerReference

### ISSUE THREAD

**Issue by muraee** [kubernetes-sigs/cluster-api#11098]
### What steps did you take and what happened?

CAPI removed RBAC for the `/finalizers` subresource in this PR
 https://github.com/kubernetes-sigs/cluster-api/pull/10552

However, management clusters with [OwnerReferencesPermissionEnforcement](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement) plugin enabled (e.g. OpenShift clusters) requires controllers setting ownerReference to have update permissions on the `/finalizer` subresource.
This will cause the CAPI cluster controller to fail to set the owner reference on infrastructure cluster objects, affecting all platforms.
```
E0826 07:45:09.811099       1 controller.go:324] "Reconciler error" err="[failed to patch ROSACluster default/helicapi-test: rosaclusters.infrastructure.cluster.x-k8s.io \"helicapi-test\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>, failed to patch ROSAControlPlane default/helicapi-test-control-plane: rosacontrolplanes.controlplane.cluster.x-k8s.io \"helicapi-test-control-plane\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>]" controller="cluster" controllerGroup="cluster.x-k8s.io" controllerKind="Cluster" Cluster="default/helicapi-test" namespace="default" name="helicapi-test" reconcileID="cc6aa9e4-caed-47ef-9c19-cf88170f4184"
```
see: https://sdk.operatorframework.io/docs/faqs/#after-deploying-my-operator-why-do-i-see-errors-like-is-forbidden-cannot-set-blockownerdeletion-if-an-ownerreference-refers-to-a-resource-you-cant-set-finalizers-on-

### What did you expect to happen?

CAPI Clusters can be successfully created on management clusters with [OwnerReferencesPermissionEnforcement](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement) plugin enabled.

### Cluster API version

v1.8.1

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
Wow, TIL about this plugin :)

> This admission controller also protects the access to metadata.ownerReferences[x].blockOwnerDeletion of an object, so that only users with update permission to the finalizers subresource of the referenced owner can change it.

Interesting behavior that we need finalizer permissions on our objects to be able to modify ownerReferences of owned resources.

(cc @fabriziopandini @chrischdi fyi)

Feel free to open a PR for it (+ please add a comment why we need this)

**Comment by muraee** [comment]
opened a PR: https://github.com/kubernetes-sigs/cluster-api/pull/11106
