### ISSUE TITLE
./gcp-deployer delete doesn't clean up context

### ISSUE THREAD

**Issue by wangzhen127** [kubernetes-sigs/cluster-api#111]
It seems that the kubernetes context is not removed after deleting the cluster using gcp-deployer.

To reproduce:
```
$ ./gcp-deployer delete
$ kubectl config get-contexts
```
You will see
```
CURRENT   NAME                          CLUSTER      AUTHINFO           NAMESPACE
*         kubernetes-admin@kubernetes   kubernetes   kubernetes-admin 
```

I expect at least it is not the current context, or the context is removed.

**Comment by roberthbailey** [comment]
Closing this since we are deleting gcp-deployer. Please re-open if this is still an issue with clusterctl delete (which just merged today).

/close
