### ISSUE TITLE
v1alpha2 infrastructure provider scaffolding

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes-sigs/cluster-api#1113]
/kind feature

We should provide a way to help developers implement infrastructure providers.  Ideally, most of these providers should be rather uniform in construction.

Some common concerns:

1. Reading details from the associated machine-object
2. Putting instance addresses (such as ip address or internal hostname) in a predictable place that can easily be scraped by the machine-controller
3. Uniform logging for high-level events (create, delete)
4. Uniform events
5. Possibly some level of conformance testing.
6. Error handling intelligence (expired cloud credentials, invalid configuration)
7. High-level interface (eg, the machine actuator interface) that describes proper 'flow' through various stages
8. Possibly Reconcile loop including above mentioned interface

How might we try to provide code that is reusable and customizable?  Library you can import via vendor?  Some project you can fork, and then later merge updates from upstream?

Some functionality will be quite kubernetes-specific; For instance, how does the infrastructure know to delete an instance?  What field should it watch on the machine-object, and what value?  This implies there will be a watch on machine-objects and EnqueueRequestsFromMapFunc or similar mechanism.

**Comment by detiber** [comment]
I definitely like the idea of having a library that can be used to provide common functionality.

I'm not a huge fan of a scaffolding repo, unless we somehow deliver it as a template that can do the find/replace necessary for users, since this has proven to be error prone and difficult for users in the past.

Another option that we may have is to extend kubebuilder or otherwise provide a kubebuilder like tool to stamp out a basic provider.

**Comment by michaelgugino** [comment]
kubebuilder like tool might work, but how do we enable providers to take advantage of enhancements down the road?

My dream is to just do ``` upstream stuff (merge)-> my stuff``` kind of thing.  As a provider implementer, I don't want to have to worry about the k8s part, just the cloud part.

**Comment by detiber** [comment]
@michaelgugino I'm not sure there is a good solution there, as we can't guarantee that users aren't doing something that would cause a merge conflict.

That said, putting the majority of functionality into a library would help alleviate some of the pain there.

**Comment by michaelgugino** [comment]
@detiber yeah, there might be merge conflicts, but you can always resolve those, and I think that would be easier than some other approaches.

Yeah, library at the very least would be quite helpful.

Perhaps we can come up with a sane workflow around kubebuilder + branch merging on the user's end.

**Comment by ncdc** [comment]
Copying content from #1245 from @akutz:
> GitHub now allows projects to be created from templates. In fact, the kubeadm bootstrap provider repository was generated from the Kubernetes template project.

>It would dramatically reduce the barrier to entry when it comes to creating new CAPI providers if there was a kubernetes-sigs/cluster-api-provider-template-project repository from which new providers could be generated.

**Comment by vincepri** [comment]
Closing this for now given inactivity / release of v1alpha3.

/close
