### ISSUE TITLE
flakes in clusterctl upgrade tests

### ISSUE THREAD

**Issue by cahillsf** [kubernetes-sigs/cluster-api#11133]
summarized by @chrischdi 🙇 

---

According to [aggregated failures](https://storage.googleapis.com/k8s-triage/index.html?job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades) of the last two weeks, we still have some flakyness on our clusterctl upgrade tests.

* ~~[3 Failures](https://storage.googleapis.com/k8s-triage/index.html?date=2024-10-21&text=connect%3A%20connection%20refused&job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades): `Internal error occurred: failed calling webhook [...] connect: connection refused`~~
  
  * **[2024-12-19 update]** appears to be fixed via https://github.com/kubernetes-sigs/cluster-api/pull/11349
  * Component: CAPD
  * Branches:
    * main
    * release-1.8
* ~~[2 Failures](https://storage.googleapis.com/k8s-triage/index.html?date=2024-10-20&text=x509%3A%20certificate%20signed%20by%20unknown%20authority&job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades&xtext=connect%3A%20connection%20refused%7CTimed%20out%20waiting%20for%20all%20Machines%20to%20exist%7CFailed%20to%20create%20kind%20cluster): `x509: certificate signed by unknown authority`~~
    * **[2024-12-19 update]** this appears to be fixed via https://github.com/kubernetes-sigs/cluster-api/pull/10513 and https://github.com/kubernetes-sigs/cluster-api/pull/11478 
  * Component: unknown
  * Branches:
    * main
    * release-1.8
    * release-1.7

* ~~[2 failures](https://storage.googleapis.com/k8s-triage/index.html?date=2024-10-21&text=failed%20to%20run%20clusterctl%20version%3A&job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades&xtext=connect%3A%20connection%20refused%7CTimed%20out%20waiting%20for%20all%20Machines%20to%20exist%7CFailed%20to%20create%20kind%20cluster%7Cx509%3A%20certificate%20signed%20by%20unknown%20authority%7CTimed%20out%20waiting%20for%20Machine%20Deployment%7CTimed%20out%20waiting%20for%20Cluster): `failed to run clusterctl version:`~~

  * **[2024-12-19 update]** no longer found in [test history](https://storage.googleapis.com/k8s-triage/index.html?date=2024-12-19&text=failed%20to%20run%20clusterctl%20version%3A&job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades&xtext=connect%3A%20connection%20refused%7CTimed%20out%20waiting%20for%20all%20Machines%20to%20exist%7CFailed%20to%20create%20kind%20cluster%7Cx509%3A%20certificate%20signed%20by%20unknown%20authority%7CTimed%20out%20waiting%20for%20Machine%20Deployment%7CTimed%20out%20waiting%20for%20Cluster) - reason unknown
  * Component: clusterctl/test framework it seems
  * Branches:
    * release-1.7
    * release-1.6

* ~~[5 Failures](https://storage.googleapis.com/k8s-triage/index.html?date=2024-09-02&text=Timed%20out%20waiting%20for%20Machine%20Deployment&job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades)~~: `Timed out waiting for Machine Deployment clusterctl-upgrade/clusterctl-upgrade-workload-... to have 2 replicas`
  * **[2024-10-21 update]** no failures in [recent history](https://storage.googleapis.com/k8s-triage/index.html?date=2024-10-21&text=Timed%20out%20waiting%20for%20Machine%20Deployment&job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades) but did have some as recently as [2024-10-03](https://storage.googleapis.com/k8s-triage/index.html?date=2024-10-16&text=Timed%20out%20waiting%20for%20Machine%20Deployment&job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades).  Unclear what introduced the improvement (this was relatively infrequent to begin with)
  * **[2024-12-19 update]** once again not apparent in [recent history ](https://storage.googleapis.com/k8s-triage/index.html?date=2024-12-19&text=Timed%20out%20waiting%20for%20Machine%20Deployment&job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades)...
  * Component: unknown
  * Branches:
    * release-1.8
    * main

* ~~[2 Failures](https://storage.googleapis.com/k8s-triage/index.html?date=2024-09-02&text=Timed%20out%20waiting%20for%20Cluster&job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades): `Timed out waiting for Cluster clusterctl-upgrade/clusterctl-upgrade-workload-... to provision`~~ - resolved with: https://github.com/kubernetes-sigs/cluster-api/pull/11220
  
  * Component: unknown
  * Branches:
    * release-1.8
    * main

* ~~[36 failures](https://storage.googleapis.com/k8s-triage/index.html?date=2024-09-02&text=Timed%20out%20waiting%20for%20all%20Machines%20to%20exist&job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades): `Timed out waiting for all Machines to exist`~~ split off into: https://github.com/kubernetes-sigs/cluster-api/issues/11209

* ~~[16 Failures](https://storage.googleapis.com/k8s-triage/index.html?date=2024-09-02&text=Failed%20to%20create%20kind%20cluster&job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades): `Failed to create kind cluster`~~ - resolved with: https://github.com/kubernetes-sigs/cluster-api/pull/11220
  
  * Component: e2e setup
  * Branches:
    * main
    * release-1.7

Link to check if messages changed or we have new flakes on clusterctl upgrade tests: [here](https://storage.googleapis.com/k8s-triage/index.html?job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades&xtext=connect%3A%20connection%20refused%7CTimed%20out%20waiting%20for%20all%20Machines%20to%20exist%7CFailed%20to%20create%20kind%20cluster%7Cx509%3A%20certificate%20signed%20by%20unknown%20authority%7CTimed%20out%20waiting%20for%20Machine%20Deployment%7CTimed%20out%20waiting%20for%20Cluster)

/kind flake

**Comment by chrischdi** [comment]
> ```
> Failed to create control group inotify object: Too many open files
> Failed to allocate manager object: Too many open files
> ```

That sounds very suspicious regarding to 
https://main.cluster-api.sigs.k8s.io/user/troubleshooting.html?highlight=sysctl#cluster-api-with-docker----too-many-open-files

Maybe would be a good start here to collect data about the actual used values :-)

**Comment by BenTheElder** [comment]
> 	"cluster": "eks-prow-build-cluster",

I don't know if we're running https://github.com/kubernetes/k8s.io/blob/3f2c06a3c547765e21dce65d0adcb1144a93b518/infra/aws/terraform/prow-build-cluster/resources/kube-system/tune-sysctls_daemonset.yaml#L4 there or not

Also perhaps something else on the cluster is using a lot of them.

**Comment by ameukam** [comment]
I confirm the daemonset runs on the EKS cluster.

**Comment by BenTheElder** [comment]
It's possible? This part shouldn't really take long though ..

I suspect that would be a noisy neighbor problem on the EKS cluster (I/O?)

Doesn't explain the inotify-exhaustion like failures.

**Comment by sbueringer** [comment]
We recently increased concurrency in our tests. With that we were able to reduce Job durations from 2h to 1h.

We thought it's a nice way to save us time and the community money. 

Maybe we have to roll that back

**Comment by sbueringer** [comment]
main: https://github.com/kubernetes-sigs/cluster-api/pull/11067
release-1.8: https://github.com/kubernetes-sigs/cluster-api/pull/11144

**Comment by cahillsf** [comment]
related note ( i split off one of the messages into a separate issue https://github.com/kubernetes-sigs/cluster-api/issues/11209 just so this conversation didn't get too convoluted) -- we are going to try reverting the concurrency increase and see if the situation improves

https://github.com/kubernetes-sigs/cluster-api/pull/11220
https://github.com/kubernetes-sigs/cluster-api/pull/11222

**Comment by BenTheElder** [comment]
> We can see that the multi-user.target[2](https://github.com/kubernetes-sigs/cluster-api/issues/11133#user-content-fn-2-513293cf5fe2e6bd271239d298b6b756) is reached at the same time as the journal started to log. On a failing test, there is a already 24 seconds of difference. I'm wondering if randomly (under heavy load) we don't reach the 30 seconds of timeout[3](https://github.com/kubernetes-sigs/cluster-api/issues/11133#user-content-fn-3-513293cf5fe2e6bd271239d298b6b756) for reaching the multi-user.target hence the failure.

That makes sense, ordinarily this part shouldn't take long, it doesn't need to fetch anything over the network and it should be pretty fast.

But in a resource starved environment it might take to long. In that environment I would also expect Kubernetes to be unstable though, api-server/etcd will be timing out if make it that far.

**Comment by sbueringer** [comment]
@cahillsf What is the current state?

**Comment by cahillsf** [comment]
> @cahillsf What is the current state?

sorry @sbueringer was out on PTO, i just updated the description with the current status (one net new flake pattern)

---

i did some investigation on the most frequent:
> [3 Failures](https://storage.googleapis.com/k8s-triage/index.html?date=2024-10-21&text=connect%3A%20connection%20refused&job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades): Internal error occurred: failed calling webhook [...] connect: connection refused

- failing example where the `ClusterClass` is not getting reconciled: 
    - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1839604474990039040
    - https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1839604474990039040/artifacts/clusters/clusterctl-upgrade-management-yu9mot/resources/clusterctl-upgrade/ClusterClass/quick-start.yaml (variables reconciled - `RefVersionsUpToDate` not `True`)
    - CAPI logs: https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1839604474990039040/artifacts/clusters/clusterctl-upgrade-management-yu9mot/logs/capi-system/capi-controller-manager/capi-controller-manager-768dc55749-t8gwj/manager.log (clusterclass failing to reconcile - observed generation not incremented)

i was not able to find much indication in the logs about what might be going wrong here.  could be some issue with the kube components but it seems we are not collecting these in the artifacts for this test.  any thoughts as to how to better troubleshoot this?  maybe ill open a PR to try to collect the `kube-system` logs for this test?

**Comment by sbueringer** [comment]
@cahillsf No worries, welcome back :)

> failing example where the ClusterClass is not getting reconciled

Not sure if you meant it that way, but I think the problem is not that CC is not getting reconciled. The problem is that we cannot deploy the DockerClusterTemplate:
> Internal error occurred: failed calling webhook "default.dockerclustertemplate.infrastructure.cluster.x-k8s.io":
> https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1839604474990039040

The consequence of that is then that the ClusterClass cannot be reconciled.

The question is, why is the CAPD webhook not up at this time. 

Can we do a quick PR to drop this in docker.yaml?
```yaml
    - old: "--leader-elect"
      new: "--leader-elect\n        - --logging-format=json"
```

Using JSON logging for e2e tests was a nice idea at the time, but overall it just makes troubleshooting without Grafana (which is what we do most of the time) pretty painful.

**Comment by cahillsf** [comment]
yes thanks for clarifying

> Can we do a quick PR to drop this in docker.yaml?

Sure thing, should ill add this replacement for all of the v1.8 providers -- sound good?

**Comment by sbueringer** [comment]
I would drop them entirely from docker.yaml

**Comment by cahillsf** [comment]
oh oh i misread on the first pass (see you've already approved but dropping the PR here so it gets linked: https://github.com/kubernetes-sigs/cluster-api/pull/11318)

**Comment by sbueringer** [comment]
Okay so what I was looking for was basically a way to correlate when the test failed and when CAPD was coming up. To then try to figure out what's going on. This should be easier with "regular" timestamps now

**Comment by cahillsf** [comment]
> - that clusterctl waits until providers are up (maybe worth to check)

it does appear to, the management cluster is created with [InitManagementClusterAndWatchControllerLogs](https://github.com/kubernetes-sigs/cluster-api/blob/76328ed38a61cba346dc4f1644ad2b5a8de64291/test/e2e/clusterctl_upgrade.go#L380) which waits for all deployments to be available [here](https://github.com/kubernetes-sigs/cluster-api/blob/76328ed38a61cba346dc4f1644ad2b5a8de64291/test/framework/clusterctl/clusterctl_helpers.go#L120) by calling [WaitForDeploymentsAvailable](https://github.com/kubernetes-sigs/cluster-api/blob/76328ed38a61cba346dc4f1644ad2b5a8de64291/test/framework/deployment_helpers.go#L72)

the logic seems pretty straightforward and sound here? not sure if anything sticks out to you 

> - that the kubectl apply has some sort of retry so it doesn't fail immediately (also worth to check)

it does not, [CreateOrUpdate](https://github.com/kubernetes-sigs/cluster-api/blob/76328ed38a61cba346dc4f1644ad2b5a8de64291/test/e2e/clusterctl_upgrade.go#L451) is called on the `managementClusterProxy` which is defined [here](https://github.com/kubernetes-sigs/cluster-api/blob/76328ed38a61cba346dc4f1644ad2b5a8de64291/test/framework/cluster_proxy.go#L293) and has no retry logic

can open a PR to add support for some retry option to be passed into CreateOrUpdate and see if that helps

**Comment by sbueringer** [comment]
> the logic seems pretty straightforward and sound here? not sure if anything sticks out to you

Probably fine. I assume waiting for `Available` to be true on a Deployment means that the capi-controller Pod is `Ready`? (which would include readinessProbes to work which includes webhook server to be up)

> It does not, [CreateOrUpdate](https://github.com/kubernetes-sigs/cluster-api/blob/76328ed38a61cba346dc4f1644ad2b5a8de64291/test/e2e/clusterctl_upgrade.go#L451) is called on the managementClusterProxy which is defined [here](https://github.com/kubernetes-sigs/cluster-api/blob/76328ed38a61cba346dc4f1644ad2b5a8de64291/test/framework/cluster_proxy.go#L293) and has no retry logic
> can open a PR to add support for some retry option to be passed into CreateOrUpdate and see if that helps

Ah okay, I thought we might have a retry. But it's probably a good thing. Adding a retry there might hide some problems 

I see potentially a gap between Deployment being Available / Pod being Ready and kube-proxy updating iptables so the webhook is actually reachable.

I think it would be important to clarify the timeline:
* based on Pod timestamps, when is the webhook server actually up (to confirm clusterctl is waiting correctly)
* when is the request failing

Let's try to get those timestamps. 

If there is only a gap of 1-2 seconds we might want to retry CreateOrUpdate with dry-run until all webhooks work and then run CreateOrUpdate once without dry-run.

**Comment by cahillsf** [comment]
> I think it would be important to clarify the timeline:
> 
>  - based on Pod timestamps, when is the webhook server actually up (to confirm clusterctl is waiting correctly)
>  - when is the request failing
> Let's try to get those timestamps.
> 
> If there is only a gap of 1-2 seconds we might want to retry CreateOrUpdate with dry-run until all webhooks work and then run CreateOrUpdate once without dry-run.

taking this [same failure example](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1839604474990039040), `CreateOrUpdate` call fails at `09/27/24 11:10:05.875`:
```go
[FAILED] Expected success, but got an error:
...
  In [It] at: /home/prow/go/src/sigs.k8s.io/cluster-api/test/e2e/clusterctl_upgrade.go:451 @ 09/27/24 11:10:05.875
```

but the CAPD logs are reflecting the webhook server as up at `I0927 11:09:59.835554`:
```go
I0927 11:09:59.835554       1 server.go:242] "Serving webhook server" logger="controller-runtime.webhook" host="" port=9443`
```

so 6 seconds between the server as up and the call failing, not sure if we want to give the dry run approach a shot anyway? 
maybe we add collection of `kube-system` logs to further investigate this?
> I see potentially a gap between Deployment being Available / Pod being Ready and kube-proxy updating iptables so the webhook is actually reachable.

**Comment by cahillsf** [comment]
circling back to this @sbueringer now the most frequent flake (https://github.com/kubernetes-sigs/cluster-api/issues/11133#issuecomment-2427763004) is only occurring on `release-1.8` branches: https://storage.googleapis.com/k8s-triage/index.html?date=2024-11-18&text=connect%3A%20connection%20refused&job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades

so it seems this dry-run approach worked 

(last flake on `main` is visible on[ this timeline](https://storage.googleapis.com/k8s-triage/index.html?date=2024-11-06&text=connect%3A%20connection%20refused&job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades) and occurred 10/28 prior to the dry-run update merge on 10/29).  do you think that is enough data to backport to release-1.8?

**Comment by BenTheElder** [comment]
[I'm still lurking here but there's been a lot going on and it seems like you all are making progress 😅]

**Comment by cahillsf** [comment]
no conclusions, but adding some findings re: 
> [2 Failures](https://storage.googleapis.com/k8s-triage/index.html?date=2024-10-20&text=x509%3A%20certificate%20signed%20by%20unknown%20authority&job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades&xtext=connect%3A%20connection%20refused%7CTimed%20out%20waiting%20for%20all%20Machines%20to%20exist%7CFailed%20to%20create%20kind%20cluster): x509: certificate signed by unknown authority

[taking one specific example](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-release-1-8/1852504358629937152) (have observed similar patterns in other failures) the test fails while [migrating the CRs](https://github.com/kubernetes-sigs/cluster-api/blob/06a3bc0df61f8e18abd575b22444aea1a97caaa9/cmd/clusterctl/client/cluster/upgrader.go#L385) in the `UpgradeManagementClusterAndWait` process [initiated here](https://github.com/kubernetes-sigs/cluster-api/blob/06a3bc0df61f8e18abd575b22444aea1a97caaa9/cmd/clusterctl/client/cluster/upgrader.go#L385) in the e2e test from `v0.4.8` -> `v1.6.8`.  

Note: the CRs are migrated  _before_ any [changes are rolled out to the providers](https://github.com/kubernetes-sigs/cluster-api/blob/06a3bc0df61f8e18abd575b22444aea1a97caaa9/cmd/clusterctl/client/cluster/upgrader.go#L390-L408)

looking at the [CAPD controller logs](https://storage.googleapis.com/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-release-1-8/1852504358629937152/artifacts/clusters/clusterctl-upgrade-management-1sv984/logs/capd-system/capd-controller-manager/capd-controller-manager-7cb759f76b-f2x2z/manager.log), we can see they start filling up with these errors shortly after the upgrade command is run:
```
2024/11/02 01:44:37 http: TLS handshake error from 10.244.0.1:28755: remote error: tls: bad certificate
2024/11/02 01:44:38 http: TLS handshake error from 10.244.0.1:20689: remote error: tls: bad certificate
2024/11/02 01:44:39 http: TLS handshake error from 10.244.0.1:29264: remote error: tls: bad certificate
2024/11/02 01:44:40 http: TLS handshake error from 10.244.0.1:10669: remote error: tls: bad certificate
```

the migration eventually times with this line `@ 11/02/24 01:45:01.663`:
```
Error: failed to migrate clusterctl-upgrade/clusterctl-upgrade-workload-zszpga-control-plane: action failed after 10 attempts: Internal error occurred: failed calling webhook "validation.dockermachinetemplate.infrastructure.cluster.x-k8s.io": failed to call webhook: Post "https://capd-webhook-service.capd-system.svc:443/validate-infrastructure-cluster-x-k8s-io-v1alpha4-dockermachinetemplate?timeout=10s": x509: certificate signed by unknown authority
```

before the log stream cuts off, we can see these logs in the CAPD manager:
```
I1102 01:45:18.422998       1 deleg.go:130] controller-runtime/certwatcher "msg"="Updated current TLS certificate"  
I1102 01:45:18.423382       1 deleg.go:130] controller-runtime/certwatcher "msg"="Updated current TLS certificate" 
```

not exactly sure where to go next with this -- this `v0.4.8` version is using `sigs.k8s.io/controller-runtime v0.9.7` maybe there is some issue with the certwatcher in this version?

**Comment by sbueringer** [comment]
> (last flake on `main` is visible on[ this timeline](https://storage.googleapis.com/k8s-triage/index.html?date=2024-11-06&text=connect%3A%20connection%20refused&job=.*periodic-cluster-api-e2e.*&test=.*clusterctl%20upgrades) and occurred 10/28 prior to the dry-run update merge on 10/29). do you think that is enough data to backport the changes to release-1.8?

Absolutely

**Comment by sbueringer** [comment]
@cahillsf potentially related: https://github.com/kubernetes-sigs/cluster-api/issues/10522

**Comment by sbueringer** [comment]
@cahillsf probably related: https://github.com/kubernetes-sigs/cluster-api/issues/10522

The best idea I have is rerunning clusterctl upgrade if we hit this error (but of course only for clusterctl v0.4.x because we can't fix it anymore)

@chrischdi wdyt?

**Comment by chrischdi** [comment]
> @cahillsf probably related: #10522
> 
> The best idea I have is rerunning clusterctl upgrade if we hit this error (but of course only for clusterctl v0.4.x because we can't fix it anymore)
> 
> @chrischdi wdyt?

This is testing the upgrade from v0.4.8 to v1.6.8 right? So the upgrade is done using clusterctl v1.6.8. So its about rerunning on v1.6.8.

Retrying clusterctl upgrade may help and maybe is the easiest 👍 .

Just to take a step back:

* We start clusterctl upgrade which
  * Upgrades cert-manager (to an old version)
  * tries to migrate CRDs and then fails here

Another approach when retrying clusterctl upgrade is not good enough may be to run out-of-band the cert-manager upgrade (and upgrade to the same or a more recent version?!) + directly the CR migration including retries.

Afterwards run the normal clusterctl upgrade as before.

Note: and only for upgrades to v1.6.x :-)

Offtopic: Shoutout to @cahillsf , awesome progress here! ❤️

**Comment by sbueringer** [comment]
@chrischdi Can we simply backport the longer timeout that you introduced in #10513 into release-1.7, and release-1.6?

Do we know if that issue alls occurs in tests that use clusterctl v1.5?

If not I would consider doing one additional v1.6.x release and then we're good

**Comment by chrischdi** [comment]
+1 on backporting that and also cut a v1.6.9 for this.

But v1.5 seems also to be affected:

https://storage.googleapis.com/k8s-triage/index.html?text=x509%3A%20certificate%20signed%20by%20unknown%20authority&job=.*-cluster-api-.*&test=.*1%5C.5.*&xjob=.*-provider-.*

**Comment by chrischdi** [comment]
so maybe:
* backport the timeout for 1.7
* retry upgrade for 1.5.x and v1.6.x?
  * the second retry should succeed as cert-manager should get stable

**Comment by cahillsf** [comment]
@sbueringer @chrischdi have a draft PR up here for retrying the upgrade: https://github.com/kubernetes-sigs/cluster-api/pull/11478

comments welcome

**Comment by cahillsf** [comment]
/assign

since there is a lot of outdated context here and we are approaching the end of this release cycle, i was thinking it would be good to close out this issue within the next couple weeks and open a new one with a refreshed state of the clusterctl flakes (still a couple popping up)

wdyt @chrischdi @sbueringer ?

**Comment by cahillsf** [comment]
updated the summary, everything identified in this PR has been resolved or has a separate issue open.  i think there is one new flake for the upgrade test -- will open a new issue for that one after some investigation

/close

**Comment by sbueringer** [comment]
Thank you very much!
