### ISSUE TITLE
Fix release crawler for LWKD

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#11182]
### What would you like to be added (User Story)?

As a users I would like to be informed about new CAPI releases
As a maintainer/release team I would like to be spread the voice about new CAPI releases

### Detailed Description

LWKD is weekly email with news about the K8s ecosystem
It seems that the configuration of the crawler that looks up for changes in subproject is wrong WRT to Cluster API, we should fix it!

### Anything else you would like to add?

Based on my understanding this is where the fix should be done
- [here](https://github.com/yankay/lwkd/blob/588d8d5a606261401c5154f7c3abd612ce861396/scripts/release-crawler/README.md?plain=1#L42) - Wrong url
- [here](https://github.com/yankay/lwkd/blob/588d8d5a606261401c5154f7c3abd612ce861396/scripts/release-crawler/main.go#L18-L53) - Cluster API should move from kubernetes to kubernetes-sigs

### Label(s) to be applied

/kind feature
/area release

cc @kubernetes-sigs/cluster-api-release-team

**Comment by chrischdi** [comment]
Thanks @Sunnatillo for opening the PR!

xref:
- https://github.com/kubernetes-sigs/lwkd/pull/432

**Comment by chrischdi** [comment]
/reopen

I created:
- https://github.com/kubernetes-sigs/lwkd/pull/441

To fix some more :-)
