### ISSUE TITLE
Decide on a documentation versioning/scheme

### ISSUE THREAD

**Issue by moshloop** [kubernetes-sigs/cluster-api#1119]
What is the planned approach for handling documentation re v1alpha1 vs v1alpha2?  I see a couple of potential approaches:

1) Have a different documentation site for each version, similar to k/k
2) Have 1 documentation site focusing on master, and just highlighting version specific differences
3) Have 1 documentation site with a common, v1alpha1 and v1alpha2 sections

@davidewatson @vincepri @ashish-amarnath @detiber @rudoi 

My vote is for option 2 until we reach beta and then switch to option 1.

**Comment by detiber** [comment]
My preference is to have a documentation site for each version, since v1alpha2 will differ significantly from v1alpha1. We can leverage the Netlify integration that we have currently in the following ways to handle this:
- enable per-branch subdomains in Netlify
- add a Netlify a new config to the release-0.1 branch
- Add a header to the docs in `master` to indicate that they are under heavy development and link to v1alpha1 docs.

**Comment by moshloop** [comment]
I am happy with that as well, who has the rights to create the new subdomain?

**Comment by detiber** [comment]
I'll work on following up with @davidewatson on this
/assign
/assign @davidewatson

**Comment by davidewatson** [comment]
I have enabled per branch netlify [deployments](https://www.netlify.com/docs/continuous-deployment/#branches-deploys) and am using https://github.com/kubernetes-sigs/cluster-api/pull/1156 to test.

**Comment by davidewatson** [comment]
The URL for the `release-0.1` branch should be `https://release-0.1--kubernetes-sigs-cluster-api.netlify.com/`. I think we just need to configure a CNAME and update the `netlify.toml` now. See https://github.com/kubernetes/community/issues/3454#issuecomment-484534141 for the complete instructions.

**Comment by detiber** [comment]
I went ahead and created the PR for the DNS subdmain here: https://github.com/kubernetes/k8s.io/pull/318
I'll work on creating a PR to update the Netlify config.

**Comment by detiber** [comment]
Netlify config update here: https://github.com/kubernetes-sigs/cluster-api/pull/1176

**Comment by davidewatson** [comment]
For some reason the branch name `release-0.1` is causing problems. I think it's the dot and the [DNS haiku](https://www.cyberciti.biz/humour/a-haiku-about-dns/) is right. Either way, here's where we are:

- Netlify [deployment contexts](https://www.netlify.com/docs/continuous-deployment/#deploy-contexts) are configured for branches named: `release-0.1`, `release-01`, and `v1alpha1`.

<img width="923" alt="Screen Shot 2019-07-22 at 8 38 51 PM" src="https://user-images.githubusercontent.com/11819015/61681084-d3493780-acc0-11e9-9cba-431db6659f13.png">

- A `release-01` branch was created from `release-0.1` and is correctly served from https://release-01--kubernetes-sigs-cluster-api.netlify.com/ 

What do we think about renaming the `release-0.1` release to something without dots?

**Comment by davidewatson** [comment]
Maybe the right thing to do is just enable all branches...

**Comment by vincepri** [comment]
What about naming the subdomain v1alpha1 instead of v0-1?

**Comment by detiber** [comment]
@vincepri The issue is less about the subdomain used for the redirects and CNAME entries, and more about the name of the underlying branch name (that is the target of the redirects).

**Comment by detiber** [comment]
I'm not sure how the k8s docs are handling the redirects, I'm not seeing anything related to it in the release-1.15 branch netlify config for example: https://github.com/kubernetes/website/blob/release-1.15/netlify.toml

**Comment by detiber** [comment]
It looks like some of it is abstracted away in the hugo config: https://github.com/kubernetes/website/blob/release-1.15/config.toml

**Comment by detiber** [comment]
Aha, I think I cracked the code, it looks like Netlify might just replace `.` with `-`: https://release-0-1--kubernetes-sigs-cluster-api.netlify.com/

**Comment by davidewatson** [comment]
🙃okay! So we can keep the branch names... Do we want to deploy all branches? I think so...

**Comment by detiber** [comment]
+1 to all branches

**Comment by detiber** [comment]
Created PRs to fix the netlify URL: https://github.com/kubernetes-sigs/cluster-api/pull/1204 and https://github.com/kubernetes/k8s.io/pull/323

@davidewatson With that I believe we can delete the Netlify configurations for `release-01` and `v1alpha1` and also delete the `release-01` branch.

**Comment by detiber** [comment]
@davidewatson I believe the [Assigning a custom domain steps](https://www.netlify.com/docs/custom-domains/#assigning-a-custom-domain) need to be performed within the Netlify config, and may require some additional trickery as described here: https://community.netlify.com/t/common-issue-how-to-use-netlify-s-branch-deploy-feature-without-netlify-dns/128

**Comment by davidewatson** [comment]
Thanks Jason, I’ll take a look tonight.

**Comment by vincepri** [comment]
This should be implemented and ready to go, @detiber do you think we can close this one out?

**Comment by detiber** [comment]
Yes, let's close
/close
