### ISSUE TITLE
Possible version inconsistency for indirect dependency

### ISSUE THREAD

**Issue by HappyHacker123** [kubernetes-sigs/cluster-api#11258]
### What would you like to be added (User Story)?

</h3><em>kubernetes-sigs/cluster-api</em> has already opted into module and indirectly depends on <em>coreos/go-systemd</em> through a GOPATH project. And project <em>coreos/go-systemd</em> already opted into module and released a v2+ version with the major branch strategy. The latest module path of <em>coreos/go-systemd</em> is <em> "github.com/coreos/go-systemd/v22" </em>. From module-unaware project\'s perspective, it interprets the import path <em> "github.com/coreos/go-systemd" </em> as coreos/go-systemd\'s latest version. But from the Go Modules\' point of view, path <em> "github.com/coreos/go-systemd" </em> equals to version v0/v1 or the latest version that doesn’t use the module. So when you try to get <em>coreos/go-systemd</em> through the indirect path <em> "github.com/coreos/go-systemd" </em> which comes from module-unaware project, the module pulls the old version of coreos/go-systemd. This causes version of coreos/go-systemd , which you are dependent on, sticked at the old version coreos/go-systemd .

### Detailed Description

Eliminate the inconsistency.

### Label(s) to be applied

/kind feature
/area dependency
/area cleanup

**Comment by chrischdi** [comment]
Note: we only have an indirect deoendency on `github.com/coreos/go-systemd` and depend on both.

The indirect dependency comes from depending on `github.com/flatcar/ignition@v0.36.2` and `github.com/flatcar/container-linux-config-transpiler@v0.9.4`:

```
❯ go mod graph | grep go-systemd@v0.0.0
sigs.k8s.io/cluster-api github.com/coreos/go-systemd@v0.0.0-20191104093116-d3cd4ed1dbcf
github.com/flatcar/container-linux-config-transpiler@v0.9.4 github.com/coreos/go-systemd@v0.0.0-20191104093116-d3cd4ed1dbcf
github.com/flatcar/ignition@v0.36.2 github.com/coreos/go-systemd@v0.0.0-20181031085051-9002847aa142
```

So this is propably related to https://github.com/kubernetes-sigs/cluster-api/issues/9157 .

**Comment by sbueringer** [comment]
/close

No update in the last month. Feel free to reopen
