### ISSUE TITLE
Slow machine deployment upgrade

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1127]
/kind bug

**What steps did you take and what happened:**
I issued an update to a machineDeployment. Everything ended up working in the end but it was very slow. In fact, it was 10 minutes between each node being scaled up / down. So each reconcile loop, the MachineSet would take exactly one action. Note: There are two machinists during an update event. The original one that scales down and the new one that scales up. So once the machine deployment is updated, a new MachineSet is created. One node is added. Ten minutes elapse and a new node is added and a previous node is deleted. Another 10 minutes elapse and the final old node is deleted.

**What did you expect to happen:**
I expected this to happen much more quickly. I am wondering if some code isn to returning a retry result and instead returning successfully?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
@chuckha do you have logs from the infra provider during this time?

**Comment by chuckha** [comment]
I don't but can recreate them. I was watching the logs and it was nothing interesting. It did everything I was expecting except there was a 10 minute space between when things happened.

**Comment by vincepri** [comment]
A few other details to check: Do Machine have NodeRef properly set? Do the MachineSets associated with the MachineDeployment have AvailableReplicas?

**Comment by chuckha** [comment]
The associated MachineSets do need have available replicas. It does work, it just takes a long time.

**Comment by ncdc** [comment]
@chuckha which provider were you using - capd?

**Comment by chuckha** [comment]
@ncdc yes, I have not tried on CAPA yet so it may very well be a CAPD issue.

**Comment by ncdc** [comment]
I've heard similar reports with CAPA
