### ISSUE TITLE
CAPI Ovewrites coredns image

### ISSUE THREAD

**Issue by kotyara85** [kubernetes-sigs/cluster-api#11301]
### What steps did you take and what happened?

Hello everyone,
I'm using capi 1.8.3 and deploying kube v1.30.3 without coredns addon, so it's installed by using a helm chart.
Image repo for an official helm chart is different, what I've noticed is that something changes an image from coredns/coredns to registry.k8s.io/coredns

That stopped after I shutdown capi mgmt cluster 💀

Coredns helm chart and official have different format of image tags

### What did you expect to happen?

Capi not to overwrite coredns image if coredns is set to skip

### Cluster API version

1.8.3

### Kubernetes version

1.30.3

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
You have set the "controlplane.cluster.x-k8s.io/skip-coredns" annotation on the KCP object and KCP is still modifying your CoreDNS Deployment?

That should be impossible, xref: https://github.com/kubernetes-sigs/cluster-api/blob/d86ba52721e8be732f7b1fb725cc8bab360af67e/controlplane/kubeadm/internal/workload_cluster_coredns.go#L109

**Comment by kotyara85** [comment]
> You have set the "controlplane.cluster.x-k8s.io/skip-coredns" annotation on the KCP object and KCP is still modifying your CoreDNS Deployment?
> 
> That should be impossible, xref:
> 
> https://github.com/kubernetes-sigs/cluster-api/blob/d86ba52721e8be732f7b1fb725cc8bab360af67e/controlplane/kubeadm/internal/workload_cluster_coredns.go#L109

Hm, looks like I need to add that label to control planes, addition to skip step in kubeadm. Thanks

**Comment by sbueringer** [comment]
Ah yup. I assumed you meant that annotation when you wrote "coredns is set to skip" :)

Please note, it's an annotation not a label.

**Comment by kotyara85** [comment]
> Ah yup. I assumed you meant that annotation when you wrote "coredns is set to skip" :)
> 
> Please note, it's an annotation not a label.

Yeah, I already have one for kube proxy. Haha. Thanks again!
