### ISSUE TITLE
Provide public functions to create "generic" Cluster API resources for use in tests

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#11334]
### What would you like to be added (User Story)?

As a developer of controllers that read Cluster API resources, I want an easy way to create  "generic" Cluster API resources for use in tests.

### Detailed Description

The core repository has a package, `internal/test/builder`, that makes it easy to create "generic" Cluster API resources. However, the package is not public. I would like us to publish this package, e.g., under `util/test/builder`.

### Anything else you would like to add?

In the past, I have made a copy of the `internal/test/builder` package. But I would prefer to import the upstream package.

There may be good reasons for keeping the package internal, but none have occurred to me yet.

I think moving the package is straightforward. I've done it in [this commit](https://github.com/dlipovetsky/cluster-api/commit/28647fa8519b2bec09cfe17fe3d9b1765772ce28), and all unit tests pass. 

### Label(s) to be applied

/kind feature
/area testing

**Comment by sbueringer** [comment]
I would be okay to make it public, but I don't want to guarantee stability of this package. I don't want to be forced to create another package like this if we need changes to the package

**Comment by sbueringer** [comment]
To clarify. I'm not concerned about keeping the builders roughly stable. It's more about the definition of some of these CRDs:  https://github.com/kubernetes-sigs/cluster-api/blob/1ae8a33bbae3fac60658f9de0a4265682bfc51e3/internal/test/builder/infrastructure.go#L181

Are you interested in the entire package or mostly just builders.go?

**Comment by dlipovetsky** [comment]
Thanks for triaging!

> I would be okay with making it public, but I don't want to guarantee stability of this package.

I agree. I think that is reasonable, given that the use case is narrow, and strictly developer-facing.

(If the package is not public, a developer has two alternatives: copy the package, or implement it themself. If they copy the package ,they'll likely update it in the future, and have to deal with any breaking changes. If they implement it themself,  they'll need to keep it up to date with upstream specs. Dealing with breaking changes in an imported package seems easier than either alternative.)

> Are you interested in the entire package or mostly just builders.go?

I think I need I have only used the exported functions and structs. Here is a [test helper](https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/blob/a1470d46bf57eb5e6bf6c6dcf8c1e86c2a1455d0/pkg/controllers/namespacesync/controller_test.go#L174-L205) I wrote with the (copied) package.

**Comment by sbueringer** [comment]
I'm wondering if something like the CRDs in this file are useful outside of core CAPI: https://github.com/kubernetes-sigs/cluster-api/blob/1b75b1054f798a9dec0050b541073d7696bc7b2a/internal/test/builder/infrastructure.go

We have similar CRDs for various contracts, but I think usually providers are just using their own types so not sure if they need generic infra / bootstrap / ... CRDs.

**Comment by dlipovetsky** [comment]
> I'm wondering if something like the CRDs in this file are useful outside of core CAPI: https://github.com/kubernetes-sigs/cluster-api/blob/1b75b1054f798a9dec0050b541073d7696bc7b2a/internal/test/builder/infrastructure.go

Yes, the CRDs in the file are useful, because they are necessary for envtest-based tests.

**Comment by sbueringer** [comment]
@fabriziopandini wdyt?

**Comment by dlipovetsky** [comment]
Thanks for being open to this request :pray: .

I'll file a PR.

/assign
