### ISSUE TITLE
[e2e tests] Make the scaleSpec Public and Add Hook for Reusability

### ISSUE THREAD

**Issue by mboukhalfa** [kubernetes-sigs/cluster-api#11332]
### What would you like to be added (User Story)?

As a CAPM3 tester, I would like to reuse the CAPI scalability test with CAPM3 without duplicating it, similar to how [md_remediation.go](https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/test/e2e/md_remediations_test.go) reused.

### Detailed Description

In order to reuse the `scaleSpec` test we propose the following changes to make the test more flexible and provider-agnostic:

**Export [`scaleSpec`](https://github.com/kubernetes-sigs/cluster-api/blob/0000f09199d77e0bae3852b572ecbe055334334d/test/e2e/scale.go#L145)/[`scaleSpecInput`](https://github.com/kubernetes-sigs/cluster-api/blob/0000f09199d77e0bae3852b572ecbe055334334d/test/e2e/scale.go#L64C6-L64C20):**
        The current `scaleSpec` test function is not accessible outside its package. By exporting it outside the package it will be publicly available and reusable for other providers, such as Metal3 (CAPM3).

**Add a Hook for Post-Cluster Creation Actions**:
        A hook function is needed similar to [`PostNamespaceCreated`](https://github.com/kubernetes-sigs/cluster-api/blob/0000f09199d77e0bae3852b572ecbe055334334d/test/e2e/scale.go#L120) but called after the cluster namespace and name are generated and before applying the template maybe [here](https://github.com/kubernetes-sigs/cluster-api/blob/0000f09199d77e0bae3852b572ecbe055334334d/test/e2e/scale.go#L622). This will allow us to:
        

1. Apply `BareMetalHosts` (`BMHs`) resources in the correct namespace.
2. Call the Fake API Server (FKAS) to retrieve the cluster API endpoints `host` and `port`, and set them in the template placeholders before applying it.

### Anything else you would like to add?

These changes will allow us to align our scalability tests with the existing CAPI tests without duplicating code across projects and extend the use of CAPI’s scalability tests across multiple providers.

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
Feel free to open a PR, then we can discuss the details. In general it's fine

**Comment by mboukhalfa** [comment]
Can you please assign [mquhuy](https://github.com/mquhuy) he will follow up on the issue and the open PR

**Comment by sbueringer** [comment]
I think they can only self-assign. I can only assing org members or folks that already commented on this issue.
