### ISSUE TITLE
cert-manager is always updated 

### ISSUE THREAD

**Issue by faiq** [kubernetes-sigs/cluster-api#11348]
### What steps did you take and what happened?

As cert-manager was updated to version to 1.16.1 in https://github.com/kubernetes-sigs/cluster-api/pull/11322 

A few key changes in the chart make the current code make it so that cert-manager is always upgraded even if it is not necessary.

How to recreate:

1. Create a cluster with kind, or use any kubernetes cluster 
2. Run clusterctl init. This is an example command - 

```shell
clusterctl init --kubeconfig=/path-to-my-kubeconfig --core cluster-api:v1.8.4 --bootstrap kubeadm:v1.8.4 --control-plane kubeadm:v1.8.4 --infrastructure docker:v1.8.4,aws:v2.6.1,nutanix:v1.5.3 --addon helm:v0.2.5 --wait-providers
```

I got logs like this 

```
Fetching providers
Installing cert-manager version="v1.16.0"
Waiting for cert-manager to be available...
Installing provider="cluster-api" version="v1.8.4" targetNamespace="capi-system"
Installing provider="bootstrap-kubeadm" version="v1.8.4" targetNamespace="capi-kubeadm-bootstrap-system"
Installing provider="control-plane-kubeadm" version="v1.8.4" targetNamespace="capi-kubeadm-control-plane-system"
```

3. Run upgrade apply 

```
clusterctl upgrade apply --core cluster-api:v1.8.4 --bootstrap kubeadm:v1.8.4 --control-plane kubeadm:v1.8.4 --infrastructure docker:v1.8.4,aws:v2.6.1,nutanix:v1.5.3 --addon helm:v0.2.5 -v=5 --wait-providers
``` 

I observe that cert-manager is scaled down and recreated even though the same version is to be installed 

Logs from upgrade:

```
No default config file available
Potential override file searchFile="/home/fraza/.config/cluster-api/overrides/cert-manager/v1.16.0/cert-manager.yaml" provider="cert-manager" version="v1.16.0"
Fetching file="cert-manager.yaml" provider="cert-manager" type="" version="v1.16.0"
Checking if cert-manager needs upgrade...
CRD migration check passed CustomResourceDefinition={"name":"certificaterequests.cert-manager.io"}
CRD migration check passed CustomResourceDefinition={"name":"certificates.cert-manager.io"}
CRD migration check passed CustomResourceDefinition={"name":"challenges.acme.cert-manager.io"}
CRD migration check passed CustomResourceDefinition={"name":"clusterissuers.cert-manager.io"}
CRD migration check passed CustomResourceDefinition={"name":"issuers.cert-manager.io"}
CRD migration check passed CustomResourceDefinition={"name":"orders.acme.cert-manager.io"}
Deleting cert-manager version="v1.16.0"
``` 

I believe that this is happening because the leader election namespace is hard coded to `kube-system` in the upstream chart see https://github.com/cert-manager/cert-manager/issues/6716 

When we list objects that belong to the cert-manager deployment we miss these objects  (EDIT because `kube-system` isn't passed in)

https://github.com/kubernetes-sigs/cluster-api/blob/0202f9c6ec3726e775056f6290aff302b6708d4d/cmd/clusterctl/client/cluster/cert_manager.go#L244

and then when we get to this check, we determine an upgrade is needed 

https://github.com/kubernetes-sigs/cluster-api/blob/0202f9c6ec3726e775056f6290aff302b6708d4d/cmd/clusterctl/client/cluster/cert_manager.go#L377

### What did you expect to happen?

I expect cert-manager to not get recreated when the expected version is correct

### Cluster API version

$ clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"", GitTreeState:"", BuildDate:"", GoVersion:"go1.23.2", Compiler:"gc", Platform:"linux/amd64"}

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by neolit123** [comment]
@faiq your observations seem correct to me.
would you like to send PR that amends the code?

**Comment by faiq** [comment]
@neolit123 i'll take a look and see what i can come up with.

**Comment by fabriziopandini** [comment]
I don't have time to look into this ATM 😓 
@neolit123 do you have time to confirm this is an actual issue and to make a first pass at the PR?

**Comment by neolit123** [comment]
> I don't have time to look into this ATM 😓 @neolit123 do you have time to confirm this is an actual issue and to make a first pass at the PR?

i reviewed it already, but i don't have time to confirm locally.
i think the argument in the comment above the code change is valid.

**Comment by sbueringer** [comment]
I would imagine there is a way to confirm via e2e test logs (also that it's fixed).

E.g. the clusterctl upgrade job from v1.8 => main should only install and then not upgrade cert-manager (should be "broken" on main and fixed on the PR)
