### ISSUE TITLE
Provide util function about MachineDeployment to calculate and compare machine-template-hash

### ISSUE THREAD

**Issue by sivchari** [kubernetes-sigs/cluster-api#11358]
### What would you like to be added (User Story)?

As a developer, I'd like to make the util function to calculate machine-template-hash.

### Detailed Description

Currently, We can't calculate machine-template-hash since the util function is located in internal package (e.g. [MachineTemplateDeepCopyRolloutFields](https://github.com/kubernetes-sigs/cluster-api/blob/16232aa3fedd905879305843136b01a6f9076b49/internal/controllers/machinedeployment/mdutil/util.go#L386C6-L386C42) and [Compute](https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/util/hash/hash.go#L30)). 
So if I want to calculate the machine-template-hash, I need to copy the code and use it. But as you can see, these action isn't good for extensibility and maintainability. So I want the public function to solve above scenario.
I think it's okay to make the public function like this in util package.

```go
package hash

import (
	clusterv1 "sigs.k8s.io/cluster-api/api/v1beta1"
	"sigs.k8s.io/cluster-api/internal/controllers/machinedeployment/mdutil"
	internalHash "sigs.k8s.io/cluster-api/internal/util/hash"
)

func ComputeMachineTemplateHash(md *clusterv1.MachineDeployment) (uint32, error) {
	templateHash, err := internalHash.Compute(mdutil.MachineTemplateDeepCopyRolloutFields(&md.Spec.Template))
	if err != nil {
		return 0, err
	}
	return templateHash, nil
}
```

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
Why do you need to calculate the machine-template-hash?

**Comment by sivchari** [comment]
Our team needs to know how many machines is related with MachineSet that MachineDeployment uses now. So, we want to calculate machine-template-hash.

**Comment by sbueringer** [comment]
Is there a reason why you can't use the status fields of the MD?

If you want to identify:
* which MS belong to a MD
* which one is the current / latest MS of an MD

I would recommend using other labels.

Just to avoid confusion, the templateHash that we calculate with this func is not what we use for the label on the MachineSet (we add an additional random suffix).

**Comment by sivchari** [comment]
Thanks for comment. Sorry, we can't use the MachineDeployment status since internal requirement of our team (Of course, it's best decision to use that value).

> If you want to identify:
> - which MS belong to a MD
> - which one is the current / latest MS of a MD

I get your suggestion. However, which label should we use or should we attach the unique label ourself via webhook etc ?

> Just to avoid confusion, the templateHash that we calculate with this func is not what we use for the label on the MachineSet (we add an additional random suffix).

Surely, machine-teplate-hash has a random suffix, but the calculated hash from MachineDeployment's template is contained in the value, isn't it ? Thus, we should be able to identify the current/latest MachineSet if we  use above function.

**Comment by enxebre** [comment]
>Sorry, we can't use the MachineDeployment status since internal requirement of our team

Can you elaborate on why is there a restriction on reading the md.status.udpatedRepliacs? And the on the use case in general so we can reason about the best way to go?

**Comment by sbueringer** [comment]
The revision annotation can be used to figure out which MS is the "current" MachineSet: https://github.com/kubernetes-sigs/cluster-api/blob/f8a2970e9c8516f2c3d5cad4985543314a215a6b/internal/controllers/machineset/machineset_controller.go#L1013-L1018

To figure out which MS belongs to a MD you can use this logic: https://github.com/kubernetes-sigs/cluster-api/blob/24b2644579062ff1286546a395be76e3a6b9ce26/internal/controllers/machinedeployment/machinedeployment_controller.go#L349

Without the adopt part.

**Comment by sivchari** [comment]
Thank you for some advices for me. isCurrentMachineSet's comparison is better for our team.

> I would highly recommend neither messing with nor relying on the machine-template-hash label (I would not consider it a stable API)

Okay, I prefer your thought. So, I use other label and  close  this issue . Thanks.
