### ISSUE TITLE
Unexpected Delete Annotation / Deletion Policy Behavior

### ISSUE THREAD

**Issue by ivelichkovich** [kubernetes-sigs/cluster-api#11387]
### What steps did you take and what happened?

https://github.com/kubernetes-sigs/cluster-api/blob/ce58362fefb10c2c9e462a9a6c850733f4d87161/internal/controllers/machineset/machineset_delete_policy.go#L47

The `newest` and `oldest` delete policies honor the `cluster.x-k8s.io/delete-machine` above unhealthy machines but the `random` delete policy does not. This behavior is unexpected, I'd expect them to honor the annotation the same way.

### What did you expect to happen?

Delete policy of `oldest`, `newest`, `random` doesn't change functionality of `cluster.x-k8s.io/delete-machine` annotation

### Cluster API version

All

### Anything else you would like to add?

(not sure if this is a bug report or feature request)

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
/triage accepted

@ivelichkovich Feel free to open a PR
