### ISSUE TITLE
Document requirements of conformant Infrastructure and Bootstrap providers

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#1138]
#997 introduces Infrastructure and Bootstrap providers. The Cluster API subproject is implementing a [kubeadm Bootstrap provider](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm), but external orgs will implement most Infrastructure providers.

How does a Cluster API end-user evaluate the quality of providers? One way is for Cluster API to write set of conformance tests that providers must pass. Passing providers can call themselves "Cluster API conformant."

To implement the conformance tests, we need to state the requirements.

/priority important/long-term
/cc @vincepri

**Comment by dlipovetsky** [comment]
I'm going to jot down a couple of requirements here. Disclaimer: I haven't proposed these formally, and there's no consensus on them.

1. A conformant provider MUST be able to reconcile objects in the same namespace as other conformant providers.
0. A conformant provider MUST be able to reconcile objects for multiple clusters in the same namespace.
0. A conformant provider MAY be able to reconcile objects in multiple namespaces. There is a security trade-off similar to the one [described here](https://github.com/vincepri/cluster-api/blob/states-preboot-proposal/docs/proposals/20190610-machine-states-preboot-bootstrapping.md#machine-controller-can-access-any-machine-or-cluster-in-any-namespace).

**Comment by detiber** [comment]
Related bootstrap provider documentation issue: https://github.com/kubernetes-sigs/cluster-api/issues/1726
Related machine infrastructure provider documentation issue: https://github.com/kubernetes-sigs/cluster-api/issues/1725
Related cluster infrastructure provider documentation issue: https://github.com/kubernetes-sigs/cluster-api/issues/1724

I believe the above issues and their associated PRs likely handle the main requirements to resolve this issue

**Comment by vincepri** [comment]
The related issues are all closed, and I think we have covered most of this in the book now.

/close
