### ISSUE TITLE
Question: ControlPlane  BootstrapFailed

### ISSUE THREAD

**Issue by h-shihao** [kubernetes-sigs/cluster-api#11427]
### What steps did you take and what happened?

Using the combination of cluster - API and kubeivrt, reference documentation at https://cluster-api.sigs.k8s.io/user/quick-start.

If the kubectl get kubeadmcontrolplane command is executed, the controlplane is abnormal.

See MachinesReady bootstrapfail@machine /testk8s-control-plane-nwn9s.

How should I troubleshoot and solve this problem next?

![image](https://github.com/user-attachments/assets/bdedd8b2-f45d-46be-bc6f-0d4619560172)

Refer to https://cluster-api.sigs.k8s.io/user/troubleshooting to check the/var/log/cloud - init - the output. The log. Found the following error,

2024-11-15 08:04:43,049 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2024-11-15 08:04:43, 052-util. py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from  '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed

![image](https://github.com/user-attachments/assets/55de3934-2533-498a-b99e-5168374c57e9)
Question 1: How do I install the Containerd and kubeadm commands on the VM? Is it configured through cloud-init?

Question 2, kubeadm init need '/ run/kubeadm/kubeadm yaml' file, how to provide the virtual machine?
How should I handle this?

### What did you expect to happen?

Create a k8s on k8s cluster using the cluster api + kubevirt

### Cluster API version

Cluster API version: v1.8.5

### Kubernetes version

Kubernetes version：v1.28.3
kubevirt version: v1.1.0

**Comment by fabriziopandini** [comment]
Cloud init, kubeadm and its prereqs should be added to the image you are using.
Cluster API community uses the [image builder project](https://github.com/kubernetes-sigs/image-builder) to create compliant images, if the images provided by the kubeivrt team are not compliant, probably the best course of action is to create an issue in the kubeivrt provider repo

/close
