### ISSUE TITLE
GCE Machine Deployer Cannot Create/Access GCE VMs

### ISSUE THREAD

**Issue by jessicaochen** [kubernetes-sigs/cluster-api#115]
Deployer succeeds, however no node machines are provisoned. gce-machine-deployer throws a lot of the following error:

Error checking existance of machine instance for machine object gce-master-test1; Get https://www.googleapis.com/compute/v1/projects/jesschen-gke-dev/zones/us-central1-c/instances/gce-master-test1?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o

Assigning to self for initial triage.

**Comment by jessicaochen** [comment]
Issue was introduced somewhere between these two commits:
https://github.com/kubernetes-sigs/cluster-api/commit/3cf25650bdece7f326741f771e31794a484c6966

https://github.com/kubernetes-sigs/cluster-api/commit/a4f58439a3f93d8884e65dd595c0e0f9d6614819

Will try to get a narrower range but it there was a lot going on with the repo moving in that range.

**Comment by jessicaochen** [comment]
As a side note, given how many feature PRs that went in while the deployer was broken, we really need to have automated provisioning tests as presubmits to make sure things do not get broken/have proper testing.

Bump https://github.com/kubernetes-sigs/cluster-api/issues/18

**Comment by krousey** [comment]
This was a result of [this](https://github.com/kubernetes-sigs/cluster-api/commit/262113e72fb0857d5289e5b804a5ee3f639a6ea6#diff-f819d90c5667b689aab84ca0f5f170bd) particular change in the machine templates yaml file. It switched the startup script to one that tried to use kubenet (without appropriate permissions) and broke some of the networking on the master. The old startup script was still there and worked, it was just not maintained as the default one.

This came as a by-product of adding a mapping, and changing the GCEProvider config, and updating the template to match that without carefully considering which script it would map to. The fix to change the template to the old script is already in. https://github.com/kubernetes-sigs/cluster-api/pull/107 aims to get the kubenet script actually working.

**Comment by kcoronado** [comment]
Fixed with #107
