### ISSUE TITLE
Update lodash

### ISSUE THREAD

**Issue by davidewatson** [kubernetes-sigs/cluster-api#1168]
/kind bug

**What steps did you take and what happened:**

According to GitHub `lodash` needed to be updated again:

<img width="1018" alt="Screen Shot 2019-07-17 at 10 10 46 AM" src="https://user-images.githubusercontent.com/11819015/61395845-4004a200-a87b-11e9-8c72-803a1e28cecb.png">

**What did you expect to happen:**

GitHub should be happy.

**Anything else you would like to add:**

This already occurred once before: https://github.com/kubernetes-sigs/cluster-api/pull/578

**Comment by detiber** [comment]
There is an open PR for this here: https://github.com/kubernetes-sigs/cluster-api/pull/1157
