### ISSUE TITLE
sigs.k8s.io redirect isn't working

### ISSUE THREAD

**Issue by kris-nova** [kubernetes-sigs/cluster-api#118]
If you try to load `https://sigs.k8s.io/cluster-api/` it redirects to `https://github.com/kubernetes-sigs/cluster-api/blob/master/` which returns a 404

**Comment by roberthbailey** [comment]
@thockin - do you know where these redirects are configured? I just checked `https://sigs.k8s.io/kubeadm-dind-cluster`

**Comment by rsdcastro** [comment]
Note that https://sigs.k8s.io/cluster-api (no trailing /) redirection works correctly.

**Comment by dims** [comment]
@roberthbailey the redirects are defined in the k/k8s.io repo - https://github.com/kubernetes/k8s.io/search?q=sigs.k8s.io&unscoped_q=sigs.k8s.io

**Comment by nikhita** [comment]
This is fixed in https://github.com/kubernetes/k8s.io/pull/128. Thanks @spangenberg!  :tada: 

Closing.
/close
