### ISSUE TITLE
Improvement in hack files

### ISSUE THREAD

**Issue by prankul88** [kubernetes-sigs/cluster-api#1196]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I was going through the hack files in the repo. I encountered 2 problems./
1. In pin-dependency.sh script there is `source "${KUBE_ROOT}/hack/lib/init.sh"` whereas there is no such folder. Thus it fails.
2. update-bazel.sh script doesnot run from the hack directory which I dont find ideal. It runs from the cluster-api root directory.

**What did you expect to happen:**
I expected them to run without fail from the folder itself.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I wish to take up this issue and wanted some help before.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by vincepri** [comment]
+1 on fixing the first problem you mentioned. I'm not sure what is the issue with `update-bazel.sh`, the `Makefile` runs it as part of generating bazel files.

**Comment by prankul88** [comment]
@vincepri In second problem I feel we should able to run update-bazel file manually too which it fails. Thoughts?
