### ISSUE TITLE
Record events when Machine bootstrap and infra references are deleted

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1199]
/kind feature

**Describe the solution you'd like**
As part of Machine deletion, we should record events when the associated bootstrap and infra resources are completely deleted.

**Anything else you would like to add:**
We may need to add a CAPI finalizer to each bootstrap and infra resource so we can guarantee we see the deletions.

/priority important-soon
/area machine
/milestone v1alpha2

**Comment by ericzhang08** [comment]
Hi @ncdc . I have read the code about Machine Deletion. 
I want to confirm if my understanding is correct.

Do you mean we should add Finalizers for  Bootstrap and InfrastructureRef when Finalizers not exist,  and Delete them  when isDeleteReady function  is true.
```
// isDeleteReady returns an error if any of Boostrap.ConfigRef or InfrastructureRef referenced objects still exists.
func (r *ReconcileMachine) isDeleteReady(ctx context.Context, m *v1alpha2.Machine) error
```

**Comment by ncdc** [comment]
Thinking about this some more, I'm not sure if we need this, or should do this. I was originally thinking it would be nice to have a record of the infra/bootstrap resources being deleted, but I'm no longer sure it makes sense for these to be events. What matters is whether these resources still exist, or not, and the easiest way to check for that is to issue `get` requests and see if they come back as 200s or 404s. I'm quite tempted to close this... Thoughts?

**Comment by ericzhang08** [comment]
Ok,I will find other issues to contribute.
