### ISSUE TITLE
cluster-installer - machine delete should wait for finalizers to finish before returning success

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#12]
_From @ajitak on November 14, 2017 21:45_

When a machine CRD is marked for deletion, finalizers should delete node vm. Cluster installer should wait for finalizers to finish deleting vm whenever delete machine code path is triggered.

_Copied from original issue: kubernetes/kube-deploy#390_

**Comment by rsdcastro** [comment]
_From @ajitak on November 27, 2017 18:50_

Code ref https://github.com/kubernetes/kube-deploy/blob/master/cluster-api/deploy/deploy_helper.go#L192

**Comment by rsdcastro** [comment]
_From @pipejakob on January 3, 2018 19:39_

I had this working a while ago before we froze the prototype code in preparation for the KubeCon event, but it was rolled into work for https://github.com/kubernetes/kube-deploy/issues/355 as well. I still have the code if anyone is interested in referencing it, but it will need a lot of rebasing after the recent refactoring to do proper Machine reconciliation and parallel Machine handling. For now, though, I am unassigning the issue from myself since I am now focused on Istio work.

**Comment by rsdcastro** [comment]
/assign @jessicaochen 

Is this still relevant? If not, can you close it out?

**Comment by k4leung4** [comment]
this is now fixed.
On machine deletion, the machine actuator will delete the underlying machine/vm and only on success will it remove the finalizer. Until the underlying machine/vm is successfully deleted, the machine object is still present.
