### ISSUE TITLE
RFE : Cluster Pivot parameter 

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api#1206]
**Describe the solution you'd like**
As a Kubernetes operator I would like to declaratively state whether or not the management resources should be pivoted to the target cluster from within the cluster spec, e.g. 

```yaml
spec:
  pivot: true
```

Currently today this operation resides within clusterctl and I think this is a layer violation because it should be a declared state of the cluster.  

The purpose of this issue is to sort out the logistical issues associated with making this type of change. 

**Anything else you would like to add:**
xref: https://github.com/timothysc/clusteradm/pull/10#discussion_r307778385 

/kind feature
/cc @rudoi @detiber @ncdc

**Comment by detiber** [comment]
One concern that I have with this is that we would need to have a way to ensure that a managment cluster administrator could disable the ability for users to set/override this value.

**Comment by timothysc** [comment]
> One concern that I have with this is that we would need to have a way to ensure that a managment cluster administrator could disable the ability for users to set/override this value.

Isn't that just an admission control webhook that admins control?

**Comment by detiber** [comment]
@timothysc indeed, but we would need a story and documentation around it.

**Comment by detiber** [comment]
If the cluster-api controllers are in charge of handling the pivoting of resources, then we need to assume that the controllers have knowledge of `clusteradm` and the `clusteradm-operator`.

If there are multiple providers deployed in the original management cluster, then how would the controller know which of the deployed providers need to be deployed on the pivoted cluster?

Do we just assume in this model that we use the same credentials for the pivoted cluster-api and provider components as the original management cluster? Or do we assume that the user deploying the Cluster is also providing credentials to be used for the pivoted cluster?

**Comment by timothysc** [comment]
I'm wondering what the boundary lines really need to be?  

Can we/should we abstract away provider details.

**Comment by timothysc** [comment]
> If there are multiple providers deployed in the original management cluster, then how would the controller know which of the deployed providers need to be deployed on the pivoted cluster? 

By name + label , and it would have to be running with the local kubeconfig available.  Once the kubeconfig is available it should be able todo a label query and xfer those resources.  

Still needs more thought, but I totally think this is possible.

**Comment by timothysc** [comment]
After discussions with @ncdc if we auto-label components, this will be trivial. 

/assign @ncdc 

Happy to close this in favor of a different issue and cross ref where needed.

**Comment by ncdc** [comment]
I don't know that I'd commit to calling it 100% trivial, but it will be easier. It's more that we need to define labeling requirements for providers for any & all resources they create and manage.

**Comment by timothysc** [comment]
Closing this as we have thought about different approach here.
