### ISSUE TITLE
Cannot delete a machine if there is no cluster

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1218]
/kind bug

**What steps did you take and what happened:**
I created a cluster and then a machine and deleted them both. The cluster was deleted and then the machine was unable to delete because it couldn't find the cluster:

```
E0801 14:08:10.060421       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to get cluster \"my-cluster\" for machine \"my-machine\" in namespace           
\"default\": Cluster.cluster.x-k8s.io \"my-cluster\" not found"  "controller"="machine-controller" "request"={"Namespace":"default","Name":"my-machine"}                                                
```

**What did you expect to happen:**
I expect the machine to be deleted.

**Comment by ncdc** [comment]
I'm going to port https://github.com/kubernetes-sigs/cluster-api/pull/1180 to master to fix this
