### ISSUE TITLE
Addresses cannot be empty but are marked optional in the spec

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1221]
/kind bug

**What steps did you take and what happened:**
Addresses on infra machines should be allowed to be empty as not all providers need them or will use them.

**What did you expect to happen:**
I expected not having an "addresses" field to be acceptable.

/lifecycle active
/assign

**Comment by chuckha** [comment]
this is missing a check for ErrNotFound

https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/machine/machine_controller_phases.go#L251

**Comment by vincepri** [comment]
IIRC the check fails on nil slices but not on zero-length ones, you should be able to marshal an empty slice and it should decode it without errors.

**Comment by chuckha** [comment]
That would still require my provider that doesn't need or use an optional field to specify the field in the CRD
