### ISSUE TITLE
GitHub project template for creating a v1alpha2 provider

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api#1245]
/kind feature

**Describe the solution you'd like**
GitHub now allows projects to be created from [templates](https://help.github.com/en/articles/creating-a-repository-from-a-template). In fact, the [kubeadm bootstrap provider](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm) repository was generated from the [Kubernetes template project](https://github.com/kubernetes/kubernetes-template-project).

It would dramatically reduce the barrier to entry when it comes to creating new CAPI providers if there was a `kubernetes-sigs/cluster-api-provider-template-project` repository from which new providers could be generated.

**Comment by timothysc** [comment]
It might make sense to tool wrap kube-builder.

**Comment by vincepri** [comment]
Duplicate of #1113
