### ISSUE TITLE
gcr.io/k8s-cluster-api/cluster-api-controller:v0.1.9 not found

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#1258]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
docker pull gcr.io/k8s-cluster-api/cluster-api-controller:v0.1.9
Error response from daemon: manifest for gcr.io/k8s-cluster-api/cluster-api-controller:v0.1.9 not found

but 
docker pull gcr.io/k8s-cluster-api/cluster-api-controller:v0.1.4
works

root@jj-master:~/go/src/sigs.k8s.io/cluster-api# git tag
0.0.0-alpha.1
0.0.0-alpha.2
0.0.0-alpha.3
0.0.0-alpha.4
0.1.0
0.1.1
0.1.2
0.1.3
v0.1.4
v0.1.5
v0.1.6
v0.1.7
v0.1.8
v0.1.9

we do have v0.1.9 tag

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jichenjc** [comment]
so can we create v0.1.9 or someone point out the images location?

**Comment by detiber** [comment]
@jichenjc we've switched from the previous container registry location to a new one when we adopted the image promoter from wg-k8s-infra. We've also started to put the container image location in the release notes for each release. For v0.1.9 it is: us.gcr.io/k8s-artifacts-prod/cluster-api/cluster-api-controller:v0.1.9

**Comment by jichenjc** [comment]
ok, let me close this , thanks
