### ISSUE TITLE
Status being overwritten in some cases prior to patching status

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#1259]
/kind bug
/priority critical-urgent

**What steps did you take and what happened:**
From raymon on #cluster-api slack:

> i call patch && status.patch like in [aws cluster-api provider close function ](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a86ee59d81c4b1d1b3ee7114fc42231816fd9d7f/pkg/cloud/scope/cluster.go#L138) in my crd controller. i test in my cluster<kubernetes v1.14.4>, and i found the first client.patch will make no change when the patch.Data only contains status change.
>
> what's more, the `typedClient.Patch` function will copy the server response to the obj, thus the `client.Status().Patch` func would not contain any changes because the obj is the same with the early saved patch obj.

Since in the case of a call to `Client.Patch` with only changes to `Status`, the resource passed in will be overwritten by the cached version of the resource, it will result in a noop when calling `Client.Status().Patch` instead of updating the `Status` as we would expect.

To guard against this, we should make a deep copy of the resource before calling `Client.Patch`, and then pass in the deep copy to `Client.Status().Patch` to ensure that we persist the `Status` in all cases.

This will require updates to all places where we are updating resources in cluster-api, but also in all v1alpha2 providers.

**Environment:**
- Cluster-api version: latest/v1alpha2
- Kubernetes version: (use `kubectl version`): v1.14.4

**Comment by chuckha** [comment]
Ahh ok, I traced the code and understand now:

https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/typed_client.go#L132

This would be the line causing the unexpected behavior.

Agreed with the provided solution. Make a deep copy before calling .Patch with the current object then use the deep copy in the .Status().Patch call along with the original copied object.

For a concrete example:
The original object:
https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/cluster_controller.go#L88
Deep copy before here:
https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/cluster_controller.go#L92
Use that deep copy here:
https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/cluster_controller.go#L99

**Comment by chuckha** [comment]
Actually I think I just hit this bug so..

/lifecycle assign

**Comment by DirectXMan12** [comment]
We can't be certain that a given endpoint will overwrite status.  There's nothing that advertises it in discovery.  It's a hidden "feature".

**Comment by chuckha** [comment]
This is closed with #1261
