### ISSUE TITLE
Add util func for generating kubeconfig secret name

### ISSUE THREAD

**Issue by dennisme** [kubernetes-sigs/cluster-api#1266]
/kind feature
/assign
/good-first-issue

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
In the review of https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/136 @detiber suggested that we add a method to the `utill` package to generate the kubeconfig secret name as it will be used other places in the ecosystem.

See https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/136#discussion_r314444351 for details. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by joonas** [comment]
I have a pretty good idea of what we want to do here, so I can go ahead and take this one
