### ISSUE TITLE
Move RBAC kubebuilder rules in each respective controller

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1272]
/kind feature

**Describe the solution you'd like**
RBAC kubebuilder rules from `controllers/doc.go` should be moved to each respective `*_controller.go` file based on what the controller actually needs access to.

/help
/good-first-issue

**Comment by Xenwar** [comment]
I am interested in working on this issue. Would it be possible to take it ?

**Comment by dongwangdw** [comment]
Is there any background on this issue?
As I see from doc.go, there is one line and others are all commented lines.
Are these commented lines are the rules? Is there any doc about them so that I can understand more about them?

**Comment by detiber** [comment]
The RBAC rules are generated using the annotations in the commented lines

The Kubebuilder Book should have some documentation on the annotations: https://book.kubebuilder.io/

**Comment by dongwangdw** [comment]
@detiber 
thanks here is the link. https://book.kubebuilder.io/reference/markers/rbac.html

As Xenware got this. I hope this would help.
