### ISSUE TITLE
Cluster Controller should create kubeconfig Secret for remote clusters

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#1274]
/kind feature

**Describe the solution you'd like**
in v1alpha2, cluster controller should take care of creating the config map with the kubeconfig for accessing remote clusters before setting the BootstrapReady annotation.

At this stage, all the required certificates should exist as secrets in the management cluster, and the Cluster.Status.APIEnpoints list should contain the control plane endpoint 

**Anything else you would like to add:**
We want to avoid that creating kubeconfig Secret for the remote cluster is a task for all the infrastructure providers, so IMO CAPI is the best candidate...

/cc @akutz @detiber

**Comment by rudoi** [comment]
CABPK creates a secret containing the kubeconfig. Is this meant to be something different?

**Comment by vincepri** [comment]
Long term, the kubeconfig creation can be made in CAPI, but only if there is enough standards/conventions that we can follow to get the necessary information to generate it (apiendpoints, certificates, and so on). 

If we can align on how to get those information, the feature can move to Cluster API easily.

**Comment by fabriziopandini** [comment]
> CABPK creates a secret containing the kubeconfig. Is this meant to be something different

@rudoi, it is the same, but the current implementation assumes controlplaneEndpoint is known before creating the cloud-config for kubeadm init, but this is not always the case (e.g. CAPV). 
This is why we should move this out of CAPBK. 

> If we can align on how to get that information, the feature can move to Cluster API easily.

I agree. 
apiendpoints are already part of the API, and there is already utils for remote config management. 
The last bit is certificates, but there is work ongoing here as well (see e.g. https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/74)

**Comment by dennisme** [comment]
Do we want to make a meeting topic for Wednesday? If we decide on something I am happy to cleanup my mess :)

**Comment by akutz** [comment]
If we do then I will be there to explain CAPV's side of things. The tl;dr is that vSphere doesn't have a built-in LB solution, so fun work-arounds are necessary :(

**Comment by fabriziopandini** [comment]
I think there are some more things to be considered...
E.g a kubeconfig file is required to set NodeRef, and this should happen before boostrapReady is set at cluster level

**Comment by kanwar-saad** [comment]
There are two secrets in CAPBPK; <cluster-name>-certs and <cluster-name>-kubeconfig. Does this mean to move both to CAPI since they are related or just kubeconfig one?

**Comment by detiber** [comment]
Just the Kubeconfig one
