### ISSUE TITLE
kubectl scale doesn't work on v1a2 machinedeployments

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api#1279]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Created a MachineDeployment, nodes are all fine. 

Then:
```
kubectl scale machinedeployments.cluster.x-k8s.io --replicas 2 rudeboy-pizzatown-nodes                                                                      
The machinedeployments "rudeboy-pizzatown-nodes" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```

**What did you expect to happen:**
MachineDeployment successfully scaled to 2.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by vincepri** [comment]
@rudoi Would you be able to check if this issue still occurs after this PR? https://github.com/kubernetes-sigs/cluster-api/pull/1281/files

**Comment by ncdc** [comment]
Should be fixed by #1281. Please reopen if it's still not working.
/close

**Comment by rudoi** [comment]
/reopen 

something is up with resource version:
```
k scale --replicas=2 machinedeployments/mytu-nodes --resource-version='16871'
machinedeployment.cluster.x-k8s.io/mytu-nodes scaled
```

^ this works, but without it it says `invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update`

**Comment by ncdc** [comment]
@rudoi the resourceVersion 0x0 error is a kubernetes bug: https://github.com/kubernetes/kubernetes/issues/80515. Is it ok to close this since it's not a cluster-api issue?

**Comment by rudoi** [comment]
darn! yep, no problem.

/close
