### ISSUE TITLE
GCP deployer support for different versions of Docker

### ISSUE THREAD

**Issue by kawych** [kubernetes-sigs/cluster-api#129]
Currently gcp-deployer supports only Docker 1.12.0. I've tried to set it up to run with Docker 17.03.2-ce and identified several places that need to be fixed:

1) Remove legacy check for 1.12.0 - issued PR #128
2) Update `apt-get install` command here: https://github.com/kubernetes-sigs/cluster-api/blob/ec53b5b32946270f48f382e7295c631fac530623/gcp-deployer/machine_setup_configs.yaml#L35 to specify Docker version provided in machines.yaml file instead of default one. This requires also different apt-get repositories setup, similar to https://github.com/kubernetes-sigs/cluster-api/blob/ec53b5b32946270f48f382e7295c631fac530623/gcp-deployer/machine_setup_configs.yaml#L136
3) For docker 17.03.2-ce, Docker options specified here are not passed correctly to the daemon: https://github.com/kubernetes-sigs/cluster-api/blob/ec53b5b32946270f48f382e7295c631fac530623/gcp-deployer/machine_setup_configs.yaml#L36, this also needs to be resolved

This will probably need to be done for terraform deployer as well.

cc @krousey @jessicaochen

**Comment by roberthbailey** [comment]
gcp-deployer is gone. If this is still an issue with clusterctl on GCP, please open an issue in https://github.com/kubernetes-sigs/cluster-api-provider-gcp. 

/close
