### ISSUE TITLE
Ensure proper handling of ErrorMessage/ErrorReason for referenced resources

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#1294]
/kind feature

**Describe the solution you'd like**
Ensure that we are properly checking a referenced resource for ErrorMessage/ErrorReason for referenced resources. If they are present, then we should not attempt to use data from those resources and we should propagate a summary to the user via our ErrorMessage/ErrorReason pointing the user to the resource(s) with ErrorMessage/ErrorReason set.

/priority important-soon
/milestone v1alpha2

**Comment by vincepri** [comment]
This should be already implemented as described, `reconcileExternal` method in cluster and machine controllers sync the errors back with the main resources.

**Comment by vincepri** [comment]
https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/machine_controller_phases.go#L156-L167

**Comment by detiber** [comment]
@vincepri looking at the linked code, it just copies the ErrorMessage/ErrorReason from the external resource, it doesn't give any additional context to the user

**Comment by vincepri** [comment]
@detiber Is this something we might want to look soon-ish or should we close it in favor of #1658 ?

**Comment by detiber** [comment]
/close
closing in favor of #1658
