### ISSUE TITLE
Bot for stale vendored cluster API 

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#13]
_From @jessicaochen on January 3, 2018 19:20_

Create a robot that will warn when the vendored cluster API is falling behind master.

Context:
On creation of cluster-api-gcp, there was a discussion on whether we were going to vendor the cluster-api or directly reference it. We decided to vendor it so it would be a better example of the right pattern to folks attempting to make their own machine controller. The downside to this is that the vendored cluster-api could fall behind the latest cluster-api. A robot warning about falling behind was the suggested mitigation.
 

_Copied from original issue: kubernetes/kube-deploy#471_

**Comment by justinsb** [comment]
Another thing this could do: automatically send PRs for out of date docker base images.

**Comment by justinsb** [comment]
I've started on this ... a PR that is created by my WIP script https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/33

(I'm trying to figure out how this should behave in general - feedback welcome)

**Comment by ncdc** [comment]
I don't believe we need to automate updating a repo's vendoring of cluster-api. I suggest we close this issue. WDYT?

**Comment by ncdc** [comment]
As suggested by @dhellmann, I'm going to close and we can always reopen issues if needed.

/close
