### ISSUE TITLE
[0.1] Add concurrency support for MachineSet, MachineDeployment controllers

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1303]
/kind feature

**Describe the solution you'd like**
#1302 added support for controlling the concurrency of the cluster and machine controllers. We should add eventually support for the MachineDeployment and MachineSet controllers too.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by prankul88** [comment]
Hi @ncdc ,I can like to take up this issue if you are okay with it.

**Comment by timothysc** [comment]
@ncdc Move to close this issue as v1alpha2 is out, providers are transitioning and this would be a feature back-port.

**Comment by ncdc** [comment]
/close

On Sep 25, 2019, at 12:16 PM, Timothy St. Clair <notifications@github.com> wrote:

﻿

@ncdc<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fncdc&data=02%7C01%7Cgoldsteina%40vmware.com%7C088c2a75f7f54f01b06408d741d3a73f%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637050249612547637&sdata=FEc%2BL17%2FvkytwBf96tCJGnrW5CG9GFUBskeKTPgaPa0%3D&reserved=0> Move to close this issue as v1alpha2 is out, providers are transitioning and this would be a feature back-port.
