### ISSUE TITLE
Add utility function for getting and extracting the cluster kubeconfig

### ISSUE THREAD

**Issue by joonas** [kubernetes-sigs/cluster-api#1306]
**Describe the solution you'd like**

As a follow-up to [#1301 (comment)](https://github.com/kubernetes-sigs/cluster-api/pull/1301#discussion_r316740315), it was suggested that the functionality in [clusterclient](https://github.com/kubernetes-sigs/cluster-api/blob/b7b6070a10d689f77b135993c858b688e31600ba/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go#L169-L178) for getting and extracting a kubeconfig for given cluster were made available in [`util/kubeconfig/kubeconfig.go`](https://github.com/kubernetes-sigs/cluster-api/blob/b7b6070a10d689f77b135993c858b688e31600ba/util/kubeconfig/kubeconfig.go).

Naming-wise this could be called something like `Fetch`, but that's left up to the implementer.

**Anything else you would like to add:**

/kind feature

**Comment by prankul88** [comment]
If no one has taken this up yet, I would like to work on this issue. I have recently started contributing and this might be a good issue to get started.

**Comment by kashifest** [comment]
I would be interested to work on this issue. I would like to take it if it is ok with others.

**Comment by ncdc** [comment]
@prankul88 would you want to pair with @kashifest on this?

**Comment by prankul88** [comment]
@ncdc Sure I will :) Thanks

**Comment by kashifest** [comment]
Thanks @ncdc, me and @prankul88  have started working on it!

**Comment by kashifest** [comment]
@joonas  and @vincepri . We have a question.  From the issue description and discussion in #1301  what we understand that the ' GetKubeconfigFromSecret' method should be also inside 'kubeconfig.go'.   That means the same method will be in two places?

**Comment by kashifest** [comment]
Thanks for the clarification @detiber

**Comment by joonas** [comment]
@kashifest you'll also want to make sure that your pull request has this the master branch of this repository as the base so that it can be merged to the correct repository.
