### ISSUE TITLE
Investigate controllers flaky tests

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1315]
/kind bug

**What steps did you take and what happened:**
Our current tests use controller-runtime `testenv` to spin up a local API Server and test against it. After moving to Kubebuilder v2, all controllers are now running at the same time, every now and then, MachineDeployment and MachineSet tests fail and we need to reissue a `/retest`.

/help
/priority important-longterm

**Comment by ncdc** [comment]
Closing this in favor of #1377 
/close
