### ISSUE TITLE
[0.1] Pivot kubeconfig secrets

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1316]
/kind feature

**Describe the solution you'd like**
Currently if any KubeConfig secrets are created pre-pivot, these secrets must be recreated post-pivot since the secrets are not moved as part of the pivot. I'd like to see the secrets moved as part of the pivot in order to simplify the post-pivot edge cases.

**Comment by tahsinrahman** [comment]
Don't we need the same for other releases?

**Comment by detiber** [comment]
This should already be the case for v0.2.x
/close
