### ISSUE TITLE
Set up firewall rules for cluster in GCP deployer

### ISSUE THREAD

**Issue by kawych** [kubernetes-sigs/cluster-api#132]
In clusters created with GCP deployer, pods can't connect to ports exposed by Kubelet on other nodes. For my cluster "test1" I worked it around adding a firewall rule:
```
Targets: test1-worker
Source IP ranges: 192.168.1.0/24, 192.168.0.0/24
Protocols: tcp
Action: ALLOW
```
192.168.1.0/24, 192.168.0.0/24 are IP ranges of pods in my cluster.

cc @karan @krousey

**Comment by spew** [comment]
Taking a look at fixing this one.

**Comment by spew** [comment]
I have reproduced this issue, there is active work going on in this area by @mkjelland

**Comment by kawych** [comment]
@spew @mkjelland 

This is not fixed yet. The firewall rule added in #352 enables communication between cluster nodes, but does not allow connections from pods running on a cluster to ports exposed from other nodes.

**Comment by spew** [comment]
@mkjelland can you take a look at this one?

**Comment by mkjelland** [comment]
/reopen
I'll take another look, thanks!

**Comment by roberthbailey** [comment]
@kawych - is this relevant to the google provider in clusterctl? The gcp deployer code is going away prior to the alpha release of the cluster api.

**Comment by roberthbailey** [comment]
Manually moved to https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/70.
