### ISSUE TITLE
Avoid patching Cluster object in Machine Controller

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1333]
/kind cleanup

**Describe the solution you'd like**
Currently, when the Machine controller sees the first control plane machine with a reference, we call the MachineReconciler's `reconcileClusterStatus` method to set the Status.ControlPlaneInitialized field to true. 

Long term, this logic should move to the Cluster reconciler, which will need to watch and retrieve its Machines before being able to set the field.

**Comment by tahsinrahman** [comment]
@vincepri if you're not working on this, can i take this? thanks!

**Comment by vincepri** [comment]
Go for it!
