### ISSUE TITLE
Deleting a Cluster does not delete related MachineDeployments

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#1349]
/kind bug

**What steps did you take and what happened:**
Deleting a Cluster does not clean up related MachineDeployments

**What did you expect to happen:**
Any MachineDeployments related to a Cluster be deleted when the Cluster is deleted

**Additional Information**
It appears that we were previously only patching Status for MachineDeployments, so the OwnerRef change was never committed back to the API Server. However, because of the lack of guarantees around how the patch semantics work with the controller-runtime client, we also need to be careful not to assume that we can just patch the resource or status for an object and have other pending changes not be overwritten.

**Environment:**

- Cluster-api version: latest from master

**Comment by ncdc** [comment]
@detiber when you have a few minutes, would you please update the description for this issue with the results of your findings? I was trying to page #1380 and this back into memory, and having more information here would be useful. Thanks!
