### ISSUE TITLE
MachineDeployment with more than 0 replicas appears to delete its own MachineSet and not create another one

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api#1366]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Create v1a2 cluster with 3 controlplane machines and 12 machinedeployments. 

Consider the following set of machinedeployments:
```
cluster-nodes-0
cluster-nodes-1
cluster-nodes-2
...
cluster-nodes-11
```

This creates MachineSets:
```
cluster-nodes-0-abc
cluster-nodes-1-def
etc
```

Several days later I noticed that any MachineDeployment with replicas > 0 has had its MachineSet deleted and not replaced. 

**What did you expect to happen:**
MachineSets to not be mysteriously deleted.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This happened on three separate clusters. The time between creation and deletion has varied, and I have not been able to reproduce in isolation (I have created a cluster and will check it regularly...)

I am continuing to investigate and will add comments as I find new stuff.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by rudoi** [comment]
OK i'm in an interesting state on my new cluster:

MachineDeployment status:
```
status:
  observedGeneration: 3
  unavailableReplicas: 1
```

MachineSet's ownerRef seems to be wrong:
```
- apiVersion: cluster.x-k8s.io/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: MachineSet
    name: ar1a-nodes-0
    uid: d63b12a0-3a99-4df5-b3c8-0ab092caf00f
```

**Comment by rudoi** [comment]
https://github.com/kubernetes-sigs/cluster-api/blob/c4b86d69d8b504aefb40cf28f706cde6762998b3/controllers/machinedeployment_sync.go#L149

This sets the ownerRef to a MachineSet. Shouldn't this be MachineDeployment?

**Comment by vincepri** [comment]
It should be

/lifecycle active
