### ISSUE TITLE
docs/book: Quick Start 

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1369]
/kind documentation

**Describe the solution you'd like**
The book needs a quickstart tutorial to go from zero to Kubernetes using AWS and Kubeadm providers.

**Comment by detiber** [comment]
IMO, this should live in CAPA and not here. I think it makes sense for us to reference the CAPA docs, but we shouldn't be maintaining CAPA docs in this repo.

**Comment by ncdc** [comment]
Let's make sure each provider has a quick start/getting started tutorial in a consistent location in each repo.

**Comment by ncdc** [comment]
TODO: transfer to CAPA or close & recreate in CAPA
