### ISSUE TITLE
docs/book: Document controllers and their flow

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1370]
/kind documentation

**Describe the solution you'd like**
To have a good amount of documentation for v1alpha2, we should document what each controller does, their contracts and link to the code wherever possible.

**Comment by moshloop** [comment]
I think this potentially needs to be split into 2 (with some overlapping content).

1) Document the controllers and state machines from the perspective of users to aid in troubleshooting
2) Document from a CAPI developers perspective to aid in working on  new/existing providers

**Comment by vincepri** [comment]
I'm fine with that, @chuckha has started working on some parts of this in the linked PRs

**Comment by randomvariable** [comment]
/assign 
I can be the test subject

**Comment by ncdc** [comment]
/milestone v0.3.0

Trying to keep only the bare minimum in v0.2.x so we can eventually close it out

**Comment by ncdc** [comment]
Looks like we have most or all of these documented. Let's open up specific issues in the future if needed.

/close
