### ISSUE TITLE
docs/book: Clusterctl

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1372]
/kind documentation

**Describe the solution you'd like**
The current [clusterctl document](https://github.com/kubernetes-sigs/cluster-api/blob/9e748f6e18444a2901d722dd0c6e7b002c68e58f/docs/how-to-use-clusterctl.md) is not in the book. We should try to port the current document and make the necessary adjustments where needed.

**Comment by kikisdeliveryservice** [comment]
hi, do you mind if i give this a try?

**Comment by vincepri** [comment]
@kikisdeliveryservice That sounds good! The content should be ported here https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/tooling/clusterctl.md within the book :)
