### ISSUE TITLE
Makefile: move target comments above target names

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1374]
/kind cleanup

**Describe the solution you'd like**
Instead of having a make target like this:
```
.PHONY: generate-manifests
generate-manifests: $(CONTROLLER_GEN) ## Generate manifests e.g. CRD, RBAC etc.
```

I would prefer it to be formatted like this:
```
 ## Generate manifests e.g. CRD, RBAC etc.
.PHONY: generate-manifests
generate-manifests: $(CONTROLLER_GEN)
```

IMHO, this makes it easier to read, especially if a target has dependencies.

/help
/good-first-issue
/priority important-longterm
/milestone Next

**Comment by vincepri** [comment]
FYI, This breaks the `make help` target

**Comment by ncdc** [comment]
So it does. I guess I can live with it 😄 
/close
