### ISSUE TITLE
MachineReconciler: make Client a proper field

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1382]
We are trying to be explicit when we invoke methods on the embedded Client field (Get/Patch/Delete/etc). Let's make client.Client a proper field.

/kind cleanup
/good-first-issue
/help
/milestone Next
/priority important-longterm

**Comment by vincepri** [comment]
Might be worthwhile to note that this is the pattern we have from kubebuilder, maybe we should open an issue there as well to make its own field?

**Comment by ncdc** [comment]
We can, but I assume they had a reason for making it embedded. To me, if you have an embedded field, it's because you want indirect access to the embedded type's fields or methods (i.e. `r.Get()` instead of `r.Client.Get()`).

It sounded to me like there is a desire to be explicit (`r.Client.Get()`), and if we want to go with that convention, then I would prefer to disallow the embedding here.

**Comment by vincepri** [comment]
I'm a big +1 for being explicit
