### ISSUE TITLE
A redundant owner reference check

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1389]
/kind cleanup
/priority backlog

https://github.com/kubernetes-sigs/cluster-api/blob/203d8f7d66b2a9058012a10fb08e69eaafe11dcb/controllers/cluster_controller_phases.go#L91-L98

The if check could be removed to simplify code since the ensureOwnerRef function will not add a second owner ref if it already exists which would make the Patch a no-op. 

However if this was added for performance reasons then we should add a comment stating such but I don't believe any performance tests have been run or at least published publicly.

**Comment by alejandrox1** [comment]
would like to take a look at this one :eyes:

**Comment by detiber** [comment]
/assign @alejandrox1 
It's yours :)

**Comment by detiber** [comment]
Just set `/lifecycle active` when you start working on it to let others know it's being worked on :)

**Comment by alejandrox1** [comment]
:nerd_face: 
/lifecycle active
