### ISSUE TITLE
machine should not stay in running phase after the infra obj been deleted

### ISSUE THREAD

**Issue by xrmzju** [kubernetes-sigs/cluster-api#1398]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
after machine turns into running phase, i delete the infra object and machine controller watches the event but only logs about the infra obj not found err, and stays in running phase

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by kashifest** [comment]
I want to take this task if no one else is looking into it

**Comment by kashifest** [comment]
What is the expectation here?

**Comment by ncdc** [comment]
If `Machine.Status.InfrastructureReady` is true and we get a 404 not found back from the call to `r.reconcileExternal` from within `reconcileInfrastructure`, we probably need to set `Machine.Status.ErrorReason` and `ErrorMessage`. WDYT @vincepri?

**Comment by vincepri** [comment]
That's what I would expect as well

**Comment by kashifest** [comment]
Ok Thanks for the information. I am working on it
