### ISSUE TITLE
ClusterClient should return controller-runtime client not static client

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1407]
/kind feature

**Describe the solution you'd like**
It would be nice if ClusterClient was actually just controller-runtime's client. 

**Anything else you would like to add:**
I think ClusterClient can go away in favor of client.Client.

Unless there is some reason we're using the typed client, of course.

**Comment by ncdc** [comment]
+1 to removing ClusterClient

**Comment by chuckha** [comment]
I'm gonna grab this as it's blocking some work on cabpk side

/assign
/lifecycle active

**Comment by ncdc** [comment]
FWIW, I thought you were referring to `cmd/clusterctl/clusterdeployer/clusterclient` so I was kinda surprised when the PR was as small as it was 😁

**Comment by chuckha** [comment]
ah, yes, that one will have to wait i'm afraid

**Comment by akutz** [comment]
Hi @andrewsykim,

Please take note of this issue as it will affect a lot of the code you're writing in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/502.

**Comment by ncdc** [comment]
@chuckha says he doesn't need to make this change any more.
/close
