### ISSUE TITLE
Add `cloud provider` project to the dependency list in the document

### ISSUE THREAD

**Issue by zdyxry** [kubernetes-sigs/cluster-api#1412]
/kind feature

**Describe the solution you'd like**

When I try to implement cluster-api-provider v1alpha2, I find that depend on the `cloud provider` project when deploying the target node(It will automatically set the providerID for the next steps). Maybe we should explicitly declare this in the documentation.

**Comment by ncdc** [comment]
@zdyxry thanks for filing this. There is no `cloud provider` project per se. But we do have a requirement/expectation that a `Node` must have its `spec.providerID` filled in, and it must match the value in the `Machine`.

I think we need to find a way to document the specifications/requirements/expectations of the entire ecosystem as it relates to Cluster API. I'm not sure exactly where that goes, though.

/kind documentation
/remove-kind feature
/milestone Next
/priority important-soon

**Comment by vincepri** [comment]
This seems to be a documentation issue that should be covered in in https://master.cluster-api.sigs.k8s.io/architecture/controllers/machine.html#required-status-fields-1

**Comment by zdyxry** [comment]
yes, I will close this issue.
