### ISSUE TITLE
Verify go modules in CI 

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1419]
/kind feature

**Describe the solution you'd like**
As part of our `make verify` target, we should add another scripts that calls `make modules` and checks if there are any changes.

/help
/good-first-issue

**Comment by ncdc** [comment]
We recently merged https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1131 for CAPA - @pjot726 if you're still interested, could you copy that over to here?

**Comment by ncdc** [comment]
Or please let us know if you won't have time to work on this.

**Comment by pjot726** [comment]
@ncdc I don't think I'll be able to work on this for a while, sorry. Feel free to reassign the issue.
