### ISSUE TITLE
Document image building process 

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1421]
/kind documentation

**Describe the solution you'd like**
We need a document in the current book to describe how to build images, add new images using the [image-builder](https://github.com/kubernetes-sigs/image-builder). 

The document should contain instructions to build images for AWS, vSphere (OVAs), and GCP. These can be tackled separately so we can have some fast iteration on these bits.

**Comment by timothysc** [comment]
It should not really live here but link to the image builder repo whose docs need to be updated.

**Comment by ncdc** [comment]
/milestone v0.3.0

Trying to keep only the bare minimum in v0.2.x so we can eventually close it out

**Comment by ncdc** [comment]
Need to link to image builder docs, then we can close

**Comment by vincepri** [comment]
@detiber do you have the new url that we need to link to?
