### ISSUE TITLE
Add deprecation message to each clusterctl command

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1423]
/kind documentation

**Describe the solution you'd like**
We should add a warning/deprecation message to the clusterctl CLI. The message should display before every command, and maybe we can add a 2-5s delay before continuing.

**Comment by wfernandes** [comment]
Hey @vincepri. I'm new to Cluster API but want to start contributing to the project. This seems like a good first issue.
Did you have an appropriate deprecation message in mind?

I was thinking of using the [`Deprecated` property](https://github.com/spf13/cobra/blob/19cf35ea77e5981f8e8b90a897af621f2be864f6/command.go#L75) on each `cobra.Command` to inform users about the tool's deprecation.

**Comment by vincepri** [comment]
That sounds like a really good approach!

Feel free to self-assign this issue and mark it with `/lifecycle active` when you start working on it :)

/help
/good-first-issue
/milestone v0.2.x
/priority important-longterm
/area clusterctl

**Comment by wfernandes** [comment]
@vincepri Thanks! Since the entire clusterctl tool is planned on being deprecated I'll specify the following generic message for each command: 

**This utility has been deprecated in v1alpha2 and will be removed in a future version.**

/assign
