### ISSUE TITLE
Please add a version command for clusterctl

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api#1427]
/kind feature

**Describe the solution you'd like**
When submitting a bug report for one of the cluster api providers I wanted to provide the best information to recreate the issue I am experiencing, so I wanted to quickly provide when and what commit or tag my `clusterctl` command was built from.  Except that's not really easy to do right now.

**Comment by aaroniscode** [comment]
@fabriziopandini Do you mind if I work on this?

**Comment by fabriziopandini** [comment]
fixed by https://github.com/kubernetes-sigs/cluster-api/pull/2061
/close
