### ISSUE TITLE
pivot fails due to secret's empty owner reference UID

### ISSUE THREAD

**Issue by jdef** [kubernetes-sigs/cluster-api#1428]
/kind bug

**What steps did you take and what happened:**

attempted to pivot from a KIND cluster to a GCP cluster, failed due to (I think) the recently applied patch #1411 (see https://github.com/kubernetes-sigs/cluster-api/pull/1411#issuecomment-533288562)

**What did you expect to happen:**

99% of the pivot to succeed, like it did a few days ago

**Anything else you would like to add:**

CAP/GCP provider is built from master, today

**Environment:**

- Cluster-api version: v1alph2 (HEAD: 44491e485ce206f8e5203f858e9f8672b0763168)
- Minikube/KIND version: 0.5.x
- Kubernetes version: (use `kubectl version`): 1.15.3
- OS (e.g. from `/etc/os-release`): mixed

**Comment by jdef** [comment]
cc @ncdc @vincepri

**Comment by andrewsykim** [comment]
Seeing the same issue with CAPV
```
F0923 18:19:49.673318    2684 create_cluster.go:59] unable to pivot cluster api stack to target cluster: unable to pivot cluster API objects: Failed to move cluster: default/management-cluster: failed to move Secrets for Cluster default/management-cluster to target cluster: failed to move Secret default/management-cluster-ca: error copying Secret default/management-cluster-ca to target cluster: error creating Secret default/management-cluster-ca: Secret "management-cluster-ca" is invalid: metadata.ownerReferences.uid: Invalid value: "": uid must not be empty
```

cc @akutz

**Comment by andrewsykim** [comment]
I can try to tackle this one 

/assign

**Comment by vincepri** [comment]
@andrewsykim Check with @tahsinrahman which self-assigned the issue first to make sure we're not duplicating work, also please use `/lifecycle active` when you start working on a particular issue.

**Comment by andrewsykim** [comment]
Oops! missed that @tahsinrahman was already assigned! Happy to fix this one if you haven't started work on it @tahsinrahman, let me know :)

**Comment by tahsinrahman** [comment]
@andrewsykim sure :smile: /unassign

**Comment by tahsinrahman** [comment]
@andrewsykim sure smile 
/unassign
