### ISSUE TITLE
Godoc for the api types need curation

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api#1441]
When parsing the API via godoc which is the standard consumption model for most Go developers, it's in a very bad state to the point of being illegible.  This should be the canonical source of truth that developers should be able to reference when trying to understand the API and it's behaviors.  

https://godoc.org/github.com/kubernetes-sigs/cluster-api/api/v1alpha2

**Comment by rudoi** [comment]
@randomvariable FYI the first thing I'm taking a look at is how to fix up those conversion functions that were generated and exported. So ugly :(

**Comment by ncdc** [comment]
/milestone v0.3.0

Trying to keep only the bare minimum in v0.2.x so we can eventually close it out

**Comment by vincepri** [comment]
going to close this as it's more an ongoing issue and it should probably be tackled with linters and during reviews, feel free to reopen if necessary

/close
