### ISSUE TITLE
Link MachineSets/MachineDeployments to their Cluster via both Labels and OwnerReferences

### ISSUE THREAD

**Issue by dgoodwin** [kubernetes-sigs/cluster-api#145]
Owner references were added to Machines created via a MachineSet in https://github.com/kubernetes-sigs/cluster-api/pull/108

However as it stands today there is no established link required between MachineSet and it's Cluster. Similar for MachineDeployment.

Would it be reasonable to implement two links:

1. Require (via validation) a label linking MachineSet / MachineDeployment to a Cluster, and Machine to it's MachineSet as well as it's Cluster. This would be useful for querying in a multi-tenant environment where there are multiple Clusters even in a single namespace. During validation the Cluster does not have to exist, the label must simply be set.
1. Controllers set OwnerReference on MachineSet + Deployment as soon as the Cluster linked in the now manadatory label exists. This would allow for the same cascading deletion we implemented for MachineSet -> Machine.

All of this is possible to add-on but we were wondering if this makes sense for the core of cluster-api?

**Comment by staebler** [comment]
I do not think that adding an OwnerReference to the Cluster on the MachineSet makes sense. Since the user is required to create both the Cluster and the MachineSets, it seems to me that it would be unexpected behavior to a user if the MachineSets were deleted when the Cluster was deleted.

**Comment by staebler** [comment]
Does anybody have any opinions on whether a `LocalObjectReference` in the spec of MachineSet that points to the Cluster would be better than a cluster-name label on the MachineSet?

**Comment by roberthbailey** [comment]
Closing in favor of https://github.com/kubernetes-sigs/cluster-api/issues/41. 

/close
