### ISSUE TITLE
Broken links in CRD documentation

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#1461]
**What steps did you take and what happened:**
Navigated to the links and it took me to a 404.
For example, https://git.k8s.io/community/contributors/devel/api-conventions.md#idempotency

**What did you expect to happen:**
Take me to the correct documentation.
https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency

**Anything else you would like to add:**
https://github.com/kubernetes-sigs/cluster-api/blob/16a5738adc030a890481b715d305729e521d853d/api/v1alpha2/machineset_types.go#L69

**Comment by wfernandes** [comment]
If this issue is valid, I can have a PR ready soon.

**Comment by ncdc** [comment]
Hi @wfernandes, thanks for filing. I'd suggest we change the title to indicate that there are broken links (we normally use "fix" in PR titles). Does that work for you?

**Comment by wfernandes** [comment]
@ncdc Apologies. For some reason, after I updated the title the bot added the "kind/bug" label again. I removed the annotation from the initial comment.

**Comment by ncdc** [comment]
No worries, thanks for changing it!
