### ISSUE TITLE
How about commit `vendor` to this repo

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#1468]
For some offline build or some machines under firewall, the build will be failed, how about commit `vendor` as well into this repo?

/cc @vincepri @detiber

**Comment by ncdc** [comment]
We previously had the vendored code committed to the repository, but decided instead to omit it. Does your organization have access to a go proxy that you could use behind your firewall?

**Comment by gyliu513** [comment]
@ncdc Yes, we do have a proxy, but the proxy sometimes does not work, and we need to switch to some new proxies, adding vendor would facilitate the development work a lot if proxy does not work.

**Comment by ncdc** [comment]
/assign @justinsb
😄

**Comment by randomvariable** [comment]
Summary of CAPI call comments on 2019/10/02

- @vince: Not having vendor committed simplifies dev experience, prevents out-of-sync vendor directories being committed.
- @timothysc: Having the vendor directory is important to air-gapped environments
  - @liztio: Only for building
- @justinsb: Geo-restrictions may also be an important consideration.
- @detiber: Asking for people to set up goproxies may be too large an ask
- @davidewatson: Some companies have legal review for dependencies, and it's a lot easier with a single vendor directory.

**Comment by timothysc** [comment]
There are a number of constraints that exist on external BigCo.s are many, which is why most of kubernetes org still has a vendor folder.  
- deps on proxy 
- github's down 
- audit review 
...

**Comment by vincepri** [comment]
I'm not sure if at all possible, but could we have a presubmit job to update and commit the vendor after each merge?

**Comment by justinsb** [comment]
I think we have a few options:

1) Create a goproxy service that works everywhere (including behind country-wide-firewalls)
2) Put the vendored content into the repo, but keep it off the master branch.  Then have some sort of tool to use that info locally, either a goproxy that reads from these branches, or some sort of copy-from-the-other branch script
3) Have a shadow branch that includes the vendor directory that auto-updates (e.g. master => master-with-vendor) 
4) Just re-enable the vendor directory
5) Re-enable vendor, but have a bot that updates vendor on all PRs

_1) Create a goproxy service that works everywhere (including behind country-wide-firewalls)_

I feel that goproxy services are still fairly new, it might well be that this gets fixed.  But I'm not sure we can count on it.  We could have a kubernetes specific proxy service, along with dumps of all our dependencies, but I'm not sure where we could put this that would be any better in terms of firewalls.  Any suggestions here @gyliu513  ?


_2) Put the vendored content into the repo, but keep it off the master branch.  Then have some sort of tool to populate vendor, either a goproxy that reads from these branches, or some sort of copy-from-the-other branch script_

It's cute, but it might be pretty hacky.  It feels like as much work as  optional 3, but also a not-great experience for the person building the code as well.  Probably wouldn't have just the subset of the vendored code that was actually in use, making auditing harder.  The one potential upside here is if we put it into a _different_ kubernetes wide repo, as part of figuring out a better process around dependency approval, but that's probably a ton of process.

_3) Have a shadow branch that includes the vendor directory that is auto-updates (master-with-vendor)_ 

Probably the best developer experience, and likely a reasonable audit experience?  But could become confusing for anyone looking at the branches.  One downside: vendor changes don't appear in PRs - I'm thinking here more of the "I use a new function, what did I pull in" use case than the more annoying case of "I updated controller-runtime and now my PR is a million lines".  For the latter, I think we should split up the PR into commits (1: go.mod / go.sum changes 2: vendor changes). 

_4) Just re-enable the vendor directory_

It's a bit of a drag, but it does have the advantage that we clearly see vendor changes, so it satisfies the PR review case and the audit review case.

_5) Re-enable vendor, but have a bot that updates vendor on all PRs_

So if I submitted a PR that needed a vendor update (and I didn't do remember to update vendor myself), the bot would propose a PR on my PR that added the vendor changes.  Then developers could keep using go.mod/go.sum, but vendor would still be visible in PR review.  (And it would be nicely split out into a separate commit)  Is this what you were suggesting @vincepri ?

**Comment by vincepri** [comment]
Something like that, or even if the bot commits to the branch directly after merging the PR (postsubmit job) would be ok.

If we go down the 4) path, we'd need to ask users to separate vendor commits from the other ones. One upside for this solution is that we have a lot of the tools for verification and automation in an older v1alpha2 commit

**Comment by gyliu513** [comment]
Thanks all for the discussion and comments here, really appreciate this, great team !!

@justinsb Having a goproxy service that works everywhere is a great idea, if we can have this service running in AWS etc, then it should helps.

For 4) path, just like `dep`, when developers commit code, they should make sure the PR include commits for `auto generated code` to facilitate the review.
