### ISSUE TITLE
RFE: Cluster API SDK

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1471]
**User Story**

As a developer I would like to use Cluster API as a framework to build infrastructure or bootstrap providers.

**Detailed Description**
For the `v0.3` cycle, I'd like to propose to move all exposed Cluster API code under `sdk/` (naming can be changed, this is an example) directory. This directory should contain code that providers and other tools can use to build on top of Cluster API. 

***Goals***
1. To provide a self contained SDK for adopting and developing with Cluster API.
1. To provide API guarantees and clear boundaries around breaking changes.
1. To release the SDK as part of each Cluster API iteration.
1. To provide a testing framework for unit testing, end to end, and integration. (Separate action item)

***Non-Goals*** 
1. To make the SDK a separate Go module and have a different release cadence.
1. To create new code or abstractions as part of this iteration.

/kind feature

**Comment by detiber** [comment]
Personally, I would like to avoid this for this current cycle to avoid the code churn that would result in downstream providers, especially after we just went through that with v1alpha2.

**Comment by vincepri** [comment]
We should discuss during planning. If anyone is interested working on this, I'm +1 at prioritizing given that it'll give us a better story around releasing and developer experience.

/cc @timothysc

**Comment by vincepri** [comment]
Given that clusterctl fills some of this purpose, I'm gonna go ahead and close this one out. 

/close
