### ISSUE TITLE
CAPI quickstart doesn't work if existing cluster has taints

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes-sigs/cluster-api#1486]
**What steps did you take and what happened:**
I tried to run through the CAPI quick start for vSphere and noticed that the CAPI components and the `infrastructure-components.yaml` file from all providers don't tolerate any taints, so an existing cluster built with kubeadm doesn't work cause it applies the master taints for control plane nodes.

Tolerating _all_ taints is probably not ok, but I think practically we should tolerate the well-known taints at least for the quick start which probably applies for the 80% of users that try it. Or a kubeadm-based cluster at the very least. 

**What did you expect to happen:**
The quick start to work quickly.

**Anything else you would like to add:**

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by ncdc** [comment]
Are you saying your bootstrap/management cluster has the taints?

**Comment by andrewsykim** [comment]
yes, for CAPA and CAPV it's patched (via kustomize) as part of the examples directory. e.g. https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/examples/provider-components/manager_tolerations_patch.yaml

**Comment by ncdc** [comment]
I'm wondering about the taints in your cluster (not the tolerations)?

**Comment by andrewsykim** [comment]
Happy to work on this once we agree on a set of tolerations. 

It has `node-role.kubernetes.io/master` - which is added by default by kubeadm.

**Comment by ncdc** [comment]
This is probably something we need to fix, and I'm trying to gather the facts. The quickstart works if you use a kind bootstrap cluster. I take it you didn't use kind?

**Comment by andrewsykim** [comment]
I didn't use Kind and I just verified that Kind does _not_ apply any taints on nodes which explains the quick start working only for Kind.

**Comment by andrewsykim** [comment]
I think just tolerating `node-role.kubernetes.io/master` is a good start

**Comment by detiber** [comment]
If we want `clusterctl` to continue to work, then tolerating `node-role.kubernetes.io/master` would probably be a minimum requirement.

**Comment by andrewsykim** [comment]
> If we want clusterctl to continue to work, then tolerating node-role.kubernetes.io/master would probably be a minimum requirement.

Just to be clear, I think most examples out there of `clusterctl` does include a toleration of `node-role.kubernetes.io/master`, but if you are bringing your own cluster it does not tolerate it even though most clusters may have the same taints as one that is bootstrapped by clusterctl.

**Comment by vincepri** [comment]
The assumption of the quickstart is also that you wouldn’t run the controllers on a control plane node, given that they can run on a simple node.

Is this something that can maybe go in an advanced section?

**Comment by detiber** [comment]
> The assumption of the quickstart is also that you wouldn’t run the controllers on a control plane node, given that they can run on a simple node.

Should that be the case, though? For example, if running on a Cluster API provisioned cluster in AWS, this would require an IAM profile for the Nodes that has a much higher set of permissions than we would generally require today.

**Comment by andrewsykim** [comment]
> The assumption of the quickstart is also that you wouldn’t run the controllers on a control plane node, given that they can run on a simple node.

I think in reality most management clusters would only have control plane nodes though? Especially if we're advising users to not run workloads on a management cluster

**Comment by vincepri** [comment]
> Should that be the case, though? For example, if running on a Cluster API provisioned cluster in AWS, this would require an IAM profile for the Nodes that has a much higher set of permissions than we would generally require today.

Given that the AWS provider uses (by default) credentials mounted in a secret, I don't see why you'd need wider permissions on Nodes.

> I think in reality most management clusters would only have control plane nodes though? Especially if we're advising users to not run workloads on a management cluster

From what I've seen, that's not the case and controllers usually run on workload clusters. Let's add an advanced section that shows how to add taints on control plane nodes?

**Comment by andrewsykim** [comment]
> Let's add an advanced section that shows how to add taints on control plane nodes?

The problem isn't that control plane nodes don't have the taints, it's that the provided deployment specs for CABPK, CAPI and CAP* don't tolerate any taints so they don't work out of the box for any cluster that do have taints.

**Comment by vincepri** [comment]
Apologies, I meant an advanced guide on how and where to add tolerations for the manager deployments

**Comment by andrewsykim** [comment]
Is that easier for users vs if the manager deployments tolerated well-known taints like `node-role.kubernetes.io/master`? If you tolerate the taint, the deployments will likely still run on workload nodes but can also run on clusters where you only have control plane nodes. We can't tolerate all taints, but `node-role.kubernetes.io/master` (kubeadm-based cluster) seems to fall in to the 80% of existing clusters out there.

**Comment by ncdc** [comment]
👍. We also have these tolerations in the examples we generate, but not in the components yaml we ship with the releases.

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/c6b8c307095892de15b1edcf8d610967dec77750/examples/provider-components/manager_tolerations_patch.yaml
