### ISSUE TITLE
Define a convention for watching specific namespaces or all

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#1490]
**User Story**

As an operator, I would like to have a convention for deploying cluster API providers for watching objects in a specific namespace

**Detailed Description**

Most of the cluster API providers already support watching objects in a specific namespace, but there is no formal convention about how this should be exposed to the users.

By defining a convention, it will be possible to implement higher-level tools to automatically deploy any provider watching objects in a specific namespace

***Goals***
 - To define a convention for requirements on how to expose to the users' options for configuring namespaced deployments 

/kind feature

**Comment by fabriziopandini** [comment]
Similar to this: 
Defining a convention for scaling up / down a provider, where scaling down to 0 == shut down the provider

**Comment by vincepri** [comment]
I stumbled upon this issue reading the clusterctl proposal, we've already started an effort to label external objects https://github.com/kubernetes-sigs/cluster-api/pull/1570

**Comment by vincepri** [comment]
/kind documentation

Let's document a convention that requires pluggable providers to provide flags to watch all or a single namespace.

**Comment by fabriziopandini** [comment]
WIP in https://github.com/kubernetes-sigs/cluster-api/issues/1490
