### ISSUE TITLE
v1alpha3 API types

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1502]
Once master branch is open to breaking changes from v1alpha2, we need to create the types for the next iteration.

- Copy types from api/v1alpha2.
- Rewrite imports.
- Set the storage version to v1alpha3 types.
- Make sure the generated CRDs contain both v1alpha2 and 3.

/kind feature
/milestone v0.3.0

**Comment by ncdc** [comment]
Master is open 😄
