### ISSUE TITLE
bootstrap/kubeadm: Test infra and automation

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1505]
After merging CABPK under this repository, we need to add new jobs that only run when CABPK code is changed.

/milestone v0.3.0
/priority important-soon
/help
/kind feature

**Comment by tahsinrahman** [comment]
I'm thinking of doing like this.

I'm not sure what scripts to run when corresponding dirs are changed, so I've referenced two new scripts `./scripts/ci-capd.sh` and `./scripts/ci-cabpk.sh` that we don't have yet. Does it look ok? :) 

https://github.com/kubernetes/test-infra/compare/master...tahsinrahman:capa?expand=1

**Comment by vincepri** [comment]
We might be able to avoid this if we do #1527

**Comment by ncdc** [comment]
This is integrated into the main CAPI builds.
/close
