### ISSUE TITLE
test/infrastructure/docker: Release story

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1507]
After merging CAPD under this repository, we need to figure out what our release story is going to look like and how to automate the process

/milestone v0.3.0
/priority important-longterm
/help
/kind feature

**Comment by chuckha** [comment]
This is mostly automated already and the release process is the same as CAPI with a few modifications that are documented https://github.com/kubernetes-sigs/cluster-api/blob/master/test/infrastructure/docker/docs/release.md#creating-a-release

I'll close this issue but feel free to open a new one if something else needs defining.

/close
