### ISSUE TITLE
[0.2] Change the default image in manifests to target release-0.2

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1509]
Now that master is open to v1alpha3, we want to change the tag referenced by default https://github.com/kubernetes-sigs/cluster-api/blob/release-0.2/config/default/manager_image_patch.yaml#L10 to be `release-0.2`, given that `latest` builds on the master branch instead.

/kind feature
/priority important-soon
/milestone v0.3.0
/help

**Comment by prankul88** [comment]
Hi @vincepri , Can I take this up?

**Comment by vincepri** [comment]
sure thing! :)

**Comment by ncdc** [comment]
Fixed by #1541 
/close
