### ISSUE TITLE
Status.Phase values in Cluster and Machine should be consistent with k/k

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1522]
Currently, in [Cluster](https://github.com/kubernetes-sigs/cluster-api/blob/484d4c6e4401efcbbb5a6949564c7d8f6d2151e8/api/v1alpha2/cluster_phase_types.go#L32-L51) and [Machine](https://github.com/kubernetes-sigs/cluster-api/blob/484d4c6e4401efcbbb5a6949564c7d8f6d2151e8/api/v1alpha2/machine_phase_types.go#L32-L60) the `Status.Phase` field values aren't following upstream conventions, they should all be in CamelCase format. 

/kind feature
/priority important-soon
/milestone v0.3.0
/help

**Comment by ncdc** [comment]
@tahsinrahman this can't be implemented until we have the v1alpha3 api package
