### ISSUE TITLE
Ship CAPI with batteries included

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1527]
**User Story**

As a developer/user/operator I would like to deploy a single Cluster API manager/binary with everything except cloud providers for easier management of Cluster API resources

**Detailed Description**

[A clear and concise description of what you want to happen.]

***Goals***
- Ship Cluster API manager including CABPK, and possibly the future control plane manager.
- Deploy all CRDs and resources with a single command.

***Non-Goals*** 
 - Include infrastructure providers.

/kind feature
/milestone v0.3.0
/priority important-soon

**Comment by detiber** [comment]
If we do this, I would like to make sure that we don't consolidate the controllers for the different "providers" into the same go package, and that we do some level of verification that we aren't importing core logic that external providers do not have access to in the "default" provider implementations.

**Comment by ncdc** [comment]
+1. We aren't planning on merging all the controllers into a single package. Hopefully that won't be an issue with kubebuilder. If you see any evidence of preferential coding treatment to in-tree providers, definitely raise a concern. We're ok for now, though, given the current state of the repo.

**Comment by vincepri** [comment]
@chuckha How do you feel about the above? I can take those action items if you don't have time.

**Comment by fabriziopandini** [comment]
I'm + 1 with Jason on getting moving with and then iterate simplifying automation
But somehow, we should preserve the ability to work on single pieces and assemble everything at release/package time

**Comment by vincepri** [comment]
I'm fine to merge the PR, I'd like to make sure we're aligned on the state of the repository after it merges, happy to do the work

**Comment by chuckha** [comment]
Big +1 on alignment. Let's merge the PR and then get to this point iteratively.
