### ISSUE TITLE
docs/book: Use weave CNI with docker quickstart

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#1533]
Upsides of using weave CNI:
- Avoid a known issue with Calico, kind v0.5.1, and CAPD v0.2.0.
- Remove need to override`Cluster.Spec.ClusterNetwork`

See https://github.com/kubernetes-sigs/cluster-api/pull/1484#discussion_r331046681

**Comment by ncdc** [comment]
@neolit123 mentioned there might be some issues with Weave and docker-in-docker

**Comment by detiber** [comment]
The initial motivation around this issue was to help simplify the quickstart examples used, and avoid user confusion on why we are overriding the podCIDR in the KubeadConfig rather than leaning on defaults.

**Comment by neolit123** [comment]
the problem we saw with WeaveNet was a special case in the prow cluster using docker-in-docker and might have been related to the VMs that GCE gives us or the kubekins image.

perhaps nobody will encounter the same problem in the wild:
https://github.com/weaveworks/weave/issues/created_by/neolit123

i think Weave as the default is OK, but if someone wants to test a different CNI they should resort to the kubeadm docs, which already include the pod cidr notes:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

**Comment by vincepri** [comment]
@dlipovetsky do we still want to tackle this?
