### ISSUE TITLE
Figure out what to do with submodule Makefiles

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1543]
Now that we have multiple modules (assuming the cabpk one merges) in this repo, we need to figure out the interactions between Makefiles and release.

I like keeping modules fairly independent and responsible for their own Makefiles, but this super duper subjective so any other ideas would be good to have. This vision is: top level makefile calls module makefiles and each module has its own makefile that can build the project it is responsible for.

/kind question

**Comment by ncdc** [comment]
Question: do we need to have cabpk and capd as separate go modules?

**Comment by detiber** [comment]
> Question: do we need to have cabpk and capd as separate go modules?

Arguable, but if we intend for them to be reference implementations for developers that want to create their own provider implementations, then having them as Go modules with their own Makefile, prow tooling, etc would help.

**Comment by chuckha** [comment]
no, but they would still need their own release process, or at least CAPD would

One thing I liked about CAPD as a separate repo was that it give people a place to look and see how it was structured. That's a lot more buried and now providers have to go to the more complex providers such as CAPA or CAPV

But overall, no, there's no strict requirement that they need to be separate go modules.

**Comment by detiber** [comment]
That said, the value of a reference implementation is pretty limited. When we provided a skeleton repo most people hit issues with copy/paste errors and missing places they needed to rename/modify for their own types/purposes. Having a walkthrough of creating a provider from scratch as we did in the v1alpha1 docs was a much smoother onboarding approach for new projects.

**Comment by ncdc** [comment]
I don't know about capd, but for capi + cabpk, the proposal in #1527 is to ship a single manager binary in a single image that has all the controllers for capi and cabpk. We wouldn't have to make any edits to the Makefile for the manager binary/image - we would instead need to add the cabpk controller setup code into capi main.go. I am not sure how kubebuilder, `make generate`, etc. would work for cabpk code under bootstrap/kubeadm.

**Comment by chuckha** [comment]
sounds good. I'm ok closing this this in favor of #1527 if you are.

**Comment by chuckha** [comment]
The rest of this ticket is about CAPD's Makefile. We need to build out release process and make this Makefile behave like other provider's makefiles. I'm going to make a new issue outlining the work for CAPD release.

/close
