### ISSUE TITLE
Use Spec.ClusterName to get the linked cluster

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1547]
As a follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/1539#discussion_r335020736, we can improve the code to use Spec.Name to get the cluster instead of using the util metadata label.

/kind important-longterm
/kind feature
/help
/milestone v0.3.0

**Comment by vincepri** [comment]
/priority important-longterm

@noamran Would you be interested in this issue? We'd have to wait for the linked PR to merge first though

**Comment by noamran** [comment]
> /priority important-longterm
> 
> @noamran Would you be interested in this issue? We'd have to wait for the linked PR to merge first though

Sure! Thanks for tagging me.

**Comment by vincepri** [comment]
I'll assign myself, even if you work on it :)
