### ISSUE TITLE
Document how to upgrade from v1alpha2 to v1alpha3

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1550]
This is a release blocker, we need documentation on how to upgrade from v1alpha2 providers to v1alpha3.

/kind documentation

**Comment by detiber** [comment]
@vincepri can you please add some more context on the CABPK related changes for v1alpha2 to v1alpha3? especially around the way the components will no longer be distributed from the old repo and the manager will no longer be a separate Deployment?

**Comment by vincepri** [comment]
Yeah, once I get more items, I'll open the sub-issues, this is to track the larger effort of upgrading from v1alpha2

**Comment by rudoi** [comment]
Just to document a few things I've run into slapping v1alpha3 onto v1alpha2:
```
The ClusterRoleBinding "capi-manager-rolebinding" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"capi-aggregated-manager-role"}: cannot change roleRef
```

```
The Deployment "capi-controller-manager" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"cluster.x-k8s.io/provider":"cluster-api", "control-plane":"cluster-api-controller-manager"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**Comment by noamran** [comment]
The upgrade process using `clusterctl` is already documented [here](https://master.cluster-api.sigs.k8s.io/clusterctl/commands/upgrade.html).
Once the documentation is [reorganized](https://github.com/kubernetes-sigs/cluster-api/issues/2434) it might make sense to also close this issue (if there are no additional details we want to add).

**Comment by vincepri** [comment]
@noamran any updates on this? is there anything we can help with?
