### ISSUE TITLE
Add shellcheck to make verify

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1551]
As part of `make verify` target, we should also run shellcheck on all the scripts in this repository. An example is available in the CABPK repository https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/master/hack/verify-shellcheck.sh

/kind feature
/help
/milestone v0.3.0
/priority important-longterm

**Comment by prankul88** [comment]
@vincepri Hi, Do you like the implementation where CABPK uses `utils.sh` for getting root path?
