### ISSUE TITLE
Avoid using //nolint in the codebase

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1553]
Unless absolutely necessary, we should try and remove the `//nolint` comments in the codebase by fixing the linting issues.

/kind feature
/help
/priority backlog
/milestone v0.3.0

**Comment by detiber** [comment]
@vincepri can you call out specific context? Otherwise we are likely to just close this the next time we do backlog grooming.

**Comment by prankul88** [comment]
@tahsinrahman Thanks.
I would like to take this up.
