### ISSUE TITLE
Find better name for clusterv1.MachineClusterLabelName 

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1569]
The variable name is a little misleading as this label isn't applied only to machines, or not anymore. We should find a better name such as `LabelClusterName` or similar, open to suggestions.

As part of this change, make sure to update the `v1alpha2-to-v1alpha3.md` document with the changes providers will need to apply.

/priority important-longterm
/milestone v0.3.0
/kind cleanup

**Comment by detiber** [comment]
I think `ClusterLabelName` might read a bit better, but not overly picky here.

**Comment by vincepri** [comment]
Either way :)

Also,
/help
