### ISSUE TITLE
Clusterctl create cluster

### ISSUE THREAD

**Issue by jessicaochen** [kubernetes-sigs/cluster-api#157]
Implement v0 cluster bootstrapping in clusterctl tool.

Overall Clusterctl Design: https://docs.google.com/document/d/1-sYb3EdkRga49nULH1kSwuQFf1o6GvAw_POrsNo5d8c/edit#heading=h.mhd2l21c5f2l
Overall Bootstrap Design: https://docs.google.com/document/d/1CnzIXtitfbO6Y7ZxVWROGO8jr19t0vooDx-YQ7c2nbI/edit

v0 scoping:
- The clusterctl tool will use a temporary minikube as the external cluster api stack and then optionally pivot into the internal stack
- Long term, it would be good to make it piecemeal like kubeadm phases so that various parts can be subbed out. However, that is not covered in this issue.

To minimize/not depend on provider-specific code in the vanilla case, the following things need to be done differently than what is currently (May 11, 2018) done in gcp-deployer & tf-deployer:
- Machine or cluster controller should update cluster object with endpoint instead of the deployer #158
- Kubeadm join token should be fetched by machine controller should fetch the token instead of having it passed in as a flag #159
- Kubeconfig should be fetched from cluster master via ssh. Deployer should provide ssh key for machine actuators to apply to provisioned machines. #160

Note: Once clusterctl tool is working well, gcp-deployer will get deprecated and removed. In the interim, that means code in the cloud directory will be supporting two different deployers.

**Comment by spew** [comment]
@jessicaochen I am trying to figure out if issue https://github.com/kubernetes-sigs/cluster-api/issues/159 can be closed. I was looking at clusterctl today and I think since the implementation simply brought kubeadm into gcp-machine-controller and removed tokens entirely from gcp-deployer we can consider it closed.

Agree?

**Comment by jessicaochen** [comment]
It needs to be done for all the supported providers (ie. gcp and vsphere) before I can remove the dependency from clusterctl.

**Comment by roberthbailey** [comment]
@jessicaochen - can you provide current status for this issue? What remains before we can close it?

**Comment by jessicaochen** [comment]
Two of the subissues are still open. I prefer to keep this issue open while sub issues are not closed (to provide context and motivation to sub issues). However, I am not opposed if folks prefer this parent issue closed and keep tracking on sub issues.

**Comment by nupejosh** [comment]
Hey @jessicaochen I'm doing a deep dive on cluster-api in hopes to contributing to the community with a provider of my own. I want to understand a bit more about clusterctl. Can you approve my request for access to the google docs, Overall Clusterctl Design & Overall Bootstrap Design, that you pasted above?

**Comment by roberthbailey** [comment]
@nupejosh - are you a member of the cluster lifecycle sig mailing list? You can always join the list and disable receiving email if you just want to get permissions. It's difficult for Googlers to make docs publicly visible, so we often share them with the mailing lists and you are likely to hit the same issue with other docs that you stumble across.

**Comment by nupejosh** [comment]
@roberthbailey Thanks for the tip! I just joined the kubernetes-sig-cluster-lifecycle group and mailing list. I'll see what docs have been shared there.

**Comment by jessicaochen** [comment]
Agreed that if you join the groups, (in this case, kubernetes-sig-cluster-lifecycle@googlegroups.com and/or kubernetes-dev@googlegroups.com) you should have all the access you need. Do let me know if you still do not have access.

**Comment by timothysc** [comment]
Closing parent and child issues can reference.
