### ISSUE TITLE
[cabpk] [docs] external etcd doc improvement

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1575]
/kind documentation
/good-first-issue

Clean up the documentation to provide support for etcd clusters created with https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/. Right now the docs are etcdadm specific, namely the locations of certs. Be generic (say which certs  are needed) and then provide default location examples for etcdadm and kubeadm etcd setups.

The document mentions they must be base64 encoded but using `kubectl create secret --from-file` (or whatever that command is) base64 encodes things by default. Instead, provide an example using the kubeadm create secret --from-file telling the user this base64 encodes the data. If they don't want to use kubeadm create secret they will have to base64 encode the files by hand.

**Comment by chuckha** [comment]
@vishakhanihore How is this going? Do you still have time to work on this issue?

**Comment by prankul88** [comment]
@chuckha I can work on this.
