### ISSUE TITLE
[cabpk] Create E2E test framework

### ISSUE THREAD

**Issue by moshloop** [kubernetes-sigs/cluster-api#1577]
If we are generating cloud-init then a KVM/QEMU based framework should work - AppVeyor supports nested virtualization for CI, and we could potentially work with test-infra to get some nested virtualization capable runners on GCP.

* Testing the logic of the controller could be done with the standard kube-builder testing framework
* Testing the output of this provider would use KVM, e.g.:

1) Generate cloud-init for controller
2) Spin up a KVM instance with cloud-int and wait for ip
3) Generate cloud-init for worker
4) Spin up second KVM instance
5) Test that both nodes have registered/joined.

**Comment by chuckha** [comment]
closing this in favor of the CAEP proposal https://github.com/kubernetes-sigs/cluster-api/pull/1571

/close
