### ISSUE TITLE
[cabpk] Ability to configure hostname via cloud-config

### ISSUE THREAD

**Issue by zjs** [kubernetes-sigs/cluster-api#1579]
/kind feature

**Describe the solution you'd like**
 I would like to be able to define a hostname via cloud-config data.

For example, I may want to use a specific hostname for each of my nodes.

**Anything else you would like to add:**
A golang template for configuring this could look something like:
```
{{- if .HostName }}
hostname: {{ .HostName }} 
{{- end }}
```

**Comment by akutz** [comment]
cc @yastij

**Comment by joonas** [comment]
@yastij did you have any updates on this?

**Comment by vincepri** [comment]
@zjs Is this still relevant for your use cases?

Bumping to next for now.

/milestone Next

**Comment by vincepri** [comment]
Closing this for now, feel free to reopen if the problem persists
/close
