### ISSUE TITLE
[cabpk] Write "/etc/hosts" and "/etc/hostname"

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api#1580]
/kind feature

**Describe the solution you'd like**
The bootstrap data should include the files `/etc/hosts` and `/etc/hostname` with the values derived from the host. This ensures these files reflect the correct values without requiring a reboot before the systemd-hostnamed service updates them.

**Comment by chuckha** [comment]
Trying to figure this one out, but this sentence has me a bit stumped 

> The bootstrap data should include the files /etc/hosts and /etc/hostname with the values derived from the host.

It sounds like the files `/etc/hosts` and `/etc/hostname` need to be correctly populated with data only known by the host. If there is an external thing that can provide the data these files need, then perhaps the thing responsible for making the bootstrap data can get the necessary data from that external system.

However, if only the host knows what values need to be there, then either the host needs to exist before CABPK generates data and the user adds these files to the KubeadmConfigSpec or the user could inject a script to generate these files before kubeadm init runs.

not really sure where to put this, so i'm leaving it low priority in the current milestone. Please adjust if necessary, this is a best guess.

/milestone v0.3.0
/priority important-longterm

**Comment by akutz** [comment]
cc @yastij

**Comment by joonas** [comment]
@yastij did you have any updates on this?

**Comment by vincepri** [comment]
@yastij Any updates? 

Bumping to next for now.

/milestone Next
/priority awaiting-more-evidence

**Comment by vincepri** [comment]
Closing this due to lack of updates

/close
