### ISSUE TITLE
[cabpk] Wiring up the Format field

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#1582]
/kind feature

**Describe the solution you'd like**
A PR for adding the `Format` field to `KubeadmConfig.Spec` is open. This issue is to discuss how we want to use it in the controller. 

**Anything else you would like to add:**
The `Format` field is used to specify the output format of the bootstrap data that the controller generates.

**Comment by vincepri** [comment]
Do we still need this issue in the future or have we set on cloud-init for now?

**Comment by detiber** [comment]
If we want to support other base OSs in the future (such as Flatcar Linux), we'll still need to look into this.

**Comment by ncdc** [comment]
Based on [this conversation in Slack](https://kubernetes.slack.com/archives/C8TSNPY4T/p1596111297392800), I am closing this as it does not have a user story around what an additional format would be. There will be a new issue opened soon to discuss adding support for Ignition as a bootstrap format, either in CABPK or as a separate provider.

/close
