### ISSUE TITLE
[cabpk] Remove CAPI Crds

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1585]
/kind feature

**Describe the solution you'd like**
If possible, it would be great to remove the config-capi directory. I'm not sure we need to create Clusters/Machines in our integration test. Another alternative is execing `go` to do what the script https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/master/hack/update-capi-crds.sh does.

**Anything else you would like to add:**
Keeping this up to date is annoying and if we can automate it that would be excellent.

**Comment by detiber** [comment]
This can likely be closed now that CABPK isn't a separate module with separate tooling.

**Comment by vincepri** [comment]
This has been done as part of #1545 

/close
