### ISSUE TITLE
[cabpk] Show the actual kubeadm configuration applied to a machine

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#1587]
/kind feature

**Describe the solution you'd like**
The typical kubeadm configuration generated by CABPK is minimal, and kubeadm applies many defaults, the values of which are not observable in any CAPI objects. Today, my options are to inspect `/tmp/kubeadm.yaml` on the machine, or fetch the kubeadm configuration from the cluster's control plane.

**Anything else you would like to add:**
Being able to observe the actual configuration applied to the machine will improve the debugging experience.

**Comment by chuckha** [comment]
This is blocked on kubeadm implementing this feature for us to use and won't be coming until at least 1.17+

Until then it will be up to the user to dump as much kubeadm config as they can

/milestone Next

**Comment by vincepri** [comment]
Going to close this for now given that we haven't gotten user stories for this ask in a while and it seems there are missing pieces in kubeadm.

/close
