### ISSUE TITLE
[cabpk] Figure out long-term interface for static pod kustomizations with kubeadm

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#1588]
/kind feature

**Describe the solution you'd like**
Kubeadm 1.16 introduced `kubeadm init --experimental-kustomize kubeadm-patches/` to allow customization of the static pods for certain environments. Is there a way that  this can be passed through to kubeadm, or allow arbitrary arguments to be appended to kubeadm init/join

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by chuckha** [comment]
One thing came up around this idea. It would be nice to be able to increase the verbosity that kubeadm spits out. I'll make a separate issue for that. I wonder if we could do something like expose exactly the flags kubeadm exposes for a given version. I'd have to think more about it.

/milestone Next

**Comment by vincepri** [comment]
/remove-lifecycle frozen

@fabriziopandini Is this something we want to support?

**Comment by fabriziopandini** [comment]
I'm +1 to close this one given there is no concrete ask for this feature and no actionable items
