### ISSUE TITLE
Remove use of ginkgo/gomega from unit tests

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1589]
We use ginkgo/gomega for e2e tests, but not unit tests. We should remove all imports of ginkgo and gomega from unit tests and either use normal assertions such as

```go
if e, a := "expected", "actual"; e != a {
  t.Errorf("....")
}
```

or rally around something like `testify`.

/kind cleanup
/priority important-longterm
/help
/good-first-issue
/milestone v0.3.0

**Comment by vincepri** [comment]
We should standardize tests around gomega/ginkgo, wdyt?

**Comment by ncdc** [comment]
I'd honestly rather use testify for unit tests, and ginkgo for e2es

**Comment by vincepri** [comment]
Either, or. I'd like to avoid g.Expect(g.Success()... etc

**Comment by ncdc** [comment]
In units, yes. Kubernetes code essentially has ginkgo as the standard framework for e2es, though.

**Comment by vincepri** [comment]
Yeah, this issue of RegisterWithT only applies to unit tests

**Comment by ncdc** [comment]
I see that now. Let me change this issue to reflect that.

**Comment by ncdc** [comment]
Chatted offline with Vince. Going to hold off on this for now. Will reopen if needed.
/close
