### ISSUE TITLE
Machine Controller Should Fetch Kubeadm Join Token

### ISSUE THREAD

**Issue by jessicaochen** [kubernetes-sigs/cluster-api#159]
Currently, the kubeadm join token is passed in via a command line flag. This is problematic because tokens expire and may not be valid at when a new machine is requested. What really should be done is have the machine controller generate/fetch a token from the control plane when about to provision a machine.

**Comment by spew** [comment]
Taking a look.

**Comment by spew** [comment]
Working on this one today.
