### ISSUE TITLE
How to add `cluster api provider ibmcloud` to glossary

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#1592]
I found in the document https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/reference/glossary.md#capi , it mentioned that `CAPI` means `Core Cluster API`, but how to add `cluster api provider ibmcloud` here? The short name seems also `capi`.

How about we rename the `Core Cluster API` to `CAP`?

FYI @detiber @vincepri

**Comment by detiber** [comment]
@gyliu513 we've encountered this in the past with AWS (CAPA) and Azure (CAPZ) in the past, since IBM is already pretty short, could I recommend CAPIBM?

I think trying to change the convention for what we call CAPI would cause too much confusion at this point.

**Comment by gyliu513** [comment]
Thanks @detiber , it does make sense, can you help review the PR?
