### ISSUE TITLE
[flake] Cluster Reconciler [It] Should successfully set Status.ControlPlaneInitialized on the cluster object if controlplane is ready 

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1597]
**What steps did you take and what happened:**
`Cluster Reconciler [It] Should successfully set Status.ControlPlaneInitialized on the cluster object if controlplane is ready ` is flaking. From https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/1595/pull-cluster-api-test/1184834417806282752/build-log.txt:

```
[90m------------------------------[0m
[91m[1m• Failure [12.040 seconds][0m
Cluster Reconciler
[90m/home/prow/go/src/sigs.k8s.io/cluster-api/controllers/cluster_controller_test.go:38[0m
  [91m[1mShould successfully set Status.ControlPlaneInitialized on the cluster object if controlplane is ready [It][0m
  [90m/home/prow/go/src/sigs.k8s.io/cluster-api/controllers/cluster_controller_test.go:224[0m

  [91mTimed out after 10.000s.
  Expected
      <bool>: false
  to be true[0m

  /home/prow/go/src/sigs.k8s.io/cluster-api/controllers/cluster_controller_test.go:272
```

**What did you expect to happen:**
No test flake.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: master in the past 1-2 weeks

/kind flake
/priority important-soon
/milestone v0.3.0
/help

**Comment by ncdc** [comment]
This is flaking a lot. Raising priority

**Comment by vincepri** [comment]
Thank you Thank you Thank you Thank you

**Comment by ncdc** [comment]
Looking/thinking about this more - I think it's sometimes taking more than 10 seconds for the machine reconciler to process & patch the machine (to add the finalizer), for the patch to be recorded in etcd, and for the test case to see the machine with the finalizer. I hesitate to say "let's just increase the timeout", but so far, I'm not seeing any evidence of anything else happening.

**Comment by liztio** [comment]
Looks like the timeout patch fixed, closing for now.

/close
