### ISSUE TITLE
Support adopting a cluster from a set of existing machines

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#16]
_From @rsdcastro on January 29, 2018 21:38_

This item tracks supporting users providing a list of machines that will be used to bootstrap the cluster rather than requiring machines to be added via the cluster API.

_Copied from original issue: kubernetes/kube-deploy#522_

**Comment by ncdc** [comment]
I'm not entirely certain what this issue is asking for specifically. Is it:

- I have some servers that are already running Kubernetes and I want to create `Machine` custom resources that represent these preexisting servers?
- Something else?

**Comment by vincepri** [comment]
Closing this issue given the project's scope and goals. This particular feature is allowed but not necessarily supported.

/close
