### ISSUE TITLE
Change remote.NewClusterClient to return a controller-runtime client.Client

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1606]
The current signature
```go
func NewClusterClient(c client.Client, cluster *clusterv1.Cluster) (ClusterClient, error)
```

should be changed to
```go
func NewClusterClient(c client.Client, cluster *clusterv1.Cluster, scheme runtime.Scheme) (client.Client, error)
```

It would be nice to omit `scheme`, but I'm not sure if that's possible.

The reason for making this change is that it reduces our use on typed clients - the `ClusterClient` interface uses the `CoreV1()` typed clientset.

Because the drain code uses client-go's type client `kubernetes.Interface`, we will probably need to create a new `RestConfig()` method (used by https://github.com/kubernetes-sigs/cluster-api/blob/9bb9187fc711eae667c1ad0bb7803214dcf63692/controllers/machine_controller.go#L285)

/priority important-longterm
/help
/kind cleanup

**Comment by vincepri** [comment]
/milestone v0.3.0

Whoever works on this, please document this breaking change in the tracking document https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/providers/v1alpha2-to-v1alpha3.md :)

**Comment by noamran** [comment]
I can't assign myself, but I will work on this.

**Comment by ncdc** [comment]
cc @akutz for feedback - how do you feel about a change like this?
