### ISSUE TITLE
Implement custom certificate authority support for tf-deployer

### ISSUE THREAD

**Issue by spew** [kubernetes-sigs/cluster-api#161]
In [PR-153](https://github.com/kubernetes-sigs/cluster-api/pull/153) initial support was added for custom CAs when using gcp-deployer. However, the tf-deployer version of the same functionality was left unimplemented. This issue tracks the work to implement that functionality in the tf deployer.

**Comment by roberthbailey** [comment]
tf-deployer is gone.

/close
