### ISSUE TITLE
Automate creation of k8s clusters with different storage and networking options

### ISSUE THREAD

**Issue by yashbhutwala** [kubernetes-sigs/cluster-api#1623]
**User Story**

As a user, I would like to  for streamline inputting different storage and networking options into the creation of k8s clusters

https://kubernetes.io/docs/concepts/storage/volumes/#types-of-volumes
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/

/kind feature

**Comment by ncdc** [comment]
@yashbhutwala thanks for this idea. Could you please be more specific with your feature request - how do you envision Cluster API helping you set up storage volumes and/or networking?

**Comment by yashbhutwala** [comment]
@ncdc pardon me I'm new to cluster-api, so I can't speak to any particular approach. 

What I am hoping for with this feature request is some aspect of custom composobality for different kinds of CNI plugins (i.e.: Calico, Flannel, etc.) as well as storage setups particularly for Onprem environments (i.e.: NFS, ceph, etc.) directly via the CRD spec.  

Perhaps, this is already possible, if so, can you point me to some docs?

**Comment by ncdc** [comment]
Cluster API does not manage add-ons at this time (CNI plugins, storage configuration). There are ongoing efforts to handle add-on management separately - the meeting minutes are available [here](https://docs.google.com/document/d/10_tl_SXcFGb-2109QpcFVrdrfnVEuQ05MBrXtasB0vk/edit?ts=5c94e9ae#heading=h.t413tvzgp6b4).

@timothysc @fabriziopandini @justinsb @stealthybox have you all thought about how CAPI may (or may not) deal with add-ons?

**Comment by fabriziopandini** [comment]
One option is:
- as soon as kubeadm is going to offer addon management, CAPI can leverage
on it

Il giorno gio 24 ott 2019 alle ore 19:41 Andy Goldstein <
notifications@github.com> ha scritto:

**Comment by detiber** [comment]
@fabriziopandini I believe that is one of the requirements to be able to support this, however it will not be sufficient in and of itself. There are different requirements on the infrastructure that will need to taken into account to support this as well (for example security group/firewall rules that allow traffic for a given CNI or storage provider). Ideally this will be exposed through the addon somehow and we'll be able to propagate it through cluster-api to the provider as needed.

**Comment by stealthybox** [comment]
> security group/firewall rules

Could this use-case be delivered via a privileged `Daemonset` contained within a kustomized addon for the target OS/net-env ?

**Comment by detiber** [comment]
> Could this use-case be delivered via a privileged Daemonset contained within a kustomized addon for the target OS/net-env ?

It potentially *could*, but it is then deferring the credentials requirements down to the workload cluster, which I'm not sure is something that we'd want to do here, especially considering these Security Groups are currently owned by the management cluster rather than the workload cluster.

**Comment by vincepri** [comment]
Hey folks, we discussed this topic during October 30th community meeting and the consensus was that for now this is out of scope for Cluster API.

The quick start guide already has some pointers on how to install CNI, specifically Calico. As others have mentioned, in the future this user story might be addressed with addon management.

/close

**Comment by dlipovetsky** [comment]
Addons such as CNI and CSI are out of scope for Cluster API.

That said, an addons can have infrastructure requirements. For example, a CNI requires that machines must have be reachable at certain ports.
