### ISSUE TITLE
Surface events and errors

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1625]
This issue serves as an umbrella to drive a larger effort to expose more information to users via events on Cluster/Machine/Machineset/MachineDeployment. 

/kind feature
/milestone v0.3.0
/priority important-soon
/area ux

**Comment by vincepri** [comment]
/cc @dims 

for more use cases

**Comment by ncdc** [comment]
@vincepri can you enumerate any specific events we should add?

**Comment by randomvariable** [comment]
Also
/kind documentation

**Comment by ncdc** [comment]
@vincepri bump

**Comment by vincepri** [comment]
Need a spike to enumerate the individual tasks. As an example, we don't log any events on Cluster and we could log some here and there.

**Comment by ncdc** [comment]
Ok, thanks. I don't imagine anyone will work on this without more guidance, though. WDYT?

**Comment by vincepri** [comment]
Right yeah, I need to take some time to enumerate all the possible events needed

**Comment by ncdc** [comment]
Can we roll this into the issue about conditions?

**Comment by vincepri** [comment]
Closing this given that we'll probably tackle this when doing conditions

/close
