### ISSUE TITLE
🏃 Post submit jobs should run CAPD and CABPK related verification on PRs

### ISSUE THREAD

**Issue by ashish-amarnath** [kubernetes-sigs/cluster-api#1627]
**User Story**
As a developer, I would like to catch unintentional breaking changes to the code that may affect CAPD and CABPK.  

**Detailed Description**
Currently, the only CAPD and CABPK related verification that is done is running `go test -v ./...`.
There were other verification steps that were being performed in the old repos that will have to be migrated.

[A clear and concise description of what you want to happen.]

***Goals***
 - 1. Identify submit verification gaps, specifically related to CAPD and CABPK from the corresponding historical repos.
 - 1. Add the missing verification steps to the CAPI repo

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by ncdc** [comment]
Closing in favor of #1837 
/close
