### ISSUE TITLE
Validate Spec.Version field with a regex

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1629]
Version fields are currently treated as a simple optional string (pointer). Kubebuilder offers markers for validating strings with regular expressions. If the version field is used, we usually expect it to be a semver (+ the leading `v` maybe? cc @ncdc).

/milestone v0.3.0
/kind feature
/priority important-longterm
/area api

**Comment by akutz** [comment]
Hi @vincepri,

The semver pattern allows an optional leading `v`. FWIW, Go modules requires it, but the semver spec doesn't. As you said, there is a [Kubernetes package](https://github.com/kubernetes/apimachinery/tree/master/pkg/util/version) for parsing semvers.

**Comment by vincepri** [comment]
I was more thinking about using a regex with `// +kubebuilder:validation:Pattern` marker as described in https://book.kubebuilder.io/reference/markers/crd-validation.html

**Comment by akutz** [comment]
Sure. I was simply pointing to the package as a reference for the patterns that were deemed suitable by the k/k community.

**Comment by detiber** [comment]
It will be important to not exclude versions that are currently being used today. 

Since we haven't enforced it, I'm not sure that the versions that have been used conform to semver. @aaroniscode

**Comment by detiber** [comment]
I am not, which is why I tagged in @aaroniscode, @codenrhoden might have additional context here as well.

**Comment by aaroniscode** [comment]
I've used a version based on the VMware binaries like "v1.15.3+vmware.1". We'd want to make sure that doesn't break.

**Comment by ncdc** [comment]
`v1.15.3+vmware.1` is a valid semver and is parsable. We spent **a lot** of time debating how to format the version for our builds.

**Comment by akutz** [comment]
While the above is true, funny enough, you can’t use two + chars with the k/k parsing library. I have a list of odd restrictions written somewhere. Will find it

**Comment by ncdc** [comment]
Yeah, I think I filed that issue 😄 or was at least involved.

**Comment by ncdc** [comment]
https://github.com/kubernetes/kubernetes/issues/75297

**Comment by imikushin** [comment]
I see version strings like `v1.15.3+vmware.1.20-guest.3.15` in my current work.

**Comment by vincepri** [comment]
I'm gonna close this out for now given that now we have webhooks and we can make sure the versions are valid semver there

/close
