### ISSUE TITLE
machine remains undeleted while cluster has been deleted

### ISSUE THREAD

**Issue by xrmzju** [kubernetes-sigs/cluster-api#1643]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
-  create a cluster, and create machines use machineset, everything goes ok.
-  delete the cluster 
-  find out that still remains machine in deleting state, the log says ”can not find cluster <clusterName>“ from [machine controller](https://github.com/kubernetes-sigs/cluster-api/blob/bad33a82c9ea5fbef94216103bac48515beea32b/controllers/machine_controller.go#L124)

**What did you expect to happen:**
all resources under the cluster be deleted successfully

**Anything else you would like to add:**
the root cause of this bug is that cluster controller try to [delete it's child in background](https://github.com/kubernetes-sigs/cluster-api/blob/bad33a82c9ea5fbef94216103bac48515beea32b/controllers/cluster_controller.go#L172) (in this case, only the machinSet, machines are the child of the machineSet) and list it's child 5 seconds later, if not exist anymore, cluster controller will proceed to delete it infra resource. on the other way, the machineSet controllers uses the kubernetes garbage collector to delete the machine resources, if we delete the machineset in `Background`
 propagationPolicy , the machineset resource will be deleted immediately. so the next time cluster controller list it's children, the machineset will not be found any more. but the machine deleting in background may still be processed by the machine controller, and need get the cluster obj in it's reconcile func, thus the finalizer will not be successfully removed.

**Solutions**
i try the `Foreground ` propagationPolicy and this case solved, but i'm not sure if it is a proper solution.

**Notes**
Here is a Column describes the resources's ownerRef and finalizer in cluster-api and it's provider

  | ownerRef Name | ownerRef Set By | Finalizer Name | Finalizer Set By
-- | -- | -- | -- | --
cluster | / | / | cluster.cluster.x-k8s.io | cluster-controller
infra cluster | cluster | cluster-controller | self-defined-infra-cluster-finalizer | clusterinfra-controller
machineDeployment | cluster | machineDeployment controller | / | /
machineSet(create alone) | cluster | machineSet controller | / | /
machineSet(create by machine deployment)) | machineDeployment | machineDeployment controller | / | /
machine(create alone) | cluster | machine controller | machine.cluster.x-k8s.io | machine-controller
machine(create by machineset) | machineSet | machineSet controller
machine infra | machine | machine controller | self-defined-infra-machine-finalizer | machineinfra-controller
bootstrap | machine | machine controller |   |

**Comment by xrmzju** [comment]
@detiber @ncdc @vincepri any good idea?

**Comment by ncdc** [comment]
Thanks for the detailed research! Foreground deletion is a good idea, but I think it might be better to allow a machine to be deleted in the absence of a cluster. I think this will be required if you start from scratch, create a machine, and then try to delete it (without creating any cluster).

**Comment by xrmzju** [comment]
> Foreground

in normal case, we need the cluster exist if we want to delete the machine, because we need to delete the k8s node in workload cluster.

**Comment by ncdc** [comment]
So maybe we need both foreground deletion from the cluster's code + we need to allow a machine to be deleted if there's no cluster for it.

**Comment by xrmzju** [comment]
> So maybe we need both foreground deletion from the cluster's code + we need to allow a machine to be deleted if there's no cluster for it.
i think ’the allow no cluster part‘ is not that simple, it is hard to decide whether we need a cluster...

**Comment by vincepri** [comment]
+1 on allowing dependent objects to be deleted when the parent isn't there

**Comment by detiber** [comment]
My concern with foreground deletion is that it would block any additional events from happening while waiting on the deletion, I think we should try to maintain asynchronous behavior here.

**Comment by ncdc** [comment]
Looking at a few scenarios:

1. Given a Cluster, Machine(s) for control plane, MachineDeployment(s) for workers:
    1. Delete Cluster
        1. Cluster controller starts deleting children & the sequencing is such that the Cluster is deleted before all the Machines are deleted (this issue)
        1. **Opinion**: if the Cluster is gone, blocking the deletion of the Machine is unnecessary

1. Given a Machine and nothing else:
    1. Delete Machine
        1. Fails because Cluster does not exist
        1. **Opinion**: if the Cluster is gone, blocking the deletion of the Machine is unnecessary

1. Given a Cluster, Machine(s) for control plane, MachineDeployment(s) for workers:
    1. Delete a single Machine
        1. Expectation is that Cluster exists so the MachineReconciler can talk to the workload cluster to delete the Node for this Machine
        1. **Opinion**: this is the happy path

Am I missing anything?

**Comment by detiber** [comment]
Does the issue stem from the way we are filtering "child" resources here?

Should we also ensure that we block on *any* `Machine*` resources that are associated with the `Cluster` rather than rather than just the direct children (while still only issuing deletes to direct children)?

**Comment by ncdc** [comment]
> Should we also ensure that we block on any Machine* resources that are associated with the Cluster rather than rather than just the direct children (while still only issuing deletes to direct children)?

That could be an improvement to the current logic. But I also think we need to allow Machine deletions when the Cluster doesn't exist.

**Comment by detiber** [comment]
> That could be an improvement to the current logic. But I also think we need to allow Machine deletions when the Cluster doesn't exist.

No objections there.

**Comment by ncdc** [comment]
https://github.com/kubernetes-sigs/cluster-api/issues/1649 to allow machine deletions when cluster is not there

**Comment by ncdc** [comment]
Ok, did some testing. The only time I was able to get the machine deletion to hang is with this flow:

1. Create machine
1. Create cluster
1. Remove cluster finalizers
1. Delete cluster
1. Try to delete machine

This simulates what is outlined in this issue, where the cluster accidentally gets deleted before all the machines. I think if we do what @detiber suggested, and block removing the cluster's finalizer if there are any descendants (direct or indirect), this should solve the problem. Thoughts?

**Comment by vincepri** [comment]
> block removing the cluster's finalizer if there are any descendants (direct or indirect), this should solve the problem

This is the solution I'd prefer, it's simple and expected behavior I'd say

**Comment by ncdc** [comment]
PTAL at #1650
