### ISSUE TITLE
RFE: CAPI failure domain & control plane support

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1647]
**User Story**

As a Cluster API operator I would like to have the control plane resource create Machines in different failure domains.

**Detailed Description**

The ControlPlane proposal offers a streamlined way to have control plane management in Cluster API. However, it does not support failure domains; this issue is an addendum to add basic support for failure domains to `ControlPlane` and `Machines`. 

**Contract changes**

- **Infrastructure providers [optional]**
   - During reconciliation, an infrastructure provider populates `Status.FailureDomains` in its cluster resource (e.g. `AcmeCluster`).
- **Cluster controller**
   - During reconciliation, the infrastructure provider object linked in `Cluster.Spec.InfrastructureRef` (if any) is parsed using unstructured object utilities. The reconciler parses and copies `Status.FailureDomains` from the InfrastructureCluster to Cluster.
- **Control Plane controller**
   - During reconciliation, the control plane controller takes `Cluster.Status.FailureDomains` slice, filters the ones that are applicable for control plane use, and picks one by some deterministic method.
   - The controller must take into account which machines have been created in which failure domain and evenly spread between all the available domains. 
   - If there are more replicas than available failure domains, the controller just cycles between the available one without erroring.

**Data model changes**

### FailureDomain
```golang
type FailureDomain struct {
  // Id is the unique identifier of this failure domain.
  Id string `json:"id"`

  // ControlPlane determines if this failure domain is suitable for use by control plane machines.
  // +optional
  ControlPlane bool `json:"controlPlane,omitempty"`

  // Attributes is a free form map of attributes an infrastructure provider might use.
  // +optional
  Attributes map[string]string `json:"attributes,omitempty"`
}
```

### ClusterStatus
```golang
type ClusterStatus struct
```
- **To add**
  - **FailureDomains [optional]**
    - Type: `[]FailureDomain`
    - Description: FailureDomains describes the available failure domains for the cluster to use.

### MachineSpec
```golang
type MachineSpec struct
```
- **To add**
  - **FailureDomain [optional]**
    - Type: `*FailureDomain`
    - Description: FailureDomain is the failure domain to be used for this Machine.

***Goals***
1. To allow a generic mechanism for the Control Plane controller to generate control plane machines that span multiple failure domains.
2. To avoid requiring user intervention at the Control Plane level to define the Control Plane's failure domains.
3. To allow infrastructure providers to indicate which failure domains are available for a given `Cluster`.

***Non-Goals / Future Work*** 
1. To support failure domains for `MachineSet` or `MachineDeployment`.

/kind proposal
/milestone v0.3.0
/priority important-soon

**Comment by alexbrand** [comment]
Is my understanding correct in that the goals here are:

1. The infrastructure providers "advertise" available failure domains via the Cluster resource
2. The ControlPlane controller reads the available failure domains from the Cluster resource
3. The ControlPlane controller creates ControlPlane machines in each failure domain

**Comment by detiber** [comment]
@alexbrand I would probably reword your 3rd goal to:
- The ControlPlane controller creates ControlPlane Machines, spreading them across the failure domains as evenly as possible

Depending on the scale of the ControlPlane or the number of failure domains it may not be possible to have a Machine in *each* failure domain, or it may require multiple machines in some failure domains. 

It may also be good to add an additional goal:
- The ControlPlane controller ensures ControlPlane Machines continue to be spread as evenly as possibly across failure domains during the process of an upgrade

**Comment by detiber** [comment]
@ncdc @vincepri how should we handle getting the details of the proposal documented in repo? It seems like data that we'd want to make sure is highlighted...  Maybe it's just a matter of updating the provider implementer docs for now, but I feel like we also need to capture the architectural details somewhere as well.

**Comment by ncdc** [comment]
@detiber I'd probably add content to the cluster infra provider spec doc describing failure domains, and probably talk about them in the control plane provider spec doc too. Would that suffice?

**Comment by vincepri** [comment]
Opened https://github.com/kubernetes-sigs/cluster-api/issues/1901
