### ISSUE TITLE
Support updating Status.InfrastructureReady on Cluster

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1657]
**Detailed Description**

Follow-up issue to #1622, the cluster controller should update `Status.InfrastructureReady` if the linked infrastructure reference `Status.Ready` changes.

/kind feature
/milestone v0.3.0
/priority important-longterm

**Comment by lubronzhan** [comment]
Hi @vincepri , should the controller also update the `status.conditions.InfrastructureReady` as well? I run into a strange situation when deleting a cluster. I have a finalizer that blocks deleting. And a controller should remove that finalizer if cluster is in `Ready` state, however I checked the cluster status, the cluster status is `Infrastructure Ready:  true`, but inside `status.conditions`, `InfrastructureReady` is false, thus making the ready condition false. So the deletion was stuck.

```
Status:
  Conditions:
    Last Transition Time:     2021-03-19T07:13:34Z
    Status:                   True
    Type:                     Ready
    Last Transition Time:     2021-03-22T06:47:27Z
    Message:                  Cleaning up the AVI load balancing resources before deletion
    Reason:                   AviResourceCleanup
    Severity:                 Info
    Status:                   False
    Type:                     AviResourceCleanupSucceeded
    Last Transition Time:     2021-03-22T06:47:21Z
    Message:                  Cleaning up the AVI load balancing user credentials before deletion
    Reason:                   AviResourceCleanup
    Severity:                 Info
    Status:                   False
    Type:                     AviUserCleanupSucceeded
    Last Transition Time:     2021-03-19T07:13:34Z
    Status:                   True
    Type:                     ControlPlaneReady
    Last Transition Time:     2021-03-19T07:03:56Z
    Status:                   True
    Type:                     InfrastructureReady
  Control Plane Initialized:  true
  Control Plane Ready:        true
  Infrastructure Ready:       true
  Observed Generation:        3
  Phase:                      Deleting
Events:                       <none>

```

K8S version: `v1.20.4`
IAAS: `vSphere`
CAPI version: `0.3.14`

**Comment by vincepri** [comment]
Hi @lubronzhan, we usually don't use closed issues. Could you please open a new one with the context above?

**Comment by lubronzhan** [comment]
Yeah sure thanks
