### ISSUE TITLE
Remove cluster != nil checks from codebase

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1667]
After #1539 has been merged, the Cluster object is now required, we should audit the codebase and remove any cluster check if nessary.

/kind cleanup
/milestone v0.3.0
/priority important-soon

**Comment by nader-ziada** [comment]
@vincepri are you already working on this, or can I take it? should be straight forward.

**Comment by vincepri** [comment]
I'm not, feel free to assign yourself to the issue :)

**Comment by vincepri** [comment]
Going to reopen this as there is more work that's going to be merged in that'll need some of this work as well

/reopen

**Comment by ncdc** [comment]
Done
/close
