### ISSUE TITLE
Rename ErrorMessage and ErrorReason to FailureMessage and FailureReason

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1670]
There is a lot of confusion when talking about these errors and why they're fatal errors. One possible solution is to improve the godoc around these fields and rename them to align them to the expected phase.

/kind cleanup
/priority backlog

**Comment by ncdc** [comment]
Gut reaction: sounds good

**Comment by vincepri** [comment]
/cc @noamran 

If you'd like to work on this, this task requires some documentation pieced and probably filing issues in each infrastructure provider repository tagged as v1alpha3
