### ISSUE TITLE
Support Tilt as dev environment

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1674]
**User Story**

As a developer I would like to have documentation on how to use tilt for fast development cycles.
As a developer I would like to have tilt files in CAPI repos to get up and running.

**Detailed Description**

This issue is to track the possibility to adopt Tilt as a development environment to simplify the dev experience for new contributors and existing ones. 

NB: This work is probably going to be best-effort support, it should be called out in any documentation we publish.

/kind feature
/help
/milestone Next
/priority backlog

**Comment by detiber** [comment]
Ideally, I think we should ship Tiltfile in repo that would work for development of CAPI. I believe this Tiltfile should focus on development against only the CAPI repo (as opposed to the current tilt environments such as https://github.com/chuckha/capi-dev and https://github.com/detiber/capi-dev).

**Comment by chuckha** [comment]
I recently updated capi-dev to work with v1alpha3 architecture, it's simplified a lot from before. 

cc @noamran because she's been using tilt a bit as well!

**Comment by noamran** [comment]
> I recently updated capi-dev to work with v1alpha3 architecture, it's simplified a lot from before.
> 
> cc @noamran because she's been using tilt a bit as well!

Yes! I have been using it too.

I can work on this issue (if that's OK).

**Comment by vincepri** [comment]
Go for it! If you'd like to chat more about it before hand, feel free to reach out

**Comment by noamran** [comment]
> Go for it! If you'd like to chat more about it before hand, feel free to reach out

I will. Thank you!

**Comment by vincepri** [comment]
Can this be closed @ncdc ?

**Comment by ncdc** [comment]
Yes!
/close
