### ISSUE TITLE
Profile Cluster API to provide guidelines on memory and cpu requirements

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1677]
- Document that users should set requests and limits. 
   - If we don't have recommended baseline values today, we should say so in the docs. 
   - Indicate that we plan to provide that data in the future after performing profiling.
- Perform profiling around memory and CPU usage and post results in this issue.
   - Add documentation on how to profile CAPI.
- Update YAML with baseline requests with a comment on how these were calculated.
   - We should target the 80% use case.
- Update the documentation with instructions on how to tune these values for different environments, which values to avoid (e.g. less than 1 CPU as limit).

/kind documentation
/milestone v0.3.0
/priority important-soon
/help

**Comment by ncdc** [comment]
Doing some milestone grooming. This is a nice to have IMHO.

/priority important-longterm
/milestone Next

**Comment by fabriziopandini** [comment]
closed in favour of https://github.com/kubernetes-sigs/cluster-api/issues/7308
