### ISSUE TITLE
clusterctl validate cluster

### ISSUE THREAD

**Issue by wangzhen127** [kubernetes-sigs/cluster-api#168]
Implement the client side cluster validation in clusterctl tool.

Design doc: https://docs.google.com/document/d/1e1ds0sdlGzC2U_DpSf5zWFYPlpPh5giyW8MXzhDthNk/

This issue tracks things that lives on the client side, i.e. checking the following things are running and healthy
- master node
- master components: kube api server, etcd, scheduler, etc
- Cluster API stack: cluster api server, controller manager, etcd for cluster api, etc

**Comment by wangzhen127** [comment]
/unassign @wangzhen127
There is still [some work left to validate the cluster itself](https://github.com/kubernetes-sigs/cluster-api/blob/master/clusterctl/cmd/validate_cluster.go#L72). Un-assign myself as I am currently busy on something else. I am happy to guide who ever pick this up later if needed.

**Comment by girikuncoro** [comment]
@wangzhen127 has anyone continue working on this? I'm happy to pick it up, if no one has not. would love to know how to start

**Comment by wangzhen127** [comment]
@girikuncoro, I haven't found time to push this forward. Feel free to pick it up. I am happy to review if needed.

**Comment by girikuncoro** [comment]
ok thanks @wangzhen127 I'll pick it up. any pointer to partial works that you have done? also in your comment https://github.com/kubernetes-sigs/cluster-api/issues/168#issuecomment-414002174, the link seems to be broken

**Comment by fanzhangio** [comment]
Assign this issue to @girikuncoro 
/assign @girikuncoro

**Comment by wangzhen127** [comment]
See https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/cmd/validate_cluster.go

**Comment by roberthbailey** [comment]
@wangzhen127 - is this something that you plan to finish or should we close this tracking issue?

**Comment by girikuncoro** [comment]
@roberthbailey sorry just found time to do it, I'll finish it off

**Comment by ncdc** [comment]
@wangzhen127 @detiber @vincepri @chuckha now that #679 is merged, should we close this, or is there more work left to do?

**Comment by wangzhen127** [comment]
We can close this now. Validation is a wide topic. If we want to extend existing checks to additional validations, we can open specific issues on those.
