### ISSUE TITLE
[capd] Better darwin support

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1685]
Our os x / darwin support is bad for capd at the moment.

Problem: CAPD creates a kubeconfig secret that uses the Docker network as the IP address. This address is not exposed directly on os x systems. This means when we use the kubeconfig secret from os x we end up not being able to connect.

Current solution: The current solution is to look up the 127.0.0.1 port (through docker) that the load balancer exposes that forwards to the nginx instance used as a load balancer. We then have to replace our kubeconfig secret and also remember to add 127.0.0.1 as an additional CertSAN.

Improvement proposal: The existing cluster object has an APIEndpoint on the docker network. In addition to this APIEndpoint, I propose we add a second APIEndpoint that is the 127.0.0.1 address that would work with os x. 

Unsure if having multiple APIEndpoints in the Cluster object would be bad. I don't think so, but if they are all expected to work then we'd run into issues.

The other idea I had, if we can't reuse the Cluster.Spec.APIEndpoints field is to add an annotation to the Cluster object with the darwin-friendly endpoint.

cc @detiber @fabriziopandini as I've had separate conversations with both about this in the past.

/kind feature

**Comment by fabriziopandini** [comment]
How do you envision using the second Cluster.Spec.APIEndpoints?

**Comment by chuckha** [comment]
Both very reasonable suggestions. Probably easier in general than the proposal here. I'd be most inclined to a field on the DockerCluster so it can be ignored or used if needed. There is no additional cruft, like an extra secret floating around.

**Comment by vincepri** [comment]
/close

Closing this for now, given that documentation covers how to deal with CAPD on MacOS and CAPD is mostly for dev purposes
