### ISSUE TITLE
Refactor MachineSet reconciler to be consistent with Cluster and Machine patterns

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1689]
We rewrote the Cluster and Machine controllers in v1alpha2 using new patterns and conventions. For example, we use a `defer` statement with our patch helper to ensure the object being reconciled is always patched to persist whatever changes we made when reconciling.

We should update the MachineSet reconciler to follow these patterns.

/priority important-longterm
/kind cleanup

**Comment by vincepri** [comment]
@srm09 Are you still working on this issue?

**Comment by srm09** [comment]
Yes @vincepri 
I would be creating a PR soon enough.
