### ISSUE TITLE
Refactor MachineDeployment reconciler to be consistent with Cluster and Machine patterns

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1690]
We rewrote the Cluster and Machine controllers in v1alpha2 using new patterns and conventions. For example, we use a defer statement with our patch helper to ensure the object being reconciled is always patched to persist whatever changes we made when reconciling.

We should update the MachineDeployment reconciler to follow these patterns.

/priority important-longterm
/kind cleanup

**Comment by srm09** [comment]
After @vincepri 's PR linked above, is this issue still relevant? Atleast the point made in the description seems to be taken care of.

**Comment by vincepri** [comment]
/close

This has been done
