### ISSUE TITLE
Shellcheck verification is not working locally

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1693]
**What steps did you take and what happened:**
Run `make verify`

**What did you expect to happen:**
Shellcheck verification step to succeed, instead an error shows up:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1460k  100 1460k    0     0  4320k      0 --:--:-- --:--:-- --:--:-- 4320k
curl: (6) Could not resolve host: shellcheck-v0.7.0.darwin.x86_64.tar.xz
```

/kind bug

**Comment by prankul88** [comment]
I will take this up!

**Comment by ashish-amarnath** [comment]
Could you also please uncomment https://github.com/kubernetes-sigs/cluster-api/blob/master/hack/verify-shellcheck.sh#L16

**Comment by prankul88** [comment]
> Could you also please uncomment https://github.com/kubernetes-sigs/cluster-api/blob/master/hack/verify-shellcheck.sh#L16

@ashish-amarnath Sure, I will update. Thanks
