### ISSUE TITLE
Apply labels to Machines if they're part of a MD or MS

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1695]
**User Story**

As a user I would like to be able to quickly filter all Machines that are part of a MachineDeployment or MachineSet.

**Detailed Description**

We can adopt two new labels `cluster.x-k8s.io/deployment-name` and `cluster.x-k8s.io/set-name` (naming TBD, just an example) with the respective value being either the MD or MS names. 

/kind feature
/help
/priority important-longterm

**Comment by detiber** [comment]
If we do this, in addition to the `cluster.x-k8s.io/cluster-name` label, we could potentially remove the label selectors from the specs and simplify the definitions of MS and MD resources.
