### ISSUE TITLE
util.IsControlPlaneMachine(machine *clusterv1.Machine) is true if the label value is "false"

### ISSUE THREAD

**Issue by thebsdbox** [kubernetes-sigs/cluster-api#1697]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
As far as I understand it, for a control plane `machine` we set a label `cluster.x-k8s.io/control-plane: "true"`, I would presume that for a worker node we would set the label as false, or at least could do?

However the check for this label to be determined true is that the label isn't empty, so  `cluster.x-k8s.io/control-plane: "false"` is actually `true`. 

**What did you expect to happen:**
`false` to mean `false`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 0.2.6
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): 1.14.x
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by detiber** [comment]
In reality, we could probably just use the existence of the key to indicate control plane, and update all existing uses of the label to just use `""`

**Comment by vincepri** [comment]
I'd change the logic to return false iff the label doesn't exist or the value is anything other than `true`
