### ISSUE TITLE
Support multiple providers for cluster bootstrapping

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#17]
_From @rsdcastro on January 29, 2018 21:45_

Currently only GCP is supported. This item is about - more easily - supporting other providers when bootstrapping a cluster.

_Copied from original issue: kubernetes/kube-deploy#524_

**Comment by rsdcastro** [comment]
This could include defining an interface and/or documentation. The goal is that anyone implementing a new provider knows that they would need to implement the bootstrapping story as well (assuming we keep the current implementation of starting an instance to install the controller as default). @krousey @karan

**Comment by rsdcastro** [comment]
_From @karan on January 31, 2018 18:8_

Related #550

**Comment by rsdcastro** [comment]
As supporting more providers is out of scope for alpha, moving it to beta.

**Comment by roberthbailey** [comment]
We currently support gcp + vsphere and we are adding support (out of tree) for openstack, aws, etc. Marking as fixed.

/close
