### ISSUE TITLE
🐛CAPD `./test/infrastructure/docker/hack/verify-docker-build.sh` fails

### ISSUE THREAD

**Issue by ashish-amarnath** [kubernetes-sigs/cluster-api#1716]
**What steps did you take and what happened:**
Run `./test/infrastructure/docker/hack/verify-docker-build.sh`

**What did you expect to happen:**
Building CAPD manager image should have been successful.

**Anything else you would like to add:**
`./test/infrastructure/docker/hack/verify-docker-build.sh` fails like 

```
Step 7/16 : RUN go mod download
 ---> Using cache
 ---> 7df08f81d163
Step 8/16 : RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o manager main.go
 ---> Running in 6d1054e84d92
$GOPATH/go.mod exists but should not
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o manager main.go' returned a non-zero code: 1

```

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
/assign

**Comment by chuckha** [comment]
I cannot reproduce, this script worked for me.

@ashish-amarnath can you try again on mater? If it still fails I'm guessing there's something weird going on with your environment.

/priority awaiting-more-evidence
/remove-priority important-soon

**Comment by ashish-amarnath** [comment]
This seems to be local to my branch and not on master. A side-effect of some change I suppose. I'll fix my branch.

/close
