### ISSUE TITLE
remains orphan resources with no machine refer to

### ISSUE THREAD

**Issue by xrmzju** [kubernetes-sigs/cluster-api#1718]
**What steps did you take and what happened:**
~~we intend to create 3 object in [one replica reconcile process](https://github.com/kubernetes-sigs/cluster-api/blob/f869765493749d60c4e75afc59e7ddc3bdfc1c2e/controllers/machineset_controller.go#L249).if  infraConfig  and bootstrapConfig create success and machine create failed,  then bootstrapConfig and infraConfig will be left there forever..~~

forgive me miss the delete part in [L303](https://github.com/kubernetes-sigs/cluster-api/blob/f869765493749d60c4e75afc59e7ddc3bdfc1c2e/controllers/machineset_controller.go#L303), but i do see  a lot of bootstrap remains in my env, i doubt the scale down action delete the machine only, but remains the gc controller to delete the infraconfig and bootstrapconfig, but if the machine has not been handled by machine controller, then no ownerRef would be set on infra config and bootstrap config, then the orphan object remains
**What did you expect to happen:**
scale a machineset with 10 replicas should means 10 infraConfigs,10 bootstrapConfigs and 10 machines, we only ensure 10 machines in our logic.

/kind bug

**Comment by xrmzju** [comment]
@detiber @ncdc @vincepri

**Comment by vincepri** [comment]
@xrmzju What version of Cluster API are you using?

**Comment by ncdc** [comment]
@xrmzju is this still an issue for you?

**Comment by ncdc** [comment]
Doing some milestone grooming. We can bring this back if we hear back.

/milestone Next

**Comment by vincepri** [comment]
This is gonna be fixed in https://github.com/kubernetes-sigs/cluster-api/pull/1947

**Comment by vincepri** [comment]
or at least part of it

**Comment by vincepri** [comment]
Closing this for now, feel free to reopen if necessary

/close
