### ISSUE TITLE
Cluster status phase should be provisioned after an API server endpoint is available

### ISSUE THREAD

**Issue by vijaykatam** [kubernetes-sigs/cluster-api#1722]
**What steps did you take and what happened:**
1. Create custom resources for Cluster, Machine and provider specific resources.
2. As soon as infrastructure provider sets `InfrastructureReady` to true, the status of Cluster object changes to `Provisioned`.

**What did you expect to happen:**
I was expecting Cluster status to be in Provisioning until an API endpoint is available.

**Anything else you would like to add:**
`InfrastructureReady` is used by bootstrap provider (CABPK) and now part of cluster-api to whether or not set `Bootstrap.Data` on the corresponding Machine object and isn't by itself an indicator of cluster status.

**Environment:**

- Cluster-api version: Tested with v1alphav2 but the same issue exists in master branch as well.
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): 1.15.1
- OS (e.g. from `/etc/os-release`): VMware Photon OS

/kind bug

**Comment by vincepri** [comment]
I'm not opposed to the change, seems only cosmetic / quality of life. I'd like to check in with @akutz though first to make sure they're on board with this approach.

**Comment by vincepri** [comment]
We'll need to update the appropriate documentation as well https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/providers/v1alpha2-to-v1alpha3.md and describe the change

**Comment by vijaykatam** [comment]
@vincepri added doc for the change.
