### ISSUE TITLE
Controlplane machines created after deleting a controlplane machine are in pending forever

### ISSUE THREAD

**Issue by sirao** [kubernetes-sigs/cluster-api#1723]
**What steps did you take and what happened:**
1. Create the management cluster
2. Create Cluster API infrastructure
3. Create CABPK infrastructure
4. Create AWS user stack
5. Set AWS Credentials as Environment variables
6. Create CAPA infrastructure
7. Create Cluster [cluster1.txt](https://github.com/kubernetes-sigs/cluster-api/files/3813055/cluster1.txt)
8. Create controlplane machine 0 [controlplane1.txt](https://github.com/kubernetes-sigs/cluster-api/files/3813058/controlplane1.txt)
9. Create controlplane machine 1 [controlplane-test-kr-1.txt](https://github.com/kubernetes-sigs/cluster-api/files/3813056/controlplane-test-kr-1.txt)
10. Delete controlplane machine 1 after it coming to running state
11. Create controlplane machine 2 [controlplane-test-kr-2.txt](https://github.com/kubernetes-sigs/cluster-api/files/3813057/controlplane-test-kr-2.txt)

**What did you expect to happen:**
ControlPlane machine creation should up provisioned and running

**Anything else you would like to add:**
[cabpk-log.txt](https://github.com/kubernetes-sigs/cluster-api/files/3813082/cabpk-log.txt)
[capa-log.txt](https://github.com/kubernetes-sigs/cluster-api/files/3813083/capa-log.txt)
[capi-log.txt](https://github.com/kubernetes-sigs/cluster-api/files/3813084/capi-log.txt)

**Environment:**

- Cluster-api version: 0.2.6
- Minikube/KIND version: v0.5.1
- Kubernetes version: (use `kubectl version`): Client v1.13.3, Server v1.15.3
- OS (e.g. from `/etc/os-release`): darwin 64bit

/kind bug

**Comment by ncdc** [comment]
Cluster API v0.2.x (v1alpha2) does not support removing control plane machines without some additional work to make sure you maintain etcd quorum. We should be able to address this when we implement the KubeadmControlPlane proposed in #1613 

cc @detiber @randomvariable

**Comment by randomvariable** [comment]
Notes from meeting:
@detiber : Should be addressed by #1613
