### ISSUE TITLE
Add specification document for machine infrastructure provider

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1725]
We should add a specification document for what a machine infrastructure provider must do. For example, something like:

- A machine infrastructure provider must provide a CustomResourceDefinition to represent provider-specific details for machine infrastructure. For example, if your provider is Acme, a reasonable name for the CRD might be AcmeMachine.
- The CRD must have spec and status
- The CRD's status must have the following fields
    - Ready
    - ...
- A machine infrastructure provider must reconcile its custom resources
    - ... Define required behaviors ...

etc.

/kind documentation
/priority important-soon
/milestone v0.3.0

**Comment by chuckha** [comment]
Most of this is covered https://cluster-api.sigs.k8s.io/architecture/controllers/machine.html

**Comment by ncdc** [comment]
I'll probably work on adapting it to a slightly different format. Thanks.
