### ISSUE TITLE
Add GCP provider instructions to docs

### ISSUE THREAD

**Issue by rsmitty** [kubernetes-sigs/cluster-api#1731]
**User Story**

As a user, I'd like to be able to quickly grab the GCP deploy commands from the getting started page.

**Detailed Description**

Add GCP instructions based on the latest release of the gcp infrastructure provider so that we can quickly deploy capg components.

**Anything else you would like to add:**

I'll take this on, just wanted to create a new issue for it to track it.

/kind feature

**Comment by nader-ziada** [comment]
There is a similar issue in the `cluster-api-provider-gcp`repo https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/151

**Comment by wfernandes** [comment]
/kind documentation
Feel free to mark it `/lifecycle active` whenever you start working on this. Also thanks for doing this!
