### ISSUE TITLE
Issue with Cluster-API using Docker provider

### ISSUE THREAD

**Issue by sb1975** [kubernetes-sigs/cluster-api#1735]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
GO111MODULE="on" go get sigs.k8s.io/kind@v0.5.1
  182  cat > kind-cluster-with-extramounts.yaml <<EOF
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
EOF

  183  kind create cluster --config ./kind-cluster-with-extramounts.yaml --name clusterapi
  184  export KUBECONFIG="$(kind get kubeconfig-path --name="clusterapi")"
197  kind create cluster --config ./kind-cluster-with-extramounts.yaml --name clusterapi
  198  export KUBECONFIG="$(kind get kubeconfig-path --name="clusterapi")"
  199  kubectl get nodes
  200  kubectl create -f https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.2.6/cluster-api-components.yaml
  201  kubectl get all
  202  kubectl get all --all-namespaces
  203  kubectl create -f https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/releases/download/v0.1.5/bootstrap-components.yaml
  204  kubectl create -f https://github.com/kubernetes-sigs/cluster-api-provider-docker/releases/download/v0.2.1/provider_components.yaml
  205  kubectl create -f https://github.com/kubernetes-sigs/cluster-api-provider-docker/releases/download/v0.2.1/provider-components.yaml
214  cat > cluster.yaml <<EOF
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: capi-quickstart
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: DockerCluster
    name: capi-quickstart
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: DockerCluster
metadata:
  name: capi-quickstart
EOF

  215  cat cluster.yaml
  216  kubectl apply -f cluster.yaml
  217  cat > machine.yaml <<EOF
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  name: capi-quickstart-controlplane-0
  labels:
    cluster.x-k8s.io/control-plane: "true"
    cluster.x-k8s.io/cluster-name: "capi-quickstart"
spec:
  version: v1.15.3
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: KubeadmConfig
      name: capi-quickstart-controlplane-0
  infrastructureRef:
    kind: DockerMachine
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    name: capi-quickstart-controlplane-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: DockerMachine
metadata:
  name: capi-quickstart-controlplane-0
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  name: capi-quickstart-controlplane-0
spec:
  initConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        # Default thresholds are higher to provide a buffer before resources
        # are completely depleted, at the cost of requiring more total
        # resources. These low thresholds allow running with fewer resources.
        # Appropriate for testing or development only.
        eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
  clusterConfiguration:
    controllerManager:
      extraArgs:
        # Enables dynamic storage provisioning without a cloud provider.
        # Appropriate for testing or development only.
        enable-hostpath-provisioner: "true"
EOF

  218  kubectl apply -f machine.yaml
  219  kubectl --namespace=default get secret/capi-quickstart-kubeconfig -o json   | jq -r .data.value   | base64 --decode   > ./capi-quickstart.kubeconfig
  220  apt install jq -y
  221  kubectl --namespace=default get secret/capi-quickstart-kubeconfig -o json   | jq -r .data.value   | base64 --decode   > ./capi-quickstart.kubeconfig
  222  kubectl --kubeconfig=./capi-quickstart.kubeconfig   apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml

unable to recognize "https://docs.projectcalico.org/v3.8/manifests/calico.yaml": Get https://                                                                                                               172.17.0.3:6443/api?timeout=32s: EOF
unable to recognize "https://docs.projectcalico.org/v3.8/manifests/calico.yaml": Get https://                                                                                                               172.17.0.3:6443/api?timeout=32s: EOF
unable to recognize "https://docs.projectcalico.org/v3.8/manifests/calico.yaml": an error on                                                                                                                the server ("") has prevented the request from succeeding
unable to recognize "https://docs.projectcalico.org/v3.8/manifests/calico.yaml": an error on                                                                                                                the server ("") has prevented the request from succeeding
unable to recognize "https://docs.projectcalico.org/v3.8/manifests/calico.yaml": an error on                                                                                                                the server ("") has prevented the request from succeeding

# cat capi-quickstart.kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5ekNDQWJPZ0F3SUJBZ                                                                                                               0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1URXdOek                                                                                                               U1TWpFeE9Gb1hEVEk1TVRFd05ERTVNall4T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVl                                                                                                               KS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSytwCkxGZzN5QzlCQzdyK2tIQk5kUmh4RWpqS2poYkNwVkl3                                                                                                               QXVOY1lzZ08wUUUrRUtndnVqa0pQekhUakpNTGNOVlkKNktKcW9hZ3g3akowL3YwSlhJYmFLQkJJVkQwOXphVkFCTHRTY                                                                                                               lJNVkxCZkw1aTYrT0NVUzVrU0ZHRyt2N1ljcApmZ0ZCZFErWU4yRUFoejNIMGJheGVRSXI3UllEY2NtbXBaREtOL2l4Qk                                                                                                               dkYWF3WEE0SE5OSFhFb0NmTVgwbVQ2Cm5VZmtVMGo4dlZhd0xvOTlpZE43OWIyMmpJMVl2Umd3T0Y0bm9QeEtVN2NWL29                                                                                                               NL012YjErQmtsTDkyMkxBUlQKb0VEZlFKbUhTOFIrTlNEbHhDQ003L1MyZGx6RHJocUNYd2RBRmVlblhjekpQVzdIbG1u                                                                                                               Qkk3Y2x3ZUlxMVArcwppSXhRNWtvY1JrTHNxcm1xSkVjQ0F3RUFBYU1tTUNRd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR                                                                                                               0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRGsrZXoxc05yQmN2OVdPcG1RYz                                                                                                               hnckkKelVFRFBJTm1OYjJCQ2kyODliVkROSTdnbFUxTDJVV3phUXdUMGE2WXJXellDaWZLRXppbi9TTXlkMGREVnRoeQp                                                                                                               4RlBMQ2ZnVFRKdE0yRkQ0aitRaCtWYndIY0N3V2R6OVpBMHkrZmlrOU5CM3ZOeFdlV1FlRUMzRVV4RUFvSnJPCjlYUGFU                                                                                                               TWRvSDJQdFVxMDhzaTlDNzlxSExqbmk4MmRjVUdqNWIwK3VRWlJuYnN0S2JjTTltK0ZkZlByaTNoMG0KS214UVBxUjhqO                                                                                                               FAzMUNucjQ4ZnhoUG5TTk5rd2ZwaFd4aW1MSS9QYW1TZnlhQUFmK0FoQVo4WVA3UEJrdmRISQppK2toZUQ4Umtvc3ZtM2                                                                                                               5vOWlRQzRTTDE0eU15TVdBanhyVzFFWkMvdkNsNXlaUlVMb0lEWnNSQVBNSkNBbVk9Ci0tLS0tRU5EIENFUlRJRklDQVR                                                                                                               FLS0tLS0K
    server: https://172.17.0.3:6443
  name: capi-quickstart
contexts:
- context:
    cluster: capi-quickstart
    user: kubernetes-admin
  name: kubernetes-admin@capi-quickstart
current-context: kubernetes-admin@capi-quickstart
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4VENDQWRtZ0F3SUJBZ0lI                                                                                                               V2gxSEJiSEpBREFOQmdrcWhraUc5dzBCQVFzRkFEQVZNUk13RVFZRFZRUUQKRXdwcmRXSmxjbTVsZEdWek1CNFhEVEU1T                                                                                                               VRFd056RTVNakV4T0ZvWERUSXdNVEV3TmpFNU1qWXpPVm93TkRFWApNQlVHQTFVRUNoTU9jM2x6ZEdWdE9tMWhjM1JsY2                                                                                                               5NeEdUQVhCZ05WQkFNVEVHdDFZbVZ5Ym1WMFpYTXRZV1J0CmFXNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHd                                                                                                               Bd2dnRUtBb0lCQVFDc2tFekZMZmYwQ3dlWm01ajkKaVFOMXRQT1VpY0F1cjAwV3BzazEwcUVseWJhbU1HZU5zS0x6ZVNl                                                                                                               Vk1JNHdUcTBNdDc0N2xWTGpaWjNHanRldQpPdVkxK2FTNDhpc0JSZzJvbG5wS2dHZG5Ca3BlVkd6ZGpJcGM0U1hsZHdEQ                                                                                                               jBEYjhrdDkwNjd3ZVpaaHZoWHhxCmxzWUpqaktFcnlIZUNJRURFYmIycEZ6SzBLNTJSTHF4d2VYYmdFTzM5MUE1WFF5cD                                                                                                               hUTG1sT1hGTjNDcit4REYKSGZzRzBDR0M0MDNxYVo0TWtLbDJMYnFyT3podWZnZnR4U0g0dUFPTUQ3a0JIcmNHZTVseVV                                                                                                               CWEtCeXAwT1BNUwpSNERMQ1BHVDc4ZWpmUkNZRXpzcnI1bW54WmFiYjc3ZUhCa1Z4ZFgxaGZkb3cyMHNhcmpGTUFLczUv                                                                                                               b3BGK1RuClIwaVpBZ01CQUFHakp6QWxNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY                                                                                                               0QKQWpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWZTcjlpU2g1bE00OFFnTzBGOU42aFI1dU1NY0d3ZXlJMUZySgo5Sl                                                                                                               FNR09UbFNsVFdyeUlnUU9veGhaL1B1QVllWWZJSWJiUndlNjkrUnhEN1pPekxwUjlDK3lGRXhWOXlkZGJVCm14dHMxc2t                                                                                                               DZWlDT2U5dWtEVTBKUm5nZ1hqR2taQ0tzSWdzVjMyRm9iQVh6cFRVOFNJN0VwK0xHMXZZQXE3eGQKM2svT25GVGRwUFZQ                                                                                                               RDZqQ3dqVDliVmdkSThGeVJ1ZmlYMVVuRVdXaDFvS2lFYWhPWmJmQlgyVE5YT3gweWNtNwp4YnZJTzlEVFVYdEI5M3FuM                                                                                                               WJtanp2S0Y1YVNQV3E4L2FiT1FTUndaZVRYT1dPdzRuVUh4UnBzM09BNTRMTEFuCm90OXpIQmNYdGNWakt4T1grMW9hOT                                                                                                               RycVVQM01JcXlpMGx4VkRoUURPbmN6Nmlyb3NnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBckpCTXhT                                                                                                               MzM5QXNIbVp1WS9Za0RkYlR6bEluQUxxOU5GcWJKTmRLaEpjbTJwakJuCmpiQ2k4M2tubFRDT01FNnRETGUrTzVWUzQyV                                                                                                               2R4bzdYcmpybU5mbWt1UElyQVVZTnFKWjZTb0JuWndaS1hsUnMKM1l5S1hPRWw1WGNBd2RBMi9KTGZkT3U4SG1XWWI0Vj                                                                                                               hhcGJHQ1k0eWhLOGgzZ2lCQXhHMjlxUmN5dEN1ZGtTNgpzY0hsMjRCRHQvZFFPVjBNcWZFeTVwVGx4VGR3cS9zUXhSMzd                                                                                                               CdEFoZ3VOTjZtbWVESkNwZGkyNnF6czRibjRICjdjVWgrTGdEakErNUFSNjNCbnVaY2xBVnlnY3FkRGp6RWtlQXl3anhr                                                                                                               Ky9IbzMwUW1CTTdLNitacDhXV20yKysKM2h3WkZjWFY5WVgzYU1OdExHcTR4VEFDck9mNktSZms1MGRJbVFJREFRQUJBb                                                                                                               0lCQUc0U3JhV3BLTnpXbkVaegpaaWR6V20yZXV6RW9uUm9xWC9YdTliSUxaUmVCajZ4NmU5TjV0TGV4dEhvSnV1azloa3                                                                                                               p5ZDdueUNpbGJERVUzCm9JUld0Ym9BUC81cEd0MTVIZ1ZIMTBIbW5nNnRpSXFiTjhZcWU2ZTdSajBVcDdyNVlkbkNwaDh                                                                                                               pcjZDRUZiUXQKWmF0bitYTG03WHFOYkFFQlU2bnRodFBWREF1aC9VTWRZQ09MSjMvRWloeDBmM2V3Z1dCUURwaDl6Mlk3                                                                                                               OFdkMQp2REZ0YXBQbTRCRWJVeVY4WDlGWkxsK2FYRW5WM2M5T2ZUMmJrNG5DUTFxdlR3VVJNOFIrR0dIcGNjNWpQVm9rC                                                                                                               nk0NUcvNTAwK0xaWW01bmZwbkxEeW40OFo0cUZHd3RVR2llWWVwc3R4VXQwalZkTHRJRGZGYUxNZ1M5NTd3S1YKVE1oQ3                                                                                                               lnRUNnWUVBMGlzWE9yMHl4SjF4dkVRaHlqYks4ZTNCa3ZQcU9xek9pcCtYVUNrT2UyUFpqT2oxMlFCdwo4OVF0UUZKWnZ                                                                                                               FY3R3RGZmMUZFdUZPMG9KVkdFZWE3VGFuVVFIOXpiZ2RvejB5RVAwcWlWRzBSLzlEWU9hcFFqCkJlajlqQ1E0Z1VWS3JR                                                                                                               REg2Q1prTjZsTTc5S0pmQ2NYNGRKUVlBWnlRck9Ya2tFay9ubE94ZWtDZ1lFQTBqSGgKNlhtcnNucys1VS91dXNXTm5ZS                                                                                                               2pURkZXb0RIWEFjNGd3b3pFQVErODNxelJNQWMvQWVEV0ROeUsyZjFhODBVMwpIMGV2T0lRZDNEMGZ4clJZNmRFMzlMNz                                                                                                               JzczFINUNPL3lWekZyL0RkajJNZFBoVXZxYmVGbUVqL0xoZ1ZoRnpQCmNFRjg3blVSV3NhTjU2eHAvd29nM3gxVUxPZUp                                                                                                               NZmJkVXR4TXp6RUNnWUVBbW1HMjNab1BTZWhSbkxiN2p6dnkKbGdaTk5ISmg4NW51Mmx0aTNpcGFqZjhKMW4xbDRuSjFo                                                                                                               bGFzcXR3VE9MK2NkdDlVVnZVUEFhWTM0RG5pTXpSZAo3b3h4UE1hU28rOHlOSHZMMExXdldlbFdpSUNRMUc5ZXpyK1lTR                                                                                                               Ep2STE1UC9ZZGVVVVNxUjB6Z3pDWCtnaW1CClhJdU9LUXR6TVZZVkdBVXNkSldOYk1rQ2dZQUVtV2JTRHdGOHhFbWFCdW                                                                                                               U0V241QXhnMEFySDd5dm1Sdis2eW4KMVNDc3pVVmFzZmxaemE3SlFid3RSOTRaNnZ0RWUyMDdWL3d6aG1DSTR5V0EyWTF                                                                                                               nZ0YxekU0S2VZdk9Cd0c1LwozM0hMNmI5UFZlSGI2K2JCRmV6c2FoeDdTN2VjejlNU0o3eXVFdzJ3S013T0Y2MnlFT3ly                                                                                                               TlI4VVpIU1NEVTdHCmMxK1M0UUtCZ1FETllNa25rMVJrbmxzWllGdHZxdnVNb2xFNUoxWDdXMWhyU1JwaFY0L0RRY0MzU                                                                                                               VV1OWFmeXcKTGJuTFBySDhhQzZKZnYvQ3NpN2J2VEpYNHpsWUxXbDB6dDBNSUd3QitzbEYzMXluOGk5eFhHZEVsT01vTU                                                                                                               o3YQpRbWhqMnpHelNtMWhnVnpnd2F0YTlKMTQ0bHZMVkM0S3B3eXBsdWRvcWJuUGdZaWM3MjBVTkE9PQotLS0tLUVORCB                                                                                                               SU0EgUFJJVkFURSBLRVktLS0tLQo=
root@kubebuilder:~# kubectl --kubeconfig=./capi-quickstart.kubeconfig  get nodes
Unable to connect to the server: EOF

# kubectl describe cluster
Name:         capi-quickstart
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"cluster.x-k8s.io/v1alpha2","kind":"Cluster","metadata":{"annotations":{},"name":"capi-quickstart","namespace":"default"},"s...
API Version:  cluster.x-k8s.io/v1alpha2
Kind:         Cluster
Metadata:
  Creation Timestamp:  2019-11-07T19:25:36Z
  Finalizers:
    cluster.cluster.x-k8s.io
  Generation:        1
  Resource Version:  15043
  Self Link:         /apis/cluster.x-k8s.io/v1alpha2/namespaces/default/clusters/capi-quickstart
  UID:               1eee79e6-51ea-45c3-ab77-45ff902f79e3
Spec:
  Cluster Network:
    Pods:
      Cidr Blocks:
        192.168.0.0/16
  Infrastructure Ref:
    API Version:  infrastructure.cluster.x-k8s.io/v1alpha2
    Kind:         DockerCluster
    Name:         capi-quickstart
Status:
  API Endpoints:
    Host:                172.17.0.3
    Port:                6443
  Infrastructure Ready:  true
  Phase:                 provisioned
Events:                  <none>

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version: ~# kind version
v0.5.1

- Kubernetes version: (use `kubectl version`): 
# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T18:57:36Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): ubuntu 16.04

/kind bug

**Comment by ncdc** [comment]
@sb1975 is this something you can consistently reproduce?

**Comment by sb1975** [comment]
it did work when I tried again.
So I will close this.
Now I am looking at complex scenarios, but will raise that separately.
Thank you :)

Commands for Reference : 
1  GO111MODULE="on" go get sigs.k8s.io/kind@v0.5.1
    2  cat > kind-cluster-with-extramounts.yaml <<EOF
    3  kind: Cluster
    4  apiVersion: kind.sigs.k8s.io/v1alpha3
    5  nodes:
    6  - role: control-plane
    7    extraMounts:
    8      - hostPath: /var/run/docker.sock
    9        containerPath: /var/run/docker.sock
   10  EOF
   16  export PATH=$PATH:/root/go/bin/
   22  apt-get update -y
   23  apt install docker.io
   24  kind create cluster --config ./kind-cluster-with-extramounts.yaml --name clusterapi
   25  export KUBECONFIG="$(kind get kubeconfig-path --name="clusterapi")"
   26  kubectl cluster-info
   27  kubectl version
   28  kubectl create -f https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.2.7/cluster-api-components.yaml
   29  kubectl create -f https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/releases/download/v0.1.5/bootstrap-components.yaml
   30  kubectl create -f https://github.com/kubernetes-sigs/cluster-api-provider-docker/releases/download/v0.2.1/provider-components.yaml
   31  vi cluster.yaml
   32  kubectl apply -f cluster.yaml
   33  vi machine.yaml
   34  kubectl apply -f machine.yaml
   36  apt install jq -y
   37  kubectl --namespace=default get secret/capi-quickstart-kubeconfig -o json   | jq -r .data.value   | base64 --decode   > ./capi-quickstart.kubeconfig
   39  kubectl --kubeconfig=./capi-quickstart.kubeconfig   apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml
   40  kubectl --kubeconfig=./capi-quickstart.kubeconfig get nodes
   43  vi machinedeployment.yaml
   44  kubectl apply -f machinedeployment.yaml
   45  kubectl --kubeconfig=./capi-quickstart.kubeconfig get nodes

**Comment by sb1975** [comment]
root@capd:~# kubectl create --kubeconfig=./capi-quickstart.kubeconfig namespace mynamespace
namespace/mynamespace created
root@capd:~#
root@capd:~# kubectl --kubeconfig=./capi-quickstart.kubeconfig run nginx --image=nginx --restart=Never -n mynamespace
pod/nginx created
root@capd:~#
root@capd:~#
root@capd:~# kubectl --kubeconfig=./capi-quickstart.kubeconfig get pods -n mynamespace
NAME    READY   STATUS    RESTARTS   AGE
nginx   1/1     Running   0          14s
root@capd:~#
root@capd:~#
root@capd:~# kubectl --kubeconfig=./capi-quickstart.kubeconfig get pods -n mynamespace -o wide
NAME    READY   STATUS    RESTARTS   AGE   IP               NODE                                                      NOMINATED NODE   READINESS GATES
nginx   1/1     Running   0          25s   192.168.61.193   capi-quickstart-capi-quickstart-worker-85cbf8fd8c-mpr2l   <none>           <none>
