### ISSUE TITLE
Document approaches for infrastructure providers to consider for securing sensitive bootstrap data

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1739]
**User Story**

As a user/operator, I would like to avoid exposing sensitive data (such as certificate private keys) in hypervisor bootstrap data to minimize attack surfaces.

**Detailed Description**

CAPI generates sensitive cluster data (such as private keys) for the apiserver, etcd, etc. These are stored as secrets in Kubernetes. The kubeadm bootstrapper copies the contents of the secrets into bootstrap data in the KubeadmConfig resource, which is then copied into the Machine resource. Infrastructure providers such as CAPA and CAPV (and presumably others that use cloud-init style bootstrap data) use this bootstrap data as the user data for the VM/hypervisor. In many/most instances, if a user has read-only access to the VM in the provider's API (such as AWS's ec2:DescribeInstances permission), this likely grants them access to the user data, and therefore access to the sensitive data.

Ideally, the VM itself has permission to read the sensitive data, but a user with cloud provider API access to the VM must not be able to do so.

The method used to secure this sensitive data is likely specific to each infrastructure provider. We should document what types of mechanisms to look for (such as a secure data store) so the developers of an infrastructure provider can implement this functionality.

/kind documentation
/priority important-soon
/milestone v0.3.0

cc @akutz @detiber @randomvariable

**Comment by detiber** [comment]
@ncdc I would also probably add that beyond just the secrets injected during init, the bootstrap tokens and encryption key (for control plane) that we inject for join also fall under this category as well.

**Comment by ncdc** [comment]
Right, I meant to mention the bootstrap tokens too. What encryption key are you referring to?

**Comment by detiber** [comment]
Ah, I didn't realize we were still injecting the CA and service account keypairs instead of leveraging the ability to transfer the secrets using kubeadm.

**Comment by randomvariable** [comment]
We need to do the injection in any case for the initial control plane node.

**Comment by alexeldeib** [comment]
this and https://github.com/kubernetes-sigs/cluster-api/issues/1846 are very similar/dupes

**Comment by alexeldeib** [comment]
@vincepri @fabriziopandini Started a doc and expanded on the existing PR. The doc is fairly short right now, I mostly wanted to highlight the API types and how the implementation would change from https://github.com/kubernetes-sigs/cluster-api/pull/1860

https://github.com/kubernetes-sigs/cluster-api/pull/3038

https://docs.google.com/document/d/1R_E3uu8Uvfe4pOcTrfQYUolJCK8mUS58Kq4A8zmqTr8/edit?usp=sharing

**Comment by randomvariable** [comment]
Important to note that the history of this also included advising people to use provider specific features where necessary, for example https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1490 and https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/582

**Comment by alexeldeib** [comment]
Ah, I see there are two side to this issue:
- Bootstrap provider needs secure sources for data (what i'm tackling)
- Infrastructure providers may need a secure place to put that data (the issues you linked)

Perhaps i'll reopen one of the other issues I closed as dupes to reflect the work more accurately, as those are better aligned to the task. But i'm also about to open a PR to fix it, so maybe not a huge deal to disambiguate *shrugs*

**Comment by vincepri** [comment]
/close

Closing in favor of #3762
