### ISSUE TITLE
Categorize events to distinguish between create/delete events

### ISSUE THREAD

**Issue by harishspqr** [kubernetes-sigs/cluster-api#1743]
**User Story**
Currently the machine events does not indicate if they were related to create/delete of a Machine. 
We need more metadata about the event to distinguish between create and delete events. 
**Detailed Description**

**Anything else you would like to add:**

/kind feature

**Comment by ncdc** [comment]
@noamran do you have an approach in mind for this?

**Comment by noamran** [comment]
> @noamran do you have an approach in mind for this?

@ncdc not yet. Is there a specific approach you think I should be taking?

**Comment by ncdc** [comment]
We currently use `.Eventf` to record events. There is also `.AnnotatedEventf`, which would allow us to set annotations on the events when we create them. I think that's one possible approach (define a key and values indicating create vs delete)

**Comment by ncdc** [comment]
After talking to @yastij yesterday, it sounds like a newer events API is going to remove the annotation support. The recommended path forward is to use conditions instead of events. xref #1658

**Comment by ncdc** [comment]
Going through open unassigned issues in the v0.3.0 milestone. We have a decent amount of work left to do on features (control plane, clusterctl, etc). I think we need to defer it to v0.4.

/milestone Next

**Comment by vincepri** [comment]
Going to close this one for now, and merge the requirement in the conditions proposal coming up.

cc @fabriziopandini 
/close
