### ISSUE TITLE
Reset cluster.status.ControlPlaneInitialized to false when all control plane machines are removed

### ISSUE THREAD

**Issue by accepting** [kubernetes-sigs/cluster-api#1746]
**What steps did you take and what happened:**

After we remove all control plane machines in a cluster, the cluster's status ControlPlaneInitialized is still marked as true. This will have a very bad result when we create another new control plane machine in this cluster next time, because the machine will try to join the existing cluster and will fail absolutely.

**What did you expect to happen:**

Cluster's status.ControlPlaneInitialized should be set to false when all control plane machines are removed.

**Environment:**

- Cluster-api version: Commit SHA: 86c86080f
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): 1.14.4
- OS (e.g. from `/etc/os-release`): centos 7.2

/kind bug

**Comment by ncdc** [comment]
Reviewed in today's community meeting. See https://github.com/kubernetes-sigs/cluster-api/pull/1747#issuecomment-553586095 for the update.

**Comment by ncdc** [comment]
Closing as per linked comment.
/close
