### ISSUE TITLE
bug in quickstart docs

### ISSUE THREAD

**Issue by jduncan-rva** [kubernetes-sigs/cluster-api#1750]
**What steps did you take and what happened:**
There's a docs bug in "Install Infrastructure Provider > Docker"

The code snippet is:

```
kubectl create -f https://github.com/kubernetes-sigs/cluster-api-provider-docker/releases/download/v0.2.1/provider_components.yaml
```

and kicks a 404 error. 

The file should be `provider-components.yaml`, I think. That file exists and seems to work.

/kind bug

**Comment by 1060351485** [comment]
Hi! I'd like to take this issue. Thank you!
/assign
