### ISSUE TITLE
Ability to disable rolling updates

### ISSUE THREAD

**Issue by johngmyers** [kubernetes-sigs/cluster-api#1754]
**User Story**

As an operator I would like to disable the MachineDeployment rolling update mechanism so that I can manage rolling updates with external code.

**Detailed Description**

I would like to have MachineDeployment handle the provisioning and removal of machines, but handle the process of rolling updates using external code with more knowledge, context, and ability than the MachineDeployment rolling update controller.

/kind feature

**Comment by ncdc** [comment]
I'm not sure off-hand how we could make the update logic pluggable. Did you have any thoughts on how to implement that?

**Comment by vincepri** [comment]
Until #1689 and #1690 are fixed, I wouldn't add new features to the existing MS/MD codebase. 

One potential idea is to use and build on top of MachineSets instead of MachineDeployment if you want to control the rolling update mechanism.

**Comment by johngmyers** [comment]
You could implement this by removing the restriction that `maxUnavailable` and `maxSurge` cannot both be 0.

The reason to build on top of MachineDeployment would be to get the other features of MachineDeployment, such as maintaining a MachineSet per template revision and cleaning up not-ready machines.

**Comment by akutz** [comment]
Potentially related to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/628

**Comment by ncdc** [comment]
@johngmyers I'm still trying to figure out what this might look like. If both maxUnavailable and maxSurge are set to 0, how do you envision managing the updates?

**Comment by johngmyers** [comment]
@ncdc I would envision managing the updates with code that is external to cluster-api. That code would have better knowledge than cluster-api, possibly coordinating with the workloads to avoid excessive disruption.

That code could effect updates by attaching `cluster.k8s.io/delete-machine` annotations to nodes, allowing cluster-api to update them despite `maxUnavailable`, or by incrementally scaling the underlying MachineSets.

**Comment by vincepri** [comment]
@johngmyers I'm 100% sure if this solves your issue, but in v1alpha3 we added an annotation to stop reconciliation on objects.

https://master.cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html#support-the-clusterx-k8siopaused-annotation-and-clusterspecpaused-field

/lifecycle frozen

**Comment by vincepri** [comment]
/remove-lifecycle frozen

@johngmyers Do you have any updates on this?

**Comment by johngmyers** [comment]
It looks like the `Paused` annotation/field disables too much of reconciliation. For this use case the desire is to have the reconciliation create new machines when there aren't enough, but to let external code identify when to remove particular machines.

**Comment by vincepri** [comment]
Closing in favor of #1271 

/close
