### ISSUE TITLE
Validation webhooks

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1757]
**User Story**

As a user, I would like to get early validation errors if the supplied configuration is invalid.

As a Cluster API developer, I would like to be able to add strict validation to Cluster API types.

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature
/milestone v0.3.0

**Comment by wfernandes** [comment]
I'll work on getting the following validation moved to webhooks as a start:
- https://github.com/kubernetes-sigs/cluster-api/blob/fa6fab8b99edf1709efad2c61eca7c9e5b96204f/controllers/machine_controller_phases.go#L155-L161
- https://github.com/kubernetes-sigs/cluster-api/blob/fa6fab8b99edf1709efad2c61eca7c9e5b96204f/controllers/machinedeployment_controller.go#L151-L156
- https://github.com/kubernetes-sigs/cluster-api/blob/fa6fab8b99edf1709efad2c61eca7c9e5b96204f/controllers/machineset_controller.go#L164-L169

Let me know if there are other validations that make sense to move to a webhook.

**Comment by wfernandes** [comment]
There's also 
- https://github.com/kubernetes-sigs/cluster-api/blob/80b9d58b6a079236553f5ea67f8950722b9bc541/api/v1alpha3/defaults.go#L24-L26
We could move this to a webhook as well. Although I feel this is more of a Mutating webhook rather  than a validating one.

**Comment by wfernandes** [comment]
Progress so far:
- [x] Setup Machine Webhook Validation
- [ ] Setup Machine Deployment Webhook Validation 
- [ ] Setup Machine Set Webhook Validation 
- [ ] Ask if we should add defaults or Mutating Webhook Validation to Machine
- [ ] Try adding e2e test?

**Comment by vincepri** [comment]
I'd skip the defaults for now, until we want to tackle mutation webhooks as well.
