### ISSUE TITLE
Machineset finishes syncing replica with machines still under deleting state

### ISSUE THREAD

**Issue by accepting** [kubernetes-sigs/cluster-api#1760]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
1. In an existing cluster, create a machineset with 3 machines.
2. Scale the machineset down to 2 machine. 
3. Starts to delete machine M. Due to our cloud provider's reason,  the related machineinfra cannot be removed for a long time. Machine M is under **deleting** state during this time.
4. Machineset finishes scaling down before machine M is deleted successfully.

**What did you expect to happen:**

During scaling down, machineset should keep waiting until all machines have been deleted successfully. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
After reading the machineset codes, I found these
- Machineset deletes machines without waiting to check all machines are deleted successfully. [L353](https://github.com/kubernetes-sigs/cluster-api/blob/c28d769f98f2a6624f6651cc2eef3190504b4a87/controllers/machineset_controller.go#L353)
- Invoking `client.Delete()` only sets the `DeletionTimestamp` field on Machine object. When the function returns, it does not mean the Machine object has been deleted from etcd successfully.
- machineset will ignore deleting machines when syncing its replicas. [L196](https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/machineset_controller.go#L196)

**Environment:**

- Cluster-api version: master branch
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): 1.14.4
- OS (e.g. from `/etc/os-release`): centos

/kind bug

**Comment by detiber** [comment]
I want to make sure that I'm understanding.

Is the issue here that we are not reflecting the state of the Machines that are waiting to complete deletion in that status here?

Or, are you expecting that we wait for full deletion of each Machine prior to continuing the deletion of additional Machines as part of the workflow?

**Comment by accepting** [comment]
> I want to make sure that I'm understanding.
> 
> Is the issue here that we are not reflecting the state of the Machines that are waiting to complete deletion in that status here?
> 
> Or, are you expecting that we wait for full deletion of each Machine prior to continuing the deletion of additional Machines as part of the workflow?

@detiber  The Machineset status should reflect the state of those machines.

When I delete machines by scaling Machineset down, I will watch the Machineset status to know whether those machines has fully deleted. If Machineset status does not take deleting machines into account when calculating its status, we can't make right decision.

**Comment by vincepri** [comment]
@accepting Are you still interested in exploring this issue?

**Comment by vincepri** [comment]
Closing due to lack of updates.

Feel free to reopen if you'd like to still tackle this issue.

/close
