### ISSUE TITLE
[cabpk] Patch fail first time a new config is generated

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1769]
/kind bug

**What steps did you take and what happened:**
Create a new Machine with a KubeadmConfig, the first time the config is patched, the reconciler fails with the following validation error.

> E0909 02:00:09.747522       1 kubeadmconfig_controller.go:143] reconciler "msg"="failed to patch config" "error"="KubeadmConfig.bootstrap.cluster.x-k8s.io \"test1-controlplane-0\" is invalid: []: Invalid value: map[string]interface {}{\"apiVersion\":\"bootstrap.cluster.x-k8s.io/v1alpha2\", \"kind\":\"KubeadmConfig\", \"metadata\":map[string]interface {}{\"creationTimestamp\":\"2019-09-09T01:59:36Z\", \"generation\":2, \"name\":\"test1-controlplane-0\", \"namespace\":\"default\", \"ownerReferences\":[]interface {}{map[string]interface {}{\"apiVersion\":\"cluster.x-k8s.io/v1alpha2\", \"kind\":\"Machine\", \"name\":\"test1-controlplane-0\", \"uid\":\"664e6ba6-901d-43c8-988e-21b833c71392\"}}, \"resourceVersion\":\"598\", \"uid\":\"ca7cd586-dfa3-44d4-b65d-b8fb931600c9\"}, \"spec\":map[string]interface {}{\"clusterConfiguration\":map[string]interface {}{\"apiServer\":map[string]interface {}{\"extraArgs\":map[string]interface {}{\"cloud-provider\":\"gce\"}}, \"clusterName\":\"test1\", \"controlPlaneEndpoint\":\"34.102.137.26:443\", \"controllerManager\":map[string]interface {}{\"extraArgs\":map[string]interface {}{\"allocate-node-cidrs\":\"true\", \"cloud-provider\":\"gce\", \"cluster-cidr\":\"192.168.0.0/16\", \"service-cluster-ip-range\":\"10.96.0.0/12\"}}, \"kubernetesVersion\":\"v1.15.3\", \"networking\":map[string]interface {}{\"podSubnet\":\"192.168.0.0/16\"}}, \"initConfiguration\":map[string]interface {}{\"nodeRegistration\":map[string]interface {}{\"kubeletExtraArgs\":map[string]interface {}{\"cloud-provider\":\"gce\"}, \"name\":\"{{ ds.meta_data[\\\"local_hostname\\\"] }}\"}}}}: validation failure list:\nspec.clusterConfiguration.networking.dnsDomain in body is required\nspec.clusterConfiguration.networking.serviceSubnet in body is required" "kubeadmconfig"={"Namespace":"default","Name":"test1-controlplane-0"} "machine-name"="test1-controlplane-0"
E0909 02:00:09.747915       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="KubeadmConfig.bootstrap.cluster.x-k8s.io \"test1-controlplane-0\" is invalid: []: Invalid value: map[string]interface {}{\"apiVersion\":\"bootstrap.cluster.x-k8s.io/v1alpha2\", \"kind\":\"KubeadmConfig\", \"metadata\":map[string]interface {}{\"creationTimestamp\":\"2019-09-09T01:59:36Z\", \"generation\":2, \"name\":\"test1-controlplane-0\", \"namespace\":\"default\", \"ownerReferences\":[]interface {}{map[string]interface {}{\"apiVersion\":\"cluster.x-k8s.io/v1alpha2\", \"kind\":\"Machine\", \"name\":\"test1-controlplane-0\", \"uid\":\"664e6ba6-901d-43c8-988e-21b833c71392\"}}, \"resourceVersion\":\"598\", \"uid\":\"ca7cd586-dfa3-44d4-b65d-b8fb931600c9\"}, \"spec\":map[string]interface {}{\"clusterConfiguration\":map[string]interface {}{\"apiServer\":map[string]interface {}{\"extraArgs\":map[string]interface {}{\"cloud-provider\":\"gce\"}}, \"clusterName\":\"test1\", \"controlPlaneEndpoint\":\"34.102.137.26:443\", \"controllerManager\":map[string]interface {}{\"extraArgs\":map[string]interface {}{\"allocate-node-cidrs\":\"true\", \"cloud-provider\":\"gce\", \"cluster-cidr\":\"192.168.0.0/16\", \"service-cluster-ip-range\":\"10.96.0.0/12\"}}, \"kubernetesVersion\":\"v1.15.3\", \"networking\":map[string]interface {}{\"podSubnet\":\"192.168.0.0/16\"}}, \"initConfiguration\":map[string]interface {}{\"nodeRegistration\":map[string]interface {}{\"kubeletExtraArgs\":map[string]interface {}{\"cloud-provider\":\"gce\"}, \"name\":\"{{ ds.meta_data[\\\"local_hostname\\\"] }}\"}}}}: validation failure list:\nspec.clusterConfiguration.networking.dnsDomain in body is required\nspec.clusterConfiguration.networking.serviceSubnet in body is required"  "controller"="kubeadmconfig" "request"={"Namespace":"default","Name":"test1-controlplane-0"}

**What did you expect to happen:**
Patch should succeed without errors.

**Comment by ncdc** [comment]
I moved this from CABPK to CAPI. I can't remember if we fixed this already - if so, please close (and link to the PR). Thanks!

**Comment by chuckha** [comment]
/unassign

I'm pretty sure this is fixed but haven't verified

**Comment by vincepri** [comment]
It's not but I have opened #1918 to fix it
