### ISSUE TITLE
Tab on Quick Start confusing

### ISSUE THREAD

**Issue by craiglpeters** [kubernetes-sigs/cluster-api#1774]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
1. Try to do the [quick start](https://cluster-api.sigs.k8s.io/user/quick-start.html)
1. Get to the step Setup Management Cluster
1. Try to click the 'Azure' tab, and nothing happens
![image](https://user-images.githubusercontent.com/9445180/68817652-2d3a8800-0637-11ea-95be-c3d3ef46ac2a.png)
1. Realize that " AWS | Azure | vSphere | OpenStack " is *one* tab only after clicking like 20 times

**What did you expect to happen:**
It to be clear that only Docker is on a different tab

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by vincepri** [comment]
@craiglpeters Do you have any suggestions here?

**Comment by ncdc** [comment]
If we used `/` instead of `|` would that be less confusing?
