### ISSUE TITLE
Support for a resource annotation that prevents a controller from reconciling the resource

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api#1780]
**User Story**

As an operator I would like to be able to disable reconciliation for one or more resource types by applying an annotation to a resource that indicates to the controller(s) that the resource should be ignored (ie. not reconciled) until the annotation is removed.

**Detailed Description**

For example, https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/628 - an annotation may be placed on a `VSphereMachine` that instructs the `VSphereMachine` controller to skip reconciliation until the annotation is removed. This is useful when it's necessary to power off the backing VM to perform diagnostics and want to keep the CAPV controller from powering back on the VM.

**Anything else you would like to add:**

This annotation could be generic enough to be useful for a broad number of CAPI related resources. @detiber indicated it may be something that could be used during the pivot.

/kind feature

**Comment by detiber** [comment]
@fabriziopandini this is something that had been previously discussed as a potential way to simplify the pivot scenario.

**Comment by fabriziopandini** [comment]
Yes, even though for the Pivoting scenario the requirement is to suspend actions for a whole infrastructure provider, not a for a single machine

**Comment by vincepri** [comment]
+1 to this proposal, it could be useful in a number of places, especially for debugging purposes.

/milestone v0.3.0
/priority important-soon
