### ISSUE TITLE
MachineDeployments to support multiple control plane nodes.

### ISSUE THREAD

**Issue by sb1975** [kubernetes-sigs/cluster-api#1781]
**User Story**

As a user I would like to deploy my workload cluster with multiple master nodes and worker nodes.

**Detailed Description**

While Machinedeployments are supported for worker nodes they are not supported for master nodes.

In a scenario where I have a workload cluster where there is a need for a control plane (with multiple master nodes(control-plane machines) running the control plane services and resiliency of those services) I would need a mechanism to spin up multiple control-plane machines.
Secondly in future there might be need for autoscaling of those control-plane machines depending on the load of the control-plane machines.

/kind feature

**Comment by ncdc** [comment]
This is being implemented as part of the KubeadmControlPlane proposal from #1613. The tracking issue for work items is #1756

Closing as a duplicate.

/close
