### ISSUE TITLE
bootstrap-provider: make kubeadm call customizable

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#1782]
**User Story**

As an operator I would like to be able to kustomize the KubeadmCommand (not only PreKubeadmCommands and PostKubeadmCommands)

**Detailed Description**

In my use case I'm generating the control plane certificates via Vault instead of the kubeadm bootstrap provider. It's possible to add a certificate generation script before kubeadm is called, but that's not enough. I also have to customize the actual kubeadm call, e.g.:
```bash
kubeadm join --config /tmp/kubeadm-controlplane-join-config.yaml --skip-phases preflight,control-plane-prepare/certs,control-plane-prepare/kubeconfig
```

Because of this (and I guess there are also a few more valid use cases), it would be great if the kubeadm command itself can also be customized via the KubeadmConfig. Currently it's hard-coded here: 
* https://github.com/kubernetes-sigs/cluster-api/blob/master/bootstrap/kubeadm/cloudinit/controlplane_join.go#L34
* https://github.com/kubernetes-sigs/cluster-api/blob/master/bootstrap/kubeadm/cloudinit/controlplane_init.go#L36

Because we cannot decide before which node has to execute `kubeadm init` or `kubeadm join` I would propose adding a field to specify additional kubeadm arguments.

/kind feature

**Comment by ncdc** [comment]
+1, I'd at least like to be able to customize the log level

**Comment by chuckha** [comment]
+1 as well. I wonder if it's on kubeadm's roadmap to be completely configurable via command line? I'm guessing no, but perhaps @neolit123 can comment.

Regardless, I have a few questions about the Vault workflow. What exactly makes the call to Vault to generate the certs? How does Vault respond? Would it be possible to write the certificates to a secret before the bootstrap provider runs?

**Comment by sbueringer** [comment]
@chuckha 

Currently it would be difficult. The problem is we used regular PKI backends in Vault a few years ago when we started with our Kubernetes platform. Unfortunately now we're not able to extract the CA from Vault anymore (we're in the middle of a migration to rollover this CAs with other CAs which we have full access to).

If I'm not mistaken (a colleague of mine implemented it), kubeadm expects root CAs to generate other certificates. So our current solution is to generate a lot of the certificates which kubeadm usually generates by ourselves via the Vault pki backend. So we would have to parameterize a lot of certificates and not only the 4 root CAs. This issue is resolved after we rolled over our CAs, because then we will have full access to the CAs again (but this will take a little bit). (correct me if I"m wrong @kabakaev)

Another thing we're trying to achieve is to only handover a short-lived Vault token via user-data and then retrieve the root CAs with it. The Vault tokens will be expired after the node is ready. The goal is to avoid leaking our CAs in user data.

**Comment by sbueringer** [comment]
Hm, when I think about it a little bit more it's even more complicated in our case. We're using these commands:
* init control plane:
  ```bash
  kubeadm init --config /tmp/kubeadm.yaml --skip-phases=addon --experimental-kustomize /opt/conf/k8s/kustomize
  ```
* join control plane:
  ```bash
  kubeadm join --config /tmp/kubeadm-controlplane-join-config.yaml --skip-phases preflight,control-plane-prepare/certs,control-plane-prepare/kubeconfig --experimental-kustomize /opt/conf/k8s/kustomize
```
* join worker:
  ```bash
  kubeadm join --config /tmp/kubeadm-controlplane-join-config.yaml --experimental-kustomize /opt/conf/k8s/kustomize", machineName
  ```

The difference between worker and control plane join is not really a problem, because we know already if a Machine will be a worker or a control plane node when writing the KubeadmConfig.

But the control plane args are different depending on if it's a join or an init. So a single field like `KubeadmArgs []string` wouldn't be enough to fullfill this use case. I see the following options:
* KubeadmJoinCommand and KubeadmInitCommand fields
* KubeadmJoinArgs and KubeadmInitArgs fields

I think the first option would be easier as the full command can be just overwritten if the default value is not enough. The second options would make more sense if there are meaningful dynamic arguments generated by the kubeadm bootstrapper (which cannot be hardcoded in the KubeadmConfig).

**Comment by neolit123** [comment]
> +1 as well. I wonder if it's on kubeadm's roadmap to be completely configurable via command line? I'm guessing no, but perhaps @neolit123 can comment.

it's the complete opposite. flags are moving to config and the proposal to allow patching config from the command line (ala kubectl patch) did not receive full agreement.

**Comment by gaulzhw** [comment]
+1. I'd like to add --skip-phases to skip addon.

**Comment by neolit123** [comment]
skipping phases is also possible using the config.

**Comment by dlipovetsky** [comment]
I see use cases that are not currently supported by CABPK:
1. `--v` (kubeadm log verbosity)
1. `--experimental-kustomize` 
1. `--skip-phases`

Alll are part of kubeadm's imperative interface. However, CAPBK exposes a declarative interface (the KubeadmConfig custom resource), and translates that to imperative kubeadm operations[1]. 

Exposing the imperative operations to the user has challenges:
1. Some imperative operations (e.g. `--skip-phases`) should apply only in some cases (e.g. bootstrapping the first control plane replica).
1. Some imperative operations may change or be removed from in a future kubeadm version, and there is no machinery to automatically "convert" the operations. This machinery does exist for the declarative interface (i.e. kubeadm configuration).
1. Imperative operations are hard to validate.

Before we allow CABPK to expose the imperative operations (and need to address these challenges), let's consider how we can support the 3 use cases declaratively.

1. `--v` (kubeadm log verbosity). We could add a `KubeadmConfiguration.Spec.Verbosity string` field.
1. `--experimental-kustomize`. We could add a `KubeadmConfiguration.Spec.ExperimentalKustomize []string` field, where every element is a path. Kustomize manifests can be passed in using the existing `KubeadmConfiguration.Spec.Files` field.
1. `--skip-phases`. We could ask kubeadm maintainers to add this to the kubeadm configuration. As a precedent, preflight checks were added, though not everyone agreed with that change. 

[1] For example, https://github.com/kubernetes-sigs/cluster-api/blob/master/bootstrap/kubeadm/cloudinit/controlplane_init.go#L36

**Comment by neolit123** [comment]
> KubeadmConfiguration.Spec.ExperimentalKustomize 

this is tricky. it's essentially binding between the CAPBK API and the kubeadm CLI. `--extermential-kustomize` is an alpha feature that may become stable (`--kustomize`) or be deprecated.

delegating the kubeadm CLI choices to a generic `extraArgs` is safer for CAPBK. it might break users eventually, but same goes for users having bash scripts with kubeadm flags.

**Comment by chuckha** [comment]
I would be in favor of exposing a verbosity setting on kubeadm but not a generic whatever-you-want field. That would, for now, be too large of a footgun.

The verbosity flag is the one i've had numerous requests for.

**Comment by dlipovetsky** [comment]
> I would be in favor of exposing a verbosity setting on kubeadm

+ 1

> but not a generic whatever-you-want field. That would, for now, be too large of a footgun.

That's a good point. I agree that `extraArgs` is a footgun. But if it is not provided, must the user maintain their own kubeadm-based bootstrap provider? Would the user choose this over the footgun :smile:.

(For reference, there is an `extraArgs` in the kubeadm configuration, too, and one problem I have seen is that `extraArgs` values can conflict with the values of explicit fields.)

**Comment by CecileRobertMichon** [comment]
Can I help with this one?

**Comment by ncdc** [comment]
Thanks @CecileRobertMichon! Could you please describe briefly what you're thinking of implementing?

**Comment by CecileRobertMichon** [comment]
@ncdc from looking at the thread it looks like a verbosity setting is the one that has the most demand/consensus so I'm thinking of starting there, wdyt?

**Comment by chuckha** [comment]
That would be awesome 🙏

**Comment by chuckha** [comment]
@vincepri we can close this

/close

@sbueringer Please open a new issue if this does not satisfy the original use case! thank you!
