### ISSUE TITLE
More frequent releases

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1784]
/kind feature

CAPI has fairly large minor releases so in order to get more folks testing the code that may make it into the next minor version release, we are considering doing more frequent releases. This would mean that while the stable release, v0.2.x has been released we are working on v0.3. Instead of waiting until everything is done, we want to release v0.3.0-alpha.x releases. These would be pre-releases unlike the v0.2.x releases which would be real releases.

Action Items
- [x] Remove pre-release tag on all existing releases
- [ ] Release a pre-release version

Tagging relevant folks: @ncdc @vincepri @akutz

**Comment by vincepri** [comment]
Let's discuss this after KubeCon in the community meeting to get more feedback, I'm +1

/milestone v0.3.0
/assign
/priority important-soon

**Comment by ncdc** [comment]
To clarify a bit, when I mentioned this at office hours the other day, I was suggesting we do alpha releases of the upcoming unreleased next minor version - `v0.3.0-alpha.*`. Not for the current shipping version. I suppose we could do `v0.2.x` alphas, although I'm guessing it's more trouble than it's worth.

**Comment by chuckha** [comment]
Will clarify, thanks for the correction

**Comment by ncdc** [comment]
Going to start doing this.
/close
