### ISSUE TITLE
Proposal: make machine.spec.bootstrap.data a reference to a secret

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1790]
**User Story**

As a user/operator I would like to change machine.spec.bootstrap.data from "a string" to "an object reference to a secret" to make my bootstrap data as secure as possible.

**Detailed Description**

If we have sensitive information in machine bootstrap data, such as certificates, we should be storing the entire bootstrap data in a secret, instead of as a field on the machine.

**Anything else you would like to add:**

No

/kind feature

**Comment by michaelgugino** [comment]
Why wouldn't this be accounted for in the bootstrap reference?

**Comment by ncdc** [comment]
The bootstrap reference is currently a reference to a single resource that potentially contains bootstrap configuration details and that contains the bootstrap data. The current requirement for a bootstrap resource is that it has `status.bootstrapData` (`string`) and `status.ready`) (`bool`). Once `status.ready` is `true`, CAPI's machine reconciler copies from `status.bootstrapData` into the machine's `spec.bootstrap.data` (`string`) field.

I'd like to change the contract so a bootstrap provider generates a secret containing the bootstrap data, and this is the only place the bootstrap data is stored in etcd.

**Comment by vincepri** [comment]
+1 to this proposal, it should be pretty straightforward to implement and it improves our security story.

**Comment by michaelgugino** [comment]
> Once status.ready is true, CAPI's machine reconciler copies from status.bootstrapData into the machine's spec.bootstrap.data (string) field.

I'm disappointed that this shipped if that's the case.  Copying data onto the machine-object was specifically called out during v1alpha2 planning as a bad idea.

Whoever consumes the userdata (or whatever is living in the secret) should be the thing that has a reference to it.

**Comment by ncdc** [comment]
The road from v1alpha1 to v1alpha2 was a net positive, but it wasn't a perfect end state. We'll keep iterating and improving. We're still alpha, after all!

**Comment by ncdc** [comment]
@michaelgugino suggested adding a new field e.g. `dataRef` or something like that, to ease with migrations

**Comment by ncdc** [comment]
This was implemented.
/close
