### ISSUE TITLE
Kind v0.6.0 deprecates `kind get kubeconfig-path` 

### ISSUE THREAD

**Issue by b2jrock** [kubernetes-sigs/cluster-api#1796]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
When following the installation guide in the book, when setting `KUBECONFIG` environment variable using the command listed, kind throws a deprecation warning.
 

**What did you expect to happen:**
No deprecation warning from kind.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I think the context command it suggests is also needed.

**Environment:**

- Cluster-api version: 0.2.7
- Minikube/KIND version: 0.6.0
- Kubernetes version: (use `kubectl version`): 1.16.3
- OS (e.g. from `/etc/os-release`): N/A

/kind bug

**Comment by vincepri** [comment]
We'll also need to backport the quick start changes to the release-0.2 branch

**Comment by kacole2** [comment]
I hit this problem today. Thanks for opening the issue @b2jrock.

**Comment by b2jrock** [comment]
Looks like clusterctl has an issue with this as well. See #1801. I have a backport ready, but I don't want to recommend kind v0.6.0 if it's non-functional with that version.

**Comment by ncdc** [comment]
We should update all docs to be based on kind 0.6+

**Comment by Thor-wl** [comment]
Well, how can i get the path of kubeconfig when kind is upgraded to v0.9.0? Anyone can help?

**Comment by eli-halych** [comment]
> Well, how can i get the path of kubeconfig when kind is upgraded to v0.9.0? Anyone can help?

Also interested

**Comment by eli-halych** [comment]
> Well, how can i get the path of kubeconfig when kind is upgraded to v0.9.0? Anyone can help?

I used Kind v0.11.1 and this is what worked for me: `kind get kubeconfig --name test`
You basically need to specify cluster name after what you need to get.

**Comment by sbueringer** [comment]
@Thor-wl I'm not sure you can still get the path, but you can export a kubeconfig via `kind get kubeconfig`
