### ISSUE TITLE
Support for MachinePool in CABPK

### ISSUE THREAD

**Issue by juan-lee** [kubernetes-sigs/cluster-api#1799]
**User Story**

As a developer I would like to be able to leverage the CABPK to provide bootstrap config to types other than Machine and MachineSet for the purposes of adding support for MachinePool or other future types that might require bootstrap configuration.

**Detailed Description**

Currently CABPK depends on Machine to determine if it needs to generate bootstrap configuration that Machine will consume to provide as input to its infrastructure provider. In order for MachinePool to take advantage of how CABPK provides bootstrap configuration, CABPK will need to become more generic.

**CABPK depends on Machine to:**
- Get the owning Cluster instance
- Check if a Machine's Infrastructure is ready
- Check if a Machine's Bootstrap.Data is already populated
- Provide a fallback k8s version if not specified in KubeadmConfig
- Check if a Machine is a control plane
- Locking if the Machine is a control plane

**Proposed Changes**
- Provide a data interface via `Unstructured` for the KubeadmConfig to reference instead of Machine
- Add a watch for MachinePool - explicit references to Machine and MachinePool are still required for watch
- Keep explicit dependency on Machine for managing control plane
- Generic implementation for handling non-control plane Machines

**Anything else you would like to add:**

#1703 and #1665 are dependent on this feature.

/kind feature

**Comment by ncdc** [comment]
> Provide a data interface via Unstructured for the KubeadmConfig to reference instead of Machine

@juan-lee could you expand on what you mean here?

**Comment by vincepri** [comment]
I originally suggested to @juan-lee that we could use an approach like we do today when we handle external objects in the Machine and Cluster controller code. 

By providing a contract to the KubeadmConfig owner's, we can use different API types / CRDs and use the unstructured package to get the information we need (for example the cluster name).

This would remove the need for a KubeadmConfig's owner to be a Machine and its use beyond single machine objects.

**Comment by ncdc** [comment]
Ok, thanks for the clarification. That's what I thought but I wasn't certain.
