### ISSUE TITLE
E2E tests for cluster bootstrapping

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#18]
_From @rsdcastro on January 29, 2018 21:49_

Basic set of E2E tests for cluster bootstrapping across supported providers.

_Copied from original issue: kubernetes/kube-deploy#525_

**Comment by jessicaochen** [comment]
Ideal one of these is also a presubmit to stop PRs from breaking bootstrapping with changes.

**Comment by timothysc** [comment]
No longer applies to this repo.
