### ISSUE TITLE
Clusterctl create command fails with kind v0.6

### ISSUE THREAD

**Issue by prankul88** [kubernetes-sigs/cluster-api#1801]
**What steps did you take and what happened:**
Ran clusterctl command `clusterctl create cluster --bootstrap-type kind --bootstrap-cluster-cleanup=false -c cluster.yaml -m controlplane.yaml -p provider-components.yaml -a addons.yaml -v 32`

**OUTPUT**

> F1126 06:42:36.719468   26660 create_cluster.go:61] could not create bootstrap cluster: unable to get bootstrap cluster kubeconfig
> 
> /home/ubuntu/.kube/config: no such file or directory

**What did you expect to happen:**
Clusterctl to fetch the correct kubeconfig file and proceed forward.

**Anything else you would like to add:**
This seems to occur due to some breaking changes in kind v0.6.0. KIND now exports / merges kubeconfigs in the same way that kops, minikube, and other tools do. (https://github.com/kubernetes-sigs/kind/issues/1060)

**Environment:**

- Cluster-api version: v1Alpha2
- Minikube/KIND version: kind v0.6.0
- Kubernetes version: (use `kubectl version`): v1.15
- OS (e.g. from `/etc/os-release`): Ubuntu16.04

/kind bug

**Comment by fabriziopandini** [comment]
Clusterctl v2 is going to drop the creation of the bootstrap process, so this issue should not apply to master

**Comment by ncdc** [comment]
This may have been fixed by #1792. We should test.
