### ISSUE TITLE
Clusterctl v2 contract for providers

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#1802]
***Goals***
1. To formalize contract rules/expectations any provider implementation should respect in order to be managed by clusterctl v2
1. To formalize effects - e.g. in terms of limited usability - in case one of the above rules is not respected

***Non-Goals/Future Work***
1. To update the clusterctlv2 and the clusterctl v2 proposal with contracts rules discussed on this issue

***User Story***

As a provider developer, I would like clusterctl to manage my provider 

As a clusterctl developer, I need some rules in order to manage all the providers 

***Contract rules***

*** Provider components

a. The provider is required to generate a single YAML file[1] with all the necessary components for installing the provider (CRD, Controller, RBAC etc.). The URL of the YAML file should be provided in the configuration of the provider. Infrastructure providers MUST release a file called `infrastructure-components.yaml`, while bootstrap provider MUST release a file called `bootstrap-components.yaml` (exception for CABPK, which is included in CAPI by default).

b. The components YAML should contain one Namespace object; this namespace will be used as a default target namespace for installing the provider components.
> In case the default target namespace is not provided, the user will be required to specify a target namespace
> In case there is more than one namespace object in the components YAML, clusterctl can't handle the provider installation. TBD: define an annotation in order to define which Namespace is the target namespace?

c. The components YAML can contain environment variables matching the regexp `\${\s*([A-Z0-9_]+)\s*}`; it is highly recommended to prefix the variable name with the provider name e.g. `{ $AWS_CREDENTIALS }`

d. ** Pending discussion on https://github.com/kubernetes-sigs/cluster-api/issues/1525 ** 
the providers MUST support an annotation to skip reconciliation on objects or respect the Cluster's pause contract.

e. ** Pending discussion on https://github.com/kubernetes-sigs/cluster-api/issues/1490 ** 
The Deployment for the provider controller MUST have a container named `manager` and support the `--namespace` argument. 

*** Cluster templates

a. The provider might provide one or more YAML file with a cluster template, to be stored in the same folder of the component YAML
b. the default cluster template should be named `config.yaml`
c. additional cluster template should be named `config-flavor.yaml`
> In case there is no cluster template, `clusterctl config` will fail for the provider

b. A template YAML can contain go template directives; following context is passed to the template:
```
type TemplateOptions struct {
	ClusterName       string
	Namespace         string
	KubernetesVersion string
	ControlplaneCount int
	WorkerCount       int
}
```

*** Provider objects
a. Clusterctl move takes care of moving provider-specific objects as well. However, this feature is currently limited to object referenced by the cluster-api core objects (Cluster, Machine, etc.). 
There is no support for pivoting Hierarchies of provider-specific objects

/kind proposal

Notes
[1] only for dev porpuses it will be supported reading from a folder where there are more YAML file and a kustomize file for building the final YAML (e.g. the `/config` folder generated by kubebuilder)

**Comment by vincepri** [comment]
Let's start a working document in the book for all the points above except the last two (templates and external objects)

**Comment by fabriziopandini** [comment]
I'm closing this because the first part of the contract was documented by https://github.com/kubernetes-sigs/cluster-api/pull/1893, while the missing parts are tracked in separated issues
/close
