### ISSUE TITLE
capi-controller-manager error: secret "webhook-server-cert" not found

### ISSUE THREAD

**Issue by nader-ziada** [kubernetes-sigs/cluster-api#1803]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
- install cert manager using `kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v0.11.0/cert-manager.yaml`
- run `make release-mainfests`
- deploying cluster-components yaml generated from previous step to kind cluster
- `capi-controller-manager` pod fails to start giving an error `MountVolume.SetUp failed for volume "cert" : secret "webhook-server-cert" not found`

**What did you expect to happen:**
- `capi-controller-manager` pod to run successfully 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
in cert-manager  the [defaultWebhookServingSecretName](https://github.com/jetstack/cert-manager/blob/66d32a204f667a19e49af31963deeb54f6d596d6/cmd/controller/app/options/options.go#L128)  is `cert-manager-webhook-tls` instead of `webhook-server-cert` currently used

**Environment:**

- Cluster-api version: master as of commit `2ab0681eb05849f61a58475b0a6848fbe54dd44f`
- Minikube/KIND version: kind v0.5.1
- Kubernetes version: (use `kubectl version`):  v1.16.2
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by ncdc** [comment]
@nader-ziada I am unable to reproduce this. I end up with a secret called `webhook-server-cert`:

```
$ k -n capi-system get secret
NAME                  TYPE                                  DATA   AGE
default-token-79jkm   kubernetes.io/service-account-token   3      10s
webhook-server-cert   kubernetes.io/tls                     3      8s
```

And my pod runs:

```
$ k -n capi-system get pod
NAME                                       READY   STATUS    RESTARTS   AGE
capi-controller-manager-5b5444f47d-fjxn9   1/1     Running   0          16s
```

You _may_ see the mount failure, but that should be an ephemeral issue - here it is for my pod:

```
$ k -n capi-system describe pod
Name:         capi-controller-manager-5b5444f47d-fjxn9
Namespace:    capi-system
...
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
...
Events:
  Type     Reason       Age                  From                         Message
  ----     ------       ----                 ----                         -------
  Normal   Scheduled    103s                 default-scheduler            Successfully assigned capi-system/capi-controller-manager-5b5444f47d-fjxn9 to kind-control-plane
  Warning  FailedMount  102s (x2 over 103s)  kubelet, kind-control-plane  MountVolume.SetUp failed for volume "cert" : secret "webhook-server-cert" not found
  Normal   Pulling      101s                 kubelet, kind-control-plane  Pulling image "gcr.io/k8s-staging-cluster-api/cluster-api-controller:master"
  Normal   Pulled       97s                  kubelet, kind-control-plane  Successfully pulled image "gcr.io/k8s-staging-cluster-api/cluster-api-controller:master"
  Normal   Created      97s                  kubelet, kind-control-plane  Created container manager
  Normal   Started      97s                  kubelet, kind-control-plane  Started container manager
```

**Comment by nader-ziada** [comment]
when the secret is called that `webhook-server-cert` it didn't work for me on a fresh kind cluster, I will try it all again from scratch

**Comment by nader-ziada** [comment]
when I tried from scratch again, the pod is running, do know what happened before!

@ncdc do we want to rename the secret anyway since it doesn't find or should I close the PR and issue?

**Comment by ncdc** [comment]
This ephemeral error is expected and acceptable. It does eventually find the secret, once it's created. No need to rename it. Let's close the issue and PR.

**Comment by nader-ziada** [comment]
ok, thanks and sorry about the noise
