### ISSUE TITLE
Add Ability to Reboot Hosts (remediation)

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes-sigs/cluster-api#1808]
> ⚠️ Cluster API maintainers can ask to turn an issue-proposal into a [CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/YYYYMMDD-template.md) when necessary, this is to be expected for large changes that impact multiple components, breaking changes, or new large features.

***Goals***
1. Add api/abstraction to support rebooting hosts on a per-machine basis

***Non-Goals/Future Work***
1. Providers will be in charge of best determining in their components how to perform such an operation.

**User Story**

As a user I would like to support rebooting machines for node remediation.

**Detailed Description**

Our bare metal users really want to reboot hosts because they might be using converged infrastructure (lots of storage), and re-provisioning might be very costly.  Rebooting masters in the cloud might also be desirable if users don't trust automated remediation to delete/replace masters. 

## Things requesting reboots implement the following

Whatever is doing the remediation or otherwise request the machine be rebooted, ensure it follows the following abstraction
```
(look at machine-object status)
if last-boot-time < reboot-request-time
    do nothing

if last-boot-time > reboot-request-time
 && (time.Now() - last-boot-time > X) (1-2 hours; host must be up for some duration before requesting another reboot)
    update reboot-request-time
```

## Changes to infra provider (or machine-controller in v1alpha1)

So, I wrote this with v1alpha1 in mind, some status fields would need to move to/from the machine-controller/infra-provider, but it should be somewhat obvious.

## Changes to machine-controller

Syncs last-boot-time from infra-object.

### Option 1

```
sync infra.status.last-boot-time

if infra.status.last-boot-time < machine.status.reboot-request-time && (time.Now() - last-boot-time > X)

    if !infa.status.was-stopped
        if instance-state != stopped
            stop instance
            return to requeue reconcile
        if instance-state == stopped
            update infra.status.was-stopped true
            return to requeue reconcile
    
    if infra.status.was-stopped
        if instance-state != running
            start instance
            return to requeue reconcile
        if instance-state == running
            update infra.status.was-stopped false
            update infra.status.last-boot-time == time.Now()
            return to requeue reconcile

if last-boot-time > reboot-request-time
    do nothing
```

### Option 2

```
machine-controller (or possibly bare-metal-operator)

update infra.status.last-boot-time

if infra.status.last-boot-time < machine.status.reboot-request-time && (time.Now() - last-boot-time > X)

    if !infra.status.was-rebooted
        reboot instance
            if success
                (need to eagerly retry this to avoid multiple calls to the cloud provider)
                update infra.status.was-rebooted true
                return to reconcile

    if infra.status.was-rebooted
        return to reconcile (keep reconciling this object until last-boot-time is new)

if infra.status.last-boot-time > reboot-request-time && was-rebooted
    infra.status.was-rebooted false
```

**Contract changes [optional]**

Infrastructure providers would optionally support this abstraction by implementing certain actions.

**Data model changes [optional]**

Add:
- machine.status.last-boot-time
- infra.status.last-boot-time
- infra.status.was-stopped (bool) (option 1)
- infra.status.was-rebooted (bool) (option 2)

We could probably use 'was-rebooted' status element for both option 1 and option 2 and leave the implementation up to the provider.

/kind proposal

**Comment by michaelgugino** [comment]
For each case, we need to consider the inability to successful boot the VM after stopping.  Perhaps we should sync the 'was-rebooted' field to the machine-object as well, so we can build alerting/fallback remediation around such a condition (and possibly add a reboot-attempt timestamp, or just use the reboot attempt timestamp itself instead of a boolean for comparisons).

**Comment by zaneb** [comment]
For reference, our current proposal for implementing this in the baremetal infra provider is at metal3-io/metal3-docs#48
An earlier proposal was very similar to Option 2 here, but we settled on a separate CRD because people were uncomfortable with handling future-dated requests and with the mechanics of collapsing multiple concurrent reboot requests (from different sources) into a single timestamp. (See metal3-io/baremetal-operator#239 for comments).

I don't think the design chosen for the Machine API presents any problems for the BareMetalHost, but it may be worth considering similar issues.

**Comment by michaelgugino** [comment]
> For reference, our current proposal for implementing this in the baremetal infra provider is at [metal3-io/metal3-docs#48](https://github.com/metal3-io/metal3-docs/pull/48)
> An earlier proposal was very similar to Option 2 here, but we settled on a separate CRD because people were uncomfortable with handling future-dated requests and with the mechanics of collapsing multiple concurrent reboot requests (from different sources) into a single timestamp. (See [metal3-io/baremetal-operator#239](https://github.com/metal3-io/baremetal-operator/pull/239) for comments).
> 
> I don't think the design chosen for the Machine API presents any problems for the BareMetalHost, but it may be worth considering similar issues.

@zaneb 

My thinking for future-dated requests would be to use the on/off feature: https://github.com/kubernetes-sigs/cluster-api/issues/1810 along with some other component not part of the machine-controller (eg, you could still build the node-maintenance operator).  The idea here is to define an abstraction other components can use (such as machine health checks) to reboot the node, more or less as an interface to the underlying cloud's api.  Just like the awscli doesn't have a --reboot-at for there power options, you'd need to build another component that keeps track of scheduling.

I think I'm going to put together another RFE for the 'power-state-lock' so there aren't race conditions in the various controllers.

**Comment by zaneb** [comment]
The issue wasn't so much handling future-dated requests (everyone agrees that another component should do that) as that we *didn't* want to handle future-dated requests but the user can supply any time they want. In my original PR I addressed this by simply interpreting anything user-provided time in the future as the current time. This made people unhappy ;)

**Comment by michaelgugino** [comment]
> The issue wasn't so much handling future-dated requests (everyone agrees that another component should do that) as that we _didn't_ want to handle future-dated requests but the user can supply any time they want. In my original PR I addressed this by simply interpreting anything user-provided time in the future as the current time. This made people unhappy ;)

I think I see what you're saying.  Yeah, what I'm proposing here has not much to do with times after the current time.  Basically, we're comparing if the previous boot-time is older or newer than the last time a request was made.  Well-behaved clients should only use current time in that field.  It's basically a signal to say 'this thing was already requested to be rebooted, I don't need to make that request'

The machine-controller just decides if the request-time is newer or older than the boot-time.  If new, reboot.  If older, no reboot needed since that request was in the past.  Enforcing some minimum time between reboots will allow some time for components to update statuses, eg, health checking, if a user rebooted the machine, MHC decides machine is unhealthy, the machine comes back, MHC does nothing for X minutes because it realizes it was just rebooted and the situation might resolve itself.

**Comment by dlipovetsky** [comment]
This reminded me of `kubectl rollout restart deployment/$name`: https://github.com/kubernetes/kubernetes/pull/76062/

**Comment by zaneb** [comment]
Thanks for the link! So it [looks like](https://github.com/kubernetes/kubernetes/pull/76062/commits/1bf99e2e4ecb27d0dd4579c9f137c957ba159901#diff-748eb419a51edef8e7552290e2a9738eR32-R77) that works by adding an annotation `kubectl.kubernetes.io/restartedAt` with the value being the current time *as determined by the client*.
However, that only works because *any* change to the Deployment causes a rolling restart of the Pods (so the actual value is ignored). In our case, it doesn't solve the problem of being able to determine whether we need to initiate another reboot or if it has been done already.

**Comment by vincepri** [comment]
As per April 27th 2020 community guidelines, this project follows the process outlined in https://github.com/kubernetes-sigs/cluster-api/blob/master/CONTRIBUTING.md#proposal-process-caep for large features or changes.

Following those guidelines, I'll go ahead and close this issue for now and defer to contributors interested in pushing the proposal forward to open a collaborative document proposal instead, and follow the process as described.

/close

**Comment by michaelgugino** [comment]
@vincepri I disagree this issue should be closed.  Where else are we supposed to document RFE's that don't have a proposal yet?

**Comment by vincepri** [comment]
@michaelgugino Thanks for bringing this up, per last week meeting going forward we’ll do all proposals in a google doc following the process outlined above. There is space in each community meeting for members to add their proposals to be discussed in. 

Another good venue to have more visibility is slack and the mailing list.

We’ve closed all the other issue-proposals today, not just this one in an effort to move everything to a more collaborative environment, and leave issues to be more for actionable items rather than large spanning proposals.

**Comment by michaelgugino** [comment]
@vincepri there's a difference between proposals and RFEs.  RFEs should have an issue, and we can link to one or more proposals from that issue until some proposal is accepted.

**Comment by vincepri** [comment]
Feel free to reopen
