### ISSUE TITLE
Add machine/infra feature support fields

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes-sigs/cluster-api#1811]
> ⚠️ Cluster API maintainers can ask to turn an issue-proposal into a [CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/YYYYMMDD-template.md) when necessary, this is to be expected for large changes that impact multiple components, breaking changes, or new large features.

***Goals***
1. Add fields to machine and infra objects that indicate supported features

***Non-Goals/Future Work***
1. Define all features
1. Implement feature behaviors

**User Story**

As a developer I would like to build components that can take automated actions against machines for maintenance and remediation.  I need to know on a per-machine basis whether or not an operation can be successfully completed.

**Detailed Description**

I might want to build a remediation controller that reboots a host instead of deleting it, however, not all providers might support rebooting instances (eg, they haven't implemented it yet, or they can't/won't).

I might want to build a maintenance controller (such as taking snapshots) that wants to stop an instance.  In AWS, for example, spot instances cannot be stopped, but there's not really anything to indicate that on the machine-object.

**Contract changes [optional]**

syncs more status fields from infra-object to machine-object

**Data model changes [optional]**

machine.status.features
infra.status.features

Example:
```yaml
feature:
- stop-supported: True
- reboot-supported: False
```

After an infracontroller has made some kind of determination as to the abilities of a particular instance, it updates it's own status field with the supported features.  These features are synced to the corresponding machine-object to be consumed by 3rd-party controllers or end-users.

/kind proposal

**Comment by vincepri** [comment]
I'm wondering if we actually need any changes to Cluster API core types. Following what the spot instances proposal has done, we can build a small CAEP that defines a convention for infrastructure provider to use. 

Clients that want to use this feature can use the conventions established in the proposal, alongside some utilities. 

I'd like to open the discussion and involve more folks working on infrastructure providers to see if this is something we want in v1alpha3, and make sure we're ready for it and there is a clear need, use cases, and requirements.

**Comment by michaelgugino** [comment]
@vincepri can you be more specific about conventions.

I like it on the machine object for a few reasons.

1. Human accessible.  If I want to power off a machine, I can see if that operation is supported.
1. External components only need to worry about integrating with machines, not reading any data from elsewhere.
1. Most likely we'll set the power state of a machine on the machine itself, rather than elsewhere.  At least that's what makes sense to me.

**Comment by vincepri** [comment]
As per April 27th 2020 community guidelines, this project follows the process outlined in https://github.com/kubernetes-sigs/cluster-api/blob/master/CONTRIBUTING.md#proposal-process-caep for large features or changes.

Following those guidelines, I'll go ahead and close this issue for now and defer to contributors interested in pushing the proposal forward to open a collaborative document proposal instead, and follow the process as described.

/close
