### ISSUE TITLE
Support private registries with bootstrap-type KIND clusters

### ISSUE THREAD

**Issue by MnrGreg** [kubernetes-sigs/cluster-api#1818]
**User Story**

As an operator I would like to use `clusterctl create cluster  --bootstrap-type kind` with provider images hosted in a private registry. I would like `clusterctl` to be capable of taking a trusted CA as input to the bootstrap process.

**Detailed Description**

Currently `clusterctl create` fails to pull images where it cannot validate the registry endpoint certificate. There seems to be no way to inject the trusted certificates when using `clusterctl`

As per [cri documentation](https://github.com/containerd/cri/blob/master/docs/registry.md) one can append `/etc/containerd/config.toml` with either of the below options in order to trust or skip certificate validation.

1.
```ini
[plugins.cri.registry.configs."my.custom.registry".tls]
    ca_file   = "ca.pem"
```
2.
```ini
[plugins.cri.registry.configs."my.custom.registry".tls]
  insecure_skip_verify = true
```

**Workaround**

Current workaround is to side load the provider images during KIND start up. For example:
```shell
kind load docker-image my.custom.registry/repo/cluster-api-controller:v0.2.7 --name management-cluster
```

Most Cluster API provider templates have their `ImagePullPolicy` set to `Always`, so those manifests also need to be reconfigured.

**Miscellaneous**
@akutz has outlined using `cloud-init files` or `cloud-init ca-certs` for controlplane and machine resources #1793. This doesn't apply to the KIND bootstrap cluster though.

/kind feature

**Comment by ncdc** [comment]
@fabriziopandini could you please comment on this, in light of clusterctl v2?

**Comment by ncdc** [comment]
@MnrGreg the implementation of clusterctl that currently ships is end-of-life and is being rewritten from scratch with the upcoming v1alpha3 (v0.3.0) release early next year. We will no longer be creating the bootstrap cluster for you. Instead, it becomes a prerequisite, and it's up to you to create it before invoking clusterctl. You could configure the custom CA as part of creating your bootstrap cluster (again, outside of the scope of Cluster API and clusterctl).

Given that you have a workaround, would it be ok to close this?

**Comment by MnrGreg** [comment]
Thanks for the explanation.
