### ISSUE TITLE
clusterctl pre-pull images

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#1829]
**User Story**

As an operator would like to pre-pull all the required images for using clusterctl on an air-gapped environment

**Detailed Description**

As an operator, I would like to: 
1) go to a machine with internet access
2) pre pull al the required images for the set of provider I would like to install
3) extract them as tarballs
4) make them available in the management cluster before actually initialize it / installing providers

In order to make 2 happen we have some options:
a) add a `--list-images` flag to `clusterctl init` like e.g. `clusterctl init --infrastructure aws --list-images`. In alternative/addition we can use `--prepull-images`
b) add another top-level command to `clusterctl` (TBD)

/kind feature

**Comment by ncdc** [comment]
@vincepri since you put this in backlog, should we go to Next? Or do we need this for a3?

**Comment by vincepri** [comment]
I remember chatting with @fabriziopandini about it and it seemed very low priority. I'll leave it up to him to decide if it's going into Next or this milestone

**Comment by fabriziopandini** [comment]
I'm ok in keeping this in the milestone for now

**Comment by fabriziopandini** [comment]
@ncdc @vincepri I'm starting to work at this implementing the solution A described above (add a --list-images flag to clusterctl init); pre-pull can be achieved by simply `clusterctl init --list-images | xarg docker pull`.

Is it ok for you?
Do you expect the cert-manager images to be included in the list?

**Comment by Arvinderpal** [comment]
:+1:  on keeping this as a milestone. 
I suppose steps 3 and 4 from above would be something along the lines of:

1. `docker save`  tars on clusterctl host
2. scp tars to all nodes on the mgmt cluster
3. `docker load` tars on all mgmt cluster nodes

We could put the above steps under `clusterctl init --prepull-images` and this would be in addition to the `--list-images` flag. 

Would love to help with this. :)

**Comment by Arvinderpal** [comment]
Thinking about this a bit more in the context of private repositories. We have several options:

1. We leave it to the user to ensure that all the required images are present in their private registry.
2. We support listing the required images but leave it to the user to then pull, tag and then push them to their private repo.
3. We support an init sub-command -- e.g. `--push-to-private-repo <repo-address>` -- where  (i) User provides the private registry address and ensures the clusterctl host has appropriate access privileges. (ii) We inspect the yamls to extract all the required images and we also overwrite the repo name with that of the private repo. (iii) We pull the images from external sources, tag them using the private repo name and push them to the private repo. 

IMO, option (3) would be really useful.
