### ISSUE TITLE
Fixes needed for infrastructure provider implementer guide

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#1831]
#1682 introduced new provider documentation. There are a few issues that need to be addressed in the current state of the docs:
- docs/book/src/providers/implementers-guide/building_running_and_testing.md
  - Deployment -> Cluster API
    - Link for cloning the cluster-api repo is broken
- docs/book/src/providers/implementers-guide/create_api.md
  - MailgunClusterSpec definition
    - Requester field is missing json tags and is not indented the same as previous lines.
- docs/book/src/providers/implementers-guide/generate_crds.md
  - Under Create a Repository
    - link for go modules is broken

/kind bug

**Comment by ncdc** [comment]
@prankul88 has a PR open for this but he's not in the org yet, so we can't assign it to him. Assigning to myself to indicate that it's assigned.

/assign
