### ISSUE TITLE
Add targets to build/test/verify test/infra/docker

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#1837]
**User Story**

As a [developer] I would like to run `make` commands from the cluster-api directory to execute build/test/verify commands in test/infrastructure/docker.

**Anything else you would like to add:**

Also hook up to CI.

/kind feature

**Comment by ncdc** [comment]
I don't _think_ we necessarily need new prow jobs for capd. We probably can just integrate it into scripts/{ci-build.sh,ci-make.sh,ci-test.sh} etc. WDYT?

**Comment by wfernandes** [comment]
I also noticed that when I run `make test` in test/infrastructure/docker I get the following error:
```
make: *** No rule to make target `lint', needed by `test'.  Stop.
```
The Makefile in test/infrastructure/docker doesn't have targets `lint` and `lint-full`. There are quite a few linting errors in that repo so if we decide to create `lint` targets then we would have to address the linting errors to get `make test` to pass.

**Comment by vincepri** [comment]
The inner Makefile definitely needs some attention, so +1 to that. 

The prow jobs should be discussed in a different issue. It might be worthwhile to be separate and only run if we're changing anything in the sub-folder, so we can save CI time on every PR.
