### ISSUE TITLE
Document logging standards

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#1840]
If returning errors to the controller-runtime error, the logger no longer shows the line where the fault occurred, and the controller implementation cannot make use of structured logging in that area, which can lead to inconsistent logging.

Standards for logging should be documented.

/kind documentation

**Comment by ncdc** [comment]
/unassign

Looking for someone else to carry this forward

**Comment by vincepri** [comment]
Closing this for lack of action items, logging is now primarily dependent upon controller runtime

/close
