### ISSUE TITLE
KubeadmConfig bootstrapping isn't working (or is slow) in master

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1849]
**What steps did you take and what happened:**
This job tests CAPI master against CAPA master and is failing: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cluster-api-provider-aws-make-conformance-master/1202917621897367552.

If you look at the CAP* artifacts, you'll see the KubeadmConfig resources have empty statuses: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cluster-api-provider-aws-make-conformance-master/1202917621897367552/artifacts/logs/capa.info.

Looking at the CAPA log, the last "cluster infrastructure not ready" log line is at 12:01:43. 

We see bootstrap data is still not available at 12:18:45:

```
2019-12-06T12:18:45.021100977Z stderr F I1206 12:18:45.019804       1 awsmachine_controller.go:289] controllers/AWSMachine "msg"="Bootstrap data is not yet available" "awsCluster"="test-1575633003" "awsMachine"="test-1575633003-controlplane-0" "cluster"="test-1575633003" "machine"="test-1575633003-controlplane-0" "namespace"="default" 
```

It appears that maybe (?) it's generated and ready to go in the last log line for the pod:

```
2019-12-06T12:18:48.131236953Z stderr F I1206 12:18:48.131032       1 awsmachine_controller.go:380] controllers/AWSMachine "msg"="Creating EC2 instance" "awsCluster"="test-1575633003" "awsMachine"="test-1575633003-controlplane-0" "cluster"="test-1575633003" "machine"="test-1575633003-controlplane-0" "namespace"="default" 
```

Then the test is killed due to a timeout waiting to get the kubeconfig secret for the cluster.

**What did you expect to happen:**
It works.

**Anything else you would like to add:**
Maybe this is from the recent v1alpha3 kubeadm types?

**Environment:**

- Cluster-api version: master e.g. commit dbd90a99a

/kind bug
/priority critical-urgent
/milestone v0.3.0

**Comment by vincepri** [comment]
The providers weren't using the correct version. Although the real issue is this line https://github.com/kubernetes-sigs/cluster-api/blob/master/bootstrap/kubeadm/controllers/kubeadmconfig_controller.go#L464-L465 which only reconciles the objects if the version matches v1alpha3.

Should we keep it like this or update it so we reconcile for v1alpha2 as well?

**Comment by vincepri** [comment]
At least we've proven that conversion webhooks are working for kubeadm types :)

**Comment by detiber** [comment]
> The providers weren't using the correct version. Although the real issue is this line https://github.com/kubernetes-sigs/cluster-api/blob/master/bootstrap/kubeadm/controllers/kubeadmconfig_controller.go#L464-L465 which only reconciles the objects if the version matches v1alpha3.

> Should we keep it like this or update it so we reconcile for v1alpha2 as well?

This is mainly for the version listed on the reference, which is something we should probably update during conversion (since we own both the types in this case).

**Comment by ncdc** [comment]
The version _shouldn't_ be an issue - the controller should only be watching a single version, and the conversions should be happening from any other version to the watched version. If the data post-conversion isn't modifying the apiVersion, we should not look at the apiVersion and just match on GroupKind

**Comment by vincepri** [comment]
The controller is watching a single version, but the reference was pointing to a v1alpha2 object and wasn't matching in the `if` condition linked above as @detiber mentioned.

I'll update the kubeadm config controller to look only for GroupKind, I don't think we should update the references in conversion though.

**Comment by detiber** [comment]
> I'll update the kubeadm config controller to look only for GroupKind, I don't think we should update the references in conversion though.

If we don't update the references, then at some point through upgrades they will no longer be referencing a supported api version, which would then require the user to manually change the api version for the objectRef.

**Comment by ncdc** [comment]
Updating the refs is a separate area of concern. If we want to consider doing that, let's please file an issue to discuss.

**Comment by vincepri** [comment]
I'm torn because we let the user create the objects and link them together, +1 on creating another issue about it

**Comment by detiber** [comment]
Created https://github.com/kubernetes-sigs/cluster-api/issues/1852 for discussing the conversion.
