### ISSUE TITLE
Support clusters without external control-plane endpoints / load balancer in v1alpha3

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api#1850]
**User Story**

As a user/operator I would like to deploy a cluster that does not rely on an external control-plane endpoint in v1alpha3 because some platforms lack native load balancer capabilities, the facility commonly leveraged for external endpoints.

**Detailed Description**

In v1alpha2 it is possible to deploy a cluster that does not rely on an external control-plane endpoint. This is possible because of the API endpoint discovery workflow diagrammed below:

![API endpoint discovery](https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-vsphere/master/docs/design/api-endpoint-discovery.svg?sanitize=true)

We would like CAPI v1alpha3's `Cluster` and `KubeadmConfig` controllers to continue to support the behaviors in the above workflow in order to continue the enablement of infrastructure providers on platforms without a native load balancing solution.

**Anything else you would like to add:**

It's understood that clusters deployed in this manner will not support control plane upgrades, and that is a risk that can be explained via documentation at the infrastructure provider level.

/kind feature

cc @yastij

**Comment by ncdc** [comment]
I think it would probably take a lot of work to special-case this type of effort, and given that we want to move in the direction of full lifecycle management (including upgrades), I don't believe this is the proper path forward.

I would prefer that we work on having at least one reference implementation of a load balancer (with machines as the backends) that can be deployed across a wide variety of environments. Examples could include HAProxy, nginx, Envoy, Kubernetes services, etc.

The work that @moshloop started on Machine Load Balancers (#1761 and the more-current Google Doc) is where I would like to see us go.

Does that make sense?

**Comment by akutz** [comment]
Hi @ncdc,

Thank you for such a thoughtful response. I tend to agree with you, but I want to let @yastij chime in when he's back online. Thank you!

**Comment by ncdc** [comment]
I meant to circle back to this a while ago and never did... I don't think there is anything stopping either the Cluster or KubeadmConfig pieces from continuing to work the way they did before KubeadmControlPlane. Would it be ok to close this and either reopen or file a new issue if we find there are things that break the behavior?

**Comment by ncdc** [comment]
Discussed in the community meeting. Closing.
/close
