### ISSUE TITLE
webhook conversions for Machine* resources should automatically update the api group version for their bootstrap references

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#1852]
**User Story**

As a workload cluster operator I would like cluster-api to handle updating the api versions used in the references to KubeadmConfig and KubeadmConfigTemplate resources.

**Detailed Description**

Part of the conversion process for Machine* resources should be to update the api group versions for objectRefs to KubeadmConfig and KubeadmConfigTemplate resources. Otherwise after cluster-api has been upgraded to a point that the API version is no longer supported it would require a manual external modification to update the objectRef to a supported API version.

Since this objectRef is there for the use of cluster-api controllers to fetch and reconcile the child resources, it should be the responsibility of cluster-api to ensure that the api version for the references is kept in sync with the version that the controllers request.

/kind feature

**Comment by vincepri** [comment]
As outlined in https://github.com/kubernetes-sigs/cluster-api/pull/1938#issuecomment-585440209 this might not be the solution we actually want.

I'm going to bump this from the milestone for now, let me know if that's ok with you all

/milestone Next

**Comment by vincepri** [comment]
/close

Closing this given that as of v0.3.0 we now understand contract versions from the CRDs
