### ISSUE TITLE
Add liveness and readiness probes

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1855]
**User Story**

As a developer/user/operator I would like to have liveness and readiness probes for the Cluster API manager so that I am better informed when it is operational and ready to receive requests.

**Detailed Description**

See user story.

**Anything else you would like to add:**

It would be ideal if the readiness probe could only return true once the webhook server is online and ready to receive requests. I'm not sure how feasible this is, though.

/kind feature
/milestone v0.3.0
/priority important-soon
/help

**Comment by prankul88** [comment]
@ncdc I would like to work on this if possible

**Comment by chuckha** [comment]
This will be important for the e2e tests. I pretty much have to resort to retrying my creates until the webhook services are ready to respond. Would be happy to work with you @prankul88 if you'd like, feel free to reach out on slack or here. No obligation though, if you'd like to tackle it yourself that works for me too.

**Comment by ncdc** [comment]
Note, whatever we don't won't be 100% accurate and may still flake because the goroutine our readiness checks run in is different from the goroutine for the webhook server. See https://github.com/kubernetes-sigs/controller-runtime/issues/723 for more details.

**Comment by prankul88** [comment]
@chuckha Thanks. Would love your help. Give me some time to have a little more knowledge about it. Will reach out :)

**Comment by ncdc** [comment]
There is work in progress for CAPA here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1487/. We should be consistent.
