### ISSUE TITLE
kubeconfig secret is not cleaned when control-plane Machine is deleted

### ISSUE THREAD

**Issue by jaimegag** [kubernetes-sigs/cluster-api#1861]
**What steps did you take and what happened:**
When creating a `control-plane` Machine, 5 secrets are created (prefixed with the cluster name) in the management cluster: `ca, etcd, sa, proxy and kubeconfig`.
However if you delete the `control-plane` Machine (`kubectl delete -f xxx-control-plane.yml`), only 4 secrets are deleted and the `kubeconfig` one is left behind.
If you create the `control-plane` Machine again, the `kubeconfig` secret is not updated and is no longer holding the right certificate info that is installed in the `control-plane` node. So when you create your `kubeconfig` from the `kubeconfig` secret, your `kubectl` commands will fail when checking the kube-api server certificate.

**What did you expect to happen:**
All 5 secrets are deleted when the `control-plane` Machine is deleted.

**Anything else you would like to add:**

**Environment:**

- Cluster-api version: v0.2.7
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): v1.1.5.5
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04.6 LTS

/kind bug

**Comment by ncdc** [comment]
The kubeconfig secret is created and owned by the cluster. I know we've discussed this in the past, so @chuckha might have some more back history. Going forward, this secret will belong to the KubeadmControlPlane (if you're using that).

**Comment by ncdc** [comment]
The KubeadmControlPlane will own this going forward.
/close

**Comment by rosskukulinski** [comment]
@ncdc can you provide a little bit more detail? Is this a v1alpha3 change?  Is this something that lands in 6 months?

**Comment by ncdc** [comment]
@rosskukulinski it will be in v1a3. If you use KubeadmControlPlane, that owns the kubeconfig secret. If you opt not to use KubeadmControlPlane, the Cluster owns it.
