### ISSUE TITLE
Add cluster api e2e test to CI

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#1884]
**User Story**

As a developer I would like to run `make test-e2e` in cluster-api's CI to improve test coverage and increase confidence in expected behavior.

**Detailed Description**

We can add this as a pre-submit job for now. See this discussion: https://github.com/kubernetes-sigs/cluster-api/pull/1859#discussion_r356215082

**Anything else you would like to add:**
This issue can be worked on after this PR https://github.com/kubernetes-sigs/cluster-api/pull/1859 is merged in.

I'm guessing a PR needs to be made to test-infra: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api/cluster-api-presubmits.yaml

/kind feature

**Comment by chuckha** [comment]
@wfernandes do you see these e2e tests as providing benefit over either the integration tests or the capd-e2e tests?

**Comment by wfernandes** [comment]
@chuckha I do believe they provide a benefit. I had a couple of issues where these tests would've caught some bugs if they were being run in CI.

- https://github.com/kubernetes-sigs/cluster-api/issues/2068
- https://github.com/kubernetes-sigs/cluster-api/pull/1958

I also believe they are stable and hopefully won't be a burden to maintain.

**Comment by chuckha** [comment]
Gotcha! thanks :) 

/lifecycle active
