### ISSUE TITLE
Introduce the control plane provider

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#1890]
**User Story**

As an operator I would like to use swappable control plane provider for my-management clusters

**Detailed Description**

*sorry if I didn't catched this need in advance while discussing the Kubeadm Based Control Plane Management / the clusterctl CLI stub*

The kubeadm Based Control Plane Management offers a higher-level abstraction for manging control planes.

However, this abstraction depends on the usage of kubeadm, and being the kubeadm bootstrap provider swappable, also the kubeadm Based Control Plane Management should be swappable as well.

This issue is for discussing how this can be addressed and what impacts this can have on clusterctl

Currently, I see two options.
1. Bind the Kubeadm Based Control Plane Management and the kubeadm bootstrap provider into a unique provider; this does not requires changes to the clusterctl UX, but IMO this is a kind of a stretch
1. Introduce a new category of providers, the "Control-Plane providers", and adapt the clusterctl UX to manage this. This will require probably a new flag to `clusterctl init` and a defaulting rule to similar to the one required for the kubeadm bootstrap provider + TBD

Most probably some other changes will be required in both cases, depending on how this provider should be deployed (e.g. in a separated namespace or as "addon" of CAPI/CABPK) 

**Anything else you would like to add:**

/area clusterctl
/cc @vincepri @ncdc @detiber 

/kind feature

**Comment by vincepri** [comment]
For v1alpha3 I'm leaning towards the first option, bundle the control plane with the bootstrapper. This would allow us to move quicker towards release without having to introduce yet another concept into the mix, and solves the problem of separating kubeadm bits from CAPI.

**Comment by detiber** [comment]
Personally, I'd prefer option 2, since it would avoid us having to split it apart later and handling any type of conversion or migration needed.

**Comment by vincepri** [comment]
Closing now that #1916 has merged

/close

**Comment by detiber** [comment]
I believe we still need this issue to track adding support to clusterctl v2 for the new "controlplane provider"

**Comment by vincepri** [comment]
Going by the issue description, seems it was only to address the solution related to the controlplane implementation, which has been done.

@fabriziopandini Do you want to keep using this one for clusterctl as well or open a new one?

**Comment by fabriziopandini** [comment]
@vincepri if I follow this thread/[the code](https://github.com/kubernetes-sigs/cluster-api/blob/83c7edf23e727d89880f3adc697a9db41488e98c/Makefile#L296-L301) properly there will be 4 YAML for each cluster-api project release:
1. `core-components.yaml` (capi core components)
2. `bootstrap-components.yaml` (kubeadm bootstrap provider components)
3. `controlplane-components.yaml` (kubeadm control plane provider components)
4. `cluster-api-components.yaml` (batteries included: core + kubeadm bootstrap + kubeadm controlplane)

This is ok, but I would prefer to keep the issue open until we define if:
- if 2. 3. are self-contained (all of them deploy CRD, RBAC and the controller) e.g. https://github.com/kubernetes-sigs/cluster-api/blob/83c7edf23e727d89880f3adc697a9db41488e98c/config/bootstrap/kustomization.yaml does not install the CABPK manager. Who is in charge to deploy the CAPBK manager? (same for the kubeadm controlplane)
- if 2. 3. are going to be deployed in dedicated namespaces e.g. https://github.com/kubernetes-sigs/cluster-api/blob/83c7edf23e727d89880f3adc697a9db41488e98c/config/bootstrap/kustomization.yaml targets the capi-system namespace, while in v1alpha2 CAPBK was deployed in a separated namespace.

As soon as the two points above are clarified we can close this and I can track the clusterctl work in the existing tracking issue.

/re-open
/cc @rsmitty

**Comment by detiber** [comment]
If we do choose to deploy 2 and 3 to a separate namespace along with the manager, we would also need to add the ability to disable the "core controllers" or have separate controller-managers for each of the providers.

We are also currently encountering an issue with deploying the kubeadmcontrolplane webhooks properly that are related to breaking out the kubeadmcontrolplane from the core components. If we had a separate controller manager, it would allow us to basically leverage the same boilerplate from controller-runtime to solve that problem as well.

**Comment by fabriziopandini** [comment]
So I see two options:
a) make the kubeadmcontrolplane and the kubeadmbootstrap as "addons" to the core provider (same namespace, same manager of CAPI)
b) make the kubeadmcontrolplane and the kubeadmbootstrap similar to any provider (dedicated namespace, dedicated manager)

a) might seems easier from a CAPI release perspective, but 
- it introduces a new entity, "the addon"; the lifecyle of the addons should be defined: can I add/remove addons? how adding/removing addons impacts on the CAPI deployment?
- it introduces a special for kubeadmcontrolplane and the kubeadmbootstrap, because none of the other external controlplane/bootstrap provider will be embedded in the CAPI manager.

Considered all the above implication, from a clusterctl perspective, b) is ways simpler that a)

**Comment by fabriziopandini** [comment]
considering also the thread https://kubernetes.slack.com/archives/C8TSNPY4T/p1577721107071100, it sees that that a) brings also problems around webhooks.

So b) have also the advantage that it fits better in the kubebuilder model

**Comment by fabriziopandini** [comment]
/assign
/lifecycle active

https://github.com/kubernetes-sigs/cluster-api/pull/2099 implements the clusterctl part of this issue (everything else should be already in place)
