### ISSUE TITLE
Cannot import e2e framework from infrastructure provider

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api#1895]
**What steps did you take and what happened:**
It is not currently possible to import the e2e framework from an infrastructure provider due to the framework's relative import of CAPI. Attempting to build with Go or running a `go mod` command will result in the following error:

```shell
go: sigs.k8s.io/cluster-api/test/framework@v0.0.0-20191213221537-1bb8132e8c03 requires
	sigs.k8s.io/cluster-api@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**What did you expect to happen:**
For things to work.

**Anything else you would like to add:**
An infrastructure provider can fix this by running:

```shell
export _golang=$(grep '^go' go.mod) && \
       _module=$(grep '^module' go.mod) && \
rm -f go.sum && cat <<EOF >go.mod && make modules && unset _golang _module
${_module}

${_golang}

require (
  sigs.k8s.io/cluster-api master
  sigs.k8s.io/cluster-api/test/framework master
)

replace (
  sigs.k8s.io/cluster-api => sigs.k8s.io/cluster-api master
)

EOF
```

Long-term an infrastructure provider should not be required to use a `replace` to resolve the version error when importing the test framework. This likely means the test framework should avoid using a relative import. Understandably this makes development harder on the multiple modules found in the cluster-api repository. 

At the same time it's not clear the burden of working around the issues created by the relative imports should be the responsibility of external repository owners to resolve. Especially given the fact that the purpose of the test framework is to be used by as many infrastructure providers as possible.

**Environment:**

- Cluster-api version: `master` (1bb8132e8c034d0d24346e3138747e94a90f6d18)

/kind bug
/area testing

cc @chuckha

**Comment by vincepri** [comment]
@akutz Can you test again the import now that the linked PR has been merged?
