### ISSUE TITLE
[Question] How can I auto scale my cluster?

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#1897]
After the cluster was created by cluster api, how can I auto scale the cluster based on workload?

FYI @detiber @vincepri

**Comment by gyliu513** [comment]
I found a related issue here https://github.com/kubernetes/enhancements/issues/609 , but no recent update for it.

**Comment by vincepri** [comment]
We've put some possible work for the cluster autoscaler in the roadmap draft document linked in #1863. This is definitely something we'd like to do, we need a spike to outline the needed efforts.

**Comment by gyliu513** [comment]
Good to know, thanks @vincepri
