### ISSUE TITLE
Add support for multi-project clusters on GCE

### ISSUE THREAD

**Issue by mkjelland** [kubernetes-sigs/cluster-api#191]
Once PR #183 is merged, a single project for a cluster is defined in the GCEClusterProviderConfig. Only a single project is supported. This issue is to allow the GCEClusterProviderConfig to take a list of projects that are supported for the cluster. Then each machine will need to define its own Project field in GCEMachineProviderConfig, which will be required to be in the list in GCEClusterProviderConfig.

Provisioning of networks, firewall rules and service account permissions will be impacted by this change.

**Comment by rsdcastro** [comment]
Curious as to whether we heard about this use case from users and any more details they might have reported.

**Comment by mkjelland** [comment]
This came out of a conversation about where the configuration for the project field should be stored in PR #183

**Comment by rsdcastro** [comment]
Got it. It seems like no specific example was mentioned, just as a general possibility. Let's keep this issue open to gather more input.

**Comment by roberthbailey** [comment]
This issue was moved to kubernetes-sigs/cluster-api-provider-gcp#35
