### ISSUE TITLE
Remove terraform binary from source tree

### ISSUE THREAD

**Issue by craigtracey** [kubernetes-sigs/cluster-api#192]
The terraform binary has been checked in to the tree.  This makes the tree large and has git complaining about large file sizes.  And, from a technical perspective, vendoring a binary in this way can have other undesirable aspects (ie. will we vendor it forever? what about security updates? etc).

While it is already too late for tree bloat, we should remove terraform from the tree and, instead, pull the terraform binary in with a Dockerfile.

**Comment by craigtracey** [comment]
Related: https://github.com/kubernetes-sigs/cluster-api/issues/152

**Comment by rsdcastro** [comment]
See #185 which is pulling the terraform binary on container creation.

**Comment by karan** [comment]
Yeah we can just nuke it -- it's now installed as part of the controller image.
