### ISSUE TITLE
kubeadm init fails to recognize docker installed via snap 

### ISSUE THREAD

**Issue by adiastra** [kubernetes-sigs/cluster-api#1926]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

Installed docker using 
snap install docker --classic

**What did you expect to happen:**
kubeadm to recognize that the docker service was installed and running

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

root@sbt-linux20191:~# snap install docker --classic
Warning: flag --classic ignored for strictly confined snap docker

docker 18.09.9 from Canonical✓ installed
root@sbt-linux20191:~# kubeadm init --node-name master --dry-run
W1218 18:08:01.437533   28491 validation.go:28] Cannot validate kube-proxy config - no validator is available
W1218 18:08:01.437721   28491 validation.go:28] Cannot validate kubelet config - no validator is available
[init] Using Kubernetes version: v1.17.0
[preflight] Running pre-flight checks
        [WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING FileExisting-socat]: socat not found in system path
        [WARNING Hostname]: hostname "master" could not be reached
        [WARNING Hostname]: hostname "master": lookup master on 127.0.0.53:53: server misbehaving
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR Service-Docker]: docker service is not active, please run 'systemctl start docker.service'
        [ERROR Swap]: running with swap on is not supported. Please disable swap
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by adiastra** [comment]
root@sbt-linux20191:~# snap services
Service         Startup  Current   Notes
docker.dockerd  enabled  active    -
kubelet.daemon  enabled  inactive  -
lxd.activate    enabled  inactive  -
lxd.daemon      enabled  inactive  socket-activated

**Comment by adiastra** [comment]
root@sbt-linux20191:~# which docker
/snap/bin/docker
root@sbt-linux20191:~#

**Comment by vincepri** [comment]
This issues seems like it should be reported upstream in kubeadm, given that Cluster API is mostly a user of kubeadm.

/priority awaiting-more-evidence

**Comment by ncdc** [comment]
Closing due to age. If this is for kubeadm proper, please file an issue at https://github.com/kubernetes/kubeadm.

/close

**Comment by neolit123** [comment]
@adiastra 
kubeadm looks for `docker` command in PATH.
if the command is not present there there is no way to execute commands such as `docker pull`.
adding "snap" detecting is a non-goal for kubeadm.

you either need to make sure the `docker` command works, or not install docker from snap.

**Comment by Alex2357** [comment]
> @adiastra
> kubeadm looks for a `docker` command in PATH.
> if the command is not present there there is no way to execute commands such as `docker pull`.
> adding "snap" detecting is a non-goal for kubeadm.
> 
> you either need to make sure the `docker` command works, or not install docker from snap.

I have exactly same problem.  

```
john@john-VirtualBox:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
john@john-VirtualBox:~$ which docker
/snap/bin/docker
john@john-VirtualBox:~$ 

john@john-VirtualBox:~$ sudo su
root@john-VirtualBox:/home/john# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
root@john-VirtualBox:/home/john# which docker
/snap/bin/docker
root@john-VirtualBox:/home/john# 
```
```
