### ISSUE TITLE
ExcludeNodeDrainingAnnotation contains io.io

### ISSUE THREAD

**Issue by vivgoyal** [kubernetes-sigs/cluster-api#1930]
\bug
ExcludeNodeDrainingAnnotation = "machine.cluster.x-k8s.io.io/exclude-node-draining"
This annotation has repeated string io.io

**Comment by ncdc** [comment]
/kind bug
/help
/good-first-issue
/priority important-soon
/milestone v0.3.0

I'm not sure that we should adjust the constant in v1alpha2, but we definitely should fix it in v1alpha3.

**Comment by vivgoyal** [comment]
Its doesnt harm anyone so its fine to keep as is in v1alpha2 but good to fix in v1alpha3

**Comment by vincepri** [comment]
Need to migrate during conversion as well, don't we?

**Comment by prankul88** [comment]
> Need to migrate during conversion as well, don't we?

@vincepri Can you please elaborate?

**Comment by vincepri** [comment]
We have conversion webhooks in place, you can find them under `api/v1alpha3/<type>_webhook.go`. When we perform v1a2<->v1a3 conversions, we need to convert the annotation in the old/new format.

**Comment by detiber** [comment]
The conversion webhooks are under `api/v1alpha2/<type>_webhook.go`, the defaulting and validation webhooks are under `api/v1alpha3/<type>_webhook.go`.

**Comment by vincepri** [comment]
What Jason said :)

**Comment by vincepri** [comment]
The conversions are actually hosted here https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha2/conversion.go

**Comment by prankul88** [comment]
@vincepri @detiber Thanks 
/lifecycle active

**Comment by ncdc** [comment]
@prankul88 are you still working on this?

**Comment by prankul88** [comment]
@ncdc Sorry for the delay. Will push a patch against this soon.

**Comment by ncdc** [comment]
@prankul88 any updates on this? Thanks!
