### ISSUE TITLE
Mark kubeadm fields optional & omitempty + document defaults if kubeadm defaults the fields

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1941]
**User Story**
We can make the Kubeadm types a little nicer to use by allowing empty values where kubeadm will fill in default values. See #1939 for an example.

To close this issue we should audit all the fields of Kubeadm config files to see which are defaulted and which are not.

**Detailed Description**
/kind feature

/priority important-longterm
/milestone Next

**Comment by vincepri** [comment]
@fabriziopandini this would be good to tackle soon-ish as well if you're up for it

**Comment by vincepri** [comment]
cc @sethp-nr
