### ISSUE TITLE
Labels should be propagated from MachineDeployment/set to infrastructure provider

### ISSUE THREAD

**Issue by Lokicity** [kubernetes-sigs/cluster-api#1943]
**User Story**
Right now, when adding labels to MachineDeployment, it only propagate to the Machine object but not the AWSMachine. This makes using label selection on AWSMachine difficult.

**Detailed Description**
When label MachineDeployment, AWSMachine created as part of the MachineDeployment be labeled as well

**Anything else you would like to add:**
Talked to @aaroniscode and @vincepri, this feature can be added in v1alpha3

/kind feature

**Comment by detiber** [comment]
My testing PR has a change that allows for setting owner refs when cloning templates.
