### ISSUE TITLE
MachineSet shouldn't use update as a fallback for Status.Replicas

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1945]
Once the support for CRDv1 lands in Cluster API, we should default MachineSet.Status.Replica field to "0" and remove the fallback to Status().Update() from the MachineSet controller.

/kind cleanup
/assign
/milestone v0.3.0
/priority important-longterm

**Comment by ncdc** [comment]
Note, this requires CRDv1 support in controller-runtime (https://github.com/kubernetes-sigs/controller-runtime/pull/752, and possibly others) and a new release of c-r, so this may take some time before it's actionable.

**Comment by vincepri** [comment]
I was planning to update to master controller-runtime when the linked PR merges, until we have a release. That way, we can move 1.16 along

**Comment by vincepri** [comment]
/milestone v0.3.4

This should be pretty straightforward now that we have webhooks in place, it's a matter of removing https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/machineset_controller.go#L674-L684

**Comment by benmoss** [comment]
With the fallback call to `Update` removed I am still seeing

```
[capi-controller-manager-85d9865b55-d9lpg manager] I0415 14:02:12.712185       9 recorder.go:52] controller-runtime/manager/events "msg"="Warning"  "message"="failed to patch MachineSet's Status: MachineSet.cluster.x-k8s.io \"ben-md-0-75475bdf58\" is invalid: status.replicas: Required value" "object"={"kind":"MachineSet","namespace":"default","name":"ben-md-0-75475bdf58","uid":"f46145da-8e4b-4f32-9216-ea19dcc58726","apiVersion":"cluster.x-k8s.io/v1alpha3","resourceVersion":"6112"} "reason"="ReconcileError"
```
