### ISSUE TITLE
Define release cycle

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1949]
We should formally define & document & adhere to a proper release cycle for this project. It doesn't have to be too heavyweight, and could look something like this:

1. Start of cycle: review all open issues (backlog grooming)
1. Feature freeze: cutoff date for deciding which features are in/out for the release
1. Code freeze: cutoff date when all new features should be ready & merged
1. Something about alpha/beta/RC releases & bug fixes
1. Release day

I'd love to have advice and guidance from people who have worked on Kubernetes releases to know what we should consider doing (e.g. @justaugustus)

This came out of the v1alpha2 retrospective (#1438)

**Comment by vincepri** [comment]
Merging this with #2372 

/close
