### ISSUE TITLE
Document personas

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1951]
As part of the v1alpha2 retrospective (#1438), we said we wanted to document personas for this project. @tashimi, @moshloop, @samba, and I met and came up with a document. This is a reminder to convert it to markdown and add it to docs/book.

**Comment by elmiko** [comment]
i talked with @ncdc online today and he shared [this document](https://docs.google.com/document/d/1agSWDp1s_ESirNi-5g1WTMuzfAkxkvjO9WIBHRcjmn8/edit). i am going to take a stab at converting it for the book.

/assign

**Comment by ncdc** [comment]
Thanks!
/unassign
