### ISSUE TITLE
Guard around generated names for machines from machinesets/machine deployments

### ISSUE THREAD

**Issue by k4leung4** [kubernetes-sigs/cluster-api#196]
The current logic for generating machine names for machinesets is to append a hash to the name in the template spec.
If the template spec name is long, it may force the generated name to exceed the max length allowed for a kubernetes object.

The machine set controller should validate the generated name length is valid and that the validation logic for the template spec should check the base length is short enough to have a hash be appended.

**Comment by vincepri** [comment]
We should also document what the limitations are and provide some sort of early validation.

**Comment by chuckha** [comment]
The validations and guards are built into kubernetes. If the template spec name is long, the GenerateName function handles it correctly: 

https://github.com/kubernetes/apiserver/blob/master/pkg/storage/names/generate.go#L49

I tried to reproduce this error with a machine spec name of length 251 and everything was fine.

/close

Please reopen and provide reproduction steps and the error encountered.
