### ISSUE TITLE
Should CAPI pod in 0.2.8 have a kube_rbac_proxy sidecar like CABPK?

### ISSUE THREAD

**Issue by corrieb** [kubernetes-sigs/cluster-api#1960]
This isn't really a bug, but means of tracking a question that was asked in Slack.

CAPBK 0.1.5 has the kube_auth_proxy sidecar and our infrastructure provider pod also uses the kube_auth_proxy. I believe it's to protect the metrics endpoint.

CAPI 0.2.8 doesn't have this sidecar configured. Curious as to whether that's an oversight or deliberate. 

Thanks.

/kind feature

**Comment by ncdc** [comment]
It's possible the sidecar came from a newer version of kubebuilder generation. We'll investigate & make sure this is consistent.

**Comment by noamran** [comment]
Summarizing a discussion with @ncdc -
In **v1alpha2**, the sidecar is enabled in [CABPK](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/master/config/default/kustomization.yaml#L29) while it’s not present in [CAPI](https://github.com/kubernetes-sigs/cluster-api/blob/release-0.2/config/default/kustomization.yaml).
This probably stems from the fact that an older version of kubebuilder was used for CAPI. 

In **v1alpha3**, the sidecar is enabled in [CABPK]( https://github.com/kubernetes-sigs/cluster-api/blob/master/bootstrap/kubeadm/config/default/kustomization.yaml#L33) and the [KCP](https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/config/default/kustomization.yaml#L33) but not for [CAPI](https://github.com/kubernetes-sigs/cluster-api/blob/master/config/core/kustomization.yaml#L37).

Based on the _Is the metrics endpoint protected ?_ part of the _Monitoring_ section in the [kubebuilder book](https://book-v1.book.kubebuilder.io/beyond_basics/controller_metrics.html.) - we should have it enabled for all our managers. 
Will work on enabling the sidecar in the master core capi manager.

**Comment by chuckha** [comment]
Thanks for the update! I wondered where that came from (sidenote: I removed a period in the kubebuilder book link if you're wondering why i edited your comment)

**Comment by joonas** [comment]
This was fixed in #2035 against master.

@corrieb do you need this backported for v1alpha2?

/close
