### ISSUE TITLE
Delegate Node drain to Cluster API controller on upgrade

### ISSUE THREAD

**Issue by dippynark** [kubernetes-sigs/cluster-api#1967]
**User Story**

As a developer I would like to trigger a drain of a Node before replacing it for a upgrade.

**Detailed Description**

Cluster API does not specify the behaviour when a Machine version is changed and it is up to the infrastructure provider whether to perform an [in-place upgrade or a replace](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20181121-machine-api.md#in-place-vs-replace).

In the case or a Node replace, it would be useful if an infrastructure provider could signal to the Cluster API controller to drain the Node before deletion to reuse [existing drain functionality](https://github.com/kubernetes-sigs/cluster-api/pull/1096).

If the infrastructure provider could simply delete the corresponding Machine before a replace and rely and some higher level object (e.g. a MachineDeployment) recreating the Machine then that could trigger the existing drain functionality, but this seems like too much power to be given to a infrastructure provider and wouldn't solve the issue for standalone Machines.

Should such a drain be a responsibility of the Cluster API controller or should the infrastructure provider be required to perform the drain in this case?

**Anything else you would like to add:**

I am implementing a [Kubernetes infrastructure provider](https://github.com/dippynark/cluster-api-provider-kubernetes) where Nodes run as Pods. In this case, a Node replace makes the most sense when performing an upgrade and I am trying to decide how to implement this. 

The corresponding issue is [here](https://github.com/dippynark/cluster-api-provider-kubernetes/issues/3).

This seems to overlap with the following issue: https://github.com/kubernetes-sigs/cluster-api/issues/1271
But I feel this issue differs in that it wants to answer how to inform the Cluster API controller that a drain is necessary rather than how to perform a drain.

/kind feature

**Comment by detiber** [comment]
@dippynark triggering an upgrade (either of the whole cluster or an individual MachineDeployment) really isn't part of the role of an Infrastructure provider, but rather something/someone above cluster-api.

It is generally expected that Machines should be immutable after creation: https://master.cluster-api.sigs.k8s.io/user/concepts.html#machine-immutability-in-place-upgrade-vs-replace and that changes are made using a MachineDeployment.

**Comment by dippynark** [comment]
@detiber great thank you - sorry I missed that assumption
