### ISSUE TITLE
Extract kubeadm providers into their own manager

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1971]
Very open to feedback/changes on this issue.

***Goals***
1. Separate core components from Kubeadm specific components
1. Provide a batteries included YAML manifest
1. Provide individual components YAML manifest (core, kubeadm-bootstrap, kubeadm-control-plane)
1. Provide a release image for the core provider and the kubeadm-bootstrap provider and the kubeadm-control-plane provider.
1. Get master working with KubeadmControlPlane

***Non-Goals/Future Work***
1. Extract non-kubeadm related components from core

**User Story**

We need a clean separation so the kubeadm components can each be replaced. 

**Detailed Description**

I plan on:

* adding `main.go` to `cluster-api/bootstrap` and `cluster-api/controlplane`
* extracting the kubeadm related components (bootstrap provider & control plane) and associated webhooks into a new main.go in the above directory
* Working on fleshing out the release story.
  * adding Makefiles to the `cluster-api/bootstrap` and `cluster-api/controlplane` directories (maybe)

**Contract changes [optional]**

* Remove the kubeadm flag on the core cluster-api manager.
* Besides that, this should be transparent to the user. The quickstart will point at the newly generated manifest. Quickstart clusters will not be affected.

**Data model changes [optional]**

None

/kind proposal

/cc @vincepri @detiber @rsmitty @fabriziopandini

**Comment by detiber** [comment]
> **Goals**
> 
> 1. Separate core components from Kubeadm specific components
> 2. Provide a batteries included YAML manifest
> 3. Provide individual components YAML manifest (core, kubeadm)

This should likely be core, kubeadm bootstrapper, kubeadm control plane

> 4. Provide a release image for the core provider and the kubeadm provider

Similarly, should likely have the bootstrapper and kubeadm control plane listed separately here.

> 5. Get master working with KubeadmControlPlane

> **Detailed Description**
> 
> I plan on:
> 
> - adding a new cmd/kubeadm-manager

Should be a new manager for each of the kubeadm-based providers

> - extracting the kubeadm related components (bootstrap provider & control plane) and associated webhooks into a new main.go in the above directory

Similar to above, should be separate managers.

> - Working on fleshing out the release story.

**Comment by fabriziopandini** [comment]
+1 on splitting in three: core, kubeadm bootstrapper from the kubeadm control plane

**Comment by chuckha** [comment]
oof, we want three? that seems like overkill to me, is there a time when we'd replace the kubeadm control plane and not the kubeadm bootstrapped?

**Comment by chuckha** [comment]
> +1 on splitting in three: core, kubeadm bootstrapper from the kubeadm control plane

Does this make it easier for clusterctl?

**Comment by detiber** [comment]
Main reasons for preferring 3 separate controller managers over 1:
- Each are separate types of providers
- One may want to deploy the Kubeadm Bootstrapper without the Kubeadm Control Plane support
- One may want to customize the behavior of either the bootstrapper or the control plane provider for their own needs and consume the upstream variant of the other.

**Comment by chuckha** [comment]
I think in light of that, I'll put the main.go in the cluster-api/bootstrap and cluster-api/controlplane directories. Updating main description.

**Comment by detiber** [comment]
@chuckha I wonder if it would make sense for each of the "batteries included" providers to have it's own separate `config` directory as well, rather than the current way we are attempting to split them out today?

**Comment by chuckha** [comment]
I'd say yes, that would likely be easier. I think each provider would basically need to be a kubebuilder project. They are set up that way already right now, just missing main.go, config and makefile

**Comment by ncdc** [comment]
Another data point, FYI: when you combine multiple controllers in a single process, they all share the same shared informer caches for cluster, machine, etc. (less overall memory usage). When you split them into multiple processes, they can't share (more overall memory usage).

**Comment by chuckha** [comment]
> Another data point, FYI: when you combine multiple controllers in a single process, they all share the same shared informer caches for cluster, machine, etc. (less overall memory usage). When you split them into multiple processes, they can't share (more overall memory usage).

Do we have data points on our memory usage? This is good to be aware of but until we can show that there is a significant difference and people actually care about really pushing the memory footprint down, we can avoid hacks by keeping the managers separate. This also makes it easier for folks to simply not use our bootstrap provider or control plane provider if they want to implement their own.

**Comment by ncdc** [comment]
I don't, no. Just mentioning it so you're aware. And I don't have any objections to splitting them up. Also, anyone extremely conscious about memory could potentially build a custom binary that incorporates whatever controllers they need (e.g. core + bootstrap + control plane + infra).
