### ISSUE TITLE
MachineDeployment annotations should be under x-k8s.io

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1984]
The annotations described in https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/mdutil/util.go#L42-L53 are still under the old domain. They should be moved under the new `x-k8s.io` domain for consistency.

As part of this change, we need to add support in the conversion logic between the old/new annotation.

/kind cleanup
/help

**Comment by alexander-demichev** [comment]
Talked with @hpandeycodeit and got his approval to assign this issue on me :)
