### ISSUE TITLE
Implement a shared framework for creating test objects

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#1993]
The PR https://github.com/kubernetes-sigs/cluster-api/pull/1977 is introducing a framework that creates test objects (clusters, machines etc.), taking care of all the relations/ancillary objects like secrets etc.etc.

As per comment https://github.com/kubernetes-sigs/cluster-api/pull/1977#discussion_r362238933, the framework, currently specifically designed for clusterctl move, might come in handy for unit/integration testing elsewhere within the repository.

This issue is for collecting use cases/possible requirement for broader use in the repo and for discussing how to make this happen (e.g. where to relocate the framework)

/cc @detiber @vincepri

**Comment by vincepri** [comment]
@fabriziopandini do we want to keep this open?

**Comment by fabriziopandini** [comment]
IMO we can close this, because there is no additional use cases collected so far.
We can always re-open/re-create when something concrete shows up.
/close
