### ISSUE TITLE
Push job is broken

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1998]
**What steps did you take and what happened:**
https://prow.k8s.io/?repo=kubernetes-sigs%2Fcluster-api

This is blocking me moving forward with e2es since the additional managers are not getting images pushed.

/kind bug
/assign

**Comment by ncdc** [comment]
I think we're hitting a 20-minute max time for a single cloud build

**Comment by ncdc** [comment]
Yes, `1200s` in `cloudbuild.yaml`.
