### ISSUE TITLE
GCP: document how to tear down a cluster created via Cluster API

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#20]
_From @rsdcastro on January 29, 2018 21:55_

_Copied from original issue: kubernetes/kube-deploy#527_

**Comment by mkjelland** [comment]
@rsdcastro is this for GCE specifically? It seems like we should have 2 separate issues, one for each provider, until clusterctl support deletions. I'm imagining the document will describe how to delete all GCE resources that were created by the cluster api and by kubernetes.

**Comment by rsdcastro** [comment]
I agree about having 2 separate issues. Can you please rename this to focus on GCP and have another to document for vSphere?

**Comment by mkjelland** [comment]
@rsdcastro I don't think I have the ability to rename this one, do you?

**Comment by rsdcastro** [comment]
Done. We need to fix permissions in the repo to allow you to do it.
