### ISSUE TITLE
Write conversion unit tests

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2002]
As a follow-up to #1992, we need to write some unit tests in a `conversion_test.go` file that goes alongside our `conversion.go` files that unit-tests conversions from v1alpha2 -> v1alpha3 and vice-versa.

/kind cleanup
/milestone v0.3.0
/priority important-soon

**Comment by joonas** [comment]
@vincepri is there more work that needs to be done here still?

**Comment by vincepri** [comment]
Nope, this is all done

/close
