### ISSUE TITLE
Reconcile external methods in Cluster and Machine should respect Paused behavior

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2006]
As a follow-up to #1985, we need to add support for the Cluster and Machine reconciler to stop the reconciliation on external objects if the objects have the pause annotation.

/kind feature

**Comment by nader-ziada** [comment]
@vincepri should the check be on `paused` status of the cluster, or the external objects themselves?

**Comment by vincepri** [comment]
Just the objects, the `reconcileExternal` methods aren't going to be called if the Cluster is Paused

**Comment by joonas** [comment]
@nader-ziada are you actively working on this?

**Comment by nader-ziada** [comment]
@joonas i haven’t started on it yet. Did you want to work on it?
