### ISSUE TITLE
SSH Provider to support already provisioned machines (VMs)

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#201]
The current providers (gcp, terraform) both target environments that have infrastructure APIs. They create machines with these APIs and then provision the machines with Kubernetes.

The SSH provider targets environments with machines already provisioned with an OS. It does not create the machines, but only provisions them with Kubernetes. This is useful in a "bare metal" environment where PXE/iPXE (or similar mechanisms) are not available.

The provider must be given each machine's address (hostname/IP) and a valid SSH private key.

The initial idea is for the machine's address to be a property of the MachineSpec ProviderConfig, and for the SSH private key to be stored in a Secret labeled with the name of the cluster.

**Comment by dlipovetsky** [comment]
I and colleagues at Platform9 are actively working on this, but plan to initially host it in a separate repo. Once we do, we hope to find additional maintainers and eventually request a repo, as per #152.

Can someone /assign me?

**Comment by rsdcastro** [comment]
Thanks, Daniel.

I'm curious on the approach. Can you share more details on how you're planning to do it? We can perhaps discuss that in the community meeting to get feedback.

Please also post the link to the repo you're using for it.

/assign dlipovetsky

**Comment by dlipovetsky** [comment]
@rsdcastro Absolutely, I will share a doc.

**Comment by dlipovetsky** [comment]
Here is a [proposal gdoc](https://docs.google.com/document/d/1B2j_OzZ18ITIefrI7KyKxfgHku3E7X_lLlgAcCERvms/edit?usp=sharing). Thanks in advance for your feedback.

**Comment by rsdcastro** [comment]
Copying a few more people that can help review this document.

cc @krousey @roberthbailey @karan @mkjelland

**Comment by roberthbailey** [comment]
@dlipovetsky - I read through your doc and left some comments. Do you have any ideas how this would work with MachineSet or MachineDeployment?

**Comment by dlipovetsky** [comment]
@roberthbailey Thanks for your feedback!

We would like to take advantage of MachineDeployment for server-side rolling upgrades, but I haven't come to any conclusions about how the provider would work with MachineSet or MachineDeployment, although I'm starting to think about it now!

Perhaps the MachineSet controller can create the Machine objects with a ProviderConfig that omits machine-specific values like Host, and these objects can remain in a "crash loop" where the SSH machine actuator's Exists method keep returning an error (since without a Host value, it can't SSH to the machine) until the user updates the ProviderConfig.

An alternative might be for the user to create Machine objects with complete ProviderConfigs and labels, then create a MachineSet with the right selector, and wait for the controller to adopt the Machine objects.

On a note related to MachineSet, we will use the SSH provider to deploy multiple masters, and would like to revive the discussion about support for multiple masters in controllers, e.g., a MachineSet variant with semantics resembling a StatefulSet.

**Comment by iamzhout** [comment]
@dlipovetsky Hi, Daniel, is there any further work or discussion on this proposal? 

I'm also interested in this topic.

**Comment by timothysc** [comment]
Closing as it's out of the scope of the core.
