### ISSUE TITLE
Control plane should scale up serially, not in parallel

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#2016]
We recently implemented [control plane scale up](https://github.com/kubernetes/kubeadm/issues/1793). If the desired number of control plane machines exceeds the actual number, and at least one control plane machine exists, the controller will create multiple machines in parallel. (Once created, each machine runs `kubeadm join --control-plane`).

I think we should scale up control planes serially. Before creating an additional control plane machine, we should verify that every etcd member has started. We could also verify that the etcd cluster has quorum (if it does not have quorum, creating a new machine might be a waste of time and resources. On the other hand, if it does have quorum, it might lose it after we create the machine)

Today, etcd still [recommends](https://etcd.io/docs/v3.3.12/op-guide/runtime-configuration/) that the cluster be scaled up or down one member at a time. Moreover, there are [known issues](https://github.com/kubernetes/website/issues/17870) with running kubeadm join --control-plane in parallel.

In the future, we will likely be able to scale up in parallel by using etcd non-voting members (learners). Kubeadm is already [exploring this idea](https://github.com/kubernetes/kubeadm/issues/1793).

/cc @detiber @randomvariable @chuckha

**Comment by dlipovetsky** [comment]
#1902 is required to scale the control plane serially.

**Comment by dlipovetsky** [comment]
I think we meant to spell this out in the proposal; I will file a PR to update it.

**Comment by chuckha** [comment]
Some interesting information regarding this issue: https://github.com/kubernetes/kubeadm/issues/2001#issuecomment-573189739

It's tracked upstream here: https://github.com/kubernetes/kubeadm/issues/1793

Until that is fixed we should indeed join serially or block on `kubeadm join` call and only run at concurrency level 1.

**Comment by ncdc** [comment]
Fixed by #2335 
/close
