### ISSUE TITLE
Unable to make cluster object using docker provider

### ISSUE THREAD

**Issue by prankul88** [kubernetes-sigs/cluster-api#2028]
**What steps did you take and what happened:**
I have been following https://master.cluster-api.sigs.k8s.io/user/quick-start.html for setting CAPI with docker provider. I was able to do just fine with the management cluster. When applying cluster object I got an unusual error:
 `unable to recognize "cluster.yaml": no matches for kind "Cluster" in version "cluster.x-k8s.io/v1alpha3"`
`unable to recognize "cluster.yaml": no matches for kind "DockerCluster" in version "infrastructure.cluster.x-k8s.io/v1alpha3"`

**What did you expect to happen:**
I expected it to create a cluster object (I wasn't getting such error in v1Alpha2)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.2.8
- Minikube/KIND version: v0.6.1
- Kubernetes version: (use `kubectl version`): v1.15
- OS (e.g. from `/etc/os-release`): ubuntu

/kind bug

**Comment by ncdc** [comment]
https://master.cluster-api.sigs.k8s.io/user/quick-start.html is the documentation for the bleeding edge master branch of the repository. I see you wrote you're using cluster-api v0.2.8 - is that correct? If so, that does not contain the v1alpha3 api version. If you are using v0.2.8, you should follow the instructions at https://cluster-api.sigs.k8s.io/user/quick-start.html, which is for the stable v1alpha2 version.

If you want to use v1alpha3, you need to use the master branch of cluster-api from git. The easiest way to do that is follow the instructions at https://master.cluster-api.sigs.k8s.io/developer/tilt.html.

/assign
/priority awaiting-more-evidence
/milestone Next

**Comment by prankul88** [comment]
@ncdc Correct. I didn't realise that the CAPI components applied were of v2. 
In the quick start section of the link I was following, it has referred to v0.2.8 for installing CAPI components. Would it be nice to change that?

Otherwise, this issue is not valid. Will close it. Thanks

**Comment by ncdc** [comment]
We'll update the quickstart when we get closer to the v1alpha3 release. At this time, however, I don't believe there are any updates we can make to it.
