### ISSUE TITLE
CONTRIBUTING link on the 'book' version is broken

### ISSUE THREAD

**Issue by iranzo** [kubernetes-sigs/cluster-api#2046]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

Go to https://cluster-api.sigs.k8s.io/introduction.html

Click on `Contributor Guide` that points to: https://cluster-api.sigs.k8s.io/CONTRIBUTING.html

**What did you expect to happen:**
Get contributor guide shown

/kind bug

**Comment by vincepri** [comment]
The fix has been applied on the master branch, are you willing to backport it to `release-0.2`? https://github.com/kubernetes-sigs/cluster-api/commit/301fc1f19d3e4f1974d1d9370d4890a5fa81e139

**Comment by iranzo** [comment]
Let me try to do it

**Comment by iranzo** [comment]
Hopefully handled in https://github.com/kubernetes-sigs/cluster-api/pull/2052

**Comment by ncdc** [comment]
Fixed.
/close
