### ISSUE TITLE
util package: Make functions that fetch/filter many Machines consistent with one another

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#2062]
The `util` package has functions that fetch or filter many machines. Some functions use the `clusterv1.MachineList` type, others use `[]*clusterv1.Machine`. Let's standardize on one.

(Issue came out this discussion: https://github.com/kubernetes-sigs/cluster-api/pull/2037#discussion_r366055528)

/priority important/long-term

**Comment by dlipovetsky** [comment]
> The change looks fine, although the slice of pointers has the benefit of avoid unnecessary copies when passing the items around.

-- https://github.com/kubernetes-sigs/cluster-api/pull/2037#discussion_r365606448

**Comment by pydctw** [comment]
> @pydctw Are you going to work on this issue?
thanks for the reminder. Sorry but I didn't have a chance to work on it. I will unassign for now

**Comment by fabriziopandini** [comment]
@CecileRobertMichon, does https://github.com/kubernetes-sigs/cluster-api/pull/4160 fixes this problem?

**Comment by CecileRobertMichon** [comment]
It doesn't. I can take that one separately though since I'm already in that area.

/assign
