### ISSUE TITLE
Move relevant code from controlplane to util package

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#2063]
Some functions (e.g. that fetch or filter Machines) should be moved from the controlplane package to the util package.

(Issue came out of this discussion: https://github.com/kubernetes-sigs/cluster-api/pull/2037#discussion_r366055528)

**Comment by vincepri** [comment]
@benmoss this might be worthwhile to explore this cycle

**Comment by benmoss** [comment]
@dlipovetsky is this still relevant? We now rely a lot on the `FilterableMachineCollection` in KCP, would that be what we want to move to util?

**Comment by dlipovetsky** [comment]
I think this got done, but the issue wasn't closed.

**Comment by CecileRobertMichon** [comment]
Actually did this in #4160
