### ISSUE TITLE
Kubeadm-based control plane management KEP: Decide support policy for non-control-plane workloads on control plane machines

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#2064]
Control plane replicas that are machines can also run non-control plane workloads. Let's figure out how this affects
(a) control plane workloads
(b) the control plane management design

(Discussion started here: https://github.com/kubernetes-sigs/cluster-api/pull/2037#discussion_r365607020)

**Comment by vincepri** [comment]
Good discussion topic for weekly's meeting

**Comment by dlipovetsky** [comment]
Good point! I missed this today. I'll add it to next week's agenda.

**Comment by detiber** [comment]
imo, we can assume that users may want to run non-control plane workloads, however I don't necessarily think we need to take that fully into account when managing the machines. Rather I would prefer that we focus on describing the behaviors so that users that wish to run non-control plane workloads on the control plane Machines will be able to design their deployment and management strategy on top of it in a way that will work as they expect.

**Comment by dlipovetsky** [comment]
From @timothysc in the meeting: Is a control plane machine cordoned and drained when it is deleted?

Yes; the control plane manager does not implement the delete; the Machine controller does that, and it does cordon and drain.

**Comment by dlipovetsky** [comment]
> imo, we can assume that users may want to run non-control plane workloads, however I don't necessarily think we need to take that fully into account when managing the machines.

Agree with @detiber. I'd like to make this explicit in the docs, and then close.

**Comment by vincepri** [comment]
/milestone Next

Moving this to next, waiting for more folks to chime in with some guidance / use cases

**Comment by vincepri** [comment]
@dlipovetsky any updates on this issue?

**Comment by jdef** [comment]
we have use cases that involve users running workloads on CP nodes. it would be unfortunate if, for example, control plane nodes were not properly drained before rolling them.

**Comment by ncdc** [comment]
I am also in favor of continuing to drain all nodes, including control plane nodes.

**Comment by vincepri** [comment]
@dlipovetsky @jdef Do you folks have time to add some bits to the Cluster API book or the KCP proposal around this?

**Comment by dlipovetsky** [comment]
Thanks for the ping @vincepri.

>Let's document the current behavior, and possibly extend the KCP documentation (and maybe proposal) to outline what's in scope and out of scope when running workloads on control plane members.

I'll PR this.

/assign

**Comment by vincepri** [comment]
/lifecycle frozen

We need some documentation around this, especially now that we're using KCP extensively

**Comment by fabriziopandini** [comment]
I'm giving a shot to this one
/assign
/lifecycle active
