### ISSUE TITLE
"kubectl get machinedeployments"  should have more metadata, maybe support -o wide as well. 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api#2067]
**User Story**

As a developer I'd like to see `machinedeployment` information in a similar way to how i see deployment information in a standard k8s cluster

**Detailed Description**

In general you can see the number of available pods for a deployment, and other metadata , and even more with `-o wide`... it would be nice to have some symettrey for machinedeployments... so that we can see how many machines are in a cluster, and s o on... Example:
```
$> kubectl get deployments 
myns    mypod    1/1     1            1           21h
```

Whereas right now, in CAPI, we get 

```
➜  bin git:(master) ✗ kubectl get machinedeployment  -o wide
NAME                      AGE
workload-cluster-1-md-0   4h43m
```

**Anything else you would like to add:**

Since we're still alpha, I suspect this issue might be redundant to other UX overhauls or work being done... Feel free to close if its a dupe of a similar UX improvemnt or epic that is already known. '

/kind feature

**Comment by ncdc** [comment]
xref https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/#additional-printer-columns and https://book.kubebuilder.io/reference/markers/crd.html (kubebuilder:printcolumn)

/priority important-longterm
/milestone Next
/area ux
/help
/good-first-issue

**Comment by prankul88** [comment]
@ncdc Will this apply to v1a2 as well?

**Comment by vincepri** [comment]
@prankul88 Let's do this on master (v1a3) for now

**Comment by prankul88** [comment]
@vincepri I am planning to add "Available" and "Ready" fields. Is there any other field that would be a nice addition?
