### ISSUE TITLE
Fix glossary terminology around management clusters

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#2072]
/kind bug
/area documentation

https://github.com/kubernetes-sigs/cluster-api/pull/2042, fixes a linking error, but we have confusing terminology around "target management cluster", which dates to when clusterctl v1 pivoting was the predominant way of using Cluster API.

This terminology needs to be cleaned up in relation to management and guest clusters.

**Comment by wfernandes** [comment]
I can work on this if none are opposed 😄 
/assign

**Comment by ncdc** [comment]
@wfernandes see #2042

**Comment by ncdc** [comment]
@outofmem0ry has a PR for this (with some outstanding requested edits)

**Comment by wfernandes** [comment]
@ncdc Yup. Seems like this is pretty much done. I'll assign it to @outofmem0ry
/assign @outofmem0ry
