### ISSUE TITLE
quickstart lack of instructions to determine control plane is up

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes-sigs/cluster-api#2074]
Section: https://cluster-api.sigs.k8s.io/user/quick-start.html#usage

"After the controlplane is up and running, let’s retrieve the target cluster Kubeconfig:"

How can I determine the control plane is up and running?

/kind bug

**Comment by wfernandes** [comment]
- [ ] Instructions for v1a2 - using kubectl
- [ ] Instructions for v1a3/ KubeadmControlPlane components.
