### ISSUE TITLE
KubeadmControlPlane Spec should be fully mutable

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api#2083]
**User Story**

As an operator I would like to be able to modify a `KubeadmControlPlane` in the following ways:
1. change `.spec.version`
2. change `.spec.infrastructureTemplate`
3. change `.spec.kubeadmConfigSpec`

Each of these changes should produce a result (upgrade kubernetes, change a control plane instance type, modify a kube-apiserver argument).

**Detailed Description**

We have some plans for the `KubeadmControlPlane` involving upgrade. An upgrade, in summary, means making new machines one by one, removing etcd members, checking for the kubeadm configmap, etc. 

I think, if possible, we should just consider this control plane Machine replacement. This gets us a handful of other use cases for free, like modifying cluster configuration, changing infrastructure configuration, etc. The Machines behind the `KubeadmControlPlane` remain immutable but the control plane itself becomes flexible. 

To highlight a specific use case, we have some Cluster API clusters that were not provisioned with `TopologyManager`, and we really need to enable that functionality. I was assuming initially that the upgrade capabilities in v1a3 would help us cover that by providing for Machine replacement. So, for example, we can get both an upgrade and new apiserver arguments simultaneously by changing the spec of a `KubeadmControlPlane` object. 

I think we should consider this before implementing a Machine replacement flow that is _specific_ to upgrades.

Also, sorry I didn't know if this should be a feature or a proposal. 

/kind feature

**Comment by ncdc** [comment]
1 and 2 should already be in the works or implemented.

3 is a bit trickier (and currently disallowed via webhook validation). Once `kubeadm init` has executed, we're only doing `kubeadm join`s going foward, so any changes to the `ClusterConfiguration` or `InitConfiguration` in the `KubeadmConfigSpec` are not evaluated. The `JoinConfiguration` is something we could consider allowing to be mutated, so future control plane `Machine`s could take advantage of whatever changes are in there. The topology manager, for example, appears to be a flag you set on the kubelet, so you probably could modify `JoinConfiguration.NodeRegistrationOptions.KubeletExtraArgs` to enable this (if we allowed mutations).

There's also a use case where someone might need to adjust the apiserver flags when upgrading to a newer minor version (switching from in-tree AWS EBS to external CSI for EBS, for example). Currently we'd need to adjust the `ConfigMap` that kubeadm stores in `kube-system` that contains the `InitConfiguration` and `ClusterConfiguration`. cc @fabriziopandini @randomvariable 

I am 💯 in favor of figuring out how to do this sort of stuff. I'd also like to make sure we take our time with the design, so I'd ask that we do this in v0.3.x or possibly v0.4.0, depending on timing & what the changes look like. WDYT?

**Comment by rudoi** [comment]
Yeah!

No issues with taking our time. I was confident that there were some mechanics in the Kubeadm provider/Kubeadm itself that may complicate this, but I wanted to make sure I called it out as a use case. 

I can take the lead on a proposal/design/etc if that would help.

**Comment by sethp-nr** [comment]
/remove-lifecycle stale

I think the third item is still a valid feature request. It seems likely to tug on / help define #2769 .

**Comment by dhawal55** [comment]
@ncdc If I understand correctly, it is possible to update apiserver flags and other configuration by  updating the `kubeadm-config` ConfigMap in `kube-system` and manually rolling the nodes.

**Comment by ncdc** [comment]
@dhawal55 I believe that will work

**Comment by dhawal55** [comment]
@ncdc Thank you. I tested it and it works. Do you know if progress is made in this regard and are you targeting a specific release milestone for this change?

**Comment by ncdc** [comment]
@dhawal55 I am not aware of any updates. Would you have time to prepare a PR for it?

**Comment by Arvinderpal** [comment]
+1 We (airshipctl community) are building out clusters using CAPI and need finer control over the kubeadm configuration parameters. We also make use of the latest/cutting-edge features in K and would like to upgrade our existing clusters as those features get incorporated into kubeadm. 

One option here is to introduce a run-time flag to KCP (e.g. `--enable-expert-mode`) that bypasses  [validation checks](https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go#L92), and would essentially do the following:

```
allowedPaths := [][]string{
  {"spec", "*"},
  ...
```

See https://github.com/kubernetes-sigs/cluster-api/issues/3014 which brings mutability to `PreKubeadmCommands`, `PostKubeadmCommands` and `Files`. This functionality has recently been merged. 

Also, related to this discussion is https://github.com/kubernetes-sigs/cluster-api/issues/1584 -- which wants to open up `KubeletConfiguration` and `KubeProxyConfiguration`.

**Comment by ncdc** [comment]
We should try to find a solution that works for everyone, and I'd prefer to avoid adding "expert mode" flags to enable something like this.

Additionally, we have to add logic that copies changes made to the KCP spec to the kubeadm ConfigMap that lives inside the workload cluster - it's not sufficient to solely set `allowedPaths` to `*`.

@Arvinderpal would you be able to enumerate which specific fields you'd like to manipulate, and we can consider them on a case by case basis?

Thanks!

**Comment by detiber** [comment]
Part of the issue with updating the kubeadm configmap will be that the version of the kubeadm config stored there will be dependent on the version of kubeadm that was used to create it, and unless that version is < v1.15 I suspect it will be a v1beta2 configuration rather than the v1beta1 configuration that we have embedded in our types.

**Comment by mariusgrigoriu** [comment]
Wouldn't the strategy of taking on individual fields make this a recurring issue and put cluster api always behind whatever capabilities come out in kubeadm? How might we allow the whole config file to be regenerated?

**Comment by detiber** [comment]
> Wouldn't the strategy of taking on individual fields make this a recurring issue and put cluster api always behind whatever capabilities come out in kubeadm? How might we allow the whole config file to be regenerated?

Potentially yes, but we also need to be able to target a least common denominator configuration format to support the minimum k8s version that we expect to support in cluster-api.

Treating the kubeadm config as an opaque blob leads to a few different issues:
- We can't validate the config for users nor provide any type of feedback on why it may be failing to bootstrap/join a cluster
- We can't handle any automation around upgrade related tasks for the cluster
- We fully externalize the complexity to the user to provide a kubeadm config that works for a given kubernetes version they are requesting, rather than providing any assurances on the Cluster API side as to which versions of kubernetes/kubeadm are supported

**Comment by Arvinderpal** [comment]
> @Arvinderpal would you be able to enumerate which specific fields you'd like to manipulate, and we can consider them on a case by case basis?

Can we start with `joinConfiguration.nodeRegistration.kubeletExtraArgs` and also expose (and allow mutation of) `KubeletConfiguration` and `KubeProxyConfiguration` (https://github.com/kubernetes-sigs/cluster-api/issues/1584)?

More than happy to do the leg work in implementing these changes, if we can reach some consensus here.

**Comment by Arvinderpal** [comment]
> Part of the issue with updating the kubeadm configmap will be that the version of the kubeadm config stored there will be dependent on the version of kubeadm that was used to create it, and unless that version is < v1.15 I suspect it will be a v1beta2 configuration rather than the v1beta1 configuration that we have embedded in our types.

Can we assume `v1beta1` for now?

There is a separate issue for v1beta2 here: https://github.com/kubernetes-sigs/cluster-api/issues/3150

**Comment by detiber** [comment]
> Can we assume v1beta1 for now?

For mutating the stored kubeadm config in the workload cluster, unfortunately not. It already is v1beta2 in the general case today and the config map handling we have today around it just happens to get away with there being high similarity between the versions.

> There is a separate issue for v1beta2 here: #3150

That issue is more around being able to consume the v1beta2 config and leveraging the v1beta2 config for bootstrapping nodes.

**Comment by ncdc** [comment]
I would be in favor of `joinConfiguration.nodeRegistration.kubeletExtraArgs`, as I believe that is self-contained (does not have to be copied to the ConfigMap). Does anyone foresee any issues here (other than the possibility that you might specify args that prevent the kubelet from running correctly)?

We should probably continue to use #1584 for fleshing out the component config ideas.

**Comment by ncdc** [comment]
For v1beta1 vs v1beta2 in the ConfigMap, we are currently working with the data as `*unstructured.Unstructured`, which means we don't specifically to have convert to/from versioned kubeadm go types, but @detiber is correct that we have been lucky up til now that things are generally compatible in this space between v1beta1 and v1beta2. We may need to start adding logic that checks the apiVersion of the `ClusterConfiguration` in the ConfigMap, and then alter our behavior based on version.

**Comment by detiber** [comment]
I believe @shysank is currently looking into this
/assign @shysank
/lifecycle active
/remove-help

**Comment by shysank** [comment]
@vincepri @detiber should we open a new issue to track the remaining immutable kcp specs or just reopen this one?

**Comment by detiber** [comment]
@shysank I'm fine either way

**Comment by shysank** [comment]
@rudoi @detiber Would you mind re-opening since I don't have access?

**Comment by vincepri** [comment]
@shysank Could you open different issues for the remaining bits instead of having this high level issue? It'd be good to understand which pieces are missing and tackle them separately, we might be able leverage the help wanted and good first issue tags as well.

/close

**Comment by jdef** [comment]
I see this was closed, are there follow-up issues that should be linked here (because I'm probably interested in following them more closely).

**Comment by shysank** [comment]
@jdef I've created issues for tracking individual items in kcp that are still immutable. Feel free to create new issues if I missed anything.
/cc @vincepri

**Comment by neolit123** [comment]
note that making some of the fields mutable and changing their values, can have strange effects on a running cluster.
some on-the-fly changes in the kubeadm ClusterConfiguration are simply not supported.

- networking - unclear, but likely changing this is not recommended
- dns - ditto
- certificatesDir - this seems fine
- featureGates - these currently only include dual-stack and ecdsa key support. switching the ecdsa gate might be fine, but i don't think this is the case for dual-stack
- hyperkube - deprecated, the field should not be used by CAPI.
