### ISSUE TITLE
[e2e framework] Remove exec calls to kind

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2086]
**User Story**
We depend on the `kind` binary to exist, but we do not need to (for the management cluster). I believe everything used by the framework is exposed by the library as of kind@v0.7.0. But it might be best to double check. Listed below are the `kind` commands used by the management cluster creator in the framework

https://github.com/kubernetes-sigs/cluster-api/blob/master/test/framework/management/kind/mgmt.go

**Detailed Description**
Operations used are:
- kind create cluster --name name
- kind create cluster --name name --config configfile
- kind load docker-image image --name name
- kind delete cluster --name name

Completing this issue will remove a binary dependency for the e2e environment and allow us to only need to manage a single version of kind using go modules instead of installing a binary before running the tests.

**Anything else you would like to add:**
/priority backlog
/milestone Next
/help
/kind feature

**Comment by tahsinrahman** [comment]
Create and delete looks straighforward,   https://github.com/kubernetes-sigs/cluster-api/pull/2089

But there seems no library function in kind for loading docker image. 
https://github.com/kubernetes-sigs/kind/blob/28c928b772d3e4c3553eb445fe6dc0d39b59e323/pkg/cmd/kind/load/docker-image/docker-image.go#L75-L152

**Comment by chuckha** [comment]
@tahsinrahman do you think this function could work? https://github.com/kubernetes-sigs/kind/blob/master/pkg/cluster/nodeutils/util.go#L101

**Comment by tahsinrahman** [comment]
thanks @chuckha ! PTAL :)
