### ISSUE TITLE
Experiment with a kubeadm bootstrap controller rewrite to improve abstractions and unit testability

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2090]
In light of the [fake-client being deprecated](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client/fake) (thanks for keeping an eye on things @vincepri), I believe we should stay ahead of this inevitability. However, without either copying in the fake client and managing it as our own dependency the only other option provided by controller runtime is to set up a real api server and a real etcd cluster (of 1) and run full reconcile tests.

I believe there is an alternative that will provide us with faster tests to program with (that don't require an api server), build abstractions that may become useful across providers and potentially be the base of something like an sdk for cluster api providers, and finally, scratch an itch to experiment a bit more with how reconcilers are refactored. We won't learn if it's a bad idea without trying it out!

The way the kubeadm bootstrap reconcile code is structured now is, essentially, one big pile of code with no clear boundaries. This was an intentional design decision at the outset so that refactoring was easy and we weren't tied to any abstractions we didn't need. Duplicated code was intentional as it's much easier to modify duplicated code than add special cases to immature abstractions.

Because of the current structure, it is very difficult to unit test a single piece of code. The only reason it is possible is because we have a fake client that works well enough for our tests.

In one recent example of where the current reconciler falls short was debugging a race condition. It was pretty difficult to stare at the code long enough and think about it hard enough to see why there was a race condition. I believe it was difficult to debug (besides the inherent difficulty of debugging races) is because the code itself is somewhat complex and hard to reason about. It took me a fair bit of time just staring at the code to see why there was in fact, a race condition.

***Goals***
1. Create a drop-in replacement for the kubeadm bootstrap provider.
    * Subgoal: new provider, as it's an experiment, is completely abandon-able and does not change any code in cluster-api/ until we decide the experiment is a success or failure.
1. Create clear boundaries within the controller of the kubeadm bootstrap provider.
1. Create unit tests for the complex logic within each component of the controller
1. Flesh out e2e tests to ensure we have coverage from an integration perspective
1. Can be worked on independently of Cluster API outside of the repo.
1. Could theoretically unit test to hit least 90+% coverage, but actually doing that is NOT a goal
    * This means that we could easily test almost every line of code. Exceptions are made for things like standard library calls that do not usually fail or generally don't need complex logic and testing. For example, `fmt.Println` returns an `int, error` but we don't need to encapsulate `fmt` package anywhere and we don't really mind not testing it. This is maybe not a great example since there shouldn't be any `fmt.Println` lines in the code.

***Non-Goals/Future Work***
1. Achieve 100% unit test or even close to 100% unit test coverage. The ABILITY to unit test is the important part.
    * To make the same point in a different way. Being able to add a unit test for a specific piece of logic that has bug is effectively the same as adding the test itself. The logic here is that if there is a bug in the code AND you can easily write a test to prove that bug exists then you can easily write that code and fix the bug in the logic. This allows you to not add tests for very simple logic that very likely doesn't have bugs keeping the actual tests needed to be maintained to a minimum

**User Story**

* As a developer I would like to be able to read the controller code and understand what it's doing quickly. 
* As a developer I'd like to have some common functions/types available to help me write my provider.

**Detailed Description**

After a bit of thinking and tinkering, I would want to start with a few additional packages or at least types to help the controller remain as a focused piece of essentially glue code.

The boundaries of each part of the program will generally follow [clean architecture](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html). The inner circles know nothing of the outer circles and are joined together by abstractions (in go, this is interfaces or function types in simple cases).

### Components

These are all subject to change and just a brief idea of what I had in mind. It's just something to get the conversation going that makes sense from looking at existing controllers for a little bit.

#### Controller

The controller is responsible for handling events from kubernetes and deciding if the event should be rereconciled or not. It does not need to have any other functionality besides passing values around and gluing things together to be able to make this decision.

#### Datastore/Client

This is basically the Client with a struct that wraps the Get and Update and whatever calls with something more human friendly than Get/Update.

#### Logger

Pretty much everything needs a logger. Think of this as being part of the inner circle. We already do a decent job of this in the reconciler today.

#### Kubeadm configuration/cloud init generation/certificate management

I haven't figured out the best split here but I think something would make sense as patterns for these abstractions become clear.

**Contract changes [optional]**

None. This would be a drop-in replacement.

**Data model changes [optional]**

None

/kind proposal
/milestone Next

**Comment by vincepri** [comment]
As per April 27th 2020 community guidelines, this project follows the process outlined in https://github.com/kubernetes-sigs/cluster-api/blob/master/CONTRIBUTING.md#proposal-process-caep for large features or changes.

Following those guidelines, I'll go ahead and close this issue for now and defer to contributors interested in pushing the proposal forward to open a collaborative document proposal instead, and follow the process as described.

/close
