### ISSUE TITLE
Generic labels for metrics-services deployed

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#2097]
**What steps did you take and what happened:**
1. `make generate-manifests`
1. `make release-manifests`
1. `kubectl apply -f out/cluster-api-components.yaml`
1. `kubectl get services -A --show-labels`
    ```
    NAME                                                               LABELS
    capi-kubeadm-bootstrap-controller-manager-metrics-service          control-plane=controller-manager
    capi-kubeadm-bootstrap-webhook-service                             <none>
    capi-kubeadm-control-plane-controller-manager-metrics-service      control-plane=controller-manager
    capi-kubeadm-control-plane-webhook-service                         <none>
    capi-controller-manager-metrics-service                            control-plane=controller-manager
    capi-webhook-service                                               <none>
    ... 
    [EDITED output for brevity]
    ```

The labels on the `capi-*-metrics-service` are `control-plane=controller-manager`. These don't seem correct. 

**What did you expect to happen:**
I'd expect them to have no labels like the webhook service or if they are meant to have labels then they should have the corresponding correct labels.

**Environment:**
- Cluster-api version: 827d3e4b339272d249cd3f9432ed4fef604440ea

/kind bug

**Comment by MarcelMue** [comment]
I just watched the recording of the cluster api meeting and want to pick this up.

From the meeting I am not entirely sure if the scope should just be to remove these labels for now or use the provider labels right away that were apparently discussed somewhere.

**Comment by ncdc** [comment]
Thanks @MarcelMue! The provider labels discussed elsewhere are what @wfernandes is working on: #2070 #2112
