### ISSUE TITLE
Support for automated cluster tear down via Cluster API

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#21]
_From @rsdcastro on January 29, 2018 21:57_

_Copied from original issue: kubernetes/kube-deploy#528_

**Comment by roberthbailey** [comment]
@rsdcastro - is this clusterctl delete?

**Comment by roberthbailey** [comment]
/close

If this issue requires something above and beyond `clusterctl delete` then please re-open and add more details.
