### ISSUE TITLE
clusterctl init fails on kind cluster

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#2115]
**What steps did you take and what happened:**
1. kind create cluster
1. In cluster-api repo, `./cmd/clusterctl/hack/local-overrides.py`
1. Ran the output of the above command, for me it was 
`clusterctl init --core cluster-api:v0.3.0 --bootstrap kubeadm-bootstrap:v0.3.0 --infrastructure aws:v0.5.0 -v 4`. 
I added the `-v 4` for verbose output.
1. Got the following error:
```
...
Creating: rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding, /capa-system-capa-proxy-rolebinding
Throttling request took 172.236367ms, request: POST:https://127.0.0.1:62418/apis/rbac.authorization.k8s.io/v1/clusterrolebindings
Error: failed to get current provider object: no matches for kind "" in version "v1"
...
```
**What did you expect to happen:**
Expected it to initialize a management cluster.

**Environment:**
- Cluster-api version: db823b790de0e73614205895dbfbf2b4402bb833
- Minikube/KIND version: kind v0.6.1 go1.13.4 darwin/amd64

/kind bug
/area clusterctl

**Comment by fabriziopandini** [comment]
@wfernandes I can't reproduce the error locally. do you still have the error with the latest commits at master?

**Comment by wfernandes** [comment]
I will try and see if I can reproduce the behavior today. If I'm unable to, I'll close this issue 😄

**Comment by wfernandes** [comment]
This is no longer an issue.
I tested it with Cluster API: 45ca8b1f565f2014ae8c95c8671e357b541e7f61 
/close
