### ISSUE TITLE
Audit the clusterctl UX

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#2118]
Before v1alpha3 is cut, we should audit the new clusterctl UX, ensuring consistency on
- commands, command helps, examples
- flags and flags shorthands (see https://github.com/kubernetes-sigs/cluster-api/pull/2099#discussion_r368408177)
- logs/output
- etc.

**Comment by wfernandes** [comment]
I'll be happy to help with this if you need any. I was planning on going through the extensive documentation and following through step-by-step.

**Comment by vincepri** [comment]
Closing this for now, we can revisit the UX in a future version and during the code walkthrough after v0.3.0 is released

/close
