### ISSUE TITLE
Kind v0.7 no longer supports `kind get kubeconfig-path` failing to create the cluster

### ISSUE THREAD

**Issue by kacole2** [kubernetes-sigs/cluster-api#2120]
**What steps did you take and what happened:**
Related to #1796 and #1801 

Tried to create the management cluster
```
$ clusterctl create cluster \
   --bootstrap-type kind \
   --bootstrap-flags name=management-cluster \
   --cluster ./out/management-cluster/cluster.yaml \
   --machines ./out/management-cluster/controlplane.yaml \
   --provider-components ./out/management-cluster/provider-components.yaml \
   --addon-components ./out/management-cluster/addons.yaml \
   --kubeconfig-out ./out/management-cluster/kubeconfig
```

Error Log:
```
NOTICE: clusterctl has been deprecated in v1alpha2 and will be removed in a future version.
I0122 10:55:37.476538   22406 createbootstrapcluster.go:27] Preparing bootstrap cluster
I0122 10:56:27.770811   22406 createbootstrapcluster.go:36] Cleaning up bootstrap cluster.
F0122 10:56:28.710990   22406 create_cluster.go:61] could not create bootstrap cluster: unable to get bootstrap cluster kubeconfig: error running command: kind get kubeconfig-path --name=management-cluster
Stdout:

Stderr:
ERROR: unknown flag: --name
: exit status 1
```

kind no longer supports kubeconfig-path
```
$ kind get kubeconfig-path
Gets one of [clusters, nodes, kubeconfig]

Usage:
  kind get [command]

Available Commands:
  clusters    Lists existing kind clusters by their name
  kubeconfig  Prints cluster kubeconfig
  nodes       Lists existing kind nodes by their name

Flags:
  -h, --help   help for get

Global Flags:
      --loglevel string   DEPRECATED: see -v instead
  -q, --quiet             silence all stderr output
  -v, --verbosity int32   info log verbosity
```

**What did you expect to happen:**

clusterctl to create the management cluster with kind

**Anything else you would like to add:**
 No issues with Kind 0.6.1. Seems like the 0.7 upgrade removed the flag that clusterctl is using

**Environment:**

- Cluster-api version: 0.2.9
- Minikube/KIND version: 0.7
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):  Ubuntu 18.04 amd64

/kind bug

**Comment by ncdc** [comment]
@kacole2 we are rewriting `clusterctl` and it won't be creating `kind` clusters any more. We could update the documentation in our stable branch that `kind` v0.7+ is not compatible with `clusterctl` from 0.2.x.

**Comment by vincepri** [comment]
For Cluster API 0.2.x, we suggest you to use KIND v0.5 or v0.6. We'll have support for new kind versions in v0.3+

**Comment by kacole2** [comment]
Perfect. Thanks @ncdc and @vincepri. I was following the prior quick start material for CAPV and that's why. Will be on the lookout for v0.3

closing this issue.

**Comment by cloudmaniac** [comment]
Was the documentation updated somewhere? I just had the exact same issue and I couldn't find a branch where the documentation mention kind version.
