### ISSUE TITLE
Control plane failure domain handling

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2131]
Some brief background. A failure domain is a component of infrastructure that can fail. In AWS and azure these can be thought of as availability zone. In Google Cloud these are simply called zones. This concept is named failure domain to also account for other types of infrastructure isolation in environments we don't and can't know about, such as a custom bare metal environment.

There is a bit of an intricate interaction between components:

1. The infrastructure provider [defines a `failureDomains` field in the Status of the InfraCluster struct](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/api/v1alpha3/awscluster_types.go#L89).
2. The infrastructure cluster controller [figures out what availability zones/failure domains exist and sets the status on the InfraCluster](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/controllers/awscluster_controller.go#L169-L181)
3. This data gets [copied into Cluster API buy the cluster controller](https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/cluster_controller_phases.go#L178-L182).
4. This data can now be used by other controllers since other other controllers will have access to the Cluster API cluster object.

In a simple case, the user creates their InfraCluster and Cluster objects and the failure domains get copied over. The kubeadm control plane controller can then take the list of failure domains on the cluster object and start assigning failure domains to machines that it creates. However, there are plenty of ways this can go wrong and edge cases we want to consider.

I firmly believe we can implement a naive solution for v1alpha3 and iterate as we go forward, but this issue can help us flesh out the edge cases that we may encounter moving forward.

# Necessary assumptions

If we make the assumption that all failure domains that the infra cluster controller sets on the infraCluster.status.failureDomains can communicate with each other, then you can stop reading here and close the issue as there won't be a problem in the cases outlined below.

If however, we cannot make that assumption, we may encounter some serious problems, theoretically, that we, at some point, not necessarily v1alpha3, will want to take into account. Below are listed the two cases that will cause problems.

## Case 1: Changing zones

A control plane of n >=3 nodes requires at *least* two reconciliations to become active. The first reconciliation will create the first node. The second reconciliation will create the remaining nodes. The list of failure domains is read from the cluster during each reconciliation loop. This means that if the list of failure domains changes between the first and second reconciliation it is possible to end up in a state where one machine exists in a failure domain that is no longer supported.

## Case 2: Updating zones after initialization

Imagine a happy case where a control plane of n=3 nodes has successfully been created and is evenly distributed across multiple failure domains. Now, something happens to the cloud and the infrastructure provider realizes the availability zones have changed which then triggers an update of the InfraCluster.status.failureDomains which then gets copied into the cluster.status.failureDomains. Now we decide to scale the control plane to n=5. We get two new nodes in two new failure domains. Scale down is an ok event since we aren't adding anything. Upgrade also breaks due to new nodes in new failure domains that don't work with old failure domains.

## Solution, the easy assumption

To see an implementation where we have made the assumption that failure domains work together, please see this PR: https://github.com/kubernetes-sigs/cluster-api/pull/2126.

## Solution, the hard assumption

We will have to manage state relative to the control plane. For example, when a control plane is spun up it captures the failure domains from the Cluster object and DOES NOT update them until either a scale to 0 event or perhaps an upgrade event which would create a new control plane in an entirely new region, however we can't assume migration would work here so this case may be hopeless and the only solution would be new cluster in the new failure domains copied manually with something like velero. 

cc @randomvariable @detiber 

/kind feature

**Comment by randomvariable** [comment]
Think we need to clarify what an availability zone is, as I don't think a simple status field is sufficient in the final end state:

Let's take AWS and Azure separately, as they're the ones I've looked at previously:

### AWS
For AWS, the primary identifier of a host’s membership of a failure domain is the subnet, with a 1:many mapping of subnets to Availability Zones, which themselves function as a "datacentre" unit of availablity within a given region.

In addition, AWS supports [placement groups](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html), for defining rack affinity/anti-affinity rules within an availability zone. For a Kubernetes control plane, it would be recommended to place the machines in a “partition placement group”, which can support rack isolation of up to 7 machines within an AZ. Placement groups need to be created ahead of time and referenced when launching instances using a unique per-region, per-account name.

### Azure
Azure provide three constructs for failure domains - an availability zone provides for individual placement of machines across failure domains. Azure also provides [Availability Sets](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/tutorial-availability-sets), which function as an anti-affinity rule and is recommended for use with HA clustered applications such as etcd, and [Placement Groups](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-placement-groups#placement-groups) which are an affinity rule for low latency applications. Availability Sets and Placement Groups are separate resources created on demand and referenced in the Virtual Machine Scale Set definition.

**Comment by detiber** [comment]
@chuckha my initial concerns where less about the changing of failure domains after a cluster is created as much as:
- We are consistent with the use of failure domains when they are defined. For example, if failure domains are defined we always use them, rather than having a fallback that could not set a failure domain if the controller fails to query Machines.
- A provider implements failure domains where it had previously not supported them and how we handle that for existing Clusters. In this case, I think we can take a naive approach and just reconfigure the existing Machines with their current failure domain, and let the next Upgrade or Scale events handle the spreading of instances across the failure domains rather than trying to reconfigure the existing machines.

**Comment by randomvariable** [comment]
Also, if failure domains change when they're already defined, consider a machine in a now non-existent failure domain as a candidate for replacement?

**Comment by chuckha** [comment]
>  In this case, I think we can take a naive approach and just reconfigure the existing Machines with their current failure domain, and let the next Upgrade or Scale events handle the spreading of instances across the failure domains rather than trying to reconfigure the existing machines.

This is a little bit confusing, how could we reconfigure machines? We'd actually move them to the new updated failure domain list? That seems like a lot of work. I suggest we don't reconfigure anything and simply do nothing to existing machines if failure domains change.
