### ISSUE TITLE
Allow `clusterctl` to specify a custom Workload Cluster template

### ISSUE THREAD

**Issue by aaroniscode** [kubernetes-sigs/cluster-api#2133]
**User Story**

As an operator I would like to be able to choose between multiple Workload Cluster templates when using `clusterctl` to create a new Workload Cluster. I might do this for a few reasons:

* Test different configurations. For example a CAPA cluster template designed to use Calico CNI and another CAPA cluster template designed to use VPC CNI.
* Test a configuration change, like adding Audit configuration to the KubeadmConfig

**Detailed Description**

As an operator I would like to store my Workload Cluster templates in source control, like GitHub. When deploying a cluster using `clusterctl` I'd like to be able to choose the template, like:

`clusterctl config cluster dev --source=https://github.com/aaroniscode/capi-templates/capa-vpc-cni.yaml`

Might also want to be able to use a local file

`clusterctl config cluster dev --source=~/templates/capa-vpc-cni.yaml`

/kind feature
/area clusterctl

**Comment by aaroniscode** [comment]
Some additional notes:

As @Arvinderpal pointed out in Slack, the `--flavor` flag could be used to point to different templates if the source could be changed to a different Github repository, and one where you don't have the requirement to publish a release.

Also when the filesystem backed is merged #1963, having the option to use a local template on the filesystem would be a good option to have.

**Comment by fabriziopandini** [comment]
/lifecycle active
As per various discussions, including also:
- read templates from ConfigMap
- allow listing variables required by a workload cluster template
