### ISSUE TITLE
Consideration for errors in util packages

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2138]
We should evaluate how we use errors and wrapping.

While it is very useful to wrap errors in order to get an accurate stack trace, it is not always the expected thing for a library function to do, especially one that isn't doing anything special with the errors at all. For example, it's very easy to make [this mistake](https://github.com/kubernetes-sigs/cluster-api/pull/2136/files#diff-7b8f8e70923c1014d93b823babc68271R213).

I am leaning towards the opinion of not wrapping errors in util functions as util functions are just that, utilities that are not handling errors for us. If they don't handle errors for us but do wrap the errors then the caller has to remember to unwrap the error. I think that's somewhat unexpected behavior from a util library.

If the caller needs to return the error then they should at that point wrap the error and return.

However, I think this only applies to functions that are trying to wrap calls from the controller runtime client. 

I'm not sure I've come to a good generalization for this problem yet, but would love to hear input if anyone thinks or has thought about this.

I wonder if @davecheney has any thoughts here? (except of course that util is not a good package name 😬)

The overall goal is to not surprise the caller by messing with the error. But maybe it's on the caller to remember to unwrap the errors. 

/kind bug

**Comment by detiber** [comment]
I'm a bit torn on this...  One of the main reasons that we have for wrapping the errors is to improve the ability to debug the issue by giving an accurate stack trace.

The particular bug pointed out would also be relatively easier to handle if we had our own IsNotFound test for errors that automatically did the unwrapping as well. Obviously this isn't an ideal situation either.

Hopefully we can find a decent approach that allows us to keep the ability to have decent stack traces as well as reduce the likelihood of common bugs like forgetting to call errors.Cause() on an error before testing it.
