### ISSUE TITLE
[e2e framework] Enable conformance test suite run

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2141]
I want an e2e test that spins up a cluster, runs the kubernetes conformance tests and returns the results. This would be the first step in automating opening PRs to the kubernetes conformance repo here https://github.com/cncf/k8s-conformance.

If you're looking for inspiration, take a look at CAPA. They aren't using the framework but have implemented the conformance test running workflow.

I estimate this work to take about a week to get right for someone who is familiar with the end-to-end tests.

/kind feature
/milestone Next
/priority important-longterm

**Comment by vincepri** [comment]
closing in favor of https://github.com/kubernetes-sigs/cluster-api/issues/2826

/close
