### ISSUE TITLE
clusterctl repositories: don't exclude versions with semver build metadata

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#2157]
In https://github.com/kubernetes-sigs/cluster-api/blob/54f26d7fd2b5d1c3a96e14bff717040d72fe8b9e/cmd/clusterctl/pkg/client/repository/repository_github.go#L214 and https://github.com/kubernetes-sigs/cluster-api/pull/1963/files#diff-88bc45b90b0324f78a6bea9e5c59aa26R123 (not yet merged), the github and local repositories for clusterctl exclude versions with semver build metadata. I believe we should include versions with build metadata.

/area clusterctl
/priority important-soon
/milestone v0.3.0
/kind feature

cc @fabriziopandini

**Comment by fabriziopandini** [comment]
@ncdc the change is really simple but I'm not sure I understand the use case you want to address.

I expect the provider's author to publish assets/cut a release on github for major/minor releases, eventually, we can assume also pre-release asset will be published (e.g. rc for v1alpha3), but I don't expect anyone publishing release assets for buildversions.

**Comment by ncdc** [comment]
Some authors may use build metadata, so I think it's safer to include these versions.

**Comment by fabriziopandini** [comment]
thank.
Ok in removing this so clusterctl can adapt to whatever the provider's author decides.
/assign

**Comment by ncdc** [comment]
Do you want to see if a new contributor would be interested in taking this up?

**Comment by fabriziopandini** [comment]
/reopen
to track that the same change is required for the FileSystem backend introduced by https://github.com/kubernetes-sigs/cluster-api/pull/1963
/help
/good-first-issue
