### ISSUE TITLE
Rewrite generate-yaml.sh as a go program

### ISSUE THREAD

**Issue by spew** [kubernetes-sigs/cluster-api#216]
The generate-yaml.sh bash script is growing in scope and complexity. We should rewrite it as a go program to make it easier for development as well as testing.

**Comment by karan** [comment]
+1

**Comment by roberthbailey** [comment]
Alternatively, we should move the complex logic into the gcp cluster controller and make it just set env vars like project / zone.

**Comment by roberthbailey** [comment]
This issue was moved to kubernetes-sigs/cluster-api-provider-gcp#19
