### ISSUE TITLE
Clusterctl logging

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#2164]
**User Story**

1. As an operator, I would like to have nice output from clusterctl
2. As an operator, I would like to have knobs to increase verbosity output from clusterctl
3. As an operator, I would like to capture clusterctl output and process it easily, grabbing values when required
 4. As a developer, I would like to get the raw flaw of clusterctl output and do custom processing on it
 5. As a developer, I would like to inject my own logger

**Detailed Description**

Defining the output for a CLI app is tricky. Standard user output, Verbose output/Logs, machine-readable output.

If you look at kubeadm as a prior-art, you can see how those requirements conflated over time:
- "standard" user output is generated via `fmt.Printf`, and this is annoying when trying to use the kubeadm code as a library
- "verbose output" a.k.a. logs are generated via `klog`,  and  `klog` and `fmt.Printf` mixes up in a weird way
- machine output is generated via a separated solution based on API machinery

For clusterctl I would like to tackle the problem in a simpler way.

First of all, I would like to user `logr.Logger` as a reference interface because:
- It is the default logging interface used in cluster API
- it has a nice separation between log messages and values that are added to a log message.
- using an interface allows injecting any logger implementation (use case 6).

Second, I would like to build a custom `logr.Logger`, thus implementing a user-friendly version of the  `klogr.Logger` implementation used in cluster API, so the user output will change from

```
"Msg"="Fetching providers"
"Msg"="Installing the cert-manager"
"Msg"="Waiting for the cert-manager to be available..."
"Msg"="Installing" "Provider"="cluster-api" "Version"="v0.3.0" "TargetNamespace"="capi-system"
"Msg"="Installing" "Provider"="kubeadm-bootstrap" "Version"="v0.3.0" "TargetNamespace"="capi-kubeadm-bootstrap-system"
"Msg"="Installing" "Provider"="docker" "Version"="v0.3.0" "TargetNamespace"="capd-system"
....
```
To
```
Fetching providers
Installing the cert-manager
Waiting for the cert-manager to be available...
Installing Provider="cluster-api" Version="v0.3.0" TargetNamespace="capi-system"
Installing Provider="kubeadm-bootstrap" Version="v0.3.0" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="docker" Version="v0.3.0" TargetNamespace="capd-system"
...
```
With this logger, I can reasonably address the use cases from 1...5 with a solution much more simpler and cleaner that what we have in kubeadm.

See https://github.com/kubernetes-sigs/cluster-api/pull/2150 for a draft implementation of this logger

**Anything else you would like to add:**

/kind feature

/area clusterctl

**Comment by vincepri** [comment]
Do we want to tackle the implementation side of this in the current milestone?

**Comment by fabriziopandini** [comment]
Yes, this or an equivalent solution should be in the milestone

**Comment by vuil** [comment]
+1 on the custom logging. The ability to allow custom processing of the logs produced would be welcomed functionality. Some basic cleansing to improve readability doesn't hurt either.

**Comment by fabriziopandini** [comment]
implemented by https://github.com/kubernetes-sigs/cluster-api/pull/2191
/close
