### ISSUE TITLE
External watchers should key off of GroupKind, not GroupVersionKind

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#2168]
Related to #2140, if we have code like this:

```go
_, loaded := r.externalWatchers.LoadOrStore(obj.GroupVersionKind().String(), struct{}{})
```

we probably need to change it to key off of just GroupKind. Otherwise, if we see an object reference to 2 different API versions for the same kind (e.g. v1alpha2 and v1alpha3 KubeadmConfig), we'll start 2 different `source.Kind` watchers, 1 for each API version.

We'll likely need to tie in to the fix for #2140, because if we have a v1alpha3 controller and it sees a v1alpha2 external object, we'll want to make sure we watch the v1alpha3 objects and not v1alpha2.

cc @detiber @vincepri @chuckha 

/kind cleanup
/priority important-longterm
/milestone Next

**Comment by vincepri** [comment]
This should probably go in v0.3, wdyt? Given that we'll need to find a solution before release

**Comment by ncdc** [comment]
Technically if we watch both a2 and a3 versions, it just means we get the objects enqueued more than we'd like, but I don't think this is strictly required. #2140 is, though.
