### ISSUE TITLE
clusterctl config providers yaml output doesn't work

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#2170]
**What steps did you take and what happened:**
```
$ clusterctl config providers --output yaml
NAME                TYPE                     URL
aws                 InfrastructureProvider   https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/latest/infrastructure-components.yaml
cluster-api         CoreProvider             https://github.com/kubernetes-sigs/cluster-api/releases/latest/core-components.yaml
docker              InfrastructureProvider   https://github.com/kubernetes-sigs/cluster-api-provider-docker/releases/latest/infrastructure-components.yaml
kubeadm-bootstrap   BootstrapProvider        https://github.com/kubernetes-sigs/cluster-api/releases/latest/bootstrap-components.yaml
vsphere             InfrastructureProvider   https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/latest/infrastructure-components.yaml
```
The output is not in yaml format

**What did you expect to happen:**
Expected yaml output.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 7816c0c01a97824103a2ee8fa8078625f0d56d36

/kind bug
/area clusterctl

**Comment by fabriziopandini** [comment]
Currently the output format is implemented only for `clusterctl config providers <provider-name> --output yaml`

But I agree this is not intuitive so I think we should error out in case of `clusterctl config provider --output yaml` (w/o <provider-name>) or split the current command in two so there will be no more confusion.

**Comment by wfernandes** [comment]
Yes. I agree that this feature is not necessary. I don't believe that it needs to be done for the next milestone.
