### ISSUE TITLE
Vendoring k8s/k8s

### ISSUE THREAD

**Issue by jessicaochen** [kubernetes-sigs/cluster-api#218]
There recently has been concern about importing k8s/k8s in the cluster-api repo. As I understand it, the reasoning is:
- k8s/k8s is large.
- We already depend on the client and apimachinery from k8s. If we pull the entire k8s/k8s, there will be multiple copies of code and more opportunity for mixups
- k8s/k8s is complex. It is best to keep dependencies small and easy to reason about.

Created issue to allow for discussion

**Comment by roberthbailey** [comment]
As discussed in the cluster api working group meeting today, we are going to close this issue and **not** vendor k/k into the cluster-api repository. 

/close
