### ISSUE TITLE
Remove protobuf tags from our API types

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#2181]
CRDs do not currently support protobuf encoding, and we have a few fields that currently have protobuf tags on them. We should remove them to avoid confusing developers (we can add back later if/when CRDs support protobuf).

/help
/good-first-issue
/priority important-longterm
/milestone Next
/kind cleanup

**Comment by colinlodter** [comment]
I can take a look at this.

/assign

**Comment by ncdc** [comment]
@colinlodter thanks! Please comment `/lifecycle active` when you start working on it.
