### ISSUE TITLE
[docs] Document how infrastructures should implement failure domain

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2184]
Infrastructure providers will need to do some extra work to enable support for failure domains.

This only applies to control plane machines, but with a little extra work on machine deployments we could extend this to work with worker nodes as well, however distributing workers across failure domains is not a high priority for v0.3.0.

I suggest that in v1alpha3, if infrastructure providers want to support the optional feature of failure domains, the infrastructure provider controllers should **always** populate the FailureDomain on an InfraMachine during a reconcile. Since an InfraMachine is immutable, the part that figures out what failure domain the instance lives on can be skipped if it's already determined.

The reason we want to do this is so we can copy the information out into the Machine type within cluster-api so that the Control Plane providers will have a way to act appropriately as they scale up and down.

/kind documentation
/milestone v0.3.0
/priority important-soon

**Comment by vincepri** [comment]
Regarding generic documentation of how it should be implemented, we should add this to the v1alpha2-to-v1alpha3 document.

The failure domain feature is completely optional and opt-in as it was spec'd in #1269, we should allow for the value to be empty in v1alpha3, and consider to make it a requirement in the next version.

**Comment by chuckha** [comment]
> The failure domain feature is completely optional and opt-in as it was spec'd in #1269, we should allow for the value to be empty in v1alpha3, and consider to make it a requirement in the next version.

It is optional yeah, but if an infrastructure provider *wants* to implement it, I'd suggest they always populate the field, does that make sense? The provider does not have to implement this feature, but if a provider wants to support failure domain, they should always populate the failure domain field on an InfraMachine so that the user has the least amount of work to do (no work whatsoever) if they choose to use it.

**Comment by vincepri** [comment]
Yep! Sounds good to me, I just wanted to make sure because when I first read ` infrastructure providers always populate the FailureDomain on an InfraMachine during a reconcile` it was becoming a requirement.

**Comment by chuckha** [comment]
Ahh, I see, let me see if I can reword that so that's not the initial reaction, thanks for the feedback
