### ISSUE TITLE
clusterctl command supporting a version flag

### ISSUE THREAD

**Issue by tkrausjr** [kubernetes-sigs/cluster-api#2186]
**User Story**

As a consumer(Operator or Developer) of CAPI, when I follow the Providers instructions for using Cluster API I would like to know the current version of clusterctl I am running or have installed and whether it is up to date. Also for troubleshooting / logging issues it would be helpful to be able to report on the version of the executable being used.

[A clear and concise description of what you want to happen.]

` #  clusterapi version
                                                         
Client Version: version.Info{Major:"0", Minor:"2", GitVersion:"v0.2.9", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}`

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by ncdc** [comment]
Hi @tkrausjr, we are completely reworking clusterctl, and we already have #2061 that will be coming in v0.3.0/v1alpha3.

**Comment by tkrausjr** [comment]
OK thanks @ncdc  .Sorry about that I searched Issues but didnt find that one. Closing
