### ISSUE TITLE
Update Finalizer handling to use controller-runtime utilities

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#2198]
**Detailed Description**

Currently we frequently use the following pattern for adding Finalizers in many controllers:

```go
	if !util.Contains(mp.Finalizers, clusterv1.MachinePoolFinalizer) {
		mp.Finalizers = append(mp.Finalizers, clusterv1.MachinePoolFinalizer)
	}
```

and removing Finalizers:

```go
mp.ObjectMeta.Finalizers = util.Filter(mp.ObjectMeta.Finalizers, clusterv1.MachinePoolFinalizer)
```

This was because we adopted the pattern prior to controller-runtime providing utilities around managing Finalizers. Now that [controller-runtime provides utilities for this](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil), we should adopt those.

We should update the current handling of adding and removing finalizers with [AddFinalzer](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil#AddFinalizer) and [RemoveFinalizer](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil#RemoveFinalizer).

/priority important-longterm
/help
/good-first-issue

**Comment by daxmc99** [comment]
@detiber This looks like a good first issue to cut my teeth on for cluster-api. 
Mind if pick it up?

**Comment by detiber** [comment]
@daxmc99 it's all yours.
/assign @daxmc99 
/lifecycle active
