### ISSUE TITLE
[question] where to check if target cluster doesn't have cluster-api object

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#2219]
**User Story**

As a [developer/user/operator] I would like to [high level description] for [reasons]

**Detailed Description**
I am trying to migrate openstack provider from v1alpha2 to v1alpha3 with https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/503

now follow the https://master.cluster-api.sigs.k8s.io/clusterctl/commands/move.html
I am able to create a cluster (control plane) but there is no such pods such as capi-controller-manager-xx and no definition for cluster, machinedeployment etc

I guess it's not pivoting from bootstrap cluster now ? can someone help to provide some guide on if this kind of scenario happens, what should I check? do I need explict run pivoting at v1alpha3 now? thanks

```
root@jj-master:~/go/src/sigs.k8s.io/cluster-api-provider-openstack/examples/output# kubectl --kubeconfig kubeconfig get nodes
NAME                          STATUS   ROLES    AGE     VERSION
test-cluster-controlplane-0   Ready    master   8m57s   v1.17.1
root@jj-master:~/go/src/sigs.k8s.io/cluster-api-provider-openstack/examples/output# kubectl --kubeconfig kubeconfig get pods
No resources found.
root@jj-master:~/go/src/sigs.k8s.io/cluster-api-provider-openstack/examples/output# kubectl --kubeconfig kubeconfig get pods --all-namespaces
NAMESPACE     NAME                                                  READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-564b6667d7-h5zv2              1/1     Running   0          8m45s
kube-system   calico-node-gjnqf                                     1/1     Running   0          8m45s
kube-system   coredns-6955765f44-8t5tk                              1/1     Running   0          8m45s
kube-system   coredns-6955765f44-jxhs6                              1/1     Running   0          8m45s
kube-system   etcd-test-cluster-controlplane-0                      1/1     Running   0          9m1s
kube-system   kube-apiserver-test-cluster-controlplane-0            1/1     Running   0          9m1s
kube-system   kube-controller-manager-test-cluster-controlplane-0   1/1     Running   0          9m1s
kube-system   kube-proxy-6cng6                                      1/1     Running   0          8m45s
kube-system   kube-scheduler-test-cluster-controlplane-0            1/1     Running   0          9m1s

```

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by jichenjc** [comment]
at my bootstrap cluster, I can see following: 

```
root@jj-master:~/go/src/sigs.k8s.io/cluster-api-provider-openstack/examples/output# kubectl get pods --all-namespaces
NAMESPACE                           NAME                                                             READY   STATUS    RESTARTS   AGE
cabpk-system                        cabpk-controller-manager-7846c6796b-66srb                        2/2     Running   0          12m
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-58c9d4c4dc-77p5w       2/2     Running   0          14m
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-5669586667-stgn5   2/2     Running   0          14m
capi-system                         capi-controller-manager-6b5dfc94cf-c7rtb                         2/2     Running   0          14m
capo-system                         capo-controller-manager-79bc567576-4nfrt                         1/1     Running   0          12m
cert-manager                        cert-manager-6b78b7c997-cwh7j                                    1/1     Running   0          17m
cert-manager                        cert-manager-cainjector-54c4796c5d-hnt9p                         1/1     Running   0          17m
cert-manager                        cert-manager-webhook-77ccf5c8b4-6s7p7                            1/1     Running   1          17m
kube-system                         coredns-5c98db65d4-2mk7p                                         1/1     Running   0          18m
kube-system                         coredns-5c98db65d4-8ctdp                                         1/1     Running   0          18m
kube-system                         etcd-clusterapi-control-plane                                    1/1     Running   0          18m
kube-system                         kindnet-w4bkn                                                    1/1     Running   0          18m
kube-system                         kube-apiserver-clusterapi-control-plane                          1/1     Running   0          18m
kube-system                         kube-controller-manager-clusterapi-control-plane                 1/1     Running   0          17m
kube-system                         kube-proxy-tq6fj                                                 1/1     Running   0          18m
kube-system                         kube-scheduler-clusterapi-control-plane                          1/1     Running   0          17m

```

**Comment by ncdc** [comment]
@jichenjc did you see the warning section in the move documentation?

> Before running clusterctl move, the user should take care of preparing the target management cluster, including also installing all the required provider using clusterctl init.

These are the rough steps for a "pivot":

1. Have a source aka bootstrap management cluster (up to you to set this up)
1. `clusterctl init ...`
1. `clusterctl config cluster ... | kubectl apply -f -`
1. Wait for cluster to be up and running
1. Get the kubeconfig for the new cluster
1. `clusterctl init ...` using the new cluster's kubeconfig
1. `clusterctl move ...` specifying the kubeconfigs as appropriate for "from" and "to"

cc @fabriziopandini for 👀

**Comment by fabriziopandini** [comment]
> I am trying to migrate OpenStack provider from v1alpha2 to v1alpha3 

@jichenjc why are you trying to Pivot/Move while trying to upgrade? Am I missing something?

FYI, in clusterctl there is work ongoing for supporting provider upgrade, but it is not yet complete in master ATM; however, at a high level, the upgrade procedure will be:
- delete current providers components (without deleting CRD and namespaces)
- install the provider components for the new version
During this operation, the Cluster API objects (cluster, machines etc.) won't be touched; Cluster API objects will be upgraded by the conversion webhooks in the new provider version.

**Comment by ncdc** [comment]
@fabriziopandini I believe the "migrate" reference was just about updating the code to support v1alpha3. I'm pretty sure this is not an upgrade scenario. I think it's a pure move (pivot) question.

**Comment by fabriziopandini** [comment]
@ncdc ok, then your sequence is the right way to go. 
I'm going to copy/paste into the clusterctl book because this can be useful for other users as well

**Comment by jichenjc** [comment]
@ncdc @fabriziopandini thanks a lot for your help, at v1alpha1 phase I know clusterctl is something will be called and clusterctl is responsible for pivoting and no manual or explict action is needed. 
and I was told clusterctl is deprecated and will be removed (in clusterctl command line output)

```
l# ./clusterctl
NOTICE: clusterctl has been deprecated in v1alpha2 and will be removed in a futu                                                       re version.
```

so I thought it will be other methods to do the migration(pivoting) from bootstrap to new created cluster... now I guess I still need follow above steps (1-7) especially step 7 to do the movement, right? Thanks

**Comment by ncdc** [comment]
That's right. We didn't want to maintain the v1alpha1 implementation of clusterctl, which is why in v1alpha2 we printed out that it was deprecated. But we instead decided to redesign it entirely, which is what you're seeing in v1alpha3 (i.e. it is no longer deprecated, just 100% different).

**Comment by jichenjc** [comment]
ok, got it ,I will read the doc again and try the steps above then work on my PR ( will post result and everything fine will close this issue), thanks

**Comment by jichenjc** [comment]
ok, at least I got following progress after run move command..

Performing move...
 "msg"="Discovering Cluster API objects"
 "msg"="Clusters to move"  "Count"=1

though see this error, might need some code change somewhere..
Error: action failed after 3 attempts: error creating "cluster.x-k8s.io/v1alpha3, Kind=Cluster" test-cluster/test-cluster: no matches for kind "Cluster" in version "cluster.x-k8s.io/v1alpha3"

**Comment by vincepri** [comment]
do you have the stack trace of why the capi controller manager is crashing?

**Comment by jichenjc** [comment]
I followed https://master.cluster-api.sigs.k8s.io/ and perform all the steps there then when the master node is up, I start to use clusterctl move
command and see the error something like Cluster CRD not see in cluster.x-k8s.io/v1alpha2

I struggled a while then decide to give up this way to switch to clusterctl init (the steps above)
but at first step saw this error, maybe openstack not in provider yet..

```
root@jj-master:~/go/src/sigs.k8s.io/cluster-api-provider-openstack# ../cluster-api/bin/clusterctl init
performing init...
Error: failed to get provider components for the "cluster-api" provider: failed to read "core-components.yaml" from provider's repository "cluster-api": failed to download files from GitHub release v0.2.9: failed to get file "core-components.yaml" from "v0.2.9" release
```


```
root@jj-master:~/go/src/sigs.k8s.io/cluster-api-provider-openstack# ../cluster-api/bin/clusterctl config repositories
NAME                    TYPE                     URL
aws                     InfrastructureProvider   https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/latest/infrastructure-components.yaml
cluster-api             CoreProvider             https://github.com/kubernetes-sigs/cluster-api/releases/latest/core-components.yaml
docker                  InfrastructureProvider   https://github.com/kubernetes-sigs/cluster-api-provider-docker/releases/latest/infrastructure-components.yaml
kubeadm-bootstrap       BootstrapProvider        https://github.com/kubernetes-sigs/cluster-api/releases/latest/bootstrap-components.yaml
kubeadm-control-plane   ControlPlaneProvider     https://github.com/kubernetes-sigs/cluster-api/releases/latest/control-plane-components.yaml
vsphere                 InfrastructureProvider   https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/latest/infrastructure-components.yaml

```

**Comment by fabriziopandini** [comment]
if you want to test clusterctl from your local dev env you have to:
- Add the openstack provider to the clusterctl config, as described here https://master.cluster-api.sigs.k8s.io/clusterctl/configuration.html ; please note that the openstack provider is expected to comply the https://master.cluster-api.sigs.k8s.io/clusterctl/provider-contract.html 
- Set up a local overrides as described here https://master.cluster-api.sigs.k8s.io/clusterctl/developers.html

**Comment by jichenjc** [comment]
made some progress based on the info above, @fabriziopandini able to create part of the containers and now facing following error , assume it's related to provide specific issue so working on that, thanks a lot ！


```
 bin/clusterctl init --core cluster-api:v0.3.0 --bootstrap kubeadm-bootstrap:v0.3.0 --infrastructure openstack:v0.5.0 --control-plane kubeadm-control-plane:v0.3.0
performing init...
Error: failed to create provider object apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition, /openstackclusters.infrastructure.cluster.x-k8s.io: CustomResourceDefinition.apiextensions.k8s.io "openstackclusters.infrastructure.cluster.x-k8s.io" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha2", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc00534dff8), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}, apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha3", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc005cf0000), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: must have exactly one version marked as storage version, status.storedVersions: Invalid value: apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha3", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc005cf0000), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}: must have the storage version v1alpha3]
```

**Comment by fabriziopandini** [comment]
@jichenjc let me know if I can help

**Comment by jichenjc** [comment]
I am able to create cluster now (though some other problems still existing), so I close this issue, thanks a lot for your help~

$KUBECONFIG is still set to use /root/.kube/kind-config-clusterapi even though that file has been deleted, remember to unset it
Creating cluster "clusterapi" ...
 ✓ Ensuring node image (kindest/node:v1.15.0) 🖼
 ✓ Preparing nodes 📦
 ✓ Creating kubeadm config 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Cluster creation complete. You can now use the cluster with:

export KUBECONFIG="$(kind get kubeconfig-path --name="clusterapi")"
kubectl cluster-info
performing init...
 - cluster-api CoreProvider installed (v0.3.0)
 - kubeadm-bootstrap BootstrapProvider installed (v0.3.0)
 - kubeadm-control-plane ControlPlaneProvider installed (v0.3.0)
 - openstack InfrastructureProvider installed (v0.5.0)

Your cluster API management cluster has been initialized successfully!

You can now create your first workload cluster by running the following:
