### ISSUE TITLE
IsControlPlane function for metav1.Object

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#2225]
**User Story**

As a developer, I would like to check my InfrastructureMachine is a control plane one without retrieving the Machine via the owner reference, in order that I can apply defaults in my provider.

**Detailed Description**

the `./util` package contains the following:
``` golang
func IsControlPlaneMachine(machine *clusterv1.Machine) bool {
	_, ok := machine.ObjectMeta.Labels[clusterv1.MachineControlPlaneLabelName]
	return ok
}
```

Provide a variant that can do that for runtime.Object or unstructured so it can take infrastructure machines. This would remove duplication in CAPA, as well as this variant in the bootstrap controller:

``` golang
// IsControlPlaneMachine checks if an unstructured object is Machine with the control plane role.
func (co ConfigOwner) IsControlPlaneMachine() bool {
	if co.GetKind() != "Machine" {
		return false
	}
	labels := co.GetLabels()
	if labels == nil {
		return false
	}
	_, ok := labels[clusterv1.MachineControlPlaneLabelName]
	return ok
}
```

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature
/priority backlog

**Comment by vincepri** [comment]
If you need labels, you probably need to use metav1.Object rather than a runtime one

**Comment by randomvariable** [comment]
Yeah, that would also work.

**Comment by randomvariable** [comment]
Turned out not to need this in the end.
