### ISSUE TITLE
KubeadmControlPlane upgrade handling for etcd/coredns/kube-proxy

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#2226]
**User Story**

We need to ensure that during a KubeadmControlPlane upgrade that we are properly handling the management and upgrade of etcd/coredns/kube-proxy as part of the upgrade process. These are things that the external cluster-api-upgrade-tool do not currently address.

From slack conversation:

@detiber: etcd should be fine since it's handled by the static manifests from running kubeadm join controlplane, coredns is likely to be a bit trickier, since it's running as a deployment

@rudoi: coredns is a bit zestier too because that often gets upgraded out of band from kubernetes upgrades - so automated things would need to be aware of default versions and whether or not the current version deployed is newer, etc

@ncdc: the etcd and coredns images/tags are listed in the kubeadm configmap in the workload cluster. if you change the etcd image, the next kubeadm join will pick up the change. if you change the coredns image, you have to run kubeadm init phase addon coredns

/kind feature
/assign @detiber 
/priority important-soon
/milestone v0.3.0

**Comment by ncdc** [comment]
Note, the v1alpha2 upgrade tool supports changing etcd using the `--kubeadm-configmap-patches` feature.

**Comment by chuckha** [comment]
Here's my take at 5:00 on a thursday

1) maintain a map by hand for now from k8s version => core dns version. This solves the problem immediately and buys us a little bit of time
2) write a script to generate the k8s version => core dns map by:
- writing a script that finds all the point versions of kubernetes using git tags 
- For each tag, generate a go script that imports that kubernetes version and prints the kubernetes version and the core dns constant, `constants.CoreDNSVersion`
- Integrate that script into `make generate` and let CI tell us when it needs to be updated.

**Comment by ncdc** [comment]
Jotting down so we don't forget it: CoreDNS also may need to have its config file (which is stored in a ConfigMap) "migrated" when upgrading to a newer version. There is code in kubeadm to do this (it, in turn, vendors code from a CoreDNS repo to do the actual config migration). We presumably don't want to try to vendor the kubeadm code for this, nor do we really want to vendor the CoreDNS migration code, as that ties CAPI/KCP to specific versions of Kubernetes/kubeadm and CoreDNS. It might be worth trying to build container images for various versions of CoreDNS that we can run as part of an upgrade that perform the migration.

**Comment by vincepri** [comment]
We'll do a spike to understand the solutions / requirements
/assing

**Comment by ncdc** [comment]
Some more thoughts:

The ConfigMap should be per KCP controller, live in the same namespace as the controller, and have a standard name such as `cluster-api-kubernetes-addon-versions`. Sample:

```json
{
  "etcd": {
    "1.17": "3.3.17",
    "1.18": "3.3.20",
  },
  "coredns": {
    "1.17": "1.6.5",
    "1.18": "1.6.7",
  }
}
```

When you change `KubeadmControlPlane.Spec.Version`, the KCP controller copies the values from the ConfigMap into `KubeadmControlPlane.Spec.KubeadmConfigSpec.ClusterConfiguration...` (this requires the webhook to allow these values to be mutable). If you try to change `KubeadmControlPlane.Spec.Version` and one of the `ClusterConfiguration` fields for the etcd or CoreDNS image tags, the values from the ConfigMap win.

Before rolling out new machines, the controller updates the `kube-system/kubeadm-config` ConfigMap in the workload cluster with the updated etcd and CoreDNS image tags.

The controller also runs the CoreDNS config migrator and updates the CoreDNS configmap in the workload cluster.

The controller is responsible for updating the image tag in the CoreDNS Deployment, and the image tag in the kube-proxy DaemonSet.

**Comment by detiber** [comment]
Who is responsible for maintaining this ConfigMap? I'd assume that we'd want to ship a default ConfigMap, but how do we determine if we should update the ConfigMap on a ClusterAPI upgrade? We'd at least need a way to determine if a user has modified the ConfigMap to avoid stomping their changes.

**Comment by ncdc** [comment]
My initial thinking was that we could put the plumbing in place for this to be manual, and we could add more automation around shipping a populated ConfigMap later. But maybe that's not a good approach?

For etcd, we know that if you leave `KubeadmControlPlane.Spec.KubeadmConfigSpec.ClusterConfiguration.Etcd.Local.ImageTag` blank, then `kubeadm join` will choose the appropriate version based on what's hard-coded into `kubeadm` itself. So for etcd, you really only need the ConfigMap populated if you're not using the default upstream images... right?

CoreDNS is not updated as part of `kubeadm join`, but rather it could be updated if you ran `kubeadm init phase addon coredns` (this must be run on a workload cluster node, however). If we did somehow orchestrate running this as part of the KCP upgrade process, it would use the version of CoreDNS baked into `kubeadm`, which has the potential to change across different `kubeadm` versions. We would need to ensure we run the version of `kubeadm` that matches the desired version specified in the KCP spec. And, if you needed to use a custom image tag for CoreDNS, the code in `kubeadm` that performs CoreDNS `Corefile` migrations assumes that your image tag matches exactly with the upstream CoreDNS versions (e.g. it needs to be 1.6.7 exactly, and not 1.6.7+some.build.metadata). We could potentially extract this logic and adjust it slightly to be more accommodating of semver build metadata, and run it in the KCP code rather than coming up with a way to run `kubeadm`.

**Comment by detiber** [comment]
> My initial thinking was that we could put the plumbing in place for this to be manual, and we could add more automation around shipping a populated ConfigMap later. But maybe that's not a good approach?

I think my worry is about the level of effort (on both maintainers and on users) into maintaining this approach even if we automate the updating of the ConfigMap...

- How granular would we want to get with the k8s version to other component mapping?
  - Would we want to keep the same patch version granularity that exists with current kubeadm?
  - Would we want to go minor version, and risk potential issues with deploying a newer version of a component for a given patch release?
- Are we willing to tell users that they need to upgrade cluster-api to support a new version of Kubernetes on the workload clusters?
  - How do we handle users that aren't ready to update to the latest release yet? Are we getting into a case where we now have to maintain previous release series for longer?
  - Currently we have an informal support statement, and users could deploy older workload clusters if they support the config version of the Kubeadm bootstrapper, do we now have a more formal support cycle and they are no longer supported (or have to now self-manage the ConfigMap to continue working)?

> For etcd, we know that if you leave KubeadmControlPlane.Spec.KubeadmConfigSpec.ClusterConfiguration.Etcd.Local.ImageTag blank, then kubeadm join will choose the appropriate version based on what's hard-coded into kubeadm itself. So for etcd, you really only need the ConfigMap populated if you're not using the default upstream images... right?

I believe you can still use non-upstream images as long as you use the same tag, so you could override the ImageRepository and just publish images that have the same tags as the upstream images. But if the tag differs, then the above does indeed apply.

> CoreDNS is not updated as part of kubeadm join, but rather it could be updated if you ran kubeadm init phase addon coredns (this must be run on a workload cluster node, however). If we did somehow orchestrate running this as part of the KCP upgrade process, it would use the version of CoreDNS baked into kubeadm, which has the potential to change across different kubeadm versions. We would need to ensure we run the version of kubeadm that matches the desired version specified in the KCP spec. And, if you needed to use a custom image tag for CoreDNS, the code in kubeadm that performs CoreDNS Corefile migrations assumes that your image tag matches exactly with the upstream CoreDNS versions (e.g. it needs to be 1.6.7 exactly, and not 1.6.7+some.build.metadata). We could potentially extract this logic and adjust it slightly to be more accommodating of semver build metadata, and run it in the KCP code rather than coming up with a way to run kubeadm.

It looks like there is a release binary that they generate, I'm wondering if we could convince them to also ship containers as well. It looks like each new release is additive, so we could potentially leverage a `latest` tag and a k8s Job to do the configuration mutation

**Comment by ncdc** [comment]
> How granular would we want to get with the k8s version to other component mapping?

I was thinking just minor for simplicity, but if that could pose problems, then we could require it be the patch level.

> Are we willing to tell users that they need to upgrade cluster-api to support a new version of Kubernetes on the workload clusters?

If users are maintaining the ConfigMap themselves, they wouldn't need to upgrade cluster-api (but the burden is on them to update the ConfigMap as new Kubernetes versions come out).

We could consider maintaining the contents of the ConfigMap and publishing them in our docs as new Kubernetes versions come out. This would eliminate the need to update to a newer version of cluster-api just to be able to acquire the latest ConfigMap data.

> It looks like there is a release binary that they generate, I'm wondering if we could convince them to also ship containers as well

That would be helpful!

---------------------

We don't necessarily have to make this perfect from the beginning, and we can iterate to improve. We have a few paths we can consider:

1. Document how to upgrade everything (but don't write any code)
1. Manual approach (ConfigMap managed by users) (need to figure out how we'd want to handle the CoreDNS Corefile migration)
1. Automated approach (ConfigMap managed by users, or something else we maybe haven't thought of).

**Comment by neolit123** [comment]
some Qs / comments:
- apart from the KCP controller would there be other consumers of the ConfigMap (not including users)? might have missed some context in the above discussion.
- can the version mapping be hardcoded in the controller, the same way kubeadm hardcodes it's mapping?
- what is the release cadence of the controller compared to the 3 month k8s release cycle? slower / faster?

> "1.17": "3.3.17",

- patch version bumps will not be handled by a MAJOR.MINOR key. if 1.17.1 includes a CVE fix for etcd 3.3.18, would this imply manual CM updates by users for PATCH level upgrades?
- if kubeadm cannot be queried for a version, an alternative is to use:
https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml
which @yastij contributed, but this would not work for air-gaped.

**Comment by ncdc** [comment]
> apart from the KCP controller would there be other consumers of the ConfigMap (not including users)? might have missed some context in the above discussion.

Not that I would imagine.

> can the version mapping be hardcoded in the controller, the same way kubeadm hardcodes it's mapping?

Technically, yes. That would require us to release new versions of Cluster API every time new Kubernetes versions come out (or, maybe we could do it such that we only have to do it when the etcd or CoreDNS version changes). But I'd like to find a way to avoid doing this.

> what is the release cadence of the controller compared to the 3 month k8s release cycle? slower / faster?

I wouldn't say we have a regular cadence at this time. Basically whenever we are ready with a new release.

> patch version bumps will not be handled by a MAJOR.MINOR key. if 1.17.1 includes a CVE fix for etcd 3.3.18, would this imply manual CM updates by users for PATCH level upgrades?

In this scenario, you would edit the ConfigMap and change the "1.17" value to be "3.3.18" and then trigger KCP upgrades.

> if kubeadm cannot be queried for a version, an alternative is to use:
https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml
which @yastij contributed, but this would not work for air-gapped.

Right, we have to support air-gapped. One possible option would be to build a tool that users could run that would generate the ConfigMap. The tool would need internet access, but nothing else.

**Comment by neolit123** [comment]
> Technically, yes. That would require us to release new versions of Cluster API every time new Kubernetes versions come out (or, maybe we could do it such that we only have to do it when the etcd or CoreDNS version changes). But I'd like to find a way to avoid doing this.

i see, this does not seem desired, indeed.

>> patch version bumps will not be handled by a MAJOR.MINOR key. if 1.17.1 includes a CVE fix for etcd 3.3.18, would this imply manual CM updates by users for PATCH level upgrades?

> In this scenario, you would edit the ConfigMap and change the "1.17" value to be "3.3.18" and then trigger KCP upgrades.

i'm trying to think of a way to delegate the complexity of manual edits to the air-gapped use case only for PATCH level upgrades. ultimately with an internet connection the "mapping mechanic" can fetch from the internet:
https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml

for air-gapped however there has to be exact pinning.

maybe the following can be done:
```
resolveLatest: true
etcd:
  '1.17': 3.3.17
  '1.18': 3.3.20
coredns:
  '1.17': 1.6.5
  '1.18': 1.6.7
```

in kubeadm we have the following logic:
- when the user deploys using kubeadm 1.17.0 kubeadm will deploy the latest version of k8s 1.17.x
- it's doing that by fetching a version from the internet
- if the internet version fetch fails it falls back to a pinned version in the binary

`resolveLatest` can be true by default, which means the upgrade process will try to fetch the latest coredns from `dependencies.yaml` and if false it will not do so.
if the internet fetch fails, it can fallback to the value in the map.

i must say however that the version fetch in kubeadm has caused us a number of troubles with ComponentConfig related to defaulting, unit-tests and the overall non-determinism. so enabling this by default has to be carefully considered.

another issue here is that kubeadm is moving out of k/k, so potentially k/kubeadm would need a dependencies YAML for the source of truth of what the kubeadm "distribution" uses in terms of etcd and coredns versions. k/k will remain mostly mapping for kube-up at that point.

**Comment by rudoi** [comment]
> For etcd, we know that if you leave KubeadmControlPlane.Spec.KubeadmConfigSpec.ClusterConfiguration.Etcd.Local.ImageTag blank, then kubeadm join will choose the appropriate version based on what's hard-coded into kubeadm itself.

> CoreDNS is not updated as part of kubeadm join

I think the above two pieces of information lead me to be in favor of a documentation-only approach, with maybe some code for making ClusterConfiguration pieces mutable and updating the kubeadm configmap when those pieces change(?). 

- I expect `kubeadm` to pick my `etcd` version for me.
- If I want to use a custom image for `etcd`, I expect to interact with Kubeadm's configuration.
- I expect `kubeadm` to initialize coreDNS when the cluster is created, but not manage it any further. Many folks have tooling to manage/configure coreDNS and in my experience the configuration is often customized to at least some degree. 

The lifecycles of `etcd` and `coreDNS` are different enough from each other that I don't think it would be worth trying to capture their version management in a single process.

**Comment by ncdc** [comment]
FWIW, I'd like to see kubeadm get out of the business of installing CoreDNS...

**Comment by detiber** [comment]
> FWIW, I'd like to see kubeadm get out of the business of installing CoreDNS...

That is part of the goal of the cluster-addons project: https://github.com/kubernetes-sigs/cluster-addons

**Comment by ncdc** [comment]
It sounds like we'd at least want to consider adding code to KCP to allow mutation of `KubeadmControlPlane.Spec.KubeadmConfigSpec.ClusterConfiguration.Etcd.Local` - at least the `ImageMeta` part. And then have KCP sync those values to the kubeadm ConfigMap in the workload cluster.

I do also think KCP should adjust the image tag for the container in the kube-proxy DaemonSet.

Maybe we leave CoreDNS out of scope for now?

**Comment by detiber** [comment]
> It sounds like we'd at least want to consider adding code to KCP to allow mutation of KubeadmControlPlane.Spec.KubeadmConfigSpec.ClusterConfiguration.Etcd.Local - at least the ImageMeta part. And then have KCP sync those values to the kubeadm ConfigMap in the workload cluster.

This might be a bit tricky as we've modified the types a bit and do not have the defaulting logic that exists in `kubeadm`. Additionally, we are using the `v1beta1` kubeadm types and I would expect the ConfigMap to be the latest that the version of kubeadm that created the configmap supports.

**Comment by ncdc** [comment]
> This might be a bit tricky as we've modified the types a bit and do not have the defaulting logic that exists in kubeadm

What defaulting are you referring to here?

> Additionally, we are using the v1beta1 kubeadm types and I would expect the ConfigMap to be the latest that the version of kubeadm that created the configmap supports.

Assuming the structure of the etcd image metadata is consistent, we'd just do a patch, which will work with all api versions

**Comment by detiber** [comment]
> What defaulting are you referring to here?

The API types defaulting that is applied by Kubeadm

**Comment by ncdc** [comment]
I don't think there's any defaulting (as in scheme defaulting) that's applicable here?

**Comment by ncdc** [comment]
From what I see, the only things it defaults are
- Enable local etcd if neither external nor local is specified
- Set the default data dir if it's local and the dir is empty

**Comment by ncdc** [comment]
Here's my latest proposal:

First, forget the discussion about a custom ConfigMap that maps Kubernetes versions to etcd/CoreDNS versions, at least for the time being. We can get upgrades without this.

# etcd
- relax the validating webhook to allow mutations to the etcd image details in KCP spec
- add code that syncs the etcd image details from the KCP to the kubeadm-config ConfigMap in the workload cluster

# kube-proxy
- add code to KCP controller to update the kube-proxy DaemonSet in the workload cluster to match KCP.spec.version
- images must be pullable (public or private registry), as the DaemonSet applies to all nodes in the workload cluster, and the OS images from which they booted won't have version n (current version) and n+1 (new version) both preloaded
- we may need code in KCP controller to wait to update the DaemonSet until all machines (control plane and workers) are at least the same minor version or even patch version (e.g. don't want a 1.18 control plane, 1.17 worker nodes, and bump all kube-proxy pods to 1.18)

# CoreDNS
- relax the validating webhook to allow mutations to the CoreDNS image details in KCP spec
- add code to KCP controller that syncs the CoreDNS image details from the KCP to the kubeadm-config ConfigMap in the workload cluster (this may be optional but good for consistency, so the ConfigMap isn't out of date compared to what's running)
- add code to the KCP controller that performs a Corefile migration, if necessary
- add code to the KCP controller that updates the container image in the CoreDNS Deployment
- make all of this opt in (or out), either via a feature gate (all or nothing), or per KCP (spec field)

**Comment by detiber** [comment]
I like that the etcd/kube-proxy handling avoids the need for managing k8s -> component version mappings.

It looks like we'll still need to maintain some type of mapping for the coredns upgrade handling, though.

**Comment by ncdc** [comment]
We _could_ start (emphasis on _start_) with no automated mapping, and document that users must be aware of CoreDNS changes and make them manually when upgrading control planes. And then in the future, figure out a way to automate it. I'd at least like to suggest we take this approach when coding, so we have all the CoreDNS upgrade plumbing in place and it's possible to do an upgrade as long as you know the desired new version. WDYT?

**Comment by vincepri** [comment]
Avoiding the mapping sounds good to me as well, users will need to input (in `dns.imageRepository/dns.imageTag` the newer version of CoreDNS they'd want when upgrading.

In the future, when we might introduce some generic mapping that can work across all of these components, thoughts?

**Comment by detiber** [comment]
> We could start (emphasis on start) with no automated mapping, and document that users must be aware of CoreDNS changes and make them manually when upgrading control planes. 

+1, I definitely think this is the safest and most conservative approach we can take for now.

> And then in the future, figure out a way to automate it. I'd at least like to suggest we take this approach when coding, so we have all the CoreDNS upgrade plumbing in place and it's possible to do an upgrade as long as you know the desired new version. WDYT?

I think my biggest concern here is less around the image upgrade, but rather what happens if we update the image across a boundary that requires an updated core file. Do we end up in a situation where we have taken a functional workload cluster running working applications to breaking all service resolution in the cluster due to DNS failures?

In the short term, we can likely take a dependency on the coredns migration code and do some type of semantic version comparison to make sure it's a version that is supported by the migration code we have embedded. That would require that we potentially release a new version of cluster-api for each new CoreDNS release (or maybe just anytime a version of k8s ships with a newer version of CoreDNS).

Longer term, anything we can do to make the consumption of the conversion code out of band wrt cluster-api upgrades would be beneficial, I think.

**Comment by ncdc** [comment]
Totally agree we can't break people if we change the image version and not migrate the Corefile. So we need to pull that in for now, I think.

**Comment by sethp-nr** [comment]
I think one of the wisest decisions core Kubernetes made in modeling Pods was to not consider the "version" of a container as somehow separate from and above its configuration. As a cluster operator, I tend not to think of versions of components like DNS or etcd so much as the overall configuration, of which container image tag is a part.

From my perspective, being able to identify out-of-date control plane Machines and effectively replace them (including etcd membership details, etc.) is doing something I have no replacement for in other toolsets. However, I'm not sure that cluster-api is the first tool that I would reach for when managing a Deployment or DaemonSet or associated resources – would you help me understand the urgency of pulling in management of those components as part of this release?

**Comment by sethp-nr** [comment]
Another way to put my question is that a kubernetes upgrade requires N moving parts, where N > 3. A lot of those parts have been identified in excellent detail in this thread, which is valuable in and of itself, but it's my supposition that not every part will or could be addressed by the v1alpha3 release of cluster-api. I've had success orchestrating management of both the kube-dns Deployment and the kube-proxy DaemonSet in the past with other tooling, but never had an answer for "automatically replace control plane machine M and manipulate the etcd membership, etc." 

An outcome that provides me that novel tooling but does not yet make my kube-proxy life any easier is perfectly acceptable to me! That said, I'm certainly only speaking from my experience and it's very likely I'm missing some important context on why `kubectl apply` isn't a viable strategy for CoreDNS management.

**Comment by vincepri** [comment]
Chatted with @sethp-nr over Zoom. It seems the main concern was separation of responsibilities between Cluster API and Kubeadm, and provide ways to disable behaviors (like CoreDNS upgrade) at least until we have a better solution in place.

We agreed that adding a flag to KCP so folks can opt out is a good mid-term solution, and while we learn from users over time, we'll revisit and adjust.

I'll open up 3 different issues later today with the work items that @ncdc listed above so we can start assigning folks that want to work on it and track them closely before v0.3.0 release.

If folks are 👍 with the plan, we can also probably close out this issue.

**Comment by ncdc** [comment]
Thank you @vincepri & @sethp-nr for chatting face to face. I'm glad it sounds like you were able to clear things up. The plan is 👍 for me.

**Comment by ncdc** [comment]
@sethp-nr @detiber ok to close this?

**Comment by detiber** [comment]
+1 from me for closing this in favor of the individual prs

**Comment by vincepri** [comment]
Closing this for now, tracking in the individual issues linked above, thanks all!

/close
