### ISSUE TITLE
Investigate make-verify improvements

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2227]
**What steps did you take and what happened:**
The make-verify test can take a [long time](https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-verify). Locally, it seems to be spending a while in  `conversion-gen`, but it could just be that the job is doing a lot. I wonder if we could split this into multiple jobs to take advantage of parallel execution on prow?

Steps to close this issue:

1. Identify timings of the various steps of the make-verify job.
2. Think about ways to speed this job up.
3. Open Issue(s) for improvements to be made.

This will improve the amount of time it takes for PRs to merge and for us to get signal back from CI.

/priority Backlog
/milestone Next
/help
/kind cleanup

**Comment by vincepri** [comment]
This is still valid, if it can be investigate it'd save lots of testing time locally.

/lifecycle frozen

**Comment by vincepri** [comment]
Closing given that we need something more actionable here, there is * definitely * room to improve our tooling, although it might require extensive changes in both conversion-gen and gengo.

/close
