### ISSUE TITLE
Leader election config maps are not deleted when provider is deleted

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#2230]
**What steps did you take and what happened:**
1. Followed steps to install provider components on a `kind` cluster using `clusterctl init`.
    ```
    $ ./cmd/clusterctl/hack/local-overrides.py
    $ clusterctl init --core cluster-api:v0.3.0 --bootstrap kubeadm-bootstrap:v0.3.0 --control-plane kubeadm-control-plane:v0.3.0 --infrastructure=aws:v0.4.8 --target-namespace default
    ```
1. Once the components were installed, I tried to delete them,
    `$ clusterctl delete --all`
1. `kubectl get configmaps --show-labels`

**What did you expect to happen:**
Expected to not see any config maps.

**Anything else you would like to add:**
I don't believe this is a clusterctl specific bug, but I'm tagging (/area) it because I happened to reproduce it via clusterctl. Also I don't think this is a blocker for this release (0.3).

**Environment:**
- Cluster-api version: 72e293f86fb0ba61732ba1a28ddc0fe46d43853c

/kind bug
/priority backlog
/area clusterctl

**Comment by ncdc** [comment]
The leader election configmaps are created by client-go code (our manager -> controller-runtime -> client-go). Until/unless client-go supports labeling on creation, we either:

1. recognize they'll be orphaned and ignore them
1. work to adjust the client-go and controller-runtime code so we can label them on creation
1. have our managers label them post-creation

/milestone Next

**Comment by detiber** [comment]
@ncdc I'm pretty partial to option 1

If we do want to handle additional handling, I would like to suggest that we do not pivot the configmap and let the controllers create new configmaps as they come up on the new management cluster.

**Comment by ncdc** [comment]
Yeah, same. Also, I don't think clusterctl is moving these configmaps.

**Comment by vincepri** [comment]
+1 to keep ignore the configmaps

/priority awaiting-more-evidence

**Comment by fabriziopandini** [comment]
Small not.clusterctl is not pivoting providers; they are re-installed from scratch in the target cluster before pivot
+1 to ignore

**Comment by wfernandes** [comment]
@vincepri Feel free to close.
