### ISSUE TITLE
[capd] Clean up control control plane node get

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2234]
When CAPD tries to set the provider ID on a newly joined node it looks for a control plane node to `exec` into. It finds a random one that may or may not be finished joining the control plane. We should find the initial control plane container or any control plane container that is part of the cluster.

Here is the offending code: https://github.com/kubernetes-sigs/cluster-api/blob/master/test/infrastructure/docker/docker/machine.go#L202 The problem lies in the assumption that every control plane node in this list will be available for apiserver requests.

This does not flake the capd tests but is a bad assumption to make and will clean up the logs in future.

/kind bug
/priority backlog
/milestone Next
/help

**Comment by alexbrand** [comment]
Hey @chuckha! Is this something I can pick up?

**Comment by chuckha** [comment]
@alexbrand absolutely!

**Comment by alexbrand** [comment]
Discussed with @chuckha and we decided to hold off on this until the health checking work is ready to go.

Context (#cluster-api in Kubernetes Slack): https://kubernetes.slack.com/archives/C8TSNPY4T/p1581347372052900

**Comment by vincepri** [comment]
Is this still the case now that CAPD has been updated to support v1alpha3 and KCP?

**Comment by fabriziopandini** [comment]
Now the code is slightly different; it looks for the new node (instead of one of the control plane nodes) and it runs kubectl inside the node; the code looks also re-entrant and the controller will retry this until nodeRef is set
So IMO this issue can be closed.
