### ISSUE TITLE
[vSphere] Move terraform state to machine object, instead of file system

### ISSUE THREAD

**Issue by karan** [kubernetes-sigs/cluster-api#224]
- [x] Basic support for tf-state in Machine object. Bootstrap will remain a special case.
- [x] Integrate with clusterctl after #263 merges.
- [x] Remove master VM file copies
- [x] Base64 encode tf-state before storing it in the machine.
- [x] Update controller image

/label cluster-api-vmware
/kind feature

/assign @karan

**Comment by karan** [comment]
After #264 is merged:

[ ] Integrate with clusterctl (#263)
[ ] Base64 encode tf-state before storing it in the machine

**Comment by jessicaochen** [comment]
clusterctl create logic using #264 is in! It can create a cluster and all the vms.

It does look like there are some issues with the vsphere logic that may interfere with updates. It seems like it cannot read state for existing objects:
`ERROR: logging before flag.Parse: E0601 20:51:39.442443       1 controller.go:120] Error checking existance of machine instance for machine object jesschen-tf-test-vptpd; open /tmp/cluster-api/machines/jesschen-tf-test-vptpd/terraform.tfstate: no such file or directory`

**Comment by karan** [comment]
Thanks Jess! As mentioned in #264, updates are not tested. Updates will be done after we move to clusterctl and delete vsphere-deployer.
