### ISSUE TITLE
[kubeadm control plane] health checks

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2243]
**User Story**
In order to support cluster operations (scale up, scale down, upgrade), the controller must know if the cluster is in a state to run the operations. To this end we need a health check library for those features to use.

**Detailed Description**

Please see the health checks in issue https://github.com/kubernetes-sigs/cluster-api/issues/2241.

This requires a central library that will connect to a single etcd instance 
1. A way to talk to a specific etcd client

This library can be used and a health check client can be built on top of it. This work will be coordinated with #2241 and #2242 

/kind feature
/assign
/lifecycle active
/milestone v0.3.0
/priority important-soon

**Comment by chuckha** [comment]
/assign @randomvariable 

Also assigning naadir since he did the bulk of the thinking on this one 🙏

**Comment by vincepri** [comment]
@chuckha Should this be part of the v0.3.0-rc.0 milestone or do you want to take more time to complete it?

**Comment by chuckha** [comment]
@vincepri i'll have the PR open today!
