### ISSUE TITLE
[kubeadm control plane] documentation

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2244]
**User Story**

We need to shape up our documentation story by the end of the milestone. 

**Detailed Description**

We need to have

* Quickstart 
  * An example of a KubeadmControlPlane 
* How to scale up
* How to scale down
* How to upgrade
* How to fix a damaged node by deleting it
* How to implement a control plane provider

/kind documentation
/milestone v0.3.0
/priority important-soon

**Comment by ncdc** [comment]
Didn't realize this was here when I filed #2466. Copying what I wrote over there:

Document the steps for upgrading workload cluster using KubeadmControlPlane, including:

- An overview of the process (control plane first, then workers)
- How to change the version for the control plane
- How to change the OS image (OVA, AMI, etc) for the control plane machines
- How to change the version & OS image for MachineDeployments, MachineSets
- Mention that we recommend MachineDeployments over standalone Machines or MachineSets and why
- Mention that standalone Machines will need to be deleted and recreated

**Comment by chuckha** [comment]
I'll pick this up

/assign
/lifecycle active

**Comment by chuckha** [comment]
@ncdc 

> How to change the version & OS image for MachineDeployments, MachineSets
> Mention that we recommend MachineDeployments over standalone Machines or MachineSets and why
> Mention that standalone Machines will need to be deleted and recreated

I'm a little confused as to why these are included. In my mind they don't relate to the control plane and should be covered by the machine deployment documentation, but I'm curious about your thinking. Can you expand on what you'd like to see relating to these bullet points and how they relate to the kubeadm control plane?

**Comment by ncdc** [comment]
The MD & MS bits were for general upgrades. If your goal is to upgrade a cluster, you'd want to know how to do the control plane and the workers. I think our documentation organization likely needs improvement (#2146) and if you want to focus on just the control plane aspect for now, 👍.
