### ISSUE TITLE
conversion-gen behaviour changes depending on directory checkout

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#2249]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
For cluster-api and at least cluster-api-provider-aws, `make generate` changes behaviour depending on where the repository is checked out. This can cause prow job failures if there is a mismatch.

The scenarios are:
Repository checked out to `${GOPATH}/src/sigs.k8s.io/cluster-api`:
No change in files - matches Prow.

Repository checked out to `~/go/src/sigs.k8s.io/cluster-api` with no `GOPATH` variable set:
New `sigs.k8s.io/cluster-api` directory hierarchy created with conversion files built underneath there.

Repository checked out to `${GOPATH}/src/somewhere_else:`
Comments that begin with `sigs.k8s.io` will now begin with `somewhere_else`

Repository checked outside of `~/go` with no `GOPATH` variable set:
Comments will now begin with `./api`

Repository checked outside of `~/go` with `GOPATH` set to `~/go`:
No change in files - matches Prow.

**What did you expect to happen:**
Directory checkout should not affect behaviour.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by detiber** [comment]
I'm testing against a newer version of k8s.io/code-generator, and I think that it is resolved with that update

**Comment by detiber** [comment]
This issue still seems to be happening under some situations
/remove-lifecycle stale

**Comment by CecileRobertMichon** [comment]
this is what we had in capz to solve at least the non gopath/gopath scenario: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/Makefile#L47

**Comment by vincepri** [comment]
Closing this given that it seems to be fixed, although if it happens again let's please investigate.

/close
