### ISSUE TITLE
[clusterctl] add unit tests for ensureNamespaces

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#2252]
As per https://github.com/kubernetes-sigs/cluster-api/pull/2245#issuecomment-581563431 we should add unit tests for the `ensureNamespaces` function introduced by https://github.com/kubernetes-sigs/cluster-api/pull/2245

/area clusterctl
/help
/priority backlog

**Comment by prankul88** [comment]
I can try this.
/assign

**Comment by fabriziopandini** [comment]
great!
/lifecycle active

**Comment by vincepri** [comment]
@prankul88 are you still working on this?

/milestone Next

**Comment by prankul88** [comment]
@vincepri Sorry I was occupied with something else.
Anyone else interested can take this up. I will unassign myself in the meanwhile.

/unassign

**Comment by akhil-rane** [comment]
@vincepri I am trying this
/assign

**Comment by vincepri** [comment]
@akhil-rane it seems that @hazbo already has a PR out for this issue

**Comment by akhil-rane** [comment]
@vincepri No problem, I will unassign myself
/unassign

**Comment by wfernandes** [comment]
@vincepri I believe we can close this issue since the PR above was merged in.

**Comment by vincepri** [comment]
👍
/close
