### ISSUE TITLE
Should we update Cluster.Status.FailureDomains to ListType=map

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#2256]
If we adopt CRD v1, I'm wondering if we should also update FailureDomains from a map to a ListType=map (as is supported by controller-tools [v0.2.5](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.2.5))?

This is a part of the server-side apply work that is being tracked here: https://github.com/kubernetes-sigs/structured-merge-diff/issues/115

**Comment by vincepri** [comment]
If we update, I'm all +1 for this given that I chose the map specifically because I didn't have guarantees for all the IDs in a list.

**Comment by vincepri** [comment]
Blocked on CRDv1 update

**Comment by detiber** [comment]
@vincepri is this something we should now look at for the v0.3.0-rc.0 milestone?

My main concern here is that since we are introducing the type this upcoming release, if there is a chance we are going to want to change it we should do it before the release rather than after to avoid having to deal with a conversion issue down the line.

**Comment by vincepri** [comment]
If someone can pick it up tomorrow, we can definitely add it to the RC. That said, it's fine to break things between RCs.

**Comment by detiber** [comment]
I'm not concerned as much with the RC.

/priority important-soon

**Comment by vincepri** [comment]
/milestone Next

Moving this out of the milestone due to timing and required API/code changes in CAPI and infrastructure providers

**Comment by vincepri** [comment]
Yes, we should probably investigate this once we have better support for server side apply

**Comment by vincepri** [comment]
@detiber Server side apply support from controller runtime is still lacking, pushing this back a bit.
