### ISSUE TITLE
[vSphere] Store provider config variables in secrets

### ISSUE THREAD

**Issue by karan** [kubernetes-sigs/cluster-api#226]
This is for security and safety, since the provider config blob can contain sensitive credentials.

/kind feature

/assign @karan

**Comment by karan** [comment]
After a little more thought, this might not work since the provider config will still need to exist on the objects. So we can't actually have them only in secrets.

**Comment by roberthbailey** [comment]
This issue was moved to kubernetes-sigs/cluster-api-provider-vsphere#9
