### ISSUE TITLE
[e2e framework] Add feature to allow skipping any clean up

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2268]
**User Story**
As a developer I want to have my cluster not get cleaned up. 

I specifically want to control if the framework cleans up or not. A different issue would be to not clean up on failures. However, the feature outlined here would allow me to not clean up even on success which is sometimes a desirable state.

**Detailed Description**

It's nice to run the tests and end up with the cluster in whatever state it ran in. This is extremely useful for debugging failures that are reproducing and a very common workflow I find myself using. However, I have to go in and uncomment the clean up code every time I want to do this. It would be nice if there was a way to tell the e2e framework not to clean up after itself.

The other thing this can be used for is to end up with a cluster in a known state that you can play with and examine. A quick and dirty way to get a CAPI cluster up and running locally.

**Anything else you would like to add:**

/kind feature
/help
/milestone Next
/priority important-longterm

**Comment by SataQiu** [comment]
Maybe I can have a try.

**Comment by chuckha** [comment]
@SataQiu please!
