### ISSUE TITLE
Machine phase not reconciled after move

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#2283]
**What steps did you take and what happened:**
As reported in slack https://kubernetes.slack.com/archives/C8TSNPY4T/p1580942689463400 by @Anuj2512 after completing `clusterctl move` it seems that the `Phase` field of `Machine` objects is not properly reconciled

```
NAMESPACE   NAME                                                                             PROVIDERID                                       PHASE
default     machine.cluster.x-k8s.io/cluster--vsphere-20200205114135-controlplane-0        vsphere://42214efc-5ff4-7772-428e-8b47d966f726   
default     machine.cluster.x-k8s.io/cluster--vsphere-20200205114135-md-0-d788c65c-dz5bc   vsphere://4221c39c-1545-c705-08a6-89966e854c5f   
```
^^^ Note: PHASE field is empty.

The same problem happens for CAPD, CAPA, CAPV.
Once updated the MachineDeployment to use 2 replicas instead of 1, the reconciliation process started and updated the  `Phase` from ‘empty’ to ‘running’ and successfully created 2nd worker machine.

**What did you expect to happen:**
`Phase` field properly set

**Anything else you would like to add:**
The move operations creates `Cluster` objects with `Cluster.Paused=true`, then creates all the descendant objects belonging to clusters, and finally sets `Cluster.Paused=false`.
As a consequence, the first reconciliation cycle triggered after object creation is Noop.

The next reconciliation is due in 10 min (resync period), but:
1. this is not ideal, and we should consider if/how to trigger a reconciliation after `Cluster.Paused` goes from `true` to `false`.
2. apparently there is a gap in the reconciliation logic (_"waited for more then 30 minutes for Phase to be updated but no luck"_).

I investigated 2 for CAPD, and found the gap in the reconciliation logic, fixed https://github.com/kubernetes-sigs/cluster-api/pull/2274.

However, we should define how to address 1 and audit CAPA CAPV for 2

A possible solution for 1 is to requeue with a short interval when `Cluster.Paused=true` instead of returning

**Environment:**
- Cluster-api: 5d3d0d1cb

/kind bug
/cc @detiber 
/cc @yastij

**Comment by vincepri** [comment]
The other solution we discussed was to have all the objects that want the pause functionality to watch Cluster objects and trigger a reconciliation request

**Comment by nader-ziada** [comment]
anybody working on this? or can I assign myself to it?

**Comment by detiber** [comment]
All yours @nader-ziada :)
