### ISSUE TITLE
Running lint-full twice in CI

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2286]
**What steps did you take and what happened:**
`make lint-full` needs to only be run once in CI, not twice.

[This](https://github.com/kubernetes-sigs/cluster-api/blob/master/Makefile#L473) gets called from [this](https://github.com/kubernetes-sigs/cluster-api/blob/master/scripts/ci-integration.sh#L66)

And [this](https://github.com/kubernetes-sigs/cluster-api/blob/master/scripts/ci-make.sh#L23) is a ci call to lint-full. 

Do we really need both of these to be run on both CI jobs?

/kind bug
/milestone Next
/priority backlog
/help

**Comment by ncdc** [comment]
No, `lint-full` should not be a dependency for any other make targets

**Comment by detiber** [comment]
+1 to having it be a separate test and not being a dependency for other targets.

**Comment by chuckha** [comment]
@detiber Are you suggesting a separate CI test for lint-full?

**Comment by detiber** [comment]
I'm fine with it being part of a grouped set of tests that do general "validation", I just hate seeing it cause cascading failures to other tests like the integration or unit test jobs.

**Comment by ncdc** [comment]
What Jason said 😄

**Comment by chuckha** [comment]
> I'm fine with it being part of a grouped set of tests that do general "validation", I just hate seeing it cause cascading failures to other tests like the integration or unit test jobs.

💯 

For anyone looking to tackle this: The fix is fairly low effort, remove `lint-full` a dependency everywhere it appears in the main Makefile.
