### ISSUE TITLE
v1alpha3 conversions create all new Machines for MachineDeployments

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api#2287]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

- create v1alpha2 capi/capi cluster
- scale down all controllers
- apply v1alpha3 components (which scales up capi)
- everything up-converted
- got all new Machines

**What did you expect to happen:**
Conversion should be able to retain existing Machines

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I'm fairly certain this has to do with `cluster.x-k8s.io/deployment-name: my-md-name` being added to MachineDeployments as part of conversion. This label is *not* added to Machines as part of conversion, which means existing Machines are not matching the MachineDeployment's selector. 

Personally, I do not think we should be adding this new label to MachineDeployments, but I could be convinced otherwise. The alternative, though, is to somehow retrieve MachineDeployment name as part of conversion for Machines, which could get spicy.

**Environment:**

- Cluster-api version: master
- Kubernetes version: (use `kubectl version`): 1.16.2

/kind bug

**Comment by rudoi** [comment]
/assign

I'll grab whatever solution, but would like to discuss first. 

/cc @vincepri @ncdc @detiber

**Comment by detiber** [comment]
> Personally, I do not think we should be adding this new label to MachineDeployments, but I could be convinced otherwise. The alternative, though, is to somehow retrieve MachineDeployment name as part of conversion for Machines, which could get spicy.

So, part of my rationale here, is that it is leading us towards a path where we are not requiring users to do error prone manipulation around defining unique labels for each of their MachineDeployments. 

But maybe the answer is rather than automatically appending a MachineDeployment label we could rather add it as a default if the user does not specify their own labels?

**Comment by rudoi** [comment]
I think that's a reasonable change. In general I think the rationale makes sense, but I also think it's important to not cause a full rollout of infrastructure as part of the upgrade. I'll open a PR.

/lifecycle active
