### ISSUE TITLE
Design and implement a machine lifecycle state machine

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#23]
_From @rsdcastro on January 29, 2018 22:6_

Proposal doc: https://docs.google.com/document/d/1Kz8bmAF6AZXcagjE4robuStPG93VB9YHj5xBiLI0bt0/edit

_Copied from original issue: kubernetes/kube-deploy#530_

**Comment by rsdcastro** [comment]
@roberthbailey Can you update this issue and whether we still want to block alpha on it?

**Comment by roberthbailey** [comment]
/close

The phases / states added by @hardikdr have done this.
