### ISSUE TITLE
Inconsistency in documentation: CRDs in v1alpha2 and clusters in v1alpha3.

### ISSUE THREAD

**Issue by bsctl** [kubernetes-sigs/cluster-api#2300]
**What steps did you take and what happened:**
Just following the Quick Start here https://master.cluster-api.sigs.k8s.io/user/quick-start.html, I have CRDs in v1alpha2 and clusters in v1alpha3. Clusters are not created because of missing API.

**What did you expect to happen:**
Consistency in documentation.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by jichenjc** [comment]
@bsctl maybe provide the provider name will be helpful ... aws? vsphere?others?

**Comment by jan-est** [comment]
@jichenjc @bsctl I have issues with Quick Start as well. Both kind version: 
``` kind v0.6.1 go1.13.1 linux/amd64 ``` and ``` kind v0.7.0 go1.13.6 linux/amd64 ```

I am using ```Docker``` infrastructure provider. 

While deploying cluster, getting following errors.
```
unable to recognize "cluster.yaml": no matches for kind "Cluster" in version "cluster.x-k8s.io/v1alpha3"
unable to recognize "cluster.yaml": no matches for kind "DockerCluster" in version "infrastructure.cluster.x-k8s.io/v1alpha3" ```

**Comment by bsctl** [comment]
@jichenjc doesn't matter. All example in the tutorial reports `apiVersion: cluster.x-k8s.io/v1alpha3`
Not hard to see.

**Comment by fabriziopandini** [comment]
@bsctl @jan-est 
I would say this is not an inconsistency in the doc; it simply reflects the current state of the work on v1alpha3 release on the master branch (still WIP).

As of today, the latest release currently available is v1alpha2, and the documentation is at https://cluster-api.sigs.k8s.io/ (without master at the beginning of the hostname)

Coming back to v1alpha3, the documentation on the master branch (https://master.cluster-api.sigs.k8s.io/), is getting ready for the upcoming first release of the v1alpha3 series, but currently, there is not yet a published v1alpha3 release with the v1alpha3 manifests. 

If you want to follow documentation from the master branch, as of today, you have to clone the source repositories and follow developer instructions, like e.g. https://master.cluster-api.sigs.k8s.io/clusterctl/developers.html.

/remove-kind-bug
/area documentation
/triage support

**Comment by bsctl** [comment]
@fabriziopandini thanks.

**Comment by jan-est** [comment]
@fabriziopandini thanks! This helped!

**Comment by jichenjc** [comment]
ok, this info is helpful to me @bsctl 
as I am using openstack stuffs on v1alpha3 and I didn't see the error you report 
so I thought it's provider specific... thanks
