### ISSUE TITLE
MachineDeployment Cluster name label should be set in defaulting webhook rather than in reconciliation

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api#2302]
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Early in the reconciliation loop we set a label based on the parent Cluster object's name:
https://github.com/kubernetes-sigs/cluster-api/blob/ad659a92645b4fa39fbb758aa1d523e223df6c1f/controllers/machinedeployment_controller.go#L151-L153

The defaulting webhook is better suited for this, so this logic should move into `machinedeployment_webhook.go`. 

A test for this can be added into the existing fixture here: https://github.com/kubernetes-sigs/cluster-api/blob/ad659a92645b4fa39fbb758aa1d523e223df6c1f/api/v1alpha3/machinedeployment_webhook_test.go#L27

Follow up to #2289

/kind bug
/help
/good-first-issue

**Comment by harshit98** [comment]
Hi, can I take up this issue?
