### ISSUE TITLE
Update e2e framework to use gomega.*WithOffset 

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#2305]
**User Story**

As an e2e framework consumer, I would like assertions within the e2e framework helper methods to point to where in my tests the failure occurred rather than the failure within the e2e framework.

**Detailed Description**

Anywhere we are currently using gomega assertions, we should be using the `WithOffset` equivalent. In cases where we a helper method is calling another helper method, the value passed for the offset should be appropriate for the levels of nesting within the e2e framework required as well.

https://onsi.github.io/gomega/#making-assertions-in-helper-functions

/kind feature
/priority important-longterm
/help

**Comment by chuckha** [comment]
I don't know how I feel about this. On the one hand, we do get to see which line in *our* code failed. On the other hand, It's now harder to see exactly which line in the framework failed. Looking more closely, `*WithOffset` makes sense in some places and not others. For example, a pure assertions helper function is a great place to use `*WithOffset`, but this framework is doing a lot of Create/Eventually/Wait and has no pure assertion helpers.

However, I think this brings up an interesting discussion point, but first, an example of why I find using `*WithOffset` a little bit confusing in this framework:

```
      should create a multi-node controlplane cluster [It]
      /Users/cha/dev/capi-dev/cluster-api/test/infrastructure/docker/e2e/docker_test.go:82

      Expected
          <int>: 3
      to equal
          <int>: 2

      /Users/cha/dev/capi-dev/cluster-api/test/infrastructure/docker/e2e/docker_test.go:119
```

And if we look at that code...

```
113: // Set up the KubeadmControlPlane
114: createKubeadmControlPlaneInput := framework.CreateKubeadmControlPlaneInput{
115: 	Creator:         client,
116:  	ControlPlane:    controlPlane,
117: 	MachineTemplate: template,
118: }
119: framework.CreateKubeadmControlPlane(ctx, createKubeadmControlPlaneInput)
```

Now we have to do some manual guessing as to which expectation failed. 

So, it looks like this framework, as it's not doing any pure assertion functions that we want to hide, doesn't benefit from using `*WithOffset`. 

The interesting discussion that we can have on this front though is to make the framework more go-like and remove the Ginkgo dependency entirely! It might look something like this:

```go
// Framework
// If there is a race condition between the pod reporting Ready and the web server actually being ready you should wrap this in an Eventually.
func CreateKubeadmControlPlane(input InputType) error {
    if err := input.Creator.Create(ctx, input.MachineTemplate); err != nil {
        return err
    }
    return input.Creator.Create(ctx, input.ControlPlane)
}

// My tests
Describe('...', func() {
    It('should create a control plane', func() {
        Eventually(framework.CreateKubeadmComntrolPlane(input)).Should(Succeed())
    })
})
```

The benefits here are that the framework becomes just a go library that allows users to use their own preferred testing library. The framework becomes reusable for other tools that might be trying to automate cluster actions (but that's not a main design point). And in the case where we DO want to provide assertions, we could, at that point, use `*WithOffset`.

**Comment by chuckha** [comment]
@fabriziopandini @akutz @yastij @CecileRobertMichon 

Folks using the e2e testing framework, I'm curious if you have thoughts on this issue.

**Comment by detiber** [comment]
> Now we have to do some manual guessing as to which expectation failed.

We could help that out by annotating our assertions: https://onsi.github.io/gomega/#annotating-assertions

**Comment by akutz** [comment]
FWIW, I've used both models heavily. I agree it's nice to see the line that failed, but you don't see *what* failed. As @detiber said, that's easier to do if you annotate assertions and/or return wrapped errors out of an `Eventually` or `Consistently`. Funnily enough, I raised this in December with the same exact caveats:

![image](https://user-images.githubusercontent.com/101085/74356329-caff3980-4d83-11ea-8491-d8f1145a4b5c.png)

I ultimately think it depends. The offset logic is helpful when it's closer to the test cases. In a framework I find it loses some of its utility due to the disconnect between the framework and the test cases using the framework.

It would also be entirely easy to make this optional by:

* Always using the offset variants
* Having a default offset value of `0` and allowing someone to override that either globally (if the offsets are always one stack frame from the top) or per helper function.

**Comment by detiber** [comment]
I kind of like the idea of having the option of using offsets or not, but if we do that, then we probably need to take into account that chained helpers would need to adjust the offset appropriately. https://github.com/kubernetes-sigs/cluster-api/pull/2311#discussion_r378352429 points out an example.

**Comment by akutz** [comment]
Hi @detiber,

Exactly. And it's more than that as well. You could have:

```go
func HelpMe1() string
func HelpMe2() string
func HelpMe3() string
```

Let's say `HelpMe1()` uses an offset of `1`. But what if you have this call stack?

```
nonFrameworkCaller -> HelpMe3() -> HelpMe2() -> HelpMe1()
```

Should `HelpMe1()`'s offset be `1` or `3`?

**Comment by chuckha** [comment]
I'm not dissatisfied with the current stack traces, especially as they help me debug in Prow without needing to do any manual string matching.

This problem gets thornier by the minute and I don't see a very high value proposition. I'd definitely be more interested if this, for example, was blocking someone from implementing for some reason or really stymieing some users, but I haven't had that feedback yet, has anyone else?

**Comment by akutz** [comment]
The fact is that when an eventually or consistently fails, offset or no, you still see the stack trace printed (or you should). You *can* find your way, pretty easily, back to the non-framework caller. I think the idea of an offset works well in a contained test file, but perhaps less so in a framework with uncertain call stacks to the places an offset might be used.

**Comment by detiber** [comment]
I'm trying to think about the user experience of someone adopting the test framework for their provider. Assuming that they are importing a "known good" version of the framework, I would expect that the majority of use cases they'd want to know where things failed in their tests.

I'd expect the framework to mostly be an implementation detail for them, rather than a key part of their debugging process.

**Comment by chuckha** [comment]
> I'm trying to think about the user experience of someone adopting the test framework for their provider. Assuming that they are importing a "known good" version of the framework, I would expect that the majority of use cases they'd want to know where things failed in their tests.
> 
> I'd expect the framework to mostly be an implementation detail for them, rather than a key part of their debugging process.

Totally agree about the framework being an implementation detail, but it still feels fairly immature, especially given the overhaul it recently got and the lack of go module tags.

Maybe we can keep this in the backlog until we gather some more feedback from the field? If folks find the stack traces confusing/hard to understand then we can bump the priority here. But if they don't find the stack traces difficult to read/use, then it might not be a problem at all. 

For example, if we start using this in the CAPA e2e tests and the stack traces are a pain in the butt we can figure out why and solve that problem that may or may not align with this particular issue.

**Comment by fabriziopandini** [comment]
@vincepri, considering this getting stale and the discussions in https://github.com/kubernetes-sigs/cluster-api/issues/2955, I'm +1 for closing this issue...
