### ISSUE TITLE
e2e framework should allow for use outside of ginkgo

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#2306]
**User Story**

As an e2e framework user, I would like to be able to call e2e helpers from tests that are not managed by ginkgo

**Detailed Description**

Currently we only expose helper methods that call the global assertions provided by gomega. If we want to allow for use outside of ginkgo, we can likely provide a wrapper similar to Gomega's `WithT`: https://github.com/onsi/gomega/blob/6be6c439588487cd908a3a700795660c2a16dfec/gomega_dsl.go#L348

/kind feature
/priority important-longterm
/help

**Comment by chuckha** [comment]
cc

**Comment by vincepri** [comment]
I'd almost consider this as a non-goal for the foreseeable future. Thoughts on closing this out? 

/cc @fabriziopandini

**Comment by fabriziopandini** [comment]
Being a library, this is still something interesting to explore in the long term
However AFAIK there is no concrete need for this now, and considering that it requires changing methods signatures, I'm ok in closing this issue and move this in the roadmap as an item to be planned for some future relase

**Comment by vincepri** [comment]
/close

We're going to keep using ginkgo for e2e tests, while integration and units are moving to go-test
