### ISSUE TITLE
[e2e framework] MachineDeployment Cleanup

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2309]
The e2e framework can help in creating a machine deployment. However, the assertions around it are waiting for the nodes to exist on the cluster. This test can be improved (and exercise more of cluster api) by waiting for the machines to have node refs instead of listing nodes directly

/kind cleanup
/milestone Next
/priority backlog
/help

**Comment by vincepri** [comment]
cc @fabriziopandini

**Comment by fabriziopandini** [comment]
/close
We are already waiting for all the nodes having noderef
see https://github.com/kubernetes-sigs/cluster-api/blob/5596ab2a8d3f7dc14ca63e7f425df7c8f76fab3d/test/framework/machinedeployment_helpers.go#L81-L112
