### ISSUE TITLE
Document that providers MUST validate references are in the same namespace

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#2318]
***Goals***
1. Replace current uses of `corev1.ObjectReference` with more appropriate types

***Non-Goals/Future Work***
1. Modify other types used

**User Story**

As a consumer of Cluster API I would like to have fields that are currently using `corev1.ObjectReference` to use more appropriate data types so that it is clear which fields are used (all of them) vs having to guess which fields are in use.

**Detailed Description**

Upstream documentation discourages the use of `corev1.ObjectReference`: https://godoc.org/k8s.io/api/core/v1#ObjectReference. In order to align better with upstream convention we should adopt types that are more fitting for their purpose.

When the referenced type is constant and in the same namespace, we should likely use `corev1.LocalObjectReference` instead.

When we also need type information for the referenced resource and that resource is in the same namespace, we should likely use `corev1.TypedLocalReference`

If for some reason we need to cross namespaces with a reference, we should likely create our own type that is a subset of `corev1.ObjectReference`

To ease this transition, we should gracefully handle the conversions within the conversion webhooks.

**Contract changes [optional]**

Any type that is currently using `corev1.ObjectReference` would be updated to a more appropriate type.

**Data model changes [optional]**

Any type that is currently using `corev1.ObjectReference` would be updated to a more appropriate type.

/kind proposal

**Comment by vincepri** [comment]
We really should just have one type with

```
    // Kind of the referent.
    // More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    // +optional
    Kind string `json:"kind,omitempty" protobuf:"bytes,1,opt,name=kind"`
    // Namespace of the referent.
    // More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
    // +optional
    Namespace string `json:"namespace,omitempty" protobuf:"bytes,2,opt,name=namespace"`
    // Name of the referent.
    // More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    // +optional
    Name string `json:"name,omitempty" protobuf:"bytes,3,opt,name=name"`
```

We can have it in our own types?

**Comment by detiber** [comment]
I'd rather avoid having a `Namespace` field where we do not allow cross-namespace references, otherwise it's just an extra thing we need to validate and adds potential for a poor user experience.

I would say the same thing for references that are known types (Secret, ConfigMap, etc), for similar reasons.

**Comment by enxebre** [comment]
cross referencing PR https://github.com/kubernetes/kubernetes/pull/87459 to add more context.

**Comment by detiber** [comment]
Also relevant PR to update the api conventions doc: https://github.com/kubernetes/community/pull/4705

**Comment by detiber** [comment]
I'm happy to work on this for https://github.com/kubernetes-sigs/cluster-api/milestone/16, also happy to help work with this on other folks if anyone else is interested in contributing to this.

**Comment by vincepri** [comment]
@detiber If you have time or would like to, @srm09 was interested in getting up to speed on this issue and the problems it solves

**Comment by srm09** [comment]
@detiber What would be a potential usecase of using `LocalObjectReference` over `TypedLocalObjectReference`. AFAIU, the latter type is a more stringent case of the former.
IMHO, we should always use the latter to guarantee the object being referred to.

**Comment by detiber** [comment]
In case anyone else is interested, @srm09 is leading discussion of this issue in the following doc: https://docs.google.com/document/d/1S4zP7k39R0FcKg_MGk4jNHsFwIre06iL2ySYlTSpOGk/edit?ts=5f8f2fe3

**Comment by vincepri** [comment]
/milestone Next

Moving the milestone for now, not sure if we'll have someone that can push this forward across CAPI + providers.

**Comment by enxebre** [comment]
@vincepri is this intended for v1beta1?

**Comment by vincepri** [comment]
Probably too late right now?

**Comment by vincepri** [comment]
Next seems good for now, once we want to prioritize for the next API release we can reprioritze this issue

**Comment by fabriziopandini** [comment]
/triage accepted

the original ask to improve documentation is still valid; the discussion about how to model reference is tracked in https://github.com/kubernetes-sigs/cluster-api/issues/6539 so I suggest to drop it from this thread

/help

**Comment by sbueringer** [comment]
@fabriziopandini I think I would close this issue:
1. It has been open forever and nobody is volunteering
2. Does it really make sense to document: "If you have a ref in your API object that has to reference an object in the same namespace please add validation for it"?
  * I assume that it could be totally valid for provider CRs to reference objects in different namespaces. 
  * Something generic like this applies basically to API fields. "Please add validation if not all possible values are valid".
4. Are provider authors actually finding that hint in our documentation?

**Comment by fabriziopandini** [comment]
/close
as per the comment above. 
also, this is probably that will probably be part of the bigger discussion on reviewing how we model references
