### ISSUE TITLE
Support feature gates for experiments

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2328]
**User Story**

As a [developer/user/operator] I would like to [high level description] for [reasons]

As a developer I would like to work on experimental features behind a flag, folks are expected to opt-in.

As a operator I would like to have the ability to enable/disable certain experimental features.

**Detailed Description**

- Modify `main.go` to accept a new flag called `feature-gates`, following upstream k/k convention using a `map[string]bool` (look at https://github.com/kubernetes/component-base/blob/v0.17.2/featuregate/feature_gate.go)

- Add `exp` folder under root.
    - `exp/api` containing types
    - `exp/config` containing kustomize limited to CRD
    - `exp/controllers` containing controller logic
       - new controllers will be added in cluster-api manager `main.go` when feature gate is enabled

/kind feature

**Comment by vincepri** [comment]
This is a follow-up issue to #1910

**Comment by sedefsavas** [comment]
I'd like to work on this issue. I am also working on #1910, so this will be needed for that issue.

**Comment by sedefsavas** [comment]
Currently, CAPI uses Go flags and feature-gate is implemented using pflags in k/k.
For the sake of consistency, I am thinking to using pflags for adding feature gate and then in a separate issue, porting other flags to pflags slowly.
How does this sound?

**Comment by vincepri** [comment]
Are they compatible with each other? I think we can easily switch to `pflags` as part of this effort, wdyt?

**Comment by sedefsavas** [comment]
Yes I agree. I think porting will be easy. I will put out a PR first to move existing flags to pflags.

**Comment by vincepri** [comment]
Sounds good! We should also open an issue to do the same for infrastructure providers and add a note to this document https://master.cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html stating that this is an optional change.

**Comment by sedefsavas** [comment]
I have used "cmd/kubeadm/app/features/features.go" wrapper library of "k8s.io/component-base/featuregate" for this feature.

For the exp directory, keeping features in their own directory may help features to be more isolated from each other:
exp
 |____ feature
                |_____api
                |_____config
                |_____controllers
So, I didn't add /exp directory to this PR for now.

**Comment by vincepri** [comment]
@sedefsavas I'm not sure if we should split the features into folders, I'd rather have them under one folder and enable/disable the controllers with the feature flags. 

We also might want to consider adding the experimental APIs to CAPI's config/ folder, this will reduce the need of another component manifest to be published.

**Comment by detiber** [comment]
@vincepri I would not expect experimental APIs to be available or enabled by default.

**Comment by vincepri** [comment]
I'm not suggesting the features to be enabled by default, rather just the CRDs included in the cluster-api-components.yaml file. In alternative, we can ship the experimental features separately, but that complicates releases, deployments, and maintenance.
