### ISSUE TITLE
[vSphere] rename terraform provider to vSphere provider

### ISSUE THREAD

**Issue by karan** [kubernetes-sigs/cluster-api#233]
It seems like optimizing for a generic terraform controller is more overhead than we need right now. So we will scope the terraform work to just vsphere. This will improve refactoring all cloud/terraform to cloud/vsphere and tf-deployer to vsphere-deployer.

**Comment by roberthbailey** [comment]
How tied to vSphere is the current code? I think having a generic terraform provider has a lot of value as it makes it easy to add support for new environments. 

/cc @kris-nova

**Comment by karan** [comment]
@krousey and I talked about it a little, and decided that trying to generalize the provider might be over optimization for now. For example, I want to pull user/password/server address in the cluster spec but those fields don't map 1:1 to all terraform supported environments.

I am happy to fork the tf code into a vsphere exclusive one and keep the tf code around as well.

**Comment by karan** [comment]
The decision from the meeting today was that we will create a copy of the existing tf code, and rename the copy to vsphere. Terraform provider will stay as a playground for others to prototype in.
