### ISSUE TITLE
Tilt workflow broken

### ISSUE THREAD

**Issue by johnharris85** [kubernetes-sigs/cluster-api#2350]
**What steps did you take and what happened:**
When running `tilt up` against the master branches for CAPI (7eead355bcbc36aa1625ecfde617dfc1f8133c31) & CAPA (19dd80de9d26b40b50a42c02d96c16cc4016e2c4) I get the following error:

```
Error: command ["kustomize" "build" "/home/john/go/src/sigs.k8s.io/cluster-api-provider-aws/config"] failed.                                                                       
error: exit status 1                                                                                                                                                               
stdout: ""                                                                                                                                                                         
stderr: "Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/home/john/go/src/sigs.k8s.io/cluster-api-provider-aws/config'\n"
```

**What did you expect to happen:**
Working Tilt workflow

**Anything else you would like to add:**
Looks like it was caused with https://github.com/kubernetes-sigs/cluster-api/commit/ad28a70ab0c3ee804cebc8084fdbb92e10cc24b6#diff-1a474bf970407efc3332970120c1a429L176 as reverting that line gets a little further / resolves this specific issue.

**Environment:**

- Cluster-api version: master
- Tilt version: v0.12.1
- Minikube/KIND version: 
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by vincepri** [comment]
This is a known issue, unfortunately we need the kustomize webhook changes to the providers https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1572

**Comment by vincepri** [comment]
This is a known issue, unfortunately we need the kustomize webhook changes to the providers https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1572

**Comment by vincepri** [comment]
The linked PR has been merged
