### ISSUE TITLE
bootstrap.DataSecretName isn't reconciled if bootstrap.Data is set

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api#2363]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
- apply v1alpha3 yaml to v1alpha2 cluster
- machines generally look okay
- CAPA controller upset because `dataSecretName` is not being set, so it's continuously reconciling AWSMachines, etc

**What did you expect to happen:**
1. CABPK controller converts all bootstrapDatas to secrets (this does happen)
2. CAPI controller keeps (or removes?) bootstrap.Data in Machine objects and sets the bootstrap.DataSecretName appropriately (this does not happen)
3. CAPA controller sees the new DataSecretName and happily reconciles

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Conversely, we could tell CAPA controller to continue to respect bootstrap.Data, but that seems backwards as we're trying to deprecate that field. 

I think we may want to do something with the early return here:
https://github.com/kubernetes-sigs/cluster-api/blob/27a6031a1d6aa1a310c905b7d1afa331ab1cfd2d/controllers/machine_controller_phases.go#L165-L169

**Environment:**

- Cluster-api version: master
- Minikube/KIND version: 0.7.0
- Kubernetes version: (use `kubectl version`): 1.16.2
- OS (e.g. from `/etc/os-release`): ubuntu 18.04

/kind bug

**Comment by vincepri** [comment]
looking into this
>CAPI controller keeps (or removes?) bootstrap.Data in Machine objects and sets the bootstrap.DataSecretName appropriately (this does not happen)
