### ISSUE TITLE
Clusterctl: Object status lost during move

### ISSUE THREAD

**Issue by maelk** [kubernetes-sigs/cluster-api#2370]
In the move command, clusterctl only uses the "create" operation, hence the current status of the object moved is lost. I guess this is by design because a new reconciliation will recreate those statuses. However, in CAPBM, we have some objects where we cannot loose the status. 

Our BareMetalHost holds some information in the status fields that reflect the content of the Ironic database (baremetal provisioner). When pivoting, the target cluster ironic database is empty, and repopulated based on the content of the status fields with the current state of the node. If the status is present, the node is seen as already provisioned. But If those are empty, then the node will go through the full cycle and be re-provisioned, hence the whole cluster will disappear. 

We were also discussing moving those fields to the spec, but they are not user input, they are set by the controller only and should not be touched by the user, so we would prefer to have a way to move the status. Do you think it would be ok to add something in the move implementation to move the statuses too, or should we move those objects with another executables than clusterctl ?

**Comment by detiber** [comment]
It's not just the create operation. It's a side effect of defining the status subresource for a CRD, any create or update does not effect Status, Status required a separate update.

The upstream API guidelines also state that Status should be recreatable.

Anything that needs to persist for any type of move or backup/restore operation really should not be in Status.

**Comment by maelk** [comment]
ok, thank you for the clarification, we should then modify our objects.

**Comment by guettli** [comment]
This PR adds a warning to the docs: https://github.com/kubernetes-sigs/cluster-api/pull/8145
