### ISSUE TITLE
Code freeze policies w/ releases

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2372]
We should document a timing policy for code freeze. Often times during a cycle we find ourself adding more changes than previously discussed. Let's try and find guidelines that makes sense with our development processes.

/kind documentation

**Comment by chuckha** [comment]
If we take cues from the latest [Kubernetes release](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.18), enhancements freeze (must have a proposal in implementable state, must have an open issue in the milestone) is 7 weeks before release followed by code freeze (no more additions to code; only release blocking issues get merged) 3 weeks before release.

We could probably twiddle the timing a bit (5 weeks and 2 weeks perhaps) and relax the enhancements requirements to either CAEP + issue or just issue with 3 +1s from approvers (this is for our light-weight proposal process that is an issue only)

**Comment by detiber** [comment]
My take is:
- move away from date based releases
- set a date for feature freeze
- based on features desired for next release by feature freeze, set a tentative code complete date.
- once all features are in (or bumped) cut an rc release, keep churning on rc release until blocking bugs are 0
- only accept bugfixes until release is cut

Work to set next feature freeze and future proposals can go on in parallel to the above process.

Additionally, anything behind an experimental feature gate can likely be allowed to happen independent of the current release cycle, but that is likely a separate discussion.

**Comment by vincepri** [comment]
From @ncdc in #1949:

```
We should formally define & document & adhere to a proper release cycle for this project. It doesn't have to be too heavyweight, and could look something like this:

Start of cycle: review all open issues (backlog grooming)
Feature freeze: cutoff date for deciding which features are in/out for the release
Code freeze: cutoff date when all new features should be ready & merged
Something about alpha/beta/RC releases & bug fixes
Release day
I'd love to have advice and guidance from people who have worked on Kubernetes releases to know what we should consider doing (e.g. @justaugustus)

This came out of the v1alpha2 retrospective (#1438)
```

**Comment by fabriziopandini** [comment]
+100

**Comment by vincepri** [comment]
/close

This has been done
