### ISSUE TITLE
[Doc] The deprecation notice of clusterctl in v1alhpa2 doc is out of date 

### ISSUE THREAD

**Issue by jessehu** [kubernetes-sigs/cluster-api#2387]
**What steps did you take and what happened:**
CAPI v1alpha2 doc https://cluster-api.sigs.k8s.io/tooling/clusterctl.html says
`This utility has been deprecated in v1alpha2 and will be removed in a future version. `
and https://master.cluster-api.sigs.k8s.io/clusterctl/overview.html (should be the v1alpha3 doc) still provides an updated clusterctl.

Per @detiber's feedback on https://kubernetes.slack.com/archives/C8TSNPY4T/p1582205493288400?thread_ts=1582204591.288200&cid=C8TSNPY4T:

`clusteradm has morphed into clusterctl v2: https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20191016-clusterctl-redesign.md and I believe most (if not all) of the functionality outlined in the proposal should already be merged into the master branch at this point`

**What did you expect to happen:**
Update or Remove the deprecation notice of clusterctl in v1alhpa2 doc https://cluster-api.sigs.k8s.io/tooling/clusterctl.html to comply with the latest clusterctl status.

**Anything else you would like to add:**

**Environment:**
- Cluster-api version: v1alpha2

/kind bug

**Comment by jessehu** [comment]
@vincepri Shall we remove the deprecation notice?

**Comment by vincepri** [comment]
We should either remove it, or replace it with a link to the upcoming changes, if the docs are ready, or the proposal.

**Comment by jessehu** [comment]
Maybe we can remove the notice and add a section in the v1alpha3 doc (https://master.cluster-api.sigs.k8s.io/clusterctl/overview.html) to highlight the clusterctl command line change from v1alpha2.

**Comment by vincepri** [comment]
I'd rather not link to the master branch, because that might change at any given point. Although there is no release branch today that we can link to 🤔

**Comment by detiber** [comment]
It might be better to link to the proposal for now, and then possibly publish a new version with an updated link once we have a release

**Comment by vincepri** [comment]
Closing, fixed in #2445 

/close
