### ISSUE TITLE
Ensure we have a cohesive and well documented contact page for the project

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#2391]
This issue is mostly a tracking issue to remind myself to go back and ensure that we have an easy to point to page in the docs that is an up to date canonical resource for how users and contributors can contact the project through various channels

/assign
/priority important-soon
/milestone v0.3.0
/kind documentation

**Comment by vincepri** [comment]
I've pointing to https://master.cluster-api.sigs.k8s.io/#community-discussion-contribution-and-support

**Comment by detiber** [comment]
Thanks, at a quick glance it looks like it's missing a few things:
- mailing list (other than mentioned for group membership for docs)
- discuss

and we should probably have more expedient access to pointers towards contact info for the sig-sponsored providers.

**Comment by vincepri** [comment]
I'm not sure about others but it seems to me that discuss isn't really used for Cluster API, other than that, +1 making it easier to get in touch

**Comment by detiber** [comment]
If it wasn't for google groups not being available in China, and needing an alternative for asynchronous communication I would agree with you.

**Comment by randomvariable** [comment]
Review SECURITY_CONTACTS as well

**Comment by vincepri** [comment]
@detiber do you think we can get this done this cycle?

**Comment by detiber** [comment]
I'll see what I can do.
