### ISSUE TITLE
KubeadmControlPlane - When removing an etcd member, proxy through a node other than the one being modified

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#2393]
**Detailed Description**

After #2382 is merged, we need to improve the handling of etcd membership removal to be more robust by proxying through a Machine/Node other than the one that is having it's membership removed. This will prevent potential issues with loss of connection during the process.

/kind feature
/milestone v0.3.0
/priority important-soon

**Comment by prksu** [comment]
@vincepri interested work on this

**Comment by randomvariable** [comment]
@prksu sounds good. just ping a `/lifecycle active` message on this issue if you start.

**Comment by ncdc** [comment]
Something to consider, that we did in the upgrade tool: we initially tried to pick a pod other than the one from the node being removed, but switched to trying all etcd pods, returning with the first successful response. Maybe we'd want to do both - try all pods except the one being removed? (https://github.com/vmware/cluster-api-upgrade-tool/blob/b5279e9c63b537a9559165881883b7ddb1c3aceb/pkg/upgrade/control_plane.go#L1060-L1066 for what we do in the upgrade tool)

**Comment by prksu** [comment]
trying all nodes except the one being removed sounds a good idea.
i'll try this

/assign
/lifecycle active
