### ISSUE TITLE
KCP: ensure machine that is being deleted during upgrades or scale down isn't the etcd leader

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#2398]
**Detailed Description**

For correctness, the control plane controller should ensure etcd leadership is on a machine that isn't about to be deleted. Two optimisations are possible:

* Where there are at least two candidates for deletion, pick the machine which is not etcd leader
* Where there is only one candidate, move the etcd leadership to a different machine.

/kind feature
/help

**Comment by detiber** [comment]
I would argue that we should probably always handle this by moving the leadership, otherwise we risk causing conflicts with the failure domain handling.

**Comment by vincepri** [comment]
In terms of milestone, when do we want to tackle this?

**Comment by detiber** [comment]
I think we still want to attempt to get this in prior to v0.3.0.
/milestone v0.3.0

**Comment by vincepri** [comment]
Are we planning to do this for `v0.3.0` or should we punt this to v0.3.x?

**Comment by chuckha** [comment]
let's leave it in v0.3.0 and if it looks like it will merge today i'll put it in the RC milestone

**Comment by michaelgugino** [comment]
We need to update the first comment or title to reflect that this is specifically about upgrades.

**Comment by vincepri** [comment]
/retitle KCP: ensure machine that is being deleted during upgrades isn't the etcd leader
