### ISSUE TITLE
Support for hooks for resource cleanup during machine deletion

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#24]
_From @rsdcastro on January 29, 2018 22:9_

_Copied from original issue: kubernetes/kube-deploy#531_

**Comment by rsdcastro** [comment]
_From @roberthbailey on February 7, 2018 6:37_

What types of resources are you thinking about? Would this be handled by finalizers for the machine objects (e.g. if on GCP we created an advanced route per machine then the finalizer for the machine would be responsible for deleting the route)?

**Comment by rsdcastro** [comment]
cc @k4leung4

**Comment by roberthbailey** [comment]
I think that the finalizer approach we are taking satisfies this feature request, so I'm going to close this issue.

/close
