### ISSUE TITLE
Installing infrastructure provider errors out with namespaces "capv-system" already exists

### ISSUE THREAD

**Issue by outofmem0ry** [kubernetes-sigs/cluster-api#2402]
**What steps did you take and what happened:**
In the quick start guide, while [installing infrastructure provider](https://cluster-api.sigs.k8s.io/user/quick-start.html#install-infrastructure-provider) for vSphere, the YAML snippet, in the guide creates `capv-system` namespace. In the next step, `kubectl create -f https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/download/v0.5.4/infrastructure-components.yaml` the `infrastructure-components.yaml` file also defines the `capv-system` namespace object. Because of this running `kubectl create` throws the following error

```shell
[root@centos ~]# kubectl create -f https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/download/v0.5.4/infrastructure-components.yaml
customresourcedefinition.apiextensions.k8s.io/vsphereclusters.infrastructure.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/vspheremachines.infrastructure.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/vspheremachinetemplates.infrastructure.cluster.x-k8s.io created
role.rbac.authorization.k8s.io/capv-leader-election-role created
clusterrole.rbac.authorization.k8s.io/capv-manager-role created
clusterrole.rbac.authorization.k8s.io/capv-proxy-role created
rolebinding.rbac.authorization.k8s.io/capv-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/capv-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/capv-proxy-rolebinding created
service/capv-controller-manager-metrics-service created
deployment.apps/capv-controller-manager created
Error from server (AlreadyExists): error when creating "https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/download/v0.5.4/infrastructure-components.yaml": namespaces "capv-system" already exists
```
**What did you expect to happen:**
This does not impact any functionality but for someone following the docs for the first time, this message can be misleading. 

**Anything else you would like to add:**
Removing the namespace object from `infrastructure-components.yaml` will solve it but does not appear to be a good idea and I'm not sure if there are other dependencies. One approach could be replacing `kubectl create -f` with `kubectl apply -f`. This way it won't error out and users will get the message that the namespace object is unchanged.

Happy to submit a PR for either approach or if there is a better alternate.

**Environment:**

- Cluster-api version: v1alpha2
- KIND version: 0.7.0
- Kubernetes version: (use `kubectl version`): 1.16.3
- OS (e.g. from `/etc/os-release`): Ubuntu

/kind bug
/kind documentation

**Comment by vincepri** [comment]
This is something that might be resolved by clusterctl v1alpha3. The quickstart is intended to be operating on an empty cluster. I'm not sure if I'd fix the documentation, I'd rather wait for the next version of clusterctl and v1alpha3.

/priority awaiting-more-evidence
/milestone Next
