### ISSUE TITLE
Provide a yaml output format for clusterctl config repositories

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#2410]
**User Story**

As a operator I want to quickly see what `$HOME/.cluster-api/clusterctl.yaml` looks like after running
`clusterctl config cluster --help`

**Detailed Description**

Add a way, and surface via the help information the way to see the embedded clusterctl.yaml so an operator can see the format and override it if they want.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by randomvariable** [comment]
Via Slack https://kubernetes.slack.com/archives/C8TSNPY4T/p1582554891002400, the functionality is there in `clusterctl config repositories`, need to cross-reference in the help and also provide an `-o yaml` type command

**Comment by jayunit100** [comment]
+100

**Comment by jayunit100** [comment]
This should probably print a warning or fail ?  bc i dont have that YAML.
```
-  cluster-api git:(master) ✗ bin/clusterctl  config provider --infrastructure=docker
Error: failed to get configuration for the InfrastructureProvider with name docker. Please check the provider name and/or add configuration for new providers using the .clusterctl config file
```
Provide configuration values to be used for variable substitution when installing providers or creating clusters.

**Comment by wfernandes** [comment]
@prankul88 Thanks for reaching out regarding this issue. 

>  https://kubernetes.slack.com/archives/C8TSNPY4T/p1582554891002400

So I think the idea here is not necessarily the contents of the `$HOME/.cluster-api/clusterctl.yaml` but rather from the slack conversation what is being asked for is a YAML formatted output of `clusterctl config repositories`.

So in this case we don't necessarily need the path of the config file. In my understanding, we need to add a `-o yaml` flag for `clusterctl config repositories` and that should print out the repository list which is a `[]Provider` but in yaml format.

https://github.com/kubernetes-sigs/cluster-api/blob/23a9ec341de33c399c542558c22046cb413082d5/cmd/clusterctl/cmd/config_repositories.go#L63 

Let me know if this makes sense. Happy to help 🙂

**Comment by wfernandes** [comment]
@randomvariable Maybe we should retitle this issue to specify the ask from the slack convo. WDYT?

**Comment by randomvariable** [comment]
Yup sure, retitle how you think best.

**Comment by wfernandes** [comment]
/retitle Provide a yaml output format for clusterctl config repositories

**Comment by prankul88** [comment]
@wfernandes Thanks for taking a look :)
