### ISSUE TITLE
Convert all unit tests to use gomega

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2423]
Longer term, we should try to switch all our tests to use gomega and follow the same pattern in every place.

The goal is to help be more consistent in how we write test and set a standard. When using `gomega` outside of `ginkgo`, it's pretty easy to find a good balance between standard go tests and gomega interfaces.

As an example:
```go 

import . "github.com/onsi/gomega"

func TestFunction(t *testing.T) { // <-- Declares what I'm about to test.
	g := NewGomegaWithT(t)
        t.Run("function should do X", func(_ *testing.T) { // <-- Set a short expectations on what it's being tested.
		[...]
		g.Expect(err).ToNot(HaveOccurred())
	}
}
```

/kind cleanup
/milestone Next

**Comment by vincepri** [comment]
/retitle Convert all unit tests to use gomega

**Comment by fabriziopandini** [comment]
/close
from a quick check this work is complete
