### ISSUE TITLE
[clusterctl] Missing clusterctl-settings.json in docker provider for clusterctl developer setup workflow

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#2424]
**What steps did you take and what happened:**
Following steps here: https://master.cluster-api.sigs.k8s.io/clusterctl/developers.html#clusterctl-for-developers

0- Create a kind cluster
1- Build clusterctl running:` make clusterctl` in CAPI directory
2- Create clusterctl-settings.json file for infrastructure-docker
3- cmd/clusterctl/hack/local-overrides.py

Get this error:
Traceback (most recent call last):
  File "cmd/clusterctl/hack/local-overrides.py", line 202, in <module>
    load_providers()
  File "cmd/clusterctl/hack/local-overrides.py", line 95, in load_providers
    raise Exception('failed to load clusterctl-settings.json from repo {}: {}'.format(repo, e))
Exception: failed to load clusterctl-settings.json from repo ./test/infrastructure/docker: [Errno 2] No such file or directory: u'./test/infrastructure/docker/clusterctl-settings.json'

**What did you expect to happen:**
I expected it to create and install the providers I specified in clusterctl-settings.json

**Environment:**

- Cluster-api version: https://github.com/kubernetes-sigs/cluster-api/commit/215b16b002fd843397f89200cd79d44891b20252

/area clusterctl
/kind bug

**Comment by danniel1205** [comment]
I assume we could create that file by ourselves. But the question is what content we should put inside of the clusterctl-settings.json for docker provider ?

**Comment by sedefsavas** [comment]
For docker developer setup, there is a different workflow: 
https://cluster-api.sigs.k8s.io/clusterctl/developers.html#additional-steps-in-order-to-use-the-docker-provider

Closing this issue.
