### ISSUE TITLE
[Doc][clusterctl] Following clusterctl for developers doesn't work for vsphere provider

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#2425]
**What steps did you take and what happened:**
Following steps here for vsphere provider: https://master.cluster-api.sigs.k8s.io/clusterctl/developers.html#clusterctl-for-developers
1. Create a kind cluster
1. Build clusterctl running: `make clusterctl` in CAPI directory
1. Create clusterctl-settings.json file for infrastructure-vsphere
1. `cmd/clusterctl/hack/local-overrides.py`
1. `./bin/clusterctl init --core cluster-api:v0.3.0 --bootstrap kubeadm:v0.3.0 --control-plane kubeadm:v0.3.0 --infrastructure vsphere:v0.6.0`

> Fetching providers
> Error: failed to get provider components for the "vsphere:v0.6.0" provider: failed to detect default target namespace: Invalid manifest. There should be no more than one resource with Kind Namespace in the provider components yaml

**What did you expect to happen:**
I expected it to create and install the providers I specified in clusterctl-settings.json

**Anything else you would like to add:**
There are 2 namespaces in vsphere infrastructures-component.yaml that is copied to $HOME/.cluster-api/overrides folder by local-overrides.py: capv-webhook-system and capv-system

Solution: Manually creating one of the namespaces in kind cluster and deleting it from  infrastructures-component.yaml solves this problem, but then we hit another issue of finding images. The local-overrides.py does not build images automatically.

Two things need to be added to the doc after fixing the issue above: 
1. Set PULL_POLICY to IfNotPresent in Cluster API Makefile
1. Locally build images and manifests
1. Load images to kind cluster
Then, following the steps in the doc works.

**Environment:**

- Cluster-api version: https://github.com/kubernetes-sigs/cluster-api/commit/215b16b002fd843397f89200cd79d44891b20252

/area clusterctl
/kind bug

**Comment by fabriziopandini** [comment]
@sedefsavas I think that there is a problem int he vsphere manifest, because web-hook components should be deployed into the capi-webhook-system namespace, not into capv-webhook-system
/cc @vincepri @yastij

**Comment by ncdc** [comment]
@sedefsavas can you retest now that https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/764 is in?

**Comment by sedefsavas** [comment]
yes, will retest and update this issue.

**Comment by sedefsavas** [comment]
This is working with the latest changes. Closing.
