### ISSUE TITLE
KubeadmControlPlane upgrade could potentially scale down prior to scaling back up

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#2430]
copied from https://github.com/kubernetes-sigs/cluster-api/pull/2334#issuecomment-590406929

1. `upgradeControlPlane` kicks off because we've got >0 machines that `requireUpgrade`
2. A replacement `Machine` is created, and one of the `selectedForUpgrade` `Machine`s gets annotated with `kubeadm.controlplane.cluster.x-k8s.io/upgrade-replacement-created`
3. The machine in step 2 boots into an invalid state because of one of the various kubeadm tripping hazards. At this point, we've marked one of the `replacementCreated` Machines for deletion, but nothing is being deleted because the etcd health check is failing (the number of etcd members != the number of control plane machines)
4. A human operator says "I know how to handle bad machines, I `k delete` them" and the cleanup process kicks off
5. We still have a `replacementCreated` machine (even though I just deleted its replacement), so `upgradeControlPlane` goes into the `scaleDownControlPlane` flow, where the etcd health check is now passing because the number of control plane `Machine`s _does_ == the number of etcd members

At no point does the cluster go into an unhealthy state, but instead of getting scale up-then-down semantics for the KCP upgrade I get down-then-up semantics. I think the safety check around "don't delete the last ControlPlane if there are other Machines" mitigates the risk of totally losing a cluster, but it was at least a little surprising.

/kind bug
/priority important-soon
/help

**Comment by benmoss** [comment]
/close 

This has been resolved by no longer using annotations for determining upgrade state
