### ISSUE TITLE
[docs] quick start / clusterctl reorganization suggestion

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#2434]
Suggestion: get rid of the yaml-based quickstart and replace it with one that is clusterctl based. We already have the clusterctl quickstart in https://master.cluster-api.sigs.k8s.io/clusterctl/overview.html. I'm not 100% sure what the organization should be. One idea:

- Quick Start contains the clusterctl day 1 flow
- "2. clusterctl CLI" becomes a brief blurb about how clusterctl manages all things Cluster API, with a link to the Quick Start

Thoughts?

/kind documentation

**Comment by vincepri** [comment]
💯 I think we should definitely do this before release
