### ISSUE TITLE
Defaulting webhooks should always set label from Spec.ClusterName

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2438]
We need to make sure that defaulting webhooks for all our type that have a `Spec.ClusterName` field, have logic to default the Cluster Label to the value in Spec.ClusterName.

/kind feature
/milestone v0.3.0
/priority important-soon

**Comment by prankul88** [comment]
@vincepri Hi, I can take this up if you are okay.

**Comment by vincepri** [comment]
go for it!
