### ISSUE TITLE
Spec.ClusterName field should be immutable

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2439]
We need to make sure users aren't allowed to change the `Spec.ClusterName` field after it has been set. Validation webhooks for any type containing this field should contain logic to refuse any updates to the field's value.

/kind feature
/milestone v0.3.0
/priority important-soon

**Comment by sedefsavas** [comment]
I'd like to work on this, can you assign it to me please?

**Comment by vincepri** [comment]
sure!

you can use `/assign` to self-assign issues and set `/lifecycle active` when you're actively working on them
