### ISSUE TITLE
Document Cluster API alpha criteria

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#244]
Cluster API alpha has been discussed in the community meeting, but not documented in an issue for future reference.

This issue is to document proposed alpha criteria to be met, which use cases will be met, and which platforms are being targeted.

This should be shared on slack and in the community meeting.

**Comment by spew** [comment]
Created an issue here: https://github.com/kubernetes-sigs/cluster-api/issues/250 which will be shared and others can edit.

**Comment by spew** [comment]
Posted the issue in slack, will bring it up in the next meeting. 

/close
