### ISSUE TITLE
Bootstrap controllers should set `Spec.Type` when creating and reading Secrets

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2440]
Bootstrap controllers create a Secret in v1alpha3 https://github.com/kubernetes-sigs/cluster-api/blob/eea0aa1c4197d92ab4de3c4c631229ae6877b3bd/bootstrap/kubeadm/controllers/kubeadmconfig_controller.go#L692. 

Secrets have a `Type` field https://godoc.org/k8s.io/api/core/v1#Secret which can be optionally set. 

- Create new secret type, e.g. `bootstrap.cluster.x-k8s.io/data`, add it to `api/v1alpha3` in Cluster API.
- Change the bootstrap controller create the secret using this type.
- Update the `v1alpha2-to-v1alpha3.md` document and ask provider to only read bootstrap data secrets that have this type set.

As a follow-up:
- Make sure that controllers (like CAPA) that read this secret, make sure to only read this type (tbd what this looks like).

/kind documentation
/milestone v0.3.0
/priority important-soon
/help

**Comment by wfernandes** [comment]
I can take work on this if no one has objections 🙂 
/assign

**Comment by neolit123** [comment]
re: auth. an impresionator can potentially match the SecretType as well, so from my POV this seems to serve the ownership distinction purpose.
