### ISSUE TITLE
Exclude metadata when restoring converted objects

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2441]
Cluster API ships with [conversion utilities](https://github.com/kubernetes-sigs/cluster-api/blob/master/util/conversion/conversion.go) to preserve fields that have been added to an API version, but are not present in a previous one.

When performing conversions, we store the "hub" object in an annotation in json format using https://github.com/kubernetes-sigs/cluster-api/blob/master/util/conversion/conversion.go#L96

- Change this function to cleanup everything that's in Metadata before marshaling the object to json.
- Make sure to perform this action only on a copy of the source object.
- Update the function comment to warn users that metadata is not stored.

/kind cleanup
/help
/milestone v0.3.0
/priority important-soon

**Comment by wfernandes** [comment]
Going to take this one 🙂 
/assign
/lifecycle active

**Comment by wfernandes** [comment]
Just to get some clarification on this...does this mean we have to clean up `ObjectMeta` from the source object before adding it as an annotation on the destination object? 

Because that means we will be getting rid of the labels, annotations, name, owner references etc..

**Comment by vincepri** [comment]
yeah that should be fine, metadata is always converted / restored
