### ISSUE TITLE
Discussion: Should we rename references to metal3.io from BareMetal Provider to metal3.io instead?

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#2447]
**User Story**

All references in documentation (and clusterctl) reference the metal3.io provider as the Baremetal Provider, which is a bit misleading. There could be multiple baremetal providers in the future, such as one that could leverage Packet's [tinkerbell project](https://tinkerbell.org/).

**Comment by maelk** [comment]
How far do you think we should go with the renaming ? Is it sufficient to rename it in the CAPI docs + clusterctl only ? What about the provider CRDs ? Moving from baremetalcluster.infrastructure.cluster.x-k8s.io to something like metal3cluster.infrastructure.cluster.x-k8s.io would completely break backwards compatibility, or force us to make some heavy conversion logic in the controllers. It would be a big change, but at the same time, it would be best to do it now than later, considering breaking backwards compatibility at this point is easier than later on with higher adoption levels.

**Comment by maelk** [comment]
I have made a PR to show the changes on CAPI side. Those are minors and can be done without hassle. However, I am a bit against further changes due to the API compatibility break related to renaming things within the provider itself. What do you think ?

**Comment by kashifest** [comment]
> Is it sufficient to rename it in the CAPI docs + clusterctl only

IMHO, we should stick to renaming it in CAPI docs and clusterctl only. Changing the CRDs would not only require a lot of changes but it could potentially break the backwards compatibility as you correctly mentioned.

**Comment by jan-est** [comment]
I agree with @maelk and @kashifest. At this point I don't see any point of renaming it anywhere else than CAPI docs and clusterctl.
