### ISSUE TITLE
LastUpdated field of Machine Status is not populated

### ISSUE THREAD

**Issue by JoelSpeed** [kubernetes-sigs/cluster-api#2452]
The `LastUpdated` field in the `MachineStatus` is meant to be set to the time that the status was last observed. 

I interpret this as, every time the status is updated in any way, the `LastUpdated` field should be updated to `now` just before the `Machine` is patched.

It would be useful if this worked not only for UX for users to see the controller is doing something, but also for Machine Health Checking where the field can be used to determine if a Machine has been stuck without a node for a long period after the `Machine` controller first observes it

**What steps did you take and what happened:**
- Create a Machine in Cluster API

**What did you expect to happen:**
- The `LastUpdated` field should be set when the status of the `Machine` is first updated

**Environment:**

- Cluster-api version: `master` 
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-12-04T07:23:47Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

/kind bug

**Comment by vincepri** [comment]
something that could be possible here is to get the information from the patch helper if there the object had changes

**Comment by detiber** [comment]
Based on the description being status observed, I think relying on the patch helper is probably not what we want here...  We should likely set it to `metav1.Now()` as part of the function that is updating Status.

**Comment by vincepri** [comment]
We don't actually have a status method in the machine controller. If you're referring to `reconcilePhase`, that might be fine, but there is no guarantee that when any other field in status change, the phase changes as well

**Comment by JoelSpeed** [comment]
Would it make sense to take a copy of the `status` before the defer block and then compare this to `m.Status` inside the defer and update the timestamp if they differ (just before `Patch` is called)? 
https://github.com/kubernetes-sigs/cluster-api/blob/25b281e30f4304353c42ac7ebcddf37648847866/controllers/machine_controller.go#L130-L138

**Comment by detiber** [comment]
True, but in essence Status is something that should be the "observed" state of the world at the time of the current reconciliation, so maybe we need to think about potentially updating the Phase each time, or just defer it since we plan on moving towards Conditions post v1alpha3.

**Comment by vincepri** [comment]
I see two possible paths forward:

- Set `Status.LastUpdated` only when the Phase changes, we can do this in `reconcilePhase`.
   - We'll have to update the comment description as well to reflect this change.

- Modify `helper.Patch` function to return an output describing what the patcher has actually done or patched. This could be useful in a number of places, also it could give us a venue where we can find if the patches were actually applied or it was a no-op.

Example:
```
type PatchOutput struct {
    ObjectPatchedAt *metav1.Time
    StatusPatchedAt *metav1.Time
}
```

potentially in the future we could also extend this struct to include the actual patches sent to the client for better debuggability and observability.

**Comment by JoelSpeed** [comment]
@vincepri I think the second option of extending the `Patch` means that we would have to patch twice every time the status is updated, the first one to update the status, the second one to update the `LastUpdated` because the status was changed in the first patch,  this might make the update logic a bit complicated? I don't know if double updates might also cause some issues with reocnciles or conflicts?

I'm gonna have a go at implementing the first option of changing the field on phase changes for now

/lifecycle active
