### ISSUE TITLE
standardize codebase on controller-runtime's client's ObjectKey instead of types.NamespacedName

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2459]
Basically replace all instances of types.NamespacedName with ObjectKey when controller-runtime's client package is already imported. This prevents an additional import and keeps the code base consistent.

/kind feature
/priority important-longterm
/milestone Next

**Comment by detiber** [comment]
In some cases, we can likely also use `util.ObjectKey` in place of manually building up the `client.ObjectKey`
