### ISSUE TITLE
Document that dollar mark needs to be escaped for variable expansion in clusterctl

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#2460]
Just a small todo / note to self.

When using env vars, for example a password, if it contains a dollar symbol, in addition to being single quoted, it needs to be doubled, .e.g.:
The password foo$bar must be represented as:

PASSWORD='foo$$bar'

Looks like some variable expansion happening in viper, but can get hit.

/kind feature
/area documentation

**Comment by fabriziopandini** [comment]
@randomvariable I checked viper documentation and there is nothing about variable expansion...

**Comment by fabriziopandini** [comment]
This one was fixed by https://github.com/kubernetes-sigs/cluster-api/pull/2858
Sorry I missed this issue reporting the same problem
