### ISSUE TITLE
Add version table to README.md

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes-sigs/cluster-api#2476]
It's unclear what branch maps to what release in cluster-api for development purposes.

We should add a table like this one: https://github.com/kubernetes-sigs/cluster-api-provider-aws/#compatibility-with-cluster-api-and-kubernetes-versions

/kind bug

**Comment by cpanato** [comment]
@vincepri how can i discovery or know the version to create this documentation for CAPI?

**Comment by vincepri** [comment]
/lifecycle frozen

We should add this to the book

**Comment by fabriziopandini** [comment]
/close
it turns out there is already this table in the book https://cluster-api.sigs.k8s.io/reference/versions.html#cluster-api-version-support-and-kubernetes-version-skew-policy
