### ISSUE TITLE
Controllers must respect the `Type` field of secrets.

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#2479]
**User Story**

As an operator I would like to ensure that controllers are reading in secrets of a specified type in order to ensure integrity and validity.

**Detailed Description**

Cluster API components should only read secrets that respect the correct `Type`. 

**Anything else you would like to add:**

References:
#2478 Issue that discusses updating older secrets that don't have the `Type` field yet.
#2440 Issue that sets `Type` for new secrets created by the kubeadm bootstrap controller.
#2443 (comment) PR

/kind feature

**Comment by vincepri** [comment]
@wfernandes Is there anything else to do here?

**Comment by wfernandes** [comment]
@vincepri I don't think so. It seems that the referenced issues above have been closed through their respective PRs.
Thanks.
/close
