### ISSUE TITLE
clusterctl: improve error message when parsing templates fails

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#2495]
**What steps did you take and what happened:**
call `clusterctl config cluster` with an invalid template or a variable that makes your template an invalid yaml

You get an error: like 
```
Error: failed to parse yaml: failed to unmarshal yaml fragment: "apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3\nkind: HAProxyLoadBalancer\nmetadata:\n labels:\n  cluster.x-k8s.io/cluster-name: vsphere-quickstart\n name: vsphere-quickstart\n namespace: default\nspec:\n user:\n  authorizedKeys:\n  - ssh-rsa AAAA...\n  name: capv\n virtualMachineConfiguration:\n  cloneMode: linkedClone\n  datacenter: Datacenter\n  datastore: ssd01\n  diskGiB: 25\n  folder: TKG\n  memoryMiB: 8192\n  network:\n   devices:\n   - dhcp4: true\n    networkName: VM Network\n  numCPUs: 2\n  resourcePool: */Resources\n  server: vcenter.lab\n  template: capv-haproxy-v0.5.3-77-g224e0ef6\n": error converting YAML to JSON: yaml: line 25: did not find expected alphabetic or numeric character
````

Which is hard to debug, mostly because:

- the YAML is divided into documents (split by ---)
- then documents are processed one by one
- the error message `line 25: did not find expected alphabetic or numeric character is referred to the fragment, not to the whole YAML file`;

**What did you expect to happen:**
A bettor error management, that at least makes it easy to identify what document the error refers to.

E.g. failed to parse the 6th document in the provider yaml ...

**Anything else you would like to add:**
The func to be fixed is https://github.com/kubernetes-sigs/cluster-api/blob/308f931d5f0c457d6253efedffe7e860126c0744/cmd/clusterctl/pkg/internal/util/yaml.go#L56

**Environment:**

- Cluster-api version:v0.3.0-rc.2

/kind bug
/help
/area clusterctl

**Comment by fabriziopandini** [comment]
xref https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/792

**Comment by kacole2** [comment]
@fabriziopandini I'm hitting this same exact error. However, I have no idea how to fix this. Is there something I can do to change my configuration? I'm not sure what character it's finding that's producing this error:
```
error converting YAML to JSON: yaml: line 25: did not find expected alphabetic or numeric character
```
