### ISSUE TITLE
clusterctl: allow empty env variables

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#2497]
**What steps did you take and what happened:**
```
export TEST=
```
And then read a template/a component YAML file that uses the test variable e.g.
```
clusterctl config cluster test --infrastructure docker:v0.3.0 --target-namespace default
Error: failed to perform variable substitution: value for variables [TEST] is not set. Please set the value using os environment variables or the clusterctl config file
```

**What did you expect to happen:**
I would like clusterctl to consider the empty env variables (because empty is different than unset !)

**Anything else you would like to add:**
The issue should be fixed [here](https://github.com/kubernetes-sigs/cluster-api/blob/55a9fe3cd2216c50ff2ecd90dab4816728323416/cmd/clusterctl/pkg/client/config/reader_viper.go#L61) by adding `viper.AllowEmptyEnv(true)`

It would be nice to add a unit test as well

**Environment:**

- Cluster-api version: v0.3.0-rc.2

/area clusterctl
/help
/kind bug

**Comment by vincepri** [comment]
are there any particular use cases that we're trying to solve with this feature?

**Comment by fabriziopandini** [comment]
@vincepri I have no a specific use case in mind (I just spotted this viper behavior by chance while testing)

**Comment by vincepri** [comment]
If that's ok with you, I'd leave this like it is for now and come back to this issue if there are use cases or bug reports, wdyt?

**Comment by fabriziopandini** [comment]
@vincepri it seems there is a use case in vSphere.
The change should be really simple. Do you want to reconsider and put this in the milestone?

**Comment by vincepri** [comment]
Sure, if you think it's valuable, let's do it

/milestone v0.3.0
