### ISSUE TITLE
clusterctl: UX improvement NoSchedule taint for single nodes

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api#2499]
**User Story**

As a user I would like to have a small reminder in the documentation and when running commands that the cert-manager and CAPI components will not work on a single node VM that still has the NoSchedule taint on it.  `clusterctl init` will timeout without much information if the providers just wait indefinitely for an available node.

**Detailed Description**

The typical pivot operation (start with kind, pivot to a management cluster that has been stood up by CAPI) uses a single VM, however, that process does not remove the NoSchedule taint from the single VM.  So the next steps in `clusterctl` will timeout and the pods will hang indefinitely.

The documentation should prompt that during the instructions, and as a stretch goal it'd be nice if `clusterctl` could handle that situation since it will probably be common (or will it be common?)

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by nader-ziada** [comment]
is the idea that `clusterctl` move should remove the NoSchedule taint after its done pivoting?

**Comment by voor** [comment]
I think it's a little more complicated than that, what if your management cluster isn't a single node?

**Comment by nader-ziada** [comment]
yeah, this issue is only applicable if its a single node cluster, correct?

**Comment by detiber** [comment]
It's likely to be an issue on any cluster where there are only control plane Machines without any worker Machines.

**Comment by nader-ziada** [comment]
I guess I'm trying to figure out what the expected behaviour should be: 
 - clusterctl checks if there are no workers and remove the NoSchedule taint 
 - clusterctl checks if there are no workers and gives an error message
 - clusterctl does nothing and we add an item in docs to clarify the requirements of the target cluster

**Comment by detiber** [comment]
We can likely add a check to clusterctl that looks at the cluster's Nodes to see if there are any that have the problematic NoSchedule taint and returns an error if so.

I don't think we should modify taints on the management cluster's Nodes, though.

**Comment by nader-ziada** [comment]
makes sense to me, will work on that

**Comment by voor** [comment]
Maybe if you only have master nodes (specifically look for the `node-role.kubernetes.io/master` key), fire off an error message and prompt for a `--with-tolerations` option that could re-do the same operations with a toleration for the NoSchedule key?

**Comment by vincepri** [comment]
>clusterctl does nothing and we add an item in docs to clarify the requirements of the target cluster

This is something we should do today, if we can get it in v0.3.0 that'd be great!

**Comment by voor** [comment]
I'm okay with this going stale, I realize it's a fairly unique use case, if someone else is passionate about it feel free to bump it.

**Comment by vincepri** [comment]
Given that we've merged https://github.com/kubernetes-sigs/cluster-api/pull/3034 to (partially) solve this issue, I'll go ahead and close this for now, we can revisit later if necessary.

/close
