### ISSUE TITLE
Cluster API Alpha - Exit Criteria

### ISSUE THREAD

**Issue by spew** [kubernetes-sigs/cluster-api#250]
To declare Cluster API alpha as complete the following must be true:

**Release Vehicle and Certification**
* On this repository, a release branch named "alpha" must be created. 
  * In the release branch, out of the prow infrastructure, all integration and unit tests must be passing.
  * The release branch must satisfy all the requirements given below.

**Requirements** 
* The github issue milestone named "[cluster-api-alpha-implementation](https://github.com/kubernetes-sigs/cluster-api/milestone/2)" must have zero open issues.
* The gcp-deployer directory must be deleted from the repository.
* There must be integration tests running out of the CI build for clusterctl using GCP as a provider, the test suite must include the following scenarios:
  * Create, Delete
  * Update
    * Grow / Shrink node count
    * Upgrade Kubernetes version
* The architecture diagram in the root of the repository must be updated and accurate

**Beta**
The exit criteria for beta is being tracked here: https://github.com/kubernetes-sigs/cluster-api/issues/259

**Comment by timothysc** [comment]
I'd add some more details: 

- Some form of test-grid integration / posting 
- Discoverability... (how will releases be posted?) tracked, etc?  I'm a big fan of goreleaser. 
  - Provider integrations... Where do folks find/get integrations?

**Comment by timothysc** [comment]
Closing, we are currently tracking inside of https://github.com/kubernetes-sigs/cluster-api/milestone/4
