### ISSUE TITLE
Could not delete KubeadmControlPlane object if owner cluster has already being deleted

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#2507]
**What steps did you take and what happened:**
Not sure if deleting an object whose owner reference has already been deleted should be a supported workflow but creating this in case it is.
1. Create KubeadmControlPlane object and a control plane cluster is initialized.
1. Delete that cluster and try to delete KubeadmControlPlane object, it stucks because reconcile function first tries to get the owner cluster.

**What did you expect to happen:**
I expected to be able to delete KubeadmControlPlane object even if  its owner cluster is missing.

**Environment:**

- Cluster-api version: https://github.com/kubernetes-sigs/cluster-api/commit/5e03ae53c91683c1ade05c5635acf95364352abe

/kind bug

**Comment by ncdc** [comment]
Was the Cluster 100% gone but the KubeadmControlPlane was still there, or was the Cluster in the middle of being deleted?

**Comment by sedefsavas** [comment]
Cluster was gone and KubeadmControlPlane deletion stucks here:

```
cluster.cluster.x-k8s.io "mgmt-cluster" deleted
haproxyloadbalancer.infrastructure.cluster.x-k8s.io "mgmt-cluster" deleted
vspherecluster.infrastructure.cluster.x-k8s.io "mgmt-cluster" deleted
vspheremachinetemplate.infrastructure.cluster.x-k8s.io "mgmt-cluster" deleted
kubeadmcontrolplane.controlplane.cluster.x-k8s.io "mgmt-cluster" deleted
```

It says deleted but the  object is kubeadmcontrolplane still there:
```
➜  out_change git:(master) ✗ kubectl get kubeadmcontrolplane -A       
NAMESPACE   NAME            READY   INITIALIZED   REPLICAS   READY REPLICAS   UPDATED REPLICAS   UNAVAILABLE REPLICAS
default     mgmt-cluster           true                     2      
```

**Comment by ncdc** [comment]
Ok, we may need to modify the cluster controller to block removing the cluster's finalizer if there is still a control plane around.

**Comment by ncdc** [comment]
https://github.com/kubernetes-sigs/cluster-api/blob/cb079834fa40d09dbfdaf35de16679ccd8e4f9c6/controllers/cluster_controller.go#L210-L224

only does the delete, but it doesn't block if it's still there and being deleted

**Comment by ncdc** [comment]
@sedefsavas did you have any `Machines` for the `KubeadmControlPlane`?
