### ISSUE TITLE
Review webhook certificate/issuer strategy 

### ISSUE THREAD

**Issue by alexbrand** [kubernetes-sigs/cluster-api#2510]
We are currently creating three separate issuers for the validating/mutating/conversion webhook certificates.

```
$ kubectl get issuer -n capi-webhook-system
NAME                                           AGE
capi-kubeadm-bootstrap-selfsigned-issuer       109m
capi-kubeadm-control-plane-selfsigned-issuer   109m
capi-selfsigned-issuer                         109m
```

Review this strategy and figure out if we should collapse to a single issuer.

cc/ @vincepri

**Comment by vincepri** [comment]
Thanks for filing the issue! 

If we want to re-use CAPI's issuer we might need to rework kustomize to accomodate this change, we might need a spike to understand what changes are needed and evaluate if we actually want to go down this path.

**Comment by vincepri** [comment]
Closing this given that it's a nice to have, and we should probably move away (or document how to) from self signed certs.
