### ISSUE TITLE
Cluster Autoscaler scale from zero UX

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes-sigs/cluster-api#2527]
Cluster Autoscaler supports scale from zero for cloud-native providers.  This is done via compiling CPU, GPU, and RAM info into the cluster autoscaler at build time for each supported cloud.

We are attempting to add cluster-api support to the cluster-autoscaler to scale machinesets, machinedeployments, and/or other groupings of machines as appropriate.  We are trying to keep an abstraction which is isolated from particular cloud implementations.  We need a way to inform the cluster-autoscaler of the value of machine resources so it can make proper scheduling decisions when there are not currently any machines in a particular scale set (machineset/machinedeployment, etc).

We will need input from the autoscaler team, as well as input from api reviewers to ensure we obtain the best solution.

/kind proposal

**Comment by vincepri** [comment]
As per April 27th 2020 community guidelines, this project follows the process outlined in https://github.com/kubernetes-sigs/cluster-api/blob/master/CONTRIBUTING.md#proposal-process-caep for large features or changes.

Following those guidelines, I'll go ahead and close this issue for now and defer to contributors interested in pushing the proposal forward to open a collaborative document proposal instead, and follow the process as described.

/close
