### ISSUE TITLE
Add unit & integration testing for clusterclient

### ISSUE THREAD

**Issue by jessicaochen** [kubernetes-sigs/cluster-api#254]
This for integration tests where we actually use kubectl etc.

Will involve making sure kubectl and etcd is installed on the presubmit image etc.

**Comment by ingvagabund** [comment]
@jessicaochen are you talking about specific presubmit image?

**Comment by jessicaochen** [comment]
The image by testinfra used to run the presubmit tests for this repo.

**Comment by ncdc** [comment]
What are we talking about testing here? Which code and/or workflow(s)?

**Comment by timothysc** [comment]
closing
