### ISSUE TITLE
KCP: Handle `etcd` upgrades

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2543]
This issue is a follow-up to #2226.

- relax the validating webhook to allow mutations to the etcd image details in KCP spec
- add code that syncs the etcd image details from the KCP to the kubeadm-config ConfigMap in the workload cluster

/kind feature
/milestone v0.3.0
/priority critical-urgent
/area control-plane

**Comment by vincepri** [comment]
cc @chuckha

**Comment by chuckha** [comment]
reminder to self: need to ensure that if external is set and local gets updated that should fail validation

**Comment by vincepri** [comment]
@chuckha want me to open a different issue for that?

**Comment by chuckha** [comment]
got it, #2580
