### ISSUE TITLE
Document infrastructure machine templates & immutability

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#2557]
We should document that when using infrastructure machine templates (e.g. in KubeadmControlPlane, MachineDeployment, MachineSet), these templates are generally meant to be immutable. If you want to change a field in one of these templates (e.g. AWS instance type), the typical process is to duplicate an existing template, update field(s), give it a new name, and create it in the apiserver. Once the new template has been persisted, then modify the KubeadmControlPlane/MachineDeployment/MachineSet to have it reference the new template. This will trigger a rolling update.

One caveat, is that some infrastructure providers, at their discretion, can choose to support in-place modifications of certain template fields, as long as they understand that Cluster API **WILL NOT** trigger a rolling update. This could be helpful if an infrastructure provider is able to do a live change for something like # of CPUs or memory.

/kind documentation
/help
/milestone Next

**Comment by scottslowe** [comment]
I'd like to help with this issue. Do we anticipate this would create a new standalone doc somewhere (like in the `docs` directory), or that it should be a new page/section in the book?

**Comment by ncdc** [comment]
It should show up on our docs site, so it'll need to go somewhere in `docs/book/src`. I'm not sure off the top of my head where the best place in there is. Do you have any thoughts?

**Comment by scottslowe** [comment]
Perhaps in the “Tasks” section, with a title like “Changing Infrastructure Machine Templates” or similar?

**Comment by ncdc** [comment]
SGTM. We can always move it around later if needed.

**Comment by scottslowe** [comment]
PR submitted, appreciate any feedback.
