### ISSUE TITLE
clusterctl: manage cert-manager image changes

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#2566]
**What steps did you take and what happened:**
https://github.com/kubernetes-sigs/cluster-api/pull/2558 is introducing the possibility to change the image for cert-manager during init.
However, currently, there is no way to manage successive changes to the cert-manager images, so it is necessary to introduce support for cert-manager upgrades in clusterctl

**What did you expect to happen:**
I expect that cert-manager image can be changed in some way

**Anything else you would like to add:**
As initial solution for this problem, it is possible to leverage on a solution similar to what already implemented for web-hooks upgrades.
This solution basically re-install the components, triggering a patch a case component already exists.

**Environment:**

- Cluster-api version: https://github.com/kubernetes-sigs/cluster-api/pull/2558 branch

/kind bug
/area clusterctl
/lifecyle active 
/cc @vincepri 
/cc @ncdc

**Comment by detiber** [comment]
Do we need to worry about potentially orphaning resources that may no longer be part of a new cert-manager release, but were part of an older release?

**Comment by fabriziopandini** [comment]
@detiber since the manifest is statically embedded and we are supporting only image version changes, I think the proposed trade-off is acceptable (there won't be orphaned resources unless the manifest is changed, but this requires a release)

**Comment by detiber** [comment]
@fabriziopandini sgtm, I'm wondering the best place to document that we should verify this manually prior to updating the manifests or at least prior to releasing.

**Comment by ncdc** [comment]
@fabriziopandini cert-manager has changed its architecture a bit in releases after 0.11. I'm not sure it's as simple as just applying a new manifest. For example, it's my understanding that the apiservice we're currently watching and waiting to be available no longer exists in newer versions, so the code we have in clusterctl to wait for cert-manager availability will have to change.

**Comment by vijaykatam** [comment]
The docs for 0.11 to 0.12 call out removal of Webhook API service. See https://cert-manager.io/docs/installation/upgrading/upgrading-0.11-0.12/#removal-of-the-webhook-api-service

**Comment by fabriziopandini** [comment]
@ncdc @vijaykatam 
I apologize, but probably the title of the issue created some confusion.

The proposed solution is designed "to manage successive changes to the cert-manager images" not for managing "full" cert-manages upgrades like 0.11 --> 0.12

I'm changing the title of the issue to make this more clear

**Comment by vincepri** [comment]
Closing this given that we'll support a newer version of cert-manager in v0.3.9 w/ clusterctl init or upgrade.

/close
