### ISSUE TITLE
[kubeadm control plane] ensure etcd settings are correct

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2580]
If a user uses the external setting of etcd we need to make sure changes to the local etcd don't validate in the web hook because defining both external and local doesn't make any sense as far as kubeadm config is concerned

/kind bug
/assign
/priority important-longterm

**Comment by vincepri** [comment]
/help
/milestone v0.3.x

Although it would be nice to have in v0.3.0, maybe @nader-ziada or @gab-satchi are interested in helping here?

**Comment by nader-ziada** [comment]
I. can work on it, but not sure whats needed yet

/assign
