### ISSUE TITLE
Scale in support for KCP

### ISSUE THREAD

**Issue by jan-est** [kubernetes-sigs/cluster-api#2587]
I would like to start an discussion about KCP scale in support. This feature is much needed in small baremetal clusters where operators don't want to run idle resources for upgrade and all possible resources are in use. 

User Story

As an operator I would like to update my baremetal control plane machines without having additional baremetal machines.

Detailed Description

KCP upgrade should support scale in when infrastructure don't have extra resources and cluster is running minimum 3 control plane nodes. In case of only one KCP and no extra resources the upgrade of baremetal control plane is left to the operator.  

/kind feature

**Comment by jan-est** [comment]
Proposal opened [#2688 ](https://github.com/kubernetes-sigs/cluster-api/pull/2688)

**Comment by vincepri** [comment]
As per April 27th 2020 community guidelines, this project follows the process outlined in https://github.com/kubernetes-sigs/cluster-api/blob/master/CONTRIBUTING.md#proposal-process-caep for large features or changes.

Following those guidelines, I'll go ahead and close this issue for now and defer to contributors interested in pushing the proposal forward to open a collaborative document proposal instead, and follow the process as described.

/close
