### ISSUE TITLE
Cluster API Beta - Exit Criteria

### ISSUE THREAD

**Issue by spew** [kubernetes-sigs/cluster-api#259]
To declare Cluster API beta as complete the following must be true:

**Release Vehicle and Certification**
* On this repository, a release branch named "beta" must be created. 
  * In the release branch, out of the prow infrastructure, all integration and unit tests must be passing.
  * The release branch must satisfy all the requirements given below.

**Requirements** 
* The github issue milestone named "[cluster-api-beta-implementation](https://github.com/kubernetes-sigs/cluster-api/milestone/3)" must have zero open issues.
* All provider / cloud specific code is removed from the repository (i.e. google cloud, vsphere, etc).

**Comment by dims** [comment]
- Do we need more than one working cloud implementation?
- Do we need release signal(s) / conformance test(s) from these possibly out-of-tree providers?

**Comment by enxebre** [comment]
Since the actuator implementations are going out of tree, do we wanna set a common alpha/beta criteria for them here? or should this just live independently in each repo?

**Comment by timothysc** [comment]
After we are done with alpha1 we will reaccess priorities for either v1alpha2 or v1beta1 in milestones.
