### ISSUE TITLE
Agent nodes have role of "<none>"

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api#2596]
**User Story**

As a [developer/user/operator] I would like to [high level description] for [reasons]

**Detailed Description**

Currently, capi clusters have agent nodes with role `<none>`:

```
% kubectl --kubeconfig=./examples/_out/clusterapi.kubeconfig get no
NAME                          STATUS   ROLES    AGE     VERSION
capz-cluster-controlplane-0   Ready    master   6m43s   v1.16.7
capz-cluster-controlplane-1   Ready    master   5m10s   v1.16.7
capz-cluster-controlplane-2   Ready    master   3m51s   v1.16.7
capz-cluster-md-0-xbm55       Ready    <none>   3m41s   v1.16.7
capz-cluster-md-0-xmtz2       Ready    <none>   2m49s   v1.16.7
```

We should consider applying a role in capi since this isn't anything provider specific.

ref: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/423

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

cc @detiber 

[Miscellaneous information that will assist in solving the issue.]

**Comment by fabriziopandini** [comment]
Xref because relevant for this issue https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/2019-07-16-node-role-label-use.md#use-of--labels

**Comment by ncdc** [comment]
If anyone has opinions on what labels to use by default for worker nodes, please share your ideas here!

**Comment by ncdc** [comment]
(or we could leave it up to the user and not have any CAPI defaults)

**Comment by ncdc** [comment]
Should also make sure this is consistent with all SIG Cluster Lifecycle sub-projects

**Comment by yhrenlee** [comment]
Hi everyone! 

We used to heavily rely on `node-role.kubernetes.io` for conveniently showing names of node roles in the `ROLES` column of `kubectl get nodes` output, as well as using this label to schedule our workloads to the right nodes. It looks like this label cannot be used anymore. 

Could we perhaps use the new allowed label `role.node.kubernetes.io/* ` as the new standard for node role names? And it would be great to have this label have the previous behavior of having the name displayed in kubectl output as well? It looks like this label would be safe given this [proposal](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md#proposal) 

Thanks!

**Comment by CecileRobertMichon** [comment]
cc @mboersma who originally reported the issue in capz in case he has any thoughts on this.

**Comment by jfrabaute** [comment]
Here is a PR implementing the proposed new label `role.node.kubernetes.io/*`: https://github.com/kubernetes/kubernetes/pull/89242

There are 2 preliminary commits for minor code refactoring and adding test coverage for the existing code before adding the new code.

**Comment by jfrabaute** [comment]
Rereading the KEP more carefully, I think this PR is not correct.
What it should probably propose is to add `role.node.kubernetes.io/*` as an other way to provide node role to be displayed by `kubectl` and available in tooling like `gcloud` (which is forbidding the usage of `node-role.kubernetes.io/*`, that's why this PR exists).

Is that correct?

**Comment by vincepri** [comment]
Closing in favor of #493 

/close
