### ISSUE TITLE
Docs: evaluate if possible to remove install.md

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#2601]
**Detailed Description**
rif. https://github.com/kubernetes-sigs/cluster-api/pull/2590#discussion_r389754110

The Cluster API quick-start imports the `install.md` file which is basically the quickstart minus setting up the workload cluster. If possible, we should we get rid of this file and merge all its content into `quick-start.md`.

**Anything else you would like to add**:
Before implementig the change, it should be verified if the `install.md` file is used elsewhere.

/kind documentation
/priority backlog

**Comment by ncdc** [comment]
At today's meeting, we agreed to remove the duplication.
/help

**Comment by randomvariable** [comment]
Had rewritten a chunk of the quickstart in #2628 so have included this change as well.

/assign
/lifecycle active
