### ISSUE TITLE
[kubeadm control plane] consider modifying ready checks

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2602]
The KubeadmControlPlane status looks at nodes within the workload cluster. Since the kubeadm control plane controller should not (can not?) be tied to resources on a different cluster from where the controller is running, we may need an alternative ready check. One that bubbles up through Machines.

Perhaps if the Machine's ready relies on the Ready status (maybe it already does) then we can use the machine's ready checks to determine the number of ready nodes for the control plane.

~The issue I'm seeing is that after a control plane comes up the reconciler has nothing to do so will only rereconcile after 10 minutes, however during the final reconcile before the 10 minute pause, only 2/3 nodes are Ready. This means that for 10 minutes the status is out-of-date and reports 2/3 nodes are ready until the full re-reconcile happens.~ Fixed by receiving notifications from the workload cluster nodes.

/kind bug
/area control-plane
/milestone v0.3.x

**Comment by detiber** [comment]
An alternative using Machines as an intermediate here is to take a similar approach to what the MachineHealthCheck controller is doing around setting up Watches for Nodes on the workload clusters.

**Comment by chuckha** [comment]
oh if there's already a precedent for watching workload cluster nodes, i'm +1 that approach

**Comment by ncdc** [comment]
Yes, if what matters is node readiness, we can & should be watching the appropriate nodes.

**Comment by randomvariable** [comment]
Oh, just noticed this. The node readiness check underpins #2705
