### ISSUE TITLE
Add version check during `kube-proxy` daemonset upgrade

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#2606]
**User Story**

As a user/operator I would like to see errors if the version I have in KCP spec.Version is not valid for kube-proxy upgrades (such as current kube-proxy version is higher.)

**Detailed Description**

CoreDNS upgrade already has semver validation so once [the PR](https://github.com/kubernetes-sigs/cluster-api/pull/2574) is merged we can reuse some part of that check. 
We can also address `restricting version upgrades to one minor change` issue here: https://github.com/kubernetes-sigs/cluster-api/issues/2578

/kind feature

**Comment by ncdc** [comment]
@sedefsavas since the kube-proxy version matches the overall cluster version in the KubeadmControlPlane spec, would this be covered by #2578?

**Comment by ncdc** [comment]
(i.e. do you think we need a separate issue for this?)

**Comment by sedefsavas** [comment]
Yes, good point! Closing this.
