### ISSUE TITLE
KCP: Add e2e tests for kube-proxy daemonset upgrade

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#2608]
We should add e2e tests using the e2e framework to test kube-proxy daemonset upgrade. 
This is a follow up issue to https://github.com/kubernetes-sigs/cluster-api/issues/2544

/milestone Next
/priority backlog

**Comment by vincepri** [comment]
/milestone v0.3.x

given that this didn't make the cut
