### ISSUE TITLE
KCP: Add e2e tests for CoreDNS deployment upgrade 

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#2609]
We should add e2e tests using the e2e framework to test CoreDNS deployment upgrade.
This is a follow up issue to https://github.com/kubernetes-sigs/cluster-api/issues/2545

/help

**Comment by rajansandeep** [comment]
I can help writing the tests.

**Comment by wfernandes** [comment]
@rajansandeep Are you working on this? If you are, feel free to `/assign` and `/lifecycle active`.

**Comment by vincepri** [comment]
/milestone v0.3.x

given that this didn't make the cut

**Comment by gab-satchi** [comment]
Hey @rajansandeep are you still working on this?
