### ISSUE TITLE
KCP: Add e2e tests for ETCD upgrade

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#2610]
We should add e2e tests using the e2e framework to test ETCD upgrade by modifying ETCD version in kubeadm config map.
This is a follow up issue to https://github.com/kubernetes-sigs/cluster-api/pull/2579

/help

**Comment by vincepri** [comment]
/milestone v0.3.x

given that this didn't make the cut

**Comment by gab-satchi** [comment]
Fixed by #2785 
/close
