### ISSUE TITLE
Specify namespace in the resource references

### ISSUE THREAD

**Issue by 2mind** [kubernetes-sigs/cluster-api#2611]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
In the current implementation of machineset - bootstrapRef, infraRef should be in the same namespace as the controller itself, namespace will be ignored.

https://github.com/kubernetes-sigs/cluster-api/blob/v0.2.10/controllers/machineset_controller.go#L262

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I would like to be able specify namespace in the resource references.

**Environment:**

- Cluster-api version: v0.2.10
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): 1.17.3
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by randomvariable** [comment]
This was done intentionally and is in essence a deprecation of the old behaviour. Cross-namespace support breaks the ability to use a namespace as a security boundary, e.g. referencing a bootstrap config from another namespace may allow an attacker to get access to a cluster they are not currently privileged to access.

The namespace field will be removed in due course.

/kind documentation
