### ISSUE TITLE
[capd] remove kubeadm reset 

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2618]
I've seen the capd-e2es fail on this call many times.

The kubeadm reset hack is actually a hack to remove a control-plane node cleanly from a kubeadm cluster. However, as this is now handled by the kubeadm control plane we should remove the calls to kubeadm reset entirely and not have the machine controller worry about `kubeadm reset`.

/kind bug
/milestone v0.3.x
/priority important-longterm

**Comment by fabriziopandini** [comment]
That' means that building control panes-up using stand-alone machines is deprecated with CAPD?

**Comment by chuckha** [comment]
It's not deprecated but it will no longer automatically manage the config map and all the other nice things kubeadm reset does. This brings CAPD in line with other providers such as CAPA, which, @detiber can confirm or deny, won't automatically manage control plane machine removals without user intervention.

**Comment by fabriziopandini** [comment]
kk, thanks for clarification!
