### ISSUE TITLE
[capd e2es] capture webhook logs 

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2619]
In addition to the provider controller logs, the capd-e2es should also dump any webhook logs. Note that capd itself has no web hooks, but CAPI does indeed and those could be interesting.

/kind bug
/milestone v0.3.x
/priority important-longterm

**Comment by fabriziopandini** [comment]
@benmoss just saw a notification about this issue.
this should be already addressed by latest changes in the test framework; also capd-e2e test are going to be replaced by test e2e...

**Comment by vincepri** [comment]
Should we close this one out?

**Comment by fabriziopandini** [comment]
@vincepri +1 to close
