### ISSUE TITLE
Create controller app utility functions for leader election and recorder logic

### ISSUE THREAD

**Issue by mkjelland** [kubernetes-sigs/cluster-api#262]
Create utility functions for leader election and recorder logic in [gce machine controller app](https://github.com/kubernetes-sigs/cluster-api/blob/master/cloud/google/cmd/gce-machine-controller/app/controller.go). This logic will be reused by the gce machine controller app in PR #242. The logic should be refactored to remove the duplicated logic.

**Comment by roberthbailey** [comment]
@pwittrock / @droot - Is there support for standard k8s leader election built into the kubebuilder framework? I'd love to close this as obsolete now that we've switched to CRDs.

**Comment by vincepri** [comment]
Leader election should be supported in controller-runtime's manager, I don't think it's being used at this point though.

**Comment by ncdc** [comment]
I don't think this is necessary for v1alpha1. I propose we defer.

**Comment by vincepri** [comment]
Agreed!

/milestone Next
/priority important-longterm

**Comment by ncdc** [comment]
As best I can tell, the manager automatically enables leader election. I'm going to close this but we of course can reopen if needed.

/close
