### ISSUE TITLE
Add coredns validation in KCP validation webhook

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#2620]
**User Story**

As an operator, I would like to ensure my coredns version update is "migratable" by having extra validation in the webhook.

**Detailed Description**

In KCP KubeadmConfig, there is a property
```
dns:
...
  ImageTag: 1.2.3-foobar.1
```
We need to have validation in the webhook that takes the `ImageTag` and make sure it is valid using the `github.com/coredns/migration` library. 
I believe there is a `migration.validUpMigration` method that does it but unfortunately it is not exported. 

**Anything else you would like to add:**

Currently coredns upgrade code calls the `migration.Migrate` which does migrate up and not migrate down. So that means we are only handling upwards migrations at the moment.

/kind feature
/area control-plane

**Comment by rajansandeep** [comment]
> I believe there is a migration.validUpMigration method that does it but unfortunately it is not exported.

If it's really required, I can help with exporting it. (I feel it won't be required, since the `migration.Migrate` validates the version first before attempting to migrate the corefile) 

> Currently coredns upgrade code calls the migration.Migrate which does migrate up and not migrate down. So that means we are only handling upwards migrations at the moment.

There is a `migration.MigrateDown` function which handles downgrades. (Although it is advised against downgrading coredns)

**Comment by detiber** [comment]
@rajansandeep I think the idea with the validating webhook is to provide feedback to the user that the migration is unsupported when they attempt to update the resource rather than having to notice an event and/or inspect logs to determine that they applied a request for an incompatible version.

**Comment by vincepri** [comment]
/milestone v0.3.x

given that this didn't make the cut
