### ISSUE TITLE
CAPD worst-case-scenario cloud simulator for naughty clouds.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api#2627]
Follow on to #2591 which is closed, but, took quite a while to close b/c of cloud ambiguities.  Seems like as CAPI matures, its entire bug reporting and testing process should be self contained.  I'm somewhat new to   sig-cluster-lifecycle, so let me know if this might be misinformed.

**Motivating issues**

I dug through the CAPI backlog, and saw alot of ambiguous issues and alot of toil around reproducing things... 

- https://github.com/kubernetes-sigs/cluster-api/issues/2446 (need for robust CAPD testing)
- https://github.com/kubernetes-sigs/cluster-api/issues/2584 (disambiguating bug sources)
- https://github.com/kubernetes-sigs/cluster-api/issues/2591 (disambiguating bug sources)
- https://github.com/kubernetes-sigs/cluster-api/issues/2283 (reporting bugs requires 2x work)

**User Story**

As a developer, I'd like to be able to know that clusters failing to come up because of  cloud latency, I/o, LB, firewall, or other errors I'm having are easily binned into one of two categories.
 
- not inflamed at all by CAPI's logical robustness   (i.e. clearly a provider issue) 
- inflamed by a bug in CAPI which can be reproduced from a cloud neutral test environment, such as CAPD)  (i.e. clearly a CAPI issue) 

**Detailed Description**

per @randomvariable 's comment in https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1627 . it looks like sometimes we can have CAPI issues which are really 'some subset of cloud providers that do things funny' .  I guess the goal should be for any CAPI issue that we can reproduce it without any specific cloud provider.  The salient things we might see in a cloud provider that we *dont* see naturally in CAPD might be

- latency of networking (simulate this by running `stress` in the background)
- latency of storage (same simulation as above) 
- multiple restarts of compute units during an install (probably easy to delete nodes periodically during a running CAPD test, but havent tried it) 
- large numbers of nodes (this is tricky since most laptops probably cant simulate more then 2 nodes, but theres no reason we couldnt have a c5d.9xlarge or such image to do so in a CI CAPI Stress environment)

**Anything else you would like to add:**

I think having this kind of simuilation environment that is highly localized and reproducible  in place will  save providers lots and lots and lots of time and confusion in the future, and i suspect it could be built in quite short order.

It will also give us a systematic way to file and triage bugs which are 'maybe infra related'.

/kind feature

**Comment by jayunit100** [comment]
possibly relevant to @dlipovetsky 's re-entrancy stuff that i heard about the other day, in terms of integration testing.

**Comment by jayunit100** [comment]
cc @randomvariable @ncdc

**Comment by jayunit100** [comment]
@randomvariable

**Comment by randomvariable** [comment]
Have another scenario to add:
Small MTU

**Comment by jayunit100** [comment]
So I originally filed this aiming to hack on it but... im not really doing much in the CAPI space currently, should we keep this open or close it?  up to you all @vincepri @ncdc .

**Comment by randomvariable** [comment]
Keep it open. Weirdly had remembered about doing this the other day. I may take a look at after getting the kubetest one in.

**Comment by vincepri** [comment]
Closing this given that the issue seems too broad, if there are more specific asks feel free to open different issues. From the backlog grooming, we'd like to have something to accomplish these scenarios, but it needs more actionable items.

/close
