### ISSUE TITLE
RFE: make the DX and E2E test consistent with the new UX based on clusterctl

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#2636]
***Goals***
1. To make the Developer Experience (DX) and E2E test more consistent with the new UX based on clusterctl

***Non-Goals/Future Work***
1.  TBD

**User Story**

- As a user, I'm instructed to use clusterctl
- As a developer, I would like to be guided in testing/validating the same paths the users do during my daily routine (rif local E2E test, CAPD, possibly Tilt)
- As the E2E test operator, I would like to test/validate the same paths the users do during (rif CAPI pull/periodic jobs, providers E2E test based on the test framework) 

**Detailed Description**

The v1alpha3 / v0.3.0 release of Cluster API, introduces a re-designed clusterctl tool with the goal to support a simplified user experience for the end-users.

However, as of today, most of the tools used by Cluster API developers experience & for the Cluster API E2E tests are still based on the “kubectl apply” approach (e.g. Tilt, Cluster API - E2E framework).

The goal of this issue is to agree on a plan of action for making the developer and E2E workflows (DX and E2E) more similar to the end-user workflow (UX), so it will be possible to detect problems earlier in the development cycle.
Nb. the work in https://github.com/kubernetes-sigs/cluster-api/pull/2321 might be a good starting point for this effort

**Contract changes**

TBD changes to the E2E test framework

**Data model changes**

None

/kind proposal

**Comment by vincepri** [comment]
💯 

/milestone v0.3.x

**Comment by fabriziopandini** [comment]
With #2884 merged, e2e workflow are now clusterctl based.

**Comment by vincepri** [comment]
Do we want to close this one out and tackle the development experience separately? It's probably going to be an ongoing task.

**Comment by fabriziopandini** [comment]
Ok
/close
