### ISSUE TITLE
Decouple kubeadm token from machine controllers

### ISSUE THREAD

**Issue by karan** [kubernetes-sigs/cluster-api#265]
Currently, all machine controllers are run with `--token` argument that's produced and provided by the client - https://github.com/kubernetes-sigs/cluster-api/blob/bf2fea154a5a170a2d24919ea40d6ecd5dc0c01f/vsphere-deployer/deploy/deploy.go#L45

Instead of doing that, the controller itself should generate the token. We then decouple the token from the controller during runtime.

Another problem it solves is that by default kubeadm tokens expire after 24 hours. That means that if someone tries to add a new machine to a cluster after 24 hours, it will not work. If the token is generated on-demand during machine creation, we get around that.

/cc @jessicaochen @roberthbailey @kris-nova

**Comment by spew** [comment]
This is complete for gcp-deployer and will be ported into clusterctl soon: 
  https://github.com/kubernetes-sigs/cluster-api/pull/199

**Comment by spew** [comment]
Should we close this issue @karan ?

**Comment by karan** [comment]
We should apply this to vsphere actuator as well before we close this issue. `clusterctl` can't be made to work with vsphere until the token is decoupled in the yaml.

Do you want to work on that?

**Comment by spew** [comment]
We have another open issue here: 
https://github.com/kubernetes-sigs/cluster-api/issues/159 which is similar, I will take this up once clusterctl is ready for more development (waiting for it to stabilize a bit).

**Comment by spew** [comment]
This is now complete
