### ISSUE TITLE
KCP: expose additional LeaderElection configuration as flags

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api#2653]
**Background**

The default leader election configuration options are:
- `LeaseDuration`: 15 seconds
- `RenewDeadline`: 10 seconds
- `RetryPeriod`: 2 seconds

These values are quite small, but reasonable for most controllers. However, when the KCP controller is facilitating an upgrade, there is a legitimate risk that API server connectivity is disrupted (see #2652). On a self-managed cluster, because of these small values, this disruption can result in the controller losing track of its leader election. This causes the controller pod to crash. 

**The Request**

We (as self-managed cluster users) would like to be able to configure these parameters. Flags seem reasonable!

/kind feature
/cc @vincepri @mytunguyen @sethp-nr

**Comment by rudoi** [comment]
just waiting for https://github.com/kubernetes-sigs/cluster-api/pull/2656 and then i'll get going on this

**Comment by trutx** [comment]
I can pick this up if you don't mind

**Comment by rudoi** [comment]
let's try this again!

/assign @trutx
