### ISSUE TITLE
Ability to specify kubeconfig context for clusterctl client library

### ISSUE THREAD

**Issue by vuil** [kubernetes-sigs/cluster-api#2659]
**User Story**

As a user of clusterctl library I would like to flexibility in providing a specific kubeconfig struct or context name to use with the provided kubeconfig file to identify the cluster we are acting on.

**Detailed Description**

There are often use cases where a user may be dealing with other clusters after the management cluster is set up. e.g.

- create mgmt cluster
- create workload cluster with mgmt cluster
- switch context to workload cluster, operate on it
- create another workload cluster

where it is quite conceivable the the current kube context may no longer point to the mgmt cluster. 
we are working on tool using the clusterctl library that will track the context/kubeconfig used for the mgmt cluster but today clusterctl APIs only take a kubeconfig path, and does not give the flexibility to target anything but the cluster pointed to by the current context in said path.

**Anything else you would like to add:**

The suggestion is to allow the caller to provide a context name to use in conjunction with the kubeconfig path provided, or accept a kube  Config object to provide the required flexibility.

/kind feature
/area clusterctl
/cc @fabriziopandini

**Comment by wfernandes** [comment]
I don't mind working on this if this is something that is useful for `clusterctl`.

I can see the feature being used for a few clusterctl commands like `init`,`delete`, and `upgrade`. 
`move` already is taking the _from_ and _to_ kubeconfig.

Open to discussion 🙂

**Comment by fabriziopandini** [comment]
@wfernandes thanks for volunterering! 
The main issue to be addressed before starting this change is to define how to avoid breaking compatibility/how to limit impacts on the client using the library.

My proposal here is:
1. for the main clusterctl API (/cmd/clusterctl/client) to preserve compatibility by adding new methods and deprecating old ones.
2. for the low level clusterctl API (/cmd/clusterctl/client/*) to relax the compatibility constraints and do the changes, but this requires discussion at sig level I think.

@ncdc @vincepri opinions?

**Comment by vincepri** [comment]
As long as it's documented somewhere, +1

**Comment by ncdc** [comment]
Looking at the code, we'd need to adjust (or add a replacement) `ClusterClientFactory`, as that's the thing the primarily creates a client, and it currently only takes in a kubeconfig but no other options. What else (if anything) is there that needs changing?
