### ISSUE TITLE
Quickstart tabs broken in Required Configuration for Common Providers section

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#2671]
/kind documentation
/kind bug
/priority critical-urgent
/milestone v0.3.1

**What steps did you take and what happened:**
In the quick start, if you click on one of the Tabs under the Required Configuration for Common Providers section, it expands and links back to the Initialization for Common Providers section rather than expanding the tab selected.

**What did you expect to happen:**
The correct tag to open

**Comment by wfernandes** [comment]
@detiber When I go to https://cluster-api.sigs.k8s.io/user/quick-start.html#required-configuration-for-common-providers and click on the tabs, they seem to be opening the correct information **which differs** from the Initialization for Common Providers section.

Is this the correct behavior? Are you seeing a different behavior?

**Comment by detiber** [comment]
A PR to fix this was merged earlier today
/close
