### ISSUE TITLE
Support variants of image tags in KCP for kube-proxy, coredns etc...

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#2689]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Setting kcp.spec.version to 1.17.3 results in a kube-proxy daemonset being applied with a "1.17.3" tag.

**What did you expect to happen:**
Tag being "v1.17.3"

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This is currently occuring due to the reconciliation of the kube-proxy daemonset due to upgrades.

There are additional issues when dealing with version numbers that may be semver compliant, e.g. "v1.17.3+build1", but do not contain OCI compatible characters for tags.

Finally, the KCP controller should account for independent build tags for different components, e.g. API server could be at build1, and kube-proxy is at build2.

**Environment:**

- Cluster-api version: 0.3.0
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

/kind bug
/lifecycle active

**Comment by randomvariable** [comment]
> Finally, the KCP controller should account for independent build tags for different components, e.g. API server could be at build1, and kube-proxy is at build2.

No longer a concern. *phew*

**Comment by wfernandes** [comment]
@randomvariable Let me know if you need any help with this issue.

**Comment by ncdc** [comment]
@randomvariable mind striking out the KCP version skew text in the description?
