### ISSUE TITLE
MachineSet implementation for scaling up & down

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#27]
_From @rsdcastro on January 29, 2018 22:27_

Some thoughts/questions:
- Choose a specific instance to remove rather than arbitrary instance
- Does scaling down use any smart logic to pick the node to remove?
- Does scaling down drain nodes by default? (But allow removing machines w/o draining)

_Copied from original issue: kubernetes/kube-deploy#536_

**Comment by rsdcastro** [comment]
_From @roberthbailey on February 7, 2018 6:35_

We should definitely support removing a specific machine from the set. This isn't supported today in replica sets so there isn't precedence in that API (although customers have asked for it) but it is required by the cluster autoscaler. 

Ideally scaling down would choose the best node to remove from the cluster. The cluster autoscaler has code that does this, so it might be possible to reuse that here. For the initial implementation (alpha) we can just pick one randomly. 

I'm of the opinion that scaling down should drain by default but allow a "force delete" which skips draining.

**Comment by k4leung4** [comment]
/assign @p0lyn0mial 
fixed with PR, https://github.com/kubernetes/kube-deploy/commit/4d8e94db3c530816249edc367ba817a6d22e5893
