### ISSUE TITLE
KubeadmControlPlane controller shouldn't rely on annotations to operate

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2702]
The KubeadmControlPlane requires us to set annotations on machines as they go through the upgrade process, however, as actions+labelling a machine isn't an atomic operation there is ample opportunity for a mismatch of annotation and reality as discovered by @rudoi and @sethp-nr. 

KubeadmControlPlane shouldn't be using the labels to assume state. It should always be looking at reality and not interpreted reality. However, the annotations can exist so humans have a way to bypass particular situations that the controller cannot recover from. For example, selecting a machine for deletion. If there is one selected, we'd use it, but otherwise, we'd figure out the best one and use that (without setting any annotation).

cc @vincepri 

/kind bug

**Comment by fabriziopandini** [comment]
Being this the first iteration on KCP. I'm +1 for keeping things simple.
Let's reconsider annotation for humans when the "particular situations that the controller cannot recover from" are spec-ed out, but ideally we should work for avoiding those situations

**Comment by vincepri** [comment]
I'd agree, it seems the simplest thing to do today is to nail the KCP flow and have it work without setting any annotations first. We can revisit the need for annotations in special cases later on

**Comment by detiber** [comment]
+1 for removing annotations, the initial idea was to use the annotations as internal implementation details rather than expecting users to interact with KCP through them. If we remove the need for the annotations, then the original requirement for them no longer exists.

**Comment by vincepri** [comment]
/retitle KubeadmControlPlane controller shouldn't rely on annotations to operate
