### ISSUE TITLE
liche, link checker should be more relaxed

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2703]
Our link checker, https://github.com/raviqqe/liche, should not be checking links we don't control. This is asking to break CI whenever external links change.

However, we really shouldn't have any 404s so when external links change maybe it's good that it fails.

Unfortunately https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/docs/getting-started.md this moved. I think this should link to the repo itself where they would be responsible for making documentation obvious. It's less likely a repo will move than an actual document.

Separately, liche really needs to handle retries. https://github.com/raviqqe/liche/issues/36

/kind bug

**Comment by chuckha** [comment]
now we've hit too many requests. Disabling it for now.

**Comment by benmoss** [comment]
What do we think about using github actions for this as a periodic job? I fear that if we make it a periodic on Prow we will never look at it. We can also just make it optional on PRs, but it's noise there if the link has broken for reasons other than the PR (ie if a server somewhere out on the internet changes)

**Comment by vincepri** [comment]
I'd prefer to keep using prow whenever we can. We can make the job optional and only trigger it when there are documentation changes
