### ISSUE TITLE
KCP: clarify updateStatus comment when setting Initialized

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2709]
In KCP controller the `updateStatus` method is in charge of updating `KubeadmControlPlane.Status` struct after each iteration. This line https://github.com/kubernetes-sigs/cluster-api/blob/5f14f88152342e2bec7b43c904ecb911f8301e4f/controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go#L337 states that the `kcp.Status.Initialized` is only set once, even if the configmap goes away.

Unless I missed something, the `workloadCluster.ClusterStatus` could return false and the value won't be set. It also doesn't take into account that after pivot the status isn't present anymore, a situation that has pivot + delete could prevent the Initialized field to be set, would this be a problem or is `status.initialized` mostly cosmetic?

/kind cleanup

**Comment by detiber** [comment]
Initialized was meant to provide backward compat for setting Cluster.Status.ControlPlaneInitialized, until a later release when we no longer support the old non control plane provider workflow.
