### ISSUE TITLE
Create library for setting common command line flags amongst providers

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api#2710]
**User Story**

As a developer I would like to not have to set flags in every provider because that is tedious and error-prone.

**Detailed Description**

Per discussion on https://github.com/kubernetes-sigs/cluster-api/pull/2664, we should create a library that allows for the easy setting of common command line flags.

/kind feature

**Comment by vincepri** [comment]
Closing in favor of #3427 

/close
