### ISSUE TITLE
A Documentation Bug at vSphere

### ISSUE THREAD

**Issue by billhoph** [kubernetes-sigs/cluster-api#2748]
The Entries starting from vSphere_FOlDER should be = instead of :

<img width="788" alt="Screenshot 2020-03-21 at 9 52 01 PM" src="https://user-images.githubusercontent.com/28106000/77228342-902dc400-6bc1-11ea-83e9-e4a3060c9697.png">

**Comment by SataQiu** [comment]
Thank you for reporting this :+1: @billhoph 
/assign
