### ISSUE TITLE
KubeadmControlPlane v2 iteration and robustness

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2753]
Please see below for plan of action and feel free to ask questions!

/kind cleanup
/area control-plane
/milestone v0.3.x
/priority critical-urgent

**Comment by fabriziopandini** [comment]
xref https://github.com/kubernetes-sigs/cluster-api/issues/2636 because there can be overlaps

**Comment by vincepri** [comment]
v0.3.3:

- @sedefsavas Enable CAPD e2e tests to do multi-control plane and upgrades https://github.com/kubernetes-sigs/cluster-api/blob/master/test/infrastructure/docker/e2e/docker_test.go#L185-L216
- Add more tests to CAPD e2e file
  - @sedefsavas Kube-proxy
  - @gab-satchi CoreDNS
  - @wfernandes Etcd
- @fabriziopandini  Get https://github.com/kubernetes-sigs/cluster-api/pull/2321 merged
- @fabriziopandini  Merge KCP tests #2742

>=v0.3.4:

- Finish up clusterctl e2e framework PR (init, move, delete)
   - Make e2e CI tests use the clusterctl workflow (init, etc)
   - Write up a framework / test pipelines that can work across any infrastructure provider
   - Self managed cluster focused tests
- Unit tests and coverage analysis 
   - @wfernandes @fabriziopandini To run a coverage analysis and see what gaps we have today
- Refactoring
   - Remove annotations and make sure code is re-entrant 
   - Figure out how to add watchers on remote clusters Nodes (xref https://github.com/kubernetes-sigs/cluster-api/issues/2577)
   - Node join remediation / retry (long term)
      - @yastij Add experimental controller that checks if a control plane machine has a node without the label and mark it as failed after a certain amount of time.


Ongoing:
- Code cleanup

**Comment by fabriziopandini** [comment]
WRT to #2321, My proposed plan is to close the current PR and proceed with the following plan
- [ ] Owner: @fabriziopandini Extend current E2E framework for allowing
  - clusterctl based test workflows
  - switch of the infrastructure provider used by E2E tests by changing the config file (portable workflows)
- [ ] Document how to write E2E tests (different approaches)
- [ ] Create a new version of pull-cluster-api-capd-e2e that mimics the quick-start
  - use clusterctl
  - can works with any providers (CAPA and CAPV implementation provided as example)
- [ ] Owner:TBD Replace pull-cluster-api-capd-e2e with ^^. Nb. Only the docker provider will be automatically tested; other providers are E2E variations are provided for supporting development/as a template (or library) to be used by the provider authors for implementing their own E2E tests
- [ ] Owner:TBD Create a new E2E test workflow for PIVOT (based on clusterctl, CAPD, CAPA and CAPV implementations
- [ ] Owner:TBD Create a new E2E test workflow for UPGRADE (tbd if this can be merged in ^^)

@vincepri @sedefsavas @wfernandes @gab-satchi opinions?

**Comment by vincepri** [comment]
+1 from me, let's open different issues if we all agree on the plan

**Comment by vincepri** [comment]
Going to retitle this issue to be tracking the KubeadmControlPlane rewrite

/retitle KubeadmControlPlane v2 iteration and robustness

**Comment by sethp-nr** [comment]
Once there's a more robust test framework in place, I'd like to discuss #2652. As it stands, KCP upgrades are fairly disruptive; as long as the KCP is able to make progress things recover quickly, but there's an opportunity to be more graceful in the common case by using `--shutdown-delay-duration` and imposing a cooling off period between "stopping" the API server (plus some work to make this possible) and removing the etcd member.

**Comment by enxebre** [comment]
This might be relevant to include here:
https://github.com/kubernetes-sigs/cluster-api/issues/2818
https://github.com/kubernetes-sigs/cluster-api/issues/2836

**Comment by randomvariable** [comment]
@vincepri We discussed refactoring the dialler that we send to the etcd client to pass in all of the etcd pods. Still a worthy activity?

**Comment by vincepri** [comment]
Seems @sedefsavas opened https://github.com/kubernetes-sigs/cluster-api/issues/2844

**Comment by sethp-nr** [comment]
One idea I'd like to discuss is changing our current notion of "health check": currently health checks are acting as both safety guards and timing sequencers, and will likely soon be reconciliation hooks (#2841). 

I suspect a more useful model than "is the control plane healthy right now?" would be: "would I transition the control plane closer to or further from a healthy state with this change?"

For example, deleting a control plane machine is likely to put the cluster in a degraded state, unless the etcd membership for that machine has already been removed. In that case, deleting the Machine actually moves the cluster to a less degraded state by (eventually) tearing down the static api server pod that may or may not be accepting traffic it can't handle.

I think there's even more hay to be made around etcd: there are some edges the KCP is currently willing to traverse that it maybe should not, like going from 2 etcd members to 1.

My hope is that such a model would let us rephrase the KCP reconciliation loop as an ordered list of reconciliation steps: first to get back to healthy, then to meet the requested specification. What do other folks think?

**Comment by vincepri** [comment]
> I suspect a more useful model than "is the control plane healthy right now?" would be: "would I transition the control plane closer to or further from a healthy state with this change?"

+1 on making this distinction, we should work out a plan of action on how we want to see this happen. @sedefsavas given that you started thinking about health checks, do you want to put a small proposal in an issue together?

**Comment by benmoss** [comment]
I'd really like to see us break apart break apart the controllers, I think they're really overburdened with responsibility. We have resorted to testing private methods and splitting structs across files, both of which I think are smells and signs that we are struggling with how big the objects and methods of these controllers are.

**Comment by vincepri** [comment]
@benmoss Sounds like a good refactoring we could do for v0.4 after a proposal is written up. I'd like to hear other folks' thoughts as well though. @ncdc @detiber

**Comment by benmoss** [comment]
Yeah I'll write something up when I have a chance

**Comment by fabriziopandini** [comment]
I'm +1 for breaking down the controller in focused reconciliation loops (simular to what we have in other controllers).

https://github.com/kubernetes-sigs/cluster-api/issues/2859 goes in that direction trying to extract a first isolated reconciliation loop.

Also merging the current scale up/scale down logic that exists under ReconcileNormal and under ReconcileUpgrade can greatly contribute to cleanups (upgrade=just another reason to scale up or down, not a separated workflow)

**Comment by ncdc** [comment]
@vincepri 👍

**Comment by detiber** [comment]
+1 to working towards breaking up the controller into more easy to rationalize and test components. I'm happy to see that we are taking the time/effort to clean up and refactor the initial implementation. 

> Also merging the current scale up/scale down logic that exists under ReconcileNormal and under ReconcileUpgrade can greatly contribute to cleanups (upgrade=just another reason to scale up or down, not a separated workflow)

Much of the scale up/scale down logic is already consolidated, the main differences that exist are related to priority of operations (upgrades are prioritized over other scaling events) and determining the set of Machines to operate over (Machine selection in scale down for upgrade looks different than general scale down). If we can do further consolidation while keeping the correct behaviors and grokability of the code, I think that would be great.

**Comment by wfernandes** [comment]
👍 Having the relevant unit/e2e tests should enable us to do this with more confidence.

**Comment by vincepri** [comment]
Folks — Can this tracking issue be closed now? It seems we've checked most of the boxes, we can follow-up with other, more focused, issues if we need.

**Comment by fabriziopandini** [comment]
WRT to tests we are done / finishing last bits (docs, decommission capd_e2e job)
I'm not fully up to date on the refactoring activities

**Comment by vincepri** [comment]
Closing for now, we can file the rest of the issue separately, if any.

/close
