### ISSUE TITLE
improve safety for end-user during control plane deletion

### ISSUE THREAD

**Issue by boluisa** [kubernetes-sigs/cluster-api#2759]
**User Story**

As an operator, I would like to delete control plane nodes in a way that does not leave behind etcd members or in a way that does not require running Kubeadm reset prior to machine deletion.

**Detailed Description**

A delete of a control plane object should remove it corresponding etcd member from the etcd cluster.

/kind feature

**Comment by vincepri** [comment]
The current code in v1alpha3 takes care of this when scaling down https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go#L541-L550, is this what you were asking?

**Comment by boluisa** [comment]
@vincepri  no, not via scaling down. I meant by deleting the control plane object itself. for example: ```kubectl delete machine controlplane-1```

**Comment by detiber** [comment]
One way to achieve this:
- Add a KCP owned finalizer to the Machine when creating or adopting
- Update etcd/kubeadm config entries when deletion of Machine is detected before removing finalizer

**Comment by vincepri** [comment]
/milestone Next

gonna punt to next for now given the pending testing and robustness in KCP #2753

**Comment by vincepri** [comment]
Somewhat related: https://github.com/kubernetes-sigs/cluster-api/issues/2818

**Comment by vincepri** [comment]
Closing this given that we reconcile the etcd membership with what Machines are available (and without a deletion timestamp).

/close
