### ISSUE TITLE
Exposing cluster control plane "knobs"

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#276]
Kubeadm exposes a variety of control plane "knobs" through the [config file](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/).

Take the `apiServerCertSans` knob, for example. If a cluster has multiple masters and keepalived is used to fail over between them, the Virtual IP managed by keepalived must be added to the API Server Cert SANs.

While individual providers can expose these knobs in their own ProviderConfigs, there are probably some knobs that are provider-agnostic. Even if such knobs do not become part of the Cluster API types, defining some conventions on their use in ProviderConfigs might help.

**Comment by dlipovetsky** [comment]
Instead of creating their own API to expose control plane "knobs," providers could use ComponentConfigs.

There is a proposal that will make it easier to use ComponentConfigs:
> Find a home for the ComponentConfig API types, hosted as a staging repo in the “core” repo that is kubernetes/kubernetes
Make ComponentConfig API types consumable from projects outside of kube and from different parts of kube itself

https://docs.google.com/document/d/1-u2y03ufX7FzBDWv9dVI_HyiIQZL8iz3o3vabeOpP5Y/edit?ts=5b3a4e44#

**Comment by dlipovetsky** [comment]
Related discussion from the [Wed 13 June 2018 meeting](https://docs.google.com/document/d/16ils69KImmE94RlmzjWDrkmFZysgB2J4lGnYMRN89WM/edit#heading=h.xil9madvokmo):

> [mvladev] Specifying per Machine kubelet and other component configuration
> Right now it's only possible to specify the dynamic kubelet configuration, not possible to specify on a per-kubelet basis special flags that should be configured
> Don't see it in the api anywhere. It isn't provider specific.
> Can put into the cloud config, but specific for GCE.
> Want to describe "this machine has these flags on the kubelet"; with the machines api cannot do it directly. First have to create the cloud configuration as a config map and reference it.
> Punting on component configuration to next week....

**Comment by ncdc** [comment]
This hopefully will be a feature of a kubeadm-based bootstrap provider. We're still working on a proposal for machine bootstrapping, and we'll also be writing a design doc for a kubeadm bootstrap provider.

**Comment by ncdc** [comment]
Do we want to keep this open and close it when v1alpha2 is released? Or should we close it now, knowing it'll be part of CABPK?

**Comment by detiber** [comment]
I think it should be safe to close it now.
