### ISSUE TITLE
KCP: allow changing of spec.kubeadmConfigSpec.clusterConfiguration.imageRepository

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#2777]
**User Story**

As a user, I would like to be able to change the image registry I'm using for control plane components.

**Detailed Description**

I'd like to be able to modify the following path in KubeadmControlPlane: `spec.kubeadmConfigSpec.clusterConfiguration.imageRepository`. If I decide to use a different registry after I've created a cluster, I'll need to be able to change this field (the webhook validation currently doesn't allow it).

**Anything else you would like to add:**

N/A

/kind feature

**Comment by vincepri** [comment]
Should we use this when upgrading CoreDNS, etcd, and kube-proxy as well?

**Comment by ncdc** [comment]
kubeadm uses this field if the more specific ones aren't set. We shouldn't need to add any logic here.

**Comment by vincepri** [comment]
For etcd that should be the case, but given that we do upgrade `kube-proxy` and `CoreDNS` outside of kubeadm, we should probably account for this in those functions?

Also, could this value change over time?
