### ISSUE TITLE
[KCP] Increase unit test coverage

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#2779]
Following issue https://github.com/kubernetes-sigs/cluster-api/issues/2753, this issue is to track unit-test-coverage increase efforts.
There are several TODO unit tests are added to the test files. 
We should focus on improving the current coverage which is as follows: 

**kubeadm/controllers:**

```
controller.go | 56.2% statements
helpers.go | 63.8% statements
scale.go | 59.2% statements
status.go | 82.8% statements
upgrade.go | 59.5% statements

```

**kubeadm/internal:**
```
etcd | 0% files, 0% statements
cluster.go | 8.6% statements
control_plane.go | 53.8% statements
etcd_client_generator.go | 0% statements
failure_domain.go | 0% statements
kubeadm_config_map.go | 16.9% statements
machine_collection.go | 90.2% statements
workload_cluster.go | 2.8% statements
workload_cluster_coredns.go | 76.8% statements

```

**Comment by sedefsavas** [comment]
cc @wfernandes @fabriziopandini

**Comment by nader-ziada** [comment]
Since this seems like a bit of work, I suggest we split the work by folder so multiple people can work on it

for example, I can start working on some of the internal files without tests while someone else can pick other packages if they want to

**Comment by sedefsavas** [comment]
Good idea @nader-ziada 
I will focus on scale and upgrade tests.

**Comment by wfernandes** [comment]
/assign
@nader-ziada What files are you going to work on specifically?
I was thinking of `workload_cluster*` and moving onto `kubeadm_config_map*`

**Comment by nader-ziada** [comment]
i'll take these
```
etcd | 0% files, 0% statements
cluster.go | 8.6% statements
control_plane.go | 53.8% statements
etcd_client_generator.go | 0% statements
```

**Comment by wfernandes** [comment]
Are there any more areas that require testing in KCP? Should we close this issue?

**Comment by vincepri** [comment]
We can probably close this for now, we're tacking the rest in #2753 

/close
