### ISSUE TITLE
Run CAPD e2e tests in parallel

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#2795]
**User Story**

As a developer I would like to run `make test-capd-e2e` tests in parallel in order to save time.

We keep increasing the `--timeout` option to `go test` as we add more e2e tests. Our CI should be able to run these tests in parallel to save time.

Ref https://github.com/kubernetes-sigs/cluster-api/pull/2785

/kind feature

**Comment by detiber** [comment]
It might be good to take a look at some of the things we've done in the CAPA e2e tests to enable parallelization: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/test/e2e/e2e_suite_test.go

There are quite a few gotchas that are likely to come into play, especially if the current tests are expecting specs to run serially.

**Comment by wfernandes** [comment]
Going to take a peek into this.
/assign

**Comment by vincepri** [comment]
@wfernandes I think this might have been outdated, we're tackling this with the new clusterctl-based e2e tests 

cc @fabriziopandini @sedefsavas

**Comment by wfernandes** [comment]
@vincepri I'm assuming this issue was for the tests in `test/infrastructure/docker/e2e`. But if we are switching to the clusterctl tests in `test/e2e` then do we need the docker tests in the future?

**Comment by wfernandes** [comment]
I'll hold off on this until we understand what needs to be done.
/hold

**Comment by fabriziopandini** [comment]
My opinion is that as soon as test e2e gets functional parity with docker e2e (and we should be really near to that), we won't need docker e2e test anymore.
FYI I have already open ann issue to nuke clusterctl e2e tests for the same reason.

**Comment by vincepri** [comment]
Going to close this out for now given that we're moving away from the older capd e2e tests

/close
