### ISSUE TITLE
Have upgrade functionality (as tool or server side)

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#28]
_From @rsdcastro on January 29, 2018 22:39_

_Copied from original issue: kubernetes/kube-deploy#537_

**Comment by rsdcastro** [comment]
_From @roberthbailey on February 7, 2018 6:36_

Alternatively, implement server side upgrades as part of the MachineDeployment resource type.

**Comment by roberthbailey** [comment]
@k4leung4 - do machine deployments meet the exit criteria of this issue (for nodes)? I think they do, just wanting a second opinion. 

If so, then we should either re-scope this to control plane upgrades or close it and spawn a separate issue for control plane upgrades.
