### ISSUE TITLE
[question] how to pin failureDomain in control plane? 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#2800]
**User Story**

As a [developer/user/operator] I would like to [high level description] for [reasons]

**Detailed Description**

[A clear and concise description of what you want to happen.]

this comes from https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/525
in openstack provider the availiability zone is used for failureDomain in cluster-api now, and from the analysis
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/525#issuecomment-604848047

seems cluster-api need provider provide a set of failureDomains then cluster-api will select best fit one, is this analysis correct? do we have a way to pin the failureDomain to one or more given value ?

I am currently adding a availability zone choice to openstack provider, before make change there want to confirm that is the right way to go.. thanks
**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by vincepri** [comment]
> seems cluster-api need provider provide a set of failureDomains then cluster-api will select best fit one, is this analysis correct?

This is correct, only working in KubeadmControlPlane at the moment.


> how to pin failureDomain in control plane?

What do you mean here? Is this for control plane machines or just any generic machine?

**Comment by jichenjc** [comment]
> > how to pin failureDomain in control plane?
> 
> What do you mean here? Is this for control plane machines or just any generic machine?

the control plane, I find a place to pin worker node ,but didn't find where to pin the failuredomain for the control plane node

**Comment by sbueringer** [comment]
@vincepri Right now the infrastructure provider detects failure domains and then the KubeadmControlplane controller chooses between these failure domains to distribute the control plane machines equally. I think it would be nice if there's any way to restrict or filter the failure domains for a cluster. So that it's possible to decide in which failure domains the control plane is spun up (e.g. to decide if you get a regional or zonal cluster). Right now it's only possible to set the failure domain in the MachineSpec (i.e. for example in a MachineDeployment).

**Comment by vincepri** [comment]
@jichenjc @sbueringer That makes sense, it should be possible to achieve that use case today by restricting the list of failure domain with the `.ControlPlane` boolean to true. The logic or restriction flags can be placed on the ClusterInfrastructure Spec. I can provide an example later today if the concept isn't clear

**Comment by sbueringer** [comment]
@vincepri Ah of course got it. So it would work like this:
* add a field to restrict the failure domains in the infrastructure-provider specific Cluster resources
* set ControlPlane to true (in the infrastructure cluster controller) only on those failure domains which are viable for control plane machines

Okay I guess then the only question is if it's preferred to implement the field to restrict the failuredomains in KubeadmControlPlane or if this should be done in every infrastructure provider who wants to implement this feature.

**Comment by vincepri** [comment]
That's correct. To give some background, during proposal times, it was pointed out that having failure domains restrictions / options on the KCP resource would be a little tricky, given that we don't know how infrastructure providers shape their domains, or which options they want to expose. 

To avoid adding filtering based on a map without type safety or validation, we left it up to the infrastructure providers to decide how and what to offer to their users

**Comment by sbueringer** [comment]
@vincepri Okay sounds reasonable. We just wanted to make sure it's not something which is just missing in the KCP resource. Then we'll just add it to the OpenStackCluster

**Comment by vincepri** [comment]
Sounds good!

Feel free to close when ready.

**Comment by jichenjc** [comment]
so the confirm, set the ControlPlane flag in the provider should be good enough ,correct ?
the provider itself knows which one to be failuredomain and then go ahead and set the flag :)
@vincepri @sbueringer I will close this question, thanks for answering :)

**Comment by sbueringer** [comment]
> so the confirm, set the ControlPlane flag in the provider should be good enough ,correct ?
> the provider itself knows which one to be failuredomain and then go ahead and set the flag :)
> @vincepri @sbueringer I will close this question, thanks for answering :)

No I think you got it wrong. The idea is to filter the AZs for the control plane via a field and then set the ControlPlane bool to true for the failure domain:

```
// FailureDomainSpec is the Schema for Cluster API failure domains.
// It allows controllers to understand how many failure domains a cluster can optionally span across.
type FailureDomainSpec struct {
	// ControlPlane determines if this failure domain is suitable for use by control plane machines.
	// +optional
	ControlPlane bool `json:"controlPlane"`

	// Attributes is a free form map of attributes an infrastructure provider might use or require.
	// +optional
	Attributes map[string]string `json:"attributes,omitempty"`
}
```

But I'll comment in the PR on CAPO what to change
