### ISSUE TITLE
KCP: CoreDNS upgrade with imageRepository containing subpaths doesn't work

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2810]
**What steps did you take and what happened:**
Try to set `dns.imageRepository` to a repository that has a subpath like `foo.io/upgrade`, the upgrade fails with:
```
E0327 22:36:32.212262       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to update CoreDNS deployment: failed to validate CoreDNS: toVersion \"v1.6.5_foo.4\" must be greater than fromVersion \"v1.6.5_foo.4\""  "controller"="kubeadmcontrolplane" "request"={"Namespace":"default","Name":"test-upgrade"}
```

**What did you expect to happen:**
Upgrade to succeed.

/kind bug
/area control-plane
/milestone v0.3.x

**Comment by vincepri** [comment]
See https://play.golang.org/p/McES6F4X5L6 for more details on why this is happening

**Comment by vincepri** [comment]
If having subpaths in the imageRepository is valid, we should either fix it by having some utils to parse images, or if they're not allowed we should have webhooks in place

**Comment by vincepri** [comment]
cc @fabriziopandini @neolit123

**Comment by neolit123** [comment]
is this a bug in the coredns migration library?

**Comment by fabriziopandini** [comment]
fyi this piece of clusterctl is doing image repository and it handles repository sub paths properly
https://github.com/kubernetes-sigs/cluster-api/blob/f07371de19756a95a4a1f09c236ace004261be22/cmd/clusterctl/client/config/imagemeta_client.go#L130-L160
As discussed https://github.com/kubernetes-sigs/cluster-api/pull/2558#discussion_r388986918, this approach provides users the flexibility to organize their own local repository as they wish (with subpaths or not).
Hopefully, the same approach can be used as a base for the utils Vince is suggesting.
