### ISSUE TITLE
Fold in Weaveworks helmchart for capi-components

### ISSUE THREAD

**Issue by casibbald** [kubernetes-sigs/cluster-api#2811]
***Goals***
1. Include capi-components helm chart into upstream, update build tools to autogenerate the chart.

***Non-Goals/Future Work***
fully generate the helm repo automatically with CI

**User Story**

As a developer, I would like to deploy CAPI-Components using helm to simplify the management of my CAPI infrastructure.

**Detailed Description**

I want to be able to autogenerate a helm chart using the base manifests.
Only helm packaging included.

**Contract changes [optional]**

NA

**Data model changes [optional]**

NA

/kind proposal

**Comment by vincepri** [comment]
I put a hold on the related PR, we can discuss it at the next community meeting if this is something that we want to do and support as a community

**Comment by elmiko** [comment]
this came up during the weekly meeting today, and there were several opinions expressed that any change like this would require maintenance and possibly some form of automated generation.

i just wanted to chime in here and echo those opinions, i think we before we add more configuration/manifests beyond the basic template and yaml files we currently have there would need to be a plan in place for the maintenance and lifecycle around changes to the core manifests.

**Comment by ncdc** [comment]
+1, thanks for the summary @elmiko. Additionally, we have logic in `clusterctl` that handles installations in the proper order, and upgrades in the proper order. We want users to use `clusterctl` (either CLI, or as a go library) for these tasks, and we don't currently have the desire to maintain any other approaches.

If you're interested in maintaining Helm charts for this, that's fantastic, but our ask is that you maintain them in the helm/charts repo, or some other repo.

**Comment by vincepri** [comment]
Closing this per our discussion in our meeting today

/close

**Comment by tuunit** [comment]
> helm/charts

Hi @ncdc @vincepri @sbueringer,

is this still the current stance on this topic? A helm chart for the generic CRDs like `Cluster`, `KubeadmConfigTemplate`, `KubeadmControlPlane` etc. and installing the cluster operator and webhook controller would be highly valuable for a lot of people. This would allow setting up `cluster-api` with a full declarative approach using Flux or Argo.

Basically I would imagine having a Helm chart for the base of `cluster-api` in this upstream repo. On top of that, provider developers could provide their own helm charts with the specific implementations.

I would be willing to open a PR for a generic Helm chart. If you deem it as a desired alternative approach for installing `cluster-api` now.

**Comment by ncdc** [comment]
Hi @tuunit, I don't work on cluster-api any more. Just wanted to let you know.
