### ISSUE TITLE
Unable to connect to API of workload cluster

### ISSUE THREAD

**Issue by JohnOnTheWeb** [kubernetes-sigs/cluster-api#2815]
**What steps did you take and what happened:**
Followed quickstart to create docker infrastructure in KIND / Docker environment

**What did you expect to happen:**
Be able to connect to API with kubectl

**Anything else you would like to add:**
Created workload cluster with following command
clusterctl --target-namespace test1 --config /home/john/.cluster-api/clusterctl.yaml config cluster test | kubectl apply -f-

Cluster,DockerCluster,dockermachine,machine all seem to have been created
![image](https://user-images.githubusercontent.com/5436671/77871515-0063c780-720a-11ea-9b06-57e508f2226a.png)

kind nodes appear to be running
![image](https://user-images.githubusercontent.com/5436671/77871601-40c34580-720a-11ea-8da1-59172236822b.png)

downloaded kubeconfig secret and set kubectl path variable
all Kubectl commands timeout
the kubeconfig secret seems to point to https://172.17.0.3:6443 but docker does not report it is exposing this port so I am confused.

**Environment:**

Windows 10, WSL2 Ubuntu 18.04
latest of below...left jubernetes at 1.17
- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by fabriziopandini** [comment]
I'm not a windows user, but this seems really similar to the problem user are facing on macOS https://github.com/kubernetes-sigs/cluster-api/issues/1685

The workaround so far is to change the API server address in the kubeconfig file to 127.0.0.1:[load balancer host port] (in your example 41307)

**Comment by fabriziopandini** [comment]
/close 
given lack of updates
feel free to re-open if the problem still exists
