### ISSUE TITLE
Control Plane Provider should reconcile by removing etcd member for voluntary machine disruptions e.g deletion

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#2818]
**What steps did you take and what happened:**
Delete a control plane machine.
It causes the Control Plane Provider health checks to fail and reconciliation to stop.

**What did you expect to happen:**
When something deletes a Machine the Control Plane Provider reconciles by removing the corresponding etcd member and updating related metadata.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by vincepri** [comment]
/milestone v0.3.x
/priority important-soon

@fabriziopandini @sedefsavas any of you wants to pick this one up? It'd be great to have support for this use case in the next version

**Comment by sedefsavas** [comment]
I can take this one.
/assign
