### ISSUE TITLE
Make clusterctl cert-manager timeout configurable

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#2822]
**User Story**

As a developer using the clusterctl library, I would like to be able to specify a custom timeout for waiting for cert-manager to be available, as the default hard-coded 10 minute value might not be enough if my internet connection is slow.

As a user using clusterctl, I would like to be able to specify a custom timeout for waiting for cert-manager to be available, as the default hard-coded 10 minute value might not be enough if my internet connection is slow.

**Detailed Description**

See user story

**Anything else you would like to add:**

N/A

/kind feature

**Comment by vincepri** [comment]
@fabriziopandini How do we set other timeouts today? Environment variables, flags?

**Comment by ncdc** [comment]
MVP for me is library-only for an API consumer. Bonus is a flag or env var.

**Comment by fabriziopandini** [comment]
The simplest implementation will be using envvars, like e.g we are doing for the overrideFolder.
Library only requires an interface change, soI highly raccomand to tackle this with https://github.com/kubernetes-sigs/cluster-api/pull/2597 and https://github.com/kubernetes-sigs/cluster-api/issues/2659

**Comment by nader-ziada** [comment]
@fabriziopandini I was trying to implement this by adding a flag to the init command, do you think that is better or doing a env var?

**Comment by ncdc** [comment]
Ok, env var is fine for now 😄
