### ISSUE TITLE
NPE in MachineDeployment controller when spec.Strategy is Empty

### ISSUE THREAD

**Issue by DheerajSShetty** [kubernetes-sigs/cluster-api#2825]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Tried to machinedeployment cluster without webhooks, i.e without capi-webhook-system namespace and its components. I used the machinedeployment that is part of each release which does not have `MachineDeploymentStrategy` set.

**What did you expect to happen:**
Since `MachineDeploymentStrategy` member is mentioned optional, I expected the MachineDeployment creation to succeed. But there was a NPE at 
https://github.com/kubernetes-sigs/cluster-api/blob/3288e3e5ecee56ae7bf6007f55a4e1138fe1f3cc/controllers/machinedeployment_controller.go#L189

From my discussion with Cluster-api team, I gather that we need to run webhooks or else there might be unforeseen issues. But it would be better if there is no NPE, and a warning instead.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Crash Log

> I0328 04:51:52.238391       1 reflector.go:185] Listing and watching controlplane.cluster.x-k8s.io/v1alpha3, Kind=KubeadmControlPlane from pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105
I0328 04:51:52.335551       1 tracker.go:54] controllers/Machine "msg"="Adding watcher on external object" "machine"="trial3-control-plane-k6m52" "namespace"="namespace1" "GroupVersionKind"="infrastructure.cluster.x-k8s.io/v1alpha3, Kind=AWSMachine"
I0328 04:51:52.335637       1 controller.go:138] controller-runtime/controller "msg"="Starting EventSource"  "controller"="machine" "source"={"Type":{"apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha3","kind":"AWSMachine"}}
I0328 04:51:52.336030       1 controller.go:282] controller-runtime/controller "msg"="Successfully Reconciled"  "controller"="machine" "request"={"Namespace":"namespace1","Name":"trial3-control-plane-k6m52"}
E0328 04:51:52.336156       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 410 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1536040, 0x24ca6a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1536040, 0x24ca6a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
sigs.k8s.io/cluster-api/controllers.(*MachineDeploymentReconciler).reconcile(0xc000458900, 0x192ad40, 0xc000076078, 0xc000439b00, 0xc000180580, 0x0, 0x0, 0x6, 0xc000439b00)
	/workspace/controllers/machinedeployment_controller.go:181 +0x6c6
sigs.k8s.io/cluster-api/controllers.(*MachineDeploymentReconciler).Reconcile(0xc000458900, 0xc0006a1270, 0xa, 0xc0006a1250, 0xb, 0xc000517c00, 0x0, 0x0, 0x0)
	/workspace/controllers/machinedeployment_controller.go:125 +0x4f3
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001ce540, 0x15873c0, 0xc000643920, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.1/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001ce540, 0x114f700)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.1/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0001ce540)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.1/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00011e460)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00011e460, 0x3b9aca00, 0x0, 0xc000118101, 0xc000044540)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00011e460, 0x3b9aca00, 0xc000044540)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.1/pkg/internal/controller/controller.go:193 +0x328

**Environment:**

- Cluster-api version: v0.3.2
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): Client version v1.15.5, server version v1.17.3
- OS (e.g. from `/etc/os-release`): 

/kind bug

**Comment by vincepri** [comment]
This is expected behavior. The webhook code is treated as integral part of the Cluster API core, and it's a required dependency. 

Currently, the defaulting happens here https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha3/machinedeployment_webhook.go#L130-L136

**Comment by DheerajSShetty** [comment]
I agree. Can we handle the NPE and log warning instead?

**Comment by vincepri** [comment]
We could, but that defeats the purpose of having webhooks imo. We should assume that webhooks are part of the same code paths, and guards/checks should be elsewhere.

**Comment by DheerajSShetty** [comment]
We can close this issue .
