### ISSUE TITLE
Clustertctl should validate kubernetes version is >= v1.16.0

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#2837]
**What steps did you take and what happened:**
xref https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1676

Clustertctl fails if the management cluster is <= v1.16.0

Followed the Quickstart in the docs line by line exactly and I got this error when running:
clusterctl init --infrastructure aws

> Error: action failed after 10 attempts: failed to create clusterctl inventory CRDs component: apiextensions.k8s.io/v1, Kind=CustomResourceDefinition, /providers.clusterctl.cluster.x-k8s.io: n
o matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1

**What did you expect to happen:**
Clustertctl should validate that the management cluster is >= v1.16.0 or provide a meaningful error message to the users

**Anything else you would like to add:**
As a first thought, this check can be implemented as a part of the "EnsureCustomResourceDefinitions", which is the first method called in most of the clusterctl commands and the first requiring v1.16.0 features

**Environment:**

Cluster-api-provider-aws version:
> clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.3",  GitCommit:"ecff70af1b839c4086335234d88b1b8c00c3383c", GitTreeState:"clean", BuildDate:"2020-03-27T22:25:55Z", GoVe
rsion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}

Kubernetes version: (use kubectl version):
> Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersi
on:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:
54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

OS (e.g. from /etc/os-release):
> MacOS Catalina 10.15.4

/kind bug
/area clusterctl

**Comment by prksu** [comment]
i'll take this one
/assign
