### ISSUE TITLE
kind helpers setup error when using kind v0.7.0

### ISSUE THREAD

**Issue by prksu** [kubernetes-sigs/cluster-api#2840]
**User Story**

As a developer, I would like to use kind v0.7.0 for run e2e-test

**Detailed Description**

In `test/helpers/kind.Setup()` we run `kind get kubeconfig-path` which already removed in v0.7.0 and caused an error. 

https://github.com/kubernetes-sigs/cluster-api/blob/09f87a2aadcd590952e17684f5c05259337e4da9/test/helpers/kind/setup.go#L64

We need to migrate the behavior so it can also support in v0.7.0

**Anything else you would like to add:**

https://github.com/kubernetes-sigs/kind/issues/1060 there is a guide for migrating this 

/kind feature
/area testing

**Comment by vincepri** [comment]
/assign @detiber 

Can we write a deprecation notice or remove this from the codebase in the next path release?

**Comment by prksu** [comment]
I don't think we need to write deprecation notice since it doesn't affect any user/dev experience, it will still work in versions below v0.7.0

**Comment by vincepri** [comment]
@prksu `test/helpers` should have been effectively deprecated when v1alpha3 was released, but we didn't add any notice and this was an oversight. This package has been replaced by the `test/framework` that came out of this proposal https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20191016-e2e-test-framework.md.

**Comment by fabriziopandini** [comment]
@gab-satchi FYI, we are planning to deprecate test/helpers in CAPI as soon as CAPA stops to use methods in this package

**Comment by fabriziopandini** [comment]
/remove-lifecycle stale

The cleanup is not yet completed

**Comment by vincepri** [comment]
Closing, we've moved to v0.8 for v1alpha3 and v0.9 for v1alpha4

/close
