### ISSUE TITLE
Provide a library to work with container images

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2850]
We should have a package under `util/` to deal with container images, more specifically:

- We can copy this function from k/k https://github.com/kubernetes/kubernetes/blob/master/pkg/util/parsers/parsers.go#L36-L59 to add basic validation.
- Our parsing function will have to do some extra parsing to split the name of the repository (last part after splitting by `/`) and the base repository.
- Create a struct similar to
```go
type Image struct {
   Repository
   Name
   Tag
   Digest
}
```

As an example, let's take the string `"k8s.gcr.io/dev/coredns:1.6.2"`, when parsed it should return
```go
Image{
  Repository: "k8s.gcr.io/dev"
  Name: "coredns"
  Tag: "1.6.2"
  Digest: ""
}
```

/kind feature
/milestone v0.3.x

**Comment by vincepri** [comment]
cc @gab-satchi @randomvariable

**Comment by nader-ziada** [comment]
I can work on this one

/assign
