### ISSUE TITLE
kubectl diff for CAPI objects

### ISSUE THREAD

**Issue by sethp-nr** [kubernetes-sigs/cluster-api#2851]
**User Story**

As a user or operator, I would like to use `kubectl diff` to understand what object changes will result when I run an apply.

**Anything else you would like to add:**

Currently the biggest issue is that our webhooks are not configured to permit dry run:

```
Error from server (BadRequest): admission webhook "default.kubeadmcontrolplane.controlplane.cluster.x-k8s.io" does not support dry run
```

This worked in the v1alpha2 timeframe, but maybe that was so because we didn't have webhooks then?

/kind feature
/assign
/lifecycle active

**Comment by vincepri** [comment]
Good find!

/milestone v0.3.4
