### ISSUE TITLE
Add Status or Conditions metadata to MachineHealthChecks

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api#2863]
**User Story**

As a Administrator I'd like to be able to confirm my MHC's were targetted at all clusters that needed and properly labelled, without needing to test them "for real" (which obviously is a dangerous test to run - as it involves deleting compute units).

**Detailed Description**

Per https://github.com/kubernetes-sigs/cluster-api/issues/2861, It would be good to easily see the Status of a MHC, for example, what machines it applied to.  I'd almost go so far as to say there should be a clear indicator if it dient' apply to any machines also.

**Anything else you would like to add:**

/kind feature

**Comment by vincepri** [comment]
cc @fabriziopandini

**Comment by JoelSpeed** [comment]
@jayunit100 Just reading this and trying to understand the request here

If my understanding is correct you would like to see for example a list in the status that contains the Machine names that the MHC is targeting? 
```
targetMachines:
- machine-1
- machine-2
```

> without needing to test them "for real" 

I wasn't sure here whether you just meant deleting a Machine as a test or whether you expect there to be some sort of dry run mode for the MHC?

> I'd almost go so far as to say there should be a clear indicator if it dient' apply to any machines also.

I think listing the Machines targeted would be clearer than the ones not targeted. There may be cases where users want to apply many MHCs with varying conditions targeting different groups of nodes, seeing which Machines are targeted in this scenario would likely be a smaller list. I also think being more explicit about which Machines are matched is probably easier to reason about, eg "Is machine-1 being targeted, yeah it's in the list" seems more natural than "no it's not missing from the list", if that makes sense?

**Comment by gab-satchi** [comment]
> I'd almost go so far as to say there should be a clear indicator if it dient' apply to any machines also.

I read this as "If the MHC doesn't target any machines, there should be some type of feedback since it likely means the MHC was misconfigured". I ran into this while testing MHC where I had a typo in my label and that caused 0 targets for the MHC. Describing the MHC wasn't helpful as the Status was showing empty values for Target, Healthy/Unhealthy instead of 0 (separate issue) 

/assign
/lifecycle active

**Comment by gab-satchi** [comment]
Hadn't thought of that usecase. Given it's feasible to target 0 machines, I think seeing either a 0 for Target or an empty list of targets is sufficient. There's no need to raise a warning for 0 machines.
