### ISSUE TITLE
[clusterctl] Add unit tests for InitImages method

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#2871]
Currently, we do not have any unit tests for [`InitImages`](https://github.com/kubernetes-sigs/cluster-api/blob/51138ad376d42552524527c10d7d02d530e93291/cmd/clusterctl/client/init.go#L99) in [`init_test.go`](https://github.com/kubernetes-sigs/cluster-api/blob/51138ad376d42552524527c10d7d02d530e93291/cmd/clusterctl/client/init_test.go)

There is a basic test being added in PR https://github.com/kubernetes-sigs/cluster-api/pull/2856 but we need the other cases to be fleshed out. 
See https://github.com/kubernetes-sigs/cluster-api/pull/2856/files#diff-f516e05fd6c3975f176daa8f8fa37c8eR31

/good-first-issue
/area clusterctl

**Comment by ericzhang08** [comment]
Could I have a look for this issue?
/assign

**Comment by vincepri** [comment]
Go for it @ericzhang08.

/milestone v0.3.4

**Comment by wfernandes** [comment]
Adding this for context.
I've added another test for `InitImages` as part of PR: https://github.com/kubernetes-sigs/cluster-api/pull/3059

I still believe we can add more test cases as part of this issue/PR. For example, 
- `returns images for cert-manager`
- `returns images for the default providers`

**Comment by wfernandes** [comment]
@ericzhang08 Are you still working on this? Else I can fill in a few more tests as part of the PR mentioned above.

**Comment by ericzhang08** [comment]
@wfernandes Have you already add all tests? If not, I will add others this week.

**Comment by wfernandes** [comment]
@ericzhang08 I don't believe I have added all the test cases. So far I've been adding test cases that are specific to the use cases I run into when I need to touch that part of the code. 
I've been avoiding adding all the test cases as technically they do not pertain to the issue that I'm working on. So go for it 🙂

**Comment by joaopapereira** [comment]
@ericzhang08 I do not mind to give it a try if you do not have time.
If so you can assign it to me.

**Comment by wfernandes** [comment]
@joaopapereira Feel free to assign it to yourself with `/assign` and mark it as `/lifecycle active` to indicate that you are working on it. Thanks!
