### ISSUE TITLE
CAPD Error running clusterctl init to transform ephemeral cluster to Management Cluster

### ISSUE THREAD

**Issue by sb1975** [kubernetes-sigs/cluster-api#2872]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

clusterctl init --core cluster-api:v0.3.0 --bootstrap kubeadm:v0.3.0 --control-plane kubeadm:v0.3.0 --                                                                      infrastructure docker:v0.3.0
Fetching providers
Error: failed to get provider components for the "docker:v0.3.0" provider: failed to get repository client for the InfrastructureProvider                                                                       with name docker: error creating the local filesystem repository client: failed to get latest version: failed to get local repository ve                                                                      rsions: failed to list release directories: open /home/ubuntu/.cluster-api/overrides/infrastructure-docker: no such file or directory

**What did you expect to happen:**
$ clusterctl init --core cluster-api:v0.3.0 --bootstrap kubeadm:v0.3.0 --control-plane kubeadm:v0.3.0 --                                                                      infrastructure docker:v0.3.0
Fetching providers
Installing cert-manager
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v0.3.0" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v0.3.0" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v0.3.0" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-docker" Version="v0.3.0" TargetNamespace="capd-system"

Your management cluster has been initialized successfully!

You can now create your first workload cluster by running the following:

  clusterctl config cluster [name] --kubernetes-version [version] | kubectl apply -f -

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Problem was fixed by following below steps :
cp cmd/clusterctl/test/testdata/docker/v0.3.0/cluster-template.yaml ~/.cluster-api/overrides/infrastructure-docker/v0.3.0/
cat > ~/.cluster-api/clusterctl.yaml <<EOF
providers:
- name: docker
url: /home/ubuntu/.cluster-api/overrides/infrastructure-docker/latest/infrastructure-components.yaml
type: InfrastructureProvider
EOF

It might be helpful if the code is updated with $HOME instead of hard coded /home/ubuntu.

Thanks to Alexander Hughes for perfect steps.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`): ubuntu 18.04

/kind bug

**Comment by elmiko** [comment]
i think this issue needs to be addressed through our capd documentation.

**Comment by elmiko** [comment]
this is in our docs https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/clusterctl/developers.md

**Comment by vincepri** [comment]
@sb1975 given @elmiko's point above, do you think we can go ahead and close this issue?

**Comment by sb1975** [comment]
I was able to do it following the steps given by
