### ISSUE TITLE
test-capd-e2e fails occasionally with same error

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#2889]
**What steps did you take and what happened:**
cluster-api-capd-e2e test sometimes fails for PRs (and it occasionally fails in Prow job too) with the following error:
```
  [91mTimed out after 600.001s.
  Error: Unexpected non-nil/non-zero extra argument at index 1:
  	<*errors.errorString>: &errors.errorString{s:"old nodes remain"}[0m
```

**What did you expect to happen:**
I expected it to be less flakey.

**Anything else you would like to add:**
This issue is most likely hits the 10 min timeout interval.

/kind bug
/area testing

**Comment by vincepri** [comment]
@sedefsavas should we close this given the work we're doing on e2e and the increased timeout?

**Comment by sedefsavas** [comment]
Yes, closing.
