### ISSUE TITLE
KubeadmControlPlane is not deploying the correct number of Replicas

### ISSUE THREAD

**Issue by jseely** [kubernetes-sigs/cluster-api#2890]
**Summary:**
kubeadm join on the second control plane succeeded, both control plane `Machines` are in `Running` state, but no 3rd `Machine` was created, even though the KCP replica desired count is 3. `kubectl get nodes` shows only one of the control planes (the second one that did the join).

**What steps did you take and what happened:**

- Checked out both `cluster-api` and `cluster-api-provider` to `v0.3.3` and `v0.4.1` respectively.
- Created a local deployment of the management components via `kind create cluster && tilt up`. (Tilt config included `"enable_providers": ["azure", "docker", "kubeadm-bootstrap", "kubeadm-control-plane"],`)
- Apply cluster template: [jseely-capz.yaml](https://gist.githubusercontent.com/jseely/d58dd3c89cbbb8c6e9e89e90fcba5928/raw/b762dc0f9130de90ab4820b11c34dea265c2cd92/jseely-capz.yaml)

**What did you expect to happen:**

Expected result: 3 Control Plane and 3 worker nodes are provisioned in Azure
Actual result: 2 Control Plane and 3 worker nodes are provisioned in Azure

Both Control Plane nodes have active kube-apiservers but they both only see themselves as part of the cluster (`kubectl get nodes` on each node only returns itself). (Possible split-brain)

```
justin @ archon ➜  cluster-api-tools  k get KubeadmControlPlane        
NAME                        READY   INITIALIZED   REPLICAS   READY REPLICAS   UPDATED REPLICAS   UNAVAILABLE REPLICAS
jseely-capz-control-plane   true    true          2          1                2                  1
justin @ archon ➜  cluster-api-tools  k get Machines
NAME                                PROVIDERID                                                                                                                                                             PHASE
jseely-capz-control-plane-hjvzx     azure://///subscriptions/13743e75-5e4f-44fc-877c-296bcb5185d5/resourceGroups/jseely-capz/providers/Microsoft.Compute/virtualMachines/jseely-capz-control-plane-pp5kg   Running
jseely-capz-control-plane-lxxmm     azure://///subscriptions/13743e75-5e4f-44fc-877c-296bcb5185d5/resourceGroups/jseely-capz/providers/Microsoft.Compute/virtualMachines/jseely-capz-control-plane-qhf8k   Running
jseely-capz-md-0-654d878fc4-5hmng   azure://///subscriptions/13743e75-5e4f-44fc-877c-296bcb5185d5/resourceGroups/jseely-capz/providers/Microsoft.Compute/virtualMachines/jseely-capz-md-0-zjrq8            Provisioning
jseely-capz-md-0-654d878fc4-csmqs   azure://///subscriptions/13743e75-5e4f-44fc-877c-296bcb5185d5/resourceGroups/jseely-capz/providers/Microsoft.Compute/virtualMachines/jseely-capz-md-0-4m6nr            Running
jseely-capz-md-0-654d878fc4-ncbtg   azure://///subscriptions/13743e75-5e4f-44fc-877c-296bcb5185d5/resourceGroups/jseely-capz/providers/Microsoft.Compute/virtualMachines/jseely-capz-md-0-rfq4x            Running
justin @ archon ➜  cluster-api-tools  k get AzureMachines
NAME                              AGE
jseely-capz-control-plane-pp5kg   119m
jseely-capz-control-plane-qhf8k   121m
jseely-capz-md-0-4m6nr            123m
jseely-capz-md-0-rfq4x            123m
jseely-capz-md-0-zjrq8            123m
```

Cloud init files from both Control Plane Nodes: [Gist](https://gist.github.com/jseely/8c86db2cdd02dc3e76589b825623674b)

**Environment:**

- Cluster-api version: v0.3.3 (CAPZ version: v0.4.1)
- Minikube/KIND version: kind v0.7.0 go1.14.1 linux/amd64
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

/kind bug

**Comment by vincepri** [comment]
cc @CecileRobertMichon 

We'll probably need to look at the KCP controller logs as well

**Comment by CecileRobertMichon** [comment]
For context, @jseely and I discussed at length on Slack: https://kubernetes.slack.com/archives/CEX9HENG7/p1586471169049800

**Comment by vincepri** [comment]
@CecileRobertMichon Can this issue be closed? Do we have any action items here?

**Comment by CecileRobertMichon** [comment]
Not sure, @jseely did you end up fixing the issue on your end?
