### ISSUE TITLE
e2e upgrade tests should exercise failure domains

### ISSUE THREAD

**Issue by benmoss** [kubernetes-sigs/cluster-api#2895]
The CAPD e2e upgrade test that was added doesn't exercise failure domain logic. It's been the source of a lot of bugs too, so it's important that we have coverage. Whether or not this means we should have two tests, one FD and one non, I'm not sure about. 

/kind bug
/area testing

**Comment by vincepri** [comment]
Please add/track this in https://docs.google.com/spreadsheets/d/1uB3DyacOLctRjbI6ov7mVoRb6PnM4ktTABxBygt5sKI/edit#gid=0 as a sub-test
