### ISSUE TITLE
[KCP] Get etcd client using all nodes in ReconcileEtcdMembers

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#2896]
ReconcileEtcdMembers() logic can be simplified by connection a health etcd member automatically by using all nodes as endpoint during getting etcd client.

This improvement can be done after https://github.com/kubernetes-sigs/cluster-api/pull/2888 is merged.

/area control-plane

**Comment by sedefsavas** [comment]
cc @benmoss

**Comment by vincepri** [comment]
/kind cleanup
/assign @gab-satchi @sedefsavas 
To sync up offline and re-triage this

**Comment by vincepri** [comment]
Going to close this for now, the KCP rework for etcd has mostly happened, and this change doesn't seem necessary at this point

/close
