### ISSUE TITLE
Tool to recover if the master is bricked

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#29]
_From @rsdcastro on January 29, 2018 22:45_

In case metadata can't be accessed/reconstructed, this tool would allow the cluster to be restored with the cluster API components.

Related to https://github.com/kubernetes/kube-deploy/issues/532

_Copied from original issue: kubernetes/kube-deploy#538_

**Comment by rsdcastro** [comment]
_From @roberthbailey on February 7, 2018 6:45_

This sounds like a disaster recovery tool, so there is possibly some overlap with https://github.com/heptio/ark

**Comment by timothysc** [comment]
out of scope.
