### ISSUE TITLE
Broader release process of clusterctl

### ISSUE THREAD

**Issue by kris-nova** [kubernetes-sigs/cluster-api#290]
@pwittrock @roberthbailey @krousey @rsdcastro @craigtracey @karan @timothysc 

Looping in a few folks who might have opinions here.

Today on the sig call we had a short discussion about a broader release pattern for the `clusterctl` tooling. _More information on `clusterctl` can be found [here](https://github.com/kubernetes-sigs/cluster-api/tree/master/clusterctl)_

The two arguments being discussed:

### 1) Follow the broader Kubernetes 3 months release cycle

This creates a sense of more "official" tooling, and gives the user confidence they are running the most updated version of the tool.

This also is a slower release cycle, and introduces problems with timing (we aren't ready for a release, etc)

### 2) Follow an independent release cycle and offer our own binaries/images

Somehow we build out a build system, and independently manage our own releases.

This allows a more frequent release cycle, and gives us flexibility with our releases

### 3) Hybrid approach 

We have our own independent build cycle, and every 3 months we just update the Kubernetes release with our most recent stable release.

Commence bikeshedding.

**Comment by karan** [comment]
More info on the short-term manual plan will be in #256

**Comment by pwittrock** [comment]
FWIW both kubebuilder and kustomize release independently and on-demand through pushing a tag to the git repo.  This then triggers a build of the artifacts and publishes them to GitHub as a new release tar.gz.  It also builds containers and pushes them to gcr.io.

This is pretty simple to do and we could help you with it if need be.

**Comment by timothysc** [comment]
FWIW I think we should hook into test automation to get signal, and try to match, or lag, cadence with upstream.  

Currently there is no CI signal for the different incantations and backends for clusterAPI + tooling, and getting that signal will be important for knowing when it's ok to cut a release.

**Comment by karan** [comment]
The beautiful feature of clusterctl is that it's independent of the K8s version. The components that are installed are independent of the tool; `create cluster` installs a package, the contents of which are easily configurable (the machine setup config map. That in part allows us to not be tied to any specific k8s version and follow our own release process. We can patch and release as often as necessary, not any more and not any less.

**Comment by ncdc** [comment]
We will be creating a PR with a proposed release cadence for the project shortly. I'll make sure it's tagged to close this on merge.
