### ISSUE TITLE
Allow existing k8s clusters to join a management cluster

### ISSUE THREAD

**Issue by sherifkayad** [kubernetes-sigs/cluster-api#2914]
**User Story**

As an Operations Team Member I would like to use the cluster API provider implementation to let existing k8s clusters pre cluster API to join my management cluster in order for me to be able to use the cluster API spec not only for new clusters but also for existing clusters in my organization.

**Detailed Description**

It's explicitly mentioned in the non goals that one of the cluster API non-goals is:

> To manage non-Cluster API provisioned Kubernetes-conformant clusters.

However, in real life, operations teams would love to use the cluster API not only to manage the lifecycle of new clusters but also existing k8s clusters pre the introduction of the cluster API in their life.

I personally have a project that's requiring a bunch of k8s clusters and now we see that we will need a bunch of clusters more in the near future and that's why we are searching for the best way to manage those clusters in a way that can make the life of our ops teams much easier.

/kind feature

**Comment by vincepri** [comment]
Thank you for bringing this up @sherifkayad, we discussed this during the April 22nd community meeting, in general consensus is that adoption is out of scope for this project. That said, we want to help efforts outside Cluster API by making adoption possible, but not supported.

From the [meeting notes](https://docs.google.com/document/d/1fQNlqsDkvEggWFi51GVxOglL2P1Bvo2JhZlMhm2d-Co/edit#heading=h.f01iryv94gfi):
> Discussion on support for adopting an existing cluster into cluster-api, vs leaving that as an unsupported but allowed process and then possibly documenting/supporting a migration path

Going to close this issue for now, please feel free to reach out if you have any other questions or if we can help in any way.

/close

**Comment by kfox1111** [comment]
While in general I don't think adopting every existing k8s cluster is a good idea, what about kubeadm deployed clusters? a process to adopt them would be good I think.
