### ISSUE TITLE
UI dashboard for visualizing cluster-api managed clusters

### ISSUE THREAD

**Issue by sherifkayad** [kubernetes-sigs/cluster-api#2916]
**User Story**

As a user of the cluster API, I would like to be able to see the managed clusters and some basic metrics about them in a friendly UI in order for me to get an easy visualization about my managed clusters.

**Detailed Description**

Similar to the approaches of most of the k8s cluster management solutions (e.g. Rancher / Gardener / .. etc.), I think having a friendly UI dashboard with the following is a great feature:
- Which clusters are managed by the cluster API / which provider
- Some basic metrics / gauges (similar to the Rancher Dashboard)
- The ability to perform some actions 

/kind feature

**Comment by davidewatson** [comment]
The group may or may not have developers with the rights skills and interests, but this would be great for user experience one day.

**Comment by vincepri** [comment]
@johnharris85 is going to demo a plugin for [Octant](https://github.com/vmware-tanzu/octant) either next week or the week after

**Comment by sherifkayad** [comment]
@vincepri @johnharris85 sounds great! .. could you please post a link for the demo video here in this issue?

**Comment by bboreham** [comment]
[Weave Scope](https://github.com/weaveworks/scope/) is another possible starting-point - I don't know if anyone has done a ClusterAPI plugin for it yet, but maybe having the link here will encourage someone.

**Comment by vincepri** [comment]
Super supportive of having efforts to provide user interfaces, and we should definitely follow-up with some documentation on how to use and setup such tools. In general, for this repository we don't think it falls under our current responsibilities.

Should we close this one out and follow-up with some PRs to the book when UI tools are ready to be used?

**Comment by sherifkayad** [comment]
@vincepri I definitely agree that the responsibility of this repo would be to document the tools / reference how to integrate them in its book.

In the meantime, maybe it's fine to leave that issue here open until those PRs get merged / until the first tool emerges.

What do you think?

**Comment by fabriziopandini** [comment]
might be an issue in the octant/weave scope repositories can reach the right audience for carrying on this task...

**Comment by lyveng** [comment]
> @johnharris85 is going to demo a plugin for [Octant](https://github.com/vmware-tanzu/octant) either next week or the week after

@vincepri / @johnharris85 Is this the github issue vmware-tanzu/octant#600 tracking the cluster api plugin work for octant? Did the demo happen? I'd love to try it out if you need some beta testers.

**Comment by vincepri** [comment]
@lyveng The demo hasn't happened yet, we're kind of stalled in this area, but it'd be great to circle back once we have more time / plan for the next cycle.

**Comment by vincepri** [comment]
Closing in favor of #3802 

/close
