### ISSUE TITLE
Add some code coverage analysis as part of prow PR feedback

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#2918]
**User Story**

As a developer I would like to have some code coverage feedback from prow when I submit PRs to CAPI.

**Detailed Description**
This is important to developers submitting PRs to analyze how many tests are being introduced into the code base and/or removed and the quality of the tests as well.
This will also enable reviewers to assist in improving the test code base as well. 
This is important for the long-term reliability of the project and the overall confidence.

**Anything else you would like to add:**

This issue was created as part of the action item raised by @benmoss during the [April 15 CAPI Meeting](https://docs.google.com/document/d/1fQNlqsDkvEggWFi51GVxOglL2P1Bvo2JhZlMhm2d-Co/edit#heading=h.he83twhnfcx2)

Some other notes:
- [Istio bot nagging on tests](https://github.com/istio/istio/pull/22965#issuecomment-614161208) 🙂 
- https://github.com/kubernetes/test-infra/blob/master/robots/coverage/docs/design.md

/kind feature
/area testing
/cc @vincepri @benmoss

**Comment by benmoss** [comment]
/unassign

maybe someone with more familiarity on the prow ecosystem can do this

**Comment by sbueringer** [comment]
We could also integrate the overall coverage (not the diff introduced through the PR) in the Prow job view.
But I'm not sure how useful it is. If we produce coverage files with our go tests we could have a view like this in Prow basically for free:
![coverage](https://user-images.githubusercontent.com/4662360/117708054-a3d62880-b1cf-11eb-923e-2c3d4b054222.png)
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-coverage-unit/1391811481351229440
