### ISSUE TITLE
Remove cmd/clusterctl/test

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#2930]
With #2884 clusterctl is now tested by the CAPI e2e tests, so it is possible to remove e2e tests `under cmd/clusterctl/test`

/kind cleanup
/area clusterctl
/help
/good-first-issue

**Comment by prankul88** [comment]
@fabriziopandini Is it safe to remove whole /cmd/clusterctl/test folder

**Comment by fabriziopandini** [comment]
@prankul88 yes
