### ISSUE TITLE
Remove deprecated DeleteNodeAnnotation

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#2944]
We've marked `DeleteNodeAnnotation` for deprecation as part of this PR https://github.com/kubernetes-sigs/cluster-api/pull/2929.

This issue is to track its removal.

/kind cleanup
/milestone v0.4.0

**Comment by detiber** [comment]
@elmiko this will have implications for the cluster autoscaler integration

**Comment by elmiko** [comment]
thanks for the heads up @detiber, it certainly will!

**Comment by elmiko** [comment]
i think this is still active, maybe someone can correct me if that's not the case.
/remove-lifecycle stale

**Comment by detiber** [comment]
Indeed, this is still applicable
/lifecycle frozen

**Comment by furkatgofurov7** [comment]
@vincepri this seems a duplication of #3954 and there was #3955 to fix it. However, we might need to backport it to release-0.3, and I can take care of it if needed.

**Comment by fabriziopandini** [comment]
AFAIK removal of deprecated features should not be backported

**Comment by furkatgofurov7** [comment]
@fabriziopandini in that case, this can be closed as it is a duplication, IMO.
