### ISSUE TITLE
clusterctl init returns config file not found error in clean environment

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#2947]
**What steps did you take and what happened:**
1. In your environment, ensure that you do not have `$HOME/.cluster-api/clusterctl*`. This is the default path location that clusterctl looks at for its config.
1. Run `clusterctl init`

See the following error:
```
Error: failed to initialize the configuration reader: Config File "clusterctl" Not Found in "[/Users/wfernandes/.cluster-api]"
```

**What did you expect to happen:**
Expected `clusterctl init` to succeed without having to create an empty `$HOME/.cluster-api/clusterctl.yaml` for example.

**Anything else you would like to add:**
This is important for user experience.
This is where we need to fix it. 
Suggestion: Perhaps check if the `path` is empty and if the error is `viper.ConfigFileNotFoundError`, then ignore it.

https://github.com/kubernetes-sigs/cluster-api/blob/ba3bd5c095e0c7af6d39ff62a6bd77b8609722fe/cmd/clusterctl/client/config/reader_viper.go#L64-L68

**Environment:**

- Cluster-api version: Current master. At the time ba3bd5c095e0c7af6d39ff62a6bd77b8609722fe

/kind bug
/help
/good-first-issue
/area clusterctl

**Comment by fabriziopandini** [comment]
Ok for me to test if we are using default clusterctl file (path is empty)
However we should preserve also the behaviour introduce by https://github.com/kubernetes-sigs/cluster-api/pull/2899 (error if a config file is specified but it doesn't exist)

**Comment by fabriziopandini** [comment]
A possible alternative is to revert 2899 and and a test for checking file exists in case EOF path != ""
This probably is cleaner and more explicit than using ReadInConfig to check file existance
@wfernandes opinions?
