### ISSUE TITLE
listDescendants should also fetch machinepools

### ISSUE THREAD

**Issue by devigned** [kubernetes-sigs/cluster-api#2952]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

When deleting a cluster, machinepools are not deleted. This is due to [`listDescendants` not collecting machinepools](https://github.com/kubernetes-sigs/cluster-api/blob/99a95aaa59492924b04e6dddbea17992fecca24d/controllers/cluster_controller.go#L361-L392).

**What did you expect to happen:**
MachinePools to be deleted when a cluster is deleted.

**Environment:**

- Cluster-api version: master

/kind bug

**Comment by CecileRobertMichon** [comment]
@prankul88 are you still working on this?

**Comment by prankul88** [comment]
@CecileRobertMichon Sorry for the delay. Will be trying for a fix in a couple of days.
