### ISSUE TITLE
Improvements in Developers Guide

### ISSUE THREAD

**Issue by prankul88** [kubernetes-sigs/cluster-api#2956]
**What steps did you take and what happened:**
Going through the [developers guide](https://cluster-api.sigs.k8s.io/developer/guide.html), I noticed a few things that were missing. 

1. [Edit Manifests](https://cluster-api.sigs.k8s.io/developer/guide.html#edit-the-manifests) section does not tell the file where the image name needs to change. (for capd).
2. The management cluster requires `cert-manager` as a pre-requisite (now handled by clusterctl), which is not mentioned in the developer guide.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.3
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind documentation

**Comment by vincepri** [comment]
/milestone Next

Happy to put it in v0.3 milestone if someone can pick this up

**Comment by prankul88** [comment]
If no one is taking this up, I can assign it to me. Will push the patch today.
