### ISSUE TITLE
Define config var for clusterctl log level

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#2957]
**User Story**

As a [developer/operator] I would like to see the higher verbosity logs from clusterctl by setting the log level in a config file or environment variable.

**Detailed Description**
Currently as a developer/operator if we want more log output from clusterctl we have to add the flag `-v<int>`. This is great but I have to keep remembering to add that flag for all my clusterctl commands. I was wondering if it would be useful to add an environment variable or a config variable support like `CLUSTERCTL_LOG_LEVEL` which would take an integer. This way, I can just set that value and see the higher log output all the time.

**Anything else you would like to add:**
Just to note with the current implementation, if this var is set, doing a `clusterctl config cluster test -i aws` for example, would print out the logs along with the cluster yaml and hence won't be able to directly `kubectl apply`.

Just wanted to see if this is worth adding to clusterctl!

/kind feature
/area clusterctl

**Comment by fabriziopandini** [comment]
WRT to having a variable for setting log levels I don't have strong preference
WRT to commands that generate yaml output, I think we should output logs on stderr for  (AFAIK this is how kebectl does); probably this should be a separated issue

**Comment by wfernandes** [comment]
@fabriziopandini Yes I agree. I was going to open a separate issue for the logs to be printed onto stderr but got distracted 😄 I'll do that now.

**Comment by wfernandes** [comment]
https://github.com/kubernetes-sigs/cluster-api/issues/2963 is the issue as discussed above.

**Comment by jodavis-suse** [comment]
I took a quick look at this, but wasn't clear if klog would allow outputing to anything that wasn't stdout easily.  I also found klog or logr are used in different parts of the cluster-api code, which may make it difficult to implement.
So I'm curious to see if @cpanato comes to the same conclusion.

**Comment by cpanato** [comment]
@jodavis-suse I did some testing and using the klog I saw the output in the terminal without any problems

**Comment by jodavis-suse** [comment]
Yes, `-v` options do work for controlling the verbosity of output, but I think the request was about separating out the output.  (rereading) Ah, there are two things being asked for
 - control of the log level through a config variable, not just from the `-v` command line option
 - split of the debug output from stdout, which is mentioned here but captured in #2963 

Sorry for combining the two in my comment.  I'll take a look at your commit. :)
