### ISSUE TITLE
clusterctl log output should be printed to stderr

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#2963]
**What steps did you take and what happened:**
When I print out higher verbosity logs from clusterctl for example `clusterctl config cluster -v5 test -i aws`, it prints out the logs and output to stdout. So piping the output such as `clusterctl config cluster -v5 test -i aws | kubectl apply -f -` doesn't work.

**What did you expect to happen:**
I'd expect the logs to be printed out to stderr which is a more ubiquitous behavior I believe.

/kind bug
/area clusterctl
/help

**Comment by fabriziopandini** [comment]
The same should apply to cluster config provider -o yaml

**Comment by jodavis-suse** [comment]
Easy one liner to intentionally break and create both debug and error log output (by using clusterctl without a provider):
`clusterctl config cluster failcluster -v 5 1>stdout.txt 2>stderr.txt`

**Comment by wfernandes** [comment]
I just tested this on the current clusterctl cli and it seems to work. 
```
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.7-alpha.0.38-303f4923517c42-dirty", GitCommit:"303f4923517c42a0fad9d40935eafcc151e0f288", GitTreeState:"dirty", BuildDate:"2020-06-24T17:55:51Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
```
It seems that this got fixed as part of PR https://github.com/kubernetes-sigs/cluster-api/pull/3124


/close
