### ISSUE TITLE
[CAPBK] [KCP] [clusterctl] Support moving custom certs 

### ISSUE THREAD

**Issue by Arvinderpal** [kubernetes-sigs/cluster-api#2964]
**User Story**

As a user/operator I would like my custom certificates to be moved by clusterctl during a move operation. 

**Detailed Description**

Currently, when a clusterctl move is performed, only _generated_ certificates are moved from the source to the target cluster. This is due to the fact that current code skips over custom certs. Only generated certs are assigned OwnerReferences which are subsequently used by clusterctl during the move process:
https://github.com/kubernetes-sigs/cluster-api/blob/29dd8f3aa9b5a6b367df35b7e460f693f9e582d4/util/secret/certificates.go#L238-L244

It is left as an exercise to the user to actually move the custom certificates from the source to target cluster. The user can hack together some scripts to do this, but that's not ideal. Instead, capbk/kcp can be enhanced to also take ownership of the custom certs much like they do with generated certs. 

One approach is to create a flag for capbk/kcp `take-ownership-of-cert-secret` which defaults to false (to preserve current behavior) but if enabled, will Update the OwnerReference on the Secret to that of capbk/kcp. 

/kind feature

@intlabs

Related issue: https://github.com/kubernetes-sigs/cluster-api/issues/1642

**Comment by Arvinderpal** [comment]
Also, I'd be more than happy to submit a small PR that implements this.

**Comment by fabriziopandini** [comment]
Clusterctl is designed to move also certificates without owenrref. This is called soft ownership and assumes the user provided certificates follow the same naming convention used for certificates https://github.com/kubernetes-sigs/cluster-api/blob/18ce96a31a4a7102848effecd05c3753003e092c/cmd/clusterctl/client/cluster/objectgraph.go#L333

**Comment by Arvinderpal** [comment]
@fabriziopandini thanks for the pointer to the soft ownership. 
One issue that we faced (and possibly others will too) is that the code currently uses `-` as the delimiter; however if you our cluster name contains `-`, the code will not function (e.g. `workload-cluster`):
https://github.com/kubernetes-sigs/cluster-api/blob/18ce96a31a4a7102848effecd05c3753003e092c/cmd/clusterctl/client/cluster/objectgraph.go#L343

Imposing a requirement on cluster naming is probably too restrictive. But perhaps on `certificate-name/kubeconfig` we can. That is, we use the very last occurrence of `-` as the separator and document that  `certificate-name/kubeconfig` should not contain `-` if soft ownership is desired. 
Example: `my-workload-cluster-sa`

**Comment by fabriziopandini** [comment]
Thanks for clarifying the problem
I think this can be fixed by checking that the name ends with one of the well known suffix (kubeconfig + certificates)
/assign
/lifecycle active
