### ISSUE TITLE
GCP Provider: Automatically add firewall rule (if necessary)

### ISSUE THREAD

**Issue by spew** [kubernetes-sigs/cluster-api#297]
When communicating with a cluster there needs to be a firewall rule created that enables this communication. Previously this was a manual step documented in the gcp-deployer documentation. This should be done automatically somehow so that users don't need to know about this.

**Comment by spew** [comment]
The manual command was:
```
gcloud compute firewall-rules create cluster-api-open --allow=TCP:443 --source-ranges=0.0.0.0/0 --target-tags='https-server'
```

**Comment by karan** [comment]
I don't know if many folks would be comfortable with opening all in-bound traffic. So maybe this could be a pre-requisite rather than an automated step (as much as I hate doing things manually, opening up FW rules is pretty sensitive).

**Comment by roberthbailey** [comment]
This issue was moved to kubernetes-sigs/cluster-api-provider-gcp#36
