### ISSUE TITLE
Failed to create bootstrap data secret for KubeadmConfig

### ISSUE THREAD

**Issue by abhinavnagaraj** [kubernetes-sigs/cluster-api#2970]
What steps did you take and what happened
Launched a 3 masters/3 workers HA cluster in vSphere.
Updated the kubernetes version on this cluster by modifying  KCP, MachineDeployment and VSphereMachineTemplate. This triggered the rolling upgrade.

Error in the boostrap controller logs
kubectl logs -f  capi-kubeadm-bootstrap-controller-manager-5bb9bfdc46-ch5rg -n capi-kubeadm-bootstrap-system manager

> I0427 22:18:32.935314       1 kubeadmconfig_controller.go:416] controllers/KubeadmConfig "msg"="Creating BootstrapData for the worker node" "kind"="Machine" "kubeadmconfig"={"Namespace":"default","Name":"capi-quickstart-md-0-2vhvp"} "name"="capi-quickstart-md-0-b94d4dc9d-5z5rj" "version"="1269" 
I0427 22:18:32.935991       1 kubeadmconfig_controller.go:485] controllers/KubeadmConfig "msg"="Creating BootstrapData for the join control plane" "kind"="Machine" "kubeadmconfig"={"Namespace":"default","Name":"capi-quickstart-6mtfj"} "name"="capi-quickstart-kwnlm" "version"="4559" 
I0427 22:18:32.976280       1 control_plane_init_mutex.go:105] init-locker "msg"="Checking for lock" "cluster-name"="capi-quickstart" "configmap-name"="capi-quickstart-lock" "namespace"="default" 
I0427 22:18:32.976358       1 control_plane_init_mutex.go:112] init-locker "msg"="Control plane init lock not found, it may have been released already" "cluster-name"="capi-quickstart" "configmap-name"="capi-quickstart-lock" "namespace"="default" 
I0427 22:18:32.977906       1 kubeadmconfig_controller.go:416] controllers/KubeadmConfig "msg"="Creating BootstrapData for the worker node" "kind"="Machine" "kubeadmconfig"={"Namespace":"default","Name":"capi-quickstart-md-0-2vhvp"} "name"="capi-quickstart-md-0-b94d4dc9d-5z5rj" "version"="1269" 
E0427 22:18:32.986979       1 kubeadmconfig_controller.go:441] controllers/KubeadmConfig "msg"="failed to store bootstrap data" "error"="failed to create bootstrap data secret for KubeadmConfig default/capi-quickstart-md-0-2vhvp: secrets \"capi-quickstart-md-0-2vhvp\" already exists" "kind"="Machine" "kubeadmconfig"={"Namespace":"default","Name":"capi-quickstart-md-0-2vhvp"} "name"="capi-quickstart-md-0-b94d4dc9d-5z5rj" "version"="1269" 
E0427 22:18:32.987143       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create bootstrap data secret for KubeadmConfig default/capi-quickstart-md-0-2vhvp: secrets \"capi-quickstart-md-0-2vhvp\" already exists"  "controller"="kubeadmconfig" "request"={"Namespace":"default","Name":"capi-quickstart-md-0-2vhvp"}

What did you expect to happen:
Expected the kubeadmconfig controller to skip creation of boostrap data secret if it already exists. 

Environment:

- Cluster-api version: v0.3.3
- KIND version: v0.6.0
- Kubernetes version: 1.16.7
- OS: CentOS 7

/kind bug

**Comment by vincepri** [comment]
/priority awaiting-more-evidence

The strange part about this issue is that the call to create the bootstrap data secret should only ever made once, if it gets in there twice we might be missing a check — definitely requires a little bit more investigation
