### ISSUE TITLE
[question] do we support external cloud provider ?

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#2977]
**User Story**
This comes from 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/489

openstack used to have intree cloud provider and now it's targeting to move to external and
some projects like https://github.com/kubernetes/cloud-provider-openstack will be used,

so the question is do we need to consider this into 
1) a general cluster-api consideration
2) an addon to cluster-api
3) need each cluster api provider consider it? 

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by detiber** [comment]
@jichenjc There should be nothing preventing the use of the in-tree cloud provider that I'm aware of. I know https://github.com/kubernetes-sigs/cluster-api-provider-vsphere makes use of it and cluster-api-provider-azure recently added support as well: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/456

**Comment by ncdc** [comment]
@detiber I assume you meant out-of-tree 😄

**Comment by detiber** [comment]
doh, yes, edited the comment to fix :joy:

**Comment by jichenjc** [comment]
@detiber thanks a lot :) yes, I mean out of tree provider
so it's provider's responsibility to create those and not in cluster-api scope :)

thanks ~

@sbueringer FYI

**Comment by sbueringer** [comment]
So in Azure it seems to be just another flavor and a document describing how to deploy the CCM: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/527/files

Seems reasonable

**Comment by jichenjc** [comment]
yes, so this is something we can replicate into ours
not something in cluster-api scope, instead, do it in provider..
