### ISSUE TITLE
Error running clusterctl init in v0.3.4

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#2982]
**What steps did you take and what happened:**
as per https://kubernetes.slack.com/archives/C8TSNPY4T/p1588162142132000?thread_ts=1588162135.131900&cid=C8TSNPY4T

got
> Error: failed to get provider components for the "vsphere" provider: failed to perform variable substitution: value for variables [VSPHERE_PASSWORD, VSPHERE_USERNAME] is not set. Please set the value using os environment variables or the clusterctl config file

when running clusterctl init with 0.3.4

**Environment:**

- Cluster-api version: 0.3.4

/kind bug

**Comment by elmiko** [comment]
i ran into this as well with the "docker" provider. similar error message for me.
