### ISSUE TITLE
MachineSet controller deletion requests don't need to run in a WaitGroup

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2989]
The MachineSet controller currently uses a WaitGroup when it scales down: https://github.com/kubernetes-sigs/cluster-api/blob/59a696e07b5e4620ba66ce17cd35d2d0b0ae73d0/controllers/machineset_controller.go#L377-L393

This was added around v1alpha1 timeframe because Delete at that time was blocking. Today, these Delete calls can be done sequentially because they return right away and don't have to wait for the delete to finish.

/kind cleanup
/milestone v0.3.x
/priority backlog
/help

**Comment by akhil-rane** [comment]
@vincepri Can I take this up?

**Comment by vincepri** [comment]
go for it @akhil-rane !
