### ISSUE TITLE
Says AWS_B64ENCODED_CREDENTIALS is not set

### ISSUE THREAD

**Issue by kferrone** [kubernetes-sigs/cluster-api#2990]
**What steps did you take and what happened:**
Followed [quick start](https://cluster-api.sigs.k8s.io/user/quick-start.html) exactly. 
Got to the step below:
```
export AWS_B64ENCODED_CREDENTIALS=$(clusterawsadm alpha bootstrap encode-aws-credentials)
```
then ran the following:
```
clusterctl init --infrastructure aws
```
Got this error

> Error: failed to get provider components for the "aws" provider: failed to perform variable substitution: value for variables [AWS_B64ENCODED_CREDENTIALS] is not set. Please set the value using os environment variables or the clusterctl config file

Next I created the cluster config file with correct info. Still got the error?

**What did you expect to happen:**
Init to work . . . 

**Environment:**

- Cluster-api version:
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.4", GitCommit:"7cda00b20b09cdccf2ce4e5e952ecfdc0f87ccd5", GitTreeState:"clean", BuildDate:"2020-04-28T23:14:45Z", GoVersion:"go1.13
.8", Compiler:"gc", Platform:"darwin/amd64"}

- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12
", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersio
n:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):
Mac OS
/kind bug

**Comment by vincepri** [comment]
Without posting the output, was the `AWS_B64ENCODED_CREDENTIALS` actually set to some value, or was it empty?

/cc @wfernandes

**Comment by kferrone** [comment]
@vincepri 
I ran `echo $AWS_B64ENCODED_CREDENTIALS | base64 --decode`
It is an AWS profile with access key, secret, region, and a name called default for the profile. Just like the one in `$HOME/.aws`

Like this:
```
[default]
aws_access_key_id = ...
aws_secret_access_key = ...
region = us-west-2
```

**Comment by fabriziopandini** [comment]
This error was fixed by https://github.com/kubernetes-sigs/cluster-api/pull/2983
Please upgrade to v0.3.5; possible workaround to pass the --config flag
/close
