### ISSUE TITLE
Switch RWMutex's to sync.Map in remote cluster caches

### ISSUE THREAD

**Issue by JoelSpeed** [kubernetes-sigs/cluster-api#2991]
**User Story**

This will improve the readability and maintainability of the remote cluster caching code

**Detailed Description**

The remote cluster caching code introduced in #2880 includes two maps that are accessed currently by grabbing a lock from two RWMutexs. These could be replaced by a [sync.Map](https://golang.org/pkg/sync/#Map) (or wrapper around it) that would then reduce this complexity within our code

(Originally suggested by @vincepri)

/kind feature

**Comment by vincepri** [comment]
/priority backlog

I'm fine keeping what we have today, this is more of a possible cleanup suggestion

**Comment by vincepri** [comment]
I think we can actually close this, reading the code again and discussing it more with @ncdc on Slack, I don't think sync.Map is useful in this case

/close
