### ISSUE TITLE
Set User Agent and Request Timeout for Remote Cluster Caches

### ISSUE THREAD

**Issue by JoelSpeed** [kubernetes-sigs/cluster-api#2993]
**User Story**

We should set a user agent on the clients used by the remote cluster caches introduced in #2880 so that request logs can be tracked back to the cluster caches.

We should also set a Timeout on the requests so that failed connections time out rather than hanging

(Originally suggested by @fabriziopandini and @ncdc)

/kind feature

**Comment by nader-ziada** [comment]
I think I need a little bit more context, can't find any previous conversations about this, is it just adding the user agent and timeout to the remote cluster client?

**Comment by fabriziopandini** [comment]
Yes, it is just that.
The user agent can be helpful when auditing API server calls
The timeout helps to avoid being blocked (by default the client waits forever)
