### ISSUE TITLE
Machine deletion should complete when kubelet is not responding

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#2998]
**What steps did you take and what happened:**
_disclaimer: not 100% sure this is a real bug or an error in my test strategy_ 

While testing MHC I created a cluster with CAPD, then in order to simulate a problem, I stopped the  kubelet service on a node.

MHC remediation was triggered and a new machine created, but the existing machine was not deleted due to 

```
machine_controller.go:390] controllers/Machine “msg”=“Drain failed” “error”│
=“error when waiting for pod \“coredns-6955765f44-lwlhv\” terminating: global timeout reached: 20s” “clus│
ter”=“demo” “machine”=“demo-md-0-b5b9dd448-qscgb” “namespace”=“default” “node”=“demo-demo-md-0-b5b9dd448-│
qscgb” 
```

Now, it is fine that the drain operation failed because kubelet is not responding; so to get the machine deleted I restarted kubelet, but what if kubelet can't be restarted?

**What did you expect to happen:**
The machine controller to be able to handle machine deletion when kubelet is not running, possible after retrying the drain operation a finite number of times/for a limited time frame.

**Environment:**

- Cluster-api version: v0.3.5

/kind bug
/area machine

**Comment by ncdc** [comment]
@fabriziopandini I think https://github.com/kubernetes-sigs/cluster-api/blob/0bb5cbfc9e846ade5e327a5810cbb0c1b120824a/controllers/machine_controller.go#L377-L380 covers your scenario?

**Comment by fabriziopandini** [comment]
@ncdc thanks for pointing this out. Let me quickly re-check before closing
