### ISSUE TITLE
Documentation of CABPK Additional Features

### ISSUE THREAD

**Issue by l4z41** [kubernetes-sigs/cluster-api#3000]
**Detailed Description**

Found the `KubeadmConfig` object for additional features from CABPK very useful as I was experimenting with CAPI and CAPV but they aren't well documented and just some examples for often occuring use cases could be super helpful as I found myself quick in source code, slack and existing issues.

Examples needed for:
- `KubeadmConfig.Files` specifies additional files to be created on the machine
- `KubeadmConfig.PreKubeadmCommands` specifies a list of commands to be executed before kubeadm init/join
- `KubeadmConfig.PostKubeadmCommands` same as above, but after kubeadm init/join
- `KubeadmConfig.Users` specifies a list of users to be created on the machine
- `KubeadmConfig.NTP` specifies NTP settings for the machine

**Anything else you would like to add:**

Examples for custom certs, proxy settings, containerd settings for registry mirror and NTP could be helpful here as a simple example like this is not mentioned anywhere.
```
spec:
  template:
    spec:
      ntp:
        servers:
          - IP_ADDRESS
        enabled: true
```

/kind documentation

**Comment by vincepri** [comment]
/milestone v0.3.10

If the PR goes in v0.3.9, that's fine although want to remove this as a release blocker

**Comment by ncdc** [comment]
@CecileRobertMichon are you still interested in working on this?

**Comment by CecileRobertMichon** [comment]
Yes sorry I completely forgot about this, I can work on it today or Monday
