### ISSUE TITLE
Flaky test: e2e tests timing out

### ISSUE THREAD

**Issue by benmoss** [kubernetes-sigs/cluster-api#3009]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/2975/pull-cluster-api-capd-e2e/1257736277134938115

Not sure which part is taking more time than usual, it would be really nice if we had timestamps of everything being logged.

/kind bug
/area testing

**Comment by fabriziopandini** [comment]
@benmoss test infra is having a bad time lately
We are observing a general increase on timeouts also on all the kubeam jobs. 

However, In this case, I would prefer to push for removing  `pull-cluster-api-capd-e2e` as soon as possible instead of investigating flakes
@vincepri opinions?

**Comment by vincepri** [comment]
After the MachineDeployment tests are in the new e2e job, we can remove the old one

**Comment by CecileRobertMichon** [comment]
/close

old capd e2e test will be removed in favor the new infra e2e tests.
