### ISSUE TITLE
issue with provisioning worker cluster (dial tcp 172.17.0.2:6443: i/o timeout)

### ISSUE THREAD

**Issue by ginobiliwang** [kubernetes-sigs/cluster-api#3013]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
I am installing clusterApi using kind, follow steps on this link(it is almost the same with quickstart tutorial).
https://notes.elmiko.dev/2020/04/17/exploring-cluster-api.html

After all the steps, the "controlplane-0" and "worker-0" never go to running state.

`[root@sdw1 v0.3.0]# kubectl --kubeconfig work-cluster.kubeconfig get nodes
NAME                          STATUS   ROLES    AGE     VERSION
work-cluster-controlplane-0   Ready    master   6m29s   v1.17.2
`
`
[root@sdw1 v0.3.0]# kubectl --kubeconfig work-cluster.kubeconfig get nodes
NAME                          STATUS   ROLES    AGE   VERSION
work-cluster-controlplane-0   Ready    master   13m   v1.17.2
`

`
[root@sdw1 v0.3.0]# kubectl get machines
NAME             PROVIDERID                               PHASE
controlplane-0   docker:////work-cluster-controlplane-0   Provisioning
worker-0                                                  Pending`

`
[root@sdw1 v0.3.0]# kubectl get pods -n capi-system
NAME                                       READY   STATUS    RESTARTS   AGE
capi-controller-manager-6d7b58b889-rw6s4   2/2     Running   0          18m` 

The log message from infrastructure provider shows message as below.

`E0506 02:52:56.234289       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create client for Cluster default/work-cluster: Get https://172.17.0.2:6443/api?timeout=32s: dial tcp 172.17.0.2:6443: i/o timeout"  "controller"="machine" "request"={"Namespace":"default","Name":"controlplane-0"}
I0506 02:53:02.615820       1 machine_controller_noderef.go:53] controllers/Machine "msg"="Machine doesn't have a valid ProviderID yet" "cluster"="work-cluster" "machine"="worker-0" "namespace"="default"`

`E0506 02:53:02.615883       1 machine_controller.go:226] controllers/Machine "msg"="Reconciliation for Machine asked to requeue" "error"="Bootstrap provider for Machine \"worker-0\" in namespace \"default\" is not ready, requeuing: requeue in 30s" "cluster"="work-cluster" "machine"="worker-0" "namespace"="default"
I0506 02:53:12.009865       1 machine_controller_noderef.go:53] controllers/Machine "msg"="Machine doesn't have a valid ProviderID yet" "cluster"="work-cluster" "machine"="worker-0" "namespace"="default"`

`E0506 02:53:12.009929       1 machine_controller.go:226] controllers/Machine "msg"="Reconciliation for Machine asked to requeue" "error"="Bootstrap provider for Machine \"worker-0\" in namespace \"default\" is not ready, requeuing: requeue in 30s" "cluster"="work-cluster" "machine"="worker-0" "namespace"="default"
E0506 02:53:32.617682       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create client for Cluster default/work-cluster: Get https://172.17.0.2:6443/api?timeout=32s: dial tcp 172.17.0.2:6443: i/o timeout"  "controller"="machine" "request"={"Namespace":"default","Name":"controlplane-0"}
I0506 02:53:42.014170       1 machine_controller_noderef.go:53] controllers/Machine "msg"="Machine doesn't have a valid ProviderID yet" "cluster"="work-cluster" "machine"="worker-0" "namespace"="default"`

`E0506 02:53:42.014228       1 machine_controller.go:226] controllers/Machine "msg"="Reconciliation for Machine asked to requeue" "error"="Bootstrap provider for Machine \"worker-0\" in namespace \"default\" is not ready, requeuing: requeue in 30s" "cluster"="work-cluster" "machine"="worker-0" "namespace"="default"`

`I0506 02:54:12.020773       1 machine_controller_noderef.go:53] controllers/Machine "msg"="Machine doesn't have a valid ProviderID yet" "cluster"="work-cluster" "machine"="worker-0" "namespace"="default"`

**What did you expect to happen:**
worker cluster successfully provisioned.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.0
- Minikube/KIND version: 0.8.0
- Kubernetes version: (use `kubectl version`):
[root@sdw1 v0.3.0]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`):

[root@sdw1 v0.3.0]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

[root@sdw1 v0.3.0]# docker --version
Docker version 19.03.2, build 6a30dfc

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by ginobiliwang** [comment]
`[root@sdw1 v0.3.0]# kubectl get machine
NAME             PROVIDERID                               PHASE
controlplane-0   docker:////work-cluster-controlplane-0   Provisioning
worker-0                                                  Pending
[root@sdw1 v0.3.0]#
[root@sdw1 v0.3.0]#
[root@sdw1 v0.3.0]# kubectl describe machine controlplane-0
Name:         controlplane-0
Namespace:    default
Labels:       cluster.x-k8s.io/cluster-name=work-cluster
              cluster.x-k8s.io/control-plane=true
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"cluster.x-k8s.io/v1alpha3","kind":"Machine","metadata":{"annotations":{},"labels":{"cluster.x-k8s.io/cluster-name":"work-cl...
API Version:  cluster.x-k8s.io/v1alpha3
Kind:         Machine
Metadata:
  Creation Timestamp:  2020-05-06T01:58:41Z
  Finalizers:
    machine.cluster.x-k8s.io
  Generation:  3
  Managed Fields:
    API Version:  cluster.x-k8s.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:cluster.x-k8s.io/cluster-name:
          f:cluster.x-k8s.io/control-plane:
      f:spec:
        .:
        f:bootstrap:
          .:
          f:configRef:
            .:
            f:apiVersion:
            f:kind:
            f:name:
            f:namespace:
        f:clusterName:
        f:infrastructureRef:
          .:
          f:apiVersion:
          f:kind:
          f:name:
          f:namespace:
        f:version:
    Manager:      kubectl
    Operation:    Update
    Time:         2020-05-06T01:58:41Z
    API Version:  cluster.x-k8s.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"machine.cluster.x-k8s.io":
        f:ownerReferences:
          .:
          k:{"uid":"1fdc1271-7e32-4ac5-9ce9-ccf6dc576726"}:
            .:
            f:apiVersion:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        f:bootstrap:
          f:dataSecretName:
        f:providerID:
      f:status:
        .:
        f:bootstrapReady:
        f:infrastructureReady:
        f:lastUpdated:
        f:phase:
    Manager:    manager
    Operation:  Update
    Time:       2020-05-06T02:00:26Z
  Owner References:
    API Version:     cluster.x-k8s.io/v1alpha3
    Kind:            Cluster
    Name:            work-cluster
    UID:             1fdc1271-7e32-4ac5-9ce9-ccf6dc576726
  Resource Version:  2854
  Self Link:         /apis/cluster.x-k8s.io/v1alpha3/namespaces/default/machines/controlplane-0
  UID:               fa98c83d-7a53-4c1f-b73d-65f617a491c0
Spec:
  Bootstrap:
    Config Ref:
      API Version:     bootstrap.cluster.x-k8s.io/v1alpha3
      Kind:            KubeadmConfig
      Name:            controlplane-0-config
      Namespace:       default
    Data Secret Name:  controlplane-0-config
  Cluster Name:        work-cluster
  Infrastructure Ref:
    API Version:  infrastructure.cluster.x-k8s.io/v1alpha3
    Kind:         DockerMachine
    Name:         controlplane-0
    Namespace:    default
  Provider ID:    docker:////work-cluster-controlplane-0
  Version:        v1.17.2
Status:
  Bootstrap Ready:       true
  Infrastructure Ready:  true
  Last Updated:          2020-05-06T01:58:46Z
  Phase:                 Provisioning
Events:                  <none>
[root@sdw1 v0.3.0]#`

**Comment by ginobiliwang** [comment]
[root@sdw1 v0.3.0]# kubectl get machine
NAME             PROVIDERID                               PHASE
controlplane-0   docker:////work-cluster-controlplane-0   Provisioning
worker-0                                                  Pending

**Comment by ginobiliwang** [comment]
[root@sdw1 v0.3.0]# kubectl describe machine controlplane-0
Name:         controlplane-0
Namespace:    default
Labels:       cluster.x-k8s.io/cluster-name=work-cluster
              cluster.x-k8s.io/control-plane=true
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"cluster.x-k8s.io/v1alpha3","kind":"Machine","metadata":{"annotations":{},"labels":{"cluster.x-k8s.io/cluster-name":"work-cl...
API Version:  cluster.x-k8s.io/v1alpha3
Kind:         Machine
Metadata:
  Creation Timestamp:  2020-05-06T01:58:41Z
  Finalizers:
    machine.cluster.x-k8s.io
  Generation:  3
  Managed Fields:
    API Version:  cluster.x-k8s.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:cluster.x-k8s.io/cluster-name:
          f:cluster.x-k8s.io/control-plane:
      f:spec:
        .:
        f:bootstrap:
          .:
          f:configRef:
            .:
            f:apiVersion:
            f:kind:
            f:name:
            f:namespace:
        f:clusterName:
        f:infrastructureRef:
          .:
          f:apiVersion:
          f:kind:
          f:name:
          f:namespace:
        f:version:
    Manager:      kubectl
    Operation:    Update
    Time:         2020-05-06T01:58:41Z
    API Version:  cluster.x-k8s.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"machine.cluster.x-k8s.io":
        f:ownerReferences:
          .:
          k:{"uid":"1fdc1271-7e32-4ac5-9ce9-ccf6dc576726"}:
            .:
            f:apiVersion:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        f:bootstrap:
          f:dataSecretName:
        f:providerID:
      f:status:
        .:
        f:bootstrapReady:
        f:infrastructureReady:
        f:lastUpdated:
        f:phase:
    Manager:    manager
    Operation:  Update
    Time:       2020-05-06T02:00:26Z
  Owner References:
    API Version:     cluster.x-k8s.io/v1alpha3
    Kind:            Cluster
    Name:            work-cluster
    UID:             1fdc1271-7e32-4ac5-9ce9-ccf6dc576726
  Resource Version:  2854
  Self Link:         /apis/cluster.x-k8s.io/v1alpha3/namespaces/default/machines/controlplane-0
  UID:               fa98c83d-7a53-4c1f-b73d-65f617a491c0
Spec:
  Bootstrap:
    Config Ref:
      API Version:     bootstrap.cluster.x-k8s.io/v1alpha3
      Kind:            KubeadmConfig
      Name:            controlplane-0-config
      Namespace:       default
    Data Secret Name:  controlplane-0-config
  Cluster Name:        work-cluster
  Infrastructure Ref:
    API Version:  infrastructure.cluster.x-k8s.io/v1alpha3
    Kind:         DockerMachine
    Name:         controlplane-0
    Namespace:    default
  Provider ID:    docker:////work-cluster-controlplane-0
  Version:        v1.17.2
Status:
  Bootstrap Ready:       true
  Infrastructure Ready:  true
  Last Updated:          2020-05-06T01:58:46Z
  Phase:                 Provisioning
Events:                  <none>
[root@sdw1 v0.3.0]#

**Comment by ginobiliwang** [comment]
I have changed the environmental variable to the following and tried again, issue still exits.

+++++++++++++++++++++++++++++++++++++
export DOCKER_POD_CIDRS=192.200.0.0/16
export DOCKER_SERVICE_CIDRS=10.0.1.0/24
export DOCKER_SERVICE_DOMAIN=cluster.local
+++++++++++++++++++++++++++++++++++++

Issue is the same with "dial tcp 172.17.0.2:6443: i/o timeout", looks like this ip is with docker's network arch.

++++++++++++++++++++++++++++++++++++++++
[root@sdw1 v0.3.0]# ifconfig
br-4debc70eea1d: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.19.0.1  netmask 255.255.0.0  broadcast 172.19.255.255
        inet6 fc00:f853:ccd:e793::1  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::1  prefixlen 64  scopeid 0x20<link>
        inet6 fe80::42:c7ff:fedb:82c4  prefixlen 64  scopeid 0x20<link>
        ether 02:42:c7:db:82:c4  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

br-bbecac09d4de: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
        ether 02:42:e9:0e:39:be  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:eeff:fe7e:a21e  prefixlen 64  scopeid 0x20<link>
        ether 02:42:ee:7e:a2:1e  txqueuelen 0  (Ethernet)
        RX packets 968326  bytes 68143491 (64.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1185835  bytes 1741940036 (1.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
+++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by fabriziopandini** [comment]
> dial tcp 172.17.0.2:6443: i/o timeout
does not seem a bug to me, but a networking problem in your setup. 
I saw similar errors in environments with a proxy ... 
/remove-kind bug  
/priority awaiting-more-evidence

@elmiko PTAL

**Comment by elmiko** [comment]
> does not seem a bug to me, but a networking problem in your setup.

that it my initial guess as well. i would double check what the docker network cidr is, also check your external network. i matched DOCKER_POD_CIDR to my pod network, and DOCKER_SERVICE_CIDR to my local network.

also check the firewall settings in centos to make sure nothing is blocking traffic to the pod network.

**Comment by ginobiliwang** [comment]
@elmiko , thanks for comments.
I did some trouble shooting.
+++++++++++++++++++++++++++++++++++++++++++
[root@sdw1 v0.3.0]# ifconfig
br-46701fee4f7d: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.19.0.1  netmask 255.255.0.0  broadcast 172.19.255.255
        inet6 fc00:f853:ccd:e793::1  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::1  prefixlen 64  scopeid 0x20<link>
        inet6 fe80::42:41ff:fef0:e830  prefixlen 64  scopeid 0x20<link>
        ether 02:42:41:f0:e8:30  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:5a:64:22:cf  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
++++++++++++++++++++++++++++++++++++++++++++++++

The issue is like, when i created the control-panel cluster using 

kind create cluster --config kind-cluster-with-extramounts.yaml --name clusterapi

it would create a bridge to route traffic for this "clusterapi" cluster. As you can see above , the bridge has ip section 172.19.0.0/16, which is automatically chose by kind.

Once i issue the command 

kubectl apply -f work-cluster.yaml

It is going to create a work cluster, the work cluster is with a haproxy LB. The LB would use ip address based on docker0 bridge, for instance,
if docker0 is 172.17.0.1, haproxy lb will be 172.17.0.2
if docker0 is 192.168.1.1, haproxy lb will be 192.168.1.2 (i did an experiment by changing docker0 to 192.168.1.1, and found out the rule)

So, that is the target ip address pods in control-panel cluster would like to visit.
"dial tcp 172.17.0.2:6443: i/o timeout"

As a result, control-panel cluster with ip section 172.19.0.0/16, could not visit  172.17.0.2:6443.

As preparations, I have flush away all the rule in iptable and nat table.
I did set the environmental variables
export DOCKER_POD_CIDRS=172.18.0.0/16 && 
export DOCKER_SERVICE_CIDRS=172.28.4.0/24 && 
export DOCKER_SERVICE_DOMAIN=cluster.local 

but still no luck.

On the other hand, if i create two kind clusters with kind command

kind create cluster --config kind-cluster-with-extramounts.yaml --name clusterapi
kind create cluster --config kind-cluster-with-extramounts.yaml --name clusterapi1

All the nodes would be under the same bridge, for example  172.19.0.0/16.

I assume that there is some issue or settings i do not know for clusters created by cluster-api services.

**Comment by lnovara** [comment]
I had a simular issue caused by the fact that `kind` is creating the containers in the `kind` network while CAPD is creating them in the `bridge` one making them not accessible from the kind management cluster.

I had to `docker network connect bridge kind-control-plane` to make the workload cluster accessible from the management one.

I got the same issue on both Linux and Mac.

Hope it helps.

**Comment by elmiko** [comment]
interesting, i have not experienced this behavior with the bridge. i do see the haproxy lb pods that are created, but my network defaults must tolerate this. fwiw i wrote the article that @ginobiliwang referenced on a machine with stock fedora 31 server instance.

**Comment by lnovara** [comment]
I don't know, I got the same issue on Docker for Mac and Debian.

After doing the `docker network connect` command everything started working, I even scheduled a pod on the management cluster to check if I was able to reach the load balancer and I couldn't.

I don't remember having done anything fancy with the docker networking on that two machines.

**Comment by elmiko** [comment]
glad to hear we have a good workaround.

i'm not sure how the docker deployments differ between macos/debian and fedora, but i have not had to run that command to make this work on my machines. i tend to run all fedora and centos boxes though, so i have to think it's just a difference in distro configuration.

**Comment by elmiko** [comment]
i tried to reproduce what is happening, but when i run kind i only see the addition a virtual network interface, and no bridge is created.

if i run `kind create cluster --name foo`, i get one new ethernet device created (the virtual interface), and no new pods (no lb).

this is all done on fedora 31 server, just wanted to add another data point to the discussion.

ifconfig before kind
```
[mike@localhost ~]$ ifconfig                                                         
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500                                
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255               
        inet6 fe80::42:ebff:fee5:f0e7  prefixlen 64  scopeid 0x20<link>              
        ether 02:42:eb:e5:f0:e7  txqueuelen 0  (Ethernet)                            
        RX packets 4048619  bytes 555570688 (529.8 MiB)                              
        RX errors 0  dropped 0  overruns 0  frame 0               
        TX packets 6861308  bytes 9980763679 (9.2 GiB)                               
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

ifconfig after kind
```
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:ebff:fee5:f0e7  prefixlen 64  scopeid 0x20<link>
        ether 02:42:eb:e5:f0:e7  txqueuelen 0  (Ethernet)
        RX packets 4048643  bytes 555572096 (529.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6861311  bytes 9980763941 (9.2 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth21dbd30: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::a43f:48ff:fe63:d64b  prefixlen 64  scopeid 0x20<link>
        ether a6:3f:48:63:d6:4b  txqueuelen 0  (Ethernet)
        RX packets 24  bytes 1744 (1.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12  bytes 988 (988.0 B) 
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by fabriziopandini** [comment]
Same here. I jump from macos and ubuntu but I never faced the same problem 🤔

**Comment by elmiko** [comment]
i wonder if this is a kind issue?

**Comment by ginobiliwang** [comment]
@elmiko, i have been looking for some config that could assign kind clusters with certain subnets, which could used to prevent kind from creating a new bridge, but did not found out.
If it exits, it could definitely being used in cluster-api project to mitigate the issue.

@lnovara , thanks for the information, i will try the walk-around.

**Comment by ginobiliwang** [comment]
@lnovara  it works after applying the command!

**Comment by lnovara** [comment]
I think that this might be related to the recent kind 0.8.0 release which changes the default network in which kind clusters are created.

Is this a CAPD "bug"? What CAPD should do now? Create the workload clusters in the same Docker network in which CAPD is running?

Ref: https://github.com/kubernetes-sigs/kind/releases/tag/v0.8.0

**Comment by ginobiliwang** [comment]
> I think that this might be related to the recent kind 0.8.0 release which changes the default network in which kind clusters are created.
> 
> Is this a CAPD "bug"? What CAPD should do now? Create the workload clusters in the same Docker network in which CAPD is running?
> 
> Ref: https://github.com/kubernetes-sigs/kind/releases/tag/v0.8.0
Agree.

With this PR, i did some experiments.
https://github.com/kubernetes-sigs/kind/pull/1538

[root@sdw1 clusterApiTest]# export KIND_EXPERIMENTAL_DOCKER_NETWORK=bridge
[root@sdw1 clusterApiTest]# kind create cluster --name testcluster
Creating cluster "testcluster" ...
WARNING: Overriding docker network due to KIND_EXPERIMENTAL_DOCKER_NETWORK
WARNING: Here be dragons! This is not supported currently.
 ✓ Ensuring node image (kindest/node:v1.18.2) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-testcluster"
You can now use your cluster with:

kubectl cluster-info --context kind-testcluster

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
[root@sdw1 clusterApiTest]#
[root@sdw1 clusterApiTest]#
[root@sdw1 clusterApiTest]# docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                  NAMES
5c2fd5864ce4        kindest/node:v1.18.2           "/usr/local/bin/entr…"   47 seconds ago      Up 45 seconds       127.0.0.1:46534->6443/tcp              testcluster-control-plane
6c13e01f16a7        kindest/node:v1.17.2           "/usr/local/bin/entr…"   46 hours ago        Up 46 hours                                                work-cluster-worker-0
dbee24165041        kindest/node:v1.17.2           "/usr/local/bin/entr…"   46 hours ago        Up 46 hours         45625/tcp, 127.0.0.1:45625->6443/tcp   work-cluster-controlplane-0
14f9d231d4c5        kindest/haproxy:2.1.1-alpine   "/docker-entrypoint.…"   46 hours ago        Up 46 hours         46169/tcp, 0.0.0.0:46169->6443/tcp     work-cluster-lb
7517986056a4        kindest/node:v1.18.2           "/usr/local/bin/entr…"   46 hours ago        Up 46 hours         127.0.0.1:40518->6443/tcp              clusterapi-control-plane
[root@sdw1 clusterApiTest]#
[root@sdw1 clusterApiTest]# docker exec -it 5c2fd5864ce4  /bin/bash
[root@testcluster-control-plane:/#
............
[root@testcluster-control-plane:/# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.6  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:ac:11:00:06  txqueuelen 0  (Ethernet)
        RX packets 10490  bytes 15697524 (15.6 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8320  bytes 688158 (688.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Looks like latest version of kind would definitely cause that issue.

ClusterApi use `docker` command to spawn containers under bridge docker0, but control panel is using bare-metal `kind` command under bridge kind.  It should be the root cause of issue.
https://github.com/kubernetes-sigs/cluster-api/blob/0b964b734167081a2a994f28983877140c58c50c/test/infrastructure/docker/docker/kind_manager.go#L256-L285

Short term walkaround is to use this variable to assign the bridge using by control panel container.

`KIND_EXPERIMENTAL_DOCKER_NETWORK`

**Comment by fabriziopandini** [comment]
@elmiko @lnovara @ginobiliwang should we document this?

**Comment by elmiko** [comment]
> @elmiko @lnovara @ginobiliwang should we document this?

imo, seems worth mentioning in a note or something

**Comment by lnovara** [comment]
I agree with @elmiko, while we wait for a proper fix this should be mentioned in the documentation to avoid some head scratching for people approaching the project. 😄

**Comment by vincepri** [comment]
Closing this now that the kind v0.8.x instructions have been merged.

/close
