### ISSUE TITLE
Possibility to modify preKubeadmCommands during a KCP update

### ISSUE THREAD

**Issue by Jaakko-Os** [kubernetes-sigs/cluster-api#3014]
**User Story**

As a developer I would like to have a possibility to modify preKubeadmCommands during KCP update for maintaining compatibility with new images.

**Detailed Description**

Situation can occur if we need to do something different due to new versions of the kubernetes binaries (kubeadm, kubelet, kubelet) that are baked into a new image.
E.g change a load balancer configuration, call another sysctl to start a new service or something else that was moved or renamed.

/kind feature

**Comment by maelk** [comment]
I believe the situation would be the same with postKubeadmCommands and files.

**Comment by ncdc** [comment]
As discussed in the community meeting today, I believe we started with complete immutability, and have been opening up fields to mutability as the need arises. We typically have had to write logic specific to each field (e.g. to sync data into the kubeadm configmap in the workload cluster). But for pre/postKubeadmCommands and files, those likely wouldn't require any syncing.

I think I'm ok allowing these specific fields to be mutated. Anyone else want to weigh in?

**Comment by vincepri** [comment]
cc @detiber

**Comment by maelk** [comment]
During the meeting, you were mentioning an issue with rollback. What would be the strategy for rollback then ? I would expect the commands would be related to the image we use, so they would need to be in sync.

**Comment by ncdc** [comment]
We don't actually support any rollbacks in KCP, so never mind about what I said in the meeting 😄. Whatever is in the KCP spec must be valid whenever creating a new control plane machine.

**Comment by maelk** [comment]
Hi there! Are there any updates regarding this ? @ncdc and @detiber ? thank you!

**Comment by detiber** [comment]
I'm a +1 to allowing mutability for the PreKubeadmCommands and PostKubeadmCommands fields.

**Comment by maelk** [comment]
Just a note that we would need it for files too. It is the same use-case.
