### ISSUE TITLE
e2e Framework: Add machine helper to wait and validate status of machine

### ISSUE THREAD

**Issue by gab-satchi** [kubernetes-sigs/cluster-api#3016]
**User Story**

As a developer I would like more e2e helpers in order to make developing providers easier

**Detailed Description**

Request to add a helper to `machine_helpers` that will make asserting on a machine's state easier. Similar to other helpers, it should take intervals as an argument to determine how often to check and when to timeout. 

/kind feature

**Comment by sedefsavas** [comment]
@gab-satchi which status checks are you looking here? I added a noderef check in a PR that may be useful but can add more based on your feedback.
