### ISSUE TITLE
Provisioned phase?

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api#3036]
Are these phase definitions correct?

https://github.com/kubernetes-sigs/cluster-api/blob/98d461988fec43f6471ff13417bfe079fcbc5b5c/controllers/machine_controller_phases.go#L60-L68

See also: https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20190610-machine-states-preboot-bootstrapping.md#transition-conditions-2

The machine controller reconciles infrastructure before the InfrastructureRef before the NodeRef, so m.Status.InfrastructureReady is always true in the second case, right? Does anything use Provisioned state right now and expect a nodeRef?

**Comment by vincepri** [comment]
These values have been only informational, and shouldn't be used in any controllers or code. I agree with you that the current logic is a little confusing. We'll probably always transition from `provisioning` -> `running` given the code above.

Another reason why conditions are a better way to determine the status of our objects

**Comment by vincepri** [comment]
Probably ok to close this for now, given that we're planning to remove the phase field in the next cycle. Feel free to reopen if necessary

/close
