### ISSUE TITLE
Adapt clusterctl move to the new multi-tenancy model

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3042]
**User Story**

As a User, I would like to use clusterctl for creating multy-tenant clusters.

**Detailed Description**

https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1713 is introducing the possibility for a provider to use many credentials with a single instance of a provider.

We should define if/how this scenario is supported by clusterctl.

**Anything else you would like to add:**

clusterctl already support two other different types of multy-tenancy, see https://cluster-api.sigs.k8s.io/clusterctl/commands/init.html#multi-tenancy

The approach introduced by CAPA is potentially by far simpler than the existing ones, and if we can potentially have all the providers to converge on the same approach this can result in a relevant simplification of manifests generation (e.g. no more need of the WebHook namespace) and of clusterctl (lots of corner cases won't be necessary anymore)

/kind feature

**Comment by fabriziopandini** [comment]
/area clusterctl
even do this problem is not clusterctl specific

**Comment by vincepri** [comment]
@randomvariable is working on this in the providers for v1alpha3, although we should revisit in v1alpha4 and forward. It's definitely something we might want to tackle before getting to beta.

/milestone Next

**Comment by randomvariable** [comment]
Thanks for this issue Fabrizio. 

/priority important/long-term

**Comment by vincepri** [comment]
We need to add definitions for what multi-tenancy is to the glossary

**Comment by randomvariable** [comment]
And a provider contract. We should definitely put this in 0.4.0

/assign

**Comment by vincepri** [comment]
Renamed this, hopefully it's going to be a bit more clear going forward :)

**Comment by fabriziopandini** [comment]
Given that we are moving to a single manager watching all namespaces for each provider, I started to investigate possible cleanups/action items:
- [ ] Run webhooks as part of the main manager #3822
- [ ] Docs: document new definition of multi-tenancy (a single infrastructure provider supporting multiple credentials)
- [ ] Docs: remove existing notes about previous models of multitenancy 
- [ ] inventory:
  - `GetDefaultProviderVersion` --> `GetProviderVersion`
  - `GetDefaultProviderNamespace` --> `GetProviderNamespace`
- [ ] clusterctl delete:
  - Remove (or depreacate) the `--namespace` flag in `clusterctl delete` and in the corresponding library method
- [ ] inventory/management group:
  - Remove `ManagementGroupList`
  - `deriveManagementGroups` should return `ManagementGroup` instead of `ManagementGroupList`; the func should error if there is more than 1 core provider or more that 1 provider instance for the same bootstrap_/control-plane/bootstrap provider
  - Remove `checkOverlappingCoreProviders`
  - `checkOverlappingProviders` should be simplified under the assumption there could be only 1 core provider
  - `GetManagementGroups` --> `GetManagementGroup`
- [ ] installer:
  - `simulateInstall` should fail if there is more than 1 instance of the same provider
  - `Validate` should be adapted to the fact that there is only one management group
- [ ] Upgrader:
  - `Plan` should return a single upgrade plan
  - `ApplyPlan` and `ApplyCustomPlan` should drop the core provider parameter given that there is only one management group in the cluster
- [ ] clusterctl upgrade plan:
  - Should returns single plan
  - Should fail gracefully if run against a v1alpha3 cluster with more than one instance of the same providers.
- [ ] clusterctl upgrade apply:
  - Should deprecate the --management-group flag and fail if the value provided does not match the existing management group

**Comment by wfernandes** [comment]
@fabriziopandini I can start creating individual stories for the tasks here and we can start adding in more details if needed.

**Comment by wfernandes** [comment]
- [ ] Remove `--watching-namespace` from clusterctl and then revert #3246. See https://github.com/kubernetes-sigs/cluster-api/issues/3119#issuecomment-742667762 for more details.

**Comment by fabriziopandini** [comment]
@vincepri @CecileRobertMichon @randomvariable @yastij @nader-ziada reminder to keep this in the radar

> ... we are introducing the possibility for a provider to use many credentials with a single instance of a provider.
> We should define if/how this scenario is supported by clusterctl.

**Comment by vincepri** [comment]
How would clusterctl support multiple credentials?

**Comment by fabriziopandini** [comment]
> How would clusterctl support multiple credentials?

That the point I'm trying to understand. 

For instance, last I checked the AWS proposal it was introducing different types of cluster principals.
Does clusterctl have to support all the AWS cluster principals types during init? how?
Also, are the other providers implementing a similar approach than AWS, so we can design a single UX?

**Comment by fabriziopandini** [comment]
Linking https://github.com/kubernetes-sigs/cluster-api/issues/4035 because it touches changing credentials during pivoting

**Comment by randomvariable** [comment]
> Does clusterctl have to support all the AWS cluster principals types during init? how?

For init, other than installing the CRDs, no.
For move, ideally clusterctl should move AWS*Principal resources, including the global ones.

However in the most common case, we only expect the management cluster to be moved, and in that case, will use a singleton `AWSClusterControllerPrincipal` which is a no-op type of principal that just states the cluster is using the credentials present at controller startup, which is the same secret mounted to `~/.aws/credentials` as it is currently in v1alpha3

**Comment by nader-ziada** [comment]
For capz, 
no changes needed for init 
no changes need for move;  the `AzureClusterIdentity` type gets moved since its a capz resource and we decided at the time the referenced `identity` itself should be the responsibility of the user to move/create in the new namespace since its out of the scope of the controller

**Comment by yastij** [comment]
for now on the CAPV side, we're having two types of credentials:
- a secret for namespaced credentials
- later down the road  we'd also have a`VSphereAccount` CRD which would be cluster-scoped for accounts that are available for multiple vcenters.

**Comment by sbueringer** [comment]
In case it's relevant in any way, CAPO is using a secret, which is usually located in the same namespace as the Cluster resource, but is referenced via a SecretRef which would also allow using a secret in another namespace.

**Comment by fabriziopandini** [comment]
Trying to distill a generalised approach and possible impacts on clusterctl and in the CAPI provider operator as well:

For the init workflow:
- all the providers/identity management systems do requires to install new CRD types; this could be managed by the existing machinery in clusterctl because identity types will be packaged together with the existing CRDs;
- most of the providers plans to have credentials resources defined in their infrastucture-components.yaml and to use variables substitution for allowing users to specify an initial set of credentials (as of today); CAPZ instead assumes the user has to create credentials before doing clusterctl init (might be there is a chicken egg problem here, given that `AzureClusterIdentity` CRD is not yet installed in the cluster at this stage...)

For the move workflow:
- we should ensure clusterctl could manage variants variants: Global Identity vs namespace identity, identity in secrets vs identity in CRD
- As of today following constraints stands:
  - Move will consider all the kinds defined in the CRDs installed by clusterctl + Secrets and ConfigMap, including both namespaced and global kinds; 
  - If those kind are namespaced, only resources in a given namespace will be considered;
  - The resulting set of resources will be further filtered excluding everything:
     1. Is not linked to a cluster via the owner ref chain
     2. Is not explicitly marked as force move (at CRD or at resource level)
      
Are 1 or 2 enough to address the requirement for all the providers/identity management systems?

**Comment by fabriziopandini** [comment]
Thanks to the work in https://github.com/kubernetes-sigs/cluster-api/pull/4514, we can finally nail down required changes in clusterctl move.

- during the discovery, on top of what is considered today, clustectl has to collect secrets from the namespaces where the infrastructure providers are running
- the filtering step process at the end of the discovery process should be updated in order to manage additional owner chain roots (not only the owner chain below Cluster and CRS); additional owner chain root to be considered for move will be identified via a new label TBD applied at CRD level or at resource level (IMPORTANT! providers have to apply the label on their CRDs)
- there should be check in place about existence of all the target namespaces (this should be already the case, but there are no unit test in place for multiple namespaces)
- the move/delete order should consider the multiple owner chain (this should be already the case, but there are no unit test in place for multiple namespaces)
- Cluster level objects should not be deleted from the source cluster.

NB. move will continue to create or update both global and namespace objects, as of today

@randomvariable @nader-ziada @yastij @gab-satchi @sedefsavas @vincepri

**Comment by sedefsavas** [comment]
@fabriziopandini Will it be straightforward to backport this to v0.3.x release? Asking because CAPA is supporting multi-tenancy in v1alpha3 releases.

**Comment by fabriziopandini** [comment]
> @fabriziopandini Will it be straightforward to backport this to v0.3.x release? Asking because CAPA is supporting multi-tenancy in v1alpha3 releases.

I don't think we are going to backport this; changes are sort of invasive and not all the guidelines for the providers (https://github.com/kubernetes-sigs/cluster-api/pull/4514) are not yet merged

**Comment by fabriziopandini** [comment]
We should wait for  #4628 as well
