### ISSUE TITLE
Document clusterctl upgrade for multi-tenant clusters

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3043]
https://cluster-api.sigs.k8s.io/clusterctl/commands/upgrade.html should provide details about how to upgrade multi-tenant cluster.

**Anything else you would like to add:**
This issue is derived from https://github.com/kubernetes-sigs/cluster-api/issues/2997#issuecomment-623549302
The main points to be documented are the limitations about:
- usage of instance-specific variables vs upgrades.
- lack of support for upgrades with change contract (in case of instance-specific variables)

Once the current process is documented, we should consider also possible improvements to the UX.
 
/area clusterctl
/kind documentation

**Comment by vincepri** [comment]
/close

In favor of #2997
