### ISSUE TITLE
clusterctl upgrades does not support change of contract with multi-tenancy

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3044]
This issue is derived from https://github.com/kubernetes-sigs/cluster-api/issues/2997#issuecomment-623549302

clusterctl does not support provider upgrades if the following conditions apply:
- muti-tenancy
- providers use instance-specific variables
- the upgrade requires change of contract

because:
- change of contract requires to be upgraded at the same time
-  usage of instance-specific variables requires to upgrade 1 provider at time

/kind bug
/area clusterctl

**Comment by vincepri** [comment]
When do we want to get this fixed? Should we document the limitations?

**Comment by fabriziopandini** [comment]
> When do we want to get this fixed? 

This is for v1alpha4

> Should we document the limitations?

I'm fine in document or fix, but currently there is no strategy defined for this use case (user are blocked)

**Comment by fabriziopandini** [comment]
NB. the documentation part should be fine; there is still the problem that users are blocked in case of change of contract

**Comment by vincepri** [comment]
Are there any action items in this issue?

**Comment by fabriziopandini** [comment]
yes. it is required some design to get a process/some code change in place to make it possible v1alpha3-->v1alpha4 in case of multi-tenancy & providers using instance-specific variables

**Comment by vincepri** [comment]
Closing this in favor of #3042 
/close
