### ISSUE TITLE
clusterctl should manage controller flags

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3045]
**User Story**

As an operator, I would like a simple way to provide controller flags during init 
As an operator, I would like clusterctl to preserve controller's flags during upgrades

**Detailed Description**
The number of flags in controller is growing, mostly due to the work on experiments, but currently clusterctl manages only the --namespace flag during init and upgrades.

Currently, there is a possible workaround to provide any other controller flag (different than namespace), but it requires to manually change the components yaml and to provide it to clusterctl as an override or using a local repository, but this is not a really user friendly.

**Anything else you would like to add:**
As a possible solution for this effort, in the past, it was discussed the usage of component config in Kubebuilder, but I'm not aware of progress in this area.
Another option is to leverage the Providers object created by clusterctl, but this requires some design and it covers the upgrade part only.
Also the work on templates can be interesting for this effort if it will be extended to the provider components as well.

/kind feature
/area clusterctl
/area upgrades

**Comment by vincepri** [comment]
See https://github.com/kubernetes-sigs/controller-runtime/blob/master/designs/component-config.md for CR component config

**Comment by fabriziopandini** [comment]
Even if with envsubst the most urgent problem was addressed (`--feature-flags`) I think we should keep around so we don't forget that the UX for flags like -`-enable-leader-election` or `--metrics-addr` (and many others) is still not ideal
/remove-lifecycle stale

**Comment by vincepri** [comment]
Related to #3427

**Comment by vincepri** [comment]
Closing in favor of #3427 

/close
