### ISSUE TITLE
Consolidate access to Machine phase statuses

### ISSUE THREAD

**Issue by benmoss** [kubernetes-sigs/cluster-api#3046]
**User Story**

As a developer I want the codebase to use a consistent definition of `Pending`/`Provisioning`/`Provisioned`/`Running`/`Failed`/`Deleting` so that we can have a clear and consistent mental model of what these words mean.

**Detailed Description**

Right now there is a lot of code strewn about the codebase that checks various things that represent these phases. For example, bugs can occur if people forget to check `FailureMessage` and only check `FailureReason`, or check `NodeRef` but not `InfrastructureReady`.

Additionally, if we ever want to change the definition of one of these phases, we will need to also audit the entire codebase for things that are trying to detect the same state transitions.

**Anything else you would like to add:**

This is *not* about the codebase using `machine.Status.Phase`.  That should continue to be considered stale state and should not be relied on.

/kind feature

**Comment by vincepri** [comment]
@benmoss Thanks for filing this, it seems the use cases span into the work @fabriziopandini is pushing forward with `Conditions` on all Cluster API objects.

**Comment by benmoss** [comment]
/close
Not sure I feel this is as valid / worth doing anymore
