### ISSUE TITLE
Add security section to CAEP template

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#3062]
We've started to brush up against security concerns, particularly RBAC in the development of features and proposals. Wonder if it's worth creating an explicit section about in the CAEP template.

Initial thing could be:

### Security Model Changes

In this section, describe how Cluster API's security model would be affected by your proposal/feature.

#### Roles

Identify the expected users or systems as roles that would interact with the Kubernetes management and/or workload cluster as it relates toh 

### RBAC
RBAC (role-based access control) is the standard used for Kubernetes
authorization. This allows users to configure who can perform actions on
resources in specific scopes. RBAC can be used to enable each of the roles
defined above. In most cases, it will be desirable to have all resources be
readable by most roles, so instead we'll focus on write access for this model.

##### Read Permissions
For each role and resource pair, state whether or not the role would be able to read the resource.

| Role   | Resource 1 | Resource 2 |
|--------|------------|------------|
| Role 1 | Yes/No     | Yes/No     |
| Role 2 | Yes/No     | Yes/No     |

##### Write Permissions
For each role and resource pair, state whether or not the role would be able to write the resource.

| Role   | Resource 1 | Resource 2 |
|--------|------------|------------|
| Role 1 | Yes/No     | Yes/No     |
| Role 2 | Yes/No     | Yes/No     |

Add further commentary as needed

**Comment by randomvariable** [comment]
/kind documentation
/assign

Happy to add it if folk agree.

**Comment by fabriziopandini** [comment]
+1 from me. 
Not sure which role are expected to be listed, but I like the idea of having something that forces me to this about RBAC and security when reading a proposal

**Comment by vincepri** [comment]
/help
/milestone v0.3.x

Please do, this is a great reminder to _always_ think about security when writing a proposal!

**Comment by fabriziopandini** [comment]
@randomvariable are you still working at this? otherwise, I can take the ticket

**Comment by randomvariable** [comment]
I'll do it now, since I already have a section in the CAPA multitenancy prop
