### ISSUE TITLE
documentation: add example for enabling feature gates in CAPI book

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api#3073]
/kind documentation

The clusterctl [documentation](https://cluster-api.sigs.k8s.io/clusterctl/configuration.html) should include an example for adding flags to the various providers to enable a feature gate (we can use MachinePool as an example since it's the only one supported across multiple providers right now).

**Comment by fabriziopandini** [comment]
this is related to https://github.com/kubernetes-sigs/cluster-api/issues/3045

**Comment by akutz** [comment]
Hi @CecileRobertMichon,

I was looking at this issue to see if it is something with which I can help. I have not worked on CAPI in a while, and so a lot of the clusterctl bits are new to me. Could you please provide more information on what you would like to see documented? I found the following related to feature gates:

* [Implement `--feature-flag` in `main.go`](https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html?highlight=feature,gate#optional-implement---feature-gates-flag-in-maingo)
* [Example with Tilt](https://github.com/kubernetes-sigs/cluster-api/commit/07a65a49543c06c0f20cb065c28f56c06a7d8211)

What I am now seeing, and I guess I expect to see, is one of the following:

* Some flag in `clusterctl` for enabling feature flags
* Some way/flag in `clusterctl` for modifying a provider's controller manager flags
* Some way in the provider contracts to influence the flags for the provider's controller manager

I did not see any of this, so either I am missing something or I am unsure of what you're wanting to document. Can you please help? Thanks!

**Comment by CecileRobertMichon** [comment]
@akutz the right fix is #3045 I think which would, as you said, allow setting flags for a provider's controller manager. In the meantime, the only way to enable a feature gate is to manually set the flag on the manager by overriding the provider config, and that's the workaround I wanted to document (and it should probably be part of https://cluster-api.sigs.k8s.io/clusterctl/developers.html). @fabriziopandini what do you think? does it make sense to document the manual way as a workaround for now or should we wait for #3045?

See https://kubernetes.slack.com/archives/CEX9HENG7/p1589827095210000 for more background.

**Comment by akutz** [comment]
Hi @CecileRobertMichon,

Ah, so I think you confirmed what I was thinking was the case. Just to be sure, can you please confirm that today, the only way to set feature flags, or change any flags other than `namespace`, is by overriding the provider config locally?

If that is the case, my concern is that any documented example for enabling feature flags will result in:

* Data that needs to be consistently checked/refreshed against the provider's components, or...
* An operation with something like `sed` to inject the flag(s) into the provider's components that could fail if said (HA! I made a punny) components are updated in such a way that they are no longer compatible with the `sed` match/replace

Thoughts?

**Comment by fabriziopandini** [comment]
@akutz @CecileRobertMichon, I'm ok in documenting the workaround while #3045 gets addressed.

A simple workaround is to download the controller manifest to `$HOME/.cluster-api/overrides/<provider-label>/<version>/<file-name.yaml>` and edit the controller flags before doing init

NB. worth adding that the same operation must be repeated before upgrades (see warning https://cluster-api.sigs.k8s.io/clusterctl/commands/upgrade.html)

**Comment by rbitia** [comment]
@fabianofranz @CecileRobertMichon Can we document the workaround in documentation too? I see the fix is scheduled for vNext but I'd love to see it prioritized in a sooner milestone :D  

Also as a user I need more description on where the controller manifest lives and what to change to enable feature gates.

**Comment by fabriziopandini** [comment]
related PR https://github.com/kubernetes-sigs/cluster-api/pull/3325
