### ISSUE TITLE
Add contrib folder guidelines to CONTRIBUTING.md

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#3074]
**User Story**

As a developer I would like to to better understand CAPIs guidelines for `contrib` folders. For example, if I wanted to contribute a yaml processor in order to extend clusterctl's templating.

**Anything else you would like to add:**
Ref https://github.com/kubernetes-sigs/cluster-api/pull/3052

/kind feature
/kind documentation

**Comment by fabriziopandini** [comment]
/close
Given that we are not using the contribs folder so far.
We can always re-open/re-create if this be reconsidered in future
