### ISSUE TITLE
Add .status.observedGeneration to all objects

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api#3078]
**User Story**

Many Kubernetes objects have an `observedGeneration` in the status that enables comparison against `.metadata.generation`. This is helpful for implementing other controllers against CAPI types that want to wait until changes are reconciled by the CAPI controllers before jumping in and doing their work.

**Detailed Description**

Add `.status.observedGeneration` and have each controller set this value from `.metadata.generation` at the end of reconciliation.

/kind feature

**Comment by randomvariable** [comment]
CAPI conditions will have an ObservedGeneration field, so will need to be done as part of that work.

**Comment by benmoss** [comment]
And do we want to do this for *every* object? `KubeadmConfigTemplate`?

**Comment by fabriziopandini** [comment]
being the generation number linked to changes to the object's spec, IMO we should add the field to any object that allows spec mutation

**Comment by vincepri** [comment]
Templates don't have a status subresource today

**Comment by benmoss** [comment]
/reopen

We need to add the code to start updating `ObservedGeneration` once #3118 has merged using the new `WithStatusObservedGeneration` option there.
