### ISSUE TITLE
Set CAPI status to paused or running

### ISSUE THREAD

**Issue by casibbald** [kubernetes-sigs/cluster-api#3085]
**User Story**

As a operator I would like to set my CAPI management cluster to a state of Paused or Running for the reason of needing to safely backup or restore my CAPI cluster.

**Detailed Description**

In order to safely backup, restore, duplicate a cluster and leave it in 'stopped' state there is a need for the following clusterctl commands.

`
clusterctl state stop
clusterctl state start
clusterctl status
 > CAPI processes are stopped
 > CAPI processes are running
`

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by vincepri** [comment]
/help
/priority backlog

Today, clusters have a `spec.paused` field you can use to pause reconciliation, you'd have to patch every cluster you have in your management cluster. In alternative, another potential and safe solution is to scale down the deployments to `replicas = 0`, back up the cluster, and scale them back up.

**Comment by casibbald** [comment]
Will build this an external cli tool and reach into mover.go to pause or
resume the app

**Comment by fabriziopandini** [comment]
@casibbald is this still a problem or we can close the issue?

**Comment by casibbald** [comment]
I came up with a very ugly workaround however it would be good to have it
from the clusterctl binary tool.

**Comment by vincepri** [comment]
Could we potentially leverage the management cluster operator to allow something like this? @wfernandes

**Comment by fabriziopandini** [comment]
/close
This is going to be implemented as part of https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20201020-capi-provider-operator.md
