### ISSUE TITLE
Document clusterctl version support

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#3090]
The support matrix (added in https://github.com/kubernetes-sigs/cluster-api/pull/3031) needs details for clusterctl.

/kind documentation

**Comment by fabriziopandini** [comment]
From my point of view clusterctl is bound to ClusterAPI version, so e.g. v1alpha3 clusterctl is compatible with all the provider that are compatible with the v1alpha3 contract.
@dlipovetsky is this ok for you?

**Comment by dlipovetsky** [comment]
@fabriziopandini That sounds right. I think it would be good to say add that to the doc.
