### ISSUE TITLE
Document management/workload cluster upgrade order

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#3091]
The version support doc (added in https://github.com/kubernetes-sigs/cluster-api/pull/3031) should describe the correct order of upgrading the management and workload clusters.

/kind documentation

**Comment by vincepri** [comment]
@randomvariable Do you have time to finish this before EOW/v0.3.9?

**Comment by randomvariable** [comment]
Yup.
