### ISSUE TITLE
MachineDeploymentStatus.Phase value "ScalingUp" is too broad

### ISSUE THREAD

**Issue by joshrosso** [kubernetes-sigs/cluster-api#3095]
**User Story**

When all node replicas are created and running, the `Phase` of the `MachineDeployment` remains `ScalingUp` until all machines report as `Ready`. 

As a user, this is confusing as I think the controller is stuck trying to create new machines or the underlying provider is struggling to create new nodes.

This was a source of confusion for another user at https://github.com/kubernetes-sigs/cluster-api/issues/2446#issuecomment-592097547.

The easiest means of replicating this behavior is to create a new cluster and not instantiate the CNI. 

```bash
kubectl get machinedeployment
NAME      PHASE       REPLICAS   AVAILABLE   READY
c2-md-0   ScalingUp   3
```

```bash
kubectl get machine
NAME                       PROVIDERID                    PHASE
c2-control-plane-22xtg     aws:////i-0201ea8274bcd2a88   Running
c2-control-plane-45vh5     aws:////i-0be5382f60f93781c   Running
c2-control-plane-fmlhh     aws:////i-0d13670782c34531e   Running
c2-md-0-67b5f57cd4-7dr2q   aws:////i-01e26abdc533da07d   Running
c2-md-0-67b5f57cd4-k4qx6   aws:////i-0d7d0f2138749ff41   Running
c2-md-0-67b5f57cd4-rsqtl   aws:////i-053ae02696cf1550a   Running
```

The field in question is:
https://github.com/kubernetes-sigs/cluster-api/blob/f50487481eee941224ec79064d5be1560d82cfe2/api/v1alpha3/machinedeployment_types.go#L195-L197

**Proposal**

When the nodes are created but not `Ready`, is it worth adding a status such as:

* `Bootstrapping`
* `BoostrappingNode(s)`

The goal being providing better UX to the operator in troubleshooting when scaling fails?

If desirable, I'd be happy to knock this out.

/kind feature

**Comment by vincepri** [comment]
/area ux
/priority important-longterm
/milestone v0.3.x

This might be a good opportunity for conditions to solve.

**Comment by fabriziopandini** [comment]
Yes, concerns about object state are part of the condition work.
Ensuring this match objects Phase is an additional step, but I see the point in keeping this in the radar

**Comment by vincepri** [comment]
We should try and remove the Phase field in v1alpha4 and move to conditions

**Comment by enxebre** [comment]
Related to https://github.com/kubernetes-sigs/cluster-api/pull/4174
