### ISSUE TITLE
Document control-plane-controller in Concepts docs

### ISSUE THREAD

**Issue by joshrosso** [kubernetes-sigs/cluster-api#3097]
Before opening an MR, I just wanted to make sure ya'll felt this was appropriate:

As of `v1alpha3`, the `control-plane-controller` and `kubeadmControlPlane` API have become first-class citizens. We should update the Concepts page to include this object and controller where appropriate.

Additionally, the namespace/controller/API diagram should be updated to include  `ns/capi-kubeadm-control-plane-system`, `capi-kubeadm-control-plane-controller-manager`, and `KubeadmControlPlane`, with friendlier names in the diagram, as per the existing:

![image](https://user-images.githubusercontent.com/6200057/82765394-77ad7600-9dcb-11ea-9473-831114211290.png)

/kind feature

**Comment by fabriziopandini** [comment]
I'm +1 to document control plane provider in this schema; additionally we should consider also documenting MHC

**Comment by joshrosso** [comment]
I'll take this, you can `/assign joshrosso`.
