### ISSUE TITLE
Support upgrading/pivoting cluster to multi-master

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#31]
_From @rsdcastro on January 29, 2018 22:57_

_Copied from original issue: kubernetes/kube-deploy#540_

**Comment by ncdc** [comment]
This sounds like the ask is to be able to scale a one-node control plane to multi-node. Is that accurate?

**Comment by vincepri** [comment]
I think this might be safe to close given that #30 has been fixed.

**Comment by ncdc** [comment]
Sold.

/close
