### ISSUE TITLE
Kubeconfig secret is not rotated on cluster upgrade

### ISSUE THREAD

**Issue by ashoksekar07** [kubernetes-sigs/cluster-api#3113]
**What steps did you take and what happened:**
I created a cluster. All the certificates in the cluster had an expiry of 1 year. On upgrading the cluster, all the certificates inside the cluster were rotated and the expiry changed to 1 year from the time of upgrade. But the kubeconfig secret that gets created still had the older expiry period and it was not refreshed.

**What did you expect to happen:**
I expected the kubeconfig secret to be rotated on cluster upgrade so that the certificates don't expire and make the kubeconfig unusable.

**Anything else you would like to add:**

**Environment:**
- Cluster-api version: v0.2.11
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): 1.17.4
- OS (e.g. from `/etc/os-release`): Amazon Linux 2

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by benmoss** [comment]
You are referring to the user's client certificate (`.users[0].user.client-certificate-data`)? The cluster certificate has a 10 year expiry.

**Comment by detiber** [comment]
> You are referring to the user's client certificate (.users[0].user.client-certificate-data)? The cluster certificate has a 10 year expiry.

Yes, the client certificate embedded in the kubeconfig is the issue.
