### ISSUE TITLE
clusterctl deletes ClusterRole and ClusterRoleBinding resources when they share a prefix w/ a namespaced delete

### ISSUE THREAD

**Issue by JTarasovic** [kubernetes-sigs/cluster-api#3119]
**What steps did you take and what happened:**
Init an infrastructure provider in a namespace
`clusterctl init --infrastructure aws  --watching-namespace test --target-namespace test`

Init an infrastructure provider in a namespace that has the same prefix
`clusterctl init --infrastructure aws  --watching-namespace test-1 --target-namespace test-1`

Delete infrastructure components in first namespace
`clusterctl delete --infrastructure aws --namespace test`

ClusterRole and ClusterRoleBindings for both namespaces are deleted

**What did you expect to happen:**
Only resources belonging to the provider / namespace to be deleted.

**Anything else you would like to add:**
Seems to be [here](https://github.com/kubernetes-sigs/cluster-api/blob/87c0343549fe6dc8017eeb94d66f7c826e75cc4e/cmd/clusterctl/client/cluster/components.go#L174)

**Environment:**
N/A

/kind bug
/area clusterctl

**Comment by fabriziopandini** [comment]
That's an interesting one.

The code for delete check for the namespace prefix for identifying the resource belonging to a prefix.
https://github.com/kubernetes-sigs/cluster-api/blob/b8026b35a857fb15407290507cb3ae202fa581b6/cmd/clusterctl/client/cluster/components.go#L169-L177

But in this case when you delete the `test` instance it check for all the objects with namespace prefix `test-` which is a substring of the namespace prefix of the other instance, that is `test-1-`, so both gets deleted.

So as a workaround, for now, you should use namespace names that are not contained one with another (e.g. `test-1` & `test-2`)

In the meantime, we should look to a more robust way to link RBAC rules to a specific instance (e.g. Labels or Annotations)

/remove-triage support

**Comment by JTarasovic** [comment]
Yeah, not sure why it got labelled support. I'd already linked the line that deleted based on prefix (174).

**Comment by vince** [comment]
Wrong vince @fabriziopandini

**Comment by vincepri** [comment]
Do we have anyone working on this, or should we bump it from the milestone?

**Comment by wfernandes** [comment]
@vincepri Apologies. I didn't get a chance to look at this. But I think it should be bumped from this release.

> So as a workaround, for now, you should use namespace names that are not contained one with another (e.g. test-1 & test-2)

Maybe we document this as a known bug. WDYT?

**Comment by fabriziopandini** [comment]
I'm +1 to document and bump the fix to the next release

Working on the fix is tricky, because we should preserve the current approach for some time for retro compatibility e.g. assuming that we move to labels for identifying the cluster to which a clusterRoleBinding belongs,

if you
- run clusterctl init with an older version of clusterctl
- clusterRoles gets created with name prefix (but without labels)
- install latest clusterctl with the fix for using annotations
- run clusterctl upgrade should delete the installed version (without labels) and replace with a new one (with labels)

^^ mean that we should support both current and new approach for some time

**Comment by wfernandes** [comment]
I'll create a PR updating the clusterctl docs with a warning for now. We can tackle the real solution as part of the next release.
 Thanks @JTarasovic for surfacing this bug.

**Comment by fabriziopandini** [comment]
This is probably won't be a problem anymore when the new multitenancy model lands

**Comment by fabriziopandini** [comment]
I think this issue can be closed given https://github.com/kubernetes-sigs/cluster-api/issues/3042 the scenario with many instances of the same provider in a cluster is not out of scope. 
If so, it is possible to remove the warning in clusterctl delete and in the clusterctl delete logs (revert https://github.com/kubernetes-sigs/cluster-api/pull/3246/files)

@wfernandes @vincepri opinions?

**Comment by wfernandes** [comment]
I think this can be closed once we remove the support for `--watching-namespace` because once that's done then we won't be able to reproduce this issue. 
And then as part of closing this issue, we should revert #3246.

**Comment by fabriziopandini** [comment]
/close
@wfernandes, we should more the action item from the previous command in a separated issue/within a TODO list for the CPI operator work
