### ISSUE TITLE
Add support for Azure Provider 

### ISSUE THREAD

**Issue by Meegul** [kubernetes-sigs/cluster-api#312]
I'm currently working on implementing an Azure actuator that is being hosted in an external repository at the moment. Currently the goal is to match the functionality of the existing providers. Can I get /assign 'ed for this?

**Comment by dims** [comment]
related to https://github.com/kubernetes-sigs/cluster-api/issues/432

**Comment by roberthbailey** [comment]
Provider now exists: https://github.com/kubernetes-sigs/cluster-api-provider-azure

/close
