### ISSUE TITLE
Machine and KubeadmControlPlane disagree on k8s version validation

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api#3128]
**What steps did you take and what happened:**

Generate a machinepool-flavored cluster manifest:

```clusterctl config cluster capz-machinepool -f machinepool --worker-machine-count 1 --kubernetes-version 1.18.3 > capz-machinepool.yaml```

Then apply the manifest and get a validation error on the "version" field:

```shell
% k apply -f capz-machinepool.yaml 
cluster.cluster.x-k8s.io/capz-machinepool unchanged
azurecluster.infrastructure.cluster.x-k8s.io/capz-machinepool unchanged
azuremachinetemplate.infrastructure.cluster.x-k8s.io/capz-machinepool-control-plane created
machinepool.exp.cluster.x-k8s.io/capz-machinepool-mp-0 unchanged
azuremachinepool.exp.infrastructure.cluster.x-k8s.io/capz-machinepool-mp-0 unchanged
kubeadmconfig.bootstrap.cluster.x-k8s.io/capz-machinepool-mp-0 created
The KubeadmControlPlane "capz-machinepool-control-plane" is invalid: spec.version: Invalid value: "": spec.version in body should match '^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([-0-9a-zA-Z_\.+]*)?$'
```

Adding a `v` prefix to `v1.18.3` in the manifest fixes it, but note that:
- This worked fine until recently (until after #2691?)
- the `MachinePool` in the same manifest is happy with either `1.18.3` or `v1.18.3` AFAICT

**What did you expect to happen:**

I expected that CAPZ and `clusterctl` would create a valid manifest without built-in validation errors. Perhaps `clusterctl` itself should have errored rather than allow "1.18.3" through.

**Anything else you would like to add:**

**Environment:**

- Cluster-api version: v0.3.6
- Minikube/KIND version:  KIND v0.7.0
- Kubernetes version: (use `kubectl version`): v1.18.3
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
Let's reconcile the two and make sure they adhere to the same standard

cc @CecileRobertMichon @juan-lee

**Comment by CecileRobertMichon** [comment]
Is there a reason why both `1.18.3` and `v1.18.3` can't be valid? It worked fine before that validation was added so is it possible that requiring the `v` prefix is an artificial requirement? cc @randomvariable

**Comment by randomvariable** [comment]
The decision was as a result of 
https://github.com/kubernetes-sigs/cluster-api/pull/2691#discussion_r393266948

I did originally have it defaulting to add the v prefix for you.

**Comment by CecileRobertMichon** [comment]
/retitle "Machine and KubeadmControlPlane disagree on k8s version validation"

**Comment by CecileRobertMichon** [comment]
/retitle Machine and KubeadmControlPlane disagree on k8s version validation
