### ISSUE TITLE
KubeadmConfig controller should not rely on previously set status 

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3134]
**What did you expect to happen:**
As per comment https://github.com/kubernetes-sigs/cluster-api/pull/3122#discussion_r433250967 and https://github.com/kubernetes-sigs/cluster-api/pull/3125#discussion_r434177064

The KubeadmConfig controller implements a subset of reconcile logic in the main reconcile loop
https://github.com/kubernetes-sigs/cluster-api/blob/7b9762100a1d4852a037a9ace0ea96af0b22c20e/bootstrap/kubeadm/controllers/kubeadmconfig_controller.go#L198-L242

We should move this to separated reconcile func, and make sure the logic does not rely on previously set status. Instead, it should check for the real state of things. E.g. Instead of checking status for ensuring the secret was created in a previous reconciliation loop, we should check if the secret actually exists.

/kind bug
/area bootstrap

**Comment by fabriziopandini** [comment]
Nb. if we implement lookup for existing secrets, this logic potentially can be removed
https://github.com/kubernetes-sigs/cluster-api/blob/7b9762100a1d4852a037a9ace0ea96af0b22c20e/bootstrap/kubeadm/controllers/kubeadmconfig_controller.go#L801-L803

**Comment by killianmuldoon** [comment]
@ramineni Have you had time to work on this?

**Comment by ramineni** [comment]
@killianmuldoon sorry for the delay . Got time to get back on this.

Could you help me understand is this issue still relevant now? I see code is changed around 
> L204: ` case config.Status.BootstrapData != nil && config.Status.DataSecretName == nil: ` this doesn't exist in reconcile loop anymore, 

> Nb. if we implement lookup for existing secrets, this logic potentially can be removed
Is this the pending item?

Thanks,

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

This is more a code small than something that creates real issues, and the issue is mostly inactive since sept 2022
/Close
