### ISSUE TITLE
Add conditions to the DockerCluster object

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3141]
**User Story**

As a developer/user/operator I would like to have conditions documenting the operational state of `DockerCluster` objects 

**Detailed Description**
A `DockerCluster` object in CAPI is responsible for creating a container that creates the cluster infrastructure-

As a consequence, I'm proposing to start implementing the following for the `DockerCluster` object:

- LoadBalancerProvisionedCondition

**Anything else you would like to add:**
As required by the condition CAEP, the `DockerCluster` objects should also provide a `Ready` condition describing the overall state of the object.

/kind feature

**Comment by vincepri** [comment]
Fixed by #3142 

/close
