### ISSUE TITLE
KCP needs to change owner references of control plane secrets on adoption

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#3144]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
* Create a v1alpha2 cluster
* Update to v1alpha3, with a KCP with an upgraded version
* All control plane secrets are deleted and recreated except for the kubeconfig
* Cluster is borked

**What did you expect to happen:**
* Control plane secrets are not replaced

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.6
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): v1.16.7
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
@sethp-nr

**Comment by rudoi** [comment]
ohhhhh this is interesting. 

that's basically the same flow our clusters went through but we didn't see this behavior.

**Comment by vincepri** [comment]
Isn't this covered in https://github.com/kubernetes-sigs/cluster-api/blob/d54acb51d11a3e14a88b4f9f64f8611d58044f7c/controlplane/kubeadm/controllers/controller.go#L509-L542

**Comment by randomvariable** [comment]
Possibly a race condition if you apply a KCP that immediately forces an upgrade.

**Comment by sethp-nr** [comment]
Weird, I'm not tracking how the race condition would present – if there are adoptable machines, whether we succeed or fail, we should halt further reconciliation until they've been adopted and the local cache reflects that: https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/controllers/controller.go#L244-L249 

Which resource are your secrets owned by? It might be something to do with how we find the cluster secrets for adoption – in my testing they were always owned by the KubeadmConfig for the first Machine in the cluster, maybe that assumption doesn't hold?

**Comment by vincepri** [comment]
Needs another pass / triage

**Comment by ncdc** [comment]
We have determined the root cause. The adoption logic checks only for secrets with controller owners, but CAPBK in v1alpha2 only ever creates secrets with non-controller owners; thus, the adoption logic does not reparent the secrets correctly.

When @sethp-nr tested this, it was using a fork with slightly different code that checks for any ownership, not specifically controller ownership.

@sethp-nr plans to open a PR to fix this.

/assign @sethp-nr 
/unassign @randomvariable
