### ISSUE TITLE
KCP does not delete old control plane as soon as new upgraded control plane comes up

### ISSUE THREAD

**Issue by DheerajSShetty** [kubernetes-sigs/cluster-api#3146]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
 

- Create a v1alpha2 cluster with 3 control planes
- Update the namespace to v1alpha3
- Create KCP with replica set to 3 for adopting the 3 control planes
- KCP tried upgrading the cluster, but while scaling it created 5 replicas before deleting old replicas

**What did you expect to happen:**

- Expected an old control machine to be deleted after successfully creating new control plane.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 0.3.6
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): 1.16.7
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by detiber** [comment]
Steps that were taken prior to seeing this issue:
- Cluster was originally created using v1alpha2 types and controllers
- controllers/crds were upgraded to v1alpha3
- KCP resources were created to adopt existing Machine-based control plane instances
- KCP adoption triggered an upgrade

When the upgrade was initiated there were 2 new replicas that were created prior to the first deletion occurring for existing replicas.

**Comment by rudoi** [comment]
I just saw this behavior updating from 0.3.2 to 0.3.5, not during a v1alpha2-3 update, FYI.

**Comment by sedefsavas** [comment]
@rudoi 
I observe the same behaviour with a single control plane machine. This looks like a different issue, because the issue above is related to an error during upgrade, there was supposed to be an upgrade there whereas here upgrade should have never been triggered (but successfully upgrades after it is triggered). 
 I think we should track this in a new issue: https://github.com/kubernetes-sigs/cluster-api/issues/3170

**Comment by vincepri** [comment]
This one has been fixed in #3234 

/close
