### ISSUE TITLE
Update Cluster API to handle kubeadm v1beta2 configuration

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3150]
**User Story**

As a user, I would like Cluster API to support Kubeadm v1beta2 config as part of KubeadmConfig and KubeadmControlPlane because the v1beta1 configuration is deprecated and will eventually lose support.

**Detailed Description**
Kubeadm is deprecated, and while there is not yet a date for removal, we should start to plan for starting to use v1beta2 in cluster API.

The issue is complicated by the fact that there is not yet agreement on k/k on how to handle component config upgrade and, as a consequence, kubeadm is not offering an automatic conversion func.
This is also relate to the work of moving kubeadm out of k/k and make it usable as a library (currently on hold 😞 ).

/kind feature

**Comment by vincepri** [comment]
/milestone Next

Unfortunately we'll have to tackle this item in v1alpha4 given that we might need breaking changes and/or a redesign of the current APIs.

**Comment by vincepri** [comment]
Closing this in favor of https://github.com/kubernetes-sigs/cluster-api/issues/3150

/close

**Comment by Arvinderpal** [comment]
@vincepri 

> Closing this in favor of #3150
> 
> /close

@vincepri Did you mean to reference some other issue or was this closed by accident?

**Comment by vincepri** [comment]
It should have been closed in favor of #2769
