### ISSUE TITLE
Refactor test CRDs in controller/external

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3168]
As per comment https://github.com/kubernetes-sigs/cluster-api/pull/3136#discussion_r436819480

In `controller/external/testing.go` we are exposing a set of test CRDs as a pointer e.g. https://github.com/fabriziopandini/cluster-api/blob/d09777b1a19f7635d75c978fd844db6e3003a927/controllers/external/testing.go#L27

Those CRDs are used in several tests, and being pointers, this exposes CAPI unit tests to side effects whenever a test applies a change to those objects.

Unfortunately, changing how objects are exposed today is a breaking change, but as soon as possible, we should change the code stopping to expose vars but rather exposing a function that returns a new instance of the object.

While refactoring, worth to consider if this is something we want to continue having this test values as public objects and if this is the right package for them (e.g. vs moving to the test package).

/kind bug
/area testing

**Comment by hazbo** [comment]
> While refactoring, worth to consider if this is something we want to continue having this test values as public objects and if this is the right package for them (e.g. vs moving to the test package).

Where do you think might be an appropriate place to put these? Is the idea to create exported funcs that return an instance of each given CRD, in this case?

i.e.
```go
func GetGenericBootstrapCRD() apiextensionsv1.CustomResourceDefinition {
    return apiextensionsv1.CustomResourceDefinition{
		TypeMeta: metav1.TypeMeta{
			APIVersion: apiextensionsv1.SchemeGroupVersion.String(),
			Kind:       "CustomResourceDefinition",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "genericmachines.bootstrap.cluster.x-k8s.io",
			Labels: map[string]string{
				clusterv1.GroupVersion.String(): "v1alpha3",
			},
		},
		Spec: apiextensionsv1.CustomResourceDefinitionSpec{
			Group: "bootstrap.cluster.x-k8s.io",
			Scope: apiextensionsv1.NamespaceScoped,
			Names: apiextensionsv1.CustomResourceDefinitionNames{
				Kind:   "BootstrapMachine",
				Plural: "genericmachines",
			},
			Versions: []apiextensionsv1.CustomResourceDefinitionVersion{
				{
					Name:    "v1alpha3",
					Served:  true,
					Storage: true,
					Subresources: &apiextensionsv1.CustomResourceSubresources{
						Status: &apiextensionsv1.CustomResourceSubresourceStatus{},
					},
					Schema: &apiextensionsv1.CustomResourceValidation{
						OpenAPIV3Schema: &apiextensionsv1.JSONSchemaProps{
							Type: "object",
							Properties: map[string]apiextensionsv1.JSONSchemaProps{
								"spec": {
									Type:                   "object",
									XPreserveUnknownFields: pointer.BoolPtr(true),
								},
								"status": {
									Type:                   "object",
									XPreserveUnknownFields: pointer.BoolPtr(true),
								},
							},
						},
					},
				},
			},
		},
	}
}
```

Is there some overlap where for a period of time both the `var` and a func like this one could co-exist while work is in progress on it?

**Comment by fabriziopandini** [comment]
I think that a func in an internal package will be enough to fix this issue (might me returning a pointer instead of a copy of the struct), but considering the type of problem, IMO we should avoid coexistence of current and target solution and wait for when v1alpha4 work start.
