### ISSUE TITLE
[question] Is cluster-api calico only?

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#3174]
**User Story**

As a [developer/user/operator] I would like to [high level description] for [reasons]

**Detailed Description**

Is cluster-api , e.g we mentioned we support add-ons so that we can create different CNI

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/services/ec2/securitygroups.go#L368-L488

only support calico 

during discussion https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/555
we found security groups (cloud provider perspective) might align CNI

so what's the strategy of CNI support in different providers?

**Comment by jichenjc** [comment]
yes, I understand cluster-api is not specific to one CNI but the implementation is related to Calico
and I understand Calico is widely used so agree for now it's a good thing to use

https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1137 is a good reference ,thanks for the pointing @vincepri @benmoss

**Comment by vincepri** [comment]
Good to close this issue?

**Comment by jichenjc** [comment]
yes, works for me
