### ISSUE TITLE
Add resource relationship diagrams to the doc

### ISSUE THREAD

**Issue by superbrothers** [kubernetes-sigs/cluster-api#3187]
I'm a newbie of Cluster API. I have created Cluster API resource relationship diagrams to learn Cluster API for myself.

- https://docs.google.com/document/d/1byUfKYdOwyhSg5ZShSR29d5FxyhQtekAekiBZezV89A/edit?usp=sharing

I think it's useful for first time learners. I'd like to add them to the documentation if you'd like.

What do you think?

**Comment by fabriziopandini** [comment]
I'm +1 with the idea 
Just wondering if we should use plat uml like other diagrams we have in the book

**Comment by vincepri** [comment]
+1 to reusing the same diagrams we have today, we have some automation to generate them [here](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/Makefile#L28)

**Comment by superbrothers** [comment]
> +1 to reusing the same diagrams we have today, we have some automation to generate them here

Nice! 😍
