### ISSUE TITLE
Prioritize machines without node reference when scaling down machine deployments.

### ISSUE THREAD

**Issue by sb464f** [kubernetes-sigs/cluster-api#3193]
**What steps did you take and what happened:**
I have like 10 replicas of machines running via machinedeployment, where 8 have node references and two are still hanging around with no node references. And if I scale down md to 8 it is bringing down random machines.

**What did you expect to happen:**
Prioritize machines without node reference to bring down. 

**Environment:**

- Cluster-api version: 0.3.3
- Kubernetes version: (use `kubectl version`): v1.18.3
- OS (e.g. from `/etc/os-release`):ubuntu

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
Sounds reasonable to me, we can probably add this in v0.3.x given that it's a benign improvement, @ncdc thoughts?

**Comment by ncdc** [comment]
👍 (@sb464f & I chatted on Slack about this)

**Comment by vincepri** [comment]
Whoever is looking into implement this change, MachineSet gets the priority list from: https://github.com/kubernetes-sigs/cluster-api/blob/0225dbfdb3fd16538336a2cc6f6857119bf72aec/controllers/machineset_delete_policy.go#L133

Each of those functions needs to be changed to look for `Machine.Status.NodeRef` and return a higher priority for those. 

Given that now we also have `MachineHealthCheckSucceded` condition, we can probably also check that and prioritize unhealthy machines the same way.

Tests are probably going to break given that NodeRef defaults to `nil`, they might need a cleanup.
