### ISSUE TITLE
Document how to contribute to Cluster API effort

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#32]
_From @rsdcastro on January 29, 2018 23:39_

_Copied from original issue: kubernetes/kube-deploy#545_

**Comment by roberthbailey** [comment]
@karan added https://github.com/kubernetes-sigs/cluster-api/blob/master/CONTRIBUTING.md in https://github.com/kubernetes-sigs/cluster-api/commit/549a7ee63fbff5adb29f1b90645b43ae86df775c#diff-6a3371457528722a734f3c51d9238c13 the day after the original issue (in the old repo) was opened, which addressed this. Marking as fixed.
