### ISSUE TITLE
MachineHealthCheck will match Machines across cluster boundaries

### ISSUE THREAD

**Issue by JoelSpeed** [kubernetes-sigs/cluster-api#3202]
**What steps did you take and what happened:**
- Create a management cluster with at least two workload clusters running on it.
- Ensure that there is a label common to some Machines across at least two workload clusters
  - Eg, add the label `role: worker` to MachineDeployments on the two clusters
- Create a MachineHealthCheck  with `clusterName` pointing to one of the clusters, but the label selector pointing to the shared label, eg `role: worker`

- The MachineHealthCheck will now health check/target machines across all clusters assuming they match the label in the label selector

**What did you expect to happen:**
- The MachineHealthCheck should only target machines that are part of the cluster defined in its clusterName field.

**Anything else you would like to add:**

We could resolve this by enforcing the label selector contains the cluster name label

**Environment:**

- Cluster-api version: master
- Minikube/KIND version: 0.8.1
- Kubernetes version: (use `kubectl version`): 1.17.3
- OS (e.g. from `/etc/os-release`):

/kind bug
/area health

**Comment by vincepri** [comment]
This should be pretty straightforward, here is where we list the Machines attached to a MHC object: https://github.com/kubernetes-sigs/cluster-api/blob/80653d174c6f5bb5ea76fbafbe2f0c50cc1185dd/controllers/machinehealthcheck_targets.go#L205-L212

The list uses the label selector we have under `spec.selector` to filter the machines we want to target. In the webhook defaulter https://github.com/kubernetes-sigs/cluster-api/blob/80653d174c6f5bb5ea76fbafbe2f0c50cc1185dd/api/v1alpha3/machinehealthcheck_webhook.go#L55-L58 we already default the MHC own label to the ClusterName, we should add a default to spec.selector as well and force `Spec.Selector.MatchLabels` to always have `ClusterLabelName` set to `Spec.ClusterName`.

**Comment by benmoss** [comment]
What is the point of the `clusterName` selector now that there's a mandatory `selector`?

**Comment by benmoss** [comment]
Do we want to deprecate `clusterName` and move people to using `selector` exclusively for this?

**Comment by ncdc** [comment]
@benmoss hi, are you working on this?

**Comment by benmoss** [comment]
@ncdc hey, yep

**Comment by ncdc** [comment]
Thanks! Mind marking it active?
