### ISSUE TITLE
Support for better deletion priority granularity and precedence for MachineSets

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#3227]
**User Story**

As a Cluster API user I would like MachineSet deletion priority to be easier to understand, especially when external integrations are involved

**Detailed Description**

Currently we lump a lot of different deletion priority mechanisms for MachineSet under the same priority levels, so there is no clear precedence for which mechanisms take priority. There are also slightly different prioritization levels given to some of the common prioritization mechanisms under `RandomDeletePriority` compared to `OldestDeletePriority` or `NewestDeletePriority`.

Some of the various priority mechanisms today:
- Machine is already deleting (non-zero deletionTimestamp)
- Annotation for deleting Machine based on external integrations is present
- Prioritize deletion of Machines that do not yet have a NodeRef
- Machines that have FailureMessage/FailureReason set

**Anything else you would like to add:**

Initial discussion that brought about this issue: https://github.com/kubernetes-sigs/cluster-api/pull/3222#discussion_r443058501

/kind feature

**Comment by vincepri** [comment]
/milestone v0.4.0

Going to set v1alpha4 for now to see if we need a redesign or not

**Comment by fabriziopandini** [comment]
/close

the issue is here since long time, but given the lack of cooments/progress it seems that there is no concrete need to define better deletion priorities
