### ISSUE TITLE
KCP should pause reconciliation while machines are failed but not eligible for automatic remediation

### ISSUE THREAD

**Issue by benmoss** [kubernetes-sigs/cluster-api#3230]
**User Story**

As an operator I would like to not have KCP continue to do scale up / scale down operations when a machine is in a failed state but is not marked for remediation so that I can triage the problem and not have it compounded by additional operations KCP might decide to take.

**Detailed Description**

Right now we have code in place to not do scaling operations while we are waiting on machine provisioning and deletion. With #3185 we will have code that handles machines marked by MHC for remediation. @detiber pointed out that we still may have machines that have `FailureMessage` and/or `FailureReason`s on them but not the MHC conditions for automatic remediation. This could happen if the user is not using MHC, or if the MHC has hit a `maxUnhealthy` quota.

We could instead just pause reconciliation of this cluster until all the machines are not failing. Users could manually remediate and either bring them back to healthy states or scale them down. This will also help us ensure we aren't going to interfere with external remediation.

/kind feature
/area control-plane

**Comment by fabriziopandini** [comment]
I see some potential downside in the change requested by this issue:
if we are in the middle of the first deployment of a 5 node CP (scale up from 0 to 5), and e.g. there is a problem on the 4th node, this PR will block the CP creation and wait for user intervention before going up to 5 nodes.

Instead I think that KCP should always continue to try to do its work, and block only if the next action might lead the cluster to a potential bad state; e.g.
- in case of scale up you have too have enough healthy members to mantain quorum if the new replica does not comes up (except 1 to 2)

**Comment by detiber** [comment]
@fabriziopandini 100% agree that once we can tell how an operation would affect quorum that it would be preferable to use that to block actions rather than this approach.
