### ISSUE TITLE
Calico Manifest assumes Service IP range

### ISSUE THREAD

**Issue by krousey** [kubernetes-sigs/cluster-api#324]
A Calico manifest has a hard-coded service IP that makes an assumption that it falls within the cluster's service cidr. This assumption is made https://github.com/kubernetes-sigs/cluster-api/blob/7fdecc5cc4b4174ab5c540a027fcfccc7183f66f/cloud/vsphere/templates.go#L372 and https://github.com/kubernetes-sigs/cluster-api/blob/7fdecc5cc4b4174ab5c540a027fcfccc7183f66f/cloud/vsphere/templates.go#L492

This needs to be an address that falls withing the cluster's [Service CIDR](https://github.com/kubernetes-sigs/cluster-api/blob/7fdecc5cc4b4174ab5c540a027fcfccc7183f66f/cloud/vsphere/templates.go#L271) because it can be changed by the end-user [here](https://github.com/kubernetes-sigs/cluster-api/blob/7fdecc5cc4b4174ab5c540a027fcfccc7183f66f/clusterctl/examples/vsphere/cluster.yaml.template#L8)

/kind cluster-api-vsphere
/cc @karan

**Comment by cadmuxe** [comment]
Thanks, I will create a patch.

**Comment by roberthbailey** [comment]
This issue was moved to kubernetes-sigs/cluster-api-provider-vsphere#8
