### ISSUE TITLE
[docs] Add controller architecture docs for MachinePool

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api#3244]
We should add a page for MachinePool in the architecture/controllers section of the book to document the controller flow for MachinePools, similar to https://cluster-api.sigs.k8s.io/developer/architecture/controllers/machine.html and https://cluster-api.sigs.k8s.io/developer/architecture/controllers/control-plane.html.

/kind documentation
/help

**Comment by shreyasbapat** [comment]
I believe this is not taken by anyone :D 

So, can I work on this?

**Comment by vincepri** [comment]
Go for it! 

cc @CecileRobertMichon @juan-lee

**Comment by shreyasbapat** [comment]
Can I add details from this? https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20190919-machinepool-api.md

**Comment by fabriziopandini** [comment]
/lifecycle active
Sure, the proposal is a good starting point; the actual implementation of the code is https://github.com/kubernetes-sigs/cluster-api/tree/master/exp/controllers to be documented is here

**Comment by shreyasbapat** [comment]
> /lifecycle active
> Sure, the proposal is a good starting point; the actual implementation of the code is https://github.com/kubernetes-sigs/cluster-api/tree/master/exp/controllers to be documented is here

Thanks @fabriziopandini . I will look into it

**Comment by CecileRobertMichon** [comment]
/assign @shreyasbapat 

Let me know if you need any guidance! I can also help review once you have a draft.

**Comment by vincepri** [comment]
/milestone v0.4.0

Let's pair this task with taking MachinePool out of experiments

**Comment by fabriziopandini** [comment]
/remove-lifecycle stale
@shreyasbapat any update on this?
