### ISSUE TITLE
Dump logs from minikube before cluster is deleted

### ISSUE THREAD

**Issue by mkjelland** [kubernetes-sigs/cluster-api#325]
Before the minikube cluster is deleted by clusterctl, dump the logs from the cluster api control loops into the clusterctl log files. When the minikube cluster gets deleted we lose access to those logs which might point to an issue in setting up the internal cluster.

**Comment by timothysc** [comment]
Given a larger refactor of clusterctl I'm going to close this issue due to history and open up a larger umbrella.
