### ISSUE TITLE
Should we be updating observed generation automatically in the patch helper?

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#3256]
/kind question

@vincepri @fabriziopandini One thing that just came to my mind, if we are expecting to be able to rely on using status.observedGeneration as a way to say that a resource has been reconciled to match the desired spec, then we should likely ONLY update observedGeneration when we have successfully reconciled the given resource to the state fully defined in the spec (not just partial reconciliation, in the case of controllers that return early and finish reconciliation of state through re-entrancy). 

With that in mind, I'm not sure that we can rely on the patch helper to properly set observedGeneration, rather we might need to set it explicitly in each of the controllers when it is appropriate to do so.

**Comment by vincepri** [comment]
It's probably fair to say we'll need to improve it to only update it if there are no reported errors, it'll require some changes which we can hopefully make in v0.4.

We ended up going this way because in lots of places we were setting the ObservedGeneration regardless in all defer functions.

**Comment by detiber** [comment]
The problem is that, if I remember correctly, the rationale for adding it was to have a way for external tooling or controllers to know that the reconciling controller has indicated the resource is "up to date", if we are setting observedGeneration prematurely and potentially on resources that are not under the controllers management, then we are not meeting the expectations of the feature.

If we ship something that does not meet the expectations of the consumers, then we are very likely to be doing more harm than good by adding and setting the field in a way that appears to be relatively arbitrary.

**Comment by vincepri** [comment]
The code changed to only patch when returning errors, now we only need to update the documentation on each ObservedGeneration field to reflect the change and explain the caveats.
