### ISSUE TITLE
Improve reconciliation of updates to KubeadmControlPlane ClusterConfiguration

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#3259]
**User Story**

As a user I would like to be able to mutate more fields for KubeadmControlPlane.Spec.KubeadmConfigSpec.ClusterConfiguration and for those changes to be rolled out in a way that makes sense based on their use.

**Detailed Description**

Currently today we limit the number of fields that are mutable for the Cluster Configuration and the fields that we do allow mutation any mutation triggers a full rolling upgrade of the cluster.

In some cases (such as a change that only affects the kubeproxy daemonset or coredns deployment) the changes are triggering a rolling update when they could be better handled through more targeted changes to those in-workload-cluster resources directly without also rolling out changes to the deployed Machines.

To add to this for the purposes of adoption and existing Machines, we don't currently have a way to know what the subset of ClusterConfiguration that should trigger a rolling update to pre-existing Machines and which should not. 

There are also additional challenges in that the embedded versions of the kubeadm configuration types do not necessarily align with the version that may be stored in the in-workload-cluster configmap that is managed by kubeadm, nor do we know if that version of the configmap represents the state of any pre-existing Machines during adoption.

Rather than try to manage all possible permutations of kubeadm configuration and comparing against the in-workload-cluster configmap, which would also require replicating kubeadm's defaulting and conversions, we can instead compare the fields that we allow mutation on against through introspection.

We are already doing this for coredns or kubeproxy related fields, we could easily introspect the fields against the current state of the deployment/daemonset as we do today.

We could extend this further to cover the additional fields by introspecting the mirror pods for etcd, the controller manager, and the api server static pods.

While we can likely make determinations about a good majority of the fields through direct comparisons against the mirror pod, there may be additional introspection that needs to be done, such as validation of SANs configured on certificates, but those should also be able to be done at runtime through a request directly to the pod through the apiserver proxy or through executing a command on the remote pod.

/kind feature

**Comment by CecileRobertMichon** [comment]
@detiber @vincepri are we still trying to get this done for v0.4? Is it release blocking for v0.4.0?

**Comment by fabriziopandini** [comment]
/close
over time the mutable surface of KCP has been increased addressing more use cases
