### ISSUE TITLE
Patch helper should validate before/after object are the same

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#3269]
The current patch helper implementation lets users to create a helper with object A and patch with object B. Given the lack of validation, we should add more bits in place to make sure the before/after object have the same GroupVersionKind and Name.

To add this validation, we'd also have to validate that the object is a valid `metav1.Object`. In the future, we might want to switch the `obj` parameter in `NewHelper` function and `Patch` method to be a `controllerutil.Object`; this isn't technically possible today because it'd be a breaking change.

That said, controller-runtime client doesn't support operating on objects without an ObjectMeta. If a user is creating a new helper and patching a non-meta object, the patch would return an error (https://github.com/kubernetes-sigs/controller-runtime/blob/2d4c4877f906e09df759c8b44355caf547299a99/pkg/client/typed_client.go#L109-L112).

What do folks think? Is it ok to change the interface from `runtime.Object` to `controllerutil.Object` and add the validation bits?

/kind cleanup

**Comment by vincepri** [comment]
cc @detiber @CecileRobertMichon @devigned @fabriziopandini @ncdc

**Comment by fabriziopandini** [comment]
I'm +1
TBH I don't consider this a breaking change, because an objects without an ObjectMeta already fails, but let's wait for v1alpha4

**Comment by ncdc** [comment]
+1 to me for v0.4.
