### ISSUE TITLE
Automate release note generation

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes-sigs/cluster-api#327]
We should have something like https://github.com/kubernetes/release/blob/master/relnotes for releases so that release notes don't have to be manually curated.

**Comment by neolit123** [comment]
attempting a `/milestone` command as per the discussion with @roberthbailey yesterday.

/milestone cluster-api-alpha-implementation

**Comment by roberthbailey** [comment]
I filed https://github.com/kubernetes/test-infra/issues/8690

**Comment by timothysc** [comment]
TODO: This is much broader problem that should be a breakout of issues.

**Comment by ncdc** [comment]
This is done.
/close
