### ISSUE TITLE
Quickstart fails to create reconcile cluster and machinedeployment objects

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes-sigs/cluster-api#3274]
**What steps did you take and what happened:**

Following latest published quickstart.

Download things
```
curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.3.6/clusterctl-linux-amd64 -o clusterctl
wget https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v0.5.4/clusterawsadm-linux-amd64

chmod +x the-stuff-I-downloaded

```

```
. ~/my/cloud/rc
export AWS_B64ENCODED_CREDENTIALS=$(./clusterawsadm-linux-amd64 alpha bootstrap encode-aws-credentials)
```

(Note, quickstart docs have instructions for v0.5.5 which is unreleased, so using v0.5.4)

Using kubeconfig for existing OpenShift cluster rather than KIND.

```
clusterctl init --infrastructure aws:v0.5.4
```

Completes successfully

```
clusterctl config cluster mgugino-capi --kubernetes-version v1.17.3 --control-plane-machine-count=3 --worker-machine-count=3 --infrastructure=aws:v0.5.4 > mgugino-capi-quickstart.yaml
```

Edit iamRole to one that already exists and has proper permissions.

```
kubectl apply -f mgugino-capi-quickstart.yaml
```

Completes successfully

```
kubectl get cluster
NAME           PHASE
mgugino-capi   Provisioning
```

Followed by:

```
./kubectl get machinedeployments
NAME                PHASE   REPLICAS   AVAILABLE   READY
mgugino-capi-md-0                                  
```

Okay, that's when I noticed things were definitely wrong.  Obviously PHASE and other columns should be populated.

**What did you expect to happen:**
Things to work.

**Anything else you would like to add:**
Tried adding additional subjects to some rolebindings but to no avail.  I'm not sure how all this RBAC stuff is wired together, there's quite a lot of it and the naming is very confusing.

**Environment:**

- Cluster-api version: 
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 

Logs from controller:
```
E0701 16:48:24.717670       1 controller.go:247] controller-runtime/controller "msg"="Reconciler error" "error"="[awsclusters.infrastructure.cluster.x-k8s.io \"mgugino-capi\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , \u003cnil\u003e, kubeadmcontrolplanes.controlplane.cluster.x-k8s.io \"mgugino-capi-control-plane\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , \u003cnil\u003e]"  "controller"="cluster" "request"={"Namespace":"default","Name":"mgugino-capi"}
E0701 16:48:44.243417       1 machinedeployment_sync.go:208] controllers/MachineDeployment "msg"="Failed to create new machine set" "error"="machinesets.cluster.x-k8s.io \"mgugino-capi-md-0-68fd5496f9\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , \u003cnil\u003e" "machinedeployment"="mgugino-capi-md-0" "namespace"="default" "machineset"="mgugino-capi-md-0-68fd5496f9"
E0701 16:48:44.243460       1 machinedeployment_controller.go:146] controllers/MachineDeployment "msg"="Failed to reconcile MachineDeployment" "error"="machinesets.cluster.x-k8s.io \"mgugino-capi-md-0-68fd5496f9\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , \u003cnil\u003e" "machinedeployment"="mgugino-capi-md-0" "namespace"="default" 
E0701 16:48:44.244013       1 controller.go:247] controller-runtime/controller "msg"="Reconciler error" "error"="machinesets.cluster.x-k8s.io \"mgugino-capi-md-0-68fd5496f9\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , \u003cnil\u003e"  "controller"="machinedeployment" "request"={"Namespace":"default","Name":"mgugino-capi-md-0"}
E0701 16:48:45.227574       1 controller.go:247] controller-runtime/controller "msg"="Reconciler error" "error"="[awsclusters.infrastructure.cluster.x-k8s.io \"mgugino-capi\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , \u003cnil\u003e, kubeadmcontrolplanes.controlplane.cluster.x-k8s.io \"mgugino-capi-control-plane\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , \u003cnil\u003e]"  "controller"="cluster" "request"={"Namespace":"default","Name":"mgugino-capi"}
```

**Comment by detiber** [comment]
@michaelgugino I believe in the call you mentioned that you were attempting to run this on OpenShift, based on this error message:

```
E0701 16:48:24.717670       1 controller.go:247] controller-runtime/controller "msg"="Reconciler error" "error"="[awsclusters.infrastructure.cluster.x-k8s.io \"mgugino-capi\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , \u003cnil\u003e, kubeadmcontrolplanes.controlplane.cluster.x-k8s.io \"mgugino-capi-control-plane\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , \u003cnil\u003e]"  "controller"="cluster" "request"={"Namespace":"default","Name":"mgugino-capi"}
```

It looks like there is some type of admission controller at play that is preventing the creation of resources with the appropriate finalizers needed. Based on the limited digging I did, it looks like it's related to the OwnerReferencesPermissionsEnforcement and it appears to require additional RBAC to make things work.

It looks like the RBAC can be updated to allow for Update for the appropriate finalizers subresource to give the appropriate permissions (https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement), but I'm not sure if that is something that is supported by the controller-tools generation tooling or if it would cause issues with Kubernetes Clusters  that do not have that admission controller enabled

**Comment by michaelgugino** [comment]
@detiber thanks for digging into this.  I think if that's a built-in admission controller, it's likely others will bump into this if using an existing cluster as well.  I'll investigate.

**Comment by fabriziopandini** [comment]
@michaelgugino is there an update for this issue?

**Comment by michaelgugino** [comment]
No, I haven't had a chance to dig into this.  It's on my todo list, but don't be afraid to look into it if you're interested.

**Comment by fabriziopandini** [comment]
Unfortunately, I don't have CAPO environments to dig into.
just wondering if we should keep the issue open here or move it to the CAPO repo where might be there could be more eyes on this.

**Comment by sbueringer** [comment]
> Unfortunately, I don't have CAPO environments to dig into.
> just wondering if we should keep the issue open here or move it to the CAPO repo where might be there could be more eyes on this.

Is this really related to CAPO? Maybe I missed something but it looks like CAPA on an OpenShift management cluster to me. 

Maybe we should close the issue as it's pretty old and nobody had time to dig into this for a quite a while.

**Comment by fabriziopandini** [comment]
/close
We can always a new issue if we manage to collect more info
