### ISSUE TITLE
Document/relax template immutability requirements

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#3283]
Now that #3181 has been merged, we should provide some better documentation and guidelines for providers implementing templates allowing for the templates to be mutable. 

From Cluster API perspective, _template references_ are immutable, as in you'd have to change the whole reference to have a MachineSet or KCP rollout new machines. Providers can allow mutability for fields that can be mutated in place.

/kind cleanup
/kind documentation
/milestone v0.3.x

**Comment by fabriziopandini** [comment]
@vincepri we already have https://cluster-api.sigs.k8s.io/user/concepts.html?highlight=immu#machine-immutability-in-place-upgrade-vs-replace documenting mutability for infrastructure provider templates
Is this enough to close this issue or there is something else you want to add?

**Comment by vincepri** [comment]
Yes, sounds good thanks for the link!

/close
