### ISSUE TITLE
Add tests for listDecendents fetching MachinePools

### ISSUE THREAD

**Issue by prankul88** [kubernetes-sigs/cluster-api#3294]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
This is a follow up to PR #3196 

**What did you expect to happen:**
Add test for the functionality added.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by rudy2steiner** [comment]
I'd like to work on this issue, please assign to me!

**Comment by fabriziopandini** [comment]
/remove-lifecycle stale
@rudy2steiner is there any update on this issue?

**Comment by rudy2steiner** [comment]
sorry, I'm new to k8s and  try to finish this work as soon as possible!

**Comment by fabriziopandini** [comment]
@wangzewang any update on this issue?
