### ISSUE TITLE
Potential bug during drain

### ISSUE THREAD

**Issue by dthorsen** [kubernetes-sigs/cluster-api#3300]
**What steps did you take and what happened:**
We created a cluster in AWS, and we created 3 MachineDeployments with 1 replica each, each in its own AZ.
We created a simple deployment with 3 replicas, readinessProbe with `initialDelaySeconds: 120`, and node anti-affinity so that the pods scheduled such that there was one on each Node.
We created a PDB covering this deployment that set minAvailable to 2.
We patched all 3 MachineDeployments simultaneously to add a new label to the template, with the intent to trigger a rolling update on all 3 MachineDeployments in parallel.
We observed the new Machines provision as part of the surge step.
We observed the pods for the deployment. For a short period of time (going to repeat the test to get more accurate timing, stay tuned), it appeared the PDB was being honored. One pod went down, the other 2 remained Running.
After a short while, both of the other 2 pods terminated simultaneously without regard to the PDB.

**What did you expect to happen:**
The rolling update should honor the PDB and Pod readiness status during drain.

**Anything else you would like to add:**
We are currently working to gather more detail such as timing and some additional debug logging. We were able to reproduce this issue after seeing it in a live environment.

**Environment:**

- Cluster-api version: ~v0.5.1~ v0.3.2
- Minikube/KIND version: n/a
- Kubernetes version: (use `kubectl version`): 1.16.8
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by ncdc** [comment]
Did the 2 pods that terminated simultaneously do so because their Machines were deleted as part of the MachineDeployment rolling update?

**Comment by ncdc** [comment]
Also, re Cluster-api version, v0.5.1 looks like a CAPA (AWS provider) version - which Cluster API version are you using?

**Comment by dthorsen** [comment]
> Also, re Cluster-api version, v0.5.1 looks like a CAPA (AWS provider) version - which Cluster API version are you using?

Oops. Fixed that

**Comment by dthorsen** [comment]
> Did the 2 pods that terminated simultaneously do so because their Machines were deleted as part of the MachineDeployment rolling update?

That is my suspicion but we are actively reproducing again and gathering additional detail.

**Comment by dthorsen** [comment]
/close
We have isolated this to a bug in one of our own controllers and not within CAPI.
