### ISSUE TITLE
[ClusterResourceSet] Ownership of resources 

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#3301]
Currently, resources (Secrets/ConfigMaps) have ClusterResourceSet as owner reference and they are being deleted when CRS is deleted. Owner references will possibly be used by `clusterctl move` and also might be beneficial if we want to detect changes in resources along the way when we support different apply strategies other than `ApplyOnce`.

To avoid the deletion of resources when ClusterResourceSet is deleted, we can have a finalizer that removes the owner references on CRS deletion.

**Comment by vincepri** [comment]
@sedefsavas Should this be marked as a bug? Do we want to prioritize it for this cycle?

**Comment by sedefsavas** [comment]
I don't think this is a bug, we need to decide if we want CRS resources to be cleaned up with the CRS deletion or not.

**Comment by sedefsavas** [comment]
Replica of https://github.com/kubernetes-sigs/cluster-api/issues/3399
Closing.
