### ISSUE TITLE
periodic-cluster-api-test-release-0-2 is failing linting

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#3304]
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#unit%20tests-release-0-2 is failing consistently. Something is off with the linter. I've tested manually on my laptop and get the same error. If I reduce the number of linters in use to a small number (e.g. one to three), it seems to pass. But running e.g. just `deadcode` by itself exits nonzero with nothing else printed to stdout/stderr.

/help

**Comment by hanumanthan** [comment]
Hi @ncdc Happy to pick this up. Can you give a bit more details on how to reproduce this and pointer to the file would be helpful. Thanks

**Comment by fabriziopandini** [comment]
@hanumanthan IMO you can start checking out the release 0.2 branch and running `make lint` will be enough to reproduce; the linter settings are in `.golangci.yml`

**Comment by hanumanthan** [comment]
@fabriziopandini When i run lint with `fast=false` (make lint-full) - it works fine whereas `make lint` exits with exit code 1.
**Unit test make target uses lint and not lint-full**

There are 2 ways to solve the problem
1. Upgrading golangci-lint to its latest version from 1.18.0 to 1.28.1 doesnt exit but it throws a larger problem. There are so many lint complaints. List of errors [here](https://gist.github.com/hanumanthan/d4b413afe51d752cd2825d007ee964a6)
2. Running lint with `fast=false` works with the given version.

What do you recommend ?

**Comment by fabriziopandini** [comment]
@hanumanthan I'm +1 to run lint-full in CI
@ncdc @vincepri @detiber opinions? ^^

**Comment by vincepri** [comment]
Lint-full sound good, might be worth removing the other target if it doesn't work properly. I'm not sure if it's worth fixing / upgrading.

**Comment by ncdc** [comment]
👍 lint-full.

I'm fine removing the lint target in this branch.

**Comment by detiber** [comment]
+1 to lint-full from me

**Comment by hanumanthan** [comment]
BTW there are some unit test failures in this branch. I can take a look at it if isnt being worked on though would need some help 😃

**Comment by ncdc** [comment]
@hanumanthan I don't see any failures at https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#unit%20tests-release-0-2. What were you seeing?

Closing as this issue has been resolved.

/close
