### ISSUE TITLE
 [Docs] Add experimental features section

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#3315]
We should add a section where we have a list of active experimental features with some introduction and examples on how to use each of them. 

Current experimental features are ClusterResourceSet and MachinePool.

/kind documentation

**Comment by CecileRobertMichon** [comment]
related to https://github.com/kubernetes-sigs/cluster-api/issues/3073

**Comment by fabriziopandini** [comment]
@sedefsavas 
PTAL https://github.com/kubernetes-sigs/cluster-api/pull/3325; this can simplify the UX for experimental features

**Comment by shreyasbapat** [comment]
I would like to work on it

**Comment by fabriziopandini** [comment]
@shreyasbapat we are using /lifecycle active to signal that someone is working on an issue, and in this case, it seems @sedefsavas is already working on it

**Comment by shreyasbapat** [comment]
Thanks @fabriziopandini . I am sorry for the inconvenience

**Comment by vincepri** [comment]
@shreyasbapat No worries! If you're looking for something to do, I'd suggest to filter the issues and look either for `good-first-issues` or others marked as `help-wanted`

**Comment by fabriziopandini** [comment]
@shreyasbapat No worries! We should probably highlight this convention in https://github.com/kubernetes-sigs/cluster-api/blob/master/CONTRIBUTING.md#finding-things-that-need-help (feel free to open an issue/send a PR for this 😉 )

**Comment by shreyasbapat** [comment]
> @shreyasbapat No worries! We should probably highlight this convention in https://github.com/kubernetes-sigs/cluster-api/blob/master/CONTRIBUTING.md#finding-things-that-need-help (feel free to open an issue/send a PR for this 😉 )

Added https://github.com/kubernetes-sigs/cluster-api/pull/3347 for this :D

**Comment by vincepri** [comment]
/milestone v0.3.9
@sedefsavas are you still working on this?

**Comment by vincepri** [comment]
@sedefsavas Are you still working on this?

**Comment by sedefsavas** [comment]
Yes, will push an initil PR for it soon to get feedback.
