### ISSUE TITLE
Provide a means to opt-out of kube-proxy updates in KCP

### ISSUE THREAD

**Issue by tvs** [kubernetes-sigs/cluster-api#3318]
**User Story**

As a user, I would like to opt-out of the kube-proxy updates provided by the KCP. In air-gapped systems we cannot pull container images, they're instead baked into the image and pre-loaded to the container runtime. When performing a rolling update, it then becomes important to guide the add-ons updates so that they roll out in a synchronized fashion with the new Machines.

**Detailed Description**

Similar to #3023, provide an annotation that will skip the kube-proxy update in KCP.

/kind feature

**Comment by vincepri** [comment]
Thanks @tvs 

/help
/milestone v0.3.x
/priority important-soon

**Comment by vincepri** [comment]
/assign @tvs 
/milestone v0.3.7

Going to have this in v0.3.7 given that it's a pretty small change.

**Comment by fabriziopandini** [comment]
+1
