### ISSUE TITLE
Builds should be updated to Go 1.15, once we adopt Kubernetes 1.19

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#3322]
See https://github.com/kubernetes/kubernetes/issues/92521 for more information, opened this issue to track it for v1alpha4.

/kind cleanup
/area dependency
/milestone v0.4.0

**Comment by cpanato** [comment]
Kubernetes is built now with go1.15
@vincepri should we proceed with the changes?

**Comment by vincepri** [comment]
Soon-ish 😄 , once we open the main branch to v1alpha4/v0.4.x and update controller runtime, we should we good to make the change in test-infra

**Comment by justaugustus** [comment]
go1.15.1 is scheduled for 9/1.
I'd say wait until kubernetes/kubernetes updates before picking it up.

**Comment by bboreham** [comment]
> adopt Kubernetes 1.19
> update controller runtime

Should there be issues for these?

**Comment by vincepri** [comment]
@bboreham Will open something once controller runtime upstream is more stable / has a release tag

**Comment by bboreham** [comment]
Is it written somewhere why cluster-api has not updated to controller-runtime 0.6?

**Comment by vincepri** [comment]
Timing + it required breaking changes which we can't do until next release
