### ISSUE TITLE
Make Tilt to work with envsubst style variables

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3326]
https://github.com/kubernetes-sigs/cluster-api/pull/3270 introduced support for envsubst style variable in the component yaml, but the Tilt file still implements variable substitution without envsubst
 
https://github.com/kubernetes-sigs/cluster-api/blob/492970b1c9d14551f04e819a49e4216c9927fddd/Tiltfile#L185-L192

As a workaround, it is possible to use `kustomize_substitutions`  in `tilt-settings.json`, but this is far from ideal...

```
  "kustomize_substitutions": {
    ...
    "CLUSTER_RESOURSE_SET_FEAUTURE:=false": "false",
    "MACHINE_POOL_FEATURE:=false": "false"
  }
```

**Comment by CecileRobertMichon** [comment]
This is how CAPZ dealt with it if it helps https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/82b903d6eaef7eff13b4c89602f965dc2fa76b0c#diff-1a474bf970407efc3332970120c1a429

**Comment by fabriziopandini** [comment]
I think we will be more on the safe side if we expose a utility under hack/tools similar to envsubst but backed by the clusterctl library, but this can be also a follow up improvement
