### ISSUE TITLE
Remove current metrics due to memory consumption and loading of TSDBs

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#3327]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Reviewing the published Prometheus metrics, these should probably be revised:
It isn't recommended to use gauge metrics with per cluster and namespace labels. This is because every cluster will create a new gauge, which is never GC'd, and creates a new time series in Prometheus, costing CPU, memory and disk space.
For a large churn of clusters, the controller would need to be frequently restarted to delete old counters from memory. 

Conditions are the correct way to provide per-cluster status information, and the existing metrics should be removed. 

Example replacement metrics would be:
Old:
```go 
	ClusterControlPlaneReady = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "capi_cluster_control_plane_ready",
			Help: "Cluster control plane is ready if set to 1 and not if 0.",
		},
		[]string{"cluster", "namespace"},
	)
```
New, though difficult to track for creation and deletion of resources:
```go 
	ActiveClusters = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "cluster_api_kubeadm_control_planes_active",
			Help: "Number of active kubeadm control planes managed by the controller",
		},
		nil,
	)
```

```go 
	KubeadmControlPlaneConditions = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "cluster_api_kubeadm_control_plane_current_conditions",
			Help: "Current conditions for all control planes managed by Cluster API kubeadm control plane controller",
		},
		[]string{"condition","value"},
	)
```

where the condition an actual value would both be labels. The dimensionality is finite here as arbitrary user-provided values are not recorded.

An easier metric, which doesn't rely on keeping track of clusters would be:

```go 
	KubeadmControlPlaneConditions = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "cluster_api_kubeadm_control_plane_reconciled_conditions_total",
			Help: "Count of all conditions which have been reconciled",
		},
		[]string{"condition","value"},
	)
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 0.3.6
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by ncdc** [comment]
Maybe we should split this into 1 issue for removing all the current metrics (they duplicate information directly available on Clusters, Machines, etc), and 1 for coming up with some new metrics? cc @wfernandes as I think you authored the original metrics.

**Comment by wfernandes** [comment]
I think it would be best to split into multiple issues as well. This one can focus on removing irrelevant, misleading or duplicate metrics.
If we want to come up with new metrics we should define what they are and how to calculate them. 🙂 

Linking this issue https://github.com/kubernetes-sigs/cluster-api/issues/1477 since it feels related. Maybe we can continue to use this issue to track what metrics operators may be interested in a world of Clusters with Conditions.
