### ISSUE TITLE
Remove kubeadm token creation duplication between GCP and Vsphere controllers

### ISSUE THREAD

**Issue by spew** [kubernetes-sigs/cluster-api#333]
We need to refactor out the bit of token creation code into a module that is more shareable and unit tested. It could support different token creation strategies over time. For comparison here are the two implementations:

VSPHERE:
```
func getKubeadmToken() (string, error) {
	tokenParams := kubeadm.TokenCreateParams{
		Ttl: time.Duration(10) * time.Minute,
	}
	output, err := kubeadm.New().TokenCreate(tokenParams)
	if err != nil {
		return "", fmt.Errorf("unable to create kubeadm token: %v", err)
	}
	return strings.TrimSpace(output), err
}
```

GCP
```
type GCEClientKubeadm interface {
	TokenCreate(params kubeadm.TokenCreateParams) (string, error)
}

func (gce *GCEClient) getKubeadmToken() (string, error) {
	tokenParams := kubeadm.TokenCreateParams{
		Ttl: time.Duration(10) * time.Minute,
	}
	output, err := gce.kubeadm.TokenCreate(tokenParams)
	if err != nil {
		glog.Errorf("unable to create token: %v", err)
		return "", err
	}
	return strings.TrimSpace(output), err
}
```

**Comment by spew** [comment]
Note that the TrimSpace is needed because the exec command itself can / will append a space. It would not be needed if we had a library form of this to call into.

**Comment by spew** [comment]
We should probably create a new package named tokengen or the like and then have an implementation that currently uses `kubeadm token create` and eventually gets swapped out for one that calls into a library directly (when available).

**Comment by roberthbailey** [comment]
Since these implementations have been moved out of this repo I'm going to close this issue. If we find common code across provider repos we can certainly move it into shared libraries here, but I don't think we should worry too much about doing it early in the project when folks are iterating quickly. 

/close
