### ISSUE TITLE
Move away from using the actual CRDs for the provider contracts

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#3331]
**User Story**

As a developer, I would like to move away from using information in the actual CRDs (labels) to represent the provider contracts, so that the Cluster API controllers no longer need read permissions on CRDs.

**Detailed Description**

https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html#apply-the-contract-version-label-clusterx-k8sioversion-version1_version2_version3-to-your-crds describes how a provider can inform Cluster API controllers which specific provider API versions align with Cluster API API versions.

The Cluster API manager currently requires get/list/watch permissions on customresourcedefinitions because of this. We should try to avoid this, and instead move to a different resource that can provide this information (such as a `Provider` CRD that we define).

/kind feature
/milestone v0.4.0
/kind api-change
/priority important-soon

**Comment by fabriziopandini** [comment]
FYI, we already have a Provider crd managed by clusterctl, but in this case, it describes a provider instance.
Happy to discuss how to harmonize the two concepts.

**Comment by vincepri** [comment]
Related to #3427

**Comment by CecileRobertMichon** [comment]
@fabriziopandini can we close this now that the operator work is underway?

**Comment by fabriziopandini** [comment]
@CecileRobertMichon I don't think so. 
Afaik this concept was not included in the operator proposal, and doing so will introduce an hard decency between the operator and the core API while instead the operator should be optional

**Comment by sbueringer** [comment]
As discussed in the backlog grooming on 11nd February, we are happy with our current mechanism as it is pretty lightweight and works. The only alternative we currently see is introducing another CRD, which seems like overkill.

@killianmuldoon To open an issue to improve the documentation of the contract labels in the implementers guide

/close
