### ISSUE TITLE
Document CAPD Usage and Upgrade Requirements

### ISSUE THREAD

**Issue by Arvinderpal** [kubernetes-sigs/cluster-api#3342]
**User Story**

As a developer/user I would like to have clear and accurate instructions on using CAPD for development, for testing and for just learning CAPI.

**Detailed Description**

CAPD uses KinD under-the-hood. KinD has very specific image requirements  for its Nodes (see https://github.com/kubernetes-sigs/kind/releases). In particular, specific {images,tags,digest} must be used for a given Kubernetes version. Failing to do this results in unpredictable behavior. 

In order for a user to **reliably** create clusters, she must specify {images,tags,digest} in the `DockerMachineSpec.CustomeImage`. For example, for Kubernetes version 1.16.4:
```
		kind: DockerMachineTemplate
		spec:
		  template:
		    spec:
		      customImage: "kindest/node:v1.16.4@sha256:b91a2c2317a000f3a783489dfb755064177dbc3a0b2f4147d50f04825d016f55"
```

When upgrading the Kubernetes version, the `DockerMachineSpec.CustomeImage` must be updated prior to the upgrade. For example, here we update customImage field to the appropriate value for v1.17.0:
```
kc get dockermachinetemplate -n=default test-control-plane -o json | jq '.spec.template.spec.customImage="kindest/node:v1.17.0@sha256:9512edae126da271b66b990b6fff768fbb7cd786c7d39e86bdf55906352fdf62"' | kubectl apply -f-
```
CAPD does not currently allow mutations on DockerMachineTemplate (this may change: https://github.com/kubernetes-sigs/cluster-api/issues/3338). Alternative is to create a brand new template and patch KCP/MD accordingly (see https://cluster-api.sigs.k8s.io/tasks/upgrade.html).

After the template is updated, KCP for control-plane nodes and MachineDeployment for workers can be patched. For example: 
```
kubectl get kcp -n default test-control-plane -o json | jq '.spec.version="v1.17.0"' | kubectl apply -f-

kubectl get md -n default test-md-0 -o json | jq '.spec.template.spec.version="v1.17.0"' | kubectl apply -f-
```

**Anything else you would like to add:**

The above instructions should be documented. Perhaps a good place to put them is in `test/infrastructure/docker/docs/kind.md`.

/kind feature

**Comment by Arvinderpal** [comment]
If the above sounds good to people, I can add the docs under `test/infrastructure/docker/docs/kind.md`

**Comment by fabriziopandini** [comment]
IMO this one should be merged into https://github.com/kubernetes-sigs/cluster-api/issues/3338, because the underlying problem is the same and the solution to be documented depends on the decisions we are going to take on that issue.

> In order for a user to reliably create clusters, she must specify {images,tags,digest} in the DockerMachineSpec.CustomeImage

FYI in E2E, we are using extensively CAPD without specifying a `CustomeImage`; if you leave the custom image field empty, CAPD will pick up the official kindest image for a kubernetes version (if available on the docker hub)

**Comment by Arvinderpal** [comment]
> IMO this one should be merged into #3338, because the underlying problem is the same and the solution to be documented depends on the decisions we are going to take on that issue.
The issues are separate. The underlying problem here is that the user may use a specific release of KinD (e.g. 0.7 vs 0.8), but if she does not specify a digest corresponding to {K version, KinD release}, then weird errors can arise -- I experienced these myself and would like to save others the trouble :)
I gave the upgrade as an example and we can keep that discussion in #3338

> FYI in E2E, we are using extensively CAPD without specifying a `CustomeImage`; if you leave the custom image field empty, CAPD will pick up the official kindest image for a kubernetes version (if available on the docker hub)
In my experience, certain combinations do pass, but others do not (thus the need to document). 
I see that our e2e tests do the following upgrade: 
```
KUBERNETES_VERSION_UPGRADE_FROM: v1.17.2
KUBERNETES_VERSION_UPGRADE_TO: v1.18.2
```
I would suspect that they are passing b/c we are likely pulling the latest kind release (0.8.1) and the images (pulled from docker hub) without specifying the digest, correspond to this (latest) release. 
Can you point me to the scripts for the test infra? I can confirm this.

**Comment by fabriziopandini** [comment]
This is the CI script https://github.com/kubernetes-sigs/cluster-api/blob/d40fcd73e6c1bdf2bd6e90f91c0a8ecaaeb184ac/scripts/ci-e2e.sh

CAPD uses kind images to get something will all the prerequisites in places, but internally it does not rely on kind for other tasks and it should not be impacted by kind v0.7 / v0.8 differences (at least for what I'm aware of).

Instead, for the KIND cluster hosting the management cluster, know problems are documented e.g [here](https://cluster-api.sigs.k8s.io/clusterctl/developers.html#additional-steps-for-the-docker-provider).

If this is the case, IMO it is not viable to ask users to use `customImage` and docker image digest, so I would like to understand what kind of error arise and get them fixed in CAPD.

**Comment by Arvinderpal** [comment]
@fabriziopandini I realize that capd uses kind more as a lib and does not actually call the executable. However, it does use kind. In particular, go.mod seems to pull a kind at a specific commit: https://github.com/kubernetes-sigs/cluster-api/blob/master/go.mod#L42

This commit by @randomvariable  made the change from the standard 0.7.0. Was the choice to use kind at 981bd80d3802 seems arbitrary?.
```
git show be2d5957276d416020784e64c41430c709ed89c6
...
-       sigs.k8s.io/kind v0.7.0
+       sigs.k8s.io/kind v0.7.1-0.20200303021537-981bd80d3802

```

I'm not saying that this is necessarily causing the problems I'm seeing; however, pulling in kind from arbitrary commit points seems risky to me.

**Comment by randomvariable** [comment]
Not sure why I let it hang off that commit. I think it was an oversight.

**Comment by fabriziopandini** [comment]
hopefully, the import will be fixed by https://github.com/kubernetes-sigs/cluster-api/issues/2992

**Comment by randomvariable** [comment]
Thinking back, I think at the time, the repo was flaking a lot in the CAPD tests, and bumping the version was one of the things I was trying to fix it.

**Comment by Arvinderpal** [comment]
Interesting. Hopefully the upgrade to 0.8 will be smooth :wink: 
I documented the issue I was seeing in: https://github.com/kubernetes-sigs/cluster-api/issues/3367
I'll close this issue.
