### ISSUE TITLE
[question] do we support external LB? 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#3352]
**User Story**

As a [developer/user/operator] I would like to [high level description] for [reasons]

**Detailed Description**

this inspired from https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/584

do cluster-api has any provider support external LB solution? e.g I can create several master nodes behind a external LB ?

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by ncdc** [comment]
We do have Cluster's `spec.controlPlaneEndpoint`, which is a tiny bit of foundation for this (it provides a stable endpoint for the control plane). Some providers do support load balancers, such as cluster-api-provider-aws (CAPA), which manages an ElasticLoadBalancer for the control plane, including VM membership. This is baked in to CAPA, and you can't currently swap it out for another load balancer solution.

We do have #1250 as a request for a load balancer provider, along with a proposal for it at https://docs.google.com/document/d/17Z_F_lmv4WgXaG9TaayOwwpCGRRoBxLbY070TSXDhvs/edit. I would be interested in picking this back up and seeing it move forward. Do you mind if we close this and proceed in #1250?

**Comment by jichenjc** [comment]
sure, this works totally fine with me, thanks a lot
