### ISSUE TITLE
[ClusterResourceSet] ClusterResourceSetBinding is not cleaned up

### ISSUE THREAD

**Issue by maplain** [kubernetes-sigs/cluster-api#3357]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
1. Create a Cluster and apply a label;
2. Create a CRS selecting the above Cluster and a corresponding Secret;
3. After the CRS's corresponding Secret gets applied, delete the cluster;
4. Check the ClusterResourceSetBinding:
```bash
➜  ✗ k get clusterresourcesetbinding bkp-s-1 -o yaml
apiVersion: addons.cluster.x-k8s.io/v1alpha3
kind: ClusterResourceSetBinding
metadata:
  creationTimestamp: "2020-07-16T18:20:02Z"
  generation: 2
  name: bkp-s-1
  namespace: default
  ownerReferences:
  - apiVersion: addons.cluster.x-k8s.io/v1alpha3
    blockOwnerDeletion: true
    controller: true
    kind: ClusterResourceSet
    name: cluster-components
    uid: 9f3b3040-94bb-49b2-8f92-bad9fb0dcf25
  resourceVersion: "42649"
  selfLink: /apis/addons.cluster.x-k8s.io/v1alpha3/namespaces/default/clusterresourcesetbindings/bkp-s-1
  uid: 31e33402-3d56-4252-93c5-982a9308bfad
spec:
  bindings:
  - clusterResourceSetName: cluster-components
    resources:
    - applied: true
      hash: sha256:fa2042db4c7f3023976888a616c02cba1b87cf01970ddea0ae20516092255a47
      kind: Secret
      lastAppliedTime: "2020-07-16T18:20:03Z"
      name: cluster-components
```
5. Create the cluster with the same name;
6. Check the cluster, no resource in the CRS is applied

**What did you expect to happen:**
1. CRS is applied when Cluster is deleted and created back;

**Anything else you would like to add:**
ClusterResourceSetBinding persists information that should expire when the matching resource is gone.

**Environment:**

- Cluster-api version: v0.3.7
- Minikube/KIND version: kind v0.7.0 go1.13.6 darwin/amd64
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by ncdc** [comment]
cc @sedefsavas
