### ISSUE TITLE
Standardize polling on wait.PollImmediate(...)

### ISSUE THREAD

**Issue by spew** [kubernetes-sigs/cluster-api#336]
In PR https://github.com/kubernetes-sigs/cluster-api/pull/331 we were able to reduce the amount of time required to run a subset of the project unit tests by ~80% by switching from Poll(...) to PollImmediate(...).

We should move every other location to use PollImmediate unless there is a good reason why we need a delayed Poll.

**Comment by roberthbailey** [comment]
There are two remaining uses of `util.Poll(...)`, both in https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/machineset/controller.go.
