### ISSUE TITLE
[clusterctl] refactor `config` subcommand

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#3360]
**User Story**

As a [developer/user] I would like to have a separate subcommand `clusterctl generate` that generates the yaml required to create workload clusters and infrastructure providers.

**Detailed Description**

Currently `clusterctl` has the following commands that prints out yaml for the workload cluster and infrastructure providers:
```
clusterctl config cluster <cluster-name>
clusterctl config provider --infrastructure <infra:verssion> -o yaml
```
Since this may not be as intuitive to many, we can break these specific commands to:
```
clusterctl generate cluster <cluster-name>
clusterctl generate provider <infra:version>
```
These above commands will evaluate the variables present in the templates. These commands should return an error if a variable does not have a value.

**Anything else you would like to add:**

[Original Slack Discussion](https://kubernetes.slack.com/archives/C8TSNPY4T/p1594832083125600).
Since this is clearly a breaking change, we propose this for v1alpha4 release.

/kind feature
/area clusterctl

**Comment by fabriziopandini** [comment]
Question: are we planning to maintain `clustetrctl config` commands? I see some value in `clusterctl config provider --infrastructure <infra:verssion>` (without -o yaml)

**Comment by wfernandes** [comment]
Yes. I still believe that those commands provide value. Currently we have:
```
# Display the list of providers and their repository configurations that are shipped within clusterctl
clusterctl config repositories
# Display information about a provider. clusterctl fetches the provider components from the provider repository
clusterctl config provider --infrastructure <infra:version>
```
As of now I don't think we should remove them.

Another thought:
We also have a `get` verb that _may_ be added into clusterctl as part of #3293. The difference I see between `config` and `get` is that `get` could mean to retrieve resources and information from the management cluster specifically. 

If we feel that the above definition of `get` is too restrictive we could consider expanding it and moving the above subcommands into `get`. My only concern here is that if a user does `clusterctl get provider` they may confuse it to return information that is present in `kubectl get providers`.

**Comment by wfernandes** [comment]
Question to the community: 
Currently, `clusterctl config provider --infrastructure aws -o yaml` does NOT do variable substitution. That is, it prints out the original yaml with the variables. Do we want the `clusterctl generate provider --infrastructure aws` to process variables and return the final yaml?
That is, do we want something like `clusterctl generate provider -i aws | kubectl apply -f -`?

**Comment by vincepri** [comment]
`clusterctl generate provider -i aws | kubectl apply -f -` This should great to me, it'd be great to have also a `--raw` option that doesn't do variable substitution

**Comment by wfernandes** [comment]
Makes sense. Currently, `clusterctl config provider -i aws -o yaml` doesn't do variable substitution. So that functionality can be represented with the `--raw` option. 

I also think adding the `--from` flag to the `clusterctl generate provider` command might be helpful for those wanting to point to a specific file url path.

I know that this particular issue is marked for v0.4.0 but I think it's closely related to https://github.com/kubernetes-sigs/cluster-api/issues/3379. And we may be able to add this command in. This way the change will be additive and non-breaking to users. 

WDYT? I'm fine with whatever direction we choose.

**Comment by vincepri** [comment]
I'm +1 on the --from flag as well, let's make sure it's consistent with the rest of the commands. 

I'd suggest to introduce the `generate` verb in this v0.3.x, and wait to have move these commands in v0.4.0. `clusterctl generate yaml -` could be a good starting point to get the template envsubst command we need

**Comment by wfernandes** [comment]
Referencing this issue comment since it is closely related and provides specific "user stories" for these commands.
https://github.com/kubernetes-sigs/cluster-api/issues/3379#issuecomment-664663534

**Comment by vincepri** [comment]
Do we want to keep this on the roadmap for v1alpha4?

**Comment by wfernandes** [comment]
We currently have `clusterctl generate yaml`. The behavior of the commands suggested above `clusterctl generate cluster` and `clusterctl generate provider` may be affected with the management cluster operator work.

I think we can keep this in the roadmap as a nice-to-have since the intent of this issue is to improve the UX for clusterctl.

**Comment by vincepri** [comment]
@fabriziopandini Can we do this before v0.4.0 release? Seems could be a breaking change.

**Comment by fabriziopandini** [comment]
@vincepri I think yes, but I'm not entirely sure about the ask:

Add 
```
clusterctl generate cluster <cluster-name>
clusterctl generate provider <infra:version>
```

Keep config commands?
Change some behavior (add --raw flag)?

**Comment by vincepri** [comment]
`config` would probably be deprecated in favor of `generate`

**Comment by vincepri** [comment]
Then we can remove it in a next release

**Comment by vincepri** [comment]
@shysank Are you interested in tackling this issue?

**Comment by fabriziopandini** [comment]
/re-open
given that some work still has to be done (--raw if remember well; @shysank to keep me honest here)

**Comment by fabriziopandini** [comment]
Uhmm it seems I can re-open this, @shysank what about opening a new issue to track the missing part

**Comment by shysank** [comment]
Done
