### ISSUE TITLE
[book] Add advanced section to document using kustomize + yaml templates

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api#3373]
For some users, clusterctl is not flexible enough to configure clusters past the quickstart experience. Many of the providers provide example "flavor" templates as references. However, for more advanced users that need greater control over the cluster configuration, the templates need to be curated to fit their use case (eg. add custom images, modify cloud provider args, etc.)

In the future, a [templating solution](https://github.com/kubernetes-sigs/cluster-api/issues/3252) might be integrated into clusterctl and fill the gap between the day 0 experience and the flexibility required by advanced users.

In the meantime, we should consider adding an advanced section in the documentation about using kustomize and templates, possibly with a note about the future templating engine in clusterctl. Currently, the Cluster API book only covers clusterctl as UX for cluster API which might make users think that applying yaml templates without using clusterctl config is not supported anymore (and the only other option is the overrides directory which is intended for developers, not users).

See also https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/776

**Comment by scottslowe** [comment]
I can take this issue. I have some existing content on using `kustomize` with Cluster API that should be straightforward to adapt and get added to the documentation.

/assign

**Comment by vincepri** [comment]
@scottslowe Are you still working on this issue?

**Comment by scottslowe** [comment]
@vincepri Yes, I am. There's a lot here, so I've been trying to figure out just how much to include/exclude. For example, should I include information on customizing the `kustomize` transformers so they are more Cluster API "aware"?

**Comment by vincepri** [comment]
Can you provide an example?

**Comment by scottslowe** [comment]
For example, without customizing the NameReference transformer then the use of the namePrefix and nameSuffix directives won't work properly; the `metadata.name` field will get updated, but fields like the `spec.infrastructureRef.name` field of an AWSCluster object won't get updated. You then end up with a broken manifest.

This blog post I wrote has some additional information: https://blog.scottlowe.org/2020/03/17/kustomize-transformer-configuration-cluster-api-v1alpha3/

**Comment by fabriziopandini** [comment]
I think that we can present this by use cases/ complexity:
- Basic
  - Use kustomize to build templates variant (assembling together different templates bits but without applying transformation, something like what we are doing for E2E test)
- Advanced
  - Make name prefix/suffix customisable

This has the advantage that we can start by few use cases and then add more in incrementa follow ups
