### ISSUE TITLE
kustomize_substitutions in tilt-settings.json is broken

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#3375]
**What steps did you take and what happened:**
1. Try to use `kustomize_substitutions` for variables that you do **not** set as environment variables
1. These placeholders are replaced with the empty string

**What did you expect to happen:**
1. Successful replacement from `kustomize_substitutions` from `tilt-settings.json`

**Anything else you would like to add:**
The change to use kustomize with envsubst (#3361) accidentally broke this. We can maybe try to copy all the substitutions into `os.environ` before running kustomize.

/kind bug

**Comment by vincepri** [comment]
/milestone v0.3.x

Chatting with @wfernandes, I'd like to see a `clusterctl` generic command that
- Takes any files as input, uses our internal envsubst implementation, and prints out the result.
- It has a `--variables` flag to print out all the variables
  - This can be used to look at the defaults, print out all the required variables

**Comment by ncdc** [comment]
/assign
/lifecycle active
FYI @alexeldeib
