### ISSUE TITLE
MachineSet should have last transition time for replica counts in status

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes-sigs/cluster-api#3380]
**User Story**

As a developer I would like to build components that can take actions when the machineset is settled or unsettled for custom integrations.

**Detailed Description**

I want to prevent terminating a current machine's instance (using deletion lifecycle hooks) until a replacement machine is created.  One way to enable this workflow is to prevent removal until the machineset has the necessary number of ready/available replicas.  However, this is a potential race condition between the time a machine is deleted and the time a machineset updates those counts.  Additionally, if the machineset is disabled for any reason, the information will be stale, so having the transition time will inform me that my action is taking place after the machineset has been reconciled and not before.

To be clear, this transition timestamp should be updated when the replica counts have changed.

/kind feature

**Comment by michaelgugino** [comment]
@vincepri you mentioned during weekly meeting you might have some preferred implementation for this (conditions, I think you said?)  Could you provide a synopsis here?  I'd like to get a patch together.

**Comment by vincepri** [comment]
Yeah, we could add Conditions, although I just noticed that the MachineSet type doesn't have the field yet https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha3/machineset_types.go#L110.

Depending on your timeline, I'm fine for now to have a timestamp, we could move to a condition later and deprecate the field.

**Comment by michaelgugino** [comment]
Do we want to model conditions roughly after pod conditions?  https://godoc.org/k8s.io/api/core/v1#PodCondition

If we think conditions will be added, we might as well make this the first one.  What do we want to name it?  I'm mostly interested in when all replicas are available.  Maybe "AllReplicasAvailable" ?

We can do just timestamp for now if we think conditions is going to be quite involved.  I think settling on a basic model for conditions should be simple, though, and we can just add conditions as we see fit.

**Comment by vincepri** [comment]
If we add conditions, we should be consistent with the rest of the conditions that have already been added on Cluster/Machine. You can see more in https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha3/condition_consts.go for some examples

**Comment by vincepri** [comment]
We have our own type in https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha3/condition_types.go#L55-L88

**Comment by michaelgugino** [comment]
Those conditions seem suitable to me.  I'll try to put something together soon.
