### ISSUE TITLE
Should we utilize conditions for deletion flows

### ISSUE THREAD

**Issue by gab-satchi** [kubernetes-sigs/cluster-api#3383]
Conditions have been used so far to show the operational state of an object (and its dependents) along with the provisioning progress. This issue is to discuss potentially using conditions during the scale down / deletion flow. 

If conditions should be used for deletion: 
- What should happen to existing conditions that describe the provisioning / operating phases of an object? for ex: VPCReady, InfrastructureReady
- What happens to the summary Ready condition. The Ready condition is meant to indicate an object is operationally ready and is a summary of its other conditions. 

If conditions shouldn't be used for deletion, how can we provide the "at a glance" view of the entire cluster during deletion?

/kind design

**Comment by detiber** [comment]
+1 from me for utilizing conditions during the deletion flow.

As a side note, I think it might not be a bad idea to bubble up that reconciliation is paused on a resource (either from having the annotation directly or transitively through Cluster.Spec.Paused being true).

**Comment by vincepri** [comment]
+1 from me as well

**Comment by vincepri** [comment]
/milestone v0.4.0

@fabriziopandini To check / open different issues with action items for Cluster API.
@randomvariable @yastij @CecileRobertMichon to open different issues in each infrastructure provider.

**Comment by fabriziopandini** [comment]
/assign
/lifecycle active

I have sent a PR proposing a solution:

> What should happen to existing conditions that describe the provisioning / operating phases of an object? 

Those conditions (or some of those conditions) transition from status=True to status=False with reason deleting

> What happens to the summary Ready condition

The Ready condition reflects the above change and transition to status=False with reason deleting
