### ISSUE TITLE
failed to run [u'kustomize', u'build', u'./config']: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ximbal** [kubernetes-sigs/cluster-api#3390]
**What steps did you take and what happened:**
First time taking out cluster api for a spin.

Followed the steps from the book, to run a local deployment with Docker
In a terminal tried the following
```
$cd ~/Development/explorations/cluster-api
$make -C test/infrastructure/docker docker-build REGISTRY=gcr.io/k8s-staging-cluster-api
$make -C test/infrastructure/docker generate-manifests REGISTRY=gcr.io/k8s-staging-cluster-api
$cat > clusterctl-settings.json <<EOF
{
  "providers": ["cluster-api","bootstrap-kubeadm","control-plane-kubeadm", "infrastructure-docker"]
}
EOF
$cat > kind-cluster-with-extramounts.yaml <<EOF
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
EOF
$kind create cluster --config kind-cluster-with-extramounts.yaml
$kind get clusters
$kind load docker-image gcr.io/k8s-staging-cluster-api/capd-manager-amd64:dev
$cat > ~/.cluster-api/clusterctl.yaml <<EOF
providers:
  - name: docker
    url: $HOME/.cluster-api/overrides/infrastructure-docker/latest/infrastructure-components.yaml
    type: InfrastructureProvider
EOF
$cmd/clusterctl/hack/local-overrides.py
```
getting this:

```
$ cmd/clusterctl/hack/local-overrides.py
clusterctl local overrides generated from local repositories for the cluster-api, bootstrap-kubeadm, control-plane-kubeadm, docker providers.
in order to use them, please run:

Traceback (most recent call last):
  File "cmd/clusterctl/hack/local-overrides.py", line 235, in <module>
    print_instructions(overrides)
  File "cmd/clusterctl/hack/local-overrides.py", line 220, in print_instructions
    for name, type, next_version in overrides:
  File "cmd/clusterctl/hack/local-overrides.py", line 173, in create_local_overrides
    components_yaml = execCmd(['kustomize', 'build', os.path.join(repo, config_folder)])
  File "cmd/clusterctl/hack/local-overrides.py", line 121, in execCmd
    raise Exception('failed to run {}: {}'.format(args, e))
Exception: failed to run [u'kustomize', u'build', u'./config']: [Errno 2] No such file or directory
```

**What did you expect to happen:**
Run the local-overrides.py 

**Anything else you would like to add:**

What am I doing wrong/missing?

Thanks.

Book documentation, jumping from one section to another, not ideal.
Book documentation, incomplete to spin up a local docker, or at least missing a clear example, you're reading about docker and the example relates to AWS!

**Environment:**

- Cluster-api version: 
$ clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.7-48-60a6daf4b9ecb7", GitCommit:"60a6daf4b9ecb74a9111b3269e7016988a8afc00", GitTreeState:"clean", BuildDate:"2020-07-23T17:31:33Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
- Minikube/KIND version:
$ kind version
kind v0.8.1 go1.14.4 darwin/amd64
- Kubernetes version: (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`):
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.6 (18G4032)
      Kernel Version: Darwin 18.7.0
      Boot Volume: HD
      Boot Mode: Normal
      Computer Name: uo
      User Name: XXXXXXXX
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 6 days 5:21

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
Hi @ximbal, do you have `kustomize` installed and on your path? You can install it on Mac using `brew install kustomize`

**Comment by ximbal** [comment]
That helped, now I am getting:
```$ cmd/clusterctl/hack/local-overrides.py
clusterctl local overrides generated from local repositories for the cluster-api, bootstrap-kubeadm, control-plane-kubeadm, docker providers.
in order to use them, please run:

Traceback (most recent call last):
  File "cmd/clusterctl/hack/local-overrides.py", line 235, in <module>
    print_instructions(overrides)
  File "cmd/clusterctl/hack/local-overrides.py", line 220, in print_instructions
    for name, type, next_version in overrides:
  File "cmd/clusterctl/hack/local-overrides.py", line 159, in create_local_overrides
    assert p is not None, 'invalid configuration: please specify the configuration for the {} provider'.format(provider)
AssertionError: invalid configuration: please specify the configuration for the docker provider```

Where clusterctl-setting.json 
```
{
  "providers": ["cluster-api","bootstrap-kubeadm","control-plane-kubeadm", "docker"]
}```

and

~/.cluster-api/clusterctl.yaml
```
providers:
  - name: docker
    url: $HOME/.cluster-api/overrides/infrastructure-docker/latest/infrastructure-components.yaml
    type: InfrastructureProvider
```

Thanks for the help.
