### ISSUE TITLE
Conformance Tests for Clusters with Cluster API enabled

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#34]
_From @rsdcastro on January 29, 2018 23:15_

_Copied from original issue: kubernetes/kube-deploy#543_

**Comment by rsdcastro** [comment]
This item should cover how to test that a cluster that has cluster API enabled is comformant, which means that E2E scenarios via cluster API on the particular provider that is enabled in the cluster are working.

**Comment by rsdcastro** [comment]
cc @AishSundar

**Comment by AishSundar** [comment]
@rdc is this item tracking setting up CI for ClusterAPI Conformance tests or is it looking for guidance on how to trigger an one-off e2e conformance test run against an UP'ed cluster? If its the former is there a milestone or timeline we are looking for this to be ready?

**Comment by dpb587-pivotal** [comment]
Cross-referencing... this is now documented as a Validation Requirement in the [Cluster API Scopes and Objectives](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/scope-and-objectives.md):

> Cluster API MUST have conformance tests to ensure that Cluster API and a given provider fulfill the expectations of users/automation.

**Comment by timothysc** [comment]
TODO: outline a reasonable action plan so newcomers could work on this.

**Comment by timothysc** [comment]
Closing b/c we are creating new e2es this cycle and we'll visit real-real conformance once we approach beta.
