### ISSUE TITLE
Mechanism to migrate workload clusters across providers

### ISSUE THREAD

**Issue by sb1975** [kubernetes-sigs/cluster-api#3407]
**User Story**

As an operator I would like to have the ability to migrate my workload Cluster from one Provider to another(for example from a Baremetal Cluster to AWSCluster). This could be needed due to Business reason, strategic move towards a Cloud Provider or simply for cost savings. 

**Detailed Description**

clusterctl migrate --source-provider metal3 --target-provider aws --cluster-name my-cluster

(the above is just an example the actual command could be different but provides the functionality to migrate workload cluster from one Cloud PRovider to another Cloud Provider.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by ncdc** [comment]
What sequence of actions would you expect this migrate command to perform?

**Comment by detiber** [comment]
There are a handful of issues that would need to be solved that make me default to want to say that this is not within the scope of the Cluster API project:
- backup/restore of etcd data between workload clusters
- workload clusters are expected to maintain a static api endpoint and there is no way to migrate a static api endpoint between different infrastructure providers in a generic way
- any ingress or services of type load balancer used for incoming traffic for applications deployed on a workload cluster cannot be migrated between different environments in a generic way
- any persistant volume storage used by applications would not be able to be migrated in a generic way between the different environments.

This feels to me like a problem that needs to be solved at a layer above Cluster API that can take the above issues into account.

**Comment by vincepri** [comment]
Closing this issue for now, given that it might not be something that Cluster API can do today, or that we can put on the roadmap.

/close
