### ISSUE TITLE
Transition tilt-settings file to tilt_config

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api#3415]
**User Story**

As a [developer] I would like to consistent configuration in my tilt file so I can put configuration in a single place.

**Detailed Description**

Currently as a developer I create a `tilt-settings.json` as defined on https://cluster-api.sigs.k8s.io/developer/tilt.html#create-a-tilt-settingsjson-file

I believe the `tilt-settings.json` file was from a time before `tilt_config.json` was a [documented way](https://docs.tilt.dev/tiltfile_config.html) of doing project specific settings.

**Anything else you would like to add:**
We ran into this in CAPZ from of a [contribution](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/templates/flavors/README.md#from-tilt-config) that added some additional the settings to the `tilt_config.json`. It would be useful to consolidate the settings to the a single file to the newly recommended tilt config file.

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
/remove-lifecycle stale
I think it is important to keep up with tilt improvements

**Comment by CecileRobertMichon** [comment]
/close 

due to https://github.com/kubernetes-sigs/cluster-api/pull/5156#issuecomment-906809788
