### ISSUE TITLE
TKG CLI Install Failure

### ISSUE THREAD

**Issue by markedwards77** [kubernetes-sigs/cluster-api#3416]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
I was trying to deploy the TKG management cluster to a vSphere lab environment using the TKG CLI on a windows 10 latpop.  This was the first time doing this so no previous configuration existed on the machine but each time I tried to deploy via the installer interface or CLI I got the error:-  
"unable to set up management cluster, : unable to build management cluster configuration: unable to get template: failed to read "cluster-template-dev.yaml" from provider's repository "infrastructure-vsphere": failed to read file "C:\\Users\\Mark%20Edwards\\.tkg\\providers\\infrastructure-vsphere\\v0.6.5\\cluster-template-dev.yaml" from local release v0.6.5" 

The file is there and accessible.

**What did you expect to happen:**
The TKG install fails at step 1/8 due to above error, I expect to complete.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I created a new local user account (tkg) and ran the install in the same way using this account with the configuration files created under c:\users\tkg\.tkg.  This worked without issue so I believe the problem to be with the space in my name and hence a space in the file path.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): v1.18.3+vmware.1
- OS (e.g. from `/etc/os-release`): Windows 10

/kind bug
/area clusterctl
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
Hi @markedwards77 @wfernandes,

For TKG specific issues, bugs, or support, please refer to VMware specific documentation and reporting channels. 

@wfernandes If we have identified a potential bug in `clusterctl` here, let's open a different issue with clusterctl specific context. 

I'm going to go ahead and close this for now, we can pick this up in the proper support channels separately.

/close
