### ISSUE TITLE
MD RollingUpdate support to only add new node after one old node deleted completely

### ISSUE THREAD

**Issue by jzhoucliqr** [kubernetes-sigs/cluster-api#3417]
**User Story**

As a operator I would like to support scale in for the MachineDeployment, to only launch new nodes after deleting existing nodes, due to resource constraints or other stateful resources (for eg disks) on the workers.

**Detailed Description**

The use case is to support hyper converged storage solutions like OpenEBS and Portworx. With disk autoprovision, Portworx will try to use existing disk to attach to worker nodes. If no existing disk found, will create new ones. 

Then for upgrade, the behavior I'm trying to achieve is, only until one old node completely deleted then start create a new node, so the existing disk can attach to the new node. 

I can achieve partially by setting maxSurge=0 and maxUnavailable=1. The issue is when MachineSet calculate replica count, it does not contain Machines in deleting state, so new node is launched before old node is deleted, even through maxsurge=0. 

**Anything else you would like to add:**

I think there are two ways to achieve this: 
1. Add a new strategy, like RollingRecreate
2. Update RollingUpdate strategy to add a new flag, IncludeDeletingReplicas, when this flag presents, MachineSet controller takes into consideration of deleting Machines for replica count, to make sure total machines will not exceed maxSurge.

Personally I prefer solution 2. Let me know if this makes sense. 

/kind feature

**Comment by detiber** [comment]
I'm a +1 to the logic in 2, but I think I would like to argue that the current behavior should be considered a bug and we should fix it without introducing a new flag for the appropriate behavior.

**Comment by jzhoucliqr** [comment]
Thanks. Will have a PR for the fix.
