### ISSUE TITLE
Deleting a Node object after registration also deletes Machine when using MachineHealthCheck 

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes-sigs/cluster-api#3419]
**What steps did you take and what happened:**
* Delete a Node resource in a cluster after it has been successfully registered 
* Notice that cluster API will delete the underlying machine and replace it with a new one.  

**What did you expect to happen:**
The underlying machine should not have been deleted right away.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.6
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
Related to https://github.com/kubernetes-sigs/cluster-api/issues/3421

**Comment by vincepri** [comment]
This sounds like expected behavior to me, ok to close?
