### ISSUE TITLE
Generate v1alpha4 types

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#3428]
Tracking issue to generate Cluster API types for:

- Core types
- CABPK
- KCP
- CAPD

/kind feature
/area api
/milestone v0.4.0

**Comment by srm09** [comment]
@vincepri should I assign this one to myself, now that am added to the `k8s-sigs` org?

**Comment by srm09** [comment]
As an FYI, this is a useful [kubebuilder](https://book.kubebuilder.io/multiversion-tutorial/tutorial.html) link for creating multi-version API.
