### ISSUE TITLE
RFE: Pod based control plane provider

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#3429]
Folks have been asking here and there for a pod-based control plane. With v1alpha3, we introduced support for control plane providers, which users can use to specify which provider they'd like to use to manage their control plane.

/kind feature
/kind design
/milestone Next

**Comment by hardikdr** [comment]
[Gardener](https://github.com/gardener) deploys pod-based control-planes and also follows the core principles of cluster-api. I am generally interested in developing the control-plane provider for it, but haven't been able to spend enough time yet, would be more than happy to collaborate if there is an added interest. 
- A very minimal start: https://github.com/hardikdr/gardener-controlplane-provider
- Essentially it'd be about mapping the cluster-object with the shoot-object, and MachinePoolAPI to gardener's MachineAPI.

**Comment by christopherhein** [comment]
@hardikdr do you plan on using something that would define the control plane template? Or are you thinking that each release of the controlplane provider would map to a specific k8s version that gets created?

**Comment by hardikdr** [comment]
>do you plan on using something that would define the control plane template?

Yes, basically I'd hope to introduce a `GardenerManagedContolPlane` CRD with a field of `Spec.Version` to allow users to configure the k8s version of choice. The CRD would then simply map to the cluster-resource of the gardener-orchestrator at runtime, and the rest of the responsibility of spawning the cluster should then be taken care of by gardener. 
- In a similar way, the MachinePoolAPI of cluster-api can be mapped to the gardener's MachineAPI.

**Comment by randomvariable** [comment]
Is this essentially CAPN now, and do we need this?

**Comment by vincepri** [comment]
/close

This RFE is in a different repository as @randomvariable mentioned, https://github.com/kubernetes-sigs/cluster-api-provider-nested
