### ISSUE TITLE
Quick start with AWS fails

### ISSUE THREAD

**Issue by inductor** [kubernetes-sigs/cluster-api#3438]
**What steps did you take and what happened:**

```
$ clusterawsadm bootstrap iam create-cloudformation-stack
Error: unknown command "bootstrap" for "clusterawsadm"
Run 'clusterawsadm --help' for usage.
unknown command "bootstrap" for "clusterawsadm"
```

and even if i set the iam user correctly the setup fails

```
$ clusterctl init --infrastructure aws
Fetching providers
Installing Provider="cluster-api" Version="v0.3.8" TargetNamespace="capi-system"
Error: action failed after 10 attempts: failed to create provider object cert-manager.io/v1alpha2, Kind=Certificate, capi-webhook-system/capi-serving-cert: Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

```
$ clusterawsadm alpha bootstrap create-stack
```

worked with cluster-api-provider-aws 0.5.4 and cluster-api 0.3.8

**Environment:**

- Cluster-api version: 0.3.8
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by ncdc** [comment]
It looks like we updated the docs in anticipation of changes to cluster-api-provider-aws that are coming the in v0.5.5 release. The documentation does state you need v0.5.5, and provides a link to the instructions that are valid for earlier versions (and it looks like you were able to locate that). I'd like to propose that we close this issue - is that ok?

**Comment by vincepri** [comment]
/priority awaiting-more-evidence
/milestone Next

+1 to closing, seems the docs are up to date
