### ISSUE TITLE
[ClusterResourceSet] Add Sync mode

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#3447]
**User Story**

As a developer/user/operator I would like to apply a resource using ClusterResourceSet and update its version or change some other fields using the same ClusterResourceSet resource.

**Detailed Description**

To support this use case, we can consider adding a `Sync`/`Reconcile` mode in addition to `ApplyOnce` mode that reapplies the resources on resource hash change and/or periodically.

/kind feature

**Comment by vincepri** [comment]
@sedefsavas Are we still interested in pushing this forward or should we close it for now?

**Comment by sedefsavas** [comment]
There were no requests to move this forward, I think we can close it until there are new use cases.

**Comment by jessehu** [comment]
Hi gurus, can we reopen this please? We have a upgrade case that need to re-apply this CRS (with updated secret content). Thanks.

**Comment by sbueringer** [comment]
@jessehu I think this issue was essentially superceded by: https://github.com/kubernetes-sigs/cluster-api/issues/4807 Can you please check if the new issue fulfills your use case?

**Comment by jessehu** [comment]
Exactly! Glad to see it's almost done 👍
