### ISSUE TITLE
KCP may have extraneous RBAC roles

### ISSUE THREAD

**Issue by DheerajSShetty** [kubernetes-sigs/cluster-api#3451]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
The roles specified for KCP here might not be needed
https://github.com/kubernetes-sigs/cluster-api/blob/69347982dc6983615cd439e975cccb397083859e/controlplane/kubeadm/config/rbac/role.yaml#L68

These roles are not used

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.8
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
@sedefsavas Can you investigate + triage?

**Comment by sedefsavas** [comment]
Yes, I am looking into this.

**Comment by sedefsavas** [comment]
These are unused rbac rules added to control plane. I don't think removing them will affect anything. Have a PR open, I think it can go in v0.3.9.

**Comment by detiber** [comment]
+1 to removing these rules
/priority important-soon
