### ISSUE TITLE
Switch KCP to use ClusterCacheTracker.GetClient for the workload cluster client

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#3457]
Now that we have remote.ClusterCacheTracker, we should be able to use it to get a client for KCP to use for the workload cluster, instead of creating one - https://github.com/kubernetes-sigs/cluster-api/blob/7c8bb5e75f65d1f2376e20df8a965a166183bff7/controlplane/kubeadm/internal/cluster.go#L100-L103. See https://github.com/kubernetes-sigs/cluster-api/blob/7c8bb5e75f65d1f2376e20df8a965a166183bff7/controllers/machine_controller.go#L435 for an example of getting a client.

/area control-plane
/kind cleanup
/priority important-longterm
/milestone v0.4.0

**Comment by pulkitmehra** [comment]
@wfernandes , I would love to help here, this seems to me good first issue, could you help assign this to me ?

**Comment by vincepri** [comment]
@pulkitmehra Are you still working on this issue?

**Comment by pulkitmehra** [comment]
@vincepri , when is the deadline for this issue? I can get this in by end of this month?

**Comment by vincepri** [comment]
No rush, take your time!

**Comment by furkatgofurov7** [comment]
Hi @pulkitmehra! If you are not working on this, I can take this up. 

/cc @vincepri

**Comment by pulkitmehra** [comment]
Sure- sorry for not completing this task.
