### ISSUE TITLE
Cert Manager times out when initializing the workload cluster with capi components

### ISSUE THREAD

**Issue by eratnch** [kubernetes-sigs/cluster-api#3485]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

This is inspired from kubernetes-sigs/cluster-api-provider-openstack#614 
When initializing a target cluster with capi and capo components, cert manager times out.

**What did you expect to happen:**
The target cluster is initialized with capi and provider components(in this case capo) so that a clusterctl move can be attempted.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Logs are available in kubernetes-sigs/cluster-api-provider-openstack#614 thread

**Environment:**

- Cluster-api version: This issue happens with both 0.3.7 and 0.3.8
- Minikube/KIND version: kind v0.7.0 go1.13.6 linux/amd64
- Kubernetes version: (use `kubectl version`): Client Version: v1.17.4
Server Version: v1.17.0
- OS (e.g. from `/etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
I stumbled in this problem when the networking was not fully operative on the workload cluster (missing CNI).
Could you kindly check if the networking is properly set up before running clusterctl init on the workload cluster?
If this is is not the case, please provide the clusterctl init output (run with -v 5), and the output of kubectl get pods -A

/priority awaiting-more-evidence

**Comment by eratnch** [comment]
In this case CNI (Calico) was applied to the workload cluster before trying clusterctl init.

Here are the steps

* kubectl --kubeconfig /tmp/kubeconfig.yml get nodes 

```
NAME                             STATUS   ROLES    AGE   VERSION
ostgt-dflt-control-plane-zsbrg   Ready    master   21h   v1.17.3
ostgt-dflt-md-0-7zgqx            Ready    <none>   21h   v1.17.3
ostgt-dflt-md-0-9t7xw            Ready    <none>   21h   v1.17.3
ostgt-dflt-md-0-blmtd            Ready    <none>   21h   v1.17.3
```

* clusterctl --kubeconfig /tmp/kubeconfig.yml init -i openstack -v5:
 ```
No default config file available
Installing the clusterctl inventory CRD
Creating CustomResourceDefinition="providers.clusterctl.cluster.x-k8s.io"
Fetching providers
Fetching File="core-components.yaml" Provider="cluster-api" Version="v0.3.8"
Fetching File="bootstrap-components.yaml" Provider="bootstrap-kubeadm" Version="v0.3.8"
Fetching File="control-plane-components.yaml" Provider="control-plane-kubeadm" Version="v0.3.8"
Fetching File="infrastructure-components.yaml" Provider="infrastructure-openstack" Version="v0.3.1"
Fetching File="metadata.yaml" Provider="cluster-api" Version="v0.3.8"
Fetching File="metadata.yaml" Provider="bootstrap-kubeadm" Version="v0.3.8"
Fetching File="metadata.yaml" Provider="control-plane-kubeadm" Version="v0.3.8"
Fetching File="metadata.yaml" Provider="infrastructure-openstack" Version="v0.3.1"
Installing cert-manager
Creating Namespace="cert-manager"
Creating CustomResourceDefinition="challenges.acme.cert-manager.io"
Creating CustomResourceDefinition="orders.acme.cert-manager.io"
Creating CustomResourceDefinition="certificaterequests.cert-manager.io"
Creating CustomResourceDefinition="certificates.cert-manager.io"
Creating CustomResourceDefinition="clusterissuers.cert-manager.io"
Creating CustomResourceDefinition="issuers.cert-manager.io"
Creating ServiceAccount="cert-manager-cainjector" Namespace="cert-manager"
Creating ServiceAccount="cert-manager" Namespace="cert-manager"
Creating ServiceAccount="cert-manager-webhook" Namespace="cert-manager"
Creating ClusterRole="cert-manager-cainjector"
Creating ClusterRoleBinding="cert-manager-cainjector"
Creating Role="cert-manager-cainjector:leaderelection" Namespace="kube-system"
Creating RoleBinding="cert-manager-cainjector:leaderelection" Namespace="kube-system"
Creating ClusterRoleBinding="cert-manager-webhook:auth-delegator"
Creating RoleBinding="cert-manager-webhook:webhook-authentication-reader" Namespace="kube-system"
Creating ClusterRole="cert-manager-webhook:webhook-requester"
Creating Role="cert-manager:leaderelection" Namespace="kube-system"
Creating RoleBinding="cert-manager:leaderelection" Namespace="kube-system"
Creating ClusterRole="cert-manager-controller-issuers"
Creating ClusterRole="cert-manager-controller-clusterissuers"
Creating ClusterRole="cert-manager-controller-certificates"
Creating ClusterRole="cert-manager-controller-orders"
Creating ClusterRole="cert-manager-controller-challenges"
Creating ClusterRole="cert-manager-controller-ingress-shim"
Creating ClusterRoleBinding="cert-manager-controller-issuers"
Creating ClusterRoleBinding="cert-manager-controller-clusterissuers"
Creating ClusterRoleBinding="cert-manager-controller-certificates"
Creating ClusterRoleBinding="cert-manager-controller-orders"
Creating ClusterRoleBinding="cert-manager-controller-challenges"
Creating ClusterRoleBinding="cert-manager-controller-ingress-shim"
Creating ClusterRole="cert-manager-view"
Creating ClusterRole="cert-manager-edit"
Creating Service="cert-manager" Namespace="cert-manager"
Creating Service="cert-manager-webhook" Namespace="cert-manager"
Creating Deployment="cert-manager-cainjector" Namespace="cert-manager"
Creating Deployment="cert-manager" Namespace="cert-manager"
Creating Deployment="cert-manager-webhook" Namespace="cert-manager"
Creating APIService="v1beta1.webhook.cert-manager.io"
Creating MutatingWebhookConfiguration="cert-manager-webhook"
Creating ValidatingWebhookConfiguration="cert-manager-webhook"
Waiting for cert-manager to be available...
Error: timed out waiting for the condition
```
* kubectl --kubeconfig /tmp/kubeconfig.yml get po -A

```
NAMESPACE      NAME                                                     READY   STATUS    RESTARTS   AGE
cert-manager   cert-manager-84bb546784-spbwv                            1/1     Running   0          21h
cert-manager   cert-manager-cainjector-65f677f4fc-6bz26                 1/1     Running   0          21h
cert-manager   cert-manager-webhook-bbb8f9db9-xftlz                     1/1     Running   1          21h
kube-system    calico-kube-controllers-59d85c5c84-p6tmf                 1/1     Running   0          21h
kube-system    calico-node-2prn5                                        1/1     Running   0          21h
kube-system    calico-node-65h5f                                        1/1     Running   0          21h
kube-system    calico-node-d2j84                                        1/1     Running   0          21h
kube-system    calico-node-ph7ht                                        1/1     Running   0          21h
kube-system    coredns-6955765f44-djqnj                                 1/1     Running   0          21h
kube-system    coredns-6955765f44-g9n6k                                 1/1     Running   0          21h
kube-system    etcd-ostgt-dflt-control-plane-zsbrg                      1/1     Running   0          21h
kube-system    kube-apiserver-ostgt-dflt-control-plane-zsbrg            1/1     Running   0          21h
kube-system    kube-controller-manager-ostgt-dflt-control-plane-zsbrg   1/1     Running   0          21h
kube-system    kube-proxy-cjk7d                                         1/1     Running   0          21h
kube-system    kube-proxy-f6cb4                                         1/1     Running   0          21h
kube-system    kube-proxy-flfp7                                         1/1     Running   0          21h
kube-system    kube-proxy-nsww6                                         1/1     Running   0          21h
kube-system    kube-scheduler-ostgt-dflt-control-plane-zsbrg            1/1     Running   0          21h
```

**Comment by fabriziopandini** [comment]
Waiting for cert-manager to be available is basically running 
```
kubectl wait --for=condition=Available --timeout 600s apiservice v1beta1.webhook.cert-manager.io
```
If this condition is meet now, you can try to increase the certmanager timeout during init.
If not, there should be something in your network setup preventing to reach out to the cert-manager-webhook.

**Comment by eratnch** [comment]
Thanks @fabriziopandini.

I compared the cert manager on my Kind management cluster with that of the target cluster. 

**On Kind mgmt cluster**
kubectl get apiservice v1beta1.webhook.cert-manager.io
```
NAME                              SERVICE                             AVAILABLE   AGE
v1beta1.webhook.cert-manager.io   cert-manager/cert-manager-webhook   True        2d1h

```
**On workload cluster**

kubectl --kubeconfig /tmp/kubeconfig.yml get apiservice v1beta1.webhook.cert-manager.io
```
NAME                              SERVICE                             AVAILABLE                      AGE
v1beta1.webhook.cert-manager.io   cert-manager/cert-manager-webhook   False (FailedDiscoveryCheck)   2d

```
Can you please point out on how to check further on the networking set up on my workload cluster so the cert-manager-webhook is reachable and discover check passes.

**Comment by fabriziopandini** [comment]
I can give you only a generic suggestion because I don't know cert-manager internals in detail.
You can look at the `cert-manager/cert-manager-webhook` service (which is backing `v1beta1.webhook.cert-manager.io`), check its endpoints, then create a debug pod and try to get an answer from those endpoints (see e.g. https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/). The other suggestion is to look at NetworkPolicies created by CAPO, if any

Please consider also contacting the cert-manager maintainers (they are usually super helpful)

**Comment by fabriziopandini** [comment]
@eratnch 
Do you managed to solve the cert-manager problems?

**Comment by eratnch** [comment]
@fabriziopandini no, the issue is still there.

**Comment by fabriziopandini** [comment]
Ok, sorry to hear that.
Unfortunately, I don't have CAPO environments to try to reproduce 😓 

Have you consider to move issue to the CAPO repository, given that it seems that cert-manager does not works properly on the workload cluster only? 
Also, might be related https://github.com/kubernetes-sigs/cluster-api/issues/3274#issuecomment-652622670
