### ISSUE TITLE
Add conditions to MachineDeployment Object

### ISSUE THREAD

**Issue by Arvinderpal** [kubernetes-sigs/cluster-api#3486]
User Story
As a developer/user/operator I would like to have conditions documenting the operational state of MachineDeployment objects.

Anything else you would like to add:
As required by the condition CAEP, the MachineDeployment objects should also provide a Ready condition describing the overall state of the object.

Tasks:

- [x] Summary `ReadyCondition` and Node availability condition `AvailableCondition` https://github.com/kubernetes-sigs/cluster-api/pull/4625
- [x] MachineSet related conditions: `MachinesCreatedCondition`, `MachinesReadyCondition` and `ResizedCondition` https://github.com/kubernetes-sigs/cluster-api/pull/5056
- [ ] MachineDeployment scaling related conditions: `MachinesSpecUpToDateCondition` and `ResizedCondition`
- [ ] Remove the use of Phases 
- [ ] Cleanup: Change calculateStatus() --> updateStatus() to be consistent with the rest of the code base.

Related: [Conditions for KCP](https://github.com/kubernetes-sigs/cluster-api/issues/3137)

/kind feature

**Comment by Arvinderpal** [comment]
Ideally, we would have something similar to [DeploymentProgressing](https://github.com/kubernetes/api/blob/master/apps/v1/types.go#L426).

This is more to bring in line with how `kubectl rollout status` works. With `clusterctl rollout status my-md-0` we would also watch the progression of the MD by looking at MachinesReadyCondition. I think that would accomplish something similar.

**Comment by Arvinderpal** [comment]
Can I be assigned this ticket? Not that anyone else is jumping to work on it :laughing: 
I'll need this for the `clusterctl rollout status` command: https://github.com/kubernetes-sigs/cluster-api/issues/3439

**Comment by vincepri** [comment]
@Arvinderpal Sure, feel free to take it! 

/priority important-soon
/assign @Arvinderpal

**Comment by Arvinderpal** [comment]
@vincepri @detiber I have the PR ready. PTAL
https://github.com/kubernetes-sigs/cluster-api/pull/4174

**Comment by vincepri** [comment]
@fabriziopandini to check if the PR is ready to go and double check the release blocking status

**Comment by enxebre** [comment]
For MachineDeployments it'd be interesting to consider signal as conditions and differentiate rolling upgrades e.g
- Upgrading Version.
- Upgrading because of bootstrap provider change.
- Upgrading because of an infra change.

Thoughts?

**Comment by Arvinderpal** [comment]
@enxebre More granular info would be great. Are you suggesting a new condition for each of those bullets? Would they be better captured in the Reason/Message of a single condition? I'm leaning towards the latter.

**Comment by enxebre** [comment]
cc @muraee

**Comment by sbueringer** [comment]
Solution is proposed in https://github.com/kubernetes-sigs/cluster-api/pull/10897

/close
