### ISSUE TITLE
Clusterctl incorrectly encodes Windows file paths for local repository

### ISSUE THREAD

**Issue by genehynson** [kubernetes-sigs/cluster-api#3487]
**What steps did you take and what happened:**

_Note: I originally produced this with the TKG cli, but investigation shows it's an issue within clusterctl itself._

The issue is that a recent [Windows 10 update](https://support.microsoft.com/en-us/help/4467268/url-encoded-unc-paths-not-url-decoded-in-windows-10-version-1803-later) changes the Windows URI pathing behavior: _"In Windows 10, version 1803 and later versions of Windows, URLs (such as SharePoint document libraries) can't be referenced by Universal Naming Convention (UNC) paths that contain URI encoding characters."_

This is an issue occurs if the user on Windows has a space in the username like `C:\Users\Gene Hynson\...` or `C:\Users\test space\...`

To reproduce this issue on Windows 10 1803+, provide a local providers URL to clusterctl with a space in the path like: `file:///C:/Users/test space/some/path/to/file.yaml`. Notice it becomes encoded as `file:///C:/Users/test%20space/some/path/to/file.yaml` and Windows fails to resolve this path. 

Error message: 
```
failed to read "cluster-template-definition-dev.yaml" from provider's repository "infrastructure-vsphere": failed to read file "C:\\Users\\test%20space\\.tkg\\providers\\infrastructure-vsphere\\v0.7.0\\cluster-template-definition-dev.yaml" from local release v0.7.0
```

**What did you expect to happen:**

clusterctl should not encode the path (at least for Windows). 

Expected: When local providers URL is provided to clusterctl and there is a space in the path like: `file:///C:/Users/test space/some/path/to/file.yaml` clusterctl should not encode this path and Windows should be able to resolve it. 

**Anything else you would like to add:**

- Line of code causing this issue (I think): https://github.com/kubernetes-sigs/cluster-api/blob/4e90523fa94618a4cbddbd9fec98ab052873bc89/cmd/clusterctl/client/repository/repository_local.go#L147
- Exception is thrown here: https://github.com/kubernetes-sigs/cluster-api/blob/4e90523fa94618a4cbddbd9fec98ab052873bc89/cmd/clusterctl/client/repository/repository_local.go#L98-L101
- Go Playground reproducing the issue: https://play.golang.org/p/O7dpNE9L_ye
- Microsoft article about this change in Windows 10: https://support.microsoft.com/en-us/help/4467268/url-encoded-unc-paths-not-url-decoded-in-windows-10-version-1803-later
- Relevant issue: https://github.com/kubernetes-sigs/cluster-api/issues/3416

**Environment:**

- Cluster-api version: 0.3.8
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): 1.18
- OS (e.g. from `/etc/os-release`): Windows 10

/kind bug
/area clusterctl

**Comment by wfernandes** [comment]
Do we want to support version of windows older than `Windows 10 Version 1803`?

**Comment by genehynson** [comment]
I believe versions <1803 support unencoded paths (e.g. `C:\Users\test space\...`). The 1803 update just removed support for encoded paths (e.g. `C:\Users\test%20space\...`). So if we remove the encoding step (at least for Windows), we should support all versions of Windows

**Comment by wfernandes** [comment]
That's what I suspected...I don't have a windows env older that <=1803 to verify that. 
As per our discussion via Slack...I'm handing this off to you since I don't have a proper Windows dev environment setup. Thanks.
/assign @genehynson
