### ISSUE TITLE
Include cert-manager upgrade in `clusterctl upgrade plan`

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#3491]
**User Story**

As a user/operator I would like to see if cert-manager has an available upgrade when using `clusterctl upgrade plan`.

**Detailed Description**

As part of PR https://github.com/kubernetes-sigs/cluster-api/pull/3364, we can now upgrade cert-manager to the new version (v0.16.0) from the old version (v0.11.0) when we run `clusterctl upgrade apply`.
It would be nice to see the available cert-manager upgrade when running `clusterctl upgrade plan` so that operators who are planning upgrades are more aware of the changes.

**Anything else you would like to add:**
For context, here's the issue comment from the PR #3364 review. 
https://github.com/kubernetes-sigs/cluster-api/pull/3364#issuecomment-671861226

This could also help UX when upgrading to future versions of cert-manager.

/kind feature
/area clusterctl

**Comment by vincepri** [comment]
+1 this would be great to have.

/milestone v0.3.9

**Comment by wfernandes** [comment]
I can take a look into this
/assign
