### ISSUE TITLE
Out of date documentation for provider implementers

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#3492]
**What steps did you take and what happened:**
[In our documentation we have a list of providers](https://github.com/kubernetes-sigs/cluster-api/blob/43dd623ce667a1ff33e0d2d649b9a3dea2977f02/docs/book/src/reference/providers.md#provider-implementations
). Here we track the ones that follow v1alpha3 types.

> Providers marked in bold are known to support v1alpha3 API types.

However, the list seems to be incorrect because providers like `OpenStack` and `Packet` seem to follow the v1alpha3 contract but are **not** marked as bold.

**What did you expect to happen:**
- Either we should not mark providers that are abiding by the v1alpha3 contract in bold since the list will eventually go out of date and become misleading.
OR
- If we want to track what providers are supporting v1alpha3 contracts, we should update this list to ensure we aren't providing misleading information.

**Anything else you would like to add:**
Is there a way to automate this? With the next release of v1alpha4, should this become a table that's auto generated?

**Environment:**

- Cluster-api version: <=v0.3.8
- Minikube/KIND version: n/a
- Kubernetes version: (use `kubectl version`): n/a
- OS (e.g. from `/etc/os-release`): n/a

/kind bug
/kind documentation

**Comment by fabriziopandini** [comment]
I'm +1 to remove bold and add something like. Check provider documentation for updated info about which contract are they supporting

**Comment by danniel1205** [comment]
@wfernandes @fabriziopandini I would love to help, could you help assign this to me ?
