### ISSUE TITLE
More production style OS images (non-alpine... debian ? centos?) images for CAPD

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api#3493]
**What steps did you take and what happened:**

A few DNS situations and OVS based cni solutions dont work , properly on CAPD.    Additionally certain packages often used in production k8s clusters (from ubuntu and centos) arent available.   Typically an image such as  centos/ubuntu (those at  https://github.com/kubernetes-sigs/cluster-api-provider-vsphere#kubernetes-versions-with-published-ovas ) would be what i would expect for realistic testing.

**What did you expect to happen:**

We can test CAPD like a production cluster with any CNI/standard DNS behaviours. 

**Anything else you would like to add:**

The specific instance im noticing here is antrea as a CNI testbed, which expects OVS to be installed.

**Environment:**

- Cluster-api version: master
/kind bug
 
Note there are workarounds here, but i assume using a standard debian image like the ones used for CAPV and CAPA clusters would give us parity.

**Comment by jayunit100** [comment]
workaround: we can install stuff (like alpine ovs) for any individual one issue, but likely most users would have a better dev/hacking type experience if they just got a stock ubuntu/centos version as the baselayer.

**Comment by fabriziopandini** [comment]
@jayunit100 CAPD uses imaged built by kind, and currently, only the load balancer image is built with alpine, while the node image is already built using ubuntu

Load balancer image
```
docker exec 38b8d7d820b3 cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.10.3
PRETTY_NAME="Alpine Linux v3.10"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

Nodes (with kindest/node:v1.17.2)
```
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
```
More recent versions are using Ubuntu 20.10

**Comment by jayunit100** [comment]
Ok I may be mistaken .... will double check today what the issue is .

**Comment by randomvariable** [comment]
The image definition is in the Kind repo. Should be mostly Ubuntu based.

**Comment by jayunit100** [comment]
makes sense,  im going to close this. thanks naadir / fabrizio
