### ISSUE TITLE
"clusterctl get kubeconfig capi-quickstart" did not work as per quick start guide to get kubeconfig

### ISSUE THREAD

**Issue by krmayankk** [kubernetes-sigs/cluster-api#3509]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Followed this documentaiton https://cluster-api.sigs.k8s.io/user/quick-start.html
One of the steps is to run to get kubeconfig of the workload cluster,so that i can apply CNI

```
clusterctl get kubeconfig capi-quickstart
```

**What did you expect to happen:**
expected the command to work, but i got the error message

```
Error: unknown command "get" for "clusterctl"
Run 'clusterctl --help' for usage

clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.8", GitCommit:"9e4e82aabd2dfe7a52ebd0b7d6b802a9be4ff93d", GitTreeState:"clean", BuildDate:"2020-07-31T20:50:54Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"darwin/amd64"}
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 0.3.8
- Minikube/KIND version: v0.8.1
- Kubernetes version: (use `kubectl version`): v1.18.2
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
@krmayankk sorry for this problem
The `clusterctl get kubeconfig` command is actually on master, but it is not yet part of a release. By mistake, we merged the change to the relative documentation too early and here it is an error:
AFAIK there are two workarounds:
- make clusterctl from master (clone the repo, run `make clusterctl`, use the binary under the bin/ folder)
- use the old syntax for retrieving the kubeconfig
```
kubectl --namespace=default get secret foo -o jsonpath={.data.value} | base64 --decode 
```

**Comment by krmayankk** [comment]
thanks @fabriziopandini i was able to get it to work by getting the kubeconfig from the secrets
