### ISSUE TITLE
Add option for scale-in for KCP

### ISSUE THREAD

**Issue by jan-est** [kubernetes-sigs/cluster-api#3512]
**User Story**

As a baremetal cluster administrator I would like to upgrade my KCP without any extra resources. 

**Detailed Description**

The current KCP implementation always scale-out during the upgrade. Original design was to make sure that KCP with one replica can be scaled safely. However, this is a very restrictive implementation in environments (such as baremetal) where there are no additional resources to scale out.

I think we should consider to change KCP upgrade to scale-in by default. This implementation would work in all HA clusters, and the change will not affect UX. I think it would be better to handle KCP with one replica as a specific case, not other way around.  

Before going into any pluggable upgrade strategy implementation this simple and easy fix in logic, would make life easier to baremetal infrastructure providers. At the same time it does not change anything from the perspective of virtual environment providers. 

**Anything else you would like to add:**

This would be more in line with the general recommendation of etcd, that a member should be removed before adding a replacement. See: [ETCD faq](https://etcd.io/docs/v3.4.0/faq/)

/kind feature

**Comment by vincepri** [comment]
Thanks for filing this! Going to set this feature for v1alpha4, we might want to apply some breaking change to let folks choose their strategy and default to what we do today, this might need a design-change to the KCP proposal.

/milestone v0.4.0

**Comment by jan-est** [comment]
@vincepri sounds good! Let's try to keep design as simple as possible in v0.4.0. Let users choose from default and scale-in. If scale-in is selected, KCP scale-in one member at the time.

**Comment by jan-est** [comment]
@vincepri I have been working an experimental code for scale-in feature. Is there anyone in the community that could go through the KCP upgrade and scaling workflow with me? I would like to talk more in details what to take account while trying to scale-in the KCP and does this affect for example Etcd and control plane health checks? I can take this into this week community meeting as well. 

I would like experiment scale-in feature locally before we continue with KCP proposal design-changes.

**Comment by ncdc** [comment]
cc @randomvariable @detiber

**Comment by randomvariable** [comment]
Had the beginnings of a conversation in Slack, so will summarise here:

Early drafts of the KCP proposal did include scale-in for upgrades, and there was some discussion about it before we settled on scale out. The case for supporting both was reviewing what other projects were doing, in particular, if you look at Cloud Foundary Container Runtime, you get the following rollout strategies ([from this doc](https://docs.google.com/document/d/1RnUG9mHrS_qmhmm052bO6Wu0dldCamwPmTA1D0jCWW8/edit#):

Delete-create (default in CFCR)
* Stops processes, deletes the VM and then creates and provisions a VM

Create-swap-delete (default in CAPI)
* Creates and provisions a new VM before stopping the old one

Can see a benefit in supporting Delete-create in any resource constrained environment (whether that's bare-metal, OpenStack or vSphere resource pools).

I think it therefore makes sense to make this selectable, defaulting to the current behaviour (and also for MachineDeployments).

In terms of things to be aware of:
* Upgrading a control plane with a single replica (then definitely don't ever scale in)
* etcd quorum, mostly handled in https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/internal/workload_cluster_etcd.go#L41:L41

**Comment by jan-est** [comment]
Hi, how should we proceed with this scale-in feature. Can we proceed with design changes in KCP proposal?

I have tested this feature couple of days now and I have a working code and an idea how we could add this feature. Currently changes covers following cases:

- if scale-in is enabled and replica count is not 1 -> scale-in
- if scale-in is enabled and replica count is 1 -> force to scale-out
- else scale-out.

Enabling of the scale-in is similar to machinedeployment's way of enabling rollingupdate. We could add `KubeadmControlPlaneSpec.UpgradeStrategy` as follows :

```
// UpgradeStrategy is a field to select an upgrade strategy. If field is not precent
// KCP uses default scale-out strategy. Only supported additional upgrade strategy is ScaleIn.
// +optional
UpgradeStrategy UpgradeStrategyType `json:"upgradeStrategy,omitempty"`

type UpgradeStrategyType struct {
	// +optional
	Type string `json:"type,omitempty"`
}
```
With this we can add new strategies later and add more features into existing ones in the future. Any thoughts?

**Comment by randomvariable** [comment]
/retitle Add option for scale-in for KCP

**Comment by randomvariable** [comment]
I think so. I'll leave it to the maintainers to decide timing etc...

**Comment by vincepri** [comment]
Given that this is a large-ish feature addition, I'd propose to target v1alpha4 and consider backporting if the code changes aren't invasive.

/cc @CecileRobertMichon

**Comment by jan-est** [comment]
Is there any time schedule set for a v1alpha4 release?

**Comment by fabriziopandini** [comment]
+1 to v1lapha4

**Comment by vincepri** [comment]
@jan-est We don't have any estimates today I'd expect it either by end of year / early 2021

**Comment by jan-est** [comment]
> @jan-est We don't have any estimates today I'd expect it either by end of year / early 2021

Thanks @vincepri good to know.

**Comment by jan-est** [comment]
@fabriziopandini @vincepri Do you want me to make a proposal for this one?

**Comment by vincepri** [comment]
Possibly yeah, maybe we could get a small google doc started, and then a PR to the current KCP proposal

**Comment by jan-est** [comment]
> Possibly yeah, maybe we could get a small google doc started, and then a PR to the current KCP proposal

Google doc sounds good for now.

**Comment by jan-est** [comment]
Here is the Google doc https://docs.google.com/document/d/1fQNlqsDkvEggWFi51GVxOglL2P1Bvo2JhZlMhm2d-Co/edit#

**Comment by jan-est** [comment]
Here is the [google doc]( https://docs.google.com/document/d/1HWHTL6g45HrrBppGWgDi_1VkWRMA0Ue3IRBONcqKFKE/edit#heading=h.2lrpo279kcej)

**Comment by hanlins** [comment]
Hi, I've chatted with some other folks and they have similar demands. In their scenario they have stateful workloads and specifically they're leveraging local persistent volumes (for performance and cost) so they can't afford losing VMs as the disks will be gone. Is it possible to include an in-place option for cluster upgrade? I know this contradicts the immutable VM principal in cluster api, but that does seem to be a reasonable ask, any suggestions for the stateful scenario?

**Comment by jan-est** [comment]
> Hi, I've chatted with some other folks and they have similar demands. In their scenario they have stateful workloads and specifically they're leveraging local persistent volumes (for performance and cost) so they can't afford losing VMs as the disks will be gone. Is it possible to include an in-place option for cluster upgrade? I know this contradicts the immutable VM principal in cluster api, but that does seem to be a reasonable ask, any suggestions for the stateful scenario?

@hanlins We also have similar requirements and in-place upgrade would be good to have in KCP. I would like to see both scale-in and in-place upgrade in v1alpha4.

**Comment by fabriziopandini** [comment]
In-place upgrades seem a different topic than scale-in (vs scale-out) rollout strategy, so might be this should be moved to a separate issue.

Nevertheless, I have a set of concern WRT to this topic:
- in-place upgrade most probably requires access to the machines, and as of today CAPI is specifically designed to work without it.
- in-place upgrade most probably requires specific knowledge about the machine guest OS, and TBH I'm not sure this is something that should be in the responsibility of CAPI
- many providers are designed to work with backed in version artifacts, so we should clearly state the line of demarcation between CAPI, KCP and provider-specific capabilities.
- in kubeadm there is a discussion about a kubeadm-operator, and I would like to avoid to engage in overlapping efforts

**Comment by fabriziopandini** [comment]
/remove-lifecycle stale
this is being worked
