### ISSUE TITLE
Unable to overwrite imageRepository for worker nodes

### ISSUE THREAD

**Issue by dhawal55** [kubernetes-sigs/cluster-api#3516]
**What steps did you take and what happened:**
I want to use a private registry for all my images. `KubeadmControlPlane` support's it my setting `imageRepository` under `clusterConfiguration` but it is ignored when applied to `KubeadmConfigTemplate`. As a result the pause containers are still pulled from `k8s.gcr.io` and doesn't work for us in a firewalled environment

**What did you expect to happen:**
`KubeadmConfigTemplate` should read the `imageRepository` field and set it to kubeadm config

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
In the `joinWorker` method, it is only reading the `joinConfiguration`
https://github.com/kubernetes-sigs/cluster-api/blob/eb07294ddebe8099c359c35a1e42f79244e7d33f/bootstrap/kubeadm/controllers/kubeadmconfig_controller.go#L450

**Environment:**

- Cluster-api version: v0.3.7
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): v1.1.6.9
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
> This particular issue can be closed

/close

@dhawal55 thanks for raising this topic

**Comment by dhawal55** [comment]
@dims Thank you for the info. Do you have more info on the pain points of running kubelet as container?
