### ISSUE TITLE
Consolidate controllers implementation to use scope objects

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3517]
**User Story**

As a developer, I would like to have a simple way to pass objects throw the chain of `reconcile` funcs inside each controller
As a developer, I would like to have a consistent implementation approach in different controllers

**Detailed Description**

If a look at controllers, as of today all the `reconcile` funcs are getting in input the same list of parameters, and in most cases, this list is composed by 3 or more objects.

- As of today, adding a new parameter to this list has a domino effect, because you have to change all the signatures up to the point where the value is used.
- In order to implement conditions, there is an increasing need of issue `Patch` command in the middle of the reconcile logic, but given the above limitation, we are recreating the patch helper/reimplementing the `Patch` call in many places instead of re-using that exists in the main reconcile loop, and this is risky due to the increasing number of patch options.
- In most cases, this list is already missing of the `log` parameter, and as a consequence, we are recreating the same `log.WithValues` in many places

In order to address this problem I would like to discuss the option to introduce a scope object with the goal to provide a single object for passing along the `reconcile` funcs chain the following objects:

- the operation context (`ctx`)
- the object to reconcile + all the related objects (e.g. `machine`, `infraMachine`, `bootstrapConfig`)
- the `log` instance with all the `WithValues` keys for ^^
- the `patchHelper` for ^^

The scope object should provide access to the above objects, expose the `Patch` method (thus ensuring the various patch options are defined in a single place).

Additionally, the scope can implement some utility methods to handle the contained objects, like e.g. filters; by moving such details of object handling detail out of the reconcile loop, there is a concrete opportunity to clean up and make more readable reconcile logic in the main controller file.

WDYT?

**Anything else you would like to add:**

Scope objects are already used in CAPA
KCP has a controlplane object that acts as a scope object

/kind cleanup

**Comment by detiber** [comment]
I too would like to avoid extending the "scope" pattern further.

It makes debugging more difficult, makes testing more difficult (what all do I need to populate in the scope as a bare minimum for testing this thing), and it tends to leak much further than the controller code and down into libraries as well.

**Comment by vincepri** [comment]
Now that we have the logger passed in with the context, we should be able to close this one out for now. As mentioned above, I don't think expanding the `scope` pattern found in CAPA is actually something we might want to do.
