### ISSUE TITLE
Add cleanup section to the quick start

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3523]
**User Story**

As a user, I would like to clean up all the resources after completing the CAPI quick start

**Detailed Description**

In the https://cluster-api.sigs.k8s.io/user/quick-start.html we should provide a new paragraph with instruction for cleaning up all the resources created during the quick start, and more specifically explain how to

- Delete the workload cluster
- Delete the management cluster

/kind documentation
/help

**Comment by vincepri** [comment]
If someone wants to tackle this, we can merge it whenever
