### ISSUE TITLE
Allow upgrading CAPI management cluster to specific version

### ISSUE THREAD

**Issue by dhawal55** [kubernetes-sigs/cluster-api#3524]
**User Story**

Allow `clusterctl upgrade` to pin to a specific version
Allow `clusterctl init` to generate yaml for management cluster

**Detailed Description**

Currently `clusterctl upgrade` allows to plan and apply the latest version only. Also, there is no apply command for management cluster (there are separate create and upgrade commands). It will be nice to have `clusterctl upgrade` command take version as input. 

Also, I would like an option for `clusterctl init` to generate yamls for management cluster so we can add it in source control and use kubectl to apply it. This allows us to apply management cluster and pick and choose the version we want. It also allows for any customizations if needed

/kind feature

**Comment by fabriziopandini** [comment]
/triage support

> Allow clusterctl upgrade to pin to a specific version

This is possible. See e.g. https://cluster-api.sigs.k8s.io/clusterctl/commands/upgrade.html#upgrade-apply (the example for upgrading to a pre release gives you the right syntax)

> Allow clusterctl init to generate yaml for management cluster

Clusterctl init does much more than generating yaml, however if you want to get only the yaml you can use the clusterctl config provider command with the -o yaml flag

**Comment by dhawal55** [comment]
@fabriziopandini Thank you. I didn't knew about `clusterctl config provider` had an option to generate yaml. That's exactly what I was looking for. 

If I apply the below 4 yamls, is it same as running `clusterctl init`:
```
clusterctl config provider  --infrastructure vsphere:v0.7.1 -oyaml > cluster-api/infrastructure.yaml
clusterctl config provider  --core cluster-api:v0.3.8 -oyaml > cluster-api/core.yaml
clusterctl config provider  --bootstrap kubeadm:v0.3.8 -oyaml > cluster-api/bootstrap.yaml
clusterctl config provider  --control-plane kubeadm:v0.3.8 -oyaml > cluster-api/control-plane.yaml
```

**Comment by fabriziopandini** [comment]
> If I apply the below 4 yamls, is it same as running clusterctl init

Nope. You should apply also cert-manager.
NOTE. if you create a management cluster by your own, then there is no guarantee clusterctl (e.g. clusterctl upgrade) will work

**Comment by dhawal55** [comment]
@fabriziopandini oh ya, I already have cert-manager pulled out in yaml since we deploy multiple capi providers in a cluster. If I generate the yamls for the new version using `clusterctl config provider`, will I still be missing any clusterctl goodies?

**Comment by fabriziopandini** [comment]
Yep. if you use kubectl apply to create providers then you are on your own...

**Comment by fabriziopandini** [comment]
/close
feel free to re-open if there are still pending questions
