### ISSUE TITLE
clusterctl should block its usage across minor versions of CAPI

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#3534]
**User Story**

As a user I would like to ensure that I'm using the appropriate version of clusterctl with a management cluster because I do not want to have unexpected side effects when performing cluster operations.

**Detailed Description**

If we have a v1alpha3 management cluster (which may have been created by `clusterctl-v1a3 init`), then we should be blocked from using a clusterctl cli from a newer minor release (e.g. `clusterctl-v1a4 init -i <infra>`). However, we still want upgrades to work.
`clusterctl-v1a3 --> clusterctl from a v0.3.x release`
`clusterctl-v1a4 --> clusterctl from a v0.4.x release`

**Anything else you would like to add:**
- See last discussion topic in [meeting notes from Aug 26, 2020](https://docs.google.com/document/d/1fQNlqsDkvEggWFi51GVxOglL2P1Bvo2JhZlMhm2d-Co/edit#heading=h.bry1m1cz2gt9).
- See https://github.com/kubernetes-sigs/cluster-api/pull/3484#discussion_r473115371 for other relevant discussion

**Other questions to consider:**
- **Q:** From the meeting notes, when we say  `clusterctl-v1a4` cannot be used with `clusterctl-v1a3`, what do we mean by that? Do we mean that a management cluster that has been initialized by `clusterctl-v1a3` cannot be operated on by `clusterctl-v1a4` (_except for upgrades_)? 
- **Q:** For [n-Core multi-tenancy](https://cluster-api.sigs.k8s.io/clusterctl/commands/init.html#multi-tenancy), are we expecting users to have two versions of`clusterctl`'s installed if there are two versions of management clusters installed in separate namespaces on the same k8s cluster?
- **Q:** Regarding provider metadata, it seems this is a solution that decoupled the version of `clusterctl` vs. the management cluster contract. Do we need to have an option that allows upgrading across contract versions based on the version of `clusterctl` used?

 
/kind feature
/area clusterctl

**Comment by fabriziopandini** [comment]
+1 to this
IMO the most tricky part is that in a multitenancy scenario a management cluster could be both v1alpha3 and v1apha4 at the same time. Happy to brainstorm about how to get this addressed

**Comment by vincepri** [comment]
/priority important-soon

One clarification, clusterctl shouldn't support environments running multiple different versions of the controllers going forward

**Comment by wfernandes** [comment]
Yes, moving forward this may look a little different. We **may** have to ensure that there is consistency between the clusterctl CLI and the management cluster operator versions rather than the version of the management cluster itself.

**Comment by fabriziopandini** [comment]
/close
This has been fixed by the work in preparation for v1alpha3 --> v1alpha4 upgrades
