### ISSUE TITLE
Add documentation for clusterctl sub-command `get kubeconfig`

### ISSUE THREAD

**Issue by prankul88** [kubernetes-sigs/cluster-api#3535]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Clusterctl added subcomand `get kubeconfig` command via #3460 .
Although the documentation for the same is missing in the cluster-api book.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind documentation
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by iamemilio** [comment]
@wfernandes, I was just reading through the quick start, and it seems like the most logical place to add this would be in the clusterctl overview docs linked in the next steps at the end. I just wanted to verify that this makes sense.

**Comment by fabriziopandini** [comment]
IMO the new command should be documented with a new link in [clusterctl commands](https://cluster-api.sigs.k8s.io/clusterctl/commands/commands.html) opening a page under [this folder](https://github.com/kubernetes-sigs/cluster-api/tree/master/docs/book/src/clusterctl/commands) that already hosts the reference for all the other commands.
It will be great to link the page from the quick start where we are calling the command at the end of the [accessing-the-workload-cluster](https://cluster-api.sigs.k8s.io/user/quick-start.html#accessing-the-workload-cluster) paragraph.

**Comment by prankul88** [comment]
@fabriziopandini Thank you for clarification. 

> IMO the new command should be documented with a new link in clusterctl commands opening a page under this folder that already hosts the reference for all the other commands.

@iamemilio I guess this is all I had in mind :)
