### ISSUE TITLE
KCP reports nil error message when there are etcd health problems

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3537]
**What steps did you take and what happened:**
While creating a cluster with KCP I noticed this event:
```
 kubectl get events
LAST SEEN   TYPE      REASON                  OBJECT                                MESSAGE
...
7m21s       Warning   ControlPlaneUnhealthy   kubeadmcontrolplane/test1             Waiting for control plane to pass etcd health 
check to continue reconciliation: <nil>
...
```

**What did you expect to happen:**
The event to provide the error message

**Anything else you would like to add:**

**Environment:**

/kind bug

**Comment by ncdc** [comment]
Is this the same as #3519?
