### ISSUE TITLE
any criteria to `clusterctl move` action?

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#3542]
**User Story**

we created a secret in bootstrap cluster and I found it's not moved to new cluster (target)
any reference what kind of secret will be moved from bootstrap to new one? 

https://cluster-api.sigs.k8s.io/clusterctl/commands/move.html didn't give detail info on it

if the secret is not moved automatically, then I have to guide user to recreate it at target cluster as well.. so need some guide

As a [developer/user/operator] I would like to [high level description] for [reasons]

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
/triage support

@jichenjc internals of clusterctl move are documented [here](https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#move).

Following paragraphs might be of interest as well:
- https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#ownerreferences-chain
- https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#links-to-external-objects

**Comment by jichenjc** [comment]
thanks, I will dig more with the info , appreciate~ 
@fabriziopandini

**Comment by fabriziopandini** [comment]
feel free to reach out for any question
