### ISSUE TITLE
Consider moving MachineHealthCheck into a different API group

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#3547]
MachineHealthCheck is today part of the core types. As we approach v1alpha4, I'd like to propose to move this type into a different API group under Cluster API. This move would allow us to further extend the ability for different kinds of healthcheck in the future targeted at different environments (e.g. control plane, external etcd, and so on) without potentially slowing down the core types to get to v1beta1.

Given that an API group transition can't be performed with conversion webhooks, in v1alpha4 we can keep a controller that when it receives `core/MachineHealthCheck` converts and creates a `<group>/MachineHealthCheck`. We'd remove this logic in v1alpha5/v1beta1.

Thoughts?

/kind cleanup
/milestone v0.4.0

**Comment by fabriziopandini** [comment]
I'm +1 to keep the core Cluster API scoped.

MHC should be a pluggable/replaceable component, like CAPBK or KCP
WRT to the conversion controller, +1 as well, because it could be an interesting pattern to explore

**Comment by JoelSpeed** [comment]
As the MHC scope seems to have grown a lot since the original implementation, and is likely going to undergo many further changes as we stabilise on external remediation vs conditions etc, I think this makes a lot of sense. 
+1 from me

**Comment by jan-est** [comment]
+1 to this.

**Comment by detiber** [comment]
+1 from me
