### ISSUE TITLE
clusterctl unable to delete multiple providers from a namespace

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#3558]
**What steps did you take and what happened:**
1. `clusterctl init --infrastructure docker --target-namespace foobaz`
1. `clusterctl delete --core cluster-api --bootstrap kubeadm --control-plane kubeadm --infrastructure docker --namespace foobaz`
    This command only deletes the core `cluster-api` provider.`
1. If I run the same command again, it only deletes the boostrap `kubeadm` provider.
1. If I run the same command the third time, it only deletes the control-plane `kubeadm` provider.
1. Finally, if I run the command again, it then deletes the infrastructure provider `docker`.

**What did you expect to happen:**
I expected all the specified providers within that namespace to be deleted. 

Perhaps it would be convenient to do something like `clusterctl delete --all --namespace foobaz` to delete all the providers within the specified namespace.

**Anything else you would like to add:**
This issue was raised in slack. [See slack thread for context](https://kubernetes.slack.com/archives/C8TSNPY4T/p1598384161097900).

**Environment:**
- Cluster-api/clusterctl version: v0.3.9

/kind bug
/area clusterctl

**Comment by fabriziopandini** [comment]
The behavior above is totally unexpected, the command should not change its behavior in subsequent runs 

In the original intern, -all was an alternative to deleting single providers, and --namespace was an option to delete a single provider in case of multitenancy (so --all and --namespace were not meant to be used together)

However I see that the flags now allows for different permutations, so I'm ok in supporting (and documenting) different scenarios
