### ISSUE TITLE
Add version print column for MachinePool

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api#3561]
Apply the changes in https://github.com/kubernetes-sigs/cluster-api/pull/3560 to MachinePool.

This can be done by adding a printcolumn line to https://github.com/kubernetes-sigs/cluster-api/blob/master/exp/api/v1alpha3/machinepool_types.go#L207.

/good-first-issue
/help
/kind feature

**Comment by Evalle** [comment]
I can help with that
/assign
