### ISSUE TITLE
Kubernetes upgrades to v1.19 are flaky

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#3564]
During today session, we manually tested upgrading Kubernetes clusters from v1.18 to v1.19. More often than not, upgrades didn't successfully complete.

From @ncdc:
> In Kubernetes 1.19.0, the certificates API (which does CertificateSigningRequests for node bootstrapping, among other things) introduced version v1. The kube-controller-manager switched to only speaking v1 of this API.
>
> If you have a control plane with a load balancer in front, it is possible/likely that during an upgrade from 1.18 to 1.19, the 1.18 kube-controller-manager will be removed (as part of deleting one of the old machines), and the 1.19 kube-controller-manager will potentially acquire the leader election lock. It then connects to the load balancer, and there’s a chance it gets routed to one of the remaining 1.18 apiservers. If/when this happens, the kube-controller-manager will be unable to process any new CertificateSigningRequests (because it’s asking for certificates v1, which doesn’t exist in 1.18). This means all new node bootstrapping will fail.
>
> The solution is to update kubeadm so the kube-controller-manager, kube-scheduler, and kubelet of control plane nodes talk to the local API endpoint for the apiserver (i.e. the local apiserver static pod), instead of going through the load balancer.

For more information see [this slack thread](https://kubernetes.slack.com/archives/C8TSNPY4T/p1598899864038100).

Related to https://github.com/kubernetes/kubeadm/issues/2270 and https://github.com/kubernetes/kubeadm/issues/2271.

/milestone v0.3.10
/kind bug

**Comment by vincepri** [comment]
/close

This has been fixed with Kubernetes 1.19.1

**Comment by chymy** [comment]
> This has been fixed with Kubernetes 1.19.1

Hi， @vincepri, Why not update the code？
https://github.com/kubernetes-sigs/cluster-api/blob/d1dc87d5df3ab12a15ae5b63e50541a191b7fec4/controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go#L475-L486

Upgrading from k8s1.17.9 to 1.19.4 also failed.

**Comment by chymy** [comment]
Why not upgrade across 2 Minor versions? Is it related to API compatibility?

https://github.com/kubernetes-sigs/cluster-api/blob/d1dc87d5df3ab12a15ae5b63e50541a191b7fec4/controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go#L488-L504

**Comment by neolit123** [comment]
K8s components have a version skew and skipping minor versions is not
supported.

https://kubernetes.io/docs/setup/release/version-skew-policy/
