### ISSUE TITLE
[Release v0.3.9] No more binaries and yamls for v0.3.9, expected?

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cluster-api#3565]
**What steps did you take and what happened:**
v0.3.9 release has no yamls and binaries. Is it expected?

With Kind v0.8.0, I tried clusterctl v0.3.6 and v0.3.8 to run `clusterctl init` but it failed and said that:
`Fetching providers
Fetching File="core-components.yaml" Provider="cluster-api" Version="v0.3.9"
Error: failed to get provider components for the "cluster-api" provider: failed to read "core-components.yaml" from provider's repository "cluster-api": failed to download files from GitHub release v0.3.9: failed to get file "core-components.yaml" from "v0.3.9" release`

Thanks!

**Comment by fabriziopandini** [comment]
It seems that something went wrong with the release.
Checking 
/cc @vincepri

**Comment by ncdc** [comment]
I think this has been resolved. Closing. Please reopen if you continue to have issues. Thanks.

/close
