### ISSUE TITLE
Adding a pause possibility for deployment roll outs

### ISSUE THREAD

**Issue by maelk** [kubernetes-sigs/cluster-api#3568]
**User Story**

As a baremetal cluster operator, I would like to be able to pause the roll out of my deployments. Considering the time required to deploy a node on hardware, I might be limited by the size of my maintenance window for the updates of my nodes. I could start a the roll out of a deployment and need to temporarily stop it when reaching the end of my maintenance window. I would resume it during the next maintenance window.

**Detailed Description**

As the operator, I need to be able to pause the rolling out. However, this should not prevent me from doing any other LCM activities (such as scale out or scale in possibly). I do not want to pause the machine deployment object, to allow for automatic recovery (based on healthcheck) and other LCM operations.

**Anything else you would like to add:**

This could be achieved by adding an annotation such as `cluster.x-k8s.io/pause-rollout:""` on the machine deployments. A way to achieve this would be to consider maxSurge to be 0 (here https://github.com/kubernetes-sigs/cluster-api/blob/b9f238938280b4c8248c22e50f72d44ea59b9238/controllers/mdutil/util.go#L519) and minAvailable to be equal to the desired number of replicas (here https://github.com/kubernetes-sigs/cluster-api/blob/c8527be29adb86b18daaf0ecdbcb259aacc60cc9/controllers/machinedeployment_rolling.go#L245) when the annotation is present. This means that while the roll out is paused, the number of replicas would be as desired. It would still allow for scale-out and scale-in operations, where machines would be added to the new machine set and removed from the old machine sets.

/kind feature

**Comment by vincepri** [comment]
Would the `spec.paused` field work in this use case https://github.com/kubernetes-sigs/cluster-api/blob/3da81fa4261847394ad6619e1a3cb27d3f0b4811/api/v1alpha3/machinedeployment_types.go#L83-L85?

We also have the paused annotation that stops reconciliation on an object

**Comment by maelk** [comment]
If we were to use the pause annotation on the object, then we would not be able to do some LCM actions, such as scalings. We want to pause only the update part of the reconciliation, without removing the possibility to change the number of replicas.

**Comment by vincepri** [comment]
Can you use spec.Paused field instead?

**Comment by maelk** [comment]
yes, that will do, thanks!
/close
