### ISSUE TITLE
Add tests for CAPI e2e for main branch of Kubernetes

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#3569]
The following e2e tests are required to provide good signal for upcoming Kubernetes releases

* Create and tear down of Kubernetes main branch
* Run conformance tests on main branch (currently done in CAPA)
* Upgrade of a cluster from (main branch - .1) to main branch.

/area testing
/priority important-critical

Related to #3564

**Comment by vincepri** [comment]
@randomvariable The related PR has merged, should we switch the milestone, seems there is still more work in this issue

**Comment by randomvariable** [comment]
Yes, please switch. The largest chunk got merged, but there's still CAPD e2e to actually make use of the new packages.

**Comment by randomvariable** [comment]
/lifecycle cancel
Pending https://github.com/kubernetes-sigs/cluster-api/issues/3569

**Comment by fabriziopandini** [comment]
@vincepri @ncdc @naadir @jdetiber @cecile 
While #3652 provided a viable solution for all the "real" infrastructure providers, IMO downloading CI artifacts on each node, is not a viable solution for CAPD where all the machines are containers running on a single/resource-limited prow machine.

So I’m leaning towards using `kind build node-image` so we have a docker image with everything pre-loaded to be used for creating CAPD machines.

This step takes ~20 minutes but assuming these jobs are periodic, I don't see problems.
Opinions?

**Comment by ncdc** [comment]
👍

**Comment by fabriziopandini** [comment]
/close
this is being supersede by https://github.com/kubernetes-sigs/cluster-api/issues/4043
