### ISSUE TITLE
[e2e] Reduce PR blocking e2e test duration

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#3570]
Current e2e tests take ~40 minutes for each PR, which is pretty slow to get a signal back.

Some remediations to get signal quickly without overloading prow resources:
- [x]  We can divide e2e tests into 3 categories as:
       - PR blocking smoke test: Have only `Quick Start` test as PR blocking
       - Periodic tests: Run all e2e tests periodically
       - Post-submit tests: Run all e2e tests after PRs are merged
- [x] Skip running tests for doc-only changes. 

/milestone v0.3.10

**Comment by wfernandes** [comment]
I think this issue can be closed as a result of the following PRs that have been merged.
https://github.com/kubernetes/test-infra/pull/19092
https://github.com/kubernetes/test-infra/pull/19103
https://github.com/kubernetes/test-infra/pull/19113

**Comment by sedefsavas** [comment]
Yes closing, post-submit jobs may be added in the future if periodic tests do not provide enough signalling.
