### ISSUE TITLE
cluster move --dry-run ? 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#3574]
**User Story**

I want to test whether I can move something from bootstrap to target cluster
is it reasonable to provide a comment to test what to be moved and what will be kept but
not really move them? 

if it's reasonable, I can work on it

/kind feature

**Comment by fabriziopandini** [comment]
I'm +1
This is somehow related to https://github.com/kubernetes-sigs/cluster-api/issues/3441 (it is kind of a dry run that outputs yaml)
