### ISSUE TITLE
Document how to triage E2E test failures

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3576]
**User Story**

As a developer, I would like to understand how to investigate E2E test failure and how to get access to the test logs

/kind documentation

**Comment by vincepri** [comment]
@fabriziopandini Are you still working on this?

**Comment by fabriziopandini** [comment]
IMO this can be closed, see https://master.cluster-api.sigs.k8s.io/contributing#triaging-e2e-test-failures

**Comment by vincepri** [comment]
SGTM

/close
