### ISSUE TITLE
Remove CAPD's aggressive deletion of machines

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#3581]
CAPD deletes and replaces machines if they fail to bootstrap. This was previously done to handle flakes, but it can mask errors, and make things difficult to debug.

Additionally, this behaviour is unlike most of the other providers, which explicitly fail a Machine for user intervention or for cleanup by MHC.

**Comment by CecileRobertMichon** [comment]
We actually still do that in CAPZ https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/controllers/azuremachine_controller.go#L292, I've been wanting to remove it but was waiting for MHC to work for control planes.

**Comment by vincepri** [comment]
@fabriziopandini Are you still working on this?

**Comment by fabriziopandini** [comment]
I added my name here, but it was @Boutheina-Dab who actually sent a PR

**Comment by vincepri** [comment]
/milestone Next

Going to remove from release, let's unblock the PR if possible
