### ISSUE TITLE
Clusterctl client cant be used anymore with custom provider and repository clients

### ISSUE THREAD

**Issue by teoyaomiqui** [kubernetes-sigs/cluster-api#3584]
**What steps did you take and what happened:**

We are using clusterctl version 0.3.6 as a library (not as a command line).
It was very nice to use, as it has provided a ways to inject custom providers, which we did. We don't want to rely on upstream providers and don't want to have components.yaml files on filesystem. Instead we use kustomize to implement [repository interface](https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/client/repository/client.go#L129-L149)

This allows us to build our own provider components, and keep them downstream, without need to access internet, and they fit greatly in our yaml engine built on top of kustomize.

We do this, by injecting our own implementation of repository interface for provider, when provider is requested by clusterctl client, [here is example how we do this](https://github.com/airshipit/airshipctl/blob/master/pkg/clusterctl/client/client.go#L104-L108)

It did work perfectly, and was a great help for us.

However a [recent change to clusterctl.Client construction process](https://github.com/kubernetes-sigs/cluster-api/commit/e87da61eaec4eeb5d0cd702099e2b8380b2ba719#diff-8784430185de824e528f4d2613cbb305R67-R81) , made the fields in input private. And we simply can not inject our own provider implementation, because fields following structs are private:
```
type ClusterClientFactoryInput struct {
	kubeconfig Kubeconfig
	processor  Processor
}
type RepositoryClientFactoryInput struct {
	provider  Provider
	processor Processor
}
```

**Proposed fix**

Make the fields in  [ClusterClientFactoryInput and RepositoryClientFactoryInput](https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/client/client.go#L86-L97) public, this will enable external integration with clusterctl as a library again.

Thank you, and sorry, because I am not sure if it's a feature request or a bug

**Environment:**
- Cluster-api version: 0.3.9

/kind bug
/area clusterctl
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by teoyaomiqui** [comment]
@Arvinderpal  may also assist here in explaining.

**Comment by ncdc** [comment]
👍 

@teoyaomiqui @Arvinderpal do you have availability to make the changes and open a PR?

**Comment by teoyaomiqui** [comment]
@ncdc I we can manage that

**Comment by ncdc** [comment]
Great! Please feel free to `/assign` and mark `/lifecycle active` when you're working on it.
