### ISSUE TITLE
Doc only PR should not run unit tests

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3591]
Doc only PR should not run pull-cluster-api-test, and probably also some other job as well.
e.g. It could be interesting to investigate if we can avoid to run all the verification test (by breaking down docs related verification tests and other verification tests)

**Comment by fabriziopandini** [comment]
@wfernandes @sedefsavas ^^

**Comment by vincepri** [comment]
I'm fine to keep running the `-test` one but exclude the `-e2e` which I think we've already been doing, the test job doesn't take that long?

**Comment by fabriziopandini** [comment]
yes, this is a nit, but the test job is flaky and we are using prow resources that we can spare...

**Comment by vincepri** [comment]
We should fix the test job, @wfernandes is working on the MHC tests next week

**Comment by vincepri** [comment]
Now that we've split the tests, and @wfernandes is rewriting MHC tests, I think we can close this

/close
