### ISSUE TITLE
bash/zsh auto completion for clusterctl

### ISSUE THREAD

**Issue by superbrothers** [kubernetes-sigs/cluster-api#3595]
**User Story**

As a developer/user/operator, I would like to use bash/zsh auto completion for clusterctl for improving work efficiency.

**Detailed Description**

I'd like to use bash/zsh auto completion for clusterctl command, like `kubectl completion` command.

```
$ source <(clusterctl completion bash)
```

I believe this will improve the experience for everyone - developers/users/operators.

**Anything else you would like to add:**

None

/kind feature

**Comment by superbrothers** [comment]
Auto completion of the kubectl command is provided by `spf13/cobra` library, and clusterctl also uses that library, so it can be provided easily.

I propose offering features in the next step:

1. Providing auto completion for subcommands and arguments
     - Implementation of `clusterctl completion bash/zsh` command
2. Providing dynamic auto completion for cluster-api objects
     - Such as cluster object name completion for `clusterctl get kubeconfig` command

If you feel this is good, I'll try to implement it.

**Comment by fabriziopandini** [comment]
Personally I'm +1 for 1 as a first step

**Comment by vincepri** [comment]
/milestone v0.4.0

Setting v0.4 as milestone for now, if it's a small enough change we can definitely backport this given that it could be useful
