### ISSUE TITLE
cmd/clusterctl/hack/create-local-repository.py does not work with Python 3

### ISSUE THREAD

**Issue by bboreham** [kubernetes-sigs/cluster-api#3601]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

On a machine where `python` runs Python version 3.8.2:
```
$ cmd/clusterctl/hack/create-local-repository.py
Traceback (most recent call last):
  File "cmd/clusterctl/hack/create-local-repository.py", line 182, in create_dev_config
    f.write(yaml)
TypeError: a bytes-like object is required, not 'str'
```

**What did you expect to happen:**

Expected it to run without throwing a low-level error.

**Anything else you would like to add:**

On this line: https://github.com/kubernetes-sigs/cluster-api/blob/5164a1f0e2a9f4bb6c1c3ebe304877ee470ac9c5/cmd/clusterctl/hack/create-local-repository.py#L181
changing `wb` to `w` appears to get past the problem.

**Environment:**

- Cluster-api version: commit 5164a1f0e2a9f4bb6c1c3ebe304877ee470ac9c5 on master

/kind bug

**Comment by fabriziopandini** [comment]
@bboreham thanks for reporting
Do you think you can send a patch with the suggested fix?

/milestone v0.3.10
/area clusterctl

**Comment by bboreham** [comment]
I can do, yes. 

Would be good if some Python-knowledgable person could weigh in on what we should do; I just Googled the error message.
