### ISSUE TITLE
Breaking API change in clusterctl for 0.3.9

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#3607]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
https://github.com/kubernetes-sigs/cluster-api/pull/3332 deleted the `CNIManifestPath` field from the `clusterctl.ApplyClusterTemplateAndWaitInput` struct

This effectively broke CAPA's e2e tests.

**What did you expect to happen:**
No breaking changes to e2e.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 0.3.9
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by CecileRobertMichon** [comment]
FYI this is how we went around it in CAPZ in the meantime https://kubernetes.slack.com/archives/C8TSNPY4T/p1598996683093800

**Comment by fabriziopandini** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/3332#discussion_r454611129 😓 
Sorry I did not double-checked this thread in the review 

Also we are kind of lagging in getting https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1816 merged to switch CAPA to use CRS for installing CNIs
