### ISSUE TITLE
Failed to create cluster with cluster-api v0.3.9

### ISSUE THREAD

**Issue by yannalf** [kubernetes-sigs/cluster-api#3638]
**What steps did you take and what happened:**
kind cluster create 
clusterctl config cluster clmngt --kubernetes-version x.x.x --control-plane-machine-count=1 --worker-machine-count=1 > /var/tmp/file.yaml 

kubectl apply -f /var/tmp/file/yaml 
cluster.cluster.x-k8s.io/clmngt created
vspherecluster.infrastructure.cluster.x-k8s.io/clmngt created
vspheremachinetemplate.infrastructure.cluster.x-k8s.io/clmngt created
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/clmngt created
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/clmngt-md-0 created
machinedeployment.cluster.x-k8s.io/clmngt-md-0 created
secret/vsphere-csi-controller created
configmap/vsphere-csi-controller-role created
configmap/vsphere-csi-controller-binding created
secret/csi-vsphere-config created
configmap/csi.vsphere.vmware.com created
configmap/vsphere-csi-node created
configmap/vsphere-csi-controller created
**Error from server (InternalError): error when creating "/var/tmp/clmngt.yaml": Internal error occurred: failed calling webhook "default.clusterresourceset.addons.cluster.x-k8s.io": the server could not find the requested resource**

Error from server (InternalError): error when creating "cluster-quickstart.yaml": Internal error occurred: failed calling webhook "default.clusterresourceset.addons.cluster.x-k8s.io": the server could not find the requested resource

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.9
- KIND version: 0.9.0
- Kubernetes version: (use `kubectl version`): 1.9.1
- OS (e.g. from `/etc/os-release`): CentOS 7 

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by yannalf** [comment]
Same issue with king version 0.8.1

**Comment by fabriziopandini** [comment]
/triage support

If I got this right, you have to enable the experimental feature ClusterResourseSet before using a template that leverage on this feature. See https://cluster-api.sigs.k8s.io/tasks/experimental-features/experimental-features.html

**Comment by fabriziopandini** [comment]
@yannalf
does the suggestion above solve your problem?

**Comment by yannalf** [comment]
Yes ..thanks a lot

**Comment by vincepri** [comment]
Thank you all!
