### ISSUE TITLE
Capture machine logs for the bootstrap cluster in E2E test

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3640]
https://github.com/kubernetes-sigs/cluster-api/pull/3580 introduce the machine log collector and implemented log collection for all the workload cluster created during E2E tests.

We should now implement machine log collection for the bootstrap cluster as well

/kind feature
/priority backlog

**Comment by fabriziopandini** [comment]
/help

/milestone Next
But we can merge this as soon as it is ready

**Comment by tcordeu** [comment]
@fabriziopandini can I work on this issue?

/remove-lifecycle stale

**Comment by fabriziopandini** [comment]
@tcordeu Sure!
/assign @tcordeu 
/lifecycle active

**Comment by randomvariable** [comment]
I know we don't have a label for it, but just for tracking

/area node-agent
