### ISSUE TITLE
Collect pods logs from workload clusters during E2E tests

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3641]
We should implement a mechanism to collect pods logs from workload cluster during e2e tests

A possible solution is to leverage on the machine log collector introduced by #3580 
`kind export logs` could be used as a reference on how to do this

As an additional step, once this is implemented, we should consider if to drop the streaming mechanism in place for controller pods.

/priority backlog
/kind feature

**Comment by fabriziopandini** [comment]
/area testing
/help

/milestone next
We can always pull this into a release as soon as it is ready

**Comment by arghya88** [comment]
@fabriziopandini I am interested in contributing this..Is it possible to assign this to me?

**Comment by fabriziopandini** [comment]
@arghya88 sure!
/assign @arghya88
/lifecycle active

**Comment by arghya88** [comment]
@fabriziopandini executing `docker logs` in docker_logcollector.go file should do it right?

**Comment by fabriziopandini** [comment]
@arghya88 given that we want to collect all the logs, I think the approach implemented in kind export logs is more robust.

**Comment by arghya88** [comment]
@fabriziopandini I looked at how kind export logs work. They execute common commands(https://github.com/kubernetes-sigs/kind/blob/master/pkg/cluster/internal/providers/common/logs.go#L15) and then each provider(podman, docker) execute provider specific command "docker logs" or "podman logs" as we can see here(https://github.com/kubernetes-sigs/kind/blob/master/pkg/cluster/internal/providers/docker/node.go#L169)

**Comment by tcordeu** [comment]
Can I work on this one, @arghya88 @fabriziopandini?

**Comment by fabriziopandini** [comment]
@tcordeu sure things!
/assign @tcordeu 
/lifecycle active
