### ISSUE TITLE
clusterctl get kubeconfig in EKS cluster

### ISSUE THREAD

**Issue by felipeweb** [kubernetes-sigs/cluster-api#3645]
**User Story**

As a [developer/user/operator] I would like to get user's kubeconfig using clusterctl

**Detailed Description**

CAPA generates 2 kubeconfigs for EKS cluster.
- [cluster-name]-kubeconfig  that has short life and is used internally
- [cluster-name]-user-kubeconfig for the user's usage

clusterctl get kubeconfig returns the kubeconfig that should be used only internally

I think clusterctl as an operator tool should returns the [cluster-name]-user-kubeconfig if exists

/kind feature

**Comment by felipeweb** [comment]
if it is ok I can send a PR

**Comment by fabriziopandini** [comment]
@felipeweb, I'm not aware of the implementation details of the EKS provider, but my first reaction to this request is that we should change EKS to use the same name that is used by other providers for the kubeconfig file for users usage (and pick up another name for the short-lived, internal one).

Also, I'm guessing if having a different name for the kubeconfig can lead to other errors down the path. e.g I'm thinking to MachineHealthChecks, but also the Machine controller when triggering drain, the cluster cache tracker used by many controllers...

**Comment by felipeweb** [comment]
make sense! I will open an issue on CAPA for better understand and maybe change the kubeconfigs name

**Comment by fabriziopandini** [comment]
/close
given that this will be fixed in CAPA / in the EKS provider
