### ISSUE TITLE
:bug: hack/create-local-repository.py write yaml file fails

### ISSUE THREAD

**Issue by Jaakko-Os** [kubernetes-sigs/cluster-api#3647]
**What steps did you take and what happened:**
After https://github.com/kubernetes-sigs/cluster-api/pull/3614 was merged I'm running into:

Traceback (most recent call last):
File "cmd/clusterctl/hack/create-local-repository.py", line 130, in write_local_repository
f.write(components_yaml)
TypeError: write() argument must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "cmd/clusterctl/hack/create-local-repository.py", line 241, in
repos = list(create_local_repositories())
File "cmd/clusterctl/hack/create-local-repository.py", line 162, in create_local_repositories
components_path = write_local_repository(provider, next_version, components_file, components_yaml)
File "cmd/clusterctl/hack/create-local-repository.py", line 138, in write_local_repository
raise Exception('failed to write {} to {}: {}'.format(components_file, provider_folder, e))
Exception: failed to write core-components.yaml to /home/****/.cluster-api/dev-repository/cluster-api/v0.3.8: write() argument must be str, not bytes

**What did you expect to happen:**

Expect no error.

**Anything else you would like to add:**

I was running controlplane component upgrade using clusterctl at the time of the failure.
Using 'wb' instead of 'w' here https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/hack/create-local-repository.py#L129 solved the issue.

**Environment:**

- Cluster-api version: v.0.3.5
- Minikube version: v1.13.0
- Kubernetes version: (use `kubectl version`): v1.19.0
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by bboreham** [comment]
Which version of Python do you have?

**Comment by Jaakko-Os** [comment]
> Which version of Python do you have?

Sorry for the delay in my reply. I had the information on the PR itself.
$ python --version
Python 3.6.8

**Comment by Jaakko-Os** [comment]
fixed by https://github.com/kubernetes-sigs/cluster-api/pull/3648
