### ISSUE TITLE
Improve MHC e2e tests

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3656]
The current MHC object in E2E tests is specifically configured to always trigger remediation after 30s the node is started.

https://github.com/kubernetes-sigs/cluster-api/blob/0cf9f80b63047b0694b668bee6eff6dfd046e16b/test/e2e/data/infrastructure-docker/bases/mhc.yaml#L15-L18

As per comment https://github.com/kubernetes-sigs/cluster-api/pull/3651#pullrequestreview-489763332

Can we revisit this? I understand the goal here is to make MHC fail and remediate after 30s, but if we could actually flip this to control when this happens and reduce the timeout, that would probably be better?

For example, our tests could be a little bit more controlled if we apply the unhealthy condition, wait for the timeout, and ultimately check that health check or remediation happened.

/kind feature

**Comment by fabriziopandini** [comment]
This work should possible address also testing for KCP remediation

**Comment by tcordeu** [comment]
@fabriziopandini Going to work on this issue, feel free to unassign me if someone is working on it!

/assign @tcordeu
/lifecycle active

**Comment by vincepri** [comment]
Thank you @tcordeu !

**Comment by fabriziopandini** [comment]
@tcordeu are you still working on this issue?
I'm working on https://github.com/kubernetes-sigs/cluster-api/issues/3913 and given that the two things are strictly related I can tackle this as well

**Comment by tcordeu** [comment]
Go ahead!

/unassign
