### ISSUE TITLE
Book preview does not render tabs

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3658]
**What steps did you take and what happened:**
If I open the preview of the Cluster API book at https://master.cluster-api.sigs.k8s.io/user/quick-start.html is does not see tabs:
<img width="589" alt="Screenshot 2020-09-17 at 14 53 10" src="https://user-images.githubusercontent.com/5013060/93473031-c8eef180-f8f5-11ea-819a-b6e3c449db95.png">

**What did you expect to happen:**
To see tabs, like I can see when I run `make serve-book`:
<img width="522" alt="Screenshot 2020-09-17 at 14 50 19" src="https://user-images.githubusercontent.com/5013060/93473140-ed4ace00-f8f5-11ea-8709-8879e7eadfe1.png">

**Anything else you would like to add:**
From a quick look at the HTML, the web site at master.cluster-api.sigs.k8s.io does not apply transformations to {{tabs}}{{tab}} directives at all, so most probably there is some problem in the site generation part, not in the page source. 

/kind bug
/area documentation

**Comment by vincepri** [comment]
This is likely a misconfiguration in the source code, extra parenthesis or something

**Comment by fabriziopandini** [comment]
/re-open

@vincepri, unfortunately, the preview on  https://master.cluster-api.sigs.k8s.io/user/quick-start.html is still borked (and local preview is still ok)

**Comment by fabriziopandini** [comment]
/reopen
third try 😄

**Comment by vincepri** [comment]
That's strange, the build command should be the same across all branches

**Comment by vincepri** [comment]
@detiber Would you be able to look at netlify's builds for the main branch? I don't seem to have the ability to find the logs, I can only see the public preview websites

**Comment by ncdc** [comment]
Try https://app.netlify.com/sites/kubernetes-sigs-cluster-api/deploys

**Comment by vincepri** [comment]
That's super strange, it seems https://app.netlify.com/sites/kubernetes-sigs-cluster-api/deploys/5f64bf7173642c0007d681d7 got deployed and it's definitely broken

**Comment by detiber** [comment]
I didn't see anything out of place in the logs, but I went ahead and kicked off a new build (with clearing the cache) to see if it resolves the issue.

**Comment by detiber** [comment]
So, I noticed when attempting to test this locally that I was able to reproduce it locally. It took me a bit to figure out that it was because I didn't already have the pre-processors built, and that they were failing to build because my system couldn't resolve `vbom.ml/util`

**Comment by fabriziopandini** [comment]
@detiber thanks! for jumping on this!

**Comment by detiber** [comment]
It looks like the tabs are working again now that #3671 has been merged and deployed: https://master.cluster-api.sigs.k8s.io/
