### ISSUE TITLE
kube-controller-manager and kube-scheduler do not send metrics when upgrading to k8s 1.18.8

### ISSUE THREAD

**Issue by scottdhowell3** [kubernetes-sigs/cluster-api#3663]
**What steps did you take and what happened:**
Upgraded two of our clusters to k8s 1.18.8, when this happened alertmanager began to show that kube-controller-manager and kube-scheduler were no longer in the prometheus target discovery.

Discovered in this upgrade of k8s 1.18.8 with the CAPA AMI that kubeadm was upgraded and added a flag on kube-controller-manager and kube-scheduler configurations `--port=0`. This causes both of these components to no longer serve non-http traffic. 

To test if we could fix this issue I manually changed the configurations, I did this by changing the `bind-address` on both components from `bind-address=127.0.0.1` to `bind-address=0.0.0.0`. This allowed for the components to begin communicating securely. 

When I went to implement this inside our CAPI components I discovered when rolling this out that the `bind-address` is not recognized inside the `kubeadmcontrolplane.yaml`.

**What did you expect to happen:**
When adding the `bind-address: 0.0.0.0` to controllerManager extraArgs and kubeScheduler extraArgs in the `kubeadmcontrolplane.yaml` this would then be reflected in the component configurations found on the control plane nodes. This would then allow these components to communicate securely.

**Anything else you would like to add:**
I was able to confirm that changing the bind address does make this work, when changing it manually.

**Environment:**

- Cluster-api version:v0.3.7 local, v0.3.6 cluster
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): v1.18.8
- OS (e.g. from `/etc/os-release`):Amazon-Linux-2

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
@scottdhowell3 
> When I went to implement this inside our CAPI components I discovered when rolling this out that the bind-address is not recognized inside the kubeadmcontrolplane.yaml.

Could you provide more detail about this? Are you meaning this change is not allowed by the validation webhooks? Because AFAIK controllerManager extraArgs and kubeScheduler extraArgs are included in KCP configurations

**Comment by fabriziopandini** [comment]
related issue https://github.com/kubernetes-sigs/cluster-api/issues/2083

**Comment by fabriziopandini** [comment]
@scottdhowell3 now that https://github.com/kubernetes-sigs/cluster-api/pull/3994 is merged, do you think this will still be a problem?
