### ISSUE TITLE
Test CAPI with different K8s versions

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3664]
**Detailed Description**

As of today CAPI e2e runs uses Kubernetes v1.18.x both for pre-submit and periodic jobs

We want to create a new periodic job running every 12h continuing to test v1.18.x and to switch existing pre-submit and periodic to v1.19

**Anything else you would like to add:**

This is the first time that we are testing more releases in CAPI so some preparation work is required.

1. remove version variables from https://github.com/kubernetes-sigs/cluster-api/blob/cde112b20c2e9b126d74e9804ad353e1765ecdc1/test/e2e/config/docker.yaml#L75-L79

2. add version variables to https://github.com/kubernetes-sigs/cluster-api/blob/cde112b20c2e9b126d74e9804ad353e1765ecdc1/test/e2e/Makefile#L67-L80

Please note that:
- Those variables should default to v1.19.x
- Those variables should be exported for the run target (e.g `run: export KUBERNETES_VERSION = foo`)
- We should use those variable to pre pull images before running the run target, as a replacement for https://github.com/kubernetes-sigs/cluster-api/blob/cde112b20c2e9b126d74e9804ad353e1765ecdc1/scripts/ci-e2e.sh#L49-L51

3. create a new periodic job configuration similar to https://github.com/kubernetes/test-infra/blob/6b5cd0510f3230e54374bb602ddd613cf2b178e3/config/jobs/kubernetes-sigs/cluster-api/cluster-api-ci.yaml#L25-L52 

By passing env variables for v1.18.x upgrades

/area testing
/kind feature

**Comment by varunpurohit76** [comment]
if this looks like a good first issue, can I take this up? might need some help though.

**Comment by vincepri** [comment]
@varunpurohit76 Feel free to take it, and assign yourself to it. Our team is usually in the `#cluster-api` Slack channel if you need to reach out, or github works as well

**Comment by fabriziopandini** [comment]
@varunpurohit76 let me know if you need some help for implementation

**Comment by fabriziopandini** [comment]
@varunpurohit76 sorry to ping you again, but It will be to understand when do you plan to work on this issue
we are planning to cut a new release the 1st of October and it will be really helpful to get v1.19 signal ...

**Comment by varunpurohit76** [comment]
hi @fabriziopandini 1st of October looks infeasible for me. I did not get a chance to start on this because of time crunch at my end.

**Comment by vincepri** [comment]
We don't have to deliver this by October 1st necessarily, sometime in October would be fine. This is definitely not a blocker for the release

**Comment by fabriziopandini** [comment]
/retitle Test CAPI about different K8s versions

Given that test were already started to use v1.19 for E2E tests.
Additionally, considering the discussions on https://github.com/kubernetes-sigs/cluster-api/issues/3783, I think that testing different version of Kubernetes should be restricted only to the tests focused on workload clusters, namely K8s conformance and K8s upgrades.

**Comment by fabriziopandini** [comment]
/close 
We are going to open more detailed issues according to https://github.com/kubernetes-sigs/cluster-api/issues/3693#issuecomment-730375355
