### ISSUE TITLE
Raise priority of infrastructure failures into the machine's ready condition summary

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3678]
In the following code https://github.com/fabriziopandini/cluster-api/blob/b545ca1215fb5a294f3b150c1b7a5296a2c59c77/controllers/machine_controller.go#L210-L214

we should raise the priority of the infrastructure failures given that this usually provides the most significant feedback for the users

/kind feature

**Comment by srm09** [comment]
@fabriziopandini Does this mean that no matter what the phase of the `Machine` is, the Infrastructure Condition should be shown higher than the Bootstrap Condition when consumed by the consumer, say `kubectl`.

**Comment by fabriziopandini** [comment]
> Does this mean that no matter what the phase of the Machine is, the Infrastructure Condition should be shown higher than the Bootstrap Condition when consumed by the consumer, say kubectl.

This change will raise the priority only in the summary (in the ready condition). However, if the consumer is interested in a specific signal, he can always look at specific conditions

**Comment by srm09** [comment]
As far as I understand, summarizing the conditions arranges all the conditions lexicographically except the Ready condition. Does this mean the ordering needs to be updated while building the summary? 
Does it make sense to add a Priority marker to each condition and the order of the conditions appearing in the summary is determined by this priority marker (which could be a simple integer)

**Comment by srm09** [comment]
According to the discussion with @fabriziopandini , the summary generation also gets affected by the actual order of the conditions specified during the summary generation.
