### ISSUE TITLE
Publish binaries in a compressed format

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#3680]
This is a breaking change, maybe starting with the next version we can publish clusterctl in a compressed format, when building the binary today it turns out at ~50MB, compressed it's more than half ~20MB.

It might be useful for a number of reasons, and it might definitely help save bandwidth in some environments

/kind cleanup
/milestone Next

**Comment by detiber** [comment]
@vincepri what about adding both, that way folks that would prefer to download the compressed binary to save bandwidth can do so without breaking existing tooling that is downloading uncompressed binaries.

**Comment by vincepri** [comment]
We can yeah, although I was hoping to just upload one and deduplicate, maybe we could do this in a phased approach?

**Comment by vincepri** [comment]
Closing this as it's not really a huge issue

/close
