### ISSUE TITLE
Make DockerMachine to report WaitingForControlPlane

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3683]
During cluster provisioning we are observing

```
    │ ├─BootstrapConfig - KubeadmConfig/test1-md-0-dv9m9    False  Info      WaitingForControlPlaneAvailable  6m56s  0 of 2 completed
    │ │             └─DataSecretAvailable                   False  Info      WaitingForControlPlaneAvailable  6m56s
    │ └─MachineInfrastructure - DockerMachine/test1-5tqgb   False  Info      WaitingForBootstrapData          6m55s
    │               └─ContainerProvisioned                  False  Info      WaitingForBootstrapData          6m55s
```

As you can see, the `DockerMachine` is reporting `WaitingForBootstrap` data, so the user is required to jump to the `KubeadmConfig` object in order to discover the real reason we are waiting, which is because we are still `WaitingForControlPlaneAvailable`

This issue advocates for getting the `DockerMachine` (but this apply to all the infrastructure machines) to report `WaitingForControlPlaneAvailable` directly, thus to avoid users a troubleshooting jump when trying to understand what is going on

/kind feature

**Comment by srm09** [comment]
IIUC this would involve mirroring the condition for the BootstrapConfig with a sensible fallback value in case the config is not found. This would be something similar to the `reconcileBootstrap` logic from the machine controller.

**Comment by fabriziopandini** [comment]
I think that it will be much easier to check `!cluster.Status.ControlPlaneInitialized`, which is the source of truth for this condition/status.

**Comment by fabriziopandini** [comment]
Sure!
/close
