### ISSUE TITLE
Implement a new E2E test for verifying clusterctl upgrades

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3690]
We should implement a new E2E test providing a signal on clusterctl upgrades

Ideally, the test should
- init a management cluster with providers in version X
- create a workload cluster
- upgrade providers to version Y using clusterctl upgrade
- check everything works fine (e.g. add a machine to the workload cluster)
- cleanup

As a first step we can implement a test using X = latest release for v0.3 series, Y = tip of v0.3 branch
Next, we should test v1alpha3 --> v1alpha4 upgrades as well

/kind feature

**Comment by vincepri** [comment]
@fabriziopandini Are you working on this now? It seems we might want to wait a bit longer before starting the work on clusterctl, given the operator work

**Comment by fabriziopandini** [comment]
@vincepri I would like to explore what does this activity means, especially for setting up a test with two versions of the same provider. 
Also, testing upgrade to the latest release in the v0.3.x series can't use the operator

**Comment by CecileRobertMichon** [comment]
+++

would be great if we can also use this to test upgrades of various providers

**Comment by fabriziopandini** [comment]
@CecileRobertMichon this should be the case.
The PR is out, waiting for feedback 😉
