### ISSUE TITLE
Add chaos testing to clusterctl framework to allow re-entrancy testing

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#3694]
**User Story**

A lot of the bugs that we had in earlier releases in CAPA and occasionally still pop up are to do around controller re-entrancy, especially since AWS API calls are not necessarily idempotent.

**Detailed Description**

Have a method to crash loop at random time intervals controllers in order to surface re-entrancy bugs. Furthermore, this could be added to provider periodic jobs to provide signal on re-entrancy

**Anything else you would like to add:**

Have also opened https://github.com/kubernetes-sigs/controller-runtime/issues/1177

/kind feature

**Comment by benmoss** [comment]
https://docs.chaostoolkit.org/ might be interesting to see if we can leverage

**Comment by vincepri** [comment]
/close

To be solved in controller-runtime
