### ISSUE TITLE
Add network failure testing for KCP

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#3695]
**User Story**

As a developer I would like to discover bugs in Cluster API or Kubernetes using the test framework.

e.g.
* what happens during a network partition, does cluster api behave properly, does KCP know what to do
* surfacing esoteric network device kernel bugs in CI rather than manual testing

**Detailed Description**

Particularly for KubeadmControlPlane, we should have mechanisms to do more extensive failure testing. For example, it should be possible to use `tc` to simulate poor network connectivity, partitions etc... and see how KCP behaves.

**Anything else you would like to add:**

Prior art:
http://jepsen.io/ 

/kind feature

**Comment by sbueringer** [comment]
As discussed in the backlog grooming on 11th February, this test makes sense on a real infrastructure provider. E.g. in AWS there is a service to inject failures in the network. 

/close

@yastij to link the related CAPA issue (or create one)
