### ISSUE TITLE
Update Kind to v0.9.x for CAPD and e2e tests

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#3696]
Currently, we are using Kind v0.7.1 for CAPD and e2e tests.
Kind v0.9.0 came out recently, we may want to wait until v0.9.1.

**Comment by tcordeu** [comment]
Hey @evalsocket can I work on these one? If so, would you mind helping me?

**Comment by tcordeu** [comment]
As Kind v0.9.0 depends on apimachinery v0.18.8 we should wait on https://github.com/kubernetes-sigs/cluster-api/pull/3735 to be merged (or to at least be stable), right?
cc @vincepri 

PS: Sorry for the questions, this is my first issue.

**Comment by fabriziopandini** [comment]
@tcordeu #3735 is merged now. Are you still up to work on this issue
?
