### ISSUE TITLE
KCP: support pluggable in-cluster DNS providers

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#3698]
**User Story**

As a user, I would like to create a new cluster using an in-cluster DNS provider of my choosing, instead of having kubeadm install CoreDNS, because I'd like to use something other than CoreDNS from the start.

As a user, I would like to manage my in-cluster DNS provider separately from KCP, decoupling their lifecycles, so that I'm in control of my DNS provider.

(Maybe out of scope?)
As a user, I would like to influence the initial CoreDNS configuration when bootstrapping my control plane, because my cluster needs custom CoreDNS settings to function correctly (both at bootstrapping time and beyond).

(Maybe out of scope?)
As a user, I would like an easy way to manage my CoreDNS configuration, including preserving my customizations when CoreDNS is upgraded.

**Detailed Description**

See user stories

**Anything else you would like to add:**

Something like a CoreDNS Operator might be useful or necessary for some of these stories.

kubeadm is currently responsible for installing CoreDNS and we'll need to be able to disable that.

/kind feature
/milestone Next

**Comment by neolit123** [comment]
similar comment as in:
https://github.com/kubernetes-sigs/cluster-api/issues/3700#issuecomment-699238907

> the current way is by passing `--skip-phase=addons` or a specific `addons/x`.
> but i guess for CAPI this has to be supported via the config:
> [kubernetes/kubeadm#2261](https://github.com/kubernetes/kubeadm/issues/2261)

**Comment by vincepri** [comment]
Close in favor of #5491 
/close
