### ISSUE TITLE
Error: unable to verify clusterctl version: unable to semver parse clusterctl GitVersion: strconv.ParseUint: parsing "": invalid syntax

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#3706]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**

during upgrade from cluster-api from 0.3.8 to 0.3.9
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/639

we found error that clusterctl can't run due to error

```
# bin/clusterctl version
clusterctl version: &version.Info{Major:"", Minor:"", GitVersion:"", GitCommit:"", GitTreeState:"", BuildDate:"", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
Error: unable to verify clusterctl version: unable to semver parse clusterctl GitVersion: strconv.ParseUint: parsing "": invalid syntax
```

the reason is CAPO CI build clusterctl 
```
2020-09-29 02:13:46.018685 | ubuntu-bionic-large | go build -o bin/clusterctl sigs.k8s.io/cluster-api/cmd/clusterctl
```
see following for detail
https://logs.openlabtesting.org/logs/39/639/5b2f18a30eb64cb2f6075c678f71e0ae9ad4baa2/check/cluster-api-provider-openstack-current-acceptance-test-v1.18/81ff221/job-output.txt.gz

so the question is how to fix it ? 
1) e.g avoid build clusterctl by CAPO  then download from master? 
2) if we want to build clusterctl , how can we do that ? 
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by jichenjc** [comment]
@hidekazuna FYI

**Comment by fabriziopandini** [comment]
/triage support
I suggest you to use make clusterctl to build the binary, so you will get all the version variables injected

See
https://github.com/kubernetes-sigs/cluster-api/blob/7bbd5cc18d0bc9c298789a1cdd50749599abbcf0/Makefile#L156
and
https://github.com/kubernetes-sigs/cluster-api/blob/master/hack/version.sh

**Comment by jichenjc** [comment]
I think I got the answer and no need to track this ...
thanks @fabriziopandini
