### ISSUE TITLE
MachineHealthCheck returns immediately on patch error

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#3712]
**What steps did you take and what happened:**
When MachineHealthCheck controller fails to patch `MachineOwnerRemediatedCondition` to one of the unhealthy Machines, it returns. https://github.com/kubernetes-sigs/cluster-api/blob/a0a8a75b1f02db5041f6a865f0c1946cb5f22e64/controllers/machinehealthcheck_controller.go#L255-L267

**What did you expect to happen:**
I expect it to try to patch that condition to the other unhealthy Machines as well and return all errors at the end.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
/close 
#3713 merged
