### ISSUE TITLE
v1alpha4: Move infra provider contract controlPlaneEndpoint to Status

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api#3715]
Original discussion: https://kubernetes.slack.com/archives/C8TSNPY4T/p1601405307103200

Following https://github.com/kubernetes-sigs/cluster-api/issues/168, ControlPlaneEndpoint was added as a required Spec field in InfrastructureCluster for v1alpha3: https://cluster-api.sigs.k8s.io/developer/architecture/controllers/cluster.html#infrastructure-provider.

However, this field is treated as Status by multiple infrastructure providers: For example, in CAPA ControlPlaneEndpoint.Host is set to match the value of the LB DNS name in the Status.Network field https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/controllers/awscluster_controller.go#L206, which means if you set that value as a user it will be ignored and overwritten.

Furthermore, as an infrastructure provider, it is difficult to use controlPlaneEndpoint to support configuring the API Server LB or even maybe BYO control plane IP, because it doesn’t have enough infra details. That means we end up with a very awkward user API where either the DNS Name info is duplicated (like https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/652/files#diff-61d5bf70dea2fc23b9a923ab3bbd84daR156), or the DNS Name is in a different place than the Public IP / LB spec.

Proposal is to change the infrastructure provider contract in v1alpha4 to make controlPlaneEndpoint a required _status_  field in the InfrastructureCluster object. This allows infrastructure provider to report the Cluster's control plane endpoint to Cluster API while leaving it up to each infra provider to decide if/how to make the API Server endpoint configurable by the user, support BYO LB/IP, etc.

The API type of ControlPlaneEndpoint should not need to change, that is: 

```
// APIEndpoint represents a reachable Kubernetes API endpoint.
type APIEndpoint struct {
	// The hostname on which the API server is serving.
	Host string `json:"host"`

	// The port on which the API server is serving.
	Port int32 `json:"port"`
}
```

The same requirements should still apply, that is:

> - MUST route API requests to a live kube-apiserver replica, if one is available.
> - MUST be defined before the first control plane replica is created, so that it is added to the SubjectAltNames of the kube-apiserver server certificate.
> - MUST stay the same for the entire life of the cluster.
> - MUST be a DNS record, or an IP.

/kind feature
/kind proposal

**Comment by ncdc** [comment]
It may be worthwhile to revisit #1250 when considering this

**Comment by CecileRobertMichon** [comment]
cc @alexeldeib

**Comment by CecileRobertMichon** [comment]
@ncdc I'm not sure how this proposal affects a Load Balancer provider, I think that would be an implementation detail. The controlPlaneEndpoint type would not change and CAPI shouldn't care where that host name/IP is coming from, correct?

**Comment by ncdc** [comment]
I was thinking bigger picture, like potentially removing the control plane endpoint entirely from InfraCluster, and replacing it with a load balancer (referenced by the Cluster itself). Cluster/Machine infra providers could also implement load balancing, but you could mix & match, so the assumption that an InfraCluster always has a control plane endpoint might not hold in the long run. But this is a much bigger effort than moving the InfraCluster controlPlaneEndoint from spec to status.

**Comment by CecileRobertMichon** [comment]
cc @detiber since you're looking into Load Balancer Provider. Not sure if we should include this as part of the LB provider work or do both separately. Probably the former?

**Comment by fabriziopandini** [comment]
/lifecycle frozen
given that this is related to the LB work

**Comment by CecileRobertMichon** [comment]
/area release-blocking

This should be closed as part of #4389

**Comment by vincepri** [comment]
/milestone Next 

To revisit once the load balancer proposal is tackled as part of v0.5

**Comment by dlipovetsky** [comment]
> This allows infrastructure provider to report the Cluster's control plane endpoint to Cluster API while leaving it up to each infra provider to decide if/how to make the API Server endpoint configurable by the user, support BYO LB/IP, etc.

This seems reasonable.

This is how I read the above:
- If an infra provider wants to support a user-defined control plane endpoint, they can provide some field in the InfrastructureCluster Spec. The user MAY use this field.
 - If the user does use the field, the provider uses the field to derive Status.controlPlaneEndpoint.
 - If the user does not use the field, the provider uses some internal values to derive Status.controlPlaneEndpoint.

**Comment by dlipovetsky** [comment]
In today's office hours, @CecileRobertMichon mentioned that using Spec.controlPlaneEndpoint is awkward: If the user defines this field, core CAPI controllers start to talk to the endpoint, even though the infrastructure may not yet be ready. @fabriziopandini said this may be a bug in the core CAPI controllers; instead, they should check for infrastructure to be ready _and_ for the control plane endpoint to be defined.

**Comment by dlipovetsky** [comment]
On a related note, some providers use some algorithm to derive the control plane endpoint. For example, CAPA [derives it from the cluster name](https://github.com/mesosphere/cluster-api-provider-aws/blob/09afe190c1f4d3f844dff6c6c402db4aa9daa84f/pkg/cloud/services/elb/loadbalancer.go#L304-L319).

If the algorithm changes in some way, then two provider versions may derive different control plane endpoints. One safeguard is to make the Spec.controlPlaneEndpoint a field that can be defined at most one time. By comparison, the Status subresource is typically mutable.

**Comment by CecileRobertMichon** [comment]
link above (https://github.com/mesosphere/cluster-api-provider-aws/blob/09afe190c1f4d3f844dff6c6c402db4aa9daa84f/pkg/cloud/services/elb/loadbalancer.go#L304-L319) is returning 404 for me

**Comment by dlipovetsky** [comment]
> link above (https://github.com/mesosphere/cluster-api-provider-aws/blob/09afe190c1f4d3f844dff6c6c402db4aa9daa84f/pkg/cloud/services/elb/loadbalancer.go#L304-L319) is returning 404 for me

Sorry about that. I fixed the link. It should have been https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/09afe190c1f4d3f844dff6c6c402db4aa9daa84f/pkg/cloud/services/elb/loadbalancer.go#L304-L319

**Comment by sbueringer** [comment]
@CecileRobertMichon Would it be okay for you to close this issue in favor of: https://github.com/kubernetes-sigs/cluster-api/issues/5517#issuecomment-1031559370
