### ISSUE TITLE
metadata.yaml file not found

### ISSUE THREAD

**Issue by cloudcafetech** [kubernetes-sigs/cluster-api#3717]
[root@ocp-311 cluster-api]# clusterctl init \
>    --core cluster-api:v0.3.8 \
>    --bootstrap kubeadm:v0.3.8 \
>    --control-plane kubeadm:v0.3.8 \
>    --infrastructure docker:v0.3.8 \
>    --config ~/.cluster-api/dev-repository/config.yaml
Fetching providers
Error: failed to read "metadata.yaml" from the repository for provider "infrastructure-docker": failed to read file "/root/.cluster-api/dev-repository/infrastructure-docker/v0.3.8/metadata.yaml" from local release v0.3.8: stat /root/.cluster-api/dev-repository/infrastructure-docker/v0.3.8/metadata.yaml: no such file or directory

**Comment by fabriziopandini** [comment]
/triage support
@cloudcafetech  In the older release of clusterctl the user was responsible of creating the metadata.yaml for docker provider manually or using the procedure described here https://cluster-api.sigs.k8s.io/clusterctl/developers.html#run-the-local-overrides-hack

In the upcoming v0.3.10 release, artifacts for the docker provider will be included in the release, and so the UX for this provider will be simplified and more consistent with the other providers

Please let me know if this helps
