### ISSUE TITLE
Avoid linking to the "master" branch of Kubernetes repositories

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3718]
The the "master" -> "main" branch rename can happen in k8s repositories,
in the near future, which will break the links in this repository.

We can avoid referencing a "master" branch if the URL:
"https://git.k8s.io/repo" is used instead of
"https://github.com/kubernetes/{blob|tree}/master"

/kind cleanup
/kind documentation
/priority backlog

**Comment by fabriziopandini** [comment]
/milestone Next
This can be merged whenever it is ready

/good-first-issue

**Comment by vincepri** [comment]
Duplicate of https://github.com/kubernetes-sigs/cluster-api/issues/3280 ?

**Comment by arghya88** [comment]
I can work on this if that is okay.

**Comment by fabriziopandini** [comment]
> Duplicate of #3280 ?

Not really, #3280 is about changing the main branch for this repo, this issue is about getting ready for the branch being changed in k/*

**Comment by fabriziopandini** [comment]
> I can work on this if that is okay.

Sure!
/assign @arghya88 
/lifecycle active
