### ISSUE TITLE
Implements test for self-hosted upgrades

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3728]
As of today in CAPI e2e we are testing the bootstrap-pivot to self-hosting sequence, but we are not testing self-hosting upgrades.

Ideally we should test:
- upgrading a single control plane, self-hosted cluster
- upgrading an HA control plane, self-hosted cluster

/kind feature
/area testing

**Comment by tcordeu** [comment]
@fabriziopandini can I work on this one? If so, can you provide some tips on where to start?

**Comment by fabriziopandini** [comment]
Sure!
So, currently in out e2e we are testing pivot a management cluster to a self hosted cluster, see https://github.com/kubernetes-sigs/cluster-api/blob/master/test/e2e/self_hosted.go (*), however, after pivoting, we don't do any operation on the self hosted managed cluster (apart from checking it is reconciling itself).

(*) Note that we cannot pivot the kind management cluster, because it is shared by many test running in parallel.
So we are:
- creating a workload cluster
- turn it into a management cluster (our starting cluster for pivoting)
- use it to create another workload cluster (the target cluster for pivoting)
- Do the pivot: 
  - turn this second cluster into a management cluster 
  - move the cluster definitions from the starting point to here

This issue is about:
- Extending this test, by adding a final step that upgrades the self hosted cluster (the target cluster after pivot).
- Making required changes so we can run the same test twice, one with 1 cp machines, one with 3 cp machines

/assign @tcordeu 
/lifecycle active

**Comment by chrischdi** [comment]
@anusha94 are you still working at this?
