### ISSUE TITLE
Machine controller should watch for nodes

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3729]
The machine controller already accesses nodes e.g. for retrieving the provider ID, and with https://github.com/kubernetes-sigs/cluster-api/pull/3670, for reading node conditions.

In order to make sure the Machine stay in sync with node changes, we should make the controller to watch the nodes instead of relying on requeue or on periodic resync 

/kind feature

**Comment by sedefsavas** [comment]
At a high level, reconcileNode() will be triggered on node changes. Any other aspects we want to consider when watching nodes?

**Comment by fabriziopandini** [comment]
My expectation is that a Machine should be enqueued for reconciliation every time the underlying node change. 
As a reference, this is how this is implemented in MHC
https://github.com/kubernetes-sigs/cluster-api/blob/f881755d4897695b28b4759ec4253c423ba67e56/controllers/machinehealthcheck_controller.go#L199-L202

**Comment by fabriziopandini** [comment]
/close 
#3748 merged
