### ISSUE TITLE
Release link in the quick-start is broken

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3733]
The release link in https://cluster-api.sigs.k8s.io/user/quick-start.html#install-clusterctl is broken:
```
Download the latest release; for example, to download version v0.3.0 on linux, type:
```
Should report v0.3.10

```
curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.3.9/clusterctl-linux-amd64 -o clusterctl
```
Should link to v0.3.10

/kind bug
/area documentation

**Comment by vincepri** [comment]
It works locally, it seems we just need to rebuild and republish the book from the release branch

cc @detiber

**Comment by detiber** [comment]
Looks like this has been resolved and the link is currently up to date, closing this issue.
/close
