### ISSUE TITLE
CABPK: bootstrapping can fail in low-bandwidth environments

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#3734]
**What steps did you take and what happened:**
1. Try to create a control plane in a low-bandwidth environment
1. kubeadm takes > 15 minutes to pull the preflight images (e.g. you're not using the container images baked into the OS image, for whatever reason)
1. kubeadm fails with an error like
```
[2020-10-01 22:23:53] error execution phase control-plane-prepare/certs: couldn't validate the identity of the API Server: could not find a JWS signature in the cluster-info ConfigMap for token ID "dki05w"
```

**What did you expect to happen:**
1. Successful bootstrap

**Anything else you would like to add:**
We continually refresh the bootstrap token as long as the infra machine is not ready. Once it's ready (i.e. powered on and the infra provider sees that state), we stop refreshing the token. The expiration is 15 minutes, so if it takes more than 15 minutes between when we last refreshed the token and when kubeadm tries to prepare certs, we risk encountering an expired token and failing to bootstrap.

We could change the logic so we continually refresh the token while the machine is missing its node ref.

Related Slack conversation: https://kubernetes.slack.com/archives/C8TSNPY4T/p1601652445163700

**Environment:**

- Cluster-api version: v0.3.9
- Kubernetes version: (use `kubectl version`): 1.19.x
- OS (e.g. from `/etc/os-release`): Photon

/kind bug

**Comment by vincepri** [comment]
If this gets fixed, we can possibly backport to v0.3.12, given that it could cause issues in some environments

**Comment by fabriziopandini** [comment]
@randomvariable should this fall in the node agent domain?

**Comment by randomvariable** [comment]
maybe, but we'll still be dependent on the granularity of kubeadm phases.

**Comment by randomvariable** [comment]
That's a fair point, thanks.
