### ISSUE TITLE
Flaky test: Patch Helper Should patch a clusterv1.Cluster updating both spec, status, and adding a condition

### ISSUE THREAD

**Issue by benmoss** [kubernetes-sigs/cluster-api#3747]
> Patch Helper
/home/prow/go/src/sigs.k8s.io/cluster-api/util/patch/patch_test.go:39
  Should patch a clusterv1.Cluster
  /home/prow/go/src/sigs.k8s.io/cluster-api/util/patch/patch_test.go:411
    updating both spec, status, and adding a condition [It]
    /home/prow/go/src/sigs.k8s.io/cluster-api/util/patch/patch_test.go:550
    Expected success, but got an error:
      
        <errors.aggregate | len:1, cap:1>: [
            {
                ErrStatus: {
                    TypeMeta: {Kind: "", APIVersion: ""},
                    ListMeta: {
                        SelfLink: "",
                        ResourceVersion: "",
                        Continue: "",
                        RemainingItemCount: nil,
                    },
                    Status: "Failure",
                    Message: "Cluster.cluster.x-k8s.io \"test-8zs87\" not found",
                    Reason: "NotFound",
                    Details: {
                        Name: "test-8zs87",
                        Group: "cluster.x-k8s.io",
                        Kind: "Cluster",
                        UID: "",
                        Causes: nil,
                        RetryAfterSeconds: 0,
                    },
                    Code: 404,
                },
            },
        ]
        Cluster.cluster.x-k8s.io "test-8zs87" not found
    /home/prow/go/src/sigs.k8s.io/cluster-api/util/patch/patch_test.go:580
------------------------------
> STEP: Creating the object
STEP: Creating a new patch helper
STEP: Updating the object spec
STEP: Updating the object status
STEP: Setting Ready condition
STEP: Patching the object
•I1005 20:43:28.355380   14598 server.go:231] controller-runtime/webhook "msg"="shutting down webhook server"  
Summarizing 1 Failure:
[Fail] Patch Helper Should patch a clusterv1.Cluster [It] updating both spec, status, and adding a condition 
/home/prow/go/src/sigs.k8s.io/cluster-api/util/patch/patch_test.go:580

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/3714/pull-cluster-api-test-main/1313488226450673664
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/3744/pull-cluster-api-test-main/1313479076584886272
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/3745/pull-cluster-api-test-main/1313476937657618432
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/3691/pull-cluster-api-test-main/1313273547795206144
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/3735/pull-cluster-api-test-main/1313217650565844992

/kind bug
/area testing

**Comment by vincepri** [comment]
/close 
/milestone v0.4.0

Fixed in #3735
