### ISSUE TITLE
Http proxy support for egress traffic

### ISSUE THREAD

**Issue by hanlins** [kubernetes-sigs/cluster-api#3751]
**User Story**

As a operator I would like to proxy cluster egress traffic for security compliance
As a operator I would like to store proxy credentials in secret(s) and consume them securely
As a user I would like to update cluster proxy settings via cluster API
As a user I would like to view proxy configurations being applied for my cluster

**Detailed Description**

In some corporation network, security policies or firewall rules will be applied to block egress traffic to prevent data exfiltration, which will block the traffic for pulling images from external image registry or sending telemetry data. A proxy is required in this scenario to ensure the egress traffic can be managed in a secure way.

**Anything else you would like to add:**

With current **v1alpha3** implementation, we could potentially inject proxy configs to container runtime via the [**Files**](https://github.com/kubernetes-sigs/cluster-api/blob/27a6031a1d6aa1a310c905b7d1afa331ab1cfd2d/bootstrap/kubeadm/api/v1alpha2/kubeadmbootstrapconfig_types.go#L47) hook, however it has following problems:
1. It's making assumption that kubeadm/cloud-init is being provided.
2. You need to expose the credentials in the **kubeadmconfig** object.
3. It's not supporting reconfiguration. The [**Files**](https://github.com/kubernetes-sigs/cluster-api/blob/27a6031a1d6aa1a310c905b7d1afa331ab1cfd2d/bootstrap/kubeadm/api/v1alpha2/kubeadmbootstrapconfig_types.go#L47) or [**PreKubeadmCommands**](https://github.com/kubernetes-sigs/cluster-api/blob/27a6031a1d6aa1a310c905b7d1afa331ab1cfd2d/bootstrap/kubeadm/api/v1alpha2/kubeadmbootstrapconfig_types.go#L50) hook are making use of cloud-init and it will only take effective on bootstrap. You need to perform a machine deployment rolling upgrade to ensure the change is propagated to each VM within the deployment.

It'll be helpful to add configurations in the cluster API spec to natively support http proxy to fix the issues we have above.

/kind feature

**Comment by vincepri** [comment]
This will probably need a design, let's see how we can kickstart something.

Regarding point 2, we should be able to use secrets to make sure we don't expose sensitive data https://github.com/kubernetes-sigs/cluster-api/blob/master/bootstrap/kubeadm/api/v1alpha3/kubeadmbootstrapconfig_types.go#L203-L205

/cc @CecileRobertMichon 
for CAPZ side
/kind design

**Comment by ncdc** [comment]
@hanlins thanks for filing this! Could you please update your description with as many separate user stories that you can think of? For example, I think you could have separate stories for:
- supporting non-kubeadm bootstrap providers (will require a design with proposed contract+API changes for bootstrap providers)
- supporting things other than cloud-init
- ensuring any sensitive information (usernames/passwords) are stored securely
- supporting in-place reconfiguration (doesn't really align with the project's stance on immutable infrastructure, but it doesn't hurt to write it down as a use case)

Thanks!

**Comment by hanlins** [comment]
Hi @ncdc,

Thanks for the feedback. For the user stories:
> supporting non-kubeadm bootstrap providers (will require a design with proposed contract+API changes for bootstrap providers)
> supporting things other than cloud-init

We don't actually have a user story for other bootstrap providers. I'm bringing that up just want to make sure we choose the right layer of abstraction if we decide to involve a config (e.g. we could expose a new option specifically for proxy in [**ClusterNetwork**](https://github.com/kubernetes-sigs/cluster-api/blob/6ee07b3ff2c4162a3959969a6e9c20d813ebc4d2/api/v1alpha3/cluster_types.go#L42-L44) or just [**KubeadmConfigSpec**](https://github.com/kubernetes-sigs/cluster-api/blob/6ee07b3ff2c4162a3959969a6e9c20d813ebc4d2/bootstrap/kubeadm/api/v1alpha3/kubeadmbootstrapconfig_types.go#L34-L98) to make it a provider specific thing). For whichever approach, we need to make adaptions thus we're open to either decision and want to be aligned with upstream.

> ensuring any sensitive information (usernames/passwords) are stored securely

👍 , will add

> supporting in-place reconfiguration

Yeah this is a nice to have from UX stand point but we know it's not easy and come with a cost. For openshift we notice that what they did is they need to [reboot](https://github.com/openshift/machine-config-operator/blob/55110c21f94289b8e0b36962959d101266bf3038/pkg/daemon/daemon.go#L172-L182) VMs to pick up the new changes, this is clearly not aligned with the immutable model we adopt in cluster API. Sure we can put it down as user story but we're not setting expectation that we have to the VMs in-place 😄

**Comment by hanlins** [comment]
Hi @vincepri, true we can leverage `SecretFileSource` to hide the credentials, and this is what we're planning to work on shortly. It's good that we can hide the secrets but at the same time it's difficult for users to read the proxy settings for diagnose. Ideally if we have an option just for proxy, we could add just show the HTTP(S)_PROXY url to the users and hide its credentials. Here I'm making an assumption that the URL itself is not a secret and it's the operator's job to perform security hardening and people will have to be authenticated to get proxy access.

**Comment by hanlins** [comment]
@ncdc one more thing to add for the bootstrap provider assumption. Our current approach is Linux based and grouping a new option with the bootstrap provider could be easier for the moment but we might need to come back later for windows support. Exposing a new option in `Cluster` might enforce windows to support the new option.

**Comment by hanlins** [comment]
Hi @vincepri, this is a [draft proposal](https://docs.google.com/document/d/1j-KVAZoFnaGJYyzg_64B_i-rZ3LfVEcm49ztTOSdQto/edit?usp=sharing) for the proxy changes we're planning.
