### ISSUE TITLE
Invalid ProviderID error is malformed

### ISSUE THREAD

**Issue by benmoss** [kubernetes-sigs/cluster-api#3763]
**What steps did you take and what happened:**
Have a provider write a ProviderID that doesn't match the form we describe in https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/noderefutil/providerid.go

See a confusing error in the logs:
> controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="providerID must be of the form \u003ccloudProvider\u003e://\u003coptional\u003e/\u003csegments\u003e/\u003cprovider id\u003e" "controller"="machine" "name"="bmo-md-1-6bf4fd585d-jfwbx" "namespace"="default"

**What did you expect to happen:**
I think we just want it to print out the error string verbatim, I don't know where the formatting strings are coming from.

**Anything else you would like to add:**
I remember fixing this in klog ages ago. Maybe we just need to bump that? https://github.com/kubernetes/klog/issues/139

/kind bug

**Comment by enyinna1234** [comment]
lifecycle/active

**Comment by enyinna1234** [comment]
@benmoss I'm not able to reproduce this. Can you please shed more light? What provider did you use? I can't find where the NewProviderID function gets called that involves json marshaling.

**Comment by benmoss** [comment]
@enyinna1234 sorry for the delay, I think in my case this was being logged [here](https://github.com/kubernetes-sigs/cluster-api/blob/953ad253ee2bc169ddda765efe5851c30ffb1def/controllers/machine_controller_noderef.go#L177). The issue is that klog had a bug that got fixed a while ago but this project hasn't bumped it's klog dependency in a while
