### ISSUE TITLE
Use tilt tilt/cert_manager extension

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3765]
https://github.com/tilt-dev/tilt-extensions/pull/90 recently added a new extension taking care of installing cert-manager in a dev cluster created with `tilt up`.

It is now possible to start using this extension in the CAPI Tiltfile, thus removing the existing `deploy_cert_manager` and related global variables.
See https://docs.tilt.dev/extensions.html for more info about how to use tilt extensions.

For people willing to start working on CAPI this is a great chance to understand the typical CAPI dev setup, see https://cluster-api.sigs.k8s.io/developer/tilt.html

/help
/good-first-issue
/kind cleanup

**Comment by eratnch** [comment]
@fabriziopandini,  i would like to work on this.
/assign @eratnch
