### ISSUE TITLE
machineset_controller creating new machines before adopting existing ones

### ISSUE THREAD

**Issue by Lukasz-SendGrid** [kubernetes-sigs/cluster-api#3770]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
I was going through a disaster recovery scenario where a management cluster which creates other clusters is wiped out, and the state of it is restored via velero restore. Before proceeding with the cluster rebuild and restore, I paused the cluster created via capi, and created a velero backup. 

When I performed the restore, 5/9 machines were correctly restored and adopted after unpausing the cluster. The remaining four, which existed in 2 separate machinesets of 2 machines, were not and instead the `machineset_controller` appears to have created two new replicas per machineset before trying to adopt the existing 2 machines, at which point causing there to be too many replicas in the machineset now and in turn deleted / deprovisioned the two old existing machines. This can be seen in line ~34 in the capilog below. 

[capilog.log](https://github.com/kubernetes-sigs/cluster-api/files/5356367/capilog.log)

**What did you expect to happen:**
I expected all machines to be adopted by capi, and existing nodes not to get deprovisioned / deleted. 

**Anything else you would like to add:**
The cluster was build using capm3, and baremetal operator for the infrastructure.

**Environment:**

- Cluster-api version: `v.0.3.8`
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): `v1.17.3`
- OS (e.g. from `/etc/os-release`):  Fedora 32

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
/milestone Next

Setting next milestone until we can triage a bit more

**Comment by vincepri** [comment]
/assign @sedefsavas 

to triage

/lifecycle frozen

**Comment by sbueringer** [comment]
First round of analysis:

MachineSets:
* mgmt-prod-a.mdw1-lb-6cd65b55b8
    * adopt mgmt-prod-a.mdw1-lb-6cd65b55b8-6bx6s
    * adopt mgmt-prod-a.mdw1-lb-6cd65b55b8-7bwsc
    * adopt mgmt-prod-a.mdw1-lb-6cd65b55b8-7bwsc (second time)
    * adopt mgmt-prod-a.mdw1-lb-6cd65b55b8-6bx6s (second time)

* mgmt-prod-a.mdw1-node-5945dc5864
    * adopt mgmt-prod-a.mdw1-node-5945dc5864-4hfvn
    * adopt mgmt-prod-a.mdw1-node-5945dc5864-lsmv9
    * adopt mgmt-prod-a.mdw1-node-5945dc5864-4hfvn (second time)
    * adopt mgmt-prod-a.mdw1-node-5945dc5864-lsmv9 (second time)
    * Too many replicas
        * Delete mgmt-prod-a.mdw1-node-5945dc5864-4hfvn
        * Delete mgmt-prod-a.mdw1-node-5945dc5864-lsmv9

* mgmt-prod-a.mdw1-node-5b5bc67cc7
    * Too few replicas
        * Create mgmt-prod-a.mdw1-node-5b5bc67cc7-bhl4p
        * Create mgmt-prod-a.mdw1-node-5b5bc67cc7-58x9f

* mgmt-prod-a.mdw1-prometheus-5dbc44ccb4
    * adopt mgmt-prod-a.mdw1-prometheus-5dbc44ccb4-4b2qk
    * adopt mgmt-prod-a.mdw1-prometheus-5dbc44ccb4-fd96x
    * adopt mgmt-prod-a.mdw1-prometheus-5dbc44ccb4-fd96x (second time)
    * adopt mgmt-prod-a.mdw1-prometheus-5dbc44ccb4-4b2qk (second time)
    * Too many replicas
        * Delete mgmt-prod-a.mdw1-prometheus-5dbc44ccb4-fd96x
        * Delete mgmt-prod-a.mdw1-prometheus-5dbc44ccb4-4b2qk

* mgmt-prod-a.mdw1-prometheus-6857b5dbb9
    * Too few replicas
        * Create mgmt-prod-a.mdw1-prometheus-6857b5dbb9-w7mcq
        * Create mgmt-prod-a.mdw1-prometheus-6857b5dbb9-qbfs8

Essentially, I think the machines have been adopted correctly but for some reason the `mgmt-prod-a.mdw1-node` and `mgmt-prod-a.mdw1-prometheus` MachineDeployments triggered a rollout, i.e. created new MachineSets, scaled down the Machines of the old MachineSets, created Machines for the new MachineSets.

It's strange that there are absolutely no logs from the MachineDeployment controller. @Lukasz-SendGrid Were those MachineSets managed by a MachineDeployment or in some other way?

@Lukasz-SendGrid I would try to reproduce the issue but I'm a bit confused about the order of your steps. I think it's ~ like that:
* setup Management and workload cluster
* velero backup
* delete the Management Cluster
* velero restore

I'm not sure when you paused the Cluster. "Before proceeding with the cluster rebuild and restore" sounds like maybe you paused it via the Velero JSON files or after the velero restore command (which would mean that the reconcilers had some time to reconcile)?

**Comment by Lukasz-SendGrid** [comment]
> It's strange that there are absolutely no logs from the MachineDeployment controller. @Lukasz-SendGrid Were those MachineSets managed by a MachineDeployment or in some other way?

Yes they were managed by a MachineDeployment 


> I'm not sure when you paused the Cluster. "Before proceeding with the cluster rebuild and restore" sounds like maybe you paused it via the Velero JSON files or after the velero restore command (which would mean that the reconcilers had some time to reconcile)?

I paused the cluster by changing the spec, `paused: true`, then performed the velero backup, in the velero generated backed up yaml files the owner references are still there. When the cluster was recreated, I did the velero restore waited for all the objects to get re-applied, and then removed the pause annotation from the cluster to get things reconciling again. Some more context here https://github.com/metal3-io/baremetal-operator/issues/670

**Comment by Lukasz-SendGrid** [comment]
We haven't tried to replicate the issue, at the time it seemed like a one off because this worked repeatedly on much smaller mgmt clusters i.e. managing just one cluster one node.

**Comment by killianmuldoon** [comment]
c/f https://github.com/kubernetes-sigs/cluster-api/issues/6283

**Comment by killianmuldoon** [comment]
@ywk253100 Thanks for removing the tag! Have you encountered this issue separately and do you have some info to share on the cause?

**Comment by ywk253100** [comment]
@killianmuldoon  I got a similar issue when setting the wrong label selector with MD just like said in https://github.com/kubernetes-sigs/cluster-api/issues/5957.
When I correct the label selector manually, the issue is gone in my env.

**Comment by killianmuldoon** [comment]
Let's keep the discussion on issue #5957 and allow this issue to go stale unless we get some more info specific to this use case / outcome.
