### ISSUE TITLE
Move registering field indexes logic to the API package 

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#3778]
Machine controller registers index on field `status.nodeRef.name` field, which makes getting the matching Machine easier when watching Nodes.

Currently, indexing happens in the controller, but we should move it up to the main function as field indexes are global and not per controller. And registering an index should be API version specific. So moving `indexMachineByNodeName` to API package and creating a function for registering the index (`mgr.GetCache().IndexField`) is a better option.

Some comments from @ncdc about this (https://github.com/kubernetes-sigs/cluster-api/pull/3748#discussion_r501263465):
```
1- This MachineNodeNameIndex constant isn't anything that would ever be used outside of setting up the index, so it's weird to make this part of an exported public API

2- An index on a field is API version specific, so I agree that it makes sense to think about a field index in the scope of a specific API version package

3- Field indices are global and not per controller, so it feels a bit strange to configure an index inside a controller...
                     ... unless you need to use information from the controller, but ...
4- ... This particular index does not use anything outside of the Machine struct

Would it be worth considering moving all field index registrations into the appropriate versioned API package(s), where the only thing we expose is an exported method named something like RegisterFieldIndexFunctions(), and all the inner workings can be left private (e.g. we wouldn't need to export MachineNodeNameIndex). We'd also need to remember to invoke the registration function from main.go. This works as long as our index functions are simple and don't require access to a client or something from a controller (although if we need a client, we could set up a way to pass one in to the index function).
```

**Comment by enxebre** [comment]
fwiw I have a different perspective on this, I'd like `api/` to be as lean as possible and ideally to eventually become a module on its own so consumers are not dictated with versions of transitive deps they wouldn't need to consume the API.

**Comment by ncdc** [comment]
Good point. #3465 is the issue for that... I think my primary comment is that an individual controller shouldn't be responsible for registering a field index function (unless for some reason data from the controller is necessary to implement said function). I think a compromise to my original suggestion could be to move the registration of field index functions outside of individual controllers, but not into the API package. They could go in the controllers package potentially, or some other (non-API) package. WDYT?

**Comment by vincepri** [comment]
cc @ykakarap

**Comment by enxebre** [comment]
@sedefsavas can we update the title/desc to be compatible with
https://github.com/kubernetes-sigs/cluster-api/issues/3778#issuecomment-854612259
https://github.com/kubernetes-sigs/cluster-api/issues/3778#issuecomment-854740241
https://github.com/kubernetes-sigs/cluster-api/issues/3465
?

So i.e don't add additional deps to `/api`
