### ISSUE TITLE
Need to update admissionregistration version from v1beta1 to v1

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#3780]
**What steps did you take and what happened:**
1. Updated my `kind`, `kubectl` and `clusterctl` versions to the latest. For clusterctl, I pulled the latest code for cluster-api and did `make clusterctl`.
1. Created a management cluster with verbose logging on. `clusterctl init --infrastructure aws -v10`
1. Saw the warning logs below for our `admissionregistration.k8s.io/v1beta1`

**What did you expect to happen:**
No warnings to show up.

**Anything else you would like to add:**
```
Creating Issuer="capi-kubeadm-bootstrap-selfsigned-issuer" Namespace="capi-webhook-system"
W1013 10:00:00.003796   18812 warnings.go:67] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
Creating ValidatingWebhookConfiguration="capi-kubeadm-bootstrap-validating-webhook-configuration"
W1013 10:00:00.071051   18812 warnings.go:67] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
Creating instance objects Provider="bootstrap-kubeadm" Version="v0.3.10" TargetNamespace="capi-kubeadm-bootstrap-system"
.
.
.
Installing Provider="control-plane-kubeadm" Version="v0.3.10" TargetNamespace="capi-kubeadm-control-plane-system"
Creating shared objects Provider="control-plane-kubeadm" Version="v0.3.10"
Creating CustomResourceDefinition="kubeadmcontrolplanes.controlplane.cluster.x-k8s.io"
W1013 10:00:00.813159   18812 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
Creating MutatingWebhookConfiguration="capi-kubeadm-control-plane-mutating-webhook-configuration"
W1013 10:00:00.821344   18812 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
```

**Environment:**

- Cluster-api version: b4cb2fca47edfd2e16d0175f035bfd8a5dd0fda1
- Minikube/KIND version: kind v0.9.0 go1.15.2 darwin/amd64
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):

/kind bug
/area api

**Comment by wfernandes** [comment]
If this is something that we want to fix, I'd like to take it on. Please let me know if there is anything other than upgrading the versions from `v1beta1` to `v1` that needs to be done.
/assign

**Comment by wfernandes** [comment]
> This needs changes in controller runtime, which haven't been worked on yet

Thanks @vincepri. Does it make sense to keep this issue open?

**Comment by vincepri** [comment]
See https://github.com/kubernetes-sigs/controller-runtime/issues/1161

**Comment by vincepri** [comment]
Yes, let's keep it open and track it

/milestone v0.4.0

**Comment by fabriziopandini** [comment]
@vincepri IMO this one could be closed given that we are using` admissionregistration.k8s.io/v1` https://github.com/kubernetes-sigs/cluster-api/blob/e9cacc0931eff0118442a5e596b64eccf380c731/config/webhook/manifests.yaml#L3 
and the controller runtime work seems completed
