### ISSUE TITLE
Document policies around Kubernetes and dependencies 

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#3783]
Every now and then, there is going to be breaking changes that need to be made for a number of reasons. A common which usually happens at every cycle:

- Minimum Kubernetes version
  - For management clusters
  - For workload clusters
- Controller Runtime version
  - Usually carries other Kubernetes dependencies pinned to a specific version, like k8s.io/api or client-go.

This issue should start a discussion on how to propose these changes in the community, and how to allow at the same time the project to move forward. An ideal process would give enough visibility well in advance when these changes need to happen.

/kind documentation
/milestone v0.4.0
/priority critical-urgent
/cc @detiber @CecileRobertMichon @ncdc @timothysc

**Comment by vincepri** [comment]
Hey folks, at the Oct 14th community meeting we brought up this topic, in general I'd propose something along these lines while we're in alpha:

- Clearly document the management cluster support matrix for each alpha/minor version published.
- During planning, we should discuss what should be the suggested Kubernetes version for management clusters.
  - Suggested version is going to be used throughout testing, and we can provide some support for it.
  - Older versions MAY work fine with our controllers, although we won't necessarily test them or provide extensive support.

In general, I'd like to keep up with upstream Kubernetes at least for the management cluster (N, N-2) so we can adopt new features and keep our controllers up to date.

Workload clusters are definitely different, because Cluster API today is able to create clusters on a wide range of versions. That said, we should document what range of versions are supported for each release, and when/how we can sunset support for some older versions.

**Comment by detiber** [comment]
One thing to note as we define a policy, the range of n -> n-2 is only valid for k8s <= v1.18, starting with v1.19 the support statement has moved from 9 months and/or n-2 to 1 year.

**Comment by vincepri** [comment]
The new policy could work very well for the newly defined release cadence, with some good overlap

**Comment by fabriziopandini** [comment]
@vincepri can I give this a try?

**Comment by fabriziopandini** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/6122 improved our version documentation 
/close
