### ISSUE TITLE
clusterctl init --help refers to non-existent command

### ISSUE THREAD

**Issue by benmoss** [kubernetes-sigs/cluster-api#3784]
`clusterctl init` is telling users to run `clusterctl config providers` to get a list of available providers, that command just prints out help text for the `config` subcommand.

https://github.com/kubernetes-sigs/cluster-api/blob/9cbf8be8d643203d99aca6714825abdabcbca0b1/cmd/clusterctl/cmd/init.go#L52

```
$ clusterctl init --help
...
Use 'clusterctl config providers' to get a list of available providers; if necessary, edit
$HOME/.cluster-api/clusterctl.yaml file to add new provider or to customize existing ones.
...
```

/kind bug
/area clusterctl

**Comment by prankul88** [comment]
Hi @benmoss , `clusterctl config providers` is not a valid command. The list of providers are shown in command `clusterctl config repositories`.
This is a good catch and worth updating. Thanks :)
