### ISSUE TITLE
update keps/sig-cluster-lifecycle/clusterapi in kubernetes/enhancements

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/cluster-api#3791]
the following folder in the kubernetes/enhancements (k/e) repository contains KEPs related to Cluster API:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/clusterapi

- it only has the main CAPI proposal and it is out of date:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/clusterapi/0003-cluster-api.md
KEPs are a living document and they should be kept up to date. the above proposal should be updated on big milestones to include the latest iterations of the CAPI design - e.g. v1alpha2...3...4.

- since CAPI uses its own CAEP process instead of the k8s KEPs in k/e we should create a README.md in the above folder that links to:
```
https://sigs.k8s.io/cluster-api/docs/proposals
```
(please use this exact link instead of the `tree/master/....` format)

**Comment by prankul88** [comment]
>KEPs are a living document and they should be kept up to date. the above proposal should be updated on big milestones to include the latest iterations of the CAPI design - e.g. v1alpha2...3...4.

Hi, Can we remove the [existing kep](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/clusterapi/0003-cluster-api.md) in that folder and just have a Readme which redirects that to CAEP here.

Or else if we do keep the living document, should the major release iteration be updated [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/clusterapi/0003-cluster-api.md#implementation-history)?

**Comment by neolit123** [comment]
> Or else if we do keep the living document, should the major release iteration be updated here?

my vote goes for this option.

**Comment by vincepri** [comment]
Catching up on this, @neolit123 is there any other action item?

**Comment by neolit123** [comment]
i don't know if https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/clusterapi/2495-Kubernetes-Cluster-Management-API is up to date.

**Comment by neolit123** [comment]
this item is done:
> since CAPI uses its own CAEP process instead of the k8s KEPs in k/e we should create a README.md in the above folder that links to:

https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/clusterapi/FAQ.md

**Comment by vincepri** [comment]
That KEP is wildly out of date, although I'm not sure if it makes sense to get it up to date, or amend it with a link to the CAEPs and book. WYDT?

**Comment by neolit123** [comment]
you can close this ticket if you think there is no point to keep the old CAPI KEP up-to-date.
the FAQ.md already links to the CAEPs here.

**Comment by vincepri** [comment]
👍 Thanks

/close
