### ISSUE TITLE
Switch Tilt configuration to use upstream include/load rather than using the custom tilt-provider.json

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#3793]
**User Story**

As a developer I would like the Tilt configuration to more closely match upstream conventions

**Detailed Description**

Currently we have a custom multi-repository configuration mechanism for adding provider configuration to our common cluster-api Tilt configuration. Instead, we should likely switch to the new upstream conventions (that didn't exist when our custom solution was created) of using [include/load with a Tiltfile in the child repositories](https://docs.tilt.dev/multiple_repos.html).

This would also likely require reworking the way we are doing live updates. It should be possible to use the [restart_process](https://github.com/tilt-dev/tilt-extensions/tree/master/restart_process) extension to avoid duplicating the current live update process in place (which was built using the recommended way prior to tilt extensions being introduced).

/kind feature

**Comment by vincepri** [comment]
@davideimola This is also another good issue to tackle if you're up for it

**Comment by davideimola** [comment]
Thanks @vincepri!

/assign
/lifecycle active
