### ISSUE TITLE
E2E tests break with long CNI spec

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api#3797]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/991

Tests fail with `failed to execute kustomize: : fork/exec /home/prow/go/bin/kustomize: argument list too long` after updating the Calico CNI to v1.16 (from v1.12). The latest Calico spec is longer than previous ones as a bunch of CRDs were added.

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/991/pull-cluster-api-provider-azure-e2e/1316110882949828608/build-log.txt

This is the line that fails: https://github.com/kubernetes-sigs/cluster-api/blob/bf845fa2d035dd38cbfb04355ed0550137d6f7f2/test/framework/config.go#L327

This is not currently an issue for CAPD because it uses kindnet which has a relatively short spec but will be an issue for any provider trying to apply Calico v3.15+ (CAPZ, CAPA, etc) using the E2E framework. 

Note: we've had similar issues with Tilt in the past and this was the workaround: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/829

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by CecileRobertMichon** [comment]
cc @fabriziopandini @sedefsavas @randomvariable

**Comment by fabriziopandini** [comment]
@CecileRobertMichon 
I'm looking at the workaround, and it seems that it is running `kustomize build`, which is the same we are already doing in the test framework. Might be it depends by the version of kustomize available on Prow (wild guessing at this stage)?
Are you able to reproduce locally?

**Comment by CecileRobertMichon** [comment]
I can repro locally

```

Failure [1.774 seconds]
[BeforeSuite] BeforeSuite
/Users/cerobert/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/e2e_suite_test.go:90

  Failed to generate the manifest for "infrastructure-azure" / "v0.4.0"
  Unexpected error:
      <*errors.withStack | 0xc0004ea480>: {
          error: {
              cause: {
                  error: {
                      Op: "fork/exec",
                      Path: "/usr/local/bin/kustomize",
                      Err: 0x7,
                  },
                  stack: [0x208f828, 0x21ef45c, 0x220b117, 0x238f059, 0x2401e31, 0x24035c2, 0x10c85db, 0x10c7ae4, 0x142acf8, 0x1427cc3, 0x142792f, 0x1428eb4, 0x1428b5f, 0x143bdb0, 0x143b8db, 0x143e016, 0x144daf7, 0x144d83d, 0x240168e, 0x111177c, 0x1069521],
              },
              msg: "failed to execute kustomize: ",
          },
          stack: [0x21ef52f, 0x220b117, 0x238f059, 0x2401e31, 0x24035c2, 0x10c85db, 0x10c7ae4, 0x142acf8, 0x1427cc3, 0x142792f, 0x1428eb4, 0x1428b5f, 0x143bdb0, 0x143b8db, 0x143e016, 0x144daf7, 0x144d83d, 0x240168e, 0x111177c, 0x1069521],
      }
      failed to execute kustomize: : fork/exec /usr/local/bin/kustomize: argument list too long
  occurred

  /Users/cerobert/go/pkg/mod/sigs.k8s.io/cluster-api@v0.3.10/test/framework/clusterctl/repository.go:53
```

The workaround I listed was to not echo the full template with substituted vars to stdout

**Comment by sedefsavas** [comment]
I copied the same calico.yaml to e2e cni directory and tested locally, did not get that error with kustomize_version=3.5.4.
We can create a test PR here to trigger this in prow.

**Comment by CecileRobertMichon** [comment]
I have 
``` 
kustomize version                      
{Version:3.5.5 GitCommit:897e7b6e61e65188d846c32bd3af9ef68b0f746a BuildDate:2020-05-12T00:09:31+01:00 GoOs:darwin GoArch:amd64}
```

Which provider were you using @sedefsavas? I can try to repro with the Docker provider as well.

**Comment by sedefsavas** [comment]
Yes, CAPD. I only run the quick start test.

**Comment by CecileRobertMichon** [comment]
Hmm I can't repro either with CAPD 😕  But I get the same error with CAPZ both locally and in prow

**Comment by fabriziopandini** [comment]
@CecileRobertMichon I made some investigation in this issue, but I'm not sure I'm getting the problem right, let me try to recap my current assumptions:

- We have https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/991 which is trying to upgrade to calico v3.16.3
- The PR fails with an error `Failed to generate the manifest for infrastructure-azure / v0.4.0` 
- `infrastructure-azure / v0.4.0` is defined by the following lines
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/3da52a303b650521e86ff0d56dfcca15e926779b/test/e2e/config/azure-dev.yaml#L41-L54
- So this is applying kustomize to the /config folder, and from a quick look, this is not importing CNI

I also investigated a little bit more how CNI is imported, and this does not use kustomize https://github.com/kubernetes-sigs/cluster-api/blob/f631989d3f7430b5825644a5461e116f48ed2e28/test/framework/clusterctl/e2e_config.go#L70

So, back to the error, why we get `argument list too long` when calling `kustomize build ${PWD}/config`?
Does it works when called from the command line? (locally it works for me...)

Could you kindly confirm/rectify my line of thinking?

**Comment by randomvariable** [comment]
Ah, i was wondering. it would make more sense that it's `cniData, err := ioutil.ReadFile(cniManifestPath)` as there are limits on the length of env vars (32,767 total for all env vars), whereas stdin/stdout should only be limited by memory.

**Comment by CecileRobertMichon** [comment]
@fabriziopandini :

> We have https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/991 which is trying to upgrade to calico v3.16.3

Correct

> The PR fails with an error `Failed to generate the manifest for infrastructure-azure / v0.4.0` 

Correct

> `infrastructure-azure / v0.4.0` is defined by the following lines
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/3da52a303b650521e86ff0d56dfcca15e926779b/test/e2e/config/azure-dev.yaml#L41-L54

Correct

> So this is applying kustomize to the /config folder, and from a quick look, this is not importing CNI

I agree, this was my observation as well

> I also investigated a little bit more how CNI is imported, and this does not use kustomize https://github.com/kubernetes-sigs/cluster-api/blob/f631989d3f7430b5825644a5461e116f48ed2e28/test/framework/clusterctl/e2e_config.go#L70
So, back to the error, why we get `argument list too long` when calling `kustomize build ${PWD}/config`?

I am not sure. It's a mystery to me at this point. What I don't understand is that it makes more sense that it would be `cniData, err := ioutil.ReadFile(cniManifestPath)` but the error points to   /Users/cerobert/go/pkg/mod/sigs.k8s.io/cluster-api@v0.3.10/test/framework/clusterctl/repository.go:53 (and says kustomize failed)...

> Does it works when called from the command line? (locally it works for me...)

Works locally for me as well (`kustomize build ${PWD}/config`)

**Comment by fabriziopandini** [comment]
I'm going to try to reproduce this in locally/in prow

**Comment by fabriziopandini** [comment]
I managed to reproduce in https://github.com/kubernetes-sigs/cluster-api/pull/3846, and I can confirm the error happens after succesfully loading the calico manifest, when calling kustomize build 

```
STEP: BEBUG: reading ./data/cni/calico/calico.yaml
STEP: BEBUG: reading ./data/cni/calico/calico.yaml completed, 197444 into CNI_RESOURCES env var
STEP: Creating a clusterctl local repository into "/logs/artifacts"
STEP: DEBUG: creating local repository for cluster-api - v0.3.0
STEP: DEBUG: running kustomize build /home/prow/go/src/sigs.k8s.io/cluster-api/config


Failure [0.008 seconds]
[BeforeSuite] BeforeSuite 
/home/prow/go/src/sigs.k8s.io/cluster-api/test/e2e/e2e_suite_test.go:94

  Failed to generate the manifest for "cluster-api" / "v0.3.0"
  Unexpected error:
      <*errors.withStack | 0xc0003a8480>: {
          error: {
              cause: {
                  error: {
                      Op: "fork/exec",
                      Path: "/home/prow/go/src/sigs.k8s.io/cluster-api/hack/tools/bin/kustomize",
                      Err: 0x7,
                  },
                  stack: [0x15429d7, 0x1618ab0, 0x1638f67, 0x17b4fdc, 0x1803ae5, 0x1804b4c, 0x4d8427, 0x4d7919, 0x79e0d8, 0x79af23, 0x79ab37, 0x79c1e7, 0x79be45, 0x7c88df, 0x7c83ab, 0x7cabe6, 0x7d9038, 0x7d8d6d, 0x18035f7, 0x52906f, 0x471ee1],
              },
              msg: "failed to execute kustomize:  ",
          },
          stack: [0x1618bd6, 0x1638f67, 0x17b4fdc, 0x1803ae5, 0x1804b4c, 0x4d8427, 0x4d7919, 0x79e0d8, 0x79af23, 0x79ab37, 0x79c1e7, 0x79be45, 0x7c88df, 0x7c83ab, 0x7cabe6, 0x7d9038, 0x7d8d6d, 0x18035f7, 0x52906f, 0x471ee1],
      }
      failed to execute kustomize:  : fork/exec /home/prow/go/src/sigs.k8s.io/cluster-api/hack/tools/bin/kustomize: argument list too long  occurred
```

After some googling the best explanation I have found to this is:
"Command-line arguments and environment variables both come out of the same pool of space. Set environment variables too long, and you no longer have space for command-line arguments" 😞 

So the next step is to investigate possible alternatives to pass the CNI to templates.

**Comment by CecileRobertMichon** [comment]
Oh wow good find.... In that case maybe we should reconsider using an env var as CNI data in the e2e tests configmap and instead do what our users would do which is closer to https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/Tiltfile#L201

**Comment by fabriziopandini** [comment]
I would prefer to continue use CRS instead of doing apply.
As a fallback solution we can embed calico manifest in the CRS config map, but I think I have found a nice solution that allows us to keep calico in a separate file

/lifecycle active

**Comment by fabriziopandini** [comment]
/close
by #3846
