### ISSUE TITLE
Add Cluster ControlPlaneInitialized condition

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#3798]
**User Story**

As a developer, I would like to add a ControlPlaneInitialized condition to Clusters, so that MachineHealthCheck can use it when determining if a Machine has exceeded the allotted node startup timeout.

**Detailed Description**

We currently have cluster.status.controlPlaneInitialized, but it predates conditions and does not have a timestamp associated with it. Based on discussions in #3026, we want MachineHealthCheck to base nodeStartupTimeout calculations on the latter of (controlPlaneInitialized, machine creation timestamp).

This condition MUST be set to true as soon as we are able to establish connectivity with a workload cluster. We can keep the same logic we currently have for setting cluster.status.controlPlaneInitialized.

This condition MUST be a write-once value.

We also MUST remove cluster.status.controlPlaneInitialized from v1alpha4. As far as converting from 3 to 4, I'm not sure what we'd put in for LastTransitionTimestamp...

**Anything else you would like to add:**

#3779 is similar/related

/kind feature
/kind api-change
/milestone v0.4.0
/priority important-soon

**Comment by ncdc** [comment]
cc @vincepri @JoelSpeed @detiber @fabriziopandini

**Comment by vincepri** [comment]
I assume we'll remove the boolean field?

**Comment by ncdc** [comment]
Yes!

**Comment by ncdc** [comment]
Depends on #3749 going in first

**Comment by srm09** [comment]
@ncdc IIUC the intended MHC node startup timeout calculation would be as follows:
[Current time - Max(CP.started, Machine.creationTime)] > Allotted node startup time

If the `CP.Started` value is not present(which would be the case for v1alpha3 object), then we set it to the current time during conversion. That way, for the first time, we are giving the machine the benefit of doubt here citing the lack of timestamp data being present.

Does this make sense?

**Comment by ncdc** [comment]
That's probably the only thing we can do, yes.
