### ISSUE TITLE
Clusterctl should offer a way to idempotently init a provider

### ISSUE THREAD

**Issue by benmoss** [kubernetes-sigs/cluster-api#3801]
**User Story**

As a user I would like to write scripts to deploy a management cluster. I want to be able to run this against a cluster that may have already been initialized, to avoid having to tear down and recreate the cluster each time.

If I am running `clusterctl init --provider aws` and the AWS provider of the same version and name has already been installed, it should just succeed instead of failing.

**Detailed Description**

The only way I can figure out how to easily detect whether a provider is already installed is to first search for installed providers across all namespaces. This is a bit annoying and not easy since the `providerName` field is not searchable by the `--field-selector` kubectl argument. `kubectl get providers --all-namespaces --field-selector=metadata.name=infrastructure-$PROVIDER` is the best I could figure out for now.

/kind feature
/area clusterctl

**Comment by ncdc** [comment]
Maybe the management cluster operator will help here? cc @wfernandes @fabriziopandini

**Comment by wfernandes** [comment]
> If I am running clusterctl init --provider aws and the AWS provider of the same version and name has already been installed, it should just succeed instead of failing.

This is the same behavior as the k8s API. That is, if we `kubectl create ns foobar` twice we get the error `Error from server (AlreadyExists): namespaces "foobar" already exists`.

I guess if we are using `clusterctl` in a script, we could do something like:
```shell
# install core, bootstrap, control-plane providers
clusterctl init
# Try installing aws provider in default namespace. 
# But obviously, this isn't that great either as other errors could be subdued.
clusterctl init -i aws || true 
```

> The only way I can figure out how to easily detect whether a provider is already installed is to first search for installed providers across all namespaces

Yeah..this is not great. There are many reasons regarding current multi-tenant model, global vs. namespaced providers, single provider object vs. specific ones for each provider type (core, bootstrap, control-plane, infrastructure).
This is a place where the mgmt operator could improve current UX, although, this hasn't been formalized yet (see [Open Questions section](https://docs.google.com/document/d/1ZsusF5c9pYxseuaKxTpctI5aUDqzl0sdCW4xxDbLm3k/edit#)).

**Comment by vincepri** [comment]
/milestone v0.4.0

Assigning you Warren to this given that it touches on the operator stuff
/assign @wfernandes

**Comment by vincepri** [comment]
`clusterctl init -i aws || true `

Let's not do this, maybe we can suggest some kubectl command to see if something has been installed? This seems would be easier to solve with the operator proposed types, given that you can check directly if the resource is created or not

**Comment by fabriziopandini** [comment]
If we agree on idempotency, all the logic to detect what is already there in clusterctl init, only it currently blocks as a preflight check; it * should be not difficult * to turn the preflight check into a warning

**Comment by bnason** [comment]
> Closing this given the ongoing work on the operator side and recent clusterctl improvements.

@vincepri can you expand on this? What improvements help in this scenario? I'm also trying to fortify my scripts that call `clusterctl init` and am looking for a good way to detect that it's already been initialized.
