### ISSUE TITLE
Provide "at glance" view of cluster conditions

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3802]
**User Story**

As an operator, I would like to get an "at glance" view of conditions in my cluster for quicly understanding if there are problems and where

**Detailed Description**

While testing and developing conditions, I have created a small utility that provides a simple view of conditions across a cluster, e.g.

<img width="1207" alt="Screenshot 2020-10-15 at 19 53 10" src="https://user-images.githubusercontent.com/5013060/96167716-1a53c600-0f20-11eb-8c25-fc852f3c46f6.png">

The view is inspired by the [kubectl-tree](https://github.com/ahmetb/kubectl-tree) plugin, but specifically designed for Cluster API e.g.
- It hides secrets or other objects without conditions 
- it groups machines which are in the same state 

If people find this useful, I will be happy to contribute it upstream.

**Anything else you would like to add:**

/kind feature

**Comment by vincepri** [comment]
💯 
Let's add it to clusterctl!

**Comment by timothysc** [comment]
+100!

**Comment by jsturtevant** [comment]
This is awesome. I did something similar in [CAPZ for debugging](https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/master/hack/debugging#capz-map) that helped me figure out all the dependencies and use it all the time. This is much more polished look!

Is there are reason to have it in clusterctl? I did it as a kubectl plugin becuase that is where I spend most of my time.  Something like `kubectl capi glance` would be really awesome.  

@devigned also prototyped UI similar to this in VS code. I wonder if the component could be an api that could be reused across interfaces?

**Comment by fabriziopandini** [comment]
@jsturtevant definitely yes!
My plan is to introduce in the clusterctl library the code to back this view, and then build the first sample view in clusterctl (mostly for avoiding the introduction of another release artifact), but any other UX layer can potentially reuse the same library.

I'm open to any solution we agree on as a community for the UX, but why not have more than one? 
+1 to get this in VS code as well, that's cool @devigned! I have also considered building an octant plugin, but time...

**Comment by devigned** [comment]
Yeah, I need to get back to the VSCode plugin. Maybe not next week, but in an upcoming meeting, I'll push the code and give a demo in office hours. It would be great to a prototype and see if there are others would be interested in collaborating.
