### ISSUE TITLE
CAPD clusters don't always delete

### ISSUE THREAD

**Issue by benmoss** [kubernetes-sigs/cluster-api#3804]
**What steps did you take and what happened:**
While trying to script CAPD cluster creation and teardown, I ran into this bug where it seems the cluster gets deadlocked deleting. 

```
clusterctl config cluster bmo --kubernetes-version 1.19.1 --infrastructure docker --flavor development | k apply -f-
clusterctl config cluster bmo --kubernetes-version 1.19.1 --infrastructure docker --flavor development | k delete --wait --ignore-not-found -f-
```

What I see is a single control-plane machine and the cluster stuck in the `Deleting` phase.

```
cluster_predicates.go:138] controllers/DockerCluster "msg"="Cluster was not unpaused, blocking further processing" "cluster"="bmo" "eventType"="update" "namespace"="default" "predicate"="ClusterUpdateUnpaused"
generic_predicates.go:92] controllers/DockerCluster "msg"="All of the provided predicates returned false, blocking further processing" "predicate"="ClusterUnpaused" "predicateAggregation"="Any"
dockermachine_controller.go:106] controllers/DockerMachine/DockerMachine-controller "msg"="DockerCluster is not available yet" "cluster"="bmo" "docker-machine"={"Namespace":"default","Name":"bmo-control-plane-bvnhp"} "machine"="bmo-control-plane-65rmk"
```

**What did you expect to happen:**
It tears down the cluster and machine as quickly as possible.

**Anything else you would like to add:**
I think it has something to do with triggering the deletion before the cluster gets to some provisioning stage, not sure.

**Environment:**

- Cluster-api version: 0.3.10
- Minikube/KIND version: 0.9.0

/kind bug
/area provider/docker

**Comment by benmoss** [comment]
cc @vincepri

**Comment by fabriziopandini** [comment]
@benmoss AFAIK the cleanest mode to delete a cluster is to delete the cluster object only, because this orchestrate all the deletion process in the right way
However, I agree that also kubectl delete * should work

**Comment by vincepri** [comment]
/milestone Next

Going to Next until we have a clear idea what we want to do here and what solution we should be going for

**Comment by benmoss** [comment]
Yep, just deleting the cluster does work. I think this works for CAPA, as I do this often for cleaning up CAPA clusters

**Comment by vincepri** [comment]
Is there any action items here or can we close this issue?

**Comment by fabriziopandini** [comment]
Ideally, we should audit CAPD and make sure that it supports kubectl delete *, but this is
/priority backlog

**Comment by vincepri** [comment]
Going to close this one out given that we haven't heard similar updates for a while.

/close
