### ISSUE TITLE
CusterAPI resources be subjected to assigned namespace quotas and limits

### ISSUE THREAD

**Issue by davlloyd** [kubernetes-sigs/cluster-api#3805]
**User Story**

When requesting cluster operations the resource requirements in memory, cpu and storage should be reconciled against current namespace quotas and limits. Any currently deployed resources should be included in current consumption totals. This would allow administrators to define limits to the consumers helping with the overall capacity management operations 

**Detailed Description**

A machine object is created with corresponding node resources, should have the COU, memory and disk resources included in the hosting namespace quotas consumption levels. If a request will result in the quota/limits being exceeded then the request should be denied or deployment action held until the resources are available as a result of resources being released or quotas increased

**Anything else you would like to add:**

Challenge is translation of various infrastructure resources into management cluster resources when they do not actually have an impact or footprint within the management cluster worker nodes. This is an operational governance feature more then a protection feature of the management cluster itself

/kind feature

**Comment by fabriziopandini** [comment]
Just a clarification, the request here is to manage quota for the target infrastructure (e.g. the quota on AWS, on Azure, on vSphere), right?
If so, I would recommend splitting the target infrastructure quota definition from the existing namespaces quotas, which have a different purpose and meaning in K8s.

**Comment by vincepri** [comment]
Closing due to lack of updates.

/close
