### ISSUE TITLE
Reconcile errors are no longer automatically logged

### ISSUE THREAD

**Issue by benmoss** [kubernetes-sigs/cluster-api#3821]
**What steps did you take and what happened:**
Created a CAPD cluster, saw no machines be created and the `Cluster` object is stuck in  `Provisioning`. No logs from the CAPD controller except for:

> capd-control… │ [manager] I1019 16:44:41.357752    3468 generic_predicates.go:167]  "msg"="Resource is not paused, will attempt to map resource" ""="bmo" "namespace"="default" "predicate"="updateEvent"
capd-control… │ [manager] I1019 16:44:41.357752    3468 generic_predicates.go:167] controllers/DockerCluster "msg"="Resource is not paused, will attempt to map resource" ""="bmo" "namespace"="default" "predicate"="updateEvent"

I inserted log statements into `dockercluster_controller.go`  and eventually found this was the culprit: https://github.com/kubernetes-sigs/cluster-api/blob/master/test/infrastructure/docker/controllers/dockercluster_controller.go#L77

> capd-control… │ [manager] I1019 16:44:41.380022    3468 dockercluster_controller.go:78] controller/dockercluster "msg"="docker.NewLoadBalancer" "cluster"="bmo" "name"="bmo" "namespace"="default" "reconcilerGroup"="infrastructure.cluster.x-k8s.io" "reconcilerKind"="DockerCluster" "err"="failed to list containers: failed to list nodes: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster --format '{{.Names}}\\t{{.Label \"io.x-k8s.kind.cluster\"}}\\t{{.Image}}' --filter label=io.x-k8s.kind.cluster=bmo --filter label=io.x-k8s.kind.role=external-load-balancer\" failed with error: exit status 1"

It seems with the changes to controller-runtime that landed in #3735 we are no longer getting errors logged automatically.

**What did you expect to happen:**
Some way to find out what's wrong / assist in troubleshooting

**Environment:**

- Cluster-api version: master / f1d05fa61091f8989c1d7811a3975eeec63cd1e4

/kind bug

**Comment by ncdc** [comment]
Let's add conditions to CAPD!

**Comment by fabriziopandini** [comment]
@vincepri  is this something that should be fixed in controller runtime? (log in case of error)

**Comment by benmoss** [comment]
> @vincepri is this something that should be fixed in controller runtime? (log in case of error)

From slack:
> If this is off the main branch, yes CR doesn't log anymore and it's the responsibility of the reconciler instead

https://kubernetes.slack.com/archives/C8TSNPY4T/p1603124534447900

**Comment by ncdc** [comment]
We discussed this in the controller runtime PR that removed the logging. My suggestion was that seeing a log message from `controller.go` containing an error with no real provenance was really frustrating. You knew that something in the reconciliation flow returned an error, but in many/most cases, you had know idea what actual file+line generated the error.

We've been saying (but maybe it's not written down) that if you want someone to know an error's source, you need to log it when/where constructing the error.

**Comment by benmoss** [comment]
I think it does raise the question of why the signature for `Reconcile` even has an `error` then

**Comment by detiber** [comment]
> I think it does raise the question of why the signature for Reconcile even has an error then. Normally with APIs like http.HandlerFunc that have this similar "errors stop here" structure they don't allow you to continue bubbling the error up. Then you can rely on tooling to check for unhandled errors.

The main reason currently is for the purposes of requeueing on error, this could be handled in a different way, but would likely require additional changes in controller-runtime to facilitate.

**Comment by ncdc** [comment]
I do like the ability to do retries with rate limited backoffs, for transient errors such as rate limiting.

**Comment by fabriziopandini** [comment]
+100 on the ability to do retries with rate-limited backoffs, is something that IMO makes a lot of sense

WRT to the idea of having something better in the logs than `controller.go message` I got the point, even do I really would like to have something better than our codebase full of

```
if .... err!= nil {
    write to log
    [mark a condition]
    return err
}
```

**Comment by ncdc** [comment]
When I was working on Velero, we wrote a couple of Logrus hooks that added error file+line provenance to each log message. They could also unwrap the pkg/errors stack information to determine this, so if you had code like

```go
func foo(thereIsAProblem bool) error {
  if thereIsAProblem {
    return errors.Errorf("error doing something...")
  }
}

// some other function, somewhere ...
if err := foo(true); err != nil {
  log.Error(err, "uh oh!")
}
```

it would have as log message values the location the error was created (i.e. inside the `foo` function). Maybe we could find a way to do something similar with a "wrapper" for klogr?

**Comment by vincepri** [comment]
/close

This has bene fixed in upstream controller runtime
