### ISSUE TITLE
Run webhooks as part of the main manager

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#3822]
**User Story**

Given that #3042 for v1alpha4 requires single controllers managing all namespaces, we should move the webhooks back in the main manager and run them behind RBAC in case we'll need a client in the future.

**Anything else you would like to add:**

@fabriziopandini @wfernandes  Clusterctl upgrade and operator needs to perform this migration as part of the upgrade path from v1alpha3.

/kind feature
/milestone v0.4.0

**Comment by fabriziopandini** [comment]
That's a huge simplification, yay!

**Comment by wfernandes** [comment]
I'll make a note of it somewhere in the CAEP. Thanks. And yes, definitely a huge simplification!

**Comment by wfernandes** [comment]
Just adding for future reference. This issue is referenced in the management cluster operator caep under the **Upgrade from v1alpha3 management cluster to v1alpha4 cluster** section.

**Comment by fabriziopandini** [comment]
I'm starting to work on this issue, with the goal to start clarifying impacts on clusterctl init and clusterctl upgrades
/assign
/lifecycle active
