### ISSUE TITLE
CAPD fails to initialize workload cluster when named the same as kind cluster

### ISSUE THREAD

**Issue by benmoss** [kubernetes-sigs/cluster-api#3824]
**What steps did you take and what happened:**
- Created a kind cluster named `kind`, and then made a CAPD cluster named `kind` on that management cluster
- Saw that the control plane machine was stuck in `Provisioning`
- Saw these errors in the logs:

> machine.go:334] controller/dockermachine "msg"="Setting Kubernetes node providerID" "cluster"="kind" "docker-cluster"="kind" "machine"="kind-control-plane-6m6bg" "name"="kind-control-plane-7w7vl" "namespace"="default" "reconcilerGroup"="infrastructure.cluster.x-k8s.io" "reconcilerKind"="DockerMachine"

> machine.go:346] controller/dockermachine "msg"="Error from server (NotFound): nodes \"kind-control-plane-6m6bg\" not found" "cluster"="kind" "docker-cluster"="kind" "machine"="kind-control-plane-6m6bg" "name"="kind-control-plane-7w7vl" "namespace"="default" "reconcilerGroup"="infrastructure.cluster.x-k8s.io" "reconcilerKind"="DockerMachine"

> dockermachine_controller.go:296] controller/dockermachine "msg"="failed to patch the Kubernetes node with the machine providerID" "error"="failed update providerID: command \"docker exec --privileged kind-control-plane kubectl --kubeconfig /etc/kubernetes/admin.conf patch node kind-control-plane-6m6bg --patch '{\"spec\": {\"providerID\": \"docker:////kind-control-plane-6m6bg\"}}'\" failed with error: exit status 1" "name"="kind-control-plane-7w7vl" "namespace"="default" "reconcilerGroup"="infrastructure.cluster.x-k8s.io" "reconcilerKind"="DockerMachine"

Debugging a little more it looks like the problem is in [getKubectlNode](https://github.com/kubernetes-sigs/cluster-api/blob/c60114284e73f1f0cff96a3387ab92dc7344a04c/test/infrastructure/docker/docker/machine.go#L353-L375). It lists all containers with Docker and the label selectors being used match the management cluster node as well.

**What did you expect to happen:**
It should know that the management cluster node/container is not managed by CAPD or part of this cluster.

/kind bug

**Comment by fabriziopandini** [comment]
This is somehow related to https://github.com/kubernetes-sigs/cluster-api/issues/1554 and the idea of generating unique infra names.

**Comment by vincepri** [comment]
Closing this in favor of #1554 

/close
