### ISSUE TITLE
CABPK should set an env variable allowing to detect the type of node and whether a node is initialized or joined

### ISSUE THREAD

**Issue by superbrothers** [kubernetes-sigs/cluster-api#3828]
**User Story** 

When KCP creates a control plane machine, it provides users with information on whether the machine is "initialized" or "joined", and users can perform processing based on that information.

**Detailed Description**

In out cluster, we want to check in the script of `preKubeadm` whether ControlPlane machines are to be `kubeadm init` or `kubeadm join` when they are created. When it is “joined” to control-planes, `/tmp/kubeadm-join-config.yaml` is created, so it seems to be able to determine whether it is there or not.

- https://github.com/kubernetes-sigs/cluster-api/blob/v0.3.10/bootstrap/kubeadm/internal/cloudinit/controlplane_join.go#L26-L31

However, the file path will be changed in the next release and this method is weak to these changes.

- https://github.com/kubernetes-sigs/cluster-api/pull/3776

For this reason, I propose to provide information through environmental variables as follows.

- https://github.com/superbrothers/cluster-api/commit/99da129ae863fcd45f9296ef9d45064d1cbb3003

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by CecileRobertMichon** [comment]
+1 would be useful to me as well to have a way to determine if the control plane is init'ing or join'ing in preKubeadmCommands.

https://kubernetes.slack.com/archives/C8TSNPY4T/p1603321454006600

**Comment by superbrothers** [comment]
@CecileRobertMichon I need this feature to solve exactly the same problem about LB. I was surprised that the way using iptables was exactly the same😆

**Comment by CecileRobertMichon** [comment]
ha thought there were at least 2 use cases for this... I guess not 😆 

Just out of curiosity, what infra provider are you doing this with?

**Comment by superbrothers** [comment]
It is a closed source infrastructure provider developed in-house. Since it is a configuration that runs Keepalived on ControlPlane Machines, it is necessary to determine whether it is initializing or joining.

**Comment by sbueringer** [comment]
/assign @fabriziopandini 
to take a closer look

**Comment by fabriziopandini** [comment]
I think this is valuable and also easy to achieve. however, we should do this in CABPK and for all the types of machines:
- CONTROL_PLANE_INIT
- CONTROL_PLANE_JOIN
- WORKER_JOIN

Given that cloud-init does not have a primitive for setting env variables, I'm ok with the solution proposed in https://github.com/superbrothers/cluster-api/commit/99da129ae863fcd45f9296ef9d45064d1cbb3003 or similar.

/retitle CABPK should set an env variable allowing to detect the type of node and whether a node is initialized or joined

/milestone v1.2
/help

**Comment by sbueringer** [comment]
@fabriziopandini 

Q: Do we have to figure out how to do this for Windows?

Would an alternative be to just add respective marker files so the preKubeadmCommands can check for the existence of those files?

**Comment by sbueringer** [comment]
/cc @jayunit100 
WDYT?

**Comment by fabriziopandini** [comment]
good point
/remove-help
while we figure out the windows side of the story 😅

**Comment by vincepri** [comment]
+1 to have a solution for this issue, although not super sure about the environment variable approach — aren't the `rumcmd` commands run in individual shells? Sourcing at the top might not expose the variables to other commands later

**Comment by CecileRobertMichon** [comment]
> Q: Do we have to figure out how to do this for Windows?

Yes, the CABPK init run command should be valid for both Linux (cloud init) and Windows (cloudbase init)

cc @jsturtevant

**Comment by jsturtevant** [comment]
I don't think there is a way to set environment variables cross-platform.  We can create files cross-platform and do that today: https://github.com/kubernetes-sigs/cluster-api/blob/4586b16418466bd4e290f00177adef296645076f/bootstrap/kubeadm/internal/cloudinit/cloudinit.go#L34

**Comment by sbueringer** [comment]
> I don't think there is a way to set environment variables cross-platform. We can create files cross-platform and do that today:
> 
> https://github.com/kubernetes-sigs/cluster-api/blob/4586b16418466bd4e290f00177adef296645076f/bootstrap/kubeadm/internal/cloudinit/cloudinit.go#L34

I assume we could also do that with the cloud-init "files" config which feels slightly cleaner to me.

**Comment by jsturtevant** [comment]
cloud-init "files" does work in windows: https://cloudbase-init.readthedocs.io/en/latest/userdata.html#cloud-config

**Comment by fabriziopandini** [comment]
Thanks all for chiming in!
Given that the only cross os approach is using files, then we already have
- `/run/kubeadm/kubeadm.yaml` for kubeadm init
- `/run/kubeadm/kubeadm-join-config.yaml` for kubeadm join

Personally, I don't see advantages in adding new markers files for signaling the same things so IMO the only thing we are missing is something that indicates if this is a control-plane machine or not.

TBH I assume this is not super relevant given that control plane and workers scripts are driven by different kubeadmConfig objects, but I have no strong opinions and we can both define a new file marker for machine role or simply close the issue given that using environment variables is not a viable solution and init/join can be already detected via files.

**Comment by sbueringer** [comment]
> I assume this is not super relevant given that control plane and workers scripts are driven by different kubeadmConfig objects

Agree. It's already possible to differentiate between join/init and it's possible for a user to add a marker file to e.g. the KubeadmControlPlane. Also no strong opinion, but maybe we should only introduce this new "API" if it's a frequent use case.
