### ISSUE TITLE
clusterctl init failed to get provider components for the "cluster-api:v0.3.8"

### ISSUE THREAD

**Issue by jan-est** [kubernetes-sigs/cluster-api#3835]
**What steps did you take and what happened:**

With given `clusterctl-settings.json`:
```
{
  "providers": ["cluster-api","bootstrap-kubeadm","control-plane-kubeadm"]
}
```
add after running

`cmd/clusterctl/hack/create-local-repository.py`

I try to run `clusterctl init`: 

```
clusterctl init \
   --core cluster-api:v0.3.8 \
   --bootstrap kubeadm:v0.3.8 \
   --control-plane kubeadm:v0.3.8 \
   --config ~/.cluster-api/dev-repository/config.yaml
```
I got following error:

`Error: failed to get provider components for the "cluster-api:v0.3.8" provider: failed to detect default target namespace: Invalid manifest. There should be no more than one resource with Kind Namespace in the provider components yaml`

**What did you expect to happen:**

I expect `cmd/clusterctl/hack/create-local-repository.py` to create local repository .cluster-api the way that I am able to run `clusterctl init` properly.

**Environment:**

-    Cluster-api version:
    v0.3.10

-   Minikube/KIND version:
    kind v0.9.0 go1.15.2 linux/amd64

-   Kubernetes version: (use kubectl version):
    Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

-   OS (e.g. from /etc/os-release):
    18.04.5 LTS (Bionic Beaver)
    /kind bug
    [One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
/priority awaiting-more-evidence

@jan-est I see you are using a custom config file. could you kindly compare the content of the core-components.yaml with the one available in the release artifacts?

From a quick test, installing  v0.3.8 from Github works fine:
```
bin/clusterctl init    --core cluster-api:v0.3.8    --bootstrap kubeadm:v0.3.8    --control-plane kubeadm:v0.3.8
Fetching providers
Installing cert-manager Version="v0.16.1"
...
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v0.3.8" TargetNamespace="capi-system"
...
Installing Provider="bootstrap-kubeadm" Version="v0.3.8" TargetNamespace="capi-kubeadm-bootstrap-system"
...
Installing Provider="control-plane-kubeadm" Version="v0.3.8" TargetNamespace="capi-kubeadm-control-plane-system"
...

Your management cluster has been initialized successfully!
```

**Comment by jan-est** [comment]
This was an issue on my own environment set up. Issue can be closed.

**Comment by vincepri** [comment]
Thanks @jan-est !

/close
