### ISSUE TITLE
Update corefile-migration dependency to v1.0.11

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#3851]
**User Story**

As a user I would like to have support for future kubernetes upgrades which include newer versions of coredns

**Detailed Description**

v1.0.11 of corefile-migration was recently released, we should update to it to proactively support future k8s releases which will require newer versions of coredns

/kind feature

**Comment by vincepri** [comment]
/help
/good-first-issue

/milestone v0.3.11
+ v0.4.0 as well
