### ISSUE TITLE
Forward-port modifies DockerMachine condition status to report for control plane to be ready

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3859]
https://github.com/kubernetes-sigs/cluster-api/pull/3726 modifies DockerMachine condition status to report for control plane to be ready in the v0.3 branch.
These changes should now be forward ported to v0.4 

/kind feature

**Comment by Evalle** [comment]
I think I can take care of this
/assign

**Comment by Evalle** [comment]
Hey @fabriziopandini I cannot find `release-0.4` branch. AFAIK i need it to create a PR against it. Thanks. 
![Screen Shot 2020-10-26 at 9 56 57 AM](https://user-images.githubusercontent.com/2839811/97152808-c0e66500-1771-11eb-9167-14a217a0809b.png)

**Comment by fabriziopandini** [comment]
@Evalle release 0.4 - v1alpha4 - is being developed on the main branch (master)
Sorry if I wasn't clear enough

/assign @Evalle 
/lifecycle active

**Comment by Evalle** [comment]
@fabriziopandini thanks for the quick answer, I'm gonna create a PR soon.
