### ISSUE TITLE
MachineDeployment status is not easily understood

### ISSUE THREAD

**Issue by luniHw** [kubernetes-sigs/cluster-api#3865]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
1. create a workload cluster  with one node successfully
2. after a while, get the status of MachineDeployment from management cluster, its status as below
{
  "observedGeneration": 2,
  "selector": "cluster.x-k8s.io/cluster-name=wc1-19",
  "replicas": 1,
  "updatedReplicas": 1,
  "unavailableReplicas": 1,
  "phase": "ScalingUp"
}
3. query the status of workload cluster by kubectl get nodes, the node status is NotReady
"status": "NotReady",

**What did you expect to happen:**
How to understand the value of phase in machinedeployment?
the value of phase is ScalingUp, it means one node has been joined in cluster and is not ready?
when the node becomes to be NotReady,  it will affects the value of phase? for this example, the phase is Scallingup

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

1. Anyone can help to explain the relation between cluster node and the fields (replicas,phase,updatedReplicas, unavailableReplicas) in MachineDeployment status?

2. When the cluster nodes status and amount are changed, what is the status of MachineDeploymnet?

3. MachineDeployment is a node pool, can use the status of MachineDeployment to check if the nodes in this pool are Ready?

**Environment:**
- Cluster-api version: v0.3.9
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): v1.19.1
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
@luniHw 
Let me get started by pointing out to he API where those fields are defined https://github.com/kubernetes-sigs/cluster-api/blob/18b03b91e96d3f3b70106de607516c03506a7e5e/api/v1alpha3/machinedeployment_types.go#L157-L198 

and code responsible for updating the machine deployment status https://github.com/kubernetes-sigs/cluster-api/blob/18b03b91e96d3f3b70106de607516c03506a7e5e/controllers/machinedeployment_sync.go#L349-L394

As a general comment on your questions, you should consider that MachineDeployment main responsibility is about creating the required number of machines, and so MD does not apply special considerations on the status of the Kubernetes nodes hosted on the machines.

FYI, Nodes on the machines could be monitored using a MachineHealthCheck, and there is also a parallel effort to Add conditions for giving more visibility on the node status (see eg https://github.com/kubernetes-sigs/cluster-api/pull/3670)

Might be someone else wants to add more details on this health
/help

**Comment by luniHw** [comment]
> @luniHw
> Let me get started by pointing out to the API where those fields are defined
> 
> https://github.com/kubernetes-sigs/cluster-api/blob/18b03b91e96d3f3b70106de607516c03506a7e5e/api/v1alpha3/machinedeployment_types.go#L157-L198
> 
> and code responsible for updating the machine deployment status
> 
> https://github.com/kubernetes-sigs/cluster-api/blob/18b03b91e96d3f3b70106de607516c03506a7e5e/controllers/machinedeployment_sync.go#L349-L394
> 
> As a general comment on your questions, you should consider that MachineDeployment main responsibility is about creating the required number of machines, and so MD does not apply special considerations on the status of the Kubernetes nodes hosted on the machines.
> 
> FYI, Nodes on the machines could be monitored using a MachineHealthCheck, and there is also a parallel effort to Add conditions for giving more visibility on the node status (see eg #3670)
> 
> Might be someone else wants to add more details on this thread
> /help

Thanks @fabriziopandini  for your answer, so will the Replicas of MachineDeployment not be changed because of the change of node. I mean k8s scale in/out cluster node based on Replicas of MachineDeployment, the count of node will not affect the value of Replicas, right?

**Comment by fabriziopandini** [comment]
> I mean k8s scale in/out cluster node based on Replicas of MachineDeployment, the count of node will not affect the value of Replicas, right?

Yes, in MachineDeployments the number of replicas is the number of machines.
