### ISSUE TITLE
clusterctl completion: Provide dynamic auto completion

### ISSUE THREAD

**Issue by superbrothers** [kubernetes-sigs/cluster-api#3867]
**User Story**

I'd like to use dynamic auto-completion, which dynamically completes the values of arguments and flags from cluster information and config files for improving more work efficency.

**Detailed Description**

Currently `clusterctl` provides shell autocompletion with the` clusterctl completion` command. However, this is limited to subcommands and flags. I would like to take this feature one step further by dynamically complementing values such as Cluster object name in argument and Namespace object name in `--namespace` flag to improve day-to-day operational efficiency. This is similar to dynamic completion of pod name provided by `kubectl completion` command.

The arguments and flags that the current clusterctl command can support dynamic completion are:

- `--namespace` flag: Namespace object name completion
- `--kubeconfig-context` flag: Context name completion
- cluster name argument of `clusterctl config kubeconfig` command: Cluster object name completion
- `--from-config-map` flag: ConfigMap object name completion
- `--from-config-map-namespace`: Namespace object name completion
- `--target-namespace` flags: Namespace object name completion
- `--watching-namespace` flag: Namespace object name completion
- `--bootstrap`, `--control-plane`,` --core` and `--infrastructure` flags: Provider name completion

In addition to the above, it will be planned to provide commands that use the object name created in Kubernetes cluster as an argument:

- [✨ WIP: Add command and client for \`clusterctl alpha rollout restart\` by Arvinderpal · Pull Request \#3838 · kubernetes\-sigs/cluster\-api](https://github.com/kubernetes-sigs/cluster-api/pull/3838)
- [Provide "at glance" view of cluster conditions · Issue \#3802 · kubernetes\-sigs/cluster\-api](https://github.com/kubernetes-sigs/cluster-api/issues/3802)

Supporting dynamic completion eliminates the need for operators to find for and copy and paste object names.

**Anything else you would like to add:**

- `-- bootstrap`, `--control-plane`,` --core` and `--infrastructure` flags: Provider name completion

To support provider name completion, some changes need to be made to `clusterctl config repositories` command.

For example, the value of the `--bootstrap` option is the name of the bootstrap provider. To complete this, we need to get a list of bootstrap provider names from somewhere in the following format:

```
aws-eks
kubeadm
talos
```

To get a list of providers with the `clusterctl` command, there is `clusterctl config repositories` command. However, it cannot output only names. Also, it cannot filter by provider type.

Therefore, I add the `-o name` option to output only names and the `--provider` option to filter by provider type to `clusterctl config repositories` command.

If you do `clusterctl init --bootstrap <tab>`, `clusterctl config repositories -o name --provider bootstrap` will be executed behind the scenes, and the execution result will be displayed as completion candidates.

```
$ clusterctl init --bootstrap <tab>
aws-eks  kubeadm  talos
```

Other `--core`,` --control-plane`, `--infrastructure` work in the same way.

[Miscellaneous information that will assist in solving the issue.]

/kind feature

Ref https://github.com/kubernetes-sigs/cluster-api/issues/3595

**Comment by fabriziopandini** [comment]
@superbrothers many thanks for taking the time and providing more background around this idea, really appreciated
I'm going to review the PR accordingly.

**Comment by vincepri** [comment]
/milestone Next
/assign @superbrothers 
/lifecycle active

Please change the milestone accordingly if this is something that we want to have in v0.4.x

**Comment by superbrothers** [comment]
Duplicate of https://github.com/kubernetes-sigs/cluster-api/issues/4089
