### ISSUE TITLE
Unable to set up the cluster api using docker infrastructure provider

### ISSUE THREAD

**Issue by girishgouda** [kubernetes-sigs/cluster-api#3868]
I am following the quick start guide and setting the kubernetes cluster using the docker infrastruture provider. i see that the cluster is always in the Provisioning state because of which not able to get kubeconfig and run the CNI Setup. Can anybody help on this?. I was using kind 0.9 earlier but also the same error with 0.8
-----------------------------------------------------------------------------------------------------------------------------------------------------
$ kubectl get cluster
NAME              PHASE
capi-quickstart   Provisioning
-----------------------------------------------------------------------------------------------------------------------------------------------------
kubectl get machines
NAME                                    PROVIDERID   PHASE     VERSION
capi-quickstart-md-0-5477855897-bx2ff                Pending   v1.18.2
capi-quickstart-md-0-5477855897-cq5lp                Pending   v1.18.2
capi-quickstart-md-0-5477855897-s8fdr                Pending   v1.18.2
-------------------------------------------------------------------------------------------------------------------------------------------------------
$ kubectl get kubeadmcontrolplane --all-namespaces
NAMESPACE   NAME                            INITIALIZED   API SERVER AVAILABLE   VERSION   REPLICAS   READY   UPDATED   UNAVAILABLE
default     capi-quickstart-control-plane                                        v1.18.2     
----------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by fabriziopandini** [comment]
/triage needs-informationt 

@girishgouda, in order to better understand the problem some more details are required. Could you kindly provide the CAPD logs for starting?

Also, could you kindly confirm the docker socket was mounted into the kind cluster and that the kind network is properly set to bridge?

**Comment by girishgouda** [comment]
Hi  fabriziopandini 
I was following the quick start mentioned in this link  https://cluster-api.sigs.k8s.io/user/quick-start.html. how do we get the CAPD logs

Thnaks

**Comment by benmoss** [comment]
You should be able to run `kubectl -n capd-system logs deployment/capd-controller-manager -c manager`

**Comment by girishgouda** [comment]
I1027 03:26:57.283345       1 request.go:565] Throttling request took 90.655951ms, request: GET:https://10.96.0.1:443/apis/admissionregistration.k8s.io/v1beta1?timeout=32s
I1027 03:26:57.283606       1 request.go:565] Throttling request took 90.92786ms, request: GET:https://10.96.0.1:443/apis/certificates.k8s.io/v1beta1?timeout=32s
I1027 03:26:58.081176       1 request.go:565] Throttling request took 888.475292ms, request: GET:https://10.96.0.1:443/apis/scheduling.k8s.io/v1?timeout=32s
I1027 03:26:58.081194       1 request.go:565] Throttling request took 888.462447ms, request: GET:https://10.96.0.1:443/apis/bootstrap.cluster.x-k8s.io/v1alpha2?timeout=32s
I1027 03:26:58.081207       1 request.go:565] Throttling request took 888.447801ms, request: GET:https://10.96.0.1:443/apis/cert-manager.io/v1beta1?timeout=32s
I1027 03:26:58.081212       1 request.go:565] Throttling request took 888.965804ms, request: GET:https://10.96.0.1:443/apis/authorization.k8s.io/v1beta1?timeout=32s
I1027 03:26:58.081226       1 request.go:565] Throttling request took 888.477187ms, request: GET:https://10.96.0.1:443/apis/cert-manager.io/v1alpha3?timeout=32s
I1027 03:26:58.081189       1 request.go:565] Throttling request took 888.37872ms, request: GET:https://10.96.0.1:443/apis/exp.cluster.x-k8s.io/v1alpha3?timeout=32s
I1027 03:26:58.081297       1 request.go:565] Throttling request took 888.524558ms, request: GET:https://10.96.0.1:443/apis/cluster.x-k8s.io/v1alpha3?timeout=32s
I1027 03:26:58.081305       1 request.go:565] Throttling request took 888.517ms, request: GET:https://10.96.0.1:443/apis/controlplane.cluster.x-k8s.io/v1alpha3?timeout=32s
I1027 03:26:58.081310       1 request.go:565] Throttling request took 888.621854ms, request: GET:https://10.96.0.1:443/apis/acme.cert-manager.io/v1alpha2?timeout=32s
I1027 03:26:58.081202       1 request.go:565] Throttling request took 888.44276ms, request: GET:https://10.96.0.1:443/apis/cert-manager.io/v1alpha2?timeout=32s
I1027 03:26:58.081215       1 request.go:565] Throttling request took 888.473746ms, request: GET:https://10.96.0.1:443/apis/addons.cluster.x-k8s.io/v1alpha3?timeout=32s
I1027 03:26:58.081285       1 request.go:565] Throttling request took 888.513294ms, request: GET:https://10.96.0.1:443/apis/clusterctl.cluster.x-k8s.io/v1alpha3?timeout=32s
I1027 03:26:58.081299       1 request.go:565] Throttling request took 888.628662ms, request: GET:https://10.96.0.1:443/apis/acme.cert-manager.io/v1alpha3?timeout=32s
I1027 03:26:58.082085       1 request.go:565] Throttling request took 889.043853ms, request: GET:https://10.96.0.1:443/apis/cluster.x-k8s.io/v1alpha2?timeout=32s
I1027 03:26:58.081627       1 request.go:565] Throttling request took 888.740745ms, request: GET:https://10.96.0.1:443/apis/bootstrap.cluster.x-k8s.io/v1alpha3?timeout=32s
I1027 03:26:58.082008       1 request.go:565] Throttling request took 889.078058ms, request: GET:https://10.96.0.1:443/apis/exp.infrastructure.cluster.x-k8s.io/v1alpha3?timeout=32s
I1027 03:26:58.480229       1 webhook.go:92] controller-runtime/builder "msg"="skip registering a mutating webhook, admission.Defaulter interface is not implemented"  "GVK"={"Group":"infrastructure.cluster.x-k8s.io","Version":"v1alpha3","Kind":"DockerMachineTemplate"}
I1027 03:26:58.480291       1 webhook.go:123] controller-runtime/builder "msg"="Registering a validating webhook"  "GVK"={"Group":"infrastructure.cluster.x-k8s.io","Version":"v1alpha3","Kind":"DockerMachineTemplate"} "path"="/validate-infrastructure-cluster-x-k8s-io-v1alpha3-dockermachinetemplate"
I1027 03:26:58.481054       1 server.go:121] controller-runtime/webhook "msg"="registering webhook"  "path"="/validate-infrastructure-cluster-x-k8s-io-v1alpha3-dockermachinetemplate"
I1027 03:26:58.481153       1 main.go:94] setup "msg"="starting manager"  
I1027 03:26:58.481337       1 shared_informer.go:227] caches populated
I1027 03:26:58.481393       1 server.go:141] controller-runtime/webhook/webhooks "msg"="starting webhook server"  
I1027 03:26:58.673158       1 certwatcher.go:127] controller-runtime/certwatcher "msg"="Updated current TLS certificate"  
I1027 03:26:58.673222       1 controller.go:155] controller-runtime/controller "msg"="Starting EventSource" "controller"="dockercluster" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"controlPlaneEndpoint":{"host":"","port":0}},"status":{"ready":false}}}
I1027 03:26:58.673182       1 controller.go:155] controller-runtime/controller "msg"="Starting EventSource" "controller"="dockermachine" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"ready":false}}}
I1027 03:26:58.673401       1 server.go:199] controller-runtime/webhook "msg"="serving webhook server"  "host"="" "port"=443
I1027 03:26:58.673531       1 certwatcher.go:83] controller-runtime/certwatcher "msg"="Starting certificate watcher"  
I1027 03:26:58.673645       1 reflector.go:150] Starting reflector *v1alpha3.DockerCluster (9m23.212377062s) from pkg/mod/k8s.io/client-go@v0.17.9/tools/cache/reflector.go:105
I1027 03:26:58.673664       1 reflector.go:185] Listing and watching *v1alpha3.DockerCluster from pkg/mod/k8s.io/client-go@v0.17.9/tools/cache/reflector.go:105
I1027 03:26:58.673695       1 reflector.go:150] Starting reflector *v1alpha3.DockerMachine (10m37.290062782s) from pkg/mod/k8s.io/client-go@v0.17.9/tools/cache/reflector.go:105
I1027 03:26:58.673710       1 reflector.go:185] Listing and watching *v1alpha3.DockerMachine from pkg/mod/k8s.io/client-go@v0.17.9/tools/cache/reflector.go:105
I1027 03:26:58.773706       1 shared_informer.go:227] caches populated
I1027 03:26:58.773821       1 shared_informer.go:227] caches populated
I1027 03:26:58.773907       1 generic_predicates.go:168] controllers/DockerCluster "msg"="Resource is not paused, will attempt to map resource" "dockercluster"="capi-quickstart" "namespace"="default" "predicate"="createEvent" 
I1027 03:26:58.773950       1 generic_predicates.go:168] controllers/DockerMachine "msg"="Resource is not paused, will attempt to map resource" "dockermachine"="capi-quickstart-md-0-24thl" "namespace"="default" "predicate"="createEvent" 
I1027 03:26:58.773997       1 generic_predicates.go:168] controllers/DockerMachine "msg"="Resource is not paused, will attempt to map resource" "dockermachine"="capi-quickstart-md-0-t9fjz" "namespace"="default" "predicate"="createEvent" 
I1027 03:26:58.774025       1 generic_predicates.go:168] controllers/DockerMachine "msg"="Resource is not paused, will attempt to map resource" "dockermachine"="capi-quickstart-md-0-v7gd8" "namespace"="default" "predicate"="createEvent" 
I1027 03:26:58.774088       1 controller.go:155] controller-runtime/controller "msg"="Starting EventSource" "controller"="dockercluster" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"controlPlaneEndpoint":{"host":"","port":0}},"status":{"infrastructureReady":false,"controlPlaneInitialized":false}}}
I1027 03:26:58.774125       1 controller.go:155] controller-runtime/controller "msg"="Starting EventSource" "controller"="dockermachine" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"clusterName":"","bootstrap":{},"infrastructureRef":{}},"status":{"bootstrapReady":false,"infrastructureReady":false}}}
I1027 03:26:58.774269       1 reflector.go:150] Starting reflector *v1alpha3.Cluster (10m15.053568935s) from pkg/mod/k8s.io/client-go@v0.17.9/tools/cache/reflector.go:105
I1027 03:26:58.774283       1 reflector.go:185] Listing and watching *v1alpha3.Cluster from pkg/mod/k8s.io/client-go@v0.17.9/tools/cache/reflector.go:105
I1027 03:26:58.774349       1 reflector.go:150] Starting reflector *v1alpha3.Machine (10m46.061821795s) from pkg/mod/k8s.io/client-go@v0.17.9/tools/cache/reflector.go:105
I1027 03:26:58.774368       1 reflector.go:185] Listing and watching *v1alpha3.Machine from pkg/mod/k8s.io/client-go@v0.17.9/tools/cache/reflector.go:105
I1027 03:26:58.874468       1 shared_informer.go:227] caches populated
I1027 03:26:58.874542       1 shared_informer.go:227] caches populated
I1027 03:26:58.874585       1 controller.go:162] controller-runtime/controller "msg"="Starting Controller" "controller"="dockercluster" 
I1027 03:26:58.874667       1 controller.go:155] controller-runtime/controller "msg"="Starting EventSource" "controller"="dockermachine" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"controlPlaneEndpoint":{"host":"","port":0}},"status":{"ready":false}}}
I1027 03:26:58.874685       1 generic_predicates.go:168] controllers/DockerMachine "msg"="Resource is not paused, will attempt to map resource" "machine"="capi-quickstart-md-0-5477855897-bt6sb" "namespace"="default" "predicate"="createEvent" 
I1027 03:26:58.874693       1 cluster_predicates.go:72] controllers/DockerCluster "msg"="Cluster is not paused, allowing further processing" "cluster"="capi-quickstart" "eventType"="create" "namespace"="default" "predicate"="ClusterCreateNotPaused" 
I1027 03:26:58.874729       1 generic_predicates.go:168] controllers/DockerMachine "msg"="Resource is not paused, will attempt to map resource" "machine"="capi-quickstart-md-0-5477855897-nmcpm" "namespace"="default" "predicate"="createEvent" 
I1027 03:26:58.874731       1 controller.go:155] controller-runtime/controller "msg"="Starting EventSource" "controller"="dockermachine" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"controlPlaneEndpoint":{"host":"","port":0}},"status":{"infrastructureReady":false,"controlPlaneInitialized":false}}}
I1027 03:26:58.874756       1 shared_informer.go:227] caches populated
I1027 03:26:58.874771       1 generic_predicates.go:168] controllers/DockerMachine "msg"="Resource is not paused, will attempt to map resource" "machine"="capi-quickstart-md-0-5477855897-nxsd9" "namespace"="default" "predicate"="createEvent" 
I1027 03:26:58.874732       1 generic_predicates.go:99] controllers/DockerCluster "msg"="One of the provided predicates returned true, allowing further processing" "predicate"="ClusterUnpaused" "predicateAggregation"="Any" 
I1027 03:26:58.874789       1 generic_predicates.go:168] controllers/DockerMachine "msg"="Resource is not paused, will attempt to map resource" "dockercluster"="capi-quickstart" "namespace"="default" "predicate"="createEvent" 
I1027 03:26:58.874810       1 controller.go:162] controller-runtime/controller "msg"="Starting Controller" "controller"="dockermachine" 
I1027 03:26:58.874830       1 shared_informer.go:227] caches populated
I1027 03:26:58.874845       1 cluster_predicates.go:72] controllers/DockerMachine "msg"="Cluster is not paused, allowing further processing" "cluster"="capi-quickstart" "eventType"="create" "namespace"="default" "predicate"="ClusterCreateNotPaused" 
I1027 03:26:58.874855       1 shared_informer.go:227] caches populated
I1027 03:26:58.874879       1 controller.go:189] controller-runtime/controller "msg"="Starting workers" "controller"="dockercluster" "worker count"=1
I1027 03:26:58.874881       1 cluster_predicates.go:47] controllers/DockerMachine "msg"="Cluster infrastructure is not ready, blocking further processing" "cluster"="capi-quickstart" "eventType"="create" "namespace"="default" "predicate"="ClusterCreateInfraReady" 
I1027 03:26:58.874907       1 generic_predicates.go:49] controllers/DockerMachine "msg"="One of the provided predicates returned false, blocking further processing" "predicate"="ClusterUnpausedAndInfrastructureReady" "predicateAggregation"="All" 
I1027 03:26:58.874930       1 generic_predicates.go:103] controllers/DockerMachine "msg"="All of the provided predicates returned false, blocking further processing" "predicate"="ClusterUnpausedAndInfrastructureReady" "predicateAggregation"="Any" 
I1027 03:26:58.874847       1 shared_informer.go:227] caches populated
I1027 03:26:58.874953       1 generic_predicates.go:103] controllers/DockerMachine "msg"="All of the provided predicates returned false, blocking further processing" "predicate"="ClusterUnpausedAndInfrastructureReady" "predicateAggregation"="Any" 
I1027 03:26:58.874954       1 shared_informer.go:227] caches populated
I1027 03:26:58.874984       1 shared_informer.go:227] caches populated
I1027 03:26:58.874999       1 controller.go:189] controller-runtime/controller "msg"="Starting workers" "controller"="dockermachine" "worker count"=10
I1027 03:26:58.942413       1 controller.go:281] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="dockermachine" "name"="capi-quickstart-md-0-5477855897-bt6sb" "namespace"="default"
I1027 03:26:58.942483       1 controller.go:281] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="dockermachine" "name"="capi-quickstart-md-0-5477855897-nmcpm" "namespace"="default"
I1027 03:26:58.942545       1 controller.go:281] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="dockermachine" "name"="capi-quickstart-md-0-5477855897-nxsd9" "namespace"="default"
I1027 03:26:59.124155       1 dockermachine_controller.go:135] controllers/DockerMachine/DockerMachine-controller "msg"="Waiting for DockerCluster Controller to create cluster infrastructure" "cluster"="capi-quickstart" "docker-cluster"="capi-quickstart" "docker-machine"={"Namespace":"default","Name":"capi-quickstart-md-0-t9fjz"} "machine"="capi-quickstart-md-0-5477855897-bt6sb" 
I1027 03:26:59.124184       1 dockermachine_controller.go:135] controllers/DockerMachine/DockerMachine-controller "msg"="Waiting for DockerCluster Controller to create cluster infrastructure" "cluster"="capi-quickstart" "docker-cluster"="capi-quickstart" "docker-machine"={"Namespace":"default","Name":"capi-quickstart-md-0-24thl"} "machine"="capi-quickstart-md-0-5477855897-nmcpm" 
I1027 03:26:59.124275       1 dockermachine_controller.go:135] controllers/DockerMachine/DockerMachine-controller "msg"="Waiting for DockerCluster Controller to create cluster infrastructure" "cluster"="capi-quickstart" "docker-cluster"="capi-quickstart" "docker-machine"={"Namespace":"default","Name":"capi-quickstart-md-0-v7gd8"} "machine"="capi-quickstart-md-0-5477855897-nxsd9" 
I1027 03:26:59.124558       1 controller.go:281] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="dockermachine" "name"="capi-quickstart-md-0-t9fjz" "namespace"="default"
I1027 03:26:59.124661       1 controller.go:281] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="dockermachine" "name"="capi-quickstart-md-0-24thl" "namespace"="default"
I1027 03:26:59.124731       1 controller.go:281] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="dockermachine" "name"="capi-quickstart-md-0-v7gd8" "namespace"="default"
E1027 03:27:04.675683       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create helper for managing the externalLoadBalancer: failed to list containers: failed to list nodes: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster --format '{{.Names}}\\t{{.Label \"io.x-k8s.kind.cluster\"}}\\t{{.Image}}' --filter label=io.x-k8s.kind.cluster=capi-quickstart --filter label=io.x-k8s.kind.role=external-load-balancer\" failed with error: exit status 1" "controller"="dockercluster" "name"="capi-quickstart" "namespace"="default"
E1027 03:27:05.699287       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create helper for managing the externalLoadBalancer: failed to list containers: failed to list nodes: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster --format '{{.Names}}\\t{{.Label \"io.x-k8s.kind.cluster\"}}\\t{{.Image}}' --filter label=io.x-k8s.kind.cluster=capi-quickstart --filter label=io.x-k8s.kind.role=external-load-balancer\" failed with error: exit status 1" "controller"="dockercluster" "name"="capi-quickstart" "namespace"="default"
E1027 03:27:07.345374       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create helper for managing the externalLoadBalancer: failed to list containers: failed to list nodes: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster --format '{{.Names}}\\t{{.Label \"io.x-k8s.kind.cluster\"}}\\t{{.Image}}' --filter label=io.x-k8s.kind.cluster=capi-quickstart --filter label=io.x-k8s.kind.role=external-load-balancer\" failed with error: exit status 1" "controller"="dockercluster" "name"="capi-quickstart" "namespace"="default"
E1027 03:27:08.399586       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create helper for managing the externalLoadBalancer: failed to list containers: failed to list nodes: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster --format '{{.Names}}\\t{{.Label \"io.x-k8s.kind.cluster\"}}\\t{{.Image}}' --filter label=io.x-k8s.kind.cluster=capi-quickstart --filter label=io.x-k8s.kind.role=external-load-balancer\" failed with error: exit status 1" "controller"="dockercluster" "name"="capi-quickstart" "namespace"="default"
E1027 03:27:09.528075       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create helper for managing the externalLoadBalancer: failed to list containers: failed to list nodes: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster --format '{{.Names}}\\t{{.Label \"io.x-k8s.kind.cluster\"}}\\t{{.Image}}' --filter label=io.x-k8s.kind.cluster=capi-quickstart --filter label=io.x-k8s.kind.role=external-load-balancer\" failed with error: exit status 1" "controller"="dockercluster" "name"="capi-quickstart" "namespace"="default"
E1027 03:27:10.591825       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create helper for managing the externalLoadBalancer: failed to list containers: failed to list nodes: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster --format '{{.Names}}\\t{{.Label \"io.x-k8s.kind.cluster\"}}\\t{{.Image}}' --filter label=io.x-k8s.kind.cluster=capi-quickstart --filter label=io.x-k8s.kind.role=external-load-balancer\" failed with error: exit status 1" "controller"="dockercluster" "name"="capi-quickstart" "namespace"="default"
E1027 03:27:11.622290       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create helper for managing the externalLoadBalancer: failed to list containers: failed to list nodes: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster --format '{{.Names}}\\t{{.Label \"io.x-k8s.kind.cluster\"}}\\t{{.Image}}' --filter label=io.x-k8s.kind.cluster=capi-quickstart --filter label=io.x-k8s.kind.role=external-load-balancer\" failed with error: exit status 1" "controller"="dockercluster" "name"="capi-quickstart" "namespace"="default"
E1027 03:27:12.654805       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create helper for managing the externalLoadBalancer: failed to list containers: failed to list nodes: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster --format '{{.Names}}\\t{{.Label \"io.x-k8s.kind.cluster\"}}\\t{{.Image}}' --filter label=io.x-k8s.kind.cluster=capi-quickstart --filter label=io.x-k8s.kind.role=external-load-balancer\" failed with error: exit status 1" "controller"="dockercluster" "name"="capi-quickstart" "namespace"="default"
E1027 03:27:13.677875       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create helper for managing the externalLoadBalancer: failed to list containers: failed to list nodes: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster --format '{{.Names}}\\t{{.Label \"io.x-k8s.kind.cluster\"}}\\t{{.Image}}' --filter label=io.x-k8s.kind.cluster=capi-quickstart --filter label=io.x-k8s.kind.role=external-load-balancer\" failed with error: exit status 1" "controller"="dockercluster" "name"="capi-quickstart" "namespace"="default"
E1027 03:27:14.989678       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create helper for managing the externalLoadBalancer: failed to list containers: failed to list nodes: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster --format '{{.Names}}\\t{{.Label \"io.x-k8s.kind.cluster\"}}\\t{{.Image}}' --filter label=io.x-k8s.kind.cluster=capi-quickstart --filter label=io.x-k8s.kind.role=external-load-balancer\" failed with error: exit status 1" "controller"="dockercluster" "name"="capi-quickstart" "namespace"="default"
E1027 03:27:17.578416       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create helper for managing the externalLoadBalancer: failed to list containers: failed to list nodes: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster --format '{{.Names}}\\t{{.Label \"io.x-k8s.kind.cluster\"}}\\t{{.Image}}' --filter label=io.x-k8s.kind.cluster=capi-quickstart --filter label=io.x-k8s.kind.role=external-load-balancer\" failed with error: exit status 1" "controller"="dockercluster" "name"="capi-quickstart" "namespace"="default"
E1027 03:27:22.727710       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create helper for managing the externalLoadBalancer: failed to list containers: failed to list nodes: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster --format '{{.Names}}\\t{{.Label \"io.x-k8s.kind.cluster\"}}\\t{{.Image}}' --filter label=io.x-k8s.kind.cluster=capi-quickstart --filter label=io.x-k8s.kind.role=external-load-balancer\" failed with error: exit status 1" "controller"="dockercluster" "name"="capi-quickstart" "namespace"="default"

**Comment by fabriziopandini** [comment]
> failed to list containers: failed to list nodes: command "docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster 

this happens if the docker socket is not mounted in your kind cluster as described [here](https://master.cluster-api.sigs.k8s.io/user/quick-start.html#install-andor-configure-a-kubernetes-cluster)

**Comment by benmoss** [comment]
The docs are a bit confusing now, since you have to make sure you're on the right tab for each step of the process for CAPD to work. You need to either write out this Kind config file somewhere and then run `KIND_EXPERIMENTAL_DOCKER_NETWORK=bridge kind create cluster --config $CONFIGFILE` or you can use this magic base64 encoded one-line invocation:

```bash
KIND_EXPERIMENTAL_DOCKER_NETWORK=bridge kind create cluster --config <( echo a2luZDogQ2x1c3RlcgphcGlWZXJzaW9uOiBraW5kLngtazhzLmlvL3YxYWxwaGE0Cm5vZGVzOgotIHJvbGU6IGNvbnRyb2wtcGxhbmUKICBleHRyYU1vdW50czoKICAgIC0gaG9zdFBhdGg6IC92YXIvcnVuL2RvY2tlci5zb2NrCiAgICAgIGNvbnRhaW5lclBhdGg6IC92YXIvcnVuL2RvY2tlci5zb2NrCg== | base64 -d )
```

**Comment by girishgouda** [comment]
Thanks i missed that step. it works now
