### ISSUE TITLE
pre-drain Machine Deletion hook is not honored when Cluster is deleted

### ISSUE THREAD

**Issue by maplain** [kubernetes-sigs/cluster-api#3872]
**What steps did you take and what happened:**
1. Create a CAPI management cluster and a CAPI workload cluster;
2. Add pre-drain hook annotations on workload cluster Machines;
3. Delete the workload Cluster CR from the management cluster;
4. the workload cluster is deleted successfully;

**What did you expect to happen:**
1. the deletion of the workload cluster is paused because of the pre-drain hook.

**Anything else you would like to add:**
1. https://github.com/kubernetes-sigs/cluster-api/pull/2746 added the logic to skip Node draining when Cluster is being deleted;
2. different thinkings regarding draining:
   1. https://github.com/kubernetes-sigs/cluster-api/issues/2756
   2. https://github.com/kubernetes-sigs/cluster-api/pull/3864#issuecomment-716649658
   3. https://github.com/kubernetes-sigs/cluster-api/pull/3864#pullrequestreview-516871893

**Environment:**

- Cluster-api version: v0.3.10
- Minikube/KIND version: kind v0.7.0 go1.13.6 darwin/amd64
- Kubernetes version: (use `kubectl version`):
```
➜  nimbus-goclient git:(master) ✗ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1+vmware.2", GitCommit:"9d9a7637ad75801f9296a1cebe63120c020305d4", GitTreeState:"clean", BuildDate:"2020-09-22T22:55:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
I don't have the full background on this topic, but as per https://github.com/kubernetes-sigs/cluster-api/pull/3864#issuecomment-716791501

> the motivation to skip draining nodes when deleting a cluster (#2746) was to speed up potential delays in deleting nodes, under the assumption that if you're deleting an entire cluster, it's acceptable to terminate a node/machine without being graceful (i.e. without draining).

So, If it is ok to skip drain in some use cases, IMO it is ok to skip the pre-drain hooks as well

instead, the pre-termination hook should be honored, and from a quick look at the code, this is already the case.

**Comment by vincepri** [comment]
@maplain As @fabriziopandini suggested, when the Cluster is deleted, drain doesn't run to speed up operations. If you'd still need to perform some actions before the instance goes away, the deletion/termination handler should still work.

/priority awaiting-more-evidence
/milestone Next

**Comment by maplain** [comment]
Gotcha. sorry I completely lost track of this thread. Closing it now as pre-terminate could achieve the intended behavior.
