### ISSUE TITLE
KCP should take into account HA properties of different components

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3876]
**User Story**

- As an operator, I would like to KCP to not block scaling up if *at least one* of the existing instances of APIServer is available (same for ControllerManager and Scheduler). 
- As an operator, I would like to KCP to not block scaling down if *at least one*  of the remaining instances of API server is available (same for ControllerManager and Scheduler). 
- As an operator, I would like to KCP to not block scaling up/down if the operation is not compromising the etcd quorum (thus allowing to proceed with failing etcd members when possible). 

**Detailed Description**

KCP runs `reconcileHealth`, a func that executes a set of preflight to ensure the control plane is stable before moving on with the next action (scale up, scale down, roll out).

Those preflight checks are requires that everything (API Server, ControllerManager, Scheduler, etcd) is working fine *an all the control-plane machines* before enabling the next action to start.

While having everything up and running is something desirable, this is having also a negative impact on the times KCP takes to reconcile the desired state.

This issue is about starting a discussion on the possibility to improve KCP preflight checks so that we keep into account HA properties of the different components.

- for the API server:
   - scaling up should be allowed if there is at least one API server instance up and running in the existing machines (instead of all bein up and running)
   - scaling down should be allowed if there is at least one API server in the resulting cluster (all the machines minus the one being deleted) 

- for the ControllerManager and the scheduler the same rule of API server should apply; TBD if we can force leader changes according to the next operation.

- for etcd, 
  - scale down should be allowed if the resulting cluster preserves quorum (all the etcd members minus the one being deleted) 
  - scale up should be allowed if the resulting cluster preserves quorum (all the etcd members plus the one being added; the new one should be assumed as failing in order to keep into account the worst-case scenario) 

**Anything else you would like to add:**

The work on KCP remediation pioneered this approach, by allowing remediation in case of failing components and blocking the operation only if it could be potentially destructive for etcd.

One thing that we should keep into account,  is that with those changes we are increasing the impact of a *new failure* that happens in the middle of an operation that starts with one or more failing components. 
As a consequence, we might consider if to allow the users to choose which strategy to adopt for KCP preflight checks (strict = all up and running, fast = enough - for completing the operation - up and running )

/kind feature

**Comment by sbueringer** [comment]
As discussed in the backlog grooming on 11th February, we think that we should prefer stability over upgrade speed. As there also doesn't seem to be demand from the community, we're closing this issue.

/close
