### ISSUE TITLE
Ensure addition/deletion of objects to/from the cache in tests

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api#3878]
**User Story**

As a developer, I would like to use `TestEnvironment` to create objects against a local instance of the api-server while running tests and `Get` those objects in test assertions.

**Detailed Description**

Currently, there are some instances where in the `Create` operation succeeds but the cache is not populated which leads to random flakes while running the tests. To force the cache to get updated, we need to poll for the object at regular intervals until it is found.

```golang
Eventually(func() bool {
	key, _ := client.ObjectKeyFromObject(o)
	err := testEnv.Get(ctx, key, o)
	if err != nil && apierrors.IsNotFound(err) {
		return false
	}
	return true
}, "10s").Should(BeTrue())
```
Essentially adding such a loop to `TestEnv.Create()` method and conversely adding a similar function to `TestEnv.Cleanup()` method which confirms that the object can no longer be found.

**Anything else you would like to add:**

n/a

/kind feature

**Comment by fabriziopandini** [comment]
What about to include in this issue also adding a new wait loop in the `testEnv.Cleanup` func thus ensuring the objects are actually deleted before returning?

**Comment by srm09** [comment]
@fabriziopandini I have added it to the description as a one-liner. Will expand it and include the snippet for cleanup as well

**Comment by tcordeu** [comment]
@fabriziopandini Going to work on this issue, feel free to unassign me if someone is working on it!

/assign @tcordeu
/lifecycle active

**Comment by tcordeu** [comment]
I started looking into this issue and after implementing the loop you proposed on `TestEnvironment.Create()` and I am getting this two `FAIL`s on these tests: `TestReconcileInterruptibleNodeLabel` and `TestReconcileUnhealthyMachines/Remediation_does_not_happen_if_desired_replicas_<_3` with the following error:
```
panic: You are trying to make an assertion, but Gomega's fail handler is nil.
If you're using Ginkgo then you probably forgot to put your assertion in an It().
Alternatively, you may have forgotten to register a fail handler with RegisterFailHandler() or RegisterTestingT().
Depending on your vendoring solution you may be inadvertently importing gomega and subpackages (e.g. ghhtp, gexec,...) from different locations.
```
Which got me thinking if we should use Gomega for this or maybe we should implement a simple wait loop similar to `Eventually`? Maybe the tests are not properly setup or I am missing something...

/cc @srm09 @fabriziopandini

**Comment by vincepri** [comment]
@srm09 @tcordeu This issue might have been resolved by https://github.com/kubernetes-sigs/cluster-api/pull/4086

**Comment by srm09** [comment]
#4086 might be a better fix that the one I have mentioned in the description. I am down to placing a hold on this, or potentially closing this.

**Comment by vincepri** [comment]
I think we can close it, given that I haven't seen this be a problem lately

**Comment by srm09** [comment]
@tcordeu Thanks for the work that you did on the issue. For some reason, I lost track of this issue altogether and did not reach back to you on your questions. Like Vince mentioned, another PR might have solved this bug too, plus we haven't seen this one prop up in test runs recently.
We will close this for now, and track the runs to see if this occurs again.

/close
