### ISSUE TITLE
KCP should consider MachinePools when doing delete

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3880]
As per https://github.com/kubernetes-sigs/cluster-api/pull/3863#discussion_r512991884 when doing when *"Waiting for worker nodes to be deleted first"* inside `reconcileDelete`, KCP should wait for MachinePools to be deleted as well.

/kind bug

**Comment by prankul88** [comment]
@fabriziopandini I can take a look at this!
/assign

**Comment by CecileRobertMichon** [comment]
@prankul88 any updates on this one?

**Comment by prankul88** [comment]
@CecileRobertMichon I am working on some other issue for now. Unassigning myself if anyone else would like to work on it

**Comment by wangzewang** [comment]
I'd like to work on this.
/assign

**Comment by fabriziopandini** [comment]
Should we make this release blocking, it seems pretty important to me no matter if MachinePools are still experimentals

**Comment by CecileRobertMichon** [comment]
I can take this one. I don't think it's release-blocking since it's not a breaking change, and MachinePools are experimental but agree we should get it done sooner rather than later.

/assign
