### ISSUE TITLE
Backport PR 3877 "Add reverse conversion test" to release-0.3

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#3885]
Backport #3877 to the release-0.3 branch

/help
/milestone v0.3.11

**Comment by shysank** [comment]
@ncdc There is an `ObjectMeta` field in `v1Alpha2.MachineSpec` that is now deprecated, but has no conversion logic. The new tests are now trying to modify this, and failing. Right now, we only preserve new fields during `hub -> spoke`. Should we also now add a similar logic for `spoke -> hub` for deprecated fields? 
cc: @sedefsavas

**Comment by ncdc** [comment]
Which is failing - spoke-hub-spoke?

**Comment by shysank** [comment]
Yes ->
```
Spec: v1alpha2.MachineSpec{
          		ObjectMeta: v1alpha2.ObjectMeta{
        - 			Name:         "rȯfņȥXºʕ",
        + 			Name:         "",
        - 			GenerateName: "!S躗Ȯ奯",
        + 			GenerateName: "",
        - 			Namespace:    "?pʂ鶝桲»ǵu{嗿LhǓA",
        + 			Namespace:    "",
        - 			Labels:       map[string]string{"": "ʥ"},
        + 			Labels:       nil,
        - 			Annotations:  map[string]string{"/ņ讨O+bǲ脑榡Ł嶘湆ư4": "ģ眶榰槵ʪŻ%!ʧ(MISSING)t:}ɇ"},
        + 			Annotations:  nil,
        - 			OwnerReferences: []v1.OwnerReference{
        - 				{
        - 					APIVersion: "ē錀鈛ƟHǼŶ寝`6XŤǴ",
        - 					Kind:       ">*菃澺",
        - 					Name:       "猸Jŵ驡ǖ怸偝=w驍薇=呜W锣齠Ō覗虓",
        - 					UID:        "濏脗染E村諤楰ZɣǄƐ>忤ɣ韂0ȒȽ",
        - 				},
        - 			},
        + 			OwnerReferences: nil,
          		},
          		Bootstrap:         v1alpha2.Bootstrap{ConfigRef: &v1.ObjectReference{Kind: "洫ʬïeã寿茳`exYAǢ仙閊旸H", Namespace: "ɨ柘穤囚9U擺ȋ羱ʅc", Name: "疿'`釪GwĮ", UID: "縨", APIVersion: "ŝ.ʥǩ", ResourceVersion: "ǰƄ)谢sPǆȁ岯'虼ȼ愪c", FieldPath: "劈揪皖鼶赻äúƆȼ窖决ʒ"}, Data: &"1ƀǦȀ怦ǧ晗聏"},
          		InfrastructureRef: v1.ObjectReference{Kind: "ʦ憧怐", Namespace: `¡¼1炒qá"隲Ɨ]A=`, Name: "論Q2%!Ǖ(MISSING)颵ƱBɆ", UID: "#", APIVersion: "罡|ƻ抸釅i7ɡĆ姥'忤謃pĔ蜨焥ə", ResourceVersion: "亰x僕$壌薉Š4,", FieldPath: "靹ƮKX薍ȐEŹv/"},
          		... // 2 identical fields
          	},
          	Status: v1alpha2.MachineStatus{ErrorMessage: &"Ǆ", Phase: "a铪箥Z{ʫ", BootstrapReady: true, InfrastructureReady: true},
          }
```

**Comment by ncdc** [comment]
If we dropped a field in the newer API version, that presumably means that Cluster API is no longer using it. A client that places data in that field in the spoke version theoretically might be using it in some way, but we're not using it. I _think_ my vote is to just drop it during the round trip. If people agree with that, then you could either let the caller pass in a `preComparison` function so they can make any changes necessary (e.g. copy spokeFirstGet.Spec.ObjectMeta to spokeSecondGet), or let the caller pass in equality functions that are added into `Semantic` so the comparison passes.

**Comment by vincepri** [comment]
/milestone Next

Going to remove from v0.3.11 to not make it a release blocking item

**Comment by vincepri** [comment]
I don't think we actually want to backport this given the issues we discovered with spoke -> hub -> spoke?

**Comment by ncdc** [comment]
**If** we can fix the issues, backporting could be useful.

**Comment by vincepri** [comment]
We actually disabled that test for now, it needs a complete redesign

**Comment by vincepri** [comment]
/milestone v0.3.x

Let's use `x` milestone going forward, to avoid dealing with too many specific milestones
