### ISSUE TITLE
Reconcile Cluster API Cloud Provider with the effort of moving Cloud Providers out of core K8s

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#39]
_From @rsdcastro on February 14, 2018 18:35_

This issue is to track the discussion and whether or not those should be combined in some way.

cc @kris-nova @karan @roberthbailey

_Copied from original issue: kubernetes/kube-deploy#604_

**Comment by krousey** [comment]
This might be the right goal, but right now is not the right time.

The migration of cloud provider out of core is a tricky process. From discussions I had with @cheftako, they still have a lot to figure out. They are going to do the migration over several releases, and at each step they have to figure out processes for keeping code bases in sync until they're actually separated. Having our code base in there may complicate that process, or hinder our development. Also, they have to figure out how they're going to support the core CI-testing, their CI-testing, and cross products of both. We probably have a somewhat cleaner integration path that tools like kops have done already.

**Comment by roberthbailey** [comment]
This was discussed (tangentially) as part of https://github.com/kubernetes-sigs/cluster-api/issues/383 and the decision was to create separate repos for cluster api provider code.

/close
