### ISSUE TITLE
:bug: need backport of high cpu usage during kubectl drain

### ISSUE THREAD

**Issue by jdef** [kubernetes-sigs/cluster-api#3911]
CAPI cloned k8s/k8s/staging/src/k8s.io/kubectl/pkg/drain/drain.go, and there was a bug fix that recently landed there via https://github.com/kubernetes/kubernetes/pull/95260

Quickly skimming the CAPI variant, it looks like this bug is present, and should also be fixed there too.

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by prankul88** [comment]
@jdef Thanks for pointing it out. I you are okay I can push the fix for this
