### ISSUE TITLE
Add E2E test for KCP remediation

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3913]
https://github.com/kubernetes-sigs/cluster-api/pull/3830 is going to add KCP remediation.
As soon as this merge, we should add an E2E for testing some remediation use cases.

/area testing
/kind feature

**Comment by vincepri** [comment]
/milestone v0.3.11

+ v0.4.0

**Comment by fabriziopandini** [comment]
/milestone v0.4.0
And then eventually backport

**Comment by vincepri** [comment]
/assign @fabriziopandini 

Let's tackle this as soon as we can, seems pretty important given that's control plane related
