### ISSUE TITLE
Cluster deployed to local Docker with CAPD stuck at pending status

### ISSUE THREAD

**Issue by seemiller** [kubernetes-sigs/cluster-api#3917]
**What steps did you take and what happened:**
Followed the quick start guide from the Cluster API book for deploying a cluster to Docker on a Linux VM. The machines in the workload cluster are stuck in a pending status and never became available so that a deployment or pod could be created.

### install clusterctl
```
curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.3.10/clusterctl-linux-amd64 -o clusterctl
chmod +x ./clusterctl
sudo mv ./clusterctl /usr/local/bin/clusterctl
```
### Start the kind management cluster
```
cat > kind-cluster-with-extramounts.yaml <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
EOF
kind create cluster --config kind-cluster-with-extramounts.yaml
```
### Init cluster
```
clusterctl init --infrastructure docker
```
### Generate cluster config
```
clusterctl config cluster capi-quickstart --flavor development \
  --kubernetes-version v1.18.2 \
  --control-plane-machine-count=3 \
  --worker-machine-count=3 \
  > capi-quickstart.yaml
```
### Apply cluster config
```
kubectl apply -f capi-quickstart.yaml
```
### Get kubeconfig
```
clusterctl get kubeconfig capi-quickstart > capi-quickstart.kubeconfig
```
### Deploy a CNI solution 
```
kubectl --kubeconfig=./capi-quickstart.kubeconfig apply -f https://docs.projectcalico.org/v3.15/manifests/calico.yaml
```
### Wait for status...
``` 
kubectl get kubeadmcontrolplane --all-namespaces
NAMESPACE   NAME                            INITIALIZED   API SERVER AVAILABLE   VERSION   REPLICAS   READY   UPDATED   UNAVAILABLE
default     capi-quickstart-control-plane                                        v1.18.2   1                  1         1

kubectl get machines -A
NAMESPACE   NAME                                    PROVIDERID   PHASE          VERSION
default     capi-quickstart-control-plane-vfkzs                  Provisioning   v1.18.2
default     capi-quickstart-md-0-5477855897-fglrm                Pending        v1.18.2
default     capi-quickstart-md-0-5477855897-gvmwb                Pending        v1.18.2
default     capi-quickstart-md-0-5477855897-xvjp4                Pending        v1.18.2

kubectl --kubeconfig=./capi-quickstart.kubeconfig get nodes
NAME                                  STATUS   ROLES    AGE   VERSION
capi-quickstart-control-plane-vfkzs   Ready    master   26m   v1.18.2
```
### Errors from the logs - not sure if these are relevant or not
```
kubectl logs -n capd-system capd-controller-manager-*-* -c manager
I1113 00:27:18.479762       1 machine.go:345] controllers/DockerMachine/DockerMachine-controller "msg"="error: stat /etc/kubernetes/admin.conf: no such file or directory" "cluster"="capi-quickstart" "docker-cluster"="capi-quickstart" "docker-machine"={"Namespace":"default","Name":"capi-quickstart-control-plane-7q62r"} "machine"="capi-quickstart-control-plane-vfkzs"
E1113 00:27:18.479876       1 dockermachine_controller.go:318] controllers/DockerMachine "msg"="failed to patch the Kubernetes node with the machine providerID" "error"="failed update providerID: command \"docker exec --privileged capi-quickstart-control-plane-7q5tb kubectl --kubeconfig /etc/kubernetes/admin.conf patch node capi-quickstart-control-plane-vfkzs --patch '{\"spec\": {\"providerID\": \"docker:////capi-quickstart-control-plane-vfkzs\"}}'\" failed with error: exit status 1"
I1113 00:27:23.657931       1 machine.go:333] controllers/DockerMachine/DockerMachine-controller "msg"="Setting Kubernetes node providerID" "cluster"="capi-quickstart" "docker-cluster"="capi-quickstart" "docker-machine"={"Namespace":"default","Name":"capi-quickstart-control-plane-7q62r"} "machine"="capi-quickstart-control-plane-vfkzs"
```

**What did you expect to happen:**
I understand that CAPD is for development purposes only. My goal is to learn more about cluster-api and CAPD with the intent of being able to run things in a local Docker. My expectation is that a workload cluster would be deployed where I can apply a basic deployment.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: `v0.3.10`
- Minikube/KIND version: `kind v0.9.0 go1.15.4 linux/amd64`
- Kubernetes version: (use `kubectl version`): `1.19.3`
- OS (e.g. from `/etc/os-release`): `Ubuntu 20.04.1 LTS`

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by seemiller** [comment]
Further exploration of this issue has led me to determine that this is not a bug. My problems stemmed from documentation regarding the setting of the `KIND_EXPERIMENTAL_DOCKER_NETWORK` environment variable was not clear, and insufficient disk resources on the VM.

I will probably propose wording changes to the documentation to make it clearer when to use the `KIND_EXPERIMENTAL_DOCKER_NETWORK` environment variable as well as state that at least 24GB of disk space is required for images and running containers.

**Comment by fabriziopandini** [comment]
Thanks! @seemiller and sorry for not getting on this task sooner, one the last few days the team many mantainers were busy preparing the next release.
WRT to KIND_EXPERIMENTAL_DOCKER_NETWORK, there is also https://github.com/kubernetes-sigs/cluster-api/issues/3832 that can simplify the UX around CAPD
