### ISSUE TITLE
Skip spoke-hub-spoke conversion tests

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api#3923]
**What steps did you take and what happened:**
`spoke-hub-spoke` tests were recently added in #3877 to verify that `data` annotation values from hub don't override changes made in spokes. But, this is causing other test cases which were previously thought to be correct to fail. Examples: [MachineDeployment.DeletePolicy](https://github.com/kubernetes-sigs/cluster-api/pull/3773#discussion_r520164660), [deprecated fields](https://github.com/kubernetes-sigs/cluster-api/pull/3895#discussion_r518854993)

**What did you expect to happen:**
Since this is blocking other PR's, we can skip this test for now.

**Anything else you would like to add:**
More discussions in #3895 and #3773 

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by vincepri** [comment]
/milestone Next
/help

Going to stick this issue into Next for now. The spoke -> hub -> spoke fuzzer test needs to take into account of possible API changes between versions that would result in a possible data loss.
