### ISSUE TITLE
Align Flag Names with Kubernetes Components

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/cluster-api#3924]
**User Story**

As an operator, I would like to use the same flags as upstream kubernetes components use so that there is better cohesion between the many things we deploy into Kubernetes.

**Detailed Description**

In `main.go` we have a handful of flags which slightly differ from Kubernetes standard flags like `leader-election` vs `leader-elect` in Kubebuilder we're switching those to align more closely, see https://github.com/kubernetes-sigs/kubebuilder/pull/1852 In CAPI's `main.go` we have https://github.com/kubernetes-sigs/cluster-api/blob/master/main.go#L86-L99

This would change those to be:

```
	fs.StringVar(&metricsAddr, "metrics-bind-addr", ":8080",
		"The address the metric endpoint binds to.")

	fs.BoolVar(&enableLeaderElection, "leader-elect", false,
		"Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.")

	fs.DurationVar(&leaderElectionLeaseDuration, "leader-elect-lease-duration", 15*time.Second,
		"Interval at which non-leader candidates will wait to force acquire leadership (duration string)")

	fs.DurationVar(&leaderElectionRenewDeadline, "leader-elect-renew-deadline", 10*time.Second,
		"Duration that the leading controller manager will retry refreshing leadership before giving up (duration string)")

	fs.DurationVar(&leaderElectionRetryPeriod, "leader-elect-retry-period", 2*time.Second,
		"Duration the LeaderElector clients should wait between tries of actions (duration string)")
```

/kind feature

**Comment by vincepri** [comment]
@srm09 If you're looking for more work to do, this is a good breaking change

also cc @wfernandes to align these flags with the operator work

**Comment by wfernandes** [comment]
@srm09 are you working on this? else I can do it.

**Comment by srm09** [comment]
I'd be happy to work on it, but I will get it to it by tomorrow. If you are blocked elsewhere, then you can pick it up today.

**Comment by wfernandes** [comment]
Go for it...I can look around for other things 🙂
