### ISSUE TITLE
KCP validation prevents rotating ssh keys

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api#3926]
**What steps did you take and what happened:**
when editing a KCP resource to rotate ssh keys, the kcp validating webhook rejected the change. This is mainly due to the fact we're not adding `.spec.kubeadmConfigSpec.users` to the list of allowed path. This can cause security issues when an ssh key is compromised.

cc @CecileRobertMichon @vincepri @fabriziopandini 

**What did you expect to happen:**

the patch shouldn't be rejected 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by yastij** [comment]
Ideally I'd like us to fix in 0.3, as this has security implications

**Comment by detiber** [comment]
No objections to me for fixing in 0.3.x

**Comment by CecileRobertMichon** [comment]
If we do allow `spec.kubeadmConfigSpec.users` to be updated, you'd expect the patch to trigger a rolling update and replace all the KCP machines, correct?

no objection fron me to get this in 0.3.11 if we can get the fix merged in the next 24 hours so it doesn't delay the release too much.

**Comment by vincepri** [comment]
If we can get a patch today and do a quick test, +1 to merge in v0.3.11

**Comment by yastij** [comment]
I have a branch with unit tests, opening it + triggering a quick rollout

**Comment by fabriziopandini** [comment]
+1 for me
