### ISSUE TITLE
clusterctl move drops external resources 

### ISSUE THREAD

**Issue by nader-ziada** [kubernetes-sigs/cluster-api#3933]
**What steps did you take and what happened:**

- installing an external crd (for AzureIdentity) as part of the capz `infrastructure components yaml` and adding the `clusterctl.cluster.x-k8s.io/move: "true"` label on the CustomResourceDefinition object
- adding the `clusterctl.cluster.x-k8s.io/move: "true"` label on the the actual instance of AzureIdentity
- adding the cluster as an owner reference for the actual instance of AzureIdentity

I see two issues:
- when running a `clusterctl move`; the cluster and all its related objects are moved except for the AzureIdentity
- when running a `kubectl get crd --show-lables` on the target cluster after running `clusterctl init` I don't find the `clusterctl.cluster.x-k8s.io/move: "true"` label on the crd

**What did you expect to happen:**
- I expect the AzureIdentity to be moved when the cluster is moved as part of the `clusterctl move` command

**Anything else you would like to add:**
- I don't know if this is an issue, but the AzureIdentity is created in a different namespace than the cluster

**Environment:**

- Cluster-api version: v0.3.11
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 /area clustertctl

**Comment by fabriziopandini** [comment]
@nader-ziada clusterctl move is scoped to a single namespace (see https://cluster-api.sigs.k8s.io/clusterctl/commands/move.html#clusterctl-move).

However, there are also other issues like https://github.com/kubernetes-sigs/cluster-api/issues/3081 for tracking a slightly different variation of the same problem, and also I have https://github.com/kubernetes-sigs/cluster-api/issues/3354 where I'm trying to create a comprehensive picture of all the new requirements

**Comment by vincepri** [comment]
Let's close this as duplicate of https://github.com/kubernetes-sigs/cluster-api/issues/3081?
