### ISSUE TITLE
Introduce more granularity in the CAPI conditions

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api#3938]
**User Story**

today CAPI condition do not allow granular distinction between different types of conditions: 

- terminal: unrecoverable, just remove the machine
- transient: reconcile and MAYBE it’s gonna work
- blocked:  needs manual intervention, it might be unblocked after the intervention, but re-creating the machine won't change anything (e.g. not enough permissions) 

**Detailed Description**

I'll amend the CAPI condition CAEP with more information

cc @vincepri @fabriziopandini @CecileRobertMichon  

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
Agreed, the CAEP is the right place for reaching an agreement on this topic
Personally, I'm ok with adding more info to CAPI conditions it this can provide value to consumers (humans or machines); for this issue, we should aim to have a clear distinction between Severity Warning/Error and the proposed state
