### ISSUE TITLE
Create a new label for the changes that should be adopted by providers

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#3944]
Given that providers are using mostly same tools and have similar architectures with this repo, changes going in here may be relevant to add to the providers as well.

For example, these PRs can be implemented in the providers as well: 
https://github.com/kubernetes-sigs/cluster-api/pull/3753
https://github.com/kubernetes-sigs/cluster-api/pull/3744
https://github.com/kubernetes-sigs/cluster-api/pull/3934

Having a new label or deciding to use an existing one for such changes would make easier to search them.

**Comment by vincepri** [comment]
We should really have these changes as part of the migration guide to v1alpha4, which we should have started yesterday 😄 

Example: https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html

**Comment by fabriziopandini** [comment]
milestone v0.4.0

**Comment by sedefsavas** [comment]
Just thinking out loud: Instead of just documenting, one other way to do this is to have bot that creates a duplicate PR in the registered providers repos when a certain label is added to an issue.

**Comment by vincepri** [comment]
That'd be really nice
