### ISSUE TITLE
Forward port prevents reconcileEtcdMember to remove etcd members when etcd starts slowly

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3957]
https://github.com/kubernetes-sigs/cluster-api/pull/3919 introduced a fix to reconcileEtcdMember preventing removal of etcd members when etcd starts slowly
These changes should now be forward ported to v0.4

/kind feature
/milestone v0.4.0
/priority important-soon

**Comment by vincepri** [comment]
Hi @arghya88, given that we have a critical bug that relies on this forward port, I'll open a PR soon to cherry-pick the commit so we can start working on a fix for https://github.com/kubernetes-sigs/cluster-api/issues/3961

Hope that's ok!
