### ISSUE TITLE
v1alpha4 conversion web hooks are failing

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3958]
I'm observing conversion errors in v1alpha4 conversion web hooks.

e.g https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/3921/pull-cluster-api-e2e-full-main/1333420370417422336 is reporting 

`conversion webhook for cluster.x-k8s.io/v1alpha4, Kind=Cluster failed: the server could not find the requested resource`

Also tested manually creating a v1alpha3 cluster on a management cluster based on v1alpha4.

/kind bug

**Comment by vincepri** [comment]
Is this a flake or an actual bug?

**Comment by fabriziopandini** [comment]
IMO this is an actual bug

**Comment by vincepri** [comment]
Do you have any more information? I was hoping to understand a bit more what happened here and how to avoid it in the future.

**Comment by fabriziopandini** [comment]
The only evidence I have so far are:
- E2E tests failing (see linked example, but it seems that there also self-hosted periodic test is failing consistently for the same error)
- Error in https://github.com/kubernetes-sigs/cluster-api/pull/3931 and follow up discussion at https://kubernetes.slack.com/archives/C8TSNPY4T/p1605894092412100
- Error when doing manual testing for clusterctl upgrades (see https://github.com/kubernetes-sigs/cluster-api/pull/3708#issuecomment-732413158)

**Comment by wfernandes** [comment]
/cc @srm09 
Do you have any context on the conversion webhooks from v1a3 to v1a4?

**Comment by fabriziopandini** [comment]
I'm closing this given that I don't see those error happening in E2E, we could always open a more specific issue if new evidence arises
/close

**Comment by prksu** [comment]
/reopen

@fabriziopandini @vincepri I experienced this issue.

seem it was because missing `v1alpha3` scheme
https://github.com/kubernetes-sigs/cluster-api/blob/b5f22feb5a44b5663a35b57a09dc86378d4aa042/main.go#L78-L87

tried to add the `v1alpha3` scheme it works properly. I also tried to monitor capi components(core, bootstrap, control-plane) during startup when we miss `v1alpha3` scheme it doesn't register the webhook for conversion and when added `v1alpha3` scheme it does and showing log like

```console
[manager] I0329 19:30:02.844076       9 server.go:130] controller-runtime/webhook "msg"="registering webhook" "path"="/validate-cluster-x-k8s-io-v1alpha4-cluster" 
[manager] I0329 19:30:02.844469       9 server.go:130] controller-runtime/webhook "msg"="registering webhook" "path"="/convert" 
```

**Comment by fabriziopandini** [comment]
@prksu Thanks for the detailed analysis!
We usually avoid to work on closed issues. Do you mind open a new one? 
Also, given that you have already tested a solution, do you want to send a pacth 😉  (with possibly some integration test as well?)

**Comment by prksu** [comment]
@fabriziopandini Yes sure, I'll open new one. and take a work on the issue.

/close
