### ISSUE TITLE
Template and variable metadata

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api#3968]
**User Story**

As a developer/user/operator I would like to be able to query "metadata" for a provider that details the variables supported by the config (including descriptions, default values), the templates the provider supports (with descriptions and variable details) so that automation and tooling can be built that understands what is required for a provider and its templates 

**Detailed Description**

If i need to develop automation/tooling/api that understands the CAPI providers i need to rely on naming conventions for available templates (i.e. `cluster-template*.yaml`) and yaml parsing (using `yamlprocessor`) to get the variables. There is no declaritive way for a provider to publish what variables are required for its config/templates or what templates it supports and there is no extra information such as descriptions, types, default values that would aid in building tooling that understands CAPI.

I would like to see a declarative way that providers expose:
1. the variables they support in the config/templates along with extra information such as descriptions, default values
2. the list of templates along with extra information such as descriptions 

**Anything else you would like to add:**
This would also help with #3422 

/kind feature

**Comment by wfernandes** [comment]
Although cluster templating is currently out of scope, I feel this may be added/integrated to the management cluster operator.  Referencing the CAEP https://github.com/kubernetes-sigs/cluster-api/pull/3833 here for future...reference.

**Comment by fabriziopandini** [comment]
As per the comment above I'm setting to keep this into the radar 
/milestone v0.4.0

**Comment by vincepri** [comment]
This might be a good use case for the UX experience for later https://hackmd.io/Z9tzIkGJQUaU9VbFuo6I7Q

I'll move this to Next for now, unless there is someone that can write up a proposal for v1alpha4.

/milestone Next

**Comment by vincepri** [comment]
/close

This issue is going to be solved with the operator (for provider templates) and ClusteClass (for cluster templates).
