### ISSUE TITLE
Workload clusters created with same name fails to get started

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api#3973]
**What steps did you take and what happened:**
1. Deploy CAPI components with the docker provider
2. Create a workload cluster with name `foo-wc`, maybe (1 cp + 3 worker nodes)
3. Delete the workload cluster and/or kill the CAPI deployment (by deleting the kind cluster)
4. Redo step 1 and 2

**What did you expect to happen:**
The workload cluster should be created successfully without any errors

**Anything else you would like to add:**
The logs show that the providerID for the underlying DockerMachine could not be updated. Further log investigation revealed that the `docker exec` command to patch the object was being run against a container which is not running. This container was the one that was created for the control plane machine of the workload cluster initially created in step 2.

The actual issue might be arising from the logic for `listContainers` under the `test/infra/docker` directory. It looks for all containers (started/stopped) with a set of labels, one of which is the name of the cluster itself. `--filter label=foo-wc`  

**Environment:**

- Cluster-api version: `master`
- Minikube/KIND version: v0.8.1
- Kubernetes version: (use `kubectl version`): v1.18.2
- OS (e.g. from `/etc/os-release`): 

/kind bug
/area provider/docker
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by srm09** [comment]
For the above scenario, the `docker ps` command used by `listContainers` outputs:

```
$ docker ps -a --no-trunc --filter="label=io.x-k8s.kind.cluster" --format '{{.Names}}\t{{.Label "io.x-k8s.kind.cluster"}}\t{{.Image}}' --filter="label=io.x-k8s.kind.cluster=srm-1201"
srm-1201-md-0-67f9b775b5-mtlzb	srm-1201	kindest/node:v1.18.2
srm-1201-md-0-67f9b775b5-6wfv5	srm-1201	kindest/node:v1.18.2
srm-1201-md-0-67f9b775b5-m4jf9	srm-1201	kindest/node:v1.18.2
srm-1201-control-plane-v95qv	srm-1201	kindest/node:v1.18.2
srm-1201-lb	srm-1201	kindest/haproxy:2.1.1-alpine
srm-1201-md-0-67f9b775b5-jknk5	srm-1201	kindest/node:v1.18.2
srm-1201-md-0-67f9b775b5-jbp54	srm-1201	kindest/node:v1.18.2
srm-1201-md-0-67f9b775b5-m42tl	srm-1201	kindest/node:v1.18.2
srm-1201-control-plane-n5smg	srm-1201	kindest/node:v1.18.2
```

And the error message from the logs is,
```
machine.go:345] controller/dockermachine "msg"="Error response from daemon: Container fe83c3003c6ed4b34a696417a83ae17df711b95348324d2a16f7da61caaa74bd is not running" "cluster"="srm-1201" "docker-cluster"="srm-1201" "machine"="srm-1201-control-plane-v95qv" "name"="srm-1201-control-plane-zt5wf" "namespace"="default" "reconcilerGroup"="infrastructure.cluster.x-k8s.io" "reconcilerKind"="DockerMachine" 

[manager] E1202 01:03:06.572943       8 dockermachine_controller.go:302] controller/dockermachine "msg"="failed to patch the Kubernetes node with the machine providerID" "error"="failed update providerID: command \"docker exec --privileged srm-1201-control-plane-n5smg kubectl --kubeconfig /etc/kubernetes/admin.conf patch node srm-1201-control-plane-v95qv --patch '{\"spec\": {\"providerID\": \"docker:////srm-1201-control-plane-v95qv\"}}'\" failed with error: exit status 1" "name"="srm-1201-control-plane-zt5wf" "namespace"="default" "reconcilerGroup"="infrastructure.cluster.x-k8s.io" "reconcilerKind"="DockerMachine" 
```

The container `fe83c3003c6ed4b34a696417a83ae17df711b95348324d2a16f7da61caaa74bd` is the container fore the control plane created for the workload cluster in step 2. Here is the same docker command with more fields to show the container ID and status of the container
```
$ docker ps -a --no-trunc --filter="label=io.x-k8s.kind.cluster" --format '{{.ID}}\t{{.Names}}\t{{.Label "io.x-k8s.kind.cluster"}}\t{{.CreatedAt}}\t{{.Status}}' --filter="label=io.x-k8s.kind.cluster=srm-1201"
8fde7dfadad78f3349937e2ccaff1cae4c52b1645d910cd822fdc0eb3aa5076e	srm-1201-md-0-67f9b775b5-mtlzb	srm-1201	2020-12-01 17:03:05 -0800 PST	Up 10 minutes
7dde7dc8c5f0f1b15db7c54a66cf65252f898d421e61931170147b66f38e47f9	srm-1201-md-0-67f9b775b5-6wfv5	srm-1201	2020-12-01 17:03:05 -0800 PST	Up 10 minutes
0a5df52459e328fbd0e78d76750532221d8a821d1ca1df190b4fb3e022eb7420	srm-1201-md-0-67f9b775b5-m4jf9	srm-1201	2020-12-01 17:03:05 -0800 PST	Up 10 minutes
84ad4363d008cae42fdb63ff43034e578efc0e0e0281682c5e871bed31d09667	srm-1201-control-plane-v95qv	srm-1201	2020-12-01 17:02:36 -0800 PST	Up 10 minutes
fb723700b3a614248b3050cfe0b256086c7fa29674496dcfe4dce0d1b4b8fca5	srm-1201-lb	srm-1201	2020-12-01 17:02:32 -0800 PST	Up 10 minutes
05cd7cf31431f1dce9f469f1cbaea725bc01ebe27dea2b4e6ce83a6c8ac98dbc	srm-1201-md-0-67f9b775b5-jknk5	srm-1201	2020-12-01 14:32:08 -0800 PST	Exited (137) 32 minutes ago
760c08be4ecb2dd40a88b3aef37a0a88ed08473a99fd5c679bf1f87464cbe3e5	srm-1201-md-0-67f9b775b5-jbp54	srm-1201	2020-12-01 14:32:08 -0800 PST	Exited (137) 32 minutes ago
f5f58f2b3ecacb947c15e761f73af07fcc4a912cfec3b2c9e752f7f9dd22be42	srm-1201-md-0-67f9b775b5-m42tl	srm-1201	2020-12-01 14:32:08 -0800 PST	Exited (137) 32 minutes ago
fe83c3003c6ed4b34a696417a83ae17df711b95348324d2a16f7da61caaa74bd	srm-1201-control-plane-n5smg	srm-1201	2020-12-01 14:31:39 -0800 PST	Exited (137) 32 minutes ago
```

**Comment by fabriziopandini** [comment]
@srm09 how did you managed to get stopped CAPD containers? 
AFAIK CAPD force remove all the containers when you delete machines

Also, I'm not sure if ignoring stopped containers in `listContainers` solves the issues, because this will lead to CAPD trying to create a new container but failing because another container with the same name exists.

**Comment by srm09** [comment]
IIRC, I tried to delete the cluster but for some reason it did not. Hence I went ahead and deleted the kind cluster itself. I think that is why those containers might have been left behind.

**Comment by srm09** [comment]
@benmoss pointed out this issue which is slightly related https://github.com/kubernetes-sigs/cluster-api/issues/3824

**Comment by fabriziopandini** [comment]
Thanks for the explanation; I agree we should define what is the behavior in case there is container in stopped state.
AFAIK kind nodes are not able to restart (to b verified, might be this info is outdated)

**Comment by srm09** [comment]
When you say option 1, you mean that if there exist multiple sets of containers, we should bubble the error up instead of trying to use the stopped containers, which is the current behavior.

**Comment by fabriziopandini** [comment]
Yes
Given the assumption that kind nodes are not able to restart, I think that blocking and surfacing an error is the safest thing vs trying to delete and recreate, which might be problematic for control plane nodes...
