### ISSUE TITLE
Add MachineNodeHealthyCondition to Machine’s  Ready condition

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3974]
**User Story**

As a user, I would like to get a summary of machine status by looking at the machine's ready condition

**Detailed Description**

https://github.com/kubernetes-sigs/cluster-api/pull/3670 & https://github.com/kubernetes-sigs/cluster-api/pull/3890 introduced the NodeHealthy conditions on machines, however
as per discussion https://github.com/kubernetes-sigs/cluster-api/pull/3670#discussion_r497470878 we decided to not include this condition in the machine's ready condition and to open an issue outlining the contract changes for v1alpha4.

The impact of this change, if implemented, is that a machine will not get ready until a CNI is installed in the cluster. 

Is there any objection to implementing this in v1alpha4? Should we consider backporting?

**Anything else you would like to add:**

From the conditions proposal:
- A Ready condition SHOULD be provided at object level to represent the overall operational state of the component (and IMO for a machine, this includes having the node with a CNI)
- The Ready condition MUST be based on the summary of more detailed conditions existing on the same object
- An object SHOULD NEVER be in status Ready=True if one of the object's conditions are false or if one of the object dependents is in status Ready=False.

/kind feature

**Comment by srm09** [comment]
IMO adding CNI to cluster sounds like a necessary step to make the cluster usable. And if we always want the cluster to have some CNI solution installed, then making sure that the Machine's **Ready** condition reflects that prerequisite only solidifies that contract.

**Comment by fabriziopandini** [comment]
@vincepri @CecileRobertMichon opinions about including this in v1alpha4?

**Comment by CecileRobertMichon** [comment]
This shouldn't be a breaking change correct? I'm +1 on getting this in as soon as we can but I don't think it's blocking for v0.4.0

**Comment by fabriziopandini** [comment]
Given that we are going to change the semantic of the Ready condition for the machines, from a certain PoV this could be considered breaking (this was at least what we assumed when we decided to not include the the condition in the summary during v1alpha3)

**Comment by zawachte** [comment]
Is anyone looking into this? I would love to help get this implemented.

**Comment by fabriziopandini** [comment]
@zawachte AFAIK no one is driving this discussion.
Some time ago I have tried to revive it writing https://docs.google.com/document/d/1hBQnWWa5d16FOslNhDwYVOhcMjLIul4tMeUgh4maI3w/edit?usp=sharing, but without success 😢

**Comment by sbueringer** [comment]
Solution is proposed in #10897
/close
