### ISSUE TITLE
Add KCPConditions to control plane Machine’s Ready condition

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3975]
**User Story**

As a user, I would like to get a summary of the control plane machine status by looking at the machine's ready condition

**Detailed Description**

https://github.com/kubernetes-sigs/cluster-api/pull/3900 & https://github.com/kubernetes-sigs/cluster-api/pull/3922 introduced a set of KCP based conditions on machines, include this condition in the machine's ready condition because KCP is a pluggable component.

However, this decision makes the new conditions, less accessible from the user, and it also makes the status of the machine's ready condition less predictable/not consistent with other objects ready conditions

What about making ready to consider all the conditions existing on the machine?

**Anything else you would like to add:**

From the conditions proposal:
- A Ready condition SHOULD be provided at object level to represent the overall operational state of the component (and IMO for a machine, this includes having the node with a CNI)
- The Ready condition MUST be based on the summary of more detailed conditions existing on the same object
- An object SHOULD NEVER be in status Ready=True if one of the object's conditions are false or if one of the object dependents is in status Ready=False.

/kind feature

**Comment by detiber** [comment]
Do we have to worry about this leading to circular dependencies here? Will there be a case where we can't do something in KCP until a Machine is Ready, but the Machine can't be Ready until KCP has performed some operations and can mark the appropriate conditions on the Machine allowing the Machine to become Ready?

**Comment by fabriziopandini** [comment]
> Do we have to worry about this leading to circular dependencies here?

We just went into a major refactor in KCP for getting the conditions always reconciled as a first thing in KCP, so this should not be the case.

However, the challenge is how to make this generic given that control plane is pluggable.

**Comment by fabriziopandini** [comment]
We discussed this during bug triage, and we think that Machine Ready should be about machine and node, not other things that run on top of the machine (either control plane components or other workloads).

/close
