### ISSUE TITLE
Support different bootstrap/control providers in the E2E test framework

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api#3983]
**User Story**

As a provider developer I would like to write e2e tests that use the CAPI E2E test framework for running e2e tests against a control plane and bootstrap provider that isn't kubeadm. 

**Detailed Description**
There are various places in the CAPI E2E test framework where the bootstrap & control planes providers are hardcoded or assumed to be kubeadm. This means you can't use the test framework in E2E tests where there are different control plane or bootstrap providers (e.g. CAPA EKS). A number of examples:

* [ ] The current implementation of the `validateProviders` function on the `E2EConfig` assumes that there is only 1 control plane provider and only 1 bootstrap provider and that there are kubeadm. This stops the use of other providers like the `aws-eks` ones. See [here](https://github.com/kubernetes-sigs/cluster-api/blob/master/test/framework/clusterctl/e2e_config.go#L308)
* [ ] The `InitManagementClusterAndWatchControllerLogs` function [assumes kubeadm](https://github.com/kubernetes-sigs/cluster-api/blob/2dd66d6e1559f47302c263cd75bd20265ce6403a/test/framework/clusterctl/clusterctl_helpers.go#L66:L67). The `InitManagementClusterAndWatchControllerLogsInput` should have fields for Bootstrap & Control Plane providers that can be populated (i.e. from E2EConfig).
* [ ] The [DiscoverAndWaitForControlPlaneInitialized](https://github.com/kubernetes-sigs/cluster-api/blob/2dd66d6e1559f47302c263cd75bd20265ce6403a/test/framework/controlplane_helpers.go#L218) function assumes kubeadm

/kind feature

**Comment by fabriziopandini** [comment]
@richardcase happy to know you are planning to use the E2E test framework!
1) I'm +1 to change this for validating there is at least one bootstrap/controlplane provider
2) is already implemented in https://github.com/kubernetes-sigs/cluster-api/pull/3708

**Comment by richardcase** [comment]
Additionally:
* [ ] The [ApplyClusterTemplateAndWait](https://github.com/kubernetes-sigs/cluster-api/blob/2dd66d6e1559f47302c263cd75bd20265ce6403a/test/framework/clusterctl/clusterctl_helpers.go#L125) function assumes kubeadm

**Comment by shysank** [comment]
`The DiscoverAndWaitForControlPlaneInitialized function assumes kubeadm` has been handled in https://github.com/kubernetes-sigs/cluster-api/pull/4719

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

This issue is still a interesting idea but no one showed up since 2021, we can eventually reconsider if needs arise again + there are folks interested in working on it
/close
