### ISSUE TITLE
Remove the example provider

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3991]
As per https://github.com/kubernetes-sigs/cluster-api/pull/3985#discussion_r536192993, the example provider was required for some old e2e, but given that those have been removed we can now safely delete the example provider.

- [ ] remove `cmd/example-provider`
- [ ] remove `make docker-build-example-provider` target

/kind cleanup

**Comment by sheetalsingala** [comment]
Can I give this a try?

**Comment by vincepri** [comment]
Go for it @sheetalsingala !
