### ISSUE TITLE
Makefile on main branch is referencing v1alpha3 API

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#3993]
**What steps did you take and what happened:**
I noticed that in our Makefile on the main branch, we are referencing v1alpha3 API for generating the go objects.
Affected make commands are:
`make generate-go*`

https://github.com/kubernetes-sigs/cluster-api/blob/8437691189ad8de58168f6de1312e8ee56813a5b/Makefile#L227-L268

**What did you expect to happen:**
I expect them to be using the v1alpha4 API.

**Environment:**

- Cluster-api version: 8437691189ad8de58168f6de1312e8ee56813a5b

/kind bug

**Comment by wfernandes** [comment]
/assign
If this does need to be fixed, I can submit a PR for it.

**Comment by ncdc** [comment]
This is for conversion-gen and IIRC is correct

**Comment by wfernandes** [comment]
Ahh..I see. So this is generating the conversion from v1alpha3 to v1alpha4. My bad.
/close
