### ISSUE TITLE
Upgrade cert-manager to version 1.x

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3996]
Cert manager reach version 1.0, and as soon as we move to this version we can benefit from better stability of these tools and reducing impact/simplify considerations about cert-manager upgrades

/kind feature

**Comment by vincepri** [comment]
/area dependency
/priority important-soon

We should also check with Kubebuilder to see if they can upgrade as well

**Comment by sedefsavas** [comment]
Is there a compatibility matrix for cert-manager to see if v1 cert-manager deployments support `cert-manager.io/v1alpha2` objects? Could not see any in the doc: https://cert-manager.io/docs/

Will the providers need to update their cert-manager resources too?

**Comment by vincepri** [comment]
I'd reach out first to the Kubebuilder folks by opening a new issue, they might be interested in this work as well. Let's also reach out to the cert-manager contributors, maybe they can give us some hints on how to proceed?

**Comment by fabriziopandini** [comment]
https://github.com/kubernetes-sigs/kubebuilder/issues/1896
https://github.com/jetstack/cert-manager/issues/3506

The default upgrade procedure in cert-manager requires a kubectl plugin to be installed on the machine. I have asked help in the cert-manager repo for finding alternative solutions

**Comment by meyskens** [comment]
The kubectl approach is only for Kubernetes 1.15 and below. All newer versions van do a seamless upgrade thanks to conversion webhooks. I suppose you all deal with supported Kubernetes versions. We support back to 1.11 which causes this documentation to exist. You can also keep using the v1alpha2 API in your files for a long time as Kubernetes will convert it to v1 on writing

**Comment by vincepri** [comment]
Thank you @meyskens !

**Comment by fabriziopandini** [comment]
It seems we are ok from the kubebuilder side as well https://github.com/kubernetes-sigs/kubebuilder/issues/1896#issuecomment-742950853
Thank you @camilamacedo86 as well!
