### ISSUE TITLE
MachineHealthCheck status targets keep changing

### ISSUE THREAD

**Issue by jzhoucliqr** [kubernetes-sigs/cluster-api#3997]
**What steps did you take and what happened:**
MachineHealthCheck Status targets machines names are not in order, cause continuous reconciliation of MHC

```
status:
  targets:
  - vs-static-cp-6kpcb
  - vs-static-workerpool1-vsan-cluster-6fc449df6f-qsld2
  - vs-static-workerpool1-vsan-cluster-cc7bffc69-ztw88
  - vs-static-workerpool1-vsan-cluster-cc7bffc69-phlrw
  - vs-static-workerpool1-vsan-cluster-cc7bffc69-8znsm
```

then seconds later:
```
status:
  targets:
  - vs-static-workerpool1-vsan-cluster-cc7bffc69-phlrw
  - vs-static-workerpool1-vsan-cluster-cc7bffc69-8znsm
  - vs-static-cp-6kpcb
  - vs-static-workerpool1-vsan-cluster-6fc449df6f-qsld2
  - vs-static-workerpool1-vsan-cluster-cc7bffc69-ztw88

```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.11
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
/milestone v0.4.0

We should also backport, PR seems already in flight
