### ISSUE TITLE
Clean up "deprecated" variables/functions in v1alpha4

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#4005]
I see several `deprecated` variables and functions in the master, v1alpha4 could be a good time to remove all deprecated variables/functions.

If they will be deleted, sooner is better as providers are also in the process of upgrading to v1alpha4.

/kind cleanup

**Comment by srm09** [comment]
Seems like an ideal candidate for `good-first-issue`
