### ISSUE TITLE
Cannot start capi-controller-manager

### ISSUE THREAD

**Issue by Insullone** [kubernetes-sigs/cluster-api#4012]
I followed the instruction in https://cluster-api.sigs.k8s.io/developer/guide.html
the developer guide, with the option 2, the old-fashioned way. Everything is fine until I check the status of cluster:

NAMESPACE             NAME                                         READY   STATUS             RESTARTS   AGE
capi-system           capi-controller-manager-d56f68c59-xmk6x      1/2     CrashLoopBackOff   1          13s
capi-webhook-system   capi-controller-manager-76ddbdd9dd-z6b85     1/2     CrashLoopBackOff   1          13s

I checked the logs:
kubectl logs capi-controller-manager-d56f68c59-xmk6x -n capi-system -c manager
invalid argument "MachinePool=${EXP_MACHINE_POOL:=false},ClusterResourceSet=${EXP_CLUSTER_RESOURCE_SET:=false}" for "--feature-gates" flag: invalid value of MachinePool=${EXP_MACHINE_POOL:=false}, err: strconv.ParseBool: parsing "${EXP_MACHINE_POOL:=false}": invalid syntax

**What did you expect to happen:**
The status of pods should be running.

**Environment:**

- Cluster-api version:
$ clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.11", GitCommit:"e9cf6846b6d93dedadfcf44c00357d15f5ccba64", GitTreeState:"clean", BuildDate:"2020-11-19T18:49:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Minikube/KIND version: 
$ kind version
kind v0.9.0 go1.15.2 linux/amd64

- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"

/kind bug
/area clusterctl

**Comment by fabriziopandini** [comment]
this is bacuse the doc is a little bit outdated and it doesn't' mention you should pass the generated manifest through envsubst 

```
cat your-manifest.yaml | envsubst | kubectl apply -f -
```

/remove-kind bug
/kind documentation

@Insullone do you want to send a fix for the doc?

**Comment by Insullone** [comment]
Hi fabriziopandini,
Thanks for your reply. I tried
cat config/manager/manager.yaml | envsubst
but the line 24
- --feature-gates=MachinePool=${EXP_MACHINE_POOL:=false},ClusterResourceSet=${EXP_CLUSTER_RESOURCE_SET:=false}
is not changed. I think envsubst can replace variable like ${EXP_MACHINE_POOL} but cannot process expression like ${EXP_MACHINE_POOL:=false}. It's my pleasure to make a PR if we find a way to fix the issue.

**Comment by CecileRobertMichon** [comment]
@Insullone what version of envsubst are you using? we use drone/envsubst in clusterctl. You can run `make envsubst` to get the correct binary, see https://cluster-api.sigs.k8s.io/developer/tilt.html?highlight=envsubst#prerequisites

**Comment by fabriziopandini** [comment]
I know this is not ideal but you can do 
```
make envsubst
```
