### ISSUE TITLE
Use custom service accounts instead of default for controllers

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4015]
**User Story**

As an operator, I would like to use a dedicated service account for each CAPI controller (instead of default)

/kind feature

/priority important-soon
/milestone v0.4.0

**Comment by jay-rob** [comment]
Looking through this request, do you intend to run each controller independently? Typically all of the controller running with the same `manager` share a kube `client` which was initialized with the service account injected into the pod.

**Comment by fabriziopandini** [comment]
@jay-rob in CAPI we are deploying 4 separated controllers/binaries/images, each one 1 one with a controller-runtime manager & n reconcile loops, namely CAPI, CABPK, KCP, CAPD; IMO each one of them needs its own service account.

**Comment by jay-rob** [comment]
I suspect that each of the providers may want to do a similar modification to their base manifests

**Comment by fabriziopandini** [comment]
@jay-rob yes, we are documenting such types of changes for v1alpha4 in https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
