### ISSUE TITLE
Using clusterctl generate yaml for Windows NamedPipes causes backslashes to be stripped

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api#4016]
**What steps did you take and what happened:**
Windows have named pipes which have the format `\\.\pipe\pipename`.  The [yaml processor for clusterctl](https://github.com/kubernetes-sigs/cluster-api/blob/6a7adda9ab47588c182c117aada1b084837ef03a/cmd/clusterctl/client/yamlprocessor/simple_processor.go#L98) uses the https://github.com/drone/envsubst library which is treating the `\\` as a [escape sequence](https://github.com/drone/envsubst/blob/58bc65f69603f046d02b3fe199057d625ff9aa02/parse/scan.go#L180) parsing it to `\`.  

```bash
clusterctl generate yaml --from https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/kube-proxy/kube-proxy.yml

#output truncated
      - hostPath:
          path: \.\pipe\rancher_wins
          type: null

```

**What did you expect to happen:**
The values outside the expansions don't get processed. This is how it works with envsubt locally:

```
curl -LO https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/kubeadm/kube-proxy/kube-proxy.yml
envsubst < kube-proxy.yml

#output truncated
   hostPath:
          path: \\.\pipe\rancher_wins 
```

**Anything else you would like to add:**
This seems like an issue with the drone/envsubst library escaping values outside the substitutions.  

I initially ran into this through the e2e tests which use the clusterctl library to do expansion. I am working around it by adding additional escapes but this makes the template not usable directly and also causes issues during the tilt workflow.

https://github.com/kubernetes-sigs/cluster-api/blob/6a7adda9ab47588c182c117aada1b084837ef03a/test/framework/clusterctl/client.go#L129

**Environment:**

- Cluster-api version: 0.3.11
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
/area clusterctl
/area testing

**Comment by fabriziopandini** [comment]
@wfernandes is this a clusterctl issue or an issue in the envsubst library we are importing?

**Comment by wfernandes** [comment]
Hmm...yeah I believe it does have to do with the envsubst library we are using.

If I do `cat kube-proxy.yml | ./hack/tools/bin/envsubst` I can see that the escape sequence is evaluated. 
But if I used the `envsubst` (`/usr/local/opt/gettext/bin/envsubst`) on my mac, it doesn't evaluate the escape sequence.

Well..this is unfortunate! 

After looking at the parse_test.go and seeing the examples, I think it is meant to do proper parsing for substring replacement for example.

**Comment by wfernandes** [comment]
Maybe we can open an issue on drone/envsubst and discuss a good course of action from there.
@jsturtevant WDYT?

**Comment by jsturtevant** [comment]
I opened a PR demonstrating it as well: https://github.com/drone/envsubst/issues/27

I think it should only be escaped inside the replacement but wasn't sure.

**Comment by fabriziopandini** [comment]
@jsturtevant I see some work has been done on this issue outside of CAPI.
Is this still a problem in CAPI? what are the action items to get this fixed?

**Comment by jsturtevant** [comment]
https://github.com/drone/envsubst/pull/27 merged earlier this week. It's on my list to open a PR to bump the version
