### ISSUE TITLE
MHC: add new field 'atLeastDisruptions'

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes-sigs/cluster-api#4020]
**User Story**

As a user/operator I would like to set the allowed disruptions for MHC to a bracketed range to account for machineSets/Deployments that scale from just a few to many so I can set one sensible policy rather than adjusting the number continuously.

**Detailed Description**

If I set an MHC allowedDisruptions to say, 10%, and I have less than 10 nodes, I will get zero allowed disruptions.  If I can set a minimum allowed disruptions ('atLeastDisruptions' or similar field) to an integer such as 1-3, that will allow my MHC to work whether my node group is currently scaled up or down.

Without this feature, small groups will need a high percentage or a static integer, and this is not desirable if a particular node group grows.

**Anything else you would like to add:**

We've had numerous users report confusion over the fact that most reasonable percentages round down to 0 for small node groups.  People want this to 'just work' and this will allow users to more or less have a one-size-fits-most approach to MHC.

/kind feature

**Comment by vincepri** [comment]
cc @detiber @CecileRobertMichon 

/milestone Next

**Comment by shysank** [comment]
Will this new field take precedence over the existing one if both are specified? Or can we just modify the existing parsing logic in `maxUnhealthy` field to accept a range of values?

**Comment by michaelgugino** [comment]
I think if 'atLeast' is specified, it should take precedence.  EG, maxUnhealthy=10% and atLeast=3, if you have a cluster with 10 nodes, maxUnhealthy calculated = 3.
