### ISSUE TITLE
Bulk scaling of worker nodes (e.g. 200 to 1000) overloads VC by spawning 100s of VM clone requests, and eventually fails to scale worker nodes.

### ISSUE THREAD

**Issue by alokmaurya88** [kubernetes-sigs/cluster-api#4022]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

- Deploy K8S cluster with 10 nodes
-  Scale worker nodes to 200
-  Scale cluster further from 200 to  1000 worker nodes at once
-  This leads to 100s of VM clone requests.
-  We see after some point (after scaling 300 + workers), it just keeps  of cloning VMs and deleting vms.
-  It fails to scale workers node any further 
-  We see, Powered off VMs count in VC increased upto 4000+,  and it just keeps on creating and deleting vms and VMs count in VC keeps  on increasing .

**What did you expect to happen:**

- It should gradually scale up worker nodes, even though users try to scale up too manny workers
-  It should clone VMs  in batches ->  Only after these workers are ready , it should try to clone next set of vms

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.10

- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): v1.19.3
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by yastij** [comment]
@vincepri @detiber - I think giving operators a bit more control over the pace of scaling would help decrease load on the providers

**Comment by vincepri** [comment]
We possibly can provide some options, although we should treat the scaling up/down operation as one that needs to be re-entrant (like everything else). For example, we should be able to gather information about the state of scaling before proceeding with a new "batch".

We should be able to do this pretty cleanly if we define some rules and policies, and figure out what knobs we'd want to expose

/milestone Next

**Comment by vincepri** [comment]
> We see after some point (after scaling 300 + workers), it just keeps of cloning VMs and deleting vms.

Do you have more information / logs about what's happening under the hood when the above happens?

**Comment by yastij** [comment]
@vincepri - should we have a different issue to discuss controlling the scaling pace ?

**Comment by vincepri** [comment]
Shouldn't the scaling be determined from the amount of reconciled resources specified in the controller?
