### ISSUE TITLE
Document removal of kube-dns support in kubeadm

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4026]
Kubeadm is going to drop support for kube-dns in version 1.21 (xref https://github.com/kubernetes/kubeadm/issues/1943).

This should not be a problem for CABPK/KCP users, given that almost all of them should be using CoreDNS, however, we should consider if/how to issue a note to our user in case someone is still using kube-dns by twicking KubeadmConfig.Cluster configuration. 

/kind feature

**Comment by furkatgofurov7** [comment]
@fabriziopandini hi! Has someone started working on this? I am happy to help if no one is interested. (Suggestions/pointers where to start looking and where notes must be put would be awesome to have).

**Comment by sgirem463** [comment]
@fabriziopandini Hi, I am a new contributor, would like to work on this. Would appreciate your suggestions/pointers.

**Comment by fabriziopandini** [comment]
What about adding a note in https://cluster-api.sigs.k8s.io/tasks/kubeadm-control-plane.html#kubeconfig-management. Something like
```
<aside class="note warning">
<h1>Warning</h1>
KCP support only CoreDNS as a DNS server; also kube-dns support has been removed by kubeadm in v1.21.
</aside>
```

**Comment by sgirem463** [comment]
@fabriziopandini I will work on this

**Comment by sgirem463** [comment]
@fabriziopandini @vincepri 
I have made changes to the document source, the diffs are:

ALLANs-MBP:tasks alue$ 
ALLANs-MBP:tasks alue$ git diff
diff --git a/docs/book/src/tasks/kubeadm-control-plane.md b/docs/book/src/tasks/kubeadm-control-plane.md
index 50b606cf5..d24ab4f3c 100644
--- a/docs/book/src/tasks/kubeadm-control-plane.md
+++ b/docs/book/src/tasks/kubeadm-control-plane.md
@@ -2,6 +2,14 @@
 
 Using the Kubeadm control plane type to manage a control plane provides several ways to upgrade control plane machines.
 
+<aside class="note warning">
+
+<h1>Warning</h1>
+
+KCP support only CoreDNS as a DNS server; also kube-dns support has been removed by kubeadm in v1.21.
+
+</aside>
+
 ### Kubeconfig management
 
 KCP will generate and manage the admin Kubeconfig for clusters. The client certificate for the admin user is created
ALLANs-MBP:tasks alue$ 
ALLANs-MBP:tasks alue$ 

I am not sure what tests should be done for document updates.
I did "make serve-book" to serve a api book locally, the screenshot of the page is:

<img width="1579" alt="Screen Shot 2021-03-29 at 11 38 27 PM" src="https://user-images.githubusercontent.com/78000758/112946478-67041580-90ea-11eb-9e64-9aef86966488.png">

Is there anything else I should do before pulling a PR?

**Comment by sbueringer** [comment]
@sgirem463 I think it's totally fine to just open a PR to propose this change.
