### ISSUE TITLE
Possible KCP remediation flaky test

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#4029]
**What steps did you take and what happened:**
Saw another test fail and then pass....but not sure why...

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/4017/pull-cluster-api-test-main/1339407771233161216#1:build-log.txt%3A4056

**What did you expect to happen:**
Test to pass

**Anything else you would like to add:**
After looking into it a little bit, I'm a little confused as to what happened here TBH.

```
=== RUN   TestReconcileUnhealthyMachines/Remediation_does_not_happen_if_there_is_at_least_one_additional_unhealthy_etcd_member_on_a_3_machine_CP
I1217 03:13:42.102821   11701 remediation.go:189]  "msg"="etcd cluster before remediation"  "currentMembers"=["m1-mhc-unhealthy-6rkl9","m2-etcd-unhealthy-fkkmc","m3-etcd-healthy-9zgn9"] "currentTotalMembers"=3
I1217 03:13:42.102885   11701 remediation.go:244]  "msg"="etcd cluster projected after remediation of m1-mhc-unhealthy-6rkl9"  "healthyMembers"=["m3-etcd-healthy-9zgn9 (m3-etcd-healthy-9zgn9)"] "projectedQuorum"=1 "targetQuorum"=2 "targetTotalMembers"=2 "targetUnhealthyMembers"=1 "unhealthyMembers"=["m2-etcd-unhealthy-fkkmc (m2-etcd-unhealthy-fkkmc)"]
I1217 03:13:42.102913   11701 remediation.go:113]  "msg"="A control plane machine needs remediation, but removing this machine could result in etcd quorum loss. Skipping remediation"  "UnhealthyMachine"="m1-mhc-unhealthy-6rkl9"
    remediation_test.go:606: 
        Expected
            <string>: 
        to equal
            <string>: KCP can't remediate this machine because this could result in etcd loosing quorum
```

When we look at the log lines (_A control plane machine needs..._) we know it's going in the correct code path 
https://github.com/kubernetes-sigs/cluster-api/blob/dadd7bd6233edb1e422e7af282e923abff52f830/controlplane/kubeadm/controllers/remediation.go#L113-L115

And the assertion asserts other parts of the condition including `Status`, `Reason`, `Severity`.
https://github.com/kubernetes-sigs/cluster-api/blob/dadd7bd6233edb1e422e7af282e923abff52f830/controlplane/kubeadm/controllers/remediation_test.go#L600-L607

But when it comes to `Message` suddenly it's empty?

/kind bug
/area testing
/help
/good-first-issue

**Comment by fabriziopandini** [comment]
@wfernandes last week I went through recent test failures and I did not find evidence of this problem.
Is it ok for you to close this issue or are you still seeing this error?

**Comment by wfernandes** [comment]
I'm fine with closing this if we haven't seen this pop up recently. 
Yay! Flaky test destroyed!
/close
