### ISSUE TITLE
Represent Failure domains availability and spread KCP accordingly 

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api#4031]
**User Story**

As an operator I would like to see if an AZ is down and have KCP ignore those

**Detailed Description**

Currently failure domains are assumed to be always available, or during an outage/issues with an AZ a KCP machine would still be created there. the short-term solution is to remove the AZ from the status, but this might be confusing as someone would see an AZ missing from the list for no apparent reason. As this is a breaking change, we'll likely want to defer it to v1alpha4

@detiber @vincepri 

**Anything else you would like to add:**

/kind feature

**Comment by vincepri** [comment]
We'd have to add a field like `Available` or `Usable` (or anything similar) to achieve this, although that would be a breaking change from today given that all failure domains in a list are usually considered available.

What's the downside to removing a failure domain from the list, if it cannot be used (even temporarily)?

**Comment by vincepri** [comment]
@yastij Any updates here?

**Comment by yastij** [comment]
/remove-lifecycle stale

reviving this, Ideally we should have a field to represent availability (e.g. an `Available` field). KCP should then place machines on the other failure domains.
Ideally, If two machines are in the same failure domain, KCP should have a warning condition that says so. Also long term, If an AZ turn into a ready state and machines are colocated, we should scale into the newly available failure domain, then scale down the co-located machine.

This would be very valuable during outage scenarios

**Comment by fabriziopandini** [comment]
/milestone v1.2
This is valuable, so we are moving it to the milestone and see if we get critical mass/consensus on how to move on

**Comment by fabriziopandini** [comment]
linked to https://github.com/kubernetes-sigs/cluster-api/issues/5667

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough contributors to adequately respond to all issues and PRs.
/close

Grouping this idea as well as other about failure domains into https://github.com/kubernetes-sigs/cluster-api/issues/10476 to see if we can have some traction there
