### ISSUE TITLE
MHC should ignore paused machines

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api#4032]
**What steps did you take and what happened:**

Currently, MHC ignores paused MHCs/Clusters but not paused machines, this leads to machines being deleted when the pause annotation is removed, which isn't the desired intent.

@fabriziopandini also proposed introducing an MHC-specific annotation to only skip remediation while still keeping objects being reconciled.

cc @CecileRobertMichon @vincepri 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by fabriziopandini** [comment]
/milestone v0.4.0
IMO this is a candidate for backporting as well; this is another reason I'm+1 for having a separate annotation to add when the intent is to have MHC temporarily skip remediation on a machine.

**Comment by vincepri** [comment]
+1 to respect the paused annotation, and let's definitely backport to v0.3.x as well

**Comment by vincepri** [comment]
/priority important-soon

We should also probably backport this change.
