### ISSUE TITLE
Generic clusterctl credential management workflow

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#4035]
Holding issue for more commentary in 2021 :)

**User Story**

The credentials I need for the initial creation of a Cluster API management cluster isn't the same as the one the management cluster needs when it becomes self-managed.

**Detailed Description**

Discussion in https://docs.google.com/document/d/1a1G0xtZYUmLdTKmGCNbt2V7_90N-qsFEeilplE16Zo0/edit#heading=h.oskd5jj19v2m 

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
@wfernandes ^^ given this could be relevant to the management cluster operator work

/milestone v0.4.0
/area clusterctl
/priority important-soon

**Comment by wfernandes** [comment]
@fabriziopandini Yup. This was created and is linked in the comments on the CAEP.
Reference https://github.com/kubernetes-sigs/cluster-api/pull/3833/files#r540576353

**Comment by fabriziopandini** [comment]
/triage accept
This will probably require a small proposal or some more details to make it actionable

**Comment by fabriziopandini** [comment]
/close
due to lack of activity.
let's hope people interested in working in this area can restart this discussion soon
