### ISSUE TITLE
`clusterctl delete --all --include-namespace` skips capi-webhook-system namespace

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api#4039]
**What steps did you take and what happened:**

- Install a CAPI cluster with `clusterctl init --infrastructure azure` (or another provider)
- Delete that CAPI cluster with `clusterctl delete --all --include-crds --include-namespaces`
- Note that the `capi-webhook-system` namespace remains intact
- (So does `cert-manager`, but I assume that's intentional since CAPI may not "own" it)

**What did you expect to happen:**
All namespaces and resources created by CAPI are deleted.

**Anything else you would like to add:**

```
$ clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.12", GitCommit:"9e1dd7e8e428e05bee406602952ae269d55bdbba", GitTreeState:"clean", BuildDate:"2020-12-15T16:42:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
```

**Environment:**

- Cluster-api version: v0.3.12
- Minikube/KIND version: kind v0.9.0 go1.13.8 darwin/amd64
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): Darwin morton.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

/kind bug

**Comment by fabriziopandini** [comment]
I'm +1 to close this given that we are going to drop the capi-webhook-system while implementing the changes for https://github.com/kubernetes-sigs/cluster-api/issues/3042

**Comment by wfernandes** [comment]
+1 to close this as well 🙂
