### ISSUE TITLE
Build Kubetest2 Deployer for testing across Kubernetes projects

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#4040]
**Detailed Description**

Building a kubetest2 deployer for Cluster API opens up the possibility of using Cluster API across other Kubernetes projects. 

Starter projects that we intend to use kubetest2 for are:

* cloud-provider-aws
* cluster-autoscaler

**Anything else you would like to add:**
Follow up to https://github.com/kubernetes-sigs/kubetest2/issues/48
and https://github.com/kubernetes-sigs/cluster-api/pull/3855 

/kind feature
/assign

**Comment by CecileRobertMichon** [comment]
@randomvariable should this issue supersede https://github.com/kubernetes-sigs/cluster-api/issues/2826?

**Comment by vincepri** [comment]
2826 has a bit more information, let's keep that one open instead?

**Comment by randomvariable** [comment]
Ah, i thought there was an issue, but my github search failed me.

/close
