### ISSUE TITLE
Backport KubeadmControlPlane should adopt v1alpha2 kubeconfig secrets to release 0.3

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4047]
**User Story**

https://github.com/kubernetes-sigs/cluster-api/pull/4034 introduced a fix for ensuring kubeconfig secrets created by v1alpha2 controllers are adopted by KCP, thus allowing periodic kubeconfig secret re-generation preventing the expiration of the embedded client certificate.

This fix should be backported in the release 0.3 branch; Nb. small changes are required due to differences in controller-runtime (e.g. logger is not available in the context, so it should be passed as a parameter from the reconcile method down the chain)

/kind bug

**Comment by furkatgofurov7** [comment]
@fabriziopandini I think this should have been closed by #4050, but somehow it did not?
