### ISSUE TITLE
Backport update Kind to v0.9.0 on the 0.3 branch

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4055]
https://github.com/kubernetes-sigs/cluster-api/pull/3815 dropped support from kind 0.7 and moved the project to use kind v0.9 as a default (v0.8 also works; lower versions instead won't work).

We want to do the same in the v03.x branch.

Additionally, we would like to Update Kind to change the network for machines created by CAPD from bridge to kind, so the development workflow will be simplified, as per https://github.com/kubernetes-sigs/cluster-api/pull/4002.

Last but not least, by having CAPD working consistently on the kind network both for the v0.3.x and the v0.4.x branch, it will be possible to implement the e2e test for clusterctl upgrades  v0.3.x --> v0.4.x

/kind feature

@srm09

**Comment by fabriziopandini** [comment]
/area testing
/area provider/docker
/priority important-soon
/milestone v0.3.x

@tcordeu are you interested in working on this backport, given that you already did a great job on the v0.4 branch?

**Comment by tcordeu** [comment]
I will work on it!

/assign @tcordeu

**Comment by detiber** [comment]
If we are going to update the testing/automation to use kind v0.9.0, should we also make that the new minimum requirement? Ideally, whatever we are telling users is the minimum supported version will be validated by testing to avoid issues cropping up from lack of testing.

**Comment by fabriziopandini** [comment]
+1 to make it the minimum requirement (this is already the case in the main branch)

**Comment by vincepri** [comment]
@tcordeu Any updates on this issue?

**Comment by tcordeu** [comment]
@vincepri I can work on this one tomorrow, sorry for the delay!

**Comment by tcordeu** [comment]
@vincepri I have a difficult schedule this month due to university and work, so I am going to unassign myself from this issue so that someone can pick it up!

/unassign

**Comment by prankul88** [comment]
Hi, I can try to do a quick PR for this. 
/assign
