### ISSUE TITLE
Adapt clusterctl to the managers watching all namespaces for each provider

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4056]
**User Story**

As a user, I would like to have the simplest UX possible for clusterctl

As a developer, I would like to clean up old code whenever possible

**Detailed Description**

https://github.com/kubernetes-sigs/cluster-api/issues/3042 requires that a controller must manage all namespaces, and as consequence, we are going to change how to manifest will be created (https://github.com/kubernetes-sigs/cluster-api/issues/3822)

This opens ups to a series of cleanups in clusterctl, already prototyped in https://github.com/kubernetes-sigs/cluster-api/pull/3988

However there is a blocker that should be removed before doing this changes:

In our E2E tests we are using clusterctl as a library for creating management clusters, and if the library supports only v1alpha4 manifest it will be impossible to use our current machinery to test v1alpha3 --> v1alpha4

This issue is for discussing how to resolve this problem, and how to unblock this work

**Anything else you would like to add:**

As far as I'm concerned, the current code will be capable to manage both old and new manifests, but the fact of maintaining old code/more complexity only for test purposes is not ideal

/kind feature

**Comment by fabriziopandini** [comment]
/remove-kind feature
/kind cleanup
/area clusterctl
/priority backlog
/milestone v0.4.x

@wfernandes since it is related to the management cluster operator work

**Comment by vincepri** [comment]
> In our E2E tests we are using clusterctl as a library for creating management clusters, and if the library supports only v1alpha4 manifest it will be impossible to use our current machinery to test v1alpha3 --> v1alpha4

Could we use a released CLI instead?

**Comment by fabriziopandini** [comment]
> Could we use a released CLI instead?

This is something to explore, but I would limit the usage of the shell-out approach only to a new helper specifically designed for calling `clusterctl init` in the v1alpha3-->v1alpha4 test. 

For everything else I recommend continuing to use clusterctl as a library because it is simpler to integrate/setup/deploy and it worked fine so far.

**Comment by wfernandes** [comment]
Could we just `kubectl apply` v1a3 component manifests since that's what `clusterctl init` is essentially doing?

**Comment by fabriziopandini** [comment]
> Could we just kubectl apply v1a3 component manifests since that's what clusterctl init is essentially doing?

I don't think so, for two reasons. 
- if we fake the first init, then the signal from this E2E test won't be reliable/could not catch real problems
- clusterctl init is something more than apply. On top of my mind it adds labels, changes some object names, it creates inventory objects; without those bits, the upgrade won't work.

**Comment by vincepri** [comment]
/priority important-soon

Bumping priority

**Comment by vincepri** [comment]
@srm09 @fabriziopandini Could we prioritize this?

**Comment by fabriziopandini** [comment]
I think we should get https://github.com/kubernetes-sigs/cluster-api/pull/3708 merged first, and then work on this

**Comment by fabriziopandini** [comment]
> However there is a blocker that should be removed before doing this changes:
> In our E2E tests we are using clusterctl as a library for creating management clusters, and if the l ibrary supports only v1alpha4 manifest it will be impossible to use our current machinery to test v1alpha3 --> v1alpha4

The blocker has been removed, given that https://github.com/kubernetes-sigs/cluster-api/pull/3708 is going to download older version of clusterctl binary and use it for creating a v1alpha3 cluster in the E2E tests

/lifecycle active

**Comment by fabriziopandini** [comment]
cleanups/action items:
- [ ] inventory:
  - `GetDefaultProviderVersion` --> `GetProviderVersion`
  - `GetDefaultProviderNamespace` --> `GetProviderNamespace`
- [ ] clusterctl delete:
  - Remove (or depreacate) the `--namespace` flag in `clusterctl delete` and in the corresponding library method
- [ ] inventory/management group:
  - Remove `ManagementGroupList`
  - `deriveManagementGroups` should return `ManagementGroup` instead of `ManagementGroupList`; the func should error if there is more than 1 core provider or more that 1 provider instance for the same bootstrap_/control-plane/bootstrap provider
  - Remove `checkOverlappingCoreProviders`
  - `checkOverlappingProviders` should be simplified under the assumption there could be only 1 core provider
  - `GetManagementGroups` --> `GetManagementGroup`
- [ ] installer:
  - `simulateInstall` should fail if there is more than 1 instance of the same provider
  - `Validate` should be adapted to the fact that there is only one management group
- [ ] Upgrader:
  - `Plan` should return a single upgrade plan
  - `ApplyPlan` and `ApplyCustomPlan` should drop the core provider parameter given that there is only one management group in the cluster
- [ ] clusterctl upgrade plan:
  - Should returns single plan
  - Should fail gracefully if run against a v1alpha3 cluster with more than one instance of the same providers.
- [ ] clusterctl upgrade apply:
  - Should deprecate the --management-group flag and fail if the value provided does not match the existing management group
 - [] Remove --watching-namespace from clusterctl and then revert #3246. See #https://github.com/kubernetes-sigs/cluster-api/issues/3119#issuecomment-742667762 (comment) for more details.

**Comment by CecileRobertMichon** [comment]
@fabriziopandini is this release blocking for v0.4.0?

**Comment by fabriziopandini** [comment]
@CecileRobertMichon IMO removing flags for multi tenancy in clusterctl should be release blocking,  everything else it is just a nice a code cleanup/paying down the technical dept.
