### ISSUE TITLE
Faster MachinePool instance change detection

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#4062]
During scale up/down, or upgrade operations, MachinePool detects changes very slow due to waiting both ProviderMachinePool and MachinePool reconcile. Worst case, we wait 2 x single reconcile frequency, which is 20 minutes.

Example scenario where it needs to wait next reconcile:
1- Scale up MachinePool replicas
2- ProviderMachinePool modifies Scaling group template
3- ProviderMachinePool detects any changes in the next reconcile and adds new instances to providerList
4- After providerList is populated then MachinePool can read the change during its next reconcile.

One way is to trigger more frequent reconcile if `MachinePoolPhase!= "Running"`
Or this maybe another scenario where we may benefit from an underlying Machine object attached to MachinePool.

**Comment by devigned** [comment]
I'm not sure if polling is the best way to handle this, but it is what we do in CAPZ: 

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/f46baa1119d1441f263a4a5437d589b46367eae2/exp/controllers/azuremachinepool_controller.go#L289-L295

**Comment by fabriziopandini** [comment]
I'm not really sure this how 1,2,3 can be addressed at CAPI level, given that we are not aware of the ProviderMachinePool infrastructure.
Instead for 4, I guess we can explore to add a watch from the MachinePool to the ProviderMachinePool like the Machine controller is adding a watch for InfrastructureMachine types

https://github.com/kubernetes-sigs/cluster-api/blob/ed9029bf32c3d2650703030f1783a21e7664653e/controllers/machine_controller_phases.go#L151-L153

**Comment by detiber** [comment]
I suspect there are two components to this (and similar for Machine as well, just on a smaller scale).
1) reconciling underlying infrastructure changes
  - Like @fabriziopandini mentioned above, this is likely not something we can solve well at the CAPI level
  - Provider can handle this either through polling (quicker re-reconciliation)
  - Provider likely should handle this through some type of event-driven mechanism provided by the underlying infrastructure provider. 
2) reconciling node status changing to ready
  - We would need something to trigger reconciliation of the MachinePool based on changes to the associated node: https://github.com/kubernetes-sigs/cluster-api/issues/4447#issuecomment-816721317
