### ISSUE TITLE
Cluster deletion stuck in continuous loop (CAPI/CAPZ)

### ISSUE THREAD

**Issue by ssabih** [kubernetes-sigs/cluster-api#4065]
**What steps did you take and what happened:**
I am using CAPI with CAPZ, i created the cluster but the Azure subscription ID was wrong, therefore the cluster was in provisioning state. I deleted the cluster and fixed the Azure subscription id and created the cluster with new name. The deleted cluster is showing PHASE: Deleting

**What did you expect to happen:**
I was expecting the cluster to be deleted and not shown in output of kubectl get cluster

**Anything else you would like to add:**
i believe there are similar threads but for aws provider.

**Environment:**

- Cluster-api version: v0.3.12
- Kubernetes version: (use `kubectl version`): v1.19.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by fabriziopandini** [comment]
/area provider/azure
/kind bug

@nader-ziada @CecileRobertMichon PTAL ^^

**Comment by nader-ziada** [comment]
will take a look

**Comment by nader-ziada** [comment]
The capz controller is stuck in a loop of getting this error
```
[manager] E0113 14:45:17.459070       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="error deleting AzureCluster default/test-cluster-1: failed to delete resource group: could not get resource group management state: resources.GroupsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fake-subscription' could not be found.\"" "controller"="azurecluster" "name"="test-cluster-1" "namespace"="default"
```

**Comment by nader-ziada** [comment]
This is issue should be in cluster-api-provider-azure, created this https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1118

**Comment by fabriziopandini** [comment]
/close
given the issues being moved on CAPZ
