### ISSUE TITLE
foreground deletion does not respect ordering

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#4085]
**What steps did you take and what happened:**
create a cluster
delete with `kubectl delete --cascade=foreground`

With background deletion the cluster resource enforces ordering of dependants deletion programatically, first machine scalable resources, then referenced controlPlane, then referenced infrastructure resource.
With foreground deletion this ordering is not respected, as soon as you delete the cluster resource the garbage collector triggers deletion of all dependents simultaneously

**What did you expect to happen:**
Deleting with --cascade=foreground works.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
/milestone v0.4.0
At first sight, this is the same problem of https://github.com/kubernetes-sigs/cluster-api/issues/3804, but with a wider scope

**Comment by vincepri** [comment]
@enxebre What would you expect it to happen with foreground deletion?

If we delete the Cluster object first, all controllers will stop reconciling that resource because of the missing reference, that's why the deletion process is hardcoded in code.

**Comment by enxebre** [comment]
@vincepri the deletion process as it's now enforced programatically make sense to me. This only works with background deletion, if you delete with --cascade=foreground the order won't be respected, so I think we either need to fix that or claim that foreground deletion is not supported for cluster CRs

**Comment by vincepri** [comment]
IIRC what we implement is actually foreground deletion, as in we block the chain of resources to be deleted until the inner most parts are deleted first. 

True background deletion removes the resource right away and doesn't care about chain of dependencies, we implemented this in the controller because of how the resource chain is structured.

Let's document this though

**Comment by enxebre** [comment]
>IIRC what we implement is actually foreground deletion, as in we block the chain of resources to be deleted until the inner most parts are deleted first.

Right, we crafted a foreground deletion which only works when we tell the garbage collector to work on [background mode](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#controlling-how-the-garbage-collector-deletes-dependents)
