### ISSUE TITLE
Update apiserver-builder from 1.9, or switch to CRDs?

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#409]
Some core components depend on [apiserver-builder](https://github.com/kubernetes-incubator/apiserver-builder/) v1.9-alpha.3, which depends on Kubernetes 1.9.x. Therefore components are locked to the Kubernetes 1.9.x.

Updating apiserver-builder to a newer release does not seem trivial. The project is not actively maintained. Kubebuilder--a similar project that targets CRDs--is actively maintained. CRDs do not have feature parity with API extension servers, but are closer than a few releases ago, when Cluster API chose them over CRDs. In light of the above, the time seems right to revisit the choice.

### Core components that are generated by (and import) apiserver-builder:
- Generated API code `/pkg/apis`
- Generated OpenAPI spec `/pkg/openapi`
- Cluster API controllers `/pkg/controller`
- API server `/cmd/apiserver`
- Controller manager `/cmd/controller-manager`

### Why does cluster API need an updated apiserver-builder?
The cluster API controllers may have issues running on a 1.11 or newer cluster. The Kubernetes control plane is guaranteed to be compatible with the previous minor version, so the cluster API controllers should have no issues running on a 1.10 cluster.

**Comment by dlipovetsky** [comment]
The [apiserver-builder](https://github.com/kubernetes-incubator/apiserver-builder/) project appears to not be active; the latest commit is in the v1.9-alpha.3 release from May 6. The [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) project may be a good option, but today does not provide functionality we get from apiserver-builder.

**Comment by kris-nova** [comment]
Wondering if this is alluding to the discussion of switching back to CRDs?

**Comment by dlipovetsky** [comment]
@kris-nova Yes. I should have been more explicit: kubebuilder is for CRDs only, so we could use it only if we switched back to CRDs.

For reference: [CRDs have gained parity with Aggregated APIs](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#advanced-features-and-flexibility) since the time the of the decision to use an Aggregated API.

**Comment by davidewatson** [comment]
Independently of whether `cluster-api` moves to CRDs, I think it might make sense to use `kubebuilder` for provider configs. I don't think we need dedicated storage for these resources.

**Comment by davidewatson** [comment]
Though I do suspect `cluster-api` should move to CRDs for the maintenance reasons discussed [here](https://docs.google.com/document/d/16ils69KImmE94RlmzjWDrkmFZysgB2J4lGnYMRN89WM/edit?disco=AAAAB1xreHk) on "Wed 14 February 2018".

**Comment by dims** [comment]
+1 to move to CRDs

**Comment by ingvagabund** [comment]
@enxebre FYI

**Comment by roberthbailey** [comment]
We discussed this issue during the working group meeting today and the consensus is that folks think we should move back to CRDs. @detiber has started doing some prototype work using kubebuilder (see https://github.com/detiber/cluster-api-crd) but we could use some help moving this issue forward.

**Comment by randomvariable** [comment]
What's needed to move this forward, and do we want it done within the 1.12 timeframe?

**Comment by detiber** [comment]
@randomvariable So far in https://github.com/detiber/cluster-api-crd I have the basic API structs migrated over, but work still needs to be done to finish up the generated controllers, adding the validating webhooks to ensure validation parity, and adding the mutating webhooks for setting default values.

It'll probably be next week sometime before I'll be able to continue any work on it. I'm more than happy to add additional collaborators to the repo for anyone that wants to help move the conversion forward.

**Comment by detiber** [comment]
As an update, the current work to enable this has moved into https://github.com/kubernetes-sigs/cluster-api/pull/494

**Comment by chaosaffe** [comment]
I don't think this issue meets the requirements for the [help wanted](https://github.com/kubernetes/community/blob/master/contributors/devel/help-wanted.md) label. 

Please feel free to re-add if you disagree.

/remove help

**Comment by davidewatson** [comment]
@roberthbailey, @pwittrock: Is there anything left to do for this issue?

**Comment by roberthbailey** [comment]
Nope; fixed by #494.
