### ISSUE TITLE
Upgrade the controller-runtime version to v0.8.x

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api#4096]
**User Story**
**controller-runtime** is a dependency that is vendored in the CAPI codebase. Recently, a [newer version](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.8.0) of controller-runtime has been released. 

**Detailed Description**
n/a

**Anything else you would like to add:**
The k8s bits in the controller-runtime packages have been updated to v1.20.1 . But the minimum supported version for the management cluster should still remain at v1.19.0 in the test cases.

/kind feature

**Comment by srm09** [comment]
FYI, this update causes `conversion-gen` to incorrectly generate conversion functions for types that have slices of pointers to custom objects.
For example: [checkout DockerMachinePoolStatus type](https://github.com/kubernetes-sigs/cluster-api/blob/37941fe876ec60dfdad514ccb0b8daae2b37964e/test/infrastructure/docker/exp/api/v1alpha4/dockermachinepool_types.go#L80)

**Comment by prankul88** [comment]
@srm09 Hi, does this change require to have min go version as well?

With this change merged, I got an error while running command `make clusterctl`
>  #sigs.k8s.io/controller-runtime/pkg/manager
../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.8.1/pkg/manager/manager.go:53:2: duplicate method Start
note: module requires Go 1.15
Makefile:157: recipe for target 'clusterctl' failed

**Comment by vincepri** [comment]
@prankul88 Go 1.15 is required for v1alpha4

**Comment by prankul88** [comment]
@vincepri Got it. Thanks
