### ISSUE TITLE
unable to use sigs.k8s.io/cluster-api

### ISSUE THREAD

**Issue by debankur1** [kubernetes-sigs/cluster-api#4097]
v0.3.9
# sigs.k8s.io/cluster-api/util
../../../../../pkg/mod/sigs.k8s.io/cluster-api@v0.3.9/util/util.go:429:48: undefined: controllerutil.Object
../../../../../pkg/mod/sigs.k8s.io/cluster-api@v0.3.9/util/util.go:440:46: undefined: controllerutil.Object
../../../../../pkg/mod/sigs.k8s.io/cluster-api@v0.3.9/util/util.go:464:47: undefined: controllerutil.Object
../../../../../pkg/mod/sigs.k8s.io/cluster-api@v0.3.9/util/util.go:667:8: i.IsZero undefined (type reconcile.Result has no field or method IsZero)
../../../../../pkg/mod/sigs.k8s.io/cluster-api@v0.3.9/util/util.go:669:8: j.IsZero undefined (type reconcile.Result has no field or method IsZero)

v0.3.12
# sigs.k8s.io/cluster-api/util
../../../../../pkg/mod/sigs.k8s.io/cluster-api@v0.3.12/util/util.go:441:48: undefined: controllerutil.Object
../../../../../pkg/mod/sigs.k8s.io/cluster-api@v0.3.12/util/util.go:452:46: undefined: controllerutil.Object
../../../../../pkg/mod/sigs.k8s.io/cluster-api@v0.3.12/util/util.go:476:47: undefined: controllerutil.Object
../../../../../pkg/mod/sigs.k8s.io/cluster-api@v0.3.12/util/util.go:585:114: not enough arguments in call to metadataClient.Resource("k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1".SchemeGroupVersion.WithResource("customresourcedefinitions")).Get
	have (string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)
	want (context.Context, string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions, ...string)
../../../../../pkg/mod/sigs.k8s.io/cluster-api@v0.3.12/util/util.go:795:8: i.IsZero undefined (type reconcile.Result has no field or method IsZero)
../../../../../pkg/mod/sigs.k8s.io/cluster-api@v0.3.12/util/util.go:797:8: j.IsZero undefined (type reconcile.Result has no field or method IsZero)

**Comment by vincepri** [comment]
@debankur1 Looking at the dependency chain, it seems like the controller-runtime version is incompatible with the one used by Cluster API, I'd suggest looking at the go.mod in the release-0.3 branch to make those match https://github.com/kubernetes-sigs/cluster-api/blob/release-0.3/go.mod

/triage support
/milestone Next

**Comment by debankur1** [comment]
module gitlab.eng.vmware.com/core-build/nodeconfig-operator

go 1.15

require (
	github.com/StackExchange/wmi v0.0.0-20190523213315-cbe66965904d // indirect
	github.com/ghodss/yaml v1.0.1-0.20190212211648-25d852aebe32
	github.com/go-logr/logr v0.1.0
	github.com/go-ole/go-ole v1.2.4 // indirect
	github.com/operator-framework/operator-sdk v0.19.4
	github.com/shirou/gopsutil v2.20.3+incompatible
	github.com/spf13/pflag v1.0.5
	github.com/stretchr/testify v1.5.1
	k8s.io/api v0.18.2
	k8s.io/apimachinery v0.18.2
	k8s.io/client-go v12.0.0+incompatible
	sigs.k8s.io/cluster-api v0.3.12
	sigs.k8s.io/controller-runtime v0.6.0

)

replace (
	github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.3.2+incompatible // Required by OLM
	k8s.io/client-go => k8s.io/client-go v0.17.9 // Required by prometheus-operator
	k8s.io/apimachinery => k8s.io/apimachinery v0.17.9
	k8s.io/api => k8s.io/api v0.17.9
	sigs.k8s.io/controller-runtime => sigs.k8s.io/controller-runtime v0.5.14
)
did the following change it worked fine for me..thanks for the quick response..

**Comment by vincepri** [comment]
This issue was fixed by using the correct version matrix between the operator framework and cluster api
