### ISSUE TITLE
migrate usage of "gcr.io/kubernetes-ci-images"

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/cluster-api#4103]
**Detailed Description**

as part of migrating the k8s google infra to community maintained the GCR bucket "gcr.io/kubernetes-ci-images"
is being renamed to "gcr.io/k8s-staging-ci-images".
https://github.com/kubernetes/k8s.io/issues/1460

[we already applied this change to kubeadm](https://github.com/kubernetes/kubernetes/commit/d067c2e95d7eaae1d0e9e5ea5ff916c5d25f59c4), but [a search](https://github.com/kubernetes-sigs/cluster-api/search?q=%22kubernetes-ci-images%22&type=code) revealed that CAPI has it in a few places, including :

- kubeadm forked types
- CRDs
- test framework

/kind feature
/priority important-soon
(this change will happen in the 1.21 cycle)
/help
if someone wants to help with the cleanup.

**Comment by fabriziopandini** [comment]
On top of
gcr.io/kubernetes-ci-images --> gcr.io/k8s-staging-ci-images

I suggest changing also 
https://storage.googleapis.com/kubernetes-release-dev --> https://storage.googleapis.com/k8s-release-dev

in the same PR (or in separate PR if you prefer)

**Comment by fmuyassarov** [comment]
Hi @fabriziopandini. Can I work on this ?

**Comment by neolit123** [comment]
> I suggest changing also
> https://storage.googleapis.com/kubernetes-release-dev --> https://storage.googleapis.com/k8s-release-dev

looks like the new GCS bucket doesn't have the latest artifacts:
https://github.com/kubernetes/kubeadm/issues/2380#issuecomment-766401628
https://github.com/kubernetes/k8s.io/issues/1460#issuecomment-766402175
