### ISSUE TITLE
Cert-Manager-Webhook False(MissingEndpoints)

### ISSUE THREAD

**Issue by enyinna1234** [kubernetes-sigs/cluster-api#4110]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

I deployed Cert-Manager with the command from the Cluster API book, the developer's guide section(https://cluster-api.sigs.k8s.io/developer/guide.html) - kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v0.11.0/cert-manager.yaml

The next command "kubectl wait --for=condition=Available --timeout=300s apiservice v1beta1.webhook.cert-manager.io" keeps timing out.

Querying for webhook, I get the response below:

ubuntu@sustained-coonhound:~$ sudo kubectl get apiservices | grep webhook
v1beta1.webhook.cert-manager.io                cert-manager/cert-manager-webhook   False (MissingEndpoints)   69m

**What did you expect to happen:**
I expected webhook to be available

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.12
- Minikube/KIND version: v0.9.0
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.5 LTS (Bionic Beaver)

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by enyinna1234** [comment]
I think there's a gap in the developer guide documentation. The Cert-Manager piece appears to be optional because the cert-manager is already deployed by the time one gets to that step. And running the cert-manager installation command again messes things up.

**Comment by fabriziopandini** [comment]
/remove-kind bug
/kind documentation

/milestone v0.4.0

@enyinna1234 I think this is only a problem due to the developer's guide section still linking to cert-manager v0.11.0, while currently Cluster API uses v0.16.1.

Given that you discovered this problem and you see well acquainted with this guide, what do you think about sending a PR to fix the documentation?

**Comment by fmuyassarov** [comment]
Hi, 
I can send a quick fix for this.
/assign

**Comment by fmuyassarov** [comment]
@enyinna1234 Let us know if you are still failing to deploy the cert-manager. Thanks.

**Comment by enyinna1234** [comment]
Thanks, @fmuyassarov. I was able to do more testing. There are 2 issues that I identified with the documentation here:
1. It asks to create a management cluster (https://cluster-api.sigs.k8s.io/developer/guide.html#a-cluster). But creating a management cluster also deploys cert manager. And if the user goes on to deploy cert manager as instructed further down (https://cluster-api.sigs.k8s.io/developer/guide.html#cert-manager), then the user ends up with cert manager problems. Solution? Maybe some text to say that the Cert Manager step is optional.
2. The cert-manager webhook service availability command on there (https://cluster-api.sigs.k8s.io/developer/guide.html#cert-manager) isn't working. It might be best to just link the cert-manager documentation, to guide with installation and testing.

**Comment by fmuyassarov** [comment]
> Thanks, @fmuyassarov. I was able to do more testing. There are 2 issues that I identified with the documentation here:
> 
> 1. It asks to create a management cluster (https://cluster-api.sigs.k8s.io/developer/guide.html#a-cluster). But creating a management cluster also deploys cert manager. And if the user goes on to deploy cert manager as instructed further down (https://cluster-api.sigs.k8s.io/developer/guide.html#cert-manager), then the user ends up with cert manager problems. Solution? Maybe some text to say that the Cert Manager step is optional.

Hi @enyinna1234 ,
What I understood from the [doc](https://cluster-api.sigs.k8s.io/developer/guide.html#a-cluster) is, if you install cert-manager yourself, and then run tilt up, then tilt will not install the cert-manager for you, but rather waits until it is in Ready state. I did quick test.

1. I skip the installation of the cert-manager and just run tilt up.
```
You are running Kind without a local image registry.
Tilt can use the local registry to speed up builds.
Instructions: https://github.com/tilt-dev/kind-local
Beginning Tiltfile execution
local: kubectl get namespaces
 → NAME                 STATUS   AGE
 → default              Active   65s
 → kube-node-lease      Active   66s
 → kube-public          Active   66s
 → kube-system          Active   66s
 → local-path-storage   Active   62s
local: docker pull quay.io/jetstack/cert-manager-controller:v0.16.1
 → v0.16.1: Pulling from jetstack/cert-manager-controller
 → 4e1edcbff92b: Pulling fs layer
 → d49e0ea1be90: Pulling fs layer
 → e7ca676031a9: Pulling fs layer
 → e7ca676031a9: Verifying Checksum
 → e7ca676031a9: Download complete
 → 4e1edcbff92b: Verifying Checksum
 → 4e1edcbff92b: Download complete
 → 4e1edcbff92b: Pull complete
```
As you can see tilt is trying to install cert-manager v0.16.1 here, as configured [here](https://github.com/kubernetes-sigs/cluster-api/blob/0008b5ba109e839067b96f4c5b52eab9fb657eca/tilt_modules/cert_manager/Tiltfile#L29).
 
 2. I install the cert-manager (v.0.16.0) as per prerequisites and run tilt up. ( ignore the version here) 
```
You are running Kind without a local image registry.
Tilt can use the local registry to speed up builds.
Instructions: https://github.com/tilt-dev/kind-local
Beginning Tiltfile execution
local: kubectl get namespaces
 → NAME                 STATUS   AGE
 → cert-manager         Active   106s
 → default              Active   2m17s
 → kube-node-lease      Active   2m19s
 → kube-public          Active   2m19s
 → kube-system          Active   2m19s
 → local-path-storage   Active   2m14s
local: kubectl wait --for=condition=Available --timeout=300s -n cert-manager deployment/cert-manager
 → deployment.apps/cert-manager condition met
local: kubectl wait --for=condition=Available --timeout=300s -n cert-manager deployment/cert-manager-cainjector
 → deployment.apps/cert-manager-cainjector condition met
local: kubectl wait --for=condition=Available --timeout=300s -n cert-manager deployment/cert-manager-webhook
 → deployment.apps/cert-manager-webhook condition met
local: sh -c "cat << EOF | kubectl apply -f - \napiVersion: v1\nkind: Namespace\nmetadata:\n  name: cert-manager-test\n---\napiVersion: cert-manager.io/v1alpha2\nkind: Issuer\nmetadata:\n  name: test-selfsigned\n  namespace: cert-manager-test\nspec:\n  selfSigned: {}\n---\napiVersion: cert-manager.io/v1alpha2\nkind: Certificate\nmetadata:\n  name: selfsigned-cert\n  namespace: cert-manager-test\nspec:\n  dnsNames:\n    - example.com\n  secretName: selfsigned-cert-tls\n  issuerRef:\n    name: test-selfsigned\nEOF"
 → namespace/cert-manager-test created
 → issuer.cert-manager.io/test-selfsigned created
 → certificate.cert-manager.io/selfsigned-cert created
local: kubectl wait --for=condition=Ready --timeout=300s -n cert-manager-test certificate/selfsigned-cert 
 → certificate.cert-manager.io/selfsigned-cert condition met
local: sh -c "cat << EOF | kubectl delete -f - \napiVersion: v1\nkind: Namespace\nmetadata:\n  name: cert-manager-test\n---\napiVersion: cert-manager.io/v1alpha2\nkind: Issuer\nmetadata:\n  name: test-selfsigned\n  namespace: cert-manager-test\nspec:\n  selfSigned: {}\n---\napiVersion: cert-manager.io/v1alpha2\nkind: Certificate\nmetadata:\n  name: selfsigned-cert\n  namespace: cert-manager-test\nspec:\n  dnsNames:\n    - example.com\n  secretName: selfsigned-cert-tls\n  issuerRef:\n    name: test-selfsigned\nEOF"
 → namespace "cert-manager-test" deleted
 → issuer.cert-manager.io "test-selfsigned" deleted
 → certificate.cert-manager.io "selfsigned-cert" deleted
local: make kustomize envsubst
 → make: Nothing to be done for 'kustomize'.
 → make: Nothing to be done for 'envsubst'.
local: ./hack/tools/bin/kustomize build test/infrastructure/docker/config | ./hack/tools/bin/envsubst
local: ./hack/tools/bin/kustomize build ./config | ./hack/tools/bin/envsubst
Successfully loaded Tiltfile (7.826165587s)
```
Now you can see that Tilt isn't trying to install cert-manager, but waits until it is ready.
After, I also check that the cert-manager that I installed is still there (v0.16.0)

```
$ kubectl describe pod  -n  cert-manager          cert-manager-676b755d5f-88snc
Name:         cert-manager-676b755d5f-88snc
Namespace:    cert-manager
Priority:     0
Node:         kind-control-plane/172.19.0.2
Start Time:   Wed, 03 Feb 2021 23:42:44 +0200
Labels:       app=cert-manager
              app.kubernetes.io/component=controller
              app.kubernetes.io/instance=cert-manager
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=cert-manager
              helm.sh/chart=cert-manager-v0.16.0
              pod-template-hash=676b755d5f
Annotations:  prometheus.io/path: /metrics
              prometheus.io/port: 9402
              prometheus.io/scrape: true
Status:       Running
IP:           10.244.0.2
IPs:
  IP:           10.244.0.2
Controlled By:  ReplicaSet/cert-manager-676b755d5f
Containers:
  cert-manager:
    Container ID:  containerd://eb0033f4a66bd20f0745c35eb97abfae5b6d383365a9b76c12bee6c967192883
    Image:         quay.io/jetstack/cert-manager-controller:v0.16.0
    Image ID:      quay.io/jetstack/cert-manager-controller@sha256:f821ffeaccdb8cca0360e3b6c1e046b4fd4bc3d73d9d5a6783585d6bf44967a7
    Port:          9402/TCP
    Host Port:     0/TCP
```
At this moment I am not sure that this is an issue.


> 2. The cert-manager webhook service availability command on there (https://cluster-api.sigs.k8s.io/developer/guide.html#cert-manager) isn't working. It might be best to just link the cert-manager documentation, to guide with installation and testing.

I agree on this. After seeing logs of Tilt environment above (when installing cert-manager myself), I realized that scripts are waiting until deployments are in Ready state. Maybe that should be replaced in the CAPI book too, WDYT @fabriziopandini 
snippet:

```
local: kubectl wait --for=condition=Available --timeout=300s -n cert-manager deployment/cert-manager
 → deployment.apps/cert-manager condition met
local: kubectl wait --for=condition=Available --timeout=300s -n cert-manager deployment/cert-manager-cainjector
 → deployment.apps/cert-manager-cainjector condition met
local: kubectl wait --for=condition=Available --timeout=300s -n cert-manager deployment/cert-manager-webhook
 → deployment.apps/cert-manager-webhook condition met
```

**Comment by fmuyassarov** [comment]
@fabriziopandini shall I backport this change to release-0.3 branch?

**Comment by enyinna1234** [comment]
@fmuyassarov, cert-manager gets installed at the 'cluster init' step in the guide (Quick Start doc), during the provisioning of a management cluster. So the Cert-Manager step in the guide (Developer Guide), might need to be labeled as optional.

**Comment by enyinna1234** [comment]
@fmuyassarov all of this happens before we get to Tilt.

**Comment by fabriziopandini** [comment]
> @fabriziopandini shall I backport this change to release-0.3 branch?

If there are improvements in the doc, I'm ok with it.

I would also recommend to avoid new discussions on closed issues. 
Let's create a new issue linking the old one or, if necessary, re-open the issue.
