### ISSUE TITLE
Using ClusterResourceSet with Secret fails to apply

### ISSUE THREAD

**Issue by mcwumbly** [kubernetes-sigs/cluster-api#4115]
**What steps did you take and what happened:**

1. Using kind and docker provider, create a management cluster and a single workload cluster labeled with `some-label`
2. Create a Secret with a simple namespace resource to apply to workload clusters
3. Create a ClusterResourceSet to apply the secret to the workload cluster

Secret data in `/some/path/deployment.yaml`:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: some-name
```

Create secret
```
  kubectl create secret generic some-secret \
    -n some-ns \
    --from-file=/some/path/deployment.yaml \
    --type=addons.cluster.x-k8s.io/resource-set \
    --dry-run --save-config -o yaml | kubectl_mgc apply -f -
```

Create ClusterResourceSet
```
cat <<EOF | kubectl apply -f -
apiVersion: addons.cluster.x-k8s.io/v1alpha3
kind: ClusterResourceSet
metadata:
  name: some-crs
  namespace: some-ns
spec:
  strategy: ApplyOnce
  clusterSelector:
    matchExpressions:
    - key: some-label
      operator: Exists
  resources:
    - name: some-secret
      kind: Secret
EOF
```

[This branch](https://github.com/vmware-tanzu/cross-cluster-connectivity/tree/debug-cluster-api) has a simplified stripped-down version of our `/hack/e2e.sh` script that more or less does the above, which I was using to debug this issue with dev builds of cluster-api.

**What did you expect to happen:**

1. Namespace is created on workload cluster

**What happens instead:**

1. Namespace is not created on workload cluster.
2. Logs in `controller-manager` show error indicating yaml failing to decode base64 encoded string

```
$ kubectl --kubeconfig management.kubeconfig -n capi-system logs -lcontrol-plane=controller-manager -c=manager
```

```
I0125 16:12:52.373514       1 clusterresourceset_controller.go:236] controllers/ClusterResourceSet "msg"="Applying ClusterResourceSet to cluster" "cluster-name"="cluster-a" "clusterresourceset"="connectivity" "namespace"="dev-team" 
E0125 16:12:52.378985       1 clusterresourceset_controller.go:299] controllers/ClusterResourceSet "msg"="Failed to patch ClusterResourceSet as resource owner reference" "error"="Object 'Kind' is missing in 'unstructured object has no kind'" "cluster-name"="cluster-a" "clusterresourceset"="connectivity" "namespace"="dev-team" "Resource name"="dns-server" "Resource type"=""
E0125 16:12:52.379510       1 clusterresourceset_controller.go:344] controllers/ClusterResourceSet "msg"="failed to apply ClusterResourceSet resource" "error"="failed converting data to unstructured objects: failed to unmarshal the 1st yaml document: \"LS0tCmFwaVZlcnNpb246IHYxCmtpbmQ6IE5hbWVzcGFjZQptZXRhZGF0YToKICBuYW1lOiBjYXBpLWRucwo=\\n\": error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type map[string]interface {}" "cluster-name"="cluster-a" "clusterresourceset"="connectivity" "namespace"="dev-team" "Resource kind"="Secret" "Resource name"="dns-server"
E0125 16:12:52.409041       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="[Object 'Kind' is missing in 'unstructured object has no kind', failed converting data to unstructured objects: failed to unmarshal the 1st yaml document: \"LS0tCmFwaVZlcnNpb246IHYxCmtpbmQ6IE5hbWVzcGFjZQptZXRhZGF0YToKICBuYW1lOiBjYXBpLWRucwo=\\n\": error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type map[string]interface {}]" "controller"="clusterresourceset" "name"="connectivity" "namespace"="dev-team"

```

**Anything else you would like to add:**

After upgrading from v0.3.11 to v0.3.12, we recently [started to see a failure](https://github.com/vmware-tanzu/cross-cluster-connectivity/issues/55) when attempting to apply a ClusterResourceSet that references a Secret.

This started to fail for us when we upgraded from v0.3.11 to v0.3.12, and I've narrowed things down further to [this commit](https://github.com/kubernetes-sigs/cluster-api/commit/1574cde8acdbc6a7dd57b20ca2cdac453ed2b516), which begins bypassing the cache reader for certain types of objects. For some reason, when the liveReader is used, the secret data never gets base64 decoded. (From what I can tell, in that case, the kind is not set [when it is checked here](https://github.com/kubernetes-sigs/cluster-api/blob/5da747ff79d760c7665b4f0a7dd9b6259c694d74/exp/addons/controllers/clusterresourceset_controller.go#L327-L330) in this case).

I don't see anything obviously in how the `liveReader` vs. the `cacheReader` is created, which makes me wonder if this might be an issue in controller-runtime itself.

**Environment:**

- Cluster-api version: v0.3.12 and v0.3.13 show this issue
- Minikube/KIND version: kind v0.10.0-alpha go1.14.3 darwin/amd64
- Kubernetes version: (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"18", Gi
rsion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd6
Server Version: version.Info{Major:"1", Minor:"19", Gi
rsion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}`
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sedefsavas** [comment]
Thanks for investigating this issue @mcwumbly 
I am able to replicate it and see the same reason, if cache is disabled, this doesn't happen.
Will track further.

**Comment by sedefsavas** [comment]
The problem happens here:
		`err = toUnstructured(value.Elem(), reflect.ValueOf(&u).Elem())`
https://github.com/kubernetes/apimachinery/blob/ee96543cc6730a24af1c7323dac47e52c340ba39/pkg/runtime/converter.go#L416

In apimachinery, when converting to unstructured, value.Elem() is missing TypeMeta when liveclient is used for Secrets. 
Caching or not-caching, `value` is the same but value.Elem() has TypeMeta if it is cached.

**Comment by sedefsavas** [comment]
After digging a bit more, saw that when we use live clients, we never get `TypeMeta`. 
This is the case in KubeadmContolPlane as well, it uses `mgr.GetAPIReader()` as client and the resources retrieved by that client does not have `kind` and `apiVersion`. So we may hit this issue in other places in the code where live readers are used.

If objects received by Get() call should always include the `TypeMeta`, then I think we should fix it in controller-runtime.

**Comment by sedefsavas** [comment]
The fix for this issue (thanks to @vincepri for debugging) is a temporary fix, only solving the CRS issue. 
Right now we do not use much live clients, but if we do a Get() and try to do a Patch() with a live client, we may hit the same issue.
