### ISSUE TITLE
Generate initial scaffolding for the operator

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#4118]
**User Story**

As a CAPI developer, I would like to create a space for building the operator.

**Detailed Description**

This PR adds the initial bare bones scaffolding for the CAPI operator.
```bash
kubebuilder init --domain operator.cluster.x-k8s.io
# Created Resource and Controller
kubebuilder create api --group operator --version v1alpha4 --kind CoreProvider
# Created Resources and no Controllers for each of the following 
# since we are going to have a single controller reconciler for all the resources.
kubebuilder create api --group operator --version v1alpha4 --kind BootstrapProvider
kubebuilder create api --group operator --version v1alpha4 --kind ControlPlaneProvider
kubebuilder create api --group operator --version v1alpha4 --kind InfrastructureProvider
```
**Anything else you would like to add:**

- The API will be incrementally added in.
- `make` commands coming in a separate PR.
- `Dockerfile` updates in a separate PR.

/kind feature
/area operator
/area api

**Comment by alexander-demichev** [comment]
/close
Fixed by https://github.com/kubernetes-sigs/cluster-api/pull/4117
