### ISSUE TITLE
Backport clusterctl describe documentation

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4120]
https://github.com/kubernetes-sigs/cluster-api/pull/4092 implemented documentation for the new clusterctl describe command.
We should backport this documentation in the release 0-3 branch

/kind documentation

/help
/good-first-issue

**Comment by furkatgofurov7** [comment]
@fabriziopandini I would like to send a patch for this. 

/assign

**Comment by fabriziopandini** [comment]
/close
(pr is merged)
