### ISSUE TITLE
Create make commands for the operator

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#4122]
**User Story**

As a CAPI developer, I would like to have convenient make commands to build the operator, generate manifests, and build docker images.

**Detailed Description**
Some of the commands are below but not limited to
```
# Build the binary 
make operator 
# Generate go related go
make generate-go-operator
# Generate manifests for the operator
make generate-operator-manifests
# Build and push docker images
make docker-build-operator
make docker-push-operator-manifest

# Modify the following
make release
make release-manifests
```

/kind feature
/area api
/area operator

**Comment by fabriziopandini** [comment]
What about modifying also `make generate-go` and `make generate-manifests`

**Comment by wfernandes** [comment]
Yup...Doing that as well. 🙂  Forgot to put that in. Thanks for calling it out though

**Comment by alexander-demichev** [comment]
/close 
Fixed by https://github.com/kubernetes-sigs/cluster-api/pull/4126
