### ISSUE TITLE
Document MachineHealthChecks for control planes

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api#4138]
Since #3956 merged, KCP supports remediation with machine health checks. However, the documentation on the topic is missing. In fact, the current MHC docs state:

> Control Plane Machines are currently not supported and will not be remediated if they are unhealthy

https://cluster-api.sigs.k8s.io/tasks/healthcheck.html#limitations-and-caveats-of-a-machinehealthcheck

We should update the existing documentation for MachineHealthChecks to include KCP.

/kind documentation

**Comment by CecileRobertMichon** [comment]
https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20191017-kubeadm-based-control-plane.md#remediation-using-delete-and-recreate can be used as a starting point

**Comment by scottslowe** [comment]
@CecileRobertMichon I'd like to work on this. Aside from removing the text indicating that MHC doesn't apply to KCP, what other changes do you feel are necessary?

**Comment by CecileRobertMichon** [comment]
@scottslowe awesome, thank you. I think in addition to removing the text of the limitation, it would be good to add an example of how to set it up for KCP in https://cluster-api.sigs.k8s.io/tasks/healthcheck.html#creating-a-machinehealthcheck. You can use https://github.com/kubernetes-sigs/cluster-api/blob/master/test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-kcp-remediation/mhc.yaml as an example.

**Comment by scottslowe** [comment]
@CecileRobertMichon In the "Limitations and Caveats" section of the current doc, there is a bullet that says "If no Node joins the cluster for a Node after the `NodeStartupTimeout`, the Machine will be remediated"

Should this be "If no Node joins the cluster for a Machine...", or "If no Machine joins the cluster for a Node..."? The current wording seems off.

**Comment by CecileRobertMichon** [comment]
yeah I think it should be "If no Node joins the cluster for a Machine..."

**Comment by scottslowe** [comment]
PR submitted and ready for review!
