### ISSUE TITLE
Document a guide to management cluster security

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#4139]
**What steps did you take and what happened:**
In v1alpha4 the recommend model fo multi tenancy is single controller for providers https://github.com/kubernetes-sigs/cluster-api/pull/4074.

With this model it might be the case where scalable resources and so machines for different clusters live in the same namespace. In such scenario the autoscaler would be watching nodes for the targeted cluster but would watch scalable resources for not only that cluster.

**What did you expect to happen:**
We should re evaluate the recommended multi tenancy model and document any caveats and recommended namespace topology when using autoscaling.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by enxebre** [comment]
cc @randomvariable @fabriziopandini @JoelSpeed @elmiko

**Comment by vincepri** [comment]
/kind documentation

Given the issue description seems to be referencing that an approach needs to be documented.

Is the main issue around credential management?

**Comment by randomvariable** [comment]
I'm hoping it's mostly we do some documentation about how namespaces are your security boundary in the management cluster, but will be meeting with @enxebre and @elmiko on Friday to get a better understanding, as I'm admittedly not up to speed on how the autoscaler integration was done.

**Comment by fabriziopandini** [comment]
happy to join the meeting if possible

**Comment by JoelSpeed** [comment]
I think @detiber might want to weigh in on this conversation as well. IIUC the [autodiscovery logic](https://github.com/kubernetes/autoscaler/pull/3314) that he added to the autoscaler should cater towards this at least partially?

**Comment by elmiko** [comment]
i have a feeling the conversation this friday will be very high level, but i'm glad you brought up the autodiscovery stuff @JoelSpeed. i think you are correct that it could help for the multi-tenancy issue.

**Comment by randomvariable** [comment]
/retitle Document a guide to management cluster security

Follow up from today's call:

@randomvariable  to write a doc on management cluster security as a whole, what are the security boundaries, and what does it mean to deploy multiple clusters in a single namespace.

@elmiko to contribute `includes` for Cluster Autoscaler docs in the CAPI book.

/assign

**Comment by elmiko** [comment]
added https://github.com/kubernetes-sigs/cluster-api/pull/4153
