### ISSUE TITLE
Updates to underlying configRef and infrastructureRef objects trigger MachineDeployment roll

### ISSUE THREAD

**Issue by wcurry** [kubernetes-sigs/cluster-api#4145]
**User Story**

As a CAPI operator I would like changes to my MachineDeployment's configRef (KubeadmConfigTemplate) and infrastructureRef (VSphereMachineTemplate) to trigger a Machine roll.

**Detailed Description**

We have a workaround in our pipeline that appends the MD5 hash of the Template's spec field to its name and updates the MachineDeployment reference. This process currently leaves behind orphaned objects when the Templates are updated.

/kind feature

**Comment by vincepri** [comment]
Hi @wcurry, 

MachineDeployment template references should be able to be changed, and the change should rollout a new MachineSet with the specified spec.

In order to support rollback scenarios, we usually consider the contents of a template reference immutable.  @detiber might be able to shed more light here as well.

**Comment by wcurry** [comment]
We generally fix forward, and would benefit from the templates being considered mutable.

They are actually mutable currently, but it doesn't trigger a roll. I just edited my KubeadmConfigTemplate and added a command to the postKubeadmCommands without error.

**Comment by sbueringer** [comment]
The current situation seems to be:
> These MachineTemplate resources should be immutable, unless the infrastructure provider documentation indicates otherwise > for certain fields (see below for more details).
> Some infrastructure providers may, at their discretion, choose to support in-place modifications of certain infrastructure machine template fields. This may be useful if an infrastructure provider is able to make changes to running instances/machines, such as updating allocated memory or CPU capacity. In such cases, however, Cluster API will not trigger a rolling update.
> https://cluster-api.sigs.k8s.io/tasks/change-machine-template.html

As more and more providers implement webhooks to enforce machine template immutability, I'm not sure what we should do with this issue:
* https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1255
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/858


Is it basically about if we want to reconsider the current decision? (I assume we don't want to do that)
