### ISSUE TITLE
How to add label on the worker nodes on the fly?

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#4147]
**User Story**

As a [developer/user/operator] I would like to [high level description] for [reasons]

https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/user/troubleshooting.md
told us that the only way is to execute this on the command line

```
kubectl get nodes --no-headers -l '!node-role.kubernetes.io/master' -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}' | xargs -I{} kubectl label node {} node-role.kubernetes.io/worker=''
```

but how about autoscale? if we use autoscale to increase worker nodes, how to add those labels when workers added ? 

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
Linking other thread/issue related to label management
- https://github.com/kubernetes-sigs/cluster-api/pull/3668#issuecomment-696101159
- https://github.com/kubernetes-sigs/cluster-api/issues/493 (https://github.com/kubernetes-sigs/cluster-api/issues/2596)

**Comment by jichenjc** [comment]
ok I will read this and may close this issue , thanks
