### ISSUE TITLE
Add v1alpha4 types for clusterctl

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4154]
We should add v1alpha4 types for clustertcl!

/area clusterctl
/kind api-change
/kind feature

/milestone v0.4.0
/prority important-soon
/assign 
/lifecycle active

**Comment by CecileRobertMichon** [comment]
@fabriziopandini is this release blocking for v0.4.0?

**Comment by fabriziopandini** [comment]
No, it is not.
> After some discussion, we are considering to keep clusterctl owned types on v1alpha3 version and wait for the CAPI operator to provide a clean upgrade path (with a conversion web hook)

Also migration is tracked in https://github.com/kubernetes-sigs/cluster-api/issues/4201, so let's close this one 
/close
