### ISSUE TITLE
clusterctl init fails 

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#4156]
**What steps did you take and what happened:**
1. Pull code from main branch
2. `make clusterctl`
3. `clusterctl init`

I get the following output: 
```
$ clusterctl init
Using configuration File="/Users/wfernandes/.cluster-api/clusterctl.yaml"
Fetching providers
Fetching File="core-components.yaml" Provider="cluster-api" Type="CoreProvider" Version="v0.3.14"
Fetching File="bootstrap-components.yaml" Provider="kubeadm" Type="BootstrapProvider" Version="v0.3.14"
Fetching File="control-plane-components.yaml" Provider="kubeadm" Type="ControlPlaneProvider" Version="v0.3.14"
Fetching File="metadata.yaml" Provider="cluster-api" Type="CoreProvider" Version="v0.3.14"
Error: failed to read "metadata.yaml" from the repository for provider "cluster-api": failed to download files from GitHub release v0.3.14: failed to get file "metadata.yaml" from "v0.3.14" release
sigs.k8s.io/cluster-api/cmd/clusterctl/client/repository.(*metadataClient).Get
        /Users/wfernandes/workspace/cluster-api/cmd/clusterctl/client/repository/metadata_client.go:77
sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster.(*providerInstaller).getProviderContract
        /Users/wfernandes/workspace/cluster-api/cmd/clusterctl/client/cluster/installer.go:231
sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster.(*providerInstaller).Validate
        /Users/wfernandes/workspace/cluster-api/cmd/clusterctl/client/cluster/installer.go:194
sigs.k8s.io/cluster-api/cmd/clusterctl/client.(*clusterctlClient).Init
        /Users/wfernandes/workspace/cluster-api/cmd/clusterctl/client/init.go:103
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.runInit
        /Users/wfernandes/workspace/cluster-api/cmd/clusterctl/cmd/init.go:146
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.glob..func8
        /Users/wfernandes/workspace/cluster-api/cmd/clusterctl/cmd/init.go:88
github.com/spf13/cobra.(*Command).execute
        /Users/wfernandes/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
        /Users/wfernandes/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
        /Users/wfernandes/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.Execute
        /Users/wfernandes/workspace/cluster-api/cmd/clusterctl/cmd/root.go:91
main.main
        /Users/wfernandes/workspace/cluster-api/cmd/clusterctl/main.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
```

**What did you expect to happen:**
I expected init to work.

**Anything else you would like to add:**
There is no `metadata` for the `cluster-api` provider. So that doesn't look correct.

```bash
$ clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.10-367-886a16731f90a7", GitCommit:"886a16731f90a7662ec1ce40d9b17cef06b28003", GitTreeState:"clean", BuildDate:"2021-02-08T21:26:46Z", GoVersion:"go1.14.12", Compiler:"gc", Platform:"darwin/amd64"}
Using configuration File="/Users/wfernandes/.cluster-api/clusterctl.yaml"

New clusterctl version available: v0.3.10-367-886a16731f90a7 -> v0.3.14
https://github.com/kubernetes-sigs/cluster-api/releases/tag/v0.3.14
```

**Environment:**

- Cluster-api version: 886a16731f90a7662ec1ce40d9b17cef06b28003
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
/area clusterctl

**Comment by wfernandes** [comment]
It seems that when we removed the embedded metadata (https://github.com/kubernetes-sigs/cluster-api/pull/4033) we also had an embedded metadata for the ClusterAPI CoreProvider.

https://github.com/kubernetes-sigs/cluster-api/commit/e4b5725c2b2a0175b2a6c8ed317877aeec3b7e7e#diff-50f77670b27925f39bc2bb45856ec9139db13aaa1bf9f061011f4e9e1a6301a3L112-L130

**Comment by wfernandes** [comment]
Here are some possible solutions:
1. We can include a `metadata.yaml` as part of the release assets for Cluster API releases.
2. We can have an embedded metadata just for the CoreProvider artifacts - CoreProvider, KubeadmBootstrapProvider, KubeadmControlPlaneProvider.

@fabriziopandini @vincepri WDYT?

**Comment by fabriziopandini** [comment]
I'm +1 for embedding metadata.yml in the Cluster API release asset for consistency with the providers

Also, now that more changes are merging, I do expect that clusterctl on main branch will stop to being able to install v0.3.x release versions, but this is ok because clusterctl on should work with v0.4.0 and only allow updates from v0.3.x

**Comment by vincepri** [comment]
> I do expect that clusterctl on main branch will stop to being able to install v0.3.x release versions

Let's add a check and return an error.

**Comment by wfernandes** [comment]
👍🏽  There's already a check in place that returns the error `failed to get file "metadata.yaml" from "v0.3.14" release`. If this is expected behavior, I'll close out the PR and this issue.

**Comment by wfernandes** [comment]
Since we'll be including metadata.yaml in the CAPI release assets moving forward and clusterctl v1alpha4 doesn't support installing v1alpha3 releases, I'm going to close this issue.
/close

**Comment by vincepri** [comment]
It'd be great to say "this version isn't supported with this CLI"

**Comment by vincepri** [comment]
The error above is a bit cryptic

**Comment by wfernandes** [comment]
Actually, I'll make a PR that includes a metadata.yaml file as part of the `make release-manifests` command in the out directory or any other Makefile commands that's used to generate the release assets.
/reopen

**Comment by wfernandes** [comment]
> It'd be great to say "this version isn't supported with this CLI"

 This could be done, if the CLI knew that it was a v0.4.x version. However, until we cut a tag for that the CLI will not reflect it. Also, currently if we `make clusterctl` from the main branch the GitVersion is stuck from `v0.3.10-xxx-xxx` because of some git rebase in the past.
And I'd like to avoid specifically checking if the provider versions is v0.3.x since it feels like it's hardcoding specific behavior into the v1alpha4 CLI.

For now to get this issue resolved, I'll include the metadata.yaml in CAPI releases.

**Comment by fabriziopandini** [comment]
> It'd be great to say "this version isn't supported with this CLI"

On my todo:
- clusterctl v1alpha3 should not install v1alpha4 providers/should not work on v1alpha4 cluster
- clusterctl v1alpha4 should not install v1alpha3 providers/should not work on v1alpha3 cluster (except for upgrade)
