### ISSUE TITLE
Please create new repository - kubernetes-sigs/cluster-provider-api-openstack

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/cluster-api#416]
Instead of merging the https://github.com/kubernetes-sigs/cluster-api/pull/176 PR, can we please create a new repository?

Based on the discussion in https://github.com/kubernetes-sigs/cluster-api/issues/383 please create the repository under

```
github.com/kubernetes-sigs/cluster-api-provider-openstack
```

Please seed this new empty repository from the following:
https://github.com/dims/cluster-provider-api-openstack

It has the same code as in the PR 176, reorganized just a little bit. plus a make file.

Thanks!

**Comment by dims** [comment]
cc @Lion-Wei

**Comment by kris-nova** [comment]
Watching this

**Comment by kris-nova** [comment]
@timothysc any idea how we should request a new repo?

**Comment by Lion-Wei** [comment]
@dims Thanks. 
I think we need create another pr for openstack cloud provider in clusterctl, like azure did. 
https://github.com/kubernetes-sigs/cluster-api/pull/395

**Comment by dims** [comment]
@Lion-Wei sure, please go ahead with a patch similar to #395 Though note that it has a url for the git repo so we probably need to wait for `github.com/kubernetes-sigs/cluster-api-provider-openstack` to get created.

**Comment by m1093782566** [comment]
Sounds fair, @dims 

We can wait unitl the new repo get created.

**Comment by dims** [comment]
Sent an email to steering committee based on suggestion by @jdumars - https://groups.google.com/a/kubernetes.io/d/msg/steering/IY5zSWnp1aI/RMJoUA2fBgAJ

**Comment by dims** [comment]
cc @dklyle @hogepodge @rjmorse

**Comment by hogepodge** [comment]
+1 from sig-openstack

**Comment by hogepodge** [comment]
cc @andrewsykim @jagosan

This is related to SIG-Cloud-Provider efforts, and other providers should be made aware of these efforts.

**Comment by dims** [comment]
We now have https://github.com/kubernetes-sigs/cluster-api-provider-openstack. thanks a bunch everyone
