### ISSUE TITLE
Install CSI driver by default in preparation of CSI Migration

### ISSUE THREAD

**Issue by Jiawei0227** [kubernetes-sigs/cluster-api#4166]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

CSI Migration is a Kubernetes feature that when turn on, it will redirect in-tree plugin traffic to the corresponding CSI driver. It has been Beta in k8s since v1.17 without turning on by default.

Recently, we decide to push this feature forward and it will be turn on by default in v1.22 for a lot of plugins according to our [plan]((https://docs.google.com/document/d/1j6uF9sOoGCQ9nNFVrdvCWyn77o9k3-758qsEj2K3BAY/edit)).

It would be good if cluster-api can prepare for this upcoming change. Specifically, cluster-api should deploy the corresponding CSI drivers by default for the corresponding cloud. The driver is a requisite for CSI migration to work.

- GCP - GCE PD CSI Driver
- AWS - AWS EBS CSI Driver
- Azure - Azuredisk/Azurefile CSI Driver

**2. Background**

- [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/625-csi-migration/README.md)
- [Tracking Issues](https://github.com/kubernetes/enhancements/issues?q=is%3Aissue+is%3Aopen+csi+migration)
- [Original design doc](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/csi-migration.md)
- [Public documentation](https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-csi-migration-beta/)
- [CSI Migration meeting doc](https://docs.google.com/document/d/1j6uF9sOoGCQ9nNFVrdvCWyn77o9k3-758qsEj2K3BAY/edit)

/kind feature
/cc @msau42

**Comment by fabriziopandini** [comment]
@CecileRobertMichon @nader-ziada @randomvariable @yastij 

setting milestone v0.4.0/important soon for now, but probably this should be discussed at the CAPI meeting
/milestone v0.4.0
/priority important-soon
/area

**Comment by fabriziopandini** [comment]
Might be we should raise priority on this topic:

@CecileRobertMichon @nader-ziada @randomvariable @yastij @gab-satchi 
opinions?

**Comment by randomvariable** [comment]
AWS issue is here https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1475 with corresponding PR for e2e.

**Comment by sbueringer** [comment]
@fabriziopandini I'm wondering if we have the same issue with ccm (not sure when the internal cloud provider is removed though)

**Comment by vincepri** [comment]
Are there any action items to follow up here?

**Comment by vincepri** [comment]
@yastij @randomvariable @CecileRobertMichon

**Comment by vincepri** [comment]
- Changes are required starting from Kubernetes 1.23(-ish)
- How do we install (and lifecycle manage?) these types of addons? Should we look at the addons project, what about ClusterResourceSet?
- How do we upgrade current users?

One short term solution is to include the CRS manifests as part of provider infrastructure template.

**Comment by vincepri** [comment]
/assign @CecileRobertMichon @yastij 
to collaborate on goals/non-goals/requirements

**Comment by CecileRobertMichon** [comment]
note: take a look at issue on runtime extensions

**Comment by neolit123** [comment]
kops tracking issue:
https://github.com/kubernetes/kops/issues/10777

might be worth getting some feedback from them on a zoom call.

**Comment by CecileRobertMichon** [comment]
@andyzhangx @feiskyer to help answer these questions for Azure CSI drivers and Azure CCM

**Comment by fabriziopandini** [comment]
/triage accepted

@CecileRobertMichon @yastij PTAL and update

**Comment by dtzar** [comment]
This is an important one to implement. Perhaps we can discuss where this is at on next CAPI call?

**Comment by fabriziopandini** [comment]
/triage accepted

@CecileRobertMichon @yastij PTAL and update

**Comment by CecileRobertMichon** [comment]
I don't think there is anything in scope for CAPI itself here, CAPI can't "install" CSI drivers by default since those are provider specific. It's similar to CNI and CPI/CCM/CNM (Cloud Controller Manager for out of tree cloud provider). These should be installed just like other critical cluster addons (maybe that's where https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm can help) and up to each provider to have docs/reference templates (eg. https://capz.sigs.k8s.io/topics/addons.html#storage-drivers). 

Not sure there's much more we can do here @fabriziopandini, not without adding a way for providers to hook into CAPI to provider provider-specific instructions (is that something runtimeExtensions could help with?)

**Comment by fabriziopandini** [comment]
/close

Based on the fact that there is not much to do in core CAPI.
The CAPI office hours, where we are already giving room for updates to CAAPH and providers, could be the avenue to carry on this discussion; I will add a point to the next office hours agenda
