### ISSUE TITLE
remove DNS Type field from DNS spec

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api#4177]
**User Story**

#2083 was created to make kcp spec fully mutable. But, since it's difficult to track every spec mutation in a single pr, we wanted to start with a few specs that were important, and move from there. As part of #3994 , the following specs in kcp were made mutable:
- APIServer
- ControllerManager
- Scheduler

This story aims to track the `DNS` settings in KCP

**Detailed Description**

Make `DNS` in  KubeadmControlPlane mutable

**Anything else you would like to add:**

`v1beta1` in kubeadm has now been deprecated, so we need to keep that in mind when implementing this.

/kind feature

**Comment by fabriziopandini** [comment]
AFAIK currently Cluster API/kubeadm only support CoreDNS, so I'm not really sure what are the expectation here..

**Comment by vincepri** [comment]
We probably we'll want to remove the option to switch between dns providers, and force CoreDNS (like we do today)

**Comment by vincepri** [comment]
/milestone v0.4.0
/assign @shysank 
Let's remove the option to pick a dns provider in v0.4.0?

**Comment by fabriziopandini** [comment]
Agree, this should wait for kubeadm API conversions to be implemented first

**Comment by CecileRobertMichon** [comment]
What is the action item here? Is it release blocking?

**Comment by fabriziopandini** [comment]
> What is the action item here?

Let's remove the option to pick a dns provider in v0.4.0?

> Is it release blocking?

Probably not, but being an API braking change it is now or in the next API version...

**Comment by fabriziopandini** [comment]
might be I'm wrong, but I think that what @vincepri is suggesting is to remove the field from v1alpha4 types so we are preventing errors during cluster creation as well

**Comment by sbueringer** [comment]
Would also be consistent with our doc: https://github.com/kubernetes-sigs/cluster-api/pull/4402/files

> KubeadmControlPlane is solely supporting CoreDNS as a DNS server at this time.

**Comment by CecileRobertMichon** [comment]
IMO even if only CoreDNS is supported we should still support changing the image repo/tag for dns spec to allow testing CoreDNS itself and/or allow users to use CoreDNS images in different registries. I think a warning in the doc is enough, there isn't a good way to enforce this beyond that without breaking image configuration AFAIK.

**Comment by sbueringer** [comment]
I think we were only talking about droppin the `DNSAddOnType` field of the DNS struct not the whole `DNS` field:
```go
// DNS defines the DNS addon that should be used in the cluster
type DNS struct {
	// Type defines the DNS add-on to be used
	// +optional
	Type DNSAddOnType `json:"type,omitempty"`

	// ImageMeta allows to customize the image used for the DNS component
	ImageMeta `json:",inline"`
}
```

**Comment by vincepri** [comment]
> IMO even if only CoreDNS is supported we should still support changing the image repo/tag for dns spec to allow testing CoreDNS itself and/or allow users to use CoreDNS images in different registries. I

+1 to this for sure, and to remove the field like `Type` field as @sbueringer suggested.

**Comment by CecileRobertMichon** [comment]
Okay great, that clarifies it.

/kind release-blocking
/retitle remove DNS Type field from DNS spec
/help

**Comment by fabriziopandini** [comment]
@shysank are you working on this? otherwise @ludusrusso is interested in giving a try to this...

**Comment by shysank** [comment]
I just started but haven't gotten much far. I'm fine with @ludusrusso taking it. I'll unassign myself.

**Comment by ludusrusso** [comment]
Thanks @shysank :D

/assign

**Comment by ludusrusso** [comment]
Hi!
With this change we need to handle the case of an user that is currently using v1alpha3 with dns.type != from CoreDNS.

https://github.com/kubernetes-sigs/cluster-api/blob/1b4faf5d6282bfdd0fac543c798238fe2c9a6046/controlplane/kubeadm/internal/workload_cluster_coredns.go#L90-L92

Current implementation raises error (I think) when dns.type is different from coreDNS, but if we remove the type field, than we make the assumption it is using coreDNS and could break the cluster of some user without raising a clear error.

How should we handle this?

**Comment by fabriziopandini** [comment]
@ludusrusso 
Thanks for pointing this out.

So, I investigate the issue a little bit and

1. Using cluster API v1alpha3 & kubernetes < v1.21 it is possible to spin up a cluster with kube-dns and then execute control plane upgrades using the `controlplane.cluster.x-k8s.io/skip-coredns` annotation.
2. Starting from kubernetes >= v1.21 does not support anymore Kubeadm-dns.

By removing the  clusterConfig.DNS.Type field in v1alpha4
a. we are not going to create problem to existing cluster running with core-dns, given that the only thing that is required to manage such clusters is `controlplane.cluster.x-k8s.io/skip-coredns` annotation
b. We are preventing users to create new clusters with kube-DNS, no matter if the Kubernetes/kubeadm version still support this feature or not

Given what I see in the kubeadm channel I don't see b. as a blocker, on the contrary, I like the idea of removing some edge case variants from the table.

However, I think we should ask to the community if it is ok to prevent users to create new clusters with kube-DNS, no matter if the Kubernetes/kubeadm version still support this feature or not. 

@vincepri @ludusrusso is it ok this for you?
@ludusrusso in case there is agree, do you want to raise this point at the next office hours? (otherwise I can take care of this)

**Comment by ludusrusso** [comment]
> @ludusrusso
> Thanks for pointing this out.
> 
> So, I investigate the issue a little bit and
> 
> 1. Using cluster API v1alpha3 & kubernetes < v1.21 it is possible to spin up a cluster with kube-dns and then execute control plane upgrades using the `controlplane.cluster.x-k8s.io/skip-coredns` annotation.
> 2. Starting from kubernetes >= v1.21 does not support anymore Kubeadm-dns.
> 
> By removing the clusterConfig.DNS.Type field in v1alpha4
> a. we are not going to create problem to existing cluster running with kube-dns, given that the only thing that is required to manage such clusters is `controlplane.cluster.x-k8s.io/skip-coredns` annotation
> b. We are preventing users to create new clusters with kube-dns, no matter if the Kubernetes/kubeadm version still support this feature or not
> 
> Given what I see in the kubeadm channel I don't see b. as a blocker, on the contrary, I like the idea of removing some edge case variants from the table.
> 
> However, I think we should ask to the community if it is ok to prevent users to create new clusters with kube-dns, no matter if the Kubernetes/kubeadm version still support this feature or not.
> 
> @vincepri @ludusrusso is it ok this for you?

Ok for me

> @ludusrusso in case there is agree, do you want to raise this point at the next office hours? (otherwise I can take care of this)

Yep, first time that I partecipate to a SIG Meeting :D
