### ISSUE TITLE
CertificatesDir in KubeadmControlPlane Spec should be mutable 

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api#4179]
**User Story**

#2083 was created to make kcp spec fully mutable. But, since it's difficult to track every spec mutation in a single pr, we wanted to start with a few specs that were important, and move from there. As part of #3994 , the following specs in kcp were made mutable:
- APIServer
- ControllerManager
- Scheduler

This story aims to track the `CertificatesDir` settings in KCP

**Detailed Description**

Make `CertificatesDir` spec in  KubeadmControlPlane mutable

**Anything else you would like to add:**

`v1beta1` in kubeadm has now been deprecated, so we need to keep that in mind when implementing this.

/kind feature

**Comment by fabriziopandini** [comment]
I would like to better understand the use case for making this mutable because it would be nice if we can keep this consistent in a cluster so it will be easier to support certificate rotation (with an external tool for now, might be in the future in CAPI or with the kubeadm-operator).

**Comment by fabriziopandini** [comment]
/milestone v0.4.0
/priority backlog
We can eventually punt later if there is a concrete use case for this.

**Comment by vincepri** [comment]
@shysank Do you have more details on the request above? Are there any use cases you had in mind?

**Comment by shysank** [comment]
I don't have any particular use case for this. I opened it as part of tracking all the immutable fields in kcp spec. I'm fine with closing it since there seems to be no immediate use case for this.
