### ISSUE TITLE
Installation fails: "the server could not find the requested resource"

### ISSUE THREAD

**Issue by craigbox** [kubernetes-sigs/cluster-api#418]
Generated YAML with generate-yaml.sh; machine accounts were created successfully in my GCP project.

<pre><b>export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/machine-controller-serviceaccount.json"
$GOPATH/src/sigs.k8s.io/cluster-api/clusterctl/clusterctl create cluster --provider google -c cluster.yaml -m machines.yaml -p provider-components.yaml -a addons.yaml --v=9</b>

I0707 16:45:42.817275   54909 clusterdeployer.go:115] Creating external cluster
I0707 16:45:42.817863   54909 minikube.go:46] Running: minikube [start --bootstrapper=kubeadm]
I0707 16:48:11.962869   54909 minikube.go:50] Ran: minikube [start --bootstrapper=kubeadm] Output: Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
I0707 16:48:11.974580   54909 loader.go:357] Config loaded from file /var/folders/nn/6bcypbkx16b0_45yhpv_yw3m0072tf/T/439216440
I0707 16:48:11.981297   54909 clusterdeployer.go:128] Applying Cluster API stack to external cluster
I0707 16:48:11.981320   54909 clusterdeployer.go:279] Applying Cluster API APIServer
I0707 16:48:12.469486   54909 clusterclient.go:381] Waiting for kubectl apply...
I0707 16:48:14.025886   54909 clusterdeployer.go:204] Cleaning up external cluster.
I0707 16:48:14.025938   54909 minikube.go:46] Running: minikube [delete]
I0707 16:48:15.638075   54909 minikube.go:50] Ran: minikube [delete] Output: Deleting local Kubernetes cluster...
Machine deleted.
F0707 16:48:15.639252   54909 create_cluster.go:63] unable to apply cluster api stack to external cluster: unable to apply cluster apiserver: unable to apply apiserver yaml: couldn't kubectl apply: exit status 1, output: apiservice.apiregistration.k8s.io/v1alpha1.cluster.k8s.io created
service/clusterapi created
deployment.apps/clusterapi-apiserver created
statefulset.apps/etcd-clusterapi created
service/etcd-clusterapi-svc created
secret/cluster-apiserver-certs created
Error from server (NotFound): error when creating "STDIN": the server could not find the requested resource
</pre>

If we don't delete the cluster, we can see a pod didn't create:

<pre>
$ kubectl get all
NAME                                        READY     STATUS    RESTARTS   AGE
pod/clusterapi-apiserver-7787d8f7cf-gtz2h   0/1       Error     2          1m

$ kubectl logs pod/clusterapi-apiserver-7787d8f7cf-gtz2h
ERROR: logging before flag.Parse: W0707 16:25:03.424813       1 authentication.go:229] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLE_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
Error: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:default:default" cannot get configmaps in the namespace "kube-system"
Usage:
   [flags]

Flags:
      --audit-log-format string                                 Format of saved audits. "legacy" indicates 1-line text format for each event. "json" indicates structured json format. Requires the 'AdvancedAuditing' feature gate. Known formats are legacy,json. (default "json")
      --audit-log-maxage int                                    The maximum number of days to retain old audit log files based on the timestamp encoded in their filename.
      --audit-log-maxbackup int                                 The maximum number of old audit log files to retain.
      --audit-log-maxsize int                                   The maximum size in megabytes of the audit log file before it gets rotated.
      --audit-log-path string                                   If set, all requests coming to the apiserver will be logged to this file.  '-' means standard out.
      --audit-policy-file string                                Path to the file that defines the audit policy configuration. Requires the 'AdvancedAuditing' feature gate. With AdvancedAuditing, a profile is required to enable auditing.
      --audit-webhook-batch-buffer-size int                     The size of the buffer to store events before batching and sending to the webhook. Only used in batch mode. (default 10000)
      --audit-webhook-batch-initial-backoff duration            The amount of time to wait before retrying the first failed requests. Only used in batch mode. (default 10s)
      --audit-webhook-batch-max-size int                        The maximum size of a batch sent to the webhook. Only used in batch mode. (default 400)
      --audit-webhook-batch-max-wait duration                   The amount of time to wait before force sending the batch that hadn't reached the max size. Only used in batch mode. (default 30s)
      --audit-webhook-batch-throttle-burst int                  Maximum number of requests sent at the same moment if ThrottleQPS was not utilized before. Only used in batch mode. (default 15)
      --audit-webhook-batch-throttle-qps float32                Maximum average number of requests per second. Only used in batch mode. (default 10)
      --audit-webhook-config-file string                        Path to a kubeconfig formatted file that defines the audit webhook configuration. Requires the 'AdvancedAuditing' feature gate.
      --audit-webhook-mode string                               Strategy for sending audit events. Blocking indicates sending events should block server responses. Batch causes the webhook to buffer and send events asynchronously. Known modes are batch,blocking. (default "batch")
      --authentication-kubeconfig string                        kubeconfig file pointing at the 'core' kubernetes server with enough rights to create tokenaccessreviews.authentication.k8s.io.
      --authentication-skip-lookup                              If false, the authentication-kubeconfig will be used to lookup missing authentication configuration from the cluster.
      --authentication-token-webhook-cache-ttl duration         The duration to cache responses from the webhook token authenticator. (default 10s)
      --authorization-kubeconfig string                         kubeconfig file pointing at the 'core' kubernetes server with enough rights to create  subjectaccessreviews.authorization.k8s.io.
      --authorization-webhook-cache-authorized-ttl duration     The duration to cache 'authorized' responses from the webhook authorizer. (default 10s)
      --authorization-webhook-cache-unauthorized-ttl duration   The duration to cache 'unauthorized' responses from the webhook authorizer. (default 10s)
      --bind-address ip                                         The IP address on which to listen for the --secure-port port. The associated interface(s) must be reachable by the rest of the cluster, and by CLI/web clients. If blank, all interfaces will be used (0.0.0.0). (default 0.0.0.0)
      --cert-dir string                                         The directory where the TLS certs are located. If --tls-cert-file and --tls-private-key-file are provided, this flag will be ignored. (default "apiserver.local.config/certificates")
      --client-ca-file string                                   If set, any request presenting a client certificate signed by one of the authorities in the client-ca-file is authenticated with an identity corresponding to the CommonName of the client certificate.
      --contention-profiling                                    Enable lock contention profiling, if profiling is enabled
      --default-watch-cache-size int                            Default watch cache size. If zero, watch cache will be disabled for resources that do not have a default watch size set. (default 100)
      --delegated-auth                                          Setup delegated auth (default true)
      --delete-collection-workers int                           Number of workers spawned for DeleteCollection call. These are used to speed up namespace cleanup. (default 1)
      --deserialization-cache-size int                          Number of deserialized json objects to cache in memory.
      --enable-garbage-collector                                Enables the generic garbage collector. MUST be synced with the corresponding flag of the kube-controller-manager. (default true)
      --enable-swagger-ui                                       Enables swagger ui on the apiserver at /swagger-ui
      --etcd-cafile string                                      SSL Certificate Authority file used to secure etcd communication.
      --etcd-certfile string                                    SSL certification file used to secure etcd communication.
      --etcd-compaction-interval duration                       The interval of compaction requests. If 0, the compaction request from apiserver is disabled. (default 5m0s)
      --etcd-keyfile string                                     SSL key file used to secure etcd communication.
      --etcd-prefix string                                      The prefix to prepend to all resource paths in etcd. (default "/registry/k8s.io")
      --etcd-servers stringSlice                                List of etcd servers to connect with (scheme://ip:port), comma separated.
      --etcd-servers-overrides stringSlice                      Per-resource etcd servers overrides, comma separated. The individual override format: group/resource#servers, where servers are http://ip:port, semicolon separated.
      --experimental-encryption-provider-config string          The file containing configuration for encryption providers to be used for storing secrets in etcd
  -h, --help                                                    help for this command
      --kubeconfig string                                       kubeconfig file pointing at the 'core' kubernetes server.
      --log-flush-frequency duration                            Maximum number of seconds between log flushes (default 5s)
      --loglevel int32                                          Set the level of log output
      --print-bearer-token                                      Print a curl command with the bearer token to test the server
      --print-openapi                                           Print the openapi json and exit
      --profiling                                               Enable profiling via web interface host:port/debug/pprof/ (default true)
      --requestheader-allowed-names stringSlice                 List of client certificate common names to allow to provide usernames in headers specified by --requestheader-username-headers. If empty, any client certificate validated by the authorities in --requestheader-client-ca-file is allowed.
      --requestheader-client-ca-file string                     Root certificate bundle to use to verify client certificates on incoming requests before trusting usernames in headers specified by --requestheader-username-headers
      --requestheader-extra-headers-prefix stringSlice          List of request header prefixes to inspect. X-Remote-Extra- is suggested. (default [x-remote-extra-])
      --requestheader-group-headers stringSlice                 List of request headers to inspect for groups. X-Remote-Group is suggested. (default [x-remote-group])
      --requestheader-username-headers stringSlice              List of request headers to inspect for usernames. X-Remote-User is common. (default [x-remote-user])
      --secure-port int                                         The port on which to serve HTTPS with authentication and authorization. If 0, don't serve HTTPS at all. (default 443)
      --storage-backend string                                  The storage backend for persistence. Options: 'etcd3' (default), 'etcd2'.
      --storage-media-type string                               The media type to use to store objects in storage. Some resources or storage backends may only support a specific media type and will ignore this setting. (default "application/json")
      --tls-ca-file string                                      If set, this certificate authority will used for secure access from Admission Controllers. This must be a valid PEM-encoded CA bundle. Altneratively, the certificate authority can be appended to the certificate provided by --tls-cert-file.
      --tls-cert-file string                                    File containing the default x509 Certificate for HTTPS. (CA cert, if any, concatenated after server cert). If HTTPS serving is enabled, and --tls-cert-file and --tls-private-key-file are not provided, a self-signed certificate and key are generated for the public address and saved to the directory specified by --cert-dir.
      --tls-private-key-file string                             File containing the default x509 private key matching --tls-cert-file.
      --tls-sni-cert-key namedCertKey                           A pair of x509 certificate and private key file paths, optionally suffixed with a list of domain patterns which are fully qualified domain names, possibly with prefixed wildcard segments. If no domain patterns are provided, the names of the certificate are extracted. Non-wildcard matches trump over wildcard matches, explicit domain patterns trump over extracted names. For multiple key/certificate pairs, use the --tls-sni-cert-key multiple times. Examples: "example.crt,example.key" or "foo.crt,foo.key:*.foo.com,foo.com". (default [])
      --watch-cache                                             Enable watch caching in the apiserver (default true)
      --watch-cache-sizes stringSlice                           List of watch cache sizes for every resource (pods, nodes, etc.), comma separated. The individual override format: resource#size, where size is a number. It takes effect when watch-cache is enabled.

panic: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:default:default" cannot get configmaps in the namespace "kube-system"

goroutine 1 [running]:
sigs.k8s.io/cluster-api/vendor/github.com/kubernetes-incubator/apiserver-builder/pkg/cmd/server.StartApiServer(0x1a0b3b4, 0x10, 0xc42045aea0, 0x1, 0x1, 0x1aaa550, 0x19fbf6b, 0x3, 0x19fb981, 0x2)
	/go/src/sigs.k8s.io/cluster-api/vendor/github.com/kubernetes-incubator/apiserver-builder/pkg/cmd/server/start.go:79 +0x292
main.main()
	/go/src/sigs.k8s.io/cluster-api/cmd/apiserver/main.go:35 +0xba

</pre>

```
$ minikube version
minikube version: v0.28.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by craigbox** [comment]
Have narrowed down the problem to a missing version:

<pre>
<b>apiVersion: rbac.authorization.k8s.io/</b>
kind: RoleBinding
metadata:
  name: clusterapi
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
</pre>

**Comment by craigbox** [comment]
I can get the cluster installed if I patch the file to include the v1 at the end of that line.

I do get this output in my logs also, when it's creating the master components on the newly created cluster:

```I0707 18:00:31.526745   61559 clusterclient.go:390] Waiting for kubectl apply... api not yet available: couldn't kubectl apply: exit status 1, output: apiservice.apiregistration.k8s.io/v1alpha1.cluster.k8s.io created
service/clusterapi created
service/etcd-clusterapi-svc created
secret/cluster-apiserver-certs created
unable to recognize "STDIN": no matches for kind "Deployment" in version "apps/v1beta1"
unable to recognize "STDIN": no matches for kind "RoleBinding" in version "rbac.authorization.k8s.io/v1"
unable to recognize "STDIN": no matches for kind "StatefulSet" in version "apps/v1beta1"
```

**Comment by roberthbailey** [comment]
@craigbox - can you test this with `clusterctl` from https://github.com/kubernetes-sigs/cluster-api-provider-gcp and see if it is still an issue? https://github-issue-mover.appspot.com/ throws a NPE trying to move this issue over automatically, and if it's still something we should investigate, it should be filed there as it is a gcp-specific issue. Thanks!

/close
