### ISSUE TITLE
UseHyperKubeImage setting in KubeadmControlPlane Spec should be mutable 

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api#4181]
**User Story**

#2083 was created to make kcp spec fully mutable. But, since it's difficult to track every spec mutation in a single pr, we wanted to start with a few specs that were important, and move from there. As part of #3994 , the following specs in kcp were made mutable:
- APIServer
- ControllerManager
- Scheduler

This story aims to track the `UseHyperKubeImage` settings in KCP

**Detailed Description**

Make `UseHyperKubeImage` spec in  KubeadmControlPlane mutable

**Anything else you would like to add:**

`v1beta1` in kubeadm has now been deprecated, so we need to keep that in mind when implementing this.

/kind feature

**Comment by neolit123** [comment]
note that usage of hyperkube with kubeadm deprecated in 1.17.
probably a better idea to just leave this field without any special treatment on the CAP* side.

**Comment by vincepri** [comment]
We might want to remove this field from the v1alpha4 super-types cc @fabriziopandini

**Comment by fabriziopandini** [comment]
+1 for removal.

**Comment by fabriziopandini** [comment]
The field has been removed by https://github.com/kubernetes-sigs/cluster-api/pull/4545
