### ISSUE TITLE
Consider not using -v when running tests

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api#4182]
**What steps did you take and what happened:**
While developing (e.g. adding new feature or refactoring) and running unit tests, there is always very extensive output, which makes it hard to spot where the issue is, one must scroll trough all the output to find the error message.

**What did you expect to happen:**

Running `make test` should only produce logs for tests which failed.

**Anything else you would like to add:**
I suggest `-v` should be removed from `go test -v` command and if one needs it, it can be added on demand using `TEST_ARGS=-v`. If test fails, Go will print the output of failing test anyway.

As a workaround one can use `while make test TEST_ARGS='-count 1' ; do sleep 1; done`

**Environment:**

- Cluster-api version: bfc1498d363b90f8c695aca2ba4f19d57d60ceca
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
+1 with the suggestion.

We could also have a different make target `make test-verbose` if we want to facilitate

**Comment by invidian** [comment]
I saw that other CAPI providers also use `-v`. I wonder how the process looks like to roll that to other repositories as well.

**Comment by vincepri** [comment]
Issue + PRs, that should be enough, although we are not prescriptive for providers, maintainers there might prefer different approaches
