### ISSUE TITLE
Remove Cert-Manager Deployment from Developer Guide

### ISSUE THREAD

**Issue by enyinna1234** [kubernetes-sigs/cluster-api#4190]
**What steps did you take and what happened:**
The developer guide asks to deploy cert-manager here: https://cluster-api.sigs.k8s.io/developer/guide.html#cert-manager.
This doesn't appear to be necessary because 'Clusterctl init' seems to take care of installing cert-manager.

**What did you expect to happen:**
I did not expect to have cert manager already installed.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Should the cert-manager deployment part be taken out from the developer guide?
Or should it be marked as optional?

**Environment:**

- Cluster-api version: v0.3.12
- Minikube/KIND version: v0.9.0
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.5 LTS (Bionic Beaver)

/kind documentation
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by enyinna1234** [comment]
@fabriziopandini it's related to #4110 
If you assign it to me, I can fix it

**Comment by fabriziopandini** [comment]
@enyinna1234 I don't think the cert-manager installation step should be removed from this guide, but instead it could be useful to add the following notes in the cert-manager installation parragraph:

- cert-manager installation could be skipped if planning to use Kind (it is still required if you are planning to go for "the Old-fashioned way")
- the version of cert-manager should match the version used in the Cluster API version you are planning to test/develop.

/assign
/lifecycle active

**Comment by enyinna1234** [comment]
@fabriziopandini In the guide, for when cert-manager installation is needed, can we also point to the cert-manager install documentation instead of having install steps in the guide? In case the person needs to verify or troubleshoot.
Install documentation: https://docs.cert-manager.io/en/release-0.11/getting-started/install/kubernetes.html#

**Comment by fabriziopandini** [comment]
I think that this can be easily fixed by moving the https://cluster-api.sigs.k8s.io/developer/guide.html#cert-manager paragraph under the https://cluster-api.sigs.k8s.io/developer/guide.html#option-2-the-old-fashioned-way section, and adding a note the version of cert-manager should match the version used in the Cluster API version you are planning to test/develop.

/help
/good-first-issue
