### ISSUE TITLE
"tilt down" leaves orphan cert-manager namespace

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api#4193]
**What steps did you take and what happened:**
1. `tilt up`
2. `tilt down`

`cert-manager` namespace created by `tilt up` is not cleaned up by running `tilt down`. Note that other namespaces used by CAPI are being removed.

**What did you expect to happen:**
I'd expect all resources created by `tilt up` will get removed once `tilt down` is executed.

**Anything else you would like to add:**
It seems `tilt` on it's own will not remove K8s namespaces (https://github.com/tilt-dev/tilt/pull/3165).

Perhaps something like this can be used to finalize the cleanup:
```python
    if config.tilt_subcommand == "down":
        local("kubectl delete --ignore-not-found=true namespace cert-manager")
```

See also: https://docs.tilt.dev/api.html#modules.config.tilt_subcommand

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
/milestone v0.4.0
/priority backlog

Ideally, this should go in the tilt extension we are using for managing cert-manager...

**Comment by vincepri** [comment]
For development it's probably fine to clean up cert-manager, but what if cert-manager is being used for other things outside of Cluster API?

**Comment by fmuyassarov** [comment]
> For development it's probably fine to clean up cert-manager, but what if cert-manager is being used for other things outside of Cluster API?

Perhaps we could add a label to cert-manager namespace within tilt extension for the cert-manager, and add a command to remove the cert-manager namespace in CAPI Tiltfile if the cert-manager has the label.

**Comment by invidian** [comment]
>Perhaps we could add a label to cert-manager namespace within tilt extension for the cert-manager, and add a command to remove the cert-manager namespace in CAPI Tiltfile if the cert-manager has the label.

Hmm, actually CRDs should also be removed.

**Comment by fmuyassarov** [comment]
> > Perhaps we could add a label to cert-manager namespace within tilt extension for the cert-manager, and add a command to remove the cert-manager namespace in CAPI Tiltfile if the cert-manager has the label.
> 
> Hmm, actually CRDs should also be removed.

Maybe we could do 

```
local("kubectl delete namespace cert-manager")
local("kubectl delete -f https://github.com/jetstack/cert-manager/releases/download/1.16.1/cert-manager.yaml".format(version), quiet=silent, echo_off=silent)
```
The problem with this is that we will need to make sure that cert-manager version in CAPI Tiltfile is always in sync with version set in [tilt-extension](https://github.com/tilt-dev/tilt-extensions/blob/2d72dabfb798de90a2a7197dc7f98ff88822bd75/cert_manager/Tiltfile#L29).

**Comment by fmuyassarov** [comment]
Hi @fabriziopandini ,
Do you think labeling the cert-manager namespace in tilt-extensions would help us to differenciate if the cert-manager was created as part of the tilt, or by the user. This way, during `tilt down` we could maybe do `kubectl delete -f https:// ....cert-manager.yaml` if we see the label on the cert-manager namespace ?

**Comment by fabriziopandini** [comment]
assuming that tilt is used only with temporary dev clusters, TBH, I don't think we should worry too much about tilt leaving something behind.
Nevertheless, if you want to get this fixed, I'm ok with the simplest solution possible you can think of, but as I was suggesting above, this should be fixed first in https://github.com/tilt-dev/tilt-extensions/tree/master/cert_manager, then the cert-manager extension should be upgraded in CAPI

**Comment by vincepri** [comment]
I'd agree to leave cert-manager in place when using tilt, dev clusters should be ephemeral.

**Comment by invidian** [comment]
Hm, I need to double check it, but what I found annoying was, that for some reason I wanted to do `tilt down` and then `tilt up`, to re-create everything from scratch, as some resources did not get re-created and it was also failing, because there were some resources on the cluster already.

**Comment by fabriziopandini** [comment]
unless you mess up with versions, If cert-manager already exists in the cluster tilt-up does not complain (on the contrary, it is faster), so if there is a problem with leftover resources I guess it is for something else...

**Comment by invidian** [comment]
>unless you mess up with versions

You mean with API versions? I do actually :smile:

So the `tilt down` and `tilt up` work fine, maybe except `tilt down` checking if cert-manager is functional, that seem unnecessary.

Also adding new API fields seem to work OK, it just requires `make generate` (#4185), then stopping Tilt and running `tilt up` again. Not the best developer UX, but works. Perhaps there could be another issue for it with Tilt running generate for you etc.

Anyway, if this is intended, that cert-manager resources are not cleaned up by `tilt down`, I guess this can be closed.
