### ISSUE TITLE
Clusterctl "no-op" no longer working during init

### ISSUE THREAD

**Issue by rsmitty** [kubernetes-sigs/cluster-api#4198]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

Doing `clusterctl init -b '' -c ''...` no longer skips installing the kubeadm components. Doing this is useful for testing my own controlplane and bootstrap providers.

Example:

```bash
# GCP_B64ENCODED_CREDENTIALS=$(cat ~/gcp-creds.json | base64 | tr -d '\n') clusterctl init -i gcp -b '' -c ''
Fetching providers
Installing cert-manager Version="v0.16.1"
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v0.3.14" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v0.3.14" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v0.3.14" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-gcp" Version="v0.3.0" TargetNamespace="capg-system"
```

**What did you expect to happen:**

Deployment of anything with empty string gets skipped so I'm left with only the providers specified.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by rsmitty** [comment]
cc @fabriziopandini because I *think* he's the one that does a lot of the clusterctl hacking.

**Comment by fabriziopandini** [comment]
/area clusterctl
/priority important-soon

We should definitely add a unit test to ensure this behavior gets preverved.

@rsmitty  is this happening on v0.3.x releases or on the main branch?

**Comment by rsmitty** [comment]
latest release for me. v0.3.14

**Comment by vincepri** [comment]
/milestone v0.4.0
+ backport

**Comment by fabriziopandini** [comment]
It seems there is already a test for this and it is passing 🤔 

https://github.com/kubernetes-sigs/cluster-api/blob/65e5385bffd71bf4aad3cf34a537f11b217c7fab/cmd/clusterctl/client/init_test.go#L289-L318

**Comment by fabriziopandini** [comment]
The only thing I notice is that it is using "-", while in the example above you are using "".
This is also consistent with https://cluster-api.sigs.k8s.io/clusterctl/commands/init.html#is-it-possible-to-skip-automatic-install, so it does not seems a regression to me

/remove-kind bug
/remove-priority  important-soon
/priority awaiting-more-evidence

**Comment by rsmitty** [comment]
Oh good grief, I could have sworn empty string was the proper way to specify it. I'll make sure I switch to the dash. Thanks for looking!
