### ISSUE TITLE
Cluster Actuator should be passed a deep copy of the cluster object instead of the informer provided object

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#420]
Currently the Cluster Actuator is passed in the informer provided object instead of a deep copy of the object. This differs from the behavior of the Machine Actuator which is passed a deep copy of the object.

**Comment by kris-nova** [comment]
Is there a link to where we do this for machines?

**Comment by detiber** [comment]
@kris-nova it is done here: https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/machine/controller.go#L88
