### ISSUE TITLE
Migrate clusterctl types to CAPI operator types

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4201]
**User Story**

As an operator, I would like to CAPI & clusterctl to have all the types at the same release to avoid confusion.

**Detailed Description**

In clusterctl there is the `Provider` and `Metadata` types under the `clusterctl.cluster.x-k8s.io/v1alpha3` GV.

The original plan was to convert towards the new CAPI operator types, but given that (most probably) this is not happening in the v1alpha4 cycle, in Feb 17th Office Hours it was decided to keep Provider and Metadata types in clusterctl @ v1alpha3.

This issue is for tracking this activity for milestone next (when the CAPI operator exists)

**Anything else you would like to add:**

The alternative was to implement the v1alpha4 version of these types/without any changes and then implement a “hacky” conversion procedure in clusterctl, but this work has been considered not worth the effort given that the plans for the CAPI operator are still valid, only a little bit delayed.

Also, this minimizes impacts on the users/providers authors.

/kind feature

**Comment by sbueringer** [comment]
As discussed in the backlog grooming on 11th February, we'll close this issue for now as the operator has been moved to a separate repo.
We can open a new issue once it's time for it.

/close
