### ISSUE TITLE
Revisit changes to using non-pointer types for slices

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#4209]
During controller-runtime v0.8.1 upgrade, we had to change []* types to non-pointer slices due to a conversion-gen issue.
This change is needed also in the controllers.

Using pointer types with slices makes especially `patch` operations very easy.

Opening this issue to track if new controller-gen versions fix this problem and we can revert this requirement.

**Comment by vincepri** [comment]
Should we open an issue in controller gen rather than here? How does the patch operation become easier with a pointer slice?

**Comment by sedefsavas** [comment]
I mean when we pass the pointer slice to a function that pases pointers to another function that modifies it, we don't need to go back to slice and find that object and replace it. 
I came across an example of this during the fix https://github.com/kubernetes-sigs/cluster-api/pull/4208:
https://github.com/kubernetes-sigs/cluster-api/blob/bc756c4e7ed08313413c1300859bd4dceeccb25a/test/infrastructure/docker/exp/docker/nodepool.go#L217


I'd like to discuss here if this is something we need/want before opening an issue in the controlle-gen repo.

**Comment by vincepri** [comment]
We should open an issue in controller-gen, yeah

**Comment by sedefsavas** [comment]
Opened an issue in code-gen repo: https://github.com/kubernetes/code-generator/issues/120
Closing this.

**Comment by sedefsavas** [comment]
Actually reopening this, there is additional work for us if they fix it.
