### ISSUE TITLE
Clusterresourceset secret predicates always filters out secret resources

### ISSUE THREAD

**Issue by shyaamsn** [kubernetes-sigs/cluster-api#4218]
**What steps did you take and what happened:**
Inspect cluster resource set predicates code and found that it always returns false since the object is not of type Secret but PartialObjectMetadata.

https://github.com/kubernetes-sigs/cluster-api/blob/master/exp/addons/controllers/predicates/resource_predicates.go#L47

**What did you expect to happen:**
Predicate function to return true if secret is of type addons.cluster.x-k8s.io/resource-set.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: master
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
We should probably inspect the GVK rather than trying to cast.

/milestone v0.4.0
/priority important-soon

**Comment by sedefsavas** [comment]
Kind and APIVersion fields are missing in the PartialObjectMetadata so cannot use GVK.
Looks like a controller-runtime issue that they are missing.

**Comment by vincepri** [comment]
@sedefsavas PartialObjectMetadata should have a GVK, see https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/apiutil/apimachinery.go#L82-L95

**Comment by sedefsavas** [comment]
This looks like a similar issue to this:
https://github.com/kubernetes-sigs/cluster-api/issues/4115#issuecomment-769254298

**Comment by sedefsavas** [comment]
Actually no my bad, please ignore.

/assign

**Comment by sedefsavas** [comment]
Okay no, I take it back. TypeMeta is coming empty. Thought I didn't set TypeMeate in the tests and that is why it is coming empty but no.

**Comment by shyaamsn** [comment]
I guess even if you use GVK , the issue is you wont get the type of secret that is required to filter secret. Just curious how do you plan to address fetching type of secret.

**Comment by sedefsavas** [comment]
I think there is not much we can do on that end. We move that check to the mapper function.

**Comment by vincepri** [comment]
@sedefsavas Could we check the same with the latest version of controller runtime? The mapping functions, when used with PartialObjectMetadata should have the type information filled in now

**Comment by sedefsavas** [comment]
`PartialObjectMetadata` has Type info, but is not enough to get the type of the Secret. We either watch all `Secrets` like we do for `ConfigMaps` or cache full `Secret` objects to solve this.
Opened a PR that does the latter.
