### ISSUE TITLE
Upgrade cert-manager to version 1.x on the v1alpha3 branch

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4224]
With https://github.com/kubernetes-sigs/cluster-api/pull/4013 we are now using cert-manager 1.1.0 on the v1alpha4 branch, taking benefit from better stability and reducing impact/simplify considerations about cert-manager upgrades

We should backport these changes to the v1alpha3 branch as well

/kind feature
/milestone v0.3.x

/area clusterctl
/area dependency
/priority important-soon

**Comment by vincepri** [comment]
+1

**Comment by dlipovetsky** [comment]
+1

Some due diligence:

* This applies to release-0.3, which runs on Kubernetes >= v1.16:
![image](https://user-images.githubusercontent.com/3445370/109049004-99a29480-768c-11eb-9d3e-56a0e77062ad.png)
(from https://cluster-api.sigs.k8s.io/reference/versions.html#release-components)

* As long as CAPI is running on Kubernetes >= v1.16, there are **no special requirements** to upgrade [from 0.16 to 1.0](https://cert-manager.io/docs/installation/upgrading/upgrading-0.16-1.0/), or to upgrade from [1.0 to 1.1](https://cert-manager.io/docs/installation/upgrading/upgrading-1.0-1.1/).

**Comment by fabriziopandini** [comment]
> This applies to release-0.3, which runs on Kubernetes >= v1.16
yes
> As long as CAPI is running on Kubernetes >= v1.16, there are no special requirements to upgrade from 0.16 to 1.0, or to upgrade from 1.0 to 1.1
From my test, there is no need to do intermediate steps

**Comment by fabriziopandini** [comment]
PR merged
/close
