### ISSUE TITLE
Split E2E jobs into two separate dashboard

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4226]
**User Story**

As a maintainer, I would like to get a clear signal about CAPI E2E jobs

**Detailed Description**

Currently, all the CAPI jobs are reporting in a single dashboard, https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api, but this is getting hard to read due to the growing number of job.

We should consider splitting jobs by branch by creating the `sig-cluster-lifecycle-cluster-api-0.3` dashboard and moving all the `release-0.3` jobs there.

**Anything else you would like to add:**

The new dashboard should be defined in
https://github.com/kubernetes/test-infra/blob/master/config/testgrids/kubernetes/sig-cluster-lifecycle/config.yaml#L7

Then, all the jobs with the `release-0.3` suffix under https://github.com/fabriziopandini/test-infra/tree/master/config/jobs/kubernetes-sigs/cluster-api should be updated by changing the `testgrid-dashboards` annotation, eg

https://github.com/fabriziopandini/test-infra/blob/1da5e48e74af998daa92ea9ad5c135bd28feef45/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-3.yaml#L21

Should be modified into `testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.3 `

/kind feature
/area testing
/help
/good-first-issue

/milestone v0.4.0
/priority important-soon

@vincepri @CecileRobertMichon

**Comment by fmuyassarov** [comment]
I can work on this
/assign

**Comment by fabriziopandini** [comment]
@fmuyassarov thanks!
/lifecycle active
