### ISSUE TITLE
Allow mutation of NTP settings in KubeadmControlPlane webhook

### ISSUE THREAD

**Issue by mayankbh** [kubernetes-sigs/cluster-api#4232]
**User Story**

As a user, I would like to modify the NTP servers for my KubeadmControlPlane nodes because I want new control plane nodes with new NTP settings.

**Detailed Description**

It would be useful to be able to edit the NTP settings defined in the KubeadmConfig for a KubeadmControlPlane resource, say, because-
- My NTP servers have changed
- I made a mistake when entering them
- I forgot to originally configure them when I deployed my cluster using CAPI.
 

**Anything else you would like to add:**

Currently, the KubeadmControlPlane webhook does not appear to allow mutation of these values (https://github.com/kubernetes-sigs/cluster-api/blob/fdb2f40d4582944e89a724d11afc78e262c97d42/controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go#L97-L119)

I'm relatively new to CAPI, but I think that modifying the allowlist in that webhook to include NTP servers would suffice. (as I understand, they are used in cloud-init to setup NTP on the node). I am happy to pick up the fix if this seems like a reasonable ask. 

/kind feature

**Comment by fabriziopandini** [comment]
/milestone v0.4.0
/area control-plane

Please note that if we allow this change, it will trigger a rollout, and existing control plane machines will be removed/new ones generated.
Also, wondering if the same consideration could apply to other cloud-init fields

**Comment by fabriziopandini** [comment]
@vincepri I don't see problems in enabling this (it triggers a rollout, but this seems fine for me).
opinions?

**Comment by sbueringer** [comment]
Sounds reasonable to me.
