### ISSUE TITLE
More unit test coverage for clusterctl upgrader

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api#4233]
**User Story**

Right now, the unit tests for upgrader (`upgrader_test.go`) has tests for `Plan`, and `createCustomPlan` methods. We want to add more coverage by adding tests for the other methods in the `ProviderUpgrader` interface namely: `ApplyPlan`, and `ApplyCustomPlan` methods.

#4230 partially addresses this by adding failure cases specific to running multiple provider instance version for v1alpha4 upgrade. But, we also need to have test cases for success scenarios. 

**Anything else you would like to add:**

The main challenge here to create a fake for `getUpgradeComponents` and `installComponentsAndUpdateInventory`.

/kind feature

**Comment by fabriziopandini** [comment]
/area clusterctl
/priority backlog
/milestone v0.4.0
(putting in the milestone for now, but it doesn't sees a blocker for me so we can move it later if there is no bandwidth)

/help

**Comment by fabriziopandini** [comment]
/close
We don't have feedback about errors in this area, so the coverage that we have should be already enough
