### ISSUE TITLE
Unable to use sigs.k8s.io/cluster-api

### ISSUE THREAD

**Issue by snehal1797** [kubernetes-sigs/cluster-api#4235]
**sigs.k8s.io/cluster-api - v0.3.12**

go get sigs.k8s.io/cluster-api/util@v0.3.12
../go/pkg/mod/sigs.k8s.io/cluster-api@v0.3.12/util/predicates/generic_predicates.go:147:91: e.MetaNew undefined (type event.UpdateEvent has no field or method MetaNew)
../go/pkg/mod/sigs.k8s.io/cluster-api@v0.3.12/util/predicates/generic_predicates.go:150:88: e.Meta undefined (type event.CreateEvent has no field or method Meta)
../go/pkg/mod/sigs.k8s.io/cluster-api@v0.3.12/util/predicates/generic_predicates.go:153:88: e.Meta undefined (type event.DeleteEvent has no field or method Meta)
../go/pkg/mod/sigs.k8s.io/cluster-api@v0.3.12/util/predicates/generic_predicates.go:156:89: e.Meta undefined (type event.GenericEvent has no field or method Meta)

Here is go.mod file:
```
`go 1.13

require (
        github.com/evanphx/json-patch v4.9.0+incompatible
        github.com/go-logr/logr v0.3.0
        github.com/go-logr/zapr v0.2.0
        github.com/golang/mock v1.4.4
        github.com/kr/text v0.2.0 // indirect
        github.com/metal3-io/baremetal-operator v0.0.0-20210111093319-93a6fd209b9a
        github.com/metal3-io/cluster-api-provider-metal3 v0.4.1
        github.com/niemeyer/pretty v0.0.0-20200227124842-a10e7caefd8e // indirect
        github.com/onsi/ginkgo v1.14.2
        github.com/onsi/gomega v1.10.2
        github.com/pkg/errors v0.9.1
        github.com/prometheus/common v0.13.0
        github.com/stretchr/testify v1.6.1
        go.uber.org/zap v1.15.0
        golang.org/x/oauth2 v0.0.0-20200902213428-5d25da1a8d43 // indirect
        k8s.io/api v0.20.2
        k8s.io/apimachinery v0.20.2
        k8s.io/client-go v12.0.0+incompatible
        k8s.io/utils v0.0.0-20201110183641-67b214c5f920
        sigs.k8s.io/cluster-api v0.3.12
        sigs.k8s.io/controller-runtime v0.7.0
        sigs.k8s.io/yaml v1.2.0
)

replace k8s.io/client-go => k8s.io/client-go v0.20.0

`
```

**Comment by fabriziopandini** [comment]
Might be I'm missing something, but It is not clear to me what are you trying to achieve
As a general recommendation, if you would like to import CAPI, you must keep in sync controller runtime and the transitive Kubernetes dependencies as well.

**Comment by vincepri** [comment]
You can't use a newer version of client-go, while using CAPI v0.3.12, which is based on an older version that doesn't have some breaking changes.

**Comment by fabriziopandini** [comment]
/close
feel free to re-open if you need more info
