### ISSUE TITLE
golangci-lint configuration should not use enable-all

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api#4243]
https://github.com/kubernetes-sigs/cluster-api/blob/master/.golangci.yml currently uses `enable-all: true / disable: [...]`

We should switch it to use `disable-all: true / enable: [...]`.

The golangci-lint documentation states:

>   please, do not use `enable-all`: it's deprecated and will be removed soon.
     inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  
https://golangci-lint.run/usage/configuration/

**Comment by ShrillShrestha** [comment]
Hey @CecileRobertMichon,  I am new to open source and trying to learn to contribute. I would love to work on the issue. Just a quick question, do we just need to change the `.golangci.yml` file? and under that just change `enable-all -> disable-all` and `enable -> disable`. Or do I need to look over additional stuff?

**Comment by CecileRobertMichon** [comment]
@ShrillShrestha you should only have to change the `.golangci.yml`. The goal is to change the configuration syntax but to keep the exact same linters enabled. You can see which ones are currently enabled by running `make lint`: 

```
INFO [lintersdb] Active 33 linters: [asciicheck bodyclose deadcode depguard dogsled errcheck goconst gocritic gocyclo gofmt goimports golint gomodguard goprintffuncname gosec gosimple govet ineffassign maligned misspell nakedret nolintlint prealloc rowserrcheck scopelint staticcheck structcheck stylecheck testpackage typecheck unconvert unparam varcheck]
```

I recommend running it before and after changing the configuration to using "enabled" to make sure the linters haven't changed.

**Comment by ShrillShrestha** [comment]
Thank @CecileRobertMichon, I will try to make that changes. I will let you know if I have further questions.
