### ISSUE TITLE
Make operator consistent with other CAPI parts

### ISSUE THREAD

**Issue by alexander-demichev** [kubernetes-sigs/cluster-api#4246]
**Detailed Description**

We've just started active work on the operator and should keep it consistent with other CAPI parts. From https://github.com/kubernetes-sigs/cluster-api/pull/4117#issuecomment-788317768 that includes:

- [x] avoid a new go.mod file https://github.com/kubernetes-sigs/cluster-api/pull/4126
- [x] avoid a new .gitignore and rely on the top level one (e.g. we are already doing this for KCP, CABPK) https://github.com/kubernetes-sigs/cluster-api/pull/4126
- [x] avoid a new docker file and rely on the top level one (e.g. we are already doing this for KCP, CABPK) https://github.com/kubernetes-sigs/cluster-api/pull/4126
    - [x] add docker-build makefile command
    - [x] add docker-push makefile command
- [x] avoid a new boilerplate.txt file and use the one under hack/ https://github.com/kubernetes-sigs/cluster-api/pull/4290/
- [x] the make file should be made consistent with other makefiles in CAPI
    - [ ] drop targets like run and provide a consistent dev UX (tilt)
    - [x] drop fmt/vet in favour of golangci for consistency with the rest of the codebase
    - [x] use the controller-gen under hack/tools/
    - [x] use a consistent build/package (publish) strategy
    - [x] use a unique name for the certificate secret
- [x] target a new namespace (capi-operator-system) https://github.com/kubernetes-sigs/cluster-api/pull/4126
- [x] prefix all the object names with capi-operator https://github.com/kubernetes-sigs/cluster-api/pull/4126
- [x] add the clusterctl.cluster.x-k8s.io/core="operator" label to all the objects
- [x] introduce manager_image_patch.yaml manager_pull_policy.yaml patches (see consistent dev UX) https://github.com/kubernetes-sigs/cluster-api/pull/4126
- [x] add the node-role.kubernetes.io/master toleration https://github.com/kubernetes-sigs/cluster-api/pull/4126
- [x] make roles consistent with other operators (1 file with all the roles) https://github.com/kubernetes-sigs/cluster-api/pull/4126
- [x] drop samples https://github.com/kubernetes-sigs/cluster-api/pull/4291
- [x] use cert-manager v1 API (new) https://github.com/kubernetes-sigs/cluster-api/pull/4272
- [x] remove Log field from the reconciler (and use the one from the context)
- [x] use common names for the flags (e.g. metrics-bind-addr instead of metrics-addr) https://github.com/kubernetes-sigs/cluster-api/pull/4329
   - [x] main.go
   - [x] manager_auth_proxy_patch.yaml 
- [x] switch to klog for consistency with the rest of the codebase, remove zap https://github.com/kubernetes-sigs/cluster-api/pull/4313
- [x] switch from ginkgo to go test https://github.com/kubernetes-sigs/cluster-api/pull/4316
- [x] Add leases to leader_election_role https://github.com/kubernetes-sigs/cluster-api/pull/4330
- [x] add context to reconcile() arguments https://github.com/kubernetes-sigs/cluster-api/pull/4126
- [x] Make main.go consistent with CAPI https://github.com/kubernetes-sigs/cluster-api/pull/4329

This issue will be used to track work that was/has to be done

/kind feature

**Comment by fabriziopandini** [comment]
@alexander-demichev I have updated the list according to https://github.com/kubernetes-sigs/cluster-api/pull/4126#issuecomment-792745590; please double check so we are sure to not forget any action item

**Comment by fabriziopandini** [comment]
@alexander-demichev @MarcelMue  I guess that almost all this work is completed now.
Could you kind kindly check and eventually close this issue?

**Comment by MarcelMue** [comment]
One of the things we decided to keep open right now is tilt setup - neither of us use tilt, so we would like to implement when we actually need / use it.

**Comment by alexander-demichev** [comment]
Seems like the last thing left to do is to set up tilt, I'll create a fresh issue for that.
