### ISSUE TITLE
Please create new repository - kubernetes-sigs/cluster-provider-api-aws

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#425]
Based on the discussion in #383 please create the repository under

github.com/kubernetes-sigs/cluster-api-provider-aws
Please seed this new empty repository from the following:
https://github.com/detiber/cluster-api-provider-aws

Thanks!

This request has also been sent to the steering committee: https://groups.google.com/a/kubernetes.io/forum/#!topic/steering/A8-_jz9Qd2Y

**Comment by detiber** [comment]
@davidewatson @enxebre

**Comment by davidewatson** [comment]
https://github.com/detiber/cluster-provider-api-openstack appears to be private. I am not sure it matters until the `kubernetes-sig` repo is created. There a few common changes which will be needed for additional seeded repos though, so eventually a diff might help jump-start others.

Does it make sense for me to begin making these changes against the existing openstack repo, or should I wait to see what has already been done?

**Comment by detiber** [comment]
Oops, copy pasta error, it is
https://github.com/detiber/cluster-api-provider-aws

**Comment by roberthbailey** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-aws has been created.

/close
