### ISSUE TITLE
Gate MHC's machine timer on the status of certain pods in the cluster

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#4254]
**User Story**

As a cluster operator I would like MHC to not start the clock on the status of a Machine until certain conditions have been met on the cluster, so that during bootstrap I don't get machines deleted unnecessarily.

**Detailed Description**

In particular, if I'm using out-of-tree CPI, then a node joins by kubeadm and doesn't get a provider ID until the out-of-tree CPI is running. Depending on the OCI registry the CPI is downloading from, this could take a while.

**Anything else you would like to add:**

Open to whatever mechanism could do it, but some way of waiting for the out of CPI or at least one of a particular CNI pod to appear on the control plane before the clock starts ticking, would help with this cluster bootstrapping race condition.

/kind feature

PS: Apologies for not responding to things on other issues. I will be back...

**Comment by fabriziopandini** [comment]
@randomvariable might be this PR is already trying to address this point https://github.com/kubernetes-sigs/cluster-api/pull/3752

**Comment by randomvariable** [comment]
Maybe, control plane ready might be equivalent here.

**Comment by fabriziopandini** [comment]
/milestone v0.4.0
if possible, lets dedup with https://github.com/kubernetes-sigs/cluster-api/issues/3026

**Comment by randomvariable** [comment]
Yup, I think they describe the same thing.

/close
