### ISSUE TITLE
Cert manager tilt module needs to be updated

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api#4256]
Cert manager version was recently bumped to v1.1.0 in this [commit](https://github.com/kubernetes-sigs/cluster-api/pull/4225/files#diff-c2ee8653e1d6b85f0aadf87cd438a9250806c052877248442be4d434cbc52425) but the Tilt [module](https://github.com/kubernetes-sigs/cluster-api/blob/master/tilt_modules/cert_manager/Tiltfile) wasn't updated.

There are a few changes that should be made in the module:

- default version should be v1.1.0
- apiVersions in cert_manager_test_resources need to be updated to latest available ones
- the workaround for https://github.com/jetstack/cert-manager/issues/3121 can be removed since the issue is now fixed

 I might be missing some things, we should also audit [commit](https://github.com/kubernetes-sigs/cluster-api/pull/4225/files#diff-c2ee8653e1d6b85f0aadf87cd438a9250806c052877248442be4d434cbc52425) to make sure no other changes are needed.

**Comment by fabriziopandini** [comment]
FYI, the tilt extension is hosted at https://github.com/tilt-dev/tilt-extensions/tree/master/cert_manager, so the changes should be made there before being imported under /tilt_modules
Also, if we are going to drop support for old version of cert_manager let's make this clear in the extension readme, given that it could be used outside of CAPI as well.

**Comment by davideimola** [comment]
Hi! I am taking it!

/lifecycle active
/assign

**Comment by davideimola** [comment]
Hi @fabriziopandini.
Can I ask what do you mean by "drop support for old version of cert_manager"? I am thinking to maintain the workaround by adding a further check on the module version.
I think this will allow the users to use the module with an older cert-manager or k8s versions.

Please tell me what do you think!
Thanks!

**Comment by fabriziopandini** [comment]
@davideimola, if we are going to update cert_manager_test_resources to v1, this will fail with version older that cert-manager v1.0.0

So, IMO we have three options here:
1. keep  cert_manager_test_resources as it is (v1beta1); this will work with both older and newer versions thanks to conversions, but the downside is that this behavior it is not explicit unless we take care of documenting it.
2. have two cert_manager_test_resources, one with v1 and one with v1beta1, and select which one to use according to the cert-manager version
3. have one cert_manager_test_resources, with v1, and drop support for cert-manager versions older than v1.0.0

> I am thinking to maintain the workaround by adding a further check on the module version.

it seems you are going for 2, that sounds great to me, +1
