### ISSUE TITLE
Backport improvements to clusterctl developer docs

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4259]
**Detailed Description**

As per https://github.com/kubernetes-sigs/cluster-api/pull/4220#issuecomment-791438558, improvements to the clusterctl developer docs in  https://github.com/kubernetes-sigs/cluster-api/pull/4220 should be back ported on the release 0-3 branch

/kind documentation
/help
/good-first-issue

/milestone v0.3.x

**Comment by binchenX** [comment]
done https://github.com/kubernetes-sigs/cluster-api/pull/4264

**Comment by fabriziopandini** [comment]
/close
PR merged
