### ISSUE TITLE
Please create new repository - kubernetes-sigs/cluster-provider-api-vsphere

### ISSUE THREAD

**Issue by frapposelli** [kubernetes-sigs/cluster-api#427]
Based on the discussion in #416 please create the repository under github.com/kubernetes-sigs/cluster-api-provider-vsphere

/cc @kris-nova

**Comment by roberthbailey** [comment]
I've created a seed repository for kubernetes-sigs/cluster-provider-api-vsphere for you at https://github.com/roberthbailey/cluster-api-provider-vsphere by running the following commands to preserve commit history and then cleaning up the skeleton files:

1. Clone https://github.com/davidewatson/cluster-api-provider-skeleton into your own repository.

1. Grab commits from the `cloud/vsphere` directory:

   ```bash
   mkdir -p ~/Desktop/tmp
   cd ~/Desktop/tmp
   git clone https://github.com/kubernetes-sigs/cluster-api/
   cd cluster-api
   git remote rm origin
   git filter-branch --subdirectory-filter cloud/vsphere -- --all
   mkdir -p cloud/vsphere
   mv * cloud/vsphere
   git add .
   git commit
   ```

1. Copy them into the seed repository:

   ```bash
   cd $GOPATH/src/sigs.k8s.io/
   git clone https://github.com/roberthbailey/cluster-api-provider-vsphere
   cd cluster-api-provider-vsphere
   git remote add cloud-vsphere ~/Desktop/tmp/cluster-api
   git pull cloud-vsphere master --allow-unrelated-histories
   git remote rm cloud-vsphere
   rm -rf ~/Desktop/tmp/cluster-api/
   ```

1. Repeat the previous two steps to grab the contents of the `clusterctl/examples/vsphere` directory and import them:

   ```bash
   mkdir -p ~/Desktop/tmp
   cd ~/Desktop/tmp
   git clone https://github.com/kubernetes-sigs/cluster-api/
   cd cluster-api
   git remote rm origin
   git filter-branch --subdirectory-filter clusterctl/examples/vsphere -- --all
   mkdir -p clusterctl/examples/vsphere
   mv * clusterctl/examples/vsphere
   mv .gitignore clusterctl/examples/vsphere
   git add .
   git commit
   cd $GOPATH/src/sigs.k8s.io/cluster-api-provider-vsphere
   git remote add clusterctl-vsphere ~/Desktop/tmp/cluster-api
   git pull clusterctl-vsphere master --allow-unrelated-histories
   git remote rm clusterctl-vsphere
   rm -rf ~/Desktop/tmp/cluster-api/
   ```

I'm going to proceed with removing the vsphere code from the main repository (https://github.com/kubernetes-sigs/cluster-api/issues/435) to remove provider specific code, following the recent removal of the gcp code. You can proceed with the request to the steering committee with my seed repository or create your own following the same steps.

**Comment by frapposelli** [comment]
@roberthbailey thanks Robert, what's the right venue to submit this request? my understanding was that this issue was tracking the creation of the repo

**Comment by roberthbailey** [comment]
You need to send an email to the steering committee (look at the email linked from https://github.com/kubernetes-sigs/cluster-api/issues/425#issue-340417874) and a vote in the SIG to create the repo. A key piece is having sufficient ownership of the new repo.

**Comment by frapposelli** [comment]
This has been sorted out, the repo has been created and a new subproject under SIG-VMware has been created.
