### ISSUE TITLE
Generate manifests for operator

### ISSUE THREAD

**Issue by alexander-demichev** [kubernetes-sigs/cluster-api#4271]
After https://github.com/kubernetes-sigs/cluster-api/pull/4126 will be merged, we need to generate manifests by running `make generate-operator-manifests`. This command should output CRDs and an RBAC role.

/area operator

**Comment by fabriziopandini** [comment]
/milestone v0.4.0
We should get CI signal in place ASAP so there will be guarantee that the generated files (manifests but not only) are in sync with the rest of the codebase

**Comment by vincepri** [comment]
This doesn't seem like a release blocker

/milestone v0.4.x

**Comment by alexander-demichev** [comment]
/close 
Fixed in https://github.com/kubernetes-sigs/cluster-api/pull/4312
