### ISSUE TITLE
E2E framework: file:// scheme not supported

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [kubernetes-sigs/cluster-api#4275]
**What steps did you take and what happened:**
In e2e test config file i specified provider with following component source:
```
  versions:
  - name: v0.3.0
    type: url
    value: "file://relative/path/to/components.yaml"
```

After i started E2E test i got an error:
```
  Failed to generate the manifest for "provider" / "v0.3.0"
  Unexpected error:
      <*url.Error | 0xc0004a1140>: {
          Op: "Get",
          URL: "file://relative/path/to/components.yaml"",
          Err: {
              what: "unsupported protocol scheme",
              str: "file",
          },
      }
      Get file://relative/path/to/components.yaml": unsupported protocol scheme "file"
  occurred
```

**What did you expect to happen:**
Components from this file would be installed.

**Environment:**

- Cluster-api version: 0.3.14
- KIND version: kind v0.9.0
- Kubernetes version: (use `kubectl version`): v1.19.1

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
As a workaround you can use something like:

https://github.com/kubernetes-sigs/cluster-api/blob/57c6d549ec1ffabf93b460e51efdeca856d97c1f/test/e2e/config/docker.yaml#L32-L34

If someone is interested to send a fix, the code handling urls is here

https://github.com/kubernetes-sigs/cluster-api/blob/57c6d549ec1ffabf93b460e51efdeca856d97c1f/test/framework/clusterctl/repository.go#L137-L147

/area testing
/milestone v0.4.0
/priority backlog

/help
/good-first-issue

**Comment by GrigoriyMikhalkin** [comment]
@fabriziopandini 
Thanks! I would like to take this issue to gain a little bit more familiarity with e2e framework code.
