### ISSUE TITLE
cert-manager Tolerations removed

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#4276]
**What steps did you take and what happened:**
`clusterctl init` against a bootstrap cluster whose Nodes all have the `node-role.kubernetes.io/master:NoSchedule` Taint. The cert-manager Pods never got scheduled, because they are missing the Tolerations for that Taint.

**What did you expect to happen:**
I expected `init` to complete.

**Anything else you would like to add:**
#3034 added these Tolerations, and #3511 removed them, probably by accident.

Do we want to prevent this from happening again? One idea might be to add the Taint to the one-node kind clusters used by the e2e tests. Kind removes the Taint on such clusters by default. (Update: @fabriziopandini pointed to the right place to add a regression unit test, which is a more scoped way to verify this.)

**Environment:**

- Cluster-api version: master
- Minikube/KIND version: v0.10
- Kubernetes version: (use `kubectl version`): v1.20.4

/kind bug
/area clusterctl

**Comment by dlipovetsky** [comment]
Can/should this be backported to release-0.3?

**Comment by fabriziopandini** [comment]
/milestone v0.4.0
+1 to backport as soon as this merge on main
