### ISSUE TITLE
Implement E2E for scale in rollout

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4282]
**Detailed Description**

https://github.com/kubernetes-sigs/cluster-api/pull/4073 introduced support for rollout strategy in KCP.

Currently this feature is covered by existing E2E tests only partially (scale out rollouts); we should create a new E2E test to cover the scale in rollout as well

/kind feature
/area testing

cc @jan-est

**Comment by jan-est** [comment]
@fabriziopandini I would like to implement the E2E for scale in rollout. Is it ok if I look on this one next week?

**Comment by furkatgofurov7** [comment]
@fabriziopandini hi! Is there anything else that needs to be done to close this as #4347 is already merged?

**Comment by fabriziopandini** [comment]
@furkatgofurov7 thanks for pinging me on this issue. I think we are good here now
/close
