### ISSUE TITLE
Add a side by side comparison of MachinePools and MachineDeployments in book

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api#4288]
Maybe pictures would tell the story our words have failed to tell.

Documentation showing a visual representation comparing a `MachineDeployment` and `MachinePool` would be super helpful. Perhaps, a multi-step visualization starting from initial apply and ending with deployment completed with multiple machines that describes the anatomy, relationships and choreography of the resources the user specified and the ones created by the controller. This documentation could be less developer focused and more user focused; less state diagrams and more context / intent.

@felipeweb do you think that would have helped you?

_Originally posted by @devigned in https://github.com/kubernetes-sigs/cluster-api/pull/4112#discussion_r575659891_

**Comment by vincepri** [comment]
/milestone v0.4.x

@ashish-amarnath This issue would be a good one to tackle

**Comment by Jont828** [comment]
@devigned @killianmuldoon I'm happy to give this a try. How are we currently creating the images in the docs/book?

**Comment by sbueringer** [comment]
Most of them are generated with plantuml

**Comment by Jont828** [comment]
Sounds good I'll look into it!
