### ISSUE TITLE
Run more automated checks on cluster-api repo

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#43]
_From @krousey on February 15, 2018 19:50_

We should run the following checks on PRs and in CI:

- [x] go vet
- [x] gofmt
- [ ] verify vendor depencies are correct (this is partially accomplished by build today, but it'd be nice to have better messaging around this)
- [ ] code doesn't need to be regenerated (deepcopy, conversion, clients, ...)
- [ ] BUILD files don't have to be regenerated

_Copied from original issue: kubernetes/kube-deploy#613_

**Comment by rsdcastro** [comment]
_From @vaibhavsingh97 on February 16, 2018 12:15_

Hi @krousey Can I take this issue? Any resources to fix this issue will be a great help :)

**Comment by rsdcastro** [comment]
_From @krousey on February 16, 2018 17:42_

@vaibhavsingh97 Sure! go vet and go fmt would be the easiest to start with, and they cover areas that aren't someone protected against by our current CI build and test.

I started a CI scripts directory here: https://github.com/kubernetes/kube-deploy/tree/master/scripts

Here are the PRs I submitted to turn on build and testing in CI and on PRs. Hopefully that will be instructive enough.

- https://github.com/kubernetes/kube-deploy/pull/584
- https://github.com/kubernetes/kube-deploy/pull/590
- https://github.com/kubernetes/test-infra/pull/6761
- https://github.com/kubernetes/test-infra/pull/6787
- https://github.com/kubernetes/test-infra/pull/6792

Also, if you're running the scripts locally, I would recommend Go 1.9+ because they [changed](https://golang.org/doc/go1.9#vendor-dotdotdot) the way go tools handle the vendor directory to make it easier.

**Comment by roberthbailey** [comment]
@alvaroaleman did some of this in https://github.com/kubernetes-sigs/cluster-api/pull/589 and `go vet` is taken care of by the migration to kubebuilder.

**Comment by alvaroaleman** [comment]
@roberthbailey Regarding a `Verify vendor dependencies are correct`, there is still https://github.com/kubernetes/test-infra/pull/9874 open.

When that is done I think the only missing part is the `gofmt`, we execute it in the presubmits but we don't fail a presubmit if it creates a diff

**Comment by justinsb** [comment]
Spell checkers would probably be handy - other k repos use misspell https://github.com/kubernetes/kubernetes/blob/master/hack/verify-spelling.sh 

misspell is good at not having false positives, but only detects common misspellings.  Other ones suggested in the meeting: aspell

**Comment by dlipovetsky** [comment]
Some linting would be useful. For example, [to ensure errors aren't ignored.](https://github.com/kisielk/errcheck)

@randomvariable suggested the "meta-linter" https://github.com/golangci/golangci-lint, which is currently used in the AWS provider.

**Comment by egopher** [comment]
@roberthbailey @rsdcastro Will take this. I think meta-linter is a good approach for that as it's runs a lot of checks including go vet, fmt.

**Comment by vincepri** [comment]
I think now that we have vendor and bazel verification, this issue is almost there to be closed. The only thing missing is gometalinter.
