### ISSUE TITLE
Packet provider

### ISSUE THREAD

**Issue by vielmetti** [kubernetes-sigs/cluster-api#431]
I'm looking into getting a scope of work and scaffolding and requirements and specifications for a provider for Packet. The CNCF Cross-Cloud CI work is done at Packet, as part of the CNCF cluster hosted at Packet, and so there could potentially be an internal CNCF use case pretty much right away for that code.

I'm not ready to commit any code! It seemed like a proper start to open an issue to anchor any future discussion.

The code might live at `kubernetes-sigs/cluster-provider-api-packet` when ready.

(as discussed at cluster-api weekly call on July 18)

**Comment by timothysc** [comment]
Closing, folks can PR the main docs if/when they create one.

**Comment by vielmetti** [comment]
https://github.com/packethost/cluster-api-provider-packet

PR for main docs to follow.

**Comment by vielmetti** [comment]
The relevant PR for docs is https://github.com/kubernetes-sigs/cluster-api/pull/1189
