### ISSUE TITLE
Create library for version management and user agents

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#4318]
It might be helpful here to create a library that works across all of Cluster API providers. We could require folks to use specific package variables regarding version management and whatnot. Although I'd say that might require an issue with a small proposal

_Originally posted by @vincepri in https://github.com/kubernetes-sigs/cluster-api/issues/4257#issuecomment-795840774_

**Comment by vincepri** [comment]
/retitle Create library for version management and user agents

**Comment by randomvariable** [comment]
In terms of a proposal, you don't mean a full CAEP? Just within the issue?

**Comment by vincepri** [comment]
Yeah issue is fine
