### ISSUE TITLE
Please create new repository - kubernetes-sigs/cluster-api-provider-azure

### ISSUE THREAD

**Issue by Meegul** [kubernetes-sigs/cluster-api#432]
Based on discussions during the Wed 18 July 2018 meeting. Multiple owners still need to be established. The repo should be seeded from https://github.com/davidewatson/cluster-api-provider-skeleton/ with code being imported from https://github.com/platform9/azure-provider afterwards.

**Comment by roberthbailey** [comment]
This repository now exists. 

/close
