### ISSUE TITLE
Block on unsupported Kubernetes version

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4321]
**User Story**

As a operator, I would like to get informed about unsupported Kubernetes versions when creating resources.

**Detailed Description**

As per https://github.com/kubernetes-sigs/cluster-api/pull/4292#discussion_r593770786 

CABPK currently supports only Kubernetes versions >= v1.13, but the user does not get an error message when creating Machines/MachineDeployments/KubeadmControlPlane with older version

**Anything else you would like to add:**

This is tricky, because in some cases the kubernetes version could be defined on another resources vs the KubeadmConfig/KubeadmConfigTemplate (e.g. Machines, Machine deployments), and those resurces are generic - should not be bound to CABPK limitations.

/kind feature

**Comment by CecileRobertMichon** [comment]
Is this a duplicate of https://github.com/kubernetes-sigs/cluster-api/issues/3697 ?

**Comment by fabriziopandini** [comment]
#3697 is about semantic validation of the version
This is issue is about the fact the CABPK supports only a subset of Kubernetes versions ( >= v1.13)

**Comment by vincepri** [comment]
/lifecycle frozen

@fabriziopandini What are some action items we can take as part of this issue?

**Comment by fabriziopandini** [comment]
/close
in favor of https://github.com/kubernetes-sigs/cluster-api/issues/7010
