### ISSUE TITLE
Change in the contract for Summary condition

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api#4336]
**User Story**
This issue is in regards to [this discussion](https://github.com/kubernetes-sigs/cluster-api/issues/4311#issuecomment-799596262). 

As a developer/user/operator, I would like to see the ReadyCondition be false if one of the child conditions is not present for some reason

**Detailed Description**
Since the `ReadyCondition` is a summary of a bunch of child conditions, a missing condition should be reflected while creating this summary. Currently, the logic for creating the summary skips the condition if it is not found. Instead, it should incorporate the missing condition while creating the summary.

**Anything else you would like to add:**
This would make sure that if a necessary condition is not reported, the object's ReadyCondition always reflects that. And we can make sure that watching the Ready Condition to be true would be an actual reflection of the state of the object.

/kind feature

**Comment by srm09** [comment]
@fabriziopandini also suggested the same, that we be mindful of the effect that this might have on other systems used by CAPI and providers. I will add some examples here.

**Comment by srm09** [comment]
Taking the example for the **MachinePool** controller,
it calculates the `Ready` Condition by checking the state of the child conditions:
```golang
conditions.SetSummary(mp,
	conditions.WithConditions(
		clusterv1.BootstrapReadyCondition,
		clusterv1.InfrastructureReadyCondition,
		expv1.ReplicasReadyCondition,
	),
)
```
If any of the conditions does not exist, maybe the MachinePool hasn't been reconciled yet, or could not be found (#4311), the Ready Condition would be set to `true` which does not correctly account for all the pre-requisites for a MachinePool to be ready/operational.

Similarly for **Cluster** controller,
```golang
conditions.SetSummary(cluster,
	conditions.WithConditions(
		clusterv1.ControlPlaneReadyCondition,
		clusterv1.InfrastructureReadyCondition,
	),
)
```
If any of the above conditions isn't ready(maybe it is missing or may not be ready just yet), then the cluster should indicate that by setting the `ReadyCondition` appropriately.

Given that eventually, in most cases, the conditions will be reconciled and the state appropriately set, in an enduser/consumer of the Conditions polls the Ready condition to be true, will get incorrect signals.

**Comment by fabriziopandini** [comment]
Another use cases to keep into the radar:
- Conditions that are added only at later stages of the object lifecycle (e.g. Bootstrapping on the Docker machine)

**Comment by srm09** [comment]
The advantages of this approach are:
- The controller always takes into account the necessary pre-requisites before surfacing the Ready condition on the object.
- All scenarios wherein an external ref is incorrect/missing, will automatically be handled, rather than defensively coding it in the controller logic.

**Comment by srm09** [comment]
To make this change non-intrusive, we could start with a design where the conditional associated with each condition is optional. If a condition is necessary, the controllers (CAPI or providers) would need to opt-in to mark the presence of a child condition as mandatory.
Post the rollout (with maybe a grace period), we could switch the default behavior from opt-in to opt out, thus making the behavior consistent for all providers.

Just thinking out aloud^^

**Comment by fabriziopandini** [comment]
> All scenarios wherein an external ref is incorrect/missing, will automatically be handled, rather than defensively coding it in the controller logic.

From the other side, handling this problem in the controller provides much more control and allows to surface to the user detailed info about the underlying problem: e.g. ref XYZ is incorrect/ref XYZ is missing, etc.

Instead changing the summary logic provides a generic solution, and most probably it will be really difficult or impossible to provide to the user the same level of information about the problem. e.g the user will see Ready false, might be a message reporting a which Condition is missing, but this won't document why the condition is missing.

**Comment by srm09** [comment]
To make the experience better, we should handle both the cases.
- If a controller detects a missing/incorrect ref, it should handle it in the reconcile loop
- While calculating the `ReadyCondition` if a necessary condition is missing, the summary should reflect that. 

This way, we are making sure that the Ready Condition can be reliably used to check the status of the object.

**Comment by fabriziopandini** [comment]
/milestone v0.4.0
we can eventually reconsider later if there is no agreement
