### ISSUE TITLE
Allow creation time configuration of metadata for kubeadm controlplane machines

### ISSUE THREAD

**Issue by MarcelMue** [kubernetes-sigs/cluster-api#4337]
**User Story**

As a user I would like to apply labels to controlplane machines at creation time for easier usability

**Detailed Description**

It is currently not possible to influence the labels and annotations set on machines created for a controlplane. This includes the machine, provider machine and bootstrap configuration. This is currently possible for machines created from MachineDeployments.

Allowing users to manager labels and annotations on all machines of a cluster should be possible..

**Anything else you would like to add:**

Related to this is also a refactoring of the current `Objectmeta` implementation which currently includes unneeded fields such as name / namespace.

/kind feature

**Comment by fabriziopandini** [comment]
@MarcelMue there's is already https://github.com/kubernetes-sigs/cluster-api/issues/493 with a lot on context/discussion about labels.
What about merging this thread there?

**Comment by vincepri** [comment]
@fabriziopandini This issue is a bit different, there is no way today to specify Machine labels when KCP creates its control plane machines.

**Comment by vincepri** [comment]
/close

Closing in favor of #4636
