### ISSUE TITLE
KCP observedGeneration version does not get updated after upgrade

### ISSUE THREAD

**Issue by smcaine** [kubernetes-sigs/cluster-api#4341]
**What steps did you take and what happened:**

When deploying CAPI/CAPV the KubeadmControlPlane `metadata.generation` gets updated to new version but the `status.observedGeneration` does not. It stays on version 1..

This means it cannot be compatible with something like kstatus, which relies on the conditions status but also to make sure these are in synch, see docs (https://pkg.go.dev/sigs.k8s.io/kustomize/kstatus#readme-concepts)[https://pkg.go.dev/sigs.k8s.io/kustomize/kstatus#readme-concepts]

**What did you expect to happen:**

Once the KubeadmControlPlane resources have been updated/reconciled, the `status.observedGeneration` should be updated and match the `metadata.generation`.

**Anything else you would like to add:**

Having this work in this way would allow us to control the order of deployments of controlplane nodes and worker nodes, specifically when doing upgrades using tools like kstatus/kustomize/flux.

**Environment:**

- Cluster-api version: v1alpha3
- CAPV: v1alpha3
- Kubernetes version: 1.20.4
- OS: Ubuntu 18.04

/kind bug
/area control plane

**Comment by fabriziopandini** [comment]
/priority critical-urgent
/milestone v0.4.0

From a quick check, we are not passing the `patch.WithStatusObservedGeneration{}` to `patchHelper.Patch` in https://github.com/kubernetes-sigs/cluster-api/blob/4e9f9e399e801e249fa54202ee1851792409f46a/controlplane/kubeadm/controllers/controller.go#L227

/help
/good-first-issue

**Comment by su225** [comment]
I'm getting my feet wet and do you mind if I try fixing the issue?
