### ISSUE TITLE
Add support for OnDelete update strategy to MachineDeployments

### ISSUE THREAD

**Issue by relyt0925** [kubernetes-sigs/cluster-api#4344]
Workflow I'm looking to enable:

As a user: I would like to be able to fully control the rollout to a new MachineSet after an update to my MachineDeployment (let's use the case of rolling a VM image update for example).

The basic situation I'm interested is after an update: I would like to have a behavior where I trigger the "replacement" of an existing node by deleting the machine object (kubectl  delete machine MACHINENAME). Then, once the machine is fully deleted the controller would detect that the older replica set only has N-1 replicas and proceed to spin a new replica using the new machineSet. 

It is a similar idea to the `OnDelete` strategy allowed in DaemonSet's: https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/

Workflow walkthrough:
We start initially with a machineDeployment with the following rollingUpdate parameters. **NOTE: this is a hack just to illustrate my proposal**
```
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: -1
```

```
kubectl -n master-clusteridc get machinedeployment
NAME                                          PHASE     REPLICAS   READY   UPDATED   UNAVAILABLE
tyler-test1-2021-03-06--584ef697-clusteridc   Running   3          3       3         
```

```
kubectl -n master-clusteridc get machinesets
NAME                                                     REPLICAS   AVAILABLE   READY
tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc   3          3           3
```

```
kubectl -n master-clusteridc get machines
NAME                                                           PROVIDERID                              PHASE     VERSION
tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc-ggb69   aws:///us-west-1a/i-06a6e3252883bf71f   Running   
tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc-t87jl   aws:///us-west-1a/i-043efb3b28073db2b   Running   
tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc-wnjkd   aws:///us-west-1a/i-0559536f237c6dfc1   Running   
```

2) We trigger an update that will cause a new machine replicaset to rollout
```
kubectl -n master-clusteridc edit machinedeployment
machinedeployment.cluster.x-k8s.io/tyler-test1-2021-03-06--584ef697-clusteridc edited
```

```
kubectl -n master-clusteridc get machinesets
NAME                                                     REPLICAS   AVAILABLE   READY
tyler-test1-2021-03-06--584ef697-clusteridc-5865866cfc                          
tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc   3          3           3
```

```
kubectl -n master-clusteridc get machines
NAME                                                           PROVIDERID                              PHASE     VERSION
tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc-ggb69   aws:///us-west-1a/i-06a6e3252883bf71f   Running   
tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc-t87jl   aws:///us-west-1a/i-043efb3b28073db2b   Running   
tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc-wnjkd   aws:///us-west-1a/i-0559536f237c6dfc1   Running   
```

**At this point: no machines have been removed or new machines added. All that has occurred is that the configuration has been updated to say any new machines entering the machineDeployment going forward will be initialized with the latest machineset that matches what's in the latest revision of the machine deployment**

Key point to note is `tyler-test1-2021-03-06--584ef697-clusteridc-5865866cfc` is the machineSet corresponding to the updated information

Now we simulate what I would desire out the strategy by doing the following:
3) User requests "replacement" of machine by deleting the desired machine they want to replace
```
kubectl -n master-clusteridc delete machine tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc-ggb69
machine.cluster.x-k8s.io "tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc-ggb69" deleted
```

3b) **Hack to show strategy**: Then manually decrement the replica count of the older replica set
```
kubectl -n master-clusteridc edit machinesets tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc
machineset.cluster.x-k8s.io/tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc edited

EDIT: changed replicas from 3 to 2
```

What will happen is the machine will delete and then one replica will spawn in the new machineSet
```
kubectl -n master-clusteridc get machinesets
NAME                                                     REPLICAS   AVAILABLE   READY
tyler-test1-2021-03-06--584ef697-clusteridc-5865866cfc   1                      
tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc   2          2           2
```

```
kubectl -n master-clusteridc get machines
NAME                                                           PROVIDERID                              PHASE          VERSION
tyler-test1-2021-03-06--584ef697-clusteridc-5865866cfc-wktvr   aws:///us-west-1a/i-0c4af9c7f2216489b   Provisioning   
tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc-t87jl   aws:///us-west-1a/i-043efb3b28073db2b   Running        
tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc-wnjkd   aws:///us-west-1a/i-0559536f237c6dfc1   Running        
```

Let's say then at this point a user decides to scale the machineDeployment. That would be fine as well and all additional replicas would proceed to be provisioned with the newer machineSet
```
kubectl -n master-clusteridc edit machinedeployment
machinedeployment.cluster.x-k8s.io/tyler-test1-2021-03-06--584ef697-clusteridc edited

EDIT replicas changed from 3 to 6
```

```
kubectl -n master-clusteridc get machinesets
NAME                                                     REPLICAS   AVAILABLE   READY
tyler-test1-2021-03-06--584ef697-clusteridc-5865866cfc   4          1           1
tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc   2          2           2
```

```
kubectl -n master-clusteridc get machines
NAME                                                           PROVIDERID                              PHASE     VERSION
tyler-test1-2021-03-06--584ef697-clusteridc-5865866cfc-d7d8t   aws:///us-west-1a/i-032a121263e7c8163   Running   
tyler-test1-2021-03-06--584ef697-clusteridc-5865866cfc-gjdnj   aws:///us-west-1a/i-02b50f17454371781   Running   
tyler-test1-2021-03-06--584ef697-clusteridc-5865866cfc-rr4vv   aws:///us-west-1a/i-00d3fc6e081cb0211   Running   
tyler-test1-2021-03-06--584ef697-clusteridc-5865866cfc-wktvr   aws:///us-west-1a/i-0c4af9c7f2216489b   Running   
tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc-t87jl   aws:///us-west-1a/i-043efb3b28073db2b   Running   
tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc-wnjkd   aws:///us-west-1a/i-0559536f237c6dfc1   Running   
```

Continuing the strategy the user would eventually finish "upgrading all the workers" 
```
kubectl -n master-clusteridc delete machines tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc-t87jl
machine.cluster.x-k8s.io "tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc-t87jl" deleted

kubectl -n master-clusteridc edit machinesets tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc
machineset.cluster.x-k8s.io/tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc edited

EDIT: Replicas from 2 to 1

kubectl -n master-clusteridc delete machines tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc-wnjkd
machine.cluster.x-k8s.io "tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc-wnjkd" deleted

kubectl -n master-clusteridc edit machinesets tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc
machineset.cluster.x-k8s.io/tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc edited

EDIT: Replicas from 1 to 0
```

```
kubectl -n master-clusteridc get machines
NAME                                                           PROVIDERID                              PHASE          VERSION
tyler-test1-2021-03-06--584ef697-clusteridc-5865866cfc-d7d8t   aws:///us-west-1a/i-032a121263e7c8163   Running        
tyler-test1-2021-03-06--584ef697-clusteridc-5865866cfc-gjdnj   aws:///us-west-1a/i-02b50f17454371781   Running        
tyler-test1-2021-03-06--584ef697-clusteridc-5865866cfc-hfg47                                           Provisioning   
tyler-test1-2021-03-06--584ef697-clusteridc-5865866cfc-rr4vv   aws:///us-west-1a/i-00d3fc6e081cb0211   Running        
tyler-test1-2021-03-06--584ef697-clusteridc-5865866cfc-wktvr   aws:///us-west-1a/i-0c4af9c7f2216489b   Running        
tyler-test1-2021-03-06--584ef697-clusteridc-5865866cfc-xnzd2                                           Provisioning   
```

```
kubectl -n master-clusteridc get machinesets
NAME                                                     REPLICAS   AVAILABLE   READY
tyler-test1-2021-03-06--584ef697-clusteridc-5865866cfc   6          6           6
tyler-test1-2021-03-06--584ef697-clusteridc-7689c68fbc                          
```

**Comment by relyt0925** [comment]
The key idea here is it would allow a workflow where users get to select the machines they want to trigger to upgrade with the specific deletion request versus in the current approach it automatically goes at the scheduled rate and moves on to more nodes once conditions are met. I'm thinking of situations where a user might want to do extra verification of a node joining the cluster (more than it just entering Ready/ Running state).

**Comment by relyt0925** [comment]
The flow can be executed: the main two things that seem hacky

1) You have to use a rollingUpdate strategy with a negative number in order to prevent the machineDeploymentController from automating the entire process

2) It would be nice if the machinedeployment controller could handle updating the replica counts of the older downstream machineSet instead of also having to fetch the current count on it and decrement that number after the deletion of the node. Otherwise, another node will proceed to spin up at the old version.

**Comment by relyt0925** [comment]
I put a prototype of an implementation of this in the following pr:
https://github.com/kubernetes-sigs/cluster-api/pull/4346/files

If that is something that looks like the community will accept I can handle cleaning it up further and getting it ready for acceptance. I wanted to just get a bare bones example for initial consideration.

**Comment by vincepri** [comment]
@relyt0925 Hi! Thanks for the report. I can answer and dig more into this request more tomorrow, but just wanted to throw out there that there is a delete-me annotation that can be used to give priority to some Machines in a MachineSet.

**Comment by relyt0925** [comment]
Thank you so much for your response @vincepri ! Hope you have a wonderful rest of your weekend.

I am aware of that annotation as well and you are correct there are ways to implement workarounds to support this today it just results in a lot more out of band API calls that have to be made that can have race conditions with the base controllers deployed in cluster-api. You effectively have to do a combination of that and pausing resources temporarily in order to get the desired execution.

**Comment by fabriziopandini** [comment]
/milestone v0.4.0
given that there is already a PR in flight

**Comment by relyt0925** [comment]
Hi @vincepri : I'm guessing this means y'all will consider it? A big thank you if so!!!!!! I can work on cleaning it up with proper logging/etc.

**Comment by vincepri** [comment]
I think the reasoning above makes sense, I haven't looked at the linked PR yet, but I'd also ask to have some documentation attached to it, and to check if we need to change or update any of the current controller diagrams

**Comment by relyt0925** [comment]
you got it sir!

**Comment by vincepri** [comment]
/retitle Add support for OnDelete update strategy to MachineDeployments

**Comment by relyt0925** [comment]
Updated the MachineDeployment flow chart (not the png file just the PlantUML file) to outline the control flow diagram for this path as well.

**Comment by enxebre** [comment]
/kind feature
/area machine
Thanks @relyt0925! This now fixed by https://github.com/kubernetes-sigs/cluster-api/pull/4346. Can we close this now?
/close
