### ISSUE TITLE
Homebrew formula update automation when new release is submitted

### ISSUE THREAD

**Issue by ludusrusso** [kubernetes-sigs/cluster-api#4356]
This follows #2389 

We have a working formula on Homebrew but we need to auto update the formula with new release.
They provide a simple [Github action](https://github.com/marketplace/actions/homebrew-bump-formula) to do this but we need to generate a Personal Access Token to handle that:

> One should use the Personal Access Token for token input to this Action, not the default GITHUB_TOKEN, because brew bump-formula-pr creates a fork of the formula's tap repository (if needed) and then creates a pull request.

I can work on the action but need help to generate token!

/kind feature
/help
/assign
/lifecycle active

cc @fabriziopandini @davideimola

**Comment by vincepri** [comment]
I can setup the access token once we have a PR merged for the formula in place
