### ISSUE TITLE
How to add alternative source for cluster template with Cluster API test framework?

### ISSUE THREAD

**Issue by Insullone** [kubernetes-sigs/cluster-api#4359]
I am trying to setup e2e tests following Cluster api book [3.4 Developing E2E test](https://cluster-api.sigs.k8s.io/developer/e2e.html). I encountered a problem that I cannot find a way to add alternative source for cluster template with [CAPI e2e testing framework](https://pkg.go.dev/sigs.k8s.io/cluster-api/test/framework). Specifically, I want to do the same thing as the '--from' option in 'clusterctl config cluster':
clusterctl config cluster my-cluster --kubernetes-version v1.16.3 --from ~/my-template.yaml > my-cluster.yaml
but how to add 'my-template.yaml' with CAPI e2e testing framework?

**Comment by CecileRobertMichon** [comment]
This is how we do it in CAPZ:
Define the template files here: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/test/e2e/config/azure-dev.yaml#L54
Then use the templates as flavors: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/test/e2e/azure_test.go#L227

**Comment by Insullone** [comment]
@CecileRobertMichon Thanks! It works, but I just saw a new issue that we had 3 yaml files containing kinds for cluster, controlplane and worker separately. So I need to add 3 files, but the flavor seems to support one yaml file only. Can we support adding 3 yaml files with CAPI e2e testing framework? or I have to merge them first?

**Comment by fabriziopandini** [comment]
/kind support
/area testing

@Insullone you add a many test file as you want, see e.g 
https://github.com/kubernetes-sigs/cluster-api/blob/5cd1132aa75f6358d66cf977164ace68ec87efe0/test/e2e/config/docker.yaml#L74-L82

**Comment by Insullone** [comment]
@fabriziopandini Yes, I can add many, but one flavor can only use one file, e.g. flavor 'ipv6' will use cluster-template-ipv6.yaml only. I think one file is good enough for now, so I will close the issue now.

**Comment by CecileRobertMichon** [comment]
you can use kustomize to generate the all-in-one template file, eg: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/templates/flavors/default/kustomization.yaml
