### ISSUE TITLE
MHC E2E tests are failing

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api#4361]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main has been failing since March 11th with:

```
Summarizing 2 Failures:
[Fail] When testing unhealthy machines remediation [It] Should successfully trigger machine deployment remediation 
/home/prow/go/src/sigs.k8s.io/cluster-api/test/framework/machinehealthcheck_helpers.go:159
[Fail] When testing unhealthy machines remediation [It] Should successfully trigger KCP remediation 
/home/prow/go/src/sigs.k8s.io/cluster-api/test/framework/machinehealthcheck_helpers.go:159
```

possibly related to https://github.com/kubernetes-sigs/cluster-api/pull/3752

CAPZ tests (using nightly CAPI build) are also failing https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-capi-e2e-main, so this is not Docker specific. 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by CecileRobertMichon** [comment]
> seems to be failing here https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/machinehealthcheck_targets.go#L190 by not finding the cluster
```
controllers/machinehealthcheck_targets.go:190
        return nil, errors.Wrapf(err, "error getting Cluster %s/%s for MachineHealthCheck %s", mhc.Namespace, mhc.Spec.ClusterName, mhc.Name)
        ```

**Comment by vincepri** [comment]
Thanks @CecileRobertMichon for being on top of this! 💯 
And thanks @nader-ziada for looking into it 😊
