### ISSUE TITLE
Support multiple versions releases in Homebrew

### ISSUE THREAD

**Issue by ludusrusso** [kubernetes-sigs/cluster-api#4370]
Following discussion in #2389

If you plan to support let's say release `v0.3`, i.e. provide patch updates (like `v0.3.1` and so on) for an extended period of time, then we will accept a new formula based on the default one (`clusterctl`), but this time it would be versioned (`clusterctl@0.3`).

For an example you can look up how `ansible` formula is versioned (they provide patch updates to their releases).

_Originally posted by @dawidd6 in https://github.com/kubernetes-sigs/cluster-api/issues/2389#issuecomment-805310474_

**Comment by ludusrusso** [comment]
@vincepri @fabriziopandini do we need this?

**Comment by vincepri** [comment]
We definitely do. Once we release v0.4.0, we should make sure the action can take care of bumping the right version formula

**Comment by ludusrusso** [comment]
Ok! So we can submit a "latest" formula, that is the one that I've created, and for each "0.x" release we need to submit a "clusterapi@0.x" formula to handle the release.

I think that the simpler way to handle this would be to manually create the formula when we have a "0.x" release on homebrew, and create here a github action for each formula to handle patch release update automation that match the 0.3.x release.

Or we can develop a custom github action to fully automate this stuff, It would be interesting do work on this.

Anyway, I've checked some projects like `kubectl` or `kind` in the k8s world and they only support the latest release on homebrew, if you know some projects that do this in k8s ecosystem please let me know.

Outside k8s, ansible or postgres supports versions!

**Comment by fabriziopandini** [comment]
TBH I'm +1 to keep things simple and have only a single brew formula that install latest.

If instead we want to have additional formulas, allowing to install latest from different branches, I personally would avoid the custom GitHub action and instead create a document describing required steps for creating the formula/the GitHub action.

The users can always use other methods for getting older/specific versions.

**Comment by ludusrusso** [comment]
> TBH I'm +1 to keep things simple and have only a single brew formula that install latest.
> 
> If instead we want to have additional formulas, allowing to install latest from different branches, I personally would avoid the custom GitHub action and instead create a document describing required steps for creating the formula/the GitHub action.
> 
> The users can always use other methods for getting older/specific versions.

I agree with that. So we can keep stuff as they are and just freeze a clusterctl@0.3 formula when we are going to release 0.4, and the a 0.4 when 0.5 is coming and so on.

This works if we don't want to release other 0.3.x releases when 0.4 is ready, etc.

**Comment by fabriziopandini** [comment]
> This works if we don't want to release other 0.3.x releases when 0.4 is ready, etc.

Unfortunately this is not the case, given that it happen to release a 0.3 patch release also after 0.4 is out.

> and just freeze a clusterctl@0.3 formula when we are going to release 0.4, and the a 0.4 when 0.5 is coming and so on.

I would avoid that for the reason above

**Comment by ludusrusso** [comment]
Ok got it! 
So we need multiple formula (one for latest and one for each 0.x release), or handle it manually!

**Comment by vincepri** [comment]
I'd rather automate this now than later, otherwise we end up adding more to the (already extensive) release process.

**Comment by ludusrusso** [comment]
> I'd rather automate this now than later, otherwise we end up adding more to the (already extensive) release process.

We can do, but I think we need a custom action. Do you have a different idea?

**Comment by vincepri** [comment]
Let's see if homebrew maintainers can help here in supporting this use case maybe?

**Comment by ludusrusso** [comment]
@dawidd6 what do you think is the best way to automate this?

**Comment by dawidd6** [comment]
Please explain what you want to achieve briefly cause I can't determine it from this thread.

**Comment by ludusrusso** [comment]
@dawidd6 yea, this is what I've understood, @vincepri @fabriziopandini let me know if it is correct.

Now we have a release 0.3.14 that is mapped on the formula clusterctl on homebrew-core
When we release the the 0.4.x they want to maintain to formula, a 
 - clusterctl@0.3 that will map 0.3.14 and future patch fix on 0.3.x
 - cluster that will map 0.4.x
 
We should going on this with 0.5, 0.6 etc, that will end up in having lot's of formulas to be maintained due tu path fix.

That will be super complex to handle manually, so we want to automate it!

**Comment by dawidd6** [comment]
I don't know any existing solution that would automate submitting new formulae to a tap. Please also bear in mind that once you drop support for a release it should also be noted in the versioned formula too.

**Comment by sbueringer** [comment]
@killianmuldoon 
To take a look at what we have to do.

We probably should add something to our release housekeeping tasks / issue.

**Comment by fabriziopandini** [comment]
/close
We are still figuring out how to get one formula managed properly (see https://github.com/kubernetes-sigs/cluster-api/issues/6613).
