### ISSUE TITLE
clusterctl list images should include daemonsets

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/cluster-api#4382]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

```
$ clusterctl init --infrastructure azure:v0.4.12 --list-images
gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
quay.io/jetstack/cert-manager-cainjector:v0.16.1
quay.io/jetstack/cert-manager-controller:v0.16.1
quay.io/jetstack/cert-manager-webhook:v0.16.1
us.gcr.io/k8s-artifacts-prod/cluster-api-azure/cluster-api-azure-controller:v0.4.12
us.gcr.io/k8s-artifacts-prod/cluster-api/cluster-api-controller:v0.3.14
us.gcr.io/k8s-artifacts-prod/cluster-api/kubeadm-bootstrap-controller:v0.3.14
us.gcr.io/k8s-artifacts-prod/cluster-api/kubeadm-control-plane-controller:v0.3.14
```

**What did you expect to happen:**
The image `mcr.microsoft.com/oss/azure/aad-pod-identity/nmi:v1.6.3` should also be present.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Let me know if https://github.com/kubernetes-sigs/cluster-api-provider-azure is a better place to open this issue.
Im new to the codebase but couldn't find how the list of images is populated.

**Environment:**

```
$ clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.14", GitCommit:"5a09f69fa8c4892eb45a61d8d701140eeeaa5ba8", GitTreeState:"clean", BuildDate:"2021-02-06T03:08:57Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
```

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by devigned** [comment]
Hmm... nmi is a daemonset. I wonder if that is why it was missed.

**Comment by fabriziopandini** [comment]
@devigned you are right

https://github.com/kubernetes-sigs/cluster-api/blob/f07371de19756a95a4a1f09c236ace004261be22/cmd/clusterctl/internal/util/objs.go#L32-L57

We should probably extend this logic to consider daemonset as well

/milestone v0.4
/priority important-longterm
/help
/good-first-issue

**Comment by CecileRobertMichon** [comment]
/retitle clusterctl list images should include daemonsets
/area clusterctl
