### ISSUE TITLE
Making it easier to inject new/custom repositories while using CAPI as a library.

### ISSUE THREAD

**Issue by vespian** [kubernetes-sigs/cluster-api#4384]
**User Story**

As a developer, when using CAPI as a library for building more advanced workflows, I would like to be able to easily define new sources for component manifests (e.g. manifests embedded into binary itself). Currently it is not straightforward. 

**Detailed Description**

I noticed few things when implementing new repository type for our tooling, which uses CAPI as a library.
- currently there is no easy way to integrate new repository type without discarding existing ones. The [code that handles e.g. GitHub repository is private](https://github.com/kubernetes-sigs/cluster-api/blob/aee65de4a18b891dba7bc7956867f436376cd028/cmd/clusterctl/client/repository/client.go#L153-L180) so one can not easily create e.g. a wrapper that will add new repository type on top of the ones that CAPI already supports.
- there is no way to zero-out the [default list of providers](https://github.com/kubernetes-sigs/cluster-api/blob/aee65de4a18b891dba7bc7956867f436376cd028/cmd/clusterctl/client/config/providers_client.go), only overwrite them via config reader. When coupled with having a custom repository described above, this may result in bugs and wasted time in the long term. E.g. developer A defined new repository type and overridden e.g. AWS and Azure. Developer B started playing with the tooling and wants to deploy to GCP but get an error that github repository is not supported. The error should point out that there are no manifests for GCP and not that github repository is unsupported.
- we have two very similar types:
https://github.com/kubernetes-sigs/cluster-api/blob/aee65de4a18b891dba7bc7956867f436376cd028/cmd/clusterctl/client/client.go#L108-L114
https://github.com/kubernetes-sigs/cluster-api/blob/aee65de4a18b891dba7bc7956867f436376cd028/cmd/clusterctl/client/cluster/client.go#L107
The are pretty similar, but not the same, using similar input/output parameters but not the same, and both need to be used in two different places in order to inject custom repository into CAPI. Ideally, we would have only one type used only in one place in order to introduce a new repository type. 

Please let me know if I missed something, or do not have some context. Thanks in advance.

**Anything else you would like to add:**

/kind feature

**Comment by fabriziopandini** [comment]
/remove kind-feature
/kind support

There is a lot of request in this ticket, I hope answer below are exhaustive or at least helpful...

> currently there is no easy way to integrate new repository type without discarding existing ones. 

Have you considered to contribute repository factory upstream? Repository are pretty generic bits of code solving the fetch from source X problem, and the entire community can benefit from new repository implementations.
If this is not an option for you, you can use `client.New(InjectRepositoryFactory(...))` to provide your repository factory implementation or `repository.New(....., InjectRepository(..))` to provide your own repository implementation.

> there is no way to zero-out the default list of providers

I don't think that zeroing-out the default list of providers is something we have to encourage as a community; on the contrary we have to promote all the providers implementation and ask for new implementers to add their own. 

Nevertheless, if this is not an option for you, also in this case there are options to provide your own config provider; WRT to providing a consistent user experience, acting upstream will ensure a greater level of consistency across the board; if instead for any reason you decide to implement a custom solutions, then it became a matter of documenting what your solution supports both in term of supported providers and repository types.

> we have two very similar types

Clusterctl API has two level of abstraction, the client and the inner packages.
If you act at client level only, your configurations get transparently propagated down the chain into the package layer (this is what clusterctl CLI is doing).
If you choose to act at both levels, you have to deal with two different levels of abstraction, and thus with the different signatures.

**Comment by vespian** [comment]
@fabriziopandini Thank you for a reply and I apologize for a late answer. Please see my answers below:

> Have you considered to contribute repository factory upstream? Repository are pretty generic bits of code solving the fetch from source X problem, and the entire community can benefit from new repository implementations.

Happy to do that, if CAPI community thinks that the use case is useful/makes sense:

In our product we wanted to bundle CAPI manifests together with a binary. The clusterctl command fetches the latest version from github and this requires setting up github token to avoid hitting limits and does not work well in airgapped environments. Bundling also ensures that we always use the manifests version that is in sync with the tooling.

We could have clusterctl do the same and give user an option to choose from built-in manifests or fetch the latest ones from github or use the ones provided on disk. A different approach could be just merging the code so that other people integrating CAPI could use it if they wish. 

What do you think?

**Comment by fabriziopandini** [comment]
@vespian great to hear that.
I think that the next step is to define the contract (*) around this new binary repository and start discussing it with the community (or might be to do both steps in parallel).
(*) define a set of of rules that makes this new repository provider "usable" for a wider audience in the community

**Comment by vespian** [comment]
Closing for now, I can't find time to look into it :(
