### ISSUE TITLE
Improve the way we inject ci-artifacts.sh

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#4386]
**What steps did you take and what happened:**

I tried to use `kubernetesversions.GenerateCIArtifactsInjectedTemplateForDebian` in CAPO e2e tests and instead of just adding `files` and `preKubeadmCommands` it overwrote existing ones. In my case those were files required for the cloud controller manager / internal cloud provider.

**What did you expect to happen:**

I thought `GenerateCIArtifactsInjectedTemplateForDebian` would just add new elements into those arrays instead of overwriting them completely.

**Anything else you would like to add:**

The underlying issue is that kustomize just overwrites arrays of CRDs with an unknown schema ([kustomize #2825](https://github.com/kubernetes-sigs/kustomize/issues/2825)) when using `patchesStrategicMerge`. This could be fixed by using `patchesJson6902` instead.

I already have an implementation which would improve the current state: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/b9109b4125b2dc6dcca3927347252749ae647463/test/e2e/shared/kubernetesversions/template.go

During the implementation I also found a few other things that can be improved:
* gsutil is not really required to download the files from GCS, so we can speed up every server boot by about 3 minutes by skipping the gsutil installation and just using curl
* we don't have to download the control plane images on worker nodes, this also saved about 30 seconds
* ~~bindata is unused, so it can be deleted (it has already been replaced by go embed)~~ (is getting fixed in #4378)

(The durations are from CAPO e2e tests, in this case we are using a OpenStack devstack on a GCP VM)

**Environment:**

- Cluster-api version: CAPO latest
- Kubernetes version: (use `kubectl version`): 1.20.4
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04 (image-builder/qemu)

/kind bug

I already implemented it for CAPO. If there's interest to have this implemented in this repo just let me know. Otherwise it would be okay for me to just maintain our own version of the func in the CAPO repo.

**Comment by CecileRobertMichon** [comment]
@sbueringer I had the exact same issue which is why we're not currently using `GenerateCIArtifactsInjectedTemplateForDebian ` in CAPZ. See the discussion I had with @randomvariable at the time here: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1018#discussion_r515363781

Azure also requires the azure.json file to be written on every machine for in-tree Cloud Controller Manager / out of tree cloud provider configuration.

**Comment by sbueringer** [comment]
@CecileRobertMichon Thx for the info. That was exactly my problem. 

Regarding https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1018#discussion_r516552935, as far as I know we can decide if we want to added the array entries at the start or end of the array via JSON patch.

Then I'll just open a PR here and let's see if we can get consensus on the implementation.
