### ISSUE TITLE
MHC E2E tests are failing (part II)

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#4395]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

In general the `When testing unhealthy machines remediation` tests are working again, but they are flaky:
![image](https://user-images.githubusercontent.com/4662360/112875596-ac155100-90c4-11eb-974d-2de331b75b05.png)

I took a closer look at `When testing unhealthy machines remediation Should successfully trigger KCP remediation`:

This test should works roughly like this:
* Cluster is initially provisioned with 3 control plane and 1 worker node
* One of the control plane nodes gets marked as unhealthy
* Test waits until the health check is remediated (https://github.com/kubernetes-sigs/cluster-api/blob/7478817225e0a75acb6e14fc7b438231578073d2/test/framework/machinehealthcheck_helpers.go#L127)
  * to be precise: it waits until none of the control plane nodes in the target cluster has the unhealthy condition anymore
    * it doesn't necessarily wait until the replica count of the `KubeadmControlPlane` is reached again with healthy nodes
    * this means if the target cluster only has 2 healthy nodes the wait func is done
* After that the cluster is dumped and *then* removed

Roughly 6 of the 10 last test I looked at failed. All failed during the teardown.

The following is based on this test run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1376514349782274048

Observation:
* dump only dumps 2 control plane and one worker node

Timeline:  (logs: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1376514349782274048/artifacts/clusters/bootstrap/controllers/)
* capi controller manager
  * 12:51:06.726364 first control plane node mhc-remediation-quwlwc-control-plane-v8mdf
  * 12:53:26.573836  second control plane node mhc-remediation-quwlwc-control-plane-zxqmw
  * 12:55:52.031866 third control plane node mhc-remediation-quwlwc-control-plane-2vnl4
  * 12:57:08.991183 MachineDeployment deletion starts
  * 12:57:10.158853 fourth control plane node mhc-remediation-quwlwc-control-plane-dshv6
  * 12:57:10.945848 Infrastructure provider is not ready, requeuing (& Cannot reconcile Machine's Node, no valid ProviderID yet)
  * 12:57:14.067076 KubeadmControlPlane deletion starts
  * 13:00:32.314665 Cluster infrastructure deletion starts (we're over the 3m timeout of the teardown)
* capd controller
  * 12:57:11.408083  Creating control plane machine container mhc-remediation-quwlwc-control-plane-j522w (which is the DockerMachine name of mhc-remediation-quwlwc-control-plane-dshv6)
  * 12:57:20.989721 Updating load balancer configuration for mhc-remediation-quwlwc-control-plane-j522
  * 13:00:22.023978 fails to join mhc-remediation-quwlwc-control-plane-dshv6 (this takes 3m because of a 3m timeout in CAPD)
  * 13:00:24.503623 failed to patch DockerMachine (so it has been deleted)
* capi kubeadm bootstrap controller
  * 12:57:10.439194 Creating BootstrapData for the join control plane mhc-remediation-quwlwc-control-plane-dshv6
* capi kubeadm control plane controller
  * 12:57:09.984439 Scaling up control plane (desired 3, two exists)
  * 12:57:10.562892 Reconcile KubeadmControlPlane
  * 12:57:12.742901 Reconcile KubeadmControlPlane
  * 12:57:14.390956 Reconcile KubeadmControlPlane deletion
  * 13:00:32.285659  \"mhc-remediation-quwlwc-control-plane\" not found (so it has been deleted)
* dump dumps mhc-remediation-quwlwc-control-plane-v8mdf and mhc-remediation-quwlwc-control-plane-zxqmw

So in my opinion:
* the test doesn't wait until the KubeadmControlPlane is reconciled to 3 control plane nodes again. 
* the test triggers the cluster deletion
* in the same time frame a new control plane node is created and tries to join the cluster
* the new machine is stuck for about 3 minutes (because of a 3m timeout in CAPD)
* this leads to the timeout in the test teardown
* after that all machines and the cluster get deleted (just not in time)

**What did you expect to happen:**

I suspect almost all of what I described is working correctly. I don't think we want to change the join timeout in CAPD or the test teardown timeout of 3m. I would suggest adjusting the test so that it waits until the 3rd replica is reconciled completely (i.e. it exists in the target cluster and is healthy) so we don't run into the race condition between KubeadmControlPlane reconciliation and cluster deletion.

What do you think?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Reference to the old issue: https://github.com/kubernetes-sigs/cluster-api/issues/4361 
As far as I could see they are completely unrelated.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
@sbueringer Thanks for the detailed analysis, really helpful.

Thinking a little bit about this problem, and the one decribed in part III, I'm getting of the opinion that `DiscoverMachineHealthChecksAndWaitForRemediation` should always wait for the original number of machines to be restored, meaning:
- waiting for 1 worker to exists without unhealthy conditions in the first test
- waiting for 3 CP to exists - all without unhealthy conditions - in the second test

WDYT?

**Comment by sbueringer** [comment]
@fabriziopandini 

Sounds good to me. I'll take a look at the details how best to achieve that and open a PR with a first implementation

/assign

**Comment by sbueringer** [comment]
ah nice. I'll take a look :)
