### ISSUE TITLE
Define validation strategy for provider config

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#44]
_From @rsdcastro on February 22, 2018 21:13_

As per comment in #405, "validation is another concern and independent of specifying the cloud provider in the top level object or in the provider specific config. We can't bake provider specific validation logic into the API. That needs to be pluggable somehow through a webhook, admission controller, or some other mechanism. But it's a much larger discussion." 

This issue tracks methods we'll allow for validation, including recommendations and examples.

cc @karan 

_Copied from original issue: kubernetes/kube-deploy#623_

**Comment by rsdcastro** [comment]
_From @roberthbailey on March 7, 2018 18:53_

This seems to depend on https://github.com/kubernetes/kube-deploy/issues/504

**Comment by roberthbailey** [comment]
Validation is provider specific, so this is out of scope for this repository.

/close
