### ISSUE TITLE
ci-test.sh should provide JUnit reports  for testgrid

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#4400]
**User Story**

As a developer it would be easier to get an overview over flaky unit test if we would have JUnit reports as an output of ci-test.sh.

**Detailed Description**

For comparison:
* test results ci-e2e.sh: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main&width=20
* test results ci-test.sh: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-test-main&width=20

**Anything else you would like to add:**

In case we think this would be useful, I would investigate what the best way is to generate those reports.
Some options:
* [go-junit-report](https://github.com/jstemmer/go-junit-report): create junit reports based on go test output, e.g.: `go test -v 2>&1 | go-junit-report > report.xml`
* [gotestsum](https://github.com/gotestyourself/gotestsum): runs `go test --json`. Seems to provide a very nice output (at a first glance). Could be used via `gotestsum --junitfile unit-tests.xml`
 
I think I would prefer `go-junit-report` because it just converts the go test output to a JUnit file. Shouldn't be a problematic dependency.

/kind feature

**Comment by fabriziopandini** [comment]
I'm +1 for this change.
Probably, the best way to get this is to add go-junit-report as a pinned version dependecy in hack/tools

**Comment by sbueringer** [comment]
@vincepri yes I can implement this. Just wanted to ask first :)

/assign
