### ISSUE TITLE
CAPD nightly build fails

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#4408]
**What steps did you take and what happened:**
Nightly build is failing for CAPD images:
https://testgrid.k8s.io/sig-cluster-lifecycle-image-pushes#cluster-api-push-images-nightly&show-stale-tests=

See the discussion: 
https://kubernetes.slack.com/archives/C8TSNPY4T/p1617120917279100

We may want to fix this bug with this issue: https://github.com/kubernetes-sigs/cluster-api/issues/4407

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
@sedefsavas Dumb question. could it be that the image push job currently does not push container images? 

Just looked at: https://github.com/kubernetes-sigs/cluster-api/blob/26ff3dff0d8e0b8c5635619d879e875699dfffae/Makefile#L559-L568

and I'm wondering how this target could push images. (I'm just curious because I want to implement nightly builds for CAPO)

**Comment by sedefsavas** [comment]
@sbueringer  We were initially both pushing and tagging, but then realized we already build images on every change on the master branch, so instead we changed it to just tag those existing images.

If you also need to push images, it is something similar to combination of `release-staging` (for pushing images) and `release-staging-nightly` (For tagging them).

For example, if I want to push and tag to my own repo, I do this:
```

STAGING_BUCKET=staging.sedef-xx.appspot.com STAGING_REGISTRY=gcr.io/sedef-xx make release-staging TAG=v20210120-v0.3.10-308-gc61521971 PULL_BASE_REF=master

STAGING_BUCKET=staging.sedef-xx.appspot.com STAGING_REGISTRY=gcr.io/sedef-xx make release-staging-nightly TAG=v20210120-v0.3.10-308-gc61521975 PULL_BASE_REF=master
```

**Comment by sbueringer** [comment]
@sedefsavas Ah perfect thx, that makes sense

**Comment by sbueringer** [comment]
According to test grid the PR fixed the issue: https://testgrid.k8s.io/sig-cluster-lifecycle-image-pushes#cluster-api-push-images-nightly

**Comment by sedefsavas** [comment]
Thanks for confirming.

/close
