### ISSUE TITLE
Add linter to prevent use of deprecated ioutil module

### ISSUE THREAD

**Issue by stmcginnis** [kubernetes-sigs/cluster-api#4419]
**User Story**

As a developer, I would like to make sure I am following guidelines and avoid using deprecated code.

Go 1.16 deprecated the `ioutil` module, adding `os` and `io` equivalents for included functions.

https://github.com/kubernetes-sigs/cluster-api/pull/4399#issuecomment-811504262 updated the cluster-api code to use those alternative calls.

The `ioutil` deprecation can be considered a soft-deprecation as it does not trigger deprecation errors from linters, presumably to make the transition easier for consumers of the deprecated code. Eventually this is likely to become a hard deprecation and be removed.

Since we've cleaned up existing usage, it would be good to make sure new instances are not introduced as people contribute new code. This will make it easier when that hard deprecation comes.

**Detailed Description**

See comments in https://github.com/kubernetes-sigs/cluster-api/pull/4399#issuecomment-811504262 for some suggested approaches to add linting checks to prevent the introduction of new uses of the module.

/kind feature

**Comment by sbueringer** [comment]
@stmcginnis I think we should extend this issue a bit regarding that we want to block not only ioutil but just packages we don't want to be used in general. Another example seems to be ([ref](https://github.com/kubernetes-sigs/cluster-api/pull/4399#issuecomment-810365316)).

**Comment by stmcginnis** [comment]
Good idea @sbueringer. If we set up the mechanism to lint for ioutils, no reason we can't use it for whatever set of imports we want to guard against.

**Comment by stmcginnis** [comment]
/close

This has been addressed by the upgrade of golangci-lint to 1.43.0. The updated linters used by that version include checks for `ioutil` usage.

**Comment by sbueringer** [comment]
@stmcginnis I tried to reproduce but I couldn't.

I added the following to `main.go`:
```go
	if _, err := ioutil.ReadDir("/tmp/"); err != nil {
		panic(err)
	}
```

Which linter should have detected that? Maybe it's somehow not enabled/excluded in our config?

/reopen
(for the moment)

**Comment by stmcginnis** [comment]
My mistake closing this. The other repos where I'm using golangci-lint had additional groups enabled for the `gocritic` linter that picked up the `ioutil` usage. We did not have the right groups enabled in cluster-api, so proposing the enabling of the necessary groups now.

**Comment by sbueringer** [comment]
Thx. Yeah I thought it's something like that.
