### ISSUE TITLE
remove usage of the kubeadm ClusterStatus object in Cluster API.

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/cluster-api#4423]
ClusterStatus is an API structure present in kubeadm v1beta and v1beta2 that was used to track what API endpoints are available in the cluster. in 1.18 we deprecated it and implemented another method of doing the same, by applying annotations to the kube-apiserver pods. this already the default method in kubeadm, but ClusterStatus is still maintained as the second deprecated method.

the object is stored in the kubeadm-config CM.

https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/2506-Remove-ClusterStatus-from-kubeadm-config

we had a discussion about this in the kubeadm office hours and @fabriziopandini mentioned that there could be impact on cluster API:
https://youtu.be/SZuK87bCfqI?t=1192

i see there there is some usage here:
https://github.com/kubernetes-sigs/cluster-api/search?q=clusterstatus

kubeadm has a plan to remove this API in v1beta3, which means Cluster API would not be able to use v1beta3 if it also uses ClusterStatus.

this issue is to migrate Cluster API to the new method of annotations and backport the change if needed.

**Comment by neolit123** [comment]
/assign @fabriziopandini 
please delegate if appropriate.

/kind deprecation feature
/priority important-soon

**Comment by fabriziopandini** [comment]
@neolit123 Thanks for opening this issue. It is on my agenda for the next week

**Comment by fabriziopandini** [comment]
The implementation of an alternative approach of `ClusterStatus` in the Kubeadm ConfigMap landed in [Kubernetes v1.18](https://v1-18.docs.kubernetes.io/docs/setup/release/notes/#kubeadm).

Given that, if we are considering Cluster API must support the latest three Kubernetes releases for workload clusters (as of today v1.21, v1.20, v1.19), there are no blockers for dropping `ClusterStatus` object in kubeadm v1beta3 and as a consequence in  Cluster API v1alpha4 types.

This will allow some cleanups in KCP
- Drop logic for updating the `ClusterStatus` object in the kubeadm ConfigMap while scaling down
- Drop logic for updating the `ClusterStatus` object in the kubeadm ConfigMap while remediating
- Drop "catch-all" logic for reconciling `ClusterStatus` object in the kubeadm ConfigMap (`reconcileEtcdMembers`)

The downside of this change is that Cluster API / KCP v1alpha4 won't be able to manage Kubernetes clusters < v1.17, but this should not be a problem given that this release is out of the support skew.

Another important thing to notice is that dropping `ClusterStatus` object in kubeadm v1beta3 API could affect Cluster API v1alpha3 branch as well, de facto preventing CAPI v1beta3 to manage Kubernetes v1.22 clusters, unless we decide to implement & backport a workaround to make this possible.

@vincepri @detiber @CecileRobertMichon opinions ^^ ?

**Comment by CecileRobertMichon** [comment]
> The downside of this change is that Cluster API / KCP v1alpha4 won't be able to manage Kubernetes clusters < v1.17, but this should not be a problem given that this release is out of the support skew.

👍 

> Another important thing to notice is that dropping ClusterStatus object in kubeadm v1beta3 API could affect Cluster API v1alpha3 branch as well, de facto preventing CAPI v1alpha3 to manage Kubernetes clusters >= v1.22, unless we decide to implement & backport a workaround to make this possible.

Would that be breaking back compat rules for beta, ie. support for the last 3 release and/or up to a year ? Not sure if supporting new k8s versions is part of the contract.

**Comment by vincepri** [comment]
We should definitely document this bit and potentially block and upgrade to v0.4 if a cluster is older than 1.18

**Comment by sbueringer** [comment]
> Another important thing to notice is that dropping `ClusterStatus` object in kubeadm v1beta3 API could affect Cluster API v1alpha3 branch as well, de facto preventing CAPI v1alpha3 to manage Kubernetes clusters >= v1.22, unless we decide to implement & backport a workaround to make this possible.

Not sure if we want to go there, but if I'm not mistaken we don't necessarily need kubeadm v1.22 to create a v1.22 Kubernetes clusters (or at least something like this worked in the past). So if other workarounds for v1alpha3 are more complicated, maybe we can use a kubeadm version < v1.22 to create Kubernetes clusters >= 1.22.

But not sure if that's a good idea.

**Comment by fabriziopandini** [comment]
As per discussion at the Apr 7th CAPI office hours:
- OK for Cluster API / KCP v1alpha4 won't be able to manage Kubernetes clusters < v1.17,
- Given the time rich between v1alpha4 release and Kubernetes v1.22 release, we should explore a possible workaround for allowing CAPI v1alpha3 to manage Kubernetes clusters >= v1.22

**Comment by fabriziopandini** [comment]
@CecileRobertMichon @vincepri @detiber I have investigated a possible workaround for allowing CAPI v1alpha3 to manage Kubernetes clusters >= v1.22.

This is possible, but it requires dedicated PR targeting release-0.3 branch given the number of changes landed in this area for v1alpha4. 

As a result starting from CAPI v0.3.16, it will be possible to install v1.22 clusters (older version can't do this given the changes in kubeadm)
If this is ok, I will start working on those changes

**Comment by vincepri** [comment]
I'm fine with the approach described, @CecileRobertMichon @detiber thoughts?

**Comment by detiber** [comment]
@fabriziopandini awesome news, I'm a +1 for adding support to v0.3.x for k8s v1.22+

**Comment by CecileRobertMichon** [comment]
SGTM, looks like this will be true for v0.3.17+ though as we'll most likely release v0.3.16 earlier.

**Comment by fabriziopandini** [comment]
Ok, I will start working on this and try to get this into the v0.3.x train ASAP
