### ISSUE TITLE
Add implementation of conversion webhook for CAPD

### ISSUE THREAD

**Issue by prksu** [kubernetes-sigs/cluster-api#4436]
**Detailed Description**

Currently, there is no conversion webhook hubs/spokes implementation for CAPD. It would be good if CAPD has a conversion webhook in place considering the goal of CAPD is to be a reference implementation of an infrastructure provider.

**Anything else you would like to add:**

This issue following up this comment https://github.com/kubernetes-sigs/cluster-api/pull/4417#discussion_r606236416

/kind feature

**Comment by fabriziopandini** [comment]
/close

This was fixed by https://github.com/kubernetes-sigs/cluster-api/pull/3088 and following PRs
