### ISSUE TITLE
"make generate" still writes generated code to GOPATH/src and removes files from tree

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api#4441]
**What steps did you take and what happened:**
1. `docker run -it --rm golang:alpine sh -c 'apk add -U git make bash curl gcc libc-dev && mkdir -p /usr/src && git clone https://github.com/kubernetes-sigs/cluster-api.git /usr/src/cluster-api && make -C /usr/src/cluster-api generate && git -C /usr/src/cluster-api diff --quiet'`
2. Command returns 1.

**What did you expect to happen:**
Command should return 0.

**Anything else you would like to add:**
Follow up to #4185.

**Environment:**

- Cluster-api version: 5f08b4a
- OS (e.g. from `/etc/os-release`): Alpine

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by stmcginnis** [comment]
Got it! Missing using `--output-base=/usr/src/cluster-api` in one of the subdirectories. Patch up shortly.

Thanks for catching this!

/assign

**Comment by invidian** [comment]
It seems that https://github.com/kubernetes-sigs/cluster-api/commit/e8cb88e428d75389bf2a4737639fbf787ee64178#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R296 is missing `$(CONVERSION_GEN_OUTPUT_BASE)`.

```patch
diff --git Makefile Makefile
index 47d924c8c..891edec77 100644
--- Makefile
+++ Makefile
@@ -293,7 +293,7 @@ generate-go-conversions-cabpk: $(CONVERSION_GEN)
                --input-dirs=./bootstrap/kubeadm/types/v1beta1 \
                --input-dirs=./bootstrap/kubeadm/types/v1beta2 \
                --build-tag=ignore_autogenerated_kubeadm_bootstrap_v1alpha3 \
-               --output-file-base=zz_generated.conversion \
+               --output-file-base=zz_generated.conversion $(CONVERSION_GEN_OUTPUT_BASE) \
                --go-header-file=./hack/boilerplate/boilerplate.generatego.txt

 .PHONY: generate-go-kcp
```

Fixes it.
