### ISSUE TITLE
 Add unit tests for RollingUpdate MachineDeployment Rollout Strategy  

### ISSUE THREAD

**Issue by relyt0925** [kubernetes-sigs/cluster-api#4457]
- [ ] Unit tests asserting expected functionality of functions in this file: https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/machinedeployment_rolling.go

**Comment by enxebre** [comment]
I'm closing this as the 3 referenced PRs got merged and lay down a decent basis. Let's create new issues for any particular upcoming increase coverage.
/close
