### ISSUE TITLE
Define deletion policies for physical machines

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes-sigs/cluster-api#446]
It make sense to define delete policies on the level of a cloud provider. In my case, I am not able to delete an AWS machine directly. Instead, I stop an instance and append a specific suffix. Later on, a bot that periodically checks all AWS instances removes all instances that have the suffix. This way, I can't accidentally delete machines and this approach also helps to make permission more granular so only a small group of people can actually delete instances.

The deletion policy for a physical machine is cloud provider specific. Based on use cases and restrictions some cloud providers may provide only a single way to delete a physical machine.

**Comment by roberthbailey** [comment]
It sounds like this isn't related to policies that we would define, but rather policies that you have defined already (e.g. you can't directly delete machines) that you need a way to plug in a compatible implementation for. Would having a variant/flavor of the AWS machine controller (or the deletion flow of such a controller) satisfy this use case? Or do you think there is something more generalizable here that it needs to be represented in the API or in the generic controller code?

**Comment by ingvagabund** [comment]
This is no longer relevant. It's actuator implementation detail.
