### ISSUE TITLE
TestReconcileUpdateObservedGeneration is flaky

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4461]
looking at https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-pr-test-main&width=20 is seems that TestReconcileUpdateObservedGeneration is really flaky

Two types of errors can be seen in the job

```
  controller_test.go:162: 
        Unexpected error:
            <*errors.StatusError | 0xc0007fe3c0>: {
                ErrStatus: {
                    TypeMeta: {Kind: "", APIVersion: ""},
                    ListMeta: {
                        SelfLink: "",
                        ResourceVersion: "",
                        Continue: "",
                        RemainingItemCount: nil,
                    },
                    Status: "Failure",
                    Message: "KubeadmControlPlane.controlplane.cluster.x-k8s.io \"kcp-foo-z7deww\" not found",
                    Reason: "NotFound",
                    Details: {
                        Name: "kcp-foo-z7deww",
                        Group: "controlplane.cluster.x-k8s.io",
                        Kind: "KubeadmControlPlane",
                        UID: "",
                        Causes: nil,
                        RetryAfterSeconds: 0,
                    },
                    Code: 404,
                },
            }
            KubeadmControlPlane.controlplane.cluster.x-k8s.io "kcp-foo-z7deww" not found
        occurred
```
and
```
    controller_test.go:178: 
        Timed out after 10.001s.
        Expected
            <int64>: 0
        to equal
            <int64>: 1
```

/kind failing-test
/kind flake
@sbueringer 
@davideimola

**Comment by davideimola** [comment]
Hi @fabriziopandini,
I think the first issue is caused by those lines

https://github.com/kubernetes-sigs/cluster-api/blob/e4ae2abb15c26e7e1d59dd90cbd050e6be007552/controlplane/kubeadm/controllers/controller_test.go#L157-L163

After the creation, we are not reconciling (I think it is required), and maybe we can add the generation reading inside the Eventually.

The other issue maybe can be fixed by increasing the timeout value, but I am not so sure about that...

**Comment by fabriziopandini** [comment]
the fix should be worked in testenv/controller runtime (use the live client, fix kubernetes/kubernetes#80609), so I'm temporarily disabling the test to unblock PRs

**Comment by fabriziopandini** [comment]
/close
It seems the test is stable lately

**Comment by sbueringer** [comment]
/reopen

The test is stable because we skipped it: https://github.com/kubernetes-sigs/cluster-api/blob/f73a27729acf3bc2cce2479220e1460eb6f73efb/controlplane/kubeadm/internal/controllers/controller_test.go#L159
