### ISSUE TITLE
External Bootstrap Cluster CleanUp

### ISSUE THREAD

**Issue by alejandroEsc** [kubernetes-sigs/cluster-api#448]
Allow for clean up of resources when clusterctl finishes running against an existing bootstrap cluster, i.e., a cluster that exists with a kubeconfig file having admin rights and it is not minikube (thought it could be).

Should be the next task as discussed in PR: https://github.com/kubernetes-sigs/cluster-api/pull/442#issuecomment-407825455

**Comment by alejandroEsc** [comment]
from @jessicaochen : " The only high level point you may want to think through is cleanup. As it is, after bootstrap is done, the external cluster will have a bunch of leftover controllers/objects sitting in it. We will want some cleanup logic if you plan on leaving the external cluster running. For minikube, the cleanup was handled in the deletion of the minikube cluster."

from @jessicaochen : "If you want my 2-cents on how the cleanup should be - It should probably be in the ClusterDeployer. Since that class creates all the objects in the external cluster, it should have enough context to (optionally) clean them as well."

**Comment by roberthbailey** [comment]
This feels like a special case of https://github.com/kubernetes-sigs/cluster-api/issues/479. Can we consolidate effort around defining the workflow (and make sure it includes deletion)?

**Comment by alejandroEsc** [comment]
@roberthbailey wouldnt mind chatting with you and @sflxn sometime about this. Just not sure this addresses the issue or things in mind per se as noted, but yeah can be affected by it.

**Comment by ncdc** [comment]
@detiber are you working on this now? Is there a PR in flight?

**Comment by detiber** [comment]
@ncdc yes, this is part of #731

**Comment by ncdc** [comment]
Thanks. Does 731 close this issue? If so, can we put that in 731's description?
