### ISSUE TITLE
Does Cluster API test framework support creating bootstrap cluster with minikube?

### ISSUE THREAD

**Issue by Insullone** [kubernetes-sigs/cluster-api#4483]
We are using [Cluster API test framework](https://pkg.go.dev/sigs.k8s.io/cluster-api/test/framework) for e2e tests. I see that the framework provides a way to create bootstrap cluster with kind. However, we want to create bootstrap cluster with minikube for now. Is it possible to do that with the Cluster API test framework?

**Comment by fabriziopandini** [comment]
We are not supporting the creation of cluster with Minikube, but you can provide any Kubeconfig file and everything else should just work.

Buing a little bit more specific, you have to replace the following lines in your test suite with something that creates a Minikube cluster and returns the path to the Kubeconfig file for accessing your minkube cluster

https://github.com/kubernetes-sigs/cluster-api/blob/e03c7735e46b0bf346754b4a77feddc673e69c44/test/e2e/e2e_suite_test.go#L187-L198

Once you get the kubeconfig path, it is used by the `ClusterProxy` as we are doing today for the kind cluster.

https://github.com/kubernetes-sigs/cluster-api/blob/e03c7735e46b0bf346754b4a77feddc673e69c44/test/e2e/e2e_suite_test.go#L201

Another options, is to use `--e2e.use-existing-cluster`, and `ClusterProxy` will use standard Kubernetes discovery rules to try to access an existing Kubernetes cluster

**Comment by enxebre** [comment]
Hey @Insullone I'm curious what are the constraints you have for wanting to use minikube rather than kind?

**Comment by Insullone** [comment]
@enxebre Currently we are using minikube when node images is CentOS. My team told me that they didn't use kind for CentOS because there was some issues when developing [metal3-dev-env](https://github.com/metal3-io/metal3-dev-env) if they install docker in CentOS at that time.
