### ISSUE TITLE
Periodic tests are failing: exp/addons/controllers.TestAPIs

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#4486]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

According to [testgrid](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-test-main&width=20&sort-by-failures=&exclude-non-failed-tests=100) the TestAPIs test is regularly failing in our periodic tests of the main branch (rough estimate 10-20%)

![image](https://user-images.githubusercontent.com/4662360/114920608-e6535200-9e29-11eb-8f4f-063a1a5f76eb.png)

/kind failing-test

/cc @fabriziopandini

**Comment by vincepri** [comment]
This looks like a flake, do you have time to root cause @sbueringer ?

**Comment by sbueringer** [comment]
Yes. I'll give it a try. I'm guessing it's not one of the flakes which might be caused by CPU starvation so I should be able to reproduce it easier locally.
/assign

**Comment by sbueringer** [comment]
Looks like I found the problem:
https://github.com/kubernetes-sigs/cluster-api/blob/master/exp/addons/controllers/clusterresourceset_controller.go#L484-L487

This returns an error and thus there is no reconciliation triggered (in the test a ConfigMap is created, which should trigger a reconciliation to add a binding to a ClusterResourceBinding)

**Comment by sbueringer** [comment]
One level deeper. GFKForObject tries to calculate the gfk based on TypeMeta:

https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/apiutil/apimachinery.go#L87-L90

TypeMeta looks like this:

![Uploading image.png…]()

**Comment by sbueringer** [comment]
I'm pretty sure `builder.OnlyMetadata` does not work correctly in our case. Alternative hack to get green tests: 
```golang
             Watches(
			&source.Kind{Type: &corev1.ConfigMap{}},
			handler.EnqueueRequestsFromMapFunc(r.resourceToClusterResourceSet),
			//builder.OnlyMetadata,
			builder.WithPredicates(
				resourcepredicates.ResourceCreate(ctrl.LoggerFrom(ctx)),
			),
		).
```

**Comment by vincepri** [comment]
Hmm, we should make sure that the PartialObjectMetadata objects always have the TypeMeta/GVK information filled in.

**Comment by vincepri** [comment]
In this case though the object is coming from controller runtime, which should have the information prepopulated, if that's not the case we should check in CR codebase.

**Comment by sbueringer** [comment]
@vincepri I took a closer look and actually the PartialObjectMetadata never has the TypeMeta information filled in. I'll open a PR later on which makes the error 100% reproducable for debugging. The interesting thing about this test is, the faster the test is run, the more likely it is to fail. So if the test would be a bit more correct it would fail 100%, because the implementation has an issue.

**Comment by vincepri** [comment]
Got it, thanks for the information. It seems like there is a couple of issues here to tackle, feel free to assign any possible PRs in slack.

**Comment by sbueringer** [comment]
Short update. Issue itself is fixed. Only open issue is that the test does not reliable test the expected behavior: https://github.com/kubernetes-sigs/cluster-api/pull/4491

**Comment by fabriziopandini** [comment]
Thanks @sbueringer !
/close
