### ISSUE TITLE
Can we set different variables in E2E config file for each flavor in capi e2e testing framework?

### ISSUE THREAD

**Issue by Insullone** [kubernetes-sigs/cluster-api#4488]
We are using [Cluster API test framework](https://cluster-api.sigs.k8s.io/developer/e2e.html)  for e2e tests. In the E2E config file, there is **variables** property. Can we have a separate set of variables for each flavor? Thanks.

**Comment by Insullone** [comment]
In terms of **flavor**, we use flavors to specify which cluster template file is used in the tests.

**Comment by fabriziopandini** [comment]
I'm not sure I get the use case are you trying to address.

As a little bit of background, the E2E config files is meant to configure a set of tests; if you pass variables via the variables property, it makes sense the same variable has a unique variable across all the tests.

/kind support

**Comment by CecileRobertMichon** [comment]
In CAPZ what we do is set env vars directly in the spec when they are unique to a spec, for eg https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/test/e2e/azure_test.go#L82. For the ones that are different for each spec (for eg. random or depends on the clusterName) we use a BeforeEach: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/test/e2e/azure_test.go#L65
