### ISSUE TITLE
Disambiguate naming for hosted offerings for a given provider. 

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api#449]
We don't have a canonical term for the name of a hosted kubernetes service for a given provider.  Ideally a given provider would allow for the management/provisioning of these hosted deployments but we don't have a canonical name.  Currently, we overload the term "provider". 

/cc @kris-nova @roberthbailey

**Comment by timothysc** [comment]
During our call today we called this "flavors".  
I also thought recipes made sense.  EKS/GKE - Boxed recipes.

**Comment by roberthbailey** [comment]
Wording is being voted on in https://github.com/kubernetes-sigs/cluster-api/issues/480.

**Comment by kris-nova** [comment]
Closing as #480 will track this now
