### ISSUE TITLE
Define machines deletion policies.

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#45]
_From @p0lyn0mial on February 28, 2018 16:57_

The current implementation of `MachineSet` chooses the first machine from the list to delete. As this doesn't provide any guarantees of consistency regarding the order of the items. It is random. We would like to identify some strategies that would provide better approaches for deletion.

_Copied from original issue: kubernetes/kube-deploy#625_

**Comment by rsdcastro** [comment]
_From @p0lyn0mial on February 28, 2018 16:58_

/cc @rsdcastro

**Comment by rsdcastro** [comment]
_From @mvladev on March 7, 2018 10:5_

If I would manually remove one `Machine` from a set of machines I would use the order bellow to determine which to remove:

1. `Machine` needs to be preferably removed - marked with annotation or some other means by human / cluster autoscaler (down-sizing scenario) / other controller
1. Health of the `Machine` - *unhealthy* machines first
1. If all else fails: select one at random

**Comment by ingvagabund** [comment]
@rsdcastro does it make sense to define the delete policies on the level of cloud provider itself? In my case, I am not able to delete an AWS machine directly. Instead, we stop an instance and append a specific suffix. Later on, a bot that periodically checks all AWS instances removes all instances that have the suffix. This way, I can't accidentally delete machines and this approach also helps to make permission more regular so only a small group of people can actually delete instances.

So I can imagine there can be more implementation of "how to delete an instance".

**Comment by mvladev** [comment]
@ingvagabund the physical (API call to the cloud provider) deletion of machines is not part of this issue and it's an implementation detail in your machine controller. It's about which `Machine` resource in K8S to delete during scale down.

Ideally the `scale` subresource should support this functionality, but at the moment it only has a number of desired replicas.

**Comment by ingvagabund** [comment]
@mvladev I put the physical deletion of machines here since this was the closest issue reported to that. You are right it's an implementation detail. Do you think it's worth opening a new issue and starting the conversation on that topic there?

**Comment by mvladev** [comment]
@ingvagabund sounds great!

**Comment by ingvagabund** [comment]
> Do you think it's worth opening a new issue and starting the conversation on that topic there?

https://github.com/kubernetes-sigs/cluster-api/issues/446

**Comment by timothysc** [comment]
Closing in favor of #75
