### ISSUE TITLE
Flaky e2e upgrade tests

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#4502]
**What steps did you take and what happened:**

Our upgrade tests are mostly green, but I think there are a few recurring issues left that we can fix. Example 1.21=> latest (1.22): https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main-1-21-latest

Overview of failed test runs during the last few days:

### 1.18 => 1.19

* [10-04](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-workload-upgrade-1-18-1-19-main/1380998502665949184)
  * kind pipefail issue (new kind version will fix it, so let's ignore it here)
  
### 1.19 => 1.20

* [14-04](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-workload-upgrade-1-19-1-20-main/1382448666509316096)
  * conformance test failed + flaky

* [13-04](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-workload-upgrade-1-19-1-20-main/1382086122078736384)
  * 6/9 nodes ready, conformance tests are not started  (we should have 1 control plane + 3 md + 3 mp nodes)

### 1.20 => 1.21

* [15-04](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-workload-upgrade-1-20-1-21-main/1382743995154698240)
  * conformance tests flaky + timeout after 2h15m

### 1.21 => 1.22 (main)

* [19-04](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-workload-upgrade-1-21-latest-main/1384193838528073728)
  * 7/10 nodes ready, conformance tests are not started  (we should have 1 control plane + 3 md + 3 mp nodes)

* [18-04](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-workload-upgrade-1-21-latest-main/1383831213663326208)
  * 7/10 nodes ready, conformance tests are not started  (we should have 1 control plane + 3 md + 3 mp nodes)

* [16-04](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-workload-upgrade-1-21-latest-main/1383106395573850112)
  * conformance test failed + flaky

So overall, sometimes not all nodes are ready when running the conformance tests and sometimes some of these tests fail. All those issues are in my opinion not a problem of the actual upgrade, but of our test. Some observations:

* `UpgradeMachineDeploymentsAndWait` does not wait until all machines/nodes are ready, only that all machines have the new version: https://github.com/kubernetes-sigs/cluster-api/blob/8bac033459c451a56c2fad2f32e5cc2ae42eaa79/test/framework/machine_helpers.go#L174-L182

* WaitForMachinePoolInstancesToBeUpgraded same, although we have no machines here, but we're not waiting until the nodes are joined to the cluster and ready: https://github.com/kubernetes-sigs/cluster-api/blob/8bac033459c451a56c2fad2f32e5cc2ae42eaa79/test/framework/machinepool_helpers.go#L216-L225

* during the upgrade we update the kube-proxy Daemonset pretty early, we then get image pulls errors because we only have the old kube-proxy images in the old kindest/node images and the new kube-proxy images in the new kindest/node images
  * Not an actual issue for test stability that kube-proxy is not always ready and we don't wait for it during the update.

* We use `workerMachineCount` when starting the conformance test. Imho this should be `2 * workerMachineCount` as we have a MachineDeployment and a MachinePool with each `workerMachineCount` replicas: https://github.com/kubernetes-sigs/cluster-api/blob/master/test/e2e/cluster_upgrade.go#L146-L149

I would suggest to:
* wait until the expected count of nodes in the correct version exist and are ready in the workload cluster before running the conformance test
* start the conformance test with `2 * workerMachineCount`
* I would ignore the kube-proxy issue for now, the conformance test check that all Pods are ready so this shouldn't affect the conformance test

I suspect this will at least fix the node readiness errors and probably also at least some of the conformance test failures. In my experience the conformance test has been very stable over the last few Kubernetes release, so I don't think they are the cause of the flakiness in our tests (we were running >100 conformance tests per day over the last months internally and there were very very rarely any errors).

**What did you expect to happen:**
Tests should be more stable then they are right now.

**Environment:**

- Cluster-api version: latest
- Minikube/KIND version: v0.9.0

/kind failing-test
/area testing

**Comment by fabriziopandini** [comment]
Thanks for the detailed analysis. 
The proposed changes will get rid of 50% of the failures listed above, so +100 to get a PR 

What about changing a little bit things so:
- We reduce the size of the cluster to 1CP + 2MD + 2MP (less stress on the machine resources, faster upgrade test)
- We start the conformance test with 2 * workerMachineCount (so we will test on 4 nodes instead of 3; I don't think that 6 really make a difference given that at the end we are running everything on a single machine, so I think we should always prefer stability over speed)
- We add a new helper that waits for the all the nodes to be ready, or as alternative, we add a flag to existing methods to explicitly ask to wait for node ready (I don't think we should to slow down other tests where waiting for ready is not necessary)

**Comment by sbueringer** [comment]
@fabriziopandini I'll start working on a PR. I agree with all your points. 

I would add a helper to wait for nodes ready and do that immediately before we start the conformance test. This will also speed up the test because we then don't have to wait until the MachineDeployment Machines are ready before starting the MachinePool upgrade.

/assign

**Comment by sbueringer** [comment]
PR: https://github.com/kubernetes-sigs/cluster-api/pull/4515 is now merged. I'll check testgrid the next few days.

**Comment by sbueringer** [comment]
Short update. The last 4 days after the PR was merged we have 5/16 failed tests. But at a first glance it looks like they are all from flaky conformance e2e tests. There was no failure where not all nodes were ready as seen previously, so that should be fixed.

**Comment by fabriziopandini** [comment]
yay!
/close
