### ISSUE TITLE
Should we drop support for kubeadm v1beta1 types?

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4507]
CABPK & KCP in the v1alpha4 branch support kubeadm API v1beta1, v1beta2 and soon v1beta3 (https://github.com/kubernetes-sigs/cluster-api/issues/4445).

This issue is about discussing the option to drop support for kubeadm v1beta1 types, which practically means that capi v1alpha4 cannot be used to create Kubernetes clusters < v1.15.

Now kubeadm v1.15 is N-6 as of today, this makes such release out of the skew support being discussed in https://github.com/kubernetes-sigs/cluster-api/issues/4464; however, given that this is not yet confirmed, I have opened a separated issue to see if we can get this cleanup moving.

/kind cleanup

@vincepri @CecileRobertMichon @sbueringer

**Comment by vincepri** [comment]
I'm ok dropping support in v0.4

**Comment by sbueringer** [comment]
+1 from me too. 
Main argument for me is that supporting n-6 (and it will be a lot more at the time of the release and over the lifetime of v0.4.0) is not sustainable.

**Comment by CecileRobertMichon** [comment]
> Main argument for me is that supporting n-6 (and it will be a lot more at the time of the release and over the lifetime of v0.4.0) is not sustainable.

+1 from me as well with the same reasoning

**Comment by fabriziopandini** [comment]
/milestone next
This should wait after we remove v1alpha3 API (v1alpha3 API  is embedding kubeadm v1beta1 types 😞 )

**Comment by vincepri** [comment]
Could we add a deprecation notice to the package at least?

**Comment by neolit123** [comment]
kubeadm v1beta1 was already removed in 1.22.
i will propose v1beta2 to be deprecated in 1.24 and it will be removed in e.g. 3+ releases.

**Comment by sbueringer** [comment]
> /milestone next
> This should wait after we remove v1alpha3 API (v1alpha3 API is embedding kubeadm v1beta1 types 😞 )

Based on this and the current state of the v1beta1 discussion, we will have to wait until the next api version after v1beta1 (I guess v1beta2) to drop this.

**Comment by sbueringer** [comment]
As discussed in the backlog grooming on 11th February, we'll close this issue for now. We can only drop the kubeadm v1beta1 types once we drop our v1alpha3 types (as they are embedded there). 

(we will drop them then)

/close
