### ISSUE TITLE
Introduce Hardware details in Machine object

### ISSUE THREAD

**Issue by digambar15** [kubernetes-sigs/cluster-api#4519]
**User Story**

As a [developer/user/operator] I would like to fetch hardware details from Machine object, that way It will help preplan the cluster deployment.

**Detailed Description**
 
Actually this use feature is very much necessary in cases of 5G/edge cases where you will look at the hardware details and based on that it will help classify the best fit machines for creating target cluster or extending cluster or deployment of workload on the cluster.
I am putting idea of classification where we will have requirement of specific hardware properties for specific apps/workloads, and based on this requirements, it should classify the machines. This use case will help in many ways, 
1. We will have less problem when it goes for workload deployments
2. We will have cluster ready for specific workload like Edge/5G/AI/ML etc.
3. IT will reduce less failure scenarios.
4. We will always have best fit machines in our cluster.

It would be great if we can develop a separate controller which fetch these details out of respective cloud provider instances and keep it in it's own CR or we can add support for that in machine controller.
There is two level of features needs to be supported
1. Fetch Hardware details from Instances (Cloud Provider)
2. Classification - where we can add labels based on right match hosts for further usages. (This can be dealt later)

/kind feature

**Comment by enxebre** [comment]
>As a [developer/user/operator] I would like to fetch hardware details from Machine object, that way It will help preplan the cluster deployment.

If the details are in a Machine object, doesn't it mean the cluster was already deployed? Or are you referring only to deploy the workloads in an existing cluster where you'd have nodes labeled with hardware details?

**Comment by digambar15** [comment]
Idea is to keep hardware details in machine object so it will used for future workload deployment. Also we can introduce one classification mechanism in place where we can ask user to declare his requirement (Declarative one) and classify the machines which matches to him workload and whichever hosts matches the requirement, classification controller will label the hosts with approapriate workload label so those labels will be picked later. SO here I explained you entire use cases where and how the hardware details are used or utilized. Hope you got my point.

**Comment by vincepri** [comment]
@digambar15 Thanks for filing this issue, as @enxebre mentioned the Machine object is meant to _declare_ the user intent to create/manage an actual machine, not as a tool that can help with planning.


> Actually this use feature is very much necessary in cases of 5G/edge cases where you will look at the hardware details and based on that it will help classify the best fit machines for creating target cluster or extending cluster or deployment of workload on the cluster.

This seems a detail that should be handled outside of Cluster API. Users should make their best decision with the cloud (or bare metal) they chose to use. When Cluster API comes into the picture, it's to create and manage clusters.

> We will have cluster ready for specific workload like Edge/5G/AI/ML etc.

If the idea is to "stamp" clusters, and use them later, #4430 is meant to solve that problem, although in an somewhat opinionated way to start.

> IT will reduce less failure scenarios.

Can you expand on this? Not sure how a templating of clusters would solve failure cases.

> Fetch Hardware details from Instances (Cloud Provider)

Doesn't the Kubernetes node already do this in some way? I'm assuming at this point the cluster has already been created, although if you're thinking a few steps before, that should be part of resource planning that happens outside of Cluster API.

> Classification - where we can add labels based on right match hosts for further usages. (This can be dealt later)

This can already be done today using kubelet node labels before creating a Machine.
