### ISSUE TITLE
Add support for RolloutAfter to MachineDeployments

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#4536]
We have had good feedback about KCP's upgradeAfter field (now being renamed to rolloutAfter). It'd be great to add the same functionality to MachineDeployments.

/kind feature
/milestone v0.4
/help

**Comment by fabriziopandini** [comment]
FYI This issue is somehow related https://github.com/kubernetes-sigs/cluster-api/issues/4450

And interesting nuance is that there is demand both for RolloutAfter <Instant in Time> and RolloutAfter <Time Interval>.

**Comment by chrischdi** [comment]
I assume this is still valid to get implemented to also proceed at #5218 (which was triaged as accepted and this one is required).

@enxebre are you still working on this or would you be ok if I recycle your implementation to file a new PR?

**Comment by vincepri** [comment]
Still a valid feature, we should be looking at rollout as a larger feature as well

**Comment by enxebre** [comment]
@chrischdi I'm not actively working on implementing this, please go for it.

**Comment by sbueringer** [comment]
/close

Done in #8216
