### ISSUE TITLE
Runtime error in capi kubeadm controller manager pods

### ISSUE THREAD

**Issue by rumshenoy** [kubernetes-sigs/cluster-api#4537]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
1. We have a guest cluster of 3 control plane, 200 workers on an environment.
2. Triggered a scale down the  cluster from 3 control plane, 200 worker nodes to 3 control plane, 150 workers
3. Scaled this up back to 3 Control Plane, 200 Workers)
4. Around this time capi-kubeadm-control-plane-controller-manager started seeing several restarts due to CrashLoopBackoff. On further debugging, we found a memory panic issue in manager container of these capi-kubeadm-controller-pod.

```
kubectl get pods -A | grep -v Run
NAMESPACE                                   NAME                                                              READY   STATUS             RESTARTS   AGE
          22s
vmware-system-capw                          capi-kubeadm-control-plane-controller-manager-8565c86bbf-49vgm    1/2     CrashLoopBackOff   54         6d23h
vmware-system-capw                          capi-kubeadm-control-plane-controller-manager-8565c86bbf-hd6fn    1/2     CrashLoopBackOff   56         6d23h
vmware-system-capw                          capi-kubeadm-control-plane-controller-manager-8565c86bbf-pgpmf    1/2     CrashLoopBackOff   56         6d23h
```

```
kubectl logs -n vmware-system-capw capi-kubeadm-control-plane-controller-manager-8565c86bbf-pgpmf manager | grep error
E0426 09:05:34.463486       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
```

```
E0427 18:37:39.361427       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 330 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x17fe5a0, 0x2a33240)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/runtime/runtime.go:48 +0x82
panic(0x17fe5a0, 0x2a33240)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
sigs.k8s.io/cluster-api/controlplane/kubeadm/internal/etcd.(*Client).Close(0x0, 0x8, 0x8)
	/go/src/sigs.k8s.io/cluster-api/controlplane/kubeadm/internal/etcd/etcd.go:171 +0x22
panic(0x17fe5a0, 0x2a33240)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
sigs.k8s.io/cluster-api/controlplane/kubeadm/internal/etcd.(*Client).Members(0x0, 0x1cb40a0, 0xc0000dc048, 0xc001a44ae0, 0x2, 0x2, 0x0, 0x0)
	/go/src/sigs.k8s.io/cluster-api/controlplane/kubeadm/internal/etcd/etcd.go:176 +0x3a
sigs.k8s.io/cluster-api/controlplane/kubeadm/internal.(*Workload).EtcdMembers(0xc004b6f1a0, 0x1cb40a0, 0xc0000dc048, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cluster-api/controlplane/kubeadm/internal/workload_cluster_etcd.go:226 +0x256
sigs.k8s.io/cluster-api/controlplane/kubeadm/controllers.(*KubeadmControlPlaneReconciler).canSafelyRemoveEtcdMember(0xc000406af0, 0x1cb40a0, 0xc0000dc048, 0xc0019bad20, 0xc0010a4490, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cluster-api/controlplane/kubeadm/controllers/remediation.go:182 +0x24c
sigs.k8s.io/cluster-api/controlplane/kubeadm/controllers.(*KubeadmControlPlaneReconciler).reconcileUnhealthyMachines(0xc000406af0, 0x1cb40a0, 0xc0000dc048, 0xc0019bad20, 0xc001a14200, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cluster-api/controlplane/kubeadm/controllers/remediation.go:107 +0x104c
sigs.k8s.io/cluster-api/controlplane/kubeadm/controllers.(*KubeadmControlPlaneReconciler).reconcile(0xc000406af0, 0x1cb40a0, 0xc0000dc048, 0xc0004ed520, 0xc0005b4000, 0x0, 0x0, 0x0, 0xc000866220)
	/go/src/sigs.k8s.io/cluster-api/controlplane/kubeadm/controllers/controller.go:321 +0xc42
sigs.k8s.io/cluster-api/controlplane/kubeadm/controllers.(*KubeadmControlPlaneReconciler).Reconcile(0xc000406af0, 0xc000866220, 0x15, 0xc0008130e0, 0x26, 0xc0005e6c00, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cluster-api/controlplane/kubeadm/controllers/controller.go:211 +0x67f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000fe9a0, 0x1866dc0, 0xc0004621a0, 0xc00075f500)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:255 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000fe9a0, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:231 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0000fe9a0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:210 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00125a2f0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00125a2f0, 0x3b9aca00, 0x0, 0x1, 0xc0000ea060)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00125a2f0, 0x3b9aca00, 0xc0000ea060)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:192 +0x468
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x163e252]
```

**What did you expect to happen:**
`capi-kubeadm-control-plane-controller-manager` pod to be Running

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
[logs-current.txt](https://github.com/kubernetes-sigs/cluster-api/files/6386924/logs-current.txt)
[logs-previous.txt](https://github.com/kubernetes-sigs/cluster-api/files/6386927/logs-previous.txt)

**Environment:**
- Cluster-api version: v0.3.12

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by neolit123** [comment]
this defer here is problematic:
https://github.com/kubernetes-sigs/cluster-api/blob/bfc6f80add5c21b8dc2b704951f42bc14708ebc4/controlplane/kubeadm/internal/workload_cluster_etcd.go#L47

as it would act on the entire wrapping function ReconcileEtcdMembers and not per `etcdClient` in each loop iteration.

cc @vincepri 
https://github.com/kubernetes-sigs/cluster-api/commit/e38df08235e2fadea502df775232424033b4ca43

/priority important-soon
/help

**Comment by vincepri** [comment]
> as it would act on the entire wrapping function ReconcileEtcdMembers and not per etcdClient in each loop iteration.

Why is that a problem? I was looking at the exact same code: although the defer(s) run after `ReconcileEtcdMembers` returns, even if they remain open until the end, that should be fine? How would that cause a panic?

**Comment by neolit123** [comment]
my mistake, the defers in ReconcileEtcdMembers should be fine.

the first panic is here:
https://github.com/kubernetes-sigs/cluster-api/blob/bfc6f80add5c21b8dc2b704951f42bc14708ebc4/controlplane/kubeadm/internal/etcd/etcd.go#L176

since something has `nil`-ed the c.EtcdClient value and then this also panics:
https://github.com/kubernetes-sigs/cluster-api/blob/bfc6f80add5c21b8dc2b704951f42bc14708ebc4/controlplane/kubeadm/internal/etcd/etcd.go#L171

**Comment by neolit123** [comment]
i tried to to understand more what's happening here, but went out of ideas.
one native fix is to return early in these functions if `c.EtcdClient == nil`, but that's not great.

**Comment by sbueringer** [comment]
Hm, also looked at. I also cannot see a way how this panic can occur. `EtcdClient` is only written by `newEtcdClient` and that's it.

Only way to debug I can see is make it reproducable and either add a lot of log statements or try to get something like a Mozilla rr trace (for context: https://www.jetbrains.com/help/go/debugging-with-mozilla-rr.html#collecting-mozilla-rr-traces)

**Comment by vincepri** [comment]
@rumshenoy Are you able to reproduce the issue again, or better write an integration / unit test that can reproduce it consistently?

/priority awaiting-more-evidence
/milestone Next

**Comment by fabriziopandini** [comment]
/lifecycle frozen
Finally managed to reproduce
/assign
