### ISSUE TITLE
Remove deprecated hyperkube image support in ClusterConfiguration/v1alpha4

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4542]
**Detailed Description**
The `UseHyperKubeImage` field is going to be removed in kubeadm v1beta3 API, see https://github.com/kubernetes/kubernetes/pull/101537/files

We should do the same in ClusterConfiguration/v1alpha4

**Anything else you would like to add:**
Given that 
- hyperkube images are not available on gcr since v1.16 and the project has been discontinued (See https://github.com/kubernetes/kubeadm/issues/1889)
- I'm not aware of anyone using this in CAPI

I suggest that we simply drop this field during conversions.
@vincepri @CecileRobertMichon opinions?

/kind feature

**Comment by ludusrusso** [comment]
/assign 

tnx @fabriziopandini

**Comment by CecileRobertMichon** [comment]
👍

**Comment by vincepri** [comment]
I'm fine dropping the field.
