### ISSUE TITLE
Pass down annotations from Machine to provider specific machine resources

### ISSUE THREAD

**Issue by schrej** [kubernetes-sigs/cluster-api#4543]
**User Story**

As a user I'd like to specify annotations as part of a MachineDeployment and use them on the provider specific machine resources to pass parameters to a custom controller that assigns static IP addresses.

**Detailed Description**

It's possible to specify both labels and annotations as part of the `spec.template.metadata` of a `MachineDeployment`. Both get passed down to the `MachineSet` and subsequently the `Machine` resources.
The provider specific machine resource only gets the labels, and not the annotations.

Annotations specified on `Machine`s should be passed down to the provider specific resources, which is currently only done for labels.

**Anything else you would like to add:**

[discussion in #cluster-api-vsphere](https://kubernetes.slack.com/archives/CKFGK3SSD/p1619621933222400)

/kind feature

**Comment by fabriziopandini** [comment]
Only one note from my side.
We should made sure we are consistent in how label & annotations are passed down to machines across the entire table, that means to consider also KCP (control plane providers) and MachinePool.
Those could be eventually tracked in separated issues and addressed in separated PR; ideally we should get a picture of required changes in those area before merging MachineDeployments changes, so we can properly plan for addressing deltas in v1alpha4.

**Comment by schrej** [comment]
I agree. I already planned to extend the tests for the `util.GenerateTemplate()` function to ensure the variable precedence is consistent.
