### ISSUE TITLE
Remove unused DNSAddOnType constants from kubeadm/v1alpha4 

### ISSUE THREAD

**Issue by ludusrusso** [kubernetes-sigs/cluster-api#4546]
**User Story**

As a developer I would like to live the code to be as simple as possible. In my PR #4516 I left this piece of code from v1alpha4 that I think can be safely removed: https://github.com/kubernetes-sigs/cluster-api/blob/9d825629d89c9394ddbdf1484fc9e389cf544146/bootstrap/kubeadm/api/v1alpha4/kubeadm_types.go#L157-L166 

@fabriziopandini if you are ok with this I can submit a PR!

**Comment by sbueringer** [comment]
@ludusrusso If those are just unused constants, you can go ahead and open a PR to drop them.
