### ISSUE TITLE
clusterctl multitenancy doc needs updating 

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#4548]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

A user was following https://cluster-api.sigs.k8s.io/clusterctl/commands/init.html#multi-tenancy in Slack, and found that it's outdated against the intended model from v1alpha4.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 

Mostly a reminder to @randomvariable

**Comment by fabriziopandini** [comment]
This is already fixed on the main branch of docs.
Also, more cleanups on clusterctl/docs will happen when https://github.com/kubernetes-sigs/cluster-api/issues/4056 will be implemented
/close

**Comment by randomvariable** [comment]
Ah, ok. Thx.
