### ISSUE TITLE
Backport Allow clusterctl config cluster --from on empty clusters

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4556]
https://github.com/kubernetes-sigs/cluster-api/pull/4553  fixed a version check too much restrictive preventing to run clusterctl config cluster --from on an empty cluster. we should back-port this in the release-0.3 branch

/kind bug
/milestone v0.3
/help
/good-first-issue

**Comment by Evalle** [comment]
I can take care of it.
/assign

**Comment by Evalle** [comment]
This can be closed, see https://github.com/kubernetes-sigs/cluster-api/pull/4560 
FYI @fabriziopandini
