### ISSUE TITLE
Specify extra condition checks before deleting a Machine

### ISSUE THREAD

**Issue by MohiK98** [kubernetes-sigs/cluster-api#4563]
**User Story**

As an operator I would like to specify extra condition checks before deleting a machine for better cluster management and smoother upgrade.

**Detailed Description**

Currently I'm integrating cluster api with the cloud company IaaS I'm working and here is the scenario I think upgrade process can go smoother.

Right now when I upgrade a MachineDeployment version, the following happens:
1- Create a new Machine with new version
2- Wait for it to become ready
3- Drain one of the old nodes
4- Delete the selected old node

But when I upgrade a cluster workload, pvcs will not be attached for a couple of minutes before the CSI pods are running in the new node. I'm using ceph-csi and when a node is drained the pvcs are detached and pods with pvcs have to wait for a new node with a running csi pod to be run. If extra options can be added to the MachineDeployment API, we can wait for the condition (which is a ready csi pod on the new node) and the upgrade process will have no down time. In my case the upgrade process can have up to 5 minutes of down time. It can even get worse when an issue happens when the kubelet is trying to run the CSI pods and all the pods with pvc have to wait for a long time until an administrator comes for help.

Conditions can be specified by providing a label selector and a status for them (e.g. Ready). If the feature request is accepted, I'm willing to help to develop and test it.

There can be other workarounds by adding custom ready conditions to Nodes (e.g. extra flags on kubelet) but I could not find it anywhere.

/kind feature

**Comment by vincepri** [comment]
Would Machine deletion hook https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20200602-machine-deletion-phase-hooks.md suffice for this use case?

**Comment by MohiK98** [comment]
Yes it seems perfect. Since the proposal's status is implemented, can I use it now? just asking to make sure 😄

**Comment by vincepri** [comment]
Yes, the code has already been implemented and ready to go. We should add some docs to our book

**Comment by MohiK98** [comment]
That would be great, Thanks! I'm closing the issue.
