### ISSUE TITLE
Implement support for HollowMachines in CAPD

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4565]
**User Story**
As a developer I would like to stress test CAPI for improving stability
As a developer I would like to speed up local CAPI development/test cycles
As a developer I would like to reduce E2E jobs duration & footprint
As a developer I would like to have some alternative to DockerMachines for testing autoscaler

**Detailed Description**
This issue proposes the implementation of HollowMachines in CAPD, based on kubemark/hollow kubelet.

HollowMachines will be super fast to provision and very cheap in term of resources; this makes HollowMachine a nice replacement for DockerMachines whenever the machine is not expected to host workloads, which is a good portion of our the workers machines in the current E2E tests.

Once DockerMachines are replaced by HollowMachine where possible, it will be possible to increase the number of nodes in the same tests. 

**Anything else you would like to add:**
The idea was originally proposed by @benmoss, who also pioneered the first implementation in this area.

I would like to revive this effort, but taking a different path in implementation by adding a new Machine type to CAPD instead of creating a whole new provider, so the delta diff will be minimal and easier to maintain…

/kind feature
/area testing
/assign
/lifecycle active

@sbueringer @vincepri @dims

**Comment by dims** [comment]
cc @stmcginnis

**Comment by sbueringer** [comment]
Sounds like a great improvement to me!

**Comment by elmiko** [comment]
i think this is a cool idea, would it replace the current kubemark provider?

https://github.com/kubernetes-sigs/cluster-api-provider-kubemark

**Comment by elmiko** [comment]
i would like to maximize our efforts around kubemark. whether in capd or its own provider, i think it will be valuable.

for me, the main difference between this implementation and the standalone kubemark provider is that the latter presents an option for deploying onto non-capd clusters. otherwise it seems like functionally they would be the same.

**Comment by fabriziopandini** [comment]
/close
works happening in https://github.com/kubernetes-sigs/cluster-api-provider-kubemark
