### ISSUE TITLE
Introduce dry-run functionality to init

### ISSUE THREAD

**Issue by joshrosso** [kubernetes-sigs/cluster-api#4572]
**User Story**

A user may wish to persist the YAML that is part of a `clusterctl init` to disk, prior to running `init`. This can be achieved by introducing a `dry-run` flag on the `init` command. When this flag is present, we would persist all relevant YAML to the current directory.

If there is not a way to do this currently, and we are interested in it, I'd be happy to implement it.

/kind feature

**Comment by CecileRobertMichon** [comment]
The closest thing we have to this right now is `clusterctl config provider -o yaml`. You could do something like:

```
clusterctl config provider --core cluster-api -o yaml > capi-components.yaml
clusterctl config provider --bootstrap kubeadm -o yaml > cabpk-components.yaml
clusterctl config provider --control-plane kubeadm -o yaml > kcp-components.yaml
clusterctl config provider --infrastructure azure -o yaml > capz-components.yaml
```

This wouldn't include things like cert-manager though.

**Comment by joshrosso** [comment]
@CecileRobertMichon hey, I didn't know that. Very cool.

I wonder if there's still value in a true "dry run" for `init`. I know I'd like it a lot for the experiments I'm currently running.

Let me know!

**Comment by xannz** [comment]
I was looking for this functionality for my use case. I would like to set up the management cluster via ArgoCD and a dry run flag would be really useful here to retrieve all the needed yaml manifests.

**Comment by vincepri** [comment]
/priority backlog
/milestone Next

We could consider reusing `clusterctl generate` to achieve the desired outcome. Having a `--dry-run` flag as part of `init` that outputs yaml seems a weird UX, so we'd have to think about it more.
