### ISSUE TITLE
Panic when calling clusterctl describe cluster on a cluster without a controlPlaneRef

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#4580]
**What steps did you take and what happened:**

According to PR https://github.com/kubernetes-sigs/cluster-api/pull/4343 `clusterctl describe cluster` panics when called on a Cluster without a `controlPlaneRef`

**What did you expect to happen:**
Should not panic!

**Anything else you would like to add:**
I think PR https://github.com/kubernetes-sigs/cluster-api/pull/4343 can be used as a basis (+the open review comments)

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by khos2ow** [comment]
By the look of it #4343 was abandoned with some outstanding review comments. If that's the case I can revive it and get a crack at it.

**Comment by sbueringer** [comment]
Fixed in https://github.com/kubernetes-sigs/cluster-api/pull/5228

/close
