### ISSUE TITLE
Failures in deferred calls not captured

### ISSUE THREAD

**Issue by stmcginnis** [kubernetes-sigs/cluster-api#4586]
**What steps did you take and what happened:**

Great suggestion from Stefan in https://github.com/kubernetes-sigs/cluster-api/pull/4499#discussion_r628486582

> We're probably doing this all across the code base. But I'm a bit concerned about just ignoring errors in those cases. I know
> it's not that critical in tests but let's discuss it :)
>
> Can you take a look at: https://github.com/thanos-io/thanos/blob/main/docs/contributing/coding-style-guide.md#reliability
>
> WDYT about the pattern they are using with defer runutil.CloseWithErrCapture(&err, f, "close file") ?

I think it would be a good idea to use something like that to be able to capture failure information in deferred calls.

**What did you expect to happen:**

It would be great to capture failure information rather than silently swallowing problems.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug

/assign

**Comment by sbueringer** [comment]
@vincepri No, at least not yet. Although I'm not sure if there's a linter we could enable via golangci-lint

Errors in defer calls are pretty frequently ignored, especially for thing like file.Close.

**Comment by sbueringer** [comment]
> Doesn't the linter complain if the error is ignored?

Apparently we have linter for it. gosec finding G307 detects some of these cases. The one finding we have there seems reasonable: `G307: Deferring unsafe method "Close" on type "*os.File`. I'll open a PR to fix that one in the context of #4622

**Comment by vincepri** [comment]
@sbueringer Is there any action items we have as part of this issue? If we can rework it to be more specific and provide a potential solution, we can also mark it as good-first-issue

**Comment by sbueringer** [comment]
@vincepri In my opinion we have two options depending on if we want to fix `G307: Deferring unsafe method "Close" on type "*os.File`:

1. if not: we should move the exclude of G307 above `# The following are being worked on to remove their exclusion. This list should be reduced or go away all together over time.` in .golangci.yml

2. if yes: I would propose it as described in the Thano style guide by implementing a `CloseWithErrCapture` util func which we can then use like this: `defer runutil.CloseWithErrCapture(&err, f, "close file")`


I think option 1 might not be worth help wanted it's just moving one line in the linter config. Option 2 would be good for good-first-issue. We just should decide first :)

**Comment by sbueringer** [comment]
Same for me. Let's see if @CecileRobertMichon or @fabriziopandini have a strong opinion on that. Otherwise I would adjust the linter config and close the issue.

**Comment by fabriziopandini** [comment]
+1 to leave as it is
