### ISSUE TITLE
Refactor tests using plain go tests + envtest instead of ginkgo

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4588]
As documented in https://cluster-api.sigs.k8s.io/developer/testing.html, we agreed to use plain go tests + envtest instead of ginkgo for all the integration tests (E2E test should continue to use ginkgo for the time being).

This issue is for tracking this effort.

/area testing
/kind cleanup
/help

**Comment by vincepri** [comment]
Do we need a tracking issue for this? To make it a bit better, especially for first time contributors, it might be good to enumerate in which packages we still need work to do.

**Comment by fabriziopandini** [comment]
@mboersma great to sees so much progress in this domain, thanks!
