### ISSUE TITLE
Remove clusterctl config cluster and provider subcommands

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api#4590]
**User Story**

`clusterctl config cluster` and `clusterctl config provider` are deprecated in favor of `clusterctl generate cluster` and `clusterctl generate provider` respectively. We will be supporting the old commands for `0.4.x` release, but will have to be removed in the subsequent release.

/kind feature

**Comment by sbueringer** [comment]
Has been done already at some point.

/close
