### ISSUE TITLE
Docker provider does not work

### ISSUE THREAD

**Issue by charleszheng44** [kubernetes-sigs/cluster-api#4593]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
I followed the quick start https://cluster-api.sigs.k8s.io/user/quick-start.html
1. create kind cluster
```bash
kind create cluster
```
2. download the clusterctl v0.3.16
3. initialize the docker infrastructure
```bash
./clusterctl init --infrastructure docker
```
4. generate the cluster configuration
```bash
clusterctl config cluster capi-quickstart --flavor development \
  --kubernetes-version v1.18.16 \
  --control-plane-machine-count=3 \
  --worker-machine-count=3 \
  > capi-quickstart.yaml
```
5. apply the configuration yaml
```bash
kubectl apply -f capi-quickstart.yaml
```
6. try to generate the capi-quickstart.kubeconfig 
```bash
./clusterctl get kubeconfig capi-quickstart > capi-quickstart.kubeconfig
```
but got error message 
```bash
Error: "capi-quickstart-kubeconfig" not found in namespace "default": secrets "capi-quickstart-kubeconfig" not found
```

**What did you expect to happen:**
The docker provider works out of box

**Anything else you would like to add:**
I check the capd-manager logs, and saw the following error message
```bash
E0510 18:58:03.869338       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create helper for managing the externalLoadBalancer: failed to list containers: failed to list nodes: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster --format '{{.Names}}\\t{{.Label \"io.x-k8s.kind.cluster\"}}\\t{{.Image}}' --filter label=io.x-k8s.kind.cluster=capi-quickstart --filter label=io.x-k8s.kind.role=external-load-balancer\" failed with error: exit status 1" "controller"="dockercluster" "name"="capi-quickstart" "namespace"="default"
```

I have tested the `listConatiners` function in the docker/util.go, which worked as expected. I checked the manager container of the capd-manager pod and it does not contain the `docker` command in its PATH. I am not sure if this is the cause.

**Environment:**

- Cluster-api version: v0.3.16
- Minikube/KIND version: v0.10.0
- Kubernetes version: (use `kubectl version`): v1.20.2
- OS (e.g. from `/etc/os-release`): ubuntu 20.04

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
/triage needs-information

We have a good signal in CI for the quick start with CAPD, so I'm inclined to think this is a local problem.
Looking at the sequence of actions, it seems that the kind cluster is created without the required mount of the docker socket; this prevents the cluster to be created, and the secret with the kubeconfig file too.

See the Docker infrastructure provider - CAPD tab into https://cluster-api.sigs.k8s.io/user/quick-start.html#install-andor-configure-a-kubernetes-cluster for more instructions on how to create the kind cluster for CAPD

**Comment by charleszheng44** [comment]
Following is the output of the `docker ps`

```bash
CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS          PORTS                                NAMES
09933b7c79b0   kindest/haproxy:2.1.1-alpine   "/docker-entrypoint.…"   18 minutes ago   Up 18 minutes   34595/tcp, 0.0.0.0:34595->6443/tcp   capi-quickstart-lb
611fc7bdca7e   kindest/node:v1.20.2           "/usr/local/bin/entr…"   21 minutes ago   Up 21 minutes   127.0.0.1:42493->6443/tcp            kind-control-plane
```
looks like the dockermachine_controller tries to get the manifest of kindest/node:v1.18.16, while the kindest/node in use is v1.20.2, do you think this is the cause?

**Comment by fabriziopandini** [comment]
The key message to understand what is going on is 
```
{"Namespace":"default","Name":"capi-quickstart-control-plane-fmm2l"} "machine"="capi-quickstart-control-plane-j6c68"
Unable to find image 'kindest/node:v1.18.16' locally
docker: Error response from daemon: manifest for kindest/node:v1.18.16 not found: manifest unknown: manifest unknown.
```

This is because we are relying on kind published images for node, and apparently there is not an image published for v1.18.16 (see https://hub.docker.com/r/kindest/node/tags?page=1&ordering=last_updated). You can build this image locally using kind, but if you don't have special needs, the easiest way forward is to use another Kubernetes version.

For more context see this [note](https://master.cluster-api.sigs.k8s.io/clusterctl/developers.html?highlight=kindest%2F#select-the-appropriate-kubernetes-version) in the latest release of the Cluster API book

**Comment by vincepri** [comment]
That sounds good to me

**Comment by charleszheng44** [comment]
The latest cluster-api book has changed the `kubenetes-version` to v1.19.7 for the docker provider.
