### ISSUE TITLE
[node attestation] add a controller to approve kubelet CSRs

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api#4608]
**Detailed Description**

following the merge of the CAEP, I'm opening an issue to track the addition of the node attestation controller and its interface, to handle CSR approval for Kubelet client/server certificates, this issue should also track test coverage for the feature

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by yastij** [comment]
FYI @randomvariable @vincepri @fabriziopandini

**Comment by fabriziopandini** [comment]
/close

so if someone will revive the work on this CAEP, he could make his own work breakdown.
