### ISSUE TITLE
[node attestation] introduce capi-exec-auth CLI to issue CSRs 

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api#4611]
**Detailed Description**

following the merge of the CAEP, I'm opening an issue to track the introductioin of `capi-exec-auth` CLI so that the kubelet config can use it to either:

- read certificates from disk when they're valid
- issue CSRs to renew client/server certificates when they're near expiry

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature
/priority important-soon

**Comment by fabriziopandini** [comment]
/close

so if someone will revive the work on this CAEP, he could make his own work breakdown.
