### ISSUE TITLE
Use systemd cgroupDriver in CAPD

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#4621]
**User Story**

As a  operator I would like to use the (kubeadm) default cgroupDriver (which is systemd) with CAPD.

**Detailed Description**

Starting with kubeadm 1.21 the default cgroupDriver is systemd. With the upcoming kind version we have to pin CAPD to cgroupDriver cgroupsfs, because it won't work otherwise.

More context:
* PR to pin cgroupDriver to cgroupfs: https://github.com/kubernetes-sigs/cluster-api/pull/4614
* Issue to upgrade to kind v0.11: https://github.com/kubernetes-sigs/cluster-api/issues/4503
* Slack discussion: https://kubernetes.slack.com/archives/C8TSNPY4T/p1620923791417000
* kind systemd issue: https://github.com/kubernetes-sigs/kind/issues/1726

**Anything else you would like to add:**

Goal is essentially to revert https://github.com/kubernetes-sigs/cluster-api/pull/4614 once https://github.com/kubernetes-sigs/kind/issues/1726 has been implemented and is usable for us.

/kind feature

**Comment by fabriziopandini** [comment]
For track of records I'm reporting here some some of my notes about the discussion that lead to opening this issue.
- We should to stick to kind default, because kind's team is doing an amazing job in hardening the kindest/node image (this is why we implemented and #4614).
- We are going to wait for kind to switch to systemd cgroupDriver, and possibly, we should figure out a way to help in making this happen

**Comment by sbueringer** [comment]
/remove-lifecycle stale
/lifecycle frozen

We still want to go back to systemd when it's possible.

**Comment by sbueringer** [comment]
> kubernetes v1.24.0+ and kind v0.13.0+ will do this.
> https://github.com/kubernetes-sigs/kind/issues/1726#issuecomment-1122697645

**Comment by fabriziopandini** [comment]
@sbueringer thanks this is good news.
Might be also an opportunity to start using version-aware patches across the board.

**Comment by sbueringer** [comment]
Just fyi, we might have to implement this in https://github.com/kubernetes-sigs/cluster-api/pull/6480 to get v1.24 to work.
