### ISSUE TITLE
Tests should use a randomly generated namespace

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api#4629]
**What steps did you take and what happened:**

In refactoring the unit/integration tests for #4588, we noticed that they use the "default" namespace, and not always through the `v1.NamespaceDefault` constant.

**What did you expect to happen:**

We should review and unify the use of namespaces in the tests so that each uses a randomly-generated namespace to avoid collision, and so we are not polluting the `default` namespace. See comments [here](https://github.com/kubernetes-sigs/cluster-api/pull/4615#discussion_r633466198).

**Anything else you would like to add:**

**Environment:**

/kind bug
/area testing

**Comment by fabriziopandini** [comment]
+100 to this.
It is also compliant with what we are recommending in https://cluster-api.sigs.k8s.io/developer/testing.html#quick-reference

**Comment by sbueringer** [comment]
Also the same way as the Kubernetes conformance tests are working and it's working great there, so it should also be a good fit for us.

**Comment by hzliangbin** [comment]
@mboersma hi, are you working on this already?

**Comment by mboersma** [comment]
@hzliangbin no, please have at it, and thanks!

I looked at it briefly and my only thoughts are:

- it will be a lot of work
- maybe we can use testEnv.CreateNamespace(ctx, t.Name())

**Comment by sbueringer** [comment]
@hzliangbin  I would suggest to implement it first on a relatively small package to establish the correct way to do it and then post a list like here https://github.com/kubernetes-sigs/cluster-api/issues/4588#issuecomment-838174633 in this issue to give an overview and possibly crowdsource it (your choice).

**Comment by sbueringer** [comment]
@fabriziopandini Based on the results in https://github.com/kubernetes-sigs/cluster-api/issues/5029#issuecomment-889441182 the PRs helped a lot to make the tests repeatable on a consistently running kind cluster. WDYT about opening a follow-up issue to do the same for other global resources (according to my tests in the linked comment we have the same issue in a few tests which use hard-coded node names)

**Comment by fabriziopandini** [comment]
@sbueringer global resources (like nodes, CRDs, etc) or things generated by other components (like Kubeadm config maps or CoreDNS config map) are not good candidates for this effort, but I'm +1 to apply similar changes whenever possible or at least let's make sure we do a proper cleanup after each test
@killianmuldoon ^^

**Comment by sbueringer** [comment]
I'll take a closer look later today and probably close this issue and open a follow-up issue.

**Comment by sbueringer** [comment]
I went through the repo and grepped for "default" and "NamespaceDefault". It looks like we now only use the default namespace in combination with fake client (as there are ~500 occurrences I didn't look in very close detail). I would close this issue as at least the vast majority is fixed. If someone has a concrete example feel free to reopen / open an issue.

As a follow-up I will open an issue (roughly in the next 1-2 weeks) which will focus on "can we run all our tests repeatedly using the same kind cluster". This should catch cases all cases where cluster-wide resources with a hard-coded name are used (namespaces, nodes, ...). I'll also scope it in a way that we make sure we clean up cluster-wide resources, e.g. currently we leak a lot of nodes with random-generated name.
