### ISSUE TITLE
Update to v1alpha4 imports did not update tests

### ISSUE THREAD

**Issue by stmcginnis** [kubernetes-sigs/cluster-api#4632]
**What steps did you take and what happened:**

While updating imports I noticed there are several places where an alias of something like `clusterv1alpha1`
and `clusterv1alpha2` were both changed to import `v1alpha4`. These tests appear to be testing the
migration between these versions, but now are testing the same thing.

This happened in commit e73e3d9021e5df61ea2861be6f73698a031a63c3 and a specific instance can be found here:

https://github.com/kubernetes-sigs/cluster-api/commit/e73e3d9021e5df61ea2861be6f73698a031a63c3#diff-2c830e010d7866e116a0065e20d45b39d31e0e348a5936f13c79948b0cf63347R25

In at least several of these cases, it appears this error was already introduced when switching to `v1alpha2`.

All of these cases should be reviewed to make sure they actually are still testing what we think they are testing.

/kind bug
/area testing
/area api

**Comment by CecileRobertMichon** [comment]
@vincepri @fabriziopandini this one should probably be release blocking, wdyt?

**Comment by fabriziopandini** [comment]
I'm +1 to get this fixed ASAP
I would be great if we make a list of the occurrence of this problem.

(I have searched for "sigs.k8s.io/cluster-api/api/v1alpha4", and I have found only one file with two times the same import, util/conversion/conversion_test.go; here it should not be relevant, given we are testing the marshal annotation, but nevertheless it would be nice to get this fixed)
