### ISSUE TITLE
Document CRS API does not allow empty selectors

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4635]
As per https://github.com/kubernetes-sigs/cluster-api/pull/4036#issuecomment-786981907 we should improve the CustomResourceSet API documentation (https://github.com/kubernetes-sigs/cluster-api/blob/f5dec18def709194f81a6106943ad80a88e8b4e5/exp/addons/api/v1alpha4/clusterresourceset_types.go#L40) making it explicit that empty selector are not allowed. 

/kind documentation
/help
/good-first-issue

**Comment by enxebre** [comment]
@fabriziopandini Title mention CRS but the PR desc references MHC, is this intended?

**Comment by sedefsavas** [comment]
Maybe we can add a generic note for this, something like `selectors in cluster-api projects should not "match all" if left empty`.
Considering we are going to be selecting all namespaces explicitly for multitenancy too, this will apply to all selectors.

**Comment by sbueringer** [comment]
I didn't look it up, but if it's not allowed should we block it via the webhook? (maybe we're already doing it)

**Comment by sedefsavas** [comment]
Yes, already not allowing empty selectors in the webhook for both CRS and MHC.

**Comment by fabriziopandini** [comment]
The issues is about CRS - this was the scope of the original PR -. I have fixed the link to the API (Not sure why the original comment was referring to MHC).

If we want to broaden the scope I'm fine with this, but given this is a good first issue let provide as much detail as we can so also newcomers can take up the issue.

**Comment by Madhur13** [comment]
Hello @fabriziopandini 
I am new to this community. Would like to get started with this good first issue. Can you please assign this to me?
