### ISSUE TITLE
KubeadmControlPlane: Support metadata for machines and propagate to all templates

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#4636]
This issue is to track the support of the adding `clusterv1.ObjectMeta` object information to the KCP object.

Currently, we have a single field called `InfrastructureTemplate` under `spec` which gives information to KCP on how to create the infrastructure of machines https://github.com/kubernetes-sigs/cluster-api/blob/06f58a66353d5a22a2849f2f516ee71e4664c323/controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go#L56-L58

For this issue, we propose a breaking api change to streamline the machine template and align a bit with MachineDeployments as well. The API would look as follows:

```go
type KubeadmControlPlaneSpec struct {
// [...]
	MachineTemplate KubeadmControlPlaneMachineTemplate `json:"machineTemplate"`
// [...]
}

type KubeadmControlPlaneMachineTemplate struct {
	// Standard object's metadata.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	// +optional
	ObjectMeta clusterv1.ObjectMeta `json:"metadata,omitempty"`

	// InfrastructureTemplate is a required reference to a custom resource
	// offered by an infrastructure provider.
	Infrastructure corev1.ObjectReference `json:"infrastructure"`
}
```

The conversion webhooks are going to take care of the following:
- Restore the ObjectMeta information which is not going to be available in v1alpha3.
- Convert the ObjectReference from `spec.infrastructureTemplate` to `spec.machineTemplate.infrastructure` (and vice versa).

Moreover, the `ObjectMeta` information is going to be passed to all templated objects, such as:
- Machine
- InfrastructureMachine (unstructured, dependent on the object reference)
- KubeadmConfig

/kind release-blocking
/kind api-change
/area api

/milestone v0.4

**Comment by schrej** [comment]
In MachineDeployment and MachineSet the reference is called `infrastructureRef`, so maybe we should be consistent here?
