### ISSUE TITLE
Operator: Add ObservedGeneration field to provider status

### ISSUE THREAD

**Issue by alexander-demichev** [kubernetes-sigs/cluster-api#4642]
Add ObservedGeneration field to provider status. This is a common pattern for other CAPI resources.

https://github.com/kubernetes-sigs/cluster-api/pull/4520#discussion_r625632177

/kind feature
/area operator

**Comment by asalkeld** [comment]
note this is implemented in https://github.com/kubernetes-sigs/cluster-api/pull/4926

**Comment by fabriziopandini** [comment]
@alexander-demichev any objection to closing this now that the work is being moved in a separated repo?

**Comment by alexander-demichev** [comment]
👍
/close
