### ISSUE TITLE
Refactor clusterctl generate - add --raw option to generate provider

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api#4650]
**User Story**

Part 2 of #3360 

#4584 refactored config cluster and provider subcommands to generate subcommands. We want to add `--raw` option to `clusterctl generate provider` which will skip yaml processing (not replace env variables). This also includes refactoring `skipVariables` to `skipProcess` in code. 

As a [developer/user/operator] I would like to [high level description] for [reasons]

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by vincepri** [comment]
Is there any use case for the `--raw` variable? Not opposed to it, just trying to understand the reasoning + get some requirements in place.

**Comment by shysank** [comment]
This is to replicate the current [behavior](https://github.com/kubernetes-sigs/cluster-api/issues/3360#issuecomment-662681629) of `clusterctl config provider -i aws -o yaml` which does not do variable substitution.
