### ISSUE TITLE
MachineDeployment version validation

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api#4651]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

In a MachineDeployment resource spec, if you declare a `spec.template.spec.version` value that omits the `v` prefix (e.g., "1.19.10" instead of "v1.19.10") a strange side-effect happens: the MachineDeployment gets stuck in a ScalingUp state:

```
NAME                        PHASE       REPLICAS   READY   UPDATED   UNAVAILABLE
acse-test-capz-40a35-md-0   ScalingUp                                1
```

In the capi-controller logs you see a continual stream of errors like this, suggesting that the MachineDeployment continues to try to recreate itself:

```
E0521 20:36:49.912570       1 machinedeployment_controller.go:145] controller-runtime/manager/controller/machinedeployment "msg"="Failed to reconcile MachineDeployment" "error"="machinesets.cluster.x-k8s.io \"acse-test-capz-40a35-md-0-567db869fd\" already exists" "name"="acse-test-capz-40a35-md-0" "namespace"="default" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="MachineDeployment" 
```

Upon discovering that the version was missing the "v", editing the MachineDeployment to change the version to "v1.19.10" quickly unblocked forward progress:

```
$ k get machinedeployments
NAME                        PHASE     REPLICAS   READY   UPDATED   UNAVAILABLE
acse-test-capz-40a35-md-0   Running   1          1       1
```

Most curious is the fact that the cluster is otherwise running fine, with the node that correlates to the above MachineDeployment in a running state. This edge case was detected upon attempting (and failing) to scale the MachineDeployment out to 3.

**What did you expect to happen:**

I would expect one of the following:

1) Version validation to be enforced consistently across all resource types. In my repro scenario, both the KubeadmControlPlane and MachineDeployment resources had a value of "1.19.10" (missing the "v" prefix). It seems that the "v" prefix is automatically added to the spec for KubeadmControlPlane resources:

```
$ k get kubeadmcontrolplane acse-test-capz-40a35-control-plane -o yaml | grep 'version: v'
  version: v1.19.10
```

I would expect the same to be true for MachineDeployments as well

2) If there is a reason for MachineDeployment version validation to be more strict, I'd expect that validation failure to be clearly expressed in the event and controller logs, for quicker discovery.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v1alpha4
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): 1.19.10
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04-LTS

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
This issue is somehow related to this ticket https://github.com/kubernetes-sigs/cluster-api/issues/3697

**Comment by vincepri** [comment]
cc @CecileRobertMichon

**Comment by CecileRobertMichon** [comment]
> This issue is somehow related to this ticket #3697

this is a little different, the issue here is that we are not normalizing the k8s version (adding `v` prefix) in the MachineDeployment webhook the same way we do for the KCP, Machine, and MachinePool webhooks. This results in Machines getting created correctly with the v prefix added but the MachineDeployment version doesn't match and somehow (that part is still unclear to me) it keeps trying to recreate the MachineSet, which causes the ReconcileError.

**Comment by jackfrancis** [comment]
@CecileRobertMichon where do we normalize in the other webhooks? I can try to put together a PR w/ the equivalent for MachineDeployment

**Comment by CecileRobertMichon** [comment]
@jackfrancis that'd be great. Here's an example: https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha4/machine_webhook.go#L58
