### ISSUE TITLE
Allow accepting data loss from spoke to hub in FuzzTests

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#4655]
Since there are breaking changes from v1alpha3 to v1alpha4, we can expect some data loss from v1alpha3 to 4 caused by removing a field from v1alpha4 that exist in v1alpha3.

For values that exist in the spoke version but does not exist in the Hub version, we need to define `SpokeBeforeMutation` for fuzz tests to pass.

**Comment by fabriziopandini** [comment]
@sedefsavas currently we are already doing so implementing custom fuzzer functions like in https://github.com/kubernetes-sigs/cluster-api/blob/db4736853644a6440a1b2eea990d7af99a29d992/bootstrap/kubeadm/types/v1beta2/conversion_test.go#L110-L115

**Comment by sedefsavas** [comment]
Thanks @fabriziopandini, yes this is what I was looking for.
