### ISSUE TITLE
Document our build jobs and current e2e test coverage

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#4665]
**User Story**

As a developer/maintainer I would like to have an overview which builds and e2e tests are executed on presubmit, periodically or postsubmit in CAPI. This is useful to make it easier to get a grasp of how our build works and what we're testing. It's also useful for maintainers to analyze if there are gaps  in our test coverage.

**Detailed Description**

Goal of this issue is to add a page to our book which provides an overview over our build and test jobs. Follow-up tasks are then to add additional jobs (e.g. to test CAPI against ci/latest). 

**Anything else you would like to add:**

I'll use the issue description to get a rough overview (and update it if necessary). 

Should we also include release-0.3?  => No, as the the book is versioned we will only document v1alpha4 on the default branch for now

#### Builds and Tests (WIP)
        
* Prow Presubmits
    * pull-cluster-api-build-main: ./scripts/ci-build.sh
    * [opt][always-run:false] pull-cluster-api-make-main: ./scripts/ci-make.sh
    * [opt] pull-cluster-api-apidiff-main: ./scripts/ci-apidiff.sh
    * pull-cluster-api-verify: ./scripts/ci-verify.sh
    * pull-cluster-api-test-main: ./scripts/ci-test.sh
    * pull-cluster-api-e2e-main: ./scripts/ci-e2e.sh
        * GINKGO_FOCUS: `[PR-Blocking]`
    * [opt][always-run:false] pull-cluster-api-e2e-full-main: ./scripts/ci-e2e.sh
        * GINKGO_SKIP: `[PR-Blocking] [Conformance] [K8s-Upgrade]` (i.e. "no tags")
    * [opt][always-run:false] pull-cluster-api-e2e-workload-upgrade-1-21-latest-main: ./scripts/ci-e2e.sh FROM: stable-1.21 TO: ci/latest-1.22
        * GINKGO_FOCUS: `[K8s-Upgrade]`

* Prow Periodics
    * periodic-cluster-api-verify-book-links-main: make verify-book-links 
    * periodic-cluster-api-test-main: ./scripts/ci-test.sh
    * periodic-cluster-api-e2e-main: ./scripts/ci-e2e.sh
        * GINKGO_SKIP: `"[Conformance] [K8s-Upgrade]`
    * periodic-cluster-api-e2e-workload-upgrade-1-18-1-19-main: ./scripts/ci-e2e.sh FROM: stable-1.18 TO: stable-1.19
        * GINKGO_FOCUS: `[K8s-Upgrade]`
    * periodic-cluster-api-e2e-workload-upgrade-1-19-1-20-main: ./scripts/ci-e2e.sh FROM: stable-1.19 TO: stable-1.20
        * GINKGO_FOCUS: `[K8s-Upgrade]`
    * periodic-cluster-api-e2e-workload-upgrade-1-20-1-21-main: ./scripts/ci-e2e.sh FROM: stable-1.20 TO: stable-1.21
        * GINKGO_FOCUS: `[K8s-Upgrade]`
    * periodic-cluster-api-e2e-workload-upgrade-1-21-latest-main: ./scripts/ci-e2e.sh FROM: stable-1.21 TO: ci/latest-1.22
        * GINKGO_FOCUS: `[K8s-Upgrade]`
    * cluster-api-push-images-nightly: "cloudbuild-nightly.yaml": make release-staging-nightly, make -C test/infrastructure/docker release-staging-nightly

* Prow Postsubmits:
    * post-cluster-api-push-images: "cloudbuild.yaml": make release-staging, make -C test/infrastructure/docker release-staging

* Github (Presubmit) Workflows
    * golangci-lint: golangci/golangci-lint-action@v2
    * verify: kubernetes-sigs/kubebuilder-release-tools@v0.1 verifier

* Github (On Release (?)) Workflows
    * Update Homebrew Formula On Release: dawidd6/action-homebrew-bump-formula@v3 clusterctl

#### e2e tests

* no tags:
    * capi-e2e: When testing clusterctl upgrades Should create a management cluster and then upgrade all the providers
    * capi-e2e: When testing KCP upgrade Should successfully upgrade Kubernetes, DNS, kube-proxy, and etcd in a HA cluster using scale in rollout
    * capi-e2e: When testing MachinePools Should successfully create a cluster with machine pool machines
    * capi-e2e: When testing KCP upgrade Should successfully upgrade Kubernetes, DNS, kube-proxy, and etcd in a single control plane cluster
    * capi-e2e: When testing KCP upgrade Should successfully upgrade Kubernetes, DNS, kube-proxy, and etcd in a HA cluster
    * capi-e2e: When testing MachineDeployment upgrades Should successfully upgrade Machines upon changes in relevant MachineDeployment fields
    * capi-e2e: When testing node drain timeout A node should be forcefully removed if it cannot be drained in time
    * capi-e2e: When testing KCP adoption Should adopt up-to-date control plane Machines without modification
    * capi-e2e: When testing Cluster API working on self-hosted clusters Should pivot the bootstrap cluster to a self-hosted cluster
    * capi-e2e: When testing unhealthy machines remediation Should successfully trigger machine deployment remediation
    * capi-e2e: When testing unhealthy machines remediation Should successfully trigger KCP remediation

* [PR-Blocking]:
    * capi-e2e: When following the Cluster API quick-start [PR-Blocking] Should create a workload cluster

* [Conformance]:
    * capi-e2e: When testing K8S conformance [Conformance] Should create a workload cluster and run kubetest

* [Conformance] [K8s-Upgrade]:
    * capi-e2e: When upgrading a workload cluster and testing K8S conformance [Conformance] [K8s-Upgrade] Should create and upgrade a workload cluster and run kubetest 

#### Identified gaps (TBD)

* [ ] e2e test for k/k ci/latest
    * presubmit / periodic?
    * with/without conformance test? 
* [ ] 

/kind feature

**Comment by fabriziopandini** [comment]
@sbueringer thanks for filing this issue.
IMO this documentation should target CAPI developers/mantainers, and the main goal should be to provide some hints to help people to self-triage failures; including also tips on how to run those jobs locally (or link to other pages explaining this).

Also, ideally we should document or at least quote the jobs which are not running in prow (GitHub workflows and cloudbuild jobs)

> Should we also include release-0.3?

In don't think so. The book is versioned and the latest version on main should take care of v1alpha4 only.

**Comment by sbueringer** [comment]
@fabriziopandini 

I agree, I updated the issue description accordingly.

I think I got all Jobs of the main repo I'm aware of. Can you check if I missed something?

You can ignore the documentation style. I'll document it differently in the book and would like to add the things you suggested and some kind of test matrix.

**Comment by fabriziopandini** [comment]
> Can you check if I missed something?

sgtm, off to a great start!
