### ISSUE TITLE
Divide KCP upgrade e2e test into multiple tests

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#4672]
KCP upgrade tests include 2 HA cluster upgrade tests which takes too long for providers.

For the providers that parallelize their e2e tests, calling a time-consuming cluster-api test spec reduces the parallelization benefits. Instead dividing these tests will allow providers to choose which test to call and parallelise accordingly.

I propose to place [scale-in-rollout](https://github.com/kubernetes-sigs/cluster-api/pull/4347) test to a separate spec.

**Comment by sedefsavas** [comment]
cc @jan-est

**Comment by jan-est** [comment]
Thanks @sedefsavas 
Is there anyone in the community who could like work on this one right away?

**Comment by fabriziopandini** [comment]
/kind feature
/area testing
/milestone v0.4
(setting milestone 0.4 given it seems that the sooner the better)

**Comment by tcordeu** [comment]
I can work on this one! @fabriziopandini @jan-est

**Comment by tcordeu** [comment]
I am going to go ahead and assign myself, If anyone is already working on it feel free to unassign me.

/assign @tcordeu
