### ISSUE TITLE
Refactor raw yaml const in tests

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4676]
As per discussion on https://github.com/kubernetes-sigs/cluster-api/pull/4643#discussion_r638229515, on our tests we are using two mixed approached for multiline yaml const

multiline string, not ideal because it does not respect indentation. e.g

https://github.com/kubernetes-sigs/cluster-api/blob/7478817225e0a75acb6e14fc7b438231578073d2/controlplane/kubeadm/internal/workload_cluster_test.go#L809-L821

concatenated strings, which provides a better indentation, but adds a lot of control chars

https://github.com/kubernetes-sigs/cluster-api/blob/5c19ea1f6099e68539146aa40a7631bda618c6c1/controlplane/kubeadm/internal/workload_cluster_test.go#L986-L1018

This issue is about discussing the introduction the following func into the util/yaml package

```go
// Raw returns un-indented yaml string; it also remove the first empty line, if any.
func Raw(raw string) string {
	return strings.TrimPrefix(heredoc.Doc(raw), "\n")
}
```

 So we can write our multiline yaml const in a way which respect indentation and does not requires control chars, e.g.

```go
...
		{
			name: "it should set etcd version when local etcd",
			clusterConfigurationData: yaml.Raw(`
				apiVersion: kubeadm.k8s.io/v1beta2
				kind: ClusterConfiguration
				etcd:
				  local: {}
				`),
			newImageRepository: "example.com/k8s",
			newImageTag:        "v1.6.0",
			wantClusterConfiguration: yaml.Raw(`
				apiServer: {}
				apiVersion: kubeadm.k8s.io/v1beta2
				controllerManager: {}
				dns: {}
				etcd:
				  local:
				    imageRepository: example.com/k8s
				    imageTag: v1.6.0
				kind: ClusterConfiguration
				networking: {}
				scheduler: {}
				`),
		},
```

@vincepri @CecileRobertMichon @sbueringer  opinions?

/kind cleanup

**Comment by vincepri** [comment]
Works for me!
