### ISSUE TITLE
Consider removing kube-rbac-proxy from release-0.3

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#4679]
A follow-up issue discussion from May 26th community meeting and https://github.com/kubernetes-sigs/cluster-api/issues/4325.

We recently updated kube-rbac-proxy to v0.8 in #4639, although after further consideration we might want to stop making a choice for our users and let them secure metrics endpoints by patching our components instead of shipping all our managers with a somewhat opinionated solution.

Marking this as API change given that it should be marked as breaking change if the a PR is proposed.

/kind cleanup
/kind api-change
/milestone v0.3

**Comment by CecileRobertMichon** [comment]
cc @randomvariable @micahhausler

**Comment by dthorsen** [comment]
Shipping an opinionated solution (including kube-rbac-proxy out of the box) seems to be shipping a "secure default" configuration and seems reasonable. There is nothing stopping our users from patching kube-rbac-proxy out and replacing it with something else. Do we have data that suggests the majority of users replace it with something else that would warrant changing the default?

**Comment by vincepri** [comment]
@dthorsen There is a PR in flight to remove kube-rbac-proxy in v0.4, this request is potentially to backport that change.

Regarding the secure default bit, we've actually came to this conclusion because we were shipping a very old version of kube-rbac-proxy that was affected by a CRD, so we were opting to change the defaults to only listen for metrics on a localhost port that can be potentially be exposed by users if they choose to do so.

**Comment by dthorsen** [comment]
I see. I don't feel strongly either way, but if the fix is simply to change the kube-rbac-proxy tag, wouldn't that be a less disruptive fix for users?

**Comment by vincepri** [comment]
/close

During June 2nd 2021 community meeting we've decided to keep kube-rbac-proxy in release-0.3 and go ahead with the removal in v0.4.0.
