### ISSUE TITLE
MachineHealthCheck external remediations should generate an event if not removed within a reasonable time period

### ISSUE THREAD

**Issue by elmiko** [kubernetes-sigs/cluster-api#4681]
**User Story**

As an operator I would like to know when my external remediations have not been acted upon within a reasonable amount of time. Ideally I want to see an event or some form of alert that tells me an external remediation has been created but not acted upon.

**Detailed Description**

When the MachineHealthCheck instantiates an external remediation template it has no way of knowing what has happened to that resource, and ideally it shouldn't need to know. But it is possible that the MHC creates a remediation and then that remediation is never acted upon (perhaps due to a failure in the external controller, or some other cluster related issue). In these cases it would be nice if the MHC could signal that it created an external remedation but that it was never processed. 

Initially this would be a very large window of time (eg 6 hours), perhaps with an option to adjust that window. In this way the MHC could provide a sort of "sanity check" in cases where an external remediation did not happen.

**Anything else you would like to add:**

This idea brings up the notion of controllers watching other controllers. Which in general does not seem appropriate, but in this specific case the MHC and external remediator are tightly coupled through the remediation template, it seems reasonable to emit a warning in cases where the expected behavior (ie the remediation template being removed) does not happen.

/kind feature

**Comment by JoelSpeed** [comment]
Reading through the original thread in the PR, I can understand the concerns about having the controller watching another controller.

However I think in this case there are a few reasons why this may be a valid design:
- The interaction point for the customer in this case is the MHC
- The MHC has requested some action of another controller, if it's request never gets fulfilled, I'd expect it to report that
- The alternative is that each external remediation implementer creates some sort of metric or way of reporting this up, which could lead to a proliferation of time series in prometheus

I think I'm still uncertain on how we want this information to be exposed, is a metric suitable here or would it be better on the MHC status?

**Comment by elmiko** [comment]
i like how you summarized it @JoelSpeed , my thinking was also that the MHC is the main interaction point for the user in these cases.

if we have a metric, we might get mired in keeping track of all the time series related to each emr that happens (which may not be a bad thing). but, a condition doesn't give us a convenient way to create an alert and it requires the user to look into the mhc to see what's wrong.

i _think_ i prefer the metric approach, but i don't have a strong opinion yet.

**Comment by elmiko** [comment]
wondering if this is something we should keep open? seems like i kinda forgot about it after the initial discussion. @JoelSpeed @vincepri wdyt?

**Comment by JoelSpeed** [comment]
From a UX perspective, unless we've done something else to cover this, I think we still want some sort of signal if the MHC actions don't manifest into a fixed machine

**Comment by fabriziopandini** [comment]
Shouldn't this be a responsibility of a monitoring system to look at external components properly working?

**Comment by elmiko** [comment]
i think that's fair @fabriziopandini , my concern is that i think the mhc controller should have some way of indicating that it has sent out for external remediation, but that it has not completed yet.
