### ISSUE TITLE
checksum mismatch while building docker provider test artifacts

### ISSUE THREAD

**Issue by elmiko** [kubernetes-sigs/cluster-api#4720]
**What steps did you take and what happened:**

1. get a fresh copy of cluster-api repo
2. follow clusterctl devel instructions to the [build artifacts locally](https://cluster-api.sigs.k8s.io/clusterctl/developers.html#build-artifacts-locally) step
3. build infrastructure provider with command `make -C test/infrastructure/docker docker-build REGISTRY=gcr.io/k8s-staging-cluster-api`

the following error is produced:
```
 => ERROR [builder  8/15] RUN --mount=type=cache,target=/go/pkg/mod     go mod download                                    0.4s
------
 > [builder  8/15] RUN --mount=type=cache,target=/go/pkg/mod     go mod download:
#17 0.367 verifying github.com/onsi/ginkgo@v1.16.3: checksum mismatch
#17 0.367       downloaded: h1:nbWI/w6DYT9gXDQi59Mht//PLPPFv/Hc3fHms4eVUK0=
#17 0.367       go.sum:     h1:3s86PZkI1ApJh6HFIzC1gXby/mIyZqfE5zxSvtoBSsM=
#17 0.367 
#17 0.367 SECURITY ERROR
#17 0.367 This download does NOT match an earlier download recorded in go.sum.
#17 0.367 The bits may have been replaced on the origin server, or an attacker may
#17 0.367 have intercepted the download attempt.
#17 0.367 
#17 0.367 For more information, see 'go help module-auth'.
------
executor failed running [/bin/sh -c go mod download]: exit code: 1
make: *** [Makefile:163: docker-build] Error 1
```

**What did you expect to happen:**

The docker provider images would be built

**Anything else you would like to add:**

I tried running a `go mod tidy` and `go mod vendor` in the `cluster-api/test` directory, but it also complained about the hashes.
```
$ go mod tidy                                                                                                                   
go: downloading github.com/onsi/ginkgo v1.16.3                                                                                  
go: downloading github.com/onsi/gomega v1.13.0                                                                                  
go: downloading sigs.k8s.io/kind v0.11.1
go: downloading k8s.io/klog/v2 v2.9.0
go: downloading k8s.io/utils v0.0.0-20210527160623-6fdb442a123b
go: downloading github.com/stretchr/testify v1.6.1
verifying github.com/onsi/ginkgo@v1.16.3: checksum mismatch
        downloaded: h1:nbWI/w6DYT9gXDQi59Mht//PLPPFv/Hc3fHms4eVUK0=
        go.sum:     h1:3s86PZkI1ApJh6HFIzC1gXby/mIyZqfE5zxSvtoBSsM=
```

```
$ go mod vendor
go: downloading github.com/onsi/ginkgo v1.16.3
go: downloading sigs.k8s.io/kind v0.11.1
go: downloading google.golang.org/appengine v1.6.7
verifying github.com/onsi/ginkgo@v1.16.3: checksum mismatch
        downloaded: h1:nbWI/w6DYT9gXDQi59Mht//PLPPFv/Hc3fHms4eVUK0=
        go.sum:     h1:3s86PZkI1ApJh6HFIzC1gXby/mIyZqfE5zxSvtoBSsM=
```

**Environment:**

- Cluster-api version: master branch @ 61e63e0dbbe50a276174826aaf1bcc9847ebc3a5
- Minikube/KIND version: n/a
- Kubernetes version: (use `kubectl version`): n/a
- OS (e.g. from `/etc/os-release`): Fedora 34

/kind bug
/area provider/docker
/area provider/testing

**Comment by elmiko** [comment]
cc @vincepri this seems to have come in with the recent test module changes

**Comment by vincepri** [comment]
@elmiko Can you try on top of 4721? It's kind of strange, although running the command you posted above with those changes, the build went through

**Comment by elmiko** [comment]
hmm, really weird. i tried on top of 4721 and i get the same output

```
 => ERROR [builder  8/15] RUN --mount=type=cache,target=/go/pkg/mod     go mod download                                              2.5s
------                                                                                                                                    
 > [builder  8/15] RUN --mount=type=cache,target=/go/pkg/mod     go mod download:                                                         
#17 2.431 verifying github.com/onsi/ginkgo@v1.16.3: checksum mismatch                                                                     
#17 2.431       downloaded: h1:nbWI/w6DYT9gXDQi59Mht//PLPPFv/Hc3fHms4eVUK0=                                                               
#17 2.431       go.sum:     h1:3s86PZkI1ApJh6HFIzC1gXby/mIyZqfE5zxSvtoBSsM=                                                               
#17 2.431 
#17 2.431 SECURITY ERROR
#17 2.431 This download does NOT match an earlier download recorded in go.sum.
#17 2.431 The bits may have been replaced on the origin server, or an attacker may
#17 2.431 have intercepted the download attempt.
#17 2.431 
#17 2.431 For more information, see 'go help module-auth'.
------
executor failed running [/bin/sh -c go mod download]: exit code: 1
make: *** [Makefile:163: docker-build] Error 1
```

**Comment by elmiko** [comment]
i don't know how these hashes are computed, but i wonder if i'm seeing something related to fedora (eg an updated hash lib or similar) ?

**Comment by elmiko** [comment]
from https://golang.org/ref/mod#authenticating

> When the go command downloads a module zip file or go.mod file into the module cache, it computes a cryptographic hash and compares it with a known value to verify the file hasn't changed since it was first downloaded. 

and

> The go command compares each hash with the corresponding line in the main module's go.sum file. If the hash is different from the hash in go.sum, the go command reports a security error and deletes the downloaded file without adding it into the module cache.

really makes me wonder if i'm just seeing some local crypto update. i'll keep poking around

**Comment by elmiko** [comment]
the weird just keeps getting weirder... 
i deleted `test/go.sum` and then re-ran `go mod tidy && go mod vendor && go mod verify` in the `test` directory, the only change it picked up was that ginkgo hash.

```
$ git diff go.sum
diff --git a/test/go.sum b/test/go.sum
index c1ef718cc..b2da80ad1 100644
--- a/test/go.sum
+++ b/test/go.sum
@@ -463,7 +463,7 @@ github.com/onsi/ginkgo v1.11.0/go.mod h1:lLunBs/Ym6LB5Z9jYTR76FiuTmxDTDusOGeTQH+
 github.com/onsi/ginkgo v1.12.1/go.mod h1:zj2OWP4+oCPe1qIXoGWkgMRwljMUYCdkwsT2108oapk=
 github.com/onsi/ginkgo v1.15.0/go.mod h1:hF8qUzuuC8DJGygJH3726JnCZX4MYbRB8yFfISqnKUg=
 github.com/onsi/ginkgo v1.16.2/go.mod h1:CObGmKUOKaSC0RjmoAK7tKyn4Azo5P2IWuoMnvwxz1E=
-github.com/onsi/ginkgo v1.16.3 h1:3s86PZkI1ApJh6HFIzC1gXby/mIyZqfE5zxSvtoBSsM=
+github.com/onsi/ginkgo v1.16.3 h1:nbWI/w6DYT9gXDQi59Mht//PLPPFv/Hc3fHms4eVUK0=
 github.com/onsi/ginkgo v1.16.3/go.mod h1:CObGmKUOKaSC0RjmoAK7tKyn4Azo5P2IWuoMnvwxz1E=
 github.com/onsi/gomega v0.0.0-20170829124025-dcabb60a477c/go.mod h1:C1qb7wdrVGGVU+Z6iS04AVkA3Q65CEZX59MT0QO5uiA=
 github.com/onsi/gomega v1.4.3/go.mod h1:ex+gbHU/CVuBBDIJjb2X0qEXbFg53c61hWP/1CpauHY=
```

**Comment by vincepri** [comment]
Which GO version are you using?

**Comment by elmiko** [comment]
`go version go1.16.3 linux/amd64`

**Comment by vincepri** [comment]
I've been using Go 1.16.4, and the Dockerfiles should be using that as well, might be worth a try?

It's a bit strange that it changes the `go.sum` 🤔

**Comment by elmiko** [comment]
ok, i tried testing this out with a few other go version (1.16.4, 1.16.5) and i think i must be seeing some sort of artifact from a cached build or something.

i deleted my `$HOME/go`  and `$HOME/.cache` directories, then tried running `go mod tidy` in the `test` dir and it didn't complain at all. but when i ran the makefile again, it produced the same error.

additionally, when i took the supposedly "good" hash from the makefile build and manually added it to the `go.sum` file, i started to see errors when running `go mod tidy`, but the makefile started to work.

i will keep digging to see if i can find an answer, but i think we can close this at it appears to just be something local on my machine.

**Comment by vincepri** [comment]
@fabriziopandini @ykakarap Can you folks try to reproduce?

**Comment by fabriziopandini** [comment]
I got a similar error about ginkgo checksum while running tests is Goland, and I got it fixed by enforcing usage of GOPROXY=https://proxy.golang.org
@elmiko If you are using Cluster API makefile command it will enforce GOPROXY for you; instead if you using plain go commands might be you are facing a similar problem; could you check you GOPROXY env var?

**Comment by elmiko** [comment]
> @elmiko If you are using Cluster API makefile command it will enforce GOPROXY for you; instead if you using plain go commands might be you are facing a similar problem; could you check you GOPROXY env var?

i did a few more tests with GOPROXY. here is what i did:

* fresh clone from cluster-api master, ran `make -C test/infrastructure/docker docker-build REGISTRY=localhost:5000`
  * got error
* with no GOPROXY set, `cd test && go mod tidy`
  * no error
* set `GOPROXY=https://proxy.golang.org`, `cd test && go mod tidy`
  * no error

currently, on this system it is just the makefile that is producing the checksum error. i tried these commands with both go 1.16.3 and 1.16.4.

**Comment by fabriziopandini** [comment]
> currently, on this system it is just the makefile that is producing the checksum error. i tried these commands with both go 1.16.3 and 1.16.4.

This is kind of confusing me, because we are enforcing go proxy both in the makefile and in the docker file...
🤔

**Comment by elmiko** [comment]
yeah, i'm stumped. i am trying to setup another environment to double check what i've done.

**Comment by vincepri** [comment]
> fresh clone from cluster-api master, ran make -C test/infrastructure/docker docker-build REGISTRY=localhost:5000

Is the local proxy up to date?

**Comment by ykakarap** [comment]
@vincepri I was not able to reproduce this locally. All the commands ran successfully.

**Comment by elmiko** [comment]
> Is the local proxy up to date?

afaict yes, i deleted my local `go` and `.cache` directories. is there any other location i should check?

**Comment by elmiko** [comment]
i updated my repo again today, after seeing some changes come through on go.mod and go.sum, and now the error has migrated slightly on my build machine:

```
=> ERROR [builder 12/15] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod     CGO_ENA  0.3s
------                                                               
 > [builder 12/15] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod     CGO_ENABLED=0 GOOS=li
nux GOARCH=amd64 go build -a -o /workspace/manager main.go:
#21 0.242 go: inconsistent vendoring in /workspace/test:
#21 0.242       github.com/onsi/ginkgo@v1.16.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
#21 0.242       github.com/onsi/gomega@v1.13.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
#21 0.242       sigs.k8s.io/controller-runtime@v0.9.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
#21 0.242       github.com/onsi/ginkgo@v1.16.3: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
#21 0.242       github.com/onsi/gomega@v1.12.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
#21 0.242       sigs.k8s.io/controller-runtime@v0.9.0-beta.6: is marked as explicit in vendor/modules.txt, but not explicitly required in 
go.mod
#21 0.242 
#21 0.242       To ignore the vendor directory, use -mod=readonly or -mod=mod.
#21 0.242       To sync the vendor directory, run:
#21 0.242               go mod vendor
------
executor failed running [/bin/sh -c CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o /workspace/manager main.go]: exit code: 1
```

it seemingly makes it past the previous failure point, to a new one. i'm going to keep poking at this.

**Comment by vincepri** [comment]
@elmiko Is this happening with a local registry?

**Comment by elmiko** [comment]
i am going to close this issue. i think i am just seeing the results of some sort of caching going on, or something on my local machine. i cleaned all caches, got all new code, installed new golang binaries, and rebuilt everything, and now it is working...

i have no explanations for this, and i apologize if this has wasted anyone's time. i do appreciate all the help and feedback.

**Comment by elmiko** [comment]
> @elmiko Is this happening with a local registry?

yes

**Comment by elmiko** [comment]
@vincepri does it try to use images that were created in previous steps during the build for the test stuff? (that would explain a few things)

**Comment by vincepri** [comment]
It should use cached images, yes

**Comment by elmiko** [comment]
ok, i have to imagine that is what i was seeing. now i'm wondering if there is a way to add a little warning to the docs :thinking: 

thanks again Vince!
