### ISSUE TITLE
Image Management Story in ClusterAPi

### ISSUE THREAD

**Issue by zawachte** [kubernetes-sigs/cluster-api#4727]
**User Story**

As a user, I would like to have core support in ClusterAPI for managing the "images" of Kubernetes for my clusters. This will provide a uniform deployment and upgrade story w.r.t clusters and their underlying images.

Basically I want to play with the idea of promoting "image" to a core clusterapi concept from something completly within the infrastucture provider (kind of like the load balancer proposal.).

**Detailed Description**

Whether you are on CAPA, CAPZ, CAPV a prerequisite to deploying a clusterapi cluster is to have each cloud's corresponding "image galleries" preconfigured with an image, ami, ova which you plan to create machines based off of.

In most cases, these images need to be pre-provisioned with at least kubeadm, kubelet and therefore are tied to a certain version of Kubernetes.

Most Infrastructure providers seem to have some sort of implicit contract with the naming of their "image" and the Kubernetes version that is "tied" to it. If a user is using the upstream images provided by an infrastructure provider, using this implicit contract, a user just needs to update the spec of a kubeadmcontrolplane or machinedeployment. 

If a user isn't using the upstream images provided by an infrastructure provider, they typically need to update the machine infrastructure template along with the Kubernetes version.

This idea is not fully baked but I just wanted to get people's thoughts maybe promoting "Image" to a core ClusterAPI concept. Maybe an image CRD, and an infra provider contract for their implementation?

This can open the door to image refs on kubeadmcontrolplane and machinedeployments. Users will also be able to easily manage the current kubernetes "images" they have available for cluster provisioning or already provisioned to a cluster. Maybe in the CVE case, a user can easily update all the machines,clusters using the same image.

**Anything else you would like to add:**

This is clearly more of a CAEP than an issue, was just curious about early thoughts. Also need to review the clusterclass spec again and I think there is overlap.

/kind feature

**Comment by CecileRobertMichon** [comment]
@zawachte any reason you closed this one? I was looking for an existing issue just like this and found this issue which explains it perfectly

**Comment by zawachte** [comment]
I don't think I have a good answer for you. Going to reopen.
