### ISSUE TITLE
Remove use of Viper in kubetest framework

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#4729]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

https://github.com/kubernetes/kubernetes/pull/102598 removes Viper from the Kubernetes e2e framework, but we are using it in the e2e framework, with CAPA and CAPZ as consumers.

**What did you expect to happen:**
Not use Viper

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Should be able to do this in such a way as to not break the contract with the providers using the e2e framework

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 

/lifecycle active
/assign @randomvariable

**Comment by randomvariable** [comment]
/kind backport

We'll want it on v1alpha3 until v1alpha4 + 1

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/102598 is currently held waiting on this FYI
