### ISSUE TITLE
Make clusterctl support for cert-manager more flexible

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4731]
**User Story**

As a operator I would like to use an external tool to manage cert-manager
As a operator I would like to use have control on the cert-manager version installed by clusterctl
As a operator I would like to use have control on the cert-manager manifest installed by clusterctl

**Detailed Description**

As of today clusterctl assumes to manage the cert-manager instance in the management cluster.

While this approach helped in simplifying the UX, it is also not flexible; additionally, the clusterctl version version and the corresponding manifest are embedded in clusterctl thus making any change linked to the CAPI release cycle.

With this issue I'm proposing to change clusterctl so that:
- if an instance of cert-manager ALREADY EXISTS in the cluster, to make clusterctl to use it; also clusterctl should not lifecycle manage the externally provided cert-manager instance
- if an instance of cert-manager DOES NOT EXISTS in the cluster, clusterctl will install a new one as of today, however:
  - The new version will be fetched from a repository that defaults to `https://github.com/jetstack/cert-manager/releases`, but that the user could configure similarly to what we are doing for providers (using local repositories, overrides etc)
  - The user will be allowed to change the cert-manager version to use

**Anything else you would like to add:**

related issue https://github.com/kubernetes-sigs/cluster-api/issues/4617 

@vincepri @CecileRobertMichon 

/kind feature

**Comment by davidewatson** [comment]
How will cert-manager lifecycle be managed in each case?

- When it ALREADY EXISTS we will be assuming that the operator will always install a compatible version. Is this safe?
- When it DOES NOT EXISTS and the user does not configure an override, do we now (or plan to later) upgrade whichever cert-manager we install?

My apologizes if these questions are obtuse. I'm new here... ;)

**Comment by fabriziopandini** [comment]
> When it ALREADY EXISTS we will be assuming that the operator will always install a compatible version.  Is this safe?

Clusterctl will be testing for a cert-manager version supporting the `cert-manager.io/v1` API, which is a GA version from about a year now a subject to usual API guarantees for deprecation and or conversion to the future release.
The only change here is that "externally provisioned" cert-manager became a first class option and we support it also during upgrades (no-op for externally managed cert-manager)

> When it DOES NOT EXISTS and the user does not configure an override, do we now (or plan to later) upgrade whichever cert-manager we install?

This is already the case now. The only change here is that we fetch from repository and the user can override the target version.

**Comment by davidewatson** [comment]
I worry about implicit runtime differences which might surprise users. But I [see](https://github.com/kubernetes-sigs/cluster-api/blob/70e959802aa7722efefe69158e868d7ff3eec4be/cmd/clusterctl/client/cluster/cert_manager.go#L439). Seems reasonable.
