### ISSUE TITLE
Update etcd client dependency

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#4745]
**User Story**

The etcd client dependency is very outdated, and we're missing grpc fixes as a result. Need to refactor the cluster etcd client to make use of v3.4.16.

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by vincepri** [comment]
@randomvariable Could we do this before v0.4.0?

**Comment by randomvariable** [comment]
I wasn't sure how big a change it was going to be. I'll review and get an answer today.

**Comment by randomvariable** [comment]
Just checked. There's nothing we can do here because Kubernetes depends on the older etcd client, which might be because it's stuck on an old grpc version because of cadvisor.

So

/close

**Comment by randomvariable** [comment]
The network of dependencies is:
sigs.k8s.io/controller-runtime@v0.9.0 k8s.io/apiextensions-apiserver@v0.21.1
k8s.io/apiextensions-apiserver@v0.21.1 google.golang.org/grpc@v1.27.1

Work is ongoing in https://github.com/kubernetes/kubernetes/pull/102061 to update that.

**Comment by randomvariable** [comment]
Only pulling in apiextensions-apiserver to bring in the struct for CustomResourceDefinition... potentially removable.

**Comment by randomvariable** [comment]
/reopoen

figured it out.

**Comment by vincepri** [comment]
/milestone v0.4

Let's bump it once v3.5 is released and we can validate it a bit more

**Comment by randomvariable** [comment]
I had a look at the milestone planning for etcd, their plan is to get the release out once they have signal from k/k to accept it for 1.22
