### ISSUE TITLE
Cannot use minikube >= 0.28.1 with clusterapi-apiserver

### ISSUE THREAD

**Issue by joejulian** [kubernetes-sigs/cluster-api#475]
With [this line of this PR](https://github.com/kubernetes/minikube/pull/2943/files#diff-791cd4f1bc5624fa1aec26b76983b601R32), minikube changed the behavior of kubeadm and its creation of the `admin.conf`, changing the host to `localhost`. This causes the clusterapi-apiserver to be unable to connect to the kube-apiserver as it's not listening on localhost inside the pod when clusterctl uses minikube for the external cluster.

I suspect this could be solved by connecting via the environment token with a serviceAccount with sufficient permissions instead of mounting `/etc/kubernetes` inside the pod.

ref: kubernetes/minikube#3076

**Comment by tstromberg** [comment]
I agree with @roberthbailey's workaround - but being pinned to an old version is also going to be non-sustainable long-term. I don't yet understand the motivation behind the behavior change, but I'll try to push forward kubernetes/minikube#3076

My apologies for the inconvenience.

**Comment by chaosaffe** [comment]
AFAIK this is no longer an issue after the CRD migration as we can use `v0.30.0` without any modifications, but I am not sure where other providers are at with their changes to CRD's

**Comment by roberthbailey** [comment]
Apparently we didn't have any documentation in this repo about needing a higher version, so we don't need a docs PR to fix this. I've also confirmed that I can create a CRD-based cluster using the gcp provider with minikube 0.30.0 so I'm going to close this as obsolete.

**Comment by joejulian** [comment]
Excellent, thanks!
