### ISSUE TITLE
Importing test module causes errors

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#4760]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
I bumped CAPA to sigs.k8s.io/cluster-api v0.3.11-0.20210607195256-55f064d1b9fc and then running `go mod tidy` gave me

```
go: sigs.k8s.io/cluster-api/test@v0.0.0-20210607195256-55f064d1b9fc requires
        sigs.k8s.io/cluster-api@v0.0.0-00010101000000-000000000000: reading https://proxy.golang.org/sigs.k8s.io/cluster-api/@v/v0.0.0-00010101000000-000000000000.mod: 410 Gone
        server response: not found: sigs.k8s.io/cluster-api@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

I think this works in the core repo because we have the replace statement, but when importing externally, we need a real reference.

**What did you expect to happen:**
No issues when updating.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by randomvariable** [comment]
Or do we just need a one off tag to be released first?

**Comment by randomvariable** [comment]
fixed it

Needed `sigs.k8s.io/cluster-api/test v0.0.0-20210607195256-55f064d1b9fc`

/close

**Comment by randomvariable** [comment]
fixed it in CAPA with

Actually, needed the following replace as well for it to work
`
replace sigs.k8s.io/cluster-api => sigs.k8s.io/cluster-api v0.3.11-0.20210607195256-55f064d1b9fc

require(
sigs.k8s.io/cluster-api/test v0.0.0-20210607195256-55f064d1b9fc`
)
```

/reopen

**Comment by devigned** [comment]
@CecileRobertMichon is doing a similar thing here: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1421

**Comment by randomvariable** [comment]
I think we came to a conclusion in https://github.com/kubernetes-sigs/cluster-api/pull/4765

so

/close

**Comment by sbueringer** [comment]
@randomvariable In case additional data is helpful in any way. The suggestion in #4765 worked perfectly in CAPO (https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/go.mod)
