### ISSUE TITLE
How to set up proxy to pass to "clusterctl init --infrastructure docker"

### ISSUE THREAD

**Issue by huchen2021** [kubernetes-sigs/cluster-api#4763]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
Hi,
For some reason, I need to set up proxy to pull some images.
I set up environment variable http_proxy and https_proxy.
I set up proxy for docker damon by modifing /etc/systemd/system/docker.service.d/http-proxy.conf.

When I use "kind create cluster" to create cluster, it seems ok.
kube-system coredns-558bd4d5db-4dlcp 1/1 Running 0 3h34m
kube-system coredns-558bd4d5db-7mtds 1/1 Running 0 3h34m
kube-system etcd-kind-control-plane 1/1 Running 0 3h34m
kube-system kindnet-scw2w 1/1 Running 0 3h34m
kube-system kube-apiserver-kind-control-plane 1/1 Running 0 3h34m
kube-system kube-controller-manager-kind-control-plane 1/1 Running 0 3h34m
kube-system kube-proxy-6cxdl 1/1 Running 0 3h34m
kube-system kube-scheduler-kind-control-plane 1/1 Running 0 3h34m
local-path-storage local-path-provisioner-547f784dff-mswhx 1/1 Running 0 3h34m

But when I use "clusterctl init --infrastructure docker" to transform the cluster to manager cluster, it report the following error:
NAMESPACE NAME READY STATUS RESTARTS AGE
cert-manager cert-manager-86cb5dcfdd-2lrvw 0/1 ImagePullBackOff 0 3h30m
cert-manager cert-manager-cainjector-84cf775b89-tp6mh 0/1 ImagePullBackOff 0 3h30m
cert-manager cert-manager-webhook-7f9f4f8dcb-6jphk 0/1 ImagePullBackOff 0 3h30m

I kubectl describe those pods, find all images which are pull failed, and use command "docker pull" to pull those images manually, it pull success. I don't figure out why those pods return "ImagePullBackOff" error?

Plus, there is a strange thing about this cluster. Kubernetes pods are running but docker ps does not give any output. Docker ps only has this one.
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
5027950f7f3f kindest/node:v1.21.1@sha256:fae9a58f17f18f06aeac9772ca8b5ac680ebbed985e266f711d936e91d113bad "/usr/local/bin/en..." 3 hours ago Up 3 hours 127.0.0.1:36132->6443/tcp kind-control-plane

Docker images only has this one:
REPOSITORY TAG IMAGE ID CREATED SIZE
docker.io/kindest/node af39c553b6de 3 weeks ago 1.12 GB

I guess all pods are running somewhere else. I need to set up proxy to that place. But I don't know where. Anyone? Any help?

**Comment by fabriziopandini** [comment]
Might be I'm wrong, but I think that kubelet failing to fetch cert-manager images mean that kind is not picking up the proxy (all the container started use pre-loaded image, so they are not a good signal)
Could you double check my assumption by deploying somethings else on the kind cluster, like e.g. nginx
