### ISSUE TITLE
Allow more than 1 InfrastructureProvider to be installed in e2e tests

### ISSUE THREAD

**Issue by anusha94** [kubernetes-sigs/cluster-api#4790]
**User Story**

As a developer I would like to be able to install multiple infrastructure providers as part of the e2e tests so that I can test a cluster that is spun up using multiple providers.

**Detailed Description**
The `e2e_config` forces exactly one infrastructure provider to be run as part of tests https://github.com/kubernetes-sigs/cluster-api/blob/master/test/framework/clusterctl/e2e_config.go#L484-L487. 

We would like to relax this assertion to allow more than 1 provider. 

We are building a new infrastructure provider, and want to use the docker provider for the control plane, and our new provider for the worker nodes. We are also trying to reuse the e2e setup from this repo, to reduce duplication. 

We will post a PR for this shortly. Please let us know if you think this change is acceptable. 

Thanks,
Anusha & @jamiemonserrate

/kind feature

**Comment by fabriziopandini** [comment]
Happy to see new use case for our test framework!
/area testing
