### ISSUE TITLE
Metric collection in e2e tests is broken

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#4794]
**What steps did you take and what happened:**

Our e2e tests are trying to dump metrics of our controllers via:
https://github.com/kubernetes-sigs/cluster-api/blob/303483aeea393e066d69e8c3757326c37c7a3ff3/test/framework/deployment_helpers.go#L195-L220

As far as I can see this is currently broken:
```bash
Error retrieving metrics for pod capd-system/capd-controller-manager-66c5759c8c-8whr9: Get "https://127.0.0.1:38915/api/v1/namespaces/capd-system/pods/capd-controller-manager-66c5759c8c-8whr9:8080/proxy/metrics": dial tcp 127.0.0.1:38915: connect: connection refused
```
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/4777/pull-cluster-api-e2e-main/1402586613803913216/artifacts/clusters/bootstrap/controllers/capd-controller-manager/capd-controller-manager-66c5759c8c-8whr9/metrics-error.txt

**What did you expect to happen:**

Should have worked

**Anything else you would like to add:**

I think this broke when we dropped the replacement of the `metrics-bind-addr` in `docker.yaml` to `--metrics-bind-addr=:8080`
xref: https://github.com/kubernetes-sigs/cluster-api/pull/4640

**Environment:**

- Cluster-api version: default branch

/kind bug

/cc @fabriziopandini

**Comment by vincepri** [comment]
Should we remove the collection of metrics? Or is that useful for folks when debugging e2e tests?

cc @CecileRobertMichon @yastij @randomvariable

**Comment by randomvariable** [comment]
Ah, saw this in the agenda a little while ago. We're using it a lot in CAPA to get AWS API metrics. Should work, need to do the equivalent of
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/test/e2e/data/e2e_conf.yaml#L60-L61 for however CAPD gets started

**Comment by randomvariable** [comment]
Here's an example of collected metrics
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cluster-api-provider-aws-e2e-conformance/1412328550194745344/artifacts/clusters/bootstrap/controllers/capa-controller-manager/capa-controller-manager-9c4d5c445-n7ps4/metrics.txt

**Comment by randomvariable** [comment]
Ah, it's not working because we defaulted metrics to off. I think we should turn it on for tests though. Never say no to more data to debug with.

**Comment by sbueringer** [comment]
As discussed in the meeting today. We keep the functionality and I'll fix it.
