### ISSUE TITLE
CRS should support more strategies than ApplyOnce

### ISSUE THREAD

**Issue by kbreit** [kubernetes-sigs/cluster-api#4799]
**User Story**

I would like to see CAPI CRS objects support strategies beyond just `ApplyOnce`. I find it unintuitive and confusing that you create and manage some objects (ex. nodes) using the control cluster but then other components need to be modified in the worker cluster. Also, it complicates a CICD pipeline since the control cluster's objects should be modified as well as the worker cluster's manifests.

**Detailed Description**

I would expect a `strategy: Continuous` option which periodically reconciles objects from the control cluster to the worker cluster.

/kind feature

**Comment by vincepri** [comment]
Closing in favor of #4807

/close
