### ISSUE TITLE
Wording for variants of clusters for a cluster api provider

### ISSUE THREAD

**Issue by kris-nova** [kubernetes-sigs/cluster-api#480]
We have discovered that there are several use cases to have a variant of a kubernetes cluster for a specific environment (e.g. "provider").

The example I enjoy using (that I am sure everyone is sick of hearing) is `public` and `private` topology in `kops`.

Meaning that we drastically configure and build the network in AWS differently for the two types of clusters, so the deployment strategy is different for the two. But they are both valid AWS clusters.

Here is a fictional diagram that will demonstrate the layer we are discussing.

```
.
├── cluster-api-provider-aws
│   ├── private_topology
│   ├── public_topology
│   ├── with_asg
│   └── with_ec2
├── cluster-api-provider-gce
│   ├── gke
│   └── unmanaged
└── cluster-api-provider-vmware
    ├── bar
    ├── baz
    └── foo
```

Note: The names here are fictional and are in no way suggestions for real names. I chose these just to help clarify what the layer represents. 

We decided that as a group, we need to have a word that represents this layer.

Below are suggested words that have been tossed around. If you like one of the words, please add a github emoji 👍 to the comment and cast a vote. Vote for as many as you like. Feel free to add your own if you can think of another word.

CC: @timothysc @roberthbailey

**Comment by kris-nova** [comment]
flavors

**Comment by kris-nova** [comment]
profiles

**Comment by kris-nova** [comment]
variants

**Comment by kris-nova** [comment]
implementations

**Comment by kris-nova** [comment]
styles

**Comment by kris-nova** [comment]
types

**Comment by davidjeddy** [comment]
Keeping with the nautical theme of K8:

Gulfs
Oceans
Seas
Whirlpool
Eddie
Fjord

**Comment by kris-nova** [comment]
@davidjeddy can you please separate your suggestions into single comments so folks can vote on them?

**Comment by ashish-amarnath** [comment]
doing the work for @davidjeddy

**Comment by ashish-amarnath** [comment]
Gulfs

**Comment by ashish-amarnath** [comment]
Oceans

**Comment by ashish-amarnath** [comment]
Seas

**Comment by ashish-amarnath** [comment]
Whirlpool

**Comment by ashish-amarnath** [comment]
Eddie

**Comment by ashish-amarnath** [comment]
Fjord

**Comment by ndedic** [comment]
scenarios

(con: interchangeable with topologies?)

**Comment by davidewatson** [comment]
One reason I like the word variant is the existing English definition matches our intent closely:

```
variant := a form or version of something that differs in some respect from other forms of the same thing or from a standard.
```

Notice that the title of this issue even uses it...

Aside: I can't stop thinking of users when I hear the word profile... :)

**Comment by ashish-amarnath** [comment]
+1 for the user-profile word association

**Comment by dtoebe** [comment]
Mast

**Comment by dtoebe** [comment]
trireme: https://en.m.wikipedia.org/wiki/Trireme

**Comment by kris-nova** [comment]
Per cluster api call I am going to send an email to sig-arch and sig-cluster-lifecycle suggesting the word "variants" as our champion.

**Comment by davidewatson** [comment]
@kris-nova: Should this be closed?

**Comment by roberthbailey** [comment]
I think we can close this.
