### ISSUE TITLE
It reporting Error: failed to read "cluster-template.yaml" from provider's repository "infrastructure-docker"

### ISSUE THREAD

**Issue by huchen2021** [kubernetes-sigs/cluster-api#4803]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 

When I tried to create a work cluster guided by "quick start" https://cluster-api.sigs.k8s.io/user/quick-start.html, I need to run command "clusterctl config cluster" to generate a yaml file first. But it report the following error:

$ clusterctl config cluster capi-quickstart   --kubernetes-version v1.18.16   --control-plane-machine-count=3   --worker-machine-count=3   > capi-quickstart.yaml

Error: failed to read "cluster-template.yaml" from provider's repository "infrastructure-docker": failed to download files from GitHub release v0.3.18: failed to get file "cluster-template.yaml" from "v0.3.18" release

Have no ideas why this happened? Any clue will be appreciated!

**Comment by sbueringer** [comment]
@huchen2021 You have to add the `--flavor developmen` arg:
![image](https://user-images.githubusercontent.com/4662360/121552396-b9c64b80-ca10-11eb-8241-a572fae818e4.png)

**Comment by fabriziopandini** [comment]
This is also documented in the quick start in a dedicate tab under https://cluster-api.sigs.k8s.io/user/quick-start.html#generating-the-cluster-configuration
/close

**Comment by jpmcb** [comment]
I'm also not able to get this to work. I built from source and am running:

```
SERVICE_CIDR=["10.96.0.0/12"] \
POD_CIDR=["192.168.0.0/16"] \
SERVICE_DOMAIN="cluster.local" \
./bin/clusterctl config cluster capi-quickstart --flavor development \
  --kubernetes-version v1.18.16 \
  --control-plane-machine-count=3 \
  --worker-machine-count=3
```

And I'm getting the following error message: 
```
Command "cluster" is deprecated, use `clusterctl generate cluster` instead
Error: failed to identify the default infrastructure provider. Please specify an infrastructure provider
```
What am I missing?

**Comment by jpmcb** [comment]
Providing 
```
--infrastructure aws:0.6.6
```
corrected this for me

**Comment by huchen2021** [comment]
@jpmcb  After added "--infrastructure aws:0.6.6", Does it works? Including bring up the workload cluster?  But my infrastructure is docker, now it can get yaml file, but still has issue to bring up the workload cluster.

**Comment by jpmcb** [comment]
Providing 
```
--infrastructure aws:0.6.6
```
corrected this for me. My mistake, disregard

**Comment by jpmcb** [comment]
@huchen2021 - maybe you need to provider the docker infrastructure version to the command line?
```
--infrastructure docker:v0.3.18
```
