### ISSUE TITLE
clusterctl get kubeconfig failed, it reporting: Error: "capi-quickstart-kubeconfig" not found in namespace "default": secrets "capi-quickstart-kubeconfig" not found

### ISSUE THREAD

**Issue by huchen2021** [kubernetes-sigs/cluster-api#4810]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 

When I tried to create work cluster by https://cluster-api.sigs.k8s.io/user/quick-start.html, it reporting the following error:

# clusterctl get kubeconfig capi-quickstart > capi-quickstart.kubeconfig
Error: "capi-quickstart-kubeconfig" not found in namespace "default": secrets "capi-quickstart-kubeconfig" not found

# kubectl get secret --all-namespaces | grep capi
capi-kubeadm-bootstrap-system       default-token-qpg2s                                  kubernetes.io/service-account-token   3      4d11h
capi-kubeadm-control-plane-system   default-token-pgtpc                                  kubernetes.io/service-account-token   3      4d11h
capi-system                         default-token-sp7xc                                  kubernetes.io/service-account-token   3      4d11h
capi-webhook-system                 capi-kubeadm-bootstrap-webhook-service-cert          kubernetes.io/tls                     3      4d11h
capi-webhook-system                 capi-kubeadm-control-plane-webhook-service-cert      kubernetes.io/tls                     3      4d11h
capi-webhook-system                 capi-webhook-service-cert                            kubernetes.io/tls                     3      4d11h
capi-webhook-system                 default-token-pwwsr                                  kubernetes.io/service-account-token   3      4d11h

**Comment by enxebre** [comment]
@huchen2021 I assume this is the root cause for https://github.com/kubernetes-sigs/cluster-api/issues/4811. Can you share capi/capd controllers logs?
