### ISSUE TITLE
Error cross-compiling ARM64 version of clusterctl from x86_64 Linux system

### ISSUE THREAD

**Issue by scottslowe** [kubernetes-sigs/cluster-api#4814]
**What steps did you take and what happened:**
All these steps were performed on an x86_64 Ubuntu 20.04 instance running Docker 20.10.2.
1. Cloned the "cluster-api" repository using `git clone https://github.com/kubernetes-sigs/cluster-api.git`.
2. Switch into the cloned repository.
3. Run `git checkout v0.3.19` (to build a binary for the v0.3.19 release).
4. Run `RELEASE_BINARY=./cmd/clusterctl GOOS=darwin GOARCH=arm64 make release-binary`.
The command outputs a lot (I'll attach a text file with the output) and then errors out with this:
```
# sigs.k8s.io/cluster-api/cmd/clusterctl
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: unrecognized option '-pagezero_size'
/usr/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status

make: *** [Makefile:495: release-binary] Error 2
```
Skipping step 3 (to build from the "master" branch/latest commit) does not result in this error.

**What did you expect to happen:**
I expected a binary for `clusterctl` to be built and placed in the `out` directory (as it does when building from "master"/latest commit).

**Anything else you would like to add:**
Output of `uname -a`: `5.8.0-1035-aws #37~20.04.1-Ubuntu SMP Tue Jun 1 09:54:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Environment:**

- Cluster-api version: 0.3.19
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.2

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by scottslowe** [comment]
Here's the full output of the `RELEASE_BINARY=...` command.

[build-output.txt](https://github.com/kubernetes-sigs/cluster-api/files/6650177/build-output.txt)

**Comment by scottslowe** [comment]
Another data point: at the v0.3.19 tag/commit, `Makefile` uses the Go 1.13.15 container image (the version is hard-coded in the file). Changing `Makefile` to use Go 1.16.5 fixes the error reported above and allows the build to complete successfully.

**Comment by vincepri** [comment]
@scottslowe We can probably add compilation targets in v0.4 (main branch), although v0.3 is in maintenance mode now.

The main branch is also already using Go 1.16.

/milestone Next
/priority awaiting-more-evidence

**Comment by scottslowe** [comment]
I think cross-compilation targets have already been added for v0.4 (didn't #4861 take care of this?). Since v0.3 is in maintenance mode and the main branch has already advanced to Go 1.16, it's OK to close this issue.

**Comment by vincepri** [comment]
True, I forgot that we're also publishing arm64 for linux now.

/close
