### ISSUE TITLE
Failed to move management-cluster objects

### ISSUE THREAD

**Issue by jpmcb** [kubernetes-sigs/cluster-api#4816]
**What steps did you take and what happened:**
When attempting to move cluster-api objects from a boostrap management cluster to another management cluster, I'm running into the following error:
```
Error: action failed after 9 attempts: error reading "/, Kind=" /: an empty namespace may not be set when a resource name is provided
```

Here are the steps to reproduce:
1. Start a kind cluster with:
```
ctlptl create cluster kind --registry=kind-registry
```

2. Bring tilt up:
```
$ tilt up
```
Here's what my tilt json looks like: 
```json
{
  "default_registry": "localhost:41517",
  "provider_repos": ["../../kubernetes/cluster-api-provider-aws"],
  "enable_providers": ["aws", "docker", "kubeadm-bootstrap", "kubeadm-control-plane"],
  "kustomize_substitutions": {
    "AWS_B64ENCODED_CREDENTIALS": "redacted"
  }
}
```
The `cluster-api-provider-aws` version I have is 0.6.6, pulled locally

3. Using AWS, ensure the cloud-formation stake is up
```
$ clusterawsadm bootstrap iam create-cloudformation-stack
Attempting to create AWS CloudFormation stack cluster-api-provider-aws-sigs-k8s-io
...
```
4. After waiting for cluster-api resources to be available, deploy a cluster:
```
AWS_CONTROL_PLANE_MACHINE_TYPE="m5.large" \
AWS_NODE_MACHINE_TYPE="m5.large" \
AWS_REGION="us-east-2" \
AWS_SSH_KEY_NAME="default" \
KUBERNETES_VERSION="v1.19.1" \
./bin/clusterctl generate cluster johns-aws-cluster --infrastructure=aws:v0.6.6
```
Eventually, the cluster is provisioned. And after applying the CNI to the cluster, it looks ready to use:
```
$ k get nodes
NAME                                       STATUS   ROLES    AGE   VERSION
ip-10-0-71-11.us-east-2.compute.internal   Ready    master   76s   v1.18.0
```

5. Perform a pivot from the local bootstrap cluster to the management cluster
```
 ./bin/clusterctl move --to-kubeconfig bin/capi-cluster.kubeconfig
Performing move...
Discovering Cluster API objects
Error: action failed after 9 attempts: error reading "/, Kind=" /: an empty namespace may not be set when a resource name is provided
```

**What did you expect to happen:**
I would have expected a cluster in the default namespace to have pivoted successfully without any additional intervention.

**Anything else you would like to add:**
I might be missing something, but happy to provide more info as needed

**Environment:**

- Cluster-api version: local dev build. Git sha: `19b900defb84434e3a23d786c311c5daf9d94d6d` 
- Minikube/KIND version: kind v0.10.0 go1.15.7 linux/amd64 
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`): Pop_OS! (ubuntu 20.04)

/kind bug

**Comment by jpmcb** [comment]
Some more info - Providing the `--namespace=default` flag doesn't make a difference.

Here's some of the log output from increased logging level
```
Performing move...
Discovering Cluster API objects
Secret Count=7
ConfigMap Count=2
Total objects Count=12
Excluding secret from move (not linked with any Cluster) name="default-token-j5plf"
Operation failed, retrying with backoff Cause="error reading \"/, Kind=\" /: an empty namespace may not be set when a resource name is provided"
Operation failed, retrying with backoff Cause="error reading \"/, Kind=\" /: an empty namespace may not be set when a resource name is provided"
Operation failed, retrying with backoff Cause="error reading \"/, Kind=\" /: an empty namespace may not be set when a resource name is provided"
Operation failed, retrying with backoff Cause="error reading \"/, Kind=\" /: an empty namespace may not be set when a resource name is provided"
Operation failed, retrying with backoff Cause="error reading \"/, Kind=\" /: an empty namespace may not be set when a resource name is provided"
Operation failed, retrying with backoff Cause="error reading \"/, Kind=\" /: an empty namespace may not be set when a resource name is provided"
Operation failed, retrying with backoff Cause="error reading \"/, Kind=\" /: an empty namespace may not be set when a resource name is provided"
Operation failed, retrying with backoff Cause="error reading \"/, Kind=\" /: an empty namespace may not be set when a resource name is provided"
Error: action failed after 9 attempts: error reading "/, Kind=" /: an empty namespace may not be set when a resource name is provided
sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster.retryWithExponentialBackoff
        /home/jmcb/workspace/github.com/vmware-tanzu/cluster-api/cmd/clusterctl/client/cluster/client.go:257
sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster.(*objectMover).checkProvisioningCompleted
        /home/jmcb/workspace/github.com/vmware-tanzu/cluster-api/cmd/clusterctl/client/cluster/mover.go:221
```

**Comment by fabriziopandini** [comment]
@jpmcb If I'm not wrong you are using tilt to setup your management cluster.

While, this is super convenient to debug controllers, unfortunately it comes at the cost that this is not fully equivalent to what clusterctl init does, and this could have side effects down the path when you do move.
Could you kindly retry by doing clusterctl init instead of tilt up?

**Comment by jpmcb** [comment]
Good catch - I'd be happy to, thanks for the info!

**Comment by jpmcb** [comment]
> Could you kindly retry by doing clusterctl init instead of tilt up?
This was successful and I was able to use move as expected. Thanks for the heads up!!

**Comment by guettli** [comment]
We had this error, too. We found the solution here: https://app.slack.com/client/T09NY5SBT/C8TSNPY4T/thread/C8TSNPY4T-1687782306.609499

**Comment by killianmuldoon** [comment]
>We had this error, too. We found the solution here: [app.slack.com/client/T09NY5SBT/C8TSNPY4T/thread/C8TSNPY4T-1687782306.609499](https://app.slack.com/client/T09NY5SBT/C8TSNPY4T/thread/C8TSNPY4T-1687782306.609499)

@guettli we should hopefully be re-reconciling all of the ownerReferences in core CAPI now. Do you mind sharing what verison of CAPI you ran into this issue with? It could be down to lack of re-reconciliation of ownerReferences in the infrastructure provider - that's something that should be tested for if possible.

**Comment by guettli** [comment]
@killianmuldoon sorry, it was not in my cluster. I don't know the CAPI version.

Maybe it is related to our provider. We use Hetzner, and the issue in the slack channel was about hetzner, too.

Just out of curosity: Checking all resources in a (small dev) cluster for broken ownerRef should not to hard to write.

Do you know a tool which checks all ownerRefs in a cluster?
