### ISSUE TITLE
KCP scale broken in capi v0.4.x

### ISSUE THREAD

**Issue by prksu** [kubernetes-sigs/cluster-api#4847]
**What steps did you take and what happened:**

Before v0.4.x I can scale kubeadmcontrolplane using kubectl like:
```bash
$ kubectl scale kubeadmcontrolplane.controlplane.cluster.x-k8s.io/capg-cluster-control-plane --replicas 3
```

After v0.4.0-beta.x when scaling kubeadmcontrolplane using kubectl i got an error:
```bash
$ kubectl scale kubeadmcontrolplane.controlplane.cluster.x-k8s.io/capg-cluster-control-plane --replicas 3
Error from server: admission webhook "validation.kubeadmcontrolplane.controlplane.cluster.x-k8s.io" denied the request: unable to decode autoscaling/v1, Kind=Scale into *v1alpha4.KubeadmControlPlane
```

Seem it's related to subresource validation https://github.com/kubernetes-sigs/cluster-api/pull/4366

**What did you expect to happen:**
kubeadmcontrolplane can be scaled using kubectl as v0.3.x

**Anything else you would like to add:**
This issue only occur when scaling kubeadmcontrolplane through kubectl scale subcommand, otherwise when editing kubeadmcontrolplane `.spec.replicas` using kubectl edit it works fine

**Environment:**

- Cluster-api version: v0.4.0-beta.1
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by CecileRobertMichon** [comment]
I can repro this as well 

/cc @vincepri

**Comment by CecileRobertMichon** [comment]
@yastij did kcp scale work at the time #4366 merged?

**Comment by yastij** [comment]
that's probably the isue https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go#L146 as we're trying to decode a `Kind=Scale` into a KCP object

**Comment by vincepri** [comment]
Could we get a reproducible test in place with envtest?

**Comment by CecileRobertMichon** [comment]
@yastij should we just disable the validation? seems like it doesn't work and not being able to scale at all is not great

**Comment by prksu** [comment]
@vincepri @CecileRobertMichon @yastij If this validation aims to prevent the users to scale the kcp to have even numbers of replicas, why not just validate `.spec.Replicas` like this https://github.com/kubernetes-sigs/cluster-api/blob/bc94459d95c6809875ea78bb748e766165a09c2a/controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go#L240-L259

I can confirm in `v0.4.x`, I can scale kcp to 4 replicas through kubectl edit kcp (which is the issue that we need to solve using the validation https://github.com/kubernetes-sigs/cluster-api/issues/4057)

**Comment by sbueringer** [comment]
> > and instead register a different one that works against the scalev1.Scale resource
> 
> @vincepri can you expand on this? How can we register a webhook that works against a scale resource?

> https://github.com/kubernetes-sigs/cluster-api/blob/53d99d849d63e2bcfdacea4869b288952e0f50a6/controlplane/kubeadm/config/webhook/manifests.yaml#L81

If I grepped correctly KCP is the only type where we register a validating webhook on /scale.
