### ISSUE TITLE
clusterctl does not honor contract metadata when looking up latest release for providers

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#4856]
**What steps did you take and what happened:**

Using `clusterctl` v0.3.x without explicitly specifying component versions breaks now that v0.4.0 is released.

```sh
> clusterctl init
Fetching providers
Error: current version of clusterctl could install only v1alpha3 providers, detected v1alpha4 for provider cluster-api
> clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.19", GitCommit:"665d56652a787180dc36ecbfdf183b1e436fba75", GitTreeState:"clean", BuildDate:"2021-06-09T18:20:15Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you expect to happen:**

`clusterctl` to install the latest version compatible with clusterctl

**Anything else you would like to add:**

This is following up from a Slack conversation: https://kubernetes.slack.com/archives/C8TSNPY4T/p1624629661483900

Users that were relying on things to work consistently found automation that they had built broken immediately after the v0.4.0 release was published.

**Environment:**

- Cluster-api version: v0.3.19
- Minikube/KIND version: v0.11.1
- Kubernetes version: (use `kubectl version`): v1.13.1

/kind bug

**Comment by timfpark** [comment]
Would be good to at least document somewhere that you can avoid this by explicitly specifying the version, ala:

```
$ clusterctl init --infrastructure azure -b kubeadm:v0.3.19 -c kubeadm:v0.3.19 --core cluster-api:v0.3.19
```

**Comment by detiber** [comment]
The documentation is definitely important, but I think it's quite a bit surprising for a user for the tool to work one day and then not work the next just because a new incompatible release was published.

I'd be less concerned if we were talking about a version of clusterctl that was no longer supported, but my understanding is that we plan to continue bugfix and best effort support for v1alpha3/v0.3.x of CAPI

**Comment by likamrat** [comment]
Just hit the same issue

**Comment by CecileRobertMichon** [comment]
I'm going to look into solving this 

/assign

**Comment by benc-uk** [comment]
Thanks @timfpark your command overriding the versions, just saved me a LOT of time
