### ISSUE TITLE
capi-e2e-main-1-21-latest should upgrade to CoreDNS version 1.8.4

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4857]
**Detailed Description**
As per https://github.com/kubernetes/kubernetes/pull/102466 the capi-e2e-main-1-21-latest should upgrade to CoreDNS version 1.8.4

Changes should be applied to https://github.com/kubernetes/test-infra/blob/f668b08714d2974ff1fbe68302050d74e4bbedf4/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-main-upgrades.yaml#L164

Same for capi-pr-e2e-main-1-21-latest; in this case Changes should be applied to https://github.com/kubernetes/test-infra/blob/f668b08714d2974ff1fbe68302050d74e4bbedf4/config/jobs/kubernetes-sigs/cluster-api/cluster-api-presubmits-main.yaml#L238

/kind feature

/help
/good-first-issue

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue

**Comment by Evalle** [comment]
@himanshu007-creator hi! Feel free to assign it to yourself via (`/assign <nickname>`). Thanks!

**Comment by himanshu007-creator** [comment]
\assign himanshu007-creator
