### ISSUE TITLE
Consider if to add Patches field to InitConfiguration and JoinConfiguration

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4874]
**Detailed Description**

https://github.com/kubernetes/kubernetes/pull/103063 recently added `InitConfiguration.Patches.Directory`, `JoinConfiguration.Patches.Directory` to allow the user to configure a directory from which to take patches for components deployed by kubeadm.

Should we add the same to the KubeadmConfig type in CAPI?

**Anything else you would like to add:**

IMPORTANT: This will work only on clusters with Kubernetes version >= 1.22

/kind feature
/area bootstrap

**Comment by sbueringer** [comment]
I think it would be really useful. We had to use the functionality to patch requests/limits/initContainer/... of the control plane static pod manifests because kubeadm didn't expose those fields.

**Comment by randomvariable** [comment]
I've seen requests to enable this. In particular in vSphere environments, some folks switch off their entire cluster, and when they turn it back on the entire cluster goes into CrashLoopBackoff as every etcd node complains about missing nodes on it's health status even though it's available. It's possible to work around it by changing the livenessProbe to check only that serializable (local) read, e.g.

```sh
ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key get --consistency="s" foo
```

I will also check in kubeadm to see if we should change the livenessProbe entirely as it seems wrong to have the entire cluster go into crashLoopBackoff and never recover.

**Comment by vincepri** [comment]
We should definitely file a bug in upstream kubeadm as well

**Comment by neolit123** [comment]
looks like @randomvariable filed the kubeadm ticket. it also links to a new etcd repo ticket, where the main question is how to enable more granular checks or relax the existing checks.
feels like adjusting this in kubeadm should be done.

kubeadm patches in CAPI make sense in general and @randomvariable and me discussed this today at the VMware slack.

**Comment by fabriziopandini** [comment]
/remove-lifecycle stale
given that there is a PR out for it
