### ISSUE TITLE
Kubeadm join yaml gets purged by SystemD

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/cluster-api#4876]
**What steps did you take and what happened:**
Im trying to bootstrap bare metal nodes with CAPI and have hit the issue that systemd purges files from tmp before kubeadm join runs. There is a warning about this in the cloud-init docs about that, too ( https://cloudinit.readthedocs.io/en/latest/topics/modules.html#write-files )
This also has been fixed in v1a4 but noct backported to a3 ( https://github.com/kubernetes-sigs/cluster-api/pull/3776 )

**What did you expect to happen:**
kubeadm init works

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v1alpha3 0.3.19
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by MaxRink** [comment]
i had a short exchange with @fabriziopandini on slack about this: https://kubernetes.slack.com/archives/C8TSNPY4T/p1625393799083100

**Comment by MaxRink** [comment]
@vincepri mentioned in Slack that we should backport this, while adding a big warning

**Comment by MaxRink** [comment]
Ive put up a PR to backport the behaviour: https://github.com/kubernetes-sigs/cluster-api/pull/4884

**Comment by CecileRobertMichon** [comment]
/close

fixed by #4884
