### ISSUE TITLE
ClusterResourceSet feature does not work

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#4878]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

Please refer to https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/155 for detail.

Follow the proposal guides:
- https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20200220-cluster-resource-set.md
- https://cluster-api.sigs.k8s.io/tasks/experimental-features/experimental-features.html?highlight=ClusterResourceSet#enabling-experimental-features-on-existing-management-clusters

1. Deploy two nested clusters in Kind
2. Enable ClusterResourceSet feature
3. Create secret and configmap by the samples from 20200220-cluster-resource-set.md
4. Create ClusterResourceSet by the sample from 20200220-cluster-resource-set.md
The following problem appears, but the two apiservers are running normally by kubectl command.

```
E0702 09:08:52.250697       1 controller.go:302] controller-runtime/manager/controller/clusterresourceset "msg"="Reconciler error"
 "error"="error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster \"default/cluster-sample\":
 Get \"https://cluster-sample-apiserver:6443/api?timeout=10s\": dial tcp: lookup cluster-sample-apiserver on 10.96.0.10:53: server misbehaving"
  "name"="crs1" "namespace"="default" "reconciler group"="addons.cluster.x-k8s.io" "reconciler kind"="ClusterResourceSet"
E0702 09:07:16.064594       1 controller.go:302] controller-runtime/manager/controller/clusterresourceset "msg"="Reconciler error"
 "error"="error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster \"default/cluster-virtual\":
 Get \"https://cluster-virtual-apiserver:6443/api?timeout=10s\": dial tcp: lookup cluster-virtual-apiserver on 10.96.0.10:53: server misbehaving"
 "name"="crs1" "namespace"="default" "reconciler group"="addons.cluster.x-k8s.io" "reconciler kind"="ClusterResourceSet"
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
The errors seem to hint to a network issue, which isn't necessarily related to ClusterResourceSet

**Comment by randomvariable** [comment]
>  dial tcp: lookup cluster-sample-apiserver on 10.96.0.10:53: server misbehaving

suggests DNS resolution failure. `cluster-sample-apiserver` needs to be reachable from the various pods.

**Comment by gyliu513** [comment]
Thanks @randomvariable and @vincepri , let me retest.

@wangjsty ^^

**Comment by vincepri** [comment]
Closing this due to lack of updates, please feel free to reopen if you have more details

/close
