### ISSUE TITLE
Turn of dependabot

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#4879]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

Github actions have defeated me. Although the commit code action was working fine in CAPA two weeks ago, it's now stopped working both here and there and I've yet to figure it out.

**What did you expect to happen:**

It should have worked.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
Should we just disable it for good? I didn't find much of an issue updating the dependencies manually, but it's definitely nice to have it automated

**Comment by furkatgofurov7** [comment]
Not sure, what is exactly the problem with dependabot, but @randomvariable @vincepri have you checked/looked into pretty much the same tool, [renovate](https://github.com/renovatebot/renovate), by any chance?

**Comment by randomvariable** [comment]
We need it to run `make generate` before opening the PR, which we did have via Github action in the AWS repo, but it's now stopped working.

**Comment by randomvariable** [comment]
SIG Security is looking at Snyk at the moment, so we'll wait for the outcome of that work.
