### ISSUE TITLE
docker provider does not work for the latest capi code.

### ISSUE THREAD

**Issue by dongwangdw** [kubernetes-sigs/cluster-api#4887]
I tried to follow the quick start doc https://cluster-api.sigs.k8s.io/user/quick-start.html.
And I used to docker as the provider. But the cluster is pending as 
```
NAME              PHASE
capi-quickstart   Provisioning
```
I get the cluster api controller  manger pod log and found 
```
machine_controller_noderef.go:48] controller-runtime/manager/controller/machine 
"msg"="Cannot reconcile Machine's Node, no valid ProviderID yet" 
"cluster"="capi-quickstart" "machine"="capi-quickstart-md-0-56bc7997f7-mrjxj" 
"name"="capi-quickstart-md-0-56bc7997f7-mrjxj" 
"namespace"="default" 
"reconciler group"="cluster.x-k8s.io" 
"reconciler kind"="Machine"
```

Is this a bug or I missed anything?

**Comment by CecileRobertMichon** [comment]
@dongwangdw which versions of clusterctl, docker and capi are you using?

**Comment by sbueringer** [comment]
@dongwangdw It should work as we're running this in CI. There might be some additional infos in the capd manager logs.

**Comment by dongwangdw** [comment]
Let me show my cmd binary version.
clusterctl is built from the latest code.
```
clusterctl version: &version.Info{Major:"0", Minor:"4", GitVersion:"v0.4.0-18-65a66179b95f2e", GitCommit:"65a66179b95f2e6f5ba94dd9fff92c9c90330891", GitTreeState:"clean", BuildDate:"2021-07-06T07:22:36Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

docker version 
```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Fri Dec 18 12:15:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Fri Dec  4 23:02:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.3
  GitCommit:
 runc:
  Version:          spec: 1.0.2-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

**Comment by sbueringer** [comment]
@dongwangdw Just to confirm (because it's a frequently occuring error), did you create the kind cluster with `/var/run/docker.sock` mounts?

**Comment by sbueringer** [comment]
I just went through the quickstart guide again with release v0.4.0 and it worked (cluster v0.4.0, Docker 20.10.7, kind v0.11.1, MacOS). I think the only way to reasonably debug this is with the CAPD manager logs.

**Comment by dongwangdw** [comment]
> @dongwangdw Just to confirm (because it's a frequently occuring error), did you create the kind cluster with `/var/run/docker.sock` mounts?

No, I just follow the quick start doc on my ubuntu 20.04.  

>I just went through the quickstart guide again with release v0.4.0 and it worked (cluster v0.4.0, Docker 20.10.7, kind v0.11.1, MacOS).

And I reproduced it with a updated docker version 20.10.2:
I can not do this in my mac because the network.
Can you please verify this in Ubuntu? This will make more sense to me.

My cmd is simple:

```clusterctl init -i docker```
AND
```
clusterctl generate cluster capi-quickstart --flavor development \
  --kubernetes-version v1.19.7 \
  --control-plane-machine-count=3 \
  --worker-machine-count=3 | kubectl apply -f -
```

Did I miss anything?

>It should work as we're running this in CI. There might be some additional infos in the capd manager logs.

What kind of env of the CI

**Comment by dongwangdw** [comment]
I have found some errors which might be helpful
```
controller-runtime/manager/controller/dockercluster "msg"="Reconciler error" 
"error"="failed to create helper for managing the externalLoadBalancer: failed to list containers: failed to list nodes. 
Output: [Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?]: command \"docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster --format '{{.Names}}\\t{{.Label \"io.x-k8s.kind.cluster\"}}\\t{{.Image}}\\t{{.Status}}' --filter label=io.x-k8s.kind.cluster=capi-quickstart --filter label=io.x-k8s.kind.role=external-load-balancer\" failed with error: exit status 1" 
```

>Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
With this line, should I set the docker with this sock file? How to make it?

**Comment by dongwangdw** [comment]
It is resolved. 
I missed the kind configuration in the quick start:
![Screen Shot 2021-07-09 at 10 30 15 AM](https://user-images.githubusercontent.com/2303377/125014658-af937d80-e0a0-11eb-96a5-0b73c2bee59b.png)

I should choose docker instead of 0.9.x.
After I have kind configured, it works.

Maybe we can update the book to split the tabs here to a explicit step.
close this issue.
