### ISSUE TITLE
Docs: Quick Start refers to older version of clusterctl as part of curl installation process

### ISSUE THREAD

**Issue by karuppiah7890** [kubernetes-sigs/cluster-api#4888]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

Following

https://cluster-api.sigs.k8s.io/user/quick-start.html

One of the steps is - Install clusterctl - https://cluster-api.sigs.k8s.io/user/quick-start.html#install-clusterctl

It refers to `v0.3.20` in the installation, so if one does this on MacOS (or any OS) using curl

```bash
curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.3.20/clusterctl-darwin-amd64 -o clusterctl

chmod +x ./clusterctl

sudo mv ./clusterctl /usr/local/bin/clusterctl

clusterctl version
```

And follow along with the other steps - assuming I want to work with Docker based local clusters

```bash
clusterctl init --infrastructure docker
```

And finally try to generate a cluster configuration

```bash
$ clusterctl generate cluster capi-quickstart --flavor development \
  --kubernetes-version v1.19.7 \
  --control-plane-machine-count=3 \
  --worker-machine-count=3 \
  > capi-quickstart.yaml
Error: unknown flag: --flavor
```

I get the error - `Error: unknown flag: --flavor`

This is because the above command works only in `v0.4.0` where `--flavor` is defined and does not work in `v0.3.20`

**What did you expect to happen:**

The commands mentioned in docs to work according to the mentioned install version

**Anything else you would like to add:**

I can think of two ways to fix this issue, either

- Change the doc to mention the latest version as part of installation process, which is `v0.4.0`

OR

- Fix the command to the old command that works in `v0.3.20`

```bash
$ clusterctl config cluster capi-quickstart --flavor development \
  --kubernetes-version v1.18.16 \
  --control-plane-machine-count=3 \
  --worker-machine-count=3 \
  > capi-quickstart.yaml
```

**Environment:**

- Cluster-api version: 

```bash
$ clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.20", GitCommit:"ea9dc4bdc2a9938325aab3817ece3e654873aaab", GitTreeState:"clean", BuildDate:"2021-06-30T22:21:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
```

- Minikube/KIND version:

```bash
$ kind version
kind v0.11.1 go1.16.4 darwin/amd64
```

- Kubernetes version: (use `kubectl version`): 

```bash
$ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
```

- OS (e.g. from `/etc/os-release`): MacOS

```bash
$ uname -a
Darwin karuppiahn 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
```

/kind bug
/area clusterctl
/sig docs

**Comment by CecileRobertMichon** [comment]
Hi @karuppiah7890, thanks for opening this issue. The v0.4.0 release of Cluster API was just released 2 weeks ago and most of the infrastructure providers besides Docker don't have a release yet for v1alpha4 that is compatible with v0.4.0 which is why the version in the quickstart hasn't been updated yet. However, it's an oversight that the quickstart refers to a new command (clusterctl generate) that was added in v0.4. 

I suggest we change the clusterctl version to v0.4 in the quickstart (by changing `version:"0.3.x"` to `version:"0.4.x"`) and add a warning that says if you are you using an infrastructure provider that hasn't released v1alpha4 yet, use https://release-0-3.cluster-api.sigs.k8s.io/user/quick-start.html - the link doesn't work yet because https://github.com/kubernetes/k8s.io/pull/2269 has yet to merge (cc @vincepri) but hopefully we can fix that very soon .

**Comment by karuppiah7890** [comment]
Thanks for the insight @CecileRobertMichon ! :) Makes sense 👍

**Comment by CecileRobertMichon** [comment]
@karuppiah7890 would you like to open the PR to make the fix?

**Comment by karuppiah7890** [comment]
I'm not sure about the internals of v1alpha3 vs v1alpha4 and there also seems to be a dependency on waiting for the other PR to get merged. I'll let you folks handle it. Probably at a later time when I have the bandwidth, I'll check out issues and see if I can help :)
