### ISSUE TITLE
Depreacate partial upgrade E2Etest

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4896]
**Detailed Description**

Originally in our E2E test we implemented upgrade tests for single CAPI resources:

- KCPUpgradeSpec
- MachineDeploymentUpgradesSpec 
- MachinePoolSpec

This is now superseed by ClusterUpgradeConformanceSpec, which upgrades all the resources, makes sure CP is upgraded before nodes (thus being compliant with K8s recommendations), and runs conformance on the resulting test.

We should now consider if to deprecate or refactor the legacy tests. e.g.
- KCPUpgradeSpec might still have sense, because it tries different topologies of control plane vs what we usually have in KCPUpgradeSpec
- MachineDeploymentUpgradesSpec should be re-focused to test rollout when the infrastructure template changes.
- MachinePoolSpec should be re-focused on test MachinePool machinery (except upgrades)

However, before taking a decision we should investigate if/how those test are used in the providers...
 
/kind cleanup

@sbueringer

**Comment by randomvariable** [comment]
It might be useful to have a version that doesn't have a conformance test, or maybe a simple smoke test so you can test different scenarios in your provider without a full multi-hour run.

**Comment by sbueringer** [comment]
> It might be useful to have a version that doesn't have a conformance test, or maybe a simple smoke test so you can test different scenarios in your provider without a full multi-hour run.

Could we specify this via a field on the `SpecInput`s? (i.e. always doing some kind of smoke test and conditionally executing the conformance tests)

**Comment by fabriziopandini** [comment]
+1 to have a single ClusterUpgradeConformanceSpec with some flags to skip steps

**Comment by CecileRobertMichon** [comment]
We are using those in CAPZ, +1 to being able to run upgrade tests without running the full conformance test

**Comment by randomvariable** [comment]
> Could we specify this via a field on the SpecInputs

That could work. In fact, our internal team probably have a regex that we can document or constantize on the conformance focus that functions as a smoke test.

**Comment by fabriziopandini** [comment]
@killianmuldoon ^^

**Comment by CecileRobertMichon** [comment]
/assign

@randomvariable could you please share the regex you mentioned above?

**Comment by sbueringer** [comment]
/reopen

Just reopening for a short discussion instead of creating a new issue. (we just had this discussion somewhere again).

`MachineDeploymentUpgradesSpec` and `MachinePoolSpec` have been refactored.

I wonder if we should deprecate `KCPUpgradeSpec` given that the same can be achieved with `ClusterUpgradeConformanceSpec` by:
* adding a new `ControlPlaneMachineCount` field to `ClusterUpgradeConformanceSpec`
* setting `SkipConformanceTests` to true

I think the only downside is that the tests would also check if the MD is rolled out, but I don't think that's a bad thing

@fabriziopandini @CecileRobertMichon WDYT?

**Comment by CecileRobertMichon** [comment]
> I think the only downside is that the tests would also check if the MD is rolled out, but I don't think that's a bad thing

for cloud providers that take more time to create Machines (ie. not Docker) it can be very time-consuming to roll out the whole cluster in the tests. 

if we make both ControlPlaneMachineCount and WorkerMachineCount configurable with the current values as defaults that would work. Someone could theoretically set worker count to 0 to recreate the same test and mitigate the above.

**Comment by sbueringer** [comment]
Sounds good to me!

**Comment by fabriziopandini** [comment]
+1 to have flags that makes this test configurable
we can use machine counts but also simple boolean flags to decide which tasks to perform: e.g
- I want (i have) to deploy 1 CP node. but I don't want to upgrade it
- I don't  want to run the conformance tests

**Comment by CecileRobertMichon** [comment]
@sbueringer I updated to CAPI v1.1.0-beta.1 which has this deprecation and updated the current KCP upgrade tests to use cluster upgrade tests with WorkerMachine count set to 0 for the HA scale in and scale out tests, but I'm getting this error:

```
/home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.1.0-beta.1/e2e/cluster_upgrade.go:115
Invalid argument. input.MachineCount can't be smaller than 1 when calling WaitForMachineDeploymentMachinesToBeUpgraded
Expected
    <int>: 0
to be >
    <int>: 0
/home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.1.0-beta.1/framework/machine_helpers.go:164
```

looks like we need to skip the machine deployment phases when the count is 0

**Comment by sbueringer** [comment]
@CecileRobertMichon Thx for reporting it. I agree. I've opened #5926 to fix the test.

I verified it locally and it works now.
