### ISSUE TITLE
Use the cluster name in cluster.yaml in admin.conf

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#49]
_From @karan on March 6, 2018 17:29_

Currently the cluster config is created with cluster name as `kubernetes`. There is a cluster name in the `cluster.yaml` `metadata.name`. We should start using that name for the cluster so tools can be made to target any cluster in kubeconfig file.

_Copied from original issue: kubernetes/kube-deploy#636_

**Comment by rsdcastro** [comment]
_From @karan on March 6, 2018 17:36_

cc @jessicaochen @rsdcastro - If no objections, I can start to look into this.

**Comment by rsdcastro** [comment]
It does make sense to me.

**Comment by rsdcastro** [comment]
_From @karan on March 6, 2018 17:54_

Seems like the cluster name is hardcoded in kubeadm:

https://github.com/kubernetes/kubernetes/blob/999c2ae8716b76099b30da4cea973d0e2c737f77/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L191

There's been a PR to make it configurable, but it's been stale: https://github.com/kubernetes/kubernetes/pull/52470

**Comment by rsdcastro** [comment]
Perhaps we can work on a new PR that focus on the cluster name to avoid the contention on the other point (user admins)?

**Comment by rsdcastro** [comment]
_From @jessicaochen on March 6, 2018 18:9_

I may be wrong but I think it is just the name in the kubeconfig file to reference the cluster. If you change the name in the kubeconfig file or set a new one with the name your want (https://kubernetes-v1-4.github.io/docs/user-guide/kubectl/kubectl_config_set-cluster/), you can still address the same cluster.

In that way, it really does not matter what kubeadm happens to dump as the cluster name on the master.

**Comment by rsdcastro** [comment]
_From @karan on March 6, 2018 18:15_

You are right @jessicaochen. I tried this with `s/kubernetes/testcluster` on my local kubeconfig file. I don't think we should be doing this in the final product, it's just hacky, and error prone. Instead the cluster name really just should be an option that kubeadm uses to save the original file.

**Comment by rsdcastro** [comment]
_From @jessicaochen on March 6, 2018 18:19_

I guess it depends on how important urgent this change is. Whether we want to wait for kubeadm to do it or we want an interim solution.

**Comment by rsdcastro** [comment]
_From @karan on March 6, 2018 22:18_

/label cluster-api

**Comment by rsdcastro** [comment]
_From @karan on March 7, 2018 16:55_

As a prototype we could live with managing a single cluster (or doing something hacky), but at least for an alpha/MVP, a good approach is to support cluster names.

I've already sent them a [PR for it](https://github.com/kubernetes/kubernetes/pull/60852).

**Comment by roberthbailey** [comment]
Cluster name is a provider specific implementation.

/close
