### ISSUE TITLE
Add e2e test for kubeadm feature RootlessControlPlane

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#4902]
**User Story**

As an operator I would like to be able to run the control plane as non-root (which can be achieved via the kubeadm feature `RootlessControlPlane`).

**Detailed Description**

Some context: Kubernetes 1.22 Changelog:
> Kubeadm: add the RootlessControlPlane kubeadm specific feature gate (Alpha in 1.22, disabled by default). It can be used to enable an experimental feature that makes the control plane component static Pod containers for kube-apiserver, kube-controller-manager, kube-scheduler and etcd to run as a non-root users. (#102158, @vinayakankugoyal) [SIG Cluster Lifecycle]

**Anything else you would like to add:**

The main questions we have to discuss first is when and how we want to test it. For now it's an alpha flag in kubeadm (1.22) and disabled per default.

Notes:
* As this feature matures we might want to reconsider: #4180
/kind feature

**Comment by neolit123** [comment]
the kubeadm test for this feature were added here:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-rootless-latest
(it has some unrelated k8s e2e test suite flakes)

the test workflow is defined here:
https://github.com/kubernetes/kubeadm/blob/master/kinder/ci/workflows/rootless-tasks.yaml

it contains some tasks to run a bash script on the nodes ensuring users / groups of the containers are the expected ones after cluster creation and after the kubeadm upgrade (mutable, not used by CAPI's upgrade).

if Cluster API e2e test is desired, i'd assume it would want to do similar checks.

**Comment by neolit123** [comment]
> As this feature matures we might want to reconsider: FeatureGates in KubeadmControlPlane Spec should be mutable  #4180

in the future kubeadm might do more changes behind feature gates - e.g. "etcd learner mode".

the way k8s feature gates graduate is that they always default to enabled once they reach Beta (disabled for Alpha), which means CAPI would get it without an explicit toggle. also sane downstream consumption of kubeadm features should be >= Beta in production at least.

but if there is no toggle on the CAPI side, this leaves it without test signal during the Alpha period of said features.
e.g. for the "rootless" feature we are testing a single Linux distribution (Ubuntu) in the kubeadm test.

**Comment by vinayakankugoyal** [comment]
Should we update the issue description to include the word kubeadm, to make it clear what the scope is?

**Comment by PushkarJ** [comment]
+ 1

**Comment by fabriziopandini** [comment]
The graduation of this feauture in kubeadm depends on kubelet work still being defined.
let's keep this on hold until the above point is sorted out
/remove-lifecycle stale

**Comment by fabriziopandini** [comment]
@neolit123 is there any update in kubeadm/kubelet for this effort?

**Comment by neolit123** [comment]
We are waiting to see if the user namespace kep will make alpha in 1.25.
I think the kubeadm alpha  rootless cp e2e might be enough signal, so you can put the capi e2e on hold. If the kubeadm rootless cp goes beta capi can add e2e too.
