### ISSUE TITLE
Add ClusterClass proposal API types

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4908]
**Detailed Description**

As an initial activity for the implementation of the [ClusterClass proposal](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/202105256-cluster-class-and-managed-topologies.md) we should add/change API types ad defined in the proposal.

This change should also include web hook changes as defined by the document in the [validation paragraph](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/202105256-cluster-class-and-managed-topologies.md#validations); This can be eventually a follow up PR if we want to parallelise work. 

With this regard I suggest some small amendments to the proposal

ClusterClass

- For object updates:
   - spec.worker.deployments[i].class field must be unique within a ClusterClass (added; it is already there for object create)

Cluster

- For object creation:

  - spec.topology and spec.infrastructureRef cannot be simultaneously set (added; there is already a similar check for controlPlaneRef)

 @srm09 @vincepri PTAL to the proposed amendments to the proposal

/kind feature

**Comment by srm09** [comment]
Nice catch @fabriziopandini , missed these :)
