### ISSUE TITLE
Setup tilt environment for the CAPI operator

### ISSUE THREAD

**Issue by alexander-demichev** [kubernetes-sigs/cluster-api#4916]
In order to provide a similar dev experience for operator, we should set up tilt environment as it is done for other CAPI components.

https://github.com/kubernetes-sigs/cluster-api/issues/4246

/kind feature
/area operator

**Comment by fabriziopandini** [comment]
@alexander-demichev any objection to close this now that the work is being moved in a separated repo?

**Comment by alexander-demichev** [comment]
👍
/close
