### ISSUE TITLE
Move operator API to v1alpha1

### ISSUE THREAD

**Issue by alexander-demichev** [kubernetes-sigs/cluster-api#4917]
The operator API types were initially scaffolded with v1alpha4 version. This is a new API group so it's more relevant to start from v1alpha1.

https://github.com/kubernetes-sigs/cluster-api/pull/4520#discussion_r638888843

/area operator

**Comment by fabriziopandini** [comment]
I dont'see problems in this, except the risk of generating a little bit of confusion in the users, but let's discuss this in the Office hours for broader feedback
