### ISSUE TITLE
capi-e2e-main-1-21-latest fails because of CoreDNS RBAC issues

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#4927]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

After we changed our 1.21=>latest upgrade tests to CoreDNS 1.8.4 they are failing now ([testgrid](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main-1-21-latest))

**What did you expect to happen:**
They should still work.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

CoreDNS 1.8.4 also uses EndpointSlices. Thus the ClusterRole `system:coredns` has been adapted in kubeadm (https://github.com/kubernetes/kubernetes/pull/102466/files). As we're installing the cluster with 1.21 and then just updating to 1.22 we still have the old ClusterRole. I assume we have to ensure that starting with CoreDNS 1.8.4 the ClusterRole also includes EndpointSlices. 

This problem affects all clusters installed with kubeadm < 1.22 when using CoreDNS >= 1.8.4.

Currently our jobs do not fail when the conformance test fails, but this should be fixed through #4907.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
Potential implementation:
* Patch the `system:coredns` ClusterRole somewhere in `UpdateCoreDNS` if (CoreDNS) `version` >= 1.8.4

**Comment by fabriziopandini** [comment]
@vincepri @sbueringer KCP should take care of fixing CoreDNS RBAC rules during upgrades to 1.22

TBD if this should be back ported (AFAIK there are also other problems with the 0.3 version of controller runtime/tools on 1.22)

**Comment by sbueringer** [comment]
As we want to mirror the compatibility of kubeadm <=> CoreDNS we want to support:
* Kubernetes >= 1.22 with CoreDNS >= 1.8.1 (endpoint slice support was added with [1.8.1](https://coredns.io/2021/01/20/coredns-1.8.1-release/))

So for v1alpha4 with Kubernetes >= 1.22 and CoreDNS >= 1.8.1 this means:
* newly created cluster already work because `kubeadm init` uses the correct `ClusterRole`
* for Kubernetes cluster >= 1.22 which update to CoreDNS >= 1.8.1 we have to implement some update logic

Note:
* I think CoreDNS versions 1.8.1-1.8.3 should not be used as there was a bug with the endpoint slices support: https://github.com/kubernetes/kubernetes/issues/99751#issuecomment-825735336

**Comment by randomvariable** [comment]
The proposed method sounds fine, and much like the other upgrade behaviour we have.

**Comment by sbueringer** [comment]
Note to myself: let's cherry-pick this into v1alpha3

**Comment by sbueringer** [comment]
/reopen 
to track the cherry-pick for v0.3.*

**Comment by sbueringer** [comment]
/close

(cherry-pick merged)
