### ISSUE TITLE
Reconsider how we compare Kubernetes versions

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#4938]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

During the implementation of https://github.com/kubernetes-sigs/cluster-api/pull/4937 I discovered that my initial implementation of the update logic did not apply to beta versions of Kubernetes 1.22. I used a Kubernetes version parsed by `semver.ParseTolerant` and wanted to execute the logic for all versions >= v1.22.0. As the beta version was < v1.22.0 the logic wasn't executed. The problem is that every time we compare like this our version-dependent code of the previous version is executed. This also means that when we implemented new logic for e.g. v1.22 we only start testing it *after* the v1.22 release.

We should check all usages of https://github.com/kubernetes-sigs/cluster-api/search?q=semver.ParseTolerant if the subsequent usage of the parsed values is safe. Potential solutions are:
* parse with `version.ParseMajorMinorPatchTolerant` as it only parses major/minor/patch and ignores everything else
* compare against a `zero release` version which is "less then" all other versions of the same release.

**What did you expect to happen:**
Code for a new release should already apply to beta versions.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: default branch
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
I would say the problem is not in how we Parse, but in what we expect from compare because we are considering build version to be higher than our thresholds.

Thus I think that we should go for the second option; might be we can also consider to implement out custom compare function, thus making this more explicit in the code

**Comment by sbueringer** [comment]
@fabriziopandini You're right. I changed the title and some details of the description to reflect that better.

**Comment by sbueringer** [comment]
@fabriziopandini WDYT, could this be a good first issue with some more actionable information what to do (and where)?

**Comment by fabriziopandini** [comment]
TBH I don't think this qualifies as a good first issue, given it is required to skim through the entire codebase and make evaluations case by case

**Comment by sbueringer** [comment]
I was thinking of doing that part myself and then producing a list here what exactly has to be done

**Comment by SubhasmitaSw** [comment]
Hello there, @sbueringer and @fabriziopandini. I'd want to take up this issue could you provide some further information to assist me to close it?

**Comment by sbueringer** [comment]
Okay interesting. @SubhasmitaSw Thx for your interest! :)

I think we can split this task in two:
* [ ] extend our current version.Compare func to be able to compare versions the way we want.
* [ ] go through our entire existing code and make sure we always use the right compare func.

I can take care of the second part as it's relatively complicated to go through the entire code and assess and which situation we want to compare which way.

About the first part:
* We have our own Compare func in `util/version.Compare` (https://github.com/kubernetes-sigs/cluster-api/blob/c0668a0dbf3ae48dc0f8953ef76860bd6c656bd8/util/version/version.go#L209-L224)
* Per default it is just calling compare of the semver library
* We already have an option to customize comparisons `WithBuildTags`
* I think we can add a new option `IgnorePreReleases`
* If this option is set we should set the `Pre` fields of both versions to nil before calling any `Compare` funcs

Please let me know if you have further questions :)


@fabriziopandini btw the code we recently added for v1.24 ConfigMap handling is not used yet, as our upgrade job is still upgrading to v1.24 alpha versions which are lower than v1.24.0. I think we should consider backporting those two PRs once they have been merged on main.

**Comment by fabriziopandini** [comment]
> @fabriziopandini btw the code we recently added for v1.24 ConfigMap handling is not used yet, as our upgrade job is still upgrading to v1.24 alpha versions which are lower than v1.24.0. I think we should consider backporting those two PRs once they have been merged on main.

This is not true because the comparison considers only major/minor and drops everything else 

https://github.com/kubernetes-sigs/cluster-api/blob/f973e33a597196416d8a034af469439ff92d3ccc/controlplane/kubeadm/internal/workload_cluster_rbac.go#L107

There is also a specific unit test for this

https://github.com/kubernetes-sigs/cluster-api/blob/f973e33a597196416d8a034af469439ff92d3ccc/controlplane/kubeadm/internal/workload_cluster_rbac_test.go#L81-L89

**Comment by SubhasmitaSw** [comment]
> @SubhasmitaSw Thx for your interest! :)
> 
> I think we can split this task in two:
> 
> * [ ]  extend our current version.Compare func to be able to compare versions the way we want.
> * [ ]  go through our entire existing code and make sure we always use the right compare func.
> 
> I can take care of the second part as it's relatively complicated to go through the entire code base and assess in which situation we want to compare which way.
> 
> About the first part:
> 
> * We have our own Compare func in `util/version.Compare` (https://github.com/kubernetes-sigs/cluster-api/blob/c0668a0dbf3ae48dc0f8953ef76860bd6c656bd8/util/version/version.go#L209-L224
>   )
> * Per default it is just calling compare of the semver library
> * We already have an option to customize comparisons `WithBuildTags`
> * I think we can add a new option `WithoutPreReleases`
> * If this option is set we should set the `Pre` fields of both versions to nil before calling any `Compare` funcs
> 
> Please let me know if you have further questions :)
> 
> @fabriziopandini btw the code we recently added for v1.24 ConfigMap handling is not used yet, as our upgrade job is still upgrading to v1.24 alpha versions which are lower than v1.24.0. I think we should consider backporting those two PRs once they have been merged on main.

I'll try this and let you know if I struggle somewhere. Thanks for the detailed info!

**Comment by sbueringer** [comment]
@SubhasmitaSw 
Great! Feel free to ask or just open a WIP PR (pr with `[WIP] ` prefix) if I should take a look.

@fabriziopandini Ah you're right, I missed that part!

**Comment by fabriziopandini** [comment]
/lifecycle frozen
given that it seems we have a path forward
