### ISSUE TITLE
Should we support downgrades in ManagedTopologies?

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4939]
**Detailed Description**
from https://github.com/kubernetes-sigs/cluster-api/pull/4928#discussion_r669473690

In the proposal for ClusterClass and managed topologies we are introducing a constraint that prevents the Kubernetes version to be decreased.

Should we not support any kind of rollback instead? How this should work?

/kind feature

**Comment by sbueringer** [comment]
I wonder what kind of downgrades are supported by Kubernetes itself (minor/patch)?

I'm not sure where I picked that up, but I thought downgrading a Kubernetes minor version is not safe (or at least not without rolling back to an old etcd snapshot/backup).

**Comment by fabriziopandini** [comment]
Moving to Next, Downgrades requires a bigger discussion and I don't think we can tackle this in this iteration
