### ISSUE TITLE
Lag from the nodes go ready and when they are counted as available by the owner MachineSet.

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#4946]
**What steps did you take and what happened:**
Creating a MachineDeployment and wait for replicas to go available. I'm seen a considerable lag from the moment the nodes go ready and the moment they are counted as available by the owner MachineSet.

**What did you expect to happen:**
As soon as Nodes go ready this is conveyed in the MachineSet/MachineDeployment available replicas.
This is critical for e.g rollingUpgrades with maxUnavailable/maxSurge.

**Anything else you would like to add:**
I suspect this is because this `requeue=true` [1] is possibly causing an exponential backoff in the Machine controller.
Requeue enforcement often denotes a design lack that could be mitigated by watching events and signalling state in conditions. I propose:
- Machine Controller: Drop the requeue=true above, just return. The Machine controller will reconcile whenever is appropriate since it's already watching nodes.
- MachineSet controller: Drop this requeueAfter [2]. The MachineSet controller will reconcile whenever is appropriate since it's already watching Machines and they will emit an event that the MachineSet controller will see when the ready condition is set [3].

[1] https://github.com/kubernetes-sigs/cluster-api/blob/70e959802aa7722efefe69158e868d7ff3eec4be/controllers/machine_controller_noderef.go#L74
[2] https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/machineset_controller.go#L304
[3] https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/machine_controller_noderef.go#L125

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
The `Requeue: true` in the Machine controller _could_ probably be dropped in favor of just waiting for the watch events to be triggered, that said I'm unsure why this would be causing the controller to go in exponential backoff. When the option is set Controller Runtime requeues the object immediately, so this might not be the actual reason why the readiness is taking time.

Could you elaborate a bit more on how much lag are we talking about?

**Comment by sbueringer** [comment]
Possibly related: https://github.com/kubernetes-sigs/cluster-api/issues/4447

I might be completely missing the point, but an alternative theory:

The node is found and it just isn't ready yet, so we hit this branch:
https://github.com/kubernetes-sigs/cluster-api/blob/70e959802aa7722efefe69158e868d7ff3eec4be/controllers/machine_controller_noderef.go#L115-L119

There is no requeue at all and we don't reconcile on workload cluster node changes (?). The node is detected as ready after the next resync (resync period is 10m per default).

**Comment by enxebre** [comment]
>There is no requeue at all in this case and we don't reconcile on workload cluster node changes (?). The node is detected as ready after the next resync (resync period is 10m per default).

@sbueringer This might be related as well. Though I thought we are watching nodes  https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/machine_controller.go#L232-L237

>that said I'm unsure why this would be causing the controller to go in exponential backoff.

@vincepri not sure how you mean. As fas as I can see when `requeue=true` that key is added a rate limiting that starts the exponential backoff
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go#L314
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controller.go#L128-L129
So we are requeueing=true since the moment the node is found until it goes ready. So even if this happen to no be the root cause for the lag I think we should drop it and just wait for the watched event to trigger the reconcile as the node ready condition changes.

Let me gather some logs/numbers and I'll put a PR.

**Comment by sbueringer** [comment]
@enxebre Ah wasn't sure at which step you see the lag. Yes you're right we shouldn't have the problem I described.

**Comment by enxebre** [comment]
I can reproduce this consistently and validated that the controller goes exponential back off up to 2m43.84s resulting in the lag to set the nodeRef after the Node is created.

```"namespace"="clusters-agl"
I0715 13:14:14.629839   96048 generic_predicates.go:193]  "msg"="Resource is not paused, will attempt to map resource" "configmap"="kube-scheduler" "namespace"="openshift-kube-scheduler" "predicate"="updateEvent"
I0715 13:14:14.629896   96048 generic_predicates.go:42]  "msg"="All provided predicates returned true, allowing further processing" "predicateAggregation"="All"
I0715 13:14:14.804514   96048 machine_controller_noderef.go:72] controller-runtime/manager/controller/machine "msg"="NODE DOES NOT EXIST YET" "cluster"="agl-fgvn7" "machine"="agl-fgvn7-agl-agl-57fc589f4f-ffwzz" "name"="agl-fgvn7-agl-agl-57fc589f4f-ffwzz" "namespace"="clusters-agl" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine"
I0715 13:14:14.805093   96048 controller.go:314] controller-runtime/manager/controller/machine "msg"="rate limiting" "name"="agl-fgvn7-agl-agl-57fc589f4f-ffwzz" "namespace"="clusters-agl" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" "req"={"Namespace":"clusters-agl","Name":"agl-fgvn7-agl-agl-57fc589f4f-ffwzz"}
2021/07/15 13:14:14 WHEN 2m43.84s, ITEM: clusters-agl/agl-fgvn7-agl-agl-57fc589f4f-ffwzz
```
