### ISSUE TITLE
CAPD: make the kindest/haproxy image configurable

### ISSUE THREAD

**Issue by joshrosso** [kubernetes-sigs/cluster-api#4950]
**User Story**

As an operator, I'd like to use a custom HA proxy image for my CAPD-based cluster's API server loadbalancer.

**Detailed Description**

Today, the haproxy image is hard coded and not configurable:

https://github.com/kubernetes-sigs/cluster-api/blob/bfc6f80add5c21b8dc2b704951f42bc14708ebc4/test/infrastructure/docker/third_party/forked/loadbalancer/const.go#L19-L20

Making this configurable would allow CAPD users to reference custom images and/or registries where they can pull this image from.

/kind feature

**Comment by fabriziopandini** [comment]
What about implementing something like 

```go
// DockerClusterSpec defines the desired state of DockerCluster.
type DockerClusterSpec struct {
	...

	// LoadBalancer allows to define configurations for the cluster load balancer.
	// +optional
	LoadBalancer DockerLoadBalancer `json:"loadBalancer,omitempty"`
}

// DockerLoadBalancer allows to define configurations for the cluster load balancer.
type DockerLoadBalancer struct {
	// ImageMeta allows to customize the image used for image used for the cluster load balancer
	ImageMeta `json:",inline"`
}

// ImageMeta allows to customize the image used for components that are not
// originated from the Kubernetes/Kubernetes release process.
type ImageMeta struct {
	// ImageRepository sets the container registry to pull the haproxy image from.
	// if not set, "kindest" will be used instead.
	// +optional
	ImageRepository string `json:"imageRepository,omitempty"`

	// ImageTag allows to specify a tag for the haproxy image.
	// if not set, "2.1.1-alpine" will be used instead.
	// +optional
	ImageTag string `json:"imageTag,omitempty"`
}
```

So we have something that mimics what we have in kubeadm config types?

**Comment by joshrosso** [comment]
@fabriziopandini should `ImageMeta` actually contain 3 fields, as follows?

```go
// ImageMeta allows to customize the image used for components that are not
// originated from the Kubernetes/Kubernetes release process.
type ImageMeta struct {
	// ImageRepository sets the container registry to pull the haproxy image from.
	// if not set, "kindest" will be used instead.
	// +optional
	ImageRepository string `json:"imageRepository,omitempty"`

        // Image
        // if not set, "haproxy" will be used instead.
        Image string

	// ImageTag allows to specify a tag for the haproxy image.
	// if not set, "2.1.1-alpine" will be used instead.
	// +optional
	ImageTag string `json:"imageTag,omitempty"`
}
```

**Comment by stmcginnis** [comment]
/assign

Will take a crack at the suggested change.

**Comment by vincepri** [comment]
We usually don't allow overwriting the ImageName, keeping that fixed and consistent with all the other places where ImageMeta is used

**Comment by joshrosso** [comment]
cool, makes sense -- thanks :+1:

**Comment by vincepri** [comment]
@fabriziopandini One thing to note though is that we're not calling out anywhere in the proposed API addition that the load balancer is haproxy

**Comment by stmcginnis** [comment]
@vincepri should that be in a code comment calling that out, or are you thinking somewhere more visible?

**Comment by vincepri** [comment]
Code comment could be good, I'm wondering though if we should have Haproxy as a specific field under the `DockerLoadBalancer` struct

**Comment by stmcginnis** [comment]
So like @joshrosso was suggesting, but instead of having the field in `ImageMeta`, move it up a level to the `DockerLoadBalancer` struct?

**Comment by vincepri** [comment]
Not the imageName per se, I was more suggesting something like:
`DockerLoadBalancer` -> `DockerHaproxyLoadBalancer` -> `ImageMeta`
