### ISSUE TITLE
v0.3.x: Block creation of /upgrades to Kubernetes v1.22 management clusters 

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#4966]
**User Story**

As a user I would like to get an error as early as possible when trying to upgrade a management cluster to v1.22 (using CAPI v0.3.x)

**Detailed Description**

There are different ways how a Kubernetes v1.22 management cluster could be created/updated:
1. create a new v1.22 workload cluster + clusterctl move / init / ..
2. upgrade a self-hosted <v1.22 management cluster via CAPI to v1.22

**Anything else you would like to add:**

1. Should be easy to implement by adding a version check in clusterctl v0.3.x
2. There is currently no easy way to detect if the management cluster tries to upgrade a workload cluster or itself. Happy for suggestions, otherwise I'll explore some options.

**Open questions**

* What should happen to already existing v0.3.x 1.22 management clusters? Do we have to account for them / do they even work?

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by sbueringer** [comment]
Some ideas for 2.:

Assumption: the first step in updating a cluster to v1.22 is changing the version in KubeadmControlPlane and then later on MachineDeployment etc.. I think there's nothing we can do about other control plane providers.

Some ideas:

Hand over a client to the KubeadmControlPlane webhook.

In the update validation we would block the update:
* if old version < v1.22 new version >= v1.22.0 
* if the `KubeadmControlPlane` refers to the current cluster. Options:
    * get the control plane endpoint from the cluster and compare against the API server endpoint the client is using
    * get the control plane machines and compare them against the nodes in the current cluster (nodeRef.name/uid?)


Open questions:
* Do we want to implement the same "update blocking" for MachineDeployment, etc. ?
* What do we want to do with management clusters which are already on v1.22 (in case that's possible)? Options:
   * block only updates from < v1.22 to >= v1.22.0
   * block all updates to versions >= v1.22.0, including v1.21.* => v1.22.*, v1.22.x => v1.22.y (y>x) and v1.22.x => v1.23.x

**Comment by fabriziopandini** [comment]
I'm not sure that blocking in web hooks is a viable option for v0.3.x, because this most probably requires controller runtime changes, and I don't think we can get them in the version currently used in this branch.

This leaves us to being forced to block in the controllers.
- I agree the control plane controller is the first place where upgrade are triggered so I'm +1 to block here; We can raise awareness for other CP providers to do the same
- For MD deployments, I think that we should prevent to rollout machines if the Kubernetes version is higher than the minimal Kubernetes version in the control plane, but given that there is no actually contract defining that CP machines should exists, we are kind of falling back into the kcp assumption.

**Comment by sbueringer** [comment]
Regarding: "What do we want to do with management clusters which are already on v1.22?"

I tried to deploy CAPI v0.3.21 on Kubernetes v1.22.0-rc.0 and imho it's impossible to get it to work without any more changes to CAPI. So I think we can assume we don't have any existing v1.22 CAPI v0.3.x management cluster out there.

### Exploration CAPI v0.3.21 on Kubernetes v1.22-rc.0

* build kindest/node with v1.22.0-rc.0 and created kind cluster with it
* clusterctl init --infrastructure docker (with clusterctl v0.3.21):
    * cert-manager-cainjector does not start:
        ```bash
        error registering secret controller: no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"
        ```
      Follow-up: We have to upgrade cert-manager on main
* kubectl apply cluster-api-components.yaml: (adjust feature gate parameters manually)
    * ValidatingWebhookConfiguration/MutatingWebhookConfiguration cannot be deployed as they are v1beta1
    * cert-manager.io/v1alpha2 Certificate + Issuer cannot be deployed anymore (because cert-manager webhook is not up)
    * create cert and deploy via: `k create secret generic -n capi-system capi-kubeadm-bootstrap-webhook-service-cert --from-file=tls.key --from-file tls.crt`
    * capi-controller-manager does not start: `reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.9/tools/cache/reflector.go:105: Failed to list *v1alpha3.Machine: Internal error occurred: error resolving resource`

**Comment by sbueringer** [comment]
Note from the CAPI meeting: we should also update the following pages in the book:
* Quickstart: https://release-0-3.cluster-api.sigs.k8s.io/user/quick-start.html
* Version Support: https://release-0-3.cluster-api.sigs.k8s.io/reference/versions.html

**Comment by randomvariable** [comment]
I agree that a management cluster already on v1.22 probably already is going to need manual remediation.

**Comment by sbueringer** [comment]
@fabriziopandini @vincepri  @randomvariable  I would then start implementing the part in the KubeadmControlPlane controller. As we assume we don't have healthy v1.22 management clusters out there I would implement the following:

* if self hosted && new KCP.spec.version >= v1.22 => return err

For if self hosted, I can think of the following options:
* propagate KCP controller metadata.{uid,name,namespace} via [downwards API](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api) so that the controller can try to find itself in the workload cluster (from which we can infer that the KCP controller runs in the management and workload cluster so => self hosted)
* get the control plane machines and check for all if all `.status.nodeRef.{name,uid}` also exist in the current cluster via the `managementCluster` client
* a few more other really bad hacks I even like less :)

Maybe I'm missing the one obvious and good solution :)

Discarded options:
* get the control plane endpoint from the cluster and compare against the API server endpoint the client is using
  * this doesn't work as the API server endpoint the client is using is most probably an in-cluster IP

**Comment by vincepri** [comment]
Could we check if the Cluster API CRDs are installed and block the upgrade to v1.22?

**Comment by sbueringer** [comment]
> Could we check if the Cluster API CRDs are installed and block the upgrade to v1.22?

We could, this would additionally also block when we update other management clusters (i.e. not only ourselves, in cases like mgmt cluster => mgmt cluster => workload cluster). But I think this is also a case which would be nice to cover (and it wouldn't be covered by my solutions).

So yup, this seems to be the best solution yet.

**Comment by vincepri** [comment]
We can use the partial object metadata client to find the Cluster CRD and block there. We'd need a remote client to the workload cluster, try to retrieve the CRD with PartialObjectMetadata  (see the convert references function as an example) and if the call is successful, assume it's a management cluster.
