### ISSUE TITLE
dynamic link and reconciling between machines/nodes

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#497]
Currently the link between machines and nodes relies on something arbitrarily setting an annotation on the node to match a given machine name.
https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/machine/node.go#L43
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/master/clusterctl/examples/google/provider-components.yaml.template#L294

This is to discuss about a controller mechanism for this to happen dynamically as soon as the node resulting from a given machine comes up. One possible option would be to match both by ip e.g https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/apis/cluster/v1alpha1/machine_types.go#L143

This would allow more self-contained machine<->node and would facilitate https://github.com/kubernetes-sigs/cluster-api/issues/493, it'd also ensure expected propagation MachineSet --> Machine --> Node for things like https://github.com/kubernetes-sigs/cluster-api/issues/47

**Comment by dgoodwin** [comment]
+1, we had to do this with our own controller but it feels like it makes good sense in the cluster-api controllers. We have the same node addresses struct used on both the nodes and machine status so IP matching was the best option we could come up with. Curious if there are better ways.

**Comment by enxebre** [comment]
cc @roberthbailey

**Comment by derekwaynecarr** [comment]
I agree that we should have a mechanism to automatically associate a machine to its corresponding node separate from the existing annotation.  The use case I would like to support is creation of a Machine -> creation of a Node -> Node appears to the API server without a role label -> Machine controller assigns a role label to a Node (so identifying labels that steer rather than repel workloads are centrally applied by masters and not the nodes themselves) -> Node dynamic configuration is applied based on label (from machine or other source).

**Comment by Lion-Wei** [comment]
I think we may not really care about which exact machine this node linked, we do care about is the machine's flavor, so how about use machineClass? 
Then we don't have to distinguish cloud provider, or which machine, just need to choose a type of machine.

**Comment by prashanth26** [comment]
@Lion-Wei I think we would care about which exact machine is backing the node object. This especially makes sense when we would try to link the [machine health check mechanism](https://github.com/kubernetes-sigs/cluster-api/issues/47) where we would like to update machine status based on node conditions. Does that make sense?

**Comment by alvaroaleman** [comment]
Why not simple use `Machine.Status.NodeRef` and in case you need the Machine for a node, just iterate over all machines?

**Comment by enxebre** [comment]
Even using machineClasses there's a need for a having a machine<->node map in order to reconcile information and support things like health checks, role reconciliation or draining on delete.
For reference this is a controller https://github.com/openshift/machine-api-operator/blob/master/cmd/nodelink-controller/main.go#L64 we currently use to ensure the right `machine` label is set on every node so the the core node controller can set the `Machine.Status.NodeRef` accordingly

**Comment by maisem** [comment]
As noted above we currently use an [arbitrary annotation](https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/node/node.go#L55) on the node object to link the machine and node objects, if we were to merge #565 we could use the ProviderId field instead.
cc @justinsb @roberthbailey
