### ISSUE TITLE
Implement read current state of a managed topology

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4971]
**Detailed Description**
This is part of the activities for the implementation of the [ClusterClass proposal](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/202105256-cluster-class-and-managed-topologies.md). 

As part of the ManageTopologyController reconcile loop, we want to read a ClusterClass and all the referenced templates

This step should return a struct including

- Cluster (from scaffolding)
- ClusterInfrastructure (Get*)
- ClusterControlPlane (Get*)
- ControlPlaneMachineInfrastructureTemplate (Get*)
- List of machine deployments with the cluster.x-k8s.io/cluster-name and cluster.x-k8s.io/topology label
   - Then, for each MachineDeployment
       - MachineBootstrapTemplate (Get*)
       - MachineInfrastructureTemplate (Get*)

**Anything else you would like to add:**

This could be implemented only after #4933 is completed.

Notes:
- Before using a reference it is important to call ConvertReferenceAPIContract in order to properly handle APIVersions/contract - -- upgrades.
- TBD if in case a reference is converted to a newer API contract, the Cluster/MachineDeployment/ControlPlane objects containing the reference should be patched (the existing controllers are already taking care of this; in case we are going to implement this, feel free to tackle this in a separated PR).
- ControlPlaneTemplate object might or might not have a MachineInfrastructureTemplate; in order to discover this, it is required to inspect the template spec using unstructured utils (See #4949 for the related contract changes). 
- All the get reading templates/provider types (Get*) must use the unstructured caching client and return unstructured; please note that the external package already provides a Get utility that can be used for this scope. 
- After reading the ClusterInfrastructure object and the ClusterControlPlane object it is required to set up a watch on the corresponding types.
- In case of missing objects the read operation should fail; this probably will be changed in future if/when implementing support for reconciling a subset of a topology.
- Other errors (e.g. API server connection errors) must always trigger failure for the operation.

/kind feature
/milestone v0.4

**Comment by fabriziopandini** [comment]
(assigning to myself given that Killian is not yet  kubernetes-sigs member)

**Comment by sbueringer** [comment]
@fabriziopandini Just fyi, afaik you cannot assign killian but @killianmuldoon can assign himself. Just found that out with someone from my old company.

Apparently you cannot assign somebody outside of the org, expect:
* he does it himself
* he wrote something in the issue by himself
