### ISSUE TITLE
[v1alpha3] Modification of NodeDrainTimeout requires rollout of MachineDeployment

### ISSUE THREAD

**Issue by Lirt** [kubernetes-sigs/cluster-api#4973]
Hello CAPI community,

I have a question about the `NodeDrainTimeout` configuration option. First of all I am using CAPI version `0.3.16` and I understand that [some things](https://github.com/kubernetes-sigs/cluster-api/commit/8e63984b9fcf8b01ec0229a5d011b66f8a8372b9) have changed around this configuration option.

I have this scenario:
1. When I change `NodeDrainTimeout` on `KubeadmControlPlane` (`spec.nodeDrainTimeout: "100s"`, the change is immediately accepted and no machine needs to be recreated.
2. When I change `NodeDrainTimeout` on `MachineDeployment` (`spec.template.spec.nodeDrainTimeout: "100s"`), the change is immediately accepted, but new `MachineSet` is created and the nodes in `MachineDeployment` are recreated.

Is that forced rollout designed on purpose? Do we need to rollout `MachineDeployment` on change that does not relate to machine template but rather variable related to code?

I understand that in `v1alpha4` `NodeDrainTimeout` is moved to the `MachineTemplate`. Does that change this behavior of needing to rollout the machines on `NodeDrainTimeout` change? If not, can we make it not forcing rollout on change?

Versions:
- Cluster-api version: `0.3.16`
- Kubernetes version: `1.19`
- OS: `Ubuntu 18`

/area upgrades
/area machine

**Comment by sbueringer** [comment]
@Lirt I think it changes with v0.4.0 because afaik we don't rollout changes to the templates as we consider them immutable (or at least we handle them that way). You can test it by running the v0.4.0 quick start with CAPD and play around with it.

**Comment by Lirt** [comment]
I understand that `MachineTemplate` is immutable, that's completely fine, but maybe decision to put `NodeDrainTimeout` inside of `MachineTemplate` is not so good. If I configure different `MachineTemplate` or `InfrastructureRef` in `MachineDeployment`, it forces a rollout even when only `NodeDrainTimeout` was changed, yes?

It means that the behavior will stay the same --> there is a need to re-rollout all machines when `NodeDrainTimeout` is changed.

The thing is that there should be no need to re-rollout machines, because as far as I understand `NodeDrainTimeout` parameter is not configured inside of the worker machine (I'm not changing image, flavor or anything related to VM or k8s config in VM). This variable is important only for CAPI operator to understand how much time it has to wait until it decides to not try to evict pods. IMO it's useless to force rollout this way because it's really not needed.

Example: I manage 40 clusters and I find out that I need to configure `NodeDrainTimeout` from `0s` to `60s` -> operator will rollout all worker nodes for all clusters, then I will find out it's too low, so I increase to `5m` -> again rollout all worker nodes for all clusters.

**Comment by vincepri** [comment]
Hi @Lirt, and thanks for taking the time to file an issue!

This topic keeps coming up and for good reason. The current limitation is very problematic in case there are large number of machines that need to be rolled out. For example, let's say a MachineDeployment has 100s of Machines, and we want to add or modify a field that users know it can be mutated in place, experiencing a full fleet rollout isn't great or cost effective.
A while ago, at KubeCon 2019 we chatted about this issue with @cecile and the rest of the Azure team. Truthfully, we don't have a good solution right now that we could offer, but I can see that longer term we should allow and better understand what fields can be mutated in place and which one require a full rollout.
The above can be done in a number of ways, for example by annotating fields and then introspecting them, or by going with some conventions. I'm sure we'll be able to find a solution over time, although for now and probably until beta, we'll keep immutability around given that it's makes generally things easier to develop and rely on.

**Comment by Lirt** [comment]
@vincepri Hi Vince,

thank you for response. I understand you currently cannot do much as `v1alpha4` is out, but if there will be `v1alpha5` or beta API version, it would be great if this was included in discussion (probably other variables related to operator code and not machine templates if there are more). 

I don't follow all the discussions in CAPI so it's hard for me to get into the conversations.

I think we cannot do much here in this issue, so I will close this, but if you know some place to put this topic so that it will be reviewed (and not forgotten) in next API version discussions, it would be great.
