### ISSUE TITLE
Import path for the new repository

### ISSUE THREAD

**Issue by kris-nova** [kubernetes-sigs/cluster-api#5]
Traditionally in kubernetes repositories we use the `k8s.io` domain to redirect to the codes current hosted location.

For instance with github we would have the following redirect in place:

`k8s.io/kube-deploy` --> `github.com/kubernetes/kube-deploy`

## Do we want to use the following redirect here?

Personally I think we should keep the import paths as literal as possible. The `k8s.io` redirect can be confusing to a newcomer. Furthermore there is still a bit of magic linking the two together, and if you don't know about it it could be hard to trace.

If we do switch code hosting providers later, we can use tools like `sed` and `grep` to update our codebases as needed.

**Comment by kris-nova** [comment]
CC @krousey

**Comment by krousey** [comment]
We discussed this in the meeting yesterday. There was a small majority in favor of adopting sigs.k8s.io/cluster-api. I asked that people speak up either there on here if they disagreed. Given that there's been no feedback, I'm closing this with the decision to use sigs.k8s.io/cluster-api.
