### ISSUE TITLE
Document plan on how API can support auto-scaling and other auto* features

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#50]
_From @rsdcastro on April 5, 2018 15:24_

This issue tracks an evaluation of the API to make sure that it can support the use cases for auto-scaling and any other auto* features.

This issue should cover any API changes as well. Specific implementation changes should be tracked as separate issues.

cc @krousey @roberthbailey @mwielgus 

_Copied from original issue: kubernetes/kube-deploy#666_

**Comment by rsdcastro** [comment]
cc @krzysztof-jastrzebski

**Comment by timothysc** [comment]
Closing as obsolete
