### ISSUE TITLE
Change the controlPlaneEndpoint during kubernetes cluster running

### ISSUE THREAD

**Issue by haijianyang** [kubernetes-sigs/cluster-api#5005]
**User Story**

I found that the documentation and code didn't mention update/change the controlPlaneEndpoint after setting.
As a user I want to change the controlPlaneEndpoint during kubernetes cluster running, can CAPI provide support?

/kind feature

**Comment by vincepri** [comment]
/priority awaiting-more-evidence

@haijianyang Can you outline how you'd plan to change the control plane endpoint in a cluster? Changing and endpoint means that a Cluster has to be effectively rolled out, this is why we usually suggest to place the main endpoint behind a load balancer and then attach the control plane machines to it. The endpoint must be static for the lifecycle of the cluster.

Changing the main endpoint has also a ripple effect on certificates, current nodes, etc.

**Comment by haijianyang** [comment]
> /priority awaiting-more-evidence
> 
> @haijianyang Can you outline how you'd plan to change the control plane endpoint in a cluster? Changing and endpoint means that a Cluster has to be effectively rolled out, this is why we usually suggest to place the main endpoint behind a load balancer and then attach the control plane machines to it. The endpoint must be static for the lifecycle of the cluster.
> 
> Changing the main endpoint has also a ripple effect on certificates, current nodes, clients, etc.

**Comment by haijianyang** [comment]
> /milestone Next

**Comment by therealak12** [comment]
Hi.
If I want to change `ControlPlaneEndpoint` value, is there a clear solution to handle side effects?
Or I should consider recreating the cluster?

**Comment by sbueringer** [comment]
If it's comparatively easy for you to re-create the cluster, it's probably easier.

I would expect that you have to change some fields in CAPI and then figure out how to update the 
config of everyone who was using the old endpoint. CAPI generates a kubeconfig to access the cluster in a secret.
I'm absolutely not sure who else is affected, but it probably includes kubelet on all nodes.

**Comment by therealak12** [comment]
Got my answer, Thanks for your fast and complete response @sbueringer.
