### ISSUE TITLE
Resolve release series labels in e2e config

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5008]
**User Story**

As a developer I would like to have an easily consumable way to find out the latest stable release of a CAPI release series (e.g. v0.3.x or v0.4.x).

**Detailed Description**
Kubernetes currently exposes the latest stable releases (overall or per release series) via:
* http://dl.k8s.io/release/stable.txt
* http://dl.k8s.io/release/stable-1.21.txt

This is useful when consuming Kubernetes for example in CI. We currently have the same use case as we want to reference the latest clusterctl binary of the v0.3.x release series in our clusterctl upgrade e2e test (xref: https://github.com/kubernetes-sigs/cluster-api/pull/4995#issuecomment-884939678)

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
I like the idea.
At least in first iteration marker files can be stored in the same buckets we are using for nightly build artefacts

/area testing
even if this could have different applications

**Comment by vincepri** [comment]
Is there any automation we could reuse?

**Comment by sbueringer** [comment]
I have zero idea how they do it and where to start looking. @dims?

**Comment by dims** [comment]
@sbueringer i can dig things up, but probably easier for @palnabarun as knows a lot more of the release stuff.

**Comment by fabriziopandini** [comment]
@sonasingh46 if you want, you can assign yourself to the issue (this should work also if you are not an org member yet)

**Comment by killianmuldoon** [comment]
@sonasingh46 Have you had time to work on this?

**Comment by sonasingh46** [comment]
Hey @killianmuldoon -- I did not get a chance to start on this. I can start looking on this one next week.

**Comment by killianmuldoon** [comment]
If you're still willing to pick it up that would be awesome 😄 . We've got a lot of point release updates to do today, and something like this would really help automate the process!

**Comment by palnabarun** [comment]
Sorry I missed the ping here!

We update the version markers during every release cut. `krel` (the Kubernetes release tooling) has a step in the process to update the marker file inside a publicly viewable GCS bucket. `dl.k8s.io` is just a redirect to that GCS bucket URL.

You can have a look at the code here:
https://github.com/kubernetes/release/blob/f55d5af19f1fab3e8cf6832abf331f95452a342d/pkg/release/publish.go#L155

**Comment by palnabarun** [comment]
My suggestions for a detailed plan here would be:
1. Request a GCS bucket from sig-k8s-infra
2. Write some code using [release.Publisher(...)](https://github.com/kubernetes/release/blob/f55d5af19f1fab3e8cf6832abf331f95452a342d/pkg/release/publish.go#L36) to publish the marker
3. Run a Prow Job for every pushed tag / integrate code in (2) with the existing mechanism of releasing CAPI.

Let me know in case you need any help! Happy to review stuff.

**Comment by sonasingh46** [comment]
@palnabarun -- Thank you very much. Will jump on to this one and reach out for help and reviews.

**Comment by fabriziopandini** [comment]
After digging into this a little bit it comes to me that version resolution is relative to a provider (CAPI latest != CAPV latest)

Given the latest point, using version marker in a GCS bucket gets complicated, because each provider should take care of changing the release process to publish them; therefore I'm proposing to use an alternative method to discover version info, similar to the one implemented in https://github.com/kubernetes-sigs/cluster-api/blob/535219878ced6ce483c87fe49b4a756c0f83a85a/hack/tools/mdbook/releaselink/releaselink.go#L65-L98

I also suggest the following UX in the docker.yaml file:

when configuring providers:

```diff
  - name: cluster-api
    type: CoreProvider
    versions:
-    - name: v0.3.23 # latest published release in the v1alpha3 series; this is used for v1alpha3 --> v1beta1 clusterctl upgrades test only.
-      value: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.3.23/core-components.yaml"
+    - name: "{goproxy://sigs.k8s.io/cluster-api@stable-0.3}"  # latest published release in the v1alpha3 series; this is used for v1alpha3 --> v1beta1 clusterctl upgrades test only.
+      value: "https://github.com/kubernetes-sigs/cluster-api/releases/download/{goproxy://sigs.k8s.io/cluster-api@stable-0.3}/core-components.yaml"
```

when configuring clustectl binary in variables:

```diff
-  INIT_WITH_BINARY: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.4.4/clusterctl-{OS}-{ARCH}"
+  INIT_WITH_BINARY: "https://github.com/kubernetes-sigs/cluster-api/releases/download/{goproxy://sigs.k8s.io/cluster-api@stable-0.3}/clusterctl-{OS}-{ARCH}"
```

NOTE: I'm proposing an url like syntax because it makes things explicit and it also opens up to support alternatives way to discovery info if required

For starting we need to resolve the following type of markers:
- stable-X.Y: --> Latest release in the series without pre-releases e.g. 0.3.25
- latest-X.Y: --> Latest release in the series including pre-releases e.g. v1.1.0-rc0
(eventually, in the future we will add more, e.g. for nightly)

Ideally, markers should be resolved when [reading the docker.yaml](https://github.com/kubernetes-sigs/cluster-api/blob/5026786ee809c5def466049f5befd2a786fbcefa/test/framework/clusterctl/e2e_config.go#L52) config file, so all the consumers of the E2E can benefit from marker resolution without changing tests.

**Comment by sbueringer** [comment]
Sounds perfect!

**Comment by sonasingh46** [comment]
Sounds good to me! @fabriziopandini

**Comment by sbueringer** [comment]
Short note from this Slack post: https://kubernetes.slack.com/archives/C8TSNPY4T/p1643976829466139

I think we missed an edge case with the “version resolution logic”. We were assuming it’s enough to resolve the version in the e2e config file (CAPD: docker.yaml) when loading the file. But in case of INIT_WITH_BINARY  we have to resolve the version in the clusterctl e2e test, because that config can be passed in:
* either as env var / docker.yaml
* or via ClusterctlUpgradeSpecInput

It doesn’t change a lot, only that we have to call the “version resolution func” also from the clusterctl upgrade test.

**Comment by sbueringer** [comment]
/retitle Resolve release series labels in e2e config
/milestone v1.2

**Comment by fabriziopandini** [comment]
@sbueringer am I wrong or this has been already addressed?

**Comment by sbueringer** [comment]
My current information is that @sonasingh46 wanted to work on it.

**Comment by sonasingh46** [comment]
I have not started to work on it yet. Was on PTO. Will prioritise it next week. Do we have a release deadline/blocker?

**Comment by sonasingh46** [comment]
Hey folks, did not get chance to start working on this and am occupied for couple of weeks. If anyone is interested meanwhile feel free to pick up this.

**Comment by fabriziopandini** [comment]
(doing some cleanup on old issues without updates)
/close
Unfortunately no one is picking up the issue, we can look up at the idea above even if the issue is closed.

**Comment by sbueringer** [comment]
@killianmuldoon is this something that we want to add as an idea to the CI release team backlog?

Basically it would make it possible to just reference a release series instead of a specific release in docker.yaml.

I think it's a worthwile improvement, if someone volunteers to work on it

**Comment by killianmuldoon** [comment]
>@killianmuldoon is this something that we want to add as an idea to the CI release team backlog? (improvement tasks issue or the project)

Looks useful. Let me take a closer look and maybe add it to the release team's backlog.

/assign
/reopen

**Comment by adilGhaffarDev** [comment]
@killianmuldoon I can work on this task, if its ok. I am thinking of making markers like this {#getrelease goproxy://sigs.k8s.io/cluster-api@stable-0.3},  and resolve these markers in start of e2e suite as suggested by @fabriziopandini .

**Comment by sbueringer** [comment]
What about simplifying to `sigs.k8s.io/cluster-api@v0.3`

xref: https://github.com/kubernetes-sigs/cluster-api/pull/8725#discussion_r1202284357

**Comment by sbueringer** [comment]
@fabriziopandini ^^

**Comment by killianmuldoon** [comment]
@adilGhaffarDev Awesome - let me know if you need any help with it!

/assign @adilGhaffarDev

**Comment by killianmuldoon** [comment]
@adilGhaffarDev have you had any luck with this?

**Comment by adilGhaffarDev** [comment]
> @adilGhaffarDev have you had any luck with this?

Yes its mostly done, I will create PR today. Sorry, I was on vacations, I came back last week.

**Comment by furkatgofurov7** [comment]
Changing the priority to:

/priority important-soon

based on current CI Lead's suggestion (cc @nawazkh)

**Comment by furkatgofurov7** [comment]
This is tracked in: #9104

**Comment by killianmuldoon** [comment]
/unassign

As @adilGhaffarDev is on the case :slightly_smiling_face:
