### ISSUE TITLE
Provide network allocation strategy

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#502]
Various cloud providers would need to allocate multiple subnets from a larger super network.

Common functionality could be provided to allocate smaller subnets using standard algorithms
such as [RFC 3531](https://tools.ietf.org/html/rfc3531)

**Comment by roberthbailey** [comment]
Do we have multiple providers that need this functionality or are we adding it to the shared code base under the assumption that it will be useful to share in the future?

**Comment by roberthbailey** [comment]
Closing for the same reason that the PR was closed. We can re-assess the need for this once we see similar patterns emerge across multiple providers. 

/close
