### ISSUE TITLE
Handling of .machineTemplate.infrastructureRef in ControlPlaneTemplates

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5024]
**User Story**

As a user I would like to have a good UX when configuring MachineTemplates for the ControlPlane in ClusterClass.
A good UX includes (if possible):
* no redundant configuration
* same validation rules for ControlPlaneTemplate and ControlPlane
* future-proof assumptions about how/if machineTemplates are configured in ControlPlaneTemplates

**Detailed Description**

Based on the current ClusterClass proposal and implementations we have the problem that the `.machineTemplate.infrastructureRef` in the ControlPlaneTemplate is redundant configuration (as it's also configured in the ClusterClass). If we keep it, we have the problem that we have to keep the apiVersion (only the version part of it) up-to-date.

The current idea is to keep the `.machineTemplate.infrastructureRef` and to add a reconciler to KCP which keeps the ref’s apiVersion up-to-date. Other ControlPlane providers could solve it in a similar way.

I wonder if we need to set the infrastructureRef on the KubeadmControlPlaneTemplate. We never read the infrastructureRef (in the ClusterClass implementation) and when computing the KubeadmControlPlane we first compute a InfrastructureMachineTemplate (based on ClusterClass.controlPlane.machineInfrastructure)  and then set the infrastructureRef to point to the computed InfrastructureMachineTemplate.

Based on that I’m not sure if it’s worth:
* forcing the user to set the ref in the KubeadmControlPlaneTemplate (as it’s redundant configuration, because it’s already configured in the ClusterClass)
* implement a controller which updates a ref we never read

Previous discussion in Slack: https://kubernetes.slack.com/archives/C8TSNPY4T/p1627460469457000

Overall this prob

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
I’m personally leaning towards the idea being discussed for CAPA, which basically advocates for removing from the templates all the fields that are “instance specific”, so we avoid confusion in the users.

This solution also avoids the following risks
- by allowing templates without this ref or by not keeping this ref updated, theres is the risk to have “invalid” objects in your system whenever the current assumption changes
- having different validation rules between template and object could create confusion to the users and lead to problems when crating an object from the template

NOTE: What about making sure that the new template types could be created only when the ClusterTopology feature flag is enabled, so we implicitly bar them behind the experiment label?

**Comment by sbueringer** [comment]
Yeah, I think removing the ref from the ControlPlaneTemplate is the easiest solution for the users.

Sounds plausible to me to also use the feature flag for the template types, this includes ControlPlaneTemplates and InfrastructureClusterTemplates, right? I think it would be really useful because it makes it more obvious to the users that those templates might change the next few months.

**Comment by fabriziopandini** [comment]
We should do the same for DockerClusterTemplate
@vincepri ^^

**Comment by sbueringer** [comment]
What about the providers? Would it make sense if they mirror the feature gate?

**Comment by fabriziopandini** [comment]
I guess yes, we are already doing something similar for MachinePools

**Comment by vincepri** [comment]
>  What about making sure that the new template types could be created only when the ClusterTopology feature flag is enabled, so we implicitly bar them behind the experiment label?

We can, although this ties up a template in an infrastructure provider to a Cluster API generic feature. It would also not align how MachineTemplate behave today, which can be used with other objects as well.

Is there a specific need to make this a strict requirement?

**Comment by sbueringer** [comment]
> > What about making sure that the new template types could be created only when the ClusterTopology feature flag is enabled, so we implicitly bar them behind the experiment label?
> 
> We can, although this ties up a template in an infrastructure provider to a Cluster API generic feature. It would also not align how MachineTemplate behave today, which can be used with other objects as well.
> 
> Is there a specific need to make this a strict requirement?

I think the main reason is that we (probably) want to make changes to ControlPlaneTemplates / InfrastructureClusterTemplates like dropping instance-specific needs. Hiding those Templates behind the feature gate (for now) would probably make this easier as we probably have more leeway regarding breaking changes.

**Comment by sbueringer** [comment]
/area topology

@fabriziopandini I think this has been resolved by dropping the infrastructureRef from KCPTemplate. WDYT?

**Comment by fabriziopandini** [comment]
I think we are ok for now; some more consideration will be required when we discuss how to decouple bootstrap and machine deployment, but that's still tbd
/close
