### ISSUE TITLE
Implement status.version in KCP

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5025]
**Detailed Description**

This is part of the activities for the implementation of the [ClusterClass proposal](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/202105256-cluster-class-and-managed-topologies.md). 

According to the changes to the control plane providers introduced by https://github.com/kubernetes-sigs/cluster-api/pull/4949, it is required to implement a status.version field representing the minimum Kubernetes version for the control plane machines in the cluster. 

/kind feature

**Comment by ykakarap** [comment]
@fabriziopandini I can work on this

/assign

**Comment by vincepri** [comment]
/kind release-blocking

I'd like to get this done before we release v0.4.1
