### ISSUE TITLE
Decide how to handle CAPD containers being stopped

### ISSUE THREAD

**Issue by stmcginnis** [kubernetes-sigs/cluster-api#5026]
**Detailed Description**

If we deploy a cluster using CAPD, then stop one of the containers after deployment, there is no kind of remediation that happens and depending on which container, there may only be some errors logged about failed connections.

We get a list of the containers present, but it doesn't appear we check the container status to see that the container has exited.

We should determine the appropriate way to react to these scenarios to make sure things behave as a user would expect.

**Anything else you would like to add:**

See discussion in https://github.com/kubernetes-sigs/cluster-api/pull/5021 for more context.

/kind feature

**Comment by fabriziopandini** [comment]
+1 to surface a condition, but I would defer to the user remediation because stopping container might be useful to test remediation, easing memory pressure, etc.

/milestone v0.4
