### ISSUE TITLE
ClusterCacheTracker should be able to use non-caching client 

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5035]
**User Story**

As a developer I would like to be able to use ClusterCacheTracker with a non-caching client. 

**Detailed Description**

Currently, the ClusterCacheTracker always wraps the workload cluster client into a delegating client. It is possible to provide a list of objects which should not be cached (default is ConfigMap/Secret). 

Unfortunately, this means we have to enumerate all resources we don't want to cache. If we don't want to cache at all, we have to go through the usage of the workload client, find out which resources we are using and then configure them all as uncached in the ClusterCacheTracker. Also we have to keep the list in sync with the usage of the client. As this is error-prone it would be nice if there is an option to just disable caching.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by sbueringer** [comment]
@vincepri Just to confirm:
a) we would like to use this client in KCP (instead of https://github.com/kubernetes-sigs/cluster-api/pull/5033)
b) Would it be a valid solution to just add a boolean flag `DisableCache` to `ClusterCacheTrackerOptions` and then just skip: https://github.com/kubernetes-sigs/cluster-api/blob/3c9e61af9572e3b5eaa70d46ae2b62a66c804d21/controllers/remote/cluster_cache.go#L210-L217 and use the regular client directly?

**Comment by vincepri** [comment]
Given that KCP uses workload clusters clients at each reconciliation, in v0.4 we should probably add support to retrieve a live client with something like `GetLiveClient()`, or if we want to match what controller runtime does, we can also do something like `GetAPIReader()` which returns a live api reader (client writers are always live)

**Comment by sbueringer** [comment]
Just to confirm: so the only change would be to add a func to get an uncached reader, so in cases where we don't want caching we would use that one and leave everything else the same.

**Comment by ykakarap** [comment]
/assign

I can work on this :) 

The TODOs are:
* Add APIReader support to the workload cluster client
* Adjust functions of [`Workload`](https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/internal/workload_cluster.go#L114-L118) to use the live reader where needed.

**Comment by enxebre** [comment]
@ykakarap you still planning to work on this? Just let me know I you want me to give it a go otherwise.

**Comment by sbueringer** [comment]
Looks like there is no real demand for this.

It should be easy to implement, but let's only do it if someone actually needs it


/close
