### ISSUE TITLE
archive the cluster-api-bootstrap-provider-kubeadm repository

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/cluster-api#5037]
the code for https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm lives in this repository.
the old repository is stale and should be archived.

action items:
- [x] cleanup references of https://github.com/kubernetes/test-infra/search?q=%22cluster-api-bootstrap-provider-kubeadm%22 in the k/test-infra repository.
- [x] create a ticket in https://github.com/kubernetes/org/issues/new/choose following the project archival template.
- [x] cleanup cluster-api-bootstrap-provider-kubeadm references from k/community:
https://github.com/kubernetes/community/blob/30900f80a50e8ce1e7e93e8279b7e050fecead6d/sigs.yaml#L987

**Comment by neolit123** [comment]
cc @fabriziopandini @vincepri 
/help
/priority important-longterm
/kind cleanup

**Comment by vincepri** [comment]
https://github.com/kubernetes/org/issues/2845

**Comment by vincepri** [comment]
https://github.com/kubernetes/test-infra/pull/23064

**Comment by vincepri** [comment]
https://github.com/kubernetes/community/pull/5918

**Comment by neolit123** [comment]
This is how done. Thanks to @vincepri and the github admins.
