### ISSUE TITLE
Update test grid for Kubernetes 1.22

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5060]
**Detailed Description**
Now that Kubernetes 1.22 has been released or ci signal should be updated accordingly

- [periodic-cluster-api-e2e-workload-upgrade-1-21-latest-main](https://github.com/fabriziopandini/test-infra/blob/8063552514cb3f5ef4ca853157364f1a44cb159f/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-main-upgrades.yaml#L135) should be duplicated creating `periodic-cluster-api-e2e-workload-upgrade-1-22-latest-main`; the new job should use
  - `stable-1.22` as input value for `KUBERNETES_VERSION_UPGRADE_FROM`
  - `ci/latest-1.23` as input value for `KUBERNETES_VERSION_UPGRADE_TO`
  - `capi-e2e-main-1-22-latest`as `testgrid-tab-name`

- [periodic-cluster-api-e2e-workload-upgrade-1-21-latest-main](https://github.com/fabriziopandini/test-infra/blob/8063552514cb3f5ef4ca853157364f1a44cb159f/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-main-upgrades.yaml#L135) should be renamed into `periodic-cluster-api-e2e-workload-upgrade-1-21-1-22-main`; the job should use
  - `stable-1.22` as input value for `KUBERNETES_VERSION_UPGRADE_TO`
  - `capi-e2e-main-1-21-1-22`as `testgrid-tab-name`

- [pull-cluster-api-e2e-workload-upgrade-1-21-latest-main](https://github.com/fabriziopandini/test-infra/blob/8063552514cb3f5ef4ca853157364f1a44cb159f/config/jobs/kubernetes-sigs/cluster-api/cluster-api-presubmits-main.yaml#L208) should be renamed into `pull-cluster-api-e2e-workload-upgrade-1-22-latest-main`; the job should use
  - `stable-1.22` as input value for `KUBERNETES_VERSION_UPGRADE_FROM`
  - `ci/latest-1.23` as input value for `KUBERNETES_VERSION_UPGRADE_TO`
  - `capi-pr-e2e-main-1-22-latest`as `testgrid-tab-name`

/kind feature

**Comment by sbueringer** [comment]
@fabriziopandini last one should probably be: `pull-cluster-api-e2e-workload-upgrade-1-21-latest-main`

**Comment by fabriziopandini** [comment]
Fixed, last one should be `periodic-cluster-api-e2e-workload-upgrade-1-22-latest-main`

**Comment by haardikdharma10** [comment]
I'll fix this. 
/assign

**Comment by sbueringer** [comment]
@fabriziopandini I was mainly looking at the periodic vs pull part of the job name :)

**Comment by sbueringer** [comment]
@fabriziopandini Just to confirm: I suppose we don't have to change anything for release-0.3, right? I couldn't find anything that looks like it has to be changed there.

**Comment by fabriziopandini** [comment]
Yes
I consider release-0-3 out of scope of this issue, because test for different Kubernetes version has been introduced in v1alpha4
