### ISSUE TITLE
Make error messages consistent across ClusterClass and Topology Controller

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5067]
**Detailed Description**

The error messages across the different implementations of functions in the cluster class and topology controller work are currently inconsistent as referenced here: https://github.com/kubernetes-sigs/cluster-api/pull/5045#discussion_r685231919

This is particularly important for issues that arise in the cluster topology reconciliation as users may have to manually resolve issues caused by misconfiguration. Useful error messages from the controller will be very valuable in making that a less painful process.

This issue is for discussion on how to return, wrap, and format errors to give users context and clarity when trouble shooting. The key goal is to make the error messages consistent across the code. 

**Anything else you would like to add:**
Deciding on error formatting and wrapping etc. can be done on this issue, and then changes can be implemented either by a single person or by each contributor on the PR.

/kind feature

**Comment by sbueringer** [comment]
Copying my answer from #5045

```bash
Hm I see multiple options here:
* current option: "failed to retrieve Cluster state" + "InfrastructureCluster" + ""reference is not set"
* verbose option: "failed to retrieve Cluster state" + "failed to get InfrastructureCluster" + ""reference is not set"
* shorter option: "failed to retrieve Cluster state" + "get InfrastructureCluster" + ""reference is not set"
* shortest option: "retrieve Cluster state" + "get InfrastructureCluster" + ""reference is not set"

I personally prefer the last option as it drops all that's not strictly necessary to understand what's going on on the different levels. Prefixes like "failed to" or "error ..." are imho usually not really useful. But I think across our code base we're probably using almost all of them. 

To be honest I'm not sure what we should do here, apart from that it would be nice to keep it consistent at least in the local file (which means we would have to adjust at least my calls of getReference above).

Maybe we should just discuss once what we regard as the best option and then try to use that one from now on everywhere? Right now I frequently look up what we do "locally" and then try to align to that when adding new code to CAPI.
```

In my opinion this is something we have across our entire code base. It would be nice to know how we want to handle this, imho either:
* choose one way to do this going forward (In my opinion it's not worth it refactoring all our existing code)
* trying to be locally consistent (per file / package / controller?)
* use a subset of the possible error formatting options (would be good to at least be aware that we don't really care about this and we have a few valid options)

**Comment by killianmuldoon** [comment]
I think we could focus this on all the new code and error handling that's going on in the ClusterClass + ManagedTopology work. If we think a consistent format is worth following through on it would be relatively easy to create a bunch of per-package issues that could be taken on with lower priority to improve error reporting across the code base.

I'm definitely +1 for finding a consistent way to do this going forward with a focus on what we're working on right now as the pathfinding work.

**Comment by fabriziopandini** [comment]
My two cents:
1. The func raising the error should provide all the context existing there for debugging the problem; ideally the message should be self consistent and providing enough info for the users to diagnose/fix the problem.
2. Higher level function should add additional context when this makes sense e.g. if they are calling the same function more times and surfacing which call is failing could help, or if they are part of complex process and we want to surface which phase failed.

Instead, assuming messages being composed in a certain way driven by a well known sequence of nested calls is somehow weak, because things can change or function can be reused in another way or composed in different ways.

**Comment by fabriziopandini** [comment]
Notes after a first, partial code audit:
- We should consolidate error messages in reporting gvk/name when referring to objects different than the Cluster (same notation used eg. by kubectl get/scale etc)
- We should avoid to report gvk/name of Cluster as well as namespace for any object given that those info are already added by controller runtime

**Comment by fabriziopandini** [comment]
Notes after first run:
- This error message is super verbose, might be nice to simplify
```
E0812 13:44:10.223606       9 controller.go:304] controller-runtime/manager/controller/cluster "msg"="Reconciler error" "error"="error reading current state of the Cluster topology: failed to read KubeadmControlPlane my-cluster1-qhzck: failed to retrieve KubeadmControlPlane \"my-cluster1-qhzck\" in namespace \"default\": failed to retrieve KubeadmControlPlane external object \"default\"/\"my-cluster1-qhzck\": KubeadmControlPlane.controlplane.cluster.x-k8s.io \"my-cluster1-qhzck\" not found" "name"="my-cluster1" "namespace"="default" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Cluster"
```
- It is hard to spot errors from topology/ClusterReconciler from errors from other reconcilers

**Comment by sbueringer** [comment]
@fabriziopandini I think this proves my point about that it's not that great to add prefixes like "error on" "failed when". Sometimes it's unavoidable, but in most cases this could be stripped out.
Example:
* current: `"error"="error reading current state of the Cluster topology: failed to read KubeadmControlPlane my-cluster1-qhzck: failed to retrieve KubeadmControlPlane \"my-cluster1-qhzck\" in namespace \"default\": failed to retrieve KubeadmControlPlane external object \"default\"/\"my-cluster1-qhzck\": KubeadmControlPlane.controlplane.cluster.x-k8s.io \"my-cluster1-qhzck\" not found"`
* without prefix: `"error"="reading current state of the Cluster topology: read KubeadmControlPlane my-cluster1-qhzck: retrieve KubeadmControlPlane \"my-cluster1-qhzck\" in namespace \"default\": retrieve KubeadmControlPlane external object \"default\"/\"my-cluster1-qhzck\": KubeadmControlPlane.controlplane.cluster.x-k8s.io \"my-cluster1-qhzck\" not found"`

It's a little bit shorter. Further optimization steps:
* we have the same retrieve error twice there
* imho it would be great to standardize verbs a bit if it makes sense reading/read/retrieve => get

Then it could look roughly like this:

* without prefix: `"error"="get current state of the Cluster topology: get KubeadmControlPlane external object \"default\"/\"my-cluster1-qhzck\": KubeadmControlPlane.controlplane.cluster.x-k8s.io \"my-cluster1-qhzck\" not found"`

(I think it might be useful to still keep the KCP name in our error message do not rely on that the error message below (which afaik comes from client-go?) contains it)

**Comment by fabriziopandini** [comment]
@ykakarap @sbueringer this IMO has been already address by https://github.com/kubernetes-sigs/cluster-api/pull/5153
can we close this issue?

**Comment by sbueringer** [comment]
sgtm
