### ISSUE TITLE
Housekeeping task for Kubernetes v1.22.0

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5083]
This issue track housekeeping task to be done when a new Kubernetes minor release is created.

- [x] Create/Update periodic and presubmit jobs for workload clusters upgrade and conformance https://github.com/kubernetes-sigs/cluster-api/issues/5060 https://github.com/kubernetes/test-infra/pull/23181 
- [x] Update quick-start and e2e tests https://github.com/kubernetes-sigs/cluster-api/pull/5080 

/kind cleanup

**Comment by sbueringer** [comment]
I think we can close this issue again

/close
