### ISSUE TITLE
workload Cluster failed will not be recovered

### ISSUE THREAD

**Issue by ruifaling** [kubernetes-sigs/cluster-api#5097]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

After the workload cluster has been created,if there was something error(such as vm shutdown),it will not be recovered,even if the vm has been fixed
**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.4.0
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):1.20.10
- OS (e.g. from `/etc/os-release`):centos-8

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
/help

**Comment by vincepri** [comment]
/priority awaiting-more-evidence
/milestone Next

@ruifaling Do you have more information you can share? More often than not, this is highly dependent on the infrastructure provider.

**Comment by ruifaling** [comment]
> /priority awaiting-more-evidence
> /milestone Next
> 
> @ruifaling Do you have more information you can share? More often than not, this is highly dependent on the infrastructure provider.

The infrastructure provider is OpenStack（Rocky）,Cluster API Provider OpenStack version is v0.4.0.
If the vm state become 'shutdown' or something else not 'Active' or 'build',the machinedeployment phase will be failed;even if the vm state become 'Active',the machinedeployment phase will be failed forever

**Comment by sbueringer** [comment]
@ruifaling In my opinion this is something which has to be fixed in CAPO. Very similar to this issue for the OpenStackCluster: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/951

**Comment by fabriziopandini** [comment]
/close
this has to be fixed in CAPO
