### ISSUE TITLE
Should we pause a ClusterClass?

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5121]
**Detailed Description**

As of today we are not supporting pause in ClasterClass, given the object is not reconciled.

However, during a discussion it was raised a question if we should use pause on ClusterClass as a proxy to pause an entire group of Clusters (all the cluster using the same ClusterClass), which is something not possible today.

This issue is about discussing if this option should be implemented, identifying use case, investigate feasibility. 

/kind feature

**Comment by vincepri** [comment]
To keep things a bit consistent across the board, we could consider to allow ClusterClass to pause reconciliation of the managed topology portion for all clusters that use a specific cluster class

**Comment by fabriziopandini** [comment]
> to pause reconciliation of the managed topology portion for all clusters that use a specific cluster class

I'm not sure that "a partially paused cluster" is something easier to understand for the users, but TBH we don't have data on managed Clusters with user managed additions, so mine are mostly speculation at this stage.
I'm also wondering if this could be also tricky to implement, given that if we set pause on a managed cluster, this will affect everything in the cluster, not only the managed part.

**Comment by sbueringer** [comment]
As discussed in the grooming on 18th February, let's close this for now.
We might reconsider a similar feature when/if we introduce an abstraction for rollout of ClusterClasses

/close
