### ISSUE TITLE
test: passed test suite contains failed test cases

### ISSUE THREAD

**Issue by chewong** [kubernetes-sigs/cluster-api#5123]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-capz-windows-dockershim/1417250279195152384

The job above has two failed test cases but it's marked as passed: 
```
Test started yesterday at 3:31 PM passed after 1h24m54s. (more info)
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Transferred to CAPI repo as this is an issue in the CAPI test framework and affects CAPI as well https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main-1-18-1-19.

> I think ginkgo does not return a non-zero exit code and that’s why RunContainer does not fail (which is probably good because with our current code we would otherwise not gather the test results, and wouldn’t see them in Prow)
Imho, one solution could be to read the test results after: https://github.com/kubernetes-sigs/cluster-api/blob/e0ced24598da02d8d64d93da71acbf86fd6a7e32/test/framework/kubetest/run.go#L193
And if we find failed tests, return an error.

cc @sbueringer @randomvariable

**Comment by randomvariable** [comment]
Chat from Slack, looks like we're going to have to parse the JUnit XML and figure out if something failed, which is pretty terrible.

Philosophically in the initial implementation, the current behaviour was intended given that to get any sort of result from conformance was a big success in itself. Taking the next step in making a failed conformance test fail the suite is reasonable.

**Comment by sbueringer** [comment]
fyi. Prow is using GCP/testgrid to parse junit reports for the junit lens: 
https://github.com/kubernetes/test-infra/blob/master/prow/spyglass/lenses/junit/lens.go#L162
https://github.com/GoogleCloudPlatform/testgrid/blob/master/metadata/junit/junit.go#L198-L204

No idea if it's a good idea to use it.

**Comment by randomvariable** [comment]
If it does what we want, i don't see why not.

**Comment by sbueringer** [comment]
> If it does what we want, i don't see why not.

Just thinking about that we might don't want to have a dependency on testgrid and not sure how stable it is as a library (current verison is 0.0.91). But I guess as the worst case is to copy ~200 lines of code, it shouldn't hurt to have a dependency on it.

**Comment by vincepri** [comment]
We have the `third_party` folder where you could copy code from upstream repositories if needed.

/milestone v1.0
/priority important-soon

**Comment by fabriziopandini** [comment]
/triage accepted
worth to investigate if this is still the case

**Comment by sbueringer** [comment]
Definitely still the case.

This can be reproduced ~ like this:
* Run an upgrade test locally with a breakpoint before we run kubetest
* Break the cluster (e.g. change the image in the CoreDNS Deployment to an invalid name)
* Wait 10m (or add `system-pods-startup-timeout: 1m` to `conformance.yaml`
* Step through the remaining code. I would expect us to copy the junit reports around but based on the code we don't read and parse the results to fail the e2e test if there are any failures in the junit reports


cc @knabben (Just in case you're looking for more workin a bit :), I can help you getting the local e2e test up & running)

**Comment by sbueringer** [comment]
Not sure about CAPZ I think they had other problems, but I think our problem is not solved.

Should be still reproducible via: https://github.com/kubernetes-sigs/cluster-api/issues/5123#issuecomment-1370032836

We didn't make any changes in core CAPI

**Comment by sbueringer** [comment]
@chrischdi Just that I got it right. Current behavior:
* If any conformance test fails, the test in Prow will fail as well
* If any conformance test fails, we won't get the junit report in Prow (by which we would see what exactly failed)
Is that correct?

**Comment by chrischdi** [comment]
> @chrischdi Just that I got it right. Current behavior:
> 
> * If any conformance test fails, the test in Prow will fail as well

Exactly, the case described in this issue that the test "passed" was because of the race condition because docker restarted the container.

> * If any conformance test fails, we won't get the junit report in Prow (by which we would see what exactly failed)
>   Is that correct?

We would get them in prow, but hidden in artifacts as xml file / not visualised by prow. But this will be fixed via #10493

**Comment by sbueringer** [comment]
> We would get them in prow, but hidden in artifacts as xml file / not visualised by prow. But this will be fixed via https://github.com/kubernetes-sigs/cluster-api/pull/10493

Not sure I got this part. I think we only have one xml file in artifacts, and that is the one that Prow uses to visualize: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-conformance-main/1780353942337622016/artifacts/

Are there more? (that are also uploaded to artifacts)

**Comment by sbueringer** [comment]
Ah, we move the files? So if the move doesn't happen they are still here? https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-conformance-main/1780353942337622016/artifacts/kubetest/k8s-conformance-zcv9fy/

**Comment by chrischdi** [comment]
Yeah, to make them visible to prow we have to move them up.
