### ISSUE TITLE
Support MHC in ClusterClass

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5125]
**User Story**

As a user I would like to use MHC in managed topologies

**Detailed Description**

ClusterClass provides a way to define a "stamp" to be used for creating many Cluster with a similar shape.

It would be great to have a way to include MHC in the ClusterClass, so it will be automatically included in the generated Clusters.

/kind feature

**Comment by enxebre** [comment]
@killianmuldoon you still planning to work on this? Just let me know if you want me to give a go

**Comment by killianmuldoon** [comment]
@enxebre Yeah - I should be picking it up over the next couple of days I think.

**Comment by fabriziopandini** [comment]
Adding some implementation notes:
1. given that CP/MD which already have randomly generated names, we can use the same name of the corresponding MHC objects as well
2. scope `ControlPlaneState` and `MachineDeploymentState` should be modified to host corresponding MHC objects
3. `getCurrentState` should read existing MHC objects and fill in `scope.Current` (via simple Get statements which are more performant than List)
4. `computeDesiredState` should fill in MHC objects in  `scope.Desired`, setting values for cluster, cluster ownerRef, label selectors, and other fields from ClusterClass
5. `reconcileState` should take care of:
  - creating/patching/deleting MHC for control plane
  - creating/patching/deleting MHC for MD   
  
For 5 we should consider having a `reconcileMHC` func to be used in both contexts; additionally, we should make sure to not leave orphaned MHC objects around, especially when a MD gets deleted - by topology controller or manually by the users -
