### ISSUE TITLE
Operator: delete all resources on CR deletion

### ISSUE THREAD

**Issue by asalkeld** [kubernetes-sigs/cluster-api#5133]
See : https://github.com/kubernetes-sigs/cluster-api/pull/4926

Delete does not work correctly as the generic finializer will only delete namespaced objects, not clusterRole[bindings].
So for example ClusterRoleBindings recently had a roleRef change that caused a problem..

    I installed control-plane
    I deleted the CR, causing all namespaced objects to be deleted
    I re-installed with this ea7d15c#diff-ebe503e27018c4726aec513160dd6748e65f8d4ef9822612670b58d7ca8079fb
    Error: can not change clusterrolebinding roleRef in an update..

Delete all objects that were created using our own finalizer.

/kind feature
/area operator

**Comment by fabriziopandini** [comment]
@alexander-demichev any objection to closing this now that the work is being moved in a separated repo?

**Comment by sbueringer** [comment]
/close
given that the operator was moved to another repository
