### ISSUE TITLE
ClusterClass: Rollout strategies on upgrade

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#5145]
**User Story**

As a cluster operator I would like to control the rollout of upgrades to my MachineDeployments when consuming ClusterClass such that I can verify the operation of my nodes and workloads. My workloads include [network function virtualisation](https://en.wikipedia.org/wiki/Network_function_virtualization) which are tied to particular hardware, requiring careful rollout to meet availability requirements for my telecoms network.

**Detailed Description**

Just to be clear, the person "I" is a fictional one, but is based on customers I've talked to.

In a cluster serving network functions, machines are not readily swappable even when virtualised as they are often tied to a particular piece of hardware, e.g. a Radio Access Network card providing connectivity to mobile phones at a cell site, GPUs, and other network accelerators. In this scenario, I will want to roll out one MachineDeployment, ensure everything is running OK, and then initiate the upgrade of the next Machine Deployment. 

There is a question here around automation that needs to be dug into - possibly there's some stronger signal for the workloads that can be automatically consumed somewhere and feed into a lifecycle hook of some sort. The NFV software themselves may be of varying quality though, so there could be limits to the amount of health signal they give which might at the end of the day require manual intervention to roll out MachineDeployments.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by randomvariable** [comment]
> There is a question here around automation that needs to be dug into - possibly there's some stronger signal for the workloads that can be automatically consumed somewhere and feed into a lifecycle hook of some sort. 

Interested folk may at some point want to work in the CNCF Telco WG and ETSI and define some standards.

**Comment by fire-ant** [comment]
Currently the discussions of upgrade strategy suggest that queue placement will be derived from alphanumeric ordering based on name.  This may work if there is an alignment between the role of a node and the upgrade strategy. 

My feeling is that whilst this could be a sane default  we should be able to sequence queue placement based on a customisable selector such as a label which can be specified within the managed topology of a given ClusterClass manifest. We could also include an 'ascending' bool which allows us to enforce the forwards/backwards relationship of an upgrade sequence. 

Where there are  specific hardware constraints or topological requirements (all the backend, then frontend, then app servers) it should be possible to apply reasonable logic to induce an upgrade without doing something unforeseen.

**Comment by killianmuldoon** [comment]
The requirements in this area can rely on very niche hardware constraints and relying on the Containerized Network Functions to be up and running (and warmed up as some require ramping on traffic etc.) before being able to take the old, unupgraded version online. The RolloutStrategy here could end up looking like a complicated Machine scheduler if we try to bake all of that into a controller. Is there an easy-win use case to start building these requirements around? Or

**Comment by fire-ant** [comment]
I think the MVP with the fields/annos I had mentioned to enact some level of control would be enough. 

At the application layer it is not uncommon to devise strategies with a combination of heml/kustomize/clonesets for the subset of use cases where components need to roll in a more granularly controlled order (though this precludes system components).

**Comment by fabriziopandini** [comment]
> Currently the discussions of upgrade strategy suggest that queue placement will be derived from alphanumeric ordering based on name.  This may work if there is an alignment between the role of a node and the upgrade strategy. 

A clarification here. 
The control plane will be always upgraded first, then the machine deployments; the alphanumeric ordering will be used to define a predictable order for upgrading machine deployments (but a machine deployment will never be upgraded before the control plane)

**Comment by fabriziopandini** [comment]
Note: sequencing of MachineDeployments, is now defined by the order in Cluster.Topology.Workers.MachineDeployments, so the users has full control of it. The delta to complete this story is to introduce a mechanism for pausing in between machine deployments upgrades

/milestone v1.0

**Comment by enxebre** [comment]
related https://github.com/kubernetes-sigs/cluster-api/issues/5863

**Comment by killianmuldoon** [comment]
/remove-lifecycle stale

Currently being worked on in #7401

**Comment by sbueringer** [comment]
As Killian wrote on the PR this issue is not related to #7401

**Comment by sbueringer** [comment]
@fabriziopandini I think this issue has been adressed for now by https://github.com/kubernetes-sigs/cluster-api/issues/8100

WDYT?
