### ISSUE TITLE
Support provider deprecation

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api#5152]
**User Story**

As a provider implementer, I would like to be able to deprecate a provider to support changes in the provider types / deployment options for a provider.

**Detailed Description**

In CAPA prior to version 0.7.0 we had infrastructure, control plane and bootstrap providers. This separation caused some technical and UX issues.  So with the 0.7.0 release we have removed the separate control plane and bootstrap providers and combined them into the infrastructure provider. 

It would be good if there was the ability to mark a provider as deprecated from a specific version (from 0.7.0 in out case for the `aws-eks` control plane and bootstrap providers).

We can't just removethe providers as someone may use clusterctl to install a version prior to 0.7.0

/kind feature
/area clusterctl

**Comment by sbueringer** [comment]
Mirroring what I wrote in Slack. Right now we have the following situation:
* clusterctl v0.3.x: is able to install v1alpha3 providers (CAPA < v0.7.0)
* clusterctl v0.4.x: is able to install v1alpha4 providers (CAPA >= v0.7.0) and only to upgrade v1alpha3 providers to v1alpha4

So tl;dr current clusterctl is already unable to install your old providers as they are not using the v1alpha4 contract.

**Comment by sbueringer** [comment]
+1 as it provides a better UX for end users and then less questions in Slack :)

**Comment by fabriziopandini** [comment]
(doing some cleanup on old issues without updates)
/close
unfortunately, no one is picking up the task. the thread will remain available for future reference
