### ISSUE TITLE
KCP should reset OwnerRemediated condition if the machine returns healthy

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5169]
**What steps did you take and what happened:**

When bootstrapping a cluster:
- KCP remediation was triggered, with MHC setting `HealthCheckSucceeded` condition to false on a machine
- Remediation was not possible because the control plane has only 1 node, so `OwnerRemediated` condition was set to false with reason `KCP can't remediate if current replicas are less or equal then 1`
- Some time later the machine returned healthy, with MHC setting `HealthCheckSucceeded` condition to true

However, KCP did not detected this happening and `OwnerRemediated` condition remained to false.

**What did you expect to happen:**

KCP to properly detect the machine returning healthy and this removing the remediation warning

**Anything else you would like to add:**

Please note that it makes sense to remove remediation warning only if the remediation is not yet started.

**Environment:**

- Cluster-api version: v0.3.22
/kind bug
/area control-plane

**Comment by ggaurav10** [comment]
> /milestone v0.4
> 
> Note: the fix should be back ported to v0.3 branch too

Can we please backport the fix for this issue to branch v0.4?
