### ISSUE TITLE
failed to get provider components for the "vsphere" provider

### ISSUE THREAD

**Issue by quodvis** [kubernetes-sigs/cluster-api#5171]
I try to install capi and get the following problem.

$ clusterctl init --infrastructure vsphere
Fetching providers
Error: failed to get provider components for the "vsphere" provider: failed to set the TargetNamespace on the components: converting (v1beta1.MutatingWebhookConfiguration) to (v1.MutatingWebhookConfiguration): unknown conversion

my environment is:

$ clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"4", GitVersion:"v0.4.1", GitCommit:"f6fd5ed7dc0fa75788f76f17c64ae82976fcc70b", GitTreeState:"clean", BuildDate:"2021-08-12T23:19:16Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

New clusterctl version available: v0.4.1 -> v0.4.2
https://github.com/kubernetes-sigs/cluster-api/releases/tag/v0.4.2

$ docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:08 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:16 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

$ kind version
kind v0.11.1 go1.16.4 linux/amd64

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

/kind bug

label:area/clusterctl

**Comment by sbarikdev** [comment]
This issue happened to my env with clusterctl v1.0.0 version also.

**Comment by sbueringer** [comment]
As mentioned above and on https://github.com/kubernetes-sigs/cluster-api/issues/5628

We're not able to reproduce the issue either with v0.4.2+ or v1.0.0:

```bash
$ clusterctl-v1.0.0 init --infrastructure vsphere
Fetching providers
Skipping installing cert-manager as it is already installed
Installing Provider="cluster-api" Version="v1.0.0" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v1.0.0" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v1.0.0" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-vsphere" Version="v1.0.1" TargetNamespace="capv-system"
```

The only way I can think of that this issue can occur is if clusterctl somehow fetches and older version of the vsphere provider which I think can only happen via overrides (https://cluster-api.sigs.k8s.io/clusterctl/developers.html#create-the-local-repository).

I'm not sure that there is anything we can do to help. I think the only way to investigate this further is to run clusterctl via the Go debugger and step through the code on the machines were it occurs.
