### ISSUE TITLE
RFE: Runtime Extensions

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#5175]
From a while back there has been a need for Cluster API providers to be able to define their own extensions that can work across a number of different use cases. This issue is meant to be an ongoing discussion / brainstorm on what runtime extensions goals/non-goals are, and how we can make it happen with our roadmap to beta.

#### Requirements
- We should reuse, wherever possible, the machinery in api-server and controller tools to generate well-defined RPC services.
- The system should be defined after the admission and mutation webhook registration mechanics present in api-server for custom resource definitions.

#### Goals
- To provide clear interfaces for external providers to implement their functionality.
- To support runtime registration of new extensions with clear defined boundaries and responsibilities.
- To allow to extend the validation of Cluster API resources.
- To validate provider-specific content as early as possible.
- To offer kubebuilder-like functionality to scaffold a new runtime extension in Go.

#### Non-Goals
- To replace the current provider model for infrastructure resources

/kind design
/kind proposal

**Comment by fabriziopandini** [comment]
+1000
my two cent

Goals:
- provide *generic* extension mechanism for CAPI that can be used when
   - The interaction between CAPI and the extension components requires synchronous/blocking RPC calls.
   - Given RPC call the request is blocking, and also probably adding latency, the request could evaluate in a very short time.

Noan Goals
- To replace the current extension mechanism using for complex, long running interactions with providers (based on CRD resources with well-know informations defined by the Cluster API contract)

**Comment by imikushin** [comment]
Can we have more context on what Runtime Extensions are, why they need to exist, and some examples of how exactly they would be used? Without such context, it's impossible (at least, for me) to understand the proposal or any reasoning about it. Thank you!

**Comment by vincepri** [comment]
@imikushin That's something we all need to figure out

**Comment by fabriziopandini** [comment]
Trying to move forward with the discussion, I have created https://docs.google.com/document/d/1WTGtu32rGlme16f3133MH9dLgiJxHtABp0pWZmamInc/edit?usp=sharing with:
- some notes about a first, concrete use case for Runtime Extension, external patches for ClusterClasses
- a first brain dump of things to be defined before writing the proposal on Runtime Extensions in Cluster API
