### ISSUE TITLE
Defer template deletion for MachineSets in a managed topologies

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5176]
**What steps did you take and what happened:**
While testing template rotation for a MachineDeployment in a managed topology, deletion process of the old MachineSet got stuck and the MachineSet controller started to fail due to missing templates.

**What did you expect to happen:**
The machine deployment in a managed topology to properly rotate templates

**Anything else you would like to add:**
This is a problem of syncronization between the managed topology controller and the MachineSet controller.

Managed topology controller is responsible to delete old templates in case of template rotation, but this operation has to wait for the MachineSet to actually delete all the machines before removing the template.

The current working assumption to address this issue is to implement a MachineSet topology controller watching for MachineSets with the cluster.x-k8s.io/topology label only; this controller is going to:
- add a finaliser on the machine set if missing
- detect the MachineSet being deleted after removing all the machines
- delete the corresponding templates if rotated (if different from the ones in the MachineDeployment)
- remove the finaliser

**Environment:**

- Cluster-api version: master

/kind bug

**Comment by sbueringer** [comment]
Do we need a similar mechanism for MachineDeployments? (or maybe use the one for MachineSets for both)

**Comment by fabriziopandini** [comment]
We probably need both, but let's start by MachineSet because they have more frequent turnover than MachineDeployments

**Comment by fabriziopandini** [comment]
@sbueringer should we close this issue now that https://github.com/kubernetes-sigs/cluster-api/pull/5191 is merged?

**Comment by sbueringer** [comment]
Yup, let's close it.
/close
