### ISSUE TITLE
Make sure documentation is clear that MachineDeployment is the right model for "disruption budget" style machine updates

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api#518]
Based on the discussion in the cluster-api sig meeting on 3rd Oct, @timothysc suggested to look deeper into the possibility of introducing the concept of `Disruption Budgets` in the context of machine controller. See [Disruption Budgets](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/) fore reference in context of the kubernetes pods

This issue is a tracking Issue for related discussion on the topic

**Comment by nikhita** [comment]
> Based on the discussion in the cluster-api sig meeting on 3rd Oct

[Link](https://docs.google.com/document/d/16ils69KImmE94RlmzjWDrkmFZysgB2J4lGnYMRN89WM/edit#heading=h.5d12rrrxp5o3) to the meeting notes.

/cc @alvaroaleman @xmudrii

**Comment by timothysc** [comment]
We should be recommending machine deployments and outline that we may not support on machines.

**Comment by ncdc** [comment]
We need overall documentation for MachineDeployments. We'll incorporate this information when we do that. I don't think we need to keep this open.
/close
