### ISSUE TITLE
Adding new machine deployments while control plane is upgrading in managed topologies

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#5183]
This issue is meant to be an ongoing discussion/brainstorming to see if it is acceptable or not to allow creation of new machine deployments while the control plane is upgrading/scaling.

In the initial implementation[1] of upgrade in managed topologies we are allowing creation of new machine deployments while the control plane is upgrading[2] or scaling[3].  

This needs more thought and probably some testing to see what the implications are of allowing creation of new machine deployments during an upgrade/scaling.

[1] Initial implementation of managed topologies upgrade is available at: https://github.com/kubernetes-sigs/cluster-api/pull/5178
[2] A control plane is considered upgrading if the `spec.version` and `status.version` of the control plane object do not match.
[3] A control plane is considered scaling if any of `status.replicas`, `status.readyReplicas` and `status.updatedReplicas` do not match `spec.replicas`. Note that a scaling control plane may or may not also be upgrading. 

/kind design

**Comment by sbueringer** [comment]
Afaik our e2e tests are creating everything at the same time and the MachineDeployment get up eventually. During upgrade I guess it should work in most cases as the control plane is already initialized. 

A problem could be that when a MachineDeployment is created with a higher version than the oldest control plane machine.
E.g. Control plane is upgrading from v1.21 to v1.22 and MachineDeployment is created with 1.22. New MachineDeployment 1.22 machines might not work when the kubelet communicates with a v1.21 control plane machine.

So based on `kubelet must not be newer than kube-apiserver, and may be up to two minor versions older.` (https://kubernetes.io/releases/version-skew-policy/#kubelet) I wouldn't create MachineDeployments with newer versions than our oldest control plane node. This gives us two options:
1. wait until the control plane is upgrade, then create MachineDeployment with the new version
2. create MachineDeployment with the old version, upgrade it after the control plane upgrade has finished

I think option 1 is the better one as it avoids creating machines and then directly updating them.

**Comment by fabriziopandini** [comment]
/close 
Superseed by #5222
