### ISSUE TITLE
go get / go install for projects depending on capi does not work 

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#5184]
**What steps did you take and what happened:**
```
go install sigs.k8s.io/cluster-api-provider-aws@v0.7.0: sigs.k8s.io/cluster-api-provider-aws@v0.7.0
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
Albertos-MacBook-Pro:~@albertogarla $ go get sigs.k8s.io/cluster-api-provider-aws@v0.7.0
```

```
go get: sigs.k8s.io/cluster-api-provider-aws@v0.6.8 updating to
	sigs.k8s.io/cluster-api-provider-aws@v0.7.0 requires
	sigs.k8s.io/cluster-api/test@v0.4.1 requires
	sigs.k8s.io/cluster-api@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

```
go get: sigs.k8s.io/cluster-api/test@none updating to
	sigs.k8s.io/cluster-api/test@v0.4.2 requires
	sigs.k8s.io/cluster-api@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**What did you expect to happen:**
go get / go install works

**Anything else you would like to add:**
This is the controversial clause https://github.com/kubernetes-sigs/cluster-api/blob/master/test/go.mod#L5
This can be workaround by adding a replace clause for capi in the invoking go.mod file. Nevertheless I'd expect us to provide a better solution so this commands work out of the box.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by killianmuldoon** [comment]
> adding a replace clause for capi in the invoking go.mod file 

Can you expand on this?

Another solution I'm seeing is to avoid doing this for release versions of a project so that go install etc. will work for release versions but this easier method of testing the latest code can be used for whatever the local version is. [c/f ](https://github.com/golang/go/issues/42627#issue-743663670)

**Comment by enxebre** [comment]
>Can you expand on this?

Basically what any consumer need to do today, e.g any provider https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/go.mod#L5

**Comment by killianmuldoon** [comment]
@fabriziopandini do you think we could update the release tools to pin this version for each release?

**Comment by vincepri** [comment]
@killianmuldoon What did you have in mind to do the above? The current release process happens after the tag is published

**Comment by killianmuldoon** [comment]
I was thinking maybe adding something to change this line in go.mod under 'make release' - but with the ordering there will be drift with the go.mod.

**Comment by sbueringer** [comment]
/close
in favor of #6081
