### ISSUE TITLE
Support "Static IP" configuration for the Machines

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api#519]
Currently, the IP configuration for the `Machines` only support DHCP and not static IP.
I believe there is a real use case where we do want to control the IP addresses assigned to the Machines from the cluster-api layer.
If need be one could pack in the `ProviderConfig` part of the `Machine` the static IP information and have the cloud provider provision `that` instance of a `Machine` with the provided IP. But this does not work if we want to use higher order objects like `MachineSet` and `MachineDeployment`

I believe there is a need for the ability to specify something like `IP Range` at the higher layer `MachineSet` or `MachineDeployment` and as the controllers for these higher order object create the `Machine` objects they should be able to inject an allocated IP from the range into the `Machine` object. Which then can be picked up and processed by the MachineController in a normal way. In the current behavior the provider specific callouts only happen either at the `Cluster` level or the `Machine` level. The intermediate constructs like `MachineSets` or `MachineDeployment` don't have any provider specific hooks.

Based on slack conversation with @alvaroaleman around this topic, one idea could be to implement a `MutatingAdmissionWebhook` for the `Machines` that could have the responsibility of uniquely allocating the IP to the machine from the defined IP Block

**Comment by chaosaffe** [comment]
While I do see a need for this, I think it would be preferable to have IPAM outside of the `cluster-api` but prefer to see it implemented as a separate controller. Not all clouds will require this, and a separate controller could have domain specific CRDs to represent the pools, assignments, etc...

**Comment by roberthbailey** [comment]
/assign @sidharthsurana

@sidharthsurana offered to write up a google doc describing the use cases and some possible implementation paths.

**Comment by timothysc** [comment]
This is provider specific and closing for main cluster api.
