### ISSUE TITLE
Managed topology should add topology.cluster.x-k8s.io/deployment-name to machineDeployment templates

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5193]
While generating a machine deployment out of a managed topology we are also generating a bootstrap template object and an infrastructure machine object.

However, we are not adding the `topology.cluster.x-k8s.io/deployment-name` label to the generated templates like we are doing for the MachineDeployment object.

**Environment:**

- Cluster-api version: master

/kind bug

**Comment by anusha94** [comment]
The label value for both bootstrap and infra machine template will be `machineDeploymentTopology.Name`. Is this understanding correct?

**Comment by sbueringer** [comment]
> The label value for both bootstrap and infra machine template will be `machineDeploymentTopology.Name`. Is this understanding correct?

Yes
