### ISSUE TITLE
Managed topology should add dynamic watches for InfrastructureCluster and ControlPlane kind

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5194]
While reconciling a managed topology we should add dynamic watches for InfrastructureCluster and ControlPlane kind, thus ensuring a timely reconcile whenever a change happen on those objects.

Note, this could be done either during read current cluster or during compute desired state (TBD)

**Environment:**

- Cluster-api version: master

/kind bug

**Comment by killianmuldoon** [comment]
How does this interact with #5195?

**Comment by sbueringer** [comment]
The current issue is not about managed objects the other one about templates referenced in the Clusterclass. I think they shouldnt interact.
