### ISSUE TITLE
ClusterClass webhook allow compatible reference changes

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5197]
Current ClusterClass webhook implementation ensures that references to template Objects are correct and fully provided. and then enforce immutability.

We should allow for reference changes, thus supporting the template rotation operation pattern,

However, in this case, it is required to implement checks ensuring compliance with the [compatibility rules](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/202105256-cluster-class-and-managed-topologies.md#clusterclass-compatibility) defined in the proposal (the last bullet in the list)

**Environment:**

- Cluster-api version: master

/kind bug

**Comment by fabriziopandini** [comment]
@yastij to add about the use case of renaming an apigroup, which is not included in the current compatibility definition

**Comment by sbueringer** [comment]
Minor addition: Afaik we currently make sure they are immutable: https://github.com/kubernetes-sigs/cluster-api/blob/f950b4c4ae0f3be530a7dd4a29a5d38bec404b1f/api/v1alpha4/clusterclass_webhook.go#L132-L200

**Comment by fabriziopandini** [comment]
@sbueringer you are right as sorry for did not provide full context here.

The background idea behind this issue it that at this stage, IMO we can reasonably start enabling a subset of ClusterClass mutations by enabling metadata mutation (see ClusterClass webhook should allow for metadata mutation #5192) and template rotation according to the idea of compatible change (this issue).

A similar discussion on https://github.com/kubernetes-sigs/cluster-api/issues/5195#issuecomment-912959823, however with a slight different perspective (how to react timely to changes)
