### ISSUE TITLE
Consider <cluster>-control-plane as ControlPlane name prefix in managed topologies

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5198]
I wonder if we should name the control plane `<cluster-name>-control-plane` to make sure the control plane machines are easily identifiable. Currently with managed topology the machines look e.g.: like this:

```bash
NAMESPACE   NAME                                                                                 AGE    PROVIDERID                                                             PHASE      VERSION
default     machine.cluster.x-k8s.io/my-cluster-default-worker-topology-2r27c-5c6fcc4d9d-wrm76   117s   docker:////my-cluster-default-worker-topology-2r27c-5c6fcc4d9d-wrm76   Running    v1.22.0
default     machine.cluster.x-k8s.io/my-cluster-default-worker-topology-2r27c-8f5796f45-q2slz    109s   docker:////my-cluster-default-worker-topology-2r27c-8f5796f45-q2slz    Running    v1.22.0
default     machine.cluster.x-k8s.io/my-cluster-lnwrr-95xvp                                      13m    docker:////my-cluster-lnwrr-95xvp                                      Deleting   v1.22.0
default     machine.cluster.x-k8s.io/my-cluster-lnwrr-kngmk                                      117s   docker:////my-cluster-lnwrr-kngmk                                      Running    v1.22.0
```

The worker machines are named like this `<cluster-name>-<topology-name>-<suffix>` while the control plane machines are just `<cluster-name>-<suffix>`. 

If we name the control plane `<cluster-name>-control-plane` the machines would be named `<cluster-name>-control-plane-<suffix>`

I think it would be a good idea, but it's fine for me to keep it as is if we don't get consenus.

- Cluster-api version: master

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by killianmuldoon** [comment]
👍  Sounds like an easy win for interpretability of kubectl commands etc.

**Comment by vincepri** [comment]
We should only be careful of not to exceed the max char limit on names

**Comment by sbueringer** [comment]
An entirely different variant: 

Add an additional label `machine.cluster.x-k8s.io/role` (potential values `control-plane`, `worker`) or something similar.

Prior art is: 
* CAPI: https://github.com/kubernetes-sigs/cluster-api/blob/778feb8bdf8aae4c35e9abde7c37f8d44d4f5890/api/v1alpha4/machine_types.go#L30-L33
* kubeadm: `node-role.kubernetes.io/control-plane: ""`
* Kubernetes `kubernetes.io/role` (not sure if/where that is used)

Add a new column to the CRD. The following has been tested and works: `.metadata.labels['machine\.cluster\.x-k8s\.io/role']` (specified like this on the CRD `JSONPath=".metadata.labels['machine\\.cluster\\.x-k8s\\.io/role']"`

This would give us the following output:
```bash
NAME                     AGE   ROLE            PROVIDERID                          PHASE     VERSION
my-cluster-lnwrr-kngmk   9h    control-plane   docker:////my-cluster-lnwrr-kngmk   Running   v1.22.0
```

Which is very close to:
```bash
NAME                     AGE   ROLE            PROVIDERID                          PHASE     VERSION
my-cluster-lnwrr-kngmk   9h    control-plane   docker:////my-cluster-lnwrr-kngmk   Running   v1.22.0
```
(Note: `kubectl get no` calculates the roles based on the kubeadm/Kubernetes annotations, which won't be possible that way in CRDs)

**Comment by fabriziopandini** [comment]
/milestone v0.4

I'm +1 to use the print column, given that this provides a explicit information and the solution applies both to managed and unmanaged clusters

**Comment by anusha94** [comment]
Can I take this up?

**Comment by sbueringer** [comment]
In general, I think yes.

I'm not entirely sure if we want to only add the label to control-plane nodes (in sync with `cluster.x-k8s.io/control-plane`) or also to worker nodes. kubeadm seems to only add the `control-plane` role to control-plane nodes and afaik worker nodes don't have a role.

I think I would only set the label (`machine.cluster.x-k8s.io/role`: `control-plane`) to control plane nodes.

/cc @vincepri @fabriziopandini

**Comment by fabriziopandini** [comment]
I think we should add the ROLE column to Machines, checking for `cluster.x-k8s.io/control-plane` as in the example above

```
$ kubectl get machine
NAME                     AGE   ROLE            PROVIDERID                          PHASE     VERSION
my-cluster-lnwrr-kngmk   9h    control-plane   docker:////my-cluster-lnwrr-kngmk   Running   v1.22.0
```

I don't expect this requiring us to change controllers or to apply new labels; this will leave the column empty for workers, but this is consistent with what happen for roles so I'm ok with it

**Comment by sbueringer** [comment]
I'm not sure how that would/could work. For nodes there's a builtin implementation which iterates through annotations and cut's prefixes to collect the roles.

With CRDs we can only say this column should have the value of this JSONPath. So when we try to use the value of `cluster.x-k8s.io/control-plane` we will get an empty string as value.

**Comment by fabriziopandini** [comment]
Ok, thanks for clarification.
In this case, given that addressing this with a simple print column is complex, I'm ok in adding the -control-plane suffix for Cluster Classe generated control plane objects.
We can eventually consider to add a machine.status.role field in the spec sometime in the future.

**Comment by sbueringer** [comment]
I think now I would prefer, either adding the annotation or the status field. Changing the control plane name now and changing it back later  is something I would like to avoid, as it means that users will have control planes with different names  depending on when they created their clusters.

I know it works, but it's not great and renaming a control plane I guess isn't impossible but a least a bit hacky.

**Comment by enxebre** [comment]
@sbueringer My understanding is that we are just wanting to solve a UX lack when listing machines here. So my only concern with label/annotation/status is that as a side effect we could be starting an unintended contract that might be consumed in unexpected ways. So if we go that way we should probably specify this is purely informative and not meant to be consumed.

**Comment by sbueringer** [comment]
I think in it's current unclear state this issue shouldn't be a good first issue
/remove-good-first-issu
