### ISSUE TITLE
Allow CA and key to be provided on cluster creation

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#52]
_From @rsdcastro on April 2, 2018 17:0_

Currently kubeadm init generates a self-signed certificate authority and key, which isn't a solution that suits all users.

This issue tracks allowing CA and key to be provided by the user.

_Copied from original issue: kubernetes/kube-deploy#661_

**Comment by spew** [comment]
Open PR for this issue here: https://github.com/kubernetes-sigs/cluster-api/pull/153

**Comment by spew** [comment]
As a result of PR https://github.com/kubernetes-sigs/cluster-api/pull/153 this issue has split into several sub issues:

- https://github.com/kubernetes-sigs/cluster-api/issues/161: Implement custom certificate authority support for tf-deployer
- https://github.com/kubernetes-sigs/cluster-api/issues/162: More secure transport mechanism for custom certificate authorities
- https://github.com/kubernetes-sigs/cluster-api/issues/163: Port PR-153 code into clusterctl

**Comment by rsdcastro** [comment]
Other issues tracked separately, so closing this out.
