### ISSUE TITLE
Support ClusterResourceSet in ClusterClass

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5203]
**User Story**

As a user I would like to use ClusterResourceSet in managed topologies

**Detailed Description**

ClusterClass provides a way to define a "stamp" to be used for creating many Cluster with a similar shape.

It would be great to have a way to include ClusterResourceSet in the ClusterClass, so it will be automatically included in the generated Clusters.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
I'm a little bit debated on this given that ClusterResourceSet already applies to many Clusters via label selectors, while including it in each generated Clusters seems to go in a different direction.
I will think more on it...

**Comment by sbueringer** [comment]
Fine for me

**Comment by fabriziopandini** [comment]
/close
As per comment above
