### ISSUE TITLE
Tilt should create a Kind cluster on 'tilt up'

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5204]
**User Story**
As a user I would like to have a full working Cluster API dev environment up and running with a single command.

**Detailed Description**
Today the Cluster API tilt environment requires a running Kind cluster as a prerequisite to using the tilt environment. In future the tilt setup should include the creation of a kind cluster before building and deploying the CAPI components to the cluster. 

The set up should create a kind cluster which can support the use of the CAPD provider - i.e. by setting the cluster extramounts to mount the docker socket, and apply Mac specific changes to the kubeconfig to allow it be used to access created clusters.

The Kind cluster should always be cleaned up when the tilt environment is taken down.

**Anything else you would like to add:**
The tilt dev guide in the Cluster API book should be updated in order to 

/kind feature
/area ux

**Comment by sbueringer** [comment]
> apply Mac specific changes to the kubeconfig to allow it be used to access created clusters

I think that will be almost impossible to do. The problem is that kubeconfigs of workload clusters which are created by CAPI (and stored in secrets) do not work natively on Mac. The kind cluster itself just works.

**Comment by killianmuldoon** [comment]
Yeah - I think you're right that this is a stretch, but there should be some way to make it more ergonomic than the current flow in the quick start. Right now there's a couple of sed commands to copy and paste which I think we can improve on, just need to think about how outside of a hack script.

**Comment by vincepri** [comment]
The kubeconfig bit could be something that can be included in clusterctl which could detect if the cluster is CAPD and if we're on Mac.

**Comment by sbueringer** [comment]
Sounds reasonable, just fyi we already have very similar code in our e2e tests

**Comment by fabriziopandini** [comment]
FYI I'm ok of having tilt spinning up a kind cluster; adding some notes on top of the discussion above:
- As for tilt recommendation, the kind cluster should use a local registry for better performances. This local registry should be long lived.
- During dev cycles it happens sometime to stop tilt and restarting it whiteout deleting the kind cluster (e.g to force a reload of all the components). We should continue to support this use case

**Comment by vincepri** [comment]
> During dev cycles it happens sometime to stop tilt and restarting it whiteout deleting the kind cluster (e.g to force a reload of all the components). We should continue to support this use case

Let's provide this as an option, it would be great if we can configure to cleanup the kind cluster on exit

**Comment by fabriziopandini** [comment]
+1 to get cleanup as part of tilt down

**Comment by vincepri** [comment]
/milestone v0.4

@killianmuldoon What do you think about trying to tackle this one?

**Comment by killianmuldoon** [comment]
/assign

Will do!

**Comment by killianmuldoon** [comment]
It seems that this isn't as simple as it first appears. Tilt reads the kubeconfig on tilt up so it's not able to readily work with an environment set up as part of its internal flow. It's possible there's some way around this that I haven't come across yet. Would it be acceptable to wrap the cluster setup in `hack/tilt_with_kind.sh` and update the docs so we have an alternative way of setting this up?

**Comment by fabriziopandini** [comment]
what about having `hack/kind-up.sh` thus we are providing all the pieces, but not dictating a workflow the developers should align to

**Comment by killianmuldoon** [comment]
> what about having `hack/kind-up.sh` thus we are providing all the pieces, but not dictating a workflow the developers should align to

Does the script in #5232 seem like the right approach?

**Comment by fabriziopandini** [comment]
#5232 is really similar to the script I'm using, so this will be great for me.
However let's wait for @vincepri and @sbueringer opinion before changing direction. In case we go for it, +1 to advice the new script in the docs

**Comment by sbueringer** [comment]
Script looks okay to me.

What impact does the local registry have? (do we use it? how? do we have to change something elsewhere because of it?)

I'm not sure about using it in quickstart. I like the current version of the quickstart, because it's very transparent about waht we require from kind (kind cluster + mount). The script looks like we require way more than that.

**Comment by stmcginnis** [comment]
I agree it's useful to have the quickstart be transparent about the setup. It may be good to keep the instructions mostly as-is so it helps explain what needs to be done, but then reference the script as a convenient way to accomplish those steps.

**Comment by killianmuldoon** [comment]
@sbueringer with tilt or a quickstart  CAPD cluster it's useful to have the local registry as otherwise you're pulling from cloud registries which may - like the default docker - have pull limits.

**Comment by sbueringer** [comment]
@killianmuldoon I know. But looking at the Kind documentation I think we have to change a bit more to actually use the registry. Or is it some kind of automatic mirror?

**Comment by killianmuldoon** [comment]
You can configure the local registry as an automatic mirror, but the scope of that is OS specific and out of scope. With this setup the basic capi images are loaded into the local cluster. Other images will have to be pushed to the cluster in order to be used across workload clusters.

**Comment by sbueringer** [comment]
@killianmuldoon So the registry will be deployed, but unused by tilt, right?

**Comment by killianmuldoon** [comment]
Tilt will automatically detect a registry and use it instead of using kind load (assuming the registry is detected) - https://docs.tilt.dev/choosing_clusters.html#kind

**Comment by sbueringer** [comment]
> Tilt will automatically detect a registry and use it instead of using kind load (assuming the registry is detected) - https://docs.tilt.dev/choosing_clusters.html#kind

Ah thx, interesting info.

**Comment by sbueringer** [comment]
@killianmuldoon fixed by https://github.com/kubernetes-sigs/cluster-api/pull/5232 ?

**Comment by killianmuldoon** [comment]
Re-reading this I think I should update the docs with a new PR to point to the script.
