### ISSUE TITLE
Integrate MachineHealthChecks with ClusterClasses and Managed Topologies

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5205]
**User Story**

As a user I would like to be able to use the MachineHealthCheck controller along with Clusters created and managed using ClusterClass.

**Detailed Description**

MachineHealthChecks are likely to interact with Machines created in a Cluster through ClusterClass and Managed topologies in a number of ways. This issue is for discussion of the expected behaviour of MachineHealthChecks in a managed cluster, the identification of unwanted interactions and issues that may appear and any resolution of those issues and decisions on the defined behaviour of these interactions.

/kind feature

**Comment by sbueringer** [comment]
@killianmuldoon Sounds very similar to: https://github.com/kubernetes-sigs/cluster-api/issues/5125

**Comment by killianmuldoon** [comment]
That's right 👍  I'll close this and work from there.

**Comment by killianmuldoon** [comment]
duplicate of #5125
