### ISSUE TITLE
Add Cluster name as printer column on non core types

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5208]
As per  https://github.com/kubernetes-sigs/cluster-api/pull/5202#issuecomment-912957671 we should add a Cluster column for  types in KCP, CABPK, extensions, CAPD.

Whenever the information is not available as explicit field, it should be possible to get this information from labels (see e.g. https://github.com/kubernetes-sigs/cluster-api/issues/5198#issuecomment-912717888 for an example of how this can be achived)

/kind feature

**Comment by fabriziopandini** [comment]
/milestone v0.4

Adding in the milestone given that this will nicely complement changes introduced by #5202

**Comment by budhirajamadhav** [comment]
Can I take this up?
/assign

**Comment by fabriziopandini** [comment]
/lifecycle active
Sure!

**Comment by budhirajamadhav** [comment]
Hi @fabriziopandini I saw how vinspri added spec.clusterName on object listing in #5202 , Can you please tell me in where can I find those files to do the same for KCP, CABPK, extensions, CAPD. And pardon if it's a silly doubt, I'm just new here!

**Comment by sbueringer** [comment]
Hi @budhirajamadhav ,
no problem.

KCP: controlplane/kubeadm/api/v1alpha4
BPK: bootstrap/kubeadm/api/v1alpha4
extensions: exp/api/v1alpha4
CAPD: test/infrastructure/docker/api/v1alpha4 + test/infrastructure/docker/exp/api/v1alpha4

You can also take a look at: https://github.com/kubernetes-sigs/cluster-api/pull/5180/files 
(most of the types have also been modified in #5180)

Note: As fabrizio wrote. In some cases you can just use the clusterName field from the resources, in other cases they won't have a field and you have to use the `cluster.x-k8s.io/cluster-name` label instead (as described in https://github.com/kubernetes-sigs/cluster-api/issues/5198#issuecomment-912717888).

**Comment by budhirajamadhav** [comment]
Hey @sbueringer 
I added cluster name to all the non core types explicitly like this (image).
![image.png](https://user-images.githubusercontent.com/73742540/134162621-34a9f035-5f98-42a9-897d-92869a597f64.png)
But as @fabriziopandini mentioned in the comment that when the information is not available as explicit field, it should be possible to get this information from labels. So, how will I get to know the info(spec.clusterName) is available in the jsonPath or not? Is that json available to us?

**Comment by sbueringer** [comment]
@budhirajamadhav You have to add the column by adding a Go tag to the corresponding type. You can take a look at that type if it contains the `clusterName`.

For example: Machine
columns are defined here: https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1beta1/machine_types.go#L239-L244
when you go through the struct you can find the `clusterName` field here: https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1beta1/machine_types.go#L60


Another approach is to deploy the Quickstart with CAPD/Docker (https://cluster-api.sigs.k8s.io/user/quick-start.html) and take a look at the resources.

**Comment by sbueringer** [comment]
One additional hint (based on https://github.com/kubernetes-sigs/cluster-api/issues/5290). Let's add cluster as the first column.

Please let me know if there's something I can do to help :)

**Comment by budhirajamadhav** [comment]
HI @sbueringer my work is almost done but check this a bit, when the clusterName is not available as an explicit field, like it says in the [comment](https://github.com/kubernetes-sigs/cluster-api/issues/5198#issuecomment-912717888) **"The prior art"** , do I have to add a const like this? 
![image](https://user-images.githubusercontent.com/73742540/134464958-5a74c205-82d5-492e-b47b-c158c3b68f63.png)

**Comment by sbueringer** [comment]
@budhirajamadhav Almost.

You have to add the following annotation on the type:
```
// +kubebuilder:printcolumn:name="Cluster",type="string",JSONPath=".metadata.labels['machine\\.cluster\\.x-k8s\\.io/role']",description="Cluster"
```

Then you can run `make generate-manifests` and the make target will update the CRD accordingly.

This also applies to cases where the clusterName is part of the spec. You always have to specify does columns on the Go types, the CRDs are then updated by `generate-manifests`.

**Comment by budhirajamadhav** [comment]
Ah, Much thanks @sbueringer 
Sorry, I didn't knew CRDs are updated like that. Still new to this😅

**Comment by sbueringer** [comment]
@budhirajamadhav No worries, there's no way to "just know" this :)
