### ISSUE TITLE
Use .Index func consistently when building field.Paths

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5216]
In our webhooks we often use `field.NewPath` to build paths to describe the location of validation errors. I recently found out that there's an `Index` func which we can use to add the array index. Currently, we often use string concatenation to produce something similar.

Example:

Current implementation:
```golang
field.NewPath("spec", "workers", fmt.Sprintf("machineDeployments[%v]", i), "template", "infrastructure")
```

Implementation with `Index`:
```golang
field.NewPath("spec", "workers", "machineDeployments").Index(i).Child("template", "infrastructure")
```

It's a minor problem, but I think it would be great if we can use `Index` consistently in all our webhooks.

**Environment:**

- Cluster-api version: latest

/kind cleanup
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by anusha94** [comment]
/assign

@sbueringer I can work on this!
