### ISSUE TITLE
Support Kubernetes 1.12 client libraries

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/cluster-api#522]
We would like to use these apis from a project uses Kubernetes 1.12 client-go etc. Can this project use Kubernetes 1.12 client libraries, now that kubebuilder migration is complete?

Does it require special support from Kubebuilder ? or this can be done directly at this project?

cc: @pwittrock @roberthbailey

**Comment by roberthbailey** [comment]
Which APIs are you referring to?

**Comment by tamalsaha** [comment]
https://github.com/kubernetes-sigs/cluster-api/tree/master/pkg/client

**Comment by roberthbailey** [comment]
The new code isn't using those; it's using the dynamic client instead. I updated some of the older code to stop using them but not all of it. I was considering them deprecated and only around until we get rid of all usages of them.

**Comment by roberthbailey** [comment]
@tamalsaha - was this addressed by https://github.com/kubernetes-sigs/cluster-api/pull/589? That PR re-introduced typed clients.

**Comment by tamalsaha** [comment]
#589 solves.
