### ISSUE TITLE
Discussion on operations allowed while a managed cluster is being upgraded

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#5222]
This issue is meant to be an ongoing discussion/brainstorming on the list of operations that are allowed/disallowed during a cluster upgrade.

A non-exhaustive list of operations to consider:
* Scaling up/down Control Plane
* Modifying Control Plane (changing infrastructure templates) 
* Scaling up/down MachineDeployments
* Modifying MachineDeployments (changing the bootstrap or infrastructure templates)
* Create new machine deployments

/kind design
/area topology

**Comment by ykakarap** [comment]
This issue supersedes https://github.com/kubernetes-sigs/cluster-api/issues/5183.

**Comment by sbueringer** [comment]
@ykakarap Do you mean during a control-plane upgrade?

**Comment by ykakarap** [comment]
@sbueringer mostly yes. However lets use this to look into any considerations to make while machine deployments are upgrading.

**Comment by vincepri** [comment]
Let's run some tests around the above points and figure out if this is something we need to tackle today or later.

/milestone v0.4

**Comment by ykakarap** [comment]
/assign 
to run some tests around the above points.

**Comment by fabriziopandini** [comment]
I have made some investigations on this point (with focus on KCP, but I think the same apply to other control plane providers), and the TL;DR; is:

1. The system seems already equipped to manage concurrent changes on CP, on workers or both. 
2. There is a possible risk that we are creating machines with K8s version > than K8s version in the CP (both in managed topologies or in unmanaged clusters).
3. In managed topologies there is room for limiting the user the possibility to do concurrent operations, thus making operations more straight forward/predictable. But I'm not sure this is worth to do

More in detail

1. Both KCP and MD are designed to reconcile to the desired state, no matter of the diff between current and desired. This makes them resilient to multiple changes to the same object. Also, in case both KCP and MD are changing concurrently, the only dependency between the two is a stable API endpoint, and KCP is designed to ensure this.
   
2. As of today nothing prevents the user to create machines with K8s version > than K8s version in the CP; this risk exists also in ClusterClass given that during the first phase of an upgrade topology.version is greater than CP min version (and new MD uses topology.version). IMO there are two options to explore here (not exclusive):

   1. Make ClusterClass to delay creation of new MD when this condition is detected 
   2. Make Machine (or most probably CABPK) to detect this condition and keep the machine creation on hold. However this requires to surface CP version at Cluster level

3. I'm personally -1 to implement this option. We can try to prevent multiple changes to the same object or concurrent operations between KCP & MD, but the truth is this can't prevent this to happen for external factors, like MHC, autoscales or changes to ClusterClasses. Thus I'm leaning to not introduce those limitation that might impact users and give us the false security that concurrent operations could not happen.

@vincepri @ykakarap @sbueringer opinions

**Comment by fabriziopandini** [comment]
/close
I'm working with @chrischdi to open an issue to enforce validation on version fields that will solve this issue as well
