### ISSUE TITLE
ClusterClass template name *only* update triggers reconcilliation

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5227]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Reproduced in CAPD but assumed to be an issue in the ClusterClass controller:

1) Create a clusterclass that includes two identical DockerMachineTemplates with different names e.g. template1,template2
2) Create a cluster that uses the clusterClass from (1)
3) Wait until the cluster has been reconciled fully i.e. machines and nodes up and running
4) Edit the clusterclass to change the template under workers.machineDeployments[*].template.infrastructure.ref.name e.g.
from template1 to template 2
5) View clusterctl describe cluster or similar to see machine recreation happen based on the name change, even though the spec of the machines is identical.

**What did you expect to happen:**
Machine reconciliation should not occur unless the underlying objects - in this case DockerMachineTemplates - are actually different. Name-only changes shouldn't trigger rolling out of new MachineDeployments.

**Environment:**

- Cluster-api version: c50aa1f

/kind bug

**Comment by killianmuldoon** [comment]
@fabriziopandini @sbueringer Am I right in saying the above is a bug that should be fixed?

**Comment by sbueringer** [comment]
I think yes. We can pair on debugging this by running it through the debugger if you want (but next week)

**Comment by sbueringer** [comment]
@killianmuldoon and I debugged it and the rollout is triggered because of metadata changes
```json
{
  "metadata": {
    "annotations": {
      "cluster.x-k8s.io/cloned-from-name": "my-cluster-md-0-2",
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"infrastructure.cluster.x-k8s.io/v1alpha4\",\"kind\":\"DockerMachineTemplate\",\"metadata\":{\"annotations\":{},\"name\":\"my-cluster-md-0-2\",\"namespace\":\"default\"},\"spec\":{\"template\":{\"spec\":{}}}}\n"
    }
  }
}
```

So I think it's fine for now. I want to open an issue for consistent metadata (label/annotations) rollout anyway. I'll link it here and then close the current issue

**Comment by fabriziopandini** [comment]
> I want to open an issue for consistent metadata (label/annotations) rollout anyway. I'll link it here and then close the current issue

I have still to investigate this, but it seems to me that we should not trigger rollout to align annotations or labels. However this has different nuances in KCP (and possible other control plane providers) and machine deployments, and I need some time to dig into...

**Comment by sbueringer** [comment]
@fabriziopandini My plan for the issue was mostly to investigate how we currently propagate labels/annotations on KCP/MD/MS to MS/M InfrastructureMachineTemplate, BootstrapConfigTemplate, InfrastructureMachine and BootstrapConfig and then start a discussion in the issue if the current state is as intended or what we want to change and when.
