### ISSUE TITLE
Audit APIs based on Kubernetes API conventions

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5239]
I think it would be great if we take a closer at our APIs if they comply to the API conventions (to potentially fix them before v1beta1 (TBD)).

I'm not sure how far we want to go but in my opinion it would be good to at least comply to [optional-vs-required](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required). Especially because we refer to them in our ClusterClass proposal: https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/202105256-cluster-class-and-managed-topologies.md#notes-on-template---object-reconciliation

Examples for optional vs required:
* https://github.com/kubernetes-sigs/cluster-api/issues/5233
* there are a lot of other examples in our APIs like:
    *  optional fields (`+optional`) which are not pointers
    *  required fields which have omitempty
    * ...

/kind cleanup
/area api

**Comment by anusha94** [comment]
@sbueringer I'd like to help with this. Does having separate PRs each for core CAPI, CAPD, KCP.... etc make sense?

**Comment by sbueringer** [comment]
@anusha94 I think it would be good to start with a PR for the CAPI "core" types (in api/v1alpha4) for optional vs required and then let's see where that leads us (i.e. how disruptive the change will be). 

Note: There's currently a PR open for v1beta1 types (https://github.com/kubernetes-sigs/cluster-api/pull/5248). I'm not sure how fast we will merge it but I think the "optional vs required" PR has to be rebased after #5248 has been merged and the changes have to be applied *only* on the v1beta1 types.

**Comment by randomvariable** [comment]
I'm wondering about `+optional` . Does it actually do anything if the packages aren't marked with the kubebuilder:validation:Required annotation at the top level. Been considering actually doing that in CAPA, or otherwise removing the `+optional`s

**Comment by sbueringer** [comment]
> I'm wondering about `+optional` . Does it actually do anything if the packages aren't marked with the `// +kubebuilder:validation:Required` annotation at the top level? Been considering actually doing that in CAPA, or otherwise removing the `+optional`s

either +optional, or the field being a pointer or omitempty will trigger the field not being required in the CRD

**Comment by randomvariable** [comment]
Reading https://book.kubebuilder.io/reference/markers/crd-validation.html, it says for `+optional`:

`specifies that this field is optional, if fields are required by default.` , but we haven't set required by default, so I think the actual current behaviour is everything is optional in the CRD unless marked as required. This came to the fore in CAPA recently where stuff we thought was required wasn't actually. Also from an OpenAPIv3 perspective, "optional" is just the absence of required.

For things which are pointers, I think what you actually want is `// +nullable`

**Comment by vincepri** [comment]
IIRC everything is required unless `+optional` is set. The `omitempty` field on json is also important when something is optional to make sure the json encoder doesn't send the data to the API server in case of defaults with non-pointer types.

**Comment by randomvariable** [comment]
> IIRC everything is required unless +optional is set

I thought so too, but that turned out not to be the case, requiring https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2740/files for example. We're considering getting the behaviour we thought we had by marking the API package with the validation required annotation.

**Comment by randomvariable** [comment]
Thanks for the clarification. Next question considering API conventions. What are we doing about Phase?

**Comment by vincepri** [comment]
We could choose to remove the field in v1beta1, but I'd rather keep our compatibility promise with v1alpha4. It's mostly informative, I haven't heard any feedback that's causing issues though. What do you think?

**Comment by randomvariable** [comment]
>  I'd rather keep our compatibility promise with v1alpha4. 's mostly informative, I haven't heard any feedback that's causing issues though

That makes sense, though I'm keen to have to prevent any new consumers of it appearing. Should we mark it as deprecated in the field comments?

**Comment by sbueringer** [comment]
I might be wrong but I explicitly tested `either +optional, or the field being a pointer or omitempty will trigger the field not being required in the CRD` locally and to me it looks like it works that way.

**Comment by randomvariable** [comment]
> I might be wrong but I explicitly tested either +optional, or the field being a pointer or omitempty will trigger the field not being required in the CRD/OpenAPI schema locally and to me it looks like it works that way.

I think you're right and I'm wrong and tracked down the combination of things that meant we ended up with optional fields where we didn't want in CAPA.

**Comment by sbueringer** [comment]
Note regarding your comment above: I think `kubebuilder:validation:Optional` and `+optional` or not the same. I don't know how kubebuilder tags interact with the behavior of `+optional`, pointers and `omitempty`.

**Comment by sbueringer** [comment]
I'm not sure if nullable does what you want. It's a OpenAPI Schema v3 construct to essentially modify your current type to be `type or null` (e.g. int or null).
Doc: https://swagger.io/docs/specification/data-models/data-types/?sbsearch=nullable

Looks like we're currently not using it in the core repo and it's also not mentioned in API conventions.

**Comment by fabriziopandini** [comment]
@sbueringer is there work left on this issue?

**Comment by sbueringer** [comment]
@fabriziopandini If we only look at optional vs required it should be done with my 2 open PRs. But I only checked for consistency. I didnt go over all fields to check if they should be optional or required

**Comment by fabriziopandini** [comment]
/close
As per comment above
