### ISSUE TITLE
Consistent metadata propagation behaviour

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5240]
I'm not entirely sure how it should be, but let's discuss in this issue how we want metadata to propagate and then adjust the implementation accordingly.

Right now the metadata is propagated as follows: ( from => to)

###  KubeadmControlPlane

.labels =>
.annotations =>
.spec.machineTemplate.metadata.labels => Machine.labels, InfraMachine.labels, KubeadmConfig.labels
.spec.machineTemplate.metadata.annotations => Machine.annotations, InfraMachine.annotations, KubeadmConfig.annotations

###  MachineDeployment

.labels =>
.annotations => MS.annotations
.spec.template.metadata.labels => MS.labels, MS.spec.template.metadata.labels
.spec.template.metadata.annotations => MS.spec.template.metadata.annotations

### MachineSet

 .labels =>
.annotations =>
.spec.template.metadata.labels => Machine.labels, InfraMachine.labels, KubeadmConfig.labels
.spec.template.metadata.annotations => Machine.annotations, InfraMachine.annotations

/kind bug

**Comment by vincepri** [comment]
/milestone Next

Is this a bug?

**Comment by schrej** [comment]
We're relying on the `.spec.template.metadata` for `MachineDeployment -> MachineSet -> Machine/InfraMachine` and `KubeadmControlPlane -> Machine/InfraMachine`, so we would definitely like to keep that behavior.

In my opinion it would also be good to extend `MachineDeployment -> MachineSet` to also copy over labels. Otherwise there is no way to set labels on those MachineSets when using Deployments.

cc @MaxRink

**Comment by sbueringer** [comment]
> @sbueringer I think `DockerMachine` should be `InfraMachine` for the KubeadmControlPlane, shouldn't it?
Yes, thx, fixed.

My opinion on the situation:

KCP => lgtm

> MD.annotations => MS.annotations
I think it's strange to propagate top-level MD.annotations to MS.annotations

> MD.spec.template.metadata.labels => MS.labels, MS.spec.template.metadata.labels
> MD.spec.template.metadata.annotations => MS.spec.template.metadata.annotations

It think we should also propagate `MD.spec.template.metadata.annotations` to `MS.annotations`

(I would rather propagate `MD.spec.template.metadata.{labels,annotations}` then top-level `MD.{labels.annotations}`. I don't think top-level metadata should be propagated at all)


> MS.spec.template.metadata.labels => Machine.labels, InfraMachine.labels, KubeadmConfig.labels
> MS.spec.template.metadata.annotations => Machine.annotations, InfraMachine.annotations

Seems more consistent to me to also propagate `MS.spec.template.metadata.annotations` to `KubeadmConfig.annotations`

**Comment by schrej** [comment]
> It think we should also propagate MD.spec.template.metadata.annotations to MS.annotations
> Seems more consistent to me to also propagate MS.spec.template.metadata.annotations to KubeadmConfig.annotations

I think we should always either propagate both, annotations and labels, or neither. It's not very intuitive if onlye one is propagated.

**Comment by sbueringer** [comment]
> > It think we should also propagate MD.spec.template.metadata.annotations to MS.annotations
> > Seems more consistent to me to also propagate MS.spec.template.metadata.annotations to KubeadmConfig.annotations
> 
> I think we should always either propagate both, annotations and labels, or neither. It's not very intuitive (nor logical) if only one is propagated.

100% agree. Basically my comment comes down to: "let's always propagate both and let's stop propagating top-level MD labels"

**Comment by randomvariable** [comment]
> I don't think top-level metadata should be propagated at all) 

I agree with this. Me and @sedefsavas were looking at this the other day and were pretty confused about what gets propagated and doesn't.

**Comment by fabriziopandini** [comment]
+1 for consistency
however, for MachineDeployments IMO top level label/annotations should go to MS, template label/annotations should go to machines.

**Comment by randomvariable** [comment]
Discussing with @schrej , @vincepri and @sbueringer in Slack, the conclusions we've reached is that:

MDs should behave like appsv1/Deployment
ReplicaSets and KCP should behave like ReplicaSets (or appsv1/StatefulSet in the case of KCP).

In which case, the behaviour is, where d = appsv1/deployment and r = replicaset

d.annotations => r.annotations
d.labels => nil
d.spec.template.annotations => d.spec.template.annotations
d.spec.template.labels => r.labels & r.spec.template.labels

This is in https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/sync.go#L146-L150 and https://github.com/kubernetes/kubernetes/blob/38746752af6d0ec955f4511a727da37347da3b92/pkg/controller/deployment/util/deployment_util.go#L232 with a comment here: https://github.com/kubernetes/kubernetes/issues/92896#issuecomment-655540826

From this, it would appear the outstanding task is to propagate MS.spec.template.metadata.annotations to KubeadmConfig.meta.annotations if we want to be consistent.

**Comment by randomvariable** [comment]
There is an outstanding question about InfraMachineTemplate.Spec.Template.Meta and KubeadmConfigTemplate.Spec.Template.Meta . Should all providers implement this, what is the merge behaviour, and who should when there's conflict?

**Comment by sbueringer** [comment]
/reopen

The current implementation just takes everything in `.spec.template` of InfraMachineTemplate.Spec.Template.Meta and KubeadmConfigTemplate.Spec.Template.Meta and overwrites it with propagated metadata: https://github.com/kubernetes-sigs/cluster-api/blob/9fdf087e91f6b4ffb5daf5366b0b1927a884d7a9/controllers/external/util.go#L144

Neither KubeadmConfigTemplate nor DockerMachineTemplate has .Spec.Template.Meta fields

**Comment by randomvariable** [comment]
The same is true for the other infra providers, so we should add something to the v1beta1 docs?

**Comment by sbueringer** [comment]
> The same is true for the other infra providers, so we should add something to the v1beta1 docs?

In wonder if/where we have guidance how the templates should be implemented.

**Comment by randomvariable** [comment]
> In wonder if/where we have guidance how the templates should be implemented.

I'll have a look and knock something up.

**Comment by fabriziopandini** [comment]
@sbueringer I see a couple of PR merged, is there something left on this issue or can we close?

**Comment by sbueringer** [comment]
@fabriziopandini I think the following is open:
* missing documentation that we're propagating .template.metadata of InfrastructureMachineTemplates and BootstrapConfigTemplates
    * we recommended in the v1alpha4=>v1beta1 migration doc that template resources should have template.metadata:
    > Ensure your template resources support template.meta fields. Refer to the cluster and machine provider contract docs for more information. This is not required, but is recommended for consistency across the infrastructure providers as Cluster API graduates and opens up use cases where coordinating controllers can use labels and annotations from template infrastructure resources to do external provisioning or provide configuration information, e.g. IPAM support for vSphere / bare-metal.
    > https://cluster-api.sigs.k8s.io/developer/providers/v1alpha4-to-v1beta1.html#utils-and-other
* KubeadmConfigTemplateResource does not have ObjectMeta vs. the documentation in our book: https://cluster-api.sigs.k8s.io/developer/providers/bootstrap.html#bootstraptemplate-resources

WDYT

**Comment by killianmuldoon** [comment]
/assign

I'll take a look at closing out the last couple of issues related to this.

**Comment by killianmuldoon** [comment]
@schrej Is there something specific outstanding on this issue we should tackle?

**Comment by schrej** [comment]
Oh sorry, just saw your misspelled lifecycle command and missed the PR.

/close

**Comment by killianmuldoon** [comment]
I didn't even notice that until now 😆
