### ISSUE TITLE
Add conversion webhooks to CAPD DockerMachine

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#5256]
**User Story**

As a user I would like to automatically convert DockerMachine between different versions of ClusterAPI. Currently there are no automatic webhooks registered for converting DockerMachine objects in ClusterAPI.

**Detailed Description**

This issue can be closed after all of the tasks to create a working webhook for DockerMachine are in place for a conversion from v1alpha3 to v1alpha4 and, as the release comes in, v1beta1.

/kind feature

**Comment by sbueringer** [comment]
@ykakarap If I saw correctly it's implemented in: https://github.com/kubernetes-sigs/cluster-api/pull/5248/files

**Comment by sbueringer** [comment]
But looks like we don't have a conversion_test.go (even after the PR)

**Comment by ykakarap** [comment]
@sbueringer Yes, looks like the updated #5248 now adds these conversions.

I will use this issue to open a PR to add conversion_test.go for v1alpha3 and v1alpha4 types.
