### ISSUE TITLE
Handle Mac specific kubeconfig requirements for CAPD in clusterctl

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5263]
**User Story**

As a user I would like to be able to use the quickstart on Mac without needing to make changes to the kubeconfig file manually. 

**Detailed Description**
Currently the quickstart warns Mac users that they will need to make specific changes to their kubeconfig file in order to access the workload cluster when using CAPD. A page explaining the changes is here https://cluster-api.sigs.k8s.io/clusterctl/developers.html#additional-notes-for-the-docker-provider

clusterctl could handle these changes automatically by detecting the OS when it's running ` clusterctl get kubeconfig `

This would make the quickstart more straightforward, and get rid of a pitfall in the current quick start guide.
/kind feature

**Comment by sbueringer** [comment]
The only controversial point I can see about this, is how we get the Docker port. We added a new go module to avoid the dependency to the Docker client in our main Go module. So I guess in case of clsuterctl we would run a `os.Exec` for the `docker port` command?

**Comment by killianmuldoon** [comment]
I think for Mac it would be incredibly difficult to navigate Docker Desktop to try to recreate what the CLI does to get the port mappings, so we're probably left with a raw call to the docker CLI like you said. This isn't a great pattern - it will do the job here, but at at cost.

clusterctl has a cmd package for wrapping exec commands, but as far as I can see we don't actually use it anywhere - is it on a path to deprecation?

**Comment by killianmuldoon** [comment]
I think for Mac it would be incredibly difficult to navigate Docker Desktop to try to recreate what the CLI does to get the port mappings, so we're probably left with a raw call to the docker CLI like you said. This isn't a great pattern - it will do the job here, but at at cost.

clusterctl has a cmd package for wrapping exec commands, but as far as I can see we don't actually use it anywhere - is it on a path to deprecation?

**Comment by sbueringer** [comment]
Not sure about the cmd package.

For reference, that's how we did it in our e2e tests before migrating to the Rest API / docker lib:
https://github.com/kubernetes-sigs/cluster-api/blob/release-0.3/test/framework/cluster_proxy.go#L291-L316

**Comment by fabriziopandini** [comment]
I understand this will make quick start easier, but I'm so so with the idea of having provider specific code in clusterctl.
Also, fyi kind is already doing something similar but I don't remember implementation details but I can help to search for it if it can help.

**Comment by killianmuldoon** [comment]
Agreed that this might be a step further than we'd like to go to make the quick start a little easier. It looks to me that Kind is using provider specific code i.e. they have a docker and a podman package, and the docker package has this flow: https://github.com/kubernetes-sigs/kind/blob/4910c3e221a858e68e29f9494170a38e1c4e8b80/pkg/cluster/internal/providers/docker/provider.go#L159

**Comment by killianmuldoon** [comment]
The workaround for this for most users is probably just to use `kind` to get the kubeconfig - this is changed in documentation in #7392. I think we can close this issue (as it's about the quickstart on Docker only) if that change merges.

**Comment by killianmuldoon** [comment]
/close
#7392 provides a workaround for this
