### ISSUE TITLE
Add conversion for MachinePool

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5265]
Let's add the following for MachinePools (after #5248)
* conversion.go in v1alpha4 package
* conversion fuzzy test
* webhook conversion patches in config/

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by CecileRobertMichon** [comment]
should be after #5248

**Comment by sbueringer** [comment]
> should be after #5248

+1, I fixed the description
