### ISSUE TITLE
clusterctl v1beta1 should allow upgrades starting from v1alpha3

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5269]
**Detailed Description**

Considering the v1beta1 does not introduces breaking changes from v1alpha4, and that we want to allow a smooth migration towards v1beta1, then clusterctl v1beta1 should allow upgrades starting from v1alpha3

It is also required to have v1alpha3 --> v1beta1 and v1alpha4 --> v1beta1 (one of those is already there, but not working after breaking changes for v1beta1)

**Anything else you would like to add:**

The change requires to add v1alpha3 and v1alpha4 to allowed contracts in 

https://github.com/kubernetes-sigs/cluster-api/blob/d9db8807341d7666ed1f1c6d4a4ce0497295ac2f/cmd/clusterctl/client/upgrade.go#L55-L58

same for upgrade apply.

The E2E requires a dedicated prow job similar to https://github.com/kubernetes/test-infra/blob/f234f533b3e2ff5694e35b7a0c4466b4c7292042/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-main.yaml#L25-L59

But with: 
- GINKGO_FOCUS targeting clusterctl upgrades (instead of GINKGO_SKIP)
- INIT_WITH_BINARY and INIT_WITH_KUBERNETES_VERSION

Most probably, also https://github.com/kubernetes-sigs/cluster-api/blob/7084de351638b42fddd0633a4669f435e9c9ec68/test/e2e/clusterctl_upgrade.go#L162-L165 should be changed to allow to pick a version from a specific release series (vs picking oldest).

/kind feature

**Comment by sbueringer** [comment]
Just fyi, testgrid looks like all tests are still consistently successful.
