### ISSUE TITLE
Delete relevant machines when machineset be deleted

### ISSUE THREAD

**Issue by Lion-Wei** [kubernetes-sigs/cluster-api#528]
When we delete machineset, the related machines can't be deleted automatically. 

I think it would be better if we can delete related machines when machineSet be deleted.

**Comment by Lion-Wei** [comment]
xref: https://github.com/kubernetes-sigs/cluster-api/pull/513

**Comment by roberthbailey** [comment]
Deleting a machineset *should* delete all of the machines that were created as part of the set. If that isn't happening, it's a bug and should be fixed (and a unit test added).

**Comment by chuckha** [comment]
I cannot reproduce this. Machine sets and deployments delete nodes as expected. The order is simply the oldest one first, but that's a different issue entirely.

Please reopen if I've missed a crucial piece of this ticket.

/close
