### ISSUE TITLE
Update v1alpha3->alpha4 conversion guide with recent contract revisions

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5282]
**Detailed Description**
This task involves updating the CAPI book's v1alpha3-v1alpha4 conversion guide to include recent changes in the CAPI contract.

As per https://github.com/kubernetes-sigs/cluster-api/pull/5264#issuecomment-923992674 changes made over the course of a release - e.g. clusterClass motivated changes to the CAPI contract made during v1alpha4 - should be included in the correct conversion documentation in the CAPI book where they impact providers.

 Two specific changes, 
>  #4949 on v1alpha3 -> v1alpha4 doc + the need of implementing InfrastructureClusterTemplate or ControlPlaneTemplate for ClusterClass **support**

are highlighted here, but there may be more to document on reviewing the CAPI changes over the full lifetime of v1apha4.

https://cluster-api.sigs.k8s.io/developer/providers/v1alpha3-to-v1alpha4.html

**Comment by sbueringer** [comment]
Probably makes sense to cherry-pick to release-0.4 for the release-0.4 book

**Comment by vincepri** [comment]
@killianmuldoon Are you able to open a PR to tackle the above?
