### ISSUE TITLE
Provider plugins for clusterctl

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#529]
In the course of building out https://github.com/kubernetes-sigs/cluster-api-provider-aws,
we've ended up with another tool `clusterawsadm` to handle AWS specific tasks.

https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/184 adds the ability
to get the console logs for a given machine, and now includes kube-client to do so.

It'd probably be ideal if there could be a common plugin interface like [kubectl has](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) to add this functionality.

**Comment by randomvariable** [comment]
Thanks @vincepri . More likely, been thinking more since I posted this that clusterctl should be a kubectl plugin in and of itself.

**Comment by timothysc** [comment]
closing this issue in favor of clusterctl v2
