### ISSUE TITLE
MachineSet controller listens for Machine resources.

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#53]
_From @p0lyn0mial on March 8, 2018 14:40_

The current implementation of `MachineSet` controller watches only the desired state of the cluster. This approach is not sufficient as there are other actors in the system that can easily change the current state (e.g. delete/add a `Machine`) of the cluster. Thus adding event handlers for `Machines` to our `MachineSet` along with appropriate handlers (requeue) seems to be valid approach.

See also:
#535
https://github.com/kubernetes/kube-deploy/pull/620#discussion_r172772002
https://github.com/kubernetes/community/blob/master/contributors/devel/controllers.md

_Copied from original issue: kubernetes/kube-deploy#643_

**Comment by rsdcastro** [comment]
_From @p0lyn0mial on March 8, 2018 14:40_

/cc @rsdcastro @mvladev

**Comment by roberthbailey** [comment]
@k4leung4 - can you provide an update on the current status of this issue?

**Comment by k4leung4** [comment]
this is done
/close

**Comment by k4leung4** [comment]
PR #186
