### ISSUE TITLE
Add personas to the book

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#5306]
**Detailed Description**

In the process of reviewing #4283, @enxebre suggested clarifying the personas, and it looks like there's a few I've been commonly using in CAEPs across repos which aren't in the book at  https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/user/personas.md which should probably be added

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind docs

**Comment by vincepri** [comment]
Closing this for now, please reopen if there are volunteers to tackle this bit

/close
