### ISSUE TITLE
Extend usage of the contract package

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5309]
During the work for ClusterClass we started encoding the Cluster API contract as a set of golang types wrapping unstructured defined in https://github.com/kubernetes-sigs/cluster-api/tree/main/controllers/topology/internal/contract.

This not only provided a cleaner code in the topology controller, but it also provides a well defined, centralized representation of the Cluster API contract.

Given those positive results we should now consider if to refactor the rest of the codebase to use the contract package, thus removing all the contract related operations with unstructured spread across the codebase.

This could require to:
- Move the contract package to a different location (depending on where the cleanup will impact to)
- Extending the contract package with all the rules not yet implemented (all the rules not relevant for topology reconciliation)
- Identify and modify all the places in the codebase where we rely on the Cluster API contract assumptions (a good starting point are the "reconcincileExternal" methods in the controller, but there could be other points as well)

Note: this work could eventually be divided into a series of PRs.

/kind feature

**Comment by sbueringer** [comment]
Note: I think it's also an important consideration if we want keep the package internal or if we want to make it public.

**Comment by killianmuldoon** [comment]
Maybe it's best to move it to /internal/contract for now so we can use it across the codebase, and we can make it public in a future implementation once we have a better understanding of the API that works best.

**Comment by fabriziopandini** [comment]
+1 to keep it internal for now
/milestone v1.0

**Comment by fabriziopandini** [comment]
/remove-lifecycle stale
The package now is in a position where it can be used across all the controllers

**Comment by Jont828** [comment]
@fabriziopandini @sbueringer @killianmuldoon  I'm happy to take a look at this. Is the idea that we want to add types in [internal/contract](https://github.com/kubernetes-sigs/cluster-api/tree/main/internal/contract) for the contract listed in [Machine Infra](https://cluster-api.sigs.k8s.io/developer/providers/machine-infrastructure.html) as well as [bootstrap provider](https://cluster-api.sigs.k8s.io/developer/providers/bootstrap.html)?

**Comment by fabriziopandini** [comment]
(doing some cleanup on old issues without updates)
/close
we made good progress here, we can continue extending the adoption of the contract package as background task while we work on the code base
