### ISSUE TITLE
Create unified patching/matching library

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5316]
**User Story**

As a developer I would like a single API inside CAPI to compare and alter objects.

**Detailed Description**

With the merging of PR #5259 there are now two implementation of using json patches to match and patch objects in the CAPI codebase - one under /internal/matchers and a second under controllers/topology/internal/mergepatch. The base implementation of these functions is the same with the higher level API serving specific use cases.

Currently both of these packages are internal to different packages and can't be merged. If either or both of these packages are moved in future to be more available i.e. lifting mergepatch out of topology or making either package public, consideration should be given to merging these two packages into a single common implementation - under internal or util depending on whether the package should be treated as a public API.

/kind cleanup

**Comment by fabriziopandini** [comment]
/close
given that we are exploring to move the matcher in controller-runtime which is a better collocation for this.
See https://github.com/kubernetes-sigs/controller-runtime/pull/1364

we can eventually re-open later if this proves difficult to achieve
