### ISSUE TITLE
ClusterClass rebase

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5318]
**User Story**

As a user/operator I would like to change a ClusterClass for a specific Cluster

**Detailed Description**
Many Cluster could share the same ClusterClass; whenever I change a ClusterClass, all the Cluster align to changes.
This is powerful, but in some cases I would like to have an alternative to change Clusters in a more controller way.

A possible solution to address this issue is to allow changing the ClusterClass for an existing Cluster.  

Please note that technically the current implementation of the topology controller already supports this operation, but this is currently blocked by Cluster webhook.

In order to make this possible:
- The cluster webhook should be relaxed allowing this operation; also additional checks should be implemented in order to block if we detect that this operation violates compatibility rules.
- Proper test coverage for this use case should be provided

/kind feature

**Comment by killianmuldoon** [comment]
@ykakarap I think I'm going to be working on this - indirectly as part of #5537 . Have you made any progress yet?

**Comment by ykakarap** [comment]
@killianmuldoon Please go ahead 👍🏼 :) 
I dont think I will be able to get to this in the next few days anyway.
