### ISSUE TITLE
Consider having webhooks in a separate container within the same pod

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#5323]
We're currently bundling managers and webhooks in the same container. If the manager, for whatever reason, cannot start it might cause a chain reaction failure with all other controllers as well.

As an example: 

- Let's assume that one has a management cluster with Cluster API, CABPK, KCP, and AWS installed.
- If the Cluster API core manager fails, the other controllers might fail to retrieve any core types given that the API server won't be able to connect to the webhook server.
- The above might cause not only the other controllers to fail, but also any client that's trying to retrieve or modify objects.

/kind cleanup
/kind feature
/milestone v1.0

**Comment by sbueringer** [comment]
We're assuming a case where the manager doesn't start at all because there is some kind of error with the controller?

**Comment by fabriziopandini** [comment]
Wondering if we should address this here or if this is a controller-runtime concern to run as much services as possible (eg. run webhook even if the reconciler/controller loop is failing)

**Comment by randomvariable** [comment]
is this still a concern?

**Comment by fabriziopandini** [comment]
AFAIK we nailed down the problem to controller runtime starting sequence and we are working on an improvement there.

**Comment by vincepri** [comment]
We might however want to consider to split them up, given that's the only way to guarantee that the lifecycle of the manager and the webhook server is separate from one another. The only downside is that the cache (for the webhooks that use a client) might be duplicated.

**Comment by vincepri** [comment]
/lifecycle frozen

We should still look into this

**Comment by fabriziopandini** [comment]
/close
we can reconsider if we find out problems in the current deployment method
