### ISSUE TITLE
When control plane nodes isn't avaliable the Machine spec still reports healthy status

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api#5324]
**What steps did you take and what happened:**

Through my own mistake :facepalm:, I deleted a workload cluster machines (all the them including the control plane). My provider nodes reported in a bad state:

```
kubectl get azuremachines   
NAME                                     READY   STATE
capz-e2e-wy8d22-ha-control-plane-9kvww   false   Deleted
capz-e2e-wy8d22-ha-control-plane-9s4tw   false   Deleted
capz-e2e-wy8d22-ha-control-plane-jpbqg   false   Deleted
capz-e2e-wy8d22-ha-md-0-jvk2d            false   Deleted
capz-e2e-wy8d22-ha-md-0-ng92q            false   Deleted
capz-e2e-wy8d22-ha-md-win-6g9fj          false   Deleted
capz-e2e-wy8d22-ha-md-win-nxr7h          false   Deleted
```

but the cluster api machines reported running and healthy:

```
kubectl get machines
capz-e2e-wy8d22-ha-control-plane-5pqdq       azure:///subscriptions/b9d9436a-0c07-4fe8-b779-2c1030bd7997/resourceGroups/capz-e2e-wy8d22-ha/providers/Microsoft.Compute/virtualMachines/capz-e2e-wy8d22-ha-control-plane-jpbqg   Running   v1.22.1
capz-e2e-wy8d22-ha-control-plane-l2thk       azure:///subscriptions/b9d9436a-0c07-4fe8-b779-2c1030bd7997/resourceGroups/capz-e2e-wy8d22-ha/providers/Microsoft.Compute/virtualMachines/capz-e2e-wy8d22-ha-control-plane-9s4tw   Running   v1.22.1
capz-e2e-wy8d22-ha-control-plane-wth6r       azure:///subscriptions/b9d9436a-0c07-4fe8-b779-2c1030bd7997/resourceGroups/capz-e2e-wy8d22-ha/providers/Microsoft.Compute/virtualMachines/capz-e2e-wy8d22-ha-control-plane-9kvww   Running   v1.22.1
capz-e2e-wy8d22-ha-md-0-66dbc46bf-2rmzk      azure:///subscriptions/b9d9436a-0c07-4fe8-b779-2c1030bd7997/resourceGroups/capz-e2e-wy8d22-ha/providers/Microsoft.Compute/virtualMachines/capz-e2e-wy8d22-ha-md-0-ng92q            Running   v1.22.1
capz-e2e-wy8d22-ha-md-0-66dbc46bf-4w5ll      azure:///subscriptions/b9d9436a-0c07-4fe8-b779-2c1030bd7997/resourceGroups/capz-e2e-wy8d22-ha/providers/Microsoft.Compute/virtualMachines/capz-e2e-wy8d22-ha-md-0-jvk2d            Running   v1.22.1
capz-e2e-wy8d22-ha-md-win-59b9b95674-2qkvj   azure:///subscriptions/b9d9436a-0c07-4fe8-b779-2c1030bd7997/resourceGroups/capz-e2e-wy8d22-ha/providers/Microsoft.Compute/virtualMachines/capz-e2e-nxr7h                           Running   v1.22.1
capz-e2e-wy8d22-ha-md-win-59b9b95674-h7j74   azure:///subscriptions/b9d9436a-0c07-4fe8-b779-2c1030bd7997/resourceGroups/capz-e2e-wy8d22-ha/providers/Microsoft.Compute/virtualMachines/capz-e2e-6g9fj                           Running   v1.22.1
```

```
kubectl get machine capz-e2e-wy8d22-ha-md-win-59b9b95674-2qkvj -o json | jq .status.conditions
[
  {
    "lastTransitionTime": "2021-09-24T18:28:45Z",
    "status": "True",
    "type": "Ready"
  },
  {
    "lastTransitionTime": "2021-09-24T18:25:22Z",
    "status": "True",
    "type": "BootstrapReady"
  },
  {
    "lastTransitionTime": "2021-09-24T18:28:45Z",
    "status": "True",
    "type": "InfrastructureReady"
  },
  {
    "lastTransitionTime": "2021-09-24T19:02:22Z",
    "status": "True",
    "type": "NodeHealthy"
  }
]
````

**What did you expect to happen:**
I would expect the state from the infra specs (failed in this case) to propgate to the machine spec or atleast put into unkown state.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Looking at the logs it looks like the reason no state is set is because the cluster can't be connected to and so the loop returns early before setting the status of the machines.  

It seems in the case we could grab state from the inframachine (which has more knowledge) or it could at least put it in an unknown state since it can't verify the state via the cluster.

```
kubectl logs capi-controller-manager-7dc56b9799-gdpz8

E0924 21:17:52.686897       1 machineset_controller.go:618] controller-runtime/manager/controller/machineset "msg"="Unable to retrieve Node status" "error"="error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster \"capz-e2e-wy8d22/capz-e2e-wy8d22-ha\": Get \"https://capz-e2e-wy8d22-ha-36b8332.westus2.cloudapp.azure.com:6443/api?timeout=10s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" "name"="capz-e2e-wy8d22-ha-md-0-66dbc46bf" "namespace"="capz-e2e-wy8d22" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="MachineSet" 
```

**Environment:**

- Cluster-api version: v0.4.2
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): 1.22.1
- OS (e.g. from `/etc/os-release`):windows and ubuntu

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by Arvinderpal** [comment]
@jsturtevant I think I have reproduced this partially on my CAPD cluster. Though the behavior is a bit different: 
If I delete the underlying KCP DockerMachine:
```
kc delete dockermachine test-control-plane-zhfwv
```
Then, I do see the Machine object enter a failed state:
```
NAMESPACE   NAME                         PROVIDERID                              PHASE     VERSION   NODENAME
default     test-control-plane-5hdt6     docker:////test-control-plane-5hdt6     Failed    v1.22.0   test-control-plane-5hdt6
```
However, Ready and Available Conditions in KCP do not reflect this, while a few others do suggest that something is wrong:
```
Status:
  Conditions:
    Last Transition Time:  2021-09-14T19:28:38Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2021-09-14T19:28:33Z
    Status:                True
    Type:                  Available
    Last Transition Time:  2021-09-27T18:16:10Z
    Message:               Following machines are reporting unknown control plane status: test-control-plane-5hdt6
    Reason:                ControlPlaneComponentsUnknown
    Status:                Unknown
    Type:                  ControlPlaneComponentsHealthy
    Last Transition Time:  2021-09-27T18:16:10Z
    Message:               Following machines are reporting unknown etcd member status: test-control-plane-5hdt6
    Reason:                EtcdClusterUnknown
    Status:                Unknown
    Type:                  EtcdClusterHealthyCondition
```
Also can be seen with:
```
clusterctl  describe cluster test
NAME                                                     READY  SEVERITY  REASON                       SINCE  MESSAGE
/test                                                    True                                          12d
├─ClusterInfrastructure - DockerCluster/test             True                                          12d
├─ControlPlane - KubeadmControlPlane/test-control-plane  True                                          12d
│ └─Machine/test-control-plane-5hdt6                     True                                          12d
```

**Comment by Arvinderpal** [comment]
@jsturtevant I'd be happy to take this ticket and investigate further, but let me know if you want to take a stab. :smile:

**Comment by jsturtevant** [comment]
I wonder what the differences is between the Azure provider and capd.  

> @jsturtevant I'd be happy to take this ticket and investigate further, but let me know if you want to take a stab. smile

go for it :-)

**Comment by Arvinderpal** [comment]
Some thoughts on this.

First, directly deleting provider machine objects is likely not a good approach for removing control-plane/worker nodes. If you want to remove control-plane/worker nodes, then you should use the documented mechanisms within KCP and MD to do this. 

However, if someone were to accidentally (or intentionally) delete the provider machine objects, then CAPI should reflect this accurately. Here I think there some discussion necessary with the core maintainers of the project. 

With respect to KCP specifically (I believe this is what @CecileRobertMichon mentioned in slack), KCP controller in updateStatus() will try to connect to the workload cluster to determine the Nodes in the Ready state. Couple of scenarios I looked at: 
 * If the user deleted *all* of the provider machines objects for the control-plane nodes, then updateStatus() will get a connection error since there are no control-plane nodes left to talk to. It will return early and leave the certain KCP Status fields untouched (e.g. ReadyReplicas); thus the problem you've reported. I suspect part of the challenge here is that connection errors can have multiple culprits -- e.g. it may just be a intermittent connectivity issue. One possible approach here is to mark conditions such as Available and Ready as "Unknown" instead? This should alleviate some of he confusion. 
 * In the case of 3+ control-plane nodes, when only a subset of the underlying provider machines are deleted, I see that the CAPI Machine does report the failure, but the ReadyCondition never transitions to false -- this is likely a bug:

```
$ kc describe machine test-control-plane-249r
...
Status:
  Conditions:
    Last Transition Time:  2021-09-29T03:39:26Z
    Status:                True
    Type:                  Ready
...
  Failure Message:         Machine infrastructure resource infrastructure.cluster.x-k8s.io/v1beta1, Kind=DockerMachine with name "test-control-plane-m5dj8" has been deleted after being ready
  Failure Reason:          InvalidConfiguration
```

Of course, then there is also the MachineHealthCheck controller, but I'm not familiar with what it can do.

**Comment by CecileRobertMichon** [comment]
> One possible approach here is to mark conditions such as Available and Ready as "Unknown" instead? This should alleviate some of he confusion.

+1

**Comment by fabriziopandini** [comment]
FYI, https://github.com/kubernetes-sigs/cluster-api/pull/5434 fixed this in CAPD
As soon as the error is reported by CAPD ready condition, it bubbles up through the chain
