### ISSUE TITLE
Add a flag to decide whether to clusterctl version check

### ISSUE THREAD

**Issue by chymy** [kubernetes-sigs/cluster-api#5325]
**User Story**

As a developer/user I would like to add a flag to decide whether to `Check if clusterctl needs an upgrade "AFTER" running each command and sub-command` when I use the local depository of clusterctl

**Detailed Description**

With no connection to the outside network, when I use the local depository of clusterctl(e.g.: `clusterctl upgrade plan --config /root/local-depository/clusterctl.yaml`), after each command execution, will connect to GitHub check if clusterctl needs an upgrade "AFTER" running each command and sub-command. It’s a waste of time

**Anything else you would like to add:**
add a flag to decide whether to `Check if clusterctl needs an upgrade "AFTER" running each command and sub-command` .
https://github.com/kubernetes-sigs/cluster-api/blob/2d07978ac3540df3093208814dc1fcc8b4d0a3ab/cmd/clusterctl/cmd/root.go#L62-L76

/kind feature

**Comment by vincepri** [comment]
/milestone v1.0

@chymy This seems a good improvement, feel free to add an environment variable or something similar to skip the version check 

cc @fabriziopandini

**Comment by sbueringer** [comment]
As far as I can tell this has been implemented via: https://github.com/kubernetes-sigs/cluster-api/issues/6381

@chymy Please reopen if necessary.

/close
