### ISSUE TITLE
Cluster initialisation and add-ons

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#534]
One of the goals of the AWS provider was to be CNI agnostic, and we were expecting to
use the add-ons manifest to do this.

Right now, the add-ons manifest only gets applied after the cluster is pivoted, but
we can't pivot before networking is set up, so we've ended up hardcoding one CNI.

I will probably PR a change to move the order of the add-ons application so it gets applied
as soon as the control plane is up unless there's significant opposition.

The alternative would be to have a cluster-initialisation-addons thing, though don't really see the benefit of that.

**Comment by roberthbailey** [comment]
+1 to applying addons earlier instead of creating a separate class of addons that get applied at a different time.

**Comment by mvladev** [comment]
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/addon-manager is a good tool for this.
