### ISSUE TITLE
Add cluster name field or label to DockerMachinePool

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5340]
**User Story**

As a user/operator I would like to be able to easily figure out to which cluster a DockerMachinePool belongs.

**Detailed Description**

Usually we have either a `.spec.clusterName` field or the `cluster.x-k8s.io/cluster-name` label on resources belonging to a specific cluster. DockerMachinePool has neither.

**Anything else you would like to add:**

Q1: Should it be a field or a label? I'm not sure what the exact considerations are for that.
Q2: Who applies the label, the user who creates the resource or a controller? (if a controller: which one?)

/kind feature

**Comment by vincepri** [comment]
Shouldn't the MachinePool controller add labels to the object?

**Comment by fabriziopandini** [comment]
> Shouldn't the MachinePool controller add labels to the object?

it should, but apparently ti does not.
NOTE this implicitly also answer to Q1 (it should be a label) and to Q2 (The MachinePool controller should apply labels to MachinePool infra objects)

**Comment by anusha94** [comment]
@sbueringer can I take this up?

**Comment by sbueringer** [comment]
Can be closed like the corresponding PR. I made an error when testing the cluster label for DockerMachinePool. It already is implemented.

/close
