### ISSUE TITLE
Consider adding version information to the Cluster status

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5341]
**User Story**

As a user I would like to be able to access version information about my Cluster (topology) in the Cluster status.

**Detailed Description**

(this issue is based on the following conversation: https://github.com/kubernetes-sigs/cluster-api/pull/5292#discussion_r714000418)

We currently only have version **status** information distributed over multiple resources:
* ControlPlane: .status.version (only applies to control plane providers using version, which is mandatory for ClusterClass)
* MachineDeployments: .spec.template.spec.version in combination with the replica status fields (?)
* MachinePool: .spec.template.spec.version in combination with the replica status fields (?)

If there is demand, it might be good to add summarized version information to the Cluster.status.

The control plane version (if it exists) could be e.g. used as the source of truth for any consumer, e.g a Node that does not want to break the kube version skew policy (kubelet vs apiserver) (quoted from https://github.com/kubernetes-sigs/cluster-api/pull/5292#discussion_r714681305).

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
Are we envisioning a different status for managed and unmanaged Clusters?

**Comment by sbueringer** [comment]
> Are we envisioning a different status for managed and unmanaged Clusters?

Good question. I'm not sure, but if I'm not mistaken the version part of it can be the same for both as the other resources are "connected" the same way to the Cluster resource independent of managed/unmanaged.

**Comment by fabriziopandini** [comment]
/remove-lifecycle stale
this could be relevant also for https://github.com/kubernetes-sigs/cluster-api/issues/5222#issuecomment-943422381 (option 2)

**Comment by fabriziopandini** [comment]
(doing some cleanup on old issues without updates)
/close
unfortunately, no one is picking up the task. the thread will remain available for future reference
