### ISSUE TITLE
Possible improvements for clusterctl describe

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5346]
A couple of possible improvements for clusterctl describe

- ~~`--show-conditions` should allow for showing Cluster conditions as well~~
- ~~there should be an option to show MachineSets~~
- `--disable-grouping` (default false) should be deprecated in favour of `--grouping` (default true)
- `--disable-no-echo` (default false) should be deprecated in favour of `--echo` (default false)
- TBD support clusterctl describe clusterclass

/kind feature

**Comment by fabriziopandini** [comment]
I'm taking
- --show-conditions should allow for showing Cluster conditions as well
- there should be an option to show MachineSets

**Comment by fabriziopandini** [comment]
/help
/good-first-issue 

for the remaining part

**Comment by DiptoChakrabarty** [comment]
hey @fabriziopandini  I am interested in this issue , I want to try out the ```--disable-grouping``` one first , just wanted to clarify if     ```grouping(true)``` should have the same output as  ```--disable-grouping(false)```   which  shows all the machines on separated lines, no matter if they have the same state or not (command will be clusterctl describe cluster quickstart --grouping)

 , or is other some extra functionality required

**Comment by fabriziopandini** [comment]
`grouping` semantically is the opposite of `disable-grouping`, so:
- `disable-grouping=false` should be equivalent to `grouping= true`
- `disable-grouping=true` should be equivalent to `grouping= false`

**Comment by fabriziopandini** [comment]
@DiptoChakrabarty do you want to pick up also 
- `--disable-no-echo` (default false) should be deprecated in favour of `--echo` (default false)

This should be ~same as your work in #5550

**Comment by DiptoChakrabarty** [comment]
yes I want to work on it

**Comment by sbueringer** [comment]
/reopen
Given that there is more to do.

**Comment by sbueringer** [comment]
I think the only thing potentially left is `TBD support clusterctl describe clusterclass`, but maybe that should be another issue?
