### ISSUE TITLE
Clusterctl upgrade (v1alpha3=>v1beta1) test is flaky

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5349]
Clusterctl upgrade test is flaky: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-v1alpha3-v1beta1-upgrade-main
(only for v1alpha3=>v1beta1, v1alpha4=>v1beta1 looks a lot better)

**Environment:**

- Cluster-api version: main
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind flake
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
Is this because of the webhooks?

**Comment by sbueringer** [comment]
Looks to me like the v1alpha3 CAPD controller doesn't shutdown because of RBAC issues. The new CAPD controller doesn't come up because the conversion webhook doesn't work. (this only occurs for v1alpha3+ upgrade because we introduced the serviceaccount in v1alpha4, so the v1alpha4 controller does not run into this issue)

I think one improvement would be to make sure the old Deployment is really gone before we deploy the new controller. It's highly likely that it also fixes this flake.
