### ISSUE TITLE
Explore options to handle `clusterctl generate cluster --from` for managed topologies

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#5350]
**Detailed Description**

The clusterctl generate cluster command supports creating a cluster YAML from a user-pointed template using the `--from` flag. Explore options to have a clean UX when the user uses a managed topology cluster in the template.

Options:
* Check if the references cluster class is installed on the cluster and throw and warning if the cluster class is not installed or if the cluster is not initialized.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

/area topology
/area clusterctl

**Comment by fabriziopandini** [comment]
I'm not sure there is work to be done here.
[Alternative sources for clusterctl generated cluster](https://cluster-api.sigs.k8s.io/clusterctl/commands/generate-cluster.html#alternative-source-for-cluster-templates) (everything is not a repository, specified with --from) does not have a naming convention for templates we can rely on, like we have in the provider repositories.
So we install the file we are pointed to, but we cannot automatically trigger additional fetch operation without a rule that allows us to identify what to pull next.

**Comment by ykakarap** [comment]
That makes sense. Since the conditions in which the `--from` option is used is un-deterministic we cannot do any meaningful automation here.  Since there is nothing to be done here I will close the issue. But I will wait for a few days to see if anyone else has any other thoughts.
