### ISSUE TITLE
Move error variables out of utils package

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5356]
**Detailed Description**

There are a few errors defined in the top level utils package that are better placed in the top level errors package. These errors should be deprecated and recreated in the errors package. The util errors should then be removed in a coming release.

Examples:
https://github.com/kubernetes-sigs/cluster-api/blob/573f005559b452813e4dd8175a791dc2d1b143ed/util/util.go#L58

https://github.com/kubernetes-sigs/cluster-api/blob/573f005559b452813e4dd8175a791dc2d1b143ed/util/util.go#L62

/kind cleanup

**Comment by vincepri** [comment]
These seems only used or returned within that package, should we consider instead moving the functions using them to a different package instead?

**Comment by killianmuldoon** [comment]
These do seem to be used - ErrNoCluster in kubeadmconfig_controller.go and ErrUnstructuredFieldNotFound in cluster_controller_phases.go. If they were just used in package I'd say keep them, but it looks like they're being used as importable error messages which says to me they belong in errors.

**Comment by killianmuldoon** [comment]
https://github.com/kubernetes-sigs/cluster-api/blob/58905fb5140a7844c3e24aa70d255fb8f9d0c491/bootstrap/kubeadm/controllers/kubeadmconfig_controller.go#L166

**Comment by DiptoChakrabarty** [comment]
hey can I try this issue out , I am new here , this is my approach 
move these errors in util package 
https://github.com/kubernetes-sigs/cluster-api/blob/573f005559b452813e4dd8175a791dc2d1b143ed/util/util.go#L56-L62

to the error package  here -> https://github.com/kubernetes-sigs/cluster-api/blob/58905fb5140a7844c3e24aa70d255fb8f9d0c491/errors/consts.go

then replace the util.ErrNoCluster and similar errors with the errors package ones

does this sound appropriate

**Comment by killianmuldoon** [comment]
@DiptoChakrabarty That sounds right - it's important to not remove the original variables from the utils package and instead add a deprecation message so we can remove the errors with the next breaking changes to Cluster API. So:

**Comment by killianmuldoon** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/5419#issuecomment-957334223

There's a couple of problems with this approach as it looks out of the scope of the current errors package. Currently the errors package covers mostly status conditions whereas these are closer to client errors. 

Should we expand the overall usage of the errors package to include client errors like ClusterNotFound? These are commonly used and compared errors across the code base, but there's unwanted constraints we could possibly introduce by trying to implement them all in one format.

**Comment by vincepri** [comment]
@killianmuldoon @DiptoChakrabarty Is it ok to close this issue and the related PR based on https://github.com/kubernetes-sigs/cluster-api/pull/5419#issuecomment-957756016?

**Comment by killianmuldoon** [comment]
I'm fine with that given there's no agreed way to move those errors right now.

**Comment by vincepri** [comment]
👍 
/close
