### ISSUE TITLE
Consolidate naming for predicates unPaused vs notPaused

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#5361]
**What steps did you take and what happened:**
Some times we use the term notPaused, others unPaused.

**What did you expect to happen:**
We should consolidate naming and terms in predicates unPaused vs notPaused and use always the same.
e.g
https://github.com/kubernetes-sigs/cluster-api/blob/main/util/predicates/cluster_predicates.go#L179-L183
https://github.com/kubernetes-sigs/cluster-api/blob/main/util/predicates/generic_predicates.go#L182

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by fiunchinho** [comment]
I believe they are not exactly the same. I think `Unpaused` may refer to update events when `paused` transitions to `false`.

**Comment by enxebre** [comment]
ah I see, It's not clear to me why we need `ClusterUpdateUnpaused` rather than just checking `ClusterNotPaused` everywhere, I'm probably missing some context though.
