### ISSUE TITLE
Restructure Kubeadm Bootstrap controller code

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5370]
**User Story**

As a developer I would like to more easily change the Kubeadm bootstrap codebase.

**Detailed Description**

A number of recent requests have come in to modify and change the behaviour of the Kubeadm bootstrap controller. The current codebase is difficult to modify for a number of reasons including:

1) Insufficient commenting
1) Long functions with multiple responsibilities
1) Multiple exit points from the reconciliation loop across the code

This issue covers restructuring the code to make some of these changes easier, not changing the behaviour or adding any new features to the Kubeadm Boostrap provider.

The end result - completely up for discussion - could look something like the ClusterTopologyReconciler with distinct getCurrentState, getDesiredState and ReconcileState functions that reduce the overall complexity of the reconcile flow and address the three main points above.

**Anything else you would like to add:**
Requests and changes coming into the bootstrap controller include:

1) https://github.com/kubernetes-sigs/cluster-api/issues/3430
1) https://github.com/kubernetes-sigs/cluster-api/issues/4609
1) https://github.com/kubernetes-sigs/cluster-api/issues/5294
1) https://github.com/kubernetes-sigs/cluster-api/issues/5124

/kind cleanup

**Comment by fabriziopandini** [comment]
/remove-lifecycle stale
@killianmuldoon it would be great if we can break down this is few, smaller actionable items
