### ISSUE TITLE
Add nested builders to internal/builders

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5378]
**User Story**

As a developer I would like a way to quickly create interrelated objects for testing. 

**Detailed Description**

The current internal/builders package allows objects to be created and composed from other objects e.g. the Cluster builder has a WithTopology field that allows a full topology object to be inserted and finally built into the cluster object on calling Build().

A nested builder style - where e.g. the Cluster builder accepts a Topology builder instead of a full Topology object. This would allow the full nested structure of dependent objects to be created in a single 'build' call and would allow variables to be shared between structs at build time reducing fat-finger errors when writing tests, i.e. small naming differences between templates and references. It should also make the code for tests less repetitive.

**Anything else you would like to add:**
This feature was requested here:
https://github.com/kubernetes-sigs/cluster-api/pull/5337#discussion_r718638764
/kind feature

**Comment by fabriziopandini** [comment]
/close
we will reconsider if the need arises
