### ISSUE TITLE
Cluster API Informing kube-reserved and system-reserved

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#5392]
/area api
/area kubelet
/area bootstrap

**User Story**

As a cluster operator, as I begin to load my cluster with workloads, without system-reserved or kubelet-reserved being set, my cluster can start exhibiting strange behaviour as various processes start being OOMkilled. I would like Cluster API to provide a mechanism to set these values based on my infrastructure.

**Detailed Description**

Production clusters should have system-reserved and kubelet-reserved set for the correct functioning of the cluster. Some deployers make opinionated guesses for what these should be based on the memory on the system. For example, [EKS makes a calculation based on the instance type][EKS issue].

[KEP 2369] introduced the possibility of dynamic sizing providers for the Kubelet, and CAPI could potentially act as a control point for its own Kubelet sizing provider, e.g. have something in the MachineSpec, and also have reconciliation mechanisms to copy that information from, but the proposal was not pursued. There is also likely to be Cluster Autoscaler impacts, so @elmiko might be interested too:

``` yaml
spec:
  reservations:
     kubelet: 2Gi
     system: 3Gi
```

The alternative way is to plug something into kubeadmConfig, and have kubeadm set the values on the kubelet startup flags. Not a fan of this as it's not dynamic, and also starts to even more closely couple bootstrap configuration to the machine configuration, which is something we want to decouple (#5294).

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

[KEP 2369]: https://github.com/kubernetes/enhancements/issues/2369
[EKS issue]: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1885

**Comment by sbueringer** [comment]
> Dynamic kubelet configuration is definitely deprecated if not completely deleted by now. There's a reference to that in the supporting KEP.

Some more context in: https://github.com/kubernetes/enhancements/issues/281

I wasn't aware of the deprecation. Looks like it will be dropped with 1.23.
https://github.com/kubernetes/kubernetes/pull/102966/files:
```golang
fs.MarkDeprecated("dynamic-config-dir", "Feature DynamicKubeletConfig is deprecated in 1.22 and will not move to GA. It is planned to be removed from Kubernetes in the version 1.23. Please use alternative ways to update kubelet configuration.")
```

**Comment by fabriziopandini** [comment]
/help

In order to set those values benchmark data are required; also sizing depends on number of targets objects to manage (clusters/machines) and they can be impacted by performances of the hardware used for the management cluster
