### ISSUE TITLE
Move Control plane provider contract documentation to the right chapter 

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#5393]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**
/kind documentation
/help

Follow up to #5371 , there is no document for control plane providers under `docs/book/src/developer`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
Currently https://cluster-api.sigs.k8s.io/developer/architecture/controllers/control-plane have both developer doc and provider contract

We should move everything below https://cluster-api.sigs.k8s.io/developer/architecture/controllers/control-plane#contracts to a new page under https://cluster-api.sigs.k8s.io/developer/providers/contracts

/remove-lifecycle stale
/triage accepted
/good-first-issue

**Comment by NareshKoduru** [comment]
Hello,
I want to contribute to this issue. Thanks

**Comment by fabriziopandini** [comment]
@NareshKoduru Thank you for stepping up! Feel free to /assign yourself to the issue and open a PR.
