### ISSUE TITLE
Missing documentation: Supported annotations and labels

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#5394]
**What steps did you take and what happened:**

Have had a number of customer issues that could have been alleviated if people knew about the use of the pause annotations. The pause annotation for example is mentioned with regards to the [machine health check](https://cluster-api.sigs.k8s.io/tasks/healthcheck.html?highlight=pause#skipping-remediation) but it has broader applicability.

In addition, when doing a code walkthrough, I stumbled across the `interruptible` node label, which is documented in one of the [CAEPs](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20200330-spot-instances.md#interruptible-label) but appears nowhere in the book with a concise summary as to why you want to use it.

/help

**What did you expect to happen:**

Annotations and labels are documented.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

It is probably worth having one reference document with all of the annotations and labels.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
/help

**Comment by mehabhalodiya** [comment]
Hey @randomvariable
I would like to document "annotation and labels".
Will you please give me a brief idea on resolving this by providing some reference links?
Thanks.

**Comment by fabriziopandini** [comment]
Hi @mehabhalodiya thanks for picking up this work!
I think that a good starting point for this effort is to look at the labels/annotations defined in our API packages:
- https://pkg.go.dev/sigs.k8s.io/cluster-api/api/v1beta1
- https://pkg.go.dev/sigs.k8s.io/cluster-api/bootstrap/kubeadm/api/v1beta1
- https://pkg.go.dev/sigs.k8s.io/cluster-api/controlplane/kubeadm/api/v1beta1
- https://pkg.go.dev/sigs.k8s.io/cluster-api/exp/api/v1beta1
- https://pkg.go.dev/sigs.k8s.io/cluster-api/exp/addons/api/v1beta1

**Comment by SubhasmitaSw** [comment]
Hey @mehabhalodiya are you still working on it or may I pick this up?

**Comment by SubhasmitaSw** [comment]
Thanks @mehabhalodiya 
/assign

**Comment by killianmuldoon** [comment]
@SubhasmitaSw have you had any time to work on this?

**Comment by killianmuldoon** [comment]
#6966 Related - we should document spec fields and annotations together if possible.

**Comment by hackeramitkumar** [comment]
@fabriziopandini , I would like to work on this issue. Can you please assign it to me? And If possible show me a sample list So that I can get a basic idea.

**Comment by fabriziopandini** [comment]
/assign @SubhasmitaSw
(I think you can assign yourself)

I will start bu adding a page in the book under reference with two paragraphs, one for supported labels and the other for supported annotations.
Each paragraph should have a table with label/annotation and note.

then you have to search in the locations listed in https://github.com/kubernetes-sigs/cluster-api/issues/5394#issuecomment-1039089099

for things like https://github.com/kubernetes-sigs/cluster-api/blob/bb6df67e6dbbe80707291538db9a9f76a42df451/api/v1beta1/common_types.go#L25-L27

and grab the label/annotation name + the description, something like
| label | note|
| -----|-------|
|cluster.x-k8s.io/cluster-name| this label is set on machines linked to a cluster and external objects(bootstrap and infrastructure providers) |
