### ISSUE TITLE
Security Self Assessment: [DEV-2] Verify vulnerability reporting process

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#5398]
**Detailed Description**

As part of the [security self-assessment](https://docs.google.com/document/d/1Fj_cLUN9kLruHbEgmYiEgoqZjf2rRuVOmQDGOKByaf4/edit), (#4446) am reviewing our software development practices. 

We have a SECURITY_CONTACTS and we have vulnerability reporting (via an org template?) that can be invoked hitting New Issue.

Do we know if this process is valid for subprojects? In addition, the SECURITY_CONTACTS file is outdated, and needs updating.

(I would also like to volunteer to be on that list)

/kind feature
/area security

**Comment by neolit123** [comment]
The process of batch removing these files went stale. But they are pretty much pending deletion in all repos...I'd probably delete the file and keep email / contacts in the main readme.

Girhub handles are useless as there are no github dms?

**Comment by randomvariable** [comment]
> Github handles are useless as there are no github dms?

Yes, I don't think we can use them really for private disclosure.

**Comment by PushkarJ** [comment]
/retitle Security Self Assessment: [DEV-2] Verify vulnerability reporting process
/sig security
/area security

(This topic is being discussed in the community right now across SIG Security, Contribex and SRC. Cluster API sub-project may end up benefitting from the structural changes that this discussion creates)

**Comment by fabriziopandini** [comment]
/lifecycle frozen
This has been discussed at KubeCon Detroit during a postmortem of the security assessment.

TL;DR;
The CAPI subproject doesn't have the critical mass to own its own vulnerability reporting process; in the issue templates, under "Report a security vulnerability" we are referring to the Kubernetes process described in https://github.com/kubernetes-sigs/cluster-api/security/policy, but the Kubernetes security response team should be staffed/define its own processes about how to engage sub-projects. cc @PushkarJ @ aladewberry

**Comment by sbueringer** [comment]
cc @aladewberry (looks like there is a space too much in your mention)

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough contributors to adequately respond to all issues and PRs.

As discussed with SIG security folks back in detroit when we did a retrospective on this security assessment (@aladewberry), given different staffing/size of projects, the only viable way for subprojects to handle vulnerability reporting process is to rely on the K8s process
