### ISSUE TITLE
Controller managers should use "leases" for leader-election-resource-lock 

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#5399]
**What steps did you take and what happened:**
Run Cluster API.
See controller managers use "configmapsleases" for leader-election-resource-lock.

**What did you expect to happen:**
Controller managers use "leases" as for leader-election-resource-lock. This mitigates overwhelming the apiserver in a large management cluster and avoid additional rbac.

**Anything else you would like to add:**
Controller runtime sets by default leader-election-resource-lock to "ConfigMapsLeasesResourceLock" since v0.7 so consumers can do smooth transitions. https://github.com/kubernetes-sigs/controller-runtime/blob/1730628f118be1128787012c164379e6ac46c75f/pkg/manager/manager.go#L143-L156

Configmap updates to keep the lease alive result in large memory hits for any component that caches/syncs configmaps, particularly the apiserver. Furthermore, it requires additional rbac for controllers.

We should do the sam for all providers:
- CAPA https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2827
- Azure https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1761

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by randomvariable** [comment]
Are there any cons to doing this ? Doesn't look like it ?

**Comment by sbueringer** [comment]
I think the lease lock mechanism is fine. Only the migration to it could be problematic:
(https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/manager/manager.go#L143-L156)

But I think with clusterctl that should be fine to as we first scale down and then delete the old provider before we create the new one during upgrade.

**Comment by enxebre** [comment]
Yeh and v1alpha4 uses "configmapsleases" which should be able to nicely go to "leases".
But before v1alpha4 we used controller-runtime < 0.7 so "configmaps". So custom upgrades procedures going from v1alpha3 -> v1beta1 ("configmaps" -> "leases") might be more problematic.
