### ISSUE TITLE
MachineSet controller sets MachineSetStatus

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#54]
_From @p0lyn0mial on March 8, 2018 14:21_

The current implementation of `MachineSet` controller doesn't set `MachineSetStatus` at all. This item tracks potential implementation.

For reference implementations see:

https://github.com/kubernetes/kubernetes/blob/a0844c17bfb964e3d1709784203e8404f790116c/pkg/controller/replicaset/replica_set_utils.go#L35:1

https://github.com/gardener/machine-controller-manager/blob/master/pkg/controller/machineset.go#L518

See also #535

_Copied from original issue: kubernetes/kube-deploy#642_

**Comment by rsdcastro** [comment]
_From @p0lyn0mial on March 8, 2018 14:22_

/cc @mvladev @rsdcastro

**Comment by rsdcastro** [comment]
_From @p0lyn0mial on March 8, 2018 14:42_

initial implementation was introduced in #620

**Comment by spew** [comment]
Hello p0lyn0mial are you planning to work on this one?

**Comment by spew** [comment]
hi @p0lyn0mial, in the meantime I started looking at another issue. I'm going to be working on https://github.com/kubernetes-sigs/cluster-api/issues/52 first and then I'll likely come back to this one.

**Comment by k4leung4** [comment]
apologies, i didn't notice this issue, but i have implemented it.

https://github.com/kubernetes-sigs/cluster-api/pull/180
