### ISSUE TITLE
`clusterctl version` shows wrong version for the v1.0.0 release

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#5404]
**What steps did you take and what happened:**
Download the clusterctl binary from the v1.0.0 release artifacts: https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.0.0/clusterctl-linux-amd64

Run `clusterctl version`.

The clusterctl binaries of the v1.0.0 release report the wrong version.

**What did you expect to happen:**
`clusterctl version` should report the version as `v1.0.0`.
Got: 
```
clusterctl version: &version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.0-rc.0.42-e09ed61cc9ba8b", GitCommit:"e09ed61cc9ba8bd37b0760291c833b4da744a985", GitTreeState:"clean", BuildDate:"2021-10-06T16:11:06Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

New clusterctl version available: v1.0.0-rc.0.42-e09ed61cc9ba8b -> v1.0.0
https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.0.0
```

clusterctl shows a git version that is not `v1.0.0` and suggests that an update is available.

It should show the version as `v1.0.0`.

The same happens for the darwin binary as well.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by killianmuldoon** [comment]
Agreed - after running brew install clusterctl I get:

`
clusterctl version: &version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.0", GitCommit:"e09ed61cc9ba8bd37b0760291c833b4da744a985", GitTreeState:"clean", BuildDate:"", GoVersion:"go1.17.1", Compiler:"gc", Platform:"darwin/amd64"}
`
I think we can close this, though I'm still not sure what caused the original issue.

**Comment by fabriziopandini** [comment]
@ykakarap to re-assess

**Comment by ykakarap** [comment]
The latest releases (v1.1.0-rc.0, v1.0.2, 0.4.5, 0.3.24) all seem to have the correct versions in the clusterctl binaries. Looks like the release automation works as expected. 
Closing this issue.

/close
