### ISSUE TITLE
Create jobs for the release-1.0 branch

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5410]
As part of the activities for v1/v1beta1 releases the new release-1.0 branch has been created.

It is now required to setup all the corresponding E2E tests, so we can have a signal about the state of this version of the code.

Prior art:
https://github.com/kubernetes-sigs/cluster-api/issues/5252

/kind feature

**Comment by sbueringer** [comment]
1. And `cluster-api-periodics-release-1-0-upgrades.yaml` please
2. They will be automatically created once the first test results exist after the PR in test-infra has been merged
3. The jobs will remain the same

**Comment by sbueringer** [comment]
@anusha94 Do you have time to implement the issue? Just because we're starting to cherry-pick fixes onto release-1.0 and we have no tests at all :). Please let me know if there's anything I can do to help.
