### ISSUE TITLE
CAPD - Unable to connect to the server: dial tcp  i/o timeout

### ISSUE THREAD

**Issue by christianh814** [kubernetes-sigs/cluster-api#5428]
**What steps did you take and what happened:**

Started a little bit after the 1.0 release. Following the [quickstart](https://cluster-api.sigs.k8s.io/user/quick-start.html) and using Docker.

```
$ clusterctl get kubeconfig mytest1234 > /tmp/m1234.kubeconfig
$ kubectl get nodes --kubeconfig /tmp/m1234.kubeconfig
Unable to connect to the server: dial tcp 172.18.0.3:6443: i/o timeout
```

So I tried getting the kubeconfig using KIND

```
$ kind get kubeconfig --name=mytest1234 > /tmp/mytest.kubeconfig
$ kubectl get nodes --kubeconfig /tmp/mytest.kubeconfig
Unable to connect to the server: x509: certificate is valid for 10.128.0.1, 172.18.0.5, 172.18.0.3, 127.0.0.1, not 0.0.0.0
```

I see no errors in the `capd-controller-manager` pod. This is on an Intel Mac running Docker Desktop and CAPD works fine if I run it on Linux so I'm not sure if this is a known issue using Docker on Mac or if I"m missing a configuration

**What did you expect to happen:**

CAPD Working on Mac running Docker Desktop

**Anything else you would like to add:**

CAPD Quickstart works as expected running it on Linux (Ubuntu and Fedora)

**Environment:**

- Cluster-api version: v1.0
- Minikube/KIND version: kind v0.11.0 go1.16.3 darwin/amd64
- Kubernetes version: (use `kubectl version`): v1.22.1
- OS (e.g. from `/etc/os-release`): MacOS Big Sur 11.6

/kind bug

**Comment by killianmuldoon** [comment]
@jessehu Could you open a new issue with the full details of your issue? It would be good to get the full context of those logs to see if this is related to same root issue.

**Comment by jessehu** [comment]
Thanks @killianmuldoon . I'm not able to reproduce it now.
