### ISSUE TITLE
Update tests on Kubernetes main to use etcd 3.5.1

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5436]
As soon as https://github.com/kubernetes/kubernetes/pull/105706 merges, we should update our tests running/upgrading to Kubernetes from main branch (ci/latest) to use etcd 3.5.1 too.

/kind feature
/area testing 

/milestone v1.0

**Comment by sbueringer** [comment]
@fabriziopandini I assume same for release-0.4 and in case they exist at that time release-1.0?

**Comment by fabriziopandini** [comment]
https://github.com/kubernetes/kubernetes/pull/105706 is merged
adding release blocking because we want o be sure to be aligned to Kubernetes before releasing
/kind release-blocking

**Comment by sbueringer** [comment]
@fabriziopandini Q: (as also stated in https://github.com/kubernetes-sigs/cluster-api/issues/5793): 

Supported etcd version on main is v3.5.1 for v1.23 and v1.22. (https://github.com/kubernetes/kubernetes/blob/v1.23.0-rc.1/cmd/kubeadm/app/constants/constants.go). The latest v1.22.4 release still has v3.5.0. Which version should we use for our v1.22 installations?

**Comment by sbueringer** [comment]
Based on https://github.com/kubernetes-sigs/cluster-api/pull/5797 I would assume we also use v3.5.1 for 1.22?

**Comment by fabriziopandini** [comment]
/close 
given that #5797 and corresponding PR in test-infra are merged
