### ISSUE TITLE
update "clusterctl Provider Contract" section of CAPI book with requirements to support ClusterClasses

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#5447]
**Description**

Update the "clusterctl Provider Contract" section of the CAPI book to capture the set of requirements and conditions that a provider has to meet support using ClusterClasses and managed topologies with the `clusterctl generate cluster` command.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind documentation

/assign @ykakarap

**Comment by fabriziopandini** [comment]
/area topology
/close

This has been fixed by https://github.com/kubernetes-sigs/cluster-api/pull/5582

**Comment by ykakarap** [comment]
@fabriziopandini Thanks for closing this :)
