### ISSUE TITLE
Infrastructure Azure not compatible with 1.0

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api#5448]
**What steps did you take and what happened:**
` clusterctl init --infrastructure azure`

produced

```
Fetching providers
Error: current version of clusterctl is only compatible with v1beta1 providers, detected v1alpha4 for provider infrastructure-azure
```

**What did you expect to happen:**
It provisions the azure management cluster.  Perhaps this just hasn't been released yet?  I can't see anything stating it shouldn't be, unless I'm not looking in the right place.

**Environment:**

- Cluster-api version: 1.0.0
- Minikube/KIND version: local k8s docker for desktop
- Kubernetes version: (use `kubectl version`): 1.22.2
- OS (e.g. from `/etc/os-release`): wsl on Windows 11

/kind bug
/label /area/provider/azure

**Comment by sbueringer** [comment]
Yes, CAPZ doesn't have a v1beta1 compatible release yet, but there is work ongoing. One issue where this can be tracked is: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1722

Not sure if there are others (@CecileRobertMichon)

**Comment by sbueringer** [comment]
> Thanks for the info/link @sbueringer. Interesting enough, when I try either 0.4.4 or 0.4.3 I get a different error:
> 
> `Error: this version of clusterctl could be used only with "v1alpha4" management clusters, "v1beta1" detected`
> 
> Which version of `clusterctl` is actually supported for Azure?

clusterctl v0.4.x should work. I assume your using a v0.4.x clusterctl. Are you running it against a clean cluster? I think this issue can occur if there are already v1beta1 things (IIRC CRDs) in the cluster

**Comment by sbueringer** [comment]
@dtzar `clusterctl delete` has a `--include-crd` flag, so yes, it's intentional.
