### ISSUE TITLE
Remove ginkgo code (introduced by kubebuilder migration)

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes-sigs/cluster-api#545]
We previously went through and removed all of the ginkgo code. Then it came back. There isn't much of it and the sooner we take it out the easier it will be to do so. 

This should be relatively easy, even for someone new to the project.

/cc @krousey

**Comment by alvaroaleman** [comment]
@roberthbailey Can you elaborate a little? Does that mean we don't want to use ginkgo at all?

**Comment by roberthbailey** [comment]
Pretty much. We had ginkgo originally and folks were inclined to use the built-in go test patterns rather than add an extra layer of test libraries on top for various reasons. We can discuss more in the weekly meeting if you'd like.
