### ISSUE TITLE
MHC should surface unhealthy machine exceeds MaxUnhealthy/UnhealthyRange

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5451]
When the number of unhealthy machines exceeds MaxUnhealthy/UnhealthyRange MHC stop triggering remediation as expected.
However, as an operator, I expect that the fact that a machine is unhealthy somehow surfaces on the machine itself.

**Anything else you would like to add:**
This comes from something I noticed reading the code, but I still need to test it practice.

/kind feature
/area health

**Comment by fabriziopandini** [comment]
@sbueringer it seems that a PR merged, can we re-assess and eventually close?

**Comment by sbueringer** [comment]
@fabriziopandini That was only an issue which was closed in favor fof the current one.

**Comment by fabriziopandini** [comment]
My bad, thanks for pointing it out
