### ISSUE TITLE
Moving packages not intended for external usage to internal

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5455]
This is a follow up of https://github.com/kubernetes-sigs/cluster-api/pull/5440#issuecomment-946775031 and  https://github.com/kubernetes-sigs/cluster-api/pull/5440#issuecomment-946918809 and 

**User Story**

As a user I would like to be have a clear signal about what is is subject to version guarantees and what not
As a developer I would like to be able to continually evolving CAPI and add new feautures, with clear boundaries between what can change and what instead should respect version guarantees

**Detailed Description**
For historical reason (kubebuilder scaffolding, merge of CABPK/KCP/CAPD into a single repository, etc) CAPI public surface is wider than we really want to, and this could lead to use case like the one described in the comment above whit users starting to rely on things that we are not committed to support long term.

This cause frustration both in users and maintainers.

This issue is about starting a code reorg activity for moving packages not intended for external usage to internal, thus avoiding confusions for people importing Cluster API as a go library and provide cleaner boundaries to the maintainers.

**Anything else you would like to add:**

The operation is intended to non have impact (or to have minimal impact to the users), so the proposal is to gate decision on what can be moved to internal by an analysis of Cluster API usage as  a library in following providers implemented outside of the Cluster API repository: 
- CAPA
- CAPG
- CAPT
- CAPV
- CAPZ

E.g for the bootstrap/kubeadm folder, following changes seems reasonable

bootstrap/kubeadm/controllers → bootstrap/kubeadm/internal/controllers (*)
bootstrap/kubeadm/types/upstreamv1beta2 → internal/kubeadm/types/upstreamv1beta2
bootstrap/kubeadm/types/upstreamv1beta3 → internal/kubeadm/types/upstreamv1beta3

(*) Even if we are moving the implementation detail of CABPK controllers to internal, it could make sense to provide a way for creating reconcilers, thus allowing users to combine CAPI controllers in a single binary if they want to.

/kind cleanup
/area code-organization

**Comment by fabriziopandini** [comment]
/hold
I'm going to propose this change to the community during Oct 20th office hours

**Comment by CecileRobertMichon** [comment]
+1, also this is the kind of change that should definitely not go in a patch release (but I think we've agreed to bug fixes only so we should be good on that front)

**Comment by sbueringer** [comment]
+1

**Comment by enxebre** [comment]
@fabriziopandini should we also review https://github.com/kubernetes-sigs/cluster-api/tree/main/util as part of this effort?

**Comment by fabriziopandini** [comment]
@enxebre depends on what do you have in mind with review, but ideally yes if we find out some packages not used outside CAPI we can consider to move them to internal. Not sure if we can get there given that my main concern are controllers.

**Comment by fabriziopandini** [comment]
@shivanshu1333 @vibhorrawat @kaitoii11 is there anything I can do to keep this effort moving?

**Comment by sbueringer** [comment]
@fabriziopandini @killianmuldoon WDYT should we follow a similar pattern for the new webhooks package? Would be relatively easy to change right now.

**Comment by killianmuldoon** [comment]
+1 for this where it makes sense. Even if there's nothing we're really exposing right now - I don't think there's much apart from the structs - it's good to have the pattern in place.

**Comment by vibhorrawat** [comment]
@fabriziopandini Hey, I will publish the PR during this week. Question about how do I test it locally? Kindly suggest. Thank you.

**Comment by fabriziopandini** [comment]
> Question about how do I test it locally? Kindly suggest. Thank you.

you can integration and unit tests with `make test`, and then if you want you can also run E2E test locally. more info in https://cluster-api.sigs.k8s.io/developer/testing.html

**Comment by vibhorrawat** [comment]
@fabriziopandini Hi there, just an update from my end, I'm ready with the required changes for -
`/exp/addons/controllers --> /exp/addons/internal/controllers`
However, I'm yet to test the code changes locally. As of now, following the suggested testing [page](https://cluster-api.sigs.k8s.io/developer/testing.html). Hopefully, I will have something to share before end of this week. Kindly bear with me. Thank you!

**Comment by sbueringer** [comment]
@vibhorrawat If you want, you can also open a WIP PR and CI will run all the tests for you.

**Comment by vibhorrawat** [comment]
@sbueringer @fabriziopandini Submitted the PR for review with [WIP] prefix. Kindly have a look whenever convenient. Besides, I will continue my effort towards testing the code changes locally.

**Comment by kaitoii11** [comment]
If there aren't any takers, is it okay if I also work on  `/test/infrastructure/docker/exp/controllers --> /test/infrastructure/docker/exp/internal/controllers` ?

**Comment by sbueringer** [comment]
@kaitoii11 Yup!

**Comment by fabriziopandini** [comment]
/close
the first iteration of this work is completed, we are going to open new issues as soon as new opportunity arises
