### ISSUE TITLE
Create conditions for onboarding new reviewer & maintainers on sub-areas of the projects

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5456]
Growing the reviewers/maintainer base is something we’ve been trying to do for a while. That being said, as the codebase has been growing, we’re trying to think of the best way to onboard people to OWNERs files going forward and once thing that we’d like to see is more reviewersmaintainers of subareas of the project (credits to @CecileRobertMichon for this phrase 👏)

As of today there are following OWNERS files/Owner groups defining sub areas.
- clusterctl --> cmd/clusterctl/OWNERS 
- CABPK --> bootstrap/kubeadm/OWNERS
- KCP  --> controlplane/kubeadm/OWNERS
- CAPD  --> test/infrastructure/docker/OWNERS
- ClusterClass/managed topologies  --> controllers/topology/OWNERS

Is there a particular area people are more familiar with and would be interested in reviewing/maintaining to start?

IMO there are still too much under the top level approver owner files, and thus I propose the creation of two additional OWNER files/Owner groups:
- docs/OWNES (the book)
- test/OWNERS (including test framework, E2E tests and CAPD, and eventually some packages under internal/)
- controllers/OWNERS or possibly a subset of it (this is kind of related to code reorg activities proposed in https://github.com/kubernetes-sigs/cluster-api/issues/5455)

I really would like to get to a state where the top level OWNERS are required only for changes impacting our public API/public libraries, while everything else could be managed by experts in sub areas...

Opinions?

/kind cleanup
/area code-organization

**Comment by sbueringer** [comment]
To clarify:
> Is there a particular area people are more familiar with and would be interested in maintaining to start?

Is this targeted towards reviewers or maintainers or both?

**Comment by fabriziopandini** [comment]
> I'm not entirely sure about controllers/OWNERS. Is the idea more or less "core controller/webhooks" vs the kubeadm bootstrap and control plane provider?

Now controller/ are under the responsibility of top level maintainers, and this makes it difficult to add new reviewers/maintainers specialised in this (huge) part of the code base. A possible solution is to define an OWNERS file for controller/ , or eventually we can even break it down more, e.g having subareas for machine health checks, machinedeployments/machineset etc. But given that this is for helping new people to step up, it will be great to have some feedback about if this makes sense and the right level of granularity we should aim to

**Comment by randomvariable** [comment]
I thought I was a reviewer of the book for some reason - thought that meant I could only lgtm not approve.

I would volunteer for the following:

- test framework & e2e
- KCP

**Comment by fabriziopandini** [comment]
@vincepri  @enxebre @CecileRobertMichon @sbueringer any objection about closing this now?
I think that the initial steps for using the sub-area approach has been completed, the contributor guide updated, so now we can reconsider add OWNERS file case by case when the need arise

**Comment by sbueringer** [comment]
+1 for closing this issue


> As a follow up for this issue I'd like us to possibly start discussing and brain storm to come up with a more structure program to reduce barriers for new joiners, e.g groomed targeted backlog, templates with regular tasks, mentorship assignments...

@enxebre A follow-up for this point would be nice.

**Comment by fabriziopandini** [comment]
/close
let's open other issues to track additional onboarding efforts

**Comment by enxebre** [comment]
@sbueringer let me draft something and I'll create a follow up issue
