### ISSUE TITLE
Update Versioning policy in the docs

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5459]
As pointed out at https://github.com/kubernetes-sigs/cluster-api/pull/5440#issuecomment-947394665 the current [Versioning docs](https://github.com/kubernetes-sigs/cluster-api/blob/main/VERSIONING.md#overview) imply that we will not make any breaking changes in Cluster API until the next major version:

1) > we'll occasionally want to make breaking changes. They'll be merged onto main, and will then trigger a major release (see Release Process). Because breaking changes induce a major revision, the maintainers may delay a particular breaking change until a later date when they are ready to make a major revision with a few breaking changes.

1) > NB: Pre-1.0 releases treat breaking changes a bit more lightly. We'll still consider carefully, but the pre-1.0 timeframe is useful for converging on a ergonomic API.

1) >NB: If the major release is 0, any minor release may contain breaking changes.

The stated intention with going to 1.0 was that we could continue to make breaking changes with minor releases i.e. [following the pattern in Kubernetes](https://kubernetes.io/docs/reference/using-api/deprecation-policy). 

We need a new versioning / breaking changes /versioning policy to reflect that intention. We need answers to the following questions:

1) Should we allow breaking changes on minor versions?
1) Should we enforce deprecation on all changes outside of /internal? (additional exceptions might be third_party and test)
1) What should our deprecation policy be? (Number of versions or passage of time)
1) Should we have a separate deprecation policy for code and API changes?
1) Should the main branch run ahead of the current release branch i.e. be breaking compared to the latest release version?

**Comment by vincepri** [comment]
+1 to update the versioning document with what we agreed prior to the v1.0 release.

**Comment by vincepri** [comment]
> Should we allow breaking changes on minor versions?

Yes, we're following Kubernetes practices.

> Should we enforce deprecation on all changes outside of /internal? (additional exceptions might be third_party and test)

Yes, although every exception should be documented.

> What should our deprecation policy be? (Number of versions or passage of time)

Code is usually at least 1 release in between, the APIs follow their own guarantees.

> Should we have a separate deprecation policy for code and API changes?

Yes, this is already true today. 

> Should the main branch run ahead of the current release branch i.e. be breaking compared to the latest release 
version?

Depends? Seems folks have different opinion on this one, I'd personally vote to only open the main branch to breaking changes only when we're ready for the next minor release, although we need to define how that happens and when.
