### ISSUE TITLE
Implement new  ClusterClass compatibility checks in webhook

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5461]
**User Story**
As an operator I would like to be confident that changing my clusterClass won't result in a broken cluster.

**Detailed Description**
Since #5212 there are five rules defined under clusterClass compatibility in the ClusterClass CAEP:

>   - All the references must be in the same namespace of `metadata.Namespace` - the same namespace as the existing clusterClass.
>   - `spec.workers.machineDeployments` must not remove any deployment classes (adding new or modifying existing classes is supported).
>   - `spec.controlPlane.localobjecttemplate`, `spec.controlplane.machineinfrastructure`, `spec.infrastructure`,  `spec.workers.machineDeployments[].template.infrastructure.ref` must not change apiGroup or Kind.
>   - All variables used in Clusters must not be removed.
>   - Schemas of variables used in Clusters must not be changed in an incompatible way, i.e. when the schema change would be reconciled, 
>     applying patches to templates should not lead to incompatible changes when reconciling the objects inferred from those templates.

The latter two of these are concerned with variables and patches defined in the ClusterClass and the definition of "changed in an incompatible way" requires a little bit of additional design before implementation.

This issue covers proposing and agreeing on a specific set of validation criteria for the fourth and fifth rule in the above list and ensuring all five rules are implemented in the ClusterClass webhook to ensure compatibility when a ClusterClass is changed.

/kind feature

**Comment by killianmuldoon** [comment]
I have a couple of questions I'd like to get alignment on before taking a proper run at this:

Are we assuming that listing all clusters using a clusterclass from the webhook is the supposed mechanism for ensure variables aren't in use currently? Or is there some other semaphore or lock that could be used?

The overall question I'm running into is how much validation we want to do against existing clusters / variables to make sure existing values are in line with proposed changes? 

We could:
1) Only validate new values - this would be fine for e.g. MaxLength but fails with ExclusiveMaximum. 
1) validate everything against existing values and only allow schema changes that are compatible with all existing usages.
1) do careful validation to ensure incompatible changes are not possible. e.g.:
    - Maximum can only be increased
    - Minimum can only be decreased
    - ExclusiveMaximum can never be changed
    - Enum can only be added to
    - MultipleOf can only be changed to one of its factors(😆  probably not very useful)



@fabriziopandini @sbueringer WDYT?

**Comment by fabriziopandini** [comment]
@killianmuldoon can we close this issue now that the work on Cluster/ClusterClass web hook is completed?

**Comment by killianmuldoon** [comment]
I think the variable validation issue is the last outstanding piece of work here. Let's close it when we close #5752 (I've added a Fixes tag on that PR)
