### ISSUE TITLE
Add documentation for controllers missing from book

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5475]
**User Story**

As a user/operator I would like comprehensive documentation of all CAPI controllers.

**Detailed Description**

Currently there is documentation in section 3.5 of the CAPI book for most of the controllers in CAPI but some are missing. 

Documentation could be added for the following controllers:

**Core controllers**
- [x]  Topology/Cluster Controller #5502
- [ ] ClusterResourceSet/ClusterResourceSetBinding

**Internal controllers**
- [ ] ClusterCache
- [ ] Topology/MachineDeployment
- [ ] Topology/MachineSet

c/f #5471 

/kind feature
/kind documentation

**Comment by killianmuldoon** [comment]
Hi @ariel-zilber are you planning to take on the ClusterResourceSet controller?

**Comment by ariel-zilber** [comment]
HI yes am planning to take on ClusterResourceSet

**Comment by killianmuldoon** [comment]
Thanks!

**Comment by ariel-zilber** [comment]
Hi yes I  did .I am on it 

>

**Comment by ramineni** [comment]
@killianmuldoon could I take up ClusterResourceSet controller if it's not done yet?

**Comment by killianmuldoon** [comment]
@ramineni that would be great!
