### ISSUE TITLE
During KCP rollout, etcd churn can prevent renewal of the bootstrap token causing KCP node registration to fail

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#5477]
/kind bug

Follow up from #2770

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Deploy a 3-node CP cluster using CAPV with kube-vip using PhotonOS (for some reason, it's more likely to occur here) and then set kcp.spec.upgradeAfter to trigger a rollout.

Due to a mixture of https://github.com/kube-vip/kube-vip/issues/214 and the fact we haven't yet implemented etcd learner mode in kubeadm or have full support in kubernetes, etcd leader switches around many times, with kube-vip leader election also rotating. During this time, CAPI controllers are unable to fully reconcile, and neither can kubelet register nodes. Importantly, CABPK is also unable to renew the bootstrap token. Eventually, etcd replication completes but after the 15 minute bootstrap token timeout. kubelet node registration ultimately fails and we end up with an orphaned control plane machine which is a valid member of the etcd cluster, complicating cleanup.

**What did you expect to happen:**

Rollout succeeds.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

It might be worth in these instances to have a configurable bootstrap token TTL. We can't account for every type of environment with a longer TTL so we should make it configurable and vendors and cluster operators can decide, since there is a security trade off.

Furthermore, VMware would like to request a backport to v0.3.x branch.

**Environment:**

- Cluster-api- version: v0.3.22
- Kubernetes version: (use `kubectl version`): v1.21
- OS (e.g. from `/etc/os-release`): Photon 3

**Comment by fabriziopandini** [comment]
/triage accepted
/unassign @randomvariable 
/unassign @gab-satchi 

This should be re-assessed after we improved how token renewal is managed (tokens are now renewed until the machine joins); also in kubeadm we recently discussed to revive the work on etcd learner mode

**Comment by sbueringer** [comment]
Quick update: kubeadm learner mode RFE:
* https://github.com/kubernetes/kubeadm/issues/1793#issuecomment-1268139489
* https://hackmd.io/@DAKGcrh_RpC5vlt8w5bf8A/r1qoLh9zj

**Comment by chrischdi** [comment]
Also related: had to increase the timeout here for self-hosted upgrade tests. From my analysis the reason here is also etcd churn and side-effects of it (e.g. leader-election failing which makes webhooks unavailable).

- code-change: https://github.com/kubernetes-sigs/cluster-api/blob/02f42f2ffc4114d00a300ae3d8cd39a4c934fc5c/test/framework/cluster_proxy.go#L49-L53
- xref PR discussion: https://github.com/kubernetes-sigs/cluster-api/pull/7239#discussion_r987787229

**Comment by fabriziopandini** [comment]
We should better sequence what's happening here.
KCP move leadership to another node only before deleting the current leader, so we are already minimizing the number of forced leader changes / doing what is possible for them to happen in a controlled way.
Everything else is raft periodic leader election that should be pretty stable, assuming the current leader answers timely.
🤔

**Comment by sbueringer** [comment]
> Quick update: kubeadm learner mode RFE:
> 
> * [RFE: use learner mode for joining etcd members kubernetes/kubeadm#1793 (comment)](https://github.com/kubernetes/kubeadm/issues/1793#issuecomment-1268139489)
> * https://hackmd.io/@DAKGcrh_RpC5vlt8w5bf8A/r1qoLh9zj

Just fyi

> The alpha-level code is merged for v1.27 in https://github.com/kubernetes/kubernetes/pull/113318
>  https://github.com/kubernetes/kubeadm/issues/1793#issuecomment-1377722007
