### ISSUE TITLE
Orphaned infrastructure machines during cluster deletion

### ISSUE THREAD

**Issue by gab-satchi** [kubernetes-sigs/cluster-api#5483]
**What steps did you take and what happened:**
We're seeing issues where a cluster is stuck on deletion (in VSphere). Upon investigation, we always find VSphereMachines that aren't deleted that's blocking the rest of the deletion flow. CAPI's machine_controller is meant to set a machine as the Owner of the infrastructure machine but there may be a gap where the infrastructure machine is briefly orphaned. And if the delete is issued during that gap, then the VSphereMachine never gets deleted. 

We see that machine_set controller is what creates the infrastructure machine but it no longer sets itself as the owner. The gap we _think_ our stalled clusters are running into is: 
- machine_set controller creates the infrastructure machine
- delete is issued on the cluster before machine object has the chance to set itself as the owner
- machine object is deleted and the delete doesn't propagate down to the vspheremachine
- vspheremachine doesn't get the delete signal and never gets deleted

**What did you expect to happen:**
Deletion goes through

**Anything else you would like to add:**

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by srm09** [comment]
Hey @sbarikdev any movement on this one? I have been seeing this issue pop up in a couple of downstream scenarios and would love the CAPI fix instead of bandaging the fixes in the provider.

**Comment by fabriziopandini** [comment]
/kind release-blocking
I'm adding release-blocking because It will be great to get this solved in the 1.1 release

**Comment by fabriziopandini** [comment]
/unassign @sbarikdev
/assign 
I'm stepping in to try to get this into the release
