### ISSUE TITLE
Document CRs ownership

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#5487]
**User Story**

As a cluster operator/developer I would like comprehensive documentation for the CRs ownership relationship. This comes in particularly handy as the number of CRDs of the project keeps growing.

**Detailed Description**

In order to make it easier for devs to quickly understand CAPI internals, we could include a section with some CRs ownership diagram and implications in the developer guide https://cluster-api.sigs.k8s.io/developer/architecture/controllers.html

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature
/kind documentation
/help
/good-first-issue

**Comment by fabriziopandini** [comment]
/milestone v1.1

NOTE: this issue originally was about documenting current owner chain, which is something useful per se.

I would suggest to move discussion about changing current owner chain on another issue; mostly because CAPI relies heavily on it for deletion and move on top of my mind but most probably in other places as well, and this requires proper investigation.

**Comment by Jont828** [comment]
@enxebre Did you have any ideas in mind for how to document ownership of cluster resources? This is a bit off topic, but I've recently worked on a [CAPI GUI app](https://github.com/Jont828/capi-visualization) that visualizes resources. It currently does not show the ownership relations, but what do you think about using a graph or tree to document resource ownership?

**Comment by fabriziopandini** [comment]
FYI there is already a kubctl tree plugin showing document ownership

**Comment by ashutosh887** [comment]
@enxebre @codablock I would like to work on this Issue 
/assign

**Comment by sbueringer** [comment]
cc @killianmuldoon 
IIRC we have a way to automatically generate a lot of the ownership information based on ownerRefs. This could probably be leveraged for this issue.

**Comment by killianmuldoon** [comment]
/assign

I'll take a go at this.

Linked to https://github.com/kubernetes-sigs/cluster-api/issues/4014
