### ISSUE TITLE
Security Self Assessment: [STRIDE-INFODISCLOSE-3] RFE: Improve certificate management in Cluster API

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5490]
**User Story**

As a user/operator I would like to have control on how certificates are created
As a user/operator I would like to have visibility on certificate expiration date
As a user/operator I would like CAPI to support me in certificate lifecycle management
As a user/operator I would like to have the option to rely on external tools for certificate management

**Detailed Description**

As of today Cluster API provide a minimal support for certificate management, mostly util for management of secrets with certificate authorities, while over time the responsibility of creating certificates has been delegated to control plane providers.

While this approach worked well, some shortcomings are starting to surface, mostly boiling up to the fact that there is no top level certificate management primitives in our API, and this makes it difficult and fragmented the answer to:

- how can I customise certificate at provisioning time
- how can I monitor state of my certificates (expiration date)
- how can CAPI support me in certificate lifecycle management tasks, like certificate renewal or CA rotation

Last but not least, CAPI leaks of a clean interface for integrating with external tools for certificate management, like e.g Hashicorp Vault.

This issue is about starting an effort for rethinking this area, and providing a clean solution for addressing above concerns starting from the two issues that mostly concern users, that are better support for certificate renewal and CA rotation tasks

/kind feature
/kind proposal

@randomvariable to add more from a provider PoV

**Comment by randomvariable** [comment]
@PushkarJ it would be good to get feedback from security folk.

**Comment by PushkarJ** [comment]
+1 Agree that it would be fantastic to get this as a built-in feature in CAPI. CA hierarchy and CAPI cluster hierarchy also lends itself several benefits of simplicity in how we could manage the root of trust. 

However, it might be helpful to understand what problem we are trying to solve (which might be well-known but is worth re-iterating) by sharing the current state and its drawbacks. 

Is this were Cluster API Enhancement Proposal would come into picture that elaborates more on motivations, current state, its drawbacks and future state?

**Comment by randomvariable** [comment]
> @randomvariable to add more from a provider PoV

I don't think there's anything more to add from a provider specific PoV. At least if we consider the possibility of leveraging cert-manager for generation, then we can defer provider specific implementations to it.

**Comment by PushkarJ** [comment]
Security Self Assessment: [STRIDE-INFODISCLOSE-3] RFE: Improve certificate management in Cluster API

**Comment by PushkarJ** [comment]
/retitle Security Self Assessment: [STRIDE-INFODISCLOSE-3] RFE: Improve certificate management in Cluster API
/area security
/sig security

**Comment by sbueringer** [comment]
I've created a separate issue to track machine certificate renewal specifically: https://github.com/kubernetes-sigs/cluster-api/issues/6529

**Comment by fabriziopandini** [comment]
/triage accepted
@PushkarJ  we are implementing automatic certificate renewal as described in https://github.com/kubernetes-sigs/cluster-api/pull/7268. is this enough to close this issue?

**Comment by PushkarJ** [comment]
@fabriziopandini the linked PR does look promising. We can close this with the usual caveat that if somebody feels like there is something left in the scope that is not covered in the new feature docs, we should reopen the issue.
