### ISSUE TITLE
Cloud Provider implementation for Digital Ocean

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#55]
_From @rsdcastro on January 29, 2018 23:10_

_Copied from original issue: kubernetes/kube-deploy#542_

**Comment by xmudrii** [comment]
From issue #211 

I'm interested more about that one. If that is okay, I'm interested in working on it, and if needed maintaining it. I would few pointers how and where to start, and what's the proposal process.

**Comment by kris-nova** [comment]
I think our first start here is getting a new repository - we are currently working on what that process looks like as a sig

**Comment by xmudrii** [comment]
This issue should be fixed now that https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean exists.

/close
