### ISSUE TITLE
Links to owners files should be updated to use the main branch

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5506]
found a couple of links that needs to be changed to use the main branch instead of master.

https://github.com/kubernetes/community/blob/822d3c300a1351088494dd1280a444f0ee01f9eb/sig-cluster-lifecycle/README.md?plain=1#L62

https://github.com/kubernetes/community/blob/822d3c300a1351088494dd1280a444f0ee01f9eb/sigs.yaml#L984

/kind bug
/help-wanted
/good-first-issue

**Comment by sayantani11** [comment]
Hey @fabriziopandini I saw the changes in k/community repo. But the other changes as mentioned by @sbueringer those changes have to be done to the respective repos right?

**Comment by fabriziopandini** [comment]
@sayantani11 if I got right @sbueringer comment, yes

**Comment by sbueringer** [comment]
> Hey @fabriziopandini I saw the changes in k/community repo. But the other changes as mentioned by @sbueringer those changes have to be done to the respective repos right?

Yes

**Comment by sbueringer** [comment]
/reopen 
looks like only vsphere is open: https://cs.k8s.io/?q=cluster-api%2Fblob%2Fmaster&i=nope&files=&excludeFiles=&repos=

**Comment by fabriziopandini** [comment]
it seems this is addressed now.
also, this should be tracked in vsphere then...

**Comment by sbueringer** [comment]
Yup, looks good now.

Thx @sayantani11 !

/close
