### ISSUE TITLE
Add cluster health and config checks to clusterctl

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5513]
**User Story**

As a user I would like to use clusterctl to inspect the health and config of my cluster for problems.

**Detailed Description**
Currently users can use clusterctl describe to help to surface the status of a cluster and its components. More advanced configuration and health checks baking in operational knowledge of cluster API could be added to clusterctl. 

This would be a debugging utility that would help end users pinpoint and understand issues with their cluster configuration or status that could be the source of issues with the cluster. Such a tool could be run at any time during the life of a Cluster API created cluster, catching configuration changes that have happened since cluster creation.

The approach would be similar to in homebrew's [`brew doctor`](https://github.com/Homebrew/brew/blob/master/docs/Manpage.md#doctor-dr---list-checks---audit-debug-diagnostic_check-)

Ideas for common config and health checks that could be put inside such a utility are very welcome! 😃 

/cc @vincepri 

/kind feature

**Comment by fabriziopandini** [comment]
The idea is valuable, even if IMO it is required to break down the work in smaller, actionable use cases
/lifecycle frozen

**Comment by fabriziopandini** [comment]
/triage accepted
/help
IMO such a feature will make sense after / when we are hitting GA with API; however, if someone has use case for this, let's document them and see if we can address them tactically

**Comment by fabriziopandini** [comment]
(doing some cleanup on old issues without updates)
/close
unfortunately, no one is picking up the task. the thread will remain available for future reference
