### ISSUE TITLE
Add a configuration flag for Machine Deletion Timeouts

### ISSUE THREAD

**Issue by chatla-telekom** [kubernetes-sigs/cluster-api#5516]
**User Story**

As a user I would like to have the possibility for specifying the timeout duration for machine deletion.

**Detailed Description**

According to the current implementation, the timeout for machine deletion is set to 10 seconds after which the machine is not deleted. This is not feasible in some cases as it leads to orphan machines in the clusters even after they are deleted in the control plane. By having the possibility to configure the machine deletion timeout, CAPI can retry to delete the machine until the timeout set by the user.

If the flag is not set, the timeout would fall back to the default value of 10 seconds. 

More about this can be found in this discussion on Slack: https://kubernetes.slack.com/archives/C8TSNPY4T/p1631180381209300

/kind feature

**Comment by sbueringer** [comment]
/remove-lifecycle stale
PR in progress
