### ISSUE TITLE
Lifecycle integrations for clusterClass

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5532]
ClusterClass is currently able to supply a cluster with the required objects to set up a working Kubernetes cluster through CAPI, but not all features of Cluster API, or technologies that integrate with Cluster API are covered. The [ClusterClass proposal](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/202105256-cluster-class-and-managed-topologies.md#prospective-future-work) says, under "prospective future work":

>Lifecycle integrations: Extend ClusterClass to include lifecycle management integrations such as MachineHealthCheck and Cluster Autoscaler to manage the state and health of the managed topologies.

This issue is about defining how, if desired, we can implement these Lifestyle integrations in ClusterClass. The following issues cover three areas have their own issues:

Cluster Autoscaler: #5442 
MachineHealthCheck: #5125 
ClusterResourceSet: #5203

Questions:
- Which of the above, if any, do we want to support in ClusterClass?
- Where should the line be drawn for including resources/capabilities directly in the ClusterClass spec?
- Should we have a more generic extensible interface for including integrations in ClusterClass (/cc @elmiko https://github.com/kubernetes-sigs/cluster-api/pull/5511#pullrequestreview-792420229)
- Should these integrations be embedded in the spec or use external templates?

/area topology

/cc @enxebre @sbueringer @elmiko

**Comment by fabriziopandini** [comment]
Q:  should we close this issue given that there are more detailed one for MHC, autoscaler, CRS?

**Comment by killianmuldoon** [comment]
@fabriziopandini I think we probably can given this issue isn't attracting much in the way of comments. I'm in agreement on your points above. I'm going to do a prototype PR for MHC as laid out in the [proposal ](https://github.com/kubernetes-sigs/cluster-api/pull/5511) PR. 

Other components, and the ClusterResourceSets, don't cleanly fit into the same bucket as MHC so we should think of another abstraction to integrate them with ClusterClass.
