### ISSUE TITLE
Move operator into its own repo

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#5536]
**User Story**

**Detailed Description**

As discussed in community call 27 Oct 2021 we agree on moving the operator into its own repo so It can have independent workflow development and release cycle.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

- [ ] Update CAEP
- [ ] Create New repo
- [ ] Remove branch and any related code from https://github.com/kubernetes-sigs/cluster-api

/kind cleanup

**Comment by alexander-demichev** [comment]
The operator repo was created https://github.com/kubernetes-sigs/cluster-api-operator

**Comment by fabriziopandini** [comment]
Looking forward to seeing this project take its own life!
@alexander-demichev is it possible to remove the operator branch now?

**Comment by alexander-demichev** [comment]
yes, you can delete it

**Comment by sbueringer** [comment]
@fabriziopandini Can you please merge this PR too when appropriate: https://github.com/kubernetes/test-infra/pull/25052

**Comment by vincepri** [comment]
Branch has been deleted from this repository

/close
