### ISSUE TITLE
ClusterClass validation, strict object ordering and gitops practices

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5537]
With ClusterClass we're seeing a number of complex validation questions that probe at the link between a Cluster and the ClusterClass it's stamped from.

A first solution we agreed upon in the ClusterClass proposal is to enhance the webhooks so when editing a Cluster changes are validated against the ClusterClass and vice versa. Now that we are getting to the next level of detail on this solution we recognise that this approach introduces an ordering in operations. e.g. A ClusterClass must be created before a Cluster using it is created.

This issue is for discussion of tradeoffs and implications of this approach that provides immediate feedback to the user and prevents misconfiguration, but could require additional considerations for operators, particularly those using gitops with CAPI and ClusterClass.

**Detailed description of the problem**

In our validation webhooks we would like to add a client so that we can validate Clusters and ClusterClasses against each other. 
This is becoming more important with the addition of patches and variables to ClusterClass:  #5460

Some of the high level use cases are:

1. Ensure no MachineDeploymentClass in use is removed. (ClusterClass webhook needs to check all Clusters)
2. Ensure an invalid or non-existent variable is not used in a Cluster spec (Cluster webhook needs to check the ClusterClass)

[There is a Google sheet with a more complete list of the operations where we would like to use data from the API server to validate Clusters and ClusterClasses, the impact of avoiding validation, and the alternatives.
](https://docs.google.com/spreadsheets/d/1Stx7_LwSr_J7NFzAu0pt7O7mbvJH8eKrjvPrYAHbNnA/edit?usp=sharing)

This type of validation would introduce a specified ordering in operations on Clusters and ClusterClasses. In many cases ClusterClass operations would have to take place before Cluster operations as the ClusterClass is being used to validate Clusters.

Before following this validation strategy we'd like to understand the impact of introducing strict ordering for changes to ClusterClasses and Managed Clusters on users and other members of the community.

**Comment by fabriziopandini** [comment]
@ykakarap FYI this could have Implications for clusterctl move^^

**Comment by sbueringer** [comment]
Related Slack thread: https://kubernetes.slack.com/archives/C8TSNPY4T/p1635520879223800

Reposting my opinion from there:

I lean towards strict validation and adding an annotation as escape-hatch if it becomes necessary.

I think the situation is somewhat similar to creating CRDs and CRs, so I assume/hope there is a way that GitOps tools can deal with something like this. (although as Vince said in Slack, some GitOps tool might have builtin support for CRDs to handle this)

Note: It’s not **only** about validation, we also have a defaulting webhook (which runs before validation) and it should set default values for variables. The general pattern is here that default values are set on resource create/update and then stored in etcd. I think it would be nice to also follow this pattern with variable default values (although I think we could deviate from that or find workarounds for cases where the webhooks are not run, if we want to make that possible)

**Comment by enxebre** [comment]
Related https://github.com/kubernetes-sigs/cluster-api/pull/5582/files#r743598315

**Comment by fabriziopandini** [comment]
/close
given that no objection were raised, the first implementation has been completed according to the proposal thus introducing a ordering between operation on a ClusterClass and Clusters using that one
