### ISSUE TITLE
rename `annotations.HasPausedAnnotation(obj)` - function name stutters

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#5539]
**Detailed Description**

The function name `annotations.HasPausedAnnotation` stutters. Consider renaming it to something like `annotations.HasPaused`?

**Anything else you would like to add:**

Since this will be an exposed API change we cannot directly rename the function. 
Steps to follow:
* Create the a new function `HasPaused` in the `util/annotations` package.
* Add a deprecation comment on `HasPausedAnnotation`
  * Example: `// Deprecated: use HasPaused instead.`
* Update all usages of `HasPausedAnnotation` to use `HasPaused`.

/kind feature
/help
/good-first-issue

**Comment by tamboliasir1** [comment]
Hi @ykakarap.. That means HasPaused should be copy of HasPausedAnnotation? And HasPausedAnnotation should have deprecated message? and how above issue going to affect this issue? Can you give me bit insight I would like to work on this.

Thanks

**Comment by ykakarap** [comment]
@tamboliasir1 Thanks for volunteering to work on the issue! 🚀

>That means HasPaused should be copy of HasPausedAnnotation? And HasPausedAnnotation should have deprecated message?

Yes. This is correct.

>and how above issue going to affect this issue?

If the `unit/annotations` package moves into `internal` then we can directly refactor `HasPausedAnnotation` into `HasPaused` without having to create a duplicate function and adding the deprecation notice.

For this issue, I think you can go ahead with creating `HasAnnotation` and adding the corresponding deprecation notice on `HasPausedAnnotation`. The clean up can happen in the other issue if needed.

**Comment by tamboliasir1** [comment]
Thank you so much for guidance @ykakarap. I'll work on this.

**Comment by tamboliasir1** [comment]
Hi @ykakarap.. I have one question.. Do I need to take care of replacing `HasPausedAnnotation` everywhere is it used with `HasPaused`? Or is is taken care while clean up?

**Comment by ykakarap** [comment]
Please replace usages with `HasPaused`.

**Comment by tamboliasir1** [comment]
Got it.. Thank you
