### ISSUE TITLE
Update Documentation for aid in various providers 

### ISSUE THREAD

**Issue by DiptoChakrabarty** [kubernetes-sigs/cluster-api#5546]
**User Story**

I was following the quick start guide for the cluster api project and trying to deploy my cluster in AWS but I was stuck in one the steps of initialising clusterawsadm (this is not present in the aws clusterawsadm specific page also). I was able to figure it out however it would be useful for new developers have the steps outlined for them (as most providers will follow a similar set of steps) and accidentally not mess up their PATH variables or avoid wrong installation methods

**Detailed Description**
I downloaded clusterawsadm from the aws provider releases for linux amd64 however the name was not clusterawsadm

![Selection_046](https://user-images.githubusercontent.com/45638240/139580803-06054e71-0b55-42af-8822-c576b4bfff6b.png)
My proposal is that we have a small section outlining the steps required something like this 
```sh
- wget https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v0.7.1/clusterawsadm-linux-amd64 (Download from the specific provider releases)
-  mv clusterawsadm-linux-amd64 clusterawsadm  ( Rename it if required )
- chmod +x clusterawsadm (make it executable)
- sudo mv clusterawsadm /usr/local/bin (move to directory in PATH)
- clusterawsadm version (check version if installed properly)
```
This is for the clusterawsadm which can be generalised and added for others to follow
**Anything else you would like to add:**

It seems like a trivial thing and if not required please do close the issue. 

/kind documentation

**Comment by enxebre** [comment]
/help
/good-first-issue

Probably good to add into CAPA if it's not there as well cc @randomvariable.

**Comment by randomvariable** [comment]
> Probably good to add into CAPA if it's not there as well

CAPA uses a copy of the CAPI quick start, so if it's updated here, CAPA will get updated on the next netlify deploy,

**Comment by DiptoChakrabarty** [comment]
I want to take this up

**Comment by fabriziopandini** [comment]
/lifecycle frozen
there is a PR to fix this
