### ISSUE TITLE
Check if cluster-api prow image still needs etcd

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes-sigs/cluster-api#555]
Currently the cluster-api image used by prow for our jobs contains etcd: https://github.com/kubernetes/test-infra/blob/2e10a0bbe9b34737fa022d71187528b4c4721322/images/cluster-api/Dockerfile

We should check out if this is still required and if not remove etcd from it.

**Comment by roberthbailey** [comment]
I think that since we have scripts to install kubebuilder that it shouldn't be needed.

**Comment by alvaroaleman** [comment]
This is indeed not needed, `scripts/ci-test.sh` works perfectly fine in a normal `golang` docker image
