### ISSUE TITLE
RFE: One shot deployment

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api#557]
There are several use cases where having a bootstrapping cluster is actually an impediment.  We should try to structure the framework to support such use cases for traditional deployment methods.  In this scenario, clusterctl logs inline the deployment of a cluster, and controller run in a one-shot mode to deploy the cluster.

**Comment by timothysc** [comment]
This will force abstraction layers in the code, which I'd argue would be good for the long-term health of this project.

**Comment by roberthbailey** [comment]
Do you have suggestions for how clusterctl would interact with the target environment? The reason we ended up with minikube was so that we could easily run the environment specific code in a consistent way.
