### ISSUE TITLE
Consider using latest kustomize (v4.4.0)

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5570]
We're currently using kustomize 3.9.1. At least CAPA is already using kustomize v4.4.0 (==latest as of now) (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/hack/tools/go.mod#L23).

I think it would be great to keep our kustomize dependency up-to-date if there are no reasons to stay on the old version.

If we want to change it, currently we only would have to change the version in hack/ensure-kustomize.sh
(after https://github.com/kubernetes-sigs/cluster-api/issues/5569, it might be different)

/kind feature

**Comment by randomvariable** [comment]
The only breaking change from v3 to v4 is that AWS and GCP dependencies were pulled out, which meant S3 and GCS support for URLs were dropped, neither of which we're using.

**Comment by fabriziopandini** [comment]
Putting in the milestone given that this is a developer tool
/milestone v1.1
