### ISSUE TITLE
Support JSON log format

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5571]
**User Story**

As a user I would like to be able to run the CAPI controllers with JSON log format as it's easier to parse (e.g. could be easily parsed in Loki LogQL queries).

**Detailed Description**

We're already using structured logging in our code (on the logger with k/v pairs), but it's currently not possible to actually configure our controllers to log in JSON format.

**Anything else you would like to add:**

This issue came up here: https://github.com/kubernetes-sigs/cluster-api/pull/5336#issuecomment-953579895

/kind feature
(couldn't find a better area)
/area health

**Comment by sbueringer** [comment]
@randomvariable Can you maybe please add some additional context. It sounded like there is more history / related issues on this (https://github.com/kubernetes-sigs/cluster-api/pull/5336#issuecomment-953830336).

**Comment by vincepri** [comment]
Let's make this an opt-in flag

/milestone v1.1

**Comment by sbueringer** [comment]
Update from the exploration on PR https://github.com/kubernetes-sigs/cluster-api/pull/6072:

* klog does not support the JSON log format
* components-base/logs supports the JSON log format

I think we should consider using components-base/logs as it provides us a lot of useful features:

* support for JSON log format via --logging-format (default is "text" as "json" is currently alpha: [doc](https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#json-log-format))
* --experimental-logging-sanitization flag which enables the klog SanitizingFilter. This sanitizes logging of types like crypto/x509.Certificate automatically and also allows as to flag fields on structs for sanitation.
* klog flags are deprecated in sync with core Kubernetes components ([kep](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components#removed-klog-flags))
    * flags are deprecated as soon was use component-base/logs 
    * k/k is planning to drop the flags in 1.26 (we could drop them earlier or support them longer if we want)
    * Note: those flags are not deprecated in klog itself, only in k/k through component-base/logs (more details in the KEP)

My opinion.

I think it makes sense to deprecate the klog flags in ClusterAPI too for the [same reasons mentioned in the KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components#removed-klog-flags) (tl;dr mainly 12 factor apps => drop flags for file logging). 
I also think it makes sense to use `component-base/logs` as we get JSON logging for free, without having to implement a JSON logger ourselves. Downside is that we depend on upstream k/component-base, but I think this should be fine or even an advantage when we want to align with upstream components.


Related issues:
* [klog flags have been deprecated in Kubernetes #6069](https://github.com/kubernetes-sigs/cluster-api/issues/6069)
    * After adopting component-base/logs the deprecation would be handled by that package for us.
* [Components logs sanitization #3889](https://github.com/kubernetes-sigs/cluster-api/issues/3889)
    * component-base logs adds the `--experimental-logging-sanitization` flag to enable log sanitation in klog.
    
References:
* [klog documentation including flag deprecation](https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#klog)
* [KEP-2845: Deprecate klog specific flags in Kubernetes Components](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-spstatuecific-flags-in-k8s-components)
* [JSON log format documentation](https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#json-log-format)
* [KEP-1602: Structured Logging](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging) (outlines advantages of the JSON output format)

**Comment by sbueringer** [comment]
Just fyi. The klog version we currently use has an issue that it doesn't propagate verbosity correctly, i.e. with JSON log format the `v` key is always `0`. This issue has been just fixed in klog: https://github.com/kubernetes/klog/issues/294. 

I expect that there will be a new klog version that we can pick up with the next Kubernetes / controller-runtime release before our release.

Independent of that, I don't think it should block us, as the JSON log format is currently alpha.
