### ISSUE TITLE
Add Prometheus to tilt

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5572]
**User Story**

As a developer it would be great to have an option to deploy Prometheus via `tilt up` to play around with metrics/ alerts.

**Anything else you would like to add:**

There is a PR open to add Loki/Grafana/Promtail to tilt (https://github.com/kubernetes-sigs/cluster-api/pull/5336). This issue builds upon this work and adds Prometheus.

We have to:
* deploy Prometheus
* make sure Prometheus is able to scrape our controllers (metrics port of the controllers must be available + Prometheus discovery)
* Prometheus should be available via the Tilt dashboard

/kind feature

**Comment by fabriziopandini** [comment]
Adding to milestone next given that this is not release to any specific milestone, but the sooner the better
/milestone Next
