### ISSUE TITLE
Makefile targets re-shuffle

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5574]
The CAPI Makefile is getting bigger, and we should consider if/how to make things easier to use for the new comers and for the existing maintainers as well.

A possible set of actions to make this happen using the current machinery in place is to:

- [ ] standardise targets names (e.g. some of them use kcp/cabpk/capd suffix, some other the full name of the same components)
- [ ] standardise targets documentation (e.g all with or without a final dot, consistent wording etc. etc)
- [ ] ensure all the make targets are documented/available (e.g. not all the verify checks have a dedicated target, same for hack tools)
- [ ] re shuffle make targets order, so that we can group things in sections by adding comments starting with ##@ 

Note: activities can go in separated PRs if this helps in making this happen.

A mock of a possible outcome of this activity is:

<img width="1180" alt="Screenshot 2021-11-02 at 22 41 56" src="https://user-images.githubusercontent.com/5013060/139955841-39629850-f901-405e-b48c-3efcd73fda87.png">

NOTE: once this work is completed, then it will be easier to:
- [ ] get rid of nested Makefile in the Cluster API code base, thus simplifying dev-X and maintenance
- [ ] identify and create additional targets, e.g around starting e2e with a single command, or creating a local repository for clusterctl development

/kind feature

**Comment by mrajashree** [comment]
@fabriziopandini I'd like to work on this

**Comment by sbueringer** [comment]
@mrajashree Feel free to assign yourself the issue :)

**Comment by Prajyot-Parab** [comment]
@fabriziopandini I am working on something similar, will be happy to contribute on this one.

/assign @Prajyot-Parab
