### ISSUE TITLE
ClusterClass builtin variables: labels & annotations semantic and use cases

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5577]
The current [ClusterClass proposal](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/202105256-cluster-class-and-managed-topologies.md#builtin-variables) includes the following builtin labels & annotations variables:
* `cluster.{labels,annotations}`
* `cluster.topology.controlPlane.{labels,annotations}`
* `cluster.topology.machineDeployment.current.{labels,annotations}`

### Semantic

During implementation of the [first ClusterClass patch PR](https://github.com/kubernetes-sigs/cluster-api/pull/5534) we discovered that the semantics of labels & annotations might be problematic, if we just try to set the variables in a way which would make sense according to the variable name.

* Cluster: relatively straight-forward: (same as top-level labels/annotations on the Cluster resource after reconcile)
    * `cluster.labels`: Cluster.labels (user-defined/pre-reconcile) + `cluster.x-k8s.io/cluster-name` + `topology.cluster.x-k8s.io/owned` 
    * `cluster.annotations`: Cluster.annotations (user-defined/pre-reconcile) 

* MachineDeployment: (same as top-level labels/annotations on the MachineDeployments)
    * `cluster.topology.machineDeployment.current.labels`: `cluster.x-k8s.io/cluster-name` + `topology.cluster.x-k8s.io/owned` + `topology.cluster.x-k8s.io/deployment-name`
    * `cluster.topology.machineDeployment.current.annotation`: none, because we don't set any

=> The labels we set on the MachineDeployment are not especially useful for patches as all labels with values are also available via other builtin variables. Users might expect that labels/annotations from the MachineDeploymentTopology or MachineDeploymentClass are set here. They are not, because we currently only set them in `.spec.template.metadata` in the MachineDeployment and not top-level.

* ControlPlane (same as top-level labels/annotations on the ControlPlane)
    * `cluster.topology.controlPlane.labels`: `cluster.x-k8s.io/cluster-name` + `topology.cluster.x-k8s.io/owned`
    * `cluster.topology.controlPlane.annotations`: none, because we don't set any

=> The labels we set on the ControlPlane are not especially useful for patches as all labels with values are also available via other builtin variables. Users might expect that labels/annotations from the ControlPlaneTopology or ControlPlaneClass are set here. They are not, because we currently only set them in `.spec.machineTemplate.metadata` in the ControlPlane and not top-level.

To summarize:
* the only labels/annotations which have a clear semantic are the ones from the cluster

Q: What label/annotations values would have the right UX for users?

### Use cases

It's currently not clear in which way labels & annotations would be consumed in patches.

With inline patches, they can only be used to overwrite other map[string]string fields as we don't allow accessing individual labels/annotations via `valueFrom.template`. So we can only use them to overwrite other maps, which are usually other labels/annotations. I'm not sure if it's a good idea to take labels/annotations from the Cluster, MD or ControlPlane and overwrite other labels/annotations in one of the referenced templates of a ClusterClass.

With external patches, they can (probably) be used to pass arbitrary data from e.g. Cluster.labels/annotations to an external patch engine.

### Summary

What do you think about what the semantics should be and how/if would you use those builtin variables?

I personally lean towards not implementing them for now, until we have clear use cases for them. I think we have to get them right the first time, as we probably have to rename the builtin variables if we have to go through a deprecation cycle (I assume our usual API guarantees also apply to builtin variables).

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
I'm +1 to keep things simple in the first iteration and drop builtin variables for labels/annotations until a clear use case for those variables comes up

**Comment by fabriziopandini** [comment]
@sbueringer should we close this and eventually reconsider if the need arise?

**Comment by sbueringer** [comment]
Yup
/close
