### ISSUE TITLE
ClusterClass builtin variables: ClusterNetwork

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5578]
The current [ClusterClass proposal](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/202105256-cluster-class-and-managed-topologies.md#builtin-variables) does not include any builtin variables for `Cluster.spec.clusterNetwork`. This means it's not possible to access any of those fields in ClusterClass patches.

Let's collect use cases (if there are any) for those fields, so that we can add builtin variables accordingly if there is demand.

`spec.clusterNetwork` contains the following fields:

```go
type ClusterNetwork struct {
	// APIServerPort specifies the port the API Server should bind to.
	// Defaults to 6443.
	// +optional
	APIServerPort *int32 `json:"apiServerPort,omitempty"`

	// The network ranges from which service VIPs are allocated.
	// +optional
	Services *NetworkRanges `json:"services,omitempty"`

	// The network ranges from which Pod networks are allocated.
	// +optional
	Pods *NetworkRanges `json:"pods,omitempty"`

	// Domain name for services.
	// +optional
	ServiceDomain string `json:"serviceDomain,omitempty"`
}
```

/kind feature
/area topology

**Comment by fabriziopandini** [comment]
@vuil opinions?

**Comment by vincepri** [comment]
We might want to expose these (or parts) of these variables as builtins, although we should make sure the defaults are also taken into account

**Comment by vuil** [comment]
+1 what @vincepri said as well.

Taking a step back, and a wild thought:
If we do not want to keep having to make this kind of decision with every field we add,
Is it worth considering supporting something like jsonpath or golang template struct syntax to make, say, every primitive field accessible?

**Comment by sbueringer** [comment]
Default values should be handled automatically. The default values are set when the Cluster is created (and before it is stored in etcd). The builtin variables are calculated during reconcile, so they can just consume the fields.


I'm not sure about making every field accessible. 

Context: We're currently using builtin variables to make selected fields of objects which are **not** influenced by patching available (i.e. of Cluster/MD/ControlPlane).

In theory we could probably make more fields accessible. We have the following objects:
* Cluster, MachineDeployments:
    * these objects are not patchable, so their fields don't change during patching
* ControlPlane:
    *  .spec can change during patching (when the ControlPlaneTemplate is patched), although the current builtin variables we expose (replicas/version) cannot be overwritten by patches
* ControlPlaneTemplate, ControlPlane InfrastructureMachineTemplate, InfraClusterTemplate, MD BootstrapTemplate, MD InfrastructureMachineTemplate
    * .spec can change during patching
    * external patching would already have full access to the templates anyway

This definitely requires some thought how **which field** of **which resource** can be selected.

Note: For ControlPlane and the templates we don't know the types of the fields without inspecting the schema in the corresponding CRD.

So overall I think it's an interesting thought but would definitely require significant work to make it happen.

**Comment by fabriziopandini** [comment]
+1 to keep things simple unless there are concrete use cases

**Comment by fabriziopandini** [comment]
Let's consider also surfacing a derived variable called ipfamily

**Comment by sbueringer** [comment]
We had a downstream request for this. I would propose the following additional builtin variables:

* `builtin.cluster.network.apiServerPort` (type integer)
* `builtin.cluster.network.serviceDomain` (type string)
* `builtin.cluster.network.services` (type array of string)
* `builtin.cluster.network.pods` (type array of string)
* `builtin.cluster.network.ipFamily` (type string, one of: Invalid, IPv4, IPv6, DualStack)
  * enum values are inferred from the values of our `ClusterIPFamily` type

The builtin variables are only set if the corresponding fields in the Cluster are set.

I think we should just set the fields that are set on the cluster. We don't have defaulting on any of those fields.

kubeadm defaults the fields, but I don't think that we should guess in the topology reconciler what defaults are used by a bootstrap provider later on. A ClusterClass author can implement defaulting by using a template and falling back to kubeadm default values when the builtin variables are not set.

@vuil @vincepri @fabriziopandini  @weikaipan What do you think?

**Comment by weikaipan** [comment]
One of our use cases is configuring proxy

```
      proxy:
        ...
        #noProxy is the list of destination domain names, domains, 
        #IP addresses, and other network CIDRs to exclude from proxying
        #must include Supervisor Cluster Pod, Egress, Ingress CIDRs
        noProxy: [string]
```

which needs access to pod and service CIDRs.

**Comment by sbueringer** [comment]
/assign
(to keep track of it)

**Comment by vincepri** [comment]
Would we ever want anything else under `ip`? Should we go for `ip.family` instead?

**Comment by sbueringer** [comment]
> Would we ever want anything else under `ip`? Should we go for `ip.family` instead?

Hm, I don't know. I don't foresee anything right now. I would probably use `ipFamily`, but no objections if we want to use `ip.family`.
