### ISSUE TITLE
Move Cluster and Clusterclass validation checks to the top-level webhooks package

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5594]
Since #5266 and #5518 we are using webhooks defined in the /webhook package for Cluster and ClusterClass. The implementation of the validation logic is still contained in the api package, however and are currently being called through  deprecated public methods in the api package.

This structure makes it difficult to add new checks to the webhooks as in #5585. [Note this discussion](https://github.com/kubernetes-sigs/cluster-api/pull/5585#discussion_r743082805)

The implementations for validation for Clusters and ClusterClass should be moved to the top-level webhook package.

**Comment by enxebre** [comment]
>The implementations for validation for Clusters and ClusterClass should be moved to the top-level webhook package.

@killianmuldoon you meaning to duplicate them until we drop the old methods?

**Comment by killianmuldoon** [comment]
Yeah - I'll duplicate everything in the webhooks package.

**Comment by enxebre** [comment]
no objections here, though what's the benefit vs keeping existing api.Validate call and having additional nil checks if needed? - I guess that might not scale well.
/milestone 1.1

**Comment by killianmuldoon** [comment]
@enxebre One of the main issues is with properly aggregating errors as we add new checks in the webhooks package - https://github.com/kubernetes-sigs/cluster-api/pull/5585#discussion_r743082805 so it's a question of hacking around that temporarily while waiting for 1.1 or else just inlining the function calls in the new package now.
