### ISSUE TITLE
Consider using fastjson when manipulating json bytes

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#5598]
This library https://github.com/valyala/fastjson seems interesting when it comes to manipulating json objects, which operates only on bytes. We're performing json manipulation in a number of places, we should try to switch the topology's code first.

/kind cleanup
/assign @fabriziopandini

**Comment by fabriziopandini** [comment]
/close

given recent changes in the topology controller this is not relevant anymore
