### ISSUE TITLE
Cluster/ClusterClass: variable validation and defaulting

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5612]
Goal of this issue is to implement validation (Cluster and ClusterClass) and defaulting (Cluster) of variables.

This includes:
* ClusterClass: (create/update webhook)
    * validate variable schemas
    * validate variable names are unique, not empty and don't start with `builtin`
* Cluster (create/update webhook)
    * default variables (if they don't exist)
    * validate variables based on the corresponding schema in the ClusterClass
    * validate that required variables exist
    * validate that existing variables have corresponding variable in ClusterClass

/kind feature
/area topology
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
Q: should we consider adding some safeguard, redundant validations in the reconcile loop (same as we are already doing for compatibility)?

**Comment by sbueringer** [comment]
Good question, we were thinking we leave it out of the first PR, but then introduce it with the other compatibility checks Killian is working on in the reconciler too.

(If I got it correctly, please correct me if I'm wrong @killianmuldoon)

But for me it would be also fine to already introduce it in the first PR, I think eventually we should have them

**Comment by fabriziopandini** [comment]
What is important to me is to keep this point into the radar, and it seems it is.
Then, I'm ok in breaking down the work at your convenience
