### ISSUE TITLE
ClusterClass: patch validation

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5613]
Goal of this issue is to extend our existing ClusterClass webhook (create and update), to also validate patches 
as described in the proposal.

More details can be found in the ClusterClass proposal in: Validations | ClusterClass | ClusterClassPatch and PatchDefinition

/kind feature
/area topology

**Comment by sbarikdev** [comment]
I have a couple of questions I'd like to get alignment on before taking a proper run at this:

Are we assuming that listing all clusters using a clusterclass from the webhook is the supposed mechanism for ensure variables aren't in use currently? Or is there some other semaphore or lock that could be used?

The overall question I'm running into is how much validation we want to do against existing clusters / variables to make sure existing values are in line with proposed changes?

We could:

Only validate new values - this would be fine for e.g. MaxLength but fails with ExclusiveMaximum.
validate everything against existing values and only allow schema changes that are compatible with all existing usages.
do careful validation to ensure incompatible changes are not possible. e.g.:
Maximum can only be increased
Minimum can only be decreased
ExclusiveMaximum can never be changed
Enum can only be added to
MultipleOf can only be changed to one of its factors(😆 probably not very useful)

**Comment by sbueringer** [comment]
@sbarikdev Your comment seems to be copied from: https://github.com/kubernetes-sigs/cluster-api/issues/5461#issuecomment-948792415 and thus doesn't make sense in the context of this issue.
