### ISSUE TITLE
`clusterctl move` should move ClusterClass before Clusters

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#5620]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**

The current move operation treats both ClusterClass and Clusters as roots of the move graph.

With https://github.com/kubernetes-sigs/cluster-api/pull/5596 merged there is now a requirement that we have to make sure that a ClusterClass exists in the Cluster before a cluster can use it.

Ref https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main to see that the move e2e tests (self-hosted e2e tests using ClusterClass) are failing because of this.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
/area clusterctl
/area topology

/assign @ykakarap

**Comment by fabriziopandini** [comment]
@ykakarap thanks for filing this issue
I'm happy to chat about possible solutions if this can help

**Comment by killianmuldoon** [comment]
👍  I knew there'd be fallout - I'd forgotten this test had merged. Let me know if there's anything I can help with @ykakarap

**Comment by ykakarap** [comment]
>👍 I knew there'd be fallout - I'd forgotten this test had merged. Let me know if there's anything I can help with @ykakarap

I opened a PR for this. It would be great if you can review it. #5625

**Comment by sbarikdev** [comment]
@ykakarap can you please mention what steps did you perform in this [#5625](https://github.com/kubernetes-sigs/cluster-api/pull/5625)
