### ISSUE TITLE
Is it possible to omit conditions when they don't apply to a given cluster?

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api#5624]
I discussed with @CecileRobertMichon about finding a way to omit conditions when they don't apply to a given AzureCluster. For example, there is a ready condition for virtual network peerings called `VnetPeeringsReady`, and if there are no virtual network peerings, then it would make sense to omit that condition since it doesn't apply. However, currently `VnetPeeringsReady` is set to `true` so it doesn't block the overall ready status of the AzureCluster. Is there a way to omit conditions that don't apply, and if not, I'd be interested in discussing ideas. This could benefit all cluster providers too since it could be helpful to omit conditions that don't apply as more conditions get added.

**Comment by enxebre** [comment]
hey @Jont828 I think what you are describing it's supported today and expected to be implemented in the most meaningful way by each provider. It is up to each provider to model and signal their semantics for each infra piece. Also what it's considered for readiness is a provider choice and we provide reasonable conditions primitives to support that.
See e.g [1], [2], [3].

Please let me know if this makes so we can close it or if you had something else in mind. Thanks!

[1] https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/461ef72c3b647e729298ec5507c3387dabf7b015/pkg/cloud/scope/cluster.go#L209-L233
[2] https://github.com/kubernetes-sigs/cluster-api/blob/cd541a0ef17e032ef4544aa6349ecf8f61654b13/test/infrastructure/docker/controllers/dockercluster_controller.go#L118-L125
[3] https://github.com/kubernetes-sigs/cluster-api/blob/cd541a0ef17e032ef4544aa6349ecf8f61654b13/test/infrastructure/docker/controllers/dockercluster_controller.go#L118-L125

**Comment by CecileRobertMichon** [comment]
@enxebre what we're looking at doing is having granular conditions for every Azure resource (eg. "vnetReady", "loadBalancerReady", etc), and using those conditions to determine the summary ready status of the AzureCluster. However, in some situations, depending on the AzureClusterSpec, some resources don't apply. For example, I'm only going to have a bastion resource if I enable bastionHost. If we show "bastionReady" in the conditions it would be confusing for the user if they don't have a bastion. But if we don't set that condition to true, the Ready condition won't go to true. So we're wondering what would be the best way to only include some conditions in Summary depending on the AzureCluster Spec. Would the best way be to not set `WithConditions` at all and let the controller only use the set conditions, assuming that we would set the relevant ones to false until the reconciliation succeeds ? Or do we need to have some sort of conditional logic for SetSummary based on the spec (I'd rather avoid this option if possible).

**Comment by fabriziopandini** [comment]
@Jont828 @CecileRobertMichon  If you don't add the `WithConditions` option, then the summary will be computed on all the existing conditions (excluding ready). Relevant code is https://github.com/kubernetes-sigs/cluster-api/blob/fc52fe3d5cfe05d436a7d2f0ba3cf8a1399aad59/util/conditions/getter.go#L129-L153

The `WithStepCounterIf` instead controls when the conditions message will be in the form of 1 of x, with is something that makes sense under certain circumstances, like e.g. when provisioning, but not in others (in the example above when deleting)

**Comment by enxebre** [comment]
>Would the best way be to not set WithConditions at all and let the controller only use the set conditions, assuming that we would set the relevant ones to false until the reconciliation succeeds ? Or do we need to have some sort of conditional logic for SetSummary based on the spec (I'd rather avoid this option if possible).

I see, I'm not sure we can/should provide a reasonable abstraction for providers but rather may be agreeing and documenting some best practices?

As a general patter I think it'd make sense for a provider to:
- Set all relevant conditions (spec check here) to false/unknown.
- Check current state of the world. Set each condition as true where appropriate.
- Call SetSummary so it uses all existing conditions.

wdyt?
though that wouldn't preclude other legit approaches as in [aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/461ef72c3b647e729298ec5507c3387dabf7b015/pkg/cloud/scope/cluster.go#L209-L233)

**Comment by fabriziopandini** [comment]
> Would the best way be to not set WithConditions at all 

Please note that this comes with a disadvantage, because if an external controller adds a Condition to your object, then the semantic of your ready condition gets altered; `WithConditions` solve this pinning the semantic of your ready condition to a well know set of conditions.

**Comment by CecileRobertMichon** [comment]
Opened https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1868 to track changes needed in CAPZ

we can close this one since no changes are required in CAPI for now
/close
