### ISSUE TITLE
"vsphere" provider: failed to set the TargetNamespace

### ISSUE THREAD

**Issue by sbarikdev** [kubernetes-sigs/cluster-api#5628]
I try to install capi and get the following problem.
$ clusterctl init --infrastructure vsphere
Fetching providers
Error: failed to get provider components for the "vsphere" provider: failed to set the TargetNamespace on the components: converting (v1beta1.MutatingWebhookConfiguration) to (v1.MutatingWebhookConfiguration): unknown conversion
my environment is:
$ clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.0", GoVersion:"go1.16.8", Compiler:"gc",Platform:"linux/amd64"}
$ docker version
Client: Docker Engine - Community
Version: 20.10.8
Go version: go1.16.8
$ kind version
kind v0.11.1 go1.16.4 linux/amd64

**Comment by enxebre** [comment]
fwiw I haven't been able to reproduce this so far. based on the code I'd expect it to just work https://github.com/kubernetes-sigs/cluster-api/blob/55e92ea2e2e4311ea17d319c45c11f9218bc8380/cmd/clusterctl/client/repository/components.go#L384

**Comment by sbueringer** [comment]
Same here:
```bash
 clusterctl-v1.0.0 init --infrastructure vsphere
Fetching providers
Skipping installing cert-manager as it is already installed
Installing Provider="cluster-api" Version="v1.0.0" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v1.0.0" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v1.0.0" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-vsphere" Version="v1.0.1" TargetNamespace="capv-system"
```

**Comment by oomichi** [comment]
This seems duplicated with https://github.com/kubernetes-sigs/cluster-api/issues/5171
Is it better to concentrate on the another one by closing this issue?

**Comment by sbueringer** [comment]
@oomichi The user in #5171 is using `clusterctl` `v0.4.1`this issue is about v1.0.0. Although the issue shouldn't occur in my opinion with clusterctl v0.4.2+ or v1.0.0.

**Comment by oomichi** [comment]
> 
> 
> @oomichi The user in #5171 is using `clusterctl` `v0.4.1`this issue is about v1.0.0. Although the issue shouldn't occur in my opinion with clusterctl v0.4.2+ or v1.0.0. (or at least I'm unable to reproduce it)

Thank you for letting me know the difference.
I saw your comment on another issue, it would be useful to use the same issue for both `clusterctl` v0.4.1 and v1.0.0 to understand the issue still happens on newer version.

**Comment by sbarikdev** [comment]
> This seems duplicated with #5171 Is it better to concentrate on the another one by closing this issue?

this issue happens on my side

**Comment by sbarikdev** [comment]
sorry for adding duplicate issue, I did not see the existing issue which I should have. I am closing this issue and will track it on #5171. Sorry again for the noise.
