### ISSUE TITLE
Make CAPD support Remote Docker Server on a Cluster bases

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5634]
**User Story**

As a user I would like to use CAPD without mounting the docker socket
As a developer I would like to use CAPD without starving resources on my local machine
As a developer I would like to use CAPD to run stress tests, deploying workload clusters to a pool of machines

**Detailed Description**

CAPD today talks to a local docker socket via a volume mount.

I would like to make CAPD to support different options to connect to a remote (or local) Docker Server, e.g. via ssh, tcp etc.

/kind feature

**Comment by sbueringer** [comment]
:+1: I would take a look sooner or later

**Comment by fabriziopandini** [comment]
some useful link
https://docs.docker.com/engine/security/protect-access/
https://www.cloudsavvyit.com/11185/how-and-why-to-use-a-remote-docker-host/

**Comment by fabriziopandini** [comment]
update: Given recent changes in CAPD (container.Runtime client passed via context) it is now simpler to target remote docker engine servers on per Cluster basis.
The bit that should be addressed is how to ensure communication from CAPI to remote clusters, given that the current LB solution relies on local addresses + random ports.
