### ISSUE TITLE
enable setting failureDomain as part of a cluster's topology

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api#5636]
**User Story**

As a user would like to reference a clusterClass in a cluster, and configure the failure domain of workers in its topology, to be able to re-use ClusterClass more broadly

**Detailed Description**

Today we don't offer users the ability to configure failureDomain for the various machineDeployment that is part of a `ClusterClass` which limits a bit the re-usability. We likely also need to define what is the default behaviour is when not setting such field in the cluster's topology.

**Anything else you would like to add:**

not the same, but https://github.com/kubernetes-sigs/cluster-api/issues/3358 might impact how we do this. We've had asks from CAPV users to spread machineDeployments across failure Domains (e.g. spread an MD that is GPU enabled)

/kind feature

**Comment by yastij** [comment]
cc @fabriziopandini @CecileRobertMichon

**Comment by fabriziopandini** [comment]
/area topology
/milestone v1.1
@yastij if I got this right it is your intention to work on this, right?

**Comment by fabriziopandini** [comment]
Show we consider also failure domains for control plane machines?

**Comment by yastij** [comment]
@fabriziopandini - yeah, planning to work on this. As for "should we include control plane machines?" I'm not sure we want to.

The options for CP to me are:

1. not specify anything and keep today's behaviour which read from the cluster's status
2. add a failureDomain field, that might not achieve what we want as it'll colocate everything
3. add a list of failureDomains, which is a subset of what's listed in the cluster's status. It gives more control to the user if they don't want to consume an AZ listed in the status, but that would need changes to KCP.

for `ControlPlane` I'm leaning towards 1, for `Workers` I'm leaning toward 3 as it has real use cases for workers. But not against aligning options for both (for the sake of consistency)

**Comment by vincepri** [comment]
+1 to keep control plane delegated to the control plane provider

**Comment by CecileRobertMichon** [comment]
+1
