### ISSUE TITLE
Is the label `cluster.x-k8s.io/control-plane` still used for indicating control plane CRDs?

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api#5637]
I'm trying to sort resources like Machines, AzureMachines, and AzureMachineTemplates into the Worker category and ControlPlane category like in  `clusterctl describe`. The implementation of `clusterctl describe` searches for the label `cluster.x-k8s.io/control-plane: ""` on resources like Machines, but the label is not present on AzureMachineTemplates and I believe it's not present on DockerMachineTemplates either. Should that label be added to the machine template types? Or is that label deprecated/no longer used to indicate control plane CRDs?

/kind bug

**Comment by sbueringer** [comment]
I think the intention of the label is to signal which Machines and InfrastructureMachines are control plane machines. I don't think we should set the label on the corresponding templates, based on where the templates are referenced. Especially as a template can be used e.g. in KCP and in a MachineDeployment at the same time.

**Comment by fabriziopandini** [comment]
Echoing https://github.com/kubernetes-sigs/cluster-api/issues/5638#issuecomment-966388354

/remove-kind bug
/priority awaiting-more-evidence

**Comment by vincepri** [comment]
/milestone Next

The labels is actively used on Machines that are control plane machines, you can still create a control plane without a control plane provider (like KCP). The templates though usually shouldn't have the label attached, given that's only valid on a Machine object.

**Comment by Jont828** [comment]
Gotcha, thanks for letting me know. I synced with Fabrizio and I'll look into the clusterctl discovery service a bit more.
