### ISSUE TITLE
Adding UIDs to `controlPlaneRefs` and  `infraStructureRefs` for Clusters

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api#5638]
I would like to create a lookup table for CRDs on a cluster so that when I follow the refs, I can find immediately look up the resource it refers to. I think it makes sense to use the UIDs as a the key, but I noticed all of the refs include the UID except for Cluster, which has `controlPlaneRefs` and  `infraStructureRefs` with only the name and kind. Is it possible to add the UIDs to the refs for Clusters?

/kind feature

**Comment by sbueringer** [comment]
I'm not sure we should. 

My impression is that we are intentionally only using the apiVersion, kind, name and namespace fields of `ObjectReference`.

The advantage is that we don't have to reconcile all our ObjectReferences (uid is not known to users at the time when they create the resources).

**Comment by fabriziopandini** [comment]
I'm personally -1 for this change, this will have undesired side effects to operations like move

> when I follow the refs, I can find immediately look up the resource it refers to

We are doing this in several places in CAPI, and it is not required to have UID to do so.
/priority awaiting-more-evidences

**Comment by fabriziopandini** [comment]
@Jont828 if I got it right this is for your CAPI UX project.
Might be it makes sense we sync up and we try to convey your requirements into "sigs.k8s.io/cluster-api/cmd/clusterctl/client/tree", so there will be a single discovery library with different UX on top

**Comment by Jont828** [comment]
@fabriziopandini Yep, that #5637 are both questions that I came up with when brainstorming ideas on discovery. Let's sync up and chat more about it soon.

**Comment by vincepri** [comment]
Having UIDs can break easily when moving a cluster, would suggest to always use names instead

**Comment by Jont828** [comment]
Okay that makes sense. I synced with Fabrizio and I'll look into the clusterctl discovery service and see what it's doing.
