### ISSUE TITLE
ClusterClass: Add documentation fields for variables and patches

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5649]
**User Story**

As a user of a ClusterClass it would be great if a ClusterClass provides additional information for patches and variables.

**Detailed Description**

One way to implement this would be to add additional fields (like `description`) to our Patch and Variable structs of the ClusterClass.

**Anything else you would like to add:**

For variables this can be implemented by introducing additional optional fields on the `JSONSchemaProps` struct. CRDs already have a few of them we just didn't add them to our copy of the `JSONSchemaProps` struct for the first iteration.

Some candidates are: (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema.go)
* Description
* Example
* ExternalDocs

It would be great to do it in a way which is compatible with CRDs and thus OpenAPI schema v3. This way those informations can be used later on by tools like CLIs or UIs to provide helpful information for users which want to create new Clusters or want to understand the variables of a ClusterClass (cf. what Swagger UI is doing with fields: https://petstore.swagger.io/#/pet/uploadFile)

/kind feature
/area topology

**Comment by fabriziopandini** [comment]
I'm +1 for Description + Example, 0- for External Docs mostly because it introduce a new struct

**Comment by sbueringer** [comment]
Agree. I would add Description and Example
