### ISSUE TITLE
Support external scalers for infrastructure managed by a MachinePool

### ISSUE THREAD

**Issue by dthorsen** [kubernetes-sigs/cluster-api#5658]
**User Story**

As a cluster operator, I would like to have the option to utilize external scaling applications for autoscaling infrastructure managed under a MachinePool so that we can take advantage of the capabilities of existing infrastructure scaling tools if we chose.

**Detailed Description**

There are many potential scaler implementations that support things like AWS ASG and Azure VMSS. With a small change, cluster-api can be made to optionally allow external software to manage the scaling of the node pools without needing to have support for cluster-api. Some examples of scalers that would benefit from this solution are:

- Kubernetes cluster-autoscaler using the existing cloud-provider implementations. This provides a stopgap while cluster-autoscaler's support for CAPI MachinePools to mature and reach feature parity with the existing cloud provider implementations. Incidentally, this would also allow the CAPZ provider add AKS' native managed node pool autoscaling support, which provides an fully-managed installation of cluster-autoscaler on the AKS control plane itself completely managed by the cloud provider, Azure.
- [Atlassian escalator](https://github.com/atlassian/escalator)
- Spotinst (an infrastructure provider for spotinst does not yet exist but interest has been expressed by the community for one to exist)

/kind feature

**Comment by dthorsen** [comment]
Related issue with more history and discussion: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2022

**Comment by fabriziopandini** [comment]
/triage needs-information
/unassign @dthorsen 

@CecileRobertMichon  is this still something on your radar?

**Comment by CecileRobertMichon** [comment]
@jackfrancis was in #7107

/assign @jackfrancis

**Comment by AverageMarcus** [comment]
This can be closed now with the release of https://github.com/kubernetes-sigs/cluster-api/pull/7107 right?

/cc @dthorsen @jackfrancis

**Comment by jackfrancis** [comment]
@AverageMarcus yes! (I don't seem to have privileges to do that)

**Comment by jackfrancis** [comment]
nevermind just had to use the right slash-verb
