### ISSUE TITLE
Improve FailureDomain handling in CAPI

### ISSUE THREAD

**Issue by Arvinderpal** [kubernetes-sigs/cluster-api#5667]
**User Story**

As a user/operator of a non-cloud provider cluster (e.g. baremetal), I would like CAPI to label Nodes with the [well-known label](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone) that corresponds to the failuredomain that was selected by CAPI. 

As a user/operator I would like to have more control over how CAPI balances my control-plane and worker nodes across failuredomains. For example, one of my failuredomains has less infra resources then the others; equal distribution, as is done today, would not work well for me. 

As an operator who uses (or wants to use) cluster-autoscaler, I want CAPI failuredomains and [cluster autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/clusterapi) to play nicely.

**Detailed Description**

Creating this issue to document and discuss how we can improve on the current FailureDomain support in CAPI. 

/kind feature

**Comment by Arvinderpal** [comment]
@vincepri @fabriziopandini @enxebre @elmiko 
I'm sure some or all of these points have been brought up before, but I could not find an issue on failuredomains that documented them. Perhaps we can use this issue to discuss the scope of failuredomains going forward. 
Your thoughts are much appreciated.

**Comment by vincepri** [comment]
This seems a good addition, for cloud providers it might be redundant information given that there should already be labels to that effect

cc @CecileRobertMichon @fabriziopandini @enxebre 
/milestone v1.1

**Comment by elmiko** [comment]
+1 to using the well know label for this, the autoscaler is already of aware of that label and takes it into account when the user has specified `--balance-similar-node-groups` for the autoscaler.

**Comment by enxebre** [comment]
As noted by Vince this should be already the case for environments with a cloud provider https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone

If we do this it might be part of https://github.com/kubernetes-sigs/cluster-api/issues/493.

**Comment by Arvinderpal** [comment]
@enxebre While this could get roped in with #493, I think there is simpler solution. CABPK could append the label to the join/init configs. If the user has specified FailureDomains, Machine.Spec.FailureDomain should already be set by the time we get to CABPK. If this field is set, it will insert the well-known label for the kubelet.

The zone label is one of specifically allowed labels in the kuberenetes.io/ namespace for the kubelet to set. See `--node-labels` [here](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/).

**Comment by fabriziopandini** [comment]
/remove-lifecycle rotten
I think that this is valuable, but IMOT it is is required to start a design doc trying to figure out a way forward for improving failure domain because this impacts:
- How failure domain are defined (they currently surface from infrastructure)
- How they are consumed by CAPI - how the user should express its preferences

Also, notably, there are some other well know limitations to the failure domain, such as the lack of a state notion or any rebalancing process.

**Comment by fabriziopandini** [comment]
/triage accepted
/help

This still need to figure out long term plan for failure domain
related to https://github.com/kubernetes-sigs/cluster-api/issues/5666
