### ISSUE TITLE
KCP Controller complains about Failed to watch *v1.PartialObjectMetadata: unknown

### ISSUE THREAD

**Issue by kashifest** [kubernetes-sigs/cluster-api#5672]
When we provision a cluster with one KCP the logs of KCP has the following error in almost every reconcile:

`E1115 13:06:15.103368       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1.PartialObjectMetadata: unknown`

This has started to come in the logs of KCP possibly from CAPI v1alpha4 and it has continued in v1beta1. The possible culprit is the missing verb `watch` in the rbac of KCP controller for CRD api extensions [here](https://github.com/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/controllers/controller.go#L60)

As soon as I edit the clusterrole of `capi-kubeadm-control-plane-system-capi-kubeadm-control-plane-manager-role `and add the `watch` verb manually the error seems to be gone.

**Comment by fmuyassarov** [comment]
Seems a RBAC rule related to `customresourcedefinitions` was added in https://github.com/kubernetes-sigs/cluster-api/commit/408f30bada3e2994f93ea1dddd468682f8e63bcb.
Perhaps @sbueringer has some thoughts on this?

**Comment by sbueringer** [comment]
@fmuyassarov I'll respond on the PR to avoid having two parallel discussions: https://github.com/kubernetes-sigs/cluster-api/pull/5675#discussion_r750136258
