### ISSUE TITLE
Speed up e2e test execution when using an existing cluster

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5677]
**User Story**

As a developer I would like to be able to run and develop e2e tests with an existing cluster with the shortest possible feedback loop.

**Detailed Description**

Context:
* e2e tests can be run locally as documented here: https://cluster-api.sigs.k8s.io/developer/testing.html#running-the-end-to-end-tests-locally

When running the e2e tests locally in the default case the test will
1. create a new kind cluster
2. create a local clusterctl repository
3. deploy the providers via clusterctl init (using the local clusterctl repository)
4. and then start the actual test.

With the changes proposed in this issue we can get to a state where the actual test starts after ~ 1-2 seconds.

It's already possible today to skip steps 1. and 3.  by setting `-e2e.use-existing-cluster=true` (clusterctl init is automatically skipped when the providers are already deployed).

Unfortunately step 2. takes about 1-2 minutes because we have to download 4x2 component files from Github (v0.3.x, v0.4.x, in the future also v1.0.x) and run kustomize 4x.

I would like to propose adding a flag called `-e2e.local-clusterctl-repo=<path-to-clusterctl-config.yaml>` which would allow us to skip the following step if it is set:
https://github.com/kubernetes-sigs/cluster-api/blob/ec1fa651a3791f356057517193c90d284ae920b8/test/e2e/e2e_suite_test.go#L120-L121

**Anything else you would like to add:**

When this issue and https://github.com/kubernetes-sigs/cluster-api/issues/5676 are implemented the following workflow will be possible:
```bash
./hack/kind-install-for-capd.sh
tilt up
<create local clusterctl repo> (e.g. by just running the tests without the flag once)
<start e2e tests with use-existing-cluster and local-clusterctl-repo flags>
```
This will provide us a very short feedback loop to develop and debug e2e tests.

/kind feature
/area testing

**Comment by fabriziopandini** [comment]
I'm generally +1, however in the workflow above we should account for an additional step to create the local repository

/milestone Next
Given that this doesn't have a real dependency on a release, but the sooner, the better

**Comment by sbueringer** [comment]
> I'm generally +1, however in the workflow above we should account for an additional step to create the local repository

I've added a step just if someone else read it later.

**Comment by sbueringer** [comment]
Note: The flag can of course also be used in combination with  (https://cluster-api.sigs.k8s.io/clusterctl/developers.html#create-the-local-repository)
