### ISSUE TITLE
Drop topology managed fields from KubeadmControlPlaneTemplate

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5678]
**User Story**

As a user it would be nice if I don't have to specify fields in KubeadmControlPlaneTemplate which are not used and on the KubeadmControlPlane managed by the Cluster topology controller.

**Detailed Description**

The following fields in KCPTemplate are currently unused (some of them have to be set because of the webhook):
* .spec.template.spec.machineTemplate.infrastructureRef
* .spec.template.spec.machineTemplate.metadata
* .spec.template.spec.replicas
* .spec.template.spec.version

Note: There is also `.spec.template.spec.machineTemplate.nodeDrainTimeout`, but this one is taken from the template and not managed by the topology controller.

**Anything else you would like to add:**

Proposed solution:
* Let's deprecate the fields listed above in the KCPTemplate
    * Note: this requires duplication of `KubeadmControlPlaneSpec` and `KubeadmControlPlaneMachineTemplate`
* Let's change our validation webhook logic that those fields don't have to be set anymore.

/kind feature
/area topology
/area controlplane

**Comment by fabriziopandini** [comment]
+1 from my side, but this should follow deprecation rules.
That's means that we can make all the work (refactor types etc.), but the field should remain there with a deprecation notice

/milestone v1.1
/remove-kind feature
/kind api-change
