### ISSUE TITLE
Webhook is misspelt in defaulting.go file

### ISSUE THREAD

**Issue by sandipanpanda** [kubernetes-sigs/cluster-api#5682]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

Spelling of `webhook` in defaulting.go file is wrong, it is `webook`.
Part needed to be updated: https://github.com/kubernetes-sigs/cluster-api/blob/ad965df37984cab5342be3c6320f85005f44f931/util/defaulting/defaulting.go#L17

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/good-first-issue
/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
@sandipanpanda Feel free to open a PR, if you want.

**Comment by sandipanpanda** [comment]
This issue is fixed in #5683 
/close
