### ISSUE TITLE
Option for configuring High Availability 

### ISSUE THREAD

**Issue by mihalycsokas** [kubernetes-sigs/cluster-api#5693]
**User Story**

As an operator I would like to use high availability for meeting such customer needs.

**Detailed Description**

Such needs can be fulfilled by raising replicas in controller-manager deployment.
The clusterctl should have an extra parameter that can be used at initiation time, e.g. clusterctl init -i someprovider --controller-manager-replicas 3

**Anything else you would like to add:**

The solution has to make sure replicas are created on different nodes. It could rely on anti-affinity (based on labels on pods that are already running on the node)

/kind feature

**Comment by fabriziopandini** [comment]
This is going to be addressed by the [Cluster API operator](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20201020-capi-provider-operator.md)

/milestone v1.2
