### ISSUE TITLE
Occasionally it takes 15 minutes for control plane to transition to running

### ISSUE THREAD

**Issue by pradipd** [kubernetes-sigs/cluster-api#5695]
**What steps did you take and what happened:**
When bringing up a cluster, we are noticing that the machines.cluster.x-k8s.io CR (which represents the control plane) will occasionally take 15 minutes to transition from Provisioning to Running.
We have our own CAP-Provider and a corresponding cloud provider POD.

**What did you expect to happen:**
The machine to transition to Running once the node has a providerID.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The capi logs show:
E1117 23:27:05.260237       1 machine_controller_noderef.go:192] controller-runtime/manager/controller/machine "msg"="Failed to parse ProviderID" "error"="providerID is empty" "name"="test-cluster-control-plane-jrst7" "namespace"="default" "providerID"={} "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" "node"="/test-cluster-control-plane-cscfw"
E1117 23:27:05.304931       1 machine_controller_noderef.go:192] controller-runtime/manager/controller/machine "msg"="Failed to parse ProviderID" "error"="providerID is empty" "name"="test-cluster-control-plane-jrst7" "namespace"="default" "providerID"={} "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" "node"="/test-cluster-control-plane-cscfw"
E1117 **23:27:05.319998**       1 machine_controller_noderef.go:192] controller-runtime/manager/controller/machine "msg"="Failed to parse ProviderID" "error"="providerID is empty" "name"="test-cluster-control-plane-jrst7" "namespace"="default" "providerID"={} "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" "node"="/test-cluster-control-plane-cscfw"
I1117 **23:41:35.522561**       1 controller.go:130] controller-runtime/manager/controller/machine "msg"="Starting EventSource" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" "source"={}
I1117 23:41:35.536041       1 machine_controller_noderef.go:90] controller-runtime/manager/controller/machine "msg"="Set Machine's NodeRef" "cluster"="test-cluster" "machine"="test-cluster-control-plane-jrst7" "name"="test-cluster-control-plane-jrst7" "namespace"="default" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" "noderef"="test-cluster-control-plane-cscfw"

**Environment:**

- Cluster-api version:  v0.4.2
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): v1.20.7
- OS (e.g. from `/etc/os-release`): 
NAME="Common Base Linux Mariner"
VERSION="1.0.20210819"
ID=mariner
VERSION_ID=1.0
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by pradipd** [comment]
capi logs and provider logs are https://gist.github.com/pradipd/99fff894cd95ae8bf094a91f48a4f0f8

I'm curious if there is a timing issue between when the cloud provider sets the provider id on the node and when we run func (r *MachineReconciler) reconcile and/or func (r *MachineReconciler) nodeToMachine,

**Comment by fabriziopandini** [comment]
I'm not sure what is going on but most of the delay is between this two lines
```
E1117 23:27:05.319998       1 machine_controller_noderef.go:192] controller-runtime/manager/controller/machine "msg"="Failed to parse ProviderID" "error"="providerID is empty" "name"="test-cluster-control-plane-jrst7" "namespace"="default" "providerID"={} "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" "node"="/test-cluster-control-plane-cscfw"
I1117 23:41:35.522561       1 controller.go:130] controller-runtime/manager/controller/machine "msg"="Starting EventSource" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" "source"={}
```
Where the controllers are apparently idle
This and the fact that the error happens occasionally makes me wondering if there is something ongoing at a different level, might be networking, but I don't have elements to prove or deny this theory

/priority awaiting-more-evidence

**Comment by pradipd** [comment]
What would I look for?  the connectivity seems fine.  And, if there were connectivity issues, it would not manifest itself in the same way.  Usually network connectivity issues will effect other components as well.  E..g kubeadm join would be flakey.

My guess was that it was in our cloud provider.  Specifically in the instances implementation.

**Comment by CecileRobertMichon** [comment]
@pradipd I'm curious, did you attempt to repro this with the latest v0.4 patch? I noticed you're using v0.4.2. Probably not related but worth the try. Otherwise, I think it's likely that this has something to do with your cloud provider taking a long time to set the node's provider ID. Since CAPI controllers have exponential backoff, it's possible that it tried and failed many times to get the providerID which causes it to eventually not retry as often. Note that the default sync period on the controller is 15 minutes (it will requeue at least every 15 minutes) so that corresponds to the delay you're seeing.

**Comment by pradipd** [comment]
I have not tried the latest v0.4 patch.  
I was also thinking it had to do with the cloud provider.  We have implemented the instances interface, but, I don't really see what could be intermittently going wrong.  I was wondering if there is some timing issue between when the cloud provider starts.  Perhaps the node is ready, but the cloud provider is taking a while to start so it doesn't set the provider id.

Is the 15 minutes sync period configurable?  Even that would be nice because this is affecting our development velocity because developers have to wait 15 minutes before they can use the cluster.

**Comment by CecileRobertMichon** [comment]
yes it's a manager flag https://github.com/kubernetes-sigs/cluster-api/blob/main/main.go#L163

actually looks like the default is 10mn, not 15. Keep in mind that if you lower it, that will cause your controller to reconcile more often, even if nothing has changed, which might not be desirable. It might be better to try to investigate why it's taking a long time for the provider ID to be set.

**Comment by pradipd** [comment]
We will definitely continue to try and root cause this.  changing the default is merely a workaround for developers that have to wait 15 minutes for their cluster to come up before they can do work.

In the logs provided, it does look like the providerid is set at the beginning of that 15 minute wait.  I'll have to keep poking around.

**Comment by pradipd** [comment]
I spent some time debugging this and I think I have an idea of the timing issue. 
1. The providerID is set on the InfrastructureRef object (in our case this is AzureStackHciCluster).
2. (r *MachineReconciler) reconcile() runs.  It does *not* start the node watcher because the ControlPlaneInitialized is not set on the cluster yet.
3. (r *MachineReconciler) reconcileInfrastructure() finds the providerID on the infrastructureRef and sets providerID on the machine.
4. (r *MachineReconciler) reconcileNode() sees that the providerID is set and calls (r *MachineReconciler) getNode
5.(r *MachineReconciler) getNode() returns "Failed to parse ProviderID" because the providerID is not set on the node yet.
Steps 2-5 repeat 3 times.  Then the machine reconciler doesn't run again for anywhere between 7-15 minutes.
Once the machine reconciler stops for its 7-15 minute break. the following happens
1.(r *ClusterReconciler) reconcileControlPlane sets (MarkTrue) ControlPlaneInitialized for the cluster
2. the node is patched with the providerID.  However, I'm not when that happens.  I don't think there is a status on the node object that records that.
After the 7-15 minute break, the machine reconciler runs again.
1. Now it starts the event watcther. (IMHO, it is a little late).
2. (r *MachineReconciler) getNode() finds the providerID on the node and can successfully set the noderef on the object.
After this everything proceeds like normal and the control plane is ready!

Do we have some events out of order?  
I.e. should we patching the providerID of the node first before patching the providerID in the infrastructureRef? 
Or perhaps ControlPlaneInitialized should be set on the cluster before we set the providerID on the infrastructureRef?

**Comment by sbueringer** [comment]
Question about 1. did you mean a machine or really `AzureStackHciCluster`?

I wonder why it takes so long to set the providerID on the node. Afaik this should be way faster and is the responsibility of the cloud controller manager. I'm not sure if we should start patching the providerID into node objects. If I remember correctly the OpenStack CCM sets the provider ID pretty much instantly, I would have expected a similar behavior from other cloud controller managers.

In case you want to find out when 5. happens, this should be possible if you enable the audit log of your workload kube-apiserver.

**Comment by pradipd** [comment]
For 1, I mean AzureStackHciCluster, which is the infrastructureRef in the  machine
When do you start your CCM?  do you start it as a static POD?
Currently, we take our time deploying the CCM POD.   Perhaps we need to install sooner.

**Comment by sbueringer** [comment]
So the InfrastructureMachine is actually a Cluster? :) (Obviously, but it's interesting as that's usually a `*Machine` resource)

> Currently, we take our time deploying the CCM POD. Perhaps we need to install sooner.

Ah that maybe explains it. IIRC it's deployed via a ClusterResourceSet pretty much as soon as the APIserver is available, but I'm not 100% sure about that.

**Comment by pradipd** [comment]
Ah. I see.  You are correct.  It is actually a AzureStackHCI*Machine*.  that probably make more sense.

**Comment by pradipd** [comment]
Is there a doc that describes the ordering of events?  
I've read https://cluster-api.sigs.k8s.io/developer/architecture/controllers/control-plane.html and I can see what each compoent is reponsbile for, but, i think there needs to be some ordering.
Specifically, I think that the controlplaneinitialized on the cluster needs to happen before the instrastructureMachine sets the providerID.

**Comment by CecileRobertMichon** [comment]
@enxebre do you have any thoughts on this one? Asking because it seems related to https://github.com/kubernetes-sigs/cluster-api/pull/4947

**Comment by pradipd** [comment]
Just  wanted to confirm 1 thing:
Are you setting the providerid for the control plane in cloud-init or through the cloud-provider?

**Comment by pradipd** [comment]
Also, just to be clear, i think this is an issue with just the 1st control plane node. For any subsequent node, the node watcher works well.
However, for the first control plane, it looks like there is a subtle issue between when we set the providerID on the infrastructure machine, when the cluster moves to controlplaneinitialized, and when the providerID is set on the node.

**Comment by CecileRobertMichon** [comment]
> Are you setting the providerid for the control plane in cloud-init or through the cloud-provider?

For Azure, cloud-provider-azure is responsible for setting the node provider ID. 

Just to make sure, I created a cluster in Azure with no cloud-provider. Nodes came up fine, but didn't have a providerID. CAPI logs show: 
```
E1202 01:15:57.209897       1 machine_controller_noderef.go:192] controller/machine "msg"="Failed to parse ProviderID" "error"="providerID is empty" "name"="default-15407-md-0-85d4dbdf66-4r872" "namespace"="default" "providerID"={} "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" "node"="/default-15407-control-plane-q6w89"
```
This loops until 01:20: 
```
E1202 01:20:20.334277       1 machine_controller_noderef.go:192] controller/machine "msg"="Failed to parse ProviderID" "error"="providerID is empty" "name"="default-15407-md-0-85d4dbdf66-4r872" "namespace"="default" "providerID"={} "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" "node"="/default-15407-md-0-sj8dv"
```

Then, I deployed the cloud-provider on the cluster (`mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v1.0.1` and `mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager:v1.0.1`), and shortly after the node had a providerID. At that point the cluster was about 9 minutes old.

CAPI assigned the node ref almost immediately:

```
I1202 01:22:42.543647       1 machine_controller_noderef.go:90] controller/machine "msg"="Set Machine's NodeRef" "cluster"="default-15407" "machine"="default-15407-control-plane-dvmck" "name"="default-15407-control-plane-dvmck" "namespace"="default" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" "noderef"="default-15407-control-plane-q6w89"
```

**Comment by pradipd** [comment]
Thiis is great! Thank you for doing that experiment.  I will try and do the same.
However, changing the sync period has worked out very well.
As soon as I'm done fighting all my fires, I'll come back to this and see if I can figure out where the difference is.

Is there anyway to tell what caused the reconcile loop to run?  Is it always a timer that causes the reconcile loop to run?  or does it also run when an object/CR changes?

**Comment by sbueringer** [comment]
The machine reconciler is triggered at least by:
* Machine events
* Cluster events
* [After ControlPlaneInitialized is true] workload cluster node events
(~ `For` and all the `Watch`es here: https://github.com/kubernetes-sigs/cluster-api/blob/8e2369e1bdc6ee0620332a76becdbc80eba4b918/controllers/machine_controller.go#L90-L125)

There are also some predicates which filter out events, but I don't think that's the case. Not sure but you might get more information on log levels 5/6+

**Comment by CecileRobertMichon** [comment]
In this case it's also watching the node objects (https://github.com/kubernetes-sigs/cluster-api/blob/8e2369e1bdc6ee0620332a76becdbc80eba4b918/controllers/machine_controller.go#L673) so I'm pretty sure it was queued because the Node Spec changed when the cloud provider set the provider ID.

**Comment by pradipd** [comment]
But watchClusterNodes is only started if the control plane is initilized: https://github.com/kubernetes-sigs/cluster-api/blob/8e2369e1bdc6ee0620332a76becdbc80eba4b918/controllers/machine_controller.go#L237

**Comment by pradipd** [comment]
So, control plane had to become initialized.  we then reconcile the machine, then kick off the node watcher, then update the Node Spec with provider ID.
