### ISSUE TITLE
Add spec comparison to topology integration tests

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5699]
As a developer I would like to validate the impact of complex clusterClass operations such as updating the clusterClass or moving a cluster from one clusterclass to another.

**Detailed Description**
Tests in the https://github.com/kubernetes-sigs/cluster-api/blob/main/controllers/topology/cluster_controller_test.go file test the full reconciliation loop for managed topologies, but the tests currently do not compare spec fields. For operations like moving from one clusterClass to another i.e. PR #5644 comparing spec is needed for holistic validation.

Mentioned here: (https://github.com/kubernetes-sigs/cluster-api/pull/5644#discussion_r751239906)
/kind feature

**Comment by fabriziopandini** [comment]
/remove-lifecycle stale
/help

@killianmuldoon can we provide more detail so we can tag this as a good first issue

**Comment by sbueringer** [comment]
@fabriziopandini What always confuses me is that the description of help wanted is identical to good first issue: https://github.com/kubernetes-sigs/cluster-api/issues/5699#issuecomment-1110998259
Is there a difference for us, if yes is it documented somewhere? :)

**Comment by fabriziopandini** [comment]
> Is there a difference for us (I assume so), if yes is it documented somewhere? :)

This is the explanation from the Kubernetes contributors guide https://www.kubernetes.dev/docs/guide/help-wanted/

**Comment by fabriziopandini** [comment]
(doing some cleanup on old issues without updates)
/close
unfortunately, no one is picking up the task. the thread will remain available for future reference
