### ISSUE TITLE
Design on cluster API integration with cluster registry

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#57]
_Copied from original issue: kubernetes/kube-deploy#548_

**Comment by rsdcastro** [comment]
**_From @karan on Feb 7, 2018 2:09PM PST_**

One of the ideas here is that we want to have an option during cluster creation (in the api or in the deployment tool) to register the cluster with any registry endpoint.

**Comment by ncdc** [comment]
It doesn't appear that the Cluster Registry project is active? I'm also not sure that Cluster API necessarily needs to be responsible for direct integration with Cluster Registry - this could be achieved outside of Cluster API. Do you all think we should keep this open, or can we close it?

**Comment by dhellmann** [comment]
I like the idea of working one layer at a time, from the bottom up. If we eventually want to add registry support, we can either reopen this ticket or file a new one at the point where we have a good idea of what that support means. So, let's close this.
