### ISSUE TITLE
Review and update staging use cases doc

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5705]
The doc at https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/staging-use-cases.md was last updated in 2019. It is linked from the main cluster api README and goes through a number of use cases / user stories for using the project.

Given how long ago the last update was, and issues that have been pointed out in the doc (e.g. https://github.com/kubernetes-sigs/cluster-api/pull/5702/files/96bb73c3c5461a2381faee2e4622ff3c1370b12b#r752685355). 

The staging use cases text should be reviewed and updated to bring readers expectations in line with the realities of cluster api today. A reasonable update is to remove this doc altogether and instead make it part of the cluster api book.

**Comment by dtzar** [comment]
It feels like there is overlap with this doc and these areas on the book:
- [Personas ](https://cluster-api.sigs.k8s.io/user/personas.html ) - This has the angle of "Where CAPI desires to invest resources" versus the article "why does CAPI benefit you as persona". 
- Introduction, especially the ["Why build Cluster API?"](https://cluster-api.sigs.k8s.io/introduction.html#why-build-cluster-api) section

My general proposal would be to:
1. Determine the statements in the staging document which are missing from the above pages in the book that we deem are essential.  IMO at a quick glance, this should be much less detail/volume than is in there.
2. Merge in those statements into updates to the above two pages in the book.
3. Remove the staging-use-cases article and all references to it.

**Comment by fabriziopandini** [comment]
/triage accepted
/assign

I will take a look and remove this doc altogether / make it part of the cluster api book.
