### ISSUE TITLE
Add list by index to ClusterClass webhook

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5719]
The ClusterClass webhook  in PR #5717 lists all clusters and then cycles through them to find those using the clusterClass being validated. Instead the ClusterClass webhook should use index.ClusterClassNameField to pull the correct clusters directly. 

This workflow is currently blocked as it requires envtest to test the indices. fakeClient does not populate indices  like index.ClusterClassNameField. The index currently can't be tested as there is a circular dependency between webhooks and envtest.

The index should be added once the circular dependency with webhooks has been removed.

c/f https://github.com/kubernetes-sigs/cluster-api/pull/5717#discussion_r754532743

**Comment by sbueringer** [comment]
/area topology
I'll open the issue to remove the circular dependency ASAP
