### ISSUE TITLE
clusterctl on main seems to not respect anymore the log level

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5736]
**What steps did you take and what happened:**
run clusterctl commands, eg. `clusterctl describe cluster` and got some unexpected log lines (No default config file available)

```
No default config file available
...
No default config file available
⚠️  Using a development build of clusterctl. CLIVersion="1.0.0-315-8a5e53e09ad0a5-dirty" LatestGithubRelease="v1.0.1"
```

It seems that somehow, clustectl now does not respect anymore the log level

**What did you expect to happen:**
clusterctl to print additional log lines only when -v flag is used

**Environment:**

- Cluster-api version: main

/kind bug
/area clusterctl

/milestone v1.1

**Comment by mkumatag** [comment]
looking into this issue

/assign
