### ISSUE TITLE
Reduce detail in ClusterClass proposal validation

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5753]
The [clusterClass proposal](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/202105256-cluster-class-and-managed-topologies.md ) contains a lot of detailed information about the valid rules for ClusterClass and managed topology related fields.

 These validation rules have been updated regularly to take into account issues discovered during testing and new features in ClusterClass. In order to make such changes easier in future, and to reduce the change that the proposal goes significantly out of sync with the implementation, the validation rules should be reduced in their level of detail to be representative of the validation rather than prescriptive.

/area topology
/kind documentation

**Comment by fabriziopandini** [comment]
I think the same apply to the behavior sections, where we can replace detailed sequence of steps with a "meta" list or a diagram
