### ISSUE TITLE
Ensure Cluster variable order is maintained through webhooks

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5754]
The ClusterClass defaulting webhook #5612 does not guarantee that variables are set on the Cluster in the same order as users supplied them when the Cluster goes through defaulting. 

In order to improve the UX Cluster variables should be set in a defined order and user variables should keep the order set by the end user.

/area topology

**Comment by sbueringer** [comment]
:+1:

I would suggest the following order:
* All existing variables on the Cluster are kept in the same order as they already are
* All newly added/defaulted variables are appended in the order in which they occur on the ClusterClass

**Comment by sbueringer** [comment]
Has been fixed as part of https://github.com/kubernetes-sigs/cluster-api/pull/5779 as I had to refactor the defaulting logic there anyway.
/close
