### ISSUE TITLE
Implement `fmt.Stringer` interface with value receiver

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5755]
Follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/5751#discussion_r758661985 

It seems like the String func should always be implemented with a value receiver. That way it works independent of if the type (in this example `TemplateRef`) is a pointer or not. I tested it with ~ `fmt.Sprintf("%s %s", &api.TemplateRef{..}, api.TemplateRef{..}`.

`TemplateRef` has already been fixed in #5751. This issue is about fixing other occurrences of that problem:

* [x] func (p *ProviderID) String() string {
    *  exported type in controllers/noderefutil
* [ ] func (n *Node) String() string {
    *  exported type in test/infrastructure/docker/docker/types
* [ ] func (n *NetworkRanges) String() string {
    *  exported type in api/v1beta1

Can we just change those funcs? I don't see an alternative with deprecations etc..

/kind cleanup
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by DiptoChakrabarty** [comment]
hey @sbueringer I would like to try this , I want to send PR with this one first https://github.com/kubernetes-sigs/cluster-api/blob/faffa2c609dc399a6c06596a64db179709f88f8c/controllers/noderefutil/providerid.go#L94-L98

As I can understand I need to pointer receiver to value receiver perform any modifications in the codebase if required.

**Comment by sbueringer** [comment]
> As I can understand I need to pointer receiver to value receiver perform any modifications in the codebase if required.

Exactly, although I wouldn't expect that there are modifications necessary as you can call a method without handling if the object is a pointer or not because Go does it automatically behind the scenes.

**Comment by vincepri** [comment]
Is there a linter we can use here?

**Comment by vincepri** [comment]
@sbueringer Could you also try with `%v` instead? Forcing all String() methods to be value receivers and not pointer also comes at a (struct copy) cost that it's not visible to callers.

**Comment by sbueringer** [comment]
@vincepri https://go.dev/play/p/gNt_CTprzGD

**Comment by sbueringer** [comment]
```go
package main

import (
	"fmt"
	"testing"
)

func BenchmarkValue(b *testing.B) {
	// run the Fib function b.N times
	for n := 0; n < b.N; n++ {
		fmt.Sprintf("%v", valueTest{})
	}
}

func BenchmarkPointer(b *testing.B) {
	// run the Fib function b.N times
	for n := 0; n < b.N; n++ {
		fmt.Sprintf("%v", pointerTest{})
	}
}

type valueTest struct{}

func (v valueTest) String() string {
	return "valueTest"
}

type pointerTest struct{}

func (v *pointerTest) String() string {
	return "pointerTest"
}
```

```bash
BenchmarkValue
BenchmarkValue-16      	 4087507	       285.5 ns/op
BenchmarkPointer
BenchmarkPointer-16    	 5816098	       203.7 ns/op
```

Not sure if it's a good way to benchmark it

**Comment by sbueringer** [comment]
Pointer seems to get slower with bigger structs (?)
```go
package main

import (
	"fmt"
	"testing"
)

func BenchmarkValue(b *testing.B) {
	for n := 0; n < b.N; n++ {
		fmt.Sprintf("%v", valueTest{})
	}
}

func BenchmarkPointer(b *testing.B) {
	for n := 0; n < b.N; n++ {
		fmt.Sprintf("%v", pointerTest{})
	}
}

type valueTest struct{
	abc string
	def string
	ghi string
}

func (v valueTest) String() string {
	return "valueTest"
}

type pointerTest struct{
	abc string
	def string
	ghi string
}

func (v *pointerTest) String() string {
	return "pointerTest"
}
```
```bash
BenchmarkValue
BenchmarkValue-16      	 3017197	       387.2 ns/op
BenchmarkPointer
BenchmarkPointer-16    	 2191651	       553.8 ns/op
```

**Comment by vincepri** [comment]
The benchmarks are always returning a fixed string which might be optimized, I'm more curious on why we need this change though across the board

**Comment by enxebre** [comment]
FWIW Given https://go.dev/doc/effective_go#pointers_vs_values
>The rule about pointers vs. values for receivers is that value methods can be invoked on pointers and values, but pointer methods can only be invoked on pointers.

I see it that as +1 so to ensure we always print as expected. Otherwise I have no strong opinions.

**Comment by sbueringer** [comment]
> The benchmarks are always returning a fixed string which might be optimized, I'm more curious on why we need this change though across the board

xref: https://github.com/kubernetes-sigs/cluster-api/pull/5751#discussion_r758661985

@vincepri 
If we use a pointer receiver the `String()` func is not used by `fmt.Sprintf("%s", &Node{})`, which means the objects are not printed correctly. If we want to print them correclty when `String` is implemented with a pointer receiver we have to print like this: `fmt.Sprintf("%s", &Node{}.String())` (if we want to use the `String()` func)

If we implement the func with a value receiver it just works automatically.

**Comment by sbueringer** [comment]
/reopen
(partially fixed, I've updated the issue description with the current status)

**Comment by sbueringer** [comment]
@vincepri 
`test/infrastructure/docker/docker/types.Nodes` should be trivial to fix.

What should we do with `api/v1beta1.NetworkRanges`? (asking because it's an exported type)

**Comment by vincepri** [comment]
Let's proceed with both?

**Comment by sbueringer** [comment]
> Let's proceed with both?

Sure

@DiptoChakrabarty Are you interested in opening a PR to implement the change for the two outstanding structs?

**Comment by DiptoChakrabarty** [comment]
Yes Sure
