### ISSUE TITLE
Implement safeguard validation in the topology controller

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5758]
**Detailed Description**
We recently added extensive validation for ClusterClass and Cluster topologies.

As an additional safeguard, we should now add the following check in the topology controller for:
- Check variable values against the schema defined in the ClusterClass, and more specifically
   - TBD if to default missing variables according to schema
   - Fail if a variable value does not comply with the corresponding schema
   - Fail if a variable does not have a corresponding schema  (In future we might consider relaxing this constraint and converting to a warning)
 
Please note that the topology controller already contains some safeguard check blocking incompatible changes to be applied; the check above should be considered an extension of this by preventing reconcile to happen using incompatible value variables (while instead we should not duplicate all the validation rules)

/kind feature
/area topology

/milestone v1.1

@killianmuldoon 
@sbueringer

**Comment by sbueringer** [comment]
> TBD if to default missing variables according to schema

I think we should decide this based on what would be the least surprising behavior for users. And to be honest I'm not sure which one it is. I lean towards starting with the `CRD` way of doing things and **only** defaulting on Cluster create/update and possible adding defaulting during reconciliation later on.
The only thing I wouldn't want to do is default the variables locally and *don't* write them back to the Cluster resource.

This discussion might be slightly relevant to: https://github.com/kubernetes-sigs/cluster-api/pull/5752#discussion_r759352699 (as it's about how variables can be added to a ClusterClass)

**Comment by fabriziopandini** [comment]
/close 
in favour of https://github.com/kubernetes-sigs/cluster-api/issues/5623
