### ISSUE TITLE
Ensure we don't reconcile templates which are not topology owned

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5760]
We currently have checks in place which make sure that we never reconcile InfrastructureClusters and ControlPlanes of a classy Clusters which are not topology owned (detected by the label):
https://github.com/kubernetes-sigs/cluster-api/blob/fc2bbbb74867f79e37de24ea70719fd095de6f66/controllers/topology/current_state.go#L99-L104

I think we should do the same for the ControlPlane InfrastructureMachineTemplate and the templates referenced in MDs. 

/kind feature
/area topology

**Comment by adilGhaffarDev** [comment]
Hey I want to work on this issue, I am assigning it to myself.
/assign
