### ISSUE TITLE
Run clusterclass quick-start as PR informing

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5768]
As a maintainer I would like to have a quick signal on how changes impacts on ClusterClass, so ti would be great to have clusterclass quick-start job running as PR informing

I can see two options to achieve this:
1. creating a new prow job similar to pull-cluster-api-e2e-ipv6-main 
2. renaming pull-cluster-api-e2e-ipv6-main into pull-cluster-api-e2e-informing-main and running all the jobs with a new label (cluster class and ipv6 for starting)

I'm in favor of 2, but TBH I don't remember the nuances of the ipv6 test, so the feasibility of this option should be verified

/kind feature
/area testing
/area topology
/milestone v1.1

@sbueringer @ykakarap

**Comment by sbueringer** [comment]
+1 overall

I'm also in favor of 2. with a tag like `[PR-informing]` (cf. `[PR-blocking]`)

The problem right now is that the IPv6 job is run in a way that the ClusterClass quickstart also **has to** run with IPv6. (https://github.com/kubernetes/test-infra/blob/243d30eaed8045b4ab39d4d72abcc3dcdea92de7/config/jobs/kubernetes-sigs/cluster-api/cluster-api-presubmits-main.yaml#L185-L190)
I would really like to keep using IPv4 for the ClusterClass test.

I think we should modify the QuickStartSpec to allow running the IPv6 test without this env variables:
```
          - name: IP_FAMILY
            value: "IPv6"
          - name: DOCKER_SERVICE_CIDRS
            value: "fd00:100:64::/108"
          - name: DOCKER_POD_CIDRS
            value: "fd00:100:96::/48"
```

Tasks:
* Add a new `Describe` in `quick_start_test.go` ~ `When following the Cluster API quick-start with IPv6`, which sets the flavor to ipv6
    * We can then drop the if/else with the IPFamily in the `QuickStartSpec`
* The ipv6 cluster-template can just overwrite the fields configured with `DOCKER_SERVICE_CIDRS` and `DOCKER_POD_CIDRS` with  `DOCKER_SERVICE_IPV6_CIDRS` and `DOCKER_POD_IPV6_CIDRS`
    * `DOCKER_SERVICE_IPV6_CIDRS` and `DOCKER_POD_IPV6_CIDRS` should be added to docker.yaml with the values we're currently using in the job


I think additionally to allowing running both tests in the same Job it would also be a nice cleanup (i.e. the IPv6 test is then more in line with how we usually define our tests)

**Comment by sbueringer** [comment]
I overlooked that we're also creating the bootstrap cluster with IPv6. I'm not sure if this is necessary to create an IPv6 workload cluster though.

If it is, our only option is to have a separate job.

**Comment by fabriziopandini** [comment]
I would explore if creating an ipv4 workload cluster from an ipv6 management cluster works

**Comment by ykakarap** [comment]
I am also +1 to option 2 if we workload ipv4 works with management ipv6.

>Note: without further modifications the IPv6 test would now also be run with e2e-full. But I think we can just filter it out with another tag and GINKGO_SKIP if we don't want to run it there.

Since we are already doing this in e2e-full for other tests like `Conformance` and `K8s-Upgrade` I think we should be okay with doing the same with a new tag like `IPV6`.

**Comment by sbueringer** [comment]
Yup. But maybe we want to just run it too in e2e-full. I wouldn't be opposed to it (if we get it to work :))

**Comment by fabriziopandini** [comment]
>  But maybe we want to just run it too in e2e-full.

I was only considering using management cluster ipv6 with ipv4 workload cluster for the PR-informing (and keep e2e-full as it is).
TBH, we can also expore using ipv6 for the cluster class test if ^^

**Comment by sbueringer** [comment]
> I was only considering using management cluster ipv6 with ipv4 workload cluster for the PR-informing (and keep e2e-full as it is).

Do you mean ipv4 managed with ipv6 workload?

> TBH, we can also explore using ipv6 for the cluster class test if ^^

I was just thinking that we get better signal if each of those fails on it's own, i.e. the ClusterClass gives us a clean signal without introducing potential errors from IPv6.

**Comment by fabriziopandini** [comment]
Taking a step back:
- the intent of this issue is to get ClusterClass test as PR informing
- ideally, we should get a single PR informing job, and in order to do so it is required to get IPV6 informing e ClusterClass informing to run together (and currently this test have management cluster IPV6 and workload cluster IPV6; open to any idea on how to add the clusterclass test on top of this)
- any change to e2e-full is out of scope of this issue
