### ISSUE TITLE
MachineHealthCheck overriding 

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5770]
There is an open PR to include MachineHealthCheck in the ClusterClass proposal #5125 . 

The proposal allows users to set either:

* A global MachineHealthCheck: a MachineHealthCheck for each Machine linked to a MachineDeployment in the Cluster and a MachineHealthCheck for ControlPlane Machines if defined.
          **OR**
* An individual MachineHealthCheck for the ControlPlane MachineInfrastructure and or each MachineDeploymentTopology defined in the ClusterClass.

An alternative would be to allow both the global and individual MachineHealthCheck fields to be set in the ClusterClass, but define an overriding order where any individual definition would override the global definition for the entity (MachineDeployment or ControlPlane MachineInfrastructure) that it is defined for.

This would make it easier for users to define a single exception to the global MachineHealthCheck e.g. A different spec for the ControlPlane MachineInfrastructure MachineHealthCheck, but it would add overriding behaviour that could be difficult for users to understand.

**Comment by sbueringer** [comment]
Note: Depending on how we decide to implement defaulting the defaulting could interact in interesting ways with the override logic.

**Comment by fabriziopandini** [comment]
/kind feature
@killianmuldoon is this issue still valid given that we have only MHC at the lowest level?

**Comment by killianmuldoon** [comment]
This is still valid - we might want to include MHC at least at the MachineDeployments level in future so one spec covers all MachineDeployments defined in the ClusterClass.

**Comment by fabriziopandini** [comment]
As per 29/7 backlog grooming, we are not implementing this.
/close

**Comment by sbueringer** [comment]
> As per 29/7 backlog grooming, we are not implementing this. /close

@fabriziopandini Fine for me, just an improvement suggestion. Can we maybe add a short comment with a reason as to why we're closing issues? It's hard to tell for folks who were not at the backlog grooming. (even something like apparently no demand would be helpful)
