### ISSUE TITLE
ClusterClass patches/variables: JSON `null` value does not work as expected with kubectl client-side apply

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5776]
### Overview

Currently, we support nullable variables. This means that in the variable schema `nullable` can be set and then the corresponding variable on the Cluster can be also set to `null`.

Setting `null` as variable value works as expected. But setting `null` in `openAPIV3Schema.Default` and `jsonPatch.Value` doesn't work, i.e. setting them to `null` is treated the same way as not setting them at all.

### Details

We could modify our code to be able to **handle** `null` correctly by:
* adding `// +nullable` on the `Default` and `Value` fields so `null` is stored in etcd and sent to our webhook. 
* implementing custom `Unmarshal` functions for `JSONPatch` and `JSONSchemaProps` so our webhook can handle `null` values correctly.

These changes allow us to handle `null` correctly on the **server-side**, but there is also a severe issue with `kubectl apply`:

When using `kubectl apply` (with the default client-side apply), kubectl will try to unset the `null` value when the YAML surrounding `default` and `value` fields is changed. This happens because kubectl is using json merge patch. This is not an issue for the `value` in the Cluster resource but for `openAPIV3Schema.default` and `jsonPatch.value` on the ClusterClass. 

**NOTE**: server-side apply works as expected.

### Conclusion

We could improve the situation but we would still have a severe UX issue with kubectl apply when supporting `null`. We have the following options:

#### Option 1 (proposed): Drop support for nullable

Taking a few steps back, the question is if we have to support nullable:
* Optional variables are already possible by using a variable which is not required without a default value
    * Patches can then handle non-existing variables via `enabledIf` or a `valueFrom.template`.
* Fields on templates can also be removed with the `remove` JSON patch operation, we don't need the `null` value for that.

Based on that, it seems like the best option to drop support for `nullable` as there is no clear demand for it, and it's currently impossible to provide a good all around UX with `kubectl apply`. Also the changes we would have to make to support it fully (as outlined above)  are not breaking, so we could introduce support for `nullable` later on if we want to.

#### Option 2: Improve JSON `null` handling

In this case we would implement the changes as proposed above, but we have to live with the issue with `kubectl apply` and can only document the workaround of using server-side apply.

/kind bug
/area topology
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
/milestone v1.1

I'm +1 for option1; unexpected behaviors when using plain kubectl apply could be very surprising for the users; also the alternative seems very clean and user friendly to me: if you don't want to set a value for a variable, just drop the variable from cluster.spec.variables (if the schema allows this).

**Comment by killianmuldoon** [comment]
+1 for this unless there's some use case for a null variable it doesn't make sense to go out of our way to support it.

**Comment by sbueringer** [comment]
As if the behavior of the top-level nullable isn't already bad enough. Just tried if nested nullable fields would work. Result is that the `null` is not even set on initial create

Just tested it. It doesn’t even set the nested null value on create:

local YAML:
```yaml
    - name: nullableObject
      value:
        nullableString: null
        testString: def
```
YAML in Kubernetes:
```yaml
    - name: nullableObject
      value:
        testString: def
```
kubectl debugger JSON merge patch: (on later applies)
```json
        {
          "name": "nullableObject",
          "value": {
            "testString": "def"
          }
        }
```
