### ISSUE TITLE
minReadySeconds for kubeadmControlPlane

### ISSUE THREAD

**Issue by superbrothers** [kubernetes-sigs/cluster-api#5783]
**User Story**

As a user, I would like to use minReadySeconds for kubeadmControlPlane for making the rollout of ControlPlane nodes safer.

**Detailed Description**

MachineDeployment has `minReadySeconds`, but KubeadmControlPlane does not.

In our cluster, there are times when a node needs to be rebooted after it joins the cluster, for example due to a device firmware update, and we want a  period between when a ControlPlane node becomes Ready and when the next rollout starts. If no period exists, the reboot of the new ControlPlane node and the deletion of the old ControlPlane node may occur at the same time (if maxSurge is 0). This results in a temporary period of time when there is only one healthy ControlPlane node.

**Anything else you would like to add:**

None.

/kind feature

**Comment by vincepri** [comment]
/milestone v1.1

This sound like a great addition, how would we go about tracking the time from the last rollout?

**Comment by superbrothers** [comment]
How about using `preflightChecks` function to check if all nodes associated with all control plane machines are available using `IsNodeAvailable` function?

https://github.com/kubernetes-sigs/cluster-api/blob/89db44e9a462028267ed49295359fe9db2a6a10a/controlplane/kubeadm/controllers/scale.go#L155-L163

https://github.com/kubernetes-sigs/cluster-api/blob/30ae87d0fd95a11c83e3b721f81b9f1963a0baf3/controlplane/kubeadm/controllers/controller.go#L496-L498

https://github.com/kubernetes-sigs/cluster-api/blob/89db44e9a462028267ed49295359fe9db2a6a10a/controllers/noderefutil/util.go#L26-L27

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough contributors to adequately respond to all issues and PRs.

This issue is not active since 2021, and we don't have other evidence that this new field is required anymore.
We can eventually re-open if we have evidence that the proposed change could improve KCP stability
/close

**Comment by cyber-slave-labs** [comment]
Filed a v1beta2-era follow-up with a concrete production scenario and an implementation sketch: #14059. Since #12153 moved `minReadySeconds` to `Machine.spec`, KCP is now the only Machine-creating controller that cannot set it.
