### ISSUE TITLE
Should we have a data model for "PrivateClusters"

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api#5799]
**User Story**

As an CAPZ user or CAPA or ... user, I want my cluster to have a definitional constraint that makes it private or public . 

**Detailed Description**

Looking at  the code in cluster-api-provider-azure, we can see that theres *stuff* that interprets the cluster network specification... 

```

	// set default control plane outbound lb for private v1alpha3 clusters
	if src.Spec.NetworkSpec.APIServerLB.Type == Internal && restored.Spec.NetworkSpec.ControlPlaneOutboundLB == nil {
...
	} else {
...
	}

```

**Anything else you would like to add:**

I guess first pass here would be to:
- look at Azure's impl of priv clusters (evidently this effects the way serviceType=LB works , bcideally, you'd want a Adm Controller that "knew" about wether the cluster was private or not, and made LB IPs accordingly so that users didnt accidentally expose their PRIVATE APP to the internet... 
- look at how CAPA solves this, is it similar?
- maybe theres some kind of cloud provider interface interlock here? i.e.

```
- user makes serviceType=LB
-  cloud provider checks if cluster is a CAPI one ?
   - Yes 
     - cloud provider then checks the capi cluster type
     - cloud proivder then adds azure private LB annotation to the service made by user
```

/kind feature

**Comment by jayunit100** [comment]
cc @lubronzhan might be interested?

**Comment by fabriziopandini** [comment]
The challenge that I see is finding consensus on a shared definition of "private" across infrastructure providers, given that I assume there are variations/nuances 
FYI @yastij 

/milestone v1.2

**Comment by lubronzhan** [comment]
Thanks @jayunit100 
I think we could start with, internal Load balancer for the control plane endpoint as `private` definition.
How node, workload or service is airgapped could be decided by each provider.
