### ISSUE TITLE
Cluster provisioning "succeeds" despite machine-controller failing to start

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#58]
_From @rsdcastro on February 20, 2018 23:38_

Logs from cluster-api-gcp:

I0220 15:20:25.802792   19570 deploy_helper.go:68] Created master gce-master-test1
I0220 15:21:05.422987   19570 deploy_helper.go:241] Waiting for Kubernetes to come up...
I0220 15:21:13.538578   19570 deploy_helper.go:241] Waiting for Kubernetes to come up...
I0220 15:21:21.449076   19570 deploy_helper.go:241] Waiting for Kubernetes to come up...
I0220 15:21:29.529327   19570 deploy_helper.go:241] Waiting for Kubernetes to come up...
I0220 15:21:37.577458   19570 deploy_helper.go:274] wrote kubeconfig to [/Users/rdc/.kube/config]
I0220 15:21:37.577530   19570 deploy_helper.go:85] Waiting for apiserver to become healthy...
I0220 15:22:14.658776   19570 deploy_helper.go:94] Waiting for the service account to exist...
I0220 15:22:25.097828   19570 deploy_helper.go:99] Starting the machine controller...
I0220 15:22:46.073147   19570 deploy_helper.go:136] Clusters CRD created succuessfully!
I0220 15:22:46.849643   19570 deploy_helper.go:160] Machines CRD created successfully!
I0220 15:22:46.981945   19570 deploy_helper.go:176] Added machine [gce-master-test1]
I0220 15:22:47.088406   19570 deploy_helper.go:176] Added machine [gce-node-l71sp]
I0220 15:22:47.088443   19570 deploy.go:74] The [test1] cluster has been created successfully!
I0220 15:22:47.088455   19570 deploy.go:75] You can now `kubectl get nodes`. Note: you might only see the master for the first few minutes while the machine controller spins up the node machines.

But if one checks the machine controller logs:

$ kubectl logs machine-controller -n kube-system
F0220 23:34:12.548770      80 machinecontroller.go:71] error creating machine actuator: Not recognized cloud provider: terraform

This means that ideally here we can find a way to check if the machine controller is actually up & running to act on the machine objects before returning success to the user.

_Copied from original issue: kubernetes/kube-deploy#619_

**Comment by spew** [comment]
Taking a look at this one.

**Comment by roberthbailey** [comment]
I'm going to close this as obsolete. Please reopen if you can reproduce with clusterctl.
