### ISSUE TITLE
Implement Scale Subresource for MachineSet

### ISSUE THREAD

**Issue by chaosaffe** [kubernetes-sigs/cluster-api#580]
With the move back to CRD's we haven't added support to MachineSet for using the `scale` command with `kubectl`. Adding support for the [scale subresource](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#scale-subresource) would allow for use of the `scale` command.

/good-first-issue

**Comment by stpabhi** [comment]
I would like to work on it

**Comment by flaper87** [comment]
@stpabhi sounds great, go for it! :cake:

**Comment by detiber** [comment]
The good news is that the annotation to generate the scale subresource is already present in the version of sigs.k8s.io/controller-tools that we have vendored :)

**Comment by roberthbailey** [comment]
Fixed by https://github.com/kubernetes-sigs/cluster-api/pull/582
