### ISSUE TITLE
capi cannot provision nodes

### ISSUE THREAD

**Issue by tasos71** [kubernetes-sigs/cluster-api#5807]
**What steps did you take and what happened:**

I am trying to deploy a cluster (k8s version 1.17.3 and ubuntu 19.10) and I am facing the issue below 

NAME                                                                                READY  SEVERITY  REASON            SINCE  MESSAGE
/capi-quickstart                                                                    False  Warning   ScalingUp         3d15h  Scaling up control plane to 3 replicas (actual 1)
├─ClusterInfrastructure - OpenStackCluster/capi-quickstart
├─ControlPlane - KubeadmControlPlane/capi-quickstart-control-plane                  False  Warning   ScalingUp         3d15h  Scaling up control plane to 3 replicas (actual 1)
│ │           ├─Available                                                           True                               3d15h
│ │           ├─CertificatesAvailable                                               True                               3d15h
│ │           ├─MachinesReady                                                       True                               3d15h
│ │           └─Resized                                                             False  Warning   ScalingUp         3d15h  Scaling up control plane to 3 replicas (actual 1)
│ └─Machine/capi-quickstart-control-plane-cxnmb                                     True                               3d15h
│   │           ├─BootstrapReady                                                    True                               3d15h
│   │           ├─InfrastructureReady                                               True                               3d15h
│   │           └─NodeHealthy                                                       False  Warning   NodeProvisioning  3d15h
│   └─MachineInfrastructure - OpenStackMachine/capi-quickstart-control-plane-rjmq4
└─Workers
  └─MachineDeployment/capi-quickstart-md-0
    └─Machine/capi-quickstart-md-0-c54bc8976-pzx46                                  True                               3d15h
      │           ├─BootstrapReady                                                  True                               3d15h
      │           ├─InfrastructureReady                                             True                               3d15h
      │           └─NodeHealthy                                                     False  Warning   NodeProvisioning  3d15h

my target environment is behind a proxy when I deploy a cluster, nodes seem healthy but capi cannot retrieve their status in order to continue.

**What did you expect to happen:**
Capi to read the provider ID and after that the status of control plane and worker nodes in order to continue deployment

**Anything else you would like to add:**
capi logs: 
E1207 08:53:13.511613       1 machine_controller_noderef.go:176] controllers/Machine "msg"="Failed to parse ProviderID" "error"="providerID is empty" "providerID"={} "node"="capi-quickstart-control-plane-rjmq4"
E1207 08:53:13.511635       1 machine_controller_noderef.go:176] controllers/Machine "msg"="Failed to parse ProviderID" "error"="providerID is empty" "providerID"={} "node"="capi-quickstart-md-0-hskrm"
E1207 08:54:22.535685       1 machine_controller.go:685] controllers/Machine "msg"="Unable to retrieve machine from node" "error"="no matching Machine"  "node"="capi-quickstart-control-plane-rjmq4"
E1207 08:54:22.535714       1 machine_controller.go:685] controllers/Machine "msg"="Unable to retrieve machine from node" "error"="no matching Machine"  "node"="capi-quickstart-control-plane-rjmq4"

kg machines
NAME                                   PROVIDERID                                          PHASE          VERSION
capi-quickstart-control-plane-cxnmb    openstack:///f2371339-9d3f-4973-8d21-784b91ba5279   Provisioning   v1.17.3
capi-quickstart-md-0-c54bc8976-pzx46   openstack:///6238d508-bbf4-4727-920d-e7b1e9b673a7   Provisioning   v1.17.3

kdes KubeadmControlPlane/capi-quickstart-control-plane
  Warning  ControlPlaneUnhealthy  3m38s (x21499 over 3d16h)  kubeadm-control-plane-controller  Waiting for control plane to pass preflight checks to continue reconciliation: [machine capi-quickstart-control-plane-cxnmb does not have APIServerPodHealthy condition, machine capi-quickstart-control-plane-cxnmb does not have ControllerManagerPodHealthy condition, machine capi-quickstart-control-plane-cxnmb does not have SchedulerPodHealthy condition, machine capi-quickstart-control-plane-cxnmb does not have EtcdPodHealthy condition, machine capi-quickstart-control-plane-cxnmb does not have EtcdMemberHealthy condition]

target cluster status:

kubectl --kubeconfig=./capi-quickstart.kubeconfig  get cs

NAME                 STATUS    MESSAGE             ERROR
controller-manager   Healthy   ok
scheduler            Healthy   ok
etcd-0               Healthy   {"health":"true"}

kubectl --kubeconfig=./capi-quickstart.kubeconfig  get po -A

NAMESPACE     NAME                                                          READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-bd4c647dc-jvvq9                       0/1     Pending   0          3d15h
kube-system   calico-node-8w45d                                             1/1     Running   0          3d15h
kube-system   calico-node-fw4x9                                             1/1     Running   0          3d15h
kube-system   coredns-6955765f44-lbvrf                                      0/1     Pending   0          3d16h
kube-system   coredns-6955765f44-rpj65                                      0/1     Pending   0          3d16h
kube-system   etcd-capi-quickstart-control-plane-rjmq4                      1/1     Running   0          3d16h
kube-system   kube-apiserver-capi-quickstart-control-plane-rjmq4            1/1     Running   0          3d16h
kube-system   kube-controller-manager-capi-quickstart-control-plane-rjmq4   1/1     Running   0          3d16h
kube-system   kube-proxy-fdf54                                              1/1     Running   0          3d16h
kube-system   kube-proxy-twnkh                                              1/1     Running   0          3d16h
kube-system   kube-scheduler-capi-quickstart-control-plane-rjmq4            1/1     Running   0          3d16h

**Environment:**

- external cloud provider openstack
- Cluster-api version:  0.3.23
- Minikube/KIND version: No KIND/ Actual k8s cluster 
- Kubernetes version: (use `kubectl version`): 1.20.3
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.2 LTS

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
[capi-quickstart.txt](https://github.com/kubernetes-sigs/cluster-api/files/7667174/capi-quickstart.txt)

**Comment by fabriziopandini** [comment]
/priority awayting-more-evidences

"msg"="Failed to parse ProviderID" "error"="providerID is empty" usally happens when for any reason the node on the machine does not start.

You can try to investigate this on the machine following instructions at https://cluster-api.sigs.k8s.io/user/troubleshooting.html or ask in the OpenStack provider channel given that the machine seems to be stuck in the middle of initial provisioning

**Comment by enxebre** [comment]
>nodes seem healthy but capi cannot retrieve their status in order to continue.

Do the nodes actually have the providerID set on them?

**Comment by tasos71** [comment]
thanks for the clarifications,

actually I found in the master node those logs

crictl ps -a
CONTAINER           IMAGE               CREATED             STATE               NAME                      ATTEMPT             POD ID
07fa913e85a4d       51072d10fe8cb       57 minutes ago      Running             calico-node               0                   f24370a5e54cc
1c357900bfcce       28d763a4d4e88       57 minutes ago      Exited              flexvol-driver            0                   f24370a5e54cc
b08ae3cafdd10       bb55e7a746cb8       57 minutes ago      Exited              install-cni               0                   f24370a5e54cc
117825dda3b55       bb55e7a746cb8       57 minutes ago      Exited              upgrade-ipam              0                   f24370a5e54cc
0db1f07f83f60       ae853e93800dc       About an hour ago   Running             kube-proxy                0                   fc1bb714c40e3
48d3764ad9c91       d109c0821a2b9       About an hour ago   Running             kube-scheduler            0                   c5020f78e8928
6ee64601add05       90d27391b7808       About an hour ago   Running             kube-apiserver            0                   d1163e387a635
9fcd67c680a4c       303ce5db0e90d       About an hour ago   Running             etcd                      0                   9798cb85998c7
08f69844e8788       b0f1517c1f4bb       About an hour ago   Running             kube-controller-manager   0                   17ed2eeda24a1


crictl logs
FATA[0000] ID cannot be empty

journalctl -xeu kubelet

Dec 14 19:18:13 capi-quickstart-control-plane-hmxld kubelet[1485]: W1214 19:18:13.523134    1485 driver-call.go:149] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/u
Dec 14 19:18:13 capi-quickstart-control-plane-hmxld kubelet[1485]: E1214 19:18:13.523139    1485 plugins.go:732] Error dynamically probing plugins: Error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error:
Dec 14 19:18:13 capi-quickstart-control-plane-hmxld kubelet[1485]: E1214 19:18:13.523275    1485 driver-call.go:266] Failed to unmarshal output for command: init, output: "", error: unexpected end of JSON input



Dec 14 19:18:13 capi-quickstart-control-plane-hmxld kubelet[1485]: E1214 19:18:13.543160    1485 plugins.go:732] Error dynamically probing plugins: Error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error:
Dec 14 19:18:13 capi-quickstart-control-plane-hmxld kubelet[1485]: E1214 19:18:13.543427    1485 driver-call.go:266] Failed to unmarshal output for command: init, output: "", error: unexpected end of JSON input

**Comment by tasos71** [comment]
thanks a lot for the info
