### ISSUE TITLE
ClusterClass patches: advanced template validation

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5809]
Currently, we have basic template validation for `valueFrom.template` and `enabledIf`, i.e. we make sure that they can be parsed by the Go template lib (https://github.com/kubernetes-sigs/cluster-api/blob/534bae8b6161a3e1d676c1c1cfc17ec87979b911/internal/webhooks/patch_validation.go#L96-L113).

Goal of this issue is to discuss and possibly implement an extension of this validation.

One idea would be to essentially render the templates the same way we do in our patch implementation. This requires the following steps:
* create a variables map with all builtin and user-defined variables including values (based on the OpenAPI schema) (in case of `valueFrom.template` for every template the patch applies to)
* render the template with the variables as data
* call `yaml.Unmarshal` on the result to make sure the result is valid YAML/JSON

This would rely on a lot of logic which is currently not exposed to the webhook code:
* builtin variable (calculation)
* template selection
* calculation of template-specific variables 

Of course there's also middle ground where we just use all user-defined variables and all builtin variables that could exist. We would have to make some tradeoffs anyway as some of the builtin variables depend on the specific Cluster, which is something we cannot use in the ClusterClass webhook.

/kind feature
/area topology

**Comment by fabriziopandini** [comment]
/milestone v1.1
I would like to get a little bit more understanding of how templates are used before investing in more advanced validation. 
Also, we should consider alternatives like the clusterctl tooling, think e.g. dry-run to provide support for more complex use cases.

**Comment by fabriziopandini** [comment]
I think this will be less important when topology mutation hook will be available, but let's keep this around waiting for user feedback
/remove-lifecycle stale

**Comment by killianmuldoon** [comment]
The Topology Mutation Hook includes a [ValidateTopology](https://cluster-api.sigs.k8s.io/tasks/experimental-features/runtime-sdk/implement-topology-mutation-hook.html#validatetopology) call so users with stricter validation requirements, which they can implement to their own requirements, can use that and could be encouraged to do so.

I'm not sure if we want stricter and more complex validation for inline patches with this feature in place.

**Comment by fabriziopandini** [comment]
/close
Let's consider topology mutation hooks the way forward for advanced use cases because it provides options for unit testing everything using a proper programming language
