### ISSUE TITLE
Topology reconcile should manage field removal in an intuitive way

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5811]
**User Story**

As a user/operator I would like to have a predictable and intuitive behavior of managed objects 

**Detailed Description**

The topology controller relies on a two-way merge patch to reconcile desired and current state of managed objects.

This works nicely and intuitively when a field gets added to a template, but in case a field is removed the behavior is far less intuitive because the two-way merge patch assumes the field is instance-specific, so it leaves the field in the object.

This can be surprising for the user and eventually also annoying given that the only way to actually remove the field is to edit managed objects one by one.

This issue is about making topology reconcile to provide a better an nice support for field removal

/kind feature
/kind release-blocking
/area topology
/milestone v1.1

**Comment by fabriziopandini** [comment]
@sbueringer to add more color if necessary
/assign

**Comment by sbueringer** [comment]
Sounds very concise and complete to me
