### ISSUE TITLE
Make dev kind cluster name configurable

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5820]
Currently, we're hard-coding `capi-test` as kind cluster name in the following places:
* hack/tools/tilt-prepare/main.go
* hack/kind-install-for-capd.sh

It might be good to make that configurable, e.g. via a `CAPI_KIND_CLUSTER_NAME` env var.

/kind feature

**Comment by DiptoChakrabarty** [comment]
@sbueringer where is the first file that is /hack/tools/tilt-prepare/main.go  in this repository , sorry I am unable to find it. I have done the second one for this, would like to work on this.

/assign

**Comment by sbueringer** [comment]
> @sbueringer where is the first file that is /hack/tools/tilt-prepare/main.go in this repository , sorry I am unable to find it. I have done the second one for this, would like to work on this.
> 
> /assign

Should be there after https://github.com/kubernetes-sigs/cluster-api/pull/5785 has been merged
