### ISSUE TITLE
Set default value for bootstrap secret format to cloud-init

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api#5823]
**Detailed Description**

As discussed in [#4172](https://github.com/kubernetes-sigs/cluster-api/pull/4172/files#r764995622), right now we set `format` field in bootstrap secret to empty value. We should set it via webhook to `cloud-init` explicitly.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by sbueringer** [comment]
I assume we want to default the `Format` field on KCP / KubeadmConfig and KubeadmConfigTemplate, right?

**Comment by invidian** [comment]
Created https://github.com/kubernetes-sigs/cluster-api/pull/5869 to resolve this.
