### ISSUE TITLE
ClusterClass: schema validation of Default, Enum, Example 

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5831]
Currently, we only validate that `Default`, `Enum` and `Example` (in `JSONSchemaProps`) are valid JSON. We don't validate that they comply to the schema.

Goal of this issue is to discuss if we also want to validate those fields.

In my opinion, the most important field of those is `Default`. If `Default` does not comply to the schema and a variable is defaulted, the resulting Cluster will automatically be invalid. This is an especially bad UX as the user who created the Cluster didn't set the variable and potentially didn't write the ClusterClass, but the Cluster creation/update still fails because of a value we set during defaulting in the webhook.

Notes:
* If we do it, we have to do this recursively also for all nested fields (Objects/Arrays)
* Not sure what the performance impact is, but it's probably negligible as we would only run this validation during ClusterClass create and update

Notes on implementation:
* I think it could be as easy as taking the validator we create [here](https://github.com/kubernetes-sigs/cluster-api/blob/2212968e5b962c66d39f051791bce9e3e8a0e2f9/internal/topology/variables/clusterclass_variable_validation.go#L191) and using it directly below to validate `Default`, `Example` and all `Enum` values individually + adding unit tests
    * Note: This function is already called recursively.

Context:
Afaik Kubernetes is validating neither of those fields in CRDs (but I don't think that should influence us too much)

/kind feature
/area topology

**Comment by sbueringer** [comment]
I personally think we should do it as it makes ClusterClasses safer to use and I don't expect performance issues.

I don't think it has to be release blocking but it would be nice to have and it should be possible to implement it until the release.

**Comment by killianmuldoon** [comment]
/assign

I can take this up

**Comment by killianmuldoon** [comment]
@sbueringer I have a PR that does this and validates example / enums and defaults up now.

As far as I understand defaulting was already validated, and it's validated recursively so we'll need to remove that function  - it does a bunch of stuff that seems to be CRD specific rather than relevant for our objects.  - [here's the call](https://github.com/kubernetes-sigs/cluster-api/blob/199d229248771b565ae08d2e76b9d978a5337863/internal/topology/variables/clusterclass_variable_validation.go#L182).

**Comment by sbueringer** [comment]
Agree it looks like they are already validated. I'm not sure if we should drop the call. It seems to do additional stuff, but I"m not sure if that's a problem. I'll take a closer look later and comment on the PR
