### ISSUE TITLE
 TestReconcileUnhealthyMachines is flaky

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5848]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

TestReconcileUnhealthyMachines/Remediation_does_not_happen_if_desired_replicas_<=_1 is failing from time to time.

Two recent examples:
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-test-main/1468933028284731392
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-main/1466843777606881280

/kind flake
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by killianmuldoon** [comment]
This should be solved by #5837 .  Should we leave the issue open (and let it be closed over time by the stale bot) to see if this has reduced the flakiness of the test?

**Comment by fabriziopandini** [comment]
/milestone v1.1
/area testing

/close
we can eventually re-open if new problems are reported
