### ISSUE TITLE
Cluster upgrade 1.23 => latest is broken

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5849]
The recently added 1.23 => latest upgrade e2e test is failing constantly: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main-1-23-latest

/kind failing-test
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
/milestone v1.1
/kind release-blocking

Let's make sure to figure out what's going on before release, the we can decide if we should wait for the fix or not

**Comment by stmcginnis** [comment]
Not sure if it is related in any way, but just wanted to point out this other outstanding issue we have: https://github.com/kubernetes-sigs/cluster-api/issues/5818

**Comment by fabriziopandini** [comment]
> Not sure if it is related in any way, but just wanted to point out this other outstanding issue we have: #5818

I don't think the two problems are related, because AFAIK we are not using overrides in our E2E tests; also the tests are failing due to an error upgrading CoreDNS (and this means all the clusterctl stuff worked property)

**Comment by sbueringer** [comment]
Looks like we’re trying to “upgrade” to CoreDNS v1.8.4, but the cluster already has CoreDNS v1.8.6

The test is able to set v1.8.4 in the KCP object but the CoreDNS deployment stays on v1.8.6

kubeadm CoreDNSVersion constant:
* v1.21 => v1.8.0
* v1.22 => v1.8.4
* v1.23 => v1.8.6
* master => v1.8.6

KCP log:
> E0105 13:32:57.978491       1 controller.go:317] controller/kubeadmcontrolplane “msg”=“Reconciler error” “error”=“failed to update CoreDNS deployment: failed to validate CoreDNS: toVersion \“v1.8.4\” must be greater than fromVersion \“v1.8.6\“” “name”=“k8s-upgrade-and-conformance-93j7s5-control-plane” “namespace”=“k8s-upgrade-and-conformance-87whq1” “reconciler group”=“controlplane.cluster.x-k8s.io” “reconciler kind”=“KubeadmControlPlane”

I would suggest updating the job configs to always upgrade to the CoreDNS version corresponding to the Kubernetes version we’re upgrading to
