### ISSUE TITLE
📖 CAPG missing in provider-contract file 

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api#5852]
In this `docs/book/src/clusterctl/provider-contract.md` the labels section is missing CAPG. Since we have GCP as a provider, it will be nice to have it under the label section.
In the labels table add 
```sh
CAPG:  cluster.x-k8s.io/provider=infrastructure-gcp
```

/kind documentation
/good-first-issue
/help

**Comment by killianmuldoon** [comment]
Thanks for pointing this out @sayantani11! Do you have time to work on it?
