### ISSUE TITLE
Upgrade to +2 minor version on a managed topology fails when using KCP

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#5853]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Create a ClusterClass that uses a `KubeadmControlPlaneTemplate` for the control plane. 
Create a cluster that uses the above ClusterClass.

Upgrade the version on cluster topology to a +2 minor version (eg: v1.21.2 -> v1.23.0). The change is accepted by the webhook but the topology reconciliation fails. The `TopologyReconciled` condition is false with the following message.

```
- lastTransitionTime: "2021-12-13T17:04:12Z"
  message: 'error reconciling the Cluster topology: failed to update KubeadmControlPlane/docker-cluster-6w52x: failed to patch KubeadmControlPlane/docker-cluster-6w52x: admission webhook "validation.kubeadmcontrolplane.controlplane.cluster.x-k8s.io" denied the request: KubeadmControlPlane.controlplane.cluster.x-k8s.io "docker-cluster-6w52x" is invalid: spec.version: Forbidden: cannot update Kubernetes version from v1.21.2 to v1.23.0'
  reason: TopologyReconcileFailed
  severity: Error
  status: "False"
  type: TopologyReconciled
```

**What did you expect to happen:**

One of the following:
* The cluster webhook should deny a change that is not allowed.
* KCP should allow the change.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This is because of the difference in the webhook rules we have for `cluster.topology` and `KCP`. While `cluster.topology.verison` is allowed to change to a +2 minor version KCP does not allow such a change. This inconsistency between the 2 webhooks causes this issue.

KCP webhook: https://github.com/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go#L547-L560
Cluster topology webhook: https://github.com/kubernetes-sigs/cluster-api/blob/main/api/v1beta1/cluster_webhook.go#L227-L237

The simplest approach to solve this would be to block +2 minor upgrades in cluster topology webhook. However this would mean that a user who is using a different control plane (eg: `AWSManagedControlPlane`) that would allow for a +2 minor jump is now restricted to do a +1 minor upgrade.  - This is probably okay.
If we decide to do the above we should probably capture this in the ClusterClass proposal doc and CAPI book.

**Environment:**

- Cluster-api version: `abc2ea00199f90afd634bdc8d7d760bb9e4c8329`
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
/area topology
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
It would be great to hear opinion of people managing other control plane providers about the suggested changes

**Comment by vincepri** [comment]
+1 to keep it consistent and block

**Comment by sbueringer** [comment]
If there is no other feedback, I agree that we should block +2 upgrades in the topology as well.

We can always make the validation less restrictive in the future if a +2 upgrade works with other controlplane providers.

**Comment by ykakarap** [comment]
Looks like we can go ahead with blocking +2 upgrade in topologies. I will go ahead and update the webhook and open an PR for this.
