### ISSUE TITLE
Cannot install longhorn storage on CAPI cluster

### ISSUE THREAD

**Issue by darashevcstbg** [kubernetes-sigs/cluster-api#5862]
**What steps did you take and what happened:**
I have successfully installed CAPI cluster, but I am not able to install longhorn storage on it, because they have a requirement to have 'open-iscsi' package installed on each node.

**What did you expect to happen:**
To have a mechanism in CAPI to make changes to Linux VMs using SSH or some other mechanism.

**Anything else you would like to add:**
Link to longhorn requirements: https://longhorn.io/docs/1.2.2/deploy/install/#installation-requirements

Add a way to execute a command on the nodes when they are being allocated.

**Environment:**

- Cluster-api version: 0.3.4
- Minikube/KIND version: -
- Kubernetes version: (use `kubectl version`):  v1.21.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
There are already ways to make what you are requiring.
- Add pre/post kubeadm commands if using the kubeadm bootstrap providers
- Use image builder to create your own images 

/remove-kind bug
/kind support
/priority awaiting-more-evidence

**Comment by fabriziopandini** [comment]
/close
given that is seems the answer above addressed the issue
