### ISSUE TITLE
Expose upgrade strategy in MachineDeploymentTopology/MachineDeploymentClassTemplate

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#5863]
**User Story**

As a cluster operator I would like to configure the MachineDeployment upgrade strategy for each of my worker node pools in a manage topology.

**Detailed Description**

This is not exposed today so the scenarios supported are very limited.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature
/area topology

**Comment by sbueringer** [comment]
For prior art, please see: https://github.com/kubernetes-sigs/cluster-api/issues/6278#issuecomment-1070914169

Most if it applies to this issue as well (except that we only have to add something to the MachineDeployment types, the control plane should not be adjusted)

**Comment by sbueringer** [comment]
I think I would only add it to MachineDeploymentTopology for now and not to the MachineDeploymentClass (as mentioned in the title)

**Comment by sbueringer** [comment]
Strategy has been added to both
/close
