### ISSUE TITLE
`clusterctl generate provider` should return early if working with incompatible provider versions

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#5864]
**User Story**

As a user when I run `clusterctl generate provider` on a version of a provider that is incompatible I want it to return early with an error messages that says that the version is incompatible with the version of clusterctl.

**Detailed Description**

Ref: https://github.com/kubernetes-sigs/cluster-api/issues/5851#issuecomment-993088847 for more details.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature
/area clusterctl

**Comment by sbueringer** [comment]
Afaik we already have a similar logic for `clusterctl init`

**Comment by tharun208** [comment]
@ykakarap I like to work on this

**Comment by sbueringer** [comment]
@tharun208 Feel free to assign yourself the issue with `/assign`

**Comment by ykakarap** [comment]
@tharun208 Thanks for offering to work on the issue. Later, I will add some details here that should help you get started.

**Comment by ykakarap** [comment]
@tharun208 Here are some details that should help you get started:

The `generate provider` command directly calls `c.GetProviderComponents`. We want to add a step to check if the version used are compatible before getting the provider components. 

I think you can start with adding a `GenerateProvider` to `clusterctlClient` (and the corresponding interface) that takes as input `providerName`, `providerType` and `options client.ComponentsOptions`. This function should perform a check to validate that the input provider version is compatible with the version of clusterctl and after it passed the validation it should call `GetProviderComponents` as previously being called.

**Checking compatibility:**
A provider version is considered compatible if it matches the contract version of clusterctl. To fetch the contract version of the provider you can do the following:
```golang
// Get the providers metadata.
configRepository, err := c.configClient.Providers().Get(providerName, provider.GetProviderType())
if err != nil {
	return "", err
}
providerRepository, err := c.repositoryClientFactory(configRepository, c.configClient)
if err != nil {
	return "", err
}
latestMetadata, err := providerRepository.Metadata(providerVersion).Get()
if err != nil {
	return "", err
}
// Gets the contract for the current release.
currentVersion, err := version.ParseSemantic(providerVersion)
if err != nil {
	return "", errors.Wrapf(err, "failed to parse current version for the %s provider", providerName)
}
releaseSeries := latestMetadata.GetReleaseSeriesForVersion(currentVersion)
if releaseSeries.Contract != clusterv1.GroupVersion.Version {
	return "", errors.Errorf("current version of clusterctl is only compatible with %s providers, detected %s for provider %s", clusterv1.GroupVersion.Version, releaseSeries.Contract, provider.ManifestLabel())
}
```
_Note_: Please adjust the returns in the above example as needed for the function.
Ref [here](https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/cluster/installer.go#L224-L253) for an example of checking contract.

You can use [`parseProviderName`](https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/common.go#L63) and the [`DefaultVersion`](https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/repository/client.go#L141) function of the repository client to compute the version of the input provider.

If the contracts match then we can consider that the version of the provider is compatible with the version of clusterctl. Once validated then you can go ahead and call `c.GetProviderComponents(providerName, providerType, options)` and print the output as being done previously.

I hope this information is helpful for you to get started on this issue.

Please feel free to reach out if you have any questions. 🙂

**Comment by tharun208** [comment]
thank you much. will look into this
