### ISSUE TITLE
Migrate from glog to klog

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#587]
As per [EMEA implementer's call](https://docs.google.com/document/d/1IZ2-AZhe4r3CYiJuttyciS7bGZTTx4iMppcA8_Pr3xE/edit), glog should be replaced with k8s.io/klog

Fixes: https://github.com/kubernetes-sigs/cluster-api/issues/587

**Comment by randomvariable** [comment]
Further information in https://groups.google.com/forum/#!topic/kubernetes-dev/7vnijOMhLS0

**Comment by stpabhi** [comment]
@randomvariable I would like to work on it

**Comment by randomvariable** [comment]
Thanks!

/lifecycle active
/assign @stpabhi

**Comment by randomvariable** [comment]
That message is ok, you're ready to go.

**Comment by vincepri** [comment]
@stpabhi Any updates on the migration to klog? 

Also related to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/397

**Comment by stpabhi** [comment]
@vincepri #590

**Comment by vincepri** [comment]
woot, thanks!

**Comment by vincepri** [comment]
Seems after merging #590, I can't see any logs when running `clusterctl` in cluster-api-provider-aws. Is this a known issue? Are there any further changes needed?

**Comment by vincepri** [comment]
I believe this can be closed. Feel free to reopen otherwise.

/close
