### ISSUE TITLE
Support to propagate properties in-place from MachineDeployments to Machines

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#5880]
**User Story**

As a cluster operator I would like to change the NodeDrainTimeout/NodeDeletionTimeout for the Machines belonging to a MachineDeployment.

**Detailed Description**

Today this would trigger a rolling upgrade honouring current NodeDrainTimeout in Machines which defeats the purpose of the change. We should consider NodeDrainTimeout to propagate in-place from MachineDeployments to Machines.

**Anything else you would like to add:**
If we do this, base code should be scalable to have a clean way to include fields.
This might be relevant for https://github.com/kubernetes-sigs/cluster-api/pull/6255 as well

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by sbueringer** [comment]
Note: there's now also a NodeDeletionTimeout which we should treat the same way.

**Comment by enxebre** [comment]
/retitle support to propagate properties in-place from MachineDeployments to Machines

**Comment by fabriziopandini** [comment]
moving out from the milestone because this will land later when also label propagation is fully addressed (hopefully in 1.4)

**Comment by sbueringer** [comment]
@ykakarap Can you please double-check if this issue is now done with our recent implementations and close the issue if it makes sense.

**Comment by ykakarap** [comment]
This issue is addressed in the in-place propagation work (https://github.com/kubernetes-sigs/cluster-api/issues/7731).

The feature is merged and available. 

We can close this isuse.

/close
