### ISSUE TITLE
Machines should skip draining when deleting a cluster

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#5881]
**What steps did you take and what happened:**
When deleting a cluster Machines will try to drain and honour NodeDrainTimeout.

**What did you expect to happen:**
When deleting a Cluster Machines there's no point in draining so we could ensure draining is skipped e.g use the ExcludeNodeDrainingAnnotation to avoid pdb lock situations.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
On top of my memory, this should be already the case (or at least this was), but I might be wrong.
Do you have any evidence of this not working?

/milestone v1.1

**Comment by enxebre** [comment]
@fabriziopandini just double checked and you're right, this is gated by `isDeleteNodeAllowed`.
/close
