### ISSUE TITLE
Support reset password for machine

### ISSUE THREAD

**Issue by ruifaling** [kubernetes-sigs/cluster-api#5883]
**User Story**

In the current version,after launch a cluter,if we do not know the password for root from the image ,we can only connet to the vm by keypair,I hope we can reset the password,the we could connect to the vm by password

**Detailed Description**

I hope we could reset the root password for vm by cloudinit when launch a cluster

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
/milestone v1.1
I have some concerns about the request, see comment on the PR
