### ISSUE TITLE
Too small timeout for watch in `ClusterCacheTracker`

### ISSUE THREAD

**Issue by qmloong** [kubernetes-sigs/cluster-api#5888]
**What steps did you take and what happened:**
A default timeout value was set here.
https://github.com/kubernetes-sigs/cluster-api/blob/46df46a9b6d3efe44d88148105fe63380ac531bd/controllers/remote/cluster.go#L64

And `ClusterCacheTracker` will new config by default.

https://github.com/kubernetes-sigs/cluster-api/blob/46df46a9b6d3efe44d88148105fe63380ac531bd/controllers/remote/cluster_cache.go#L181

These may cause too frequently watch request to apiserver.

Logs -4:
```
I1227 18:27:43.305280   60390 reflector.go:535] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Watch close - *v1.Node total 0 items received
I1227 18:27:53.310549   60390 reflector.go:535] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Watch close - *v1.Node total 1 items received
I1227 18:28:03.314984   60390 reflector.go:535] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Watch close - *v1.Node total 0 items received
<truncated>
```

Logs -8
```
I1227 18:27:13.093106   60017 streamwatcher.go:114] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout or context cancellation while reading body)
I1227 18:27:13.093136   60017 reflector.go:535] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Watch close - *v1.Node total 1 items received
I1227 18:27:13.093201   60017 round_trippers.go:432] GET https://10.129.96.169:6443/api/v1/nodes?allowWatchBookmarks=true&resourceVersion=251051&timeout=10s&timeoutSeconds=568&watch=true
I1227 18:27:13.093209   60017 round_trippers.go:438] Request Headers:
I1227 18:27:13.093214   60017 round_trippers.go:442]     User-Agent: manager/unknown cluster-cache-tracker (darwin/amd64) cluster.x-k8s.io/unknown
I1227 18:27:13.093218   60017 round_trippers.go:442]     Accept: application/vnd.kubernetes.protobuf, */*
```

**What did you expect to happen:**

Don't request so many unnecessary watch

**Anything else you would like to add:**

`log -8` show `timeoutSeconds` are set by `k8s.io/client-go v0.23.0`
https://github.com/kubernetes/client-go/blob/782ff783b635df54ddf44d55f3bd3e48eb4dcb9a/tools/cache/reflector.go#L401
```go
		timeoutSeconds := int64(minWatchTimeout.Seconds() * (rand.Float64() + 1.0))
		options = metav1.ListOptions{
			ResourceVersion: resourceVersion,
			// We want to avoid situations of hanging watchers. Stop any wachers that do not
			// receive any events within the timeout window.
			TimeoutSeconds: &timeoutSeconds,
			// To reduce load on kube-apiserver on watch restarts, you may enable watch bookmarks.
			// Reflector doesn't assume bookmarks are returned at all (if the server do not support
			// watch bookmarks, it will ignore this field).
			AllowWatchBookmarks: true,
		}
```

But it may have lower priority to the `timeout` , I didn't go into it

**Environment:**
N/A no matter what env.

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
Some questions in order to better understand the problem at stake:

What is the expected behavior/timeout you are proposing?

If I look at logs at level 4 it seems that we are already using 10 seconds timeout (18:27:43, then:53, then:03), and if I'm not wrong in most cases this is combined with exponential backoff; IMO this is already a good compromise between what we need (the watch to be up and running, which unfortunately is not happening fast enough) and not being too aggressive on the target cluster. 

Is this a generalized problem or something you observe in specific moments of the Cluster lifecycle? Is this related to a specific infrastructure/network configuration?

**Comment by qmloong** [comment]
> Is this a generalized problem or something you observe in specific moments of the Cluster lifecycle? Is this related to a specific infrastructure/network configuration?

I think this is a generalized problem. But actually,  it seems to be no real bad impact so far except redundant log above level 4..  I will take a closer look at `watch` code piece to confrim this short timeout value when I am free. 
Thank you for the response.
