### ISSUE TITLE
webhook-error when using Experimental flags and multiple providers

### ISSUE THREAD

**Issue by ninlil** [kubernetes-sigs/cluster-api#5916]
**What steps did you take and what happened:**

I have 2 main setup scenarios (see below)
I have 2 tests (using the capi-quickstart-tutorial, see below)

### A) One provider at a time:
```sh
VSPHERE_USERNAME="mgmt-user" \
VSPHERE_PASSWORD="*****" \
EXP_CLUSTER_RESOURCE_SET="true" \
clusterctl init --infrastructure vsphere --wait-providers

EXP_MACHINE_POOL="true" \
EXP_AKS="true" \
clusterctl init --infrastructure azure --wait-providers
```

### B) setup core before providers
```sh
EXP_CLUSTER_RESOURCE_SET="true" \
EXP_MACHINE_POOL="true" \
EXP_AKS="true" \
clusterctl init --core cluster-api

VSPHERE_USERNAME="mgmt-user" \
VSPHERE_PASSWORD="*****" \
EXP_CLUSTER_RESOURCE_SET="true" \
clusterctl init --infrastructure vsphere --wait-providers

EXP_MACHINE_POOL="true" \
EXP_AKS="true" \
clusterctl init --infrastructure azure --wait-providers
```
### 1) vsphere
```sh
clusterctl generate cluster capi-quickstart \
		--config ../clusterctl-v.yaml \
		--infrastructure vsphere \
		--kubernetes-version v1.23.0 \
		--control-plane-machine-count=3 \
		--worker-machine-count=1 | \
  	kubectl apply -f - --dry-run=server
```
### 2) azure (aks)
```sh
clusterctl generate cluster capi-quickstart \
		--config ../clusterctl-azure.yaml \
		--infrastructure azure \
		--flavor aks \
		--kubernetes-version v1.23.0 \
		--worker-machine-count=1 | \
  	kubectl apply -f - --dry-run=server
```

**What did you expect to happen:**

Test 1 and 2 should work flawless regardless of setup scenario.

But when using setup scenario A, the 2nd provider to get installed always fails on a webhook.
If "vsphere" is installed last I get error `failed calling webhook "default.clusterresourceset.addons.cluster.x-k8s.io"`
If "azure" is installed last I get error `failed calling webhook "default.machinepool.cluster.x-k8s.io"`

When using setup scenario 2 both tests works just fine.

**Anything else you would like to add:**

When the scenario (and instructions) basically says "create 1st real cluster using 'kind'; transfer capi to real cluster; then add additional providers", this will not work when we need experimental flags that can't be added to the existing system (without explicit documentation).
Also, the EXP_* flags are stated on each provider but this seems to indicate they are actually required in 'core'.. that's kind-of misleading.

(This is an awesome product btw!)

**Environment:**

- Cluster-api version: v1.0.2
- Minikube/KIND version: kind v0.11.1 go1.17.5 linux/amd64
- Kubernetes version: (use `kubectl version`): v1.21.1 (on server and client)
- OS (e.g. from `/etc/os-release`): Ubuntu 20.03.3 LTS

/kind bug

**Comment by fabriziopandini** [comment]
This is not an error, but as stated above, a consequence of the fact that experimental features (the ones documented in https://cluster-api.sigs.k8s.io/tasks/experimental-features/experimental-features.html) must be enabled in CAPI first (as well as in the subsequent calls to init).

That means that in scenario A, you need to set both EXP_CLUSTER_RESOURCE_SET and EXP_MACHINE_POOL before the first init, no matter the order you install providers.

Also please note that you can install more providers in a single init operation
```
VSPHERE_USERNAME="mgmt-user" \
VSPHERE_PASSWORD="*****" \
EXP_CLUSTER_RESOURCE_SET="true" \
EXP_MACHINE_POOL="true" \
EXP_AKS="true" \
clusterctl init --infrastructure azure, vsphere --wait-providers
```

Last note. We are aware that now it is complex to change feature flags on installed providers (https://cluster-api.sigs.k8s.io/tasks/experimental-features/experimental-features.html#enabling-experimental-features-on-existing-management-clusters); hopefully, the implementation of [this proposal](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20201020-capi-provider-operator.md) will make things simpler, but this is still a work in progress...

/remove-kind bug
/kind support

**Comment by fabriziopandini** [comment]
/close
Feel free to re-open if there are updates
