### ISSUE TITLE
📖Add KubeVirt to providers list

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api#5918]
Now that we have Cluster Api Provider KubeVirt, that should be added to the providers list [here](https://cluster-api.sigs.k8s.io/reference/providers.html)
To make the changes, add
Kubevirt with link redirecting to the repository: https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt

/kind documentation

**Comment by MukulKolpe** [comment]
Hey @sayantani11, can I work on this issue?

**Comment by AvineshTripathi** [comment]
@MukulKolpe Yes it is open you can do a self assign by commenting `/assign`
