### ISSUE TITLE
Handle kubeadm 1.24 kubelet ConfigMap name change

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5921]
With kubeadm 1.24 the UnversionedKubeletConfigMap feature gate is moving to beta and thus is enabled per default. 

According to [upcoming notable changes in kubeadm 1.24](https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/XJhn8bpvHac), `"kubeadm upgrade" will automatically handle this`. As we're not running `kubeadm upgrade` during upgrade I suspect we have to implement something on our side.

/kind feature
/area control-plane

**Comment by sbueringer** [comment]
@neolit123 If you have a moment, would be great to hear what you think about it.

**Comment by fabriziopandini** [comment]
On top of my mind in KCP we have specific logic for
1. creating new versioned KubeletConfigMap before upgrade
2. editing new versioned if required (e.g for adapting the cgroup default driver change happened in kubeadm few version ago)

I think that 1 should stop happening starting from 1.24, but a deeper analysis is required.

/milestone v1.1
It will be nice to get into the release + backport if the change is simple
