### ISSUE TITLE
Restructure KCP internal package

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5936]
We've recently moved the KCP controllers package into internal/controllers in https://github.com/kubernetes-sigs/cluster-api/pull/5929. 

As a follow-up it would be great if we can restructure (at least) the files directly in the `controlplane/kubeadm/internal` package into new sub-packages.

xref: https://github.com/kubernetes-sigs/cluster-api/pull/5929#pullrequestreview-851748669

/kind cleanup
/area control-plane

**Comment by fabriziopandini** [comment]
/milestone v1.1
(this probably won't make the release, but it will be bumped in the next one as soon we will create it)

**Comment by fabriziopandini** [comment]
/reopen
/lifecycle frozen

the KCP package structure is still not ideal, let's keep this around

**Comment by fabriziopandini** [comment]
(doing some cleanup on old issues without updates)
/close
