### ISSUE TITLE
TestMachineHealthCheck_Reconcile test is flaky

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5937]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

TestMachineHealthCheck_Reconcile fails from time to time with the following error:
```yaml
    machinehealthcheck_controller_test.go:1298: 
        Timed out after 30.001s.
        Expected
            <int>: 0
        to equal
            <int>: 1
```

Recent runs:
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-main/1480841629660090368
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-main/1479675607234121728

/kind flake
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
/area health

fyi @killianmuldoon

**Comment by fabriziopandini** [comment]
@killianmuldoon is this test still flaky?

**Comment by killianmuldoon** [comment]
Apparently not - happy to close this for now. 

:slightly_smiling_face:
