### ISSUE TITLE
Parameterize provider resources location for Tilt

### ISSUE THREAD

**Issue by gab-satchi** [kubernetes-sigs/cluster-api#5939]
**User Story**

As a developer I would like to use a custom location for my provider resources so I could work with Supervisor based resources in CAPV. 

**Detailed Description**
In CAPV, we store default set of resources under the expected `config/default` path and Supervisor based resources under `config/supervisor`. Developers (and users) would only load one or the other set of resources at a time. 

This issue is to request parameterizing [this path](https://github.com/kubernetes-sigs/cluster-api/blob/main/hack/tools/tilt-prepare/main.go#L195) in the `tilt-prepare` so that developers can load Supervisor based resources. Defaulting to `config/default` should also be done to not break any existing users' workflows. 

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
/close

This has been implemented by https://github.com/kubernetes-sigs/cluster-api/pull/9936
