### ISSUE TITLE
clusterctl: split machines into two yaml documents

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#594]
As it stands, machines.yaml contains both control plane nodes and worker nodes. `clusterctl` has logic to split these apart and apply them at the correct times.

Being able to replicate clusterctl workflow without needed clusterctl would allow people to more easily understand what it is doing.

I propose that `clusterctl` takes two flags, `--control-planes control-planes.yaml` and `--workers workers.yaml` instead of one `--machines machines.yaml` flag.

This would improve the debug-ability by allowing users to manually create the control plane nodes and before creating worker nodes.
This separation would remove logic in clusterctl that splits apart a machines yaml document into control planes and workers making clusterctl a little more dumb and a little less magical (easier to understand).

**Comment by davidewatson** [comment]
I actually dislike that there are already three options to `clusterctl`. Instead, what if the actuators were responsible for controlling the sequencing between control-plane and worker configuration (perhaps by watching for Cluster.Status.APIEndpoint to be set (or some similarly explicit field)?

**Comment by dlipovetsky** [comment]
Discussed in meeting 11/21/2018. See [meeting notes.](https://docs.google.com/document/d/16ils69KImmE94RlmzjWDrkmFZysgB2J4lGnYMRN89WM/edit#heading=h.kl99vdvs9oqh).

**Comment by chuckha** [comment]
Based on the meeting notes it looks like this is the opposite direction people want to go in. I'll open a new ticket if necessary but I think the desire here was obsoleted by the clusterctl phases work.
