### ISSUE TITLE
Replace `github.com/gosuri/uitable` with `github.com/olekukonko/tablewriter`

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#5941]
**Detailed Description**

`github.com/olekukonko/tablewriter` is introduced in the #5893 . This new library is more feature rich and can be used to do everything that `github.com/gosuri/uitable`. Therefore, it would be good to replace the later with the former so that we dont have to include two table libraries.

**Anything else you would like to add:**

`github.com/gosuri/uitable` is currently being used by the `clusterctl describe cluster` command.

[Miscellaneous information that will assist in solving the issue.]

/kind feature
/area clusterctl

**Comment by DiptoChakrabarty** [comment]
I would like to try
/assign

**Comment by DiptoChakrabarty** [comment]
@ykakarap have got everything almost ready however there is an issue in the testing part https://github.com/kubernetes-sigs/cluster-api/blob/58f834f6ef181113b78f65c14be4685572dc6c10/cmd/clusterctl/cmd/describe_cluster_test.go#L280-L287

How to access specific rows and column in tablewriter like uitable , there does not seem to be method to implement line 287.

The tests can be modified to be like these here https://github.com/olekukonko/tablewriter/blob/master/table_test.go

**Comment by ykakarap** [comment]
@DiptoChakrabarty Firstly, thank you for stepping up to work on this. 👍🏼 
I answered your query on the PR. Take a look.

**Comment by fabriziopandini** [comment]
/kind cleanup
/milestone v1.1
/area clusterctl
Being a cleanup, there is a chance that this will probably get merged after the release
