### ISSUE TITLE
Consider to dissolve or move internal/topology

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5946]
The idea is to potentially dissolve or move the internal/package, so we don’t have 3 topology packages below internal, which might be confusing.

internal/package consists of:
* internal/topology/check
* internal/topology/variables

### internal/topology/check

used by:
* internal/webhooks:
  * check.MachineDeploymentTopologiesAreUniqueAndDefinedInClusterClass(newCluster, clusterClass)
  * check.ClusterClassesAreCompatible(oldClusterClass, clusterClass)
  * check.ClusterClassReferencesAreValid(newClusterClass)
  * check.MachineDeploymentClassesAreUnique(newClusterClass)
  * check.ClusterClassesAreCompatible(oldClusterClass, newClusterClass)
* internal/controllers/topology:
  * check.ObjectsAreStrictlyCompatible
  * check.ObjectsAreCompatible
  * check.ObjectsAreInTheSameNamespace

=> Webhooks and controller use separate functions, if we want we could inline the respective funcs in the controller/webhook package depending on usage, but we previously wanted to explicitly have a dedicated check package.

#### Options for internal/topology/check:

* leave as is
* inline the funcs in the respective package
* move the check package in either controller or webhooks

=> In my opinion we should try to avoid dependencies controller=>webhooks or webhooks=>controller so I would prefer either leave it as is or inline the funcs.

### internal/topology/variables

Currently exclusively used by internal/webhooks but we were planning to also validate variables from the controller.

#### Options for internal/topology/variables

* leave as is
* inline the funcs into webhooks
* move the check package in either controller or webhooks

=> I assume that we will implement the variable validation in controller at some point. Therefore, I think we should leave it as is to avoid dependencies controller=>webhooks or webhooks=>controller.

### Overall

I think that it’s better to make shared dependencies between controllers and webhooks explicit and try to avoid direct dependencies between them whenever possible. Which essentially means I would leave the package as is.

/kind cleanup
/area topology

**Comment by fabriziopandini** [comment]
Let's keep this around while we figure it out if the current code organization is confusing for maintainers or it just works
/milestone v1.2

**Comment by fabriziopandini** [comment]
/close
given that there is no clear way forward and we can eventually create a new issue as soon as we figure out a better code organization
