### ISSUE TITLE
Workload cluster loses worker nodes after restoring the management cluster from a velero backup

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api#5957]
**What steps did you take and what happened:**
- Create a workload cluster with 3 MachineDeployments, with one replica each (1 CP node and 3 worker nodes)
- Setup velero with the AWS provider for backing up management cluster
- Backup the management cluster 
- Delete & recreate the management cluster
- Restore the management cluster using the earlier created backup
- The number of worker nodes after restoring the management cluster is less than 3

**What did you expect to happen:**
The workload cluster gets correctly adopted by the new management cluster after restore from the backup.

**Anything else you would like to add:**
From additional combing of the logs and the vCenter UI, we saw some of the worker nodes got deleted after the restore. 
Additional discrepancies that were seen:
- MachineSet, say `ms-1`, which was created by MachineDeployment, say `md-1`, has another MachineDeployment, say `md-2` set as its owner (by checking the owner references)
- From the logs, we saw that the Machine objects owned by `ms-1` were being deleted

**Environment:**

- Cluster-api version: v1.0.1
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): v1.21.x
- OS (e.g. from `/etc/os-release`): `ubuntu`

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by killianmuldoon** [comment]
@srm09 Have you by any chance got the Cluster yamls (with templates and MachineDeployments etc. to reproduce this?

**Comment by killianmuldoon** [comment]
I think @ykakarap and I have reproduced this issue after making some assumptions about the set up. We've identified two separate problems:


1) Machines being recreated on restore
This could be reproduced by specifying the same selectors on each of the MachineDeployments. When all of the MDs shared selectors adoption of the MachineSets was non-deterministic. There was a race condition and any MD could end up with any MS. Additionally an MD could end up with more than one MS. @srm09 To confirm this could you show us the selectors used in the MDs in your set up?

**Possible solution**: Ensure selectors are unique for each MachineDeployment.

2) MachineSets being adopted by the wrong MachineDeployment
This could be reproduced in most cases where the Cluster was not paused ahead of `velero backup create` being run. The issue appears to be a race condition where the MachineSets create a new Machine on their first reconcile. It can then adopt an existing Machine, leaving it with more current replicas than desired. 

On a subsequent reconcile it will then try to delete one of the Machines. In this case it could delete the existing machine. @srm09 Would it be possible to re-run your backup and restore with a paused cluster to see if this holds in your case?

**Possible solution**: Pause the cluster before running `velero backup create`. Unpause the cluster once `velero restore create` has completed.
**Alternative solution**: Use the --restore-resource-priorities flag on `velero server` to ensure that Machines are always created before MachineSets and MachineSets are always created before MachineDeployments.

**Comment by ykakarap** [comment]
Note: The proposed alternate solution for the `Machines being recreated on restore` problem will fix the problem in most cases. However, the problem could still persist when the controller picks up stale cache (a race case). The best practice would be to always pause and unpause the cluster.

**Comment by DanielXiao** [comment]
Even users pause the cluster before Velero backup, it does not solve this issue. During Velero restore, it will clean up OwnerReferences of each resource, see [resetMetadataAndStatus](https://github.com/vmware-tanzu/velero/blob/1e24d6ce718fc8fee890db34643e5be361fa5c7d/pkg/restore/restore.go#L1586). When users unpause the cluster after restoring, each MachineDeployment will try to adopt all orphan MachineSets belong to this cluster, see [getMachineSetsForDeployment](https://github.com/kubernetes-sigs/cluster-api/blob/9640fe8cfff7033a61c54a7171572ea018e74d86/internal/controllers/machinedeployment/machinedeployment_controller.go#L274). The MachineDeployment 's selector match MachineSets by following cluster name label:
`
  Selector:
    Match Labels:
      cluster.x-k8s.io/cluster-name:  wl13
`
Each MachineSet of a Cluster will have the same label:
`
Name:         wl13-md-1-5866cc59fd
Namespace:    ns13
Labels:       cluster.x-k8s.io/cluster-name=wl13
              machine-template-hash=1422771598
              node-pool=wl13-worker-pool
              velero.io/backup-name=097b21c2-6e83-4830-baa6-6453bb5d2bbf
              velero.io/restore-name=097b21c2-6e83-4830-baa6-6453bb5d2bbf
`
When there are multiple MachineDeployments in a Cluster, they may adopt MachineSets do not belong to it. Following is an example, MachineSet wl13-md-1-5866cc59fd is adopted by MachineDeployment wl13-md-2:
`
Name:         wl13-md-1-5866cc59fd
Namespace:    ns13
Labels:       cluster.x-k8s.io/cluster-name=wl13
              machine-template-hash=1422771598
              node-pool=wl13-worker-pool
              velero.io/backup-name=097b21c2-6e83-4830-baa6-6453bb5d2bbf
              velero.io/restore-name=097b21c2-6e83-4830-baa6-6453bb5d2bbf
Annotations:  machinedeployment.clusters.x-k8s.io/desired-replicas: 1
              machinedeployment.clusters.x-k8s.io/max-replicas: 2
              machinedeployment.clusters.x-k8s.io/revision: 2
              machinedeployment.clusters.x-k8s.io/revision-history: 1
API Version:  cluster.x-k8s.io/v1beta1
Kind:         MachineSet
Metadata:
  Owner References:
    API Version:           cluster.x-k8s.io/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  MachineDeployment
    Name:                  wl13-md-2
    UID:                   6685f113-10fd-4451-b626-a93ec2b40bd9
...
`
Maybe label `machine-template-hash` should be added to MachineDeployment's Selector to match only its own MachineSet.

**Comment by killianmuldoon** [comment]
`machine-template-hash` isn't good enough by itself as, if I remember right, this isn't necessarily unique from one MachineDeployment to another. 

The correct way to approach this is to add a selector with the MachineDeployment name - or some other machine deployment unique value - that's the default way to create MachineDeployment selectors. 

If you leave the MachineDeployment Selector empty on creation, as in the `clusterctl generate` output you get the following:

```
    selector:
      matchLabels:
        cluster.x-k8s.io/cluster-name: capi-quickstart
        cluster.x-k8s.io/deployment-name: capi-quickstart-md-0
```

This is then propagated to the MachineSet selector which looks like:

```
    selector:
      matchLabels:
        cluster.x-k8s.io/cluster-name: capi-quickstart
        cluster.x-k8s.io/deployment-name: capi-quickstart-md-0
        machine-template-hash: "283736771"
```

If selectors are set up like this there should be no issue with adoption. I'll create an issue to surface this as a problem though as we should have some sort of warning about configuring selectors in this way.

**Comment by killianmuldoon** [comment]
#3770 related

**Comment by fabriziopandini** [comment]
/close
due to lack of feedback, but fixing selectors should be enough and recent work on ownerRef makes things more deterministic.

Nevertheless, it seems to me that velero intentionally dropping owners' references, finalizers, managed fields leads to a reconciliation storm / the entire system being in a sort of unset state for some time, and this isn't ideal and potentially opens up to edge conditions/racy conditions. Food for tough...

**Comment by jayunit100** [comment]
ownerRef more deterministic --> by deterministic, do we mean, more precise, i.e. less likely to result in incorrect adoption ?

**Comment by jayunit100** [comment]
wondering if this is fiexed per fabrizios comments, i did a check, and in NEWERE cluster-api-controller:v1.2.7 ...  i see MORE metadata in the ownerRef, which i assume means that its unambiguous now and you wouldnt get incorrect adoptions. 

Which would mean that this issue has been solved....
 can someone confirm that ? 


```
ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: MachineDeployment
      name: tkg-vc-antrea-md-0-*lkqms* <-- extra data
```

vs the old owner ref:


```
Metadata:
  Owner References:
    API Version:           cluster.x-k8s.io/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  MachineDeployment
    Name:                  wl13-md-*2*
    UID:                   6685f113-10fd-4451-b626-a93ec2b40bd9
```

**Comment by killianmuldoon** [comment]
It doesn't look to me as if there's any additional metadata there. The `name` field is the same for both as it must refer to an actual object by groupKind i.e. `cluster.x-k8s.io/v1beta1/MachineDeployment`.

The difference in name structure here could be down to a number of things - but possibly is the result here of ClusterClass vs non-clusterclass generated MachineDeployments.

Regardless of the above, the ownerReference is the outcome of the adoption, not what it is based on (with a couple of caveats). The ambiguity in adoption in this issue was caused by the specification of the selectors used by the MachineDeployment and MachineSet to choose which Machines to set owner references on.

**Comment by jayunit100** [comment]
thx killian so this issue persists we assume then , bc nobody has changed the way those selectors work ?

**Comment by killianmuldoon** [comment]
Similar to Deployments -> Pods these selectors are defaulted but the default can be overwritten by the end user. We have an issue open for doing more to warn end-users about bad selectors https://github.com/kubernetes-sigs/cluster-api/issues/6283, but blocking there's not much support for blocking bad selectors completely.

The default selectors that CAPI uses are "correct" in the sense that adoption should always work for those cases.

**Comment by jayunit100** [comment]
bringing this full circle, @killianmuldoon clarified to me that part of the solution is using the CAPI default selectors which are, to qoute killian *good* :) .  So sounds like, at the very least, theres a workaround to this issue, or its no longer something we'd call a "bug", and the real thing here is : dont overwrite CAPI selectors unless you really know what your doing!
