### ISSUE TITLE
CRD awscluster state is not updated after succesful change regarding bastion

### ISSUE THREAD

**Issue by ksiadz** [kubernetes-sigs/cluster-api#5965]
**What steps did you take and what happened:**

I modified existing clusters to not have bastion enabled. The events logs suggested it worked fine but awsclusters CRDs state was not updated. 

**What did you expect to happen:**
`kubectl get awsclusters`
Output:
`NAMESPACE           NAME                CLUSTER             READY   VPC                     BASTION IP`
`clusters-dev        dev-db              dev-db              true    vpc-XXX   XX.XXX.XXX.XXX`

While I expected to have is updated bastion info in a cluster.

The events do show a change happen successfully:
`kubectl get events -A | grep bastion `
Output:
`clusters-dev        12m         Normal    SuccessfulTerminateBastion                      awscluster/dev-db                               Terminated bastion instance "i-XXXX"
`

**Environment:**

- Cluster-api version: v1.0.1  and v1.0.2 as well
- Kubernetes version: v1.21.5
- OS: debian

/kind bug

**Comment by fabriziopandini** [comment]
moving to Cluster API provider AWS

**Comment by ksiadz** [comment]
Okey thank you, will do that and close this one
