### ISSUE TITLE
Missing nil check in `dockerMachineController` while getting ownerCluster

### ISSUE THREAD

**Issue by aartij17** [kubernetes-sigs/cluster-api#5984]
**What steps did you take and what happened:**
This is a follow up on [this](https://github.com/kubernetes-sigs/cluster-api/issues/5961) where getting the `ownerRef` does not return a cluster. There could be a nil pointer exception due to insufficient nil checking around - 
https://github.com/kubernetes-sigs/cluster-api/blob/c6e30491b05f3c6bffed4e456601d6a27439efb0/test/infrastructure/docker/internal/controllers/dockermachine_controller.go#L397

Both cluster and error can be nil from the GetOwnerCluster function but this is not caught by our checks.

/kind bug

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by aartij17** [comment]
I discussed this with @killianmuldoon  and turns out the `nil` check done in the switch case here is sufficient. Sorry about that! 
https://github.com/kubernetes-sigs/cluster-api/blob/03d6487983735f03eece198fc870b660734775f8/test/infrastructure/docker/internal/controllers/dockermachine_controller.go#L399

**Comment by fabriziopandini** [comment]
@aartij17 thanks for checking this and reporting back!
