### ISSUE TITLE
add actual cluster version of workload clusters to status

### ISSUE THREAD

**Issue by zmalik** [kubernetes-sigs/cluster-api#5988]
**User Story**

As a developer/user/operator I would like to see the actual version of workload/remote clusters in the status of the cluster CR to gain more visibility during upgrades. 

**Detailed Description**

To add the cluster version to the `.status.version` fetching the information from the remote clusters  `/version` API endpoint. 
This is helpful when doing operations like cluster upgrades. Once we have the version in status we can use it to emit metrics also. 

**Anything else you would like to add:**
Ideally we implement it using remoteClient and not through control-plane nodes. So it works for both managed(AKS/EKS) and self-managed clusters 

/kind feature

**Comment by sbueringer** [comment]
@zmalik Thx for opening the issue. Can you please take a look at https://github.com/kubernetes-sigs/cluster-api/issues/5341. I think we might be able to deduplicate.

**Comment by zmalik** [comment]
thanks @sbueringer, somehow missed the other issue when was searching for similar issues.
I will close this one
