### ISSUE TITLE
Reconciler for Node + Machine objects

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#60]
_From @rsdcastro on January 29, 2018 22:15_

This reconciler would watch/poll for node changes to reconcile machine and nodes objects. Example scenarios: VM gets deleted manually or nodes are created w/o using cluster API.

This could include metrics to detect if tooling are acting on the cluster and not going through the cluster API.

_Copied from original issue: kubernetes/kube-deploy#532_

**Comment by rsdcastro** [comment]
_From @roberthbailey on February 7, 2018 6:30_

Isn't this part of the machine controller itself?

**Comment by rsdcastro** [comment]
IMO this reconciler would NOT be, for the most part, specific to any provider but something that is generic. For that reason, marking it as cluster-api.

**Comment by rsdcastro** [comment]
cc @k4leung4 @mkjelland 

Can you comment on this?

**Comment by k4leung4** [comment]
The machine controller currently already watches for node changes.
I think this issue can be closed.
