### ISSUE TITLE
Remove pull-cluster-api-make-main job

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6001]
We currently have a job called `pull-cluster-api-make-main` which is optional for PRs and not run per default, i.e. it can be triggered manually on PRs (`/test pull-cluster-api-make-main`). Given that we didn't use the job for a long time and that the verifications in the job are also covered by other jobs / GitHub actions we want to remove the job now (Slack xref: https://kubernetes.slack.com/archives/C8TSNPY4T/p1643213661202300).

To remove the job we have to do the following:
* kubernetes/test-infra:
    * Remove the Job configuration in https://github.com/kubernetes/test-infra/blob/802fa645f173c637230d5e947246832279d55466/config/jobs/kubernetes-sigs/cluster-api/cluster-api-presubmits-main.yaml#L21-L46
* kubernetes-sigs/cluster-api:
    * Remove the ./scripts/ci-make.sh shell script

Feel free to ask if there are any questions :)

/kind cleanup
/good-first-issue
/help-wanted

**Comment by furkatgofurov7** [comment]
As per the discussion on slack, I would like to work on this issue.

/assign
