### ISSUE TITLE
ownerReferences on ClusterResourceSetBinding are not re-updated after restoring from a backup

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#6007]
**What steps did you take and what happened:**

* Create a kind cluster and initialize it to a management cluster
* Install velero on the management cluster
* Create a workload cluster (Example name: `my-cluster`)
* Apply a ClusterResourceSet (Example name: `cni`)
* Create a backup of the management cluster using velero
* Delete the management cluster
* Recreate a kind cluster and initialize it to a management cluster
* Install velero on new management cluster
* Restore the velero back created in previous steps

**What did you expect to happen:**
The restored `ClusterResourceSetBinding` with name `my-cluster` should have ownerReferences to `{kind: Cluster, name: my-cluster}` and `{kind: ClusterResourceSet, name: cni}` but has no ownerReferences.

**Anything else you would like to add:**

*Potential fix*:
The `getOrCreateClusterResourceSetBinding` function should ensure owner references if the ClusterResoureSetBinding already exists too, not just if it is creating it for the first time. Ref: https://github.com/kubernetes-sigs/cluster-api/blob/main/exp/addons/internal/controllers/clusterresourceset_helpers.go#L112-L147

**Environment:**

- Cluster-api version: `18c7ec867f7e8eb690aa7708afe6bbc27fec1498`
- Minikube/KIND version: 
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by tranthang2404** [comment]
I have the same problem

**Comment by killianmuldoon** [comment]
@ykakarap have you been able to look at this? I can take this up otherwise if you'd like.

**Comment by ykakarap** [comment]
@killianmuldoon I did get to take a look at this. Please go ahead if you would like :)
