### ISSUE TITLE
🐛  Broken links in ./docs/book/src/developer/providers/implementers-guide/generate_crds.md

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#6027]
There are link in the doc ./docs/book/src/developer/providers/implementers-guide/generate_crds.md that are broken since the merging of #6018 

These links are in:
./docs/book/src/developer/providers/implementers-guide/generate_crds.md

The broken links are:
[✖] https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html#apply-the-contract-version-label-clusterx-k8sioversion-version1_version2_version3-to-your-crds → Status: 404
[✖] https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html#upgrade-to-crd-v1 → Status: 404
[✖] https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html#add-matchpolicyequivalent-kubebuilder-marker-in-webhooks → Status: 404
[✖] https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html#refactor-kustomize-config-folder-to-support-multi-tenancy-when-using-webhooks → Status: 404
/kind bug

/area documentation

**Comment by sbueringer** [comment]
@killianmuldoon Can we also make the last link in this list (https://github.com/kubernetes-sigs/cluster-api/pull/6028/files) a relative link when we fix the other list items?

**Comment by sbueringer** [comment]
Broken links have been fixed.
/close
