### ISSUE TITLE
Increase number of test failures required for an email alert

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#6037]
Prow / test-infra currently has an email alert set up for the tests it runs for Cluster API (and everything else). The mail is sent to a mailing list defined here: https://github.com/kubernetes/k8s.io/blob/74f4f122fdd7e4ddbe40f450f98b710edce91996/groups/sig-cluster-lifecycle/groups.yaml#L20

Because our e2e tests have a number of flakes this email list can be quite noisy. We're allowed to set a value in test-infra which defines how many failures happen before a mail is sent to the list. The value is currently set to 2 (I think across all periodic tests).

I propose setting this value to 4 for:
- periodics on from older versions of CAPI
- periodics for less recent upgrades (not latest -1 => latest)
- minK8s e2e tests

And setting the value to 3 for:
- non-upgrade periodic e2e tests 
-  K8s latest -1 => latest upgrade test

I think changing increasing this value will make the list less noisy, and make it more useful, improving how we're tracking our current test state.

**Comment by killianmuldoon** [comment]
@fabriziopandini WDYT?

**Comment by sbueringer** [comment]
/area testing

+1 from my side. I think tuning the alerts to get to a level were we actually look at them because they are not full of cases which we just want to ignore (2 failures in a row) is very very useful.

I personally would route those alerts afterwards in my inbox again and not just divert them into a folder that I'm never really looking at.

**Comment by sbueringer** [comment]
One note. I think it should be fine to just set the threshold everywhere to 4. In case of periodic e2e tests that's not an issue as they are ran every hour. So we'll get the mail after 4 hours instead of 3. In case of upgrade tests 3 could be not high enough.

**Comment by killianmuldoon** [comment]
Good point about the periodics being hourly - I'm not stuck to these values and we can revisit after changing them to see how to keep them at useful levels.

**Comment by sbueringer** [comment]
I was mostly suggesting that because I suspect 3 is too low for upgrade jobs and it's just simpler to set everything to 4 :)

**Comment by fabriziopandini** [comment]
let's bump to 4 for simplicity, then we can reconsider after a short period (but I agree current configuration is too aggressive and people just ignore emails)

**Comment by fabriziopandini** [comment]
/close
test infra PR is merged
