### ISSUE TITLE
Unable to update KubeadmControlPlane v1alpha3 resource due to v1beta1 conversion

### ISSUE THREAD

**Issue by vivek-koppuru** [kubernetes-sigs/cluster-api#6041]
**What steps did you take and what happened:**
(I can give more details on this if needed too)
1. Apply a KubeadmControlPlane v1alpha3 resource with cluster-api controllers that use v1beta1 api version.
2. Re-apply the same v1alpha3 resource without any changes.

Result:
```
The KubeadmControlPlane "test" is invalid: status.version: Forbidden: cannot be modified
```

**What did you expect to happen:**
I would expect it to apply without the webhook failing. This is because the conversion logic doesn't fill in the value for `status.version`, resulting in this change showing up in the diff here: https://github.com/kubernetes-sigs/cluster-api/blob/v1.0.2/controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go#L166

**Anything else you would like to add:**
We have found this when upgrading our dependency on capi from v1alpha3 to v1beta1 apis. During that process, we have a controller that reconciles capi resources using the `Update` command, and noticed that when applying a v1alpha3 template with the capi controllers that used v1beta1 apis, it was failing at the webhook for this error. While looking into this issue, I noticed that because v1alpha3 doesn't have this field, it doesn't translate the value during the v1beta1 conversion. 

Now as a workaround, what we have done was patched our version of capi with the intention to bring in the fix here. I have created a PR for now that essentially ignores a new field to ignore when calculating these differences. https://github.com/kubernetes-sigs/cluster-api/pull/6042

The second option would be to ignore the status section altogether because the status is not allowed for editing anyways, but it is a more intrusive change and I would assume that it might require changes to other webhooks to ignore status too if we follow a similar logic here. 

The third option would be to use the `version` under `spec` from the original resource when we are doing the conversion. We can introduce a new override for status similar to this: https://github.com/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/api/v1alpha3/conversion.go#L108. However, this would need to be done only to workaround this issue of the webhook failing.

I believe the first option with the PR would be the least impact and isolated to the problem at hand, which was why we went forward with the patch at the time. I would love to get thoughts from the community here or on the PR!

**Environment:**

- Cluster-api version: v1.0.2
- Minikube/KIND version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
Great finding, thx for opening the issue and the PR!

(I'll comment further on the PR)

**Comment by fabriziopandini** [comment]
Great finding.
On a side note, please be aware that v1alpha3 is going to be deprecated soon https://cluster-api.sigs.k8s.io/contributing#support-and-guarantees (after that date support for this API version could be dropped any time)

**Comment by vivek-koppuru** [comment]
Closing issue due to discussion in the linked PR. It should be intended behavior based on our use case.
