### ISSUE TITLE
[MachinePool] Stuck on Deleting phase, blocks whole Cluster deletion due to Finalizers

### ISSUE THREAD

**Issue by dntosas** [kubernetes-sigs/cluster-api#6049]
**What steps did you take and what happened:**
1. Created a cluster with AWS Provider and then wanted to delete it. Note: Also enabled `MachinePool` feature.
2. Wanted to delete the cluster so proceed with deletion of all CRD resources (CAPI+CAPA)
3. Looking on AWS Cloud Provider, all cloud resources deleted successfully
4. Looking on CRDs, all resources delete successfully (AWSMachinePool, ControlPlane, etc)
4. But, `MachinePool` CRDs stuck on `Deleting` phase thus also `Cluster` resource stuck on `Deleting` phase
5. Manual edited MachinePools and deleted the Finalizers, unstuck the process.

**What did you expect to happen:**
All resources to pruned successfully without manual intervention.

**Anything else you would like to add:**
I suspect is something with `MachinePool` Finalizers that need tweaking?

**Environment:**
- Cluster-api version: v1.0.3
- Kubernetes version: (use `kubectl version`): v1.21.9
- OS (e.g. from `/etc/os-release`): ubuntu-20.04

/kind bug
 
Let me know if you think I should post this also on CAPA side :)

**Comment by fabriziopandini** [comment]
is it possible to have MachinePool logs for starting?
/priority awaiting-more-evidence

**Comment by dntosas** [comment]
Ok I just bring up two identical clusters. Waited for all cloud/k8s resources to get ready and then deleted them. The one cluster just pruned successfully. The other one is stuck on Deleting phase and it seems that the MachinePool resources are the ones that are not deleted successfully so to unlock also the Cluster one.

Logs from CAPI Controller:
```
 controller/cluster "msg"="Cluster still has children - deleting them first" "name"="XXX" "namespace"="XXX" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Cluster" "count"=4
 controller/cluster "msg"="Cluster still has descendants - need to requeue" "name"="XXX" "namespace"="XXX" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Cluster" "descendants"="Machine pools: XXX-nodes-monitoring-2c,XXX-nodes-2b,XXX-nodes-2c,XXX-nodes-2a" "indirect descendants count"=0
```

Logs from CAPA Provider:
```
controller/awscluster "msg"="error deleting security groups" "error"="failed to delete security group \"sg-XXX\": DependencyViolation: resource sg-XXX has a dependent object\n\tstatus code: 400, " "cluster"="XXX" "name"="XXX" "namespace"="XXX" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster"
controller/awscluster "msg"="Reconciler error" "error"="failed to delete security group \"sg-XXX\": DependencyViolation: resource sg-XXX has a dependent object\n\tstatus code: 400, " "name"="XXX" "namespace"="XXX" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster"
controller/awscluster "msg"="Reconciling AWSCluster delete" "cluster"="XXX" "name"="XXX" "namespace"="XXX" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster"
controller/awscluster "msg"="Deleted security group" "cluster"="XXX" "name"="XXX" "namespace"="XXX" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "kind"="cluster managed" "security-group-id"="sg-XXX"
[AWSCluster.infrastructure.cluster.x-k8s.io "XXX" not found, awsclusters.infrastructure.cluster.x-k8s.io "XXX" not found]
controller/awscluster "msg"="Reconciler error" "error"="awsclusters.infrastructure.cluster.x-k8s.io \"XXX\" not found" "name"="XXX" "namespace"="XXX" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster"
controller/awsmachine "msg"="Reconciler error" "error"="awsmachines.infrastructure.cluster.x-k8s.io \"XXX-cp-1904484284-nctwz\" not found" "name"="XXX-cp-1904484284-nctwz" "namespace"="XXX" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSMachine
```

**Comment by dntosas** [comment]
To unblock the process, manually removed Finalizers from Machinepool objects and everything went smooth.

I suspect an RC that CAPA objects are removed before giving the CAPI the status that can proceed with deletion so we got this loop? WDYT?

**Comment by fabriziopandini** [comment]
I would suggest to move this issue to CAPA, given that it seems that security group deletion is the step blocking the entire chain

**Comment by dntosas** [comment]
thnx @fabriziopandini
