### ISSUE TITLE
Add ability to get list of cluster to clusterctl

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api#605]
For providers that plan to use a management cluster pattern, it will be a better user experience for users of clusterctl to be able to list all target clusters created by the management cluster.  Yes, users can use kubectl, but the break from clusterctl to kubectl is a mental break for users who are not developers.

**Comment by roberthbailey** [comment]
We discussed during a meeting last year how much to make clusterctl into a "cluster management tool" vs a "bootstraping only tool". I don't think that there was broad consensus on what we want it to end as, but my recollection is that for now we'd keep it scoped to a bootsrapping tool.

**Comment by roberthbailey** [comment]
Let's close this one, and we can re-open later or create a new issue if/when we decide to add this sort of behavior to clusterctl.
