### ISSUE TITLE
bump default cert-manager version to v1.7.0

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#6055]
**Detailed Description**

The default version of cert-manager in CAPI is `v1.5.3`.
https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/config/cert_manager_client.go#L30

A new version `v1.7.0` of cert-manager is available. 

This issue is to discuss upgrading cert-manager to the new version.

**Anything else you would like to add:**

FYI: Version `v1.5.3` is ~6 months old.

**Comment by sbueringer** [comment]
+1 to upgrade to v1.7.0.

Release notes look fine for us. There is a statement about that server side apply is used and thus Kubernetes 1.18 is required. But that should be fine as we only start management clusters with Kubernetes v1.19+ (and have a job which makes sure that they don't break)

**Comment by lentzi90** [comment]
Please note that upgrading to v1.7 [requires some extra steps](https://cert-manager.io/docs/installation/upgrading/upgrading-1.6-1.7/) since it drops support for some older API versions. I'm not aware how CAPI is handling upgrades of cert-manager but I think it is worth checking this.

It is probably only an issue with older installations since they could still have some resources stored with older version APIs.

**Comment by sbueringer** [comment]
Thx for the hint.

I think it should be fine as we migrated to v1 cert-manager resources with v0.4.0 (24 June 2021). So in theory core CAPI and all providers shouldn't use those old versions anymore. 

During upgrade:
* with clusterctl: we delete/create the resources (https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-upgrade-v0-3-to-main/1491314721595330560/artifacts/clusters/clusterctl-upgrade-qk0q62/clusterctl-upgrade.log) (delete: Certificate, CertificateRequest, Issuer create: Certificate, Issuer)
* with GitOps tools: I assume when they are using published manifests of CAPI >=v0.4.0 there should be a write on all the cert-manager resources contained in those manifests (Certificate, Issuer). Then they should be stored as v1 in etcd too.
    * There are also CertificateRequest's which are created by cert-manager. But the .status.certificate has an expiry of 1 month, so I would assume it's also updated/re-created sooner or later)

But I think to be absolutely safe it would be good to mention the migration guide (https://cert-manager.io/docs/installation/upgrading/remove-deprecated-apis/) in this doc: https://cluster-api.sigs.k8s.io/tasks/upgrading-cluster-api-versions.html
