### ISSUE TITLE
inform users about klog flags removal when importing Kubernetes v1.26

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6069]
With Kubernetes 1.23 klog flags have been deprecated **in Kubernetes**:
* Mail: https://groups.google.com/a/kubernetes.io/g/dev/c/_mRNTYDb7ys/m/WYpvLbMCAgAJ
* Release notes: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#deprecation-of-klog-specific-flags
* Documentation: https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#klog
* KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components

These flags are all also exposed in CAPI (I assume via `klog.InitFlags()`)

I didn't have the time yet to dig deeper, but the KEP provides a lot of context and details about the change.

My impression is that the deprecation itself doesn't impact us directly as the change seems to be in [k8s.io/component-base/logs](http://k8s.io/component-base/logs) and we are using klog directly.

But we should probably at least consider deprecating/removing the klog flags in CAPI too (see the reasons for it in the KEP).

/kind feature

**Comment by fabriziopandini** [comment]
/milestone v1.2
Let's start by raising awareness in the office hours and an add a note in the migration doc

**Comment by sbueringer** [comment]
I added it to the agenda for Wednesday. With the additional context we now have, that we could adopt component-base/logs  to deprecate the klog flags and get JSON logging.

**Comment by sbueringer** [comment]
@fabriziopandini klog flags are now deprecated in CAPI (done by the JSON log format PR), e.g.:
```bash
      --log-file string                        If non-empty, use this log file (DEPRECATED: will be removed in a future release, see https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components)
```

How do we want to handle it from a tracking-perspective? If current plans hold the flags will be automatically gone when we upgrade to Kubernetes v1.26. So we don't need this / or a follow-up issue for a year or so.

**Comment by fabriziopandini** [comment]
I would keep this issue and
/retitle [inform users about klog flags removal when importing Kubernetes v1.26](https://github.com/kubernetes-sigs/cluster-api/issues/6069#)

**Comment by ykakarap** [comment]
Closing this issue as per https://github.com/kubernetes-sigs/cluster-api/pull/7955#issuecomment-1398176702 and moving this as a line item in the [release tracking issue](https://github.com/kubernetes-sigs/cluster-api/issues/7672).

/close
