### ISSUE TITLE
Reformat shell command and output in the book

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#6073]
We're currently using a couple of different patterns in the Cluster API book for presenting commands and their output. 

A common pattern [used in the quickstart guide](https://cluster-api.sigs.k8s.io/user/quick-start.html#apply-the-workload-cluster), is to have two code blocks, one with the command and one with the output. The alternative [proposed here](c/f https://github.com/kubernetes-sigs/cluster-api/pull/6026#discussion_r796514087
) is to have the command and the output contained in the same code block in the text. There are also instances of having the command inline in the text with the output in a code block and other permutations.

We should try to come to consistent usage in how we present commands and their output throughout our docs. A related issue is that the width of our output is very often bigger than what the book presents, leaving a scrollbar at the bottom of the output block. This makes it harder for readers to quickly understand what the correct output of a command should be. 

cc/ @sbueringer 

c/f https://github.com/kubernetes-sigs/cluster-api/pull/6026#discussion_r796514087

**Comment by fabriziopandini** [comment]
/lifecycle frozen
/good-first-issue

+1 to change to have consistently two code blocks, one with the command - so it can be easily copied and executed locally - and one with the output
