### ISSUE TITLE
Fix github redirect issue

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#6074]
Clusterctl is not correctly able to correctly download a redirected repo a link after a github repository is moved. This issue surfaced with #6051. That issue was fixed in the short term by updating the URL for cert manager. This solution is not future proof as a future redirect may result in more failures in clusterctl.

To reproduce:
1) Set the cert manager repository to `https://github.com/jetstack/cert-manager.git` [The inverse of the Troubleshooting guide](https://cluster-api.sigs.k8s.io/user/troubleshooting.html#failed-clusterctl-init---failed-to-get-cert-manager-object)
2) Run clusterctl init

The above will result in Cluster creation failing with an error like: "failed to get cert-manager object".

Initial triaging found that the bug is coming up as part of the clusterctl [github client](https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/repository/repository_github.go). 

/kind bug

**Comment by palnabarun** [comment]
@fabriziopandini -- It completely got out of my mind that I forgot to raise a pull request with the exploration I did. Filed one now.

I will try to resolve the WIP task. The test I added isn't actually working.

**Comment by fabriziopandini** [comment]
(doing some cleanup on old issues without updates)
/close
unfortunately, no one is picking up the task. the thread will remain available for future reference
