### ISSUE TITLE
release CAPO 0.5.1 encounter issue of clusterctl init

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#6076]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

I am releasing CAPO https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/tag/v0.5.1
and after the release , found this error during

```
./clusterctl -v 10 init --infrastructure openstack

Error: failed to get provider components for the "openstack" provider: failed to get repository client for the InfrastructureProvider with name openstack: error creating the GitHub repository client: failed to get GitHub latest version: failed to find releases tagged with a valid semantic version number

```

then I debug the issue and found in 
https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/repository/repository_versions.go#L79

the function will be called twice one with major/minor=nil/nil and next time with major/minor=1/0
then at 2nd time all current CAPO tag will be ignored due to 
https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/repository/repository_versions.go#L100

and lead to the error above, currently CAPO versions are 
[v0.5.1 v0.5.0 v0.4.0 v0.4.0-beta.0 v0.3.4 v0.3.3 v0.3.2 v0.3.1 v0.3.0 v0.3.0-rc.0 v0.2.0]

so the question is are CAPI clusterctl expecting providers to have same version to clusterctl ? 
e.g clusterctl is running 1.0.x then we have to create 1.0.x in providers ? 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by jichenjc** [comment]
I commented line  100-103 lines and rebuild clusterctl 
https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/repository/repository_versions.go#L100

then at least I can successfullly run `clusterctl init`

```
Creating MutatingWebhookConfiguration="capo-mutating-webhook-configuration"
Creating ValidatingWebhookConfiguration="capo-validating-webhook-configuration"
Creating inventory entry Provider="infrastructure-openstack" Version="v0.5.1" TargetNamespace="capo-system"

Your management cluster has been initialized successfully!

You can now create your first workload cluster by running the following:

  clusterctl generate cluster [name] --kubernetes-version [version] | kubectl apply -f -


```


```
root@jitest19:~# kubectl get pods  -A
NAMESPACE                           NAME                                                             READY   STATUS    RESTARTS   AGE
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-55f5795c76-r9vrf       1/1     Running   0          23s
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-65f495cf5b-qfdf6   1/1     Running   0          22s
capi-system                         capi-controller-manager-57bbc5d67-8l8vq                          1/1     Running   0          25s
capo-system                         capo-controller-manager-76fdfb96c4-7dxgf                         1/1     Running   0          20s
cert-manager                        cert-manager-848f547974-l8lmn                                    1/1     Running   0          41s
cert-manager                        cert-manager-cainjector-54f4cc6b5-jtpzx                          1/1     Running   0          41s
cert-manager                        cert-manager-webhook-58fb868868-97s5b                            1/1     Running   0          41s
kube-system                         coredns-74ff55c5b-qmhjx                                          1/1     Running   0          3m52s
kube-system                         coredns-74ff55c5b-wbk7t                                          1/1     Running   0          3m52s
kube-system                         etcd-kind-control-plane                                          1/1     Running   0          4m4s
kube-system                         kindnet-g6d8w                                                    1/1     Running   0          3m52s
kube-system                         kube-apiserver-kind-control-plane                                1/1     Running   0          4m4s
kube-system                         kube-controller-manager-kind-control-plane                       1/1     Running   0          4m4s
kube-system                         kube-proxy-vrj7b                                                 1/1     Running   0          3m52s
kube-system                         kube-scheduler-kind-control-plane                                1/1     Running   0          4m4s
local-path-storage                  local-path-provisioner-78776bfc44-zbkb2                          1/1     Running   0          3m52s
```

**Comment by sbueringer** [comment]
@jichenjc I think one issue is that the CAPO metadata.yaml already contains a 1.0 release series which doesn't exist: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/metadata.yaml#L13-L15

The idea of this file is to map CAPO release series (v0.3.x, v0.4.x, v0.5.x) to CAPI contracts (v1alpha3,v1alpha4,v1beta1).

I think the problem is that clusterctl tries to use CAPO v1.0.x which doesn't exist. Can you drop v1.0.x from the YAML on the release and test it again?

**Comment by jichenjc** [comment]
@sbueringer indeed , thanks for the hints 
I updated the metadata.yaml and it fixed the problem :)
