### ISSUE TITLE
Rebuild tilt-prepare on tilt-up

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6077]
We are currently running `make tilt-prepare` on tilt up, but this doesn't rebuild the binary even if there are code changes if it already exists.

Recent example: We fixed the cert-manager issue and then everyone had to manually delete tilt-prepare to get a new version of tilt-prepare with the fixed clusterctl code.

I think it's very non-obvious that `tilt up` is using an outdated version of tilt-prepare/clusterctl if a user doesn't explicitly delete the binary.

So I think to make sure that we are able to use/validate the current state of clusterctl in `tilt up` it would be great if we find a way to make sure that the binary is up-to-date.

P.S. Maybe there is a simple way to "fix" the Makefile target to rebuild the binary when there are changes.

/kind feature

**Comment by sbueringer** [comment]
Agree, it applies to other binaries too, but clusterctl is in my opinion one of the things we want to test, so it would be nice to use the latest on tilt up.

And for non-experts of core CAPI it's very hard to know about those nuances (e.g. "Why do I still have that cert-manager issue with tilt up").

My thinking was along the lines of:
> If we would just build every time, this shouldn't be an issue, as 99% of the build is already cached so it should be very fast.

I was thinking that maybe we can force make to just always build the binary. (Apparently that's something you can do with PHONY, but for me it didn't work in that case)

**Comment by johannesfrey** [comment]
Hi,

I also stumbled upon this. There are two things that come to my mind:

1. Force make to always build the tilt-prepare binary in the Tiltfile:
```diff
diff --git a/Tiltfile b/Tiltfile
index 32dcd4607..e81e9ce19 100644
--- a/Tiltfile
+++ b/Tiltfile
@@ -361,7 +361,7 @@ def prepare_all():
                 debug = debug,
             )
 
-    cmd = "make tilt-prepare && ./hack/tools/bin/tilt-prepare {allow_k8s_arg}{tools_arg}{cert_manager_arg}{kustomize_build_arg}{providers_arg}".format(
+    cmd = "make -B tilt-prepare && ./hack/tools/bin/tilt-prepare {allow_k8s_arg}{tools_arg}{cert_manager_arg}{kustomize_build_arg}{providers_arg}".format(
         allow_k8s_arg = allow_k8s_arg,
         tools_arg = tools_arg,
         cert_manager_arg = cert_manager_arg,
```

2. Or make it a Phony target in the Makefile:

```diff
diff --git a/Makefile b/Makefile
index 9088ae632..f26014b6e 100644
--- a/Makefile
+++ b/Makefile
@@ -740,6 +740,7 @@ $(CONVERSION_GEN): $(TOOLS_DIR)/go.mod # Build conversion-gen from tools folder.
 $(CONVERSION_VERIFIER): $(TOOLS_DIR)/go.mod # Build conversion-verifier from tools folder.
        cd $(TOOLS_DIR); go build -tags=tools -o $(BIN_DIR)/conversion-verifier sigs.k8s.io/cluster-api/hack/tools/conversion-verifier
 
+.PHONY: $(TILT_PREPARE)
 $(TILT_PREPARE): $(TOOLS_DIR)/go.mod # Build tilt-prepare from tools folder.
        cd $(TOOLS_DIR); go build -tags=tools -o $(BIN_DIR)/tilt-prepare sigs.k8s.io/cluster-api/hack/tools/tilt-prepare
```

But there are probably better ways to do this.

@killianmuldoon As you assigned yourself, should I prepare a PR for this or are you currently in the process of doing this anyways?

**Comment by killianmuldoon** [comment]
/unassign

@johannesfrey Feel free to open a PR 😄
