### ISSUE TITLE
`clusterctl upgrade` e2e tests should detect if upgrade causes unexpected rollouts

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#6094]
**User Story**

The clusterctl upgrade e2e tests currently do not detect if an upgrade operation results in rollout of KCP, MachineDeployments, etc.

Having such a test could help in detecting cases like https://github.com/kubernetes-sigs/cluster-api/issues/6093.

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by sbueringer** [comment]
+1 I assume you mean extending the existing clusterctl upgrade test 
+1 do doing the same for the self hosted test (which uses clusterctl move)

**Comment by sbueringer** [comment]
This has been implemented for the clusterctl upgrade test: https://github.com/kubernetes-sigs/cluster-api/pull/6184
So I thin only doing the same for the self-hosted test is left.

**Comment by ykakarap** [comment]
> This has been implemented for the clusterctl upgrade test: #6184 So I think only doing the same for the self-hosted test is left.

Issue for adding rollout check to self hosted e2e tests: https://github.com/kubernetes-sigs/cluster-api/issues/6925

**Comment by sbueringer** [comment]
Okay. I'll close this issue given we have a separate one for self-hosted

/close
