### ISSUE TITLE
how to config kube-proxy mode

### ISSUE THREAD

**Issue by ruifaling** [kubernetes-sigs/cluster-api#6119]
**User Story**

As a developer, I would like to **config the kube-proxy mode for the workload cluster**,becase the default mode is iptables, and I want my cluster to use ipvs mode

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Comment by sbueringer** [comment]
I don't think the help wanted label is appropriate for this issue (yet):
/remove-help
(please see the guidelines: https://github.com/kubernetes-sigs/cluster-api/issues/6119#issuecomment-1038860460)

@ruifaling If I understand correctly this issue can be solved as part of https://github.com/kubernetes-sigs/cluster-api/issues/4512?

**Comment by fabriziopandini** [comment]
+1 for dedup with https://github.com/kubernetes-sigs/cluster-api/issues/4512
