### ISSUE TITLE
Upgrade to controller-runtime v0.11.1

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6138]
Let's upgrade to the latest controller-runtime release v0.11.1 (released today).

Tasks:
* [ ] Upgrade `sigs.k8s.io/controller-runtime v0.11.0` in go.mod files to `sigs.k8s.io/controller-runtime v0.11.1`
* [ ] Run `make modules`

/kind feature

**Comment by furkatgofurov7** [comment]
> * Run `make modules`

*`make generate modules`

**Comment by sbueringer** [comment]
Thx, updated above for future issues like that. I think I've renamed the target after I created this issue :)

**Comment by furkatgofurov7** [comment]
> Thx, updated above for future issues like that. I think I've renamed the target after I created this issue :)

Thanks, I did not know that was updated recently, it is just while working on it I got to know the make target was a bit different, but thanks for noting:)
