### ISSUE TITLE
Reduce frequency of our test jobs and remove redundant jobs

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6141]
I think it's time again to check how frequently our ProwJobs are run and potentially reduce the frequency of some jobs.

(=> is the proposed change)

* main:
  * periodic upgrade jobs: 24h
  * periodic tests: 1h
  * periodic book links: 6h => remove
* release-1.1
  * periodic upgrade jobs: 24h
  * periodic tests: 4h
  * periodic book links: 24h => remove
* release-1.0
  * periodic upgrade jobs: 24h => 48h
  * periodic tests: 4h => 12h
  * periodic book links: 24h
* release-0.4
  * periodic upgrade jobs: 24h => 48h
  * periodic tests: 4h => 12h
  * periodic book links: 24h
* release-0.3
  * periodic tests: 4h => 12h
  * periodic book links: 24h

Proposal:
* [x] Let's integrate the `verify-book-links` job into the build job: (@sbueringer https://github.com/kubernetes-sigs/cluster-api/pull/6159)
    * Context: `make verify-book-links` runs `make -C docs/book verify` which runs `$(MDBOOK) build` 
    * So it actually only builds the book, it doesn't check any broken links (which is what I thought)
    * I think we should run the book build (take ~8 sec) as part of our `pull-cluster-api-build-main` job (takes ~2 min)
      so we have one less job to manage.
    * Then it is run on every PR, we don't run build in periodics but I think we don't have to run the book build periodically
    * I would implement this change on main and release-1.1 and keep older branches as is.
    * P.S. the links are checked on PRs by our `markdown-lint-check` GitHub Action
* [x] test-infra/config/jobs/kubernetes-sigs/cluster-api: Drop `periodic-cluster-api-verify-book-links-main` and `periodic-cluster-api-verify-book-links-release-1-1`
    * Let's please also remove the job from jobs.md in the CAPI repo.
* [x] test-infra/config/jobs/kubernetes-sigs/cluster-api: release-0.4/1.0: Run upgrade tests every 48h (configured in `cluster-api-periodics-release-x-x-upgrades.yaml`)
    * Neither the release branches nor the Kubernetes releases (we only support until 1.23) will change a lot anymore
* [x] test-infra/config/jobs/kubernetes-sigs/cluster-api: release-0.3/0.4/1.0: Run tests every 12h (configured in `cluster-api-periodics-release-x-x.yaml`)
    * The release branches are only occasionally updated. We also run most tests on PRs so I think twice per day should be enough

Just an initial proposal, what do you think?

/kind feature

**Comment by fabriziopandini** [comment]
+1 we can always eventually increase on-demand/if more people steps up in helping handling the test signal

**Comment by sbueringer** [comment]
I opened a PR for the first task.

Tasks 2-4 are
/good-first-issue

**Comment by rayandas** [comment]
Hey folks, can I take this up?

**Comment by sbueringer** [comment]
> Hey folks, can I take this up?

Yes sure. Please only ignore the first task in the list above, I'll take care of that one.

**Comment by rayandas** [comment]
Sure, thanks. 
/assign

**Comment by sbueringer** [comment]
Last PR: https://github.com/kubernetes-sigs/cluster-api/pull/6204
