### ISSUE TITLE
Improve conversion fuzz-testing

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6149]
It looks like we have a gap in our fuzz testing. We had an issue today which should have been covered by the test: #6142

Our current theory is that this happened because there are a lot of fields in InitConfiguration/JoinConfiguration and we just never hit the case were only Patches were set.

Goal of this issue is to improve our fuzz testing so it would catch that issue the next time.

To do this we can use the current main branch and revert the fix PR(https://github.com/kubernetes-sigs/cluster-api/pull/6144). Then we can play around with fuzzing and see if we can adjust the test to detect the case.

One idea from Fabrizio is to configure the nil frequency for fields in the fuzzer (xref: https://github.com/kubernetes-sigs/cluster-api/pull/6144#issuecomment-1041380425)

/area testing

/kind feature

**Comment by fabriziopandini** [comment]
(doing some cleanup on old issues without updates)
/close
unfortunately, no one is picking up the task. the thread will remain available for future reference
