### ISSUE TITLE
Remove v1.23=>v1.24 upgrade test jobs for v0.4 and v1.0

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6157]
As decided today in the CAPI office hours we won't support Kubernetes v1.24 with CAPI v0.4 and v1.0. 
We already have upgrade jobs running which are testing the Kubernetes upgrade from v1.23=>latest (which will be v1.24).
Goal of this issue is to drop those jobs

Tasks:
* [ ] Drop upgrade jobs in test-infra: 
    *  https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-1-0-upgrades.yaml#L224
    * https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-4-upgrades.yaml#L224

/area testing
/kind cleanup
/milestone v1.1

**Comment by sbueringer** [comment]
/good-first-issue

P.S. I'll grep through a few repos and open PR to add myself to groups.

**Comment by Jont828** [comment]
/assign
@sbueringer Happy to take a look since we've worked together on test-infra stuff a little. Just to clarify, all I'd need to do is remove those jobs from the yaml in test-infra?

**Comment by sbueringer** [comment]
> /assign @sbueringer Happy to take a look since we've worked together on test-infra stuff a little. Just to clarify, all I'd need to do is remove those jobs from the yaml in test-infra?

Exactly!

**Comment by Jont828** [comment]
Just opened [this PR](https://github.com/kubernetes/test-infra/pull/25451), does this look right?
