### ISSUE TITLE
windows section for `Install clusterctl` in quick start

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#6161]
Given that now we are shipping a windows amd64 version of clusterctl should we add a `Windows` section to the `Install clusterctl` section of the quickstart?

This would imply that the rest of the quick start flow also needs to be evaluated for the same. 

/area clusterctl
/kind docs

**Comment by sbueringer** [comment]
I wonder how similar the quickstart is for Windows / how much we have to change / add branching for

**Comment by ykakarap** [comment]
I am not sure either. Will have to run through the quickstart on a windows machine to figure out how much and what needs to change.

**Comment by VibhorChinda** [comment]
Steps for installing clusterctl on windows :
1. Go to the working directory where you want clusterctl downloaded.
2. run curl -o clusterctl.exe "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.1/clusterctl-windows-amd64.exe"
3. Add the path of that directory to path environment variable.
4. run clusterctl version command to crosscheck proper working :v:

![clusterctl windows](https://user-images.githubusercontent.com/46090233/154470902-55e87880-0a87-4780-bf55-371711bde53f.PNG)

**Comment by fabriziopandini** [comment]
/milestone v1.2
That would be a nice addition

**Comment by ykakarap** [comment]
@VibhorChinda Would you want to open a PR to add this section to the quick start guide?

**Comment by VibhorChinda** [comment]
@ykakarap I would love to. 
Can you please point out the path of the file where  need to add this section in the repo.

**Comment by VibhorChinda** [comment]
@ykakarap thanks will submit the PR soon :v:
