### ISSUE TITLE
I want to confirm the desired number of KCP's replicas

### ISSUE THREAD

**Issue by Bo0km4n** [kubernetes-sigs/cluster-api#6165]
**User Story**
```
$ k get kcp
NAME                             CLUSTER            INITIALIZED   API SERVER AVAILABLE   REPLICAS   READY   UPDATED   UNAVAILABLE   AGE   VERSION
sample-cluster02-control-plane   sample-cluster02   true          true                   3          3       3         0             31h   v1.21.5
sample-cluster03-control-plane   sample-cluster03   true          true                   3          3       3         0             28h   v1.21.5
```

A operator can't confirm desired replicas when get KCP's information.
`REPLICAS` column means `.status.replicas`.
I guess KCP's information should show the desired numbers to the operators.

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by sbueringer** [comment]
I think that was this issue: https://github.com/kubernetes-sigs/cluster-api/issues/5332
