### ISSUE TITLE
migration-guide: document toleration of control plane taints in manager.yaml

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6172]
Let's document in our migration guide (https://cluster-api.sigs.k8s.io/developer/providers/v1.1-to-v1.2.html) that CAPI providers should tolerate both control plane taints (in manager.yaml). This makes sure they can be also run on v1.24 control plane nodes.

Let's also add a note that if the label is used in the manager.yaml that should be adjusted as well. (e.g. like here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/config/manager/manager.yaml#L52)

In core CAPI this has been added in: https://github.com/kubernetes-sigs/cluster-api/pull/5919/files

/kind feature
/area documentation
/good-first-issue

**Comment by ditsuke** [comment]
@mehabhalodiya are you still working on this one? Would be happy to pick this up instead if not. 😺

**Comment by mehabhalodiya** [comment]
@ditsuke you can pick up this 🙂 
Sorry for delaying!

**Comment by ditsuke** [comment]
Thanks Meha!
/assign

**Comment by ditsuke** [comment]
@sbueringer not sure if its supposed to be up but the migration guide in the issue body is not deployed. I accessed it on the master branch, is it supposed to be up?

**Comment by sbueringer** [comment]
@ditsuke We changed how our books are hosted.

You can find the main branch now here: https://main.cluster-api.sigs.k8s.io/developer/providers/v1.1-to-v1.2.html

https://cluster-api.sigs.k8s.io/ points to release-1.1

For local adjustments I usually use `make serve-book`

**Comment by ditsuke** [comment]
Update: I lost track of this issue. Getting back to work on it now!
