### ISSUE TITLE
Fuzz test - Failed roundtrip conversion in MachineHealthCheck

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#6182]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

```
 python infra/helper.py reproduce kubernetes-cluster-api fuzz_v1alpha3_conversion ~/Downloads/clusterfuzz-testcase-minimized-fuzz_v1alpha3_conversion-5834779365343232
INFO:root:Running: docker run --rm --privileged -i -v /home/naadir/go/src/github.com/google/oss-fuzz/build/out/kubernetes-cluster-api:/out -v /home/naadir/Downloads/clusterfuzz-testcase-minimized-fuzz_v1alpha3_conversion-5834779365343232:/testcase -t gcr.io/oss-fuzz-base/base-runner reproduce fuzz_v1alpha3_conversion -runs=100.
+ FUZZER=fuzz_v1alpha3_conversion
+ shift
+ '[' '!' -v TESTCASE ']'
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export RUN_FUZZER_MODE=interactive
+ RUN_FUZZER_MODE=interactive
+ export FUZZING_ENGINE=libfuzzer
+ FUZZING_ENGINE=libfuzzer
+ export SKIP_SEED_CORPUS=1
+ SKIP_SEED_CORPUS=1
+ run_fuzzer fuzz_v1alpha3_conversion -runs=100 /testcase
/out/fuzz_v1alpha3_conversion -rss_limit_mb=2560 -timeout=25 -runs=100 /testcase < /dev/null
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2005433927
INFO: 244201 Extra Counters
/out/fuzz_v1alpha3_conversion: Running 1 inputs 100 time(s) each.
Running: /testcase
panic: Failed roundtrip for sigs.k8s.io/cluster-api/api/v1beta1.MachineHealthCheck:

  &v1beta1.MachineHealthCheck{
        TypeMeta:   {},
        ObjectMeta: {Generation: 32, DeletionTimestamp: s"0001-01-01 00:00:00 +0000 UTC", DeletionGracePeriodSeconds: &32, Labels: {}, ...},
        Spec: v1beta1.MachineHealthCheckSpec{
                ... // 2 identical fields
                UnhealthyConditions: {},
                MaxUnhealthy:        &{IntVal: 32},
-               UnhealthyRange:      &"\xff  ",
+               UnhealthyRange:      &"�  ",
                NodeStartupTimeout:  &{Duration: s"32ns"},
                RemediationTemplate: &{},
        },
        Status: {ExpectedMachines: 32, CurrentHealthy: 32, RemediationsAllowed: 32, ObservedGeneration: 32, ...},
  }



goroutine 17 [running, locked to thread]:
sigs.k8s.io/cluster-api/api/v1alpha3.doConversionRoundtrip({0xc0001e9880, {0x1ee32f0, 0xc00000c3c0}, 0x0, {0x1ee7590, 0xc0001c6e00}, 0x0, 0x0, {0x0, 0x0, ...}}, ...)
        sigs.k8s.io/cluster-api/api/v1alpha3/conversion_fuzzer.go:188 +0x814
sigs.k8s.io/cluster-api/api/v1alpha3.FuzzV1alpha3Conversion({0x3ca10d0, 0x64, 0x64})
        sigs.k8s.io/cluster-api/api/v1alpha3/conversion_fuzzer.go:92 +0x5f2
main.LLVMFuzzerTestOneInput(...)
        ./main.945853908.go:21
==13== ERROR: libFuzzer: deadly signal
    #0 0x4b1954 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/ubsan/ubsan_diag_standalone.cpp:31:3
    #1 0x456dd8 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
    #2 0x43bfe3 in fuzzer::Fuzzer::CrashCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:233:3
    #3 0x7f83c05b63bf  (/lib/x86_64-linux-gnu/libpthread.so.0+0x153bf)
    #4 0x519ee0 in runtime.raise.abi0 runtime/sys_linux_amd64.s:164

DEDUP_TOKEN: __sanitizer_print_stack_trace--fuzzer::PrintStackTrace()--fuzzer::Fuzzer::CrashCallback()
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
```

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44857 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: [82a6513efb9800279a03b44357ef2a4a14e2085b](https://github.com/kubernetes-sigs/cluster-api/commit/82a6513efb9800279a03b44357ef2a4a14e2085b)
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44857

**Comment by killianmuldoon** [comment]
Is there a way to get added to the permissions to see these bugs?

**Comment by randomvariable** [comment]
I've asked how to change the disclosure to public now instead of May. In the mean time, you can PR yourself into https://github.com/google/oss-fuzz/blob/master/projects/kubernetes-cluster-api/project.yaml

**Comment by sbueringer** [comment]
> I've asked how to change the disclosure to public now instead of May. In the mean time, you can PR yourself into https://github.com/google/oss-fuzz/blob/master/projects/kubernetes-cluster-api/project.yaml

Do we actually want now in case there is a serious security issue found? Or do we assume that won't happen

**Comment by randomvariable** [comment]
Just the specific issue.

**Comment by fabriziopandini** [comment]
/milestone v1.2
candidate for cherry picking

**Comment by killianmuldoon** [comment]
This issue is in the Go encoding Json library at https://cs.opensource.google/go/go/+/master:src/encoding/json/encode.go;drc=2580d0e08d5e9f979b943758d3c49877fb2324cb;l=1067 

It appends bytes in order to make the decodable. I think there might be a way to make the round trip work with badly escaped strings like this - but I don't think we should as this isn't a valid value for unhealthy range - we're [validating the input](https://github.com/kubernetes-sigs/cluster-api/blob/07c0a4809361927b15cde2747b34142b7c7ead15/api/v1beta1/machinehealthcheck_types.go#L54) so it should never be possible to set this value on the MachineHealthCheck.

**Comment by fabriziopandini** [comment]
@killianmuldoon thanks for investigating.
Let's report the problem to the go-fuzz team, so they can consider how to avoid reproting false negatives.
From out side, I'm +1 to close

**Comment by AdamKorcz** [comment]
> @killianmuldoon thanks for investigating. Let's report the problem to the go-fuzz team, so they can consider how to avoid reproting false negatives. From out side, I'm +1 to close

I wrote the fuzzer that reported the issue and am working on a fix to avoid future false positives. Thank you to @killianmuldoon for looking into this issue.
