### ISSUE TITLE
The provided example to enable feature gates via extra_args in Tilt does not work

### ISSUE THREAD

**Issue by johannesfrey** [kubernetes-sigs/cluster-api#6202]
**What steps did you take and what happened:**
Enabling the ClusterClass feature-gate in the tilt-settings.json file via the described way via [extra_args](https://cluster-api.sigs.k8s.io/developer/tilt.html#tilt-settingsjson-fields).
While trying to deploy the ClusterClass resource the admission webhook denies the request with following:
```
Error from server (spec: Forbidden: can be set only if the ClusterTopology feature flag is enabled): error when creating "/tmp/docker-clusterclass.yaml": admission webhook "validation.dockerclustertemplate.infrastructure.cluster.x-k8s.io" denied the request: spec: Forbidden: can be set only if the ClusterTopology feature flag is enabled
```

**What did you expect to happen:**
That the feature-flag is enabled and the deployment works.

**Anything else you would like to add:**
The feature-gates arg is [hard-coded](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/infrastructure/docker/config/manager/manager.yaml#L22) in the providers and by that will end up as the last arg because the ones coming from Tilt are [added before](https://github.com/kubernetes-sigs/cluster-api/blob/main/Tiltfile#L260) to the ENTRYPOINT of the docker image of the manager. AFAIU the only way to use feature-gates is by settings those via [kustomize_substitutions](https://cluster-api.sigs.k8s.io/tasks/experimental-features/experimental-features.html#enabling-experimental-features-on-tilt). So using feature-gates as an example here is a bit misleading.

A solution might be to change the extra_args example to something other than the hard coded ones (`--feature-gates`, `--metrics-bind-addr`, `--leader-elect`) with a note that those are actually hard-coded. See: https://kubernetes.slack.com/archives/C8TSNPY4T/p1645705512971069?thread_ts=1645705141.237239&cid=C8TSNPY4T

**Environment:**

- Cluster-api version: latest
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
<sub>Johannes Frey <[johannes.frey@daimler.com](mailto:johannes.frey@daimler.com)>, Daimler TSS GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>

**Comment by fabriziopandini** [comment]
/milestone v1.2

Q: Can we consider using https://github.com/kubernetes-sigs/cluster-api/tree/main/hack/tools/tilt-prepare to get this working properly?

**Comment by sbueringer** [comment]
I've answered on the PR. Let's investigate a bit more what exactly happens.

**Comment by CecileRobertMichon** [comment]
I'm curious, why not use kustomize substitutions? This is what I have in my tilt-settings.json file and it works fine:

```
  "kustomize_substitutions": {
      ...
      "EXP_MACHINE_POOL": "true",
      "EXP_AKS": "true",
      "EXP_CLUSTER_RESOURCE_SET": "true"
},
...
`

**Comment by sbueringer** [comment]
That definitely works and I'm using it too. We're now just cleaning up Tilt in general so extra_args works expected overall.

**Comment by CecileRobertMichon** [comment]
We have this doc that describes it correctly: https://cluster-api.sigs.k8s.io/tasks/experimental-features/experimental-features.html?highlight=EXP_M#enabling-experimental-features-on-tilt

The other doc about extra_args is inaccurate and should be removed (or we should fix it)

**Comment by sbueringer** [comment]
> We have this doc that describes it correctly: https://cluster-api.sigs.k8s.io/tasks/experimental-features/experimental-features.html?highlight=EXP_M#enabling-experimental-features-on-tilt
> 
> The other doc about extra_args is inaccurate and should be removed (or we should fix it)

PR to improve the tilt env has been merged. I've opened this follow-up PR for the doc: https://github.com/kubernetes-sigs/cluster-api/pull/6263
