### ISSUE TITLE
How do I set the template Node size

### ISSUE THREAD

**Issue by moluzhui** [kubernetes-sigs/cluster-api#6209]
> I'm very sorry, because I didn't find the discuss forum, so I'm asking here

When I use [kind+cluster-api+cluster-autoscaler](https://notes.elmiko.dev/2020/05/22/kubernetes-autoscaler-capd.html) to achieve **automatic scaling**, the size of the new nodes seem to be related to the size of the host, but I want to set the size to quickly implement the scaling test. For example, set the size to 4 cores and 8G memory.

Is there a parameter to meet my needs?

**Comment by killianmuldoon** [comment]
I think this question might be better asked in the [autoscaler repo](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) but as far as I know our Docker infrastructure doesn't let you create nodes of different resource sizes.

**Comment by killianmuldoon** [comment]
There's a few issues related to this on the Kind repo as well: e.g. https://github.com/kubernetes-sigs/kind/issues/877 Seems like you might need to use some infrastructure that has VMs in order to get proper node resources.

**Comment by moluzhui** [comment]
Thank you very much. Maybe I didn't express it clearly, but when I deployed the autoscaling environment in `multiple places`, I found that the new node size was different in different environments, not in one environment.
I'm going to close it and look it up in other projects(kind and autoscaler)
