### ISSUE TITLE
Add flavor templates to CAPD on Tilt

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api#6219]
**User Story**

As a developer working on CAPD, I'd like to be able to easily deploy [multiple example clusters](https://github.com/kubernetes-sigs/cluster-api/tree/main/test/infrastructure/docker/examples) or [any of the templates](https://github.com/kubernetes-sigs/cluster-api/tree/main/test/infrastructure/docker/templates) through local resources in Tilt. 

**Detailed Description**

After I run `tilt up`, I'd like to see buttons for deploying each of the CAPD sample cluster templates. The clusters would have unique names (they're currently all named `my-cluster`) such as `machine-pool-5324` or `simple-cluster-48390`. These names are based on the template followed by a random number between 0-10000 so multiple clusters of the same template can be deployed without overlapping. These would be implemented as local resources in Tilt to run `kc apply -f cluster-template.yaml` for example, and another resource can be added in Tilt to delete all workload clusters. 

This is already described in CAPZ through [this issue](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/542) and [this issue](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/937), and implemented through [this PR](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/673/files) and [this PR](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/937).

For example, currently in CAPZ the flavor deployments look like this.
![image](https://user-images.githubusercontent.com/17480384/156078630-ed47e7ac-d3d2-4867-9b87-fbf96c6944f9.png)

![image](https://user-images.githubusercontent.com/17480384/156078724-fddb8012-c11a-4fa4-9c11-8d1a4a9557db.png)

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by sbueringer** [comment]
I think in CAPZ this was implemented for the cluster-template flavors not for example YAMLs (?). This would be those YAMLs then: https://github.com/kubernetes-sigs/cluster-api/tree/main/test/infrastructure/docker/templates. We don't really have a lot of maintained flavors for CAPD, but we probably also don't need that many.

In general I think this can be useful, even though we're more or less re-implementing `clusterctl config cluster` + `kubectl apply` in Tilt. 

Given that the unique benefit of Tilt is that you can work with local / non-released versions of the code / templates, I wonder if we maybe should implement this as a generic mechanism which leverages `clusterctl config cluster` (by actually using it directly) and local cluster-templates.

I think our goal should be to build this in a way that it not only works with CAPD, but also with other providers which are using the core CAPI Tilt environment.

**Comment by fabriziopandini** [comment]
/milestone v1.2
My first reaction is that the idea is interesting but it needs some refining before implementation it at least around a couple of points:
- is it worth to reinvent kubectl inside tilt? where does this starts/ends? that could be a never-ending story: create cluster, scale cluster etc. etc.; also, ultimately the developer has to be familiar with kubectl as use it.
- UX, given that we are representing templates with the same primitive used for controllers, which IMO is wrong. Have you considered https://docs.tilt.dev/buttons.html 
- portability across providers, given that there is not a convention across repositories defining if/how templates should exist in the code base; also as a developer, more than often I have my own well crafted templates that I want to use, and everyone uses its own preferred location for this

**Comment by Jont828** [comment]
The idea behind this issue was that it would be nice for developers to be able to spin up clusters for several clusters representing simple use cases like a default MachineDeployment or a MachinePool in one click and have autogenerated names so they won't collide. I don't think we'd need to handle scaling or anything complex, just to `kubectl apply` some examples and then the user can scale on their own if they need. For example, when testing MachinePool Machines, it would be convenient to apply everything and install the CNI automatically. 

I'll look into the Tilt buttons and I think the idea of having a template convention across providers is interesting as well. Btw @sbueringer do you mean `clusterctl generate cluster`? And @CecileRobertMichon do you have any thoughts?

**Comment by sbueringer** [comment]
> @sbueringer do you mean clusterctl generate cluster
Oh sorry yes. `clusterctl config cluster` was the previous name of the command, but that's gone now.

**Comment by CecileRobertMichon** [comment]
> is it worth to reinvent kubectl inside tilt? where does this starts/ends? that could be a never-ending story: create cluster, scale cluster etc. etc.; also, ultimately the developer has to be familiar with kubectl as use it.

I've noticed in slack folks are confused about how to go about creating an initial cluster after running tilt up: https://kubernetes.slack.com/archives/C8TSNPY4T/p1604048789172400

This is more of a convenience for 1) running envsubst + apply to deploy workload clusters 2) as jonathan mentioned being able to create multiple clusters with one "rerun" gesture, which is useful when developing and testing a particular template which requires changing the code and trying again (eg. trying to find a bug and just added a new log line which requires me to create another template). AFAIK `clusterctl config cluster` doesn't work with tilt because it's not setting up providers on the mgmt cluster the same way `clusterctl init` does.

We've gotten some really positive feedback about this in CAPZ, and it's always something I'm personally missing whenever I dev on CAPI/CAPD. 

> UX, given that we are representing templates with the same primitive used for controllers, which IMO is wrong. Have you considered https://docs.tilt.dev/buttons.html

I wasn't aware tilt buttons were a thing. We should look into using those as an alternative. It seems that buttons are only meant for one action though, do you know how that would fit into creating several different cluster templates? 

> portability across providers, given that there is not a convention across repositories defining if/how templates should exist in the code base; also as a developer, more than often I have my own well crafted templates that I want to use, and everyone uses its own preferred location for this

In CAPZ tilt just adds everything in your templates/ directory as a tilt local resource, so I can create my own templates locally for testing and they will automatically show up in the tilt UI. I find that super convenient for testing different variations at the same time. These templates don't have to be CAPD only, devs can add templates for any provider and use those as long as they were installed on the mgmt cluster.

**Comment by sbueringer** [comment]
> AFAIK clusterctl config cluster doesn't work with tilt because it's not setting up providers on the mgmt cluster the same way clusterctl init does.

I think it should work on our Tilt env. We are also deploying provider CRs and are also able to run e2e tests against a tilt-managed cluster.

> I wasn't aware tilt buttons were a thing. We should look into using those as an alternative. It seems that buttons are only meant for one action though, do you know how that would fit into creating several different cluster templates?

Actions have parameters, we could use a `text_input` parameter. Unfortunately there is no enum. 
But I think we can probably create one button per template via a for-loop in the Tiltfile.


P.S. Slightly related, at some point we should probably compare feature sets of our Tilt environments to learn from each other.

**Comment by Jont828** [comment]
Thanks for explaining @CecileRobertMichon. I looked into Tilt buttons and I believe they're supposed to be attached to a specific resource like this. In our use case we have a directory full of flavors and logs for the output of applying each flavor. It doesn't look like we could add that many buttons from a UI standpoint.

![image](https://user-images.githubusercontent.com/17480384/156438237-b0973a6d-2f06-494b-92d8-a567aa4914fe.png)

**Comment by fabriziopandini** [comment]
ok, I got the use case and I like the idea of having a folder where I can put my yaml and a simple way to apply them to the cluster.
WRT to button vs resources, I was proposing buttons because they allow input parameters, so we don't need many but only one as we already implemented in https://github.com/kubernetes-sigs/cluster-api/blob/eecabe4d838f812880b367903721dec287b61047/Tiltfile#L342-L344

But I don't have strong preferences and I'm also fine in experimenting in our Tiltfile

**Comment by Jont828** [comment]
Sounds good. If I'm understanding the buttons correctly, they're bound to a specific resource, so for example we could create a resource for a template and then have a button w/ a text input for adding parameters. Would we want to use the templates in this folder? https://github.com/kubernetes-sigs/cluster-api/tree/main/test/infrastructure/docker/templates

**Comment by sbueringer** [comment]
Buttons can be added either globally or on a resource. So we can have either just global buttons per template or we can e.g. associate them to the corresponding infra controller if we want to.

**Comment by Jont828** [comment]
@sbueringer I'm just a bit unsure about the buttons since if we have a lot of templates, we could run out of space. I'll open a PR to simulate what we have in CAPZ, and hopefully we can start from there.

**Comment by sbueringer** [comment]
> @sbueringer I'm just a bit unsure about the buttons since if we have a lot of templates, we could run out of space. I'll open a PR to simulate what we have in CAPZ, and hopefully we can start from there.

Sure, was just a suggestion for an alternative :)
