### ISSUE TITLE
[1.0]  Panic when adding topology to an unmanaged cluster

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#6222]
**What steps did you take and what happened:**
1) Create a cluster using cluster api version 1.0.4
2) Edit the cluster to add `spec.topology.class`
3) Apply the updated cluster

**What did you expect to happen:**
Cluster webhook to properly validate the change i.e. by not validating the new topology against the old topology.

- Cluster-api version: 1.0.4
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
/area topology

**Comment by fabriziopandini** [comment]
/milestone v1.0
This error happens in the 1.0 release only; cluster webhooks has been already improved in 1.1 and this operation is blocked/the panic cannot happen anymore

**Comment by sbueringer** [comment]
/close
as the PR has been merged
