### ISSUE TITLE
Deprecate and replace ClusterIPFamily String() method

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#6226]
ClusterIPFamily, in v1beta1 cluster_types.go, has a String function which returns on of the following:

- "InvalidIPFamily" 
- "IPv4IPFamily"
- "IPv6IPFamily"
- "DualStackIPFamily"

In #6171 it was decided that the suffix "IPFamily" was redundant in these types and could be better replaced with:
- "Invalid" 
- "IPv4"
- "IPv6"
- "DualStack"

In order to do so the current String method will have to be Deprecated and replaced. This is an interface method which could be used as a fmt.Stringer in certain places meaning we can't directly remove this method but have to replace it with a new implementation.

I think we can:
1) Deprecate the current method for release 1.2 warning that the value of the strings will change in a future release
2) After 1.3 releases change the value of the strings returned from this function.

Is this approach in line with the intended deprecation policies in [contributing.md](https://github.com/kubernetes-sigs/cluster-api/blob/main/CONTRIBUTING.md)?

/area api

**Comment by sbueringer** [comment]
> In order to do so the current String method will have to be Deprecated and replaced. This is an interface method which could be used as a fmt.Stringer in certain places meaning we can't directly remove this method but have to replace it with a new implementation.
> 
> I think we can:
> 
> 1. Deprecate the current method for release 1.2 warning that the value of the strings will change in a future release
> 2. After 1.3 releases change the value of the strings returned from this function.
> 
> Is this approach in line with the intended deprecation policies in [contributing.md](https://github.com/kubernetes-sigs/cluster-api/blob/main/CONTRIBUTING.md)?

I think it's not literally in line with the deprecation policy, but I think it's something we should make an exception for (guidelines never cover 100%). Especially given that there is no other way to change the behavior of the func **and** that this func is very rarely used (I'm only aware of CAPD).

So +1 from my side to deprecate now (in the v1.1->v1.2 doc) and change the behavior after the v1.2 release.

**Comment by fabriziopandini** [comment]
/milestone Next
Let's discuss the exception with the community
@enxebre @vincepri @CecileRobertMichon opinions?

**Comment by vincepri** [comment]
Is this actually worth an exception today? The strings definitely have some redundancy with the field, although it's not really breaking anything as far as I can tell. In terms of guidelines, it'd definitely be considered a breaking change. Apart from the face value of the change, is there anything worthwhile to warrant spend cycles for this?

**Comment by sbueringer** [comment]
Current state is that we exposed the IPFamily with `Invalid`, `IPv4` as builtin variable, and the `GetIPFamily` func returns similar values but with the IPFamily suffix.

I don't really think that it has a high priority to fix this, so I would be fine with just leaving it as is.

**Comment by killianmuldoon** [comment]
Absolutely fine with leaving this but I don't think it would need to be an exception if I'm understanding the deprecation policy right. We could:
1) Deprecate this method for a point release
2) Remove it after it's been deprecated for a point release
3) Add another String method that has the desired output

**Comment by sbueringer** [comment]
I think it's more about if it's worth the multi-release effort not necessarily that it's technically possible.

**Comment by fabriziopandini** [comment]
/close

this discussion is superseded by https://github.com/kubernetes-sigs/cluster-api/issues/7521 (move IP family to be a CAPD internal concern)
