### ISSUE TITLE
Rename 'replicas' to 'current' in KubeadmControlPlane, MachineDeployments and MachineSet kubectl output

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#6227]
Cluster API should use "current" instead of "replicas" in CLI output to express the number of instances of an object in a scalable resource.
With https://github.com/kubernetes-sigs/cluster-api/pull/6164 we're adding `desired` to all three of the above objects, showing the number of replicas. In order to be consistent with the Kubernetes output for Daemonsets we should rename the 'replicas' column to 'current'.

In detail:
As of release 1.1 the outputs for KubeadmControlPlane, MachineDeployments and MachineSets are :

KubeadmControlPlane
```
NAME             CLUSTER    INITIALIZED   API SERVER AVAILABLE   REPLICAS   READY   UPDATED   UNAVAILABLE   AGE   VERSION
cloister-9l2n7   cloister   true          true                   3          3       3         0             24h   v1.21.2
```
MachineDeployments:

```
NAME                           CLUSTER    REPLICAS   READY   UPDATED   UNAVAILABLE   PHASE     AGE   VERSION
cloister-linux-workers-jd4qq   cloister   3          3       3         0             Running   24h   v1.21.2
```

MachineSets:

```
NAME                                              CLUSTER      REPLICAS   READY   AVAILABLE   AGE   VERSION
my-cluster-default-worker-topo-bjn28-66767779f7   my-cluster   1                              21h   v1.22.0
```

In a future release  the outputs for KubeadmControlPlane, MachineDeployments and MachineSets this change (combined with the change from #6164) result in:

KubeadmControlPlane
```
NAME             CLUSTER    INITIALIZED   API SERVER AVAILABLE   CURRENT DESIRED   READY   UPDATED   UNAVAILABLE   AGE   VERSION
cloister-9l2n7   cloister   true          true                   3          3       3         0                   3        24h   v1.21.2
```
MachineDeployments:

```
NAME                           CLUSTER      CURRENT  DESIRED READY UPDATED   UNAVAILABLE   PHASE     AGE   VERSION
cloister-linux-workers-jd4qq   cloister     3       3           3     3     0          Running   24h   v1.21.2
```

MachineSets:

```
NAME                                              CLUSTER    CURRENT  DESIRED READY   AVAILABLE   AGE   VERSION
my-cluster-default-worker-topo-bjn28-66767779f7   my-cluster   1         1                         21h   v1.22.0
```

/area api

**Comment by enxebre** [comment]
+1 from me. See https://github.com/kubernetes-sigs/cluster-api/pull/5304#discussion_r715119225 for prior discussion.

Let's make sure any convention we come up with https://github.com/kubernetes-sigs/cluster-api/blob/main/CONTRIBUTING.md#crd-additionalprintercolumns

**Comment by fabriziopandini** [comment]
/milestone Next
Given this should be implemented when we rev the next API version

**Comment by sbueringer** [comment]
Q: If we want to change it with v1.3 should we add it **now** to our migration doc as deprecation? (I'm not sure where we should put that info)

**Comment by killianmuldoon** [comment]
>Q: If we want to change it with v1.3 should we add it now to our migration doc as deprecation? (I'm not sure where we should put that info)

Good idea. I think adding this to the migration doc should be enough of a warning to end-users. I think this is a pretty low impact change (Unless someone is using awk to manage clusters :smile: )

**Comment by sbueringer** [comment]
I would be fine with adding it there, given that we don't really have a better place imho (there is that one other page for clusterctl..)

**Comment by fabriziopandini** [comment]
Based on what we did in the past, breaking changes to columns have been implemented only when revving a new API version. I'm not sure we are going to rev a new API version in v1.3 and If this is not going to happen the deprecation notice will get lost ...

**Comment by Ab-hishek** [comment]
Hi @killianmuldoon! If possible, can I work on this whenever we decide to start working on this(i.e next release)?

**Comment by killianmuldoon** [comment]
@Ab-hishek Sure - we'll probably activate a bunch of these changes just before the next release cycle. I'll ping here when we decide to unblock this.

**Comment by fabriziopandini** [comment]
ACK, good to have an "official statement" about this

**Comment by sbueringer** [comment]
A solution to this is proposed in https://github.com/kubernetes-sigs/cluster-api/pull/10897

/close
