### ISSUE TITLE
Internal Error when creating k8s on Azure：failed calling webhook "default.cluster.cluster.x-k8s.io": Post "https://capi-webhook-service.capi-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-cluster?timeout=10s": dial tcp 10.0.83.153:443: connect: connection refused

### ISSUE THREAD

**Issue by Icybiubiubiu** [kubernetes-sigs/cluster-api#6229]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
kind：0.11.1
clusterctl:v1.1.1
env: GlobalAzure
k8s version:1.23.3

config.yaml:
clusterctl.exe generate cluster icy-capik8s --kubernetes-version v1.23.3 --control-plane-machine-count=3 --worker-machine-count=3 > icy-capik8s.yaml

Error:
![image](https://user-images.githubusercontent.com/61815812/156304567-7d12968a-5523-417e-a2f4-baf8a303dbc6.png)

**What did you expect to happen:**
a k8s cluster could be created successfully in my Azure subscription.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:v1.1.1
- Minikube/KIND version:0.11.1
- Kubernetes version: (use `kubectl version`):1.19.1
- OS (e.g. from `/etc/os-release`): gitbach on win11

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
Looks like there is something wrong with your CAPI controllers.

Either they are not up/ready or the kube-apiserver of your management cluster can't reach them / their webhooks.

**Comment by fabriziopandini** [comment]
/milestone v1.2
/priority awaiting-more-evidence

Given the attached info it is difficult to reproduce make a guess on why week hooks are not started.
Based on experience it is usually a networking problem given that week hook requires a fully working network setup and they usually are the first component to stress all the netwrok setup
