### ISSUE TITLE
Nightly image push jobs are failing

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6230]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

The nightly image push jobs are currently failing: https://testgrid.k8s.io/sig-cluster-lifecycle-image-pushes#cluster-api-push-images-nightly&show-stale-tests=

**What did you expect to happen:**
After a few recent PRs we are now building kustomize via go install (https://github.com/kubernetes-sigs/cluster-api/pull/5741 https://github.com/kubernetes-sigs/cluster-api/pull/6213). This seems to require some additional tools which are not installed in the image used in GCB (maybe CGO-related).

I think we should:
* [ ] take a closer look at the image we're using in GCB and probably try to add `gcc` there.
* [ ] we should go over all our ProwJobs and make sure that all relevant ones have alerting configured (the nightly push doesn't have it)

Links:
* ProwJob configs: https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/k8s-staging-cluster-api.yaml
* GCB build config: https://github.com/kubernetes-sigs/cluster-api/blob/128a8391c49e0fa2176861e020e4095c5a54a0a0/cloudbuild-nightly.yaml#L16
* Slack thread: https://kubernetes.slack.com/archives/C8TSNPY4T/p1646163639611619 (thx @sedefsavas for reporting)

**Anything else you would like to add:**
The post-submit jobs are still working, because they are only pushing images. As they don't build/push manifests they don't require kustomize (https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-api-push-images/1498778092926144512).

**To reproduce**:
```bash
$ docker run -it --entrypoint /bin/bash gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20211013-1be7868d8b
$  go install -tags tools sigs.k8s.io/kustomize/kustomize/v4@v4.5.2
...
# sigs.k8s.io/kustomize/kustomize/v4
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exec: "gcc": executable file not found in $PATH
```

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
/reopen

to confirm tomorrow if it works

**Comment by fabriziopandini** [comment]
@sbueringer I have re-triggered today's job and we are back to green

**Comment by sbueringer** [comment]
Perfect, thank you! 
Forgot we can do that :)
