### ISSUE TITLE
Ensure consistency across replica-based CLI printer columns

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#6238]
A couple of changes are being proposed to bring CLI printer columns related to replica columns in line with Kubernetes types.

Additional work needs to be done to bring the printer columns fully in line with Kubernetes. Note, the below changes can not be made until we are updating the Cluster API api version (currently at v1beta1).

Using the Kubernetes Daemonset as a model we have:
```
DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE
```

Replica related fields, and the source of their values, are listed below:
1. KubeadmControlPlane
       - Replicas => .status.replicas
      -  Ready => .status.readyReplicas
      -  Updated => .status.updatedReplicas
      -  Unavailable => .status.unavailableReplicas
1. MachineDeployments
      -  Replicas => .status.replicas
      -  Ready => .status.readyReplicas
      -  Updated => .status.updatedReplicas
      -  Unavailable => .status.unavailableReplicas
1. MachineSets
      -  Replicas => .status.replicas
      -  Ready => .status.readyReplicas
      -  Available => .status.availableReplicas
1. MachinePools
      -  Replicas => .status.replicas

The following are needed to bring each of these types in line
- [ ]  #6164 
- [ ]  #6227 
- [ ] Add "Available" and "Ready" to MachinePools
- [ ] Change "Unavailable" to "Available" in MachineDeployments and KubeadmControlPlane
- [ ] Change "Updated" to "Up-to-date" in MachineDeployments and KubeadmControlPlane
- [ ] Consider adding "Up-to_date" in MachineSets and MachinePools (This requires a more substantial change to the API)
- [ ] Reorder columns in all types so we have (DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE)

/area api

**Comment by fabriziopandini** [comment]
Still valid for the next iteration of our API version
/triage accepted
