### ISSUE TITLE
E2E framework should fail faster when terminal provisioning failures occur

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#6239]
There is currently no verification of progress when checking for all control plane machines to be available, all machine deployment machines to be available, scaling operations for KCP/MD, and rolling out updates for KCP/MD today, so if there is a terminal failure (failure message/reason set on an owned Machine), then ;you need to wait for the `wait-machine-upgrade`, `wait-control-plane`, and/or `wait-worker-nodes` timeout to trigger. It would be nice if there was also a separate timeout for progress to be made that would help these types of failures to cause the test to fail quicker and in an easier to debug way.

_Originally posted by @detiber in https://github.com/kubernetes-sigs/cluster-api/issues/6143#issuecomment-1041593793_

**Comment by fabriziopandini** [comment]
/milestone v1.2
/area testing

This is somehow related to the ongoing discussion about how to report terminal failures, e.g https://github.com/kubernetes-sigs/cluster-api/pull/6218

**Comment by killianmuldoon** [comment]
/reopen

I think this is still a nice to have if someone has time to take it on.

**Comment by sbueringer** [comment]
/remove-lifecycle rotten
(afaik it's otherwise just closed again when the job runs the next time)

**Comment by fabriziopandini** [comment]
(doing some cleanup on old issues without updates)
/close
unfortunately, no one is picking up the task. the thread will remain available for future reference
