### ISSUE TITLE
Further clean up Tiltfile and read remaining information directly in tilt-prepare

### ISSUE THREAD

**Issue by johannesfrey** [kubernetes-sigs/cluster-api#6246]
**User Story**

As a developer I would like to have a clean and easy way to use Tilt for local development.

**Detailed Description**

Based on https://github.com/kubernetes-sigs/cluster-api/pull/6214 (which passes the tilt-settings file to tilt-prepare) and a corresponding [comment](https://github.com/kubernetes-sigs/cluster-api/pull/6214#discussion_r817754888) we should further clean up the Tiltfile and read more information normally passed as flags directly within tilt-prepare.

Following flags should then be dropped and read accordingly from the tilt-settings file:
* allow-k8s-context (tilt-prepare) & allow_k8s_arg (Tiltfile)
* cert-manager (tilt-prepare) & cert_manager_arg (Tiltfile)
* kustomize-builds (tilt-prepare) & kustomize_build_arg (Tiltfile) 
* providers (tilt-prepare) & providers_arg (Tiltfile)
* tools (tilt-prepare) & tools_arg (Tiltfile)

/kind feature

**Comment by fabriziopandini** [comment]
@johannesfrey thanks for opening this issue!
/milestone v1.2
