### ISSUE TITLE
Perform manual adoption from an unmanaged cluster to a managed cluster with ClusterClass

### ISSUE THREAD

**Issue by weikaipan** [kubernetes-sigs/cluster-api#6251]
**User Story**

As a develop/operator I would like to perform manual adoption from an unmanaged cluster to a managed cluster with ClusterClass for my unmanaged clusters once I upgrade CAPI and use ClusterClass and managed topology as the first-class APIs.

**Detailed Description**

The ask is developers (`kubectl` for example) and controllers are able to update unmanaged cluster's `Cluster.spec.topology` with a `ClusterClass` for adopting this unmanaged cluster. Right now the procedure to perform manual adoption is not supported and blocked.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
/milestone v1.2

A little bit of context: 
The operation is currently blocked and not supported given that it is possible to ensure a "safe adoption" only under the assumption that the target ClusterClass fully reflects the current state of the Cluster, and that's a complex problem without a good solution yet given all the existing variant of Clusters; also, related, there is the idea to not encourage practices leading users to have one ClusterClass for each Cluster, which is an anti-pattern.

Said that I think the problem should be divided into two parts:
- Relax the webhook so people can experiment on adoption, but initially without any support/compatibility guarantees cross versions.
- If the results of the above experiments is a solution that can be applied in different contexts, well documented then we can start thinking to implement an E2E ensuring at least guarantees cross versions  given a set of assumption/limits/constraints 

I'm +1 to start with the first option to allow experimenting on adoption; this could be implemented by introducing an annotation that explicitly calls out the fact that there are no support guarantees at this stage.

**Comment by fabriziopandini** [comment]
/close 
https://github.com/kubernetes-sigs/cluster-api/pull/6292 just merged
