### ISSUE TITLE
add flags to `clusterctl upgrade apply` to wait for the upgrade to finish before exiting

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#6267]
**User Story**

A a user of `clusterctl` I would like the `clusterctl upgrade apply` command to wait for the new components to be available before the command exits. Similar to how `clusterctl init` enables this by using the `--wait-providers` and `--wait-provider-timeout` flags.
Adding flags with the same names ,`--wait-providers` and `--wait-provider-timeout`, should be fine.

**Detailed Description**

Currently after performing `clusterctl upgrade apply` the command exists immediately after the components of the new providers are installed. It would be nice to have the feature to wait for the new deployments installed using a `--wait-providers` flag (similar to init). This feature will also be useful in identifying if any of the new deployments are not spinning up as expected.

*Additional note: After this feature is implemented there we can probably refactor some our e2e tests to remove the wait logic and instead just call the upgrade command with the corresponding wait flags*

**Anything else you would like to add:**

We already have helper functions in place that are used as part of the `init` command that can be repurposed (with a little refactor) to work with the `upgrade apply` command as well.
https://github.com/kubernetes-sigs/cluster-api/blob/5026786ee809c5def466049f5befd2a786fbcefa/cmd/clusterctl/client/cluster/installer.go#L117-L129

Adding a similar wait logic after the for loop at end (after the deleting the webhook namespace section) when all the providers are updated might be a good place to start
https://github.com/kubernetes-sigs/cluster-api/blob/fa6bf66a0f12c57d3ebfb362fd634db6c62eabc6/cmd/clusterctl/client/cluster/upgrader.go#L383-L410

/kind feature

**Comment by mkumatag** [comment]
> @ykakarap @mkumatag Do you mind if I take this one?

not at all :)

**Comment by meghanajangi** [comment]
I haven't made any progress on this, so unassigning and opening it up for others.
/unassign
