### ISSUE TITLE
Support specifying container registry credentials in clusterctl config or as init command line flag

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes-sigs/cluster-api#6277]
**User Story**

As a user I would like to be able to install CAPI/CAPx components by specifying a imagePullSecret in the clusterctl config or via the CLI to support using a private registry for CAPI/CAPx images that requires authentication.

**Detailed Description**

The only way I've found thus far is to prestage the namespaces and a dockerconfigjson secret in a bootstrap cluster then patch each component service account with that secret as an image pull secret. This would be in support of air-gapped deployments.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by sbueringer** [comment]
An alternative to providing a configuration option for this might be to make clusterctl manifest templating pluggable: https://github.com/kubernetes-sigs/cluster-api/issues/3247
