### ISSUE TITLE
Use go-cmp instead of reflect.DeepEqual

### ISSUE THREAD

**Issue by shivi28** [kubernetes-sigs/cluster-api#6281]
**User Story**
In CAPA office hours, we have discussed whether we should use `go-cmp` or `reflect` library for comparison. After discussion we concluded that `go-cmp` is better than `reflect`, and have collected some reasons in [this](https://hackmd.io/-za1FEtzQzikzn4ZUZFFXw) doc as well.

_( Not sure if it's useful for CAPI, but thought to create an issue. Feel free to close if it doesn't make sense :P )_
/kind feature

**Comment by killianmuldoon** [comment]
@DiptoChakrabarty I think we shouldn't proceed with a PR on this right now - it's something we'd want to discuss before making changes to the code base I think.

**Comment by DiptoChakrabarty** [comment]
Okay sure I get it

**Comment by fabriziopandini** [comment]
/milestone v1.2
@shivi28 thanks for sharing your notes, really appreciated it.

I agree `go-cmp` has some features `reflect.DeepEqual` does not have, but IMO this alone is not a good reason to move away from the latter when those features are not required.

Let's hear other opinions as well, but unless there are stronger reasons (go-cmp significantly faster/using a fraction of the memory) I'm personally -1 to do the switch given that this could have unexpected side effects on things like how do we compute rollout strategies.

**Comment by shivi28** [comment]
Thanks everyone! Sure we can drop this, if there is any further point someone want's to add then please feel free to open this issue, till then I am closing this one.
Thanks again @fabriziopandini
