### ISSUE TITLE
Enforce good selectors on MachineDeployments

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#6283]
As documented in https://github.com/kubernetes-sigs/cluster-api/issues/5957 it is possible to configure MachineDeployment Selectors in Cluster API minimally e.g. using the cluster name only, so that they are created correctly but are not unique enough to ensure correct adoption, for example in the event of a backup and restore. The default selector, set when no selector is set on the MachineDeployment, contains both the Cluster name and the MachineDeployment name and is sufficient to ensure adoption occurs correctly.

This configuration can cause unexpected rollouts to occur when attempting to adopt a cluster by a restored management cluster. It can also cause Machines to be adopted by the wrong MachineSet, putting the cluster in a working but invalid state.

Right now the correct form of selector is opaque to users and it only causes an issue on Day N when MachineDeployment and MachineSet adoption unexpectedly shows errors.

To solve this we could (from strongest to weakest):
1) Add the default selectors to the MachineDeployment on creation, even if another selector is defined.
2) Block the creation of MachineDeployments with insufficiently specific selectors?
3) Create a webhook warning (requires https://github.com/kubernetes-sigs/controller-runtime/issues/1788) to advise users on creating MachineDeployments
4) Document the requirement for MachineDeployment selectors.

I'd prefer to got with the stronger version of this to preclude any future occurrence of this issue. I'm not sure if there's workflows that would be blocked by making strong assumptions about the MachineDeployment / MachineSet selector. 

Is there any reason we shouldn't default the selector to always include both the Cluster name and the MachineDeployment name?

**Comment by fabriziopandini** [comment]
/kind feature
/milestone v1.2

I think the current implementation derives from Kubernetes Deployments, and AFAIK also there it is up to the users to provide not overlapping selectors, but at the same time it allows the users to choose their own criteria for uniqueness.

I'm also worried by the effect of enforcing all the selectors on existing MD (it is probably a breaking change, and as far as I remember it will trigger rollouts on upgrade).

given that my first reaction is to go for option 3, but probably this requires some more thinking/different opinions

**Comment by fabriziopandini** [comment]
/triage accepted
/help
There is ongoing work in https://github.com/kubernetes-sigs/controller-runtime/pull/2014 to implement warning in controller runtime, this could potentially unblock this issue

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough contributors to adequately respond to all issues and PRs.

The idea of having a webhook providing a warning is still interesting, but it has a downside that we need to use an APi reader inside a webhook + no one is volounteering for this work/showing interest on the issue since a long time

/close
