### ISSUE TITLE
Single Node Kubernetes Cluster

### ISSUE THREAD

**Issue by debankur1** [kubernetes-sigs/cluster-api#6293]
Is it possible to create a Single Node Kubernetes Cluster, with Cluster API mostly for IoT and edge devices(VM and bare metal)?

**Comment by sbueringer** [comment]
You can create a cluster with a single control plane node, but when that node should be rolled out / upgraded we currently create a second node and then drop the old one.

Note: This behavior is specific to the KubeadmControlPlane control plane provider. Others might do this differently.

**Comment by debankur1** [comment]
> 

as an alternative can we directly use the kueadm cli to do the cluster creation?

**Comment by sbueringer** [comment]
I'm not sure if I understand the question. You can of course use kubeadm instead of ClusterAPI if you want to.

You can also create a cluster once with CAPI and then manually manage your cluster e.g. with kubeadm going forwards. Although If CAPI is still actively managing the cluster at this point I'm not sure what will happen (maybe it tries to rollback your manually upgraded cluster)

**Comment by enxebre** [comment]
@debankur1 as Stefan mentioned nothing prevents you from taking over and get into the cluster lifecycle and implement your in-place upgrade process after creation though your actions would be competing with capi desired state and so behaviour would be unexpected.
Kubeadm bootstrap/control-plane is a plugable component part of our reference implementation where we assume the control plane to be 1/3 Machines and workers to have their own Machines. I don't think we currently optimise for a single node scenario. We're having discussions about the best path forward to keep supporting managed kubernetes topologies e.g eks, so might be good to bring the single node scenario into the picture as well to brainstorm and identify patterns.

**Comment by debankur1** [comment]
> I'm not sure if I understand the question. You can of course use kubeadm instead of ClusterAPI if you want to.
> 
> You can also create a cluster once with CAPI and then manually manage your cluster e.g. with kubeadm going forward. Although If CAPI is still actively managing the cluster at this point I'm not sure what will happen (maybe it tries to rollback your manually upgraded cluster)

@sbueringer thanks for the suggestion , actually I don't want to use CAPI at all , want to manage the cluster lifecycle  with kubeadm only

**Comment by debankur1** [comment]
> @debankur1 as Stefan mentioned nothing prevents you from taking over and get into the cluster lifecycle and implement your in-place upgrade process after creation though your actions would be competing with capi desired state and so behaviour would be unexpected. Kubeadm bootstrap/control-plane is a plugable component part of our reference implementation where we test and assume the control plane to be 1/3 Machines and workers to have their own Machines. I don't think we currently optimise for a single node scenario. We're having discussions about the best path forward to keep supporting managed kubernetes topologies e.g eks, so might be good to bring the single node scenario into the picture as well to brainstorm and identify patterns for topologies beyond the reference impl.

So if I don't use Cluster API for this kind of scenario (Single Node Cluster), and only use kubeadm to manage the cluster, i believe then will no problem ?

**Comment by sbueringer** [comment]
You won't have a ClusterAPI-specific problem at least.

How to manage single node clusters with kubeadm without CAPI is probably out-of-scope of this repository.

I would advice to refer to the kubeadm documentation for that.

**Comment by fabriziopandini** [comment]
/close
given that the solution seems out of scope for CAPI
