### ISSUE TITLE
Add Codecov badge to CAPI repo

### ISSUE THREAD

**Issue by Ankitasw** [kubernetes-sigs/cluster-api#6297]
Codecov gives you a glance into the status of your project’s percentage of code coverage.

It would be good to see CAPI's code coverage on day-to-day basis since we have a good amount of unit tests coverage. Based on the results we may do some more improvements.
Also, keeping in mind that each new PR covers/tests the new code added.

Document to refer: https://docs.codecov.com/docs/quick-start

**Comment by sayantani11** [comment]
/assign
But @Ankitasw Can you explain a bit more about what do actually is desired?

**Comment by Ankitasw** [comment]
Hey @sayantani11, as you can see in our README.md that there are few badges listed there. We want to add a new badge to our repo which will tell the percentage of code coverage for overall code. Please check the link mentioned above. 
If you are still not clear, let me know, we can pair up sometime next week.

**Comment by sbueringer** [comment]
Hey folks,

let's please wait a bit and discuss it first. I'm not sure if we want it. While it is nice to see the code coverage, it might lead us to overly focus on getting to a certain percentage of test coverage vs. focusing on having the right test which cover the logic appropriately.

**Comment by fabriziopandini** [comment]
We already discussed a couple of similar issues in the past with the CAPI community(e.g. https://github.com/kubernetes-sigs/cluster-api/issues/3309, https://github.com/kubernetes-sigs/cluster-api/issues/3309) the conclusion was to not do this. 

Instead, we invested a lot in the E2E test framework, we improved out test guidelines and our review process to take the test into account, and we decided to go for more specific issues if there are features where we feel that we can benefit from additional tests.

Given that I'm personally -1 to re-open this discussion

**Comment by pydctw** [comment]
I am also personally -1 to add code coverage badge. I've seen many codebases with very high code coverage but poorly written tests. We need to strive for writing good tests to cover important use cases but code coverage percentage doesn't mean much imo.

**Comment by Ankitasw** [comment]
Thanks for the feedback everyone. If it's already discussed(which I missed) then let's close this discussion to avoid confusion.
