### ISSUE TITLE
CAPI should not use ObjectMeta.ClusterName

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6305]
There is an upstream discussion about dropping ObjectMeta.ClusterName: https://github.com/kubernetes/kubernetes/pull/108717

This field is not populated by Kubernetes and we should not use it as an CAPI Cluster Name.

This issue is about doing some research where we use it in core CAPI.

Providers are likely affected too: https://kubernetes.slack.com/archives/C8TSNPY4T/p1647448390328219

PR to fix it in core CAPI: https://github.com/kubernetes-sigs/cluster-api/pull/6306

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
Exactly. We usually have spec.clusterName in all our CRDs and any usage was accidental. 

As far as I can see we have only very very few usages and we have to fix them.
(I added some more details in the Slack thread for some other CAPI providers)

This should not in any way block the removal of the field from ObjectMeta.

**Comment by neolit123** [comment]
i was not aware that CAPI decided to use this legacy field.
probably happened in the early stages...

**Comment by sbueringer** [comment]
> i was not aware that CAPI decided to use this legacy field. probably happened in the early stages...

I don't think that was an explicit decision. We just missed a few times that we have to write `.Spec.ClusterName` and `.ClusterName` is from metadata because ObjectMeta is inlined.
