### ISSUE TITLE
generate provider command should not substitute variables when --describe is used

### ISSUE THREAD

**Issue by LucaLanziani** [kubernetes-sigs/cluster-api#6316]
**What steps did you take and what happened:**

Running the below command I got an error about variable substitution:

```bash
> clusterctl generate provider --infrastructure aws --describe
Error: failed to perform variable substitution: value for variables [AWS_B64ENCODED_CREDENTIALS] is not set. Please set the value using os environment variables or the clusterctl config file
```

**What did you expect to happen:**

Following the clusterctl [documentation](https://cluster-api.sigs.k8s.io/clusterctl/commands/init.html?highlight=--describe#how-can-i-known-which-variables-a-provider-requires) it looks like the command should skip the substitution and output the required variables:

```bash
> AWS_B64ENCODED_CREDENTIALS="This should not be needed" clusterctl generate provider --infrastructure aws --describe
Name:               aws
Type:               InfrastructureProvider
URL:                https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/
Version:            v1.3.0
File:               infrastructure-components.yaml
TargetNamespace:    capa-system
Variables:
  - AUTO_CONTROLLER_IDENTITY_CREATOR
  - AWS_B64ENCODED_CREDENTIALS
  - AWS_CONTROLLER_IAM_ROLE
  - CAPA_EKS
  - CAPA_EKS_ADD_ROLES
  - CAPA_EKS_IAM
  - CAPA_LOGLEVEL
  - EVENT_BRIDGE_INSTANCE_STATE
  - EXP_EKS_FARGATE
  - EXP_MACHINE_POOL
  - K8S_CP_LABEL
Images:
  - k8s.gcr.io/cluster-api-aws/cluster-api-aws-controller:v1.3.0

``` 

**Anything else you would like to add:**

I opened the issue in the `cluster-api-provider-aws` repo first.
It was triaged and I was asked to move it here, original issue: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3307

I would be more than happy to open a PR myself if we think this is worth solving.

**Environment:**

- Cluster-api-provider-aws version: v1.3.0
- Kubernetes version: (use `kubectl version`): None 
- OS (e.g. from `/etc/os-release`):  Archlinux

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by LucaLanziani** [comment]
I was reading the code and I might be wrong but the issue might be [here](https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/cmd/generate_provider.go#L107)

Shouldn't this be something like `raw or textOutput`?

**Comment by fabriziopandini** [comment]
@ykakarap PTAL 
/milestone v1.2
/area clusterctl

**Comment by ykakarap** [comment]
Just back from PTO. I will take a look at this this week.

**Comment by LucaLanziani** [comment]
Thanks @ykakarap, let me know if it makes sense to you and I'll be more than happy to open a PR ;)

**Comment by ykakarap** [comment]
@LucaLanziani Thanks for finding the issue. Your suggested fix should work. If you are willing to open the PR please go ahead 🚀 👍🏼

**Comment by LucaLanziani** [comment]
I suppose this needs an approval first.

**Comment by LucaLanziani** [comment]
I would love to write a test for this, can someone point me to the file where the test should be? Even better if there is already a test for a similar functionality that I can use as a reference :smile:

**Comment by ykakarap** [comment]
I believe the fix will be in  runGenerateProviderComponents . ATM there are not tests at that level of the client code. It is right where the cobra flags are compiled and the underlying library functions are called. For the purposes of this fix it might be fine to just include the fix for now.
