### ISSUE TITLE
[e2e framework] node-drain timeout test can fail because of dockerhub pull limits

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#6327]
**User Story**

As a provider implementation developer, I would like to be able to run the e2e tests without worrying about potentially hitting dockerhub pull limits.

**Detailed Description**

Currently when running the `NodeDrainTimeoutSpec` e2e test, if running on a host that has exceeded unauthenticated dockerhub pull limits, the test will fail. This can be somewhat common when re-using IPs in a cloud environment.

It would be great to be able to override the configuration for the default image in both `NodeDrainTimeoutSpecInput` and in the related call to `framework.DeployUnevictablePod()` to be able to override the default image used (`nginx:1.12`), which is hardcoded here: https://github.com/kubernetes-sigs/cluster-api/blob/89a1613756381e15568a8a9157a7ea20c7561738/test/framework/deployment_helpers.go#L330

**Anything else you would like to add:**

Possible alternative implementations:
- Allow overriding just the container image used (would require that image meet the same port configuration as the currently used nginx container)
- Allow overriding the container configuration used
- Change the hard coded container image to one that should not be susceptible to pull limits, such as the pause image that is hosted by k8s on gcr.io (and possibly already present on the machines).

If folks have an opinion on preferred approach, I can throw together a PR to address it.

/kind feature

**Comment by sbueringer** [comment]
I assume that we don't really depend on that we specifically use nginx. I didn't find anything that specifically tests the http endpoint for example.

I would prefer:
* Change the hard coded container image to the pause image
    * it has to be pulled anyway for each Pod
    * let's use the one that is "currently" used per default (not sure how that's determined)
    * I think it's fine if that diverges over time or depending on the Kubernetes version
* Additionally we can make the image overridable too if you want. I think it's useful in any case as it allows usage of private registries in e.g. airgapped environments

**Comment by detiber** [comment]
> I think an env var is easier to change for the second case because the test code doesn't have to be changed.

I think in a lot of cases the use of env vars is more confusing than explicit parameters, and if a provider wants to expose it as an env var, then it's easier to map that into an explicit parameter than it is to override an env parameter explicitly in the code.

**Comment by sbueringer** [comment]
I was thinking that maybe the use case is not necessarily that entire providers would overwrite but that folks who are testing regular providers in downstream airgapped environment might want to have an easy way to overwrite it without having to change code (in every provider). 

We already have the e2e conf which can be overridden via env variables for that use case (IIRC).

But no strong opinions either way, let's see what @fabriziopandini thinks.

**Comment by detiber** [comment]
More than happy to try and plumb it both ways if desired as well

**Comment by fabriziopandini** [comment]
+1 to switch to pause + add an image variable in spec.input.
if people want to plug env var on top of the spec.input we can add it later (or consumers can add it easily on their side), but I prefer to not introduce an implicit contract (the ENV variable name) unless there is a demand for it

**Comment by sbueringer** [comment]
Fine for me!

**Comment by fabriziopandini** [comment]
(doing some cleanup on old issues without updates)
/close
