### ISSUE TITLE
[e2e framework] Refactor the e2e test framework to enable providers to perform granular tests

### ISSUE THREAD

**Issue by aartij17** [kubernetes-sigs/cluster-api#6345]
After fixing a bug in CAPV, we wanted to verify it using e2e upgrade tests as well. 

Some context on the bug: 
A particular secret wasn't being deleted by the controllers cause it missed removing one of the finalizers. This led to the workload cluster not being deleted. 

In order to test this using the clusterctl upgrade e2e tests(`ClusterctlUpgradeSpec`), it would help if the cleanup(which is gated by the `skipCleanup` flag) could be extended as a function that the providers can invoke. This could possibly mean the following - 
1. Expose the workload cluster name and client/kubeconfig so that its resources can be accessed (for example this instance where we needed to `get` the secret)

2. Allow step-wise deletion in the cleanup. Separate functions for deletion of management cluster, workload cluster, namespace. This would help greatly when the providers want to tests a specific behavior _in between_ these stages

I hope this makes sense, I would be happy to provide more context if it doesn't :)

**Comment by fabriziopandini** [comment]
/kind feature
/area testing
/milestone v1.2

Thanks @aartij17 for reporting
This is an interesting use case. It needs some thinking given that we can apply this to all tests, but definitely worth of some additional investigations

**Comment by fabriziopandini** [comment]
/triage accepted

We are slowly adding the capability to inject func in test spec, this could follow the same pattern
/help-wanted
