### ISSUE TITLE
gci linter no longer autofixing import orders

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#6350]
gci linter is no longer fixing import order with `make lint-fix`. This issue was noted in #6348. The errors from the linter are opaque making fixing import order a manual and time consuming process for maintainers - and very discouraging for all contributors.

It seems from here that the autofix was disabled in a recent version c/f https://github.com/golangci/golangci-lint/issues/2604. I'm still researching why this occurred and will update with any information here.

We can either 
- remove `gci` from our golangci-lint. 
- or  downgrade to an older version, i.e. roll back #6335 

Until the linter's behaviour in autofixing comes back in line with expectations. I'm in favour of doing a downgrade - gci was really useful when `make lint-fix` was working.

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
Hm, could it be an alternative to call gci directly as part of lint-fix? I think they did something similar here: https://github.com/vmware-tanzu/cartographer/pull/691/files

(although I would still run gci via golangci-lint)

I think we need this only until the fixed it in golangci-lint/gci.

**Comment by vincepri** [comment]
Are folks maintaining golanci-lint aware of this issue?

**Comment by killianmuldoon** [comment]
There's an issue at https://github.com/golangci/golangci-lint/issues/2604
And a PR with a fix at https://github.com/golangci/golangci-lint/pull/2653

**Comment by sbueringer** [comment]
I think we have a few options:
1. just wait until the fix is merged in golangci-lint and then upgrade (i.e. ignore the issue until then)
2. downgrade now and then upgrade again once it's fixed (we can't upgrade golangci-lint until then)
3. provide a way to run gci "fix" via make (e.g. as part of lint-fix)

Not sure what the best way forward is, given that we don't know how soon they'll fix it. Maybe 2 for now and 3 if they don't fix it soon?

**Comment by sbueringer** [comment]
Okay PR is merged, so we picked 2. Let's see what happens upstream in golangci-lint

**Comment by killianmuldoon** [comment]
https://github.com/golangci/golangci-lint/pull/2892

This PR fixes the issue in golangci-lint. We should try to bump the version as soon as there's a new release.

**Comment by chrischdi** [comment]
Just because I did a lookup already the second time:

> Hello, there are some minor features that have been merged, so we will not create a patch release. [[0](https://github.com/golangci/golangci-lint/pull/2892#issuecomment-1161980612)]

So we have to wait for a `v1.47` [release](https://github.com/golangci/golangci-lint/releases).

**Comment by schrej** [comment]
Yep. We've also asked for a release. One of the maintainers wants to get a few more fixes in before a release, but it seems like they can't find time to implement them unfortunately. See [here](https://github.com/golangci/golangci-lint/pull/2892#issuecomment-1161980612)

**Comment by sbueringer** [comment]
@schrej Your IPAM PR depends on Go 1.18 right? (i.e. using `go 1.18` in go.mod files)

**Comment by schrej** [comment]
> @schrej Your IPAM PR depends on Go 1.18 right? (i.e. using `go 1.18` in go.mod files)

Yes. I'm using the shiny new `net/netip` package in the validation webhooks. I could also change it to https://pkg.go.dev/inet.af/netaddr, from which that std lib package has been derived and swap it out once we're on 1.18.

**Comment by killianmuldoon** [comment]
We could temporarily disable gci on the CI instead of refactoring that PR, assuming a release with the fix is inbound but just won't make it for 1.2.

**Comment by schrej** [comment]
If we can get the IPAM PR into 1.2 that way, I can switch it to netaddr, and then switch back after the bump. Having it in a release makes it easier to consume for provider implementations I think.

**Comment by sbueringer** [comment]
Just to confirm. This package is only used in the validating webhook and not as part of the API types? (so this change wouldn't be a breaking change to the API types)

**Comment by daixiang0** [comment]
Sorry for this, https://github.com/golangci/golangci-lint/pull/2892 has fixed it, let's wait for the next patch release.

**Comment by daixiang0** [comment]
New release has come, please try :)

**Comment by chrischdi** [comment]
It's currently getting tracked via https://github.com/kubernetes-sigs/cluster-api/pull/6737 , the recent golangci lint disabled some linters in revive due to performance issues.

**Comment by killianmuldoon** [comment]
I think we should close this in favor of #6737.  This no longer represents the issue with golangci-lint as of version 1.47.

This is also being tracked broadly as a part of #release task https://github.com/kubernetes-sigs/cluster-api/issues/5968

/close

**Comment by sbueringer** [comment]
Fine for me to close this, but just to mention it. I think usually we shouldn't close issues in favor of PRs. But I guess good for now as we still have #5968.
