### ISSUE TITLE
How can I recover the "Failed" phase of the cluster and machine objects?

### ISSUE THREAD

**Issue by moonek** [kubernetes-sigs/cluster-api#6366]
If `failureMessage` or `failureReason` is set in infrastructureRef , the ownerRef(i.g cluster, machine) is also set.
Conversely, if `failureMessage` or `failureReason` in infrastructureRef is changed to unset , it will not be unset in ownerRef.

Is the `Failed` phase intended to be a permanent setup?
Or do I have to unset the ownerRef directly on the infrastructureRef controller side?

**Comment by fabriziopandini** [comment]
/kind support
/close

According to the API FailureMessage/Reason should be set only in the event that there is a terminal problem, so there is no supported recovery path from it.
Feel free to re-open if more clarification are required.
