### ISSUE TITLE
RFE: Runtime Hooks for Add-on Management

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#6374]
Cluster API is currently unable to enable comprehensive add-on management because of the inability to interact with the lifecycle of a Cluster.  This issue proposes a number of RuntimeHooks, based on the [Runtime SDK](#6181), which will enable external management of add-ons based on transitions in the Cluster lifecycle.

[The full proposal is available at this link.](https://docs.google.com/document/d/1vMwzGBi6XbIwKzP5aA7Mj9UdhAWKYqI-QmdDtcxWnA4/edit#heading=h.npakzm9citnx)

This proposal is related to [recent conversations about add-ons](https://github.com/kubernetes-sigs/cluster-api/issues/5491) and leverages features developed as part of the [Cluster Topology proposal](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20210526-cluster-class-and-managed-topologies.md) , and will be based on implementation of the Runtime SDK #6181.

/kind feature
/area runtime-sdk
/kind proposal

**Comment by fabriziopandini** [comment]
Yay!
/milestone v1.2
