### ISSUE TITLE
Expose cluster and machine events in clusterctl

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#638]
/kind feature

**Describe the solution you'd like**
A good way to improve UX in case of errors is to use events to outline errors or progress and inform the user while waiting for clusterctl. Ideally, clusterctl would register with the bootstrap cluster first and watch events on a given label or field and print information back to the user around progress or failures.

**Anything else you would like to add:**
This is related to #634.

**Comment by timothysc** [comment]
Given some of the ways I would like to change clustectl I'm going to close this specific issue. 

More generally surfacing insights/state+status will be a high priority.
