### ISSUE TITLE
Allow to skip version check for Airgapped environments

### ISSUE THREAD

**Issue by sathieu** [kubernetes-sigs/cluster-api#6381]
**User Story**

As a operator I would like to be able to run ` clusterctl` on airgapped environnement without getting a timeout.

**Detailed Description**

Version check is run after every command:

https://github.com/kubernetes-sigs/cluster-api/blob/bf89e4ba8af1bb05ddb8902bb048938d789d0dac/cmd/clusterctl/cmd/root.go#L63-L73

https://github.com/kubernetes-sigs/cluster-api/blob/bf89e4ba8af1bb05ddb8902bb048938d789d0dac/cmd/clusterctl/cmd/version_checker.go#L86-L92

On our setup, this leads to a 30 seconds delay because of timeout, and a warning message.

**Anything else you would like to add:**

I can propose a PR, but how to implement this?

- an environment variable?
- when `~/.cluster-api/version.yaml` is symliked to `/dev/null`?
- as a CLI flag?

/kind feature

**Comment by fabriziopandini** [comment]
/area clusterctl
/milestone v1.2
@ykakarap if we can help @sathieu to move this forward this could be a nice addition (--skip-version-check)

**Comment by sathieu** [comment]
@fabriziopandini  @ykakarap I went for the symlink way in #6382 (using a flag for each command is not very friendly). Please review :pray: !

**Comment by sbueringer** [comment]
I would prefer implementing this in a way similar to how other binaries are handling it. 

IIRC either a flag or an env var usually. Symlinking the version file to /dev/null is in my opinion not user-friendly and we expose a detail that users usually don't have to care about. We would also have to make sure this works on all supported operating systems (this includes Windows)

**Comment by sathieu** [comment]
@sbueringer OK, but using a flag or env var will lead to timeout again when forgotten. 

What about adding this in the configuration file?

```shell
$ cat ~/.cluster-api/clusterctl.yaml
disable-versioncheck: true
```

Or in the `version.yaml` file? (NB: I can already workaround this by using a date in the future for LastCheck).

**Comment by sbueringer** [comment]
I'll leave it to Yuvaraj has he is more familiar with clusterctl. But I'm not opposed to making it possible to persistently configure this, that makes sense.

**Comment by ykakarap** [comment]
Going with the approach of adding a key in the configuration file sounds good 👍🏼 
This also comes with an added benefit of automatically supporting the environment variable `DISABLE_VERSIONCHECK`.
