### ISSUE TITLE
Utils UnmarshalClusterStatus is too lenient with inputs

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#6391]
This issue was reported from the oss-fuzz project for Cluster API. [Link](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46455#c2) (access is restricted). The issue reported is a timeout from a test case taking too long to complete.

UnmarshalClusterStatus can take a very long time. In the oss fuzz test case it took over four seconds to return an error on my machine. ClusterFuzz tries to run each test case 100 times.

 pprof reports the test gets stuck in a recursive call in fmt.printValue which is part of the attempt to Decode the string input to the method.

Right now we're not doing any upfront validation on this function and so we pass a completely unvalidated string yaml into the decoder.  I've prototyped a fix to this by using yaml.Unmarshal from the yaml.v2 library, but there may be more efficient ways to do it. Valdiating whether or not the input string is valid yaml sovles the timeout failure.

We could pre-emt this issue by doing an upfront check on the string e.g. to check that it is valid yaml. I think there's value in this as we're exposing this as a util - but I'd be interested in hearing others opinions.

/kind bug

**Comment by sbueringer** [comment]
To be honest, I would prefer not investing effort in this.

I assume we're talking about this func? https://github.com/kubernetes-sigs/cluster-api/blob/5026786ee809c5def466049f5befd2a786fbcefa/bootstrap/kubeadm/types/utils.go#L175-L181

It is used to unmarshal a type which has been deprecated and already removed in upstream v1beta3 kubeadm APIs. So it's only a matter of time until it's gone. I also don't think that we have problems with it in practice today.

**Comment by killianmuldoon** [comment]
@sbueringer that's a fair assessment. What does our support horizon look like for v1beta2 kubeadm APIs?

**Comment by sbueringer** [comment]
We started using v1beta3 for Kubernetes >v1.22 clusters. So basically we can drop them once we don't support v1.21 clusters anymore. I have no idea when that is.

**Comment by killianmuldoon** [comment]
/close

This is a wontfix in it's current state. The solution to this is to remove these types once we drop support for v1.21, when will happen isn't determined, but it doesn't need to be tracked as an issue with UnmarshalClusterStatus.
