### ISSUE TITLE
[Question] Does clusterctl move command not move infrastructure resources to target cluster ?

### ISSUE THREAD

**Issue by Bo0km4n** [kubernetes-sigs/cluster-api#6394]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
I tried below command to move cluster resources to target.
```
clusterctl move --to-kubeconfig ./move/admin.conf --namespace=default
```

**What did you expect to happen:**
I expected that infrastructure resources moved to target cluster, but it seems like move command didn't support.
Actually, `kubectl get osm, osc, osmt` showed nothing in log.

Is this intended specification ?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
/remove-kind bug
/kind support
/milestone v1.2

clusterctl move takes care or providers resources under conditions described in https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#move

**Comment by Bo0km4n** [comment]
@fabriziopandini Thanks for your comment and reference!
In short, to move the provider's resource, should I add label 'clusterctl.cluster.x-k8s.io/move' or 'clusterctl.cluster.x-k8s.io/move-hierarchy' to CRD or each resources?

**Comment by fabriziopandini** [comment]
If the CRD is installed by `clusterctl init` this should not be necessary because provider resources are directly or indirectly linked to a Cluster object (linked through the OwnerReference chain). `clusterctl.cluster.x-k8s.io/move' or 'clusterctl.cluster.x-k8s.io/move-hierarchy'  are only for objects which do not belong to a Cluster through the OwnerReference chain

**Comment by Bo0km4n** [comment]
I installed CRD and controllers without `clusterctl init`, from plain yaml files.
In this case, should I add manually `clusterctl.cluster.x-k8s.io/move  ` label to CRDs ?

And I want to ask you more one question.
What the difference of `clusterctl.cluster.x-k8s.io/move` with `clusterctl.cluster.x-k8s.io/move-hierarchy`

**Comment by Bo0km4n** [comment]
I resolved above questions.
I added the label `clusterctl.cluster.x-k8s.io: ""` to provider's CRDs and create `Provider` resource of infrastructure.
Then, `clusterctl move` command moved infrastructure provider's resources to target cluster, thanks for your helps.

**Comment by killianmuldoon** [comment]
@Bo0km4n Are you happy to close this issue?

**Comment by fabriziopandini** [comment]
> I installed CRD and controllers without clusterctl init, from plain yaml files.

Happy you solved this issue, but worth noticing that this is a scenario not officially supported, so there are no tests/guarantees this will work in future.

/close
