### ISSUE TITLE
Util Conditions patcher returns nil pointer error

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#6400]
This issue was uncovered by the oss-fuzz project. The relevant issue (restricted access) is at https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45211#c3.

Both NewPatch and patch.Apply in util/conditions/patch.go take parameters that could be nil but nil checking is not done inside these functions. 

As these are exported utils I think we should ensure they don't panic when avoidable as discussed in #6334 

/kind bug

**Comment by fabriziopandini** [comment]
+1
/milestone v1.2
