### ISSUE TITLE
Proactively monitor of etcd data inconsistency, provide warning conditions when there are large deltas

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#6402]
**User Story**

As an operator, I'm aware of a major etcd data consistency issue ( https://github.com/etcd-io/etcd/issues/13766 ) in the 3.5 series, and I would like to know if my cluster is affected.

**Detailed Description**

One of the symptoms of this issue is essentially a semi-split brain scenario where the etcd dbs become inconsistent *but* continue replicating with different data.

This could be detected in the following conditions:

etcd endpoint status provides information about the revisions and dbSize. If the control plane members have been online for a while, then dbSize and revisions should be the same or very close. In RH documentation, if the values are differing by more than 10% for at least 10 minutes, then there is an indication that there is a problem. KCP could potentially expose this as a condition of type warning.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by sbueringer** [comment]
Q: Does etcd have metrics for this so it's alternatively possible to build alerts on top of etcd metrics?
