### ISSUE TITLE
Adopt KIND as cluster bootstrapper

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#641]
/kind feature

**Describe the solution you'd like**
In the AWS provider, we've been using [kind](https://github.com/kubernetes-sigs/kind) to spin up ephemeral bootstrap clusters for clusterctl. It would be nice to replace `minikube` with `kind` and improve the developer experience. After chatting with @BenTheElder at KubeCon, seems there are ways to use it as a library.

**Comment by dims** [comment]
👍

**Comment by alejandrox1** [comment]
@vincepri could I help out with this?

**Comment by vincepri** [comment]
Sure, check with @detiber, I remember he expressed interest in working on it.

**Comment by detiber** [comment]
My initial thoughts were to introduce kind as an alternate bootstrapper alongside minikube rather than simply swap it out for the time being to avoid being too disruptive of a change to users.
