### ISSUE TITLE
Avoid refreshing BootstrapTokens forever unless necessary

### ISSUE THREAD

**Issue by lentzi90** [kubernetes-sigs/cluster-api#6410]
**User Story**

As an operator I would like to prevent constantly refreshing BootstrapTokens when there is no need for it to keep the attack surface minimal.

**Detailed Description**

Currently the BootstrapTokens are refreshed for Machines until the infrastructure is ready. After #6395 this could change to "until the Node has joined". For MachinePools, the tokens are always kept fresh so that new Machines can be added at any point.

A cut-off point was suggested for Machines, so that the token would not be refreshed indefinitely if there is some problem with the underlying provider, configuration or other. It is unclear if something similar would be possible for MachinePools. Perhaps refreshing the token when the pool is scaled?

**Anything else you would like to add:**

This suggestion came up in the discussion around https://github.com/kubernetes-sigs/cluster-api/pull/6395.
I added this issue to keep track of the discussion around it and check if there is interest for it.

/kind feature

**Comment by fabriziopandini** [comment]
/priority awaiting-more-evidence

> For MachinePools, the tokens are always kept fresh so that new Machines can be added at any point.

For Machine Pool the token gets already rotated periodically (that means that there is always one token around, but not always the same).
