### ISSUE TITLE
What is the meeting password for Wednesdays zoom meeting?

### ISSUE THREAD

**Issue by butterfly1924** [kubernetes-sigs/cluster-api#6423]
Weekly on Wednesdays @ 10:00 PT on [Zoom](https://zoom.us/j/861487554)

**Comment by vincepri** [comment]
@butterfly1924 Please join the https://groups.google.com/g/kubernetes-sig-cluster-lifecycle google group and you'll be receiving a calendar invite with the full link.

/close
