### ISSUE TITLE
Core DNS Upgrades with Cluster API

### ISSUE THREAD

**Issue by cprivitere** [kubernetes-sigs/cluster-api#6429]
This was discussed at the 3/16 cluster-api meeting and I was asked to open an issue to foster discussion on this topic.

- Currently, kcp does not upgrade coreDNS unless you explicitly pass it a version to upgrade to.
- Should this be changed? It’s very much unexpected for users. For example users using kubeadm upgrade would not see this as kubeadm would upgrade it for them.
- Currently, there is no documentation on a minimum or target version of CoreDNS to have for a particular version of K8S, only a MAXIMUM version. So even if providers wanted to manually handle this somehow, they don’t have guidance on what to enforce.
- Should management of CoreDNS be explicitly added to the provider contract?

**Comment by fabriziopandini** [comment]
/milestone v1.2

Some comments to help to start the discussion
- I'm not aware of the reason behind current approach in KCP (the proposal just suggest user to change the version); however making CoreDNS upgrade automatic is a change of behavior we should properly document and advertise, and ideally it should be deployed when bumping an API version(under which conditions it happens etc. etc.)
- Documenting which version of CoreDNS should be used for each Kubernetes version (including the minimum version required) should be a responsibility of the CoreDNS project, we can eventually link to such documentation.
- AFAIK kubeadm has a notion of CoreDNS version tested with each Kubernetes version, which I expect to match with the above documentation. Not 100% sure what we should use as a source of truth between the two docs.
-  We are currently documenting the maximum supported Kubernetes version in KCP, given the dependency on the CoreDNS migration library, but this is not really related to the Kubernetes version in the Cluster

**Comment by kfox1111** [comment]
This issue and https://github.com/kubernetes/kubeadm/issues/2318 are related I think. Might be good to widen the conversation.

**Comment by neolit123** [comment]
I guess one way for kubeadm users to find what version of corends will be
deployed for a k8s version is to use 'kubeadm confug images list' command.
It will give them the corends image version which is the same as the
corends version.

**Comment by sbueringer** [comment]
I think we should use Kubernetes as source of truth. IIRC there is a bunch of testing done in k/k when they upgrade to a new (of course already released) CoreDNS version.

E.g. here we found a bug in CoreDNS v1.8.3 which resulted in v1.8.4 being used instead: https://github.com/kubernetes/kubernetes/issues/99751

**Comment by fabriziopandini** [comment]
/lifecycle frozen
/area controlplane
/area bootstrap
/triage accepted

if we can figure out a nice and clean transition from current to the new behaviour this could be a nice UX improvement at the cost of maintaining a version map between Kubernetes version and CoreDns version.
It probably qualifiies as API change given we are changing behaviour when fields are not explicitly set
/kind api-change
/help

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

This issue is not updated since 2022, and I'm not aware of folks still interested around this topic/volunteering to do the design + implementation work

**Comment by pierreozoux** [comment]
Hi,

I'm a cluster-api user, and it seems that CoreDNS was installed by CAPI, but it is not updated by CAPI.
So it is surprising as a user.

Reading the doc, I didn't find information about it.

@cprivitere you say:
```
Currently, kcp does not upgrade coreDNS unless you explicitly pass it a version to upgrade to.
```

How can I explicitly pass it a version?

What is the best way to do it?

Should I open a new issue?

Thanks for your help!

**Comment by pierreozoux** [comment]
Answering my own question:

```
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      dns:
        imageTag: "1.12.3"
        imageRepository: "docker.io/coredns"
```

This works great!
