### ISSUE TITLE
book: Only the first 10 tabs show content

### ISSUE THREAD

**Issue by apricote** [kubernetes-sigs/cluster-api#6434]
**What steps did you take and what happened:**

- [Go to https://cluster-api.sigs.k8s.io/user/quick-start.html](https://cluster-api.sigs.k8s.io/user/quick-start.html#initialization-for-common-providers)
- Click on any tab _after_ Nutanix (the 10th)
- Observe that no box shows, even though they have content defined

**What did you expect to happen:**

I expected every tabbed content to show.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

It looks like the CSS is hardcoded for 10 tabs: https://github.com/kubernetes-sigs/cluster-api/blob/69731edd7e4e6b778fb9f742c79b5dd54d386121/docs/book/theme/css/custom.css#L390-L401

A quick fix would be to duplicate the existing CSS rules and update the numbers.

**Environment:**

- Happens on `cluster-api.sigs.k8s.io` as well as `main.cluster-api.sigs.k8s.io`

/kind bug
/area ux
 
(there is no "docs" or "book" area, and this impacts UX because the setup init docs for the later providers are hidden)

**Comment by schrej** [comment]
There is a kind for it
/kind documentation
