### ISSUE TITLE
Makefile consilidation to improve maintenance and developer experience

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/cluster-api#6445]
**User Story**

As a maintainer I would like to have as less Makefiles as possible for reducing the effort of syncing changes in-between different Makefiles.

As a developer I would like to use `make help` for getting an overview about all make targets.

**Detailed Description**

The file [test/infrastructure/docker/Makefile](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/infrastructure/docker/Makefile) contains lots of duplicate target entries which are equivalent or similar to the ones in [Makefile](https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile).
Lot's of PRs require equivalent changes for `Makefile` and `test/infrastructure/docker/Makefile`:
- #5633
- #5741
- #5547

Some changes may not get replicated to the nested Makefile
- split of generate targets in #5248

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by sbueringer** [comment]
Absolutely +1 from my side :)

**Comment by fabriziopandini** [comment]
/assign @chrischdi 
given that there is already a PR for this
