### ISSUE TITLE
ClusterClass make MachineDeployment NodeDeletionTimeout configurable via Cluster topology

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6450]
**User Story**

As a user I would like to configure the NodeDeletionTimeout of a MachineDeployment.

**Details**

Prior art for this is the addition of nodeDrainTimeout in #6278.

PR: https://github.com/kubernetes-sigs/cluster-api/pull/6379
Detailed description on what to do: https://github.com/kubernetes-sigs/cluster-api/issues/6278#issuecomment-1070914169 (of course only the NodeDeletionTimeout parts are relevant)

/kind feature
/area topology

**Comment by 24sama** [comment]
Is there any progress on this issue? I think I can fix it.

**Comment by sbueringer** [comment]
@palnabarun Do you have time to work on this?

**Comment by abhijit-dev82** [comment]
@sbueringer I can start working on this. Is that ok?

**Comment by killianmuldoon** [comment]
@abhijit-dev82 let's wait until the person already assigned to it responds. @palnabarun have you been able to make any progress so far, or are you happy to hand this off?

**Comment by fabriziopandini** [comment]
/unassign @palnabarun 
@abhijit-dev82 feel free to start working on this issue

**Comment by killianmuldoon** [comment]
@abhijit-dev82 Just to check in - are you still interested in working on this issue?

**Comment by abhijit-dev82** [comment]
@killianmuldoon Yes, got busy with some other work, will get some diffs out soon.
