### ISSUE TITLE
Improve documentation on adding new API fields with conversion code and tests

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api#6464]
**User Story**

As a CAPI developer I would like to know exactly what are the steps required to add new API fields to CAPI types, including required conversion code to limit time spent making unit tests to pass.

**Detailed Description**

It seems many people struggle with making fuzzing conversion unit tests to pass after they modify the API fields, as even after modifying the types and running code generation tool, there are still manual steps required to get it to work. It would be great if we could have a robust documentation on how the process looks like to save everyone's time.

Steps I figured which perhaps could be used as a base:

#

If adding new API field only to the latest API version type, you must:

- Modify types as needed in latest API version (or actually, in hub version).

- Run code generation make target to generate new code for newly added types.

- Manually implement conversion function for modified type to acknowledge potential data loss.

  For example, by adding code as in example below to `api/<api version>/conversions.go` or
  `api/<api version>/<type>_conversion.go`, depending on the convention of the project.

  ```go
  func Convert_v1beta1_Image_To_v1alpha3_Image(in *v1beta1.Image, out *Image, s apimachineryconversion.Scope) error {
    return autoConvert_v1beta1_Image_To_v1alpha3_Image(in, out, s)
  }
  ```

  This should make the compilation error go away.

- Ensure, that `ConvertFrom` function calls `utilconversion.MarshalData` to put hub type data into older type annotation, which will make it available to restore in `ConvertTo` function.

- Modify `ConvertTo` functions for the types including your change to restore missing data from annotation.
  This can be done by using `utilconversion.UnmarshalData` function.

**Anything else you would like to add:**

Video explaining the process: https://www.youtube.com/watch?v=Mk14N4SelNk
Recent Slack thread about it: https://kubernetes.slack.com/archives/CEX9HENG7/p1651237939040449?thread_ts=1651233277.620019&cid=CEX9HENG7
Some older related Slack thread: https://kubernetes.slack.com/archives/CEX9HENG7/p1593096497044900

CC @sbueringer

/kind feature

**Comment by fabriziopandini** [comment]
What about moving this doc to the kubebuilder book, so a wider community can benefit from these notes (we can then reference from the CAPI book)

**Comment by sbueringer** [comment]
I think the make targets, backup/restore via the annotation and the fuzz tests are CAPI specific. Not sure if there is a good way to integrate this in the kubebuilder book.
