### ISSUE TITLE
Provide CAPI specific information about the cluster.

### ISSUE THREAD

**Issue by IshmeetMehta** [kubernetes-sigs/cluster-api#6489]
**User Story**

As a cluster admin and operator I would like to know whether the cluster is managed by CAPI or not.  

**Detailed Description**

As a cluster admin and operator,I would like to add a specific [clusterProperty](https://github.com/kubernetes-sigs/about-api) using [about api](https://github.com/kubernetes-sigs/about-api).
This clusterproperty should provide the following information about the cluster:

1. Whether the cluster is a member of CAPI?
2. Explore any other metadata that can be useful for cluster membership that can be stored as [clusterProperty](https://github.com/kubernetes-sigs/about-api)

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
I like the idea of starting to document cluster properties, this is something that can be useful in many scenarios.
However, I have a background question WRT the [about api](https://github.com/kubernetes-sigs/about-api). Is there a plan to make this part of the Kubernetes API/a sort of commitment/roadmap from other SIGs to adopt this idea?

**Comment by fabriziopandini** [comment]
/triage accepted
pending for feedback about plans to make this a K8s standard
