### ISSUE TITLE
Updating the manager roles for CAPI and KCP

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api#6493]
**User Story**

In CAPV, we created a new API group `vmware.infrastructure.cluster.x-k8s.io` which is used to support the VMService in supervisor cluster. To get this to work with CC, we need to amend the CAPI and KCP manager roles to include the types included in the API group.
Just looking for thoughts on what would be the best way to do this?

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
@srm09 it seems that this API group is provider specific. What about having CAPV adding additional RBAC rules for CAPI?

**Comment by fabriziopandini** [comment]
Another option is to leverage on aggregated roles as documented in https://cluster-api.sigs.k8s.io/developer/providers/machine-infrastructure.html#cluster-api-controllers

**Comment by sbueringer** [comment]
I think this should be done via aggregated roles (`cluster.x-k8s.io/aggregate-to-manager`). 

Note: there's a similar one for KCP.

**Comment by srm09** [comment]
My thought was to use the aggregation rule as well, wanted inputs from the community around if there is another way to achieve it. Makes sense though, thanks!

**Comment by fabriziopandini** [comment]
/remove-kind feature
/kind support

/close
@srm09 closing this given that there is not follow up work in CAPI; feel free to re-open if you need more help
