### ISSUE TITLE
Nodes without cloud provider

### ISSUE THREAD

**Issue by sathieu** [kubernetes-sigs/cluster-api#6497]
**User Story**

As a operator I would like to install nodes without cloud provider, because I don't want to give access to cloud API from those nodes.

**Detailed Description**

I'm using [cluster-api-provider-vsphere](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere) to provision machines, and I've removed the CPI and CSI from the [cluster template](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/download/v1.1.1/cluster-template.yaml). I've also disabled cloud-provider by setting `cloud-provider: ''` (instead of `cloud-provider: external`).

The nodes are stuck at `Provisioned` phase, and can be moved to `Running` by setting the node's `.Spec.ProviderID` to the value of the matching machine's  `.Spec.ProviderID`. The match is done on machine name and node name.

**Anything else you would like to add:**

I can work on a PR. I propose to add a `machine.spec.MatchOnNodeName` bool.

/kind feature

**Comment by sbueringer** [comment]
Q: Can't you just run CPI only on control-plane nodes? (but that's probably the default already?)

Do you only want to avoid giving the access on certain nodes or on all nodes?

**Comment by sathieu** [comment]
@sbueringer CPI is also problematic on control-plane nodes.

I want to avoid giving the access on all nodes.

**Comment by sathieu** [comment]
Here is my current workaround from from a restricted area:

```bash
old_IFS=$IFS
IFS=$'\n'
for machine in $(KUBECONFIG=mgmt.kubeconfig kubectl get machine --output=custom-columns=NAME:.metadata.name,PROVIDERID:.spec.providerID,PHASE:.status.phase --no-headers=true); do
  machine_name="$(echo $machine | awk '{print $1}')"
  provider_id="$(echo $machine | awk '{print $2}')"
  phase="$(echo $machine | awk '{print $3}')"
  [ "$phase" = "Provisioned" ] || continue
  KUBECONFIG=workload.kubeconfig \
    kubectl patch node "$machine_name" -p '{"spec":{"providerID":"'$provider_id'"}}'
done
IFS=$old_IFS
```

**Comment by enxebre** [comment]
The ProviderID is the CAPI provider agnostic contract between machines and Nodes. We built atop it the core machine controller and any higher level abstraction which requires mapping Nodes to Machines e.g Cluster autoscaler.
Having this agnostic contract enables CAPI to build common features that scale across providers. To satisfy this contract you don't necessarily need to run the regular ccm/cloud provider but you'd need to incorporate the providerID logic somehow, e.g in a controller in your capi provider manager. I think we should probably pursue that direction instead to avoid making a foundational contract fragile.

**Comment by sathieu** [comment]
Thanks for the context @enxebre. I understand, and this issue could be closed (and discussion moved to vsphere-specific: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/924#issuecomment-1123803887).

**Comment by fabriziopandini** [comment]
As per comment above
/close
