### ISSUE TITLE
Delete command should allow to delete a specific cluster

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#65]
_From @prateekgogia on February 7, 2018 0:40_

Currently, delete command for `cluster-api-gcp` doesn't take any cluster info. We should be able to specify which cluster to delete. 
If a user has more then one cluster, there is no way right now to delete a specific cluster.

_Copied from original issue: kubernetes/kube-deploy#579_

**Comment by rsdcastro** [comment]
_From @karan on February 7, 2018 2:43_

What will happen if you do `cluster-api-gcp delete --kubeconfig $SOME_OTHER_CONFIG`?

**Comment by rsdcastro** [comment]
_From @prateekgogia on February 7, 2018 7:8_

kubeconfig file can have multiple cluster info, there is no way to tell which cluster user wants to delete. We can have an option for deleting cluster in the current context, but that may not be very clear to the user (just an opinion).

**Comment by rsdcastro** [comment]
Since this is about the general delete command in the CLI, this should not be specific to GCP and marking it as such.

**Comment by vincepri** [comment]
Is this still relevant now that `clusterctl` supports delete?

**Comment by vincepri** [comment]
CC @roberthbailey
