### ISSUE TITLE
RuntimeSDK: Consider using shared structs in RuntimeHook API types

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6506]
Based on the (already merged) Discovery hook and the current state of the "Topology Mutation Hook" and "Runtime Hooks for Add-on management" proposals we will have some shared fields in our response types (status, message, retryAfterSeconds).

We currently define them in each struct. To avoid repeatedly defining the same fields we should consider establishing common structs which we can then embed in the response types.

This *might* also make it easily possible to implement getter/setter on the fields only once and then avoid using reflection to read/write the fields.

Additional notes:
* If we are assuming (in the runtime client) that every response has a Status and Message anyway it might be a good idea to introduce a `Response` object

/kind cleanup
/area runtime-sdk

**Comment by fabriziopandini** [comment]
/milestone v1.2
Let's try do this while implementing type for topology mutation hooks or for lifecycle hooks

**Comment by sbueringer** [comment]
We'll implement this already in https://github.com/kubernetes-sigs/cluster-api/pull/6499. It's less effort than merging the other implementation in #6499 and then reverting it. We're also not really blocking additionally by implementing it correct the first time.

**Comment by sbueringer** [comment]
Implemented in #6499

/close
