### ISSUE TITLE
Fix CAPD quick-start and E2E to adapt with changes in Kind v0.13

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#6509]
**What steps did you take and what happened:**
Kind v0.13 switched images to systemd cgroup driver and thus we have to adapt quick-start and E2E to work on 1.24.

In order to make this happen, 

- We have to upgrade the kind version used in our CI to 0.13
- We are going to switch the CAPD quick-start to use ClusterClass by default, so we can leverage version-aware patch in order to have a single template that works both with 1.24 as well as older version of Kubernetes
- For the same reason we are going to upgrade our E2E tests to use ClusterClass

**Anything else you would like to add:**
Users are required to user kind 0.13 to spin up management clusters on 1.24

/kind bug

**Comment by sbueringer** [comment]
fyi, it's highly likely this will also fix https://github.com/kubernetes-sigs/cluster-api/issues/4621
