### ISSUE TITLE
Security Self Assessment: [STRIDE-DOS-1] Misuse of cloud credentials to create unlimited number of cloud resources

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes-sigs/cluster-api#6515]
**User Story**

As an operator, I would like to apply soft/hard limits on maximum number of cloud resources so that I don't end up exhausting cloud resources available

As an operator, I would like to apply rate limits on cloud resource creation request, so that I don't end up exhausting cloud resources available in a short period of time

**Detailed Description**

Snippet from Cluster API security self-assessment: https://github.com/kubernetes/sig-security/pull/40

STRIDE-DOS-1 - Misuse of cloud credentials to create unlimited number of cloud resources
Cloud credentials can be misused by someone who has access to it by accidentally or maliciously creating very large number of cloud resources to exhaust cloud capacity or for financial damage caused due to surprise bills

STRIDE-DOS-1 Recommended Mitigations

- Create safe defaults (soft and hard) for the maximum number of cloud resources that can be created.
- Apply rate limits on how many “create cloud resources” requests can be successfully processed using the same cloud credentials.
- Implement threshold based alerts when a particular soft limit is exceeded

/kind feature
/sig security
/area security

**Comment by fabriziopandini** [comment]
I'm collapsing this issue into https://github.com/kubernetes-sigs/cluster-api/issues/6152 to see if we can make some progess
/close
