### ISSUE TITLE
Security Self Assessment: [STRIDE-DOS-4] Misuse of Infra Admin credentials to create unlimited number of CRDs to exhaust etcd storage

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes-sigs/cluster-api#6518]
**User Story**

As a an operator, I would like to set safe defaults on number of CRDs that can be created especially on a management cluster so that I don't exhaust underlying etcd storage

**Detailed Description**
Snippet from Cluster API security self-assessment: https://github.com/kubernetes/sig-security/pull/40
STRIDE-DOS-4 - Misuse of Infra Admin credentials to create unlimited number of CRDs to exhaust etcd storage

Infra Admin credentials can be misused by someone who has access to it by
accidentally or maliciously creating a very large number of CRD objects in the
management cluster to exhaust underlying storage of etcd. This could occur as a
side effect of the previous threat of creating an unlimited number of clusters
but can also happen through an unlimited number of nodes and other cluster
resources being added to one or more clusters.

Recommended Mitigations

* Implement safe defaults (soft and hard) on how many CRD objects a Cluster API
  component can create, especially in a management cluster
* Safe defaults on number of cluster and nodes will also have side effect of
  preventing this threat
  * Related issues #6516 #6517 

/kind feature
/area security
/sig security

**Comment by fabriziopandini** [comment]
/milestone v1.2
It would be interesting to have some figures from users..

**Comment by fabriziopandini** [comment]
/lifecycle frozen
/triage accepted
/help

Still a valid point to document some general best practices, but I think we should rely on core Kubernetes capabilities to limit what a user can do on the API Server / etcd instead of inventig our own custom solution

**Comment by fabriziopandini** [comment]
I'm collapsing this issue into https://github.com/kubernetes-sigs/cluster-api/issues/6152 to see if we can make some progess
/close
