### ISSUE TITLE
Security Self-Assessment: [STRIDE-MULTIPLE] Cluster API Cloud Provider Security Guidance

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes-sigs/cluster-api#6519]
**User Story**

As a cloud provider I would like to know how to support Cluster API securely.

**Detailed Description**

- Ensure credentials used by Cluster API are least privileged and setting access control on Cluster API controller namespaces to prevent unauthorized access by anyone other than cloud admin.
- Implement 2FA for all maintainer accounts on Github. Apply the second pair of eyes principle when performing privileged actions such as image building or updates to the contents of the machine images.
- Use short-lived credentials that are auto-renewed using node level attestation
- Implement rate limits for creation, deletion and update of cloud resources
- Any cloud resource not linked to a cluster after a fixed configurable period of time created by these cloud credentials, should be auto-deleted or marked for garbage collection

Related: https://github.com/kubernetes/sig-security/pull/40
/kind feature
/area security
/sig security

**Comment by fabriziopandini** [comment]
/milestone v1.2
Thanks for filing this issue; probably this should be divided into smaller issues, some of them to be addressed by providers
@yastij

**Comment by fabriziopandini** [comment]
/lifecycle frozen
/triage accepted
/help

Still a valid point to document some general best practices, but providing specific guidance for each cloud infrastructure should be addressed by cloud providers

**Comment by NareshKoduru** [comment]
> What we need is a new page in the book under security with the list of points from the description above.
> 
> /remove-help /good-first issue

@fabriziopandini,
cloud-provider-best-practises would be a good name for this page?

**Comment by fabriziopandini** [comment]
Considering that everything related to cloud infrastructure falls into the realm of infrastructure providers, let's call this paragraph "infrastructure provider security guidance" (we can eventually drop security, since it is already below the security chapter).

Also, please link the new page from a small "security guidelines" paragraph at the end of https://cluster-api.sigs.k8s.io/developer/providers/cluster-infrastructure and https://cluster-api.sigs.k8s.io/developer/providers/machine-infrastructure. Something like

##Security guidelines
Please refer to (infrastructure provider security guidance)[new page].

**Comment by NareshKoduru** [comment]
> Considering that everything related to cloud infrastructure falls into the realm of infrastructure providers, let's call this paragraph "infrastructure provider security guidance" (we can eventually drop security, since it is already below the security chapter).
> 
> Also, please link the new page from a small "security guidelines" paragraph at the end of https://cluster-api.sigs.k8s.io/developer/providers/cluster-infrastructure and https://cluster-api.sigs.k8s.io/developer/providers/machine-infrastructure. Something like
> 
> ##Security guidelines Please refer to (infrastructure provider security guidance)[new page].

@fabriziopandini ,
I submitted https://github.com/kubernetes-sigs/cluster-api/pull/11131 with the inputs provided. Please review. Thanks

**Comment by sbueringer** [comment]
@fabriziopandini Should this issue be closed, now that https://github.com/kubernetes-sigs/cluster-api/pull/11131 is merged?

**Comment by fabriziopandini** [comment]
yes!
Thanks @NareshKoduru for the work!
/close
