### ISSUE TITLE
Make MachineSet extensible in a similar way that Clusters/Machines are

### ISSUE THREAD

**Issue by joejulian** [kubernetes-sigs/cluster-api#652]
/kind feature

**Describe the solution you'd like**
Add ProviderSpec to MachineSet

**Anything else you would like to add:**
In DC/OS we have a tool (MKE) that manages the lifecycle of etcd, kubernetes master components, and nodes on mesos agents. To utilize that capability with a cluster-api implementation, we only want to specify a Cluster and MachineSet and let MKE handle the rest. For that to work, we need to add our own controller logic to the MachineSet.

In our use case, the MachineSet controller would still create Machines, but the Machine controller won't do anything but update the resource state.

**Comment by detiber** [comment]
This would also enable providers to more easily build around cloud provided auto scaling groups as well.

**Comment by timothysc** [comment]
@detiber - could you link this with more context.

**Comment by detiber** [comment]
Azure provider issue: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/113
/cc @juan-lee @alexeldeib

**Comment by alexeldeib** [comment]
@cecilerobertmichon

**Comment by ncdc** [comment]
We are essentially out of time for this to make v1alpha2
/milestone Next

**Comment by ncdc** [comment]
@samba could you please 👀 and let us know if this is still something your team is interested in. If so, could you please provide more details that line up with the v1alpha2 state of the API?

@CecileRobertMichon is this issue relevant to you? Is it the same thing as the MachinePool proposal?

I'm inclined to close this and have folks open up new issues that are more specific and in line with the v1alpha2 state of the world, if that works?

**Comment by CecileRobertMichon** [comment]
@juan-lee @vincepri @justaugustus 

yes I believe the MachinePool proposal would be an alternative to this.

**Comment by ncdc** [comment]
@CecileRobertMichon thanks. I'll wait a bit to hear back from either @samba or @joejulian before closing.

**Comment by samba** [comment]
@ncdc We can close this, at least for now. Our platform needs have changed, and we probably wouldn’t approach this under v1alpha2 (and later) the same way we were thinking about it in the v1alpha1 timeframe. Thanks for checking!
