### ISSUE TITLE
Makefile: make generate-go-openapi is broken if repository is not in GOPATH

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/cluster-api#6526]
**What steps did you take and what happened:**

* Dependabot did create PRs to bump golangci-lint #6522 and the github.com/coredns/corefile-migration dependency #6522
* The follow-up GH Action runs `make generate` [here](https://github.com/kubernetes-sigs/cluster-api/blob/main/.github/workflows/dependabot.yml#L36)

This did results in
* unexpected content for the `zz_generated.openapi.go` files
* as well as having them at a wrong place.

**What did you expect to happen:**

In this case no changes for the `zz_generated.openapi.go` files.

**Anything else you would like to add:**

The reason for that is the dependabot github action [here](https://github.com/kubernetes-sigs/cluster-api/blob/main/.github/workflows/dependabot.yml#L36) does not run `make generate` inside the `GOPATH`.

This results in `make generate-go-openapi` which gets transitively executed to also not run inside the `GOPATH`.

Issue was introduced in #6462 and only affects the generation of openapi code.

For kube-openapi this is still an unresolved issue https://github.com/kubernetes/kube-openapi/issues/233

They did workaround this issue themselves in https://github.com/kubernetes/kube-openapi/issues/225 

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by chrischdi** [comment]
For now we could fix the dependabot GH action by either:
* removing `make generate` which may be okay because we restrict dependabot to only bump `golangci-lint` and `github.com/coredns/corefile-migration` which both should not affect any generated code.
* adjusting the dependabot GH action to checkout cluster-api into `GOPATH`

On long-term we could take a look at  https://github.com/kubernetes/kube-openapi/issues/233

**Comment by fabriziopandini** [comment]
I'm personally +1 to adjusting the dependabot GH action to checkout cluster-api into GOPATH because this will avoid similar problems in the future, but I will defer this to @sbueringer and @chrischdi

**Comment by sbueringer** [comment]
To fix dependabot I would favor checking out in GOPATH over dropping make generate. 

Overall it would be nice to get the root cause fixed, given that in addition to the problems that some have with generate conversion we now have a second target which forces users to checkout CAPI in GOPATH.

**Comment by sbueringer** [comment]
fyi. I'll implement a workaround for the action here: https://github.com/kubernetes-sigs/cluster-api/pull/6607
But that should be reverted if the upstream openapi-gen is fixed / or we find a way to run it outside of the GOPATH.

**Comment by sbueringer** [comment]
/reopen

Let's drop the workaround from the golangci-lint action
