### ISSUE TITLE
Update documentation for max CoreDNS version must be updated

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#6527]
Documentation about [CoreDNS max supported version](https://cluster-api.sigs.k8s.io/reference/versions.html#kubeadm-control-plane-provider-kubeadm-control-plane-controller) must be updated according to https://github.com/kubernetes-sigs/cluster-api/pull/6525

A new line for v1.2 (v1beta1) | v1.9.2 must be added on the last table on the paragraph linked above

/kind documentation

**Comment by killianmuldoon** [comment]
/assign

Seeing as I forgot this in the other PR 😆

**Comment by killianmuldoon** [comment]
/unassign

I was too so slow - there's a PR open for this already 😆 

/assign @Sonali-Rajput

**Comment by Sonali-Rajput** [comment]
> /unassign
> 
> I was too so slow - there's a PR open for this already 😆
> 
> /assign @Sonali-Rajput

It's okay hahah 😊

**Comment by chrischdi** [comment]
xref #6530 , thx @Sonali-Rajput for taking that 👍
