### ISSUE TITLE
Automatically renew machine certificates

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6529]
**User Story**

As a user I would like to be able to configure ClusterAPI to automatically renew (machine) certificates.

**Detailed Description**

Today during machine bootstrap we create certificates via kubeadm with a 1 year expiry (e.g. apiserver serving certificates).
The goal of this issue is to make this expiry visible and to provide a way to automatically recreate machines before the certificates expire.
 
**Anything else you would like to add:**

Notes:
* I'll follow-up soon with more details and ideas for implementation

/kind feature

**Comment by neolit123** [comment]
Following the original CAPI machine immutability principle machines can roll out with new certs. ..Yet there have been many talks about allowing in place upgrades on bare metal machines and similar.

Certificate rotation can be also considered as mutable operation for bare metal machines that cannot easily roll out. I don't fully know the scope of the CAPI operator but the in place rotation might be a FR for it.

**Comment by fabriziopandini** [comment]
AFAIK the scope of this iteration is renewing machine certs trough machine rotation (no in-place mutations)

**Comment by sbueringer** [comment]
> @sbueringer Does this issue refers to kubelet certs as well? If so it relates to #6317. In which case I'd expect us to design a holistic solution that would consider serving/client certs and creation/renewal.

@enxebre Sorry I didn't have the time to add more details to the issue when I created it.

Goal is specifically to renew the certificates/kubeconfigs on control plane nodes (i.e. the ones that kubeadm can renew as well: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#check-certificate-expiration)

kubelet client certificates are already automatically rotated. kubelet serving certificates  should be solved via the [Kubelet Authentication CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20210222-kubelet-authentication.md) / #6317. So I think we can and should treat those as separate topics.

(see below the full issue description / proposed solution)

**Comment by sbueringer** [comment]
#### Background information

* **control plane nodes**: kubeadm generates [certificates and kubeconfigs](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#check-certificate-expiration) with 1 year expiration
* **worker nodes**: 
  * Kubelet serving certificates are currently self-signed ([Enabling signed kubelet serving certificates](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#kubelet-serving-certs)) and are thus not validated by the apiserver. To automate this we need the implementation of the [Kubelet Authentication CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20210222-kubelet-authentication.md).
  * Kubelet client certificates are already automatically rotated ([Configure Certificate Rotation for the Kubelet](https://kubernetes.io/docs/tasks/tls/certificate-rotation/#:~:text=Kubernetes%20contains%20kubelet%20certificate%20rotation,connections%20to%20the%20Kubernetes%20API.), enabled by kubeadm).

Goal of this issue is to rotate certificates and kubeconfigs of the **control plane nodes**.

#### Proposed solution

1. KubeadmConfig reconciler surfaces expiry date (now+1 year) on first reconcile of a KubeadmConfig via `machine.cluster.x-k8s.io/certificates-expiry-date` annotation on control plane Machines
2. Based on the annotation the Machine reconciler sets the expiry date in `Machine.status.certificatesExpiryDate`
3. MachineHealthCheck detects that certificates run out based on `Machine.status.certificatesExpiryDate` and `MachineHealthCheck.spec.certificateMinExpiryDuration` and triggers a Machine rollout

#### Notes

* Let's add a `CERTIFICATES EXPIRY DATE` column to Machine.
* We should add the MachineHealthCheck field to MachineHealthCheckClass as well (for ClusterClass support).
* Let's document the feature:
  * We will only support this feature for new Machines. 

#### Follow-up

* Export the `Machine.status.certificatesExpiryDate` as metric via kube-state-metrics

**Comment by chrischdi** [comment]
Regarding

> * Export the `Machine.status.certificatesExpiryDate` as metric via kube-state-metrics
>   * We have to check if exporting dates is supported after https://github.com/kubernetes/kube-state-metrics/pull/1777

If `Machine.status.certificatesExpiryDate` is of type string and in format `time.RFC3339` (which it will be if it is a `metav1.Time`) then `kube-state-metrics` (next release already, but also after my PR) will be able to expose a metric for it 👍
