### ISSUE TITLE
Provisioning Cluster stuck when using kubelet param `register-node: "false"` 

### ISSUE THREAD

**Issue by tranthang2404** [kubernetes-sigs/cluster-api#6531]
**What steps did you take and what happened:**
I want hide master node when provision a cluster. Base on docs https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/, we can change a Kubelet param to do this. 

So in the object `KubeadmControlPlane` path `spec.kubeadmConfigSpec.initConfiguration.nodeRegistration.kubeletExtraArgs`.  I add  `register-node: "false"`.

Then, when cluster has status `Provisioned`, when I connect that cluster I can get object  normally  and no master nodes as i expected. But worker node not boostrap and all machines (masters+workers)  object stuck in state `Provisioning`. I think becase its machine cannot has Node ref. So maybe it is logic code.

**What did you expect to happen:**
- Machine Object must has status `running` and may be not has Node ref

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:  v1.1.3 + infra Docker
- Minikube/KIND version:  kind v0.14.0
- Kubernetes version: (use `kubectl version`): v1.23.3
- OS (e.g. from `/etc/os-release`): ubuntu 20.04

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by neolit123** [comment]
--register-node = false us unsupported by kubeadm

Please see this for more context
https://github.com/kubernetes/kubernetes/issues/105059#issuecomment-920823574

**Comment by fabriziopandini** [comment]
If you are using KCP to manage control plane nodes, this is not supported (we inherit kubeadm constraints)

**Comment by fabriziopandini** [comment]
/close
this is not going to be fixed
