### ISSUE TITLE
Add support for raw template URL in clusterctl generate yaml 

### ISSUE THREAD

**Issue by DannyBrito** [kubernetes-sigs/cluster-api#6535]
**User Story**

As a user I would like to use `clustertctl generate yaml --from` with a URL to a raw template.

**Detailed Description**

At the moment `clusterctl generate yaml --from` accepts only GitHub.com URLs

**Anything else you would like to add:**

when running `clustertcl generate yaml --help` the example convey the idea that it accepts any URL.
```Examples:
  # Generates a configuration file with variable values using
  a template from a specific URL.
  clusterctl generate yaml --from https://github.com/foo-org/foo-repository/blob/main/cluster-template.yaml
```

/kind feature

**Comment by fabriziopandini** [comment]
Am I wrong or this is a duplicate on https://github.com/kubernetes-sigs/cluster-api/issues/7227 and it has already been fixed by https://github.com/kubernetes-sigs/cluster-api/pull/7228?

**Comment by aniruddha2000** [comment]
I think this [part](https://github.com/kubernetes-sigs/cluster-api/blob/df0fb87932b9661ceea754dff79344fd3c395f20/cmd/clusterctl/client/cluster/template.go#L146-L154) is causing the issue.
