### ISSUE TITLE
Automate Gitbook updates

### ISSUE THREAD

**Issue by davidewatson** [kubernetes-sigs/cluster-api#655]
/kind feature

**Describe the solution you'd like**

Updating our Gitbook documentation is currently a manual process and depends on the developer having access to the git subtree module, as well as write access to the gh-pages branch. We need better automation around this, preferably through CI.

Cf. #653 and #654.

**Comment by davidewatson** [comment]
kind and kubebuilder are experimenting with using netlify instead of firebase. Two advantages of this are netlify is already used to host the core k8s documentation and it makes it wasy to implement [continuous deployment](https://www.netlify.com/docs/continuous-deployment/). 

Cf. https://github.com/kubernetes-sigs/cluster-api/pull/747#issuecomment-465885607

**Comment by detiber** [comment]
Closing, since the gitbook release updates are now fully automated.
/close
