### ISSUE TITLE
KubeadmControlPlane `spec.kubeadmConfigSpec.joinConfiguration.patches.directory` should be mutable

### ISSUE THREAD

**Issue by superbrothers** [kubernetes-sigs/cluster-api#6576]
**User Story**

As an operator I would like to be able to modify KubeadmControlPlane `spec.kubeadmConfigSpec.joinConfiguration.patches.directory`.

**Detailed Description**

I want to update the spec of apiserver of the existing cluster, but changes to this field are not permitted currently.

```
The KubeadmControlPlane "eval-control-plane" is invalid:
* spec.kubeadmConfigSpec.initConfiguration.patches.directory: Forbidden: cannot be modified
* spec.kubeadmConfigSpec.joinConfiguration.patches.directory: Forbidden: cannot be modified
```

**Anything else you would like to add:**

None

/kind feature

**Comment by sbueringer** [comment]
@superbrothers Sounds good to me.

To implement this we have to:
* add patches to allowedPaths like e.g. nodeRegistration: https://github.com/kubernetes-sigs/cluster-api/blob/062883d4fdd577cbf908df3f75ae1f83fadf3805/controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go#L144-L145
* add a corresponding unit test (there are already a lot of similar unit test cases)

**Comment by superbrothers** [comment]
@sbueringer Thanks for your quick comment. I'll implement it.

**Comment by superbrothers** [comment]
@sbueringer I've created a PR.
