### ISSUE TITLE
Allow clusterctl client to fetch/use in-cluster kubeconfig

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api#6583]
**User Story**

As a developer, I would like to be able to initialize the clusterctl client in applications running on a pod in the management cluster. For example, I'm working on a visualizer app as well as a controller for add ons that would run as a pod on the management cluster and need to init the clusterctl client. Currently the client expects a kubeconfig path to be given or it will use the default discovery rules. However, applications like cluster autoscaler that run in the cluster initialize their client with [InClusterConfig()](https://pkg.go.dev/k8s.io/client-go/rest#InClusterConfig) which gets the kubeconfig of the current cluster or returns an `ErrNotInCluster`. I would like for `client.New()` to have an option to fetch the in-cluster config instead of looking for a file. Alternatively, we could let users call that function themselves and add an option to inject the kubeconfig as a string.

**Anything else you would like to add:**

A feature like this would be useful for broadening the usability clusterctl library by allowing it to work well outside of CLI contexts. Right now, the only way to use it form within a cluster is to fetch the kubeconfig yourself using a command like `kind get kubeconfig <name> --internal` and mounting it to the container as a volume.

/kind feature

**Comment by ykakarap** [comment]
Duplicate of https://github.com/kubernetes-sigs/cluster-api/issues/6286?

**Comment by sbueringer** [comment]
I think so

**Comment by Jont828** [comment]
Gotcha I'll close this then
