### ISSUE TITLE
cluster-api top-level Makefile currently broken

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#66]
_From @craigtracey on April 10, 2018:_

The top-level Makefile for generating code is currently broken. It assumes that apiregister-gen and conversion-gen are in $GOPATH. Fix this so that generation can happen cleanly and with generation tools at the appropriate tags.

_Copied from original issue: kubernetes/kube-deploy#675_

**Comment by rsdcastro** [comment]
_From @krousey on April 10, 2018:_

I assume you going to use a docker image to fix this? If so, can you create one with the apiserver-builder release and use that tool as it wraps all the generation tools we'll need?

**Comment by rsdcastro** [comment]
@craigtracey Is this still broken?

**Comment by roberthbailey** [comment]
This appears to have been fixed by https://github.com/kubernetes-sigs/cluster-api/pull/371. Please re-open if it is still an issue.

/close
