### ISSUE TITLE
Homebrew publish on release does not work

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6613]
Looks like our homebrew action does not work / probably never worked before.

It seems to depend on a personal access token which we don't really want to use.

For more context, see: https://kubernetes.slack.com/archives/C8TSNPY4T/p1653909691012589

xref: Action logs: https://github.com/kubernetes-sigs/cluster-api/actions/workflows/update-homebrew-formula-on-release.yml

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
+1 to drop current action

We should investigate how this is done in the Kubernetes project, because relying on personal tokens is not sustainable

**Comment by sbueringer** [comment]
Opened PR https://github.com/kubernetes-sigs/cluster-api/pull/6816 to drop the action. I would keep the issue around to look for a new solution.

**Comment by fabriziopandini** [comment]
/lifecycle frozen
/help

cc @ykakarap possible improvement to the release automation

**Comment by sbueringer** [comment]
Disclaimer: Probably hard to automotate entirely as we don't want to use personalized GitHub tokens and it's non trivial to push to community owned forks like the cherry pick bot.

But maybe there's prior art or ways to optimize the manual process a bit

**Comment by fabriziopandini** [comment]
I was thinking something like kpromo, so we create the PR automatically but using personal github token
but I agree the first step should be checking how this is done in K8s

**Comment by sbueringer** [comment]
Sounds good as a fallback.

Just remembered that kubectl is available via homebrew, so we can definitely ask the k/k release team how they are doing it.

**Comment by ykakarap** [comment]
During the v1.3.2/v1.2.9 release we observed that homebrew seems to have introduced some kind of automation to automatically pick up the new version of clusterctl when available. 
That automation should take care of doing the homebrew publishing steps for our releases. 
Let's keep an eye on that automation to be sure that it continues to do what the bump process.

cc @alexander-demicev

**Comment by furkatgofurov7** [comment]
@ykakarap @sbueringer looks like we can close this issue as completed, then?

**Comment by sbueringer** [comment]
Fine for me!

**Comment by furkatgofurov7** [comment]
Hey folks, I was checking it a bit, but I could not find a automated bot PR for clusterctl in homebrew repo. I could only found https://github.com/Homebrew/homebrew-core/pull/120231 that we did not open, but this seems to be not from the bot rather a homebrew maintainer?

**Comment by sbueringer** [comment]
I think the maintainer is running a bot with his account. There are a lot of PRs opened under his name with those PR descriptions:
![image](https://user-images.githubusercontent.com/4662360/217656235-089af362-ce54-456f-b90e-a135ec17ddc6.png)


But we can also just ask him if he runs a bot or if he runs a script from time to time.

**Comment by furkatgofurov7** [comment]
> I think the maintainer is running a bot with his account. There are a lot of PRs opened under his name with those PR descriptions: ![image](https://user-images.githubusercontent.com/4662360/217656235-089af362-ce54-456f-b90e-a135ec17ddc6.png)
> 
> But we can also just ask him if he runs a bot or if he runs a script from time to time.

Sure, waiting for response here: https://github.com/Homebrew/discussions/discussions/4260

**Comment by furkatgofurov7** [comment]
Based on the conversation with homebrew maintainers, here are my findings:

- there are different ways to open the PR in homebrew AFAIU, and it can be via a bot, a script, or manually
- homebrew repo has a bot, which tracks the formulaes in the Github workflow https://github.com/Homebrew/homebrew-core/blob/91c2e435b2f354084c9183c602081840ac9558e3/.github/workflows/autobump.yml#L15 running once a day and automatically opens the PR once it detects the new release. 
- `clusterctl` is already in the [list](https://github.com/Homebrew/homebrew-core/blob/91c2e435b2f354084c9183c602081840ac9558e3/.github/workflows/autobump.yml#L142) and in the past, bot opened clusterctl bumping PRs for us: https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+author%3ABrewTestBot+clusterctl+is%3Aclosed. When I compared the dates of CAPI release (i.e CAPI v1.1.3, released on March 8th, 2022) vs bot opening the PR (i.e clusterctl 1.1.3, merged on March 10th, 2022), there is a difference of `[min 1 - max 3]` days difference between them.

Side notes:

- k/k repo also has the same configuration for [kubectl](https://github.com/Homebrew/homebrew-core/blob/91c2e435b2f354084c9183c602081840ac9558e3/.github/workflows/autobump.yml#L422) but as I noticed, they also tend to open the PR [manually](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+kubernetes-cli+is%3Aclosed+) most of the time without waiting for the bot to do it. 
- sometimes bot opened PR build can fail for some reasons (i.e https://github.com/Homebrew/homebrew-core/pull/108335#issuecomment-1219224625), so if that is the case, anyways the manual PR needs to be opened. But that is anyways tracked if we decide to fully rely on bot.

**Comment by sbueringer** [comment]
Maybe we should just continue checking if the PR is already open and otherwise open it ourselves. Instead of waiting a few days and then potentially still opening the PR ourselves.

**Comment by sbueringer** [comment]
@furkatgofurov7 WDYT should we do with this issue?

I think basically documenting that we should check if the PR exists and create it otherwise should be fine (which is what we currently have documented) and we can close this issue.

I'm not sure it makes sense to invest in more automation given that we have no good idea on how to do it.

**Comment by furkatgofurov7** [comment]
@sbueringer I am fine with closing it. My intention reaching out to maintainers of homebrew was to clarify if we really have an automation in place or not. 

> I'm not sure it makes sense to invest in more automation given that we have no good idea on how to do it.

well, as I mentioned above:

> * `clusterctl` is already in the [list](https://github.com/Homebrew/homebrew-core/blob/91c2e435b2f354084c9183c602081840ac9558e3/.github/workflows/autobump.yml#L142) and in the past, bot opened clusterctl bumping PRs for us: https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+author%3ABrewTestBot+clusterctl+is%3Aclosed. When I compared the dates of CAPI release (i.e CAPI v1.1.3, released on March 8th, 2022) vs bot opening the PR (i.e clusterctl 1.1.3, merged on March 10th, 2022), there is a difference of `[min 1 - max 3]` days between them. By then, seems we were okay with that delay but not sure what has changed now?

some kind of automation is there, but it is not quick enough to open a PR right away and takes time (in days 😄), but we usually open a PR right away during releasing process, which makes it useless IMO. So, I do agree on not investing more time on finding/implementing a new automation around it.

**Comment by sbueringer** [comment]
Yup agree the automation on the homebrew side is not very useful to us.

It basically comes down to: are we fine with opening the PR manually or do we want to invest in finding a way to automate it.

I just don't see a way to automate it without someone configuring their personal GitHub token somewhere, which seems like a no-go. The alternative is probably to create a speical GitHub user / GitHub application / .. (like Kubernetes has for Prow (?)). But that seems too much effort.

**Comment by sbueringer** [comment]
Just discussed this again. It's simply not worth the effort to implement and maintain the automation.

Let's just open the PRs manually.

/close
