### ISSUE TITLE
Unsupported or untested Kubernetes minor versions should be blocked

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#6614]
Cluster API should refuse any upgrade to a version that's not fully tested or unsupported, unless an annotation is specified that allows users to opt in to an unsupported version.

/kind feature
/priority critical-urgent

**Comment by sbueringer** [comment]
I assume same for min version on create and for both workload/mgmt clusters.

**Comment by fabriziopandini** [comment]
/close
in favor of https://github.com/kubernetes-sigs/cluster-api/issues/7010
