### ISSUE TITLE
Align to CoreDNS bump to 1.9.3

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#6641]
CAPI should align its tests to CoreDNS bump to 1.9.3 in kubeadm, rif https://github.com/kubernetes/kubernetes/pull/110489

/kind feature

**Comment by fabriziopandini** [comment]
note, the PR contains also a bump to github.com/coredns/corefile-migration v1.0.17

**Comment by sbueringer** [comment]
Migration lib is up to date in CAPI

**Comment by sbueringer** [comment]
Just for folks who are not familiar with how we align to something like that.

We usually (if supported by CAPI) use the CoreDNS version used by the respective kubeadm version.

I.e. if we have an upgrade from v1.24=>v1.25, We create the cluster with kubeadm init (v1.24) and then upgrade to v1.25 so we use the CoreDNS version of kubeadm 1.25 as `COREDNS_VERSION_UPGRADE_TO`.

This means that aligning to v1.9.3 means that we should change `COREDNS_VERSION_UPGRADE_TO` to v1.9.3 in jobs where we upgrade to v1.25

**Comment by sbueringer** [comment]
Please note there's a PR open to add the 1.2 jobs: https://github.com/kubernetes/test-infra/pull/26621

We have to make sure that they eventually also use the right CoreDNS version

**Comment by sbueringer** [comment]
(doesn't block this issue, we should just make sure to comment on the 1.2 PR to make the same adjustments)

**Comment by sbueringer** [comment]
Almost forgot. There is currently no way to verify that a bump to v1.9.3 works in the v1.24=>v1.25 job as this job is currently broken: #6596

**Comment by chrischdi** [comment]
> Almost forgot. There is currently no way to verify that a bump to v1.9.3 works in the v1.24=>v1.25 job as this job is currently broken: #6596

@sbueringer should I still go forward and already create the PR in tets-infra or should we wait on this until #6596 got fixed?

**Comment by sbueringer** [comment]
You can open the pr already if you want

**Comment by sbueringer** [comment]
/reopen

Let's keep it open until #6596 is fixed and we can verify everything works

**Comment by chrischdi** [comment]
@sbueringer I think we can close this one :-) 🎉

**Comment by sbueringer** [comment]
My idea was to verify if it actually works after #6596 is fixed. As of today we have a bunch of jobs using 1.9.3 but they are all failing because of #6596. 

But yes if you want we can close this issue. We'll notice in #6596 if the new CoreDNS version actually works anyway.

**Comment by chrischdi** [comment]
Ah gotcha 👍  thought the 1.22 job was enough, so let's wait until

- #6596

Is closed.

**Comment by sbueringer** [comment]
Ah, only the v1.24=>v1.25 is using it because we align the versions used in e2e tests to the versions hard-coded in kubeadm (and used during kubeadm init)

v1.25 is now using CoreDNS v1.9.3 which triggered this issue

**Comment by chrischdi** [comment]
Jobs for CAPI main and v1.2 which upgrade to latest (v1.25) are green 👍  No other tests upgrade to v1.25 and coredns 1.9.3.

/close
