### ISSUE TITLE
Tasks for Kubernetes v1.25

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6661]
This issue is tracking the list of tasks that should be implemented when Kubernetes v1.24 is released. **Currently, we are waiting for the Kubernetes release**

For prior art please see #5968

* CI:
    * [x] CAPD: 
       * [x] PR: #7156
       * [x] release-1.2 PR: #7174
       * `docker.yaml`: `KUBERNETES_` env vars in `variables`
       * Tiltfile
       * kind_provider.go, docker/*, ... (just grep for the previously used version in CAPD)
       * also bump kind to v0.15.0
    * [x] Jobs: https://github.com/kubernetes/test-infra/pull/27421
        * Add new periodic upgrade jobs, for all release where we want to support the new Kubernetes version
        * Adjust presubmit jobs so that we have the latest upgrade jobs available on PRs (for all releases)
        * Update `INIT_WITH_KUBERNETES_VERSION`

* [x] Book:
    * [x] Update and test quickstart
      * [x] PR: #7156
      * [x] release-1.2 PR: #7174
    * [x] Update supported versions in versions.md
      * [x] PR: #7194
      * [x] release-1.2 PR: #7195
    * [x] Update job documentation in CAPI (`jobs.md`)
      * [x] PR: #7196
      * [x] release-1.2 PR: #7197

* [x] Release specific issues:
    * [x] Adjust KCP to migrate registry: 
        * [x] #6917
        * [x] #6957

* After a Kubernetes release is cut a controller-runtime version is created. When the CR version is available we have to:
    * [x] Bump controller-runtime to use new Kubernetes Go libraries (controller-runtime, controller-tools, client-go, ...)
        * This can include upgrading the Go version (we're using the same as k/k)
        * PR: #7211
    * [x] Update `KUBEBUILDER_ENVTEST_KUBERNETES_VERSION` in `Makefile`
        * PR: #7193
    * [x] Bump conversion-gen in `Makefile` via `CONVERSION_GEN_VER`
      * [x] PR: #7118
    * [x] If the new Kubernetes version uses a new Go version
        * [x] Jobs: Update kubekins-e2e images used for jobs running against main
            * Potentially it makes sense to switch to the latest ("master") version of kubekins-e2e if there is no `-{KUBERNETES-VERSION}` tag of the image already.
            * [x] PR: presubmit https://github.com/kubernetes/test-infra/pull/27311
            * [x] PR: periodics: https://github.com/kubernetes/test-infra/pull/27326
            * [x] PR: bump Go in CAPI: #7135 
        * [x] Update go version:
            * .github/workflows
            * .golangci.yml (+ corresponding workflow file)
            * cloudbuild YAMLs (to use an image with the current go version)
            * hack/ensure-go.sh
            * netlify.toml
            * Makefiles
            * Tiltfile
        * [x] [opt] go.mod files (only if we want to increase the minimum supported version of consumers) [will bump to go 1.19 after the CR/k8s.io bump]

**Comment by chrischdi** [comment]
`Release specific issues:` / `/Adjust KCP to migrate registry` should be fixed now :-)

**Comment by sbueringer** [comment]
Just fyi. Kubernetes 1.25 is using Go 1.19

**Comment by sbueringer** [comment]
I'll be collecting some notes in this comment for the upcoming controller-runtime upgrade:
* Enable `RecoverPanic` on all our webhooks, xref: #1900

**Comment by sbueringer** [comment]
Just fyi. Added a new sub task as I noticed that we forgot to bump conversion-gen the last time. (we're currently using conversion-gen v0.23.1)

**Comment by oscr** [comment]
I will bump Go version once an updated cloudbuild image with Go 1.19 is released. 

https://console.cloud.google.com/gcr/images/k8s-staging-test-infra/GLOBAL/gcb-docker-gcloud

**Comment by sbueringer** [comment]
Yup. Also probably good to only do this after we bumped the CR/k8s.io dependencies first. Don't want to run an untested combination for too long

**Comment by sbueringer** [comment]
All done. @oscr Thank you very much!!
