### ISSUE TITLE
ClusterClass fine grained infra examples

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api#6663]
This is mostly a idea for more fine-grained clusterclass examples, am ok if folks decide to close it.  

**What steps did you take and what happened:**

I was reading the ClusterClass CAEP and felt like i wanted more fine grained examples of how to configure things that reach deep into MachineDeployments, Kubeadm configuration, `etcd` bootstrapping, and so on. 

It used to be that as users we interfaced with these things directly when creating the family of all cluster objects.

**What did you expect to happen:**

We would have a migration guide with some complex/fine-grained examples for moving to a post-cluster class world.

**Comment by fabriziopandini** [comment]
+1 to add more examples in the book.
Being the CAEP a design doc, IMO we should have other trade-offs in order to explain concepts and how things work.

What is really important however is to start collecting the use case we want to document.

**Comment by sbueringer** [comment]
I'm not sure if we should really integrate infra provider examples into our book. We will essentially copy something which (hopefully?) works today into our book and nobody will take care that it will work going forward.

In my opinion we are using cluster templates today for something like this. Why not do the same for ClusterClass based cluster templates?

**Comment by fabriziopandini** [comment]
Avoiding creating documents we cannot maintain, really resonates with what I meant by "we really need the help of the community to understand how to improve our docs one step at time..."

**Comment by sbueringer** [comment]
Considering the comments above. I don't think we should actually do this.

In my opinion cluster-templates with ClusterClasses are the maintainable way to go.

**Comment by killianmuldoon** [comment]
>Considering the comments above. I don't think we should actually do this.
In my opinion cluster-templates with ClusterClasses are the maintainable way to go.

Agreed - a compromise might be to heavily comment the manifests and then embed the latest release versions for providers in the CAPI book so that they're well documented, literate, and maintained by providers in those repos.
