### ISSUE TITLE
Cluster API Roadmap documentation outdated

### ISSUE THREAD

**Issue by oscr** [kubernetes-sigs/cluster-api#6669]
The cluster api books roadmap hasn't been updated for ~2 years:
https://github.com/kubernetes-sigs/cluster-api/blame/main/docs/book/src/roadmap.md
https://cluster-api.sigs.k8s.io/roadmap.html

I suggest to simply just delete the roadmap to avoid having to duplicate information between GitHub and the book. But it's the core teams call. I can make a pr to fix it when I know what you would like to do with it.

**Comment by sbueringer** [comment]
Looks like a duplicate of https://github.com/kubernetes-sigs/cluster-api/issues/5519

/area documentation

**Comment by oscr** [comment]
Sorry! My mistake.

**Comment by sbueringer** [comment]
No problem, nevertheless the question is reasonable. Keeping an outdated roadmap doesn't really help
