### ISSUE TITLE
CAPI periodic-cluster-api-e2e-workload-upgrade-1-21-1-22-main job fails frequently

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6676]
According to testgrid the 1.21=>1.22 upgrade job fails frequently: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main-1-21-1-22

The error looks like this
> E0620 11:02:59.604086       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: endpointslices.discovery.k8s.io is forbidden: User "system:serviceaccount:kube-system:coredns" cannot list resource "endpointslices" in API group "discovery.k8s.io" at the cluster scope

My theory is that somehow we don't patch the CoreDNS role in those test runs. Usually we patch it for Kubernetes >=1.22 and CoreDNS >= 1.8.1.

https://github.com/kubernetes-sigs/cluster-api/blob/5026786ee809c5def466049f5befd2a786fbcefa/controlplane/kubeadm/internal/workload_cluster_coredns.go#L261-L291

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by chrischdi** [comment]
I'm not able to directly reproduce it, I have to use slightly other kubernetes versions (patch version) because the referenced images of the job are not available for mac M1 and building the kind images fails on mac M1 :-(

From original file, this then builds kind images for `v1.21.14 ` and `v1.22.11`, but did also already build and fail with the previous k8s versions (`v1.22.10`):
```
export KUBERNETES_VERSION_UPGRADE_FROM="stable-1.21"
export KUBERNETES_VERSION_UPGRADE_TO="stable-1.22"
export ETCD_VERSION_UPGRADE_TO="3.5.3-0"
export COREDNS_VERSION_UPGRADE_TO="v1.8.4"
export GINKGO_FOCUS="\\[K8s-Upgrade\\]"
./scripts/ci-e2e.sh
```

mac M1 version:
```
export KUBERNETES_VERSION_UPGRADE_FROM="v1.21.12"
export KUBERNETES_VERSION_UPGRADE_TO="v1.22.9"
export ETCD_VERSION_UPGRADE_TO="3.5.3-0"
export COREDNS_VERSION_UPGRADE_TO="v1.8.4"
export GINKGO_FOCUS="\\[K8s-Upgrade\\]"
./scripts/ci-e2e.sh
```

So I may try tomorrow to reproduce it on a linux system.

**Comment by sbueringer** [comment]
Can you build/push the images on Linux and then use them on MacOS? (assuming linux images can be just used in the M1 Mac Docker for Desktop)

**Comment by sbueringer** [comment]
@chrischdi I was thinking a bit about this failure and have a theory.

Assumption: this error started to occur when we switched the upgrade test to ClusterClass

Before: We set the Kubernetes and CoreDNS with the same patch call on the KCP resource
Now: We set spec.topology.version and the CoreDNS variable at the same time on the Cluster. They might still be applied at the same time to KCP but we don't have a guarantee for that.

Let's assume:
1. the CoreDNS version is propagated
2. the KCP version is bumped to v1.22

During 1.:
* we execute: https://github.com/kubernetes-sigs/cluster-api/blob/628c05c2b27de5597a2d2397dc04adad64551ec6/controlplane/kubeadm/internal/workload_cluster_coredns.go#L104
* this bumps the CoreDNS version in the deployment
* this does not update the ClusterRole as we're not yet on Kubernetes v1.22 (https://github.com/kubernetes-sigs/cluster-api/blob/628c05c2b27de5597a2d2397dc04adad64551ec6/controlplane/kubeadm/internal/workload_cluster_coredns.go#L263-L265)

During 2.:
* we probably execute `UpdateCoreDNS` again
* we don't execute `updateCoreDNSClusterRole` because CoreDNS is already on the target version: https://github.com/kubernetes-sigs/cluster-api/blob/628c05c2b27de5597a2d2397dc04adad64551ec6/controlplane/kubeadm/internal/workload_cluster_coredns.go#L129-L131

I'm not 100% sure if this is the cause of our e2e test failure, but it looks to me like a bug anyway. Essentially always when we bump CoreDNS to >= v1.8.1 and then afterwards in another reconcile bump Kubernetes to v1.22 the ClusterRole won't be updated (it will be on the next CoreDNS upgrade though).

(cc @fabriziopandini maybe we should try to get a fix into the upcoming release if my theory is correct)

P.S. @chrischdi If my theory is correct you can reproduce with whatever kindest/node 1.21/1.22 images are published on dockerhub.

**Comment by chrischdi** [comment]
I'm trying to dig deeper into this.

/assign
