### ISSUE TITLE
Add support for ImagePullPolicy in KCP and CABPK

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#6679]
**User Story**

As a user/operator I would like to use all the latest and greatest from kubeadm

**Detailed Description**

https://github.com/kubernetes/kubernetes/pull/102901 added support for the `imagePullPolicy` option in the kubeadm config file; we should make this option available in KCP and CABPK

**Anything else you would like to add:**

This is a good opportunity to diff the entire set of kubeadm config file options supported in KCP/CABPK and identify other gaps, if any.
Prior art https://github.com/kubernetes-sigs/cluster-api/pull/4905

/kind feature

**Comment by sbueringer** [comment]
Just a note. I think we intentionally didn't add some fields because they didn't make sense in our context (I did the diff a few months back)

**Comment by akshay196** [comment]
I would like to work on this.
/assign
