### ISSUE TITLE
Check if master exists as previous command might have been cancelled

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#67]
_From @rsdcastro on January 29, 2018 21:40_

_Copied from original issue: kubernetes/kube-deploy#523_

**Comment by spew** [comment]
Think we need some more context on this one -- what does this mean? Is it still going to be valid in the 'clusterctl' world or should we just reset and close this one?

**Comment by roberthbailey** [comment]
@jessicaochen - is this still relevant with clusterctl?

**Comment by jessicaochen** [comment]
Honestly, I am not sure what this issue is talking about. Since we have a new tool (clusterctl), I assume this is not actually relevant anymore. Feel free to re-open with more context if you disagree.

/close

**Comment by jessicaochen** [comment]
(I do not seem to have rights to close the issue, could someone with rights close it?)
