### ISSUE TITLE
Not updated providers Alicloud and Baidu

### ISSUE THREAD

**Issue by oscr** [kubernetes-sigs/cluster-api#6714]
While reading the [providers list](https://main.cluster-api.sigs.k8s.io/reference/providers.html) I noticed that Alicloud only has a single commit 3 years ago and Baidu last commit was 4 years ago.  

https://github.com/oam-oss/cluster-api-provider-alicloud
https://github.com/baidu/cluster-api-provider-baiducloud

I therefore suggest removing them from the documentation for future releases since they are out of date and likely abandoned.

**Comment by vincepri** [comment]
Sounds good to keep the list up-to-date with providers that are still working with the latest versions, we should however also document the minimum requirements to be listed in the docs.

**Comment by sbueringer** [comment]
> Sounds good to keep the list up-to-date with providers that are still working with the latest versions, we should however also document the minimum requirements to be listed in the docs.

What are our minimum requirements to be listed in the doc?

**Comment by oscr** [comment]
> What are our minimum requirements to be listed in the doc?

I suggest ~"being actively developed". As long as the provider keeps improving it stays on the list.

Alternatively maybe having a CAPI and provider version compatibility table similar to https://main.cluster-api.sigs.k8s.io/reference/versions.html#core-provider-cluster-api-controller would work? Then we could just ask the provider developers to make a pr when a provider supports a new CAPI release.

**Comment by oscr** [comment]
As input to this discussion there is a ticket in the Alicloud provider asking if it's abandoned:
https://github.com/oam-oss/cluster-api-provider-alicloud/issues/1

I opened a similar one for Baidu:
https://github.com/baidu/cluster-api-provider-baiducloud/issues/24

Hopefully both will answer that development will continue. But lets see.
