### ISSUE TITLE
Ease Runtime Extension implementation by providing exported util packages

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6720]
Goal of this issue is to make it easier to implement RuntimeExtensions by exporting useful packages.

Note: We gathered some experience writing RuntimeExtensions by implementing a test extension for our e2e tests.

I would propose to:
* move `internal/runtime/catalog` to `exp/runtime/catalog`
    * I think catalog is stable enough to be exported.
* move `test/extension/server` to `exp/runtime/server`
    * While the server package is pretty new, I think we can still iterate on it given the [API guarantees for the exp package](https://github.com/kubernetes-sigs/cluster-api/blob/9a1948ee0bc7226f26276d778b140630de88a04f/exp/README.md#L12-L11).
    * By exporting the package now we can gather feedback from RuntimeExtension authors and evolve it over time.

By moving these packages it becomes a lot easier to implement RuntimeExtensions. In fact looking at our test extension it would be enough to implement a Runtime Extension for lifecycle hooks.

It should also help to implement RuntimeExtensions for topology mutation but I think we need a follow-up to:
* export a package which makes it easy to work with variables
* export a package (possibly the same) which helps folks to deal with the topology mutation hook requests/responses and generate patches. The basis for this can be: the [variable package](https://github.com/kubernetes-sigs/cluster-api/tree/main/internal/controllers/topology/cluster/patches/variables) and [lib.go from our test extension](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/extension/handlers/topologymutation/lib.go).

/kind feature

**Comment by sbueringer** [comment]
@fabriziopandini @chrischdi @ykakarap @killianmuldoon Opinions?

**Comment by killianmuldoon** [comment]
+1 I think we should make the experimental contract very explicit, and after that try to offer as much functionality (in as few public methods) as possible. +1 to both catalog and the test extension.

**Comment by ykakarap** [comment]
+1 to moving both the packages. Would simplify implementing an extension if we access to catalog and the server libraries.

I have some bandwidth and I am happy to help with the refactoring. 

/assign
