### ISSUE TITLE
Remove failure domain from cluster status upon removal from infra cluster status

### ISSUE THREAD

**Issue by aartij17** [kubernetes-sigs/cluster-api#6732]
**What steps did you take and what happened:**
- Deployed a workload cluster using CAPV with failure domain
- The failure domain is included in the machine spec when the machines are reconciled
- The cluster and VSphereCluster object status also has the failure domain
- Delete the failure domain CRs, which in turn get removed from the VSphereCluster status, but not the cluster status

**What did you expect to happen:**
The expected behavior is that the Cluster status should be clear of the failure domains and eventually KCP should not use it for CP node creation.

**Anything else you would like to add:**
Even when the failure domains are not present on the VSphereCluster status object, they show up on the Cluster object.

**Environment:**
- Cluster-api version: `v1.0.1`
- Kubernetes version: (use `kubectl version`): 1.24

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

/assign @srm09

**Comment by fabriziopandini** [comment]
It will be great to get this in 1.1.5, but given time crunch this might slip to 1.1.6

**Comment by sbueringer** [comment]
> Cherry-picking the fix to release-1.0 should be enough.

As far as I'm aware v1.0.x is out of support and there won't be another v1.0.x release.

**Comment by fabriziopandini** [comment]
As per comments above
/close
