### ISSUE TITLE
Docs on 'Local Registry' section

### ISSUE THREAD

**Issue by oatmealb** [kubernetes-sigs/cluster-api#6745]
**What steps did you take and what happened:**
When following the [Local Registry > Create A Cluster And Registry](https://kind.sigs.k8s.io/docs/user/local-registry/#create-a-cluster-and-registry) of the guide, I ran the provided `.sh` script and got
```
Error response from daemon: network kind not found
```

If I "manually" `docker network create kind`, this guide section (seemingly) works. But then the next section, [Using The Registry](https://kind.sigs.k8s.io/docs/user/local-registry/#using-the-registry) fails as the pod can't pull the `hello-app` image:
```sh
kubectl logs hello-server-<someID>
Error from server (BadRequest): container "hello-app" in pod "hello-server-<someID>" is waiting to start: trying and failing to pull image
```

**What did you expect to happen:**
The `google-samples/hello-app` runs successfully, with the locally pulled image.

**Anything else you would like to add:**

```sh
> kubectl cluster-info --context kind-kind
Kubernetes control plane is running at https://127.0.0.1:43831
KubeDNS is running at https://127.0.0.1:43831/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```
I've attached 'kubectl cluster-info dump' output.

Only these issues contain the same error:
- Unlike [this one](https://github.com/kubernetes-sigs/cluster-api/issues/4817#issuecomment-861752933), I don't have `KIND_EXPERIMENTAL_DOCKER_NETWORK` set.
- [The second issue](https://github.com/metallb/metallb/issues/711)

**Environment:**

- Cluster-api version: v1.16.3
- minikube/kind version: 0.6.1 (installed via [asdf](https://asdf-vm.com/))
- Kubernetes version: (use `kubectl version`): v1.16.3
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.2 LTS
- Docker version 20.10.7, build f0df350

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
[cluster-info_dump.log](https://github.com/kubernetes-sigs/cluster-api/files/8990539/cluster-info_dump.log)

**Comment by sbueringer** [comment]
@oatmealb
I think this issue should be opened in the kind repository

**Comment by sbueringer** [comment]
No worries :)
