### ISSUE TITLE
Cluster validation fails even though cluster has been successfully created

### ISSUE THREAD

**Issue by girikuncoro** [kubernetes-sigs/cluster-api#678]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Running cluster validation after cluster has been created
```
$ kubectl --kubeconfig kubeconfig get node
NAME               STATUS   ROLES    AGE     VERSION
gce-master-5kbc8   Ready    master   11m     v1.12.0
gce-node-gm7mx     Ready    <none>   4m50s   v1.12.0
```
```
$ kubectl --kubeconfig kubeconfig get machines
NAME               AGE
gce-master-5kbc8   11m
gce-node-gm7mx     11m
```
```
$ clusterctl validate cluster --kubeconfig kubeconfig
I0115 06:09:18.508437   44513 machineactuator.go:813] Using the default GCP client
I0115 06:09:18.508793   44513 plugins.go:39] Registered cluster provisioner "google"
Validating Cluster API objects in namespace ""
Checking cluster object "test1-chl6h"... PASS
Checking machine object "gce-master-5kbc8"... FAIL
	The corresponding node is missing.
Checking machine object "gce-node-gm7mx"... FAIL
	The corresponding node is missing.
ERROR: Machine objects failed the validation.
```

**What did you expect to happen:**
All checks should have passed since all machine objects exist

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:10Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T16:55:41Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):
```
Ubuntu 16.04.5 LTS (Xenial Xerus)
```

**Comment by vincepri** [comment]
I think this is caused by `NodeRef` not being populated in the GCP provider (same goes for AWS provider). This code https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/validation/validate_cluster_api_objects.go#L97-L134 uses `NodeRef` (which is also [optional](https://github.com/kubernetes-sigs/cluster-api/blob/9c0f9874a7d759a8a7d714dd9073947eca53bb24/pkg/apis/cluster/v1alpha1/machine_types.go#L89-L91)) to get the node name, which seems unnecessary (unless I'm missing something) given that we can get the name from the Machine object.

**Comment by girikuncoro** [comment]
Thanks for suggestion, I'll try to fix this

**Comment by ncdc** [comment]
This sounds like a provider specific issue; however, I do think it's related to #520 - does that sound right @davidewatson?

**Comment by ncdc** [comment]
Moving to Next, since we've deferred #520. Please let me know if you think this should stay in v1alpha1.

/milestone Next

**Comment by lzang** [comment]
Hit similar issue on my setup, then figured out that for the validation to pass, NodeRef needs to be not nil, which means the node needs to have the correct annotation.  You can describe your node and see if they have the annotation "cluster.k8s.io/machine"

**Comment by timothysc** [comment]
closing, we are going to take a different road.
