### ISSUE TITLE
How about the old workload clusters when the management cluster has been upgrade?

### ISSUE THREAD

**Issue by ruifaling** [kubernetes-sigs/cluster-api#6786]
Currently, my management cluster version is 1.20.10, the version of cluster-api is V0.4, the version of my workload cluster keep the same with management cluster 1.20.10 . Now for some reason , I want to upgrade my management cluster to version 1.23, thus the version of cluster-api should be upgrade at least V1.1 . So what will happen to my workload clusters(1.20.10),  can the cluster-api(1.23) continue to management  them? it Still can scaleup,scaledown?

**Comment by sbueringer** [comment]
>  I want to upgrade my management cluster to version 1.23, thus the version of cluster-api should be upgrade at least V1.1

You can also upgrade your mgmt cluster to v1.23 with v1alpha4, but it is definitely recommended to use a recent CAPI version.

>  So what will happen to my workload clusters(1.20.10), can the cluster-api(1.23) continue to management them?

The workload cluster versions that CAPI can manage doesn't depend on the Kubernetes version of the mgmt cluster.
Yes. CAPI v1.1.x can still manage 1.20.x workload clusters

> Still can scaleup,scaledown?

Yes


See https://cluster-api.sigs.k8s.io/reference/versions.html for more details

**Comment by ruifaling** [comment]
@jichenjc Does the provider-openstack support?

**Comment by ruifaling** [comment]
![image](https://user-images.githubusercontent.com/79310393/176626248-74f9346a-5678-4149-81c1-e3618d931f87.png)

**Comment by ruifaling** [comment]
> > I want to upgrade my management cluster to version 1.23, thus the version of cluster-api should be upgrade at least V1.1
> 
> You can also upgrade your mgmt cluster to v1.23 with CAPI v0.4.x, but it is definitely recommended to use a recent CAPI version.
> 
> > So what will happen to my workload clusters(1.20.10), can the cluster-api(1.23) continue to management them?
> 
> The workload cluster versions that CAPI can manage doesn't depend on the Kubernetes version of the mgmt cluster. It only depends on the CAPI version. Yes. CAPI v1.1.x can still manage 1.20.x workload clusters
> 
> > Still can scaleup,scaledown?
> 
> Yes
> 
> See https://cluster-api.sigs.k8s.io/reference/versions.html for more details

The managment upgrade to 1.23 thus the admissionregisteration.k8s.io/v1betav1 will change to admissionregisteration.k8s.io/v1 ,it does not effect on CAPI and cert-manager?

**Comment by sbueringer** [comment]
As far as I'm aware CAPI and cert-manager were using v1 CRDs already. I can't speak for infrastructure providers.

As v0.4 is out of support since a few months, I would recommend updating CAPI to a supported v1.1.x version ASAP anyway.
