### ISSUE TITLE
Enable auto assigner for cluster-api PR reviews

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#68]
Similar to https://github.com/kubernetes/kube-deploy/issues/612, but for this repo.

Quoting @krousey:

Figure out what is needed to auto assign PRs to reviewers. This will help distribute the load and also spread the mind-share amongst interested community members.

**Comment by dims** [comment]
@rsdcastro @roberthbailey So we can add a separate set of reviewers which i filed a PR for. (So we can add folks who just review and are not maintainers). We already have plugins enabled that suggest assignees.

```
dims [2:25 PM] @bentheelder @fejta @cblecker the prow plugins we have can add “Reviewers” and not “Assignees” (in github terminology). is that right?
cjwagner [2:27 PM] Yes thats correct. We only suggest assignees
dims [2:28 PM] thanks @cjwagner
bentheelder [2:29 PM] er though to be clear `/assign` does assign, but only by request. whereas blunderbuss auto adds reviewers, and the approval plugin can suggest assignees
```

**Comment by rsdcastro** [comment]
There's some context to this bug. We realized we had blunderbuss enabled, but without a "reviewers" section, we wouldn't have the auto-assigning feature working. Test Infra implemented an improvement that, without reviewers, it uses the approvers section. So that is why it is (or should be) working now.

I still believe that having a separate section is reasonable. People are removing me and others that don't have bandwidth (or have long turnaround time) and assigning others by hand. That should not happen.

And having blunderbuss also allows us to implement the policy that we want to share the load and what blunderbuss picks as reviewers are the ones to do the review (other than targeting always the same reviewers for some reason).

**Comment by dims** [comment]
All the repos in kubernetes-sigs org already have `blunderbuss` enabled - https://github.com/kubernetes/test-infra/blob/master/prow/plugins.yaml#L432
