### ISSUE TITLE
Information overlap between two clusterctl doc pages

### ISSUE THREAD

**Issue by oscr** [kubernetes-sigs/cluster-api#6804]
There is somewhat of an overlap between these two pages describing `clusterctl` commands:

- https://main.cluster-api.sigs.k8s.io/clusterctl/overview.html
- https://main.cluster-api.sigs.k8s.io/clusterctl/commands/commands.html

The first doesn't have all commands, but a nice one sentence description of each command. The seconds has all commands but no description. I suggest removing the list of commands from overview, and adding a one sentence description of each in the second. Any other opinions?

**Comment by killianmuldoon** [comment]
Sounds good to me!

**Comment by sbueringer** [comment]
Sounds good so far.

I would suggest to then change the Overview page to be an overview over all direct sub pages (commands / configuration / provider contracts / clusterctl for developer).

**Comment by fabriziopandini** [comment]
I personally think it is useful for the users to have a selection of main commands in the overview.
I would suggest adding a sentence that clarifies those are only the main ones and link to the command page for the full list

**Comment by oscr** [comment]
That's a great point @fabriziopandini. Maybe the overview should be expanded to ~"common operations" pages instead of deleted? The Quick Start gives an overview of some of the commands and maybe additional pages could cover other topics?

While we're at it: what's everyone's opinion about moving the "clusterctl installation" section from Quick Start page to it's own page under "clusterctl CLI"? I think it would be simpler to find the installation instructions and make the Quick Start shorter.

**Comment by fabriziopandini** [comment]
IMO overview is already ~"common operations", we just have to make it clear to the users to address the concern raised by this issue.

I'm personally -1 to remove clusterctl installation from the quick start, it is just a couple of lines and it makes the quick start self-contained (note: it is also out of scope of this issue)
