### ISSUE TITLE
Update Glossary with RuntimeSDK terms

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6819]
We introduced a few new terms like Runtime Hooks and Runtime Extensions in the [Runtime SDK CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20220221-runtime-SDK.md).

Goal of this issue is to add those terms to the Glossary: https://cluster-api.sigs.k8s.io/reference/glossary.html

**Comment by fabriziopandini** [comment]
+1
I guess we should do something similar for ClusterClass as well
