### ISSUE TITLE
Cluster deployer should support creation of clusters with HA controlplane

### ISSUE THREAD

**Issue by ashish-amarnath** [kubernetes-sigs/cluster-api#682]
/kind feature

**Describe the solution you'd like**
Cluster deployer should support the creation of clusters with multiple master machines

**Anything else you would like to add:**
On creating a cluster with multiple master machines, the deployer fails because the deployer finds multiple masters.
https://github.com/kubernetes-sigs/cluster-api/blob/299c318690e526b7d8c704ab40a813c00ab7b0b0/cmd/clusterctl/clusterdeployer/clusterdeployer.go#L417

cc @vincepri 

**Environment:**

- Cluster-api version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuyangbj** [comment]
@ashish-amarnath do we have any KEP description or design doc for this feature to follow up? Thanks.

**Comment by ashish-amarnath** [comment]
@yuyangbj unfortunately not.
But this PR from the aws provider implementation https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/463 should offer some context.

**Comment by ncdc** [comment]
This was fixed by #878 
/close
