### ISSUE TITLE
Improving usage in `clusterctl generate cluster --help`

### ISSUE THREAD

**Issue by oscr** [kubernetes-sigs/cluster-api#6867]
When running for example `clusterctl generate cluster --help` (there are more examples), usage is described as:

```
Usage:
  clusterctl generate cluster [flags]
```

However if you attempt to run the given example you will get an error. 

```
clusterctl generate cluster
Error: accepts 1 arg(s), received 0
``` 

Since the command has a required argument.

I would therefore like to suggest changing the usage to reflect the required arguments. For example: 

```
Usage:
  clusterctl generate cluster NAME [flags]
```

This suggestion would be similar to how kubectl usages looks:
```
kubectl create deployment --help
(...)
Usage:
  kubectl create deployment NAME --image=image -- [COMMAND] [args...] [options]
```

The commands that need to be updated are:
* `clusterctl describe cluster` in https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/cmd/describe_cluster.go
* `clusterctl generate cluster` in https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/cmd/generate_cluster.go
* `clusterctl get kubeconfig` in https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/cmd/get_kubeconfig.go
* No action needed for restore since it's deprecated.

You can use the following comment as a blue print for the changes needed: https://github.com/kubernetes-sigs/cluster-api/issues/6867#issuecomment-1178136733

You can build by running: `make clusterctl` in the root directory. Then run the binary by running `./bin/clusterctl <commands>` (on Linux. Might be different for macOS or Windows).

**Comment by oscr** [comment]
I suspect we can fix it the same way kubectl does here:
https://github.com/kubernetes/kubernetes/blob/e9b96b167fbe5bb7c16824f5515501434c9e4a2e/staging/src/k8s.io/kubectl/pkg/cmd/create/create_deployment.go#L98

I tried it with generate cluster
```diff
diff --git a/cmd/clusterctl/cmd/generate_cluster.go b/cmd/clusterctl/cmd/generate_cluster.go
index 595d03f1c..1eaa09b0e 100644
--- a/cmd/clusterctl/cmd/generate_cluster.go
+++ b/cmd/clusterctl/cmd/generate_cluster.go
@@ -47,7 +47,7 @@ type generateClusterOptions struct {
 var gc = &generateClusterOptions{}
 
 var generateClusterClusterCmd = &cobra.Command{
-       Use:   "cluster",
+       Use:   "cluster NAME",
        Short: "Generate templates for creating workload clusters",
        Long: LongDesc(`
                Generate templates for creating workload clusters.

```

This gives improved usage

```shell
./bin/clusterctl generate cluster --help

(...)

Usage:
  clusterctl generate cluster NAME [flags]
```

And the command seems to work as expected:
```
./bin/clusterctl generate cluster 
Error: please specify a cluster name

HELM_VALUES="" KUBERNETES_VERSION=1.24.4 ./bin/clusterctl generate cluster my-cluster
(... expected yaml output)
```

**Comment by oscr** [comment]
I will of course continue with the PRs to improve the remaining error messages. But the question remains: do we want to modify usage to be more in line with `kubectl`?

**Comment by fabriziopandini** [comment]
/triage accepted
/area clusterctl
I'm +1 to improve command helps

/help

**Comment by oscr** [comment]
@fabriziopandini Maybe this is also good first issue? It seems like a pretty straight forward task with plenty of interesting things to learn. Otherwise I can likely have it done by the weekend.

**Comment by ykakarap** [comment]
+1 to making it a good first issue. Lets see if others might be interested in working on it after making it a good first issue. If not feel free to take it up.

**Comment by oscr** [comment]
Great! I'll give it a few weeks and we'll see if we have any takers.

**Comment by fabriziopandini** [comment]
If you want to make this a good first issue it is required to give some more details about which command help should be improved, otherwise if the task requires some research/knowledge of the codebase

**Comment by oscr** [comment]
@fabriziopandini Good point. I've updated with more details about what commands to run, what files to change, how to change and how to test. Please take a look if you're happy with it otherwise I will add more details.

**Comment by C-Society** [comment]
Helllo @fabriziopandini and @oscr, Thank you for marking it `good first issue`,I will like to work on this.

/assign

**Comment by oscr** [comment]
Awesome @C-Society! Thank you for taking it and good luck!

**Comment by chiukapoor** [comment]
The PR has merged successfully, thank you @oscr for the detailed issue description!
