### ISSUE TITLE
We need to support CAPI -> worker etcd connections, in high latency environments

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api#6884]
Per conv w @randomvariable , since CAPI lifecycles etcd membership, the ability to talk to etcd directly, is a CORE CAPI REQUIREMENT... turns out this needs tuning in high latency enviornments !

**What steps did you take and what happened:**

Ran TC so that it limited LATENCY from mgmt to workload ControlPlanes. Theres a situation where the "KCP" has to talk directly to `etcd`.

In these cases, the attempt of the mgmt cluster's capi-kubeadm-control-plane-controller-manager is not able to talk to the API server on the 

```
I0707 16:28:45.382815       1 scale.go:212]  "msg"="Waiting for control plane to pass preflight checks" "cluster-name"="tkg-vc-robo-antrea" "name"="tkg-vc-robo-antrea-control-plane" "namespace"="default" "failures"="[machine tkg-vc-robo-antrea-control-plane-ls76r reports EtcdMemberHealthy condition is unknown (Failed to connect to the etcd pod on the tkg-vc-robo-antrea-control-plane-ls76r node: could not establish a connection to any etcd node: unable to create etcd client: context deadline exceeded) 
```

**What did you expect to happen:**

Expected to be able to configure settings in CAPI so that,  the ability of the kcp (on mgmt cluster) to talk to etcd (on wl cluster). Probably this means adding knobs to the capi KCP pod's configmap .

(per naadir likely fabrizio would suggest a cmd line flag on the kcp controller...)
i.e.

```
  - args:
    - --leader-elect
    - --metrics-bind-addr=localhost:8080
    - --feature-gates=ClusterTopology=false
    - --client-backoff-limit=32s
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: head
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`): 

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 

(updated to client backoff limit per vince comment)

**Comment by jayunit100** [comment]
oh, wait , thats an arg for kcp ? i guess well try it hang on!

**Comment by vincepri** [comment]
https://github.com/kubernetes-sigs/cluster-api/commit/ce2700c8dbb4c25adcdc38ad155a6c016a30329e

The flag has been available from v1.1

**Comment by jayunit100** [comment]
ok, should we close this, then ?

**Comment by fabriziopandini** [comment]
As per comment above
/close

We can re-open if additional work is required.
