### ISSUE TITLE
CAPI is stuck draining node if a replica-set schedules a pod on a node that is deleting.

### ISSUE THREAD

**Issue by pradipd** [kubernetes-sigs/cluster-api#6894]
**What steps did you take and what happened:**
A user has a replica set deployed with a toleration and no key (so it matches all taints including unschedulable).
The user initiates and upgrade.  The node is drained successfully and the infrastructure VM is deleted: (https://github.com/kubernetes-sigs/cluster-api/blob/6df168faf7be36236dda3ecdb478809d4df1ef79/internal/controllers/machine/machine_controller.go#L379)

Based off timing, it looks like k8s schedules a pod from the replica-set.  
And at the same time the provider successfully deletes the infrastructure VM.

However, when machine controller reconciler goes to run again, it tries to drain the node again (https://github.com/kubernetes-sigs/cluster-api/blob/6df168faf7be36236dda3ecdb478809d4df1ef79/internal/controllers/machine/machine_controller.go#L318).  But, it won't make any progress from here on out because the Pod will be stuck in pending because the physical VM doesn't exist (i'm guessing the k8s node object must still exist).

**What did you expect to happen:**
I would expect CAPI not to try and drain the nodes again.  Or if it does try and drain the nodes, not consider a pod that is pending.  Although each of those solutions comes with a potential side effects.  

**Anything else you would like to add:**
In parallel, i am pursuing why the owner of the replica set has a toleration with no key.  I'm not sure if that is intentional or a bug.
I can't imagine they want to schedule on an unschedulable pod.  But I think CAPI should be able to handle this.

**Environment:**

- Cluster-api version: v0.4.2
- minikube/kind version:
- Kubernetes version: (use `kubectl version`): 1.22.6
- OS (e.g. from `/etc/os-release`): 
NAME="Common Base Linux Mariner"
VERSION="1.0.20220316"
ID=mariner
VERSION_ID="1.0"
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"

/kind bug
area/upgrades

**Comment by pradipd** [comment]
Also, one other bit of information: we are doing a scale in with only 1 worker node.  So, we expect the worker node to be taking down and then a new worker node come up.  I can imagine most people have multiple worker nodes and are doing a scale out.  so they might not see this issue because the replica set can be created on the other worker nodes.

**Comment by enxebre** [comment]
Thanks for reporting @pradipd, could you elaborate on the use case to tolerate unschedulable?

**Comment by pradipd** [comment]
Unfortunately, I can not.  I still haven't found the reason the team has the unschedulable toleration on their replica set.
But, again, i don't think CAPI should be blocking upgrade if a POD is stuck in pending.

**Comment by enxebre** [comment]
The process is as follows:
- We check if a node is drainable e.g. drainTimeout has not been met. If it is drainable:
- We cordon the node.
- We drain - When a [Node is unreachable for too long we skip drain](https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/machine/machine_controller.go#L554-L558).
- We delete infra.
- We delete the Node CR.

As you can see in the workflow above CAPI is not blocking on a pending pod. For such scenario it will continue making progress. Now, the process contract is for Pods to honour the "cordoned" Node (i.e unschedulable) which seems this Pod is intentionally not doing, so it gets reschedule in to the cordoned Node, preventing the process from finishing.

If you can share logs we can validate the above is happening. In that case I'd think this is working as design and for the deletion to finish, cordon (unschedulable) should be honoured. Also If you can share more about the use case we can may be reason about different approaches to solve it.

**Comment by pradipd** [comment]
Sorry for the delay.
@enxebre  thank you for breaking down the process. 
We reached out to the owner (@ganga1980) and they were trying to add tolerations to schedule their deployment on the master node.  My suggestion was to use the specific key (node-role.kubernetes.io/master, node-role.kubernetes.io/control-plane) and not use a wildcard.

**Comment by fabriziopandini** [comment]
/close
reading the comment above it seems the problem has been addressed.

I would prefer to not support pods ignoring cordon taint for the time being, and reconsider only if there is strong demand for it; also, users can set timeouts and force machine deletion if necessary even if pods gets scheduled on nodes while deleting.

But frankly speaking, I think that the right approach/what we should always recommend to users is to honor cordon.
