### ISSUE TITLE
Topology Mutation Hook: Variable discovery

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6901]
**User Story**

As a cluster operator I would like to not be responsible for adding variable definitions used by a Topology Mutation Hook extension manually to a ClusterClass.

(mentioned as future work [here](https://github.com/kubernetes-sigs/cluster-api/blob/8615d34a550052866736b69c55f58198db040dc5/docs/proposals/20220330-topology-mutation-hook.md#clusterclass-author-guide))

**Detailed Description**

Some background information:
* [Topology Mutation Hook CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/8615d34a550052866736b69c55f58198db040dc5/docs/proposals/20220330-topology-mutation-hook.md#L162-L161)
* Today it is necessary to manually ensure that the variables used by a Topology Mutation Hook extension exist in the ClusterClass in which the extension is used
* This means that extension authors should document which variables are used (and their type in OpenAPI Schema v3) and ClusterClass authors have to keep the variables in the ClusterClass in sync with the extension.

It would be nice if the variable definitions would be just automatically discovered from a Topology Mutation Hook extension and "added" to a ClusterClass (details TBD).

**Anything else you would like to add:**

Things to keep in mind:
* The same variables with different types could be defined in multiple extensions and in the ClusterClass directly
* We have to figure out when the variables should be discovered (every reconcile is probably a bit too often)
* variables discovered from extensions should be then treated like every other variable in the ClusterClass (e.g. they should be used for validating/defaulting variables on a Cluster)
* do we discover variables per ClusterClass, per Cluster or per Extension(Config) (I lean towards per ClusterClass)
* we could consider only sending the discovered variables + builtin variables in a GeneratePatches call (and not all variables) to enforce that every extension has to "declare" the variables it uses

/kind feature

**Comment by fabriziopandini** [comment]
This is a super nice improvement, but also tricky to achieve.
I'm happy too pair in discussing a possible way forward

**Comment by fabriziopandini** [comment]
/lifecycle frozen
/assign
I have started collecting some ideas on this topic, I will start moving this to a doc soon

**Comment by fabriziopandini** [comment]
/unassign
/assign @killianmuldoon 
@killianmuldoon please consider if we have to keep this issue or close it now that we are tracking this work also in other umbrella issues

**Comment by killianmuldoon** [comment]
/close

The current state of this issue is [covered in the proposal amendment](https://github.com/kubernetes-sigs/cluster-api/pull/7932), and the implementation issue #7985
