### ISSUE TITLE
Cluster Upgrade stuck due to incorrect kube-proxy image being referred in the pods

### ISSUE THREAD

**Issue by nehagjain15** [kubernetes-sigs/cluster-api#6923]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
We upgraded a classy cluster from 1.21 to 1.22 but the kube-proxy image reference was updated in the daemonset, 
` image: localhost:5000/vmware.io/kube-proxy:v1.22.8_vmware.1`
 but the pod which was scheduled on new node has reference to the old image
` message: Back-off pulling image "localhost:5000/vmware.io/kube-proxy:v1.21.6_vmware.1"`

In another environment, we saw that the daemonset was not updated, and the pod being scheduled on a new node is referencing an old image that does not exist. 

**What did you expect to happen:**
kube-proxy on the new node should have been rolled out with the new image

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
[only_logs.tgz](https://github.com/kubernetes-sigs/cluster-api/files/9114532/only_logs.tgz)

- Cluster-api version:  1.1.3
- minikube/kind version:
- Kubernetes version: (use `kubectl version`): 1.23.5
- OS (e.g. from `/etc/os-release`): photon

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
What does the KCP spec look like?

**Comment by sbueringer** [comment]
I think we simply update the Daemonset at the end. 

We don't rollout kube-proxy in-sync with the invidiual machines.

See: https://github.com/kubernetes-sigs/cluster-api/blob/a0265021fd6af377654f5424e12b069e788b20c2/controlplane/kubeadm/internal/controllers/controller.go#L385-L389

(not sure what the exact moment is, but we definitely just change the image in the one DaemonSet we have once, which means that the kube-proxy image won't be always in sync with the Kubernetes version of the machine)


Note: This behavior did not change with ClusterClass.

**Comment by fabriziopandini** [comment]
/close
due to lack of activity
