### ISSUE TITLE
 Consider dedup lowestNonZeroRetryAfterSeconds

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6945]
During the Runtime SDK implementation we introduced a copy of `lowestNonZeroRetryAfterSeconds`.

Let's consider if we should deduplicate and only have this once as a util.

/kind cleanup
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by LuBingtan** [comment]
I'd like to fix this
/assign
