### ISSUE TITLE
Consider adding constants for field paths of core CAPI resources

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6946]
This is a follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/6289#discussion_r890120475

Goal of this issue is to discuss introducing constants for field paths that we currently hard-code around the code base (e.g. `"spec.infrastructureRef"`).

/kind cleanup
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
What about replacing those constants using the contract package?

**Comment by sbueringer** [comment]
I'm not sure if it's part of the contract. Up until know (afaik) contract covers the contract between core CAPI and bootstrap/infra/control plane providers.

These fields are just the always-constant paths of the fields in our core CRDs. For me it feels like they should rather be part of the clusterv1 apiGroup.
