### ISSUE TITLE
Consider introducing constants for builtin variable paths

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6947]
This is a follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/6289#discussion_r890124352

Goal of this issue is to discuss introducing constants for builtin variable paths that we currently hard-code around the code base (e.g. `"builtin.machineDeployment.topologyName"`).

/kind cleanup
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
(doing some cleanup on old issues without updates)
/close
unfortunately, no one is picking up the task. the thread will remain available for future reference
