### ISSUE TITLE
Issue triaging for `v1.3.x`

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#6950]
**Details**:

This is a pending item on the [Tasks list to prepare `v1.3.x` for development](https://github.com/kubernetes-sigs/cluster-api/issues/6615) to move GitHub issues to the new milestone.

Latest discussion on issue triaging here: https://github.com/kubernetes-sigs/cluster-api/pull/6828

cc @vincepri @sbueringer @CecileRobertMichon @fabriziopandini

**Comment by fabriziopandini** [comment]
It will be great to get to an agreement for https://github.com/kubernetes-sigs/cluster-api/pull/6828 before doing this

**Comment by fabriziopandini** [comment]
/close
we are doing this according to new process introduced by https://github.com/kubernetes-sigs/cluster-api/pull/6828 that aims to eliminate some toil on how do we manage releases
