### ISSUE TITLE
Refactor WatchDeploymentLogs to use label selectors instead of selecting deployments by name.

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/cluster-api#6965]
**User Story**

As a developer I would like to call a function in e2e tests to stream logs of deployments, selected by a label selector, for not requiring to know the exact name of the deployment in the test implementation.

**Detailed Description**

Currently we do already the same but need to know the exact deployment name to do so, example: https://github.com/kubernetes-sigs/cluster-api/pull/6892/files .

**Anything else you would like to add:**

Follow up issue via comment:

> I suggest also opening a follow-up issue so we can search for deployments with a well know label instead of relying on a well-known name. This will make the test helper usable by projects having different extensions names or for use cases where more than one extension is required [[0]](https://github.com/kubernetes-sigs/cluster-api/pull/6892#issuecomment-1181894339)

/kind cleanup

**Comment by adilGhaffarDev** [comment]
I would like to work on it. I am assigning it to myself.
/assign

**Comment by sbueringer** [comment]
/assign @adilGhaffarDev

/remove-help

given we have an open & active PR: https://github.com/kubernetes-sigs/cluster-api/pull/7039
