### ISSUE TITLE
Added ObjectMeta to KubeadmConfigTemplateResource, KubeadmControlPlaneTemplateResource

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#6976]
Following on from https://github.com/kubernetes-sigs/cluster-api/issues/5240 we should probably add ObjectMeta to all of our *TemplateResource types as we did for the Docker infrastructure templates in https://github.com/kubernetes-sigs/cluster-api/pull/5441

There's no clear use case for adding this meta to KubeadmConfigTemplateResource, KubeadmControlPlaneTemplateResource, but there seems to be consensus that this field should be added for consistency.

Related: https://github.com/kubernetes-sigs/cluster-api/issues/5393, https://github.com/kubernetes-sigs/cluster-api/pull/5371

/kind cleanup
/area bootstrap
/area control-plane

**Comment by sbueringer** [comment]
Should we then re-add it also to the documentation as part of this issue?

**Comment by sbueringer** [comment]
Done in #8180

/close
