### ISSUE TITLE
clusterctl topology plan should generate diff files in yaml

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#6985]
**What steps did you take and what happened:**
Run clusterctl topology plan and I noticed that the .diff files represent resources as a go type instead of yaml, e.g. 

```
  &unstructured.Unstructured{
  	Object: map[string]any{
  		"apiVersion": string("controlplane.cluster.x-k8s.io/v1beta1"),
  		"kind":       string("KubeadmControlPlane"),
  		"metadata": map[string]any{
  			"annotations":       map[string]any{"cluster.x-k8s.io/cloned-from-groupkind": string("KubeadmControlPlaneTemplate.controlplane.cluster.x-k8s.io"), "cluster.x-k8s.io/cloned-from-name": string("clusterclass1-controlplane-template")},
  			"creationTimestamp": string("2022-07-26T13:34:57Z"),
  			"finalizers":        []any{string("kubeadm.controlplane.cluster.x-k8s.io")},
- 			"generation":        int64(1),
+ 			"generation":        int64(2),
```

**What did you expect to happen:**
to have a diff in yaml (easier to read)

**Environment:**

- Cluster-api version: main

/kind bug
/area topology
/area clusterctl

**Comment by chrischdi** [comment]
There would be two solutions:

A: Reuse prior art from `kubectl` / `kubectl diff`:
* This would lead to using and executing the `diff` binary or to be more specific `diff -u -N`, which could get overwritten by the env var `KUBECTL_EXTERNAL_DIFF`
* The output would be as follows:
  ```
  ❯ cat ./out/modified/MachineDeployment_default_capi-quickstart-md-0-djlql.diff
  --- out/modified/MachineDeployment_default_capi-quickstart-md-0-djlql.original.yaml     2022-07-27 18:52:24.000000000 +0200
  +++ out/modified/MachineDeployment_default_capi-quickstart-md-0-djlql.modified.yaml     2022-07-27 18:52:24.000000000 +0200
  @@ -73,13 +73,13 @@
      kind: Cluster
      name: capi-quickstart
      uid: 29e69ad2-e93f-45fe-bda0-06b0c7ed97b2
  -  resourceVersion: "2116"
  +  resourceVersion: "2"
    uid: aff0a885-dd95-4a64-8fee-c188b64bb4e4
  spec:
    clusterName: capi-quickstart
    minReadySeconds: 0
    progressDeadlineSeconds: 600
  -  replicas: 3
  +  replicas: 2
    revisionHistoryLimit: 1
    selector:
      matchLabels:
  ```
  
B: use the package `github.com/pmezard/go-difflib/difflib` (which is already an indirect dependency)

* This would not make use of an external binary
* The output would be as follows:
  ```
  ❯ cat out/modified/MachineDeployment_default_capi-quickstart-md-0-djlql.diff
  --- out/modified/MachineDeployment_default_capi-quickstart-md-0-djlql.original.yaml
  +++ out/modified/MachineDeployment_default_capi-quickstart-md-0-djlql.modified.yaml
  @@ -76 +76 @@
  -  resourceVersion: "2116"
  +  resourceVersion: "2"
  @@ -82 +82 @@
  -  replicas: 3
  +  replicas: 2
  ```

Comparing the two, the main difference is the lack of printing the unchanged lines pre-post change but I think using the library may lead to less issues? WDYT?

**Comment by fabriziopandini** [comment]
I think we can get this by refactoring a little bit the current code, so we convert object to yaml first and then we use the gernerated yaml to both create the files and compute the diff (now generating yaml is nested into create files)

**Comment by chrischdi** [comment]
> ```
>   &unstructured.Unstructured{
>   	Object: map[string]any{
>   		"apiVersion": string("controlplane.cluster.x-k8s.io/v1beta1"),
>   		"kind":       string("KubeadmControlPlane"),
>   		"metadata": map[string]any{
>   			"annotations":       map[string]any{"cluster.x-k8s.io/cloned-from-groupkind": string("KubeadmControlPlaneTemplate.controlplane.cluster.x-k8s.io"), "cluster.x-k8s.io/cloned-from-name": string("clusterclass1-controlplane-template")},
>   			"creationTimestamp": string("2022-07-26T13:34:57Z"),
>   			"finalizers":        []any{string("kubeadm.controlplane.cluster.x-k8s.io")},
> - 			"generation":        int64(1),
> + 			"generation":        int64(2),
> ```

Generating the yaml is easily refactored and would drop the os.ReadFile 👍 

Still opens the question what to use for generating the actual `.diff` file. The used `cmp` library is not able to provide a proper diff for strings.
