### ISSUE TITLE
Labels and annotations for MachineDeployments and KubeadmControlPlane created by topology controller

### ISSUE THREAD

**Issue by MaxFedotov** [kubernetes-sigs/cluster-api#7006]
**User Story**

As a user I would like to specify labels and annotations for `MachineDeployment` and `KubeadmControlPlane` created by topology controller to be used used by `cluster-autoscaler` or for filtering.

**Detailed Description**

It is possible to specify `labels` and `annotations` in cluster topology spec, but they are propagated only to `machines` created by `MachineDeployment` and `KubeadmControlPlane`. 

As documented in `cluster-autoscaler` [readme](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/README.md#autoscaling-with-clusterclass-and-managed-topologies), in order to use it with Managed Topology, users had to skip `spec.topology.workers.machineDeployments[].replicas` field, which cause topology controller to always create `MachineDeployment` with only one replica. Users can later add specific `cluster-autoscaler` annotations in order to increase number of replicas. 
And as this annotations cannot be added to `MachineDeployment` during provisioning, it is impossible to create them with any other number of replicas other then one.

It will be nice to have a way to pass labels and annotation from `Cluster` topology spec to `MachineDeployment` and `KubeadmControlPlane` and also be able to update them without triggering rollout for corresponding `Machines`

/kind feature

**Comment by fabriziopandini** [comment]
/area topology
@vincepri another possible improvement for cluster.spec.topolgy and/or ClusterClass

**Comment by enxebre** [comment]
Is there any other use cases we can think of for labels/annotations? e.g Syncing from [class to Nodes](https://github.com/kubernetes-sigs/cluster-api/pull/6255).
For autoscaling in particular I'd expect this to be baked in MachineDeploymentClass API eventually e.g `.autoscaling {min: , max: }`

**Comment by fabriziopandini** [comment]
Syncing from classes to a node can happen for free if we use existing metadata fields, otherwise, if we add a new field for node labels it should be surfaced in CC as well

**Comment by fabriziopandini** [comment]
/triage accepted

As discussed in the Aug 5th issue triage meeting we should evaluate options:
- Propagate existing metadata both to MD/KCP and Machines (to be verified if this as undesirable side effects)
- Add new metadata fields for MD/KCP objects, TBD UX

**Comment by MaxFedotov** [comment]
>Propagate existing metadata both to MD/KCP and Machines (to be verified if this as undesirable side effects)

One side effect would be that any update of labels\annotations (e.g. for autoscaler) will cause Machine rollout

**Comment by jackfrancis** [comment]
Related discussion about node annotations not propagating via Machine update: https://github.com/kubernetes-sigs/cluster-api/pull/6255

**Comment by jackfrancis** [comment]
Also related: https://github.com/kubernetes-sigs/cluster-api/issues/5880

**Comment by MaxFedotov** [comment]
After the discussion during Cluster API meeting it was proposed to separate this into two different issues:
1. Propagate labels and annotations from `ClusterClass` and `Cluster.spec.topology` not only to `Machines`, but also to `MD` and `KCP`
2. Prevent triggering of `Machine` rollout when labels or annotations in `MachineDeployment.spec.template.metadata` or `KubeadmControlPlane.spec.machineTemplate.metadata` are updated (can be done as a part of #5880 or #6255)

**Comment by sbueringer** [comment]
Just to provide an update. We included this in this proposal: https://github.com/kubernetes-sigs/cluster-api/pull/7331

**Comment by fabriziopandini** [comment]
@sbueringer  @ykakarap should this issue be closed due to https://github.com/kubernetes-sigs/cluster-api/pull/7917 being merged?

**Comment by sbueringer** [comment]
I think yes.

**Comment by sbueringer** [comment]
>  also be able to update them without triggering rollout for corresponding Machines

That's not solved yet, but we have another issue for it

**Comment by fabriziopandini** [comment]
/close
as per comments above
