### ISSUE TITLE
Version validation according Kubernetes Version Skew Policy

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/cluster-api#7011]
**User Story**

As a operator I would like to ensure that creating/updating a Cluster/KubeadmControlPlane/MachineDeployment/MachineSet/Machine does not violate the [Kubernetes Version Skew Policy] for staying in supported upgrade paths and not break running applications.

**Detailed Description**

This issue proposes to add additional validation against the [Kubernetes Version Skew Policy].

Assuming version v1.X is the desired kubernetes version:

* For a KubeadmControlPlane or a ControlPlane Machine:
    * > [...] the newest and oldest `kube-apiserver` instances must be within one minor version.
* For a MachineDeployment, MachineSet or workload Machine
    * > [...] must not be newer than `kube-apiserver`, and may be up to two minor versions older.

To-be-discussed:

* Should the Kubernetes Version Skew Policy validations only get implemented for ClusterClass based Clusters / Validation on `Cluster.spec.topology.version`?
    * An arguments for that is: on ClusterClass based Clusters the topology and relations are well-defined with a top-down approach.

**Anything else you would like to add:**

* There is already version validation at the ClusterClass based clusters (via `.spec.topology.version`). [xref](https://github.com/kubernetes-sigs/cluster-api/blob/a087b0214b77fff36428c7ac513f4d02272f1f4f/internal/webhooks/cluster.go#L309)
    * The current implementation does not allow to downgrade patch versions, which would be allowed from the Kubernetes Version Skew policy side.

* Kubeadm also does [validation against the Kubernetes Version Skew Policy](https://github.com/kubernetes/kubernetes/blob/e234917e0a3e4bb384ef14c198742643a7e170fd/cmd/kubeadm/app/phases/upgrade/policy.go), but this may not map to the current documentation at [Kubernetes Version Skew Policy].

/kind feature

**Comment by neolit123** [comment]
> Kubeadm also does [validation against the Kubernetes Version Skew Policy](https://github.com/kubernetes/kubernetes/blob/e234917e0a3e4bb384ef14c198742643a7e170fd/cmd/kubeadm/app/phases/upgrade/policy.go), but this may not map to the current documentation at [Kubernetes Version Skew Policy].

the supported skew in kubeadm is documented here
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#version-skew-policy

**Comment by killianmuldoon** [comment]
I think there's a lot of overlap with this issue #7010  and existing issues e.g. https://github.com/kubernetes-sigs/cluster-api/issues/4321, https://github.com/kubernetes-sigs/cluster-api/issues/6614, https://github.com/kubernetes-sigs/cluster-api/issues/6040 - there might be more. 

It would be good to ensure that the older issues are all covered by the newer ones, close the older ones and continue the conversation on these more holistic issues.

**Comment by chrischdi** [comment]
I agree for #6040 regarding this issue.

#4321 and #6614 are more related to #7010

**Comment by fabriziopandini** [comment]
Thanks for looking for duplicates; I have consolidated everything in https://github.com/kubernetes-sigs/cluster-api/issues/7010 and in this issue

**Comment by sbueringer** [comment]
Q: Should the validation only consider the spec.version or should it also consider the current status?

E.g. if we only validate the spec it's possible to bump the version to minor versions before the rollout is finished.

**Comment by chrischdi** [comment]
> Q: Should the validation only consider the spec.version or should it also consider the current status?
> 
> E.g. if we only validate the spec it's possible to bump the version two minor versions before the rollout is finished.

Maybe yes, maybe no, also related here: #6651 .

**Comment by sbueringer** [comment]
Do we already have a clear idea what exactly we want to implement and where?

**Comment by fabriziopandini** [comment]
+1 to nail down some details first
@ramineni is it ok for your to some comments here as soon as you make up your mind around this topic/before starting implementation?

**Comment by ramineni** [comment]
> Do we have a clear idea what exactly we want to implement and where? (just asking, because it would be good to have consensus on that before we go back and forth on an implementation)

Have not gone that much far, just started to explore the details . I'll sure discuss here or in slack before going for implementation.

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

We mitigated the issue with machine set preflight checks and we highly reccommend users to turn them on.
/close
