### ISSUE TITLE
Holistic nil checking in public functions

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#7041]
Fuzzing through OSS-Fuzz has shown a number of previously unchecked nil-pointer errors in Cluster API code e.g.:
- https://github.com/kubernetes-sigs/cluster-api/pull/6334, https://github.com/kubernetes-sigs/cluster-api/pull/7040, 

There's likely to be a few other places where consumers of Cluster API's public functions could unknowingly cause a nil-pointer if not checking for nil in all parameters (and receivers potentially) before calling the function.

In most cases this is a non-issue as the nil conditions may not be possible outside of artificial cases like fuzzing, but there may be some edge-case crashes that could be prevented by improving handling of nils in public functions.

This could be resolved in a holistic way by going through CAPI public functions and checking if each parameter is nil. A helper function could be used to do this in some cases, but the expected behaviour of nil may be different depending on the function and parameter type e.g. options variadics should not return an error if nil.

If a holistic fix isn't an option there should be documentation/communication to consumers of Cluster API as a library that nil checking should be done before calling functions. 

This issue was previously discussed here: https://github.com/kubernetes-sigs/cluster-api/pull/6334#issuecomment-1084602280

/kind cleanup

**Comment by fabriziopandini** [comment]
@killianmuldoon is there a way to break down this work in small actionable chuck, so we can start tackling this progressively, and possibly spread the work across many contributors?

**Comment by killianmuldoon** [comment]
I'll update this issue with instructions on how to do this across packages, starting with a small group of packages that are regularly used outside CAPI.

**Comment by killianmuldoon** [comment]
/assign

(At least to follow up and create a more detailed task breakdown)

**Comment by killianmuldoon** [comment]
/remove-lifecycle rotten

Still got this on my to-do list :slightly_frowning_face:

**Comment by killianmuldoon** [comment]
/close

I've not gotten to this, and it hasn't picked up much traction.
