### ISSUE TITLE
bad architecture metadata in k8s.gcr.io images

### ISSUE THREAD

**Issue by 24sama** [kubernetes-sigs/cluster-api#7055]
**What steps did you take and what happened:**
The arch metadata in the `k8s.gcr.io/cluster-api/xxx` are incorrect.
For example:
```
$ docker pull --platform linux/arm64/v8 k8s.gcr.io/cluster-api/cluster-api-controller:v1.2.0
$ docker inspect k8s.gcr.io/cluster-api/cluster-api-controller:v1.2.0 | grep Arch                                                                                                                                        
        "Architecture": "amd64",

$ docker pull --platform linux/ppc64le k8s.gcr.io/cluster-api/cluster-api-controller:v1.2.0
$ docker inspect k8s.gcr.io/cluster-api/cluster-api-controller:v1.2.0 | grep Arch                                                                                                                                            
        "Architecture": "amd64",
```
The other images are correct:
```
$ docker pull --platform linux/arm64/v8 k8s.gcr.io/pause:3.7
$ docker inspect k8s.gcr.io/pause:3.7 | grep Arch                                                                                                                                                                            
        "Architecture": "arm64",
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v1.2.0
- minikube/kind version: 
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by 24sama** [comment]
Has anyone encountered this problem?

**Comment by chrischdi** [comment]
Interesting finding.

This comes from https://github.com/kubernetes-sigs/cluster-api/blob/9663ed6ab6dedfc7a343430976d4442c6aae4395/Dockerfile#L63 which then will use the platform it is building on.

We already have the ARCH `build-arg` which could get used to define `--platform` in the `FROM` line which fixes this.

I will create a PR shortly :-)
