### ISSUE TITLE
Support manage existing K8s cluster control plane.

### ISSUE THREAD

**Issue by k82cn** [kubernetes-sigs/cluster-api#7059]
**User Story**

We're going to deploy/manage k8s master by another k8s cluster (e.g. bootstrap cluster), and ask provisioned Machine to join this k8s cluster. In this way, we're going to deploy/manage k8s master as service, and leverage providers in cluster-api community to manage worker nodes, e.g. aws, gke, metal3 and so on.

**Detailed Description**

As the k8s master are deployed by another bootstrap k8s, control-plane-kubeadm is unnecessary. Prefer to provide api endpoint and kubeconf/secret for worker nodes to join.

**Anything else you would like to add:**

None

/kind feature

**Comment by k82cn** [comment]
If no discussion on this scenario, I'd like to contribute for that :)

**Comment by killianmuldoon** [comment]
I'm no sure I fully understand the use case here - or what the limitations in CAPI are that might be getting in the way. It sounds like this may require some sort of custom control plane provider.

Have you looked at https://github.com/kubernetes-sigs/cluster-api/pull/6988? It outlines a proposal for managed Kubernetes in CAPI and may be aligned with this ask.

**Comment by k82cn** [comment]
> Have you looked at https://github.com/kubernetes-sigs/cluster-api/pull/6988? It outlines a proposal for managed Kubernetes in CAPI and may be aligned with this ask.

Just went through the doc, that's what I want. I'd like to manage control plane myself (e.g. by bootstrap k8s), which seems no align CAPI's design. That's great to have such a discussion in community :)
