### ISSUE TITLE
Empty Files array in KubeadmConfigTemplate is deleted since CAPI v1.2

### ISSUE THREAD

**Issue by apricote** [kubernetes-sigs/cluster-api#7067]
**What steps did you take and what happened:**

- Setup local kind cluster
- `clusterctl init` with CAPI v1.2.1
- Create `KubeadmConfigTemplate` with `spec.template.spec.files: []`
- `kubectl get -o yaml` the created object and observer that the field `files` was removed from `spec.template.spec`.

**What did you expect to happen:**

I expected the empty files array to persist in the resource, as this was the behaviour in Cluster API v1.1

**Anything else you would like to add:**

This causes issues with `ClusterClass` for us, as we have a patch targeting the field. To make the patch easier for us (and to prevent some potential future bugs) we set the `kubeadmConfigTemplate.spec.template.spec.files` to an empty array, and then in the patch we `add` a new element to this empty array.

This worked in Cluster API v1.1, but in Cluster API v1.2 the topology controller complains that the patch can not be applied, because the path does not exist.

I wrote a script to reproduce the issue, demonstrating that it worked with v1.1.5 and does not work with v1.2.1:

<details>
<summary>Repro script</summary>

Requirements:

- bash
- kind
- clusterctl
- kubectl
- (docker)

```shell
set -e -o pipefail

K8S_VERSION=v1.24.3

init_kind_cluster() {
  NAME=$1
  K8S_VERSION=$2
  CAPI_VERSION=$3

  echo "Initializing new kind cluster '${NAME}' (version=${K8S_VERSION}) with Cluster API (version=${CAPI_VERSION})"

  kind create cluster \
    --name ${NAME} \
    --image kindest/node:${K8S_VERSION} \
    > /dev/null 2>&1

  # install capi components
  clusterctl init \
    --core cluster-api:${CAPI_VERSION} \
    -b kubeadm:${CAPI_VERSION} \
    -c kubeadm:${CAPI_VERSION} \
    -i docker:${CAPI_VERSION} \
    > /dev/null 2>&1
    
  # make sure that webhook is available
  kubectl wait \
    --namespace=capi-kubeadm-bootstrap-system \
    --for=condition=Available \
    --all=true \
    --timeout=2m \
    deployment \
    > /dev/null 2>&1

  echo "Cluster '${NAME}' initialized"
}

cleanup_kind_cluster() {
  NAME=$1
  echo "Deleting kind cluster '${NAME}'"
  kind delete cluster --name $NAME > /dev/null 2>&1
  echo "Cluster '${NAME}' deleted"
}

verify_files() {
  cat <<EOF | kubectl apply -f - > /dev/null 2>&1
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: md-0
spec:
  template:
    spec:
      files: []
EOF

  kubectl get kubeadmconfigtemplate md-0 -o jsonpath="{.spec.template.spec.files}"
}

testcase() {
  NAME=$1
  K8S_VERSION=$2
  CAPI_VERSION=$3

  init_kind_cluster ${NAME} ${K8S_VERSION} ${CAPI_VERSION}

  RESULT_RAW=$(verify_files)
  RESULT=""
  EXPECTED="[]"
  if [[ "${RESULT_RAW}" == "${EXPECTED}" ]]; then
    RESULT="PASS"
  else
    RESULT="FAIL"
  fi

  cleanup_kind_cluster ${NAME}

  echo "## TestCase=${NAME} CAPI Version=${CAPI_VERSION} Result=${RESULT} (expected=${EXPECTED} but got=${RESULT_RAW})"
}

testcase files-capi11 ${K8S_VERSION} v1.1.5
testcase files-capi12 ${K8S_VERSION} v1.2.1
```

Output for me:

```
Initializing new kind cluster 'files-capi11' (version=v1.24.3) with Cluster API (version=v1.1.5)
Cluster 'files-capi11' initialized
Deleting kind cluster 'files-capi11'
Cluster 'files-capi11' deleted
## TestCase=files-capi11 CAPI Version=v1.1.5 Result=PASS (expected=[] but got=[])
Initializing new kind cluster 'files-capi12' (version=v1.24.3) with Cluster API (version=v1.2.1)
Cluster 'files-capi12' initialized
Deleting kind cluster 'files-capi12'
Cluster 'files-capi12' deleted
## TestCase=files-capi12 CAPI Version=v1.2.1 Result=FAIL (expected=[] but got=)
```

</details>

**Environment:**

- Cluster-api version: v1.2.1
- minikube/kind version: v0.14.0
- Kubernetes version: (use `kubectl version`): v1.24.3
- OS (e.g. from `/etc/os-release`): Arch Linux

/kind bug
/area api
/area upgrades

**Comment by killianmuldoon** [comment]
It looks like this is a combination of the way Server Side Apply - introduced in 1.2.x -  treats an empty map and the way json patch add operations work. This is expected behaviour from both of those specs, so I don't know if there's a simple way to fix it. 

Would it be possible to do add the whole array instead of a single entry in the patch?

**Comment by apricote** [comment]
> Would it be possible to do add the whole array instead of a single entry in the patch?

It is possible, but inconvenient. In case we ever want to add some files to the `KubeadmConfigTemplate` (not through patches) we would need to remember to change the patch back to only add the item, or risk overwriting the full array.

**Comment by chrischdi** [comment]
> I'm trying to reproduce. What confuses me at a first glance is that in those two steps ClusterAPI isn't really involved.
> 
> * Create KubeadmConfigTemplate with spec.template.spec.files: []
> * kubectl get -o yaml the created object and observer that the field files was removed from spec.template.spec.
> 
> We have a defaulting webhook on KubeadmConfigTemplate but that wasn't changed at all.

The defaulting webhook was not part of v1.1.5, it was introduced in v1.2 ( https://github.com/kubernetes-sigs/cluster-api/commit/6ae0a733deb363145aaca91d583d7452f99b8b07 ). Removing it reverts the behaviour (`kubectl edit crd kubeadmconfigtemplate`).

**Comment by sbueringer** [comment]
That explains it. I wasn't aware that the webhook was added after v1.1.x.

Then the issue is essentially that while the webhook doesn't modify the field intentionally it runs through Unmarshal/Marshal, and because of `omitempty` the field gets lost in JSON:
```go
	// +optional
	Files []File `json:"files,omitempty"`
```

**Comment by sbueringer** [comment]
I don't think we can/should drop the webhook again and especially we can't guarantee that we won't introduce a webhook again in the future even if we drop it now.

One other workaround could to be to add an array with a dummy file instead of an empty array. It's super hacky but not sure if there are any better alternatives.

**Comment by chrischdi** [comment]
To get back to workarounds / other solutions: another solution would be to implement the patch as a [topology mutation hook](https://main.cluster-api.sigs.k8s.io/tasks/experimental-features/runtime-sdk/implement-topology-mutation-hook.html) instead of using a json patch.

**Comment by apricote** [comment]
Thanks for your response and suggestions. I will evaluate this internally tomorrow and pick one of the provided workarounds.

As this Work as intented™, we can close the issue IMO.

**Comment by sbueringer** [comment]
I think unfortunately it is. It's bad that webhooks have this kind of side effect but I think there's not much we can do. Fortunately we already have webhooks for almost all resources so there shouldn't be more changes like this in the future.

**Comment by apricote** [comment]
We decided to just add the full array in the patch with a warning about future modifications.

/close
