### ISSUE TITLE
Remove script-based mdbook install

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#7076]
We currently have a third party folder with just a single tool - the rust crate installer from https://github.com/japaric/trust which is used to install mdbook.

It appears the repo this script was cloned from is now abandoned. The last commit is from 2019, and the latest issue (open since March) asks if the repo is abandoned and currently has no response.

We should remove this tool and, if wanted, we could replace it with our own ensure-mdbook script to download binary releases from the github release page. We could also provide alternative instructions to let users developing with the book install mdbook as they prefer e.g. it's available through homebrew on Mac.

In doing so we will be able to get rid of the third_party folder from Cluster API.

/kind cleanup

**Comment by sbueringer** [comment]
I think it is used by netlify as well (see netfliy.toml). So documentation for manual installation won't work.
