### ISSUE TITLE
Add control plane dev guidance with kubeadm bootstrap

### ISSUE THREAD

**Issue by k82cn** [kubernetes-sigs/cluster-api#7089]
**What steps did you take and what happened:**

When creating a customized control plane at https://github.com/openbce/kink , I got the following error; and it seems no dev document on how to build a customized control plane to work with kubeadm bootstrap. As my project only focus on control plane part, and I'd like to work with other provider on data plane part.

```
E0818 14:10:34.488613       1 controller.go:326] "Reconciler error" err="missing certificate" controller="kubeadmconfig" controllerGroup="bootstrap.cluster.x-k8s.io" controllerKind="KubeadmConfig" kubeadmConfig="my-example/my-cluster-workers-2j7dm" namespace="my-example" name="my-cluster-workers-2j7dm" reconcileID=38526c91-9cc1-410c-badf-23347ae23763
```

**What did you expect to happen:**

Have a dev doc on how to build a customized control plane to work with kubeadm bootstrap.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- minikube/kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
+1
That's an interesting use case, it will be great if you can improve our docs after your work! 
However, at the same time we should also point out that how CABPK works today is not really a contract someone else can rely on; in fact we have E2E tests ensuring that CABPK and KCP properly create/manage workload clusters, but not how. 

/triage accepted

**Comment by k82cn** [comment]
sure, let me update the doc accordingly based on my work :)

**Comment by fabriziopandini** [comment]
@k82cn do you still want to document your learnings about implementing a new control plane controller that relies with CABPK?
