### ISSUE TITLE
v1beta1#ClusterStatus: some fields are missing ",omitempty"

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/cluster-api#7096]
Hello, it appears most fields in `ClusterStatus` type have omitempty json tag. https://pkg.go.dev/sigs.k8s.io/cluster-api/api/v1beta1#ClusterStatus except for `ControlPlaneReady` and `InfrastructureReady`.

This prevents us from zeroing the `.Status` field on `ClusterObject` (which also has `,omitempty`) and have a clean json result. https://pkg.go.dev/sigs.k8s.io/cluster-api/api/v1beta1#Cluster

Is this intentional?
/kind support
/area api
cc: @reetasingh

**Comment by killianmuldoon** [comment]
I'll leave it up to others to say whether this is intentional, but out of curiosity what's the use case for zeroing the entire `Status`?

**Comment by sbueringer** [comment]
I'm not sure why those fields don't have `omitempty`.

The only reason I can come up with is that we wanted to have those fields always visible to signal to users the current state of things (vs. having those fields "vanish" from the JSON output when the flags are false). But I think this is only the behavior because the fields are not pointers (but I don't know why they are not pointers).

But just a wild guess.

**Comment by ahmetb** [comment]
> , but out of curiosity what's the use case for zeroing the entire `Status`?

I'm trying to store these objects as JSON in another medium and I don't need their .Status field. I understand most others probably aren't trying to do this.

> I'm not sure why those fields don't have `omitempty`.

I've read the section on optionals vs requied a bit: https://github.com/kubernetes/community/blob/a329a26b1551046a0a48a0ef22d69739b3141933/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required and it is not prescriptive in terms of the `Status` fields (in `Spec` fields, `omitempty` implies an "optional" property on fields).

It's not a big deal, but I thought this part might be an oversight in case the API types are hand-written.

**Comment by fabriziopandini** [comment]
/triage needs-information

I'm struggling a little bit with the use case behind the request of zeroing status for storing data on another media, since there are other ways to strip data out of an object when being serialized.

However, taking a step back, according to https://cluster-api.sigs.k8s.io/contributing#api-conventions status field must be optional and optional field must include omitempty, so it seems a fix that we have to do
@sbueringer opinions?

**Comment by ahmetb** [comment]
Right, I could probably use various libraries to craft a YAML representation from a Go struct and manually delete certain nodes from the YAML document.

I only wanted to point out that the fact that there doesn't seem like a good reason for `Status` field to not have `,omitempty`. In general, many other Kubernetes builtin APIs have it (Namespace, ReplicaSet, Deployment, PersistentVolume...) so I'm assuming it's in general a good idea to make it omittable.

**Comment by sbueringer** [comment]
/assign

@fabriziopandini Sounds good to me. I've opened https://github.com/kubernetes-sigs/cluster-api/pull/7816 to address it.

I think our policy was slightly off. `omitempty` should not be used on **all** optional fields only "in most cases"

> In most cases, optional fields should also have the omitempty struct tag (the omitempty option specifies that the field should be omitted from the json encoding if the field has an empty value). However, If you want to have different logic for an optional field which is not provided vs. provided with empty values, do not use omitempty (e.g. https://github.com/kubernetes/kubernetes/issues/34641).
> https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md

Updated our policy in the PR as well

**Comment by sbueringer** [comment]
While implementing the PR and triaging an independent issue we found the following reasons:

> Is [adding omitempty] actually a wanted change? Seeing `ControlPlaneReady: false` in a kubectl get would probably give more signal to new users that don't know this field exist, or for existing users that are watching for changes and need to understand what's the state of things.
> @vincepri https://github.com/kubernetes-sigs/cluster-api/pull/7816/files#r1066315046

I was changing this for a couple of fields and then I realized that a lot of them are part of our contract. There could be implementations (like our topology controller) who explicitly check if the field has a certain value or hasn't been set yet.
I think we could break some of those consumers if we add `omitempty`.

xref: https://github.com/kubernetes-sigs/cluster-api/pull/7816/files#r1065737593 https://github.com/kubernetes-sigs/cluster-api/blob/c4644cdb247f38f12663b99812add43dec4423ba/internal/contract/controlplane.go#L218-L221

Just an example, but it should show the problems we (and our consumers) could run into if we start omitting false / 0 values.

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

There are no API conventions requiring to have omitempty on all the status fields; also this can lead to issues, see https://github.com/kubernetes-sigs/cluster-api/issues/7096#issuecomment-1383833097

Given that I'm closing; we can eventually reconsider if strong reason pop out

/close
