### ISSUE TITLE
Tilt no longer appears to install cert-manager and fails to start up

### ISSUE THREAD

**Issue by Skarlso** [kubernetes-sigs/cluster-api#7100]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

Run `tilt up` on a clean kind cluster.

**What did you expect to happen:**

Error:

```
Build Failed: kubernetes apply: error mapping cert-manager.io/Certificate: no matches for kind "Certificate" in version "cert-manager.io/v1"
```

I have nothing else. It worked a couple commits ago...

This issue can be worked around if I run `clusterctl init --provider aws`. That installs cert-manager and things work from there on.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 1.2.1
- minikube/kind version: v0.11.1
- Kubernetes version: (use `kubectl version`): 1.22
- OS (e.g. from `/etc/os-release`): OSX

**Tilt setting:**

```json
{
    "enable_providers": [
      "kubeadm-bootstrap",
      "kubeadm-control-plane",
      "aws"
    ],
    "default_registry": "docker.io/skarlso/capa",
    "provider_repos": [
      "/Users/skarlso/goprojects/capa/cluster-api-provider-aws"
    ],
    "kustomize_substitutions": {
      "EXP_CLUSTER_RESOURCE_SET": "true",
      "EXP_MACHINE_POOL": "true",
      "AWS_B64ENCODED_CREDENTIALS": "cred==",
      "EXP_EKS_FARGATE": "false",
      "CAPA_EKS_IAM": "false",
      "CAPA_EKS_ADD_ROLES": "false",
      "EXP_BOOTSTRAP_FORMAT_IGNITION": "true"
    },
    "extra_args": {
      "aws": ["--v=2"]
    }
}

```

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by Skarlso** [comment]
This is the offending PR: https://github.com/kubernetes-sigs/cluster-api/pull/6483/files

Aaaa... And here and now I see this OFC:

```
   "deploy_cert_manager": true,
```

Ok, this fixed my issue.

**Comment by sbueringer** [comment]
Agree. Looks like #6483 changed the default behavior.

I'll open a PR to change that back.

/reopen

**Comment by Skarlso** [comment]
Ah yes. :) Thanks! :)) 👍

**Comment by Skarlso** [comment]
Thank you! :)
