### ISSUE TITLE
bootstrap can not connect to customized controlplane because "it doesn't contain any IP SANs"

### ISSUE THREAD

**Issue by k82cn** [kubernetes-sigs/cluster-api#7101]
**What steps did you take and what happened:**

When building github.com/openbce/kink , I used `secret.NewCertificatesForInitialControlPlane` & `certifications.LookupOrGenerate` to generate all CAs & kubeconfig. I can start apiserver pod and etcd pod, the status of control plane were also updated accordingly; but kubeadm-bootstrap reported following error:

```
E0821 13:38:12.054845       1 controller.go:326] "Reconciler error" err="failed to create client for Cluster my-example/my-cluster: Get \"https://10.209.22.18:6443/api?timeout=10s\": x509: cannot validate certificate for 10.209.22.18 because it doesn't contain any IP SANs" controller="kubeadmconfig" controllerGroup="bootstrap.cluster.x-k8s.io" controllerKind="KubeadmConfig" kubeadmConfig="my-example/my-cluster-workers-wklj7" namespace="my-example" name="my-cluster-workers-wklj7" reconcileID=27aa3a38-ea6d-44da-a89c-3ca396c75f8e
```

Is there any suggestion on how to fix that? Is there anything I missed?

xref: control plane source code: https://github.com/openbce/kink/blob/main/controllers/controlplane/kinkcontrolplane_controller.go

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- minikube/kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by k82cn** [comment]
Just check the ca.crt in the cluster, it seems no subject alternative name in it. But how does kubeadm control plane make it to work? Does it refresh `clusterName-ca` after `kubeadm init`?

**Comment by sbueringer** [comment]
The ca.crt is not used as serving certificate for the apiserver. Usually kubeadm takes the CA and generates a certificate for the apiserver (and includes IP SANS). Not sure about what it exactly includes, I only know that it includes at least the SANs we configure e.g. here: https://github.com/kubernetes-sigs/cluster-api/blob/main/test/infrastructure/docker/examples/simple-cluster.yaml#L48-L51

**Comment by k82cn** [comment]
> Usually kubeadm takes the CA and generates a certificate for the apiserver (and includes IP SANS). 

Got that. In this case, I need to re-generate related certs for the components of masters.
BTW, what's the purpose of those certs without IP SANs? I found that the kubeconfig.controlplane also generate such kind of certs.

**Comment by chrischdi** [comment]
I think the ones without SANS are mostly client certificates, thats at least what I read from the table at https://kubernetes.io/docs/setup/best-practices/certificates/#all-certificates :-)

**Comment by k82cn** [comment]
Thanks very much for your input; but is there any document/suggestion on how those secret and configmap are used by kubeadmconfig.bootstrap controller? I think it's necessary to generate those secrets by my customized control plane.

```
[klausm@host24 bmm]$ kc get secret -n my-example
NAME                     TYPE                      DATA   AGE
my-cluster-ca            cluster.x-k8s.io/secret   2      27s
my-cluster-etcd          cluster.x-k8s.io/secret   2      27s
my-cluster-kubeconfig    cluster.x-k8s.io/secret   1      26s
my-cluster-proxy         cluster.x-k8s.io/secret   2      27s
my-cluster-sa            cluster.x-k8s.io/secret   2      27s
[klausm@host24 bmm]$ kc get configmap -n my-example
NAME               DATA   AGE
kube-root-ca.crt   1      42s
```

**Comment by chrischdi** [comment]
I think there is no perfect doc or documentation which is able to give you the direct answer.

https://main.cluster-api.sigs.k8s.io/developer/providers/bootstrap.html?highlight=bootstrap#behavior gives some sort of an overview but the details are in the code, maybe especially at the functions like here: 

* for `joinWorker` https://github.com/kubernetes-sigs/cluster-api/blob/24b1369f84ae9d9f2c63f184238d1784a8d5fdd0/bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go#L500

**Comment by k82cn** [comment]
I made that work to launch k8s master (only kube-apiserver and etcd for now) right now.

xref : https://github.com/openbce/kink/tree/main/controllers/controlplane/secrets

**Comment by fabriziopandini** [comment]
/remove-kind bug
/kind support
/triage accepted

/close
Given that it seems the problem has been solved
