### ISSUE TITLE
Netlify: DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.

### ISSUE THREAD

**Issue by oscr** [kubernetes-sigs/cluster-api#7109]
When working on a pr I noticed the following warning banner in Netlify:

```
DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.

The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
All Netlify builds using the Xenial build image will begin failing in the week of November 15th, 2022.

To avoid service disruption, please select a newer build image at the following link:
https://app.netlify.com/sites/kubernetes-sigs-cluster-api/settings/deploys#build-image-selection

For more details, visit the build image migration guide:
https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239
```

Source: https://app.netlify.com/sites/kubernetes-sigs-cluster-api/deploys/63049e1485be5d000807181f

**Comment by killianmuldoon** [comment]
I think we need someone with netlify access to update this image.
 @CecileRobertMichon do you have the ability to change the image used? [The details are here](https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239).

**Comment by CecileRobertMichon** [comment]
Updated the image following instructions in Netlify settings an triggered a re-deploy, everything looks good: https://app.netlify.com/sites/kubernetes-sigs-cluster-api/deploys/6305086b63dd2c07e9bd53a1

```
10:03:39 AM: Build ready to start
10:03:40 AM: build-image version: d7b3dbfb0846505993c9a131894d1858074c90b4 (focal)
```

/close
