### ISSUE TITLE
Disable deprecated linters - structcheck, deadcode, varcheck, ifshort

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#7115]
The following linters are deprecated in golangci-lint but we're still using them in our config:

- structcheck - Finds unused struct fields
- deadcode - Finds unused code
- varcheck - Finds unused global variables and constants
- ifshort - Go linter that checks if your code uses short syntax for if-statements whenever possible.

We should remove these linters at some point as they're no longer mantained, but is there a strong reason to keep any of them around? 

I think ifshort is low-impact and is currently buggy (gives different results on my machine for some reason). The others - deadcode, varcheck, and struct check [can all be replaced by `unused`
](https://github.com/golangci/golangci-lint/issues/1841)

**Comment by killianmuldoon** [comment]
I've removed the linters in https://github.com/kubernetes-sigs/cluster-api/pull/7114 to see if it's desirable / if there's any objections.

**Comment by chrischdi** [comment]
I'd 👍  for making use of `unused`. These linters sound helpful for imho.

A buggy / non-deterministic ifshort makes no sense for me.

**Comment by sbueringer** [comment]
+1 to drop them

**Comment by fabriziopandini** [comment]
+1 to drop them given that we are already running the unused linter

**Comment by killianmuldoon** [comment]
dropped in #7114 

/close
