### ISSUE TITLE
wrong report of clusterctl describe? 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#7121]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

I deleted the VM (node) and let machinset recreate it ,after that, found the `describe cluster` seems report wrong info about the machine's name (see below) , is it expected?

```
# clusterctl describe cluster capi-quickstart
NAME                                                                                READY  SEVERITY  REASON  SINCE  MESSAGE            
Cluster/capi-quickstart                                                             True                     13d                       
├─ClusterInfrastructure - OpenStackCluster/capi-quickstart                                                                             
├─ControlPlane - KubeadmControlPlane/capi-quickstart-control-plane                  True                     13d                       
│ └─Machine/capi-quickstart-control-plane-jw9tq                                     True                     13d                       
│   └─MachineInfrastructure - OpenStackMachine/capi-quickstart-control-plane-ffmnt                                                     
└─Workers                                                                                                                              
  └─MachineDeployment/capi-quickstart-md-0                                          True                     40m                       
    └─2 Machines...                                                                 True                     46m    See capi-quickstart-md-0-c65cfd7db-cnp2q, capi-quickstart-md-0-c65cfd7db-k89rk

 kubectl get machine
NAME                                   CLUSTER           NODENAME                              PROVIDERID                                          PHASE     AGE   VERSION
capi-quickstart-control-plane-jw9tq    capi-quickstart   capi-quickstart-control-plane-ffmnt   openstack:///7ca49b3a-8096-44f8-a64d-9482fabb4c9d   Running   13d   v1.24.2
capi-quickstart-md-0-c65cfd7db-cnp2q   capi-quickstart   capi-quickstart-md-0-vjz4v            openstack:///11ad7cf7-301a-4a16-8ac1-c300f1d7b5da   Running   47m   v1.24.2
capi-quickstart-md-0-c65cfd7db-k89rk   capi-quickstart   capi-quickstart-md-0-wcq9w            openstack:///30bc0e1f-56c4-46ad-8a86-940d609b08e9   Running   43m   v1.24.2

```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- minikube/kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by jichenjc** [comment]
~# clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.4", GitCommit:"1c3a1526f101d4b07d2eec757fe75e8701cf6212", GitTreeState:"clean", BuildDate:"2022-06-03T17:11:09Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by chrischdi** [comment]
Hi @jichenjc,

Could you highlight which name is wrong? I don't see any mismatch from the output 🤔 
Which Machine/Node got deleted / should not be there?

**Comment by jichenjc** [comment]
sorry, my bad .. read again and seems it's correct, not sure what I thought when I open this ticket,
need drink some tea before do this again ,sorry for confusion

I saw capi-quickstart-md-0-wcq9w  mismatch to capi-quickstart-md-0-c65cfd7db-cnp2q...
