### ISSUE TITLE
[question] healthy check behavior stuck by Terminating pod is correct? 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#7125]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

trying MHC with openstack now , 2 worker nodes ,both not reachable 
one node is updated successfully, but the other got stuck without replacement ,check the log found 
```
I0826 02:24:39.978516       1 machine_controller.go:769] "evicting pod cert-manager/cert-manager-cainjector-c9c77b797-mnfjf\n" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" machine="default/capi-quickstart-md-0-c65cfd7db-cnp2q" namespace="default" name="capi-quickstart-md-0-c65cfd7db-cnp2q" reconcileID=a059788d-8377-4d22-b744-d656c861ed8e cluster="capi-quickstart" node="capi-quickstart-md-0-vjz4v"
I0826 02:24:39.978633       1 machine_controller.go:769] "evicting pod kube-system/calico-kube-controllers-6766647d54-wgwlk\n" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" machine="default/capi-quickstart-md-0-c65cfd7db-cnp2q" namespace="default" name="capi-quickstart-md-0-c65cfd7db-cnp2q" reconcileID=a059788d-8377-4d22-b744-d656c861ed8e cluster="capi-quickstart" node="capi-quickstart-md-0-vjz4v"
I0826 02:24:39.978798       1 machine_controller.go:769] "evicting pod cert-manager/cert-manager-webhook-885b8ffcb-cxxmb\n" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" machine="default/capi-quickstart-md-0-c65cfd7db-cnp2q" namespace="default" name="capi-quickstart-md-0-c65cfd7db-cnp2q" reconcileID=a059788d-8377-4d22-b744-d656c861ed8e cluster="capi-quickstart" node="capi-quickstart-md-0-vjz4v"
I0826 02:24:39.978912       1 machine_controller.go:769] "evicting pod default/php-apache-kata-qemu-6dc96d699-lc2pv\n" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" machine="default/capi-quickstart-md-0-c65cfd7db-cnp2q" namespace="default" name="capi-quickstart-md-0-c65cfd7db-cnp2q" reconcileID=a059788d-8377-4d22-b744-d656c861ed8e cluster="capi-quickstart" node="capi-quickstart-md-0-vjz4v"
I0826 02:24:39.979107       1 machine_controller.go:769] "evicting pod cert-manager/cert-manager-8568b6f9cb-7vsq5\n" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" machine="default/capi-quickstart-md-0-c65cfd7db-cnp2q" namespace="default" name="capi-quickstart-md-0-c65cfd7db-cnp2q" reconcileID=a059788d-8377-4d22-b744-d656c861ed8e cluster="capi-quickstart" node="capi-quickstart-md-0-vjz4v"

```

Found those ports in `Terminating` status and I guess that's the root cause
have to run `kubectl delete pod php-apache-kata-qemu-6dc96d699-lc2pv php-apache-kata-qemu-6dc96d699-hf78n --force` to delete the pods (including all other teminating status pod) then everything works for the 2nd node

so the question is , whether MHC tolerating such Terminating status is reasonable request? 
**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- minikube/kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
I think this is independent of MHC. MHC just triggers the remedation. Then the MachineSet controller triggers the deletion of the Machine.

During that the Machine controller drains the node. This is done with the same code that `kubectl drain` is using. 

In my opinion this behavior is expected. There should a termintionGracePeriod that you can set on Pods that could help in that situation. Apart from that you can also use a nodeDrainTimeout then the Machine controller would just give up draining after a few minutes.

The root cause imho is why the Pod is not terminating correctly / or fast enough (?).

**Comment by enxebre** [comment]
Can you clarify why the pods are stuck so we can reason about the right angle to approach the problem? If the reason the pods are stuck on terminating state is the Node is unreachable and so the API server is unable to communicate with the kubelet on the node, then drain should continue and proceed after 5min https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/machine/machine_controller.go#L563-L565
If it's any other reason this is working as intended.

**Comment by jichenjc** [comment]
>>>The root cause imho is why the Pod is not terminating correctly / or fast enough (

I think not, as the pod is in teminating for long time , I am guessing it's because the node is gone
the pod in that node is not able to be migrated to other node ,so stuck in terminating status?

>>>If the reason the pods are stuck on terminating state is the Node is unreachable and so the API server is unable to communicate with the kubelet on the node, then drain should continue and proceed after 5min 

I will read more about the code, but I can confirm I wait for more than 1-2 hours or even more
at least, my 2 nodes are not reachable at same time so all workers are gone and become 0 worker available
that might means the pod is not able to move to new node created ?
anyway, I agree it might be general k8s question instead of capi question

**Comment by enxebre** [comment]
If the pod is deleting means eviction was allowed, now the drain logic waits for the pod to go away. If the reason for it to be stuck in deleting state is the node is unreachable then this might be a bug on our logic as that scenario should be contemplated and skipped here https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/machine/machine_controller.go#L563-L565
Otherwise we are in a different scenario and we should discuss further about the right thing to do.

/triage needs-information
