### ISSUE TITLE
Tasks for Kubernetes 1.26

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7129]
This issue is tracking the list of tasks that should be implemented when Kubernetes v1.26 is released. 
**Currently, we are waiting for the Kubernetes release and we will for a few months, mostly opening this already for tracking purposes**

For prior art please see #6661

* CI:
    * [ ] CAPD:
        * `docker.yaml`: `KUBERNETES_` env vars in `variables`
        * kind_provider.go, docker/*, ... (just grep for the previously used version in CAPD)
    * [ ] Jobs:
        * Add new periodic upgrade jobs, for all release where we want to support the new Kubernetes version
        * Adjust presubmit jobs so that we have the latest upgrade jobs available on PRs (for all releases)
        * Update `INIT_WITH_KUBERNETES_VERSION`

* [ ] Book:
    * [ ] Update and test quickstart
      * 1.24 PR  #6513
    * [ ] Update supported versions in versions.md
    * [ ] Update job documentation in CAPI (`jobs.md`)

* [ ] Release specific issues:

* After a Kubernetes release is cut a controller-runtime version is created. When the CR version is available we have to:
    * [ ] Bump controller-runtime to use new Kubernetes Go libraries (controller-runtime, controller-tools, client-go, ...)
        * This can include upgrading the Go version (we're using the same as k/k)
    * [ ] Update `KUBEBUILDER_ENVTEST_KUBERNETES_VERSION` in `Makefile`
    * [ ] Bump conversion-gen in `Makefile` via `CONVERSION_GEN_VER`
    * [ ] If the new Kubernetes version uses a new Go version
        * [ ] Jobs: Update kubekins-e2e images used for jobs running against main
            * Potentially it makes sense to switch to the latest ("master") version of kubekins-e2e if there is no `-{KUBERNETES-VERSION}` tag of the image already.
        * [ ] Update go version:
            * .github/workflows
            * .golangci.yml (+ corresponding workflow file)
            * cloudbuild YAMLs (to use an image with the current go version)
            * hack/ensure-go.sh
            * netlify.toml
            * Makefiles
            * Tiltfile
            * [opt] go.mod files (only if we want to increase the minimum supported version of consumers) [DOES NOT APPLY]

**Comment by ykakarap** [comment]
/close 
re-opening with new template.

**Comment by ykakarap** [comment]
New issue: https://github.com/kubernetes-sigs/cluster-api/issues/7671
