### ISSUE TITLE
Drop pinned kube-state-metrics tag

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7143]
Follow-up to https://github.com/kubernetes-sigs/cluster-api/pull/7095#discussion_r958498712

The idea is to stop pinning kube-state-metrics to the v2.6.0 tag in our values.yaml once the Helm Chart uses a version >=v2.6.0

cc @chrischdi 

/kind cleanup

**Comment by chrischdi** [comment]
xref https://github.com/prometheus-community/helm-charts/pull/2422

/assign
