### ISSUE TITLE
Create an untainted control plane with KCP

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#7149]
**User Story**

As an operator I would like to create a control plane without the `node-role.kubernetes.io/master:NoSchedule` taint.

**Detailed Description**

When creating a cluster I would like my control plane to be a scheduling target for all workloads. Setting the initConfiguration of KubeadmControlPlane  NodeRegistration taints to empty results in a nil field which means the taints are applied as default.

Initial conversation on this happened here: https://github.com/kubernetes-sigs/cluster-api/pull/7133

/kind feature

**Comment by killianmuldoon** [comment]
@d8660091 does this summarize your issue correctly?

**Comment by sbueringer** [comment]
nit: I assume the intention is to avoid both the old and the new control plane taint?

**Comment by d8660091** [comment]
@killianmuldoon Perfect! Thank you for creating this issue, we'll keep a close eye on it. 

BTW, created a playground snippet earlier trying to explain the bug: https://go.dev/play/p/TikiIjMYXlM

**Comment by fabriziopandini** [comment]
cc @anusha94 and @randomvariable 
First of all we should check if overriding taints is possible in kubeam, and then expose the same capability in CAPI.

However, the fact that taints will be overridden by KubeadmConfig is tricky e.g. for upgrades when we are fixing up taints to accommodate kubeadm changes.

**Comment by fabriziopandini** [comment]
Another consideration, this could impact addons relying on the taints existance

**Comment by randomvariable** [comment]
addons shouldn't "rely" on taints. Reliance on a control plane for a selector or affinity rule should be based on labels instead. We can defer that problem to the addon IMO.

**Comment by randomvariable** [comment]
had a look at kind, unfortunately:

```go
	// if we are only provisioning one node, remove the master taint
	// https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#master-isolation
	if len(allNodes) == 1 {
		if err := node.Command(
			"kubectl", "--kubeconfig=/etc/kubernetes/admin.conf",
			"taint", "nodes", "--all", "node-role.kubernetes.io/master-",
		).Run(); err != nil {
			return errors.Wrap(err, "failed to remove master taint")
		}
	}
```

**Comment by randomvariable** [comment]
In terms of what we do about scale up, I think we will need to make this explicit. As in we don't care about doing anything like setting the taints back on if worker nodes suddenly appear. The user must explicitly opt out of removing the control plane taint.

**Comment by randomvariable** [comment]
@neolit123 , is there any support for not setting the taints on the kubeadm side? i struggled to find a relevant issue in k/kubeadm.

**Comment by sbueringer** [comment]
> 	// Taints specifies the taints the Node API object should be registered with. If this field is unset, i.e. nil,
>	// it will be defaulted with a control-plane taint for control-plane nodes. If you don't want to taint your control-plane
>	// node, set this field to an empty slice, i.e. `taints: []` in the YAML file. This field is solely used for Node registration.
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta3/types.go#L218-L221

**Comment by sbueringer** [comment]
> e.g. for upgrades when we are fixing up taints to accommodate kubeadm changes.

@fabriziopandini My impression was that the "taint changes" over the last few releases have all been "implemented" by the kubeadm binary itself. I couldn't find anything in KCP where we are modifying the taints.

**Comment by sbueringer** [comment]
> Tested in tilt: the change does pass [] "taints" to kubeadm, and kubeadm doesn't taint contro-plane nodes accordingly. However, it has a side effect of making Taints "required", which is not we wanted.

@d8660091 What did you mean with it makes taints "required"?

**Comment by d8660091** [comment]
@sbueringer After I removed "omitempty" from taints, although taints can be passed from cluster-API to kubeadm, the e2e test broken. It's broken because when "taints: []" is encoded to json, it becomes "taints: null" instead of "" (omitted).

So in this sense, I cannot omit taints in your yaml, so I called it "required", which like you see, is not accurate. If we can find some way to encode "taints: []" to "taints: []", instead of "taints: null", we may able to solve this issue

**Comment by sbueringer** [comment]
Just took a closer look.

### With the current API type

* When setting taints to `[]` it is sent correctly to the server and to the defaulting/mutating webhook
* The webhook does defaulting and then json.Marshal. json.Marshal omits the empty slice and thus CR generates a patch to drop the taints field in `PatchResponseFromRaw`

### After dropping omitempty

* When setting taints to `[]` it is sent correctly to the server and to the defaulting/mutating webhook
* The webhook does defaulting and then json.Marshal. json.Marshal now preserves the taints set to `[]` but when taints is not set in YAML it is rendered as `null`. In the latter case `PatchResponseFromRaw` now generates a patch to set `taints` to `null`, which is something Kubernetes doesn't like. kubectl output:
  > The KubeadmControlPlane "capi-quickstart-control-plane" is invalid: spec.kubeadmConfigSpec.joinConfiguration.nodeRegistration.taints: Invalid value: "null": spec.kubeadmConfigSpec.joinConfiguration.nodeRegistration.taints in body must be of type array: "null"

I know it's basically the same you wrote, I though I'll add just a bit of details about the webhook implementation

**Comment by randomvariable** [comment]
I do remember this conversation in kubeadm, and we decided that to change the way kubeadm handles this would be a breaking API change.

**Comment by sbueringer** [comment]
I think kubeadm handles it correctly at the moment. They dropped omitempty btw between v1beta2 and v1beta3 APIs

**Comment by sbueringer** [comment]
Implemented a quick hack on #7161 to show that it's possible. 

I think the change from a user point of view is that when an empty slice is set it is not just dropped and ignored. This could be considered a bug fix.

**Comment by chrischdi** [comment]
> Implemented a quick hack on #7161 to show that it's possible.
> 
> I think the change from a user point of view is that when an empty slice is set it is not just dropped and ignored. This could be considered a bug fix.
> 
> (Based on my local test this would work to produce control plane nodes without control plane taints)

@sbueringer : wondering if this then also works with topology controller. Did you try that?

**Comment by sbueringer** [comment]
I would expect it to work but I didn't try it.

If the empty slice is coming from patches it's very very likely as we're just working with the JSON in the controller.
If the empty slice is coming from KubeadmControlPlaneTemplate it should work as well if the same custom marshalling is used there to "preserve" the empty array (and it should automatically as we use the same struct there)

**Comment by chrischdi** [comment]
Maybe a workaround to consider until a fix for this was implemented: Set a taint which has effect `PreferNoSchedule` to be added to all nodes. As long as all nodes (control plane and worker) have this same taint, they should be treated equally for scheduling purposes and control plane nodes should get workload scheduled.

```yaml
  taints:
  - effect: PreferNoSchedule
    key: NoTaintWorkaround
    value: true
```
