### ISSUE TITLE
Ensure correct logging of reference structs in both json and text logging

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#7150]
With recent logging changes a [reference and object logger were added to CAPI](https://github.com/kubernetes-sigs/cluster-api/commit/1a286fdf7da314bdfbb76b042f8f25f1828734a0#diff-3a86c514d2d3f52dc7235e0444e3a2c54960795d7e73cecb131b876ce306442b):

These objects may look correct in json logging, but may not correctly represent the object in text form.

https://github.com/kubernetes-sigs/cluster-api/pull/6918 Added a new logging struct `logRef` which correctly logs to both text and json formats.

We should investigate using a single structure across the codebase where references like this are used, and decide to include a single version in our internal log package, with or without helper functions.

Current reference implementation:
https://github.com/kubernetes-sigs/cluster-api/blob/1a286fdf7da314bdfbb76b042f8f25f1828734a0/internal/log/log.go#L103-L114

New reference implementation:
https://github.com/kubernetes-sigs/cluster-api/blob/a99bcf5460d83abd3201ad4441b5ce4d2529a006/test/extension/handlers/topologymutation/lib.go#L103-L127

**Comment by fabriziopandini** [comment]
What about proposing this change in Klog instead?

**Comment by killianmuldoon** [comment]
> What about proposing this change in Klog instead?

I'm not sure if this new type would be acceptable in klog (or adding it to KRef), but I can open an issue over there to check the temperature.

This should probably be cleaned up in CAPI (for WithRef) for the time being as well. I'm not sure where else structs are logged that don't appear correctly in text format, but it seems likely this might not be the only place.

**Comment by fabriziopandini** [comment]
/assign @sbueringer 
To take a look and see if we can also cleanup the tlog package

**Comment by sbueringer** [comment]
I would keep the logRef in the topologymutation package but only use it locally there.

Furthermore I'll get rid of the internal/log (aka "tlog") package and replace it with standrad klog.
