### ISSUE TITLE
Add CAPI Visualizer to `clusterctl`

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api#7155]
**User Story**

I'd like to explore adding a command like `clusterctl visualize cluster my-cluster` to open the cluster view in the visualizer app or to `clusterctl visualize` to open the visualizer management cluster view. 

/kind feature

**Comment by fabriziopandini** [comment]
I'm not 100% sure we should do this via clusterctl, because IMO the Visualizer is something like an addon for the management cluster.
Opinions?

**Comment by sbueringer** [comment]
I tend to agree with that. It would want to avoid making clusterctl a general kubectl/helm replacement over time. I think we should limit it to the absolute necessary.

**Comment by Jont828** [comment]
Yeah that makes sense. My goal was to make it more seamless to use the visualizer app for general use cases. Currently you'd need to `helm install`, wait for the deployment to be ready, and then create port-forward. Do you think that introduces too much friction (since the Tilt setup includes it with a YAML setting).

**Comment by sbueringer** [comment]
I think if you want to make visualizer easy to use for "normal" consumers independent of our tilt development setup, it would be best to further extend the Helm Chart.

Usually Helm charts for applications which provide a UI contain a service/ingress combination which can then be leveraged by consumers to expose it via a separately deployed ingress controller.

It's my impression that that's how it is usually done. Some Helm charts which should be doing this are Grafana and Prometheus.

**Comment by Jont828** [comment]
Fair enough, if we'd like to keep it separate then I'll go ahead and close out this issue.
