### ISSUE TITLE
cluster-api-push-images-nightly job is failing

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7165]
Just got a mail that our nightly image push job doesn't work anymore.

See: https://testgrid.k8s.io/sig-cluster-lifecycle-image-pushes#cluster-api-push-images-nightly

Looks like this was caused by https://github.com/kubernetes-sigs/cluster-api/pull/7135 and the new image doesn't contain gsutil anymore.

P.S. post-cluster-api-push-images still works because it doesn't use gsutil.

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by chrischdi** [comment]
Seems to be a regression via https://github.com/kubernetes/test-infra/commit/b5133abb96a85be4211c97da82c379646df4ff65 which did remove the following command which lead to an installed gsutil binary:

```
/google-cloud-sdk/install.sh \
        --disable-installation-options \
        --bash-completion=false \
        --path-update=false \
        --usage-reporting=false
```

**Comment by chrischdi** [comment]
Adding `gsutil` to the command `gcloud components install ...` in https://github.com/kubernetes/test-infra/blob/master/images/gcb-docker-gcloud/Dockerfile#L41 would install it again. However I was not able to get context of it getting deleted on purpose (at the PR).

**Comment by sbueringer** [comment]
Let's open an issue in test-infra an cc author/reviewers of this PR
