### ISSUE TITLE
Make Group / Version/ Kind mandatory for MachineList

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#717]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
cluster

clusterctl can currently read in a machines.yaml file that contains only `items` as the root key.

At first glance, it's not clear that it's a MachineList or should be interpreted as such. Other tooling,
primarily kustomize has issues handling the sample machines.yaml most providers copied.

https://github.com/kubernetes-sigs/cluster-api/pull/716 adds the ability to interpret the same objects
in a wider variety of formats, but has some hacks around handling the "typeless" MachineList.

Propose we make G/V/K mandatory for MachineList so we can use standard API Machinery to 
read documents in from the command line.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
We've already standardized on the explicit use in cluster-api-provider-aws, :+1: from me for requiring it explicitly globally.

**Comment by randomvariable** [comment]
I was thinking you can probably use something like the UniversalDeserializer. There's an example here https://github.com/kubernetes/client-go/issues/193#issuecomment-343138889

**Comment by frapposelli** [comment]
@randomvariable I've been looking at using `UniversalDeserializer`, but currently `k8s.io/client-go` does not know how to deserialize `clusterv1` objects.

Thinking about sending a simple PR in to force G/V/K with the current code path and add an issue to move to `UniversalDeserializer` post v1alpha1.

**Comment by randomvariable** [comment]
@frapposelli 

Ah, ok. Thanks for investigating. What you're suggesting sounds good as an approach.
