### ISSUE TITLE
[clusterctl] Document bootstrap flags

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#718]
/kind bug

**What steps did you take and what happened:**
I wanted to customize the arguments passed to `kind` and the documentation does not make it easy to know the syntax for `--bootstrap-flags`

**What did you expect to happen:**
I would expect an example of something as complex as passing flags from one command line tool to another.

**Anything else you would like to add:**

**Environment:**

**Comment by chuckha** [comment]
/milestone next

not sure if we even want to continue with clusterctl, so let's reevaluate next milestone

**Comment by timothysc** [comment]
I'm going to close this specific issue and focus on rallying on a well defined set of umbrella issues for next version.
