### ISSUE TITLE
Document the github Personal Access Token requirement in the book

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#7188]
**Detailed Description**

The CAPI book does not document the need for a github personal access token when working with public repos. I believe this requirement is well known to folks who regularly work with Cluster API but it would good to document the requirement in the book for more visibility.

Ref: https://github.com/kubernetes-sigs/cluster-api/issues/3982#issuecomment-1228793391

/kind documentation
/area clusterctl

/good-first-issue

**Comment by fabriziopandini** [comment]
/triage accepted
+1 
let's just make clear this is required only for folks doing extensive use of clusterctl

**Comment by aniruddha2000** [comment]
It should be documented under [clusterctl configuration](https://cluster-api.sigs.k8s.io/clusterctl/configuration.html) right?

**Comment by ykakarap** [comment]
@aniruddha2000 Under clusterctl configuration sounds good. Please add a new section in that page and document the personal access token requirements.

**Comment by fabriziopandini** [comment]
If we are targeting end users I will document this in https://cluster-api.sigs.k8s.io/clusterctl/overview.html as well (let's document it here and link it from configuration and from the clusterctl init page as well)
