### ISSUE TITLE
[clusterctl] bootstrap flags behaves unexpectedly 

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#719]
/kind bug

**What steps did you take and what happened:**
I ran
```
create cluster -v 3 \
	--provider aws \
	--bootstrap-type kind \
	--bootstrap-flags image=kindest/node:latest \
	-m ./cmd/clusterctl/examples/aws/out/machines.yaml \
	-c ./cmd/clusterctl/examples/aws/out/cluster.yaml \
	-p ./cmd/clusterctl/examples/aws/out/provider-components.yaml \
	-a ./cmd/clusterctl/examples/aws/out/addons.yaml
```

Since I wanted to use a custom kubernetes build. This worked for the first step but it passed the `--image` flag to the `kind get kubeconfig`.

It's not urgent but it makes these flags almost unusable since the flags passed in must be global to all commands `clusterctl create cluster` uses.

## The workaround

The workaround is simple. Create the cluster and use `-e` in clusterctl create cluster to pass an existing bootstrap kubeconfig.

**What did you expect to happen:**
I did not expect the flags to be global to every kind command.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/cc @vincepri 
/priority important-soon
/milestone v1alpha1

**Comment by vincepri** [comment]
Related #710
