### ISSUE TITLE
MachineStatefulSet for HA Control Plane

### ISSUE THREAD

**Issue by gdoctor** [kubernetes-sigs/cluster-api#720]
/kind feature

**Describe the solution you'd like**
I would like to add a MachineStatefulSet, in the same way the MachineDeployment and MachineReplicaSet were created. We could then build off of this to create a highly available control plane. The two key features this would give us are:
* Ordered, graceful deployment and scaling.
* Ordered, automated rolling updates.

This would give us the necessary information on ordering to perform operations, such as initial bootstrapping, needed to create an HA control plane. Has this been discussed as a part of an HA setup already?

**Comment by detiber** [comment]
@gdoctor I would love to see a more detailed (KEP-style) proposal for this.

Initial concerns that I potentially see around this approach:
- We don't currently differentiate machine types in the common cluster-api, so how we would express initial control plane node (generally kubeadm init) vs additional control plane nodes (generally kubeadm join) for the order of operations would have to work with how multiple providers handle the distinction between machine types.
- Scale up/scale down is going to be tricky to handle properly
- MachineSets are currently backed by Machines, how would providers be able to implement an interface in a way to be compatible with MachineStatefulSets? Would they just be Machines that have some additional implied context somehow? Would they be backed by a different type of object to provide conformity across providers?

**Comment by liztio** [comment]
I think this is superseded by the Control Plane proposal (#1613). Closing for now. 

/close
