### ISSUE TITLE
Introduce a `NeedsRollout` filter in `util/collections` package

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#7215]
**Detailed Description**

The [`MachinesNeedingRollout`](https://github.com/ykakarap/cluster-api/blob/bf99b6a2425c603c7a544bd318132b7270fa17cf/controlplane/kubeadm/internal/control_plane.go#L248) and the [`UpToDateMachines`](https://github.com/ykakarap/cluster-api/blob/bf99b6a2425c603c7a544bd318132b7270fa17cf/controlplane/kubeadm/internal/control_plane.go#L265) functions in `controlplane/kubeadm/internal/` use a combination of filters to determine if a machine needs rollout (or the negation = is stable). 

Let's introduce a new filter named `NeedsRollout` that will be used as the single filter in these two functions. This way we can keep the list of filters that make up a rollout in a single place.

/kind cleanup
/good-first-issue

/hold until https://github.com/kubernetes-sigs/cluster-api/pull/6983 is merged as it introduces a new filter to the list.

**Comment by dharmicksai** [comment]
Hello, I would like to work on this issue
/assign

**Comment by aniruddha2000** [comment]
@dharmicksai are you still working on this?

**Comment by dharmicksai** [comment]
Hey , I am working on the task

**Comment by ykakarap** [comment]
> Alternate solution to this would be to create the `NeedsRollout` filter in `controlplane/kubeadm/internal`

Sounds good. Go ahead with this. The  `controlplane/kubeadm/internal/filters.go` is probably the best place for this since it already holds definitions for other filters.
