### ISSUE TITLE
Also run clusterctl upgrade test with ClusterClass

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7226]
**User Story**

As a user I would like to be able to upgrade ClusterAPI without unintended consequences for ClusterClass-based clusters.

**Detailed Description**

As of today we have a clusterctl upgrade which we run in various permutations (regarding "initial" versions).
The test roughly does the following:

* Create a 1st workload cluster
* Download a specific version of clusterctl and convert the 1st workload cluster to a management cluster by installing CAPI
  * clusterctl version and contract of the CAPI version we install are configurable via env vars
* Create a 2nd workload cluster managed by the new management cluster
* Upgrade ClusterAPI
* Ensure this didn't trigger a rollout of the 2nd workload cluster
* Scale up a MD of the 2nd workload cluster

The goal of this issue is to be able to create the 2nd workload cluster with ClusterClass.

I think we can do this by adding an additional spec to clusterctl_upgrade_test.go. This spec should pin to CAPI v1.2.x, the v1beta1 contract and the workload flavor to one using a clusterclass. 

I wonder if we should inline the separate clusterctl upgrade jobs we have configured via test-infra in this file as well. xref:
* https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-upgrade-v0-3-to-main
* https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-upgrade-v1-2-to-main

I think it would make it a lot easier to have all 4 jobs defined in the test file vs. having them distributed over core CAPI and test-infra. They would then be all run as part of capi-e2e-main / e2e-full-main.
(also two less jobs in testgrid per CAPI version)

/kind feature

**Comment by fabriziopandini** [comment]
/triage accepted

Let's make sure this scenario works without changes first, then we can figure out what is the solution that makes our maintenance duties simpler

**Comment by sbueringer** [comment]
Yup definitely
