### ISSUE TITLE
Support standard input as input source for `clusterctl generate cluster` command

### ISSUE THREAD

**Issue by neoaggelos** [kubernetes-sigs/cluster-api#7227]
**User Story**

As a developer/user, I would like to pass cluster templates to the `clusterctl generate cluster` command via stdin for the following reasons:
- allow this syntax: `$any_command | clusterctl generate cluster --from -`, so that the generate command can be a part of a whole pipeline of steps
- make it easier to use clusterctl with cluster templates that are in a different machine. e.g. during development, I edit a cluster-template.yaml file locally, then pass it via stdin to `clusterctl` running on a remote host. otherwise, this would be two steps (copy the cluster template file, then run clusterctl generate cluster).

**Detailed Description**

Currently, `clusterctl generate cluster` accepts the following template sources:
- `[-i $provider] [-f $flavor]`: parse templates from released `cluster-template-${flavor}.yaml` files from the configured infrastructure providers.
- `--from $url`: parse template from github, raw URL or a local file
- `--from-config-map $cm`: parse template from a configmap in the management cluster.

I would like to suggest adding support for `clusterctl generate cluster --from -`, which would read the cluster template from stdin instead. Implementation can be quite simple, since all we need to do is handle `-` as a value in https://github.com/kubernetes-sigs/cluster-api/blob/cede911727f3cba3a402348a7c6e636d7a44ab6a/cmd/clusterctl/client/cluster/template.go#L132

**Anything else you would like to add:**

Something like this is already supported in the `clusterctl generate yaml` command, but that one has slightly different semantics from `clusterctl generate cluster` (e.g. no cluster_name, namespace, etc).

/kind feature

**Comment by neoaggelos** [comment]
I have went ahead and created a small PR for this which works fine for me. If CAPI contributors are happy with this addition, I can add some unit test coverage as well.

**Comment by sbueringer** [comment]
cc @ykakarap

**Comment by fabriziopandini** [comment]
/triage accepted

we are already supporting something similar in clusterctl generate yaml, but I'm not opposed having it gerated cluster as well

**Comment by ykakarap** [comment]
I am fine with adding the support.
