### ISSUE TITLE
Add E2E for single node clusters with scale out rollout

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#7230]
**User Story**

As a user, I would like to use CAPI for single node clusters

**Detailed Description**

We are getting a growing number of queries in slack/via other channels about single node clusters, and it would be great if we set up an E2E test for ensuring proper coverage of the scenario we already support, which is a single node cluster with a scale-out rollout policy.

**Anything else you would like to add:**

In order to cover the trickiest spots, this test should try to do an upgrade of a self-hosted E2E cluster (basically or current self-hosted test with a different template and + an additional step for upgrade)

/kind feature

**Comment by sbueringer** [comment]
Related: #3728 (essentially the self-hosted upgrade part of it)

**Comment by chrischdi** [comment]
#7239 will not implement it for single node clusters (1 replica for KCP, 0 worker nodes).

The first point failing would be: cert-manager pods not having tolerations to run on the control-plane nodes.

If that is the requirement, we should keep it out-of scope for #7239 and build on top instead.

**Comment by sbueringer** [comment]
Good finding, missed that one. Yup let's make it a follow-up

**Comment by fabriziopandini** [comment]
+1 to get an E2E test for taints: [] (with ClusterClass)

**Comment by sbueringer** [comment]
I'll follow-up once #7239 merges
