### ISSUE TITLE
Improving defaulting and validation in clusterctl alpha topology plan

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#7245]
**User Story**

As a user I would like that clusterctl alpha topology plan gives me results as accurate as possible

**Detailed Description**

As of today clusterctl alpha topology plan defaults and validates only CC and Cluster objects, leaving the users the burden to provide templates that pass validation and that include all the values that the defaulting web hook usually apply.

This issue is about leveraging on SSA dry run to perform validation and defaulting in clusterctl alpha topology plan so the user UX is simplified and results are more accurate.

**Anything else you would like to add:**

Using SSA dry run is possible only under certain circumstances, e.g there is a management cluster in place; in case the command will detect it is not possible to use SSA dry run for validation and default, it will revert to the current behavior and inform the user with a warning about the degraded quality 

/area clusterctl
/area topology
/kind feature

**Comment by ykakarap** [comment]
I am happy to work on this once I have some bandwidth but if someone wants to work on this in the meantime I am happy to pair and help :)

**Comment by sbueringer** [comment]
@fabriziopandini  Can this be merged with https://github.com/kubernetes-sigs/cluster-api/issues/7246?

**Comment by fabriziopandini** [comment]
No strong opinions, I will defer to @ykakarap.

**Comment by ykakarap** [comment]
I would recommend to keep them separate. The two issues address different concerns and are better addressed in separate PRs. Even though both of them use SSA dry run as the underlying approach they need it for different things and are consumed in different ways.

**Comment by fabriziopandini** [comment]
I'm going to close this issue now given that the GAP from this feature and what ClusterClass can do keeps growing and it doesn't seem there is much interest in contributing to this feature
/close
