### ISSUE TITLE
Make clusterctl alpha topology plan to use SSA / dry run

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#7246]
**User Story**

As a user I would like that clusterctl alpha topology plan gives me results as accurate as possible

**Detailed Description**

As of today, clusterctl alpha topology plan uses a TwoWaysPatchHelper to compute changes applied by the topology controller, but this can give false positives/false negatives given the recent move to SSA for the topology controller.

This issue is about making clusterctl alpha topology plan to use SSA apply in combination with the dry run flag, so we can provide better results.

**Anything else you would like to add:**

Using SSA dry run is possible only under certain circumstances, e.g there is a management cluster in place; in case the command will detect it is not possible to use SSA dry run for validation and default, it will revert to the current behavior and inform the user with a warning about the degraded quality

WRT to the implementation, currently clusterctl alpha topology plan is using a [dryrun.Client](https://github.com/kubernetes-sigs/cluster-api/blob/fd113025386cac495fcfd6043d0830f5fc581766/cmd/clusterctl/client/cluster/internal/dryrun/client.go#L81) that wrap a fakeClient and a real client for API reads only.

This should be changed in order to use a real client also for create/patch operations implemented with SSA apply with the dry run option (we do not want to make any change to the Cluster!)

/area clusterctl
/area topology
/kind feature

**Comment by fabriziopandini** [comment]
Note: I have hacked a little bit around this, I'm going to share what I have in a personal branch ASAP

**Comment by ykakarap** [comment]
I am interested in working on this. I will need some more time before I can get to this. In the mean time if someone wants to take stab at this I am happy to pair and help :)

**Comment by sbueringer** [comment]
Sounds good. Would be good if we only use SSA for Kubernetes >= v1.22 (CC is not supported below v1.22 anyway, but just to be safe)

**Comment by fabriziopandini** [comment]
I'm going to close this issue now given that the GAP from this feature and what ClusterClass can do keeps growing and it doesn't seem there is much interest in contributing to this feature
/close

**Comment by fabriziopandini** [comment]
I'm +1. we can bring this up in one of the next office hours (no rush here)
