### ISSUE TITLE
document migrating to user-managed cert-manager 

### ISSUE THREAD

**Issue by charlie-haley** [kubernetes-sigs/cluster-api#7280]
**User Story**

As an operator I would like to ignore cert-manager during upgrades so I can self-manage cert-manager deployments.

**Detailed Description**
Currently when upgrading CAPI through clusterctl, it tries to upgrade cert-manager based on the annotation `cert-manager.clusterctl.cluster.x-k8s.io/version`, as we manage our own cert-manager deployment this annotation is almost always out of date.

**Anything else you would like to add:**
Ideally, there would be an option to ignore cert-manager entirely through the upgrade process, as we currently handle the cert-manager upgrade process independently of CAPI. Maybe something like this?
```yaml
cert-manager:
  ignore: true
```
Another alternative could be looking at the label `app.kubernetes.io/version` instead of the annotation `cert-manager.clusterctl.cluster.x-k8s.io/version` and using that to determine an upgrade, that way it isn't tied to clusterctl?

/kind feature

**Comment by chrischdi** [comment]
clusterctl already checks if cert-manager is managed by clusterctl or by the user.
It won't update cert-manager if cert-manager was not deployed via clusterctl.

It does so by checking if the installation is externally managed:
- https://github.com/kubernetes-sigs/cluster-api/blob/cdf3b9c8203ba65936a363943957d4c04eef265e/cmd/clusterctl/cmd/upgrade_plan.go#L79

And the check if cert-manager is managed by clusterctl is done at:
- https://github.com/kubernetes-sigs/cluster-api/blob/cdf3b9c8203ba65936a363943957d4c04eef265e/cmd/clusterctl/client/cluster/cert_manager.go

By listing all api resources in namespace `cert-manager` which have the label `clusterctl.cluster.x-k8s.io/core=cert-manager` set. If there is more than 1 object found, it will try to upgrade cert-manager. If there is no api resource having this label in the cert-manager namespace, it will skip upgrading cert-manager.

Maybe this requires better documentation at the book 🤔

**Comment by charlie-haley** [comment]
Thanks for the reply @chrischdi, it looks like our cert-manager deployment got into a weird state - it was originally installed with clusterctl, now we're managing it ourselves.

Removing the labels fixes the issue for me! However, do you think an `ignore` option would still be valid if people wanted to migrate from clusterctl managed cert-manager to user-managed?

**Comment by sbueringer** [comment]
I would prefer to tell folks to just remove our label vs telling them they should add another one.

**Comment by charlie-haley** [comment]
Okay sounds good! If you want, I can raise a PR to the docs explaining this?

**Comment by fabriziopandini** [comment]
+1 to document how to transition form a managed cert-manager to unmanaged; probably this documentation should go https://cluster-api.sigs.k8s.io/tasks/certs/index.html and then link in https://cluster-api.sigs.k8s.io/clusterctl/configuration.html#cert-manager-configuration

/triage accepted
/remove-kind feature
/kind documentation
