### ISSUE TITLE
Support add annotations to MachineTemplate when `cluster generate cluster` run

### ISSUE THREAD

**Issue by scuzhanglei** [kubernetes-sigs/cluster-api#7291]
**User Story**

We have a cluster template, and when different user use this template, they may add different annotations to `MachineTemplate`. I found it was not possible to do this by Environment variable substitution.  And I tried set it in clusterctl.yaml, it didn't work too. So is there any solution to do this?
**Detailed Description**

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by sbueringer** [comment]
I'm not sure if `clusterctl generate cluster` is supposed to handle specific use cases like this. Essentially it ~ downloads cluster-templates published by providers and then runs envsubst on them. I think in general there are a lot of things that folks might want to customize in those resources, but I don't think we should adjust clusterctl to handle them.

I would recommend to either run kustomize after clusterctl generate or to just use the YAML generated by `clusterctl generate cluster` as an example and write your own YAML based on that.
