### ISSUE TITLE
Document `failureDomains` for Cluster controllers in the CAPI Book

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api#7300]
/kind bug

The [infra cluster provider contract](https://cluster-api.sigs.k8s.io/developer/providers/cluster-infrastructure.html) lists `failureDomains` as a required contract field. It's not listed in the [cluster controller](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/cluster.html) section however, and it should be added in order to be consistent.

**Comment by sbueringer** [comment]
/triage accepted

Thx for catching this.

Minor nit: It's an optional field.
