### ISSUE TITLE
Add `failureDomain` as a required field in the machine controller docs

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api#7301]
/kind bug

The [infra machine provider contract](https://cluster-api.sigs.k8s.io/developer/providers/machine-infrastructure.html) lists `failureDomain` as a required contract field. It's not listed in the [machine controller](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/machine.html) section however, and it should be added in order to be consistent.

**Comment by sbueringer** [comment]
Some nits:
`failureDomain` is an optional spec field (not required).
Would be also good to add the optional status field `addresses`.

/triage accepted

**Comment by Jont828** [comment]
Should be fixed in #7328, looks like this didn't get closed when that merged.
