### ISSUE TITLE
[e2e tests] UpgradeManagementClusterAndWait cannot upgrade to a pre-release

### ISSUE THREAD

**Issue by mboukhalfa** [kubernetes-sigs/cluster-api#7311]
**User Story**

As a developer I would like to to test upgrade a management cluster to a pre-release from e2e tests.

**Detailed Description**
Upgrading to a pre-release is already possible with `clusterctl` since we can specify custom providers instead of contract e.g:
``` 
clusterctl upgrade apply --core capi-system/cluster-api:v1.2.1 --bootstrap capi-kubeadm-bootstrap-system/kubeadm:v1.2.1 --control-plane capi-kubeadm-control-plane-system/kubeadm:v1.2.1 --infrastructure capm3-system/metal3:v1.2.0-rc.1
```
But when using e2e framework this option does not seem allowed.
The upgrade client implements setting custom providers https://github.com/kubernetes-sigs/cluster-api/blob/6e30f66cc3df04cd4c53a8bbbe2331c5f44c74b2/cmd/clusterctl/client/upgrade.go#L154-L191  
But I think these should be propagated to  `UpgradeManagementClusterAndWait` https://github.com/kubernetes-sigs/cluster-api/blob/a0f3da17e2d891fe73a016fa7e5ed861e1796766/test/framework/clusterctl/clusterctl_helpers.go#L124-L130 
So we can test upgrading to pre-release from e2e by setting the custom providers as an alternative for setting the contract. 

/kind feature

https://github.com/kubernetes-sigs/cluster-api/issues/7311#tasklist-block-a8e0e5cf-f72e-45ea-b562-659cc278e2e9

**Comment by fabriziopandini** [comment]
This implies some plumbing, but it should be doable
/triage accepted
/help
