### ISSUE TITLE
Drop fix RBAC from component management in clusterctl

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#7318]
clusterctl dropped support for many instances of the same providers a couple of release ago, but there are still some part of the code that consider this uses case. By cleaning them up we can simplify the codebase.

One of them is [fixRBAC](https://github.com/kubernetes-sigs/cluster-api/blob/dca818ab13049ea972400cae188b1bd3d47b5d55/cmd/clusterctl/client/repository/components.go#L262) while processing components.

The change is pretty simple (drop the func and corresponding tests), but the author of this PR should take care of doing some manual testing on init and upgrade from an older version of clusterctl

/area clusterctl
/kind cleanup

**Comment by oscr** [comment]
Some control questions to get the scope right from the start:
* What clusterctl version(s) would be reasonable to upgrade from?
* Should we test step by step upgrade (1.0 -> 1.1 -> 1.2 -> master) and/or "jump" upgrades (1.0 -> master, 1.1 -> master)? 
* Would creating a cluster (the getting started guide with capd) and then upgrading the cluster be a sufficient test scope?

**Comment by fabriziopandini** [comment]
> What clusterctl version(s) would be reasonable to upgrade from?

I will test upgrading from v1.2.2 (latest release with fixed RBAC) to main

> Should we test step by step upgrade (1.0 -> 1.1 -> 1.2 -> master) and/or "jump" upgrades (1.0 -> master, 1.1 -> master)?

I don't think it is necessary to test sequences, once we team from a version with fixed RBAC to the new version without RABC fix, all the combination should be the same

> Would creating a cluster (the getting started guide with capd) and then upgrading the cluster be a sufficient test scope?

Yes this (while looking at RBAC rules in the cluster) or the E2E for clusterctl upgrades

**Comment by sbueringer** [comment]
Sounds like running e2e-full on the PR should cover it (and more)

**Comment by fabriziopandini** [comment]
Yes, E2E covers it, but human eyes have to check the we are not leaving behind objects when we move from a version with fixed RBAC to the new version without RABC fix

**Comment by chrischdi** [comment]
/retitle Drop fix RBAC from component management in clusterctl
