### ISSUE TITLE
Simplify UX in clusterctl upgrades

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#7319]
clusterctl dropped support for many instances of the same providers a couple of release ago, but there is still some part of the code that consider this uses case. By cleaning them up we can simplify the UX of some commands.

One of them is [clusterctl upgrade apply](https://cluster-api.sigs.k8s.io/clusterctl/commands/upgrade.html) UX, that when upgrading single providers by using flags like --bootstrap, --infrastructure, etc requires the user to specify `namespace/name:version`. this can be simplified by allowing users to specify only `name:version` and automatically discover the namespace behind the scene.

This requires:
- Change the [parseUpgradeItem](https://github.com/kubernetes-sigs/cluster-api/blob/dca818ab13049ea972400cae188b1bd3d47b5d55/cmd/clusterctl/client/upgrade.go#L211) implementing the auto-discovery mechanism; please note that we should support both formats for a certain time, giving notice that the old format is deprecated 
- Fix unit tests accordingly
- Do some manual validation (upgrading a single provider is not covered by existing E2E tests)
- Change in parameters description/documentation

/area clusterctl
/kind cleanup

**Comment by sbueringer** [comment]
> this can be simplified by allowing users to specify only name:version and automatically discover the namespace behind the scene.

Wouldn't this mean the same provider cannot deployed twice at the same time with clusterctl? Or is that the case we dropped?
