### ISSUE TITLE
Provider Release(s)

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api#732]
**Describe the solution you'd like**
We are dutifully trekking towards a v1alpha1, but we have no documentation, or process about how we plan to release artifacts for *providers.  

/kind feature
@ncdc

**Comment by vincepri** [comment]
Related to #730

**Comment by ncdc** [comment]
Once #768 is merged, do we plan to copy/paste that process information from here to the various provider repositories?

**Comment by chuckha** [comment]
No, that's an information gathering step. The release process is very different between providers and cluster-api, copying doesn't make sense yet.

The next step is to at least automate cluster-api releases, ideally automate aws provider as well, and see what can and cannot be shared and what is unique to providers.

That document has links to other providers release process which can also be found in their repos either in issues or in their documentation.

**Comment by ncdc** [comment]
If the release process varies across providers, and that is acceptable, I'd suggest we consider closing this issue.

**Comment by chuckha** [comment]
It's not all documented yet, but we do have issues open for the documentation across many of the providers. if you'd like to close it out, by all means

**Comment by ncdc** [comment]
I don't think I have permission yet to close, so if it doesn't work, hopefully someone else can do it for me 😄 

/close

**Comment by ncdc** [comment]
Ha I take that back!
