### ISSUE TITLE
Improve RuntimeSDK error management (or conditions)

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#7321]
After some time using runtime SDK iI have found some places where we can improve error management for Runtime SDK; I'm listing some improvement idea here, but this does not imply all of them should be fixed in a single PR (many PR is fine or even better).

**Extension Config**

There is little visibility in the errors that can happen while registering a runtime extension:
- Lack of certificates
- Wrong service name/port (service not answering)
- Failures in discovery

Almost all those errors are logged, but when looking at the extension config object there are no hints about what's going on. We should consider if to add a condition to the ExtensionConfig object to surface those problems, eventually pointing to users to the logs for more details

**Hooks errors**

While there is a failure in calling a hook we surface it in a condition, but without details about the underlying errors in order to avoid infinite reconciliation due to error messages continuously changing.

While this makes sense, at the same time it makes it hard to understand what happens. In order to improve this I see two possible approaches:
- add to the error message in the condition a hint to look at logs for more detail
- surface the plain error, documenting in the developer guidelines Runtime Extension how error message should be built and what can happen if those guideline are not respected

/kind feature

**Comment by sbueringer** [comment]
> We should consider if to add a condition to the ExtensionConfig object to surface those problems, eventually pointing to users to the logs for more details

It would be good if we can check if it would fit to also cover the certificate injection in the existing Discovery condition

> add to the error message in the condition a hint to look at logs for more detail
> surface the plain error, documenting in the developer guidelines Runtime Extension how error message should be built and what can happen if those guideline are not respected

I would prefer the first option. I think the second one is too dangerous. Essentially Runtime Extension authors have to sanitize every error they return. If they do some downstream requests to cloud APIs, ... the propagated errors could change in arbitrary ways.

**Comment by fabriziopandini** [comment]
PS. we already re-inforced guidelines on error messages, so we can also consider to surface the underlying error
