### ISSUE TITLE
KCP should introspect machine certificate expiry information from node to enable automatic certificate renewal

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#7342]
**User Story**

Recently a feature was introduced in KCP to enable automatic renewal of certificates by doing a repave: https://github.com/kubernetes-sigs/cluster-api/pull/6983

This feature only works for control plane machines created using Cluster API v1.3 or above. 
For older control plane machines it needs manual intervention from the user to provide the actual certificate expiry date of the control plane machines. 

This issue is to explore ideas around how we can introspect the certificate expiry time from the node without needing manual intervention from the user.

**Detailed Description**

The certificate expiry time cannot reliably calculated from the `creationTimestamp` of the Machine object. Example: If the machine object is restored from a backup the `creationTimestamp` would have changed. 

 One possible way to calculate the certificate expiry time:
 > Cluster API / KCP introspect these values by running an exec pod temporarily on the node
>
> xref: https://github.com/kubernetes-sigs/cluster-api/pull/7268#discussion_r984800820

/kind feature
/area control-plane

**Comment by sbueringer** [comment]
I wonder if we should really introduce this mechanism in our controller. It's only needed for old machines, but we will still never be really able to remove this code again (as we will have to assume for a very long time that old machines still exist).

Apart from that I wonder if it's worth investing the effort to implement this. It's non-trivial to do considering that this probably has to work on Windows & Linux, requires privileged access to control plane machines, ... .

**Comment by sbueringer** [comment]
I wonder if there might be some other/better ways to determine the node creation date and we just missed them:
* inspect the kube-apiserver or etcd-server serving certificate for expiry (of the specific node)
  * Should be the same expiry as the other certs: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#check-certificate-expiration
* Maybe the etcd member of the machine has some "creation date"
* The creation date of the mirrored kube-apiserver / kube-controller-manager / ... Pods

**Comment by sbueringer** [comment]
@vincepri WDYT?

**Comment by fabriziopandini** [comment]
I'm +1 to explore this idea, but we should find a solution that does not require adding new binaries to the controller image (do something equivalent via some go code)
