### ISSUE TITLE
clusterctl: Consider re-using repositoryClientFactory

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7346]
While implementing #7343 we noticed that we create multiple repositoryClientFactories in clusterctl.

`newClusterctlClient`:
https://github.com/kubernetes-sigs/cluster-api/blob/44f9fd9501bd8aa2e5a77597dd9cc02a09af46e4/cmd/clusterctl/client/client.go#L188-L195

`defaultRepositoryFactory` and `defaultClusterFactory`
https://github.com/kubernetes-sigs/cluster-api/blob/44f9fd9501bd8aa2e5a77597dd9cc02a09af46e4/cmd/clusterctl/client/client.go#L207-L227

First we create and return a `client.RepositoryClientFactory` in `defaultRepositoryFactory` then 
`defaultClusterFactory` creates its own `cluster.RepositoryClientFactory` in `cluster.New`. Both are using different different parameters to call `repository.New`.

This issue is about considerung using the same repositoryClientFactory for both (if it's doable / makes sense)

/kind cleanup
/area clusterctl
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
/triage accepted
As a first step, I will make sure we are always creating repository with the same parameters given that this is probably easier, but might be that there is a solution to directly move to use only one repository client

**Comment by fabriziopandini** [comment]
/triage accepted
/priority backlog

We don't have reports of this being an issue, but it still seems a nice cleanup to have
However, if nothing happens in the future, let's consider closing this ticket

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

/close
