### ISSUE TITLE
Improve Linux tool installation in quickstart docs

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7372]
Just saw that the Kubernetes docs are installing kubectl after the download with

```bash
sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
```

(xref: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-binary-with-curl-on-linux)

Instead of chmod + mv ...

I think we should be able to use this in our quickstart as well (only for Linux).

/kind documentation
/help

**Comment by hackeramitkumar** [comment]
@sbueringer I would like to work on it. Can you assign it to me?

**Comment by hackeramitkumar** [comment]
It's going to be my first contribution to this project, So please assign it to me.

**Comment by sbueringer** [comment]
Sure!

/assign @hackeramitkumar
