### ISSUE TITLE
How to keep v1.Node in cluster when deleting Machine?

### ISSUE THREAD

**Issue by k82cn** [kubernetes-sigs/cluster-api#7378]
**User Story**

As an operator, I would like to keep **v1.Node** in the cluster when deleting Machine; as I'd like to migrate cluster-api and infra to other cluster.

**Detailed Description**

I'd like to move cluster-api and infra to other cluster; so I'd like to keep v1.Node in the cluster, just remove cluster-api CRs.

**Anything else you would like to add:**

xref: https://metal3io.netlify.app/bmo/detached_annotation.html

/kind feature

**Comment by enxebre** [comment]
Deleting the Node is part of the deletion workflow and I don't think it should be disassociated from it unless there's a strong rationale for it. For migration scenarios I'd suggest to explore spec.Pause, ,and may be open an issue to discuss best practices.

**Comment by fabriziopandini** [comment]
I agree with @enxebre, this should not be implemented unless we clarify use cases/user stories around the idea of "detaching", which is something we do not support and, as far as I remember, was never discussed during office hours.

Please also note that in most of the infrastructure providers Machine deletion implies the removal of the underlying infrastructure, so keeping the node around does not really make sense.

**Comment by sbueringer** [comment]
It sounds like the ask is to do something similar to clustectl move. Thus it can be probably solved with our current implementation accordingly.

**Comment by k82cn** [comment]
> Please also note that in most of the infrastructure providers Machine deletion implies the removal of the underlying infrastructure, so keeping the node around does not really make sense.

We're using [Metal3.BareMetalHost detached](https://metal3io.netlify.app/bmo/detached_annotation.html) feature which will not remove the infra. So in my case, I removed BareMetalHost without de-provision (the kubelet keep running), but the v1.Node was deleted by Machine.

> It sounds like the ask is to do something similar to clustectl move. Thus it can be probably solved with our current implementation accordingly.

Any guidance or links for that?

**Comment by sbueringer** [comment]
Here's the link:
> https://cluster-api.sigs.k8s.io/clusterctl/commands/move.html

But might not make any sense depending on what exactly you want to do.
