### ISSUE TITLE
clusterctl describe not working in Windows PowerShell

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#7381]
Running `cluster describe cluster my-cluster` on PowerShell results in broken output as the colors are not rendered correctly. There is a current workaround involving setting a `NO_COLOR` environmental variable to print the output without color. 

`clusterctl describe` (on main) supports a --color flag which forces color output when it's off by default (the library clusterctl uses fatih/color does this when the output is not to a terminal. Currently this flag defaults to false and is a no-op when set to false.

One solution to the PowerShell problem would be to change the usage of that flag so that when it's set to false it always turns the color off. That would allow users to explicitly opt out of using colors in the output.

/area clusterctl
/kind bug

**Comment by fabriziopandini** [comment]
/triage accepted

Q: should we report the issue to fatih/color maintainers? (or might be this already has been fixed in latest version of this library)

**Comment by sbueringer** [comment]
I'm not sure if the library is wrong, but rather our usage of it.

**Comment by fabriziopandini** [comment]
that could be another issue as well, but I think we should nail down the problem before deciding to workaround it

**Comment by killianmuldoon** [comment]
We're using the latest version (v1.13.0) but it's 1+ years old. This issue might have been solved in a more recent commit.

**Comment by killianmuldoon** [comment]
I'll report the issue, bit after going over a bunch of workarounds it seems that there's a general issue with getting colors to work in PowerShell / cmd environments. 

Changing the terminal settings as described here - https://stackoverflow.com/questions/51680709/colored-text-output-in-powershell-console-using-ansi-vt100-codes - worked to fix the output but did not actually get colors in the output 😕.

**Comment by killianmuldoon** [comment]
/close 

I believe this was fixed in https://github.com/fatih/color/releases/tag/v1.15.0.

Closing due to lack of interest.
