### ISSUE TITLE
machine controller failed to receive resource changes about some machines

### ISSUE THREAD

**Issue by ruifaling** [kubernetes-sigs/cluster-api#7385]
when delete some workload cluster,the deletion lasted a long time. From the log,I found it has been a long time not recorded about the machines of this cluster,then I edit the machine(some controlplan machine) and add some labels, it still no log about the machine.
Then I delete the pod of capi-controller-manager,after the pod has been rebuild,the machine deleted,and at last the cluster deleted.

**Comment by killianmuldoon** [comment]
I think we need a bit more information here to get to the bottom of this. 

What infrastructure provider are you using? Do you know if the infrastructure machine was deleted? Do you have the output of the logs? How long was it taking for the Machine to be correctly deleted?

/triage needs-information
/kind support
/remove-help
(The help label is too signal work that someone in the community should pick up)

**Comment by sbueringer** [comment]
Sorry Cluster API v0.4. is out of support. Can you please upgrade to the currently supported v1.2.x release series and see if the issue still occurs?

**Comment by fabriziopandini** [comment]
/close
eventually re-open a new issue if the error exists with more recent versions of Cluster API
