### ISSUE TITLE
External etcd lifecycle support

### ISSUE THREAD

**Issue by g-gaston** [kubernetes-sigs/cluster-api#7399]
**User Story**

As an operator, I would like to be able to manage the lifecycle of external etcd clusters in the same way I do for control planes, using CAPI primitives.

**Detailed Description**

Cluster API supports the use of an external etcd cluster, by allowing users to provide their external etcd cluster's endpoints.
So it would be good to add support for provisioning the etcd cluster too, so the user can have a single workflow for full management of a cluster using the external etcd topology. The user can offload the responsibility of managing an external etcd cluster to CAPI.

**Anything else you would like to add:**

Why unstacked etcd is valuable:

* External etcd topology decouples the control plane and etcd member. So if a control plane-only node fails, or if there's a memory leak in a component like kube-apiserver, it won't directly impact an etcd member.

* Etcd is resource intensive, so it is safer to have dedicated nodes for etcd, it could use more disk space, higher bandwidth. Having a separate etcd cluster for these reasons could ensure a more resilient HA setup.

Original proposal https://github.com/kubernetes-sigs/cluster-api/pull/4659/

/kind feature

**Comment by g-gaston** [comment]
@fabriziopandini, as promised :)
I'll follow up with a new PR

**Comment by nanorobocop** [comment]
How about just separating controlplane and etcd node roles?
Means provision etcd as static pods in cluster, just on dedicated for etcd nodes.
The main goal would be same - dedicated nodes for etcd (but also with kubelet).

If add 'etcd' node role, that would also help to transform cluster from one type to another.
Initially cluster could be with joined controlplane+etcd roles.
And could be transformed to separated controlplane and etcd nodes, just by changing node roles.

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

I don't see activity or progress around this topic, we might eventually reconsider if conditions change

/close
