### ISSUE TITLE
Change registry in published manifests to registry.k8s.io

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7402]
Hey folks,

I think it is time that we publish manifests with the new registry location. I did a quick test just to double check and our v1.2.3 images are already available under registry.k8s.io/cluster-api.

While we're on it. Let's check the whole repo for occurences of k8s.gcr.io and see if we can replace them all

Let's also add this to the v1.2=>v1.3 migration guide as a hint for providers.

Let's be careful about just search/replacing k8s.gcr.io across godoc / unit tests / ... . Some of them maybe shouldn't change.

/kind cleanup
/area release

**Comment by sbueringer** [comment]
@fabriziopandini WDYT?

(I flagged it as release-blocking as I think we should do this before v1.3.0)

**Comment by fabriziopandini** [comment]
Agreed
/triage accepted
/milestone v1.3
