### ISSUE TITLE
Extend ClusterClass changes e2e test to cover MD deletion

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7404]
As already written in the title, goal of this issue is to extend our ClusterClass changes e2e test to delete a MachineDeployment.

The idea is to trigger a delete of the MD via Cluster.spec.topology at the end of the test and then verify that the MD is actually deleted.

/kind feature

**Comment by fabriziopandini** [comment]
/close
PR is merged
