### ISSUE TITLE
`clusterctl move` should not pause clusters before completing all the preflight checks

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#7407]
**What steps did you take and what happened:**
* Create a management cluster with `CLUSTER_TOPOLOGY`  feature gate enabled
* Create a classy cluster
* Initialize CAPI on the classy cluster `CLUSTE_TOPOLOGY` feature gate disabled
* Perform a `clusterctl move --to-kubeconfig classy-cluster.kubeconfig`

**What did you expect to happen:**

The `clusterctl move` operation should fail since the target cluster does not have the correct feature gates enabled. Since the operation does not success the clusters should not move from the original management cluster and a user should be able to perform operations on the clusters.

However, all the clusters remain paused and the user has to manually unpause all the clusters before being able to perform any operations on the cluster.

**Anything else you would like to add:**

`clusterctl move` pauses all the clusters before performing the move. If the move operation fails the clusters remain in paused state but it would be desirable to unpause the clusters is the move operation fails.

**Environment:**

- Cluster-api version: `main`
- minikube/kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
/area clusterctl

**Comment by fabriziopandini** [comment]
/triage accepted

I agree we should complete all the preflight check before pausing the clusters, but at the same time we should not unpause the clusters if the operation fail because the operation is designed to be idempotent (so the user can restart and complete move).

**Comment by ykakarap** [comment]
Changing it so that it only pauses if the pre-flight checks pass is a good approach. I am +1 to that.

**Comment by fabriziopandini** [comment]
/close

it seems preflight checks are already done before pause, see https://github.com/kubernetes-sigs/cluster-api/blob/e8b15a15d70cf94a70df4958764de9c19fb86cf2/cmd/clusterctl/client/cluster/mover.go#L90
