### ISSUE TITLE
Consider if to drop golang.org/x/net in favor of context

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#7427]
While reviewing https://github.com/kubernetes-sigs/cluster-api/pull/7425 it surfaced that we are using golang.org/x/net, but from a quick look we are using only context from this package.

This issue is about investigating whether to drop this package and use context from golang standard library.

/kind cleanup
/help

**Comment by sbueringer** [comment]
/close

given #7426 was merged
