### ISSUE TITLE
Add pod security admission labels to CAPD provider namespace

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/cluster-api#7429]
**User Story**

As an operator I would like to set the baseline to enforce at the pod security admission configuration on my management cluster for operating a secure management cluster.

Currently when using CAPI with CAPD, all capi namespaces except `capd-system` are compliant to the `baseline` pod security admission profile.

**Detailed Description**

CAPD will always require the `privileged` profile, because it makes use of the hostPath volumes and requires privileged to mount and access the docker socket.

It is possible to set the cluster-wide enforce policy to `baseline` when provisioning CAPD using one of the following approaches:

1. Set the `capd-system` namespace to enforce, audit and warn on `privileged`.
2. Add the `capd-system` namespace to the namespace excemptions in the pod security admission configuration.

I would propose to:
* add the following labels to the `capd-system` namespace at the [namespace.yaml resource file](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/infrastructure/docker/config/default/namespace.yaml):
  ```
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
  ```
* add a test which enables `enforce: baseline` for the whole management cluster to test compatibility of CAPI to the baseline profile (The config will need to except `kube-system` because `kube-system` will almost always require the privileged profile for CNI related daemonsets).

**Anything else you would like to add:**

The same applies to CAPZ and could get adapted there. The `capz-system` namespace currently also requires the `privileged` profile because the nmi daemonset defines additional capabilities and a hostPath mounts for pod-identity.

/kind feature

**Comment by fabriziopandini** [comment]
/triage accepted

+1 to the idea
let's talk about how to add this to one (or more of the existing tests) instead of creating a new one, we already have too many of them and we start to think about how to rationalize things a little bit

**Comment by sbueringer** [comment]
+1

I would just modify the quick start Clusterclass we are using in multiple tests already accordingly + CAPD

This should not require an additional test

**Comment by sbueringer** [comment]
Sounds good, thx!
