### ISSUE TITLE
Consider "false" value when evaluating "bool" annotations

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api#7434]
**User Story**

As a user I would like existing annotations annotations explicitly set to "false" to be respected as false in Cluster API.

**Detailed Description**

For annotations where we simply look for the presence of a well-known key to indicate true/false, we should consider enabling support for explicit "false" indicators. The most obvious is the value of `"false"` in the value of the existent annotation.

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

This precedent was established as a part of this PR: https://github.com/kubernetes-sigs/cluster-api/pull/7107

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by vincepri** [comment]
Are there some examples that supporting `false` as a value is beneficial to user? Same for #7107, what's the benefit vs removing the annotation completely?

**Comment by jackfrancis** [comment]
@vincepri the idea we discussed when this issue was filed was that in the (rare) event where a new user w/ pre-existing Kubernetes infrastructure adopts Cluster API, they may already be using CAPI annotations for previous use in a negative sense, and if so we should respect that.

I don't remember the exact conversation, but (despite the fact that I filed this issue!) I would prefer that CAPI standardize to requiring significance for both key + value in any capi-specific annotations to avoid collisions w/ pre-existing usage of those annotations across the Kubernetes ecosystem. Because there's no standard set of "Kubernetes annotations", we can't guarantee uniqueness when we come up w/ a new, CAPI-specific annotation.

In any event this issue is a good thread to have this conversation for folks who are interested.

**Comment by sbueringer** [comment]
But aren't CAPI specific annotations namespaced to out namespace? I think that should guarantee that nobody else defined them before.

Nobody else should define annotations in our namespace

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.
I don't see folks willing to commit to this

> For annotations where we simply look for the presence of a well-known key to indicate true/false, we should consider enabling support for explicit "false" indicators.

We can reopen if conditions arises + someone volounteers
/close
