### ISSUE TITLE
Add extra information in the supported labels and annotations tables

### ISSUE THREAD

**Issue by hackeramitkumar** [kubernetes-sigs/cluster-api#7441]
Follow up :  #7418 

**Detailed Description**
Add two columns in the supported labels and annotations table :
- Object the label/annotation applies to
- Managed by Cluster API or by users

Please also define some consistent sort criteria for both tables.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind documentation

**Comment by hackeramitkumar** [comment]
> /trige accepted

**Comment by hackeramitkumar** [comment]
@fabriziopandini Can you suggest me some resources ?  Where I can find the following details - 
    a. Object the label/annotation applies to
    b. Managed by Cluster API or by users

**Comment by fabriziopandini** [comment]
@hackeramitkumar you can try to infer this from label/annotation description or dig into the code.
but it is ok also if you come up with a partial work and then we rally on completing it

**Comment by fabriziopandini** [comment]
/triage accepted
/priority backlog

Adding good first issue given that I think that also newcomers can kick off this work in https://cluster-api.sigs.k8s.io/reference/labels_and_annotations by:
- sorting label and annotations in alphabetical order
- add two new columns (Applies to & manage by)

Bonus point if the start compiling the two columns inferring from the label/annotations note (or looking into code)

Maintainers then can step in and rally on the PR for missing values, or eventually defer to a follow up iteration

/good-first-issue
