### ISSUE TITLE
Proactively bounce capi-controller-manager in case of netsplits 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api#7445]
(edit: removed ccm, bc its an ambiguous abbreviation)

**User Story**

As a user on the edge, in case that one node in my MC gets somehow netsplit off from my Controlplane worker nodes, id like the capi controller manager to fail, that way it bounces to a "potentially" healthy, connected other node in my MC. 

**Detailed Description**

As an example of how I was stepping through this earlier,  the steps i followed here worked https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1660...  

**Anything else you would like to add:**

I saw this in a very odd environment, admittedly, but I think its still a good idea to broaden the definition of health for the capi controller manager, if possible.  We wouldnt want a single capi-controller-manager that was having issues to slow down the remediation of a fleet of clusters running on different networks . 

/kind feature

Diagram below shows the issue i ran into in this netsplit situation.

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/826111/197611612-ab2f4362-b3b5-4c03-8f96-de99465351f7.png">

**Comment by chrischdi** [comment]
I think this is a general problem for all kind of controllers and is not specific to CAPI's controllers. It should be (or maybe is already) solved in Kubernetes itself.

Did you check if the pod gets evicted after five minutes which would map to the default of the kube-controller-managers `pod-eviction-timeout duration` parameter (which defaults to `5m0s`, [xref](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/))

As addition, there are also two other maybe interesting configuration parameters for kube-apiserver which I got from [this issue](https://github.com/kubernetes/kubernetes/issues/55713): FeatureGate `DefaultTolerationSeconds `, `default-not-ready-toleration-seconds` and `default-unreachable-toleration-seconds` ([xref]())

A workaround would be to run the CAPI Controller Manager (and also the other controllers) by multiple replicas and anti-affinity. Failed leader election should lead to failover to another replica.

**Comment by sbueringer** [comment]
>  id like the CCM to fail, that way it bounces to a "potentially" healthy, connected other node in my MC.

Not sure if I underestood the issue correctly, but changes to the CCM should be out of scope of the Cluster API project?

**Comment by sbueringer** [comment]
To be clear:
* CCM = cloud controller manager
* not capi controller manager

Wasn't your problem that the cloud controller manager was not setting the providerIDs on nodes?

**Comment by jayunit100** [comment]
- I think the cloud controller Manager issue may also have been a problem, but i saw that
- during a net split situation,  capi-controller-manager flips out if it cant connect to a control plane of a wl cluster , but it doesnt actually shutdown or bounce to a new node.

**Comment by killianmuldoon** [comment]
> during a net split situation, capi-controller-manager flips out if it cant connect to a control plane of a wl cluster , but it doesnt actually shutdown or bounce to a new node

Is the CAPI Controller Manager running with multiple replicas? If the controller is out of the network (split from the leader API server on the mgmt cluster) it should lose the lease and another replica should take up the lease. 

If the management Cluster is cut off from the network entirely it will just keep retrying to contact the workload cluster.

**Comment by jayunit100** [comment]
in this case,  the capi-controller-manager's node 
- is able to connect to *its own* apiserver, (so it doesnt lose the lease) 
- *but not that* of other WL apiservers, (so it keeps failing at any MHC type steps)

**Comment by chrischdi** [comment]
So it looks something like this, the red or orange connection here is broken in someway?

![image](https://user-images.githubusercontent.com/417870/197565520-9ec81217-6149-46f7-b0f5-5e5d51621da8.png)

**Comment by jayunit100** [comment]
Yup !!!!!!!!!

**Comment by jayunit100** [comment]
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/826111/197611574-2519a7ac-7852-41ad-8071-6f3ee32c6270.png">
similar pic to yours

**Comment by killianmuldoon** [comment]
There's a few questions that come to mind:
1) Should CAPI be considered in a non-healthy state if it can't contact a single workload cluster, or a majority or all of them? How long should this be the case before taking action?
2) Is the management cluster in HA? Is the assumption that a CAPI controller on another node would be able to communicate with the Workload Cluster? Would it be able to communicate with the APIServer on the initial CAPI controller node?
3) A compromise / best-effort mitigation could be that the CAPI controller should lose the lease if it can't contact all workload clusters (or some subset of them?). Then it's likely that another controller would get the lease and possibly be able to contact those clusters.

Could this be approached by watching a metric and alerting that the CP is not able to contact workloads? [This is discussed here](https://github.com/kubernetes-sigs/cluster-api/issues/5510).

That would give someone with insight into the network set up a change to remediate manually, or set up some deployment specific automation.

**Comment by sbueringer** [comment]
I think the answer is monitoring to be honest. Monitor Cluster API and then produce corresponding alerts with either manual playbooks or some automatic mitigation (although that's super hard with things like net splits)

Some thoughts:

> the capi controller manager to fail, that way it bounces to a "potentially" healthy, connected other node in my MC.

If we include "can the CAPI controller contact workload clusters" into our readiness/liveness probes (or if the controller just shuts down) we get the following consequences:
* we will get container restarts and CrashLoopBackoffs
* this doesn't trigger a Pod eviction and no re-scheduling of the Pod
* even if the CAPI controller Pod deletes itself it would get rescheduled on the same Node with a very high probability
  * the kube-scheduler afaik per default prefers Nodes which already have the container image locally

I don't think with a behavior like that we could maintain stable operations.

Let's assume we have a bunch of workload clusters and some of them are offline (either because they are simply broken / misconfigured or some edge "temporary not reachable" scenario). The Cluster API controller would just be permanently restarted. Imagine what happens if you have a few hundred clusters..

**Comment by jayunit100** [comment]
The answer to any logging problem can be better metrics and alerting, but logs are just a batteries included solution that work anywhere.

And  w non traditional capi deployments is there is no monitoring infrastructure guarantee.

The advantage of some kind of log in here or other lightweight aggregation is that it makes the diagnosis immediate and transparent.

**Comment by fabriziopandini** [comment]
/triage accepted

trying to make up my mind on two sides of the problem:
- how can we detect netsplit (a problem on the machine controller run on) from other network problems that affect connectivity to all or a subset of workload clusters
- how bounce should happen is interesting. What trigger the bumps? how do we ensure the newly scheduled controller doesn't get scheduled on the same machine.

**Comment by jayunit100** [comment]
Maybe it's just a naive time bomb expiration? Like once every week or something?

**Comment by fabriziopandini** [comment]
/close

unfortunately we did not reach an agreement on a way forward and the issue was not active in the last year
