### ISSUE TITLE
[Docs] Generate CRD guide

### ISSUE THREAD

**Issue by dipankardas011** [kubernetes-sigs/cluster-api#7447]
https://github.com/kubernetes-sigs/cluster-api/blob/56db3f5dd92a508906b6c53ae238adbff5fe0645/docs/book/src/developer/providers/implementers-guide/generate_crds.md?plain=1#L5

> why we are changing to this path?

https://github.com/kubernetes-sigs/cluster-api/issues/7447#tasklist-block-d0ba0da8-b262-4993-be82-6c3650ea1c9b

**Comment by killianmuldoon** [comment]
This is the module path for CAPI and other providers that are under kubernetes-sigs repos,  but 100 percent agree it would be more explicit and helpful to clearly mention why the user is in that path in the text here
.

**Comment by dipankardas011** [comment]
can we use 
```diff
// any project folder name
+ mkdir -p src/sigs.k8s.io/cluster-api-provider-mailgun
+ cd src/sigs.k8s.io/cluster-api-provider-mailgun
```
@killianmuldoon 
is it correct if I do this?

**Comment by killianmuldoon** [comment]
I think it might be clearer to simply state that the guide assumes the current directory is `src/sigs.k8s.io/`. Users who have CAPI installed will probably already have this path on their system.

**Comment by dipankardas011** [comment]
But as I don't have CAPI installed will it be correct to create any folder and do the same folder structure here?

**Comment by dipankardas011** [comment]
I am getting confused could you guide me as a beginner to CRD in K8s

**Comment by killianmuldoon** [comment]
Apologies - I misunderstood what you were aiming for.  

To get this working as in guide your steps were likely correct i.e. 

```
mkdir -p src/sigs.k8s.io/cluster-api-provider-mailgun
cd src/sigs.k8s.io/cluster-api-provider-mailgun
```

**Comment by dipankardas011** [comment]
> Apologies - I misunderstood what you were aiming for.
> 
> To get this working as in guide your steps were correct i.e.
> 
> ```
> mkdir -p src/sigs.k8s.io/cluster-api-provider-mailgun
> cd src/sigs.k8s.io/cluster-api-provider-mailgun
> ```

following this guide to get started with crd and controller good for beginners in terms of crd creation?

**Comment by dipankardas011** [comment]
I have background of go, kubernetes, docker

**Comment by killianmuldoon** [comment]
@dipankardas011 It's a better idea to follow the guide in the [kubebuilder book](https://book.kubebuilder.io/) IMO as this tutorial is very specific to Cluster API.

**Comment by dipankardas011** [comment]
Thanks @killianmuldoon
