### ISSUE TITLE
Enable revive check if-return

### ISSUE THREAD

**Issue by oscr** [kubernetes-sigs/cluster-api#7449]
**Detailed Description**

In pr #7442 most of the [recommended revive rules](https://github.com/mgechev/revive#recommended-configuration) where enabled, except two which had a lot of findings. 

This ticket is about enabling revive check: `if-return` again [here](https://github.com/kubernetes-sigs/cluster-api/blob/9d35266899202681e8faaf93d002608ad58a6ff5/.golangci.yml#L166) and fixing the findings.  

/kind feature

**Comment by fabriziopandini** [comment]
/triage accepted
/help

let's make an assessment about how much invasive this is vs the value added by the check before fixing

**Comment by oscr** [comment]
I took a look at it now and after adding an ignore for the conversions it was pretty straight forward.
