### ISSUE TITLE
kustomize v2 fails building the default config

### ISSUE THREAD

**Issue by greut** [kubernetes-sigs/cluster-api#745]
/kind bug

**What steps did you take and what happened:**

Building the components via kustomize fails.

```console
% kustomize version
Version: {KustomizeVersion:2.0.1 GitCommit:ce7e5ee2c30cc5856fea01fe423cf167f2a2d0c3 BuildDate:2019-02-08T00:57:04Z GoOs:unknown GoArch:unknown}

% kustomize build vendor/sigs.k8s.io/cluster-api/config/default
Error: rawResources failed to read Resources: Load from path ../crds/cluster_v1alpha1_cluster.yaml failed: security; file '../crds/cluster_v1alpha1_cluster.yaml' is not in or below '.../vendor/sigs.k8s.io/cluster-api/config/default'

% kustomize edit fix
2019/02/13 08:57:28 Fixed the missing field by adding apiVersion: kustomize.config.k8s.io/v1beta1
Fixed the missing field by adding kind: Kustomization
```

**What did you expect to happen:**

the YAML being built.

**Anything else you would like to add:**

Moving the `kustomization.yaml` file into the `config` directory should solve it.

**Environment:**

- Cluster-api version: master, 0f315e945d5fabe0c805ccf30fa6cf02fac6c0b5
- Kubernetes version: (use `kubectl version`): -
- OS (e.g. from `/etc/os-release`): -

**Comment by detiber** [comment]
Workaround for now is to use kustomize v1.0.11

**Comment by davidewatson** [comment]
With #759 merged, can this be closed?

**Comment by vincepri** [comment]
I believe so!

/close
