### ISSUE TITLE
Bump gomega to v1.23.0

### ISSUE THREAD

**Issue by Amulyam24** [kubernetes-sigs/cluster-api#7458]
**What steps did you take and what happened:**
On bumping gomega version to 1.23.0 in `cluster-api-provider-ibmcloud`, the e2e tests(using capi test framework) fail with
```
Failed to compile e2e:

# sigs.k8s.io/cluster-api/test/framework
../../../pkg/mod/sigs.k8s.io/cluster-api/test@v1.2.4/framework/alltypes_helpers.go:173:6: too many arguments in call to Eventually
        have (func() error, []interface{})
        want (...interface{})
../../../pkg/mod/sigs.k8s.io/cluster-api/test@v1.2.4/framework/cluster_helpers.go:58:5: too many arguments in call to Eventually
        have (func() error, []interface{})
        want (...interface{})
../../../pkg/mod/sigs.k8s.io/cluster-api/test@v1.2.4/framework/cluster_helpers.go:143:5: too many arguments in call to Eventually
        have (func() (string, error), []interface{})
        want (...interface{})
../../../pkg/mod/sigs.k8s.io/cluster-api/test@v1.2.4/framework/cluster_helpers.go:175:5: too many arguments in call to Eventually
        have (func() bool, []interface{})
        want (...interface{})
../../../pkg/mod/sigs.k8s.io/cluster-api/test@v1.2.4/framework/clusterresourceset_helpers.go:129:5: too many arguments in call to Eventually
        have (func() bool, []interface{})
        want (...interface{})
...
...
```
This is caused due to a recent change in using `Eventually` in gomega v1.23.0

- cluster-api is using gomega v1.20.1

**What did you expect to happen:**

**Anything else you would like to add:**

1. Is there a reason why an older version of gomega is used in `cluster-api`?

**Environment:**

- Cluster-api version: 1.2.4
- minikube/kind version: 
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by oscr** [comment]
Gomega v1.20.1 is [two months old](https://github.com/onsi/gomega/releases/tag/v1.20.1) so I think it's just a case of not being updated yet. But I have created a pr to upgrade Ginkgo and Gomega.

**Comment by sbueringer** [comment]
Yup. Bumping is fine

**Comment by oscr** [comment]
@Amulyam24 This seems to be fixed in Gomega `1.24.1`. Version is now being bumped in #7523 

I think this issue can be closed now

**Comment by sbueringer** [comment]
Yup if you bump to v1.24.1 there shouldn't be a compatibility issue with CAPI anymore

**Comment by Amulyam24** [comment]
Thanks @oscr and  @sbueringer !
