### ISSUE TITLE
Add support for adopting existing MachineSets to MachineDeployments

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#746]
/kind feature

**Describe the solution you'd like**
Currently MachineDeployments do not have the ability to adopt existing MachineSets as part of the reconciliation workflow the same way that MachineSets have the ability to adopt existing Machines. This causes issues when migrating MachineDeployments and their associated MachineSets to a different cluster

One of the issues that this causes is: after pivoting a cluster and deleting one of the migrated MachineDeplyments are not cleaned up through cascading deletion.

/priority important-longterm
/milestone v1alpha1

**Comment by vincepri** [comment]
Looking through the controller's code, seems like the MachineDeployment code looks for a `controllerRef`, do we lose the reference after pivoting?

**Comment by detiber** [comment]
@vincepri I haven't tested with the current pivot logic, but this would be required with my pivot PR: https://github.com/kubernetes-sigs/cluster-api/pull/731

Even with the existing pivot logic, the owner ref would not be fully valid since it would have the UID for the MachineDeployment in the source cluster and not the target cluster.
