### ISSUE TITLE
The ready condition of MachineDeployment doesn't change when a Machine CR is deleted

### ISSUE THREAD

**Issue by jessehu** [kubernetes-sigs/cluster-api#7461]
**What steps did you take and what happened:**
1. Create a workload cluster (e.g. 3 CP + 3 Workers)
2. Delete a Machine CR related to MachineDeployment
3. MachineDeployment status doesn't change until the old Machine is deleted successfully and the new Machine CR is created.

**What did you expect to happen:**
The ready condition of MachineDeployment CR should change to False right after Machine CR is deleted. The Replicas or ReadyReplicas in MD.Status might be udpated as well as.

**Anything else you would like to add:**
When Delete a Machine CR related to KCP,  the ready condition of KCP CR changes to False immediately (as expected). The Replicas, ReadyReplicas, Unavailable in MD.Status doesn't change until the new Machine CR is created.

**Environment:**

- Cluster-api version: v1.2.3
- minikube/kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by jessehu** [comment]
Related to PR https://github.com/kubernetes-sigs/cluster-api/pull/4625

**Comment by fabriziopandini** [comment]
/triage accepted

I have to look into this and come back with my consideration about the proposed changes, but I agree that the system should reflect changes as soon as possible and there should be consistency between KCP and MD

**Comment by fabriziopandini** [comment]
/lifecycle frozen
/help
it will be great if someone can take over the research work behind this issue

**Comment by haijianyang** [comment]
When Machine being deleted, the associated Node is still `ready`(node.status.conditions is ready) although it is with`NoSchedule` taint. So the readyReplicas of MachineDeployment and MachineSet are not changed. 
Only after the Machine is deleted, MachineSet and MachineDeployment will update readyReplicas.

machineset_controller knows whether the node is ready by IsNodeReady and set readyReplicas.
```go
//  /cluster-api/controllers/noderefutil/util.go
// IsNodeReady returns true if a node is ready; false otherwise.
func IsNodeReady(node *corev1.Node) bool {
	if node == nil {
		return false
	}
	for _, c := range node.Status.Conditions {
		if c.Type == corev1.NodeReady {
			return c.Status == corev1.ConditionTrue
		}
	}
	return false
}
```

```bash
# mycluster-workergroup1-pnh2w is being deleted
kubectl get nodes
NAME                           STATUS                     ROLES                  AGE   VERSION
mycluster-controlplane-bcr8j   Ready                      control-plane,master   84m   v1.23.14
mycluster-controlplane-cdv2d   Ready                      control-plane,master   87m   v1.23.14
mycluster-controlplane-m5zjc   Ready                      control-plane,master   82m   v1.23.14
mycluster-workergroup1-pnh2w   Ready,SchedulingDisabled   <none>                 85m   v1.23.14
mycluster-workergroup1-pxm7m   Ready                      <none>                 84s   v1.23.14
mycluster-workergroup1-t5std   Ready                      <none>                 84m   v1.23.14
```


Currently, we cannot know whether any nodes in the cluster are being deleted(through MachineDeployment and MachineSet).

Can we add deletingReplicas to MachineDeployment and MachineSet to record the number of Machines being deleted. When Machine is deleted, MachineDeployment and MachineSet can update deletingReplicas in real time.

**Comment by haijianyang** [comment]
@fabriziopandini

**Comment by jessehu** [comment]
similiar to https://github.com/kubernetes-sigs/cluster-api/issues/8923

**Comment by fabriziopandini** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/10897 is going to fix this, PTAL

Please note that
- there won't be anymore a MachineDeployment condition, but only a MachineDeployment available condition
- when a Machine is deleted MachineDeployment available condition will flip depending on MaxUnaivable setting (if it is set to zero as a default, it will flip immediately)
- the number of ready replicas won't be computed anymore by looking _only_ at NodeReady, but it will look at the machine's ready conditions instead.

/close
