### ISSUE TITLE
Simplifying the Makefile

### ISSUE THREAD

**Issue by oscr** [kubernetes-sigs/cluster-api#7464]
**Detailed Description**

I would like to make a few suggestions for simplifying the Makefile. 

* Removing Go based dependency installation from Makefile and instead using Go tooling. Basically copying the approach of [test-infra](https://github.com/kubernetes/test-infra/blob/master/hack/tools/tools.go) and [k/k](https://github.com/kubernetes/kubernetes/blob/master/hack/tools/tools.go).

* Creating a [hack/make-rules](https://github.com/kubernetes/test-infra/tree/master/hack/make-rules) directory for scripts used by the Makefile and then using it in targets. Again similar to [test-infra](https://github.com/kubernetes/test-infra/blob/68096feebb923af468985229c5b6d6cb91ea07d1/Makefile#L100-L102)

* Using [Makefile includes](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/e70ae1a8a880eb746941093e7675e00c76a15440/Makefile#L17) like CAPO to break out [versions](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/versions.mk) and other [common](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/common.mk) functionality. 

My suggestion is to start with the two first and after they are completed consider if the third is needed. But we could do 1 or more of these. Or if there are any other suggestions. I think these suggestions could help break down the Makefile complexity into parts that would be easier to overview. But it would of course introduce some complexity of it's own. 

/assign
/kind feature

**Comment by fabriziopandini** [comment]
/triage accepted
Let's way for others opinions on the proposed approach but I'm generally +1 to simplify the current Makefile

**Comment by oscr** [comment]
I forgot to mention this but we should be able to use dependabot with the first suggestion. This would remove some manual work.

**Comment by sbueringer** [comment]
Regarding 1. Please see: https://github.com/kubernetes-sigs/cluster-api/issues/5569

I don't necessarily see the benefit in splitting up the Makefile after we spent quite some time moving things into a monolithic Makefile if the goal would be just to make it shorter :) 

I think our reason for e.g. dropping the CAPD Makefile was to remove redundant Makefile code and reuse what we already have. But splitting it up like you suggested is definitely another discussion and we're not going back to what we had before :). 

It would be good to understand the motivation for 1-3, but especially 2+3. I'm in general fine with making things easier and de-duplicating code that we have in multiple Makefiles. I'm not sure just splitting it up to get to a shorter Makefile is worth the effort. (as I said we've spent quite some time refactoring Makefiles in the past, would be good if we have a final goal in mind going forward)

**Comment by oscr** [comment]
Thanks for the great reply with history. In hindsight "simplify" in the title was a bad choice of words :)

For 1 I was hoping for more native go tooling and thereby being able to use dependabot to bump ginkgo etc. This would automatically notify us of new versions and possible breakages. But I understand the reasoning behind the change now.

What I liked about [test-infra](https://github.com/kubernetes/test-infra/blob/master/Makefile) and [k/k](https://github.com/kubernetes/kubernetes/blob/master/build/root/Makefile) is their shortness. It's easy to overview, find what you're looking for with all scripts in the same folder, and requires minimal make knowledge. In practice they have pushed the complexity from Make to the shell scripts. But I find make a little tricky so I like that.

I also liked how [capos defines versions](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/versions.mk) and other [common functionality](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/common.mk) in separate files. So no need for a capd Makefile again :)
