### ISSUE TITLE
Pin GitHub actions to commit SHAs

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7466]
It would be great if we can pin our GitHub actions to specific commits instead of just to tags.

Recently a feature was added to dependabot ([link](https://github.com/dependabot/dependabot-core/issues/4691?notification_referrer_id=NT_kwDOAEckWLIzMDM3MzE5MTIwOjQ2NjIzNjA#issuecomment-1296532496)) which makes it possible to bump actions even if they are referencing commit SHAs.

I would suggest to use the following format:
```yaml
   - uses: actions/checkout@01aecccf739ca6ff86c0539fbc67a7a5007bbc81 # tag=v2.1.0
```

Notes:
* We should be able to get the commit SHA's by simply taking them from the tags/releases that we currently use.

/kind feature

**Comment by LuBingtan** [comment]
Hi, I'd like to open a PR for this issue
/assign

**Comment by LuBingtan** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/7502  PTAL :smile:
Thanks!

**Comment by sbueringer** [comment]
Thx!

Thx & kudos to @naveensrinivasan for bringing this up initially via https://github.com/kubernetes-sigs/cluster-api/pull/6341
