### ISSUE TITLE
Setup github team and slack alias for the release team

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#7476]
**Detailed Description:**
For the newly created release team for v1.4 cycle lets create a github team and a slack alias for the team.

Part of #7389

/assign

**Comment by ykakarap** [comment]
* PR for github team: https://github.com/kubernetes/org/pull/3802
* PR for slack alias: https://github.com/kubernetes/community/pull/6920

**Comment by sbueringer** [comment]
Final tasks:
* https://github.com/kubernetes/org/pull/3827
* https://github.com/kubernetes/community/pull/6962

**Comment by sbueringer** [comment]
PRs all merged

Thx for taking care of this!

/close
