### ISSUE TITLE
machine Status.Phase always Failed if FailureReason or FailureMessage is set

### ISSUE THREAD

**Issue by aanoaa** [kubernetes-sigs/cluster-api#7477]
**User Story**

After provider controller set machine's `Status.FailureReason` and `Status.FailureMessage`, machine `Status.Phase` is always `Failed`

**Detailed Description**

The failure can be solved while reconcile loops.
At this point, should controller clean the machine `Status.FailureReason` and `Status.FailureMessage`?

I think failure message is useful for debugging.

If the Running condition takes precedence over the Failed condition,
I think it'll be better.

<https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/machine/machine_controller_phases.go#L50>

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by killianmuldoon** [comment]
This is the intended semantics of the FailureMessage and FailureReason - they correspond to irreversible failure of some kind. If you'd like to make errors visible in the Machine object it's a good idea to set them in a Message in a condition on the Machine object.

**Comment by fabriziopandini** [comment]
this seems a duplicate of https://github.com/kubernetes-sigs/cluster-api/issues/7191
should we close/dedup?

**Comment by aanoaa** [comment]
I set FailureReason and FailureMessage only on fatal errors.
and using status.conditions on recoverable errors.
thanks.
