### ISSUE TITLE
Default cache sync period changed to 10 Hrs after moving to CRDs

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api#748]
/kind bug

**What steps did you take and what happened:**
Pre CRD implementation of the cluster-api had the cache sync period set to few sec. After the move to CRD based implementation the cache sync period has been changed to 10 Hrs. 
This behavior change ***may*** have an impact on the various provider implementation.
For the following use case I think all providers would be impacted:
If the underlying VM is deleted directly from the infrastructure, then that VM will not get re-created by the relevant actuator until the next resync happens (currently 10 hrs) . Pre CRD the lost VM would have been recreated pretty quickly.

**What did you expect to happen:**
The cache resync to happen every x sec instead of hrs (behavior should not have changed)

**Anything else you would like to add:**
The solution for this right now is to override the default in each provider implementation

Thanks to @dlipovetsky as he helped locate these default value for this resync period defined in the controller-runtime code [here](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/cache/cache.go#L88)

For each provider the way to override this is to provide `SyncPeriod` property in the `manager.Options` struct. For e.g. for the vsphere provider the `cmd.go` file that instantiates the controller inside the provider code should be something like:
```
import "sigs.k8s.io/controller-runtime/pkg/manager"
...
var syncPeriod = 60 * time.Second
// Create a new Cmd to provide shared dependencies and start components
mgr, err := manager.New(cfg, manager.Options{SyncPeriod: &(syncPeriod)})
```

Considering that this change needs to be done on each provider implementation independently, I think we should document this behavior change, with recommended value for the sync period for any new providers that may get written in the future.

**Comment by alvaroaleman** [comment]
Wouldn't the right approach here be to have informers on the node object and enq the corresponding machine when the value of the node objects `Ready` condition changes instead of unconditionally checking at the provider?

The latter may be especially problematic when working with a provider that does rate limiting.

**Comment by detiber** [comment]
@alvaroaleman I think it would depend on the provider implementation, there could still be value in reconciling the actual state of the external api to sync with the providerStatus for example.

**Comment by vincepri** [comment]
Given that this might be a light breaking change for some providers, I'm moving the milestone to Next, feel free to change it if it's important for v1alpha1. 

/milestone Next

**Comment by vincepri** [comment]
This should be safe to close now that the internal is back to 10m.

/close
