### ISSUE TITLE
Create mock Provider for testing core Controllers

### ISSUE THREAD

**Issue by pablochacin** [kubernetes-sigs/cluster-api#749]
/kind feature

It was suggested in a meeting that for testing the core controllers (e.g. cluster, machineset) it would be useful to have a mock provider. 

The actual functionality was not discussed, but it was suggested it could use some simple persistence like files for storing state (e.g. "clusters" and "machines").

**Comment by pablochacin** [comment]
I volunteer to implement this feature.

**Comment by vincepri** [comment]
Related to #11, sync up with @figo which also expressed interest.

Question: can the mock provider be KIND?

/milestone v1alpha1
/priority important-longterm
/help

**Comment by pablochacin** [comment]
@vincepri such kind provider has been discussed in the kind project, but it would require some changes in kind core implementation, which are still unclear. [There's an issue](https://github.com/kubernetes-sigs/kind/issues/276) for discussing such requirements.

**Comment by figo** [comment]
this should be covered by PR 755: https://github.com/kubernetes-sigs/cluster-api/pull/755
