### ISSUE TITLE
Support configuring the e2e test image name using a variable

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api#7501]
**User Story**

As a developer, I would like to be able to run the e2e tests using `make test-e2e` or `./scripts/ci-e2e.sh` using a custom image name and tag rather than having it be hard coded to `gcr.io/k8s-staging-cluster-api/cluster-api-controller-{ARCH}:dev`. 

**Detailed Description**

I'm building a pipeline that builds the CAPI images with a custom image name, and I'd like to be able to validate them locally before pushing to my registry. Currently, I'm manually retagging all of them to match the `gcr.io/...` image names, but it can cause confusion in the logs as others might assume it's not actually testing the images we've built. I'd like to be able to specify the input image names to use in `make test-e2e` similar to how I can specify the output images to use in `make docker-build-*` and maintain the behavior of running the e2e tests completely locally. We could define the image name with an existing pattern like `$(CONTROLLER_IMG)-$(ARCH):$(TAG)`. I believe this would be useful going forward for any CAPI user or developer who wants to build, validate, and publish images themselves.

/kind feature

**Comment by Jont828** [comment]
@CecileRobertMichon

**Comment by fabriziopandini** [comment]
I kind of remember discussing this recently in some other threads but I can't find them now, but this is hard to achieve because image name should be consistent in a couple of places (test config, scripts running tests in ci, makefiles running tests locally, also probably tilt, but not 100% sure), and there is no way to ensure a clean flow of this information given all the possible scenarios/different entry points to the process: CI, running testing locally, debugging tests with tilt.

Given that we currently suggest a different approach, which is to use well-known names + retag before pushing to a repository.

**Comment by sbueringer** [comment]
I 100% agree with Fabrizio. In addition, our scripts / Makefile / ... are already complex and hard to maintain. I think this would add additional complexity and I'm not sure if adding more complexity is worth it in this case.

I think if you want to use your own images you can also build the images in the way you want and then use your own e2e config file with `replacements`.

**Comment by sbueringer** [comment]
> @fabriziopandini @sbueringer the CAPZ e2e test allows doing this with just this line https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/Makefile#L661, would that be an acceptable add?

Would definitely reduce the scope from having it parameterizable through the entire chain (starting with script/ci-e2e.sh that we only use in Prow) to only the make target. (and having to keep that entire chain working over time).

I think we would need this 4x as we have 4 images in core CAPI e2e tests.

> Another thought: would it be enough if to run make set-manifest-image (https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L1026) to modify the image in ./config/default/manager_image_patch.yaml before running e2e since the e2e config file uses config/default to install CAPI at vNext?

I think you could try it. We are also doing this when we run `make docker-build-e2e` to change to the dev images. 

Could be that the only other thing that's not sync after this is the `images` field in docker.yaml

**Comment by fabriziopandini** [comment]
We are going down the rabbit hole...

A change in the makefile you will generate images with the new name, but then CI will fail because of old names hard-coded in https://github.com/kubernetes-sigs/cluster-api/blob/4484e6b5a3a33d714f82b43fc7130b7bed5da482/test/e2e/config/docker.yaml#L12-L27 and https://github.com/kubernetes-sigs/cluster-api/blob/4484e6b5a3a33d714f82b43fc7130b7bed5da482/scripts/ci-e2e-lib.sh#L23-L25 and probably somewhere else... The trick is to get this working consistently for all the supported way to run tests:  CI, running testing locally, debugging tests with tilt

**Comment by sbueringer** [comment]
The docker.yaml part should be only relevant if you don't push the images. If you push them to a registry the `tryLoad` doesn't have to load them.

**Comment by fabriziopandini** [comment]
> The docker.yaml part should be only relevant if you don't push the images. If you push them to a registry the tryLoad doesn't have to load them.

It will make a couple of tests to fail locally, e.g. self hosted

**Comment by CecileRobertMichon** [comment]
For docker.yaml

If tryLoad fails that's okay, it doesn't fail the overall test. If the images are available to be pulled from the registry even self-hosted test should pass.

For ci-e2e-lib.sh

We could just change those bash exports to default instead, eg.
` export REGISTRY="${REGISTRY:-"gcr.io/k8s-staging-cluster-api"}"`

**Comment by fabriziopandini** [comment]
> If the images are available to be pulled from the registry even self-hosted test should pass.

This doesn't work for docker in docker, because containerd inside workers cannot pull images from the docker instance in the host

**Comment by sbueringer** [comment]
Theoretically yes, but the self hosted test with Docker is using "load image". And it loads it from the locker docker engine.

Image names are taken from docker.yaml | images

**Comment by CecileRobertMichon** [comment]
Ah that's unfortunate 😓 I think that's why we had to fork the self-hosted thest in CAPZ https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/test/e2e/azure_selfhosted.go (loading the image doesn't work for anything that isn't kind). 

@Jont828 would you able to test with `make set-manifest-image` and seeing what breaks? If we just have to skip the self-hosted cluster test for now, then look into how we can make it work for all providers, not just docker, that could be a practical way forward. I'm not convinced we actually need any changes in `ci-e2e-lib.sh` since we're not actually building/pushing images.

**Comment by sbueringer** [comment]
> I think that's why we had to fork the self-hosted thest in CAPZ

Nope, should be all properly branched

**Comment by sbueringer** [comment]
IIRC CAPA uploads controller images before they trigger our test spec, but they are using it

**Comment by CecileRobertMichon** [comment]
Aah you're right, looks like it was introduced in https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/1aa9837cd2f9d9efe4e4eaceacb22a1b55e13969#diff-b3030e822260e7cdffc1567e8416af8e9e915d7d6830f7b92078e2e51a4dbcbaR52, something to do with moving the AzureClusterIdentity to the workload cluster that wasn't working at the time if I remember correctly... We should re-evaluate whether that's still needed 🤔

**Comment by Jont828** [comment]
I ran `make docker-build REGISTRY=jont828 PULL_POLICY=IfNotPresent` which also calls `make set-manifest-image` and it looks like it doesn't change anything in the `docker.yaml` file that Fabrizio pointed out.

**Comment by fabriziopandini** [comment]
just a data point
since one of the scenarios debugging E2E with tilt which rebuilds stuff at every change, pushing images to a remote repository could really slow down the dev process...

**Comment by Jont828** [comment]
I'd keep the existing behavior where we bypass pulling the image by having `PULL_POLICY=IfNotPresent` and having the image available locally. I was just hoping to allow us to customize the name of the image we expect to be present after running `make docker-build-e2e` so that folks can have a way to easily validate images they're building themselves, say for a custom fork.

**Comment by sbueringer** [comment]
I would have expected that after you run `make docker-build REGISTRY=jont828 PULL_POLICY=IfNotPresent` the YAML files for kustomize are modified to use your image name.

This should only leave the docker.yaml file which expects the other image names. But this should only produce **warnings** during e2e test. So then this should only leave tests which read the images from the e2e config / docker.yaml, which afaik is only the self-hosted test.

I'm not sure from your comments what currently works or doesn't work to be honest :)

If I'm right we could potential solve this by allowing to configure multiple e2e config files and just simply merging them (some straightforward YAML merge, last one wins, like values.yaml in Helm)

**Comment by fabriziopandini** [comment]
Trying to catch up on this thread.

> I was just hoping to allow us to customize the name of the image we expect to be present after running make docker-build-e2e so that folks can have a way to easily validate images they're building themselves, say for a custom fork.

What prevents users to validate their custom forks locally using gcr.io/k8s-staging-cluster-api/...:dev as a name? 
FYI This is how I validate all my local work, the important thing is to build the code I'm developing, the image repository and the tag are just not relevant.

Trying to rephrase a little bit, does the effort to allow custom names makes sense for a scenario where we are just building temporary images (and when using tilt, also refreshing them very quickly)?

> f I'm right we could potentially solve this by allowing to configure multiple e2e config files and just simply merging them
 
Q: do we really need to allow multiple e2e config files? if a new one must be provided, it could replace the old one so everything just works out of the box now. Can this be a viable solution?

**Comment by fabriziopandini** [comment]
/triage needs-information
while we discuss the right way forward

**Comment by sbueringer** [comment]
> > If I'm right we could potentially solve this by allowing to configure multiple e2e config files and just simply merging them

> Q: do we really need to allow multiple e2e config files? if a new one must be provided, it could replace the old one so everything just works out of the box now. Can this be a viable solution?

Sure it definitely works as well. It was just a suggestion to improve on what was mentioned above:

> > You can build the images in the way you want and then use your own e2e config file with replacements.
> 
> This works too but it requires forking the entire config file which isn't ideal if the only thing to change is the image/tag.
> https://github.com/kubernetes-sigs/cluster-api/issues/7501#issuecomment-1305933662

**Comment by fabriziopandini** [comment]
@Jont828 is this still a thing worth working on, I don't see progress since Jan 2023
Otherwise I'm leaning towards closing in a few weeks

**Comment by sbueringer** [comment]
I think it's still an open question if we want to support something like this (it's not just that we have to implement it, we also have to keep it stable without having proper test coverage for it)

**Comment by fabriziopandini** [comment]
personally, I'm -1 as I have already expressed in:

> Trying to rephrase a little bit, does the effort to allow custom names makes sense for a scenario where we are just building temporary images (and when using tilt, also refreshing them very quickly)?

but ultimately it boils up to having people committed to making this happen, and given the lack of progress in the last year, I see wider interest in supporting this idea.

let's give some time more, and then close. 
we can eventually re-open in future or create a new issue if people interesting in carrying over this work shows up

**Comment by sbueringer** [comment]
I think then we should remove help wanted: https://github.com/kubernetes-sigs/cluster-api/issues/7501#issuecomment-1477513389

> Please ensure that the issue body includes answers to the following questions:
> 
> Why are we solving this issue?
> To address this issue, are there any code changes? If there are code changes, what needs to be done in the code and what > places can the assignee treat as reference points?
> Does this issue have zero to low barrier of entry?
> How can the assignee reach out to you for help?

**Comment by Jont828** [comment]
I'm fine with closing for now since, as you guys mentioned, the image names are hard coded in several places. It's been a while but I remember that my use case then was that I needed to build the CAPI images, push them to a registry, and run the CAPI e2e tests. 

For anyone else who needs to do this, my workaround was just to run `make docker-build-e2e`, rename/push the images, pull the images, and rename them back to gcr.io (might have needed to run `make set-manifest` but can't recall exactly).
