### ISSUE TITLE
self-hosted E2E tests should also make sure that `clusterctl` does not own any fields at the end of the move operation

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#7510]
**Detailed Description**

https://github.com/kubernetes-sigs/cluster-api/pull/7504 fixes the issue that `clusterctl move` takes ownership of all the fields of the clusters causing  potential ownership conflicts.
The E2E tests should now also make sure to check that the `clusterctl move` operation not give `clusterctl` ownership of any of the fields.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind test

/assign

**Comment by fabriziopandini** [comment]
/triage accepted
/milestone v1.3

I will put this in the 1.3 milestone given that this can merge also after RC, but we can eventually reconsider if we don't have bandwidth
