### ISSUE TITLE
Expose additional MachineDeployment fields in ClusterClass and Cluster Topology

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#7519]
Currently CAPI exposes a number of fields to specify the config of the MachineDeployment in the Cluster Topology and ClusterClass, while the core MachineDeployment struct has a few fields that aren't exposed in either.

We should add the missing fields to both MachineDeploymentTopology and MachineDeploymentClass where appropriate to enable topology users to configure their MachineDeployments in the same way across topology-managed and topology-unmanaged clusters.

The MachineDeploymentTopology is missing the following fields when compared with MachineDeploymentSpec:
```
        ProgressDeadlineSeconds *int32 `json:"progressDeadlineSeconds,omitempty"`
        RevisionHistoryLimit *int32 `json:"revisionHistoryLimit,omitempty"`
```
The MachineDeploymentClass is missing the following fields when compared with MachineDeploymentTopology:
```
	Strategy *MachineDeploymentStrategy `json:"strategy,omitempty"`
	MinReadySeconds *int32 `json:"minReadySeconds,omitempty"`
        FailureDomain *string `json:"failureDomain,omitempty"`
        NodeDrainTimeout *metav1.Duration `json:"nodeDrainTimeout,omitempty"`
	NodeVolumeDetachTimeout *metav1.Duration `json:"nodeVolumeDetachTimeout,omitempty"`
	NodeDeletionTimeout *metav1.Duration `json:"nodeDeletionTimeout,omitempty"`
```

**Note** I've omitted some fields above that IMO don't make any sense to include - e.g. Paused, Selector, Template, ClusterName, replicas, version, etc.

My idea is to expose everything that's currently available on the MachineDeploymentTopology in the MachineDeploymentClass. That means adding:

```
        Strategy *MachineDeploymentStrategy `json:"strategy,omitempty"`
	MinReadySeconds *int32 `json:"minReadySeconds,omitempty"`
        FailureDomain *string `json:"failureDomain,omitempty"`
        NodeDrainTimeout *metav1.Duration `json:"nodeDrainTimeout,omitempty"`
	NodeVolumeDetachTimeout *metav1.Duration `json:"nodeVolumeDetachTimeout,omitempty"`
	NodeDeletionTimeout *metav1.Duration `json:"nodeDeletionTimeout,omitempty"`
```

Additionally we should consider exposing the following fields from the MachineDeployment in both the MachineDeploymentClass and MachineDeploymentTopology:

```
        ProgressDeadlineSeconds *int32 `json:"progressDeadlineSeconds,omitempty"`
        RevisionHistoryLimit *int32 `json:"revisionHistoryLimit,omitempty"`
```

/kind feature
@sbueringer @fabriziopandini WDYT?

**Comment by fabriziopandini** [comment]
/triage accepted
/area topology
/help

I think we can break down this into 2 parts and start exposing everything that's currently available on the MachineDeploymentTopology in the MachineDeploymentClass
We can eventually tackle ProgressDeadlineSeconds and RevisionHistoryLimit in a follow up iteration
