### ISSUE TITLE
Expose additional Control Plane fields in ClusterClass

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#7520]
Currently CAPI exposes a number of fields to specify the config of the Control Plane and its underlying machines in the Cluster Topology and ClusterClass.

[The Control Plane contract shows the following fields as required](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/control-plane.html). There is some variation depending on whether replicas and underlying machineInfrastructure is supported, but this is already accounted for in the topology implementation.

```
    replicas
    version
    machineTemplate
    machineTemplate.metadata
    machineTemplate.metadata.labels
    machineTemplate.metadata.annotations
    machineTemplate.infrastructureRef
    machineTemplate.nodeDrainTimeout
    machineTemplate.nodeVolumeDetachTimeout
    machineTemplate.nodeDeletionTimeout
```

The ControlPlaneTopology currently exposes all of these in some sense. The ControlPlaneClass (set in the ClusterClass) has the following missing fields when compared with ControlPlaneTopology:

```
	NodeDrainTimeout *metav1.Duration `json:"nodeDrainTimeout,omitempty"`
	NodeVolumeDetachTimeout *metav1.Duration `json:"nodeVolumeDetachTimeout,omitempty"`
	NodeDeletionTimeout *metav1.Duration `json:"nodeDeletionTimeout,omitempty"`
```

IMO we should expose these fields in the ControlPlaneClass object to make them configurable across all Clusters sharing a ClusterClass.

/kind feature
@sbueringer @fabriziopandini WDYT?

**Comment by sbueringer** [comment]
Sounds fine to me in general.

I assume the rules are similar to the MHC fields:


| CC  | Cluster.spec.topology | effective value from  |
|-----|-----------------------|-----------------------|
| -   | -                     | -                     |
| -   | set                   | Cluster.spec.topology |
| set | -                     | CC                    |
| set | set                   | Cluster.spec.topology |

Do we want/need a way to disable the timeouts in Cluster.spec.topolgoy when they are set in the ClusterClass? (we solved this for MHC with the enabled field

**Comment by killianmuldoon** [comment]
My inclination for the timeouts would be to have the topology fields overwrite the class fields - so we set them twice in the controller, first from the class and then from the topology WDYT?

**Comment by fabriziopandini** [comment]
/triage accepted
/area runtime-sdk
/help

+1 from me!
