### ISSUE TITLE
🐛  Topology MachineDeploymentFinalizer not properly applied

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#7530]
When creating a topology-managed cluster of any kind (I replicated with CAPD), create a cluster with MachineDeployments.

After creation the machineDeployment does not have any finalizers. I expected it to have the `MachineDeploymentTopologyFinalizer` - "machinedeployment.topology.cluster.x-k8s.io". The MachineSetTopologyFinalizer is still in place.

This issue is probably related to server-side apply. The current code only adds the Finalizer on creation and each subsequent reconcile of the controller does not add the finalizer. SSA interprets this as intent to drop the finalizer, and it disappears after the first reconcile.

/assign
/area topology
/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
Damn this breaks my heuristic that notifications with icons are always PRs :)
