### ISSUE TITLE
Ensure owner references are correctly re-reconciled 

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#7575]
The test in #https://github.com/kubernetes-sigs/cluster-api/pull/7569 shows that some of the ownerReferences in Cluster API are not correctly re-reconciled if they are removed for any reason. This is an umbrella issue to capture the different cases under which this can happen.

The expectation is that the ownerReference tree should look the same as on cluster creation after being re-reconciled. The following differences can be seen in #7569

1. KCP machines and standalone MachineSets can be wrongly adopted by the Cluster on re-reconcile 
    -  #7591 
3. Secret ownerReferences are not re-rereconciled correctly #6979 
    -  #7587 
    - additional bug fix in https://github.com/kubernetes-sigs/cluster-api/pull/7623
    - #7592 
4. ClusterResourceSet configmap references are not re-reconciled
   - https://github.com/kubernetes-sigs/cluster-api/pull/7590
5. KubeadmConfig and DockerMachines created by a MachineSet are initially created with two OwnerReferences: 1 for the Machine it's linked to and a second for the higher level controlling type or MachineSet.
    - #7593
7. ~~ClusterClass-owned templates are not re-reconciled with their ownerReferences~~ (There is an issue here where the ClusterClass is reconciled infrequently so it takes longer for these references to be re-reconciled. The ownerReference tree is evenually as expected in this case though, as the ClusterClass controller reconciles these references correctly.)
## ClusterClass clusters 
The ownerReference tree on creation:
![owner-references-c28fk6-before](https://user-images.githubusercontent.com/47175296/203111810-8c69126a-893d-4181-b5f3-368507921e79.svg)

The ownerReference tree after removing and re-reconciling:
![owner-references-c28fk6-after](https://user-images.githubusercontent.com/47175296/203112520-60eee1f9-37f3-4a42-bedd-02958c8ddbee.svg)

## Non-ClusterClass clusters
The ownerReference tree on 
![owner-references-mmgybv-before](https://user-images.githubusercontent.com/47175296/203112932-71cde80d-067a-48ea-a896-da47884cf4f0.svg)
creation:

The ownerReference tree after removing and re-reconciling
![owner-references-mmgybv-after](https://user-images.githubusercontent.com/47175296/203112938-a4984692-e8b8-434d-9419-310407902841.svg)

/kind bug

**Comment by sbueringer** [comment]
/triage accepted

@killianmuldoon I'm not sure who is already working on which sub-task. Please let me know if I should take over one of them.

**Comment by fabriziopandini** [comment]
Thanks for this extensive work of research.
Most of this is legacy stuff, like control-plane machines without a control-plane object controlling them, or stand-alone machines. I will trigger some discussion about triggering the process for dropping support for some of this, which is healthy for the entire project.

But, for now, praise for this work making the project more robust and resilient to ownerRefs being accidentally removed.

**Comment by sbueringer** [comment]
>  I will trigger some discussion about triggering the process for dropping support for some of this, which is healthy for the entire project.

Thx.  Absolutely agree. We should continuously try to get rid of things which are not needed anymore.

> But, for now, praise for this work making the project more robust and resilient to ownerRefs being accidentally removed.

+100. Thx @killianmuldoon great work!!

**Comment by sbueringer** [comment]
Looks like  #7587 introduced a bug: https://github.com/kubernetes-sigs/cluster-api/pull/7616/files#r1031946701

**Comment by sbueringer** [comment]
@killianmuldoon Just out of curiosity in case you just know it.

Is the ClusterClass ownerRef tree equivalent to the non-ClusterClass tree just with more ownerRefs for the ClusterClass+referenced templates? (it's a bit hard to diff in the pictures)

**Comment by killianmuldoon** [comment]
All tasks now done - will close this once #7606 is merged.

**Comment by killianmuldoon** [comment]
/close

#7606 is approved
