### ISSUE TITLE
why the worker cluster can't ready?

### ISSUE THREAD

**Issue by andyzheung** [kubernetes-sigs/cluster-api#7588]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

I use the capi : v1.0.0
capv: 1.0.0
management cluster kubernetes: 1.21.0

work cluster:
kubernetes: 1.16.3
![image](https://user-images.githubusercontent.com/22912347/203306536-be83449a-20a7-49d1-81d2-8d790867dd07.png)

![image](https://user-images.githubusercontent.com/22912347/203306622-40894d18-bc3d-477c-8f26-c9f55270dc6b.png)

kubectl logs -n capi-system capi-controller-manager-6bdc78c4d4-rkgk9
all the worker node is error:
![image](https://user-images.githubusercontent.com/22912347/203306865-cfcafc56-470b-41cd-bed5-94b201a1899c.png)
kubectl get machines
![image](https://user-images.githubusercontent.com/22912347/203307143-6c0d6c7d-f240-49b4-a0d7-80c5f99169f5.png)
kubectl logs -n capv-system capv-controller-manager-54b78d8b75-tprmz
![image](https://user-images.githubusercontent.com/22912347/203307406-c3e0eabc-e55a-4b27-bf0b-e9479a5d6808.png)

**What did you expect to happen:**
1、need the work cluster ready all the pod will be running.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
management cluster:
capi : v1.0.0
capv: 1.0.0
management cluster kubernetes: 1.21.0

work cluster: 1.6.3
why use this lower version, because I use 1.21 or above have other problem, 
kubectl describe cluster
![企业微信截图_16691150301564](https://user-images.githubusercontent.com/22912347/203309138-89a4d83c-d965-44f8-9ff6-be06afe86d1c.png)
![企业微信截图_1669115046775](https://user-images.githubusercontent.com/22912347/203309150-18d06a2c-690f-4c72-808b-e893acad89d0.png)
![企业微信截图_16691150623656](https://user-images.githubusercontent.com/22912347/203309167-935e9e79-c155-4fd5-bd82-25b92f4e210e.png)

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by andyzheung** [comment]
I manually untain the node:
taint nodes --all node.cloudprovider.kubernetes.io/uninitialized:NoSchedule-
![image](https://user-images.githubusercontent.com/22912347/203310436-03484888-6576-4481-8d0a-8d05acb939ee.png)
So I have  the following problem:

1、why all the node get taint?
node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
Is related to the log in capi? how to solve it?
![image](https://user-images.githubusercontent.com/22912347/203311444-6c9e5116-3f73-4941-b02d-8f1e4ed644bc.png)

2、csi controller crash:
kubectl logs -n kube-system vsphere-csi-controller-bfd5f675d-6wbmw vsphere-csi-controller
caller":"vsphere/virtualcenter.go:221","msg":"failed to create govmomi client with err: Post https://x.x.x.x:443/sdk: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs"

3、node show is running, but:
 kubectl get machinedeployment 
NAME                               CLUSTER                       REPLICAS   READY   UPDATED   UNAVAILABLE   PHASE       AGE   VERSION
autonomy-rnd-work-cluster-1-md-0   autonomy-rnd-work-cluster-1   3                  3         3             ScalingUp   71m   v1.16.3
kubectl describe machinedeployment autonomy-rnd-work-cluster-1-md-0
![image](https://user-images.githubusercontent.com/22912347/203312405-d8421306-2794-4b11-99f2-07d3b5f19d9f.png)

I think all the questions are coming from the question 1..

following demo-template coming from:
[demo-template.zip](https://github.com/kubernetes-sigs/cluster-api/files/10067269/demo-template.zip)

**Comment by killianmuldoon** [comment]
This might get a more expert response in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere as it seems to be down to something going wrong with the cloudprovider.

As an aside - CAPI v1.0.0 - is out of support, the current supported release is v1.2 so if you can update that would help get you better support

**Comment by andyzheung** [comment]
> 
thx, my management cluster is 1.21.0, can it use CAPI  v1.2?
@killianmuldoon 

about capv problelm can @fabriziopandini help?

**Comment by killianmuldoon** [comment]
Version support information for the core CAPI provider is here:

https://cluster-api.sigs.k8s.io/reference/versions.html#release-components

For CAPV it's here:
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere#compatibility-with-cluster-api-and-kubernetes-versions

**Comment by andyzheung** [comment]
> Version support information for the core CAPI provider is here:
> 
> https://cluster-api.sigs.k8s.io/reference/versions.html#release-components
> 
> For CAPV it's here: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere#compatibility-with-cluster-api-and-kubernetes-versions

that seems my system version is match.
my management cluster is:  1.21.0
CAPI 1.0.0 v1beta1
CAPV 1.0.0 v1beta1
this seem compatible.
but what version of workload cluster kubernetes.
I use :
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere#compatibility-with-cluster-api-and-kubernetes-versions
![image](https://user-images.githubusercontent.com/22912347/203353936-24cbc604-624c-45e5-baad-0d0203a4675c.png)

still have problem above mentioned.

If have recomment ova images and template  to deploy work cluster use the management cluster and CAPI & CAPV above?
I just need to use cluster api to test cluster autoscaler on vmware vsphere...
But meet some trouble....

**Comment by andyzheung** [comment]
if any one run cluster api+ cluster api vsphere + kubernetes, have the detail version and operation instruction?
I think I have  a lot problem so  I just need a running system on vsphere first.

**Comment by srm09** [comment]
@andyzheung
Few things here:
1. The uninitialized taint is removed by the vSphere CPI pods `vsphere-cloud-controller-manager-xxxxxx`. Can you check the logs of the pod to see if there are any obvious errors? 
2. The provider ID is also set by the CPI pods as well, can you check the `kubectl get nodes` output to see if the provider IDs are set correctly?
3. From the pods output on the cluster, it seems like the CSI pods are not fully ready and running. Can you check the output of the `vsphere-csi-controller-xxxx` pods to see what the error there is? I am suspecting that the pod might be unable to reach the vCenter instance.

**Comment by andyzheung** [comment]
> @andyzheung Few things here:
> 
> 1. The uninitialized taint is removed by the vSphere CPI pods `vsphere-cloud-controller-manager-xxxxxx`. Can you check the logs of the pod to see if there are any obvious errors?
> 2. The provider ID is also set by the CPI pods as well, can you check the `kubectl get nodes` output to see if the provider IDs are set correctly?
> 3. From the pods output on the cluster, it seems like the CSI pods are not fully ready and running. Can you check the output of the `vsphere-csi-controller-xxxx` pods to see what the error there is? I am suspecting that the pod might be unable to reach the vCenter instance.
> 
> **Update** Just checked the other comments, you posted the output of the CSI logs, and seems like the vCenter instance is unreachable. I looked at the template zip that you uploaded, and
> 
> ```yaml
> apiVersion: v1
> kind: Secret
> metadata:
>   name: csi-vsphere-config
>   namespace: '${NAMESPACE}'
> stringData:
>   data: |
>     apiVersion: v1
>     kind: Secret
>     metadata:
>       name: csi-vsphere-config
>       namespace: kube-system
>     stringData:
>       csi-vsphere.conf: |+
>         [Global]
>         cluster-id = "${NAMESPACE}/${CLUSTER_NAME}"
>         [VirtualCenter "${VSPHERE_SERVER}"]
>         insecure-flag = "true"            <<<<<======================== Add this here
>         user = "${VSPHERE_USERNAME}"
>         password = "${VSPHERE_PASSWORD}"
>         datacenters = "${VSPHERE_DATACENTER}"
>         [Network]
>         public-network = "${VSPHERE_NETWORK}"
>     type: Opaque
> type: addons.cluster.x-k8s.io/resource-set
> ```
> 
> This should get the CSI pods up and running. And then look at the state of the pods.
--------------------
Thank you so much,  I seems all the problem come from vsphere-controller-manager can't connect to vsphere? 
1、I try add this: insecure-flag = "true" .
2、I check the workload cluster vsphere controller manager--xxx logs, as you say it's really have many errors that I don't care before...
E1123 00:43:49.456930       1 connection.go:177] Failed to create new client. err: Post https://x.x.x.x:443/sdk: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs
E1123 00:43:49.456997       1 connection.go:63] Failed to create govmomi client. err: Post https://x.x.x.x:443/sdk: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs
E1123 00:43:49.457027       1 connectionmanager.go:148] Cannot connect to vCenter with err: Post https://x.x.x.x:443/sdk: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs
E1123 00:43:50.460998       1 connection.go:177] Failed to create new client. err: Post https://x.x.x.x:443/sdk: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs
E1123 00:43:50.461032       1 connection.go:63] Failed to create govmomi client. err: Post https://x.x.x.x:443/sdk: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs
E1123 00:43:50.461044       1 connectionmanager.go:148] Cannot connect to vCenter with err: Post https://x.x.x.x:443/sdk: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs
E1123 00:43:51.469453       1 connection.go:177] Failed to create new client. err: Post https://x.x.x.x:443/sdk: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs
E1123 00:43:51.469469       1 connection.go:63] Failed to create govmomi client. err: Post https://x.x.x.x:443/sdk: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs
E1123 00:43:51.469475       1 connectionmanager.go:148] Cannot connect to vCenter with err: Post https://x.x.x.x:443/sdk: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs

I have add the insecure-flag = "true" ..
@srm09

**Comment by andyzheung** [comment]
The provider ID is also set by the CPI pods as well, can you check the kubectl get nodes output to see if the provider IDs are set correctly?
===>

I didn't see provider ID? not ready is because I have not installed the calico cni..
kubectl get nodes -o wide 
NAME                                                STATUS     ROLES    AGE    VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
xx-rnd-work-cluster-1-gt5xp                   NotReady   master   5h6m   v1.16.3   10.250.8.198   <none>        Ubuntu 18.04.3 LTS   4.15.0-72-generic   containerd://1.3.0
xx-rnd-work-cluster-1-md-0-5b997db8df-bw6gt   NotReady   <none>   5h5m   v1.16.3   10.250.8.199   <none>        Ubuntu 18.04.3 LTS   4.15.0-72-generic   containerd://1.3.0
xx-rnd-work-cluster-1-md-0-5b997db8df-dcj9g   NotReady   <none>   5h5m   v1.16.3   10.250.8.204   <none>        Ubuntu 18.04.3 LTS   4.15.0-72-generic   containerd://1.3.0
xx-rnd-work-cluster-1-md-0-5b997db8df-mslql   NotReady   <none>   5h5m   v1.16.3   10.250.8.203   <none>        Ubuntu 18.04.3 LTS   4.15.0-72-generic   containerd://1.3.0

**Comment by andyzheung** [comment]
Is because I annotation the following?
![image](https://user-images.githubusercontent.com/22912347/203481050-fd0e697c-6cf9-4f17-aa96-5072f3b5b7b9.png)

**Comment by andyzheung** [comment]
> Is because I annotation the following? ![image](https://user-images.githubusercontent.com/22912347/203481050-fd0e697c-6cf9-4f17-aa96-5072f3b5b7b9.png)

really thank you so much, I got the TLS_THUMBPRINT ervery thing is OK when work cluster I use ubuntu-1804-kube-v1.16.3.ova
I will try to use other higher version of kubernetes. @srm09 
![image](https://user-images.githubusercontent.com/22912347/203484764-b827f0b5-cd7f-4589-9730-34d05860decf.png)

**Comment by fabriziopandini** [comment]
/triage accepted
/close
given the comment above
