### ISSUE TITLE
why I can't use the other ova template to create worker cluster.

### ISSUE THREAD

**Issue by andyzheung** [kubernetes-sigs/cluster-api#7597]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

https://github.com/kubernetes-sigs/cluster-api/issues/7588
I have solve the problem to use cluster api to get the cluster autoscaler capiblity for work cluster.
but only use ubuntu-1804-kube-v1.16.3.ova can setup the work cluster and can cluster autoscaler capiblitiy.
I use the ubuntu-1804-kube-v1.21.11.ova and ubuntu-1804-kube-v1.22.8.ova also can't bootstrap the controller plane..

I use this way to upload the ova to the vsphere:
https://medium.com/@abhishek.amjeet/clusterapi-for-kubernetes-a-detailed-look-on-vmware-cluster-api-2ddd541bafa9

I seem that controller vm can't setup...
![image](https://user-images.githubusercontent.com/22912347/203537003-2689b095-4c56-4d86-9ede-58a8d86292b7.png)

kubectl describe machines  controller-plane-node
![image](https://user-images.githubusercontent.com/22912347/203537182-2b204bed-0d4b-494a-8ea6-440c96ac4950.png)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

CAPI: 1.0.0
CAPV: 1.0.0
management cluster: v1.21.0
work cluster ova:   ubuntu-1804-kube-v1.21.11.ova and ubuntu-1804-kube-v1.22.8.ova also can't setup the controller plane..

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

have any idea to get what the problem.. I kubectl get logs for pods but don't find any error..

@srm09

**Comment by sbueringer** [comment]
Please use a Cluster API version which is still in support https://github.com/kubernetes-sigs/cluster-api/blob/main/CONTRIBUTING.md#support-and-guarantees (>= v1.2)

**Comment by andyzheung** [comment]
> **What steps did you take and what happened:** [A clear and concise description on how to REPRODUCE the bug.]
> 
> #7588 I have solve the problem to use cluster api to get the cluster autoscaler capiblity for work cluster. but only use ubuntu-1804-kube-v1.16.3.ova can setup the work cluster and can cluster autoscaler capiblitiy. I use the ubuntu-1804-kube-v1.21.11.ova and ubuntu-1804-kube-v1.22.8.ova also can't bootstrap the controller plane..
> 
> I use this way to upload the ova to the vsphere: https://medium.com/@abhishek.amjeet/clusterapi-for-kubernetes-a-detailed-look-on-vmware-cluster-api-2ddd541bafa9
> 
> I seem that controller vm can't setup... ![image](https://user-images.githubusercontent.com/22912347/203537003-2689b095-4c56-4d86-9ede-58a8d86292b7.png)
> 
> kubectl describe machines controller-plane-node ![image](https://user-images.githubusercontent.com/22912347/203537182-2b204bed-0d4b-494a-8ea6-440c96ac4950.png)
> 
> **Anything else you would like to add:** [Miscellaneous information that will assist in solving the issue.]
> 
> **Environment:**
> 
> CAPI: 1.0.0 CAPV: 1.0.0 management cluster: v1.21.0 work cluster ova: ubuntu-1804-kube-v1.21.11.ova and ubuntu-1804-kube-v1.22.8.ova also can't setup the controller plane..
> 
> /kind bug [One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
> 
> have any idea to get what the problem.. I kubectl get logs for pods but don't find any error..
> 
> @srm09

I try to use ubuntu-1804-kube-v1.19.6.ova it seem ok...
It that related to the management cluster kubernetes version, my management cluster is 1.21.0?

**Comment by andyzheung** [comment]
> 
oh, i will try the new version....

**Comment by fabriziopandini** [comment]
This seems an issue related to CAPV images, please move the issue in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere 
/close
