### ISSUE TITLE
Use suffixes consistently in API constants

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7611]
Follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/7591#discussion_r1029322642

We have a few inconsistencies with how we use suffixes in various constants (I audited all our constants).

### Label constants

As of today the names of our label constants are inconsistent, we have some with:
* a `LabelName` suffix
* a `Label` suffix
* a `NameLabel` suffix

I would suggest to only include a `Name` in the constant name if the label actually contains `name`. In that case we should include it before `Label` and not after.

This is consistent with most of our existing label constants except:

cluster-api/api/v1beta1:
```go
	ClusterLabelName = "cluster.x-k8s.io/cluster-name" # => ClusterNameLabel
	ClusterTopologyMachineDeploymentLabelName = "topology.cluster.x-k8s.io/deployment-name" # => ClusterTopologyMachineDeploymentNameLabel
	ProviderLabelName = "cluster.x-k8s.io/provider" # => ProviderLabel
	MachineControlPlaneLabelName = "cluster.x-k8s.io/control-plane" # => MachineControlPlaneLabel
	MachineSetLabelName = "cluster.x-k8s.io/set-name" # => MachineSetNameLabel
	MachineDeploymentLabelName = "cluster.x-k8s.io/deployment-name" #  => MachineDeploymentNameLabel
```

clusterctl:
```go
	ClusterctlLabelName = "clusterctl.cluster.x-k8s.io" #  => ClusterctlLabel
	ClusterctlCoreLabelName = "clusterctl.cluster.x-k8s.io/core" #  => ClusterctlCoreLabel
	ClusterctlMoveLabelName = "clusterctl.cluster.x-k8s.io/move" #  => ClusterctlMoveLabel
	ClusterctlMoveHierarchyLabelName = "clusterctl.cluster.x-k8s.io/move-hierarchy" #  => ClusterctlMoveHierarchyLabel
```

### Annotation constants

Let's consistently use `Annotation` as a suffix. We only have one annotation where this is not the case:
```go
        DisableMachineCreate = "cluster.x-k8s.io/disable-machine-create" # => DisableMachineCreateAnnotation
```

### Condition and Reason constants

Let's consistently use Condition and Reason as a suffix.

```go
	ExternalRemediationTemplateAvailable ConditionType = "ExternalRemediationTemplateAvailable" # => ExternalRemediationTemplateAvailableCondition
	ExternalRemediationTemplateNotFound = "ExternalRemediationTemplateNotFound" # => ExternalRemediationTemplateNotFoundReason
	ExternalRemediationRequestAvailable ConditionType = "ExternalRemediationRequestAvailable" # => ExternalRemediationRequestAvailableCondition
	ExternalRemediationRequestCreationFailed = "ExternalRemediationRequestCreationFailed" # => ExternalRemediationRequestCreationFailedReason
```

### How to make the change

I would propose to simply rename the constants in v1.4 and add it to the v1.3=>v1.4 migration doc.
Given that we **do not** modify the constant values this should be fine.

/kind cleanup

**Comment by sbueringer** [comment]
@fabriziopandini WDYT? We can also potentially mark this as help wanted.

**Comment by chiukapoor** [comment]
I would like to work on this issue.

**Comment by sbueringer** [comment]
Sounds good, but let's please wait for confirmation from Fabrizio when he's got to it.

**Comment by fabriziopandini** [comment]
/triage accepted

+1 to the approach

**Comment by chiukapoor** [comment]
Thank you @sbueringer for creating the issue and @fabriziopandini for triaging it.

I will update the constant `ClusterLabelName` to `ClusterNameLabel` and raise a WIP PR, for initial review before I proceed with the rest of the inconsistent constants.

/assign

**Comment by chiukapoor** [comment]
Updated the constant `ClusterLabelName` to `ClusterNameLabel`, executed the test using `make test` [passed], and created a WIP PR.

**Comment by sbueringer** [comment]
/reopen
For migration doc

**Comment by furkatgofurov7** [comment]
@sbueringer hey! So, documenting the changes in migration doc is missing to close this? 

/help
/kind documentation

**Comment by sbueringer** [comment]
@furkatgofurov7 yes

**Comment by sbueringer** [comment]
@chiukapoor the doc has been created now, in case you want to take over the doc part as well

**Comment by furkatgofurov7** [comment]
@chiukapoor the doc we need to document it: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/developer/providers/v1.3-to-v1.4.md

**Comment by chiukapoor** [comment]
Sure, @sbueringer @furkatgofurov7 will take over the task.

Just wanted to clarify, the changes will be documented under `Removals` sections?

**Comment by furkatgofurov7** [comment]
> Sure, @sbueringer @furkatgofurov7 will take over the task.
> 
> Just wanted to clarify, the changes will be documented under `Removals` sections?

Maybe in `Other` section, the PR was more of a renaming constants, but @sbueringer can confirm

**Comment by sbueringer** [comment]
Should go under `### API Changes`

**Comment by furkatgofurov7** [comment]
@chiukapoor hi! 
Are you still interested in this and would have some time to send a documentation PR so that we can close this issue?

**Comment by sbueringer** [comment]
@chiukapoor *friendly reminder*
