### ISSUE TITLE
Support for output flag for generate command.

### ISSUE THREAD

**Issue by Rohitrajak1807** [kubernetes-sigs/cluster-api#7612]
**User Story**

As a developer on [Arlon project](https://github.com/arlonproj/arlon/) I would like to have an `--output` flag for `clusterctl generate ...` s for a dependency on `clusterctl`. Arlon depends on clusterctl and needs wrappers around certain commands for which, we import the `cobraCommand` from `clusterctl` code, for now, we have to reimplement the `generate cluster` subcommand so that we can write the generated manifest to a file. However, this solution becomes fragile if the code for `clusterctl generate cluster` changes, so having an `--output` flag makes `clusterctl` very easy to consume.

**Detailed Description**

Now we generate a cluster manifest using the command `clusterctl generate cluster test-aws --kubernetes-version 1.23.11 --flavor eks` (say), this will output to STDOUT and requires a redirection to write it to a file. This behaviour is very intuitive if `clusterctl` is being used as a CLI, but makes the `cobra.Command` rather difficult to consume as a library.

An output flag as shown below would make this seamless.
```
clusterctl generate cluster test-aws --kubernetes-version 1.23.11 --flavor eks --output eks.yaml
```

OR

```
clusterctl generate cluster test-aws --kubernetes-version 1.23.11 --flavor eks -o eks.yaml
```

/kind feature

**Comment by sbueringer** [comment]
In general this sounds fine to me.

I just wouldn't use `--output / -o` as flag name / shortcut as a lot of folks in the Kubernetes ecosystem are used to kubectl and there it's used in a different way.

**Comment by fabriziopandini** [comment]
Sure, feel free to assign yourself to the issue; there is still some work to be done to get to an agreement about the solution, but this can be part of your work

**Comment by Rohitrajak1807** [comment]
> Sure, feel free to assign yourself to the issue; there is still some work to be done to get to an agreement about the solution, but this can be part of your work

I can't seem to assign it to me. Can you guide me on the process of doing it? Contributing guide mentions a CLA, but that's done when the PR is created. Is there something else that needs to be done beforehand?

**Comment by sbueringer** [comment]
@Rohitrajak1807 You have to write `/assign` in a comment on this issue
