### ISSUE TITLE
Use latest kind image in CAPD e2e tests

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7620]
We bumped to kind v0.17.0 a while back. Let's align the images used in CAPD to use the images published by kind v0.17.0 (can be seen here: https://github.com/kubernetes-sigs/kind/releases/tag/v0.17.0)

Notably:
* 1.25: kindest/node:v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1
* 1.24: kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315

To be clear this change is not absolutely mandatory, but I think it's better to use the kindest/node images from the corresponding kind version that we use and not from some older kind version.

/kind cleanup
/assign

**Comment by fabriziopandini** [comment]
Thanks for this change!
What about tracking this somehow on our release task list, so we periodically check we are running recent images? 
cc @sbueringer @ykakarap 
/lgtm
/approve
