### ISSUE TITLE
Cluster API and cgroups v2

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7622]
Goal of this issue for now is to figure out where we stand regarding cgroups v2 and if there's anything to do and by whom.

## Context

* cgroups v2 was recently graduated to GA in Kubernetes v1.25: https://kubernetes.io/blog/2022/08/31/cgroupv2-ga-1-25/ 
* It is recommended to use [cgroups v2](https://kubernetes.io/blog/2022/08/31/cgroupv2-ga-1-25/#what-is-cgroup-v2) if possible
* cgroups v2 requires an up-to-date operating system ([Requirements](https://kubernetes.io/docs/concepts/architecture/cgroups/#requirements))
  * OS distribution enables cgroup v2
  * Linux Kernel version is 5.8 or later
  * [Linux Distribution cgroup v2 support](https://kubernetes.io/docs/concepts/architecture/cgroups/#linux-distribution-cgroup-v2-support)
  * Container runtime supports cgroup v2. For example: [containerd](https://containerd.io/) v1.4 and later, or [cri-o](https://cri-o.io/) v1.20 and later
  * The kubelet and the container runtime are configured to use the [systemd cgroup driver](https://kubernetes.io/docs/setup/production-environment/container-runtimes#systemd-cgroup-driver)
    * This is default in Cluster API since Kubernetes v1.21 and in CAPD since v1.24
* Afaik the upstream k/k test coverage is focused on cgroups v2 and while there is no date yet cgroups v1 support will be eventually removed.
* Documentation: [blog post](https://kubernetes.io/blog/2022/08/31/cgroupv2-ga-1-25/), [docs](https://kubernetes.io/docs/concepts/architecture/cgroups/)
* cgroups version can be identified via: `stat -fc %T /sys/fs/cgroup/` (`cgroup2fs` => v2, `tmpfs` => v1) ([docs](https://kubernetes.io/docs/concepts/architecture/cgroups/#check-cgroup-version))

### core Cluster API

* supports cgroups v2 without special handling
* systemd cgroupDriver is enabled per default since Kubernetes v1.21

### Providers / image-builder

* not sure overall, but specifically for Ubuntu it's recommened to use at least Ubuntu 22.04 (which also enables cgroups v2 per default)
* there is an issue in image-builder to add support for Ubuntu 22.04: https://github.com/kubernetes-sigs/image-builder/issues/960
  * today only CAPZ and CAPOCI have Ubuntu 22.04 support in image-builder.
  * Providers in general should support cgroups v2 as there usually isn't any specific handling needed.
  * It's mostly about providing images out-of-the-box via image-builder.
  * Although I think it's important that the providers which are release-informing for k/k align the cgroup version they use for their tests to k/k

### CAPD

* systemd cgroupDriver is enabled per default since Kubernetes v1.24
  * the systemd cgroup driver wasn't supported before by the kind image we use
* kind / CAPD inherits the cgroup driver from the underlying Docker engine, examples:
  * macOS with Docker Desktop:
    * `docker info | grep "Cgroup Version"` => `Cgroup Version: 2`
    * `docker exec` + `stat -fc %T /sys/fs/cgroup/` => `cgroup2fs`
  * CI in Prow:
    * [docker info](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1594941496929292288/artifacts/localhost/docker-info.txt): `Cgroup Version: 1`
    * [journal.log](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1594941496929292288/artifacts/clusters/quick-start-9dnalg/machines/quick-start-9dnalg-control-plane-lrpwv/journal.log) => `System is tainted: cgroupsv1` ([tainted kernels](https://docs.kernel.org/admin-guide/tainted-kernels.html))

=> In my opinion there's nothing to do for CAPD, we regularly use it with cgroups v1 and v2 and it just works (we didn't even notice the difference)

**Comment by fabriziopandini** [comment]
/triage accepted
Thanks for this research!
I think the only missing bit is to ask in test-infra if/how we can enable cgroups v2 in prow machines where we run CAPD.

**Comment by sbueringer** [comment]
I'll ask in Slack if that's something doable.

**Comment by mtougeron** [comment]
We need to be careful with enabling cgroups v2 in kubernetes < 1.24 as the version of cAdvisor is definitely broken. In 1.24 it is a compatible version of cAdvisor but cgroups v2 still isn't GA until kubernetes 1.25. The general advice I've gotten (though it is anecdotal) is to not run cgroups v2 until kubernetes 1.25.

**Comment by sbueringer** [comment]
Thx for the info! To provide a bit more information:
> If you run [cAdvisor](https://github.com/google/cadvisor) as a stand-alone DaemonSet for monitoring pods and containers, update it to v0.43.0 or later.
> https://kubernetes.io/docs/concepts/architecture/cgroups/#migrating-cgroupv2

In general I would recommend reading the entire doc, a lot of useful information there.

**Comment by mtougeron** [comment]
yeah. But that doesn't help kubelet's built in node pressure work properly. It would help things like metrics-service and monitoring though.

**Comment by sbueringer** [comment]
> I think the only missing bit is to ask in test-infra if/how we can enable cgroups v2 in prow machines where we run CAPD.

Based on the Slack thread, I don't think we should invest in migrating the Prow CI cluster to cgroups v2.
