### ISSUE TITLE
clusterctl backup does not backup worker node CRs

### ISSUE THREAD

**Issue by AxiomSamarth** [kubernetes-sigs/cluster-api#7625]
**What steps did you take and what happened:**
I am backing up and restoring target clusters from one management cluster to another. I ran

`clusterct.exe backup --kubeconfig <path-to-kubeconfig> --directory <path-to-cr-file-dump-directory>`

However, I do not see the `machinedeployment`, `machinset`, `machines`, `kubeadmconfig`, provider-specific infrastructure `<provider>-machine` and `<provider>-virtualmachine` object being backed up. So, when restored, for obvious reasons the worker nodes get recreated freshly which is undesirable. 

**What did you expect to happen:**
I expect that the `machinedeployment`, `machineset`, `machines`, `kubeadmconfig`, `<provider>-machine`, `<provider>-virtualmachine` are to be backed up and restored. So that the target cluster's worker node VMs will be adopted and tracked by the restored machine objects.

**Anything else you would like to add:**
I restored the above missing CRs manually and updated them all with the right ownerreferences , etc keeping the `Cluster` in `paused` state. The VMs got **adopted** by the provider Cluster API pod. Thus, leading to preservation of the already existing worker nodes of the target cluster.

**Environment:**

- Cluster-api version: v1.1.3
- minikube/kind version:
- Kubernetes version: (use `kubectl version`): v1.23.12
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
FYI cluster API 1.1.3 is out of support.
also, FYI https://github.com/kubernetes-sigs/cluster-api/pull/7005 (clusterctl: Add move --to-directory and --from-directory flags, deprecate clusterctl backup and restore) and https://github.com/kubernetes-sigs/cluster-api/pull/7435 (Clarify clusterctl move supported use case and limitations)

In the following doc you can find details about how clusterctl determines what is in scope for move.
https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#move (as far as I remember this is not changed in recent versions, but I didn't double check this in history)

**Comment by AxiomSamarth** [comment]
This is very helpful. Thank you so much @fabriziopandini!
