### ISSUE TITLE
Consider adding the KubeCon Cluster API tutorial to the book

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7633]
I think we should consider adding the KubeCon tutorial to our book (sched: https://kccncna2022.sched.com/event/1BZDs docs: https://github.com/ykakarap/kubecon-na-22-capi-lab).

Disclaimer: Let's wait a bit for now as we currently consider migrating the book to hugo.

I think it would be nice to have the later parts of the tutorial as some sort of advanced section which walks through Cluster API features. I would restrict it to CAPD (at least for the beginning) to keep the maintenance effort a bit down. Main goal would be to showcase Cluster API features and to make it easier for new folks to understand the various features.

Main downside is probably the maintenance effort. It could be okay given that most features are pretty stable so the guide doesn't have to change too much.

Notes:
* I would skip the [Creating your first cluster with Cluster API](https://github.com/ykakarap/kubecon-na-22-capi-lab/blob/main/1-your-first-cluster.md) section as it's pretty much the same as quickstart (although we should check if we can improve the quickstart).
* I think we should drop everything we did to make the tutorial offline-capable. It's not necessary for the book and just makes it more complicated than it has to be.

/kind documentation

**Comment by sbueringer** [comment]
cc @fabriziopandini @killianmuldoon @ykakarap @jackfrancis @shivi28

**Comment by fabriziopandini** [comment]
/triage accepted
/help

huge +1 as soon as we sort out-migration + maintainability discussions

**Comment by sbueringer** [comment]
It's not, but clearly nobody has time to make it happen. So absolutely makes sense to close the issue.
