### ISSUE TITLE
Stop using owner references to determine ClusterResourceSetBinding cluster

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#7669]
The current implementation of the ClusterResourceSetBinding controller [uses the owner references in objectMeta to determine which cluster the resource binding applies to](https://github.com/kubernetes-sigs/cluster-api/blob/5e1d9600e31377b72372db3251607868cfa75c7d/exp/addons/internal/controllers/clusterresourcesetbinding_controller.go#L81).

As a result the ClusterResourceSetBinding requires two ownerReferences - one to the ClusterResourceSet and a second to the Cluster.

Currently the ClusterResourceSetBinding is always named after the Cluster it's associated with, so this name could be used to link the two. Alternatively the ClusterResourceSetBinding `.spec` could contain a clusterName field to link it to the Cluster. The second approach is more stable and explicit IMO.

The approach I'd propose is:
1) add a `clusterName` to the ClusterResourceSetBinding spec
2) use `spec.clusterName` to link ClusterResourceSetBinding to the Cluster's they link to - and use that link to decide when to delete.
3) remove the Cluster owner reference from the ClusterResourceSetBinding

**Comment by sbueringer** [comment]
Sounds fine to me in general.

Do you know when we currently use .spec.clusterName vs the cluster name label?

I think ~ core CRDs are using the spec field? (not sure IIRC)

**Comment by fabriziopandini** [comment]
+1 to add a field; we can infer the value from the ownerRef while dropping it from existing objects.

/triage accepted
/help

**Comment by killianmuldoon** [comment]
>+1 to add a field; we can infer the value from the ownerRef while dropping it from existing objects.

I think we can update the field in the CRS controller to update existing CRSbindings with the new field.

**Comment by chaunceyjiang** [comment]
hi, I'm a newbie. Can I pick up this issues? I'm not sure I can solve it.

**Comment by chaunceyjiang** [comment]
Four Tasks: 
- [ ] add a `clusterName` to the ClusterResourceSetBinding spec.
- [ ] update the field in the CRS controller to update existing CRSbindings with the new field.
- [ ] remove the Cluster owner reference from the ClusterResourceSetBinding.
- [ ] use that link to decide when to delete.

**Comment by killianmuldoon** [comment]
Thanks for volunteering @chaunceyjiang  - I think we're agreed on the approach, so it would be awesome if you could pick this up!

/assign @chaunceyjiang

**Comment by sbueringer** [comment]
@killianmuldoon Can we close this given #7680 has been merged?

**Comment by killianmuldoon** [comment]
Yup - this is fully covered.

Thanks again @chaunceyjiang!

/close
