### ISSUE TITLE
Track CAPI usage

### ISSUE THREAD

**Issue by johananl** [kubernetes-sigs/cluster-api#7670]
## General

It could be useful to find a way to track CAPI usage and adoption by the community, namely to roughly measure how many people use the project and perhaps slice the data using more detailed dimensions.

Some questions which such a solution could help us answer:

- How many people use CAPI in general?
- How many people use each CAPI provider
- How many people use each supported distro?
- Which provider flavors do people use?
- How quickly and how often do people update their clusters?

I'm wondering if a **telemetry** solution could make sense: An optional knob which, when enabled, performs some form of anonymous data collection and shipment to some internet-available service which would in turn store the data and allow interrogation by CAPI maintainers.

Of course, this is an open-source project so any data collection or "phone home" functionality should be **optional** and we should be very aware of security and privacy concerns. We should discuss opt-in vs. opt-out (opt-out is more intrusive but will almost surely result in more data).

/kind feature

**Comment by killianmuldoon** [comment]
Is there any example of a community-owned open source project which has implemented telemetry of this sort? 

I think this would be a very sensitive topic, and it could be useful to discuss it at a community meeting and the mailing list to get an idea of the broader community's opinions.

**Comment by johananl** [comment]
> Is there any example of a community-owned open source project which has implemented telemetry of this sort?

Caddy comes to mind: https://caddy.its-em.ma/v1/docs/telemetry

> I think this would be a very sensitive topic, and it could be useful to discuss it at a community meeting and the mailing list to get an idea of the broader community's opinions.

I agree 100%, and maybe telemetry isn't the only option or the best one. If there are less "intrusive" ways to gain similar insights, even partially, I'd be willing to check them out of course.

**Comment by fabriziopandini** [comment]
/triage accepted
/kind proposal

the idea is interesting, thanks for bringing this up
I think this requires a sort of proposal because what telemetry should do must be fully transparent/well documented, at the end it is a kind of contract with end users.

**Comment by johananl** [comment]
I agree. I wanted to gather very initial feedback on the idea before going into any design discussions. As said above, I'm not 100% telemetry is the best way to go, it's _one_ of the options AFAICT.

**Comment by sbueringer** [comment]
Definitely interesting to have that data. I'm not sure about legal considerations and how we as a community could run the "internet-available service" which collects the data, given that we basically don't own infrastructure.

We also have to clarify how we can staff this feature/service.

Wondering if a non-intrusive way of starting a reference page where folks can add themselve would have at least some of the benefit (of course that would only give us high-level data).


We potentially also could get some of the data by hosting e.g. the component manifests somewhere where we have access to the "pull data". But that's definitely non-trivial effort.

**Comment by johananl** [comment]
Good points @sbueringer. Maybe the CNCF could somehow help with infrastructure?

But I think the first step should indeed be figuring out if we're even able to collect telemetry data and are willing to do so after evaluating privacy and security concerns as well as user feedback.

**Comment by sbueringer** [comment]
> after evaluating privacy and security concerns as well as user feedback

Yup. I'm not a lawyer so I don't even know which rules even apply or don't apply to an Open Source project.

I'm just even concerned of the possibility that GDPRs rules about personal identifiable information and similar stuff might be relevant. (might be totally irrelevant I just don't know :))

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

There is no traction around this issue and too many open points about what we can do

/close
