### ISSUE TITLE
Updating machineType fails to reconcile MachineDeployments

### ISSUE THREAD

**Issue by thefirstofthe300** [kubernetes-sigs/cluster-api#7674]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
I created a cluster following the guide here: https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-class/write-clusterclass.html#machinedeployment-variable-overrides

This guide patches the instanceType in the AWSMachineTemplate and KubeadmControlPlaneTemplate; however, if this particular value is updated, the CAPA validation hook returns an error stating the spec is immutable (as it should be).

```
Status:
  Conditions:
    Last Transition Time:  2022-11-22T21:05:11Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-11-22T21:00:24Z
    Status:                True
    Type:                  ControlPlaneInitialized
    Last Transition Time:  2022-11-22T21:05:11Z
    Status:                True
    Type:                  ControlPlaneReady
    Last Transition Time:  2022-11-22T20:58:42Z
    Status:                True
    Type:                  InfrastructureReady
    Last Transition Time:  2022-11-26T22:27:19Z
    Message:               error reconciling the Cluster topology: failed to reconcile MachineDeployment/us-west-2-production-default-9bzkp: failed to create patch helper for AWSMachineTemplate/us-west-2-production-default-infra-djg2g: failed to request dry-run server side apply: admission webhook "validation.awsmachinetemplate.infrastructure.x-k8s.io" denied the request: AWSMachineTemplate.Spec is immutable
    Reason:                TopologyReconcileFailed
    Severity:              Error
    Status:                False
    Type:                  TopologyReconciled
  Control Plane Ready:     true
  Failure Domains:
    us-west-2a:
    us-west-2b:
    us-west-2c:
    us-west-2d:
  Infrastructure Ready:  true
  Observed Generation:   3
  Phase:                 Provisioned
Events:
  Type    Reason          Age                    From              Message
  ----    ------          ----                   ----              -------
  Normal  TopologyUpdate  67s (x258698 over 8d)  topology/cluster  Updated "AWSCluster/us-west-2-production-5gzt7"
```

**What did you expect to happen:**
New templates to be created and the cluster updated to use those.

**Environment:**

- Cluster-api version: v1.2.4
- Kubernetes version: (use `kubectl version`): 1.25.4
- OS (e.g. from `/etc/os-release`): Flatcar

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
Which version of CAPA are you using?

**Comment by thefirstofthe300** [comment]
CAPA is v1.5.0

**Comment by sbueringer** [comment]
Providers had to make changes to be compatible with ClusterClass implementation in Cluster API >= v1.2 (see the webhook part of https://cluster-api.sigs.k8s.io/developer/providers/v1.1-to-v1.2.html#required-api-changes-for-providers).

This was done in CAPA v2.0, so you will have to bump CAPA to make this work.
(disclaimer there should be a new CAPA v2.0.2 release ~ today to fix an issue, I would wait for that)

**Comment by thefirstofthe300** [comment]
This does appear to have been fixed with the upgrade.
