### ISSUE TITLE
Enabling Cluster Autoscaler on Classy Cluster Day-1 leads to unpredictable behaviour

### ISSUE THREAD

**Issue by abhijit-dev82** [kubernetes-sigs/cluster-api#7683]
**What steps did you take and what happened:**
Enable Cluster Autoscaler on classy cluster with worker eplicas field set as a Day-1 Op.

**What did you expect to happen:**
This limitaion is already mentioned in the cluster autoscaler Readme.
https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/clusterapi
"Warning: If the Autoscaler is enabled and the replicas field is set for a MachineDeployment or MachineSet the Cluster may enter a broken state where replicas become unpredictable."

**Anything else you would like to add:**
A classy cluster will have "replicas=x" field seton Day-1  and the unpredictable behaviour happens due to the conflict happening in updating in the replicas field in MD between the cluster autoscaler and the cluster topology reconciler.  This limits enabling autoscaler only on Day-0.

**Environment:**

/kind bug

**Comment by enxebre** [comment]
thanks @abhijit-dev82, closing as dup of https://github.com/kubernetes-sigs/cluster-api/issues/7293
