### ISSUE TITLE
Enable retain LGTM after squash on Cluster API repo

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#7697]
Wanted to create a tracking issue for this feature in Prow. [Kubernetes is currently implementing this](https://github.com/kubernetes/test-infra/pull/22663/files) so I can check back in after a while to ensure it's working over there and then open a PR on test-infra to enable it for CAPI.

/assign
/kind feature

**Comment by sbueringer** [comment]
Nice catch & great feature!!

I don't see a reason why it shouldn't work (but of course it's possible).

Given that it's pretty low effort, I would propose to make the change in test-infra now and then just test it.

@killianmuldoon WDYT?

**Comment by killianmuldoon** [comment]
/assign

I'll open a PR
