### ISSUE TITLE
clusterctl fails on commands using existing kubeconfig if auth plugins required

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#770]
/kind bug
/lifecycle active
/assign
/milestone v1alpha1
/priority important-soon

**Comment by detiber** [comment]
This will require re-vendoring cluster-api after https://github.com/kubernetes-sigs/cluster-api/pull/769 merges

**Comment by vincepri** [comment]
/close

Closing now that #769 is merged.
