### ISSUE TITLE
Clusterctl should support management clusters

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#772]
/kind feature

**Describe the solution you'd like**
Clusterctl should be restructured to make bootstrap cluster function as a management cluster. A new option can be provided instead of cleanup to enable pivoting or not. When disabled, both bootstrap cluster cleanup and pivoting of resources should be disabled.

/assign
/lifecycle active

**Comment by timothysc** [comment]
xref: https://github.com/kubernetes-sigs/cluster-api/issues/827

**Comment by ncdc** [comment]
@vincepri do you still want to keep this open?

**Comment by vincepri** [comment]
Yeah I don't see why not, let's punt it to next though.

/milestone Next

**Comment by timothysc** [comment]
Closing, we're going to unify the workflow.
