### ISSUE TITLE
CI failure: CAPI capi-pr-verify-main job is failing consistently 

### ISSUE THREAD

**Issue by furkatgofurov7** [kubernetes-sigs/cluster-api#7736]
Based on testgrid capi-pr-verify-main job started failing consistently for 6 times in a row:  https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-pr-verify-main 

The  error:
```
 make[2]: Leaving directory '/home/prow/go/src/sigs.k8s.io/cluster-api'
GOBIN=/home/prow/go/src/sigs.k8s.io/cluster-api/hack/tools/bin ./scripts/go_install.sh k8s.io/kube-openapi/cmd/openapi-gen openapi-gen 5e7f5fd
go: k8s.io/kube-openapi/cmd/openapi-gen@5e7f5fd: k8s.io/kube-openapi/cmd/openapi-gen@5e7f5fd: invalid version: reading https://proxy.golang.org/k8s.io/kube-openapi/cmd/openapi-gen/@v/5e7f5fd.info: 404 Not Found
	server response: not found: fetch timed out
make[1]: *** [Makefile:1177: /home/prow/go/src/sigs.k8s.io/cluster-api/hack/tools/bin/openapi-gen] Error 1
make[1]: Leaving directory '/home/prow/go/src/sigs.k8s.io/cluster-api'
make: *** [Makefile:247: generate] Error 2
+ EXIT_VALUE=2
+ set +o xtrace
Cleaning up after docker in docker. 
```

**What did you expect to happen:**
Verify main jobs pass successfully

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
It seems open-api package we are pulling seems to be not available and so the job is timing out

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
/remove-kind bug
/kind flake
/triage accepted

Let's keep an eye on it, but this seems a flake
it seems that it failed 6 times in a row in a short time frame from 22:05 CET to 22:34 CET on Dec 12th, then the following runs are back to green. I also tested this locally and everything works.

**Comment by furkatgofurov7** [comment]
> Let's keep an eye on it, but this seems a flake
> the job failed 6 times in a row in a short time frame from 22:05 CET to 22:34 CET on Dec 12th, then the following runs are back to green. I also tested this locally and everything works.

Yes, the last couple of runs are green. Let's keep an eye as you suggested 👍🏼

**Comment by chrischdi** [comment]
Seems to be general issue of proxy.golang.org : https://github.com/golang/go/issues/57185

**Comment by sbueringer** [comment]
> We have rolled out additional mitigations and have not seen any issues in around a week.

From the go issue. Let's wait 1-2 weeks and if we don't see it again I would suggest to close our issue as well for now

**Comment by furkatgofurov7** [comment]
> From the go issue. Let's wait 1-2 weeks and if we don't see it again I would suggest to close our issue as well for now

green for a bit more than a week now:

**Comment by fabriziopandini** [comment]
Thanks for keeping an eye on this!
/close
