### ISSUE TITLE
Support scoped actuators

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#776]
/kind feature

**Describe the solution you'd like**
The AWS and Azure provider are using the concept of a scope actuator. The idea is to have an interface encapsulating functions using a single struct (scope) that'd set the appropriate context and provide basic functionality for providers that use both cluster and machine resources.

**Comment by ncdc** [comment]
@vincepri given our desire to remove actuators, can we close this?

**Comment by vincepri** [comment]
Yep

/close
