### ISSUE TITLE
Define clusterctl goals and non-goals

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#777]
/kind feature

**Describe the solution you'd like**
A common confusion among today's users is clusterctl. The tool provides a quick way to create/delete/validate clusters using a bootstrap cluster (minikube/kind/existing) and pivots resources at the end. After v1alpha1, we should define goals and non-goals for clusterctl and re-work the CLI structure as needed. 

The goal of this issue is to improve UX and have a clear contract on what the utility should/shouldn't do.

**Comment by timothysc** [comment]
I'm going to close this one as in v1alpha3 my hope is to remove the need.
