### ISSUE TITLE
Extend NTP input to support more cloud-init options

### ISSUE THREAD

**Issue by pparshin** [kubernetes-sigs/cluster-api#7806]
**User Story**

As an operator I would like to customize cluster machines' NTP configuration for setting up an NTP daemon correctly.

**Detailed Description**

cloud-init provides extended options to configure NTP such as NTP client name, systemd service name to start and stop the client, configuration template and [others](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#ntp).

kubeadm config defines a limited structure:

```go
// NTP defines input for generated ntp in cloud-init.
type NTP struct {
	// Servers specifies which NTP servers to use
	// +optional
	Servers []string `json:"servers,omitempty"`

	// Enabled specifies whether NTP should be enabled
	// +optional
	Enabled *bool `json:"enabled,omitempty"`
}
```

I would like to extend this structure and add other cloud-init options, e.g.:

```go
// NTP defines input for generated ntp in cloud-init.
type NTP struct {
	// Servers specifies which NTP servers to use
	// +optional
	Servers []string `json:"servers,omitempty"`

	// Enabled specifies whether NTP should be enabled
	// +optional
	Enabled *bool `json:"enabled,omitempty"`

	// Client is a name of an NTP client to use to configure system NTP.
	// When unprovided or `auto` the default client preferred by the distribution will be used.
	// The following built-in client names can be used
	// to override existing configuration defaults: chrony, ntp, ntpdate, systemd-timesyncd
	// +optional
	Client string `json:"client,omitempty"`

	// ClientConfig defines configuration settings or overrides for the NTP client specified
	// +optional
	ClientConfig *NTPClientConfig `json:"clientConfig,omitempty"`
}

// NTPClientConfig defines configuration settings or overrides for the NTP client specified
type NTPClientConfig struct {
	// The systemd or sysvinit service name used to start and stop the NTP client service
	// +optional
	ServiceName string `json:"serviceName,omitempty"`

	// Template specifies the template to use for NTP
	// +optional
	Template string `json:"template,omitempty"`
}
```

**Anything else you would like to add:**

If the proposed feature is good enough, I'll send a pull request.

/kind feature

**Comment by fabriziopandini** [comment]
/triage accepted
I think it will be useful to provide some use cases where those settings are required
As soon as we link these changes to real user needs, I personally don't have objections to adding more knobs to NTP configuration

**Comment by pparshin** [comment]
@fabriziopandini I use specific operating systems to bootstrap machines, for example, ALT Linux which are not supported by cloud-init out of the box:

> Supported distros: almalinux, alpine, centos, cloudlinux, debian, eurolinux, fedora, miraclelinux, openEuler, openmandriva, opensuse, photon, rhel, rocky, sles, ubuntu, virtuozzo

As a result I can't configure ntp via capi. From cloud-init logs:

> RuntimeError: No template found, not rendering chrony.conf.{distro}

Also this distro has systemd unit called `chronyd` when cloud-init expects `chrony`.

I found that cloud-init has options to provide ntp template and systemd service name but capi doesn't support them. Anyway i suspect that my case might be quite rare.

**Comment by fabriziopandini** [comment]
Thanks for the clarification.
As I said I personally don't have objections to adding more knobs to NTP configuration (it is usually something very low maintenance), but let's wait for some more feedback given that this is quite an edge case

**Comment by enxebre** [comment]
Incremental change seems reasonable to me from API pov so I'm not oppose to it either. Though I'm not sure about this is the right path for the end goal. This is basically and enabler to bypass ALT Linux / cloud init support limitation. Is there any effort to fix this in the os distro or in cloud init?

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

As @enxebre suggested probably the right layer to solve this issue is cloud-init 
/close
