### ISSUE TITLE
Runtime Hook implementation guideline is not quite clear

### ISSUE THREAD

**Issue by bavarianbidi** [kubernetes-sigs/cluster-api#7812]
**What steps did you take and what happened:**
I've followed the [Implementation guideline for `Runtime Hooks`](https://cluster-api.sigs.k8s.io/tasks/experimental-features/runtime-sdk/implement-extensions.html) to implement a first version of an own hook.

The current documentation refers to the `test/extension` directory for a full example

> For a full example see our [test extension](https://github.com/kubernetes-sigs/cluster-api/tree/main/test/extension).

I've discovered all the manifests under `config/default` immediately and got something running in a very early state.
Also the `kubectl create --raw ...` commands from [tips&tricks](https://cluster-api.sigs.k8s.io/tasks/experimental-features/runtime-sdk/implement-extensions.html#tips--tricks) worked fine.

But it took me a while to understand that i missed to deploy an `ExtensionConfig` ( [`extensionconfig.yaml`](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/extension/config/tilt/extensionconfig.yaml) from `test/extension` directory).

**What did you expect to happen:**
A more clear guidance how to implement an own runtime hook.

**Anything else you would like to add:**
the RFC contains some notes about the `ExtensionConfig` (https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20220221-runtime-SDK.md#registering-runtime-extensions)

Not sure if it's worth the effort, but something to start from scratch by running some `make targets` (`kubebuilder`) commands to have everything generated for a new hook would be :heart: 

**Environment:**

- Cluster-api version:
- minikube/kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by fabriziopandini** [comment]
/triage accepted
Thanks for the feedback, great to see people starting to experiment with runtime extensions! it would be great if you can send a PR, so the doc will gain the perspective of someone approaching the topic for the first time

Also FYI, we recently made it possible to use runtime extensions with tilt, so you can quickly iterate changes, debug live etc. The process is the same as developing a provider with tilt (https://cluster-api.sigs.k8s.io/developer/tilt.html#available-providers), but this is another thing that we should probably surface better in our doc

/remove-kind bug
/kind documentation

**Comment by fabriziopandini** [comment]
I just checked the documentation and we have https://cluster-api.sigs.k8s.io/tasks/experimental-features/runtime-sdk/implement-extensions.html#extensionconfig to highlight the fact that an ExtensionConfig is required

But ok to add a reminder at the beginning of [Tips & tricks](https://cluster-api.sigs.k8s.io/tasks/experimental-features/runtime-sdk/implement-extensions.html#tips--tricks), something like

```
Make sure to add the ExtensionConfig object to yaml used to deploy the runtime extensions (see [Extensionsconfig](#extensionconfig) for more details).
```

/triage accepted
/good-first-issues

**Comment by pravarag** [comment]
@fabriziopandini I've raised a [PR](https://github.com/kubernetes-sigs/cluster-api/pull/10449) for this minor change as suggested above.
