### ISSUE TITLE
Move all existing issue templates to GitHub forms

### ISSUE THREAD

**Issue by furkatgofurov7** [kubernetes-sigs/cluster-api#7815]
**User Story**
There is a possibility to move all existing templates we have in the repo from markdown format to [GitHub forms for issue templates ](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)which is basically YAML representation of the template. Example issue template in kubernetes repo to get the idea of how it looks like: https://github.com/kubernetes/kubernetes/issues/new?assignees=&labels=kind%2Ffailing-test&template=failing-test.yaml 
kubernetes repo has already switched to the GitHub forms some time ago. See more discussion on https://github.com/kubernetes-sigs/cluster-api/pull/7778#issuecomment-1367431498

/kind feature

**Comment by fabriziopandini** [comment]
/triage accepted
It seems this is a nice way to get people to provide all the info we usually need to triage issues, so +1 from me

**Comment by sbueringer** [comment]
If I understand it correctly the main reason to switch to the YAML format is that input forms can be defined, right?

I agree that it's definitely nice to do this for bug_report, failing-test, feature_request and flaking-test.

I think it would be problematic to use it for Kubernetes bump and release tracking.

I evaluated if it would make sense to use GitHub forms when I created those templates, but given that there is almost 0 user-input required + that GitHub forms doesn't have any advanced features like taking the inputs to render the resulting markdown in the issue I would like to not migrate those two templates to GitHub forms.

**Comment by sbueringer** [comment]
@furkatgofurov7 Slightly unrelated question. Does it make sense from a user-perspective to have different issue templates for failing and flaking tests?

I wonder if we can optimize and just have one issue template for both (but fine for me if we want to have both)

**Comment by furkatgofurov7** [comment]
> If I understand it correctly the main reason to switch to the YAML format is that input forms can be defined, right?
> 
> I agree that it's definitely nice to do this for bug_report, failing-test, feature_request and flaking-test.

I was thinking the same initially and was planning to migrate only the above and leave the Kubernetes bump and release tracking. 
release tracking. does not need any input from the person who opens it and it is mostly the list of items referencing other links and checkboxes. GitHub forms do have support for both, so I think (not 100% sure yet) it is still possible to migrate the remaining two, currently, I am playing with it and hopefully will be able to show an example of it in the fork.

**Comment by sbueringer** [comment]
Sounds good. I would expect the YAML format of those issue to be a lot harder to maintain then the current (as you can just render 1:1 the same markdown when you want to see the results). 

But let's see how it goes :)

**Comment by furkatgofurov7** [comment]
> @furkatgofurov7 Slightly unrelated question. Does it make sense from a user perspective to have different issue templates for failing and flaking tests?
> 
> I wonder if we can optimize and just have one issue template for both (but fine for me if we want to have both)

@sbueringer IMO they are bit different or at least if you look from the "time for it being open" perspective, because failing tests might be fixed in 2-3 days however we might want to keep flaking test issues open for longer to check how it is behaving.  But if you/others think that is not a valid point, I am happy to merge them into one.

**Comment by furkatgofurov7** [comment]
> I agree that it's definitely nice to do this for bug_report, failing-test, feature_request and flaking-test.

So, migrating bug_report, failing-test, feature_request and flaking-test issus templates were fairly straighforward and I have them working in my fork, see https://github.com/furkatgofurov7/cluster-api/issues/new/choose and below are example issue opened from it:

- [bug_report](https://github.com/furkatgofurov7/cluster-api/issues/11), [failing-test](https://github.com/furkatgofurov7/cluster-api/issues/5), [feature_request](https://github.com/furkatgofurov7/cluster-api/issues/6) and [flaking-test](https://github.com/furkatgofurov7/cluster-api/issues/7)


> Sounds good. I would expect the YAML format of those issue to be a lot harder to maintain then the current (as you can just render 1:1 the same markdown when you want to see the results with the current format).
> 
> But let's see how it goes :)

I agree with the rendering part though I give it a try to migrate only the release tracking issue for now and if needed/agreed I can work on migrating k8s bump issue template too. 

- Here is the example issue in my fork: https://github.com/furkatgofurov7/cluster-api/issues/10


@fabriziopandini @sbueringer please let me know what do you think about it, thank you!

**Comment by sbueringer** [comment]
Overall I like it for our user-facing issue.

Some nits: (but just minor modifications no fundamental issues)
* bug report
  * Looks like we're using some hints like: "[A clear and concise description on how to REPRODUCE the bug.]"
  * The texts in the version text areas are a bit confusing to me
* feature request:
  * not sure I agree with: "Feature requests are unlikely to make progress as issues. Please consider engaging with maintainers on slack, office hours and mailing lists, instead."
  * we have 2x "What would you like to be added (User Story)?" (probably should be Detailed Description instead)
  * "Anything else you would like to add?": "[Miscellaneous information that will assist in solving the issue.]" is missing
  
I would prefer to keep the release tracking issue template in the old format. I think it's a lot easier to maintain and better fits our use case (we don't really use the input form at issue creation time)

**Comment by furkatgofurov7** [comment]
> Overall I like it for our regular issues.
> 
> Some nits: (but just minor modifications no fundamental issues)
> 
>     * bug report
>       
>       * Looks like we're using some hints like: "[A clear and concise description on how to REPRODUCE the bug.]"
>       * The texts in the version text areas are a bit confusing to me
> 
>     * feature request:
>       
>       * not sure I agree with: "Feature requests are unlikely to make progress as issues. Please consider engaging with maintainers on slack, office hours and mailing lists, instead."
>       * we have 2x "What would you like to be added (User Story)?" (probably should be Detailed Description instead)
>       * "Anything else you would like to add?": "[Miscellaneous information that will assist in solving the issue.]" is missing

Alright, thanks for quick feedback, I have address most of them in my fork so I should be able to send a PR soon and we can discuss the details there (mostly around "The texts in the version text areas are a bit confusing to me")

> I would prefer to keep the release tracking issue template in the old format. I think it's a lot easier to maintain and better fits our use case (we don't really use the input form at issue creation time)

Fine to me, I think that is in fact easier to maintain them if leave them out since they are really custom/specific



> P.S. Just a hint. You can open a PR against core Cluster API with your changes and at the same time use the same branch (doesn't have to be "main") as "default" branch in your repo.

Great, thanks for the hint. I was playing with it in my fork, but to open an upstream PR I can't use my fork but other fork in the org where I can't really set my branch as default :)

**Comment by furkatgofurov7** [comment]
@sbueringer @fabriziopandini here is the PR: https://github.com/kubernetes-sigs/cluster-api/pull/7819, PTAL
