### ISSUE TITLE
cluster-api-periodics-release-1-2 are failing

### ISSUE THREAD

**Issue by nawazkh** [kubernetes-sigs/cluster-api#7858]
**Which jobs are failing:**
- [cluster-api-periodics-release-1-2](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-1.2#capi-e2e-release-1-2)

**Which tests are failing:**
- `capi-e2e: When upgrading a workload cluster using ClusterClass [ClusterClass] Should create and upgrade a workload cluster and eventually run kubetest`
- `capi-e2e: When upgrading a workload cluster using ClusterClass with a HA control plane [ClusterClass] Should create and upgrade a workload cluster and eventually run kubetest`

**Since when has it been failing:**
- January 5th 2023, 04:34 PST

**Testgrid link:**
- https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-1.2#capi-e2e-release-1-2

**Reason for failure (if possible):**
- Appears to be a cleanup issue. 
```
STEP: Waiting for cluster k8s-upgrade-and-conformance-v9q2cd to be deleted
.
.
When upgrading a workload cluster using ClusterClass [ClusterClass]
/home/prow/go/src/sigs.k8s.io/cluster-api/test/e2e/cluster_upgrade_test.go:65
  Should create and upgrade a workload cluster and eventually run kubetest [It]
  /home/prow/go/src/sigs.k8s.io/cluster-api/test/e2e/cluster_upgrade.go:118
  Timed out after 1200.000s.
  Error: Unexpected non-nil/non-zero argument at index 1:
  	<*errors.fundamental>: old nodes remain
  /home/prow/go/src/sigs.k8s.io/cluster-api/test/framework/machine_helpers.go:151
```

**Anything else we need to know:**
- This test has failed has test five consecutively, however, failed thrice with the above test cases. 
/kind failing-test

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
Thx for reporting! I took a look, will be fixed soon

xref: https://kubernetes.slack.com/archives/C8TSNPY4T/p1673262697410139?thread_ts=1673227707.288409&cid=C8TSNPY4T

/triage accepted

**Comment by furkatgofurov7** [comment]
Just to make it visible here, [capi-e2e-release-1-3 ](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-1.3#capi-e2e-release-1-3) job has also been failing (there is no issue but we are aware of it) and should be fixed by the cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/7856 once it lands.

**Comment by killianmuldoon** [comment]
Looks like this is fixed 😄 Thanks everyone!

/close
