### ISSUE TITLE
Create kubectl/controller/actuator/etc. logic traces.

### ISSUE THREAD

**Issue by davidewatson** [kubernetes-sigs/cluster-api#787]
/kind feature

**Describe the solution you'd like**
The original `kubebuilder` documentation on which the Cluster API documentation was based included logic traces showing when controllers observed or updated status. For an example, see [Watching Resources](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/basics/what_is_a_controller.md#watching-resources). This visualization is useful in understanding the responsibilities of the common code vs. providers. Ideally we should have similar traces for each resource (e.g. `Machine`, `MachineSet`, etc.).

**Anything else you would like to add:**
Subtask of https://github.com/kubernetes-sigs/cluster-api/issues/571

Note that this can be implemented using the GitBook sequence plugin, or, if that proves to be problematic an SVG, PNG, or other file type is probaby okay too.

**Comment by sflxn** [comment]
I can add a few sequence diagrams for this if no one has signed up for it.

**Comment by ncdc** [comment]
@sflxn I see you have some commits for this issue - are you planning on opening a PR?

**Comment by sflxn** [comment]
@ncdc Yes.  I'm going to have a PR within the next day or two.  I had to abandon the sequence diagram plugin as it's really unreliable, as @davidewatson also found.  It will be png files instead.
