### ISSUE TITLE
Document how to implement provider specific clusterctl

### ISSUE THREAD

**Issue by davidewatson** [kubernetes-sigs/cluster-api#789]
/kind bug

**Describe the solution you'd like:**
The GitBook describes how to create a new provider implementation and includes sample code to [register schemes](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/provider_implementations/register_schemes.md), [add controllers](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/provider_implementations/register_controllers.md), etc. It does not document how to create a provider specific `clusterctl` implementation and this has led to issues in the past. For an example implementation see: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/389258fab9f15efc7c1d335d1ea228fd3248abba/cmd/clusterctl/main.go#L32

**Anything else you would like to add:**
It is enough to create a page showing the code which must be written. It would be nice if the implicit requirement to set an annotation were also mentioned here. Cf. https://github.com/kubernetes-sigs/cluster-api/issues/253

Subtask of https://github.com/kubernetes-sigs/cluster-api/issues/571

**Comment by ncdc** [comment]
The long term goal is to move away from provider-specific clusterctl. Closing.

/close
