### ISSUE TITLE
VMware: support VM images that come with container runtime pre-installed

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#79]
_From @rsdcastro on April 14, 2018 1:46_

VM images provided by users might have the container runtime. This issue tracks verifying if the container runtime is already pre-installed and matches the version specified by the user.

_Copied from original issue: kubernetes/kube-deploy#687_

**Comment by rsdcastro** [comment]
/cc @karan 

Karan - can you update this issue based on the current implementation using Ubuntu images?

**Comment by karan** [comment]
Currently, we disregard user preference and install docker anyways - https://github.com/kubernetes-sigs/cluster-api/blob/master/cloud/terraform/templates.go#L251 (terraform) and https://github.com/kubernetes-sigs/cluster-api/blob/master/gcp-deployer/machine_setup_configs.yaml#L40 (gcp)

**Comment by roberthbailey** [comment]
This issue was moved to kubernetes-sigs/cluster-api-provider-vsphere#11
