### ISSUE TITLE
Add Doc for supporting raw template URL in clusterctl generate yaml

### ISSUE THREAD

**Issue by aniruddha2000** [kubernetes-sigs/cluster-api#7904]
As suggested https://github.com/kubernetes-sigs/cluster-api/pull/7371#issuecomment-1368943890 by @fabriziopandini we need to add documentation for clusterctl supporting raw template UR in `clusterctl generate yaml` command.

NOTE:
- We can add [generate yaml](https://cluster-api.sigs.k8s.io/clusterctl/commands/generate-yaml.html) section of the doc like giving an example.
- Also, giving information [here](https://cluster-api.sigs.k8s.io/clusterctl/commands/generate-cluster.html#github-local-file-system-folder-or-standard-input) that we can use a raw template as well.

/kind documentation
/assign

**Comment by fabriziopandini** [comment]
Thanks for taking care of opening the issue!
/triage accepted
