### ISSUE TITLE
Error in fail: Failed to load provider. No tilt-provider.{yaml|json} file found in test/infrastructure/docker

### ISSUE THREAD

**Issue by guettli** [kubernetes-sigs/cluster-api#7920]
**What steps did you take and what happened:**

I follow this guide to test Tilt with Docker:

https://cluster-api.sigs.k8s.io/developer/tilt.html

```
❯ make tilt-up 
hack/kind-install-for-capd.sh
kind cluster already exists, moving on
tilt up
Tilt started on http://localhost:10350/
v0.31.1, built 2023-01-09

(space) to open the browser
(s) to stream logs (--stream=true)
(t) to open legacy terminal mode (--legacy=true)
(ctrl-c) to exit
Tilt started on http://localhost:10350/
v0.31.1, built 2023-01-09
W0113 13:16:41.518022 2646480 loader.go:223] Config not found: /home/guettli/.tilt-dev/config
W0113 13:16:41.518022 2646480 loader.go:223] Config not found: /home/guettli/.tilt-dev/config
W0113 13:16:41.518077 2646480 loader.go:223] Config not found: /home/guettli/.tilt-dev/config
W0113 13:16:41.518077 2646480 loader.go:223] Config not found: /home/guettli/.tilt-dev/config

Initial Build
Loading Tiltfile at: /home/guettli/syself/cluster-api/Tiltfile
local: command -v kubectl || true
local: docker version || podman version
local: go env GOOS
 → linux
local: go env GOARCH
 → amd64
ERROR: Traceback (most recent call last):
  /home/guettli/syself/cluster-api/Tiltfile:601:24: in <toplevel>
  /home/guettli/syself/cluster-api/Tiltfile:159:17: in load_provider_tiltfiles
Error in fail: Failed to load provider. No tilt-provider.{yaml|json} file found in test/infrastructure/docker
```

**What did you expect to happen:**

I expect the file to exist, and the command to work.

**Anything else you would like to add:** 

I think the docs (see above link) should focus on Docker (not AWS).

Docker is a availabe for no costs for everybody.

**Environment:**

- Cluster-api version: master
- minikube/kind version: v0.17.0 go1.18.7 linux/amd64
- Kubernetes version: (use `kubectl version`): Client Version: v1.26.0, Kustomize Version: v4.5.7, Server Version: v1.25.3
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.1 LTS

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by killianmuldoon** [comment]
The issue here might be that you're adding the docker provider in the same way the AWS provider is added. As the docker provider is built in it's possible to use it without setting a "provider repo" in the tilt-settings. AWS, as it's external, requires a pointer to the directory it's placed in. 

Try something like:

```yaml
enable_providers:
- docker
- kubeadm-bootstrap
- kubeadm-control-plane
```

If this doesn't work, it would be great if you could post your full tilt-settings file so we can debug.

**Comment by guettli** [comment]
@killianmuldoon my tilt-settings.yaml looks like this:

```
default_registry: gcr.io/your-project-name-here
provider_repos:
  - ./test/infrastructure/docker
enable_providers:
  - docker
  - kubeadm-bootstrap
  - kubeadm-control-plane
```

the corresponding directory does not contain a tilt-provider.yaml file:

```
❯ ls test/infrastructure/docker/

api  config  controllers  Dockerfile  examples  exp  
internal  main.go  OWNERS  PROJECT  README.md  templates
```

I tried to create an tilt-provider.yaml file myself, but this does not work:
```
❯ cat test/infrastructure/docker/tilt-provider.yaml
name: docker
config:
  image: "gcr.io/your-project-name-here",
  live_reload_deps: ["main.go", "go.mod", "go.sum", "api", "cmd", "controllers", "pkg"]
  label: CAPD
```

I get:
```
Traceback (most recent call last):
  /home/guettli/syself/cluster-api/Tiltfile:601:24: in <toplevel>
  /home/guettli/syself/cluster-api/Tiltfile:160:37: in load_provider_tiltfiles
Error in read_yaml: error parsing YAML from ./test/infrastructure/docker/tilt-provider.yaml: error converting YAML to JSON: yaml: line 2: did not find expected key
```

What values are needed for getting tilt running with the docker-provider?

**Comment by killianmuldoon** [comment]
The docker provider doesn't need a "provider repo". The components in the capi repo - i.e. KCP, CAPBK, CAPI core and the docker provider have builtin settings.

This should work by using:

```yaml 
enable_providers:
  - docker
  - kubeadm-bootstrap
  - kubeadm-control-plane
``` 
As your full tiltfile. (Not sure if `default_registry: gcr.io/your-project-name-here` is intentional or not in your example above - but include a default registry too if required.

**Comment by killianmuldoon** [comment]
@guettli I took a run at clarifying the docs around this in #7934. It would be great to get your feedback on it.

**Comment by guettli** [comment]
@killianmuldoon thank you very much! Removing these two lines solved the problem:

```diff
  default_registry: gcr.io/your-project-name-here
- provider_repos:
-  - ./test/infrastructure/docker
  enable_providers:
    - docker
    - kubeadm-bootstrap
    - kubeadm-control-plane
  ```
