### ISSUE TITLE
Topology controller should reset TopologyReconciled when deleting

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#7926]
**What steps did you take and what happened:**
When a cluster is deleted, after calling the delete hook, then the topology controller stops to reconcile a cluster. However, during this process, it never resets the TopologyReconciled, which will continue to represent the latest state before deletion.

I found this looking at a cluster stuck in deletion, where the TopologyReconciled was reporting an error, but this was a red herring that took some time to figure it out.

**What did you expect to happen:**
TopologyReconciled condition to be reset while the cluster is being deleted/After the hook is called.

/kind bug
/area topology
/triage accepted
/help

**Comment by cahillsf** [comment]
hey 👋  i'd like to take this on -- to ensure I am understanding the issue correctly, when a cluster with managed topology is deleted, the current behavior in the controller leads to:

-  [this return statement](https://cs.github.com/kubernetes-sigs/cluster-api/blob/197e7f90b2d8f25ffbd0b428e7c5197f3364c93c/internal/controllers/topology/cluster/cluster_controller.go#L170) in `Reconcile` which calls [reconcileDelete](https://cs.github.com/kubernetes-sigs/cluster-api/blob/197e7f90b2d8f25ffbd0b428e7c5197f3364c93c/internal/controllers/topology/cluster/cluster_controller.go#L367)
- `reconcileDelete` currently does not contain any functionality to update the `TopologyReconciledCondition`, which is less than desired as the condition is no longer accurate and simply represents the latest state before deletion.  

Does that sounds right?

**Comment by fabriziopandini** [comment]
/assign @cahillsf 
yes, you got the problem right, thanks for volunteering for this issue!

**Comment by cahillsf** [comment]
hey @fabriziopandini 👋 i just opened a draft PR to address this.  please let me know if this is along the lines of the fix you had in mind or, if not, how i can improve this fix
