### ISSUE TITLE
Improve test framework to get full logs during self-hosted test

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7929]
Context:
We have a self-hosted test which first creates a workload cluster, then runs ClusterAPI on top of this workload clusters and then ClusterAPI upgrades the cluster its running on.

Our test/framework has code which retrieves the logs from controllers. This works on the regular bootstrap / mgmt cluster. It also works in the self-hosted test up until a certain point. The logs are only retrieved until Cluster API replaces the node the controller is running on. Unfortunately, it doesn't work for the new controllers coming up on new nodes.

It would make debugging significantly easier if we would have full logs of the controllers in the self-hosted test as well.

An example can be seen here: https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1614965091675934720/artifacts/clusters/self-hosted-a10wag/logs/capi-system/capi-controller-manager/capi-controller-manager-697cc4c65d-rlzqc/manager.log

/area testing
/kind feature

**Comment by chrischdi** [comment]
There is also the case that if a container's process gets restarted, the logs stream will get canceled.

I've got some local code which:

* Creates an informer in `WatchDeploymentLogs` which
  * watches for new pods matching the selector
  * starts streaming the logs of every new pod (to seperate file)
  * restarts streaming the logs for pods which get restarts

I'll try to rebase the code and submit a PR :-)

/assign
