### ISSUE TITLE
Util Secret ParseSecretName not working correctly on clusterctl move

### ISSUE THREAD

**Issue by tidusete** [kubernetes-sigs/cluster-api#7936]
**What steps did you take and what happened:**
1. Have a Management Cluster
2. Create an Azure target cluster
3. Launch clusterctl move --to-directory testing_backup --kubeconfig ~/.kube/$(management_cluster) -v6 --dry-run -n $(target_cluster)
This is part of the output:
```
No default config file available
Moving to directory...
Discovering Cluster API objects
AzureClusterIdentity Count=1
Machine Count=2
AzureMachineTemplate Count=2
ConfigMap Count=1
MachineSet Count=1
AzureMachine Count=2
Cluster Count=1
Secret Count=13
KubeadmConfigTemplate Count=2
MachineDeployment Count=2
AzureCluster Count=1
KubeadmConfig Count=2
KubeadmControlPlane Count=1
Total objects Count=31
Excluding secret from move (not linked with any Cluster) name="cluster-identity-secret-<target_cluster>"
```
As you can see, I would like to move the secret "cluster-identity-secret-<target_cluster>"

**What did you expect to happen:**
To not exclude the secret since its linked with the cluster that i'm doing the move.
I would like to have on my testing_backup directory the secret resource cluster-identity-secret-<target_cluster>" + all the files that are actually being moved.

**Anything else you would like to add:**
Yes, I tried to debug a little bit and I believe the utility secretutil.ParseSecretName is not working properly since I'm always on the error condition.
https://github.com/kubernetes-sigs/cluster-api/blob/d87a39c85f87f60858c578feaf5192d5679a140e/cmd/clusterctl/client/cluster/objectgraph.go#L434
I tried to check the `util/secret/secret.go` and I think that there is a misunderstood between the vars `clusterName` `purposeSuffix` and possibly the `allSecretPurposes` which is defined on the `util/secret/consts.go`
https://github.com/kubernetes-sigs/cluster-api/blob/314d98e0141489e2ac7a2915c66628ad2f22d006/util/secret/secret.go#L58

Do we have a standard name convention for the resources that are being created?
The reason is because when I launch `kubectl --kubeconfig ~/.kube/$(management_cluster) get secrets -n $(target_cluster)`
I have the following output:
```
cluster-identity-secret-<target_cluster>          Opaque                    1      22h
<target_cluster>-ca                               cluster.x-k8s.io/secret   2      22h
<target_cluster>-cluster-identity-secret          Opaque                    1      58m
<target_cluster>-control-plane-xxxxx-azure-json   Opaque                    3      6h13m
<target_cluster>-control-plane-azure-json         Opaque                    3      22h
<target_cluster>-control-plane-xxxx              cluster.x-k8s.io/secret   2      22h
<target_cluster>-etcd                             cluster.x-k8s.io/secret   2      22h
<target_cluster>-kubeconfig                       cluster.x-k8s.io/secret   1      22h
<target_cluster>-proxy                            cluster.x-k8s.io/secret   2      22h
<target_cluster>-sa                               cluster.x-k8s.io/secret   2      22h
```
When I launch `clusterctl move` and i'm checking what I have inside the `allSecretPurposes`,`clusterName`,`purposeSuffix`. I have the following values using 2 different resources:
```
Using this secret cluster-identity-secret-<target_cluster>
clusterName "cluster-identity-secret"
purposeSuffix -> "<target_cluster>"
allSecretPurposes -> [kubeconfig ca etcd sa proxy apiserver-etcd-client]

Using this secret: <target_cluster>-cluster-identity-secret
clusterName <target_cluster>-cluster-identity
purposeSuffix secret
allSecretPurposes -> [kubeconfig ca etcd sa proxy apiserver-etcd-client]

```

**Environment:**

- Cluster-api version: clusterctl_version="1.3.1"
- minikube/kind version: 
- Kubernetes version: (use `kubectl version`): v1.24.6
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by killianmuldoon** [comment]
Soft ownership, which uses the name-linking, isn't the easiest way to create the object graph for objects from providers.  ownerReferences are used by `clusterctl move` for most objects AFAIK. Does the `cluster-identity-secret` have any ownerReferences?

**Comment by tidusete** [comment]
No, it doesn't have any relation.
Maybe a better definition of a cluster-identity-secret could be really useful.
I have been reading and trying to understand better the following documentation but I think is a little poor. https://capz.sigs.k8s.io/topics/multitenancy.html

**Comment by killianmuldoon** [comment]
It might be good to bring this up over at https://github.com/kubernetes-sigs/cluster-api-provider-azure for the real experts :slightly_smiling_face: You'll probably get better input on the definition of the secret - and the issues with `clusterctl move` over on that repo.

**Comment by fabriziopandini** [comment]
/remove-kind bug
/close
due to lack of updates; the explanation + alternatives is provided in https://github.com/kubernetes-sigs/cluster-api/issues/7936#issuecomment-1403787220
