### ISSUE TITLE
What are the common fields across providers?

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes-sigs/cluster-api#794]
At present, Cluster API defines a set of common fields.

In Cluster object we have the following parameter fields:

- `spec.clusterNetwork.pods.cidrBlocks`
- `spec.clusterNetwork.services.cidrBlocks`
- `spec.clusterNetwork.serviceDomain`

https://github.com/kubernetes-sigs/cluster-api/blob/f8d548b47e444972254fa23a91e626ecf7589ee2/config/crds/cluster_v1alpha1_cluster.yaml#L33-L63

There is **`providerSpec`**, which is what holds anything that is uncommon between providers and is thereby a separate topic.

Then there are status fields, which should be discussed separately – https://github.com/kubernetes-sigs/cluster-api/issues/795.

### `spec.clusterNetwork`

Overall, all fields here happen to be required. It's generally not clear why these happen to be the only fields that are defined as common Cluster API fields vs just any other parameter or add-ons or anything else. What would happen if these parameters weren't defined here at all?

I believe these are important to some implementations, but there're several other implementations where these aren't of significant meaning, or at least much much less significant over other parameters.

### `spec.clusterNetwork.serviceDomain`

This field is currently required, and I'm not entirely sure why. In majority of use-case, for application compatibility reasons you'd always want to keep the value of this to be `cluster.local`. Some providers may not allow users to chose a value of this at all. Once dynamic kubelet settings become stable, this shouldn't be need at all. Additionally, this boils down to a kubelet parameter and the DNS add-on parameter, so I'm not sure why it belongs at cluster level.

### `spec.clusterNetwork.pods.cidrBlocks` & `spec.clusterNetwork.services.cidrBlocks`

Both of these fields are currently required. In some providers these are indeed important, but in some other providers there maybe a function of network add-on parameters and/or parameters of the underlying network, neither of which are currently defined within Cluster object. Those may get defined as part of `providerSpec`, but it may not be known to the user what to set here before `providerSpec` gets evaluated, especially when a pre-existing network is being used and only a set of provider-specific identifier is all there is that is known about such a network.

**Comment by errordeveloper** [comment]
## Provider Analysis

### EKS

*TODO*

### GKE

*TODO*

**Comment by ncdc** [comment]
Closing due to age
/close
