### ISSUE TITLE
Support moving capi resources to a configurable namespace

### ISSUE THREAD

**Issue by takirala** [kubernetes-sigs/cluster-api#7940]
**User Story**

As a developer I would like to move capi resources from one cluster to another cluster and while doing so, i would want to control the namespace the resources are created in the target cluster. Right now, when i perform a move operation, clusters are always moved to the same namespace on target cluster as they are originally created in the originating cluster. I want to be able to control this so that I can move resources from multiple clusters to a single cluster and still organize them by namespace post move operation.

**Detailed Description**

I want to be able to move capi resources from namespace A on originating cluster to namespace B on target cluster. 

**Anything else you would like to add:**

This is partially possible today by doing (but not practical) :

```
clusterctl move --from-kubeconfig <> --to-directory <>
<update all *.yaml> files with a new namespace
clusterctl move --from-directory <> --to-kubeconfig <>
```
However, with above approach, the `Cluster` resource (and all its associated resource) is NOT removed in the `from-kubeconfig` cluster. 

/kind feature

**Comment by sbueringer** [comment]
I basically have two concerns about this:

 1. Do we see features like this as part of the scope of clusterctl move
> clusterctl move has been designed and developed around the bootstrap use case described below, and currently this is the only use case verified by Cluster API E2E tests.
> If someone intends to use clusterctl move outside of this scenario, it’s recommended to set up a custom validation pipeline of it before using the command on a production environment.
> https://cluster-api.sigs.k8s.io/clusterctl/commands/move.html

2. How would we identify namespace fields in the resources we are moving?

This is straightforward for the resources we know (Cluster, MachineDeployment, ...). It's a lot harder for the resources which are "behind the contract", e.g. ControlPlane, InfraCluster, BootstrapConfigTemplate. Concrete examples:
* KCP.spec.machineTemplate.infrastructureRef.namespace (https://github.com/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go#L106)
  * This one is covered by the control plane contract, so it's doable.
* I assume there can be more as every provider (mostly infra) could have own namespace fields in their CRDs.

Not sure if it's good enough if we just look for fields called "namespace" in all objects we are moving and then change them to the target namespace if the current value is the source namespace. (I think it's easy to change fields that actually shouldn't be changed).

**Comment by takirala** [comment]
> Do we see features like this as part of the scope of clusterctl move

My understanding/justification was that if `clusterctl` is moving resources from cluster A to cluster B and it is also deleting resources on cluster A as part of this move, it should be able to change namespace during the move. In earlier versions of `clusterctl` it only supported `from-kubeconfig` and `to-kubeconfig`. In more recent versions it was "enriched" to support `from-directory` and `to-directory`. This issue warrants a new flag `to-namespace` and this is just another "enrichment" of the functionality so I _assumed_ it should be in scope of `clusterctl` move.

> How would we identify namespace fields in the resources we are moving?

I am open to hearing better approaches on this, but so far I have only got a static list of resources https://github.com/kubernetes-sigs/cluster-api/pull/7941/files#diff-3458bf9e9c245fe801573500c33de535f05d3a5887f080a405b819e3c0fed415R228-R240
A better approach could probably be to use `reflect` and parse all the nested fields for `LocalObjectReference`, `TypedLocalObjectReference` or `ObjectReference` and then update the nested fields but even that might not foolproof (e.g.: what if a Resource has a struct with fields named identical to `ObjectReference` but its not really `ObjectReference`), so I used a static list. Note that, I was able to perform a move operation successfully with the change in #7941, so it "techinically" works. 
**The real answer to this question is that this will be done more correctly / cleaned up if/when we can resolve https://github.com/kubernetes-sigs/cluster-api/issues/6539**

**Comment by dlipovetsky** [comment]
> Do we see features like this as part of the scope of clusterctl move

Are there practical alternatives you have in mind?

The move [implementation](https://github.com/kubernetes-sigs/cluster-api/blob/984588796ca76631a65cfc18eef4ee95cd47ade8/cmd/clusterctl/client/cluster/mover.go#L72) performs object discovery, and that isn't exposed as a public API. Right now, the alternative is to "backup" the objects, modify the namespace where needed, and then "restore" them. The `FromDirectory` and `ToDirectory` API requires a file system, which can be impractical.

> How would we identify namespace fields in the resources we are moving?

I second what @takirala says above.

Would anything break that is not already broken?  That is, if some referenced object is in different namespace, then today's move implementation would miss it anyway, right?

**Comment by sbueringer** [comment]
> Are there practical alternatives you have in mind?

Unfortunately, not really. I'm not saying it's not in scope, I just wanted to bring up the question, given that we currently pretty much only test it in the bootstrap use case. It would be good to hear opinions from the clusterctl maintainers on it. 

> 2. Move does not identify the reference namespace field. Then, if some controller actually uses the namespace field, it will not find the referenced object.

Yup, I think that's the case that could break. But maybe that's fine if we don't expect `--to-namespace` to work for everyone (aka all providers).

If I understand the current implementation correctly we essentially hard-code the known namepaces fields of resources that we are aware of. I agree this solves the problem for those types, and for types which are part of the core repository I don't have objections to "hard-coding" it in some way or another.

The cases I wonder about are:
* KCP is just one control plane implementation. Ideally we handle control plane implementations using machines in general. The namespace field there is standardized in our contract: https://cluster-api.sigs.k8s.io/developer/architecture/controllers/control-plane.html#required-spec-fields-for-implementations-using-machines
  * Should be solvable and thus not a showstopper
* Fields in CRDs of other providers (mostly infra providers): 
  * An example: Metal3MachineTemplate seems to be using an ObjectReference to reference another object
  * Maybe there are more cases, maybe not. My point is we don't know. The question is, are reference in CRDs of other providers just not supported, do we have to support them, is there a way to support them?

We also have a few more namespace fields in the core repo that we should probably add: ClusterClass, MachinePool, .. maybe more (but that's probably not a big issue we would just have to go over them and adding them).

**Comment by fabriziopandini** [comment]
I'm also worried about injecting type-specific knowledge into clusterctl given the number of providers we officially support, this could quickly turn out into something high effort to maintain (all those resources change over time). 

Also, what about the closed-source providers that use clusterctl? how can we allow them to use this new feature with their own types?

Given that I think we should proceed with a little bit of caution. What about:

Adding a field to MoveOptions explicitly marked as experimental and allowing it to pass "an object mutating function" that will be called after get/before write (TBD) (something similar to the ~updateObjectNamespaceReferences in the example).

The key point of this solution is that we are not embedding type-specific knowledge in clusterctl now, because we don't have yet a good idea of how to write this logic in a generic way, but at the same time, we allow the community to experiment on this use case (and possibly more if the mutation function will be generic enough.

note: in this iteration this feature will be added to the library only, but not exposed to the CLI.

how does this idea sound?

**Comment by dlipovetsky** [comment]
> Adding a field to MoveOptions explicitly marked as experimental and allowing it to pass "an object mutating function" that will be called after get/before write (TBD) (something similar to the ~updateObjectNamespaceReferences in the example).

That sounds good to me, but I'll defer to @takirala. This would be a much more practical version of the mechanism that currently works, namely: "backup all resources to using `move --to-directory`, modify the resources, then restore them using `move --from-directory`"

> The key point of this solution is that we are not embedding type-specific knowledge in clusterctl now, because we don't have yet a good idea of how to write this logic in a generic way, but at the same time, we allow the community to experiment on this use case (and possibly more if the mutation function will be generic enough.

I agree.

> note: in this iteration this feature will be added to the library only, but not exposed to the CLI.

That sounds fine.

Thanks for suggesting this way forward, @fabriziopandini! :pray:

**Comment by takirala** [comment]
Sounds good @fabriziopandini and @dlipovetsky 
I have attempted this in #7966

**Comment by fabriziopandini** [comment]
/triage accepted

It seems that there is agreement on a way forward allowing us to experiment with this feature while we figure out a generic way to implement namespace transformations in objects.
