### ISSUE TITLE
Support passing custom predicates options to KubeadmConfigReconciler 

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes-sigs/cluster-api#7949]
**User Story**

We are importing cluster-api controllers in [kurator](https://github.com/kurator-dev/kurator), basically for installing k8s on any platform, especially on running VMs.

In our case, on developing installation on VMs, we depend on kubeadmControlplane API to provide k8s controlplane configurations as well.  But we has the kubeadmControlplane has reference to kurator customMachine API.  So there are lots of errors from KubeadmConfigReconciler.

The basic idea is can we add custom filter function in `controller.Options`, so we can pass the filter function as below. 

```
	c, err := ctrl.NewControllerManagedBy(mgr).
		For(&controlplanev1.KubeadmControlPlane{}, builder.WithPredicates(...) ).
		Owns(&clusterv1.Machine{}).
		WithOptions(options).
		WithEventFilter(predicates.ResourceNotPausedAndHasFilterLabel(ctrl.LoggerFrom(ctx), r.WatchFilterValue)).
		Build(r)
```

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by hzxuzhonghu** [comment]
I am willing to contribute, thanks

**Comment by fabriziopandini** [comment]
controller.Options is a type we import for controller runtime, so we can't express an opinion on the proposed change.

However, if this change gets accepted in controller runtime, then IMO controller runtime should also take care of applying the filter inside `WithOptions(options)` instead of requiring consumers to add a `builder.WithPredicates(...)` into `For(&controlplanev1.KubeadmControlPlane{}` as proposed above (not sure I understood this correctly, might be representing your intent as diff and replacing ... with actual code could clarify it).   

/triage needs-information

**Comment by hzxuzhonghu** [comment]
`controller.Options` looks a good choice to add that.  Do you think I should propose this request to controller-runtime ?

**Comment by sbueringer** [comment]
I think making this configurable in our controller doesn't require adding it to controller.Options. Honestly no idea if it would make sense to add it there (cc @vincepri).

Independent of that, I wonder if you basically want the same as: https://github.com/kubernetes-sigs/cluster-api/issues/7775

**Comment by hzxuzhonghu** [comment]
Not exactly same, here in kurator it want to filter out CR by reference kind.

**Comment by fabriziopandini** [comment]
commented on the PR. and echoing here as weel

> My personal opinion is that we should not add a new knob to filter issues we reconcile which is orthogonal to WatchFilterValue and its possible improvements being discussed in https://github.com/kubernetes-sigs/cluster-api/issues/7775.
> IMO those efforts should converge and come up with a common definition of what a filter is, that could translate into e.g. a watch filter struct or other solutions.

> Also, worth to notice that such type of change in order to actually work should be accepted by provider implementers as well, and this requires a discussion during office hours or a small proposal to rally on async.

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

The issue is not active since some time now and no other user expressed interest in the use case
/close
