### ISSUE TITLE
Add Response metric to Runtime SDK hook client

### ISSUE THREAD

**Issue by MaxFedotov** [kubernetes-sigs/cluster-api#7952]
**User Story**

As a user/operator I would like to have an additional response metric for Runtime SDK extensions to be able to trigger alerts in case of `ResponseStatusFailure` response.

**Detailed Description**

CAPI added metrics for Runtime SDK in [Add metrics to Runtime SDK hook client](https://github.com/kubernetes-sigs/cluster-api/pull/6675). But the existing metric `capi_runtime_sdk_requests_total` covers only HTTP status of the request. So if the request completes, but returns a `ResponseStatusFailure` response it is impossible to monitor\trigger the alert.

/kind feature

**Comment by sbueringer** [comment]
Sounds good to me!
Thx for opening the issue

/triage accepted
