### ISSUE TITLE
switch machine controller tests that use SSA to envtest and drop `disableNodeLabelSync`

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#7964]
**Detailed Description**

The machine controller disables portions of its reconciliation logic that depend on SSA by setting `disableNodeLabelSync` to `true` during tests. This is because the current test setup for the machine controller uses fake client which does not support SSA.

This issue to switch over the tests, at least the ones that need a working SSA, to envtest and dropping the `disableNodeLabelSync` from the machine reconciler. 

/kind test

**Comment by sbueringer** [comment]
Not sure if it is implied or not. 

Let's please also consider splittung up the code so we would only have to implement a small part of our tests with envtest.

All the pre-existing tests that have nothing to do with node label sync don't necessary have to be migrated to envtest.
