### ISSUE TITLE
Discussion: Bumping Go in older Cluster API releases

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7974]
Upstream k/k is bumping the Go version to 1.19 on patch versions of older Kubernetes minor releases (v1.23 + v1.24) (xref: https://groups.google.com/a/kubernetes.io/g/dev/c/RollV1z4fNQ)

They are doing this for two reasons:
* To ensure v1.23 can be released with a CVE free Go 1.19 (instead of Go 1.17)
* To ensure that they are using a supported Go version (1.18) for the remaining 4 months that v1.24 is in support.

Goal of is this issue is to discuss if this applies to Cluster API as well.

Current state Cluster API:
* Go version we use to compile clusterctl and our binaries (Makefile):
  * main: 1.19.4
  * release-1.3: 1.19.4
  * release-1.2: 1.18.9
* Go version in go.mod:
  * main: 1.19
  * release-1.3: 1.19
  * release-1.2: 1.17

Additionally our test jobs are using the following:
* Go version used for unit and e2e tests (+ a few binaries like ginkgo)
  * main: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230120-fd0935fac9-1.26 => Go 1.19.5
  * release-1.3: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230120-fd0935fac9-1.25 => Go 1.19.5
  * release-1.2: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230120-fd0935fac9-1.24 => Go 1.19.5

Some information about Go releases:
* CVE free (as of today): 1.19.4+, 1.18.9+
* latest: 1.19.5, 1.18.10
* Go 1.18 EOL: 2023-03-15 (Cluster API v1.2 EOL: 2023-03-28)

I would propose:
* Let's not bump to newer Go minor versions as:
  * v1.3 & main are already using 1.19
  * v1.2 is using 1.18 which is CVE free and in support until 2 weeks before Cluster API v1.2 is EOL
* Let's bump to 1.19.5 and 1.18.10 to profit from latest (non-security) fixes there
  * PRs: #7981, #7982

In general I would recommend:
* Let's bump to newer Go minor versions if there is a significant period (> 1 month ? TBD) that a Cluster API release is in support after the corresponding Go version is already out of support
* Let's definitely bump if bumping allows us to fix a CVE

Somewhat related I did a few experiments around the Go version in go.mod:
* To use new language features each module has to declare the go version it requires for those features (e.g. 1.18 for generics) (xref: https://go.dev/doc/modules/gomod-ref#go)
* It's fine if dependencies have a higher go version in go.mod as the current module.
* It is only necessary that the go version that is used to compile the binary is high enough to compile all dependencies (i.e. if a dependency of CAPI is declaring it requires Go 1.19 language features, CAPI has to be compiled with Go 1.19, the version in the CAPI go.mod could stay on 1.17 if we want to)
* This means that when we would bump the version in go.mod, we would require all our consumers to use at least this Go minor version to compile their binaries, while they could still keep an older go version in their go.mod file.

/kind cleanup

**Comment by sbueringer** [comment]
cc @fabriziopandini @jackfrancis

**Comment by jackfrancis** [comment]
The above lgtm.

My only recommendation would be a statement that we should aim to have no delta between the go.mod outcome and the version of golang used to compile release binaries. If we do then strictly speaking we aren't testing what we're releasing.

Not saying that's the lowest hanging fruit, but if we're compiling aspirational goals I'd vote for that to be in the list

Thanks for putting all this together @sbueringer!

**Comment by fabriziopandini** [comment]
/triage accepted
Thanks for this work of reasearch!

+1 to bump to 1.19.5 and 1.18.10
I consider that the skew we had in 1.2 (go.mod 1.17, compile to 1.18) has been an exception due to the introduction of generics, so we should be ok from now on.

Wondering if we should write something in our contribution guidelines. something like

For each branch, we will bump to the latest go patch release available for the go version in use of that branch
If the go version for a specific branch goes out of support, we will consider if to bump to a newer go version case by case bases, because this might have impacts on everyone importing Cluster API

**Comment by jackfrancis** [comment]
@sbueringer those are all good points, but I would probably say the following:

For the part of go.mod's responsibility that includes allowing (or disallowing) certain golang features/builtins, the best way to ensure hygiene between source and compiled binaries to is to compile w/ the same major.minor of go that is declared in go.mod. For example, as you say, a go.mod of 1.18 doesn't *require* generics, but it will certainly allow them. If our CI is set to compile @ golang 1.17 and our go.mod is configured @ 1.18 then we are going to have a problem.

I think a good pattern to copy is various github actions who re-use the version of golang in the repo's go.mod to determine the version of go as input for the action. For example, I think this is more durable:

```yaml
      - name: install go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
```

compared to this:

```
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19'
```

**Comment by sbueringer** [comment]
>  If our CI is set to compile @ golang 1.17 and our go.mod is configured @ 1.18 then we are going to have a problem.

Yup. The problem is that it won't even compile
