### ISSUE TITLE
Support for Kubernetes Extended Resources

### ISSUE THREAD

**Issue by wmgroot** [kubernetes-sigs/cluster-api#7975]
**User Story**

As a cluster administrator, I would like to allow my users to request extended resources, such as network bandwidth or disk IOPS to improve the scheduling of workloads that are sensitive to these resources not managed directly by K8s and the container runtime.

**Detailed Description**

Kubernetes supports configuring "[Extended Resources](https://kubernetes.io/docs/tasks/administer-cluster/extended-resource-node/)" for nodes, which can be requested by Pods just like any other resource. These extended resources don't support limits, such as CPU throttling or eviction when memory limits are reached. They do allow Kubernetes to make scheduling decisions about placing pods that both request an extended resource on the same node. This will help the scheduler to avoid scheduling IO hungry workloads together if configured correctly by the cluster administrators and owners of pods requesting these extended resources.

Adding a field on an appropriate node template CRD (maybe KubeadmConfigTemplate?) would allow cluster admins to manage these extended resources using Infrastructure as Code, rather than requiring REST API calls to the K8s apiserver. The CAPI controller would read the configuration of the custom resource defining these extended resources, and patch the nodes through the K8s API as they joined the cluster.

Known Obstacles
* These resources could differ within the same MachinePool, for example, if a MachinePool supports multiple AWS EC2 instance types with different maximum network bandwidth amounts.
* Placing the resource configuration into custom resource specs means that a user would likely need to write automation to determine the correct resource amounts, rather than it being pulled automatically from each cloud providers instance metadata APIs. Cloud provider specific implementations would yield better automation for cluster admins, but it would be more effort to implement.

/kind feature

**Comment by fabriziopandini** [comment]
/triage accepted

I think this requires some thinking about the API.
Registering extended resources in the API server is something that probably belongs to the Cluster, but setting extended resources for each machine/node is more nuanced given that as of today the concept of resources for each machine is deferred to infrastructure providers, and in some cases, it is derived from machine type/instance type.
It will be great to have more opinions about this...

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.
Let's keep this around to see if someone volunteers to do the necessary design work, otherwise the issue will eventually close automatically
/kind proposal

**Comment by fabriziopandini** [comment]
/close
due to lack of interest
