### ISSUE TITLE
Nodes get stuck in provisioned state because of failing refresh of credentials

### ISSUE THREAD

**Issue by AljoschaP** [kubernetes-sigs/cluster-api#7989]
**What steps did you take and what happened:**

## Short description:

When upgrading the cluster-api-controller to a version > 1.2.5 nodes get stuck in provisioned state and never reach the running state.

## Detailed description:

Our current setup consists of one management cluster responsible for itself and two workload clusters where all resources are located in different namespaces. We use AWS and the CAPA controller in version 2.0.2. We recognized the problem first, when we did an upgrade from 1.2.5 to 1.2.6 (it could be related to https://github.com/kubernetes-sigs/cluster-api/pull/7544). After the upgrade we saw that, after some time, nodes get stuck in the provisioned state and can't join the cluster properly.

![image](https://user-images.githubusercontent.com/12294054/214341264-1fdaeace-ba5c-4680-967c-e7505f6971d6.png)

When this state is reached, it seems that there is something wrong with the client credentials for the workload cluster because the log contains many entries like this one:

```
I0124 15:52:49.930948       1 reflector.go:257] Listing and watching *v1.Node from k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169
W0124 15:52:49.934248       1 reflector.go:424] k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.Node: Unauthorized
E0124 15:52:49.934533       1 reflector.go:140] k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.Node: failed to list *v1.Node: Unauthorized
```
So it seems that something with the refresh of the client credentials is not working anymore. What we can see is that the controller tries to create a new cluster accessor repeatedly for the different clusters but also that it runs into some sort of lock (which seems to be introduced by https://github.com/kubernetes-sigs/cluster-api/pull/7544):

```
0124 13:48:34.701004       1 machineset_controller.go:754] "Unable to retrieve Node status" err="failed to create cluster accessor: failed to get lock for cluster: cluster is locked already" controller="machineset" controllerGroup="cluster.x-k8s.io" controllerKind="MachineSet" MachineSet="******/workers-worker-0-58fb9c499d" namespace="******" name="workers-worker-0-58fb9c499d" reconcileID=e8476f23-ab51-4b2d-8352-1866806f02dd MachineDeployment="******/workers-worker-0" Cluster="cluster-*****/*********" Machine="******/workers-worker-0-58fb9c499d-hvnxh" node=""
E0124 13:48:34.704719       1 machineset_controller.go:754] "Unable to retrieve Node status" err="failed to create cluster accessor: failed to get lock for cluster: cluster is locked already" controller="machineset" controllerGroup="cluster.x-k8s.io" controllerKind="MachineSet" MachineSet="******/workers-worker-0-58fb9c499d" namespace="******" name="workers-worker-0-58fb9c499d" reconcileID=e8476f23-ab51-4b2d-8352-1866806f02dd MachineDeployment="******/workers-worker-0" Cluster="******/******" Machine="******/workers-worker-0-58fb9c499d-z4d6g" node=""
E0124 13:48:34.704762       1 machineset_controller.go:754] "Unable to retrieve Node status" err="failed to create cluster accessor: failed to get lock for cluster: cluster is locked already" controller="machineset" controllerGroup="cluster.x-k8s.io" controllerKind="MachineSet" MachineSet="******/workers-worker-0-58fb9c499d" namespace="******" name="workers-worker-0-58fb9c499d" reconcileID=e8476f23-ab51-4b2d-8352-1866806f02dd MachineDeployment="******/workers-worker-0" Cluster="******/******" Machine="******/workers-worker-0-58fb9c499d-4ltkt" node=""
E0124 13:48:34.704811       1 machineset_controller.go:754] "Unable to retrieve Node status" err="failed to create cluster accessor: failed to get lock for cluster: cluster is locked already" controller="machineset" controllerGroup="cluster.x-k8s.io" controllerKind="MachineSet" MachineSet="******/workers-worker-0-58fb9c499d" namespace="******" name="workers-worker-0-58fb9c499d" reconcileID=e8476f23-ab51-4b2d-8352-1866806f02dd MachineDeployment="******/workers-worker-0" Cluster="******/******" Machine="******/workers-worker-0-58fb9c499d-qcq99" node=""
E0124 13:48:34.704849       1 machineset_controller.go:754] "Unable to retrieve Node status" err="failed to create cluster accessor: failed to get lock for cluster: cluster is locked already" controller="machineset" controllerGroup="cluster.x-k8s.io" controllerKind="MachineSet" MachineSet="******/workers-worker-0-58fb9c499d" namespace="******" name="workers-worker-0-58fb9c499d" reconcileID=e8476f23-ab51-4b2d-8352-1866806f02dd MachineDeployment="******/workers-worker-0" Cluster="******/******" Machine="******/workers-worker-0-58fb9c499d-m7t2r" node=""
```

At this point only a restart of the controller solves the problem for us. If we downgrade the controller to 1.2.5 everything is working again.

**What did you expect to happen:**
I would expect that the nodes can join the cluster even if the client credentials need to be refreshed.

**Anything else you would like to add:**

I can update the issue with some information from gops if that could be helpful for you :-)

**Environment:**

- cluster-api-provider-aws version: 2.0.2
- Cluster-api version: 1.3.2
- minikube/kind version:
- Kubernetes version: (use `kubectl version`): 1.23
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by AljoschaP** [comment]
@killianmuldoon Just ping me, if you need more information. Thank you very much! :+1:

**Comment by killianmuldoon** [comment]
Thanks @AljoschaP! I'll take a look at this soon

**Comment by killianmuldoon** [comment]
Just so I can attempt to reproduce, what sort of scale were you operating at here? Can you give me a rundown of no. Clusters, MDs and Machines approx?

**Comment by AljoschaP** [comment]
3 clusters, 19 machine deployments and 50-60 machines

**Comment by killianmuldoon** [comment]
I've been trying to repro by:
-  creating 3 clusters with 5 * 4 MDs on CAPI v1.2.5 
- updating to CAPI v1.2.6
- concurrent with step 2 trying scaling, upgrade, and non-upgrade MD rollout scenarios
I haven't had any luck with replication yet though. @AljoschaP is this  consistently reproducible for you?

**Comment by AljoschaP** [comment]
I was afraid that it will be very hard to reproduce and I assume that it could be a perfect storm somehow. Yes, its very consistent and I tried it with different versions (1.2.6 and 1.2.9 if I remember it correctly) and currently we're running 1.3.2 and it still occurs. If I downgrade capi to 1.2.5 it disappears.

I can try to reproduce it on another cluster with only one workload cluster with 11 MDs and 15 machines.

**Comment by AljoschaP** [comment]
Because of a scaling operation. We shutdown our environments every evening and in the morning a lot of pods/machines are started when we startup everything again. But it also happens when only some pods/machines are launched over the day. I'm not sure if it also happens when machines are started one by one or if it only occurs when machines are launched in parallel. Thats something I could check.

**Comment by AljoschaP** [comment]
Not all 60 machines but maybe 15-20 machines and yes the management cluster stays up overnight.
