### ISSUE TITLE
Support Deploying NodeLocal DNS during init phase of a kubeadm cluster

### ISSUE THREAD

**Issue by rosskirkpat** [kubernetes-sigs/cluster-api#8011]
**User Story**

As a developer and end-user, I want cluster-api to be able to manage the configuration and deployment of NodeLocal DNS.

**Detailed Description**

Currently, NodeLocal DNS has to be deployed after a cluster is created (usually, this is a manual process following https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/#configuration), which will cause a state mismatch when certain cluster actions are performed (ex. upgrades). The mismatch is caused by the CAPI managed state for the cluster _not_ having any concept of nodelocal dns, only the standard coredns deployment.

I am actively working on this feature and aim to have a PR up in the next few business days.

The design I will be proposing in my PR will add a `NodeLocal` configuration block to the `DNS` struct under ClusterConfiguration. 

During a kcp reconciliation and prior to the NewControlPlane call, there will be an if check to see if nodeLocal is set to enabled. If it is, nodelocal dns will have the required resources configured and deployed. 

**Anything else you would like to add:**

This PR will also add IPVS support for kube-proxy during the init phase as well as adding the necessary plumbing for IPVS + nodelocal dns.

/kind feature

**Comment by sbueringer** [comment]
Same question as on the other issue, should this be implemented in kubeadm?

**Comment by fabriziopandini** [comment]
/close

The bootstrap provider hosted in this repo, CABPK, relies on kubeadm for managing the DNS, and thus this should be implemented in kubeadm first, then we can reconsider in CAPI.
As an alternative, a custom bootstrap provider should be implemented, TBD if and how this can work with KCP in its current form
