### ISSUE TITLE
Support using ipvs mode for kube-proxy during init phase of a kubeadm cluster

### ISSUE THREAD

**Issue by rosskirkpat** [kubernetes-sigs/cluster-api#8012]
**User Story**

As a developer and end-user, I want cluster-api to be able to manage the configuration of kube-proxy specific to ipvs.

**Detailed Description**

Currently, IPVS has to be enabled after the initial deployment of the cluster, which requires all nodes to be rebooted. This results in a state mismatch when certain cluster actions are performed (ex. upgrades). The mismatch is caused by the CAPI managed state for the cluster _not_ having any concept of ipvs mode being enabled for kube-proxy, resulting in iptables mode (the default) being set post-upgrade, which requires additional node reboots and has an extremely high chance of outage/downtime.

I am actively working on this feature and aim to have a PR up in the next few business days.

The design I will be proposing in my PR will add a `KubeProxy` struct containing an `IPVS` configuration block to the under ClusterConfiguration. 

During a kcp reconciliation and prior to the NewControlPlane call, there will be an if check to see if ipvs mode is set to enabled. If it is, kube-proxy will have the IPVS-specific configuration applied to the cluster configuration and the resulting machines will have IPVS mode enabled on first boot, removing the need to reboot nodes that are switched from iptables -> ipvs. 

**Anything else you would like to add:**

I am also going to enable IPVS support for nodelocal DNS as part of my PR, which includes setting the `cluster-dns` param for kubelet to the nodeLocal DNS listen address that was defined in configuration.

/kind feature

**Comment by sbueringer** [comment]
I wonder if this feature should be implemented in kubeadm first, given that our entire current ClusterConfiguration struct is kept in sync with the one from kubeadm

**Comment by rosskirkpat** [comment]
> I wonder if this feature should be implemented in kubeadm first, given that our entire current ClusterConfiguration struct is kept in sync with the one from kubeadm

I was not aware that we those are kept in sync, that is good to know. Given that, would it make more sense if I nested the NodeLocal DNS and IPVS config inside of InitConfiguration instead of ClusterConfiguration? 

I am planning to block enabling ipvs to the init phase only due to the node reboots required if it is done after a cluster is deployed as capi/k8s should not be responsible for rebooting nodes.

**Comment by killianmuldoon** [comment]
[InitConfiguration is also part of the upstream Kubeadm types](https://github.com/kubernetes-sigs/cluster-api/blob/f9b330698aef416669984ced34b23682dca9ba60/bootstrap/kubeadm/api/v1beta1/kubeadm_types.go#L35). I do think it might be worth opening an issue at the Kubeadm repo to understand that project's take on the feature.

**Comment by chrischdi** [comment]
Just to note: as long as CAPI does not support this directly: a valid workaround could be to use the annotation `controlplane.cluster.x-k8s.io/skip-kube-proxy` [[0]](https://main.cluster-api.sigs.k8s.io/reference/labels_and_annotations.html) and deploy kube-proxy manually or via a ClusterResourceSet.

**Comment by fabriziopandini** [comment]
/close

The bootstrap provider hosted in this repo, CABPK, relies on kubeadm for managing the kube proxy, and thus this should be implemented in kubeadm first, then we can reconsider in CAPI.
As an alternative, a custom bootstrap provider should be implemented, TBD if and how this can work with KCP in its current form
