### ISSUE TITLE
Removing jobs for unsupported release branches

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8039]
## Context

Currently we run tests for all release branches since v0.3, but actually supported are only v1.2 and v1.3.

## Motivation

Let's focus on maintaining test jobs of relevant releases. It's not worth the effort to maintain branches of releases which have been out of supported for a while. Especially as they start failing over time for reasons unrelated to Cluster API (e.g. [registry migration](https://github.com/kubernetes-sigs/cluster-api/issues/7811#issuecomment-1370573057)).

## Proposal

Policy: 
> Let's only keep jobs of the currently supported releases and 1 additional release in case we have to do an emergency patch release.

Now let's apply the policy to our current jobs:
* We keep the jobs for:
  * release-1.3 => still supported
  * release-1.2 => still supported
  * release-1.1 => we keep the job for one more release cycle, they will be dropped after the v1.4.0 release
* We remove the jobs for:
  * release-1.0, release-0.4, release-0.3: they are out of support for longer than one release cycle.

## Tasks

* [x] Document policy and update release tasks: #8118
* [x] Drop jobs in test-infra: https://github.com/kubernetes/test-infra/pull/28808

/kind cleanup
/area testing

**Comment by furkatgofurov7** [comment]
I am happy to help with the clean up, once we agree with all community members (including downstream).

**Comment by sbueringer** [comment]
Sounds good. I've assigned the issue to myself in the sense of that I want to ensure that the issue makes progress / is implemented. Happy to delegate the implementation / collaborate on the implementation

**Comment by sbueringer** [comment]
cc @kubernetes-sigs/cluster-api-release-team

**Comment by fabriziopandini** [comment]
/triage accepted
yay! this is a nice cleanup, it contributes to the log term health of the projects and it also helps the K8s community in the effort of containing infra costs.

**Comment by CecileRobertMichon** [comment]
+1

**Comment by cpanato** [comment]
+1 let me know if i can open the PR to remove those

**Comment by sbueringer** [comment]
I've opened a PR to document the policy and update the release tasks: #8118

Once this PR is merged someone can open a PR to drop the jobs.

**Comment by sbueringer** [comment]
I'll merge #8118 tomorrow.

@furkatgofurov7 @cpanato One of you can prepare the PR to drop the jobs for <= v1.4 if you want.

**Comment by furkatgofurov7** [comment]
> @furkatgofurov7 @cpanato One of you can prepare the PR to drop the jobs for <= v1.0 if you want. (including the dashboards)

@sbueringer sure, I'll send a PR today

**Comment by furkatgofurov7** [comment]
@sbueringer @cpanato PTAL: https://github.com/kubernetes/test-infra/pull/28808

**Comment by sbueringer** [comment]
All done.

Thx everyone!

/close
