### ISSUE TITLE
Add context to reconciler event handlers

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#8054]
With the release of the next version of controller runtime event handlers will be able to take a real context - https://github.com/kubernetes-sigs/controller-runtime/pull/2139.

Currently our reconciler event handlers - e.g. mapping functions for Watches - are using context.TODO(). With the next release of Controller Runtime we can (and should) replace them with real context objects.

/kind cleanup

**Comment by sbueringer** [comment]
Thx for opening an issue. I'll add a sub-task in my umbrella issue.
It's currently focused on CR v0.14 but I'm already collection things for v0.15 there and will split it up soon.

(xref: https://github.com/kubernetes-sigs/cluster-api/issues/7925)
