### ISSUE TITLE
Consider linking the Kubernetes New Contributor Course in our book

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8061]
Kubernetes recently added a New Contributor Course to their book: https://www.kubernetes.dev/docs/onboarding/

While it is targeted at k/k development I think ~80% of it is relevant for new CAPI contributors as well.

I wonder if we should link it (and probably a few more other pages from kuberntes.dev as well) in our CAPI book

/kind documentation

**Comment by sayantani11** [comment]
That's great idea!! I can help with it if required.

**Comment by oscr** [comment]
I think it's a great suggestion to add link(s).

@sayantani11 If you'd like to work on this please feel free to assign yourself. If you have any practical questions, please don't hesitate to ask.

**Comment by Sajiyah-Salat** [comment]
hello @sbueringer I would like to work on this. Let me know where you would like to see the changes as I am a beginner and finding the appropriate page is hard for me.

**Comment by sbueringer** [comment]
No strong opinions from my side. @oscr what do you think?

**Comment by oscr** [comment]
I think in the beginning(?) of [CONTRIBUTING.md](https://github.com/kubernetes-sigs/cluster-api/tree/main/CONTRIBUTING.md) would be a good place. It's our starting point for new contributors so I think it would be a good place to add it.

**Comment by Sajiyah-Salat** [comment]
Ohk @oscr I will do that shortly.
