### ISSUE TITLE
Pull vs. push on a scaled out star deployment topologies

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api#8080]
**User Story**

As an operator, I would like to use CAPI in a scaled-out star topology. 

**Detailed Description**

For example, I would like to potentially manage O(10^4+) sites.  In this scenario, centralized push management does not scale well.  In this deployment configuration, the controllers should run independently on the workload clusters and pull configuration from a centralized location, which could be a management cluster namespace or potentially something like a github url.  This model more closely matches core k8s watch architecture.  

There are a bunch of security implications to this type of deployment scenario, namely certificate/credential management as well as possible rotation.  

**Anything else you would like to add:**

P.S. - (I think I may have written an issue about this a couple of years ago).  

/kind feature

cc @fabriziopandini @yastij

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

It is clear in my mind we need this, but not sure if and when we will get there given that the dedicated working group stalled...

/close
