### ISSUE TITLE
workload kubernetes version upgrade from 1.24.3 to 1.24.10 is failing

### ISSUE THREAD

**Issue by sadysnaat** [kubernetes-sigs/cluster-api#8092]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

Create a cluster using cluster-api 1.3.2 

k8s version 1.24.3

which generates kubeadm-config confimap with image repository `k8s.gcr.io` 

then when I upgrade to 1.24.10 

the new repository changes kick in and image repository is change to `registry.k8s.io`
but as  coredns info is not updated in kubeadm-configmap 

new node fails with errors 

```
[2023-02-10 07:35:54] 	[ERROR ImagePull]: failed to pull image registry.k8s.io/coredns:v1.8.6: output: time="2023-02-10T07:35:54Z" level=fatal msg="pulling image: rpc error: code = NotFound desc = failed to pull and unpack image \"registry.k8s.io/coredns:v1.8.6\": failed to resolve reference \"registry.k8s.io/coredns:v1.8.6\": registry.k8s.io/coredns:v1.8.6: not found"
```

because coredns and kube-proxy images are not getting updated as part of 
https://github.com/kubernetes-sigs/cluster-api/blob/bc98c722e359066c1dc94534c498486d9891f866/controlplane/kubeadm/internal/controllers/controller.go#L382

they happen after rollout has been done 

https://github.com/kubernetes-sigs/cluster-api/blob/bc98c722e359066c1dc94534c498486d9891f866/controlplane/kubeadm/internal/controllers/controller.go#L435

**What did you expect to happen:**
kubernetes 1.24.3 to 1.24.10 upgrade to happen without errors

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 1.3.2
- minikube/kind version: 0.14
- Kubernetes version: (use `kubectl version`): 1.24
- OS (e.g. from `/etc/os-release`): Darwin *** Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

/Attached 
[coredns.txt](https://github.com/kubernetes-sigs/cluster-api/files/10705629/coredns.txt)
[kubeadm-config.txt](https://github.com/kubernetes-sigs/cluster-api/files/10705630/kubeadm-config.txt)

**Comment by sbueringer** [comment]
Which kubeadm patch version are you using on your 1.24.10  machines?

**Comment by sbueringer** [comment]
Please see https://github.com/kubernetes-sigs/cluster-api/issues/7833 for more details

**Comment by sadysnaat** [comment]
@sbueringer your hint was spot on 

My images were incorrect 
kubeadm 1.24.10 join was happening in 1.24.3 image hence the issue 

I have verified with correct images 
upgrade goes fine. 

This is not an capi or kubeadm issue. Issue was with my image resolution and usage

**Comment by killianmuldoon** [comment]
Thanks for following up with this @sadysnaat!
