### ISSUE TITLE
Consider using ginkgo.BeComparableTo instead of ginkgo.Equal

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8095]
> A few days ago I found myself very frustrated (again) with the fact that the widely used Go test assertion library, gomega, has an Equal() matcher that, when the equality assertion fails, emits the entire contents of both structs being compared. This makes finding which specific field was different a chore, especially when working with very large structs. I started looking at a way to improve this, and I found that there is a better option! Gomega added a BeComparableTo() [matcher](https://onsi.github.io/gomega/#becomparabletoexpected-interface-options-cmpoption) earlier this year that uses the gocmp package and it outputs a diff of exactly which fields are different instead of the entire object! This is a huge time saver, so I thought I would share in case anyone else runs into something similar.
> https://kubernetes.slack.com/archives/C8TSNPY4T/p1670011256246809

Sounds like a great improvement to me. Would be good if something can try it out and potentially open a PR if it works as expected in our case

Kudos @dthorsen for bringing this up

/kind cleanup
/area testing

**Comment by sbueringer** [comment]
cc @killianmuldoon @schrej (just because of somewhat related work on komega in CR)

**Comment by schrej** [comment]
Thanks! `komega.EqualObject()` currently outputs a list of non-matching paths (which is useful when wanting to exclude them, but being too lazy to write them yourself), but shows both objects separately. I'll see if I can add a diff output similar to `BeComparableTo()`.

**Comment by fabriziopandini** [comment]
I understand go-cmp does much more than plain equality, but plain equality is what we need in most cases and using BeCompatableTo is less readable than Equal when checking equality 

What about proposing to add a DeepEqual alias in gomega calling BeCompatableTo without options?

**Comment by dthorsen** [comment]
The naming of `BeComparableTo` is unfortunate, but what it is really doing is calling go-cmp's `Equal()`. So we are actually testing deep equality. 

The benefit here is that when comparing structs (especially large ones), the output of `gomega.BeComparableTo` is infinitely more readable than that of `gomega.Equal`. This is because it outputs only the different lines and a little context around them.

When not comparing large structs and simply comparing small values like most strings, int, bool, etc `gomega.Equal` is fine.

**Comment by sbueringer** [comment]
As someone who regularly has to compare large struct dumps by gomega manually I would really appreciate if we find a way to use the functionality that `BeComparableTo` provides

**Comment by fabriziopandini** [comment]
> The naming of BeComparableTo is unfortunate, but what it is really doing is calling go-cmp's Equal(). So we are actually testing deep equality.

Given that we agree on this, +1 to propose a change/an alias into gomega
