### ISSUE TITLE
clusterctl generate not accepting environment variable

### ISSUE THREAD

**Issue by lentzi90** [kubernetes-sigs/cluster-api#8097]
One of the variables in CAPM3 `infrastructure-components.yaml` does not seem to recognize the environment variable, but happily takes the value from `clusterctl.yaml`.

**What steps did you take and what happened:**

```bash
# Download the infrastructure-components.yaml for CAPM3
curl -sLO https://github.com/metal3-io/cluster-api-provider-metal3/releases/download/v1.3.0/infrastructure-components.yaml
# Check that there is a variable for "enableBMHNameBasedPreallocation".
clusterctl generate yaml --from infrastructure-components.yaml --list-variables
# Check the yaml file itself. It should show a flag like this: 
# --enableBMHNameBasedPreallocation=${enableBMHNameBasedPreallocation:=false}
grep enableBMHNameBasedPreallocation infrastructure-components.yaml
# Check that the default works as expected (flag is set to false)
clusterctl generate yaml --from infrastructure-components.yaml | grep enableBMHNameBasedPreallocation
# Try setting it to true by using environment variables
export enableBMHNameBasedPreallocation="true"
clusterctl generate yaml --from infrastructure-components.yaml | grep enableBMHNameBasedPreallocation
# Result: It is still set to false!

# Try setting the variable through clusterctl.yaml instead.
unset enableBMHNameBasedPreallocation
echo "enableBMHNameBasedPreallocation: true" > clusterctl.yaml
clusterctl --config clusterctl.yaml generate yaml --from infrastructure-components.yaml | grep enableBMHNameBasedPreallocation
# Result: It is set to true!
```

**What did you expect to happen:**

The flag should take the value from the environment variable (and it should have higher priority than the value in `clusterctl.yaml`).

**Anything else you would like to add:**

The other variable in this file (CAPM3_FAST_TRACK) works as expected and I cannot tell why it is in any way different.

**Environment:**

- Cluster-api version: v1.3.3
- minikube/kind version: -
- Kubernetes version: (use `kubectl version`): -
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04

/kind bug
/area clusterctl

**Comment by sbueringer** [comment]
Interesting

cc @ykakarap @Jont828

**Comment by aniruddha2000** [comment]
Investigating the code I found there is something wrong with this part -

https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/yamlprocessor/simple_processor.go#L122-L125

```diff
tmp, err = envsubst.Eval(tmp, func(in string) string {
-	v, _ := variablesClient(in)
+       v := os.Getenv(in)
	return v
})
```

replacing with `os.Getenv()` gets the env var successfully and if I run 

```shell
$ export enableBMHNameBasedPreallocation="true"
$ ./bin/clusterctl generate yaml --from infrastructure-components.yaml | grep enableBMHNameBasedPreallocation
        - --enableBMHNameBasedPreallocation=true
```

There may be some issue with `input.ConfigVariablesClient.Get` at [clusterctl/client/repository/template.go#L116](https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/repository/template.go#L116).

But actually, I am not sure if we are using this [clusterctl/client/config/reader_memory.go#L63-L68](https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/config/reader_memory.go#L63-L68) `Get` method or not.

**Comment by LuBingtan** [comment]
I'm not sure if this is an expected behavior. If we need to fix it, I'd like to take this up 😄

**Comment by fabriziopandini** [comment]
If the problem is in viper assuming the env variables names are all upper case, IMO this should be fixed there.

Also the fix proposed above IMO is not correct, because we intentionally use the variableClient everywhere, and the default VariableClient implementation relies on viper to allow users to define clusterctl variables both as env variables or as an entry in the clusterctl config file

What we can do at this state in CAPI is to document this viper behavior somewhere in the book, e.g. https://cluster-api.sigs.k8s.io/clusterctl/configuration.html#variables

**Comment by musaprg** [comment]
Let me take this up since it looks like a tiny fix of the docs.

/assign
/lifecycle active
