### ISSUE TITLE
Recommendations for upgrading Cluster API

### ISSUE THREAD

**Issue by oscr** [kubernetes-sigs/cluster-api#8098]
In the "Upgrading management and workload clusters" section of the CAPI book it states:
```
In addition, you must always upgrade between Kubernetes minor versions in sequence, e.g. if you need to upgrade from
Kubernetes v1.17 to v1.19, you must first upgrade to v1.18.
```
[source](https://github.com/kubernetes-sigs/cluster-api/blob/329753cae2c23d0f29a764870dc99972a50036b0/docs/book/src/tasks/upgrading-clusters.md?plain=1#L13-L14)

However from what I can see there are no recommendations how to upgrade CAPI. Is it also recommended to upgrade in sequence or to just jump to latest and greatest contract version? I would like to suggest adding a section to the book that includes this information.

**Comment by killianmuldoon** [comment]
Good timing :slightly_smiling_face: - this PR was opened recently https://github.com/kubernetes-sigs/cluster-api/pull/8073

**Comment by oscr** [comment]
Awesome! Thank you @killianmuldoon for pointing that out! :pray: 

/close
