### ISSUE TITLE
ClusterClass: Allow more fine-granular control of MachineDeployment upgrades

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8100]
### Context
When the `Cluster.spec.topology.version` is changed the Cluster topology reconciler will first upgrade the control plane and then one MachineDeployment after another (sequentially). The MachineDeployments are upgraded in the order in which they are defined in `Cluster.spec.topology.workers[]`.

### Use cases

For operators of big clusters it might take days to upgrade an entire Cluster. Thus, it's not good enough that the Cluster topology reconciler upgrades the entire cluster in one go if the Kubernetes upgrade has to be done in maintenance windows that only last a few hours.

Workload running on specific nodes / Machines / MachineDeployments might need more time to adjust to the new Kuberntes version and thus the upgrade of those MachineDeployments should be temporarily deferred.

### Proposal

**Introduce a "topology.cluster.x-k8s.io/hold-upgrade-sequence" annotation (applied on a MachineDeployment in Cluster.spec.topology.workers)**

When the MachineDeployment upgrade with ClusterClass will process a MachineDeployment with this annotation, the entire upgrade process will be suspended until the annotation will be removed.

Examples:
* If you want to pause upgrade after CP upgrade, this annotation should be applied to the first MachineDeployment in the list of MachineDeployments in Cluster.spec.topology. The upgrade will not be completed until the annotation is removed and all MachineDeployments are upgraded.
* If you want to pause upgrade after the 50th MachineDeployment, this annotation should be applied to the 51th MachineDeployment in the list.

**Introduce a "topology.cluster.x-k8s.io/defer-upgrade" annotation (applied on a MachineDeployment in Cluster.spec.topology.workers)**

When the MachineDeployment upgrade with ClusterClass will process a MachineDeployment with this annotation, **only the upgrade for this MachineDeployment** will be deferred. Other MachineDeployments will still be upgraded.

Example:
* If you want to defer the upgrades of the 3rd and 5th MachineDeployments of the list, set the annotation on them. The upgrade process will upgrade MachineDeployment in position 1,2, (skip 3), 4, (skip 5), 6 etc. The upgrade will not be completed until the annotation is removed and all MachineDeployments are upgraded.

### Notes
* The Cluster topology controller will only consider annotations in Cluster.spec.topology.workers (not on the MachineDeployments themselves)
* The `TopologyReconciled` condition will remain false until the upgrade is completed for all MachineDeployment.

Kudos to @fabriziopandini for the previous discussions on this topic!!

/kind feature
/area topology

**Comment by richardcase** [comment]
@sbueringer - this was a very helpful issue definition when coming to look at the PR, thank you 🥇
