### ISSUE TITLE
API Object is being deleted for `clusterctl move` should have an annotation to identify move operation

### ISSUE THREAD

**Issue by pkbhowmick** [kubernetes-sigs/cluster-api#8109]
**User Story**
While object is moving for `clusterctl move` should have an annotation to identify move operation
As a [developer/user/operator] I would like to [high level description] for [reasons]

**Detailed Description**
`clusterctl move` operation is used to move Cluster API objects from one management cluster to another/self managing cluster. But currently while object is deleted from the existing cluster, there is no annotation/mark than can confirm that object is being deleted for the move operation. This cause some issue for deletion webhook as in some case it needs to identify that the object is being deleted for move operation which is not actually a delete(move from one cluster to another).
[A clear and concise description of what you want to happen.]
An annotation will really help in this case to identify the move operation for the webhooks. 
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I have already implemented the patch things [here](https://github.com/pkbhowmick/cluster-api/pull/1/files). I can open PR.
/kind feature

**Comment by sbueringer** [comment]
cc @ykakarap @Jont828

**Comment by pkbhowmick** [comment]
One scenario which could be handled in better way.
https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2656

**Comment by fabriziopandini** [comment]
When move starts we signal the operation by pausing the root objects of each hierarchy we are moving (for sure Cluster and ClusterClass, but not 100 %sure about user-defined hierarchies), and this is used by CAPI controllers to prevent taking actions while the move is performed

**Comment by pkbhowmick** [comment]
Yes, in move operation child objects are deleted first which creates a problem for the deletion webhook to understand the root cause of the delete.

**Comment by pkbhowmick** [comment]
Hi @fabriziopandini
What about the above through? In my opinion, having a move annotation in the deleting objects(for move operation) will save a lot of works for the deletion webhook like this https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2656. We can think about it.

**Comment by fabriziopandini** [comment]
I took a look at the patch proposed in the issue, and I think that we can implement something similar, which could be an additional safeguard on top of the pause annotation on the roo of the different move hierarchies (BTW, as of today we are pausing Cluster and ClusterClasses only).

However, I would like to hear also some other opinions from other maintainers as well before acting on this

**Comment by sbueringer** [comment]
> However, I would like to hear also some other opinions from other maintainers as well before acting on this

cc @ykakarap @Jont828

**Comment by ykakarap** [comment]
> > However, I would like to hear also some other opinions from other maintainers as well before acting on this
> 
> cc @ykakarap @Jont828
> 
> (I personally have to take a closer look and won't have time before mid April at the earliest)

Sorry, I missed the initial ping. I can take a look at this.
