### ISSUE TITLE
Configurable Machine Initial Rollout strategy when creating the cluster

### ISSUE THREAD

**Issue by lubronzhan** [kubernetes-sigs/cluster-api#8112]
**User Story**

As a operator I would like to control the machine rollout strategy when creating the cluster for making sure the scaling of cluster could be more smoothly, in case apiserver can't handle too many newly created node at the same time

**Detailed Description**
We ran into an issue when using k8s 1.22.8, to create 3 control plane node and 33 worker node spread through 5 MachineDeployment on vSphere. RTLinux is used as base image.  After first control plane node is created, all worker nodes and are getting created at the same time, many newly created service on new node kept spamming the apiserver since node is still not ready. The first control plane node CPU spiked, as a result second node are not able to join the node in time and bootstrap token expired. The workaround applied is to extend the bootstrap token ttl time `CapbkBootstrapTokenTtl `.

We know during the upgrade of Machine of the MachineDeployment, we have strategy to define max number of unavailable Machine https://github.com/kubernetes-sigs/cluster-api/blob/72aa9d1e68971b5b489aa4dfa4c0687fca0d4f4a/api/v1beta1/clusterclass_types.go#L185. Wonder could this also be applied during cluster creation stage, or we define Similar `MachineInitialRollOut` as a strategy, similar to `MachineRollingUpdateDeployment`, gets applied during creation or scaling.
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

This is just some thought, also @ykakarap brought up that auto scaler should also be considered if we have something like this.
[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
@lubronzhan sorry if I missed this issue before.
This is an interesting idea IMO, I would extend it to both scale up and scale down, but it goes in the direction of CAPI being "gentle" on the underlying infrastructure.

However, knowing the codebase of the machine controller, this requires some research before committing to any solution, so I'm adding 
/triage needs-information
/help

**Comment by lubronzhan** [comment]
Oh I forgot I created this Jira before. I can look into the code and come up with some idea first

**Comment by fabriziopandini** [comment]
Just discussed the issue during issue triage. Please note that:

We don't have control on the communications between nodes and their control plane on the workload cluster, if this is causing issues, this should be discussed with other SIGs.

We also don't have control on the timing used to deploy all the Pods one the workload cluster, if this is causing the issue, might be worth consider improvements on the addon automation. Also autoscaling might help here.

However the idea of providing control on the initial worker scaling up is interesting (even if not directly related to the problems above)

/remove-help

while we work on defining enough details to make this actionable
