### ISSUE TITLE
Use run_if_changed consistently for all relevant jobs 

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8151]
Today we use run_If_changed on a lot of presubmit jobs to ensure they are not run if only e.g. documentation is changed.

An example can be seen here: https://github.com/kubernetes/test-infra/blob/cefc15bca2ba72af0802f825aa79b23d075297b9/config/jobs/kubernetes-sigs/cluster-api/cluster-api-presubmits-release-1-3.yaml#L125

This ensures that we are not running tests if they are not required. It would be great if we can use run_if_changed consistently for all jobs that should only be run if our code changes. 

I think the following jobs should also use run_if_changed:
* pull-cluster-api-apidiff-main
* pull-cluster-api-test-main
* pull-cluster-api-test-mink8s-main

Pro:
* less resource usage as we run a lot less jobs
* less waiting around and re-triggering for test jobs that are not relevant to doc PRs

/area testing
/kind feature

**Comment by sbueringer** [comment]
cc @fabriziopandini @killianmuldoon 

cc @furkatgofurov7 (In case you or one of the release team wants to take this task)

**Comment by furkatgofurov7** [comment]
This totally makes sense to me, it saves a lot of resources in many cases (I wish we could utilise the same functionality back in our provider, but we have Jenkins running for the tests not prow😀)



> cc @fabriziopandini @killianmuldoon
> 
> cc @furkatgofurov7 (In case you or someone from the CI team wants to take this task)

great, I can pick this up if there is no one interested working on this.

**Comment by sbueringer** [comment]
Sounds good, (forgot before, of course let's do this change for all branches)

**Comment by furkatgofurov7** [comment]
/assign

@sbueringer do we need it in `pull-cluster-api-e2e-full-<branch_name>` && `pull-cluster-api-e2e-workload-upgrade-1-26-latest-<branch_name>` presubmits as well?

**Comment by sbueringer** [comment]
No. They are optional and just run when someone triggers them manually

**Comment by furkatgofurov7** [comment]
> No. They are optional and just run when someone triggers them manually

Ah yes, forgot that. PTAL https://github.com/kubernetes/test-infra/pull/28822

**Comment by sbueringer** [comment]
PR merged. Thx!
/close
