### ISSUE TITLE
book create just one cluster 

### ISSUE THREAD

**Issue by loveyandex** [kubernetes-sigs/cluster-api#8152]
you say one or more k8s clusters but quck start has just one cluster 
and next question is what is  workload cluster  application is going to run?
![image](https://user-images.githubusercontent.com/53381292/220689806-661e733a-9bf0-4ba3-a54a-68e62933217d.png)

**Comment by fabriziopandini** [comment]
/kind documentation
@loveyandex  feel free to propose improvements to the book, I think that one or two sentences or a small "What's next" paragraph at the end of the quick start could do the trick.
The message to convey is that the users can deploy workloads in the same ways they deployed the CNI, or create additional workload clusters as they deployed the first cluster. 

/triage accepted
/good-first-issue

/title Add what's next paragraph at the end of the quick start

**Comment by Sajiyah-Salat** [comment]
I would like to take this up. can you please confirm like what would you like to see more in whatsnext paragraph othere than one line which you have mentioned above. What more we can add.

**Comment by Sajiyah-Salat** [comment]
hello can we add this? 
To deploy workloads in the same way as the CNI, users can use the same declarative approach to define and manage their workload manifests. This means that they can create manifests that define the desired state of their workloads, and apply them to their cluster using tools like kubectl or other automation tools.

Alternatively, users can also create additional workload clusters using the same declarative approach, defining the desired state of their new cluster as code and then deploying it. This can be useful in scenarios where users need to deploy new clusters for different environments or workloads.

**Comment by killianmuldoon** [comment]
Hi @Sajiyah-Salat - thanks for your interest in this! IMO all we need to do is to add a couple of lines to the existing "Next steps" block at the end of the quick start guide stating:

 - Create a second workload cluster. [Simply follow the steps outlined above](https://cluster-api.sigs.k8s.io/user/quick-start.html#create-your-first-workload-cluster), but remember to provide a different name for your second workload cluster.
 - Deploying applications to your workload cluster - use the [CNI deployment steps for pointers](https://cluster-api.sigs.k8s.io/user/quick-start.html#deploy-a-cni-solution).


Feel free to directly open a PR adding this so we can continue discussion there :slightly_smiling_face:

**Comment by Sajiyah-Salat** [comment]
Sure, I will do that shortly.
