### ISSUE TITLE
Broken book links

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8160]
Looks like we now have a few broken links in our book:

ERROR: 3 dead links found!
[✖] https://kubernetes.io/docs/admin/kube-apiserver/ → Status: 404
[✖] https://kubernetes.io/docs/admin/kube-controller-manager/ → Status: 404
[✖] https://kubernetes.io/docs/admin/kube-scheduler/ → Status: 404

https://github.com/sbueringer/cluster-api/actions/runs/4252572105/jobs/7396332975

/kind documentation
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
cc @oscr @elmiko

**Comment by sbueringer** [comment]
Regarding the change yes, regarding time I'm not sure.

We probably need a quick fix because otherwise all PRs which touch markdown are blocked

**Comment by oscr** [comment]
Then I or someone in comms will fix it during the evening.

**Comment by elmiko** [comment]
i could take a look today

**Comment by oscr** [comment]
@elmiko Awesome! Feel free to ping me when you have a pr to get a quick review

**Comment by elmiko** [comment]
i think @damdo will end up making the patch, but we'll get something up today

**Comment by damdo** [comment]
Hey yes, here is the patch: https://github.com/kubernetes-sigs/cluster-api/pull/8162
