### ISSUE TITLE
Add unit test that covers cluster health check behavior during creation of a new cluster accessor

### ISSUE THREAD

**Issue by AljoschaP** [kubernetes-sigs/cluster-api#8176]
After changing the behavior of the cluster health check when it gets executed during the creation of a new cluster accessor, a unit test that covers this case is needed. This issue is a follow-up task for https://github.com/kubernetes-sigs/cluster-api/pull/8122.

/kind cleanup
/area testing

**Comment by AljoschaP** [comment]
fyi @sbueringer

**Comment by fabriziopandini** [comment]
/close 
given that #8269 is merged
