### ISSUE TITLE
KCP should set MachinesSpecUpToDateCondition to false before create first new machine when rolling update

### ISSUE THREAD

**Issue by haijianyang** [kubernetes-sigs/cluster-api#8179]
**What steps did you take and what happened:**
Any action that triggers a KCP rolling update, such as modify the `kcp.spec.version`.
After the new machine is created, KCP's `MachinesSpecUpToDateCondition` is still not set to false.

**What did you expect to happen:**
KCP should set `MachinesSpecUpToDateCondition` to false before create first new machine when rolling update. And user can know whether KCP is rolling update through `MachinesSpecUpToDateCondition` is false.

**Anything else you would like to add:**
`upgradeControlPlane` creates a new machine before kcp save the
`MachinesSpecUpToDateCondition`.
```go
needRollout := controlPlane.MachinesNeedingRollout()
switch {
case len(needRollout) > 0:
	log.Info("Rolling out Control Plane machines", "needRollout", needRollout.Names())
	conditions.MarkFalse(controlPlane.KCP, controlplanev1.MachinesSpecUpToDateCondition, controlplanev1.RollingUpdateInProgressReason, clusterv1.ConditionSeverityWarning, "Rolling %d replicas with outdated spec (%d replicas up to date)", len(needRollout), len(controlPlane.Machines)-len(needRollout))
	return r.upgradeControlPlane(ctx, cluster, kcp, controlPlane, needRollout)
default:
	if conditions.Has(controlPlane.KCP, controlplanev1.MachinesSpecUpToDateCondition) {
		conditions.MarkTrue(controlPlane.KCP, controlplanev1.MachinesSpecUpToDateCondition)
	}
}
```

**Environment:**

- Cluster-api version: v1.3.1
- minikube/kind version: v0.17.0
- Kubernetes version: v1.24.1
- OS: CentOS 7.9

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
Hm not sure. This is basically how all our controllers work, we usually calculate conditions and write them at the end of the reconcile.

@fabriziopandini WDYT?

**Comment by fabriziopandini** [comment]
I agree with @sbueringer 
There is not much context about the use case behind this issue, but It also feels that making assumptions on a strict ordering of operations in an eventually consistent system like Kubernetes, with informers and caches all around is not the right way to go, not to mention that if we update the API server at every change in the middle of a reconcile this will impact on performance and scalability.

**Comment by haijianyang** [comment]
So how exactly do we know that KCP is rolling update. 
How to distinguish whether the newly created Machine is caused by scale out or rolling update.

**Comment by fabriziopandini** [comment]
/triage needs-information

Still trying to figure out where this discussion is leading.
