### ISSUE TITLE
Use the prebuilt GCE image in Quick Start

### ISSUE THREAD

**Issue by RyuSA** [kubernetes-sigs/cluster-api#8198]
In Quick Start, they need to build a GCE image using image-builder to getting start to GCP Cluster API Providor.

![image](https://user-images.githubusercontent.com/12961775/221885365-5e2d20bd-3067-4683-ab9e-5b7be4907c32.png)

But there are some prebuilt GCE image, like `projects/k8s-staging-cluster-api-gcp/global/images/cluster-api-ubuntu-2004-v1-23-3-nightly`.  ref: kubernetes-sigs/cluster-api-provider-gcp#806
These GCE images make it easy to tutorialize the Cluster API in GCP. Would you like to add this pre-built image to the Quick Start?

I can create a PR. Please let me know.

/kind documentation
/area area/provider/gcp

**Comment by sbueringer** [comment]
cc @richardcase @cpanato (not sure)

**Comment by cpanato** [comment]
I prefer the use builds their image; the images we prebuilt in our staging project are for test usage. I don't know if we pay for data transfer in this case.

**Comment by sbueringer** [comment]
That sounds very reasonable.
