### ISSUE TITLE
gcp-deployer delete can strand VMs if you are using MachineSets

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#82]
_From @roberthbailey on March 18, 2018 18:0_

If you create a MachineSet in your cluster and then run `./gcp-deployer delete`, the delete command will delete each machine and then tear down the cluster. If you have machines that are part of a Machineset, while the `gcp-deployer` is tearing down the machines, the MachineSet is making sure that they exist. The `gcp-deployer` then deletes the master, leaking VM resources after the cluster is deleted. 

_Copied from original issue: kubernetes/kube-deploy#654_

**Comment by rsdcastro** [comment]
_From @krousey on March 19, 2018 15:40_

cc @k4leung4 expressed interest in fixing this. Assigning to me since he's not in the k8s org yet.

/assign @krousey

**Comment by rsdcastro** [comment]
/assign @k4leung4 

Can you update status on this bug and close it out if it's fixed?

**Comment by roberthbailey** [comment]
Closing since we are removing gcp-deployer. Please re-open if you still see this behavior with clusterctl. 

/close
