### ISSUE TITLE
need lifecycle management of secret generated by KubeadmConfig

### ISSUE THREAD

**Issue by wm775825** [kubernetes-sigs/cluster-api#8209]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

i leverage capi and capi-provider-aws to set up and manage k8s clusters based on aws ec2. 

However, when i try to delete cluster by deleting its namespace, it hangs because of a secret. 

KubeadmConfigReconciler will store bootstrap data as a secret. The secret will be populated into machine.Spec.Bootstrap.ConfigRef, which is used by aws machine reconcilier when deleting aws clusters.

When i tried to delete the namespace, this secret was deleted immediately, while deleting cluster was much more slower. When aws machine reconcilation was triggered, it would first try to find this secret by field of owner machine. Unfortunately, the secret was no longer existing, which led to hanging up of aws machines deletion. Cluster could never be cleaned up without manual intervention.

**What did you expect to happen:**

when i delete the namespace, capi cluster and aws clusters could be cleaned up totally, without manual intervention.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

i think capi should manage lifecycle of resources created by iteslf, such as add a finalizer to avoid this situation and other accidental deletions.

**Environment:**

- Cluster-api version: v1.3.3
- Cluster-api-provider-aws version: v2.0.2
- Kubernetes version: (use `kubectl version`): 1.23
- OS (e.g. from `/etc/os-release`): ubuntu 20.04

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by killianmuldoon** [comment]
I think, in general, Clusters should not be deleted by deleting the namespace they're in. 

CAPI uses a deletion order that starts at the Cluster, so clusters should be deleted by deleting the Cluster first and allowing CAPI's internal deletion logic - combined with Kubernetes garbage collection - to clean up the resources in the correct order. 

There's a small note about this in the book here - https://cluster-api.sigs.k8s.io/user/quick-start.html?highlight=delete#clean-up - but it would be good to find a way to communicate this more clearly.
