### ISSUE TITLE
Optimizing presubmit and periodic jobs

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8224]
The goal of this issue is to optimize our presubmit and periodic jobs according to the following principles:
* Only run what makes sense on PRs, i.e.:
  * If no code changes we don't have to run tests and e2e tests.
  * We should only run tests which give us a good signal, we don't have to run tests on PRs that just always succeed / fail together with other tests.
  * => Benefits: less time spent waiting for tests on PRs, less re-triggering of flakes, less resource usage, thus better noise/signal ratio
* All tests/jobs should be also run as periodics to make it easy to assess job stability without having to deal with noise through changes in PRs.
* It should be possible to trigger all relevant periodics on PRs as well for debugging (an exception are the upgrade jobs where the latest one is enough).

Presubmit jobs: (current state + proposal)
* [pull-cluster-api-build-main]
  * mandatory for merge, always run
* [pull-cluster-api-verify-main]
  * mandatory for merge, always run
* [pull-cluster-api-test-main]
  * mandatory for merge, run if go code changes
* [pull-cluster-api-e2e-main]
  * mandatory for merge, run if go code changes
* [pull-cluster-api-test-mink8s-main]
  * mandatory for merge, run if go code changes
  * Proposal: optional for merge, run if manually triggered
    * Justification: in the past never failed if test-main was green, enough to run regularly as periodic
* [pull-cluster-api-e2e-mink8s-main] (should be added)
  * Proposal: optional for merge, run if manually triggered
  * Justification: parity with periodics, otherwise same justification as test-mink8s
* [pull-cluster-api-apidiff-main]
  * optional for merge, run if go code changes
* [pull-cluster-api-e2e-informing-main]
  * optional for merge, run if go code changes
* [pull-cluster-api-e2e-informing-ipv6-main]
  * optional for merge, run if go code changes
  * Proposal: optional for merge, run if manually triggered (also drop informing from the job name)
    * Justification: in the past never failed if e2e-main was green, should be also added as periodic for regular coverage
* [pull-cluster-api-e2e-full-dualstack-ipv6-main]
  * optional for merge, run if manually triggered
* [pull-cluster-api-e2e-full-main]
  * optional for merge, run if manually triggered
* [pull-cluster-api-e2e-workload-upgrade-1-27-latest-main]
  * optional for merge, run if manually triggered
* [pull-cluster-api-e2e-scale-main-experimental]
  * optional for merge, run if manually triggered

This would result in the following presubmit jobs:

* mandatory for merge, always run:
  * [pull-cluster-api-build-main]
  * [pull-cluster-api-verify-main]

* mandatory for merge, run if go code changes:
  * [pull-cluster-api-test-main]
  * [pull-cluster-api-e2e-main]

* optional for merge, run if go code changes
  * [pull-cluster-api-apidiff-main]
  * [pull-cluster-api-e2e-informing-main]

* optional for merge, run if manually triggered
  * [pull-cluster-api-test-mink8s-main]
  * [pull-cluster-api-e2e-mink8s-main]
  * [pull-cluster-api-e2e-ipv6-main]
  * [pull-cluster-api-e2e-full-main]
  * [pull-cluster-api-e2e-full-dualstack-ipv6-main]
  * [pull-cluster-api-e2e-workload-upgrade-1-27-latest-main]
  * [pull-cluster-api-e2e-scale-main-experimental]

Additional changes:
* I would suggest moving the ClusterClass quickstart from e2e-informing to e2e-main and drop the regular quickstart test from e2e-main
  * Justification:
    * The ClusterClass quickstart test tests the same as the regular one it just also covers ClusterClass.
    * The regular quickstart test is still run as part of the periodic.
    * This reduces test and thus also merge duration on PRs.
    * CAPD only provides on cluster template for users, and it is using ClusterClass.

Periodics:
* [periodic-cluster-api-test-main]
* [periodic-cluster-api-test-mink8s-main]
* [periodic-cluster-api-e2e-main]
* [periodic-cluster-api-e2e-dualstack-ipv6-main]
* [periodic-cluster-api-e2e-mink8s-main]
* [periodic-cluster-api-e2e-ipv6-main] (should be added)
  * Justification:
    * Ensure we still regularly run the ipv6 test after we changed the presubmit job to only run when manually triggered.
    * Running this job in periodics makes it easier for the CI team to monitor and reduces the frequency in which the job is run which seems reasonable given the error rate.
* [periodic-cluster-api-e2e-workload-upgrade-1-22-1-23-main]
* [periodic-cluster-api-e2e-workload-upgrade-1-23-1-24-main]
* [periodic-cluster-api-e2e-workload-upgrade-1-24-1-25-main]
* [periodic-cluster-api-e2e-workload-upgrade-1-25-1-26-main]
* [periodic-cluster-api-e2e-workload-upgrade-1-26-1-27-main]
* [periodic-cluster-api-e2e-workload-upgrade-1-27-latest-main]

Thx @killianmuldoon  for the inspiration

cc @kubernetes-sigs/cluster-api-release-team @killianmuldoon @ykakarap @fabriziopandini

/area testing

**Comment by fabriziopandini** [comment]
/triage accepted
I'm +1 with the principle of running jobs only when needed and only if they provide a meaningful signal
The only note for me is about timing, now (before RC) or after the release; I would prefer to keep jobs stable while stabilizing the release

**Comment by sbueringer** [comment]
Sounds fine to me. I can defer it to after the release

**Comment by fabriziopandini** [comment]
/help
Let's also try to get a quick feedback from the release/CI lead opinion on this (cc @ykakarap @furkatgofurov7 )

**Comment by sbueringer** [comment]
Just fyi. In addition to the jobs mention above we now have the following jobs:
* pull-cluster-api-e2e-full-dualstack-ipv6-main
* pull-cluster-api-e2e-scale-main-experimental

Let's ignore them for now

**Comment by furkatgofurov7** [comment]
Alright, to summarize all open PRs' which should lead to close this issue:

- test-infra
    - https://github.com/kubernetes/test-infra/pull/29621
 - CAPI
     - https://github.com/kubernetes-sigs/cluster-api/pull/8765
     - https://github.com/kubernetes-sigs/cluster-api/pull/8763

**Comment by furkatgofurov7** [comment]
/reopen

I will close it once the last PR is merged: #8763

**Comment by furkatgofurov7** [comment]
> /reopen
> 
> I will close it once the last PR is merged: #8763

#8763 is merged now, we can close this.

/close
