### ISSUE TITLE
clustrctl README.md references googledoc requiring login - allow anonymous RO access

### ISSUE THREAD

**Issue by Hefeweizen** [kubernetes-sigs/cluster-api#823]
/kind bug

**What steps did you take and what happened:**
The link to "experience doc here" in the cluster-api/cmd/clusterctl/README.md is a link to a google doc in edit mode.  As such, access requires a login.  This should default to a Read-only view that does not require logging in.

**What did you expect to happen:**
I'm on Github; I did not expect to have to log in to a third-party service to access documentation.

**Anything else you would like to add:**
Certainly, keep editing locked, but switch the default access to read-only and anonymous.

**Environment:**

- Cluster-api version: n/a
- Kubernetes version: (use `kubectl version`): n/a
- OS (e.g. from `/etc/os-release`): n/a
non-technical bug; error in documentation

**Comment by detiber** [comment]
@Hefeweizen The doc requires you to be a member of either the [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev) or [kubernetes-sig-cluster-lifecycle](https://groups.google.com/forum/#!forum/kubernetes-sig-cluster-lifecycle) google groups

**Comment by detiber** [comment]
/remove-kind bug
/kind documentation

We should update the documentation to call out when a document requires Google Group membership.

/priority important-soon
/milestone v1alpha1

**Comment by ncdc** [comment]
@amy will be working on this but I'll assign it to myself for now.
/assign
