### ISSUE TITLE
Cannot upgrade from `ubuntu` to `flatcar` due to some immutable fields in `kubeadmcontrolplane` spec

### ISSUE THREAD

**Issue by primeroz** [kubernetes-sigs/cluster-api#8242]
**What steps did you take and what happened:**

the `kubeadmcontrolplane` spec was updated for ignition support in https://github.com/kubernetes-sigs/cluster-api/pull/4172 

but there is a couple of fields , that i think could be mutable, that were not added to the whitelist and so when upgrading from `ubuntu` to `flatcar` the update fails

```
 reason: 'Upgrade "fctest2" failed: cannot patch "fctest2" with kind KubeadmControlPlane:
    admission webhook "validation.kubeadmcontrolplane.controlplane.cluster.x-k8s.io"
    denied the request: KubeadmControlPlane.controlplane.cluster.x-k8s.io "fctest2"
    is invalid: [spec.kubeadmConfigSpec.format: Forbidden: cannot be modified, spec.kubeadmConfigSpec.mounts:
    Forbidden: cannot be modified]'
```

* spec.kubeadmConfigSpec.format - change to `ignition` 
* spec.kubeadmConfigspec.mounts - due to https://github.com/kubernetes-sigs/cluster-api/issues/7679 

I might be totally wrong but i _think_ it should be safe to change those fields since they will only apply to new Machines created for the CP 

**What did you expect to happen:**
Be able to change those fields and so upgrade in place from `ubuntu` CP nodes to `flatcar` CP Nodes

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:  v1.3.2 
- minikube/kind version:
- Kubernetes version: (use `kubectl version`): 1.24.10
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
Yup. I think that should be safe

/triage accepted

**Comment by primeroz** [comment]
I removed the `UPDATE` verb from the webhook and performed an upgrade from ubuntu to flatcar, it worked just fine as epxected

**Comment by invidian** [comment]
When `kubeadmcontrolplane` is changed, will all controlplane nodes be replaced to reconcile the change?

**Comment by primeroz** [comment]
Yes, one by one like a normal rollout.
