### ISSUE TITLE
[Document] How to provision a k8s cluster with an existing k8s cluster but not bootstrap cluster? 

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#825]
I found that the k8s provision with openstack can either use a bootstrap cluster or use an existing cluster, but there is no document for how to use an existing cluster to provision new k8s cluster, does there are any document that I can refer? Thanks.

**Comment by pierre-emmanuelJ** [comment]
This is the same way, just use `kubeconfig` of your existing cluster. And you can use it with `clusterctl` or `kubectl`.
Little example:
https://github.com/exoscale/cluster-api-provider-exoscale/blob/create-cluster-doc/doc/create-cluster-kubectl.md
I use kind but in this case.
IMPORTANT:
follow the instructions of openstack when you build the `provider-configuration` to apply it to your existing cluster.

**Comment by detiber** [comment]
I've created a similar set of instructions for using the AWS provider with an existing k8s cluster: https://gist.github.com/detiber/8f61767b6d39d65aceab89d5a92589c4

**Comment by ncdc** [comment]
/milestone Next

as per discussion at today's Cluster API meeting

**Comment by jichenjc** [comment]
@gyliu513 maybe we should think about create an openstack own before the cluster API next version.

**Comment by gyliu513** [comment]
@amy any progress for this?
