### ISSUE TITLE
CAPD load balancer crashes on startup

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#8257]
CAPD's load balancer is known to crash by causing a resource leak on some systems - notably Fedora. This issue is caused by the initial configuration of the haproxy container used by CAPD. 

This issue has been partially fixed in https://github.com/kubernetes-sigs/cluster-api/pull/8246 which updates the config to one that will not crash when used with CAPD - i.e. setting maxconn. This [change has also been made in Kind](https://github.com/kubernetes-sigs/kind/issues/2954#issuecomment-1453826595).

The load balancer will still cause a resource leak with its initial configuration, however. The fix for this is either to update to the latest `kindest/haproxy` once one an image with the correct config is published, or to an alternative haproxy image.

Note: The upstream `haproxytect/haproxy-alpine` has sufficient config to avoid the resource leakage (thanks @richardcase!)

See also: https://github.com/kubernetes-sigs/cluster-api/pull/7344#issuecomment-1462274731

/assign
/area provider/docker
/kind bug

**Comment by sbueringer** [comment]
Given how long we lived with this issue, I would prefer waiting for the next kindest/haproxy image.

I"m not sure when it will be released, but we could ask.

**Comment by killianmuldoon** [comment]
>Given how long we lived with this issue, I would prefer waiting for the next kindest/haproxy image.

Agreed - there's no rush on this. Just wanted to capture the info from the closed PRs and track the image bump somewhere.

**Comment by sbueringer** [comment]
Yup. Just saw the two options in the issue description, which is why I wrote which one I would prefer 😃

**Comment by richardcase** [comment]
@sbueringer @killianmuldoon - i'm curious why there is a preference to use the kindest image and not an upstream image?

**Comment by killianmuldoon** [comment]
From my PoV - CAPD is tightly coupled to kind, so there's no real separation from changing to an upstream image. 

Otherwise this is a part of the code that's worked well for a long time without changes. I don't see any real upside to making the change to a new image, so I default to not changing it. But really I don't have very strong opinions here.

**Comment by richardcase** [comment]
Thats good to know, thanks for explaining @killianmuldoon :+1:
