### ISSUE TITLE
Setup jobs and dashboards for release-1.4 branch

### ISSUE THREAD

**Issue by furkatgofurov7** [kubernetes-sigs/cluster-api#8270]
### What would you like to be added (User Story)?

Setup jobs and dashboards for release-1.4 branch in test-infra repository

### Detailed Description

Soon, the release-1.4 branch is going to be created. Now we can setup the jobs in test-infra for that branch.
The steps to follow: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#setup-jobs-and-dashboards-for-a-new-release-branch

### Anything else you would like to add?

Part of #7672

### Label(s) to be applied

/kind feature

**Comment by sbueringer** [comment]
> @ykakarap @sbueringer @fabriziopandini release tasks document mentions the following:
> 
> `Remove tests for old release branches according to our policy documented in [Support and guarantees](https://github.com/kubernetes-sigs/cluster-api/blob/main/CONTRIBUTING.md#support-and-guarantees) For example, let's assume we just created tests for v1.4, then we can now drop test coverage for the release-1.1 branch.`
> 
> Do we have to drop the tests with the same PR where we are adding new tests for v1.4 or do it as a follow-up?

We can do it in a follow-up. ALso have to check if there is something to do this time, given that we just removed jobs.

**Comment by furkatgofurov7** [comment]
> We can do it in a follow-up.

Thanks for confirmation, I'll send a follow-up PR for removing them.
