### ISSUE TITLE
Consider creating a util package for mergeMaps, etc.

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8276]
Follow-up:
> I think we should move merge map (and potentially similar things) in a shared util, but this is out of scope of this PR
> https://github.com/kubernetes-sigs/cluster-api/pull/8171#discussion_r1133723008

/kind cleanup

**Comment by fabriziopandini** [comment]
/triage accepted
/help

Let's keep this scoped to mergeMaps, so it is already actionable
