### ISSUE TITLE
Consider merging ClusterClass changes and rollout e2e tests

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8277]
Follow-up:

> Not for now, but I think that if we expand this a little bit this part we can merge ClusterClassChangesSpec into this test

> I was thinking about the overlap between those tests as well.
>
> Currently I went with separate tests as the ClusterClass changes test can be used with arbitrary control plane and bootstrap providers while the rollout test specifically tests behavior of KCP (in-place propagation).
>
> As in-place propagation is not part of our contract and not even all control plane providers have a machineTemplate I thought it to be cleaner / easier to understand if we have a clean separation. So that one test is testing basic ClusterClass "actions" while the other one is testing the entire in-place propagation specifically for KCP etc.
> 
> I think there is probably a way to add some flags etc so we can have both in one test. I'm just not sure if this makes the test to complicated. Right now both tests seem nicely focused on their task, although there is definitely overlap.

xref: https://github.com/kubernetes-sigs/cluster-api/pull/8171#discussion_r1131076350

/kind cleanup
/area testing

**Comment by fabriziopandini** [comment]
/triage accepted
/help

Not a high priority, but let's consider making the KCP/providers part pluggable so we can merge the two tests and keep our test machinery as lean as possible.
