### ISSUE TITLE
Add e2e test to cover basic autoscaler scenarios

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8282]
### What would you like to be added (User Story)?

As a user it would be great if Cluster API would have coverage for basic autoscaler scenarios to ensure those work 

### Detailed Description

We would propose the following:
* Add a new e2e test (that should be usable with various infra providers)
* The e2e test should create a workload cluster with ClusterClass and deploy autoscaler on the workload cluster
* And then test the following scenarios:
  * Create a MD with 2 replicas where autoscaler manages replicas from Day 1 (test scale up / down)
    * Note: This will cover that the defaulting webhook picks the replica count based on annotations so the autoscaler can act.
  * Take back control of the MD by removing the autoscaler annotations
    * Note: We might want to check that after taking back control the topology controller can scale up/down without the autoscaler fighting back.
  * Create a MD with 2 replicas without autoscaler annotations and then hand over control to the autoscaler by setting the annotations (Day 2)
    * Note: We should validate that while we set the annotations and unset the replica field the replica field is not reset to 1.

### Label(s) to be applied

/kind feature
/area testing
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
cc @ykakarap @fabriziopandini @jackfrancis @enxebre @elmiko

**Comment by elmiko** [comment]
this is great to see, i have a feeling that @fabriziopandini 's work on https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/pull/69 is going to pay off for this

**Comment by fabriziopandini** [comment]
@elmiko yes, the kubeamark work is the foundation of https://github.com/kubernetes-sigs/cluster-api/pull/8262

**Comment by enxebre** [comment]
I'd expect us to cover MachinePool as well when as this gets merged https://github.com/kubernetes/autoscaler/pull/4676 cc @mboersma

**Comment by sbueringer** [comment]
> I'd expect us to cover MachinePool as well when as this gets merged [kubernetes/autoscaler#4676](https://github.com/kubernetes/autoscaler/pull/4676) cc @mboersma

Makes sense but I would like to get the current iteration merged first and we can extend the test to cover MachinePools in a follow up issue/PR

**Comment by fabriziopandini** [comment]
+1 to have a first version of this test to merge ASAP, and then add MP in a follow up
