### ISSUE TITLE
CRS controller should wait for Cluster DNS Service  ready before reconciling CRS objects

### ISSUE THREAD

**Issue by Levi080513** [kubernetes-sigs/cluster-api#8285]
### What steps did you take and what happened?

Cluster DNS Service is an important service for Kubernetes Cluster and it use static ip to create service.
If apply ClusterResourceSet before creating Cluster DNS Service, Cluster DNS Service may be create failed by service IP conflict before Kubernetes version v1.25, and it will make Kubernetes Cluster does't work.

similar issue https://github.com/kubernetes-sigs/cluster-api/issues/7804

some errors about this issue when using CAPI and CRS to create Kubernetes Cluster.
```
[kubelet-finalize] Updating "/etc/kubernetes/kubelet.conf" to point to a rotatable kubelet client certificate and key
error execution phase addon/coredns: unable to create/update the DNS service: Service "kube-dns" is invalid: spec.clusterIPs: Invalid value: []string{"10.96.0.10"}: failed to allocate IP 10.96.0.10: provided IP is already allocated
To see the stack trace of this error execute with --v=5 or higher
```

### What did you expect to happen?

Kubernetes cluster should work fine and Cluster DNS Service  should  created succeed.

### Cluster API version

v1.2.7

### Kubernetes version

v1.24.8

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by killianmuldoon** [comment]
Thanks for opening this @Levi080513 - I think this one is worth thinking about in order to make CRS more stable and useful for users.

/triage accepted

**Comment by fabriziopandini** [comment]
Reporting here a comment from https://github.com/kubernetes-sigs/cluster-api/pull/8048

> AFAIK "kube-dns" is the name used by kubeadm, probably by some other setup scripts, but it is not an official convention/standard defined somewhere.
> If this is true, we can't hard code this assumption unless we find a way to make this generic

**Comment by Levi080513** [comment]
Yes, if there is an official specification and definition for this service, then we can try to solve this problem.

**Comment by fabriziopandini** [comment]
I'm leaning toward closing this, because the discussion about an official specification around the DNS service name should probably happen in Kubernetes, not here. We can then eventually re-open/open a new issue here once this discussion is addressed
Opinions?

**Comment by Levi080513** [comment]
Agree. 

/close
