### ISSUE TITLE
Error encountered when using CAPD on btrfs: `Error response from daemon: Duplicate mount point: /dev/mapper`

### ISSUE THREAD

**Issue by cannonpalms** [kubernetes-sigs/cluster-api#8317]
### What steps did you take and what happened?

I'm having difficulties running CAPD/the Tilt local development environment. When I deploy a workload cluster, the `DockerCluster` controller immediately errors with the following message:
```
failed to create load balancer: error creating container \"capi-quickstart-lb\": Error response from daemon: Duplicate mount point: /dev/mapper
```
I first reported this issue in a [Slack thread](https://kubernetes.slack.com/archives/C8TSNPY4T/p1679078614167009) where @killianmuldoon kindly helped to identify that the problem is reproducible with the `btrfs` docker storage driver but not with the `overlay2` docker storage driver.

This suggests to me that the issue is unlikely to be within CAPD itself, but more likely a lower layer like kind or docker. However, this can serve as a helpful tracking issue for the issue that bubbles to the surface when attempting to use CAPD.

### What did you expect to happen?

Expected a workload cluster named `capi-quickstart-cluster` to be created.

### Cluster API version

`v1.3.5`

### Kubernetes version

1.26

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by fabriziopandini** [comment]
/triage accepted

I have recently aligned the flags used to create containers between kind and CAPD (https://github.com/kubernetes-sigs/cluster-api/pull/8157), and this included also a change for btrfs
@cannonpalms could you check with latest rc release?

**Comment by cannonpalms** [comment]
Hi @fabriziopandini, the same issue occurs on `v1.4.0-rc.1`. ISTM (and I am rather naive) that both CAPD AND kind are adding the `/dev/mapper` bind/mount point now. Perhaps CAPD can remove its workaround for btrfs support and defer to kind?

I will test a build that does this and report back.

**Comment by cannonpalms** [comment]
Simply removing CAPD's explicit bind/mount worked just fine... Please see the linked PR and tell me where I'm going wrong in my thinking here. I don't think we need to bind/mount anymore now that kind does it for us.

**Comment by fabriziopandini** [comment]
commented on the PR

**Comment by ipetrov117** [comment]
Hit the same issue when deploying a product using CAPD on an OS with the BTRFS filesystem.  From the information here and in the PR I figure that just removing the second bind/mount in the code is enough. Is that the case?

**Comment by killianmuldoon** [comment]
> From the information here and in the PR I figure that just removing the second bind/mount in the code is enough. Is that the case?

As far as I found in my local testing that fixed the issue. If @cannonpalms is happy with it, it would be good if you could pick up the PR.
