### ISSUE TITLE
Graceful node shutdown configuration

### ISSUE THREAD

**Issue by fiunchinho** [kubernetes-sigs/cluster-api#8348]
### What would you like to be added (User Story)?

As a developer I'd like to be able to configure [the graceful node shutdown options](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/) that are available in the kubelet, so that worker nodes are drained before being terminated.

### Detailed Description

These options are not available as kubelet args, so they can't be configured using the `kubeletExtraArgs` field. They can only be configured from the config file.

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by fabriziopandini** [comment]
/triage accepted
This is a revival of https://github.com/kubernetes-sigs/cluster-api/issues/4464 (and also related to https://github.com/kubernetes-sigs/cluster-api/issues/3700), and it brings up again the question of what we should do with component config considered that this work is stalled in Kubernetes and there is no clear way forward

**Comment by killianmuldoon** [comment]
AFAIU users can provide a file through cloud-init to configure the kubelet via kubeletconfiguration. kubeadm also has the option to patch kubeletconfiguration. There's definitely routes to enabling this today in a CAPI/KCP/CAPBK cluster, but the user interface isn't exactly the nicest.

**Comment by fabriziopandini** [comment]
We should probably start documenting available options as a stop gap

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

We documented in https://cluster-api.sigs.k8s.io/tasks/bootstrap/kubeadm-bootstrap/kubelet-config available options to configure kubelet.

/close
