### ISSUE TITLE
`bootstrap-cluster-cleanup` is not taking effect

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#839]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Even if I set `bootstrap-cluster-cleanup` as false, the bootstrap cluster was still deleted.

**What did you expect to happen:**

Bootstrap cluster should not be deleted if `bootstrap-cluster-cleanup` set as false.

/assign

FYI @xunpan @jichenjc @morvencao @clyang82

**Comment by gyliu513** [comment]
/uncc @gyliu513 
/cc @xunpan 

@xunpan Can you help check this as well? I recalled that you also encounter this issue before.

**Comment by timothysc** [comment]
closing, we heading into a heavy refactor for v1alpha3 regarding CLI UX.
