### ISSUE TITLE
Drop `disableInPlacePropagation` from KCP reconciler and migrate the affected tests to envtest.

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#8393]
**Detailed Description**:

The `KubeadmControlPlaneReconciler` has a additional `disableInPlacePropagation` which is sued to disable some of the parts of the controller that depend on SSA during tests. This flag is only used during testing and does not affect the controllers behavior in anyway.

This issue to track the work to drop the this flag from the controller and migrate all the affected tests. 

**Additional Information:**

Once the flag is dropped the tests will fail because they use fakeClient which does not support Server-Side-Apply. All of the affected tests should be migrated to using envtest (supports SSA).

/area testing

**Comment by fabriziopandini** [comment]
Note: we are talking about migration of tests to env tests (which uses a real API server, and this fully support SSA)

/triage accepted
/help
