### ISSUE TITLE
Replace `HelperOptions` with `ssa.FilterObjectInput`

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#8395]
**Detailed Description**:

With the introduction of [`ssa.FilterObjectInput`](https://github.com/ykakarap/cluster-api/blob/197e7f90b2d8f25ffbd0b428e7c5197f3364c93c/internal/util/ssa/filterintent.go#L26) in https://github.com/kubernetes-sigs/cluster-api/pull/8060 [`HelperOptions`](https://github.com/ykakarap/cluster-api/blob/197e7f90b2d8f25ffbd0b428e7c5197f3364c93c/internal/controllers/topology/cluster/structuredmerge/options.go#L72) becomes redundant. 

This issue is to drop `HelperOptions` and replace all of it uses with `ssa.FilterObjectInput`.

/kind cleanup

**Comment by cahillsf** [comment]
👋 I can grab this one.  Looks like `HelperOptions` has a utility function ([`newHelperOptions`](https://github.com/kubernetes-sigs/cluster-api/blob/4f60841913fa99912771c3906ee81dd13d4e9633/internal/controllers/topology/cluster/structuredmerge/options.go#L88-L99)) that is being used in one place ([serversidepathhelper.go](https://github.com/kubernetes-sigs/cluster-api/blob/4f60841913fa99912771c3906ee81dd13d4e9633/internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go#L44
)).  Should this PR also include a similar utility function for [`FilterObjectInput`](https://github.com/ykakarap/cluster-api/blob/197e7f90b2d8f25ffbd0b428e7c5197f3364c93c/internal/util/ssa/filterintent.go#L26)?

/assign @cahillsf

**Comment by Dhairya-Arora01** [comment]
Hey @ykakarap how should we change this https://github.com/ykakarap/cluster-api/blob/197e7f90b2d8f25ffbd0b428e7c5197f3364c93c/internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go#L44

**Comment by Dhairya-Arora01** [comment]
@musaprg you can work on this if you have figured it out

**Comment by musaprg** [comment]
OK, thank you! I'll take this and prepare an initial PR for it. Let us discuss the implementation details there. 
/assign @musaprg
