### ISSUE TITLE
Rename `internal/util/ssa` util functions for better naming consistency 

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#8396]
**Detailed Description:**

Rename the following functions in the `ssa` package to have consistent naming scheme:
- IsAllowedPath -> IsPathAllowed ([Ref](https://github.com/kubernetes-sigs/cluster-api/pull/8060#discussion_r1119200006))
- IsIgnorePath -> IsPathIgnored ([Ref](https://github.com/kubernetes-sigs/cluster-api/pull/8060#discussion_r1119201340))
- IsNotAllowed -> IsPathNotAllowed ([Ref](https://github.com/kubernetes-sigs/cluster-api/pull/8060#discussion_r1119200893))

All the above functions are in `internal/util/ssa` package. 

The comments on these functions should also be corrected. Example:
For  `IsAllowedPath` the comment should be changed to `// IsAllowedPath returns a functions that returns true when the Path is one of the AllowedPaths.` (similarly for the other functions).

**Additional Information:**
We need to have an explicit `IsPathNotAllowed` and cannot simple use the negation of `IsPathAllowed` and ask used to use `!IsPathAllowed()` as both the functions return a filter function and there is no simple way to get to negation of the returned function. 

/kind cleanup
/help

**Comment by cahillsf** [comment]
hey @ykakarap 👋 I'd like to pick this one up

**Comment by killianmuldoon** [comment]
/assign @cahillsf 

Thanks!
(I think you should be able to assign yourself with a command like the above)
