### ISSUE TITLE
Automation for upgrading Kubernetes version

### ISSUE THREAD

**Issue by hiromu-a5a** [kubernetes-sigs/cluster-api#8407]
### What would you like to be added (User Story)?

As an operator I'd like to simplify upgrading Kubernetes version for reduce the operation cost.

### Detailed Description

In general, upgrading k8s version consists of four steps [1]. 

1. Creating a new image for the target k8s version with image-builder.
2. Register the new image to a repository (automated by image-builder in some platforms)
3. Create a new MachineTemplate that refers to the new image
4. Update KubeadmControlPlane (if kubeadm is used) and/or MachineDeployment to refer to the new MachineTemplate

I'd like to automate steps 1-3 so that operators can switch the k8s versions just by changing MachineTemplate, like choosing a template from catalogs.

A straightforward way to realize this is to create shell scripts to automate steps 1- 3 and run them as cron jobs for example. My suggestion is to add such scripts to `/hack` directory of the CAPI repository since this task is common for most users.

[1] https://cluster-api.sigs.k8s.io/tasks/upgrading-clusters.html

### Anything else you would like to add?

- For some platforms, the image builder register created images automatically (e.g., AWS). Therefore, step 2 can be merged into step 1.
- If images are hosted by CAPI, upgrading is much easier (I think it's not realistic though). In this case, CAPI can use the shell scripts to create images.

### Label(s) to be applied

/kind feature
/kind area/upgrades

**Comment by killianmuldoon** [comment]
@hiromu-a5a  - have you investigated using a ClusterClass to upgrade? It turns steps 3 & 4 into a single line change in the Cluster object.

**Comment by hiromu-a5a** [comment]
Thank you for informing that.

> Given that I'm not sure we can/we should manage such a script in CAPI; might be a different logistic should be considered e.g. a core script hosted in the image builder project and a provider-specific script built on top of this hosted in each provider repo.

I understand. I'm considering suggesting this to the image-builder as well, but I think this can be a CAPI matter for the following reasons.

- In CAPD, the version field controls the actual Kubernetes version, thus upgrading is a CAPI task
- The required functions are maintained by image-builder, CAPI can just use them. 
- This is not a core feature, a helper script, we don't have to worry too much about its maintenance (I don't know how image-builder tests it though)
- User can use their own base MachineTemplate to "Create a new MachineTemplate" since this step is just to create copies of the base MachineTemplate with different image references

For the second point, maybe I just don't know how CAPI is struggling to maintain such dependencies, but my basic motivation is that the first point, it's a CAPI task. Kubernetes version is common attributes among providers, not provider specific which has to be abstracted by CAPI somehow.

> have you investigated using a ClusterClass to upgrade? It turns steps 3 & 4 into a single line change in the Cluster object.

Yes. However, I think ClusterClass simplifies steps 3 & 4 only for CAPD. Is that correct? 
In the other providers, we have to make a new machine template for a new image as the version field doesn't control the actual Kubernetes version. Also, the painful point are steps 1 & 2 and, moreover, binding created images to actual machine templates (i.e., not 3 & 4).
