### ISSUE TITLE
Prevent k8s version skew policy violations

### ISSUE THREAD

**Issue by hiromu-a5a** [kubernetes-sigs/cluster-api#8408]
### What would you like to be added (User Story)?

As an operator I'd like to validate the Kubernetes version skew policy when I run `clusterctl alpha rollout undo`.

### Detailed Description

The existing clusterclt rollout undo command might violate the [version skew policy](https://kubernetes.io/releases/version-skew-policy/) easily and accidentally. For example, if a user has MachineSet (revision=1, k8s version=1.22) and MachineSet (revision=4, k8s version=1.25) and mistakenly triggers rollback from revision 4 to 1, there's no way to stop it. I'd like to suggest that clusterctl raises an error if users break the version skew policy and allow the operation only if a user sets --force option. 

### Anything else you would like to add?

Possible Concerns and Solutions:
- This feature changes the default behavior of `rollout` and makes negative impact on the existing end users.
  - -> violation of version skew policy is a more serious problem. As an alternative, we can skip validation when the `version` field is empty.
- Isn't interactive-mode better than `--force` option?
  - -> users who run this command from scripts definitely need `--force` options rather than interactive-mode.
- Which control plane providers are supported?
  - -> KubeadmControlPlane, but is extensible.

Related issue: #3439 

### Label(s) to be applied

/kind feature
/area clusterctl

**Comment by fabriziopandini** [comment]
Let's keep this on hold until the discussion on https://github.com/kubernetes-sigs/cluster-api/issues/10479 is sorted out

**Comment by fabriziopandini** [comment]
Community agreed on deprecation for revision management, so also clusterctl alpha rollout undo is going away
/close
