### ISSUE TITLE
Can patchHelper provide an option to verify resourceVersion?

### ISSUE THREAD

**Issue by huaqing1994** [kubernetes-sigs/cluster-api#8412]
As a developer, I use the [patchHelper](https://github.com/kubernetes-sigs/cluster-api/blob/main/util/patch/patch.go) in our controllers to patch our CR at the end of the `reconcile()`, like CAPI does.

We found a small problem that patchHelper uses `client.MergeFrom()` in `Helper.patch()` and `Helper.patchStatus()`, causing apiserver not to verify resourceVersion when patching.
Sometimes, the controller may reconcile old data (because the controller's cache is not updated in time), and the fields(like some timestamp or random ID) written by the last `reconcile()` will be overwritten by this `reconcile()`.

We want to avoid overwriting fields due to reconciling old data, and we don't need different controllers to act on conditions of the same object.
Can patchHelper provide an option to verify resourceVersion? Prevent patching when resourceVersion validation fails.

**Comment by fabriziopandini** [comment]
/triage needs-information

I'm a little bit concerned about adding options that we are not using in CAPI for a couple of practical reasons, but I would like also to better understand the use cases because at first sight, this seems a symptom of the controller relying on something set in previous reconcile, which is generally a bad practice

**Comment by huaqing1994** [comment]
@fabriziopandini I understand your concerns.

Another specific case we have is:
CR waits for the execution of an asynchronous task. The task ID is recorded in status.taskID. Every reconcile() will check whether the task is completed, and delete the status.taskID if it is completed.
Sometimes, after task A is executed, task B will be executed immediately.
After the task ID of task B is recorded in status.taskID, the next reconcile() may also get the task ID of task A in status.taskID. Since task A has completed, the status.taskID will be deleted.
But in fact, the deleted task ID belongs to task B, causing task B to be lost.

So it would be nice if CAPI patcher could verify resourceVersion.

**Comment by jessehu** [comment]
hi @fabriziopandini could we add the option MergeFromWithOptimisticLock to CAPI patch helper?

**Comment by fabriziopandini** [comment]
Does the solution suggest by @vincepri works? this will allow you to address the use case without CAPI implementing an option we don't use - we will struggle to prevent regression on -.

But I'm also open to other options if there is consensus on how to address ^^ (or this if is not perceived as a concern).

**Comment by fabriziopandini** [comment]
Just saw https://github.com/kubernetes-sigs/cluster-api/issues/8706, which is somehow related

**Comment by jessehu** [comment]
https://github.com/kubernetes-sigs/cluster-api/issues/8706 is exactly we meant. We hit bugs in the described scenario when using CAPI patchHelper.
