### ISSUE TITLE
CAPI 1.4.0: SSA patch fails when trying to apply labels to node with duplicate fields

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api#8417]
### What steps did you take and what happened?

1. Upgrade provider to use CAPI 1.4.0
    - CAPZ Upgrade PR: (https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3298)
3. Try to provision a cluster with duplicate fields. 
    - In CAPZ, we are running into this issue with our ipv6 E2E test spec, which is dual-stack by nature. It has two `InternalIP` fields.
    - node describe: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3298/pull-cluster-api-provider-azure-e2e/1640784837444898816/artifacts/clusters/capz-e2e-2qjl7w-ipv6/nodes/capz-e2e-2qjl7w-ipv6-md-0-hvxxl/node-describe.txt
4. Observe failure with ReplicaSet failing to progress
    - build-log: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3298/pull-cluster-api-provider-azure-e2e/1640867382496858112
    - Error from CAPI `manager.log`: ```E0328 19:00:47.753464       1 controller.go:329] "Reconciler error" err="failed to apply labels to Node: failed to apply Node capz-e2e-2qjl7w-ipv6-md-0-hvxxl: failed to create manager for existing fields: failed to convert new object (/capz-e2e-2qjl7w-ipv6-md-0-hvxxl; /v1, Kind=Node) to smd typed: .status.addresses: duplicate entries for key [type=\"InternalIP\"]" controller="machine" controllerGroup="[cluster.x-k8s.io](http://cluster.x-k8s.io/)" controllerKind="Machine" Machine="capz-e2e-2qjl7w/capz-e2e-2qjl7w-ipv6-md-0-77789d59d5xn9qcz-fd7pf" namespace="capz-e2e-2qjl7w" name="capz-e2e-2qjl7w-ipv6-md-0-77789d59d5xn9qcz-fd7pf" reconcileID=37f289a0-078a-4a5d-828f-6b7f5981c599```

### What did you expect to happen?

SSA should not fail to patch node labels due to a duplicate field. This will affect any dual-stack clusters or other configurations that contain duplicate fields. 

### Cluster API version

v1.4.0

### Kubernetes version

v1.24.6

### Anything else you would like to add?

Our current theory is that SSA needs to calculate field ownership to apply the patch for labels, but the merge key is not sufficienty unique, which can cause data corruption when it is merged. The issue was seen previously in https://github.com/kubernetes/kubernetes/pull/79391

cc @ykakarap @CecileRobertMichon. Thanks for all of your investigation on this issue so far!

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by ykakarap** [comment]
Adding some context:

> Observe failure with ReplicaSet failing to progress

This is because the the machine controller is failing to sync labels to the nodes and therefore the `node.cluster.x-k8s.io/uninitialized` is never dropped from the worker nodes. Since the taint is not dropped the pods of the replica set have no nodes they can run on.

> SSA patch fails

As mentioned the node get 2 IP addresses and both of them are listed under the `node.status.addresses`. This list has a `pathMergeKey=type` (and `patchStrategy=merge`) and the `type` of both the IP entries is the same: `InternalIP`. This apparently is causing a problem with the API server when trying to apply an SSA patch.

Example from the test log (node describe):
```
Addresses:
  Hostname:    capz-e2e-2qjl7w-ipv6-md-0-hvxxl
  InternalIP:  2001:1234:5678:9abd::4
  InternalIP:  10.1.0.4
```

The relevant corev1 Node API: https://github.com/kubernetes/kubernetes/blob/fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b/staging/src/k8s.io/api/core/v1/types.go#L5210-L5212

Related item in k/k: https://github.com/kubernetes/kubernetes/pull/79391

**Comment by CecileRobertMichon** [comment]
@ykakarap in the Slack thread you said

> I think it might be because during SSA patch the api server has to calculate the field ownership to figure out how to apply the patch and this step of calculating the field ownership is probably failing because it does now know how to do that for  .status.address  when it has 2 IPs.
Need to check this theory

were you able to check if that's true? if so, can you please point me to the code?

**Comment by ykakarap** [comment]
I am verifying this and I will post here once I have more.

**Comment by CecileRobertMichon** [comment]
Confirmed the same error happens with a dual-stack cluster:

```
I0329 18:40:44.326637       1 machine_controller_noderef.go:59] "Waiting for infrastructure provider to report spec.providerID" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" Machine="capz-e2e-zloir7/capz-e2e-zloir7-dual-stack-control-plane-ppswz" namespace="capz-e2e-zloir7" name="capz-e2e-zloir7-dual-stack-control-plane-ppswz" reconcileID=0e948b57-47b3-4a17-8863-7c735ff6ecd8 KubeadmControlPlane="capz-e2e-zloir7/capz-e2e-zloir7-dual-stack-control-plane" Cluster="capz-e2e-zloir7/capz-e2e-zloir7-dual-stack" AzureMachine="capz-e2e-zloir7/capz-e2e-zloir7-dual-stack-control-plane-7thv7"
E0329 18:40:48.430615       1 controller.go:329] "Reconciler error" err="failed to apply labels to Node: failed to apply Node capz-e2e-zloir7-dual-stack-control-plane-nftfs: failed to create manager for existing fields: failed to convert new object (/capz-e2e-zloir7-dual-stack-control-plane-nftfs; /v1, Kind=Node) to smd typed: .status.addresses: duplicate entries for key [type=\"InternalIP\"]" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" Machine="capz-e2e-zloir7/capz-e2e-zloir7-dual-stack-control-plane-6jbxl" namespace="capz-e2e-zloir7" name="capz-e2e-zloir7-dual-stack-control-plane-6jbxl" reconcileID=6d4c1acb-22f3-4947-a10f-91ed8b578806
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3298/pull-cluster-api-provider-azure-e2e-optional/1641144243672059904/artifacts/clusters/bootstrap/logs/capi-system/capi-controller-manager/capi-controller-manager-8557cdcd6-z2dmx/manager.log

**Comment by ykakarap** [comment]
Ran some tests locally and confirmed that SSA does not work on Node irrespective of what the SSA patch the trying to modify (Example: patching labels, annotations, etc) as long we have "conflicting keys" on a node.

**Comment by ykakarap** [comment]
Looks like it is known that SSA does not work on Node objects.

Ref: https://github.com/kubernetes/kubernetes/issues/101029#issuecomment-819211711
> It just prevents server-side apply from tracking who owns which fields, which may prevent people from server-side applying this object. Since node is rarely applied AFAIK, this should be fairly consequence-free.

Ref: https://github.com/kubernetes/kubernetes/issues/101029#issuecomment-819212219
> The "not sufficiently unique" throws SSA off and prevents it from doing its job.

**Comment by nikhita** [comment]
> confirmed that SSA does not work on Node irrespective of what the SSA patch the trying to modify (Example: patching labels, annotations, etc) as long we have "conflicting keys" on a node.

The fix for this would be to add a custom implementation of `PatchNodeStatus` as in https://github.com/kubernetes/kubernetes/pull/90561/files#diff-c05a8ef3cf2e70bd9772568c1c984691f956b1c1c24872be34f929a8aff245eeR39 and use this implementation to patch nodes in all cases.
