### ISSUE TITLE
Docs: Configuring Kubelet in Cluster API

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#8425]
### What would you like to be added (User Story)?

As a user I would like to understand how to configure Kubelet when deployed in a Cluster API cluster using KCP and CAPBK.

### Detailed Description

Currently there's a few different approaches:
1) Write a Kubelet conf using CloudInit files
2) Add Kubelet extraArgs in the KubeadmConfigTemplate
3) Patch kubeletconfiguration using a Kubeadm patch defined in the KubeadmConfigTemplate

The documentation should layout basic examples of each approach, and detail the limitations of each.

### Label(s) to be applied

/kind feature
/kind documentation

**Comment by musaprg** [comment]
I'd like to work on this. Let me try to prepare a PR for it.

/assign
/lifecycle active

**Comment by killianmuldoon** [comment]
@musaprg  - awesome, looking forward to seeing what you come up with!

**Comment by musaprg** [comment]
I'm considering where I should put the document. I think putting it under https://cluster-api.sigs.k8s.io/tasks/bootstrap/kubeadm-bootstrap.html would be best.

**Comment by killianmuldoon** [comment]
That makes sense to me.

**Comment by guettli** [comment]
Please consider this use case: I you want to set [system-reserved](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/) during the execution of `preKubeadmCommands`.

The script detects the amount of mem and cpu, and then sets the value accordingly.
