### ISSUE TITLE
Bump Kustomize to v5

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#8457]
Kustomize released v5.0.0 in February - CAPI should bump the Kustomize version to keep up. [Release notes are here](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.0.0).

The following need to be taken care of ahead of and / or alongside the Kustomize bump:

1. Ensure encoding of `creationTimestamp` is handled correctly. This should be handled in upstream Kustomize - [issue here](https://github.com/kubernetes-sigs/kustomize/issues/5031) - but if not there are workarounds for CAPI  - e.g. patch `creationTimestamp` on each and every CRD. [Reference issue in CAPI](https://github.com/kubernetes-sigs/cluster-api/issues/8413).
2. Take care of deprecations: The following have been deprecated:
* vars  -> replacements
* bases -> resources
* patchesStrategicMerge -> patches
* patchesJson6902 -> patches

/area dependency

**Comment by fabriziopandini** [comment]
Let's consider if to wait for a patch release with the fix for creationTimestamp
/triage accepted
/help

**Comment by killianmuldoon** [comment]
>Let's consider if to wait for a patch release with the fix for creationTimestamp

Yeah - I'm watching that issue to see if there's an update. We should consider it a blocker until then IMO.

**Comment by james-callahan** [comment]
> Yeah - I'm watching that issue to see if there's an update. We should consider it a blocker until then IMO.

Should still be able to work through the deprecations in the mean-time.

**Comment by sbueringer** [comment]
I've opened a related issue to bump controller-tools: https://github.com/kubernetes-sigs/cluster-api/issues/8546

Regarding kustomize:
* Is the current kustomize version we're using introducing creationTimestamp: null (or are they coming from what controller-gen generates?)
* Or is this only happening with the new kustomize version?

Basically I wonder what the exact consequences for CAPI are if we bump kustomize based on how we use kustomize in CAPI.

**Comment by sbueringer** [comment]
Done in #10294

/close

@killianmuldoon Maybe you can double check. But as far as I can telle verything is done (and we now use kustomize v5.3)
