### ISSUE TITLE
TestPatch is flaky

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#8478]
### Which jobs are flaking?

Unit test runs on 1.4 and main.

### Which tests are flaking?

sigs.k8s.io/cluster-api/internal/util/ssa.TestPatch

### Since when has it been flaking?

This test has been flaking since it was introduced.

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-release-1-4/1640193879221211136

### Reason for failure (if possible)

I did a little bit of debugging on this one and found that sometimes the resourceVersion of the object being patched (but only for the MachineTests in my reproduction) is bumped along with the time signature in the managed fields, but there is no other change on the object.

This results in the ssa call not being cached, as it checks the resourceVersion, unexpectedly.

### Label(s) to be applied

/kind flake
/area testing

**Comment by chrischdi** [comment]
[k8s-triage search query](https://storage.googleapis.com/k8s-triage/index.html?text=Test_patch_with_Machine&job=.*-cluster-api-.*&xjob=.*-provider-.*)

**Comment by chrischdi** [comment]
Example:

```
```

[Permalink](https://storage.googleapis.com/k8s-triage/index.html?text=subtest%20may%20have%20called%20FailNow%20on%20a%20parent%20test&job=.*-cluster-api-.*&xjob=.*-provider-.*) to check occurence.

Reproducible (not 100%) locally using:
```sh
go test -race -count 120 -failfast -shuffle on -timeout 30s -run '^TestPatch$' sigs.k8s.io/cluster-api/internal/util/ssa
```

**Comment by chrischdi** [comment]
First analysis:

https://github.com/kubernetes-sigs/cluster-api/blob/235d965810ba2a29aec88ec5d34291e82e6f8891/internal/util/ssa/patch.go#L104

seems to patch the object.
The only changes I was able to see was the bump of the `.metadata.resourceVersion` and timestamp inside the managed fields.

**Comment by chrischdi** [comment]
Maybe related: https://github.com/kubernetes/kubernetes/issues/118519
