### ISSUE TITLE
Document gitops deployment for Cluster API

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#8479]
There's been a number of requests in the community lately about information for gitops deployment of Cluster API - for both the management cluster and workload clusters. We currently don't have info in the book about this, but it would be useful to provide at least a basic set-up guide so people know how to generate manifests and get up and running with Cluster API in gitops.

There's a couple of resources out there, but it would be great to get contributions from members of the community who have experience setting up CAPI that way. 

/help
/kind documentation

**Comment by dtzar** [comment]
/assign

Discussion on the community call 4/5. 

I think the focus should be on the higher-level architecture for the E2E scenario including workload cluster hydration, but to not get into specifics of implementation details - only linking to outside sources.

One relevant area where I do think could use deeper guidance is how to run a production CAPI management control plane. This may not be a part of this article, but linked to it.

**Comment by killianmuldoon** [comment]
Thanks for taking this on @dtzar  - I think the important thing with these docs is to have a place to start and to be able to point interested people in the right direction. Once we have something like that in place I think the gaps, those we can reasonably fill in the CAPI book and those we can't, will become a bit clearer.
