### ISSUE TITLE
Enable IBM POWER/s390x support for cluster-api

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#852]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Some customer want to run cluster-api on IBM POWER, it is better to enable cluster-api can run on POWER as well, including both `clusterctl` and `cluster api manager`.

/cc @vincepri @detiber 

FYI @jichenjc @morvencao @clyang82 @xunpan 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jichenjc** [comment]
not sure what's the to do items here, and IBM s390x platform https://en.wikipedia.org/wiki/Linux_on_z_Systems will also fit for changes applicable to IBM POWER

**Comment by gyliu513** [comment]
@jichenjc I think there are two items for this project:
- Build and enable the cluster api controller can run on POWER and s390x
- Update document for how to build `clusterctl` on POWER and s390x

**Comment by jichenjc** [comment]
ok, this should be something we can contribute, thanks

**Comment by detiber** [comment]
I have no objections to supporting additional architectures as long as we can also have some level of automated testing on those architectures as well.

/milestone Next

**Comment by detiber** [comment]
Reopening since this does not address the merged PR does not address the client binaries.

**Comment by gyliu513** [comment]
@detiber do you mean the `clusterctl`?

**Comment by detiber** [comment]
Closing since this has landed and CI support is being tracked here: https://github.com/kubernetes-sigs/cluster-api/issues/893

/close
