### ISSUE TITLE
Add `--name-template` flag for `generate cluster` sub-command

### ISSUE THREAD

**Issue by rbjorklin** [kubernetes-sigs/cluster-api#8534]
### What would you like to be added (User Story)?

1. As an operator I would like to be able to exclude the cluster name from the name of all the generated resources. Given that all resources are namespaced the value of having the name also included in each resource name eludes me.

### Detailed Description

I would like to be able to call `clusterctl generate cluster --name-template '{{ .Name }}'` and have that exclude the cluster name from each individual resource. The current default could be considered to be of the form: `{{ .ClusterName }}-{{ .Name }}`

### Anything else you would like to add?

This idea is not new, helm has this feature. See helm/helm#1015

### Label(s) to be applied

/kind feature

**Comment by fabriziopandini** [comment]
Let's see if other users have a similar need, but IMO we should not compare clusterctl to full-fledged template engines, and thus also assume advanced template features should be considered out of scope.

The core scope of clusterctl is to provide a solution to manage the lifecycle of providers - which is a complex and very specific problem - while managing templates is a facility we provided to get users started, but we are well aware that the majority of users rely on other tools existing in the ecosystem which are great in managing yaml, like helm, kapp or git-ops tools.

Also, clusterctl already supports pluggable template engines, so if someone wants more advanced templating features he can do using clusterctl as a library and providing a type that implements this [interface](https://github.com/kubernetes-sigs/cluster-api/blob/f71a5432af649b0a483bc694fb3b9912145141e9/cmd/clusterctl/client/yamlprocessor/processor.go#L22).

Last but not least, I would prefer to not add more complexity to our yaml processor before we define a path forward for https://github.com/kubernetes-sigs/cluster-api/issues/8325

**Comment by rbjorklin** [comment]
> assume advanced template features should be considered out of scope.

Fair enough.
