### ISSUE TITLE
Delete kind/clusterctl label

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8545]
### What would you like to be added (User Story)?

Just saw that we have a kind/clusterctl label. I would propose to move the 10 issues we have with that label to area/clusterctl and then delete the label.

Notes:
* This has to be done by someone with write access to the repo
* kind/clusterctl is not managed via test-infra (so we don't have to remove it there)

### Detailed Description

-

### Label(s) to be applied

/kind cleanup
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
cc @killianmuldoon

**Comment by killianmuldoon** [comment]
/close 

@sbueringer as discussed let's do a bulk cleanup of the labels we're using for CAPI.
