### ISSUE TITLE
Cluster API periodic test jobs are getting stuck in pending

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8560]
### What steps did you take and what happened?

From time to time some of our periodic test jobs are getting stuck in pending. I.e. a run of the test job is shown as Pending and no new runs are scheduled.

Example:
![image](https://user-images.githubusercontent.com/4662360/234041687-1eb6d724-a528-4517-9d05-6a658757a8f0.png)
(URL: https://prow.k8s.io/?repo=kubernetes-sigs%2Fcluster-api&job=periodic*&state=pending)

In this exampe [periodic-cluster-api-e2e-main](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1649961183047847936) is stuck in pending.

### What did you expect to happen?

Jobs should be just scheduled continuously and not get stuck in pending and block further runs.

### Cluster API version

main (probably also on other branches)

### Anything else you would like to add?

Notes:
* This could be a Prow issue, but it might also be of something specific to our jobs

Mitigation:
* One of the CAPI maintainers has to cancel the job currently stuck in pending and then restart it (I would recommend with latest configuration)
* I think the CI team has to be aware of this when they check testgrid and notify a maintainer if a job is stuck.

Impact:
* The stuck periodic is not run anymore and thus doesn't produce any new test data

Debug ideas:
1. Wait until another Job is stuck in pending
2. Figure out why exactly it is shown as pending (the job in the Prow UI itself looks like it's completed)
3. It might be necessary to look into the responsible Prow component and figure out why no new jobs are started (but might be the same as 2.)

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
/area testing

**Comment by sbueringer** [comment]
cc @kubernetes-sigs/cluster-api-release-team

**Comment by furkatgofurov7** [comment]
I played around a bit and found:

> main (probably also on other branches)

I see it in other release branches as well (1.2, 1.3 & 1.4)

> One of the CAPI maintainers has to cancel the job currently stuck in pending and then restart it (I would recommend with latest configuration)

Actually, I do not think this is necessary, as long as you authorize yourself using your GH account with prow, anyone can cancel and re-run the job

> It might be necessary to look into the responsible Prow component and figure out why no new jobs are started (but might be the same as 2.)

Since we do not have a direct access to prow cluster I can't think of a way we could check prow components

**Comment by sbueringer** [comment]
@furkatgofurov7 were you testing rerun on PR jobs or periodics? I wasn't able to rerun periodics until we added the cluster-api-maintainers group to rerun authconfig in our prowjob config a few weeks back.

> Since we do not have a direct access to prow cluster I can't think of a way we could check prow components

I meant looking into the source code + the data we see under artifacts. Some components like the UI (deck) can also be run locally without access to the cluster

**Comment by sbueringer** [comment]
That's strange, this shouldn't  be possible (xref: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-1-2.yaml#L213-L216).

(btw on PRs however it's different. Not sure exactly but either the PR author, org members or everyone can restart there)

Independent of all of that. We can definitely also start with the following:
* wait until one of the less important jobs gets stuck (e.g. one of the v1.2 jobs)
* open an issue (referencing that job) in test-infra and/or ask for help in Kubernetes Slack

**Comment by chrischdi** [comment]
Two new ones stuck in Pending:
<img width="1490" alt="image" src="https://user-images.githubusercontent.com/417870/235603748-c41a1494-7263-4792-a071-169da1dfcd98.png">

Both are marked as failed in Spyglass:
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-release-1-4/1653042540242276352
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-release-1-4/1652564132941008896

Both show the following at the end:
```
ERROR: Found unexpected running containers:
CONTAINER ID   IMAGE                  COMMAND                  CREATED             STATUS             PORTS                                  NAMES
8e7a762bdd15   kindest/node:v1.26.3   "/usr/local/bin/entr…"   About an hour ago   Up About an hour   33937/tcp, 127.0.0.1:33937->6443/tcp   k8s-upgrade-and-conformance-77ry3o-xr5sp-r6lsq
+ EXIT_VALUE=1
+ set +o xtrace
Cleaning up after docker in docker.
================================================================================
Cleaning up after docker
Error response from daemon: Could not kill running container 8e7a762bdd154b7492a8effc6fa47e838ea343642ca61cc6dc8ce03ccd794f40, cannot remove - tried to kill container, but did not receive an exit event
Stopping Docker: dockerProgram process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.
================================================================================
Done cleaning up after docker in docker.
```

**Comment by chrischdi** [comment]
Note: I don't have the permissions to stop or restart them.

**Comment by sbueringer** [comment]
I wonder what happened when CAPD tried to remove this container (I assume it tried it)?

Do we know if we have the same error also in jobs which are then not stuck in pending?

Not sure if there is a way to force remove the container more than the job already tries.

**Comment by chrischdi** [comment]
I was not able to figure something out on both jobs from CAPD or other logs. For both occurrences, CAPD logged the dockermachine deletion as successful.

> Do we know if we have the same error also in jobs which are then not stuck in pending?

I did not find any via k8s-triage.

> Not sure if there is a way to force remove the container more than the job already tries.

According [this](https://github.com/kubernetes/test-infra/blob/09e2a135eaa137f1639a89711682028ba920ef61/images/bootstrap/runner.sh#L31), it is already a `docker rm -f`

> Maybe there's something in the logs of this container which explains why it's not shutting down.

We don't fetch them currently. Docker logs and containerd logs did not help in this case.
Even the container seems to go to `exitted` acording containerd logs.

**Comment by sbueringer** [comment]
> > Maybe there's something in the logs of this container which explains why it's not shutting down.

> We don't fetch them currently. Docker logs and containerd logs did not help in this case.
> Even the container seems to go to exitted acording containerd logs.

I meant the logs of the container of the wl cluster: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1653406428393639936/artifacts/clusters/quick-start-s3y53t/machines/ (that's the one which doesn't shutdown, right?)

**Comment by sbueringer** [comment]
Detecting that case in CAPD would make it possible to dump more data (like all the files we have in artifacts usually)

**Comment by chrischdi** [comment]
Another pending job at https://prow.k8s.io/?repo=kubernetes-sigs%2Fcluster-api&state=pending 

* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-release-1-4/1657414027363487744
* 
![image](https://github.com/kubernetes-sigs/cluster-api/assets/417870/579941c7-9b53-46e1-b4b3-f99c7982fef3)

**Comment by chrischdi** [comment]
<img width="1489" alt="image" src="https://github.com/kubernetes-sigs/cluster-api/assets/417870/407da2be-1c1d-4d8b-9589-ca5d75d6a2e2">

Two more pending. There is no `ps -ef` yet available on this ones, hopefully we gather more info next time!.

https://prow.k8s.io/?repo=kubernetes-sigs%2Fcluster-api&state=pending

**Comment by chrischdi** [comment]
Another new prowjob stuck in Pending, but with the latest change we get some more insights:
<img width="726" alt="image" src="https://github.com/kubernetes-sigs/cluster-api/assets/417870/986e5375-bc02-4085-b344-bf11c9dfdd64">

It looks like that a container got stuck in `runc init` and/or a docker-proxy command still running, which is also related to the same "stuck" container:

```
...
root      257499      23  0 May16 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 32809 -container-ip 172.18.0.10 -container-port 6443
root      257514       1  0 May16 ?        00:00:00 /usr/bin/containerd-shim-runc-v2 -namespace moby -id f2b3aaa5affd38f7c77f448adb728d36aa8c7a7800388dd38b987e94917930ea -address /var/run/docker/containerd/containerd.sock
root      257539  257514  0 May16 ?        00:00:00 [systemd]
root      275715  257539  0 May16 ?        00:00:00 runc init
...
```

[source](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1658602241772228608/artifacts/localhost/processes-ps-ef.txt)

Docker version information:
```
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:46:54 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:54 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

[source](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1658602241772228608/artifacts/localhost/docker-version.txt)

**Comment by sbueringer** [comment]
I'm not sure what we already have. Do you think it makes sense to run docker inspect + logs on all leftover containers at this point?

**Comment by chrischdi** [comment]
Two more pending friends:
<img width="802" alt="image" src="https://github.com/kubernetes-sigs/cluster-api/assets/417870/7280c566-222f-4ed0-a2de-b12dfe07e761">



> I'm not sure what we already have. Do you think it makes sense to run docker inspect + logs on all leftover containers at this point?
> 
> I wonder if that container is even in "shutting down"

Good question. Would be also good to maybe take a look at the pid's of the leftover ones. E.g. via `cat /proc/<pid>/status` ([xref](https://github.com/opencontainers/runc/issues/3759)) or check the freezer cgroup state https://github.com/opencontainers/runc/issues/3759#issuecomment-1504318216

**Comment by sbueringer** [comment]
Sounds good

**Comment by chrischdi** [comment]
cc @sbueringer : a new stuck in pending job, ready to get deleted :-)

Some analysis from the newest pending but finished job: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-dualstack-ipv6-main/1663826741237387264 :

Continuing on the new data and the stuck `runc init` from `ps -ef`:
```sh
root      113973   97202  0 09:01 ?        00:00:00 runc init
```

We got the following outputs for `/proc/113973/status` (from [here](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-dualstack-ipv6-main/1663826741237387264/artifacts/localhost/processes-proc-information.txt)):

```
Name:	runc:[2:INIT]
Umask:	0022
State:	D (disk sleep)
Tgid:	113973
Ngid:	0
Pid:	113973
PPid:	97202
TracerPid:	0
Uid:	0	0	0	0
Gid:	0	0	0	0
FDSize:	64
Groups:	0 
NStgid:	113973	1674	1
NSpid:	113973	1674	1
NSpgid:	113973	1674	1
NSsid:	113973	1674	1
VmPeak:	 1015784 kB
VmSize:	 1015784 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	    9992 kB
VmRSS:	    9992 kB
RssAnon:	    3044 kB
RssFile:	    6948 kB
RssShmem:	       0 kB
VmData:	   77820 kB
VmStk:	     132 kB
VmExe:	    4024 kB
VmLib:	    1700 kB
VmPTE:	     140 kB
VmSwap:	       0 kB
HugetlbPages:	       0 kB
CoreDumping:	0
THP_enabled:	1
Threads:	5
SigQ:	2/257203
SigPnd:	0000000000000100
ShdPnd:	0000000000000100
SigBlk:	0000000000000000
SigIgn:	0000000000000000
SigCgt:	fffffffdffc1feff
CapInh:	0000000000000000
CapPrm:	000001ffffffffff
CapEff:	000001ffffffffff
CapBnd:	000001ffffffffff
CapAmb:	0000000000000000
NoNewPrivs:	0
Seccomp:	0
Seccomp_filters:	0
Speculation_Store_Bypass:	thread vulnerable
SpeculationIndirectBranch:	conditional enabled
Cpus_allowed:	ff
Cpus_allowed_list:	0-7
Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	3
nonvoluntary_ctxt_switches:	215
```

and for `/proc/113973/stack`

```
[<0>] __refrigerator+0x4c/0x130
[<0>] get_signal+0x7a8/0x900
[<0>] arch_do_signal_or_restart+0xde/0x100
[<0>] exit_to_user_mode_loop+0xc4/0x160
[<0>] exit_to_user_mode_prepare+0xa0/0xb0
[<0>] syscall_exit_to_user_mode+0x27/0x50
[<0>] do_syscall_64+0x69/0xc0
[<0>] entry_SYSCALL_64_after_hwframe+0x61/0xcb
```

So we can see the reason for the process to not finish is, that it is in an uninterruptible `State:	D (disk sleep)`.

From issues researched at runc (e.g. https://github.com/opencontainers/runc/issues/3663, https://github.com/opencontainers/runc/issues/2753) there had been similar issues already in the past. And the source for the issue could also be in the kernel.

We could try to get more output via:

```
     # echo `w` to `/proc/sysrq-trigger` to dump tasks that are in uninterruptable (blocked)
     # stateinterruptible to dmesg and write dmesg to a file for debugging purposes.
     echo w > /proc/sysrq-trigger
     dmesg > ${ARTIFACTS_LOCAL}/dmesg.txt
```

But I don't know if that information would help us further, this is just some random google find which could help digging into it. (I would first have to learn then what that output means).

**Comment by sbueringer** [comment]
Maybe a good next step is to first move some jobs to the community cluster and then maybe we can do some debugging with @ameukam.

(when you're back from PTO)

**Comment by chrischdi** [comment]
Another job in pending, but failed since two days:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-release-1-4/1673084379238240256

**Comment by sbueringer** [comment]
> Another job in pending, but failed since two days:
> 
> https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-release-1-4/1673084379238240256

Thx. Restarted so we have test coverage for the release today

**Comment by chrischdi** [comment]
@sbueringer : another one pending since two days:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1677639594595586048

**Comment by sbueringer** [comment]
Haven't seen this in a while. @adilGhaffarDev Are you aware of any recent occurences?

**Comment by sbueringer** [comment]
cc @killianmuldoon @chrischdi (in case you unblocked any recently)

**Comment by adilGhaffarDev** [comment]
> Haven't seen this in a while. @adilGhaffarDev Are you aware of any recent occurences?

Same here, I haven't seen any for a while.
