### ISSUE TITLE
test/e2e: Consolidate dualstack / IPv6 / ... tests

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8578]
### What would you like to be added (User Story)?

Currently we have a separate Job to run the IPv6 test. We do this because it looked like we have to create the kind bootstrap cluster with IPFamily IPv6 to provision a workload cluster with IPv6.

### Detailed Description

Given (and probably after) the recent work on the Dual Stack e2e test I wonder if it's technically possible to run our IPv4, DualStack and IPv6 clusters in the same job (and thus with the same mgmt cluster)

### Anything else you would like to add?

Le'ts wait with this issue until we have the dual stack e2e test working.

The benefit of making this happen is that we don't need a separate job for IPv6.

### Label(s) to be applied

/kind cleanup
/area testing
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
cc @killianmuldoon @chrischdi (just fyi)

**Comment by killianmuldoon** [comment]
/assign

I'll take a look at this while working on the dualstack test.

**Comment by sbueringer** [comment]
@killianmuldoon Took another look. I think we already run the IPv6 job as part of the dual stack job (just looking at the skip / focus / testgrid).
WDYT about already deleting the ipv6 presubmit + periodic now?

**Comment by killianmuldoon** [comment]
I think we can close this issue. I'll open a separate issue around consolidating the dualstack and non-dualstack e2e tests.
