### ISSUE TITLE
Use `kubectl kustomize` instead of `kustomize`

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#859]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

`kustomize` is now a sub-command for `kubectl` https://github.com/kubernetes/kubernetes/pull/73033 , so there is no need to let end user install `kustomize` separately, but installing `kubectl` is good enough.

We can update the script and document to clarify how to use `kubectl kustomize`. 

/cc @vincepri @detiber 

FYI @jichenjc @morvencao @xunpan @clyang82

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by detiber** [comment]
I'm not quite sure we should rely on `kubectl kustomize` just yet, there has been some controversy around the inclusion of kustomize in kubectl. We should probably follow the lead of `kubebuilder` here and switch only if they also switch.

**Comment by gyliu513** [comment]
@detiber the reason I want to propose this is I want to make we can use `cluster-api` as simple as possible, installing or requesting less binaries can always make life easier ;-)

**Comment by vincepri** [comment]
The CI scripts have been switched to use `kubectl kustomize`, we should be able to close this one out. If there are any issues later on to use it, we should switch back to a kustomize binary, pinned to a specific version.

/close
