### ISSUE TITLE
Replace clusterctl yaml processing with simple go templating in autoscaler e2e

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#8592]
**Detailed Description**:

The autoscaler e2e does YAML processing to build the workload YAML that gets applied during the autoscaler e2e testing.

This should be replaced by simple go templating and we dont have to use the clustectl library to do the yaml processing. 

Other parts of the e2e tests already do this. Example: https://github.com/ykakarap/cluster-api/blob/9afafad2b94490feb6d49aa4ff7979ad06e48560/test/framework/kubernetesversions/template.go#L38-L41

Ref: https://github.com/kubernetes-sigs/cluster-api/pull/8514#discussion_r1176819759

Note: Needs https://github.com/kubernetes-sigs/cluster-api/pull/8514 to be merged.

/area testing

**Comment by fabriziopandini** [comment]
I'm not sure this is necessary/the right path to go; If we look at this from another PoV, now we are consistently using env subst for all the yamls, while the debianInjectionScript is not a yaml template.

**Comment by sbueringer** [comment]
It's okay for me to keep it as is if you prefer. I see the upside in using the same templating everywhere. Just seems pretty heavy to use clusterctl as a templating engine.

Feel free to close

**Comment by fabriziopandini** [comment]
As per comment above
/close
