### ISSUE TITLE
Implement E2E test for streamlined upgrades

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#8615]
### What would you like to be added (User Story)?

It will be great to have a signal about streamlined upgrades in CAPI as well (both for legacy and classy clusters)

### Detailed Description

This [KEP](https://github.com/kubernetes/enhancements/pull/3936) introduced the idea of streamlined upgrades, and, by playing around with K8s version skew policies, making it possible to upgrade by 2 or 3 Kubernetes minor versions by minimizing the worker's machines rollouts.

### Anything else you would like to add?

The UX for streamlined upgrades in CAPI is not ideal, it requires manually upgrading through all the minors and applying "topology.cluster.x-k8s.io/hold-upgrade-sequence" to the first MD till the target version is reached, but it should work.

### Label(s) to be applied

/kind feature
/area testing
/area conformance

**Comment by vincepri** [comment]
What do we mean by "streamlined", as in just go through each revision programmatically?

**Comment by fabriziopandini** [comment]
"streamlined" was a term used in some discussion, but I'm not sure it is the best of the correct one.

What we want to test is an upgrade sequence that is allowed by K8s skew policies, that allows you to go up by three minors in faster than going through each revision; the trick is to make the control plane to go through all the steps, and only after the control plane is at the target version you can make a single upgrade for all the workers skipping the intermediate steps.

The example from the proposal is

  1. Begin: control plane and nodes on v1.40
  2. Control plane upgrade: v1.40 → v1.41 → v1.42 → v1.43
  3. Node upgrades: v1.40 → v1.43

**Comment by fabriziopandini** [comment]
Thinking again to this issue I'm now leaning toward closing it because IMO we should aim at implementing first-class support for skipping worker upgrades (vs stretching the usage of "topology.cluster.x-k8s.io/hold-upgrade-sequence" for a use case it was not designed for)

/close
