### ISSUE TITLE
Should we increase the default certificate duration to 18 months?

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#8620]
We currently create cluster certificate that last 1 year, with the current upstream efforts to increase the support skew https://github.com/kubernetes/enhancements/pull/3936, should we change the default certificate duration to allow more time for folks to upgrade their nodes?

https://github.com/kubernetes-sigs/cluster-api/blob/299024ffa3a31ee3dce3e1f12d623ea0f8e8824a/util/certs/consts.go#L26

**Comment by sbueringer** [comment]
If I see correctly this duration is only used by KCP to generate the kubeconfig secret. Today we generate it with 1 year expiry and then regenerate it after 6 months.

I'm not sure how this is related with the support skew KEP.

If I understand you're intent correctly we should probably open this issue for kubeadm instead so the hard-coded 1 year expiry that kubeadm uses (and we just inherit) is extended.

**Comment by fabriziopandini** [comment]
/triage accepted

Agree with @sbueringer, just adding that with automatic certificate rotation recently implemented also kubeadm expiration is not a big problem anymore

**Comment by sbueringer** [comment]
Adding on top of that. With the current default setup (core CAPI + KCP + CABPKG) we only rotate control plane machines. Worker machines don't have to be rotated as they use a self-signed certificate that is never validated.

**Comment by neolit123** [comment]
note that if this is an RSA cert paired with a 2048 key, expiration > 1 year would need a bigger key. e.g. 3072.

see
https://kubernetes.slack.com/archives/C019LFTGNQ3/p1683275607359709?thread_ts=1683235193.545829&cid=C019LFTGNQ3

---

off topic

cert serials must be in the 1,max range
https://github.com/kubernetes-sigs/cluster-api/blob/299024ffa3a31ee3dce3e1f12d623ea0f8e8824a/util/certs/types.go#L53

see
https://github.com/kubernetes/kubernetes/pull/117791

**Comment by fabriziopandini** [comment]
I'm leaning towards closing here, giving that cert duration is driven by kubeadm and in CAPI we now have automatic certificate renewal

**Comment by fabriziopandini** [comment]
@sbueringer @vincepri 
opinions
(if not, we should probably move the issue to kubeadm)

**Comment by sbueringer** [comment]
Agree, if there is still interest in seeing this implemented we need a change in kubeadm first.

**Comment by Levi080513** [comment]
Can we support configuration of `DefaultCertDuration`?
Users may use the kubeconfig generated by CAPI as the basis for the upper-layer management system to access the workload cluster. The current default validity period seems a bit short.

**Comment by sbueringer** [comment]
I think the scope of this issue is the certificates on the Machines, not the kubeconfig we generate.
(otherwise "should we change the default certificate duration to allow more time for folks to upgrade their nodes?" wouldn't make sense)

**Comment by fabriziopandini** [comment]
> Users may use the kubeconfig generated by CAPI as the basis for the upper-layer management system to access the workload cluster.

I would advise avoiding to re-use the kubeconfig generated by CAPI for other services (or for users).
Instead, you should create a new certificate, with a dedicated identity, and scope it down it permission to what is strictly required.

**Comment by Levi080513** [comment]
> I think the scope of this issue is the certificates on the Machines, not the kubeconfig we generate. (otherwise "should we change the default certificate duration to allow more time for folks to upgrade their nodes?" wouldn't make sense)

Yes, sorry for responding to other questions.

**Comment by Levi080513** [comment]
> > Users may use the kubeconfig generated by CAPI as the basis for the upper-layer management system to access the workload cluster.
> 
> I would advise avoiding to re-use the kubeconfig generated by CAPI for other services (or for users). Instead, you should create a new certificate, with a dedicated identity, and scope it down it permission to what is strictly required.

Thanks for the reply, this is very helpful to me.

**Comment by fabriziopandini** [comment]
/close

because: 
- changing cert duration requires changes in kubeadm first, starting by increasing key length
- we answered to question about the cert in the generated kubeconfig file
