### ISSUE TITLE
Approach to SANs injection to KCP spec 

### ISSUE THREAD

**Issue by i-prudnikov** [kubernetes-sigs/cluster-api#8624]
Dears,
Following the cluster API book, the infrastructure cluster controller should take care of preparing infrastructure for cluster deployment, and report back that it is ready. This triggers the CAPI controllers to proceed with CP and workers deployment.
The question: part of the infrastructure cluster controller job is to create LB to be used by as target cluster API server endpoint . After the LB is created we can fetch it's DNS name and we would like to inject it into SANs list in KCP object, to allow proper certificate generation.

What is the recommended approach to do that?
For example, mutating KCP spec before reporting the cluster infrastructure to be ready is not smth that seems robust, as it creates a risk that CAPI controllers will not observe this changes (due to stale cache) and start bootstrapping CP machine with outdate spec, and even worse, later when the changes would become visible to CAPI controllers, they start rolling update procedure for CP node as the KCP spec is not match to kubeadm config spec for the CP machine.

Another point: is the CAPI controllers expect that SANs are well know upfront? Before pushing KCP object into master cluster?

**Comment by fabriziopandini** [comment]
/triage accepted
/kind support

This is an interesting use case, but I'm not sure we have a great solution at this moment.

kubeam, which is used internally to KCP expects to know all the SANS upfront; that means that if you need to inject some sans you currently have two options:

- inject the value in the kcp object doing it before declaring your cluster infrastructure ready (with the caveats you described)
- inject the value in the kubedm config via pre-kubeadm commands during control-plane machine bootstrap 

The second option is probably the most robust, but it requires some bash magic and the capability for the machine to read LB metadata (or to discover them via some trick like dig).

In the future we might come up with some more elegant solutions like additional lifecycle hooks, but at this moment I'm not aware of any work/design proposal in this area.

**Comment by i-prudnikov** [comment]
@fabriziopandini, Thank you for your suggestions. So far I end up in patching kubeadm config before injecting it into user-data of VM to be created. This simplify a lot of stuff as there is no guarantee that we have all the SANs known in the context of VM running prekubeadm commands.

**Comment by sbueringer** [comment]
I really wonder how this works today in CAPA/CAPZ.

**Comment by sbueringer** [comment]
cc @CecileRobertMichon @richardcase ^^
