### ISSUE TITLE
Tests failing with "No Control Plane machines came into existence."

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#8641]
### Which jobs are flaking?

Various

### Which tests are flaking?

Various

### Since when has it been flaking?

Months

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1656055608303947776

### Anything else we need to know?

This type of failure - the workload cluster not coming up at all - is present across many tests and across all e2e jobs in 1.3, 1.4 and main.

Examples from the triage page:
- https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*&xjob=.*-provider-.*#a30173b03e60e562ff81
- https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*&xjob=.*-provider-.*#74fda7668369e3377cf4

### Label(s) to be applied

/kind flake

**Comment by killianmuldoon** [comment]
Looking at the following failures:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-release-1-4/1656331680853528576
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-release-1-4/1656271029930037248
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-release-1-4/1656089330768154624
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-release-1-4/1655786848947015680
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-release-1-4/1655665547787898880


These are all on release-1.4, but there are other failures on main and release-1.3.

**Comment by killianmuldoon** [comment]
Summing up today's CI deep dive session. ([slack thread here & recording to follow](https://kubernetes.slack.com/archives/C8TSNPY4T/p1683738496714559))

We took a look at the logs of a number of jobs running into this issue. We found that they all had the following error:

`time="2023-05-10T12:24:20.212345448Z" level=error msg="Handler for POST /v1.41/containers/f4491a84b14a449f34c0936efa205a6c29801e9cd9a7a49e8a1a398331e0a701/start returned error: driver failed programming external connectivity on endpoint k8s-upgrade-with-runtimesdk-nrad0n-r7jd7-br8cb (ded08f8232fde4eb4791a20efd565887d551aba71c42571e761b27bcddfe22d2): Error starting userland proxy: listen tcp4 127.0.0.1:42831: bind: address already in use"
`
This was recorded in both the docker log and in CAPD when it tried to start the first control-plane machine.

We traced this back to the below code in CAPD. CAPD tries to create a machine with a random port and this fails. We don't retry the operation.

https://github.com/kubernetes-sigs/cluster-api/blob/76e2fb12a37d5be71ca61e3414d284c6da5f0e4c/test/infrastructure/docker/internal/controllers/dockermachine_controller.go#L258-L265

Two possible solutions:
1 - figure out why the port doesn't become available in some cases
2 - add a retry so that if we hit this error we don't just abandon trying to create the cluster

**Comment by sbueringer** [comment]
To clarify

> This type of failure - the bootstrap cluster not coming up at all - is present across many tests and across all e2e jobs in 1.3, 1.4 and main.

Not the bootstrap cluster, but the first workload cluster we create with CAPD in the e2e test, correct?

**Comment by killianmuldoon** [comment]
>Not the bootstrap cluster, but the first workload cluster we create with CAPD in the e2e test, correct?

Yes - thanks for the clarification.

**Comment by sbueringer** [comment]
> Two possible solutions:
> 1 - figure out why the port doesn't become available in some cases
> 2 - add a retry so that if we hit this error we don't just abandon trying to create the cluster

Looks to me like the way we do it is unsafe: https://github.com/kubernetes-sigs/cluster-api/blob/0dfd68cd4ded0f51747be2e9541dd5a70876e6ad/test/infrastructure/docker/internal/docker/kind_manager.go#L195-L205

We get a random port from `net.Listen`, then close the listener and then hand it over to to Docker when we create a Node. If a second Machine is reconciled at the same time the chance is high that we get the same random port which is available until the first Node actually comes up.

I wonder if there is an alternative to let Docker pick a random port

**Comment by chrischdi** [comment]
Also: is capd even able to find a correct port? It is not running with hostNetwork.

**Comment by chrischdi** [comment]
I think we now face a different error, which I think may be unrelated to the merged change.

Taking a look at the latest jobs:

* [14/05/2023, 22:23:08	periodic-cluster-api-e2e-release-1-4](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1657905772534697984)
* [14/05/2023, 09:25:58	periodic-cluster-api-e2e-main](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1657875321602445312)
* [14/05/2023, 08:27:40	periodic-cluster-api-e2e-mink8s-main](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-release-1-4/1657843360615895040)
* [14/05/2023, 02:23:00	periodic-cluster-api-e2e-release-1-4](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1657647820611522560)
* [14/05/2023, 01:25:35	periodic-cluster-api-e2e-main](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1657633223892537344)

And digging into the logs I see the following common issue:

The DockerCluster objects of all these cases have the following conditions:
```
- lastTransitionTime: "2023-05-15T01:38:15Z"
  message: 0 of 1 completed
  reason: LoadBalancerProvisioningFailed
  severity: Warning
  status: "False"
  type: Ready
- lastTransitionTime: "2023-05-15T01:38:15Z"
  message: 'load balancer IP cannot be empty: container clusterctl-upgrade-9rghzf-lb does not have an associated IP address'
  reason: LoadBalancerProvisioningFailed
  severity: Warning
  status: "False"
  type: LoadBalancerAvailable
```

CAPD logs the same.

The output of `docker ps` shows that the load balancer pod is not started:

```
133f6a9db822   kindest/haproxy:v20230330-2f738c2                           "haproxy -sf 7 -W -d…"   13 minutes ago      Exited (0) 13 minutes ago                                             clusterctl-upgrade-9rghzf-lb
```

And the docker.log shows:

```
level=error msg="Error setting up exec command in container clusterctl-upgrade-9rghzf-lb: Container 133f6a9db8227039c530b9dae5ad4718790ec05aae6aa1c9eb28ee172c105f56 is not running"
```

Without further information.

**Comment by killianmuldoon** [comment]
>I think we now face a different error, which I think may be unrelated to the merged change.

Was also looking at this - I'm wondering if it is somehow related to the change - given the timing, but I'm really unsure.

**Comment by sbueringer** [comment]
> The output of docker ps shows that the load balancer pod is not started:

Or more specifically already exited. Looks like it was started and then exited early (just emphasizing as "container are not started at all" is a different issue)

**Comment by chrischdi** [comment]
> Or more specifically already exited.

Yes, bad wording from my side above. It is Exited so it was started.

**Comment by killianmuldoon** [comment]
I'm also seeing this locally from time-to-time, both in e2e and in creating normal clusters. Not sure if something about the change in https://github.com/kubernetes-sigs/cluster-api/pull/8642 could have made this worse, but I don't understand how.

**Comment by chrischdi** [comment]
I was not yet able to reproduce it locally :-(

WDYT about experimenting via getting a change similar to https://github.com/kubernetes-sigs/cluster-api/pull/8685/files (but with updated args to `haproxy", "-W", "-db", "-f", "/usr/local/etc/haproxy/haproxy.cfg"`) into main and see 🤔  I currently have no other idea what could happen

**Comment by chrischdi** [comment]
(Maybe I can't get it locally due to being on OSX.

**Comment by sbueringer** [comment]
You should work on Linux! :)

**Comment by killianmuldoon** [comment]
I'll see if I can reproduced locally with any sort of consistency - running the quick-start X 100 now. Then I'll see if changing the command has any impact.

**Comment by chrischdi** [comment]
/reopen

The issue will persist, just a case is hopefully solved (this is also to be checked)

**Comment by killianmuldoon** [comment]
This is looking good over the last couple of days and backported to 1.3 / 1.4 today. Let's see how it performs over the weekend.

One outstanding issue that we have is in our 0.4 and 1.0 upgrade tests (also in 1.2 but that's due to be removed soon). We still get this flake on those tests as (obviously) we haven't backported this fix. Let's see how often those flakes occur but possibly discuss introducing a fix like this if they're disruptive to the signal.

I think this probably isn't much of a problem as the 0.4 and 1.2 upgrade tests will be removed soon - both during the next release cycle so August or September. That would leave just the 1.0 job suffering from this issue, but that job will probably stick around for a long time to ensure API compatibility.

**Comment by killianmuldoon** [comment]
There's still a couple of flakes with the same error message, but nowhere near the same frequency and probably not the same root cause. Let's close this and follow up on other flakes in a separate issue.

/close
