### ISSUE TITLE
User-managed cert-manager doesn't get recognized during clusterctl init

### ISSUE THREAD

**Issue by vinibali** [kubernetes-sigs/cluster-api#8649]
### What steps did you take and what happened?

We are using an integration Helm chart to deploy cert-manager and just calling the clusterctl init afterwards.
In case if cert-manager is deployed alone with it's yaml file or the single Helm chart, clusterctl find this and doesn't trigger a deployment.
However if cert-manager is part of an umbrella chart, clusterctl init starts an apply from Github using the cert-manager.yaml.
Unfortunately this environment doesn't have the chance to use GITHUB_TOKEN variable.
Cert-manager is deployed to a custom namespace all the time and the same behavior can be seen, even after I've added the label
```
clusterctl.cluster.x-k8s.io/core=cert-manager
```
to the commonLabels here:
https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml#L17
This can be seen on the pods.
Do you have any idea what could be the problem?
If I compare the yaml output of pods of each deployment, nothing serious can be seen.

### What did you expect to happen?

Clusterctl won't apply the official cert-manager chart

### Cluster API version

v1.3.2

### Kubernetes version

v1.25.3

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by killianmuldoon** [comment]
It shouldn't matter how you install cert-manager onto your cluster. `clusterctl` checks to see if test resources - [from  this file in the CAPI repo](https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/cluster/assets/cert-manager-test-resources.yaml) - can be correctly applied to the cluster. 

[This is the relevant part of the code](https://github.com/kubernetes-sigs/cluster-api/blob/31e4807cb557c20c53fee9af3fdcbf54d2672978/cmd/clusterctl/client/cluster/cert_manager.go#L157). Can you try to apply the test resources manually to see what the result is? What version of cert-manager have you pre-applied to the Cluster?

/triage accepted

**Comment by vinibali** [comment]
This is what I was looking for. The error just showed me the problem and it seems to be a user error.
The CRD was completely missing. For now I understand the situation with all the different clusters and the occurrence of this problem.
However I still don't understand why the startupapicheck at cert-manager was completed successfully with the umbrella chart, of course it fails if I just apply the standalone cert-manager chart without the CRD. We split the factory chart - which switches the CRD inside the values.yaml - into two different charts.
Do you think if we could update the clusterctl init's check to mention the missing CRD, while the other pods are there.
Otherwise the label was not needed for cert-manager https://github.com/kubernetes-sigs/cluster-api/blob/v1.3.2/docs/book/src/clusterctl/configuration.md?plain=1#L102
Thanks for you time

**Comment by killianmuldoon** [comment]
> Do you think if we could update the clusterctl init's check to mention if the CRD is missing, but cert-manager pods are there?

I don't think so - it's hard to check for pods when we can't make real assumptions about the names and the versions installed.

You shouldn't need to add that label manually unless you want your cert-manager to be managed by clusterctl - e.g. for upgrades.

**Comment by vinibali** [comment]
Thanks, have a nice day!
