### ISSUE TITLE
Support Kubelet Config

### ISSUE THREAD

**Issue by Bo0km4n** [kubernetes-sigs/cluster-api#8670]
### What would you like to be added (User Story)?

In currently, when user add additional config of kubelet, user add params to KubeadmConfigSpec resource `.spec.joinConfiguration.nodeRegistration.kubeletExtraArgs`.

But, recently kubelet warns some args will be removed and recommended that should be set via config file specified by kubelet's --config flag.
So when we use new version Kubernetes, this how to specify kubelet args maybe will be cannot use I think.

Therefore, I suggest to make setting KubeletConfig (https://pkg.go.dev/k8s.io/kubelet/config/v1beta1#KubeletConfiguration) via KubeadmConfig resource.

### Detailed Description

NONE

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by killianmuldoon** [comment]
The `KubeadmConfig` used in CAPI is a mostly a mirror of the upstream type - https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/. I'm not sure if the CAPI type is currently missing anything included in the upstream type. But I don't think including the full kubelet config is a real option here as it would be confusing to users.

One option for setting the KubeadmConfig would be to directly pass a file into the `KubeadmConfig`

This is a very interesting discussion though - I think it's linked to #8425

**Comment by neolit123** [comment]
ideally, CAPI should let kubeadm manage the kubeletconfiguration v1beta1 GVK.

> I think it's linked to https://github.com/kubernetes-sigs/cluster-api/issues/8425

+1 to close in favor of 8425, where documenting existing approaches was proposed.

**Comment by Bo0km4n** [comment]
@killianmuldoon @neolit123 
Thanks for your mentions.
Kubelet config contents are common and fixed, so I will try to set parameters of that via KubeadmConfigSpec `.files`.

**Comment by musaprg** [comment]
I prepared several examples for #8425. They might help for this purpose.
https://github.com/musaprg/cluster-api-kubelet-config-examples
