### ISSUE TITLE
📖 add runtime ExtensionConfig in the CAPI book

### ISSUE THREAD

**Issue by aniruddha2000** [kubernetes-sigs/cluster-api#8679]
If there are some more references of `ExtensionConfig` in the CAPI book that would be a great addition, for example - 

- Having an ExtensionConfig example in the [settings](https://cluster-api.sigs.k8s.io/tasks/experimental-features/runtime-sdk/implement-extensions.html#settings) would be great.
- Adding an extra point at [deploy-runtime-extensions](https://cluster-api.sigs.k8s.io/tasks/experimental-features/runtime-sdk/deploy-runtime-extension.html#deploy-runtime-extensions) **"Register the Runtime Extension using ExtensionConfig"** is required, as it's an important step towards building runtime-SDK

**Comment by killianmuldoon** [comment]
/triage accepted 
/area documentation

Thanks for taking this on!
