### ISSUE TITLE
Consider moving IPAM provider out of experimental

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#8694]
- What are the requirements for this provider to move to v1beta1 types / guarantees?
- Are there long standing issues?
- What would be the next logical step from the current state?

cc @schrej

**Comment by sbueringer** [comment]
Just for confirm. You're talking about dropping the feature gate on the IPAM types, right? 


(there is no IPAM provider in core CAPI)

**Comment by vincepri** [comment]
Yes

**Comment by fabriziopandini** [comment]
I will defer this to the folks working on IPAM/to the majority on the community meeting, however, if I'm not wrong we just merged a couple of changes on IPAM API types, so might be worth giving some more room to gather feedback from the field before graduation (might be it will be enough doing it in 1.6 instead of 1.5)

**Comment by sbueringer** [comment]
> I'd say the requirements are that the API doesn't require any breaking changes anymore.

Absolutely up to you, but I think it's good enough if we think it's reasonable stable and fulfills the use cases we currently want to address. As we're only talking about v1beta and not v1 (I think), we have some leeway mid- to long-term to make breaking changes if actually necessary.

**Comment by rvanderp3** [comment]
Hi all, I'm following up on this discussion to see if anything has been learned that would prevent the IPAM APIs from being promoted to v1beta1.  Thanks!

**Comment by rvanderp3** [comment]
@tylerschultz @schrej following up here to see if there are any new thoughts around the possibility of promoting the API to v1beta1.  I'm happy to help with the promotion if needed.

**Comment by schrej** [comment]
I think we can go ahead and promote to beta. It's been quite a long time and we haven't found anything else. As said, we might need something for hostnames, but that would be additive, which is fine.

**Comment by killianmuldoon** [comment]
If folks are happy to move forward with this it would be good to announce it at the community meeting. The code freeze for the next release is Tuesday 14th November 2023, so there's probably enough time to get a v1beta1 set of APIs prepared and merged. If anyone's interested in taking up the work feel free to assign yourself.

**Comment by rvanderp3** [comment]
sure, we can discuss at the next meeting.  I'll go ahead and assign it to myself for now unless anyone else wants to grab it.

/assign @rvanderp3

**Comment by rvanderp3** [comment]
Per the discussion in the meeting today, will create v1beta1 for the IPAM types in the `exp` package.
