### ISSUE TITLE
Two CRDs named `clusters` as short name

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#870]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

cluster-api is using CRD name as `clusters.cluster.k8s.io`, but there is another project https://github.com/kubernetes/cluster-registry which is also using a CRD named as  `clusters.clusterregistry.k8s.io`, and both of those two CRD are using `clusters` as short name. If I deployed both CRs for those two CRDs, then what is the outpout of `kubectl get clusters`?

```
root@liugya-master-fx9nn:~# kubectl get crd | grep clusters
clusters.cluster.k8s.io                                           2019-04-02T05:30:03Z
clusters.clusterregistry.k8s.io                                   2019-04-03T06:15:06Z
```

/cc @vincepri @detiber 

FYI @jichenjc @xunpan @clyang82 @morvencao

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
There is currently no way to choose the relative priority ordering for custom resources when you execute `kubectl get`. What happens is `kubectl` downloads the API discovery document from the apiserver and stores it in a local file cache. The discovery document contains a list of all the resources the apiserver offers. Whichever `cluster` resource is first in the list is the one that `kubectl get` will retrieve.

There is also no way to reserve a unique resource name (such as `clusters`) across all API groups. If you happen to install both cluster-api and cluster-registry CRDs, you will run into the situation you described. You must be explicit to ask for `clusters.cluster.k8s.io` if you want cluster-api's `clusters` in this case.

I don't believe there is an issue here, so closing. Please feel free to reopen if needed.

/close

**Comment by domenicbove** [comment]
@ncdc do you know where that local file cache is? Is there a way to delete it?

I have this naming collision right now:
```
kafkatopics.kafka.banzaicloud.io                        2023-10-17T17:46:26Z
kafkatopics.kafka.strimzi.io                            2023-10-25T15:52:53Z
```

And decided to go with strimzi and deleted the banzaicloud one... but I still get
```
% kubectl get kafkatopic
Error from server (NotFound): Unable to list "kafka.banzaicloud.io/v1alpha1, Resource=kafkatopics": the server could not find the requested resource (get kafkatopics.kafka.banzaicloud.io)
```
