### ISSUE TITLE
Help in testing CAPI with CAPD

### ISSUE THREAD

**Issue by Sir-gits-a-lot** [kubernetes-sigs/cluster-api#8707]
### Discussed in https://github.com/kubernetes-sigs/cluster-api/discussions/8696

<div type='discussions-op-text'>

<sup>Originally posted by **Sir-gits-a-lot** May 19, 2023</sup>
cluster api not able to reconcile for docker infrastructure provider, I have created a k8s cluster using kind. 

Initialized it using clusterctl init --infrastructure docker and apply one CAPI manifest for 3 control-node + 3 worker node. It was successfully deployed, all the machines were up (docker containers). 

After that I am trying to test the benefits of doing this whole thing using CAPI (Reconcillation, full lifecycle management of workload clusters). 

For that I stopped 1 container(worker node machine), So even though Cluster CAPI detects the change and starts the reconcillation process (this I can say by checking the capd-controller-manager pod logs, it was not able to set up the worker node. I expected it to launch another conatiner and add it to the cluster but it's not able to do that. 

There is no issue with memory, I have increased the inotify limit. 

How I can resolve this? </div>

**Comment by stmcginnis** [comment]
You can try getting the logs from the capd-controller pod. If I remember right, you can find the specific name by using `kubectl get pods -n capd-system`. Once you have the name, running `kubectl logs $POD_NAME -n capd-system` will get the logs. Hopefully that output includes some error messages that could help point to what is failing.

**Comment by Sir-gits-a-lot** [comment]
The logs just say that the reconciliation process started and then waiting for the machine to report Ready status.

**Comment by killianmuldoon** [comment]
>So even though Cluster CAPI detects the change and starts the reconcillation process (this I can say by checking the capd-controller-manager pod logs, it was not able to set up the worker node. I expected it to launch another conatiner and add it to the cluster but it's not able to do that.

This behaviour is enabled by MachineHealthChecks - you can create a MachineHealthCheck object and apply it to the Cluster. This enables you to decide under what conditions machines are replaced.

There's more information and an example yaml here: https://cluster-api.sigs.k8s.io/tasks/automated-machine-management/healthchecking.html#creating-a-machinehealthcheck

**Comment by Sir-gits-a-lot** [comment]
So, I have explored the concept of machine Health check and tried it according to https://cluster-api.sigs.k8s.io/tasks/automated-machine-management/healthchecking.html#creating-a-machinehealthcheck also. The problem is machine healthcheck feature is working just fine for when I patch the worker nodes with node is unhealthy status message but if I just stop one of the docker containers acting as worker node for the setup, it's not able to bring that machine up (relaunch a container and add it to cluster).

 I want to know whether that can happen or not and if yes, how it'll be achieved. It is very important as it would clearly help me understand CAPI.

And BTW, I think machine health check should be a default feature or at least there should be a flag for it in clusterctl generate command. Because making a normal cluster into management cluster itself means installing all the CRDs (machines,machinedeployments, machinesets) so, it should also include deploying Custom resource controller. Like a CR controller/Operator for checking health of the machines, machinedeployments and machinesets. 

Please help with the issue and provide comments of the idea, thanks.

**Comment by killianmuldoon** [comment]
>but if I just stop one of the docker containers acting as worker node for the setup, it's not able to bring that machine up (relaunch a container and add it to cluster).

This should work - but might depend on how you have your MHC configured. With CAPD if you stop a DockerMachine and Node by running `docker stop` we get the Ready condition with `status:  Unknown` and `reason: NodeStatusUnknown` on the Node object.

This should be caught by the check in the basic MHC defined at https://cluster-api.sigs.k8s.io/tasks/automated-machine-management/healthchecking.html#creating-a-machinehealthcheck. If this isn't working for you it would be good to share  the full MHC object as it exists in your cluster. There might be a clue there as to why it's not working.

>machine health check should be a default feature

This is a default feature, but you're right that MHCs aren't generated by `clusterctl generate cluster`. You can create your own base templates to generate clusters from which can include things like MHCs, but  there's no flag for it in the CLI. You can enable it in the generated ClusterClass (created when using docker infrastructure and `clusterctl generate`) a[s described here](https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-class/write-clusterclass.html#clusterclass-with-machinehealthchecks).

>Because making a normal cluster into management cluster itself means installing all the CRDs (machines,machinedeployments, machinesets) so, it should also include deploying Custom resource controller

The MHC controller is always deployed as part of the capi-controller-manager. Each Cluster needs to have it's own MHCs specified.

**Comment by fabriziopandini** [comment]
Please always keep in mind that the Docker provider is not designed for production use and is intended for development environments only. 

Also, be aware that the cluster templates every provider is offering are just examples, and AFAIK most users built their own templates to take full control of their environment.

**Comment by Sir-gits-a-lot** [comment]
Thanks for your continued support. Actually I created the MHC using this link [](https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-class/write-clusterclass.html#clusterclass-with-machinehealthchecks) but still when I try to do the docker stop thing to simulate a condition of node crash (when I launch the cluster in one of the cloud where the nodes are EC2 instances/VMs and not docker containers). CAPI is not able to start new container and bootstrap it to act like a node. 

And I would really appreciate if you could help me understand why MHC comes as a separate object like an additional feature because as per my understanding initializing the cluster api (Making Bootstrap Cluster into Management Cluster/Launching a new Management Cluster) will involve the process of starting all the CRDs and Customer Resource Controllers for CAPI to work so if Machine now becomes a new K8s resource (CR) then CR Controller should also be initialized in that phase only right. This would really help me understand the concept if you could answer, thanks.

**Comment by killianmuldoon** [comment]
>And I would really appreciate if you could help me understand why MHC comes as a separate object like an additional feature because as per my understanding initializing the cluster api (Making Bootstrap Cluster into Management Cluster/Launching a new Management Cluster) will involve the process of starting all the CRDs and Customer Resource Controllers for CAPI to work so if Machine now becomes a new K8s resource (CR) then CR Controller should also be initialized in that phase only right. This would really help me understand the concept if you could answer, thanks

MachineHealthChecks CRD and controller are initialized like all other CAPI objects e.g. Machines, Clusters, but you need a specification of the MHC in a custom resource for your Cluster specifically - this aligns with the Kubernetes resource model - e.g. you need to create a service if you want to use it with a pod.

If the MHC isn't working for you it would be good to share the full MHC object as it exists in your cluster - including the status, as well as the Cluster object and the MachineDeployment object. There might be a clue there as to why it's not working.
 
We would need this information to help triage this issue.

**Comment by Sir-gits-a-lot** [comment]
> You can try getting the logs from the capd-controller pod. If I remember right, you can find the specific name by using `kubectl get pods -n capd-system`. Once you have the name, running `kubectl logs $POD_NAME -n capd-system` will get the logs. Hopefully that output includes some error messages that could help point to what is failing.

This is what the logs say 
 http: TLS handshake error from 10.244.0.1:32321: EOF

**Comment by Sir-gits-a-lot** [comment]
I am attaching my full Capi-Quickstart deployment yaml file, My problem is MachineHealthCheck is detecting node failure when I patch the node with status message "NodeisUnhealthy" but when I do docker stop on 1 of the worker node containers, it's not able to detect it. Please help me understand my mistake here. 

`apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: quick-start
  namespace: default
spec:
  controlPlane:
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: quick-start-control-plane
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: quick-start-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: DockerClusterTemplate
      name: quick-start-cluster
  patches:
  - definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/clusterConfiguration/imageRepository
        valueFrom:
          variable: imageRepository
      selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
    description: Sets the imageRepository used for the KubeadmControlPlane.
    enabledIf: '{{ ne .imageRepository "" }}'
    name: imageRepository
  - definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/initConfiguration/nodeRegistration/kubeletExtraArgs/cgroup-driver
        value: cgroupfs
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/joinConfiguration/nodeRegistration/kubeletExtraArgs/cgroup-driver
        value: cgroupfs
      selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
    description: |
      Sets the cgroupDriver to cgroupfs if a Kubernetes version < v1.24 is referenced.
      This is required because kind and the node images do not support the default
      systemd cgroupDriver for kubernetes < v1.24.
    enabledIf: '{{ semverCompare "<= v1.23" .builtin.controlPlane.version }}'
    name: cgroupDriver-controlPlane
  - definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec/joinConfiguration/nodeRegistration/kubeletExtraArgs/cgroup-driver
        value: cgroupfs
      selector:
        apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
        kind: KubeadmConfigTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - default-worker
    description: |
      Sets the cgroupDriver to cgroupfs if a Kubernetes version < v1.24 is referenced.
      This is required because kind and the node images do not support the default
      systemd cgroupDriver for kubernetes < v1.24.
    enabledIf: '{{ semverCompare "<= v1.23" .builtin.machineDeployment.version }}'
    name: cgroupDriver-machineDeployment
  - definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/clusterConfiguration/etcd
        valueFrom:
          template: |
            local:
              imageTag: {{ .etcdImageTag }}
      selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
    description: Sets tag to use for the etcd image in the KubeadmControlPlane.
    name: etcdImageTag
  - definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/clusterConfiguration/dns
        valueFrom:
          template: |
            imageTag: {{ .coreDNSImageTag }}
      selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
    description: Sets tag to use for the etcd image in the KubeadmControlPlane.
    name: coreDNSImageTag
  - definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec/customImage
        valueFrom:
          template: |
            kindest/node:{{ .builtin.machineDeployment.version | replace "+" "_" }}
      selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - default-worker
    - jsonPatches:
      - op: add
        path: /spec/template/spec/customImage
        valueFrom:
          template: |
            kindest/node:{{ .builtin.controlPlane.version | replace "+" "_" }}
      selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        matchResources:
          controlPlane: true
    description: Sets the container image that is used for running dockerMachines
      for the controlPlane and default-worker machineDeployments.
    name: customImage
  - definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/clusterConfiguration/apiServer/extraArgs
        value:
          admission-control-config-file: /etc/kubernetes/kube-apiserver-admission-pss.yaml
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/clusterConfiguration/apiServer/extraVolumes
        value:
        - hostPath: /etc/kubernetes/kube-apiserver-admission-pss.yaml
          mountPath: /etc/kubernetes/kube-apiserver-admission-pss.yaml
          name: admission-pss
          pathType: File
          readOnly: true
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/files
        valueFrom:
          template: |
            - content: |
                apiVersion: apiserver.config.k8s.io/v1
                kind: AdmissionConfiguration
                plugins:
                - name: PodSecurity
                  configuration:
                    apiVersion: pod-security.admission.config.k8s.io/v1{{ if semverCompare "< v1.25" .builtin.controlPlane.version }}beta1{{ end }}
                    kind: PodSecurityConfiguration
                    defaults:
                      enforce: "{{ .podSecurityStandard.enforce }}"
                      enforce-version: "latest"
                      audit: "{{ .podSecurityStandard.audit }}"
                      audit-version: "latest"
                      warn: "{{ .podSecurityStandard.warn }}"
                      warn-version: "latest"
                    exemptions:
                      usernames: []
                      runtimeClasses: []
                      namespaces: [kube-system]
              path: /etc/kubernetes/kube-apiserver-admission-pss.yaml
      selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
    description: Adds an admission configuration for PodSecurity to the kube-apiserver.
    enabledIf: '{{ .podSecurityStandard.enabled }}'
    name: podSecurityStandard
  variables:
  - name: imageRepository
    required: true
    schema:
      openAPIV3Schema:
        default: ""
        description: imageRepository sets the container registry to pull images from.
          If empty, nothing will be set and the from of kubeadm will be used.
        example: registry.k8s.io
        type: string
  - name: etcdImageTag
    required: true
    schema:
      openAPIV3Schema:
        default: ""
        description: etcdImageTag sets the tag for the etcd image.
        example: 3.5.3-0
        type: string
  - name: coreDNSImageTag
    required: true
    schema:
      openAPIV3Schema:
        default: ""
        description: coreDNSImageTag sets the tag for the coreDNS image.
        example: v1.8.5
        type: string
  - name: podSecurityStandard
    required: false
    schema:
      openAPIV3Schema:
        properties:
          audit:
            default: restricted
            description: audit sets the level for the audit PodSecurityConfiguration
              mode. One of privileged, baseline, restricted.
            type: string
          enabled:
            default: true
            description: enabled enables the patches to enable Pod Security Standard
              via AdmissionConfiguration.
            type: boolean
          enforce:
            default: baseline
            description: enforce sets the level for the enforce PodSecurityConfiguration
              mode. One of privileged, baseline, restricted.
            type: string
          warn:
            default: restricted
            description: warn sets the level for the warn PodSecurityConfiguration
              mode. One of privileged, baseline, restricted.
            type: string
        type: object
  workers:
    machineDeployments:
    - class: default-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: quick-start-default-worker-bootstraptemplate
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: DockerMachineTemplate
            name: quick-start-default-worker-machinetemplate
      machineHealthCheck:
        unhealthyConditions:
        - type: DemoNodeHealthy
          status: "False"
          timeout: 1s
        - type: Ready
          status: "False"
          timeout: 300s
        - type: Ready
          status: Unknown
          timeout: 300s
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerClusterTemplate
metadata:
  name: quick-start-cluster
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: quick-start-control-plane
  namespace: default
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            certSANs:
            - localhost
            - 127.0.0.1
            - 0.0.0.0
            - host.docker.internal
          controllerManager:
            extraArgs:
              enable-hostpath-provisioner: "true"
        initConfiguration:
          nodeRegistration:
            criSocket: unix:///var/run/containerd/containerd.sock
            kubeletExtraArgs:
              eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
        joinConfiguration:
          nodeRegistration:
            criSocket: unix:///var/run/containerd/containerd.sock
            kubeletExtraArgs:
              eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: quick-start-control-plane
  namespace: default
spec:
  template:
    spec:
      extraMounts:
      - containerPath: /var/run/docker.sock
        hostPath: /var/run/docker.sock
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: quick-start-default-worker-machinetemplate
  namespace: default
spec:
  template:
    spec:
      extraMounts:
      - containerPath: /var/run/docker.sock
        hostPath: /var/run/docker.sock
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: quick-start-default-worker-bootstraptemplate
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          criSocket: unix:///var/run/containerd/containerd.sock
          kubeletExtraArgs:
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capi-quickstart
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  topology:
    class: quick-start
    controlPlane:
      metadata: {}
      replicas: 3
    variables:
    - name: imageRepository
      value: ""
    - name: etcdImageTag
      value: ""
    - name: coreDNSImageTag
      value: ""
    - name: podSecurityStandard
      value:
        audit: restricted
        enabled: true
        enforce: baseline
        warn: restricted
    version: v1.26.3
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 3
`

**Comment by killianmuldoon** [comment]
Could you post the conditions of the node that's impacted here? It would also be useful if you could add the full MHC object including the status so we can see what state the MHC considers the node to be in.

**Comment by Sir-gits-a-lot** [comment]
This is the full MHC Object, Do you mean the logs of the MachineHealthCheck object that is create as part of deployment? Also, I had 1 more question, If I create a machine health check for Control Plane machine components that targets all say 3 control plane nodes, and stop all 3 docker containers corresponding to the control plane machines. What will happen, Do I loose access to my workload cluster, I tried this experiment but I have compeletely lost access to the cluster, The kube-api server is gone, I am not able to do kubectl get nodes on the workload cluster. So, how does CAPI handle such a scenario because I thought CAPI has this control plane as a separate Custom resource which will take care of such a scenario but it doesn't seem to be doing that. 
I appreciate you trying to help me understand the behaviour of Cluster API and Your response will be very valuable to me, thanks.

**Comment by killianmuldoon** [comment]
I mean find the name of the MHC that you think is malfunctioning and get the output of `kubectl get mhc <MACHINE_HEALTH_CHECK_NAME>` This will give both the spec and the status of the object which is useful. 

When you're pasting it here could you try to apply proper formatting - so it looks like a yaml. It's easier to parse this and help if it's properly formatted.

>So, how does CAPI handle such a scenario because I thought CAPI has this control plane as a separate Custom resource which will take care of such a scenario but it doesn't seem to be doing that.

If you delete your workload cluster's APIServer you will not be able to use it as a Kubernetes cluster. In a KCP control plane control plane machines run the Kubernetes control plane components in pods, but if the machines are all deleted the cluster can not recover / is not a cluster any longer. KCP with MachineHealthChecks has the ability to recover from losing some machines, but losing all machines permanently is not recoverable.

However - KCP will not allow a MachineHealthCheck to remediate machines if that would make the control plane unstable. This scenario can only occur if all three Machines are taken down by an external event - e.g. power outage. In this case restarting the Machines should bring the Cluster back up, but this might depend on infrastructure provider.

**Comment by Sir-gits-a-lot** [comment]
> >And I would really appreciate if you could help me understand why MHC comes as a separate object like an additional feature because as per my understanding initializing the cluster api (Making Bootstrap Cluster into Management Cluster/Launching a new Management Cluster) will involve the process of starting all the CRDs and Customer Resource Controllers for CAPI to work so if Machine now becomes a new K8s resource (CR) then CR Controller should also be initialized in that phase only right. This would really help me understand the concept if you could answer, thanks
> 
> MachineHealthChecks CRD and controller are initialized like all other CAPI objects e.g. Machines, Clusters, but you need a specification of the MHC in a custom resource for your Cluster specifically - this aligns with the Kubernetes resource model - e.g. you need to create a service if you want to use it with a pod.
> 
> If the MHC isn't working for you it would be good to share the full MHC object as it exists in your cluster - including the status, as well as the Cluster object and the MachineDeployment object. There might be a clue there as to why it's not working.
>  
> We would need this information to help triage this issue.

    Like if I create an EKS Cluster with 3 worker nodes using CAPA infra provider and then I log in to the management console and delete the EKS Cluster aws resource. What will happen? Will I loose the workload cluster coz in Docker Infra Provider, it's not able to handle such situation.

**Comment by killianmuldoon** [comment]
>Like if I create an EKS Cluster with 3 worker nodes using CAPA infra provider and then I log in to the management console and delete the EKS Cluster aws resource. What will happen? Will I loose the workload cluster coz in Docker Infra Provider, it's not able to handle such situation.

In general this won't work, but it may depend on the infrastructure provider. CAPI assumes that it's in control of infrastructure resources. If another system is deleting resources CAPI will have trouble tracking those changes. Depending on the specifics a MachineHealthCheck may be able to recreate machines to bring the cluster into a healthy state, but if you delete the control plane the Kubernetes cluster will not work correctly.

You should be able to ask either in the CAPA slack channel or over at the CAPA repo for specifices on EKS clusters.

**Comment by Sir-gits-a-lot** [comment]
For the CAPD infrastructure provider, is there an option by virtue of which we can do kind of configuration Management of the K8s nodes (in this case they will be containers). Like in terraform we have null resource right, Inside the null resource we can have ssh block and file provisioner resource so like after the infrastructure is created, please log in into the machine and place some files so that my nodes have baked in some manifests files which I need to apply because I won't be applying stuff from Management Cluster, I will just launch the Workload Cluster and give the Kubeconfig to the team that needs it.

So, if there is an equivalent of Terraform File Provisioner then CAPI becomes a complete tool for me otherwise also I'll work to add that feature but first I need to know.

**Comment by killianmuldoon** [comment]
I'm not sure about your end-to-end use case, but you can load files in the KubeadmConfig if you're using the Kubeadm Bootstrap Provider. These files can be appened in `spec.files`. [You can read more about this in the CAPI book](https://cluster-api.sigs.k8s.io/tasks/bootstrap/kubeadm-bootstrap.html#additional-features).

BTW - let's close this issue as it's gotten really off the original topic. If you have follow up questions like this it's a good idea to ask in the cluster-api slack channel.

**Comment by Sir-gits-a-lot** [comment]
Okay, I'll close and explore on that front but thanks for the help throughout.
