### ISSUE TITLE
Duplicated sample YAMLs

### ISSUE THREAD

**Issue by ryanmcginnis** [kubernetes-sigs/cluster-api#873]
/kind bug

**What steps did you take and what happened:**
there are are least three directories containing similar sample YAMLs, all variously maintained:

* https://github.com/kubernetes-sigs/cluster-api/tree/master/docs/examples
* https://github.com/kubernetes-sigs/cluster-api/tree/master/config/samples
* https://github.com/kubernetes-sigs/cluster-api/tree/master/sample

in learning about the API, i'm not sure which samples i should refer to. i suggest collecting the samples in one place, and keeping one copy up to date.

**What did you expect to happen:**
N/A

**Anything else you would like to add:**
N/A

**Environment:**
N/A:

**Comment by prankul88** [comment]
Hi @vincepri , I was going through this issue and saw that in [https://github.com/kubernetes-sigs/cluster-api/tree/master/config/samples](url) the files named v1alpha1 yaml have apiVersion set to "cluster.k8s.io/v1alpha2" , while there are already seperate v1alpha2 yaml available. Can you explain why is it so?
And if anybody is not working on this I can take up this issue.
Thanks

**Comment by vincepri** [comment]
It might have been a mistake and they should be probably either removed or fixed

**Comment by prankul88** [comment]
@vincepri Should I push a PR for that?
And any opinions on how the different repos mentioned in this issue should be handled ?

**Comment by vincepri** [comment]
The samples have been removed on master given that they were outdated and broken. Examples should probably go in docs / gitbook.

/close
