### ISSUE TITLE
Validate warnings in webhook unit tests

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8732]
### What would you like to be added (User Story)?

Note: This is a follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/8007 (specifically: https://github.com/kubernetes-sigs/cluster-api/pull/8007#discussion_r1202711835)

CR v0.15 extended the validating webhook interfaces to allow returning warnings. In the initial bump PR we just ignored the warning return parameter. Goal of this task is to extend our unit tests to validate that warnings are nil (as of today we never return warnings.

### Detailed Description

The following commits shows all places where we adapted unit tests to ignore the warning return parameter: https://github.com/kubernetes-sigs/cluster-api/commit/ea0dc4da091b13bea47dbb6d41340c1f434bac5d

### Label(s) to be applied

/kind cleanup
/area testing
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by Dhairya-Arora01** [comment]
Is it correct that - "Gomega matcher should expect the warning To `BeNil`" ?

**Comment by sbueringer** [comment]
I would try BeEmpty. If possible we shouldn't care about the difference between nil and an empty slice

**Comment by Dhairya-Arora01** [comment]
@sbueringer , Im happy to take this up

**Comment by sbueringer** [comment]
Currentl we expect all returned warnings to be empty except the 1-2 cases where we already validate that they are not
