### ISSUE TITLE
Improve Context handling in clusterctl

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8733]
### What would you like to be added (User Story)?

Today we have plenty of places in clusterctl where we use context.TODO(). This issue is about incrementally improving clusterctl to pass through Context top-down.

Related:
* The recent CR bump PR (https://github.com/kubernetes-sigs/cluster-api/pull/8007) introduced the new wait utils from apimachinery which means it's now even easier to pass through context into code that is run inside of the wait utils.

### Detailed Description

-

### Label(s) to be applied

/kind cleanup
/area clusterctl

One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by aniruddha2000** [comment]
Hello  @sbueringer, I would like to work on this but, could you give some more context about this issue, are you talking about everywhere we use `context.TODO()` in clusterctl scope like [this](https://github.com/kubernetes-sigs/cluster-api/blob/1e53587dc351ad8f9320ae7a424cef41f34ff795/cmd/clusterctl/client/alpha/client.go#L22) or specific to [client operations](https://github.com/kubernetes-sigs/cluster-api/blob/a63998820617313937e22c83bc5d817b1a9b35c8/cmd/clusterctl/client/cluster/installer.go#L163)? It will be helpful if you give a bit more context on this.

**Comment by ykakarap** [comment]
Sounds like a good idea. I would recommend starting with some simple wins like evaluating any root level context that are being using and seeing if we can replace them with the right context (context.Background (?) or whatever is reelvant). 

Refactoring some of the other code to pass through context from top-down might get a little tricky and we should evaluate them on a case by case basis as refactoring some of these functions would mean some of the exported clusterctl interfaces would be impacted.

**Comment by ykakarap** [comment]
Given our current [clusterctl compatibility guarantee](https://github.com/kubernetes-sigs/cluster-api/tree/main/cmd/clusterctl#compatibility-notice) it is technically okay for us to make the changes to the interface but it would be a nice to have if we can find a way to keep the impact small.

**Comment by Fedosin** [comment]
Since we use a lot of clusterctl functions in [Cluster API operator](https://github.com/kubernetes-sigs/cluster-api-operator), it would be beneficial for us to support "context" here. I'm going to implement a fix later today to instrument all required functions with "context".
