### ISSUE TITLE
Consider not requeuing for objects that we are also watching

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8735]
### What would you like to be added (User Story)?

We have a few places where we are requeuing if external objects are not in the right state (i.e. not ready). As we are also watching those objects it's unnecessary to requeue as well.

I think it should be good for performance to avoid unnecessary requeues (less items in the queue, less reconciles). It also makes the logs less noisy.

I'm aware of the following places, but let's please also audit our code in general:
* Machine controller requeues when BootstrapConfig/Infrastructure is not ready: https://github.com/kubernetes-sigs/cluster-api/blob/a63998820617313937e22c83bc5d817b1a9b35c8/internal/controllers/machine/machine_controller_phases.go#L220
  * A bit above in the func we add a watch on BootstrapConfig in `reconcileExternal`
* MachinePool controller requeues when BootstrapConfig/Infrastructure is not ready (~ same as above)

Let's start with a first PR to remove the requeue's we're already aware of and then do an audit.

### Detailed Description

-

### Label(s) to be applied

/kind cleanup
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
@vincepri @fabriziopandini @CecileRobertMichon Not sure if I'm missing something

(cc @killianmuldoon @ykakarap @Jont828)

**Comment by killianmuldoon** [comment]
Sounds like a good idea 

/triage accepted

**Comment by vincepri** [comment]
The externalReadyWait was introduced before we had the externalTracker capability in the controllers, so this should make sense to me.

**Comment by CecileRobertMichon** [comment]
+1

**Comment by fabriziopandini** [comment]
+1 good catch!
