### ISSUE TITLE
Test flaking with "machine.cluster.x-k8s.io/certificates-expiry" does not exist

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#8747]
### Which jobs are flaking?

e.g. https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main

### Which tests are flaking?

e.g. capi-e2e.[It] When testing ClusterClass rollouts [ClusterClass] Should successfully rollout the managed topology upon changes to the ClusterClass

### Since when has it been flaking?

Since merging https://github.com/kubernetes-sigs/cluster-api/pull/8711

### Testgrid link

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main

### Reason for failure (if possible)

Probably related to changes in https://github.com/kubernetes-sigs/cluster-api/pull/8711 where the order of putting this annotation in place was changed.

Failed run here: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1661640513482133504

### Label(s) to be applied

/kind flake

**Comment by killianmuldoon** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1661640513482133504

**Comment by killianmuldoon** [comment]
I'm hopefully going to do a deep dive on this later on - hopefully not to tough to fix seeing as it's just been introduced Offchance it's SSA :thinking: - which would be more complex, but I'm betting it's a timing issue.

**Comment by sbueringer** [comment]
Thx for the link!

**Comment by killianmuldoon** [comment]
/reopen

Until we see some evidence this fixes the flake.

**Comment by killianmuldoon** [comment]
Fix in #8758 didn't work - looking at this again I think the fail in https://github.com/kubernetes-sigs/cluster-api/blob/c340c1372bd71b08c2378e125f25523a7b10757d/test/e2e/clusterclass_rollout.go#L815 needs to be more tolerant instead of directly failing if this annotation isn't available yet.

@sbueringer  - WDYT?

**Comment by killianmuldoon** [comment]
Change in #8761 seemed to fix this for main, but the solution is to completely ignore the error. I'd like to revisit this to understand how we can handle the error inside the `Eventually` call instead of not handling it.

/assign

**Comment by sbueringer** [comment]
@killianmuldoon Can we please rollback the change in #8761? Let's instead pass in Gomega into without and then use g.Fail

**Comment by killianmuldoon** [comment]
>@killianmuldoon Can we please rollback the change in https://github.com/kubernetes-sigs/cluster-api/pull/8761? Let's instead pass in Gomega into without and then use g.Fail

Yeah - something like that is the plan. Let's wait until we have some functioning CI first.

**Comment by killianmuldoon** [comment]
This test is now green.

/close

**Comment by killianmuldoon** [comment]
/reopen

This issue has re-emerged in the last few days - https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*&xjob=.*-provider-.*#7b3ebfaf894e9e2e1fe0

**Comment by killianmuldoon** [comment]
/close

The fix in #8897 has solved this for now.
