### ISSUE TITLE
🐛 Fix or reduce frequency or switch off perma-failing jobs

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/cluster-api#8784]
Data as of June 3rd, 9:00 PM Eastern. Latest data can be found here:
http://storage.googleapis.com/k8s-metrics/failures-latest.json

| CI Job | Days Failed |
| --- | --- |
| post-cluster-api-provider-cloudstack-push-images |   201 |                                            
| pull-cluster-api-e2e-scale-main-experimental |   100 |                                            
| post-cluster-api-operator-push-images |  89 |                                             
| periodic-cluster-api-provider-digitalocean-conformance-ci-artifacts |  53  |                                            
| pull-cluster-api-e2e-mink8s-main |   3                                             
| pull-cluster-api-provider-aws-e2e-eks-release-1-5 | 108 |

Additional Context:
https://github.com/kubernetes/test-infra/issues/18600

Folks, i am aware that not all jobs may not be related to this repository per se, please feel free to divvy this up to respective teams/folks/repos

**Comment by sbueringer** [comment]
To split this up

core CAPI:
* pull-cluster-api-e2e-scale-main-experimental
  * We added this job as an experiment and will probably eventually use it to run some sort of scale e2e tests (with a mock provider).
  * I think the jobs shouldn't be a problem, it's an optional presubmit that only runs when it is manually triggered
* pull-cluster-api-e2e-mink8s-main
  *  Again this is an optional presubmit. We recently added it and had an initial configuration error. It should work now (https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-e2e-mink8s-main)

CloudStack
* post-cluster-api-provider-cloudstack-push-images
  * @rohityadavcloud  @davidjumani  @jweite-amazon  @dims  @g-gaston  @chrisdoherty4  @weizhouapache Can one of you please take a look?

Cluster API Operator:
* post-cluster-api-operator-push-images
  * @JoelSpeed @Fedosin @alexander-demicev @damdo Can one of you please take a look?

Digital Ocean:
* periodic-cluster-api-provider-digitalocean-conformance-ci-artifacts
  * @cpanato @gottwald @prksu @timoreimann Can one of you please take a look?

AWS:
* pull-cluster-api-provider-aws-e2e-eks-release-1-5
  * @richardcase @sedefsavas @Skarlso @Ankitasw @dlipovetsky Can one of you please take a look?

**Comment by Ankitasw** [comment]
Raised fix for pull-cluster-api-provider-aws-e2e-eks-release-1-5:  https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4314

**Comment by furkatgofurov7** [comment]
> Cluster API Operator:
> 
> * post-cluster-api-operator-push-images
>   
>   * @JoelSpeed @Fedosin @alexander-demicev @damdo Can one of you please take a look?

Fix is up: https://github.com/kubernetes-sigs/cluster-api-operator/pull/133

**Comment by cpanato** [comment]
for CAPDO is fixed now :)

**Comment by killianmuldoon** [comment]
I think that's all of the jobs fixed - thanks again @dims for bringing this up.

**Comment by dims** [comment]
thanks for the prompt responses @killianmuldoon

**Comment by sbueringer** [comment]
Should / can we close the issue?
