### ISSUE TITLE
Update kind to v0.20.0

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#8788]
### What would you like to be added (User Story)?

As a developer I want to use the latest version of kind with CAPD.

### Detailed Description

There are a few changes in the current KIND development cycle that will make updating to KIND a multi-step process. 
To summarize `kindest/node` images are now being built with `cgroupns: "private"`, and the `entrypoint` script for those nodes works under the assumption that it is enabled. 

This issue emerged first with `kindest/node:v1.27.2` which is currently the only image built with the changes in KIND. It causes Kubernetes conformance tests to fail as the test tools aren't able to `exec` correctly in the node Docker container.

This issue is discussed in https://github.com/kubernetes-sigs/cluster-api/issues/8764

At some point in the near future - and certainly with the release of kind v0.20.0 - this issue will impact all new KIND images. KIND usually rebuilds all images for each new release, so this issue will impact all of the Cluster API jobs using `stable-XXX`.

### Proposed solution

1. Pin tests to older `kindest/node` images as required. 
2. Implement changes in https://github.com/kubernetes-sigs/cluster-api/pull/8774. These changes can only be merged after we have access to the new KIND images.
3. Revert all pinned versions in 1.

### Changes to roll back
This issue should be updated with each of the changes made for (1) above so we can keep track and ensure they're all rolled back in future.

- [ ] Remove v1.26 -> v1.27 experimental presubmits: https://github.com/kubernetes/test-infra/pull/29654
  - [ ] pull-cluster-api-e2e-workload-upgrade-1-26-1-27-krte-exp
  - [ ] pull-cluster-api-e2e-workload-upgrade-1-26-1-27-kubekins-exp 
- [ ] Revert version change in main v1.26 -> v1.27 test: https://github.com/kubernetes/test-infra/pull/29682
- [ ] Revert version change in release-1.4 v1.26 -> v1.27 test: https://github.com/kubernetes/test-infra/pull/29654

**Comment by killianmuldoon** [comment]
/triage accepted

An alternative solution would be to introduce a flag to force a node-build even when the node image exists in docker hub. Any images built with KIND v0.19.0 - the latest version as of writing - are compatible with the way CAPD sets up node images and are passing conformance tests.

**Comment by sbueringer** [comment]
Thank you very very much for triaging this, really great work!!

For me it would be fine to be only compatible with the upcoming kind v0.20 images (after the release).

**Comment by sbueringer** [comment]
@killianmuldoon One question I assume when we set the new options we are not compatible with the old images anymore?

**Comment by killianmuldoon** [comment]
>One question, I assume when we set the flags for the new images we are not compatible with the old images anymore?

This is true for the `cgroupNS` private flag because of the changes in the entrypoint script. I think the other changes can be decoupled, but they may be redundant for existing images.

**Comment by BenTheElder** [comment]
> This issue emerged first with kindest/node:v1.27.2 which is currently the only image built with the changes in KIND. It causes Kubernetes conformance tests to fail as the test tools aren't able to exec correctly in the node Docker container.

First thing: please use digest pinned images to avoid issues like this + increase your security, at least until such a time as we migrate to an immutable scheme secured on registry.k8s.io (where there's more tooling in place to restrict image pushes, enforce immutability etc). (https://kind.sigs.k8s.io/docs/user/quick-start/#creating-a-cluster + release notes talk about this)

> To summarize kindest/node images are now being built with cgroupns: "private", and the entrypoint script for those nodes works under the assumption that it is enabled.

This isn't quite right, the nodes are running with `--cgroupns=private` by default now, though they may already be doing that on some hosts[^1].

I also tested the entrypoint changes with kind v0.19.0, which does not have this change though, we have not dropped the codepaths that permit functioning without it yet and wouldn't immediately, since we know lots of kind users are also using unpinned images etc.

[^1]: the default can be changed in dockerd with a flag and it defaults to private on cgroups v2 hosts in both docker and podman already

**Comment by killianmuldoon** [comment]
>First thing: please use digest pinned images to avoid issues like this

Thanks for highlighting this - I think we've chosen not to do this in the past so far because of the manual work in updating these images in `test-infra` for each release. We should come up with a better solution for this though - I'll open an issue.

>I also tested the entrypoint changes with kind v0.19.0, which does not have this change though, we have not dropped the codepaths that permit functioning without it yet and wouldn't immediately, since we know lots of kind users are also using unpinned images etc.

Interesting - I need to go back and take another look at the changes in the entrypoint script, but what I was seeing was that images build with KIND `v0.19.0` were working fine with the current CAPD setup - `cgroupns` not set, while the new `kindest/node` image for `v1.27.2` was failing in conformance unless `--cgroupns=private` was set.

**Comment by BenTheElder** [comment]
It's totally possible they're not working, but that would be considered a bug. We strive for backwards compatibility wherever possible though the intent is definitely to phase over to cgroupns=private always and eliminate the v1 + host cgroupns entrypoint hackery eventually.
