### ISSUE TITLE
Possible to delete the Machine object of a 1 control-plane cluster

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/cluster-api#8793]
### What steps did you take and what happened?

1. Followed the steps to create a CAPD cluster https://cluster-api.sigs.k8s.io/user/quick-start.html

```
export CLUSTER_TOPOLOGY=true
clusterctl init --infrastructure docker

export SERVICE_CIDR=["10.96.0.0/12"]
export POD_CIDR=["192.168.0.0/16"]
export SERVICE_DOMAIN="k8s.test"
clusterctl generate cluster capi-quickstart --flavor development \
  --kubernetes-version v1.27.0 \
  --control-plane-machine-count=1 \
  --worker-machine-count=1 \
  > capi-quickstart.yaml
kubectl apply -f capi-quickstart.yaml
```

2. Wait for all machines to be running:
```
$ kubectl get machines
NAME                                                CLUSTER           NODENAME                                            PROVIDERID                                                     PHASE     AGE   VERSION
capi-quickstart-glnkk-bfl62                         capi-quickstart   capi-quickstart-glnkk-bfl62                         docker:////capi-quickstart-glnkk-bfl62                         Running   85s   v1.27.0
capi-quickstart-md-0-lldm9-86d96bfbd4xb4jwp-fhk9j   capi-quickstart   capi-quickstart-md-0-lldm9-86d96bfbd4xb4jwp-fhk9j   docker:////capi-quickstart-md-0-lldm9-86d96bfbd4xb4jwp-fhk9j   Running   87s   v1.27.0
```

3. Delete the Machine object for the control-plane, making the workload cluster inaccessible 

```
$ kubectl delete machine capi-quickstart-glnkk-bfl62
machine.cluster.x-k8s.io "capi-quickstart-glnkk-bfl62" deleted
```

4. A new control-plane Node can't get created
```
$ kubectl get machines
NAME                                                CLUSTER           NODENAME                                            PROVIDERID                                                     PHASE     AGE     VERSION
capi-quickstart-glnkk-8h4w8                         capi-quickstart                                                                                                                      Pending   53s     v1.27.0
capi-quickstart-md-0-lldm9-86d96bfbd4xb4jwp-fhk9j   capi-quickstart   capi-quickstart-md-0-lldm9-86d96bfbd4xb4jwp-fhk9j   docker:////capi-quickstart-md-0-lldm9-86d96bfbd4xb4jwp-fhk9j   Running   2m44s   v1.27.0
```

5. The cluster cannot be deleted

```
kubectl delete cluster capi-quickstart
```

### What did you expect to happen?

It should not be possible to delete the control-plane Machine object of a single control-plane Node cluster.
Or similar to the upgrade logic, a new Machine object should be created before deleting the existing control-plane Machine object.

### Cluster API version

```
$ clusterctl version -o yaml
clusterctl:
  buildDate: "2023-05-02T15:27:48Z"
  compiler: gc
  gitCommit: 7b92ce4577e36adf013dc1dfd2b239fde4c36bc4
  gitTreeState: clean
  gitVersion: v1.4.2
  goVersion: go1.19.6
  major: "1"
  minor: "4"
  platform: darwin/amd64
```

### Kubernetes version

v1.27.0

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by killianmuldoon** [comment]
Is this more of a UX footgun or is there some use case for deleting the single control plane node?

I think this could be conceivably blocked in the webhook, but users could still delete many objects that would break their cluster. The base recommendation in CAPI is not to delete any of the objects underlying the cluster unless they really know what they're doing. The basic flow is to instead delete the cluster as a whole.

**Comment by dkoshkin** [comment]
More of a footgun, I totally understand that deleting different resources could lead to surprising results. But I opened the ticket because the risk of totally breaking the cluster AND then not being able to delete it.

**Comment by killianmuldoon** [comment]
Yeah - that's a fair point. I think this is something we should potentially fix - maybe related to https://github.com/kubernetes-sigs/cluster-api/issues/7423 which isn't the same problem but is more or less in the same space.

/triage accepted

**Comment by dlipovetsky** [comment]
Let's say I delete a ProvisionedVolume (PV). If the PV has at least one ProvisionedVolumeClaim (PVC) bound to it, the PV controller does nothing when it reconciles the delete.

In the same way, I think the Machine controller could check if the Machine is "bound," e.g., to a control plane.

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

As per the discussion above, there is not a good way to draw a line between safeguards to be implemented in the code, give admins full powers, and what instead must be achieved by defining different RBAC roles for different personas

/close
