### ISSUE TITLE
Consider pinning kind images to a sha

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#8815]
We currently set KIND image versions either by their tag or using logic to retrieve the latest stable image for a certain minor release of Kubernetes. This is against KIND's guidelines [as outlined in the release notes](https://github.com/kubernetes-sigs/kind/releases/tag/v0.19.0):

> New node images have been built for KIND v0.19.0, please use these exact images (IE like kindest/node:v1.26.3@sha256: 61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f including the digest) or build your own as we may need to change the image format again in the future sweat_smile

And also in this comment from @BenTheElder https://github.com/kubernetes-sigs/cluster-api/issues/8788#issuecomment-1579393630

We should consider pinning the images we use from KIND. Currently we set the version in a few places:

1) The default image tag [used in CAPD](https://github.com/kubernetes-sigs/cluster-api/blob/7b3f2136e0a1cb6230e2d89a44dfb5decb0c4b2f/test/infrastructure/docker/internal/docker/machine.go#L54) and the [e2e test KIND provider](https://github.com/kubernetes-sigs/cluster-api/blob/811079b63fd52efd250f32a3480877ceeb3ab0f2/test/framework/bootstrap/kind_provider.go#L40)
2) When [resolving the version for upgrade tests](https://github.com/kubernetes-sigs/cluster-api/blob/d64fd48b0d4144a8b29c728fde917bf75a10489f/scripts/ci-e2e.sh#L40)
3) When resolving the version for images in CAPD.

(I may have missed some other places)

We could solve (1) fairly easily by just pinning the tag to a known `kindest/node` release with the relevant sha.

For (2) and (3), though we'd need a source of truth - just a yaml file or similar - with a list of Kubernetes versions linked to the current KIND release. This would need to be updated at least for every KIND release and likely Kubernetes release (when a `kindest/node` image gets published. I'm not sure if the images have any other markers or labels we could use to distinguish this.

For the e2e tests when we don't have an images for the latest version of Kuberntes available it can be built on the fly. This will make upgrade tests take longer and use more CPU etc., but these tests only run once a day so they're not that intensive.

For resolving images for CAPD we would probably need to return good errors / warnings so users know that some images that may have worked in the passed will no longer be used by CAPI e.g. after upgrading to KIND v0.20.0 there may not be a recommended v1.27.0 image.

We can tackle all three of these problems separately, as they're decoupled. The only one which has hard tradeoffs IMO is (3) so it would be good to hear more opinions on ways to deal with it.

Ref: https://github.com/kubernetes-sigs/cluster-api/issues/8788

**Comment by fabriziopandini** [comment]
/triage accepted

If it is required to make us compliant with kind recommendations, I'm +1
I'm happy to pair in brainstorming possible solutions

**Comment by sbueringer** [comment]
For 2 I would prefer to always build ourselves. Except there is a low maintenance way to automatically use compatible images or build ourselves.

I wonder how this will affect CAPD users (quick start). Would they have to specify the version with Sha? Or would we have an allow list with Kubernetes versions that we automatically map to hardcoded Shas? I think it's tricky as we still want to make sure self-build images work as well

**Comment by killianmuldoon** [comment]
>I wonder how this will affect CAPD users (quick start). Would they have to specify the version with Sha? Or would we have an allow list with Kubernetes versions that we automatically map to hardcoded Shas? I think it's tricky as we still want to make sure self-build images work as well

I think mapping versions -> known SHAs is the only real way for us to do this. The easiest way to do so is to keep an updated list in the repo, but it requires some manual effort - mostly the KIND bump + when using a new version of Kubernetes. 

I'm also fine with making the e2e tests always-build. We should enable pinning images by sha at the same time though - some logic like if it has a SHA use it, if not always build - so we can speed up upgrade tests running locally etc.

**Comment by killianmuldoon** [comment]
/assign

I'd like to get this done ahead of the KIND v0.20.0 release so we don't have to deal with the issues described in #6264 until we update.

Basic approach:
1) Add a SHA to the default kind image used in CAPD / e2e
2) Always build images for upgrade tests, unless they specify a SHA.

We can treat automatically resolving known-good images as a follow up as it's not completely essential here. It may begin to impact CAPD users soon though.

**Comment by killianmuldoon** [comment]
/close

The following were done to resolve this issue:
1) Add always build to K8s upgrade tests: https://github.com/kubernetes-sigs/cluster-api/pull/8859
2) Add a `KindMapper` in CAPD which always tries to resolve a Kind version to a specific sha: https://github.com/kubernetes-sigs/cluster-api/pull/8880
3) Pin templates in older versions of Cluster API to the relevant shas for e2e tests: https://github.com/kubernetes-sigs/cluster-api/pull/8860

Going forward the list of KIND shas will need to be updated with each new KIND release so that we're normally using the latest images available. We might be able to find some way to automate this in future.

**Comment by fabriziopandini** [comment]
@killianmuldoon kudos for all the hard work here, this is keeping the light on for the next release
