### ISSUE TITLE
Timed out waiting for all machines to be exist

### ISSUE THREAD

**Issue by adilGhaffarDev** [kubernetes-sigs/cluster-api#8824]
### Which jobs are flaking?

- periodic-cluster-api-e2e-mink8s-release-1-3
- periodic-cluster-api-e2e-main
- periodic-cluster-api-e2e-release-1-4

e.g. https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-release-1-3/1666214582626029568

### Which tests are flaking?

-  When testing clusterctl upgrades (v1.x=>current) Should create a management cluster and then upgrade all the providers

### Since when has it been flaking?

Minor flakes since 04-06-2023

### Testgrid link

https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*&xjob=.*-provider-.*#2822326a66dd24850a9d

### Reason for failure (if possible)

To be analyzed.

### Label(s) to be applied

/kind flake

**Comment by chrischdi** [comment]
I'll gonna try to take a look into this

/assign

Persistent triage link https://storage.googleapis.com/k8s-triage/index.html?date=2023-07-13&job=.*-cluster-api-.*&xjob=.*-provider-.*#a20c32c92add5bfec5f5

**Comment by sbueringer** [comment]
Just looked at one of the cases. I think there's a realistic chance this is the same issue as here: https://github.com/kubernetes-sigs/cluster-api/issues/8786#issuecomment-1584332219

(can be verified by looking for preflight errors in the MachineSet and then checking if KCP has a status version)

**Comment by chrischdi** [comment]
> I'll gonna try to take a look into this
> 
> /assign
> 
> Persistent triage link https://storage.googleapis.com/k8s-triage/index.html?date=2023-07-13&job=.*-cluster-api-.*&xjob=.*-provider-.*#a20c32c92add5bfec5f5

The one I linked here matches 100% to what was described in https://github.com/kubernetes-sigs/cluster-api/issues/8786#issuecomment-1584332219

**Comment by chrischdi** [comment]
Note: this could be a different issue compared to #8786, the above linked query may lead to different issues.

Analysing the prowjob linked at the first post:

It looks like the control plane container is not able to start and CAPD reports cloud init does not work:

CAPD log:
```
E0606 23:24:39.841361       1 controller.go:326] "Reconciler error" err="failed to exec DockerMachine bootstrap: failed to run cloud config: stdout:  stderr: : error creating container exec: Error response from daemon: Container b787bae2a0df7cd9272a1ebc84209e448f9ce2e34131d3aa673c47202cdf7943 is not running" controller="dockermachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="DockerMachine" dockerMachine="clusterctl-upgrade/clusterctl-upgrade-oh686r-control-plane-rs4c7" namespace="clusterctl-upgrade" name="clusterctl-upgrade-oh686r-control-plane-rs4c7" reconcileID=4d7ed318-faad-44f8-a7dd-0b2a07851588
```

Docker log
```
time="2023-06-06T23:24:39.058365704Z" level=error msg="b787bae2a0df7cd9272a1ebc84209e448f9ce2e34131d3aa673c47202cdf7943 cleanup: failed to delete container from containerd: no such container"
time="2023-06-06T23:24:39.058475121Z" level=error msg="Handler for POST /v1.41/containers/b787bae2a0df7cd9272a1ebc84209e448f9ce2e34131d3aa673c47202cdf7943/start returned error: driver failed programming external connectivity on endpoint clusterctl-upgrade-oh686r-control-plane-6hdqw (637e7efe77a6abeb44ff037b39458562423c693c10f122156d32be2fc9081eda): Bind for 127.0.0.1:33369 failed: port is already allocated"
```

Updated link from the first comment: https://storage.googleapis.com/k8s-triage/index.html?date=2023-06-10&job=.*-cluster-api-.*&xjob=.*-provider-.*#2822326a66dd24850a9d

Additional more flexible query to find the issue independent of the query id: 
https://storage.googleapis.com/k8s-triage/index.html?text=Timed%20out%20waiting%20for%20all%20machines%20to%20be%20exist&job=.*-cluster-api-.*&xjob=.*-provider-.*

**Comment by chrischdi** [comment]
So this issue here is:
* CAPD node container for ControlPlane node tries to get started, but the pod it tires to use is already in-use
* Because of that the container for the node cannot be created.

**Comment by sbueringer** [comment]
> but the pod

I assume port?

Ah interesting. Am I seeing correctly that we hand over 0 as a host port to docker? https://github.com/kubernetes-sigs/cluster-api/blob/7a4e06c91d125164003272b40ffd6bb057b90668/test/infrastructure/docker/internal/docker/manager.go#L67

This would suggest that Docker itself should pick a random port (?) (maybe I'm looking at the wrong code)

**Comment by sbueringer** [comment]
Assuming I'm looking at the right code. I wonder if should just implement a retry and be done with it :) (+ surface it in logs that we're retrying)

**Comment by chrischdi** [comment]
> failed to exec DockerMachine bootstrap

Simple requeue won't help. The container needs to get removed too.

**Comment by chrischdi** [comment]
A simple requeue is not enough in this case. We also have to delete the container.

Sidenote reproducible via:

```
$ docker create --name foo -p 31333:8080 golang:1.20.6 tail -f /dev/null
$ docker create --name bar -p 31333:8080 golang:1.20.6 tail -f /dev/null
$ docker start foo
$ docker start bar
Error response from daemon: driver failed programming external connectivity on endpoint bar (6277eb12151633aff6a016eefa0c328c4c596831d1abda8d41751c14d114a778): Bind for 0.0.0.0:31333 failed: port is already allocated
Error: failed to start containers: bar
```

**Comment by killianmuldoon** [comment]
/reopen

To assess if this has fixed the underlying flakes and to track the cherry-picks:
https://github.com/kubernetes-sigs/cluster-api/pull/9131
https://github.com/kubernetes-sigs/cluster-api/pull/9130

**Comment by chrischdi** [comment]
[Link](https://storage.googleapis.com/k8s-triage/index.html?text=Timed%20out%20waiting%20for%20all%20machines%20to%20be%20exist&job=.*-cluster-api-.*main&xjob=.*-provider-.*) to check if issue still exists on main (because cherry-picks will only get merged after)

We're currently free of the issue since [06/08/2023, 02:37:28 UTC](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-dualstack-and-ipv6-main/1688015777170460672)

**Comment by chrischdi** [comment]
Note: after merging the cherry-picks: we should also cherry-pick #9139 on top.

**Comment by killianmuldoon** [comment]
I think we can close this now - if the same issue pops up we can take another look, but this error message is the result of a number of different possible underlying errors.

Thanks again for fixing this @chrischdi!

/close

**Comment by chrischdi** [comment]
There was only one occurence of this flake at `16/08/2023, 05:25:47` [xref](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1691651831593177088).

However, the issue here occurred during the upgrade clusterctl upgrade tests when CAPI v1.0.5 was running.

So there was no occurency since merging the fix.

Also the cherry-picks got merged now:

- #9130
- #9131
- #9243
- #9242

/close
