### ISSUE TITLE
Set higher priority to machines with machine-delete annotation while scaling down a machine deployment

### ISSUE THREAD

**Issue by xiaosuiba** [kubernetes-sigs/cluster-api#8829]
### What would you like to be added (User Story)?

As an operator, I would like to delete a specific Machine from a MachineDeployment even if there are some 'failed' or 'unhealthy' machines exist.

### Detailed Description

Currently if someone wants to delete a Machine from a MachineDeployment, he can add a `cluster.x-k8s.io/delete-machine` annotation to the Machine  and then scale down the MachineDeployment by 1. It works if all the Machines are in healthy states. But if there're some `failed` or `unhealthy` Machines exist, which machine will be deleted is unpredictable while scaling down the MachineDeployment, because a Machine with  `cluster.x-k8s.io/delete-machine`  annotation has same delete priority with the `failed` or `unhealthy` Machine. 
Can we grant higher priority to Machines with `cluster.x-k8s.io/delete-machine`  annotation while scaling down a MachineDeployment, or there're some other ways to do it?

### Label(s) to be applied

/kind feature

**Comment by enxebre** [comment]
I think giving higher prio to the explicit annotation might be reasonable. But also I'm generally concerned about overusing this annotation and consuming machine scalable resources as pets.
Can you elaborate on your particular use case, e.g. why don't just sent a targeted delete request to that Machine?

/triage accepted

**Comment by xiaosuiba** [comment]
> I think giving higher prio to the explicit annotation might be reasonable. But also I'm generally concerned about overusing this annotation and consuming machine scalable resources as pets. Can you elaborate on your particular use case, e.g. why don't just sent a targeted delete request to that Machine?
> 
> /triage accepted

I'm building a KaaS service with cluster-api. Some times our customer wants to delete a specific nodes and the iaas resources related(VM, network). As the Machines were controlled by a MachineDeployment, a new Machine will be created if I simply delete the target Machine which is not the behavior our customer want.

**Comment by enxebre** [comment]
I see, thanks! what's the specific motivation for the end user to target a specific node rather than just scale down compute and let workloads to accommodate? How deleting unhealthy/doomed Machines interferes with that motivation?

**Comment by fabriziopandini** [comment]
/close

due to lack of updates - answer to need/information in the last 6 months.
we can eventually re-open or create a new issue if new info becomes available
