### ISSUE TITLE
Optimize reconcileInterruptibleNodeLabel 

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#8848]
### What would you like to be added (User Story)?

As an operator I want CAPI to work well at scale

### Detailed Description

During the Machine controller reconcile loop, `reconcileInterruptibleNodeLabel` is doing the same `external.Get` call done `reconcileInfrastructure` for reading the infraMachine.

However, reading infraMachine is read using unstructured, which is not cached, so it can impact performance at scale by impacting the API server in the management cluster,  deducting space from the available client rate limit/burst etc.

We should consider refactoring `reconcileInterruptibleNodeLabel` so it re-use the object read in `reconcileInfrastructure`, or as alternative option make `reconcileInterruptibleNodeLabel` a sub-step of `reconcileInfrastructure`refactoring

### Label(s) to be applied

/kind feature
/area machine

**Comment by sbueringer** [comment]
I talked with Yuvaraj about it and he has time to take over this issue
/assign @ykakarap

**Comment by sbueringer** [comment]
/close

implemented via https://github.com/kubernetes-sigs/cluster-api/pull/8852
