### ISSUE TITLE
Use cache for GetConfigOwner in CABPK

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#8849]
### What would you like to be added (User Story)?

As an operator I want CAPI to work well at scale

### Detailed Description

GetConfigOwner in CABPK is reading Machine or MachinePool using unstructured, which is not cached, so it can impact performance at scale by impacting the API server in the management cluster, deducting space from the available client rate limit/burst etc.

We should consider using typed Machine or MachinePool reads instead.

### Anything else you would like to add?

`GetConfigOwner` is a public util so we should make a small investigation about usage first, make sure the change to a cached read is not impacting those use cases (including CABPK as well), and announce the change as a breaking change or implement an alternative func for `GetCachedConfigOwner`

### Label(s) to be applied

/kind feature
/area bootstrap

**Comment by sbueringer** [comment]
/triage accepted

Would be a huge improvement assuming CABPK is okay with potentially dealing with a stale object

**Comment by nojnhuh** [comment]
I can take a look at this one.
/assign

**Comment by fabriziopandini** [comment]
NOTE: I have checked the usage of the config owner, and it seems that it is ok for CABPK to use a cached client.

Most specifically,
- we are reading mostly kind, name and control plane labels (all of them do not/should not change)
- we are reading DataSecrect name but only to restore the state after pivot 
- we are reading the Kubernetes version while deciding which format to use when creating kubeadm config files (which should be ok, because in case of minor version upgrade including an API bump + stale read the old API format should still be supported due to how deprecation rules work)
