### ISSUE TITLE
Consider using remote.NodeProviderIDIndex in MachinePool controller

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#8856]
The MachinePool controller currently looks for specific node references by first looping through all of the nodes in the cluster and then checking to see if the ProviderID is among those listed on the MachinePool object. 
This could be made more efficient by using the `remote.NodeProviderIDIndex` which is how the Machine controller currently looks up nodes by provider ID.

Doing this would require refactoring the code in the MachinePool controller's `getNodeReferences`: 
https://github.com/kubernetes-sigs/cluster-api/blob/051b00606dfacd61fbff687155e485040c1b0461/exp/internal/controllers/machinepool_controller_noderef.go#L155

To look more like the Machine  controller implementation and use `index.NodeProviderIDField`
https://github.com/kubernetes-sigs/cluster-api/blob/f62294e25eb37f3eccb74a854ea9fee0ce35541d/internal/controllers/machine/machine_controller_noderef.go#L196

/help-wanted
/area machinepool

**Comment by fabriziopandini** [comment]
/triage accepted
cc @Jont828 since he is working on MachinePools

**Comment by Jont828** [comment]
That seems reasonable. I'll take a look once I'm wrapped up with the DockerMachinePool Machines implementation.

**Comment by cahillsf** [comment]
opened a PR for this, per @sbueringer closing this as "won't do"

/close

**Comment by sbueringer** [comment]
Thx for working on this! Sorry should have realized this earlier :)

**Comment by cahillsf** [comment]
> Thx for working on this! Sorry should have realized this earlier :)

np 👍
