### ISSUE TITLE
Improve the way to specify E2E test specific variables

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#8857]
**Description**:

Today we do not have a generic way to specify E2E test specific variables. The tests currently use unique names for variables that are used by individual E2E tests.

Examples:
```
KUBERNETES_VERSION_UPGRADE_FROM: "v1.26.4"
KUBERNETES_VERSION_UPGRADE_TO: "v1.27.1"

AUTOSCALER_WORKLOAD: "./data/autoscaler/autoscaler-to-workload-workload.yaml"

CAPI_SCALE_CLUSTER_COUNT: "10"
```

This issue is to explore ways to find a generic way to specify variable values for a specific tests instead of creating different variable names.

Ref: https://github.com/kubernetes-sigs/cluster-api/pull/8833#discussion_r1229548224

/area e2e-testing

**Comment by fabriziopandini** [comment]
Note: the test framework already supports something similar for timeouts; if I remember well the syntax is <default or specname>/<timeout-name>: <value>

**Comment by fabriziopandini** [comment]
/close
It is becoming a practice to have dedicated E2E config files for each test (copying the default config + customizing some variable). see e.g. https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2662

We can eventually reconsider if more specific requires pops up
