### ISSUE TITLE
File provisioning for Workload clusters

### ISSUE THREAD

**Issue by Sir-gits-a-lot** [kubernetes-sigs/cluster-api#8885]
Is there an option in CAPI to provision files to the nodes of the Workload cluster after they are provisioned? Kind of like what we have in Terraform where we can use null resource with ssh and file provisioner to have some files placed inside the nodes once they are launched by Terraform.
I am trying to find some equivalent in CAPI. If anybody knows, please let me know.

**Comment by killianmuldoon** [comment]
/kind support
/triage accepted


>I'm not sure about your end-to-end use case, but you can load files in the KubeadmConfig if you're using the Kubeadm Bootstrap Provider. These files can be appened in spec.files. [You can read more about this in the CAPI book](https://cluster-api.sigs.k8s.io/tasks/bootstrap/kubeadm-bootstrap.html#additional-features).

**Comment by Sir-gits-a-lot** [comment]
I was trying this https://cluster-api.sigs.k8s.io/tasks/bootstrap/kubeadm-bootstrap.html#additional-features thing out. Facing issue which I am not able to resolve. 

This is the error message it says:-
The KubeadmConfigTemplate "quick-start-default-worker-bootstraptemplate" is invalid: spec.template.spec.files[1].path: Invalid value: v1beta1.File{Path:"/etc/kubernetes/cloud.json", Owner:"root:root", Permissions:"0644", Encoding:"", Append:false, Content:"{\n  \"cloud\": \"CustomCloud\"\n}\n", ContentFrom:(*v1beta1.FileSource)(nil)}: path property must be unique among all files.

Any chance you might know the reason for this error, please let me know.

I am attaching the full kubeadmconfigtemplate object and the error snap as it was received for reference.

![image](https://github.com/kubernetes-sigs/cluster-api/assets/85702060/77d2f87d-75f1-4d62-8794-1290bf4054f9)
![image](https://github.com/kubernetes-sigs/cluster-api/assets/85702060/f986c338-907d-410a-8428-408671c07aa3)

**Comment by Sir-gits-a-lot** [comment]
> CAPI treats machines as immutable, so there is no way to provide additional files on existing machines using CAPI (the bootstrap providers only act at bootstrap).

I wanted to discuss 1 thing, if CAPI is actually based on K8s principle and we are extending k8s to manage machines (nodes/EC2 instances/Servers/docker containers in case of CAPD) then shouldn't CAPI also have something like clusterctl exec machine -it NODENAME cmd, because that will actually align to k8s principle of Day 2 configuration. 

Like when we call K8s as an Orchestrator of containers, they provided kubectl exec -it pod_name cmd, right? They didn't just provide K8s as a tool to launch certain pods and self-healing of those pods. 

If we develop something like an exec command to enter the machine be it docker container or an EC2 instance, it'll make the machines mutable and that'll be very beneficial use-case for CAPI in real-life use case.

Because you see, nobody can determine that I would need this configuration(files, shell scripts, applications) on my nodes coz it'll change with time. So, if CAPI says please plan beforehand to bootstrap the machines with all the required files and configurations and if you want any change afterwards, please use Config. Management Tools like Chef, Puppet, Ansible to do that, it'll actually be limiting CAPI's Capabilities. 

If you find my idea to be of any value, please reply, I would want to work in this front as I think this'll make CAPI a true one-stop solution for eve'thing K8s related.

**Comment by fabriziopandini** [comment]
> Any chance you might know the reason for this error, please let me know

You are adding twice the same file (a file with the same path)

> Like when we call K8s as an Orchestrator of containers, they provided kubectl exec -it pod_name cmd, right? They didn't just provide K8s as a tool to launch certain pods and self-healing of those pods.

I would say that the devil is in the definition of day 2 operations.
Personally, and I know this is controversial, I think that every time you have to exec in a pod or in the machine is a failure of your observability stack, and that using exec for troubleshooting is something that doesn't scale well. Also, making changes live is a high risk, because it is insecure, not reproducible, etc. so it should be the last resort in every operational book. 

But I understand that sometimes a backdoor can be handy, and when it comes to "machine exec" the reality is that every infrastructure has different solutions to allow people to access machines; it could be plain ssh, ssh via a bastion host, tunnels, or something specific to a single cloud provider (often there are many solutions for each cloud provider). But overall solutions for this issue already exists and AFAIK there is not yet widespread demand / widespread consensus / critical mass of volunteers to develop in CAPI a wrapper over those solutions.

But that's my humble personal opinion, feel free to bring up the topic during the CAPI office hours

**Comment by Sir-gits-a-lot** [comment]
In the spec.files of the kubeadmconfig template. I have experimented and successfully able to provision file into the Workload cluster but it has option of specifying the content of the file either inline or secret reference. 

How can I have a file that is present locally in my Management Cluster provisioned into the Workload cluster?

**Comment by fabriziopandini** [comment]
CAPK packages your files in the cloud-init script that the infrastructure provider will use to bootstrap the machine

**Comment by Sir-gits-a-lot** [comment]
Actually I am not able to understand the syntax of the spec.files so that I can specify a location in the management cluster where my files (shell scripts) are stored and then provision them in the Workload cluster.

I have successfully used the contentFrom syntax to specify the contents of the file and provision it but my problem is what if the content becomes too long or if I have multiple files to provision, I cannot specify all that in kubeadmconfig template, right?

Can you help me with the syntax?

**Comment by fabriziopandini** [comment]
It is up to you.
If you don't want to put all your data inline in the KubeadmConfig object you can put your files in secrets created in the same namespace of the KubeadmConfig.

Then you have to use file.contentFrom.secret and provide the name of the secret and the name of the key inside of the secret data field where the file content is stored

**Comment by Sir-gits-a-lot** [comment]
Is there an option in which I can mention list of files in a directory in the management cluster to be provisioned in the Workload cluster?

Like the files are ready with the content, in the kubeadmconfig I just want to mention the location of the file for the Bootstrap provider to fetch from.

**Comment by Sir-gits-a-lot** [comment]
I have tried the kubeadmconfigtemplate resource for provisioning files on worker nodes of workload cluster, but my requirement is to provision files on the control plane machine of workload cluster and also possible install some applications using apt, how can I do that? Is there a way in CAPI I can achieve the use case. 
I tried adding the spec.file in the KubeadmControlPlaneTemplate of controlplane.cluster.x-k8s.io/v1beta1, it seems to apply smoothly but doesn't work. I mean the file are not provisioned in the control plane machine. 

If anybody knows about this, any help will be appreciated. Thanks.

**Comment by killianmuldoon** [comment]
/triage needs-information

>I tried adding the spec.file in the KubeadmControlPlaneTemplate of controlplane.cluster.x-k8s.io/v1beta1, it seems to apply smoothly but doesn't work. I mean the file are not provisioned in the control plane machine.

**Comment by Sir-gits-a-lot** [comment]
Sure, my requirement is to provision some files in Control plane machine of the workload cluster. 
I am using CAPD for all the experimentation. 
So, I thought just like we use the spec.file of the kubeadmconfigtemplate to achieve similar result in worker nodes of the workload cluster. I can do that for control plane nodes also. 
So, I added the files section in KubeadmControlPlaneTemplate. The yaml manifest got applied w/o any errors but the effect wasn't visible in the workload cluster when it came up. Like, when I exec into the control plane container of the workload cluster, the files that I mentioned in spec.files wasn't actually provisoned.
kind: KubeadmControlPlaneTemplate
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: quick-start-control-plane
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          controllerManager:
            extraArgs: { enable-hostpath-provisioner: "true" }
          apiServer:
            # host.docker.internal is required by kubetest when running on MacOS because of the way ports are proxied.
            certSANs: [localhost, 127.0.0.1, 0.0.0.0, host.docker.internal]
        files:
        - path: /etc/kubernetes/cloud.json
           owner: "root:root"
           permissions: "0644"
           content: |
             {
               "cloud": "CustomCloud"
             }

**Comment by Sir-gits-a-lot** [comment]
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: quick-start-default-worker-bootstraptemplate
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          criSocket: 'unix:///var/run/containerd/containerd.sock'
          kubeletExtraArgs:
            eviction-hard: 'nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%'
      files:
        - path: /etc/kubernetes/cloud.json
          owner: 'root:root'
          permissions: '0644'
          content: |
            {
              "cloud": "CustomCloud"
            }
        - path: /etc/kubernetes/ansible.sh
          owner: 'root:root'
          permissions: '0644'
          content: |
            #!/bin/bash
            apt update
            apt install software-properties-common
            apt-add-repository --yes --update ppa:ansible/ansible
            apt update
            apt install ansible
            ansible --version
      postKubeadmCommands:
        - sh /etc/kubernetes/ansible.sh
        - >-
          echo "successfully provisioned ansible installation shell script and
          triggered it to install ansible" >/var/log/ansible_installation.log
---
kind: KubeadmControlPlaneTemplate
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: quick-start-control-plane
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          controllerManager:
            extraArgs: { enable-hostpath-provisioner: "true" }
          apiServer:
            # host.docker.internal is required by kubetest when running on MacOS because of the way ports are proxied.
            certSANs: [localhost, 127.0.0.1, 0.0.0.0, host.docker.internal]
        files:
         - path: /etc/kubernetes/cloud.json
           owner: "root:root"
           permissions: "0644"
           content: |
              {
               "cloud": "CustomCloud"
              }
         - path: /etc/kubernetes/ansible.sh
           owner: "root:root"
           permissions: "0644"
           content: |
             #!/bin/bash
              apt update
              apt install software-properties-common
              apt-add-repository --yes --update ppa:ansible/ansible
              apt update
              apt install ansible
              ansible --version
        postKubeadmCommands:
          - sh /etc/kubernetes/ansible.sh
          - echo "successfully provisioned ansible installation shell script and triggered it to install ansible" >/var/log/ansible_installation.log
        initConfiguration:
          nodeRegistration:
            # We have to set the criSocket to containerd as kubeadm defaults to docker runtime if both containerd and docker sockets are found
            criSocket: unix:///var/run/containerd/containerd.sock
            kubeletExtraArgs:
              eviction-hard: "nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%"
        joinConfiguration:
          nodeRegistration:
            # We have to set the criSocket to containerd as kubeadm defaults to docker runtime if both containerd and docker sockets are found
            criSocket: unix:///var/run/containerd/containerd.sock
            kubeletExtraArgs:
              eviction-hard: "nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%"`

**Comment by sbueringer** [comment]
Sorry this is simply not readable.
I meant something like this:
```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: capi-quickstart-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
        - localhost
        - 127.0.0.1
        - 0.0.0.0
        - host.docker.internal
```

**Comment by Sir-gits-a-lot** [comment]
![image](https://github.com/kubernetes-sigs/cluster-api/assets/85702060/52cbd5ec-1538-4938-939e-bfef71be435f)

Here, I am attaching an image, this will give you an idea of how my KubeadmControlPlaneTemplate looks like. 

My idea was to use spec.files just like we use for worker nodes in kubeadmconfigtemplate in control node. It applies also but the result is not seen.

**Comment by fabriziopandini** [comment]
/close

due to a lack of updates last 6 months.
we can eventually re-open or create a new issue if new info becomes available
