### ISSUE TITLE
GCP support for RHEL images

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#89]
_From @rsdcastro on February 12, 2018 18:17_

See #593 for reference.

_Copied from original issue: kubernetes/kube-deploy#594_

**Comment by rsdcastro** [comment]
Turning this into a GCP specific issue, as there's no current infrastructure or plans to have a more general Ubuntu support that works across providers.

cc @mkjelland @krousey @kcoronado

**Comment by roberthbailey** [comment]
This issue was moved to kubernetes-sigs/cluster-api-provider-gcp#14
