### ISSUE TITLE
Automate setting of KubeletExtraArgs for CAPD when using ignition

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#8907]
### What would you like to be added (User Story)?

As a user, I would like to use CAPD with ignition without taking care of different settings for the target kindest/node image

### Detailed Description

This issue is about using the kind mapper introduced by https://github.com/kubernetes-sigs/cluster-api/pull/8880, and use it to automatically set some parameters in the node registration when starting CAPD images with ignition, so the kindest/node image are started as expected.

cc @invidian @johananl 

### Anything else you would like to add?

As a reference, you can look at https://github.com/kubernetes-sigs/cluster-api/pull/8881 which solved the same problem for cloud init on CAPD.

### Label(s) to be applied

/kind feature
/area bootstrap

/triage accepted

**Comment by invidian** [comment]
Suggestion how to address this: https://github.com/kubernetes-sigs/cluster-api/pull/8881#discussion_r1239728991.
