### ISSUE TITLE
"no new finalizers" error in rapidly deleted clusters....

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api#8946]
@ykakarap helped us (me and @shivaani0505) mostly to figure this out, this is my attempt at a writeup/root cause  explanation, TLDR fast cluster deletions, finalizers, and patching can get into a race condition, but am not 100% sure about what type of patching resulted in this, bc we've done different experiments on this cluster.... 

### What steps did you take and what happened?

If you make a broken JSON Patch in a CAPI Cluster on creation and rapidly try to delete it, then
there is a race condtion where you get  finalizers that cannot be created.

```
 "Reconciler error" err="Cluster.cluster.x-k8s.io \"sgcluster\" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{\"cluster.cluster.x-k8s.io\"}" controller="cluster" controllerGroup="cluster.x-k8s.io"       controllerKind="Cluster" Cluster="default/sgcluster" namespace="default" name="sgcluster" reconcileID=286c4ac9-5243-4dc3-8fd9-f6ea806ba4cc
```

This results in situations like this:

```
  NAME         NAMESPACE  STATUS    CONTROLPLANE  WORKERS  KUBERNETES        ROLES                                   
  sgcluster    default    deleting                0/0                        <none>    ************
```

Which last forever... 

### What did you expect to happen?

Rapidly deleting clusters would be allowed even if cluster is unhealthy.

### Cluster API version

1.4.2

### Kubernetes version

1.24

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by jayunit100** [comment]
cc @ykakarap thanks for helping me root cause this one

**Comment by ykakarap** [comment]
Discussed with @shivaani0505. CAPI controllers are behaving as expected and the observed issue is a side affect of other operators on the cluster not related to CAPI.

/close

**Comment by sbueringer** [comment]
PR to ensure we only add the finalizer when we actually can (i.e. when the deletionTimestamp is not set: https://github.com/kubernetes-sigs/cluster-api/pull/8949)
