### ISSUE TITLE
MachinePool: MinReadySeconds does not work

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#8952]
### What steps did you take and what happened?

MachinePool has a MinReadySeconds field just like MachineDeployment. In MachinePools however it is not implemented.

### What did you expect to happen?

I would expect it to behave as documented:

```go
	// Minimum number of seconds for which a newly created machine instances should
	// be ready.
	// Defaults to 0 (machine instance will be considered available as soon as it
	// is ready)
	// +optional
	MinReadySeconds *int32 `json:"minReadySeconds,omitempty"`
```

### Cluster API version

main

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
(cc @CecileRobertMichon)

**Comment by killianmuldoon** [comment]
/triage accepted

Should we add a note to the field for now to communicate that it's not implemented?

**Comment by sbueringer** [comment]
Sounds like a good idea!

**Comment by enxebre** [comment]
Related tiny one https://github.com/kubernetes-sigs/cluster-api/pull/8956

**Comment by Dhairya-Arora01** [comment]
@sbueringer  will it be implemented somewhere [here](https://github.com/kubernetes-sigs/cluster-api/blob/da10c33159d9e0e156dc351ba26d1c6795fa83b6/exp/internal/controllers/machinepool_controller_noderef.go#L187)

**Comment by sbueringer** [comment]
That is definitely the place where it's "not implemented" today :).

Not sure how it should be implemented, maybe similar to MachineDeployments. I would leave this to folks more familiar with MachinePools

(cc @CecileRobertMichon @Jont828)

**Comment by Dhairya-Arora01** [comment]
hey @CecileRobertMichon @Jont828  should we create a IsNodeAvailable function like [here](https://github.com/kubernetes-sigs/cluster-api/blob/00dbf7b9f6322d7ebd06ae2efa703b23354dd37d/controllers/noderefutil/util.go#L27) and, then use it and refractor the code a bit in [machinepool_controller_noderef.go](https://github.com/kubernetes-sigs/cluster-api/blob/da10c33159d9e0e156dc351ba26d1c6795fa83b6/exp/internal/controllers/machinepool_controller_noderef.go#L186C1-L186C1)

**Comment by Jont828** [comment]
@sbueringer I'd need to poke around a bit to see how we could implement this. 

@Dhairya-Arora01 Would we be able to just call the `IsNodeAvailable` in the MachinePool controller? It seems like that function wouldn't be able to tell if the node was coming from a MachinePool or a MachineDeployment.

**Comment by Dhairya-Arora01** [comment]
@Jont828 yes, you are right. We can use `IsNodeAvailable` in `getNodeReferences` where we pass and additional parameter `minReadySeconds` which would be used in `IsNodeAvailable`
Right?
If its the right approach, I'm happy to assign myself

**Comment by Jont828** [comment]
I think that seems reasonable. I'm making changes to the Docker implementation in #8842, so I think you can implement that once it merges. That way, we can test out your changes with Docker MachinePool Machines.
