### ISSUE TITLE
MachineHealthChecks may leak when created with topology controller

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#8954]
When running scale testing one test resulted in a large number of MachineHealthChecks "leaking" and still being in existence after all clusters were deleted. It appears that some MHCs can be leaked during the deletion flow - at least when CAPI is operating at high scale.

We should investigate this issue and try to fix the underlying leak of these resources.

**Comment by enxebre** [comment]
@killianmuldoon do we have any logs from those tests we could link here for async investigation?

**Comment by killianmuldoon** [comment]
/unassign
/triage needs-information
Haven't been able to recreate this, needs more investigation to catch the leak.
