### ISSUE TITLE
Block PRs without an area label

### ISSUE THREAD

**Issue by g-gaston** [kubernetes-sigs/cluster-api#8967]
### What would you like to be added (User Story)?

As a developer I would like to have have prow block my PRs from being merged if they don't have an `area/*` label so they can be correctly classified in the release notes.

### Detailed Description

The are labels drives the prefix used for each entry in the release notes (KCP, clusterctl, e2e, etc.) Example: https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.4.3

As discussed in office hours, this will help the release team immensely by making authors/reviewers add the area label before PRs are merged. They are the people with the most information about the contents of the PR.

Ideally this should be implemented with prow instead of GitHub Action.

We propose introducing this for the 1.6 release cycle. This ensures there is enough time for folks to give feedback, reach consensus and avoids extra friction at the end of the 1.5 cycle.

### Label(s) to be applied

/kind feature
/area release

**Comment by killianmuldoon** [comment]
/triage accepted

I'd like to hear proposals for a technical solution to this first and then discuss the impact of the specific solution. I'm all for making it more obvious and necessary to add labels to PRs - but I think the level of friction will be in the details of how it's implemented.

**Comment by g-gaston** [comment]
@killianmuldoon 
I haven't fully fledged the solution, I was hoping to leave that for the implementation. I didn't think the implementation mattered as long as it followed the requirement "block PR and tell user to add an area label".

Either way, my idea was to use a combination of the `require-matching-label` prow plugin (which adds a label if some other label is missing and tide configuration with `missingLabels` (which blocks the PR if any of those labels are present).

So add "x" label if a label following `^area/*` is not present and then make tide block the PR if the label "x" is present.

**Comment by fabriziopandini** [comment]
+1 from my side, as per office hour discussion, if there are no objections let's start this work after 1.5 is cut

**Comment by sbueringer** [comment]
Change itself sounds fine to me if it makes writing release notes easier and it's fine for the community.

Implementation idea also sounds good. Overall would be good to have a low-maintenance way of achieven this. @g-gaston's idea sounds perfect.

General question about release note generation.

There seem to be two totally different ways of doing this:
* Cluster API release note generation tool:
  * uses PR icons + titles and now also area labels
* Upstream k/k relase note tool
  * uses kind labels + comments in the PR description

I assume wherever we're going with the relase note generation enforcing area labels will stay useful? (Just asking in case we're now investing time in area labels and the next step is to adopt the upstream tool and stop using area labels.. :))

**Comment by vincepri** [comment]
+1 from me as well, sounds a nice change

**Comment by g-gaston** [comment]
> I assume wherever we're going with the relase note generation enforcing area labels will stay useful? (Just asking in case we're now investing time in area labels and the next step is to adopt the upstream tool and stop using area labels.. :))

Good question @sbueringer 

AFAIK the intention is to keep using capi's release note tool and extend it when necessary. We have talked about adding things that upstream does today, like separating the module dep changes from the rest of the PR entries, but never about replacing the tool. @kubernetes-sigs/cluster-api-release-team please correct me if I'm wrong.

**Comment by sbueringer** [comment]
Thx @killianmuldoon sounds like we're heading in the right direction!

**Comment by vincepri** [comment]
We could always extend the current tooling to support area labels to better identify areas?

**Comment by sbueringer** [comment]
> We could always extend the current tooling to support area labels to better identify areas?

Already done.

**Comment by mjlshen** [comment]
This does seem to be working, e.g. https://github.com/kubernetes-sigs/cluster-api/pull/9195

If there are no objections I'll mark the issue as closed, thanks everyone for the help on this one.

/close

**Comment by killianmuldoon** [comment]
>If there are no objections I'll mark the issue as closed, thanks everyone for the help on this one.

Thanks for doing the leg work on this one @mjlshen! It's working really well IMO
