### ISSUE TITLE
Update KIND to v0.21.0 and document upgrade process

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#8977]
Since changes made to support KIND `v0.20.0` - https://github.com/kubernetes-sigs/cluster-api/pull/8908 - the process for updating KIND as a dependency has gotten more complicated. This process should be correctly documented so the change can be done in future in a single PR.

This should include:
- bumping the version and sha of the default image e.g. https://github.com/kubernetes-sigs/cluster-api/pull/8975
- adding the new image version and SHAs to the kind_mapper e.g https://github.com/kubernetes-sigs/cluster-api/pull/8880
- update kind versions in multiple places - https://github.com/kubernetes-sigs/cluster-api/pull/8908
- bump image versions used in Tiltfile, quickstart, clusterctl upgrade test and yamls e.g. https://github.com/kubernetes-sigs/cluster-api/pull/8908
- document the version change in the providers migration guide, tilt guide and the quickstart  e.g. https://github.com/kubernetes-sigs/cluster-api/pull/8908

I may have forgotten / missed something in the above. My intention is to complete this work as part of the update to KIND v0.21.0 - the resulting documentation is likely to just be that PR and a link to the PR in some relevant place - possibly the release guide.

Note: KIND v0.21.0 has now been released https://github.com/kubernetes-sigs/kind/releases/tag/v0.21.0

/kind documentation

**Comment by killianmuldoon** [comment]
/unassign

/help

This should be done during the next KIND release to ensure we have a single PR linked somewhere showing how to bump the KIND version.

**Comment by killianmuldoon** [comment]
@kubernetes-sigs/cluster-api-release-team maybe a task someone might be interested in picking up?

**Comment by chrischdi** [comment]
/reopen

Do we have to improve docs (as the title / description says)?

**Comment by cahillsf** [comment]
> Do we have to improve docs (as the title / description says)?

ah right -- i can open a followup PR, will update the [k8s updgrde template](https://github.com/kubernetes-sigs/cluster-api/blob/da0ff648111aac465dda7f30a97ff482b6f6e8e9/.github/ISSUE_TEMPLATE/kubernetes_bump.md?plain=1) with a link to this most recent kind bump pr.  anything else that should be added?  maybe some note about incrementing the Mode in the mapper file when there is a code change required in the Docker provider?

**Comment by chrischdi** [comment]
👍  That sounds awesome. Thanks!
