### ISSUE TITLE
support to create kind cluster with extra mounts via e2e framework

### ISSUE THREAD

**Issue by sonasingh46** [kubernetes-sigs/cluster-api#8983]
### What would you like to be added (User Story)?

As a CAPZ developer, I would like to create kind cluster via e2e framework that supports extra mounts for end to end tests. This is useful in workload identity, where the kind cluster node requires key pairs to be available for use by kube-controller-manager and kube-apiserver.   

### Detailed Description

To be able to use workload identity, public and private key pairs needs to be available on the control plane node. To run end to end test in capz using workload identity, currently we need a way to provide these keys to the kind cluster node e.g via extra mount. But this is currently not supported in the existing e2e framework which requires to create a kind cluster from within the capz code and not using the e2e framework for kind cluster creation.

More details on kind cluster extra mount  is here: 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/docs/proposals/20221611-workload-identity-integration.md#set-service-account-signing-flags

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sonasingh46** [comment]
cc @mboersma @CecileRobertMichon @fabriziopandini

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

I'm not aware of any activity in this area; we can re-open if someone show interest
/close
