### ISSUE TITLE
When rolling a MachineDeployment, the process of scaling down old machines seems to be not correct 

### ISSUE THREAD

**Issue by Levi080513** [kubernetes-sigs/cluster-api#8987]
### What steps did you take and what happened?

When i rolling update a MachineDeployment with 3 replicas, CAPI will create two new machine, but after the two new machine becomes ready, CAPI only delete the one of old machine.
The update strategy of MachineDeployment  is rollingUpdate, maxUnavailable is 0, maxSurge is 35%.

The event of MachineDeployment :
```
  Normal   SuccessfulCreate  22m                   machinedeployment-controller  Created MachineSet default/hw-sks-test-1.24.13-04-workergroup-6df44cbd67xjbfwf
  Normal   SuccessfulScale   20m (x2 over 4h10m)   machinedeployment-controller  Scaled MachineSet default/hw-sks-test-1.24.13-04-workergroup-79db8577bfxndjgs: 3 -> 2
  Warning  ReconcileError    19m (x31 over 4h10m)  machinedeployment-controller  when cleaning up unhealthy replicas, got invalid request to scale down default/hw-sks-test-1.24.13-04-workergroup-79db8577bfxndjgs: 2 -> 3
```

### What did you expect to happen?

CAPI should delete two old machine in this case.

### Cluster API version

v1.4.3

### Kubernetes version

v1.24.13

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by killianmuldoon** [comment]
/triage accepted

I tried to recreate this with the same settings as above but couldn't. In my case all of the Machines were correctly scaled down. I wonder is there something else going on in this cluster that resulted in this issue.

I think the first thing that's needed is a test case to reproduce this - let's continue discussion over at the PR #9004

**Comment by fabriziopandini** [comment]
/close

No updates since July 23 and we cannot reproduce
