### ISSUE TITLE
Kubeadm Controlplane Controller panics on non-existing infra machine

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/cluster-api#8989]
### What steps did you take and what happened?

We had the kubeadm controlplane controller panicking ( and successively crash looping) after encountering a machine without an InfraMachine.
<details>
  <summary>Crash message</summary>
`
I0711 15:25:52.729880       1 controller.go:118] "Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" controller="kubeadmcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="KubeadmControlPlane" KubeadmControlPlane="vsphere-sa1-gp/boje-1" namespace="vsphere-sa1-gp" name="boje-1" reconcileID=dd20f800-44ef-4ae9-8722-66a8a51e8d17
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1074bae]

goroutine 765 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x19f8660, 0x2dd11b0})
	runtime/panic.go:884 +0x212
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetManagedFields(0x0?)
	k8s.io/apimachinery@v0.26.1/pkg/apis/meta/v1/unstructured/unstructured.go:448 +0x6e
sigs.k8s.io/cluster-api/internal/util/ssa.hasFieldsManagedBy(...)
	sigs.k8s.io/cluster-api/internal/util/ssa/managedfields.go:173
sigs.k8s.io/cluster-api/internal/util/ssa.DropManagedFields({0x1f4b6d8, 0xc00153ed80}, {0x1f548b8, 0xc0002c3ec0}, {0x1f62a28?, 0x0}, {0x1c80c07, 0x18}, {0xc003fea3f0, 0x2, ...})
	sigs.k8s.io/cluster-api/internal/util/ssa/managedfields.go:48 +0x7a
sigs.k8s.io/cluster-api/controlplane/kubeadm/internal/controllers.(*KubeadmControlPlaneReconciler).syncMachines(0xc0004c9680, {0x1f4b6d8, 0xc00153ed80}, 0xc000bedb80)
	sigs.k8s.io/cluster-api/controlplane/kubeadm/internal/controllers/controller.go:596 +0x476
sigs.k8s.io/cluster-api/controlplane/kubeadm/internal/controllers.(*KubeadmControlPlaneReconciler).reconcile(0xc0004c9680, {0x1f4b6d8, 0xc00153ed80}, 0xc001210000, 0xc0006fa380)
	sigs.k8s.io/cluster-api/controlplane/kubeadm/internal/controllers/controller.go:347 +0x732
sigs.k8s.io/cluster-api/controlplane/kubeadm/internal/controllers.(*KubeadmControlPlaneReconciler).Reconcile(0xc0004c9680, {0x1f4b6d8, 0xc00153eb70}, {{{0xc0009be0d0?, 0x10?}, {0xc0009be0c0?, 0x40dc07?}}})
	sigs.k8s.io/cluster-api/controlplane/kubeadm/internal/controllers/controller.go:233 +0x7f0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1f4b6d8?, {0x1f4b6d8?, 0xc00153eb70?}, {{{0xc0009be0d0?, 0x1961da0?}, {0xc0009be0c0?, 0x0?}}})
	sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004c97c0, {0x1f4b630, 0xc000697dc0}, {0x1a71d80?, 0xc000115160?})
	sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323 +0x38f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004c97c0, {0x1f4b630, 0xc000697dc0})
	sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:231 +0x333
`
</details>

The issue was mitigated by removing the Machine without an associated inframachinem manually and letting it recreate, this time with an InfraMachine

### What did you expect to happen?

CAPI doesnt crash but just logs an error

### Cluster API version

1.4.4

### Anything else you would like to add?

Slack discussion: https://kubernetes.slack.com/archives/C8TSNPY4T/p1689089731289249

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
As mentioned in Slack, we encountered this issue when scale testing on main. At the time I assumed this was because we started caching unstructured. But as this wasn't done on v1.4 I assume there are other reasons why we end up in this situation.

Given that this panic can't occur on main I would suggest ~ backporting the code from main into v1.4:
![image](https://github.com/kubernetes-sigs/cluster-api/assets/4662360/e4baf887-f4c7-4dd1-8701-81e079c51298)

**Comment by killianmuldoon** [comment]
/triage accepted 

This was fixed on main as part of https://github.com/kubernetes-sigs/cluster-api/pull/8940/files#diff-47cf5969a7a97b70232c5d97b882424745bd1ed511b29aa56f55194688ab833cR631-R634 h/t @chrischdi. We should backport a minimal version of it.

**Comment by chrischdi** [comment]
I can take that one

/assign

**Comment by sbueringer** [comment]
@chrischdi Can this be closed?

**Comment by chrischdi** [comment]
Jep

/close
