### ISSUE TITLE
GCP support for Ubuntu image

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#90]
_From @rsdcastro on February 12, 2018 18:15_

This about tracking the current support for Ubuntu to be production ready.

Ideally this should be agnostic so all providers can use it.

_Copied from original issue: kubernetes/kube-deploy#593_

**Comment by rsdcastro** [comment]
Turning this into a GCP specific issue, as there's no current infrastructure or plans to have a more general Ubuntu support that works across providers.

**Comment by rsdcastro** [comment]
/cc @mkjelland @krousey @kcoronado 

Let's track having a production ready Ubuntu support here via the config map work being done.

**Comment by rsdcastro** [comment]
cc @kcoronado 

Katie - is the work to support Ubuntu images for GCE/vSphere tracked anywhere else? Can we close this issue?

**Comment by kcoronado** [comment]
@rsdcastro I think this is the only place it's currently tracked. I'm not entirely sure what is needed to close this issue, but one thing to note is that I had changed the default image to Ubuntu 1710 in kubernetes/kube-deploy#624. If we want to change that back to Ubuntu 1604 lts, we can use this issue to track that change.

**Comment by mkjelland** [comment]
@rsdcastro It looks like the configmap now has a field for the image to use. Currently the default is Ubuntu 1710 as @kcoronado mentioned. Is there anything else that needs to be done for this issue?

**Comment by kcoronado** [comment]
/reopen
I'll send a PR to change the default image from Ubuntu 1710 to 1604 for consistency and close the issue when it's merged.
