### ISSUE TITLE
The description of cluster paused and skipping remediation of MHC should be clearer

### ISSUE THREAD

**Issue by haijianyang** [kubernetes-sigs/cluster-api#9026]
### What steps did you take and what happened?

Original link https://cluster-api.sigs.k8s.io/tasks/automated-machine-management/healthchecking.html#skipping-remediation

### What did you expect to happen?

Original description:
`Implicit skipping when the resource is paused (using cluster.x-k8s.io/paused annotation):

When a cluster is paused, none of the machines in that cluster are considered for remediation.
When a machine is paused, only that machine is not considered for remediation.
A cluster or a machine is usually paused automatically by Cluster API when it detects a migration.`

MHC Controller
```go
// Return early if the object or Cluster is paused.
if annotations.IsPaused(cluster, m) {
	log.Info("Reconciliation is paused for this object")
	return ctrl.Result{}, nil
}

// IsPaused returns true if the Cluster is paused or the object has the `paused` annotation.
func IsPaused(cluster *clusterv1.Cluster, o metav1.Object) bool {
	if cluster.Spec.Paused {
		return true
	}
	return HasPaused(o)
}
```

According to the MHC code, only when cluster.Spec.Paused is true, none of the machines in that cluster are considered for remediation.

Cluster with cluster.x-k8s.io/paused annotation will only pause the reconciliation of the cluster, not the reconciliation of other resources including MHC.

### Cluster API version

v1.4.4

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by killianmuldoon** [comment]
/triage accepted

You're right that this is confusing - would be a good idea to clean up the documentation around this.

/help

**Comment by SubhasmitaSw** [comment]
@killianmuldoon the controller spec definition has to be modified or just the documentation needs more clarity?

**Comment by killianmuldoon** [comment]
For this we just need to clear up the documentation.

**Comment by sbueringer** [comment]
Not sure if we should introduce a second way to achieve the same thing (i.e. pausing a Cluster). If there is documentation missing we can update the documentation instead of changing the implementation.

**Comment by enxebre** [comment]
@fabriziopandini shall we close this in favour of https://github.com/kubernetes-sigs/cluster-api/issues/10130?

**Comment by fabriziopandini** [comment]
> According to the MHC code, only when cluster.Spec.Paused is true, none of the machines in that cluster are considered for remediation.

AFAIK this is not true, or at least it is only partially true.
- MHC does not remediate any machine in the cluster if the cluster is paused (pausing the cluster is like pausing all the MHC resources belonging to it).
- A specific MHC resource does not remediate any target machine if the MHC instance is paused.
- Paused machines are not remediated by MHC.

Given that, I suggest improving the note in https://cluster-api.sigs.k8s.io/tasks/automated-machine-management/healthchecking.html#skipping-remediation to

```
There are scenarios where remediation for a machine may be undesirable (eg. during cluster migration using clusterctl move). For such cases, MachineHealthCheck provides the following mechanisms to skip remediation.

- Users can skip remediation for a specific machine by setting the cluster.x-k8s.io/skip-remediation annotation on it.
- Paused Machines (Machines with the cluster.x-k8s.io/paused annotation) are not considered for remediation.
- If a specific MHC resource is paused (using cluster.x-k8s.io/paused annotation), it will stop to remediate the corresponding target machines.
- If the Cluster is paused (using the cluster.x-k8s.io/paused annotation or by setting cluster.spec.paused to true), all the MHC resources belonging to the Cluster will be implicitly paused, and thus stop remediating target machines.

Note: the last option (pausing the Cluster) is the one used by clusterctl move.
```

/good-first-issue

> @fabriziopandini shall we close this in favour of https://github.com/kubernetes-sigs/cluster-api/issues/10130?

This issue is about improving the description of the MHC behaviuor in the book.
The linked issue instead is about surfacing what is paused, so I don't think they overlap.
