### ISSUE TITLE
Can't run e2e tests locally: /etc/kubernetes/pki/sa.key not valid

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api#9069]
### What steps did you take and what happened?

With the new workload ID defaults, after setting `SERVICE_ACCOUNT_SIGNING_PUB` and `SERVICE_ACCOUNT_SIGNING_KEY` to valid RSA key contents, I still can't run tests locally:

```shell
[certs] etcd/peer serving cert is signed for DNS names [capz-e2e-control-plane localhost] and IPs [172.18.0.3 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
I0724 17:35:35.358260     168 certs.go:78] creating new public/private key files for signing service account users
error reading private key file /etc/kubernetes/pki/sa.key: data does not contain a valid RSA or ECDSA private key
file sa.key existed but it could not be loaded properly
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs.CreateServiceAccountKeyAndPublicKeyFiles
	cmd/kubeadm/app/phases/certs/certs.go:87
```

I've also tried with EDCSA: no joy.

 I think the path handling is wrong on Macs; I doubt $HOME == /etc in this context.

### What did you expect to happen?

Tests should run as before.

### Cluster API version

1.4.4.

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by killianmuldoon** [comment]
/triage accepted

Which changes are you referring to as the "new workload ID defaults" -  and which PATH are you referencing? 

 What previous version did the tests work on?

**Comment by sbueringer** [comment]
Should this be a CAPZ issue?

**Comment by killianmuldoon** [comment]
/triage needs-information

Guessing it should be - but the version number is core CAPI :thinking: - let's see if we get clarification.

**Comment by mboersma** [comment]
/close

Sorry! My bad for opening an issue before coffee. This was meant to land in the CAPZ repository. :-)
