### ISSUE TITLE
Standardize immutable cluster 

### ISSUE THREAD

**Issue by qingzhhu** [kubernetes-sigs/cluster-api#908]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
A standard way to boot immutable cluster, it's just a very basic idea and a draft implementation.
1. A pre-installed image 
   - base/security
   - kubelet
   - basic docker images
2. UserDatas passed to vm by Cloud Init
   - Generated certificates
   - kubelet parameters
   - staitc pod manifest for kube-apiserver/kube-controller-manager/kube-scheduler

* Provider only need to implement the basic function to boot vm or create fixed ip ...
* Provider do not need to handle anything about 'k8s'
* No 'computation' or downloading happened, just the 'result' of the cluster when vm boot.
* It will boot the cluster very fast.
* K8S cluster lifecycle management is implemented in a common way.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by vincepri** [comment]
/priority backlog
/milestone Next

This would be aligned with the work being discussed for v1alpha2

**Comment by qingzhhu** [comment]
Thanks for your reply, looking forward to see it happen.

**Comment by ncdc** [comment]
This sounds like a combination of:

1. making sure the image stamping work (#723) produces images with the appropriate prerequisites installed
1. separating infrastructure providers from bootstrap providers (#853, among others)

We are working on a proposal for separating infrastructure from bootstrapping. Please look for it early next week.

**Comment by timothysc** [comment]
TODO: lets leave this open but unassigned and we can revisit later on in v1alpha2.

**Comment by ncdc** [comment]
I'm inclined to close this, but we can leave it open and re-triage at the beginning of the alpha3 cycle.

/milestone Next

**Comment by ncdc** [comment]
This work is done.
/close
