### ISSUE TITLE
Add support for MachinePool Machines in CAPD

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api#9096]
### What would you like to be added (User Story)?

As a developer, I'd like to have DockerMachinePools support MachinePool Machines by leveraging the new logic in CAPI core. This way, other providers have an example implementation to follow.

### Detailed Description

Since MachinePool Machines have landed in CAPI core, we want to also include changes in CAPD to implement it. Now that we can use DockerMachines with MachinePools, we can also clean up a lot of redundant code by reusing the same logic as well.

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by Jont828** [comment]
Note: we also want to include the DockerMachines for [metadata propogation](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/metadata-propagation) so that the labels added to the MachinePool Machine are added to the DockerMachine as well.

**Comment by CecileRobertMichon** [comment]
This was done in https://github.com/kubernetes-sigs/cluster-api/pull/8842

/close
