### ISSUE TITLE
Allow downgrade in cluster.spec.topology.version if machine deployments and controlplane versions have not been upgraded

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#9098]
### What would you like to be added (User Story)?

As a developer I'd like to be able to downgrade cluster.spec.topology.version in cases where the topology reconciler has not updated the controlplane and machine deployment versions to the newer version.

### Detailed Description

As a developer, I may end up in a state where I have some issues with my ClusterClass variables/patches such that I need to change the cluster.spec.topology.version to get back to a valid reconcile before upgrading again.

E.g., I have a patch that is dependent on builtin.controlplane.version, but I don't have variable data for the newer version yet. In this case, the topology reconciler fails to apply patches and reconciliation stalls.
My cluster isn't yet upgraded in reality and controlplane.spec.version and md.spec.version hasn't changed yet, since this occurs after json patches are calculated.

In this case, I should be able to downgrade the version without any side effect.

### Anything else you would like to add?

This might be expensive, in terms of iterating over controlplane and md resources related to a cluster in the webhook?

### Label(s) to be applied

/kind feature
/area api

**Comment by sbueringer** [comment]
> This might be expensive, in terms of iterating over controlplane and md resources related to a cluster in the webhook?

Not really. If we do it right they are all cached so it should take ~ microseconds.

Probably is rather that its racy. But maybe that is something that don't want to care too much about?

**Comment by sbueringer** [comment]
Another option would be to add some sort of unsafe annotation and allow downgrades in general if it is present. Basically some signalt "I know what I'm doing"

**Comment by randomvariable** [comment]
> Another option would be to add some sort of unsafe annotation and allow downgrades in general if it is present. 

Yeah, that seems reasonable.

**Comment by sbueringer** [comment]
@fabriziopandini WDYT about adding an annotation?

**Comment by randomvariable** [comment]
In an offline conversation, I heard we're ok to proceed with this. Move to triage accepted?

**Comment by sbueringer** [comment]
Yup!!

/triage accepted

**Comment by sbueringer** [comment]
(cc @fabriziopandini)

**Comment by fabriziopandini** [comment]
+1 to using an annotation for this use case

**Comment by sbueringer** [comment]
/assign @chrischdi 

This is part of #Add new validation which blocks upgrades by which increase by 1 minor version if:
The control plane object of the Cluster has a .spec.version != current .spec.topology.version
There are any MachineDeployment, MachinePool or Machine objects with a .spec.version != current .spec.topology.version
There are any MachineSets with .spec.replicas > 0 with a .spec.version != current .spec.topology.version
Introduce the annotation unsafe.topology.cluster.x-k8s.io/disable-version-validation to skip all .spec.topology.version validations (except semver)
in case of skipping validation we should log that it was skipped
xref: https://github.com/kubernetes-sigs/cluster-api/issues/9098
