### ISSUE TITLE
Allow GCP service account K8s namespace to be configurable

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#91]
_From @rsdcastro on February 6, 2018 17:53_

See https://github.com/kubernetes/kube-deploy/pull/570 for context.

_Copied from original issue: kubernetes/kube-deploy#573_

**Comment by roberthbailey** [comment]
This issue was moved to kubernetes-sigs/cluster-api-provider-gcp#15
