### ISSUE TITLE
cluster.Actuator interface is missing Go context from exported functions

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api#910]
/kind feature

**Describe the solution you'd like**
The [`cluster.Actuator`](https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/cluster/actuator.go) interface is missing a Go [context](https://golang.org/pkg/context/) as the first parameter for the functions `Reconcile` and `Delete`:

```go
/// [Actuator]
// Actuator controls clusters on a specific infrastructure. All
// methods should be idempotent unless otherwise specified.
type Actuator interface {
	// Reconcile creates or applies updates to the cluster.
	Reconcile(*clusterv1.Cluster) error
	// Delete the cluster.
	Delete(*clusterv1.Cluster) error
}
```

The interface **should** be:

```go
/// [Actuator]
// Actuator controls clusters on a specific infrastructure. All
// methods should be idempotent unless otherwise specified.
type ActuatorWithContext interface {
	// ReconcileWithContext creates or applies updates to the cluster.
	ReconcileWithContext(context.Context, *clusterv1.Cluster) error
	// DeleteWithContext the cluster.
	DeleteWithContext(context.Context, *clusterv1.Cluster) error
}
```

Please note that I created a **new** interface instead of breaking backwards compatibility,. Still, it's important enough that I feel a breaking change is warranted. The lack of a Go context is problematic for several reasons:

* A context may be used in the Actuator implementations to help control concurrency
* Go's HTTP framework can cancel live requests using the context's Deadline and Timeout semantics.

The Go context is simply [too important](https://blog.golang.org/context) to omit just because there may be no apparent, immediate need. In fact, because both types in question are interfaces, I'd be okay wagering it's not possible to declare a context *isn't* needed. I tend to err on the side of caution and follow the policy that *any Go API should use a Context as the first parameter in exported functions for public interfaces or other public types*.

**Anything else you would like to add:**
Nope-ity nope :)

**Comment by ncdc** [comment]
Given that we are proposing removing the actuator interface, would it be ok to close this?

**Comment by davidewatson** [comment]
I feel this is premature. This is a small change, and independent of whether the actuator interface goes away, this is precisely the type of small targeted change I think we should focus on.

Too many simultaneous changes will only confuse and upset people who are already invested in this project.

**Comment by ncdc** [comment]
The machine bootstrapping proposal we're working on (ETA: early next week) will remove the Machine actuator entirely, but we aren't touching the Cluster actuator. Someone could add the context to the Cluster actuator for v1alpha2, but I would expect it to be removed when we tackle Cluster+Infrastructure later on.

**Comment by akutz** [comment]
Hi @ncdc,

The lack of a context is anti-pattern, and I think it should be added. I can't speak to what the design will be, so if you think this is no longer relevant, then closing this is up to you.

**Comment by ncdc** [comment]
I 100% agree we should add context to methods. I'm just questioning if it's worth doing this for an interface that likely will go away.

**Comment by akutz** [comment]
Hi @ncdc,

That was what I meant when I said:

>  I can't speak to what the design will be, so if you think this is no longer relevant, then closing this is up to you.

If there's no rev planned between CAPI v1alpha1 and v1alpha2, then I agree that it may not be worth adding.

**Comment by vincepri** [comment]
This can be closed now that the actuators are gone in v1alpha2.

/close
