### ISSUE TITLE
Debian Packages baked into Workload Clusters

### ISSUE THREAD

**Issue by Sir-gits-a-lot** [kubernetes-sigs/cluster-api#9100]
How can I have some debian packages baked into the worker nodes/control nodes of workload cluster that I launch using cluster api?
Can anyone suggest a method to achieve this result for CAPD infrastructure provider ? 

I have tried the kubeadmconfigtemplate (spec.file) to provision files like shell script to install some applications into worker nodes during bootstrap but it makes the bootstrap extremely slow. Also for security issue, I want to have debian packages itself to install applications which is not possible using the spec.file approach as such large secrets aren't allowed in K8s. 

What is the work-around if anybody knows?

**Comment by sbueringer** [comment]
Please note

> CAPD is a reference implementation of an infrastructure provider for the Cluster API project using Docker.
>
> **NOTE:** The Docker provider is **not** designed for production use and is intended for development environments only.

What is your use case to install debian packages in CAPD nodes?

**Comment by Sir-gits-a-lot** [comment]
I just wanted to explore CAPI as a tool using the CAPD provider for which I wanted to understand whether there is a possibility of copying debian files into worker nodes while bootstrappping.
 
My use case is I want to have certain debian packages baked into the worker nodes of the workload clusters as soon as they come up. If CAPI provides this option, it's good for me. Otherwise, I'll have to use out-of-the-box puppet/chef to do so. 

I tried with the spec.files field of kubeadmconfigtemplate object and it can be used to provision secrets like shell scripts and all but debian package is too large a file to be converted to a secret.

**Comment by sbueringer** [comment]
Usually folks are building OS images for CAPI with image-builder and then just baking everything they need into it when they build the OS Image. The huge advantage is that they don't have to run through the installation on every Machine creation
