### ISSUE TITLE
When using clusterctl init, it panics.

### ISSUE THREAD

**Issue by chaunceyjiang** [kubernetes-sigs/cluster-api#9128]
### What steps did you take and what happened?

![image](https://github.com/kubernetes-sigs/cluster-api/assets/17962021/0a9aeedb-e30d-4832-944a-436b91c98a1e)

### What did you expect to happen?

There should not be any panic information.

### Cluster API version

```
root@localhost:~# clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.0", GitCommit:"4abf44cd85c4590602e4c10543d53cd4ec914845", GitTreeState:"clean", BuildDate:"2023-07-25T15:49:47Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

```

### Kubernetes version

```
root@localhost:~# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.7", GitCommit:"84e1fc493a47446df2e155e70fca768d2653a398", GitTreeState:"clean", BuildDate:"2023-07-19T12:23:27Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:36:28Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by killianmuldoon** [comment]
Seems like a duplicate of https://github.com/kubernetes-sigs/cluster-api/issues/9101 - @chaunceyjiang could you check if the fix in https://github.com/kubernetes-sigs/cluster-api/issues/9101 works for you?

**Comment by sbueringer** [comment]
And just to be clear. This does not panic. It just prints a stacktrace. That's a huge difference :)

**Comment by chaunceyjiang** [comment]
> And just to be clear. This does not panic. It just prints a stacktrace. That's a huge difference :)

Got it. Thanks~. @sbueringer @killianmuldoon
