### ISSUE TITLE
Make ClusterClass generated object names consistent

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#9135]
Today we have various different naming conventions for objects generated by the topology controller:
* CP/MHC:  {cluster-name}-{random-suffix}
* CP: InfraMachineTemplate {cluster-name}-control-plane-{random-suffix}
* MD/MHC:  {cluster-name}-{topology-name}-{random-suffix}
* MD: BootstrapConfigTemplate: {cluster-name}-{topology-name}-bootstrap-{random-suffix}
* MD: InfraMachineTemplate: {cluster-name}-{topology-name}-infra-{random-suffix}
* MP: InfraMachinePool: {cluster-name}-{topology-name}-infra-{random-suffix}

I would suggest to simplify them and thus make them consistent. I think there is no need to put a bootstrap or infra string in the name of a BootstrapConfigTemplate / InfrastructureMachineTemplate (basically this is just repeating the type in the name)

I would suggest:
* CP/MHC:  {cluster-name}-{random-suffix}
* CP: InfraMachineTemplate {cluster-name}-{random-suffix}. (**changed**)
* MD/MHC:  {cluster-name}-{topology-name}-{random-suffix}
* MD: BootstrapConfigTemplate: {cluster-name}-{topology-name}-{random-suffix} (**changed**)
* MD: InfraMachineTemplate: {cluster-name}-{topology-name}-{random-suffix} (**changed**)
* MP: InfraMachinePool: {cluster-name}-{topology-name}-{random-suffix} (**changed**)

Note: This will also make the names in general shorter which will avoid that the names are getting hashed.

**Comment by sbueringer** [comment]
cc @fabriziopandini @vincepri @killianmuldoon @chrischdi 

/assign

**Comment by fabriziopandini** [comment]
+1 for me!

**Comment by chrischdi** [comment]
Note: the changes only affect the BootstrapConfigTemplate and InfraMachineTemplates so it also does not affect any machine later on and should be safe from that perspective 👍

**Comment by sbueringer** [comment]
Highlighted the delta above with: (**changed**)

**Comment by sbueringer** [comment]
/close

all PRs merged
