### ISSUE TITLE
Bump Go to v1.21.0 

### ISSUE THREAD

**Issue by furkatgofurov7** [kubernetes-sigs/cluster-api#9149]
### What would you like to be added (User Story)?

Golang v1.21.0 is [out](https://groups.google.com/g/golang-announce/c/Mk0Jar6hfhI/m/cJhx_m1dAgAJ). 

To read the release notes, check: https://go.dev/doc/go1.21. 

We could already start using it, unless there are no objections :) 

### Detailed Description

Bump go version in main and possibly in release branches to v1.21.0

### Anything else you would like to add?

Part of: https://github.com/kubernetes-sigs/cluster-api/issues/9094 ([Bumping go version continously](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#continuously-bump-the-go-version))

### Label(s) to be applied

/kind feature
/area dependency

**Comment by furkatgofurov7** [comment]
@kubernetes-sigs/cluster-api-release-team 

cc @killianmuldoon @sbueringer

**Comment by sbueringer** [comment]
I think we should not use it until Kubernetes does it and they chose to not pick it up for Kubernetes 1.28.

Usually this is part of our Kubernetes upgrade issue for that reason (#8708)

xref: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1691508336469659

**Comment by furkatgofurov7** [comment]
@sbueringer I agree and k8s not using it probably the there is not much left until 1.28 is out. Probably they start using it later in 1.28 patch releases, but until then we can hold this and come back again later (or feel free to close it if this is tracked in #8708 already).

**Comment by sbueringer** [comment]
Looks like they are planning to bump in January 
> we should update master to it once it opens for 1.29, we should be ready to update release branches to it in January (1 month after 1.29 release), before go1.20 hits EOL in Feb
> https://kubernetes.slack.com/archives/CJH2GBF7Y/p1691512908396339?thread_ts=1691508336.469659&cid=CJH2GBF7Y

I think for now we should continue with our usual model to bump Go when we pick up new Kubernetes versions (and don't pick it up later).

To change this model and align to what k/k is doing now I've opened this issue a while back: https://github.com/kubernetes-sigs/cluster-api/issues/7974

So I think if we want to start bumping Go later in the cycle and on release branches we have to make progress on #7974

**Comment by sbueringer** [comment]
I would close it here for now until our bump "policies" change

/close
