### ISSUE TITLE
Unable to remove useExperimentalRetryJoin field from KubeadmControlPlaneTemplate

### ISSUE THREAD

**Issue by MaxFedotov** [kubernetes-sigs/cluster-api#9169]
### What steps did you take and what happened?

`UseExperimentalRetryJoin` param in `KubeadmConfigSpec` is marked as deprecated and is planned to be removed in next releases. 

As a part of `clusterClass` refactoring, I removed `useExperimentalRetryJoin` field from my `KubeadmControlPlaneTemplate` for a new `clusterClass` version.

After updating `cluster` to use a new `clusterClass` the following error occurred:
```
E0811 14:01:32.036524       1 controller.go:329] "Reconciler error" err="error reconciling the Cluster topology: failed to create patch helper for KubeadmControlPlane/gcore-eu-mf-test1-10-bn6kn: server side apply dry-run failed for modified object: admission webhook \"validation.kubeadmcontrolplane.controlplane.cluster.x-k8s.io\" denied the request: KubeadmControlPlane.controlplane.cluster.x-k8s.io \"gcore-eu-mf-test1-10-bn6kn\" is invalid: spec.kubeadmConfigSpec.useExperimentalRetryJoin: Forbidden: cannot be modified" controller="topology/cluster" controllerGroup="cluster.x-k8s.io" controllerKind="Cluster" Cluster="system-clusters/gcore-eu-mf-test1-10" namespace="system-clusters" name="gcore-eu-mf-test1-10" reconcileID=6e10c68c-345b-41ff-861c-5d29add97b6a
```

### What did you expect to happen?

CAPI should allow to drop deprecated `useExperimentalRetryJoin` from `KubeadmConfigTemplate` template.

### Cluster API version

v1.4.1

### Kubernetes version

v1.24.15

### Label(s) to be applied

/kind bug
/area /provider/control-plane-kubeadm

**Comment by fabriziopandini** [comment]
The suggested way to change values in a KubeadmControlPlaneTemplate linked to a cluster class is a template rotation (create a new KubeadmControlPlaneTemplate, change the reference in CC); this is also enforced by KubeadmControlPlaneTemplate being immutable.

**Comment by fabriziopandini** [comment]
/triage accepted

Historical context. In KCP we are incrementally enabling changes to the spec only after checking those changes are not leading to non-functional clusters.
This change seems legit and supportive of the deprecation notice, but in other cases, it will be correct that KCP denies the change acting as a safeguard for the cluster.
