### ISSUE TITLE
Deduplicate prefixes in release notes.

### ISSUE THREAD

**Issue by Dhairya-Arora01** [kubernetes-sigs/cluster-api#9190]
### What steps did you take and what happened?

Duplication of prefix in the release note entry when the PR title already contains a prefix which is the same as its area ex- #8953 .

### What did you expect to happen?

The prefix should be deduplicated where the PR title already contains a prefix which is the same as its area as already mentioned in #9104 

### Cluster API version

Unrelated to CAPI version.

### Kubernetes version

Unrelated to Kubernetesversion.

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by killianmuldoon** [comment]
/triage accepted
/assign @Dhairya-Arora01 
Thanks for working on this!
