### ISSUE TITLE
Determine which resources are blocking `clusterctl move` during discovery

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api#9196]
### What would you like to be added (User Story)?

As a developer I want to better align the process for determining if a resource is blocking a `clusterctl move` operation with other inputs to increase overall consistency.

### Detailed Description

The first iteration of allowing resources to block a `clusterctl move` operation by #8690 requires at least one extra API call for every resource to determine if the resource is blocking the move. Instead, the initial state could be gathered during the discovery phase which would enable tighter short-circuiting where no extra API calls are required for resources not blocking a move.

### Label(s) to be applied

/kind cleanup
/area clusterctl

**Comment by fabriziopandini** [comment]
/triage accepted

echoing here https://github.com/kubernetes-sigs/cluster-api/pull/8690#issuecomment-1682711836
> @nojnhuh it would be great to get https://github.com/kubernetes-sigs/cluster-api/issues/9196 implemented before 1.6.0 is cut, because the current implementation is adding an unnecessary extra get for all the objects + the user can wait for x times the timeout for waitMove.
