### ISSUE TITLE
Use dedicated service account for machine controller pod

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#92]
_From @medinatiger on February 5, 2018 20:0_

The current code is using default service account combined an admin privileged kubeconfig. We need to strip down to appropriate access permission with a dedicated service account.

_Copied from original issue: kubernetes/kube-deploy#567_

**Comment by rsdcastro** [comment]
This is very important, but it seems that it can be added as alpha without major changes to the system, so moving it to beta.

**Comment by roberthbailey** [comment]
This issue was moved to kubernetes-sigs/cluster-api-provider-gcp#16
