### ISSUE TITLE
Consider if GenerateCIArtifactsInjectedTemplateForDebian should also handle MachinePools

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#9200]
Title says it all :)

Code ref: [main/test/framework/kubernetesversions/template.go#L71](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/framework/kubernetesversions/template.go?rgh-link-date=2023-08-18T18%3A34%3A47Z#L71)

This is a follow-up from https://github.com/kubernetes-sigs/cluster-api/pull/9016#discussion_r1290465607

**Comment by sbueringer** [comment]
cc @willie-yao @Jont828 (just fyi)

**Comment by Jont828** [comment]
I'm not sure if I have the context of what `GenerateCIArtifactsInjectedTemplateForDebian` is currently used for.

**Comment by sbueringer** [comment]
It is used for jobs that are testing against Kubernetes latest artifacts, it injects a shell script which on startup installs kubelet, kubectl, kubeadm etc..

I think it's used in CAPO, CAPA, CAPC and CAPZ has a fork of it

**Comment by sbueringer** [comment]
Let's close this issue. It's just a test util and there seems to be no demand for MachinePools (which is fine)

/close
