### ISSUE TITLE
Please create new repository - kubernetes-sigs/cluster-provider-api-ibmcloud

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#921]
Based on the discussion in #383 , can you please create the repository under github.com/kubernetes-sigs/cluster-api-provider-ibmcloud ?

Please seed this new empty repository from the following: https://github.com/multicloudlab/cluster-api-provider-ibmcloud

Thanks!

This request has also been sent to the steering committee: https://groups.google.com/forum/#!topic/kubernetes-sig-cluster-lifecycle/-REe9M7BW6k

@davidewatson @enxebre

**Comment by gyliu513** [comment]
FYI @xunpan @jichenjc

**Comment by detiber** [comment]
@gyliu513 Are there any volunteers for maintainers that are not IBM employees? That would be one requirement for adoption of the project under sig-cluster-lifecycle.

I'm also wondering if it would be better owned by sig-cloud-provider or sig-ibmcloud? There is already precedent here with cluster-api-provider-vsphere being owned by sig-vmware and cluster-api-provider-azure being owned by sig-azure.

**Comment by gyliu513** [comment]
Thanks @detiber . Yes, this project will be owned by sig-ibmcloud based on document at https://github.com/multicloudlab/cluster-api-provider-ibmcloud#community-discussion-contribution-and-support , and here what I want to do is I want to create a new repo under `kubernetes-sigs` to host the source code ;-)

Currently, this project has just been finished, and we do not have volunteers for maintainers from non IBM employees yet, but we do plan to recruit some non IBM volunteers for this project. 

I found that both of the maintainers for cluster-api-provider-vsphere are from VMWare ;-), so for the specified cloud providers, how about put the projects to `kubernetes-sigs` first and we can recruit new members later? I was planning to present the cluster-api-provider-ibmcloud in KubeCon Shanghai sig-ibmcloud intro & deep dive. Comments?

**Comment by detiber** [comment]
@gyliu513 ok, you do not need sponsorship from sig-cluster-lifecycle for hosting the repo under the kubernetes-sigs org, just sponsorship from a Kubernetes SIG, the sponsorship from sig-ibmcloud shoudl be sufficient.

**Comment by jichenjc** [comment]
@gyliu513 @detiber 
forgive me not very familiar with the process, so we should not raise the question here and raise the question somewhere else?

**Comment by detiber** [comment]
@jichenjc I think raising it here in the cluster-api repo (and sig-cluster-lifecycle) for awareness is great, however it isn't required for a sig-sponsored project to be transferred to the kubernetes-sigs organization.

**Comment by jichenjc** [comment]
@detiber thanks, great to know and thanks for the clarification

**Comment by detiber** [comment]
https://github.com/kubernetes/community/blob/5d4ceb141f14a9c66251c1c7e5582b87c745bd1c/github-management/kubernetes-repositories.md#sig-repositories are the rules for SIG-sponsored projects to be added to the kubernetes-sigs org, with the requirements falling under the project and the SIG sponsoring the project.

**Comment by gyliu513** [comment]
Based on discussion in today's meeting, I have opened an issue at https://github.com/kubernetes/org/issues/782 for support. 

Thanks @detiber for your great support !!!
