### ISSUE TITLE
Provide a method to CC Release Team on cherry-pick PRs to Releases

### ISSUE THREAD

**Issue by cahillsf** [kubernetes-sigs/cluster-api#9212]
### What would you like to be added (User Story)?

As a release team member I would like to provide a way for cherry-pick PR authors to CC the release team on cherry-pick PRs where applicable to minimize manual burden on PR author or maintainer.

### Detailed Description

CAPI Release team should be cc'ed on cherry-pick PRs to releases.  Currently we see two paths forward:

- Best way to do it, is probably by extending the cherrypicker in test-infra
  - the cherrypicker does already allow for assigning issues via the `prowAssignments` option ([link](https://github.com/kubernetes/test-infra/blob/86c155769c4ecc953f36e378d7891da803f03eea/prow/external-plugins/cherrypicker/main.go#L72))
- Alternative or temporary solution could be a GitHub action in the cluster-api repo

### Label(s) to be applied

/kind feature
/area release
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by cahillsf** [comment]
posted in [#sig-testing](https://kubernetes.slack.com/archives/C09QZ4DQB/p1692190275878519) to see if the `cherrypicker` is accepting contributions or if they have other ideas for how we can move forward

**Comment by furkatgofurov7** [comment]
/triage accepted

Thanks for looking into it!
This is tracked in tracking umbrella issue: https://github.com/kubernetes-sigs/cluster-api/issues/9104

**Comment by sbueringer** [comment]
> As a release team member I would like a way to ensure the release team is cc'ed on cherry-pick PRs to minimize manual overhead in release maintenance.

How does cc'ing the release team minimize the overhead in release maintenance?

**Comment by furkatgofurov7** [comment]
> How does cc'ing the release team minimize the manual overhead in release maintenance?

Well, maybe it is confusing to state "manual overhead in release maintenance" but rather "manual burden to PR author or maintainer to always cc RT in cherry pick PRs"

**Comment by sbueringer** [comment]
I think I'm missing a crucial piece. Why do we want to either manually or automatically cc the release team on all cherry-pick PRs?

**Comment by cahillsf** [comment]
Correct me if I am wrong, Furkat, but I believe the intention here is not to always CC the release team on all the cherry-pick PRs, but provide a method to make it easier to CC RT on cherry-pick PRs where applicable

**Comment by sbueringer** [comment]
Btw sorry for the stupid question, I'm mostly trying to understand what workflow we're aiming for :)

**Comment by furkatgofurov7** [comment]
> I think I'm missing a crucial piece. Why do we want to either manually or automatically always cc the release team on all cherry-pick PRs?

That came up in one of the improvement tasks back from 1.4 RT. So basically, in case where we decide to cherry pick a PR and that needs RT's attention (don't ask me if that would be a case ever 😄) or at least they should be aware of it, then this automation would be used. Although, now I am thinking we might be complicating things to avoid one liner comment to tag a RT GH handle if considered needed.

**Comment by furkatgofurov7** [comment]
> Correct me if I am wrong, Furkat, but I believe the intention here is not to always CC the release team on all the cherry-pick PRs, but provide a method to make it easier to CC RT on cherry-pick PRs where applicable

Yes, that is my understanding @cahillsf

**Comment by cahillsf** [comment]
sounds good - seems like this is a "Won't Do".  Closing out the issue
