### ISSUE TITLE
Run golangci-lint as soon as ok-to-test is set

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#9215]
Today we have significant toil for maintainers because they always have to manually approve the golangci-lint action for outside contributors (by clicking on approve in the "checks box").

Goal of this issue is to ensure the action is run automatically as soon as the ok-to-test label is applied.

Proposed solution:
1. Configure in the repo settings that actions only require approval for first time GitHub users
2. Update the action to immediately fail with a nice error message if the ok-to-test label is missing
  * Prior art: `contains(github.event.pull_request.labels.*.name, 'ok-to-test')`

Probably needs a bit of trial-and-error on a fork, but I think this should work

For 1.
<img width="1031" alt="image" src="https://github.com/kubernetes-sigs/cluster-api/assets/4662360/7952ff09-0632-4ee3-b84a-bd40bbc5f023">

There is potentially another alternative, which is approve workflows automatically if ok-to-test is set: https://github.com/kubernetes-sigs/metrics-server/blob/19802fd979b3c8cdf23297cebe9dc62448e9dc9d/.github/workflows/gh-workflow-approve.yaml#L14. This seems somewhat okay as it only requires actions write permissions. But I think I would prefer the option I mentioned above

**Comment by sbueringer** [comment]
Kudos to @rikatz for sharing the idea!!

**Comment by chrischdi** [comment]
That sounds great. And should be safe because gh actions do not run with the config which is on a PR.

**Comment by chrischdi** [comment]
Solution 1 has an issue:

When e.g. adding the following to the `steps` of an action:


```sh
...
    steps:
      - name: Block testing
        if: ! contains(github.event.pull_request.labels.*.name, 'ok-to-test')
        run: echo "Requires ok-to-test" && exit 1
```

It would also require the `ok-to-test` label for PRs created by kubernetes-sigs members (which is currently not the case).

Also wondering how the second one works.

Using a gh action/workflow to allow gh actions/workflow. Isn't it the case that the gh-workflow-approve workflow won't run either?

**Comment by sbueringer** [comment]
Good points. What about checking for `needs-ok-to-test `?

**Comment by chrischdi** [comment]
> needs-ok-to-test

Nope, can't do that. Sounds too easy 😂 I'll give it a try. That should do it!

**Comment by chrischdi** [comment]
Issue with that is: there is a small time window between creating a PR and gh actions which would run 🤔

**Comment by sbueringer** [comment]
Hm good point. Maybe you can check via https://cs.k8s.io/?q=%27ok-to-test%27&i=nope&files=&excludeFiles=&repos= how it works in other repos

**Comment by sbueringer** [comment]
> Also wondering how the second one works.

I suspect it works somehow btw. Otherwise they use a broken action :D

**Comment by chrischdi** [comment]
Jep, the GH action to approve the workflows when `ok-to-test` label exists works 👍 I'll create a PR for this.

**Comment by sbueringer** [comment]
Sounds like a good option. Thx!

**Comment by killianmuldoon** [comment]
Hmm - on this PR: https://github.com/kubernetes-sigs/cluster-api/pull/9251

The ok-to-test seemed to work initially to run the golangci-lint. But since the PR was pushed again it does not seem to be working - the workflow needs to be approved again. 

/reopen

**Comment by sbueringer** [comment]
Yup. It has to be approved after every single push

**Comment by sbueringer** [comment]
Probably have to trigger it in more cases: https://github.com/kubernetes-sigs/cluster-api/blob/main/.github/workflows/pr-gh-workflow-approve.yaml#L3

**Comment by chrischdi** [comment]
🤔 I'll test that again.

**Comment by chrischdi** [comment]
Tricky to catch the issue but this fixes it: https://github.com/kubernetes-sigs/cluster-api/pull/9259
