### ISSUE TITLE
A race condition between kubeadmcontrolplane and machinehealthcheck cause controlplane creation failed 

### ISSUE THREAD

**Issue by mogliang** [kubernetes-sigs/cluster-api#9220]
### What steps did you take and what happened?

We've set machinehealthcheck rule for controlplane. We observed a fail case that CP never start.

By checking log, we think the story is:
When 1st CP machine creation timeout, machineHealthCheck fired a remediation action which delete the 1st CP machine and create new one. However, in the meantime, 1st CP become responding, which makes kubeadmControlPlane think the CP has started. So, it tells the new machine to "JOIN" the cluster. And this will fail, since the 1CP got deleted soon.

### What did you expect to happen?

kubeadmcontrolplane shall determine the correct status by checking machine num, and always let 1cp machine to create cluster.

### Cluster API version

v1.5.0

### Anything else you would like to add?

capi log
![image](https://github.com/kubernetes-sigs/cluster-api/assets/1578667/191f976c-26e1-4605-a6ec-d5b11dec9190)

kubeadm controlplane log
![image](https://github.com/kubernetes-sigs/cluster-api/assets/1578667/5ea85111-f24c-479f-9ae6-bbd03794e11c)

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by killianmuldoon** [comment]
/triage accepted

Thanks for reporting this - I think we need to ensure that a KCP machine isn't reconciled in cases where it's marked for remediation. I'll try to reproduce tomorrow

**Comment by mogliang** [comment]
Adding more details. This may also related to our infra provider implementation.
We do infraMachine deletion in async way, which means when infraMachine deleted, the real machine may still functions for few more seconds-minute. We hoped async way can acclerate the total capi operation.

**Comment by sbueringer** [comment]
> Adding more details. This may also related to our infra provider implementation. We do infraMachine deletion in async way, which means when infraMachine deleted, the real machine may still functions for few more seconds-minute. We hoped async way can acclerate the total capi operation.

That sounds very dangerous

**Comment by mogliang** [comment]
We've changed to sync delete and rolled to test envionrment, please allow me some days to monitor the test result.

**Comment by mogliang** [comment]
We no longer see this issue happens after change deletion to sync pattern. 
Thanks guys!

**Comment by sbueringer** [comment]
Thx for letting us know, glad it worked out
