### ISSUE TITLE
Cluster.spec.controlPlaneEndpoint fields should be immutable once set

### ISSUE THREAD

**Issue by prometherion** [kubernetes-sigs/cluster-api#9228]
### What steps did you take and what happened?

Once a `Cluster` instance is set with a Control Plane endpoint host and port pair, it can be changed.

This leads to unclarity if this behaviour is accepted or not since there's no general reconciliation in CAPI.

### What did you expect to happen?

Once set, the `Cluster.spec.controlPlaneEndpoint` object should be immutable, as it happens with other infrastructure clusters (e.g. CAPO)

### Cluster API version

v1.5.0

### Kubernetes version

N.R.

### Anything else you would like to add?

I'm open in contributing to this by rising a PR.

### Label(s) to be applied

/kind bug
/area provider/core

**Comment by killianmuldoon** [comment]
This would definitely be a breaking change so would have to be made in a future apiVersion. I'm not sure if this is changed by any infrastructure providers today, but we already have an issue arguing that this field should be made more concretely optional - i.e. by making it a pointer in our Go types: https://github.com/kubernetes-sigs/cluster-api/issues/6416


We should consolidate discussion around how this field is changed and validated to a single issue, but I don't believe this behaviour could be changed in the current API Version.
/kind api-change

**Comment by dlipovetsky** [comment]
Related to #5005, where the user asked if changing the field is supported. We did not say yes or no. But it's clearly not supported yet.
