### ISSUE TITLE
Add additional headers to the release notes tool output

### ISSUE THREAD

**Issue by mjlshen** [kubernetes-sigs/cluster-api#9248]
As mentioned in https://github.com/kubernetes-sigs/cluster-api/issues/9104,

In recent releases, there are some additional header sections that have been manually generated, such as "Highlights" and "Deprecation Warning" - these should be automatically generated by the release notes tool even if the content is not automated, a template with placeholders is fine.

Release notes tool: https://github.com/kubernetes-sigs/cluster-api/blob/main/hack/tools/release/notes.go

**Comment by furkatgofurov7** [comment]
Based on the agreement during the call triaging https://github.com/kubernetes-sigs/cluster-api/issues/9104, setting the priority to:

/priority important-soon
