### ISSUE TITLE
Cluster deployer should support multiple controlplane machines for a cluster

### ISSUE THREAD

**Issue by ashish-amarnath** [kubernetes-sigs/cluster-api#925]
/kind feature

**Describe the solution you'd like**
Cluster deployer today supports only one controlplane machine
https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/clusterdeployer/clusterdeployer.go#L60
https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go#L1056

To create a multi-master cluster, controlplane machines will have to be added to the cluster post-pivot.

**Anything else you would like to add:**
Also, implementing support for multi-master clusters is now the responsibility of the provider implementation. https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/aws/actuators/machine/actuator.go#L99
This should probably change to be the responsibility of the upstream cluster-api

**Comment by ncdc** [comment]
Didn't we fix this in #878?

**Comment by ncdc** [comment]
As discussed in today's grooming meeting, this is done. We'll use separate issue(s) to track control plane lifecycle management.

/close
