### ISSUE TITLE
Generate ProwJob YAMLs and automate changes to test jobs

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#9257]
CAPI maintains a number of test jobs across 4 branches Kubernetes test/infra for execution in Prow. Currently updating the yamls that define these test jobs is a manual enterprise, even where the same changes need to be made in each and every test job, or with formulaic tasks such as creating jobs for a new release branch.

We should automate editing these yamls so it takes less time to execute and review and gives us more confidence in how we're changing these jobs going forward. 

There is prior art for this used by the folks at EKS which could be used as inspiration: https://github.com/aws/eks-distro-prow-jobs/

/assign

**Comment by furkatgofurov7** [comment]
@killianmuldoon 👋🏼  Just wanted to check in and know if there is any update on this issue or if Release Team members can help to move this forward. Thanks!

**Comment by killianmuldoon** [comment]
If someone has time to pick this up please do - I'm happy to pair on it and help if folks want.
