### ISSUE TITLE
Timed out after 1200.000s. Expected bool: false to be true while getting machineDeployments

### ISSUE THREAD

**Issue by adilGhaffarDev** [kubernetes-sigs/cluster-api#9258]
### Which jobs are failing?

periodic-cluster-api-e2e-mink8s-release-1-3
periodic-cluster-api-e2e-release-1-3
e.g: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-release-1-3/1693474954122629120

### Which tests are failing?

When testing MachineDeployment rolling upgrades Should successfully upgrade Machines upon changes in relevant MachineDeployment fields

### Since when has it been failing?

20-08-2023
https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*&xjob=.*-provider-.*#6185b6eccff16a274410

### Testgrid link

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-1.3#capi-e2e-mink8s-release-1-3

### Reason for failure (if possible)

To be analyzed.

### Label(s) to be applied

/kind failing-test

**Comment by chrischdi** [comment]
More persistent [triage link](https://storage.googleapis.com/k8s-triage/index.html?date=2023-08-21&text=Timed%20out%20after%201200.000s&job=.*-cluster-api-.*release-1-3&xjob=.*-provider-.*)

**Comment by adilGhaffarDev** [comment]
This flake happens only in v1.3, I have checked it is not happening in other releases. We close this once we drop v1.3 tests.

**Comment by sbueringer** [comment]
Thx for checking!

**Comment by killianmuldoon** [comment]
/close

Looks like there's no failures with this error message.

Thanks!
