### ISSUE TITLE
References to background information in documentation links are broken

### ISSUE THREAD

**Issue by pickledrick** [kubernetes-sigs/cluster-api#926]
/kind bug

**What steps did you take and what happened:**

Clicked on links,
What is a Resource
What is a Controller

On page 

https://kubernetes-sigs.github.io/cluster-api/common_code/architecture.html

**What did you expect to happen:**
Links to work

**Anything else you would like to add:**

Not sure if we should reference git pages or published URL

**Comment by davidewatson** [comment]
This was fixed by https://github.com/kubernetes-sigs/cluster-api/pull/1008
/close
