### ISSUE TITLE
Release Team: Add Release Team members onboarding documentation

### ISSUE THREAD

**Issue by furkatgofurov7** [kubernetes-sigs/cluster-api#9274]
### What would you like to be added (User Story)?

At the beginning of the release cycle, the release team members should review the documentation to become aware of the existing processes and tools used throughout the cycle. 

### Detailed Description

The idea is to have onboarding documentation per sub-team (CI signal, Comms) which outlines the tools/processes used by each team in high level. For example, CI team members should be aware/familiarize themselves with:

- prow, how to use prow commands, interact with prow etc
- [testgrid](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#Summary) dashboard, what jobs are relevant 
- test-infra repo where all the CI jobs setup live
- [k8s triage](https://storage.googleapis.com/k8s-triage/index.html?job=periodic-cluster-api-e2e-main)

Comms team:
- release note generation tool
- important communication channels
- ...

** Additionally, we could document in each sub-team Leads and Release Lead tasks about conducting an onboarding session with shadows in the first week of the release cycle to go over general responsibilities and expectations.

### Label(s) to be applied

/kind documentation
/area release

Tracked in: #9104

**Comment by furkatgofurov7** [comment]
https://github.com/orgs/kubernetes-sigs/teams/cluster-api-release-team
cc @killianmuldoon @CecileRobertMichon @sbueringer

**Comment by sbueringer** [comment]
Sounds good

**Comment by g-gaston** [comment]
Sounds good, the more we can write down the more time we save in future cycles and the less meetings we'll need.

**Comment by furkatgofurov7** [comment]
Thanks for inputs folks, I'll open a PR to add the notes shortly
