### ISSUE TITLE
Owner Reference is not set in MachineDeployment when the deployment is created in Management Cluster

### ISSUE THREAD

**Issue by DheerajSShetty** [kubernetes-sigs/cluster-api#929]
On creating  Machine Deployment in Management cluster,  cluster-api does not set owner references for the MachineDeployments, because of which
https://github.com/kubernetes-sigs/cluster-api/blob/537dfee50e59f57b40e497b6d98f7d82a0f7fcde/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go#L292

returns empty list.

Steps to reproduce
1. Create a k8s cluster.
2. Follow the steps to create all the CRDs>
3. Deploy CAPI/CAPA.
4. Create cluster
5. Create controlplane.
6. Apply addons.
7. Create MachineDeployment.

**Comment by vincepri** [comment]
Which version of the Cluster API controller are you running?

The ownerReference is set here 
https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/machinedeployment/controller.go#L221-L231

**Comment by ncdc** [comment]
@DheerajSShetty could you please let us know if this is still an issue for you?

**Comment by DheerajSShetty** [comment]
I will use capi 0.1.1 and recheck this. Last time I checked, this issue was still seen. I will check it today and update here.

**Comment by DheerajSShetty** [comment]
I could not test this on Friday. I did a quick describe MachineDeployment, which showed OwnerReference. I have to check if 
https://github.com/kubernetes-sigs/cluster-api/blob/a7a0a93a8052fd08a8fb585746f99d107227f521/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go#L292
this returns a MachineDeployment or not.

**Comment by vincepri** [comment]
@DheerajSShetty This is going to be tackled in v1alpha2, v1alpha1 has limitations around how we access workload clusters from a management one.

**Comment by vincepri** [comment]
I just tried running CAPA with the latest CAPI 0.1.3 and the OwnerReference is set properly

```json
    "apiVersion": "cluster.k8s.io/v1alpha1",
    "kind": "MachineDeployment",
    "metadata": {
        "annotations": {
            "machinedeployment.clusters.k8s.io/revision": "1"
        },
        "creationTimestamp": "2019-06-11T02:16:22Z",
        "finalizers": [
            "foregroundDeletion"
        ],
        "generation": 2,
        "labels": {
            "cluster.k8s.io/cluster-name": "test1"
        },
        "name": "sample-machinedeployment",
        "namespace": "default",
        "ownerReferences": [
            {
                "apiVersion": "cluster.k8s.io/v1alpha1",
                "blockOwnerDeletion": true,
                "kind": "Cluster",
                "name": "test1",
                "uid": "3d87808f-8bee-11e9-aff7-0242a75d7eaf"
            }
        ],
```

**Comment by DheerajSShetty** [comment]
Please close it if it is Set.
