### ISSUE TITLE
Automate new docker image builder with new apiserver and controller manager

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#93]
_From @medinatiger on February 5, 2018 19:53_

It was manually built with "apiserver-boot build container --image ". However, it needs to be extended with all the additional configuration such as openssh stuff in cluster-api-gcp/machine-controller.

_Copied from original issue: kubernetes/kube-deploy#564_

**Comment by rsdcastro** [comment]
_From @vaibhavsingh97 on February 7, 2018 18:31_

@medinatiger Can you please guide me how can I solve this issue 😄

**Comment by rsdcastro** [comment]
_From @medinatiger on February 7, 2018 18:43_

https://github.com/kubernetes-incubator/apiserver-builder/blob/master/docs/running_in_cluster.md has full instruction how to build & push a docker image.

I would like to have sth like https://github.com/kubernetes/kube-deploy/blob/master/cluster-api-gcp/machine-controller/Makefile.

@vaibhavsingh97, thanks for helping out!

**Comment by dims** [comment]
we gave Dockerfile for apiserver and controller-manager already. Nothing else to do right?

**Comment by roberthbailey** [comment]
I agree with @dims; I think this one can be closed.
