### ISSUE TITLE
Cannot `kustomize build hack/observability/kube-state-metrics` / cannot use gitops for `hack/observability/kube-state-metrics`

### ISSUE THREAD

**Issue by cwrau** [kubernetes-sigs/cluster-api#9312]
### What steps did you take and what happened?

We're trying to include the new kube-state-metrics concept for our CAPI setup but we ran into the following problem while trying to use a flux kustomization;

```
Error: accumulating resources: accumulation err='accumulating resources from '../namespace.yaml': security; file '/tmp/kustomize-2769474050/hack/observability/namespace.yaml' is not in or below '/tmp/kustomize-2769474050/hack/observability/kube-state-metrics'': must build at directory: '/tmp/kustomize-2769474050/hack/observability/namespace.yaml': file is not directory
```

### What did you expect to happen?

I expected flux, and `kustomize build`, to be able to build the folder.

### Cluster API version

N.A. / main

### Kubernetes version

N.A. / 1.25.8

### Anything else you would like to add?

Locally `kustomize build hack/observability/kube-state-metrics` also fails with;

```
Error: accumulating resources: accumulation err='accumulating resources from '../namespace.yaml': security; file '/home/cwr/projects/cluster-api/hack/observability/namespace.yaml' is not in or below '/home/cwr/projects/cluster-api/hack/observability/kube-state-metrics'': must build at directory: '/home/cwr/projects/cluster-api/hack/observability/namespace.yaml': file is not directory
```

### Label(s) to be applied

/kind bug
/area metrics

**Comment by sbueringer** [comment]
To be honest. This folder only exists for usage within our tilt development environment, not for folks to consume our "hack" kube-state-metrics chart and configuration.

**Comment by cwrau** [comment]
> To be honest. This folder only exists for usage within our tilt development environment, not for folks to consume our "hack" kube-state-metrics chart and configuration.

Ok then, do you have an official way to export these metrics? 

Or put plainly, how is the end-user supposed to get these metrics if not through kube-state-metrics combined with your config?

**Comment by sbueringer** [comment]
The plan was to eventually release the configuration as part of the release artifacts: https://github.com/kubernetes-sigs/cluster-api/issues/7229

In the meantime the only option is to copy it which is not great.

**Comment by cwrau** [comment]
Ah, ok, depending on how that will be implemented that would be the longterm preferred solution.

But, in the short term, fixing this would already allow us to not have to copy the file as we can just roll-out the kustomization with the `kube-state-metrics` deployment 😁

**Comment by sbueringer** [comment]
Yeah it's just that basically we're on the hook to maintain a dev monitoring stack in a way that folks can use it in production. This will be just the first support request of many

**Comment by fabriziopandini** [comment]
+1 to not invest in making hack/observability/ usable outside of CAPI (and close this issue with won't fix)

We already have already a plan to bring observability to a more "production" ready place, not only for CAPI, but for all the providers (and even more, given that we are working on tooling that can be used for any CRD).
Let's keep going, and if we can possibly get some help from folks interested in this, we can get it implemented faster
