### ISSUE TITLE
Add expandable auto-generated release notes for beta and RC (non-GA) releases

### ISSUE THREAD

**Issue by nprokopic** [kubernetes-sigs/cluster-api#9319]
### What would you like to be added (User Story)?

(Coming from https://github.com/kubernetes-sigs/cluster-api/issues/9104)

As a Cluster API release team member, I would like to be create auto-generated release notes for beta and RC (non-GA) releases the same like release notes are generated for GA releases.

### Detailed Description

When running `make release-notes` for a pre-release, instead of outputting a static text defined in the `Makefile`, run `go run ./hack/tools/release/notes.go` to generate release notes for a beta/RC release.

This requires adding support for beta and RC releases to `go run ./hack/tools/release/notes.go` so that (expandable) release notes are generated automatically.

Release notes for a beta/RC release must have a clear signal on top that the release is a beta/RC.

### Anything else you would like to add?

This issue could be considered obsolete if Cluster API project decides to switch to Kubernetes release-notes tool. For more details see https://github.com/kubernetes-sigs/cluster-api/issues/8292.

### Label(s) to be applied

/kind feature
/area release

**Comment by furkatgofurov7** [comment]
@nprokopic hey, just checking in the status here: is there any progress on this issue or do you need help with anything?

**Comment by chandankumar4** [comment]
I'll work on this issue.
/assign
