### ISSUE TITLE
Ensure reproducible image generation for docs and proposals

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#9331]
CAPI uses `plantuml` to generate images used in the CAPI book and CAEPs. A number of the images in the repo do not have plantuml files for generation. 

To improve the situation we should create a verify make target which verifies we are able to regenerate images as expected and catches changes in the images after generation. These changes can happen after changing, for example, the `plantuml` verison used and should be caught and closely reviewed before merging.

As part of this we should decide if all of the  images which currently have no plantuml source should be kept, or if it's possible to replace them. Those images that are retained should be retained in their current format and excepted from reproducible image building.

At time of writing the diff after deleting all `pngs`and regenerating looks like the below. Additionally the `svg` images in the repo are not currently generated using plantuml automatically.
```
        deleted:    docs/book/src/images/describe-cluster-disable-grouping.png
        deleted:    docs/book/src/images/describe-cluster-echo.png
        deleted:    docs/book/src/images/describe-cluster-how-grouping-works.png
        deleted:    docs/book/src/images/describe-cluster-show-conditions.png
        deleted:    docs/book/src/images/describe-cluster.png
        deleted:    docs/book/src/images/introduction.png
        deleted:    docs/book/src/images/runtime-sdk-lifecycle-hooks.png
        deleted:    docs/proposals/images/capi-provider-operator/fig3.png
        deleted:    docs/proposals/images/capi-provider-operator/fig4.png
        deleted:    docs/proposals/images/clusterctl-redesign/components.png
        deleted:    docs/proposals/images/conditions/cluster-provision-workflow.png
        deleted:    docs/proposals/images/conditions/upgrade-workflow.png
        deleted:    docs/proposals/images/externally-managed-cluster-infrastructure/infrastructure.png
        deleted:    docs/proposals/images/in-place-propagation/current-state.png
        deleted:    docs/proposals/images/in-place-propagation/optional-changes.png
        deleted:    docs/proposals/images/in-place-propagation/proposed-changes.png
        deleted:    docs/proposals/images/ipam-integration/consumption.png
        deleted:    docs/proposals/images/ipam-integration/sequence.png
        deleted:    docs/proposals/images/machine-states-preboot/Figure2.png
        deleted:    docs/proposals/images/runtime-hooks/runtime-hooks.png
        deleted:    docs/proposals/images/runtime-sdk/overview.png
        deleted:    docs/proposals/images/runtime-sdk/swagger-ui.png
```

**Comment by killianmuldoon** [comment]
I think we should couple it as figuring out which images we should compare is essentially the second part of the task. Without excluding those images I'm not sure how we can properly verify image generation in the CI, but open to ideas.

**Comment by sbueringer** [comment]
I think we can re-generate plantuml without having to delete all pngs. It's already a win.

**Comment by typeid** [comment]
So is the task here to just add the plantuml generation to CI, to ensure that the generation works? I'd be interested in taking this on if that's the case. 
If not, I'd still be interested but would need more clarification :)

**Comment by killianmuldoon** [comment]
Thanks @typeid  - I think the first task - as @sbueringer outlined - would be to have a `verify-diagrams` make target where we regenerate the images and ensure nothing has changed.
