### ISSUE TITLE
[blocked] implement the container image promoter process

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#936]
/kind feature

**Describe the solution you'd like**
I'd like releases to use the container-image-promoter process supported by k8s-infra working group.

Please see this for more detail
https://github.com/kubernetes-sigs/k8s-container-image-promoter

You will likely have to talk with @dims as the service is currently in beta.

**Anything else you would like to add:**

**Comment by amy** [comment]
In order to use the upstream image promoter, this issue is blocked on k8s-infra-wg writing e2e tests for the promoter. I am helping with this effort and working on a testing document to define what "done" means for e2e testing.

**Comment by chuckha** [comment]
thanks for the update

Is there an upstream issue we can track so we know when this work is unblocked?

**Comment by ncdc** [comment]
We have worked through most or all of the issues, so...
/close
