### ISSUE TITLE
Docs seem to refer to old command / old feature `clusterctl config provider` 

### ISSUE THREAD

**Issue by karuppiah7890** [kubernetes-sigs/cluster-api#9374]
### What steps did you take and what happened?

I was running `clusterctl init --help` to read options available in the command and get any other information, like docs, examples etc

I noticed the help mention the following

```
Some providers require environment variables to be set before running clusterctl init.
Refer to the provider documentation, or use 'clusterctl config provider [name]' to get a list of required variables.
```

I tried to run `clusterctl config provider aws` as I wanted to see what all variables / knobs I can provide as part of initializing a management cluster, apart from `AWS_B64ENCODED_CREDENTIALS`. I noticed that `clusterctl config provider` is no more a valid command and has been replaced by `clusterctl config repositories` and that people can look at all variables in the `infrastructure-components.yaml` available in the CAP* Infrastructure provider's release artifacts for example CAPA release artifacts, and then look for `${` in the YAML file content

### What did you expect to happen?

I expected to see a list of variables I can provide to initialize a management cluster for creating AWS workload clusters

OR

I expected to not see docs about an old / deprecated command

### Cluster API version

`v1.5.1`

```bash
$ clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"db17cb237642881cde3e3f61e77eca55e2583883", GitTreeState:"clean", BuildDate:"2023-08-29T15:42:28Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"darwin/amd64"}
```

### Kubernetes version

```bash
$ kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

### Anything else you would like to add?

-

### Label(s) to be applied

/kind bug
/area clusterctl

**Comment by karuppiah7890** [comment]
I'm glad I was able to list variables available for configuration for generating workload cluster YAMLs. I used this

```bash
clusterctl generate cluster my-cluster --list-variables --infrastructure aws:v2.2.1
```

I'm assuming a similar thing is what was implemented for `cluster init` config based on infrastructure components YAML file

**Comment by fabriziopandini** [comment]
nice catch!
/good-first-issue

**Comment by rushrs** [comment]
@SubhasmitaSw are you currently still looking into this? happy to take over if you are not.

**Comment by sbueringer** [comment]
> I'm glad I was able to list variables available for configuration for generating workload cluster YAMLs. I used this
> 
> ```shell
> clusterctl generate cluster my-cluster --list-variables --infrastructure aws:v2.2.1
> ```
> 
> I'm assuming a similar thing is what was implemented for `cluster init` config based on infrastructure components YAML file

Just to be clear. This gives you the variables for workload cluster creation. Not for the deployment of the provider
