### ISSUE TITLE
Improve description for machine deployment.spec.strategy.type

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api#9376]
### What steps did you take and what happened?

For folks doing things w/ i.e. GPU where theres resource constraints its important to know the alterantvies  RolloutStrategies.... 
```
kubo@PmilRMT2e4lE2:~$ kubectl explain md.spec.strategy
KIND:     MachineDeployment
VERSION:  cluster.x-k8s.io/v1beta1

RESOURCE: strategy <Object>

DESCRIPTION:
     The deployment strategy to use to replace existing machines with new ones.

FIELDS:
   rollingUpdate        <Object>
     Rolling update config params. Present only if MachineDeploymentStrategyType
     = RollingUpdate.


*** WHAT ELSE :) ***

   type <string>
     Type of deployment. Default is RollingUpdate.

kubo@PmilRMT2e4lE2:~$ kubectl explain md.spec.strategy.type
KIND:     MachineDeployment
VERSION:  cluster.x-k8s.io/v1beta1

FIELD:    type <string>

DESCRIPTION:
     Type of deployment. Default is RollingUpdate.
```

### What did you expect to happen?

The description would have valid rollout values since they are strongly typed

### Cluster API version

cluster-api/cluster-api-controller:v1.4.5

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by fabriziopandini** [comment]
/triage accepted

Let's change https://github.com/kubernetes-sigs/cluster-api/blob/58557b7ad20411ac259615dbe729e54193b5ee9b/api/v1beta1/machinedeployment_types.go#L155 into

// Type of deployment, allowed values RollingUpdate, OnDelete. Default is RollingUpdate.

/help
/good-first-issue
