### ISSUE TITLE
Release v0.1.1

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#938]
/assign @justinsb 

Until we get the image promoter process in place I think the gcr repo is locked down? It would be awesome to cut another release after the big backport of fixes to the release-0.1 branch.

🙏  let me know if you have questions or if you find the releasing document out of date.

**Comment by ncdc** [comment]
@chuckha is there still work to do here?

**Comment by detiber** [comment]
It looks like the release notes were never generated for the release.

**Comment by chuckha** [comment]
minimally, we only need the image pushed for a release. I'd say this is closed and release notes are not strictly required, but they would be very nice to do as part of a release.

**Comment by timothysc** [comment]
We can close this given we cut 0.1.2 today.
