### ISSUE TITLE
Updated README to clarify the difference between Cluster API and Kubernetes Cloud Provider

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#939]
/kind bug

The Kubernetes also have bunch of cloud providers at https://github.com/kubernetes/kubernetes/tree/master/pkg/cloudprovider , I think we need to clarify the difference between those two providers, comments? @detiber @vincepri

**Comment by detiber** [comment]
+1 to clarifying the differences.

**Comment by jichenjc** [comment]
ok, this can be some doc update, basically, to me cloud provider is something we can leverage from k8s perspective to get resource such as volume, files, network, machine etc, while cluster-api is focus on provisioning workers nodes from cloud then bootstrap k8s controller/nodes on top..
