### ISSUE TITLE
Not able to init capi in existing cluster k8s v1.25

### ISSUE THREAD

**Issue by diptripa** [kubernetes-sigs/cluster-api#9399]
### What steps did you take and what happened?

Installed capi v1.5.1, got 
`Error: this version of clusterctl could be used only with "v1beta1" management clusters, "v1alpha3" detected`

Downgraded to v0.3 got this error
something like kubernetes v1.25 is not supported

Upgraded to v0.4 got this error
`Error: this version of clusterctl could be used only with "v1alpha4" management clusters, "v1alpha3" detected`

### What did you expect to happen?

I expected things to work with one of these versions.

### Cluster API version

v1.5, v0.3, v0.4

### Kubernetes version

1.25

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
> Downgraded to v0.3 got this error
> Error: this version of clusterctl could be used only with "v1alpha4" management clusters, "v1alpha3" detected

This sounds very very strange. clusterctl v0.3.x should not be aware of v1alpha4 at all

**Comment by killianmuldoon** [comment]
When you say you downgraded / upgraded what steps did you take exactly? The message being reported is from `clusterctl`. You should be able to see what version of `clusterctl` is in use with `clusterctl version`

**Comment by diptripa** [comment]
Sorry updated the main comment.
on 0.3 it said, kubernetes version is not supported for v1.25

**Comment by sbueringer** [comment]
You're trying to run `clusterctl init`? Because the output from clusterctl seems to suggest it thinks CAPI is already deployed.
