### ISSUE TITLE
Documentation issue with using ignition as a bootstrap configuration

### ISSUE THREAD

**Issue by odvarkadaniel** [kubernetes-sigs/cluster-api#9402]
### What steps did you take and what happened?

I was following [this](https://cluster-api.sigs.k8s.io/tasks/experimental-features/ignition) part of the CAPI book to use ignition as a bootstrap config for my control plane machine for a workload cluster, but I run in to an issue where the AMI with the name `capa-ami-flatcar-stable-?1.22.2-*` does not exist. 

The `clusterctl` command that is being used to generate the workload cluster is using unsupported version for this feature:

```
clusterctl generate cluster ignition-cluster \
    --from https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/templates/cluster-template-flatcar.yaml \
    --kubernetes-version **v1.22.2** \
    --worker-machine-count 2 \
    > ignition-cluster.yaml
```

The kubernetes version should be v1.25.0+.

### What did you expect to happen?

I expected my control plane machine to get to phase Running.

### Cluster API version

v1.5.0

### Anything else you would like to add?

Not really a bug, but an error in the documentation as the AMI exists only for versions v1.25.0+ according to [this](https://cluster-api-aws.sigs.k8s.io/topics/images/built-amis) list.

### Label(s) to be applied
/label area/documentation

**Comment by killianmuldoon** [comment]
/triage accepted

Thanks for reporting this!

/help

**Comment by mdbooth** [comment]
ping @tormath1

**Comment by odvarkadaniel** [comment]
Would an acceptable solution to this be a change of the k8s version in the commend to `v1.25.0` and some kind of note saying that ignition is supported in 1.25+, @killianmuldoon?
If so, I could just take this.

**Comment by invidian** [comment]
How about we bump it to 1.28.1 already, since I guess they will be removed later in the future than v1.25.0? I'm pretty sure v1.22.2 existed at some point, so I assume those AMIs are now removed due to being EOL.

**Comment by ahrkrak** [comment]
genius. more docs should do this.

**Comment by killianmuldoon** [comment]
Is there any guarantee that an image exists for every stable version of Kubernetes? 

We may also not have support for a given minor version in Kubernetes - it can take time to catch up and older release branches which will have this documentation will certainly not support the latest version of Kubernetes.

I think if we want to keep this documentation from being broken the target should be keeping this version the same as the version used by the regular CAPI quickstart, but we'd need some guarantee that those AMIs will be available.

**Comment by odvarkadaniel** [comment]
I guess every major stable version should be guaranteed to have an AMI? So therefore we could just modify the command that @tormath1 posted above as:

```
clusterctl generate cluster ignition-cluster \
    --from https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/templates/cluster-template-flatcar.yaml \
-    --kubernetes-version **v1.22.2** \
+    --kubernetes-version $(curl -Ls https://dl.k8s.io/release/stable.txt | awk -F. '{$NF=0}1' OFS=. | sed 's/.0$/.0/') \
    --worker-machine-count 2 \
    > ignition-cluster.yaml
```

So we always end up with a major version of k8s.
