### ISSUE TITLE
Eliminate new instances of context.TODO() from clusterctl proxy.go

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api#9442]
Three new instances of `context.TODO()` have been introduced as a part of #9437. These should be removed in favor of utilizing existing contexts.

These are the locations of the instances:
https://github.com/kubernetes-sigs/cluster-api/blob/1779aec710473ac36bba316cf3c50c6a172f02fe/cmd/clusterctl/client/cluster/proxy.go#L168
https://github.com/kubernetes-sigs/cluster-api/blob/1779aec710473ac36bba316cf3c50c6a172f02fe/cmd/clusterctl/client/cluster/proxy.go#L194
https://github.com/kubernetes-sigs/cluster-api/blob/1779aec710473ac36bba316cf3c50c6a172f02fe/cmd/clusterctl/client/cluster/proxy.go#L405

**Comment by sbueringer** [comment]
Thx for opening the issue

/triage accepted
/area clusterctl

**Comment by chiukapoor** [comment]
I can work on this

**Comment by chiukapoor** [comment]
The PR https://github.com/kubernetes-sigs/cluster-api/pull/9437 is not merged yet

**Comment by chrischdi** [comment]
Ah yeah, so I'll remove the assignment.

/unassign chiukapoor

**Comment by nojnhuh** [comment]
@chiukapoor The PR has been merged in case you're still looking to pick this up.

**Comment by mcbenjemaa** [comment]
I will take this issue if he can't take it.

**Comment by chiukapoor** [comment]
@mcbenjemaa thank you for taking it over. I was away for a while.
