### ISSUE TITLE
Makefile improvement suggestions

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#945]
/kind feature

**Describe the solution you'd like**
I'd like to propose some changes to our Makefile targets:

- If I'm compiling locally, I only want the clientsets/listers/informers regenerated as-needed; in other words, do not regenerate every time I run any sort of build-related target. The same applies to the `go generate` output.
- If I'm compiling locally, I only want to deal with `dep` as-needed; in other words, do not run `dep ensure` unless I explicitly ask for it.

tl;dr: try to speed up builds by switching targets that aren't needed frequently to optional/opt-in instead of as dependencies

**Anything else you would like to add:**
N/A

**Comment by asauber** [comment]
cc myself

**Comment by ncdc** [comment]
Much of this has been cleaned up in master. If there's anything left over, I'll either open a new issue, or just file PRs 😄 

/close
