### ISSUE TITLE
Cluster API Operator Quickstart

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api#9473]
### What would you like to be added (User Story)?

As an operator, I would like to have quickstart instructions install cluster API and all dependencies utilizing the Cluster API Operator so that I can have a more scalable, GitOps-friendly, and better overall lifecycle for my CAPI management cluster(s).

### Detailed Description

Would like to have an alternate path to the [current quickstart](https://cluster-api.sigs.k8s.io/user/quick-start) guidance which only utilizes the operator (not clusterctl).  This is important to have in the cluster API project book for visibility.

### Anything else you would like to add?

Rough proposal would be to have a separate quickstart flow/path/page linked to at the top of the existing clusterctl quickstart page.  Open for discussion on this thread.

### Label(s) to be applied

/kind feature
/kind documentation
/area documentation

**Comment by killianmuldoon** [comment]
/triage accepted 

Sounds like a good idea. Do we know if the current CAPI operator [Getting Started](https://github.com/kubernetes-sigs/cluster-api-operator/tree/main/docs#getting-started) is up to date? If we could separate out a doc like that in the operator repo we would be able to embed it in the CAPI book. [This is similar to what we're doing for the autoscaler today](https://github.com/kubernetes-sigs/cluster-api/blob/0061757ecd7367621993e875932f1b2399d5fd80/docs/book/src/tasks/automated-machine-management/autoscaling.md#L11).

**Comment by dtzar** [comment]
I like the embed idea!  The getting started is up to date, but not streamlined for being embeded as a CAPI book quickstart.  I'd be happy to help with this.  
Step 1 - refactor getting started in operator repo
Step 2 - PR to CAPI to add a new quickstart which has that article embeded.

**Comment by alexander-demicev** [comment]
I would like to work on that. Yes, we try to keep the operator's docs up to date.
/assign
