### ISSUE TITLE
[question] why we make events to each cloud provider? 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#949]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
 looks aws provider using events here:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/aws/services/ec2/instances.go#L283

why we can't generalize it somewhere such as 
https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/machine/controller.go#L196 (or similar place)

so that we don't need have this all the provider side? any history reason?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by vincepri** [comment]
@calebamiles Let me know if there is anything I can do to get you started here (if you'd like to work on it), we can definitely tackle this in v1alpha2

**Comment by ncdc** [comment]
@jichenjc your code links are now out of date as the repositories have evolved. Could you please clarify which events you are referencing?

/milestone Next

**Comment by ncdc** [comment]
I'm guessing this was related to v1alpha1, when we had the embedded provider specs inside Machine. Now, we have split provider-specific details, including events, to provider-specific types.

Please reopen if needed.

/close
