### ISSUE TITLE
Add Addresses  into output list

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#950]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

per https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/331
we want to floating ip (access ip) to be showable in the 'get' command
this will require changes in cluster-api

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by ncdc** [comment]
Discussed in today's grooming call - closing for now as the node has this information. Please reopen with additional details if you still want this. Thanks!

/close
