### ISSUE TITLE
Create a feature group for Karpenter integration

### ISSUE THREAD

**Issue by elmiko** [kubernetes-sigs/cluster-api#9523]
As discussed during the [27 September 2023 meeting](https://youtu.be/5e5M06GIyEU) and also in the [Cluster API breakout meeting on Karpenter](https://www.youtube.com/watch?v=t1Uo18v8g48), I am proposing the formation of a feature group to investigate Karpenter integration with Cluster API.

There are several topics of interest that this feature group can answer:
* Should Cluster API integrate with Karpenter?
* What does "integration" mean?
* Will we create a Cluster API provider implementation of Karpenter?
* Will we create automation to help users deploy provider-specific versions of Karpenter?

The purpose of this issue is to gather support for the feature group, to identify possible meeting times, and to identify next steps.

As a started for the conversation, other feature groups have used the times immediately before or after the community meeting as their feature group meeting. I wonder if we might consider meeting immediately after the Cluster API community meeting?

**Comment by killianmuldoon** [comment]
Looking forward to seeing the output of this!

/triage accepted

**Comment by mtougeron** [comment]
I'd be interested in helping out with this.

**Comment by jonathan-innis** [comment]
The time immediately after or before the CAPI working group meeting sounds reasonable to me (would be starting at 9am or 11am PST (UTC−08:00) respectively I believe). Really excited to see what comes out of this collaboration! It definitely seems like there's a good number of areas that Karpenter and CAPI could hope to align on.

cc: @dims @ellistarn @njtran @tzneal @bwagner5 @jackfrancis

**Comment by nishant221** [comment]
If possible, I'd be interested in helping on this.

**Comment by faermanj** [comment]
Count me in please :)

**Comment by MaciekPytel** [comment]
I'd be interested in joining in, mostly to listen (as some of this may be interesting from cluster autoscaler perspective). Though 11am is a bit late in central european tz, so I'm not making any promises if we go with the later slot.

**Comment by ellistarn** [comment]
Excited to be part of this

**Comment by elmiko** [comment]
@ben-wilson-peak thanks, and good suggestion about updates. i will definitely update this issue once the PR for the feature group is posted.

as to broadcasting the activities of the feature group, i think we should follow the good practices of the other features groups, meaning:
* record all meetings, if no objections, and post results to the channel and on the cluster-api playlist
* keep meeting minutes
* share updates at the weekly cluster-api meeting

hopefully that will be sufficient for broadcasting what's happening. we could also post the mailing list after meetings if that would help.
