### ISSUE TITLE
Release tool review permissions for release team

### ISSUE THREAD

**Issue by g-gaston** [kubernetes-sigs/cluster-api#9524]
### What would you like to be added (User Story)?

As the release team, we would like to able to review and merge change to the release tool by ourselves without depending on maintainers, speeding up the development cycle.

### Detailed Description

We propose to add `lgtm` permissions for the release team and `approve` permissions for the release team leader, only for the [`release`](https://github.com/kubernetes-sigs/cluster-api/tree/main/hack/tools/release) folder.

Follow up from https://github.com/kubernetes-sigs/cluster-api/pull/9500#pullrequestreview-1644587693

@kubernetes-sigs/cluster-api-release-team

### Label(s) to be applied

/kind proposal
/area release

**Comment by killianmuldoon** [comment]
/triage accepted

Thanks @g-gaston for proposing this. I'm strongly in favor. Giving more responsibility for release processes and tools is the right approach.

**Comment by furkatgofurov7** [comment]
Thanks for opening the issue. 

I have no objections on the change either, as far as it speeds up processes and helps the release team.

**Comment by CecileRobertMichon** [comment]
+1

**Comment by sbueringer** [comment]
+1
