### ISSUE TITLE
Increase timeout for bootstrapping docker machine

### ISSUE THREAD

**Issue by alexander-demicev** [kubernetes-sigs/cluster-api#9530]
### What would you like to be added (User Story)?

As a user I would like to give more time to the Docker machine to bootstrap when not using CAPBK.

### Detailed Description

Currently, there is a 3 minute timeout for bootstrapping a Docker machine https://github.com/kubernetes-sigs/cluster-api/blob/main/test/infrastructure/docker/internal/controllers/dockermachine_controller.go#L307. We are using CAPD to test RKE2 bootstrap provider and it might take more than 3 minutes for bootstrap to succeed. We would like this timeout to be increased or made configurable.

cc @richardcase 

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by killianmuldoon** [comment]
/triage accepted

I think making this configurable with a 3 minute timeout is a good solution here.

**Comment by salasberryfin** [comment]
Since this has been stalled for a few months now, I'll be picking it up and pushing a PR with a proposal to make the timeout configurable.
