### ISSUE TITLE
Watch for `Cluster` resource in topology owned `MachineDeployment` controller

### ISSUE THREAD

**Issue by adityabhatia** [kubernetes-sigs/cluster-api#9532]
### What would you like to be added (User Story)?

As a user I would like to watch for the associated `Cluster` resource  in the topology based `MachineDeployment` controller. 
This watcher will ensure any changes on `Cluster` results in enqueuing a request for the corresponding  `MachineDeployment` (and subsequently `MachineSet`), thereby resulting in faster reconciliations, which is not the case currently.

### Detailed Description

This gap was noticed during the [finalizers test implementation](https://github.com/kubernetes-sigs/cluster-api/pull/9471#discussion_r1346599592) where `MachineDeployments` (and owned `MachineSet`)  were not getting reconcilied when Finalizers on `Cluster` were re-set.

### Label(s) to be applied

/kind feature
/area machinedeployment

**Comment by fabriziopandini** [comment]
/triage accepted
cc @killianmuldoon

**Comment by sbueringer** [comment]
Sounds good for the case where we want a reconcile to be triggered after Cluster unpause.
