### ISSUE TITLE
ClusterCacheTracker: Memory leak when kubeconfig is rotated too often, and CAPI is running on the workload cluster

### ISSUE THREAD

**Issue by ionutbalutoiu** [kubernetes-sigs/cluster-api#9542]
### What steps did you take and what happened?

Steps to reproduce the error:
* Deploy cluster-api with AWS provider.
* Create an EKS cluster (more info [here](https://cluster-api-aws.sigs.k8s.io/topics/eks)).
* Move cluster-api components to the new workload cluster via [clusterctl move](https://cluster-api.sigs.k8s.io/clusterctl/commands/move.html#clusterctl-move) command.
* Add some `MachinePool` and `AWSManagedMachinePool` resources.
* After some running time, observe `capi-controller-manager` logs being spammed, and pod memory increasing. 

We have a `v1.27.4` EKS cluster deployed via cluster-api, and we recently upgraded from `v1.3.7` to `v1.5.2`.

Everything went fine with the upgrade. However, after a week of running, I noticed the `capi-controller-manager` pod being spammed (about 300 logs per minute) with:
```
W1010 12:56:12.276785       1 reflector.go:533] k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: failed to list *v1.Node: Unauthorized
E1010 12:56:12.276815       1 reflector.go:148] k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.Node: failed to list *v1.Node: Unauthorized
W1010 12:56:12.713455       1 reflector.go:533] k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: failed to list *v1.Node: Unauthorized
E1010 12:56:12.713488       1 reflector.go:148] k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.Node: failed to list *v1.Node: Unauthorized
```

and pod memory usage being high.

Restarted the pod, everything is fine again. But slowly with time, the same issue reproduces again.

### What did you expect to happen?

Pod logs that are not being spammed, and pod memory not increasing over time.  

### Cluster API version

v1.5.2

### Kubernetes version

v1.27.4-eks-2d98532

### Anything else you would like to add?

I already investigated and solved this issue, but I want to bring more context on the issue first.

When deploying EKS Kubernetes clusters via cluster-api AWS provider (CAPA), there are two `kubeconfig` secrets being set:
* `<CLUSTER_NAME>-kubeconfig`
* `<CLUSTER_NAME>-user-kubeconfig`

The `<CLUSTER_NAME>-user-kubeconfig` is meant to be used by users, while `<CLUSTER_NAME>-kubeconfig` is being used internally by CAPI, and it's rotated every `sync-period`, since it contains an expiring token to access the EKS API. More details [here](https://cluster-api-aws.sigs.k8s.io/topics/eks/creating-a-cluster#kubeconfig).

When running cluster-api in the workload cluster, this code path causes a memory leak when `<CLUSTER_NAME>-kubeconfig` is rotated frequently:
https://github.com/kubernetes-sigs/cluster-api/blob/a82c340118994d52f009065665a5bd4c4e0d3528/controllers/remote/cluster_cache_tracker.go#L298-L330

Notice that in this part of the code, when CAPI is running in the workload cluster, the `t.createClient` is called twice:
1. https://github.com/kubernetes-sigs/cluster-api/blob/a82c340118994d52f009065665a5bd4c4e0d3528/controllers/remote/cluster_cache_tracker.go#L298-L299
2. https://github.com/kubernetes-sigs/cluster-api/blob/a82c340118994d52f009065665a5bd4c4e0d3528/controllers/remote/cluster_cache_tracker.go#L324-L325

However, the function `t.createClient` also starts a goroutine with the `clusterAccessor` cache:
https://github.com/kubernetes-sigs/cluster-api/blob/a82c340118994d52f009065665a5bd4c4e0d3528/controllers/remote/cluster_cache_tracker.go#L449-L450 

Using more verbose logging, I noticed that immediately after the goroutine cache starts, there's a cluster nodes watcher registered:
```
I1010 22:05:29.890187       1 reflector.go:287] Starting reflector *v1.Node (10h52m8.919938079s) from k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231
I1010 22:05:29.902920       1 reflector.go:323] Listing and watching *v1.Node from k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231
```

I believe this is happening, because we have the following watcher already registered on the `ClusterCacheTracker`:
https://github.com/kubernetes-sigs/cluster-api/blob/a82c340118994d52f009065665a5bd4c4e0d3528/exp/internal/controllers/machinepool_controller.go#L325-L331

However, looking in the `ClusterCacheTracker` code, this watcher is supposed to be started just once:
https://github.com/kubernetes-sigs/cluster-api/blob/a82c340118994d52f009065665a5bd4c4e0d3528/controllers/remote/cluster_cache_tracker.go#L541-L545

But, when I restart the `capi-controller-manager`, I see that the watcher registers twice for the same cluster. This is confirmed by seing this twice:
```
I1010 22:05:29.890187       1 reflector.go:287] Starting reflector *v1.Node (10h52m8.919938079s) from k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231
I1010 22:05:29.902920       1 reflector.go:323] Listing and watching *v1.Node from k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231
```

So, one of the goroutine is leaked.

This is happening because, in the initially mentioned code path, we start the cache twice. Before overwriting the cached client with the in-cluster configuration, we never stop the initial cache, and that runs continuously in the background.

I noticed that stopping the cache would also stop the goroutine that watches the nodes continuously.

This wouldn't be a memory leak problem if `kubeconfig` is not rotated frequently, since the `clusterAccessor` is never re-created. However, when the loaded `kubeconfig` expires, the `healthCheckCluster` fails, and the `clusterAccessor` is deleted:
https://github.com/kubernetes-sigs/cluster-api/blob/a82c340118994d52f009065665a5bd4c4e0d3528/controllers/remote/cluster_cache_tracker.go#L656-L668

This causes the `clusterAccessor` to be recreated on the next `Reconcile` loop, and the troublesome code path leaks another goroutine with the cluster node watcher. And this happens every time the loaded EKS cluster `kubeconfig` expires, and the `clusterAccessor` is recreated.

The log spam comes the fact that, after a long running time, we have a lot of leaked goroutines trying to list cluster nodes, with an expired `kubeconfig`.

### Label(s) to be applied

/kind bug
/area clustercachetracker

**Comment by killianmuldoon** [comment]
/triage accepted

Thanks for catching this and submitting a fix. I really appreciate the detailed description of the problem. Let's continue discussion primarily on the PR.

**Comment by sbueringer** [comment]
Thx for the great issue description, really really nice!

Reviewing the PR now (
