### ISSUE TITLE
Workload cluster is in pending state forever (Setting up with CAPD)

### ISSUE THREAD

**Issue by tholka-hypto** [kubernetes-sigs/cluster-api#9545]
### What steps did you take and what happened?

1. Created file - manager-cluster.yaml
```kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: manager-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.28.0
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
networking:
  ipFamily: ipv4
  apiServerPort: 6060
  apiServerAddress: 127.0.0.1
  serviceSubnet: "10.60.0.0/25" # 10.60.0.0 - 10.60.0.127
  # serviceSubnet: "10.60.0.128/25" # 10.60.0.128 - 10.60.0.255 # Saving this IP Range for future serviceSubnet needs
  podSubnet: "10.60.1.0/24" # 10.60.1.0 - 10.60.1.225
```
2. export KIND_EXPERIMENTAL_DOCKER_NETWORK=bridge
3. kind create cluster --config ./manager-cluster-api.yaml
4. CLUSTER_TOPOLOGY=true clusterctl init --infrastructure docker
5. clusterctl generate cluster workload-cluster --flavor development --infrastructure docker --kubernetes-version v1.28.0 --control-plane-machine-count=2 --worker-machine-count=4 > workload-cluster-api.yaml
6. kubectl apply -f workload-cluster-api.yaml
7. clusterctl describe cluster workload-cluster
For this last command, getting the error `Error: get InfraCluster reference from Cluster: cannot get object - object reference not set`
8. kubectl get cluster
```NAME               PHASE     AGE   VERSION
workload-cluster   Pending   20m   v1.28.0```

### What did you expect to happen?

Expected to see the cluster getting provisioned

### Cluster API version

Installed via `brew`. Version `1.5.2`

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.0", GitCommit:"855e7c48de7388eb330da0f8d9d2394ee818fb8d", GitTreeState:"clean", BuildDate:"2023-08-15T21:26:40Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/arm64"}


### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by stmcginnis** [comment]
One common thing when running a lot of cluster node containers locally in Docker is running out of system resources.  You're only creating a single node for your `kind` control plane, but then for your workload cluster you are creating 6 additional nodes. This can easily deplete available resources where the nodes fail to initialize.

This has happened a lot when just creating a kind [cluster with a lot of nodes](https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files). An interesting experiment might be to simplify things as a test and just spin up a 6 node kind cluster. If that fails to work, then CAPI/CAPD is out of the equation. It may also make it easier to troubleshoot what is happening.

If it does work, then at least you've eliminated one area of potential failures and it's easier to know to focus on what CAPD is doing.

**Comment by fabriziopandini** [comment]
IMO the scenario above with all those customizations for the kind node is not supported, and IMO we should not consider it unless there is a strong use case for it (currently it is not needed for the development/CI use cases CAPD is used for).

apiServerPort: 6060 + other network settings are probably simply not tested/not fully wired down the line e.g in Kubeadm templates, but I would classify this as a nice to have/low low priority.

I would instead say that KIND_EXPERIMENTAL_DOCKER_NETWORK=bridge should not be supported, it could drag us into annoying docker networking issues, and we steered away from this in the past simply using the default kind network

**Comment by fabriziopandini** [comment]
/close 
due to lack of activity
