### ISSUE TITLE
Speed up e2e tests by increasing concurrency / # of ginkgo nodes

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#9579]
This issue is about running our e2e tests with more ginkgo nodes / concurrency instead of 3.

I think this would improve our dev efficiency because we end up with a quicker feedback loop for e2e-full. It also allows us to add more e2e tests without being too worried about test durations.

For context: Slack: https://kubernetes.slack.com/archives/C8TSNPY4T/p1697730320651299

**Comment by sbueringer** [comment]
cc @kubernetes-sigs/cluster-api-release-team 

I'll open the PR for release-1.4. Happy if someone wants to take over the rest of the issue

**Comment by killianmuldoon** [comment]
Thanks!

/triage accepted

**Comment by sbueringer** [comment]
To mention it here. I think we can see 10 as an intermediate step to gather more experience with higher concurrency.

Once we moved all jobs to the EKS cluster, we can figure out what node size they are using, use higher CPU request/limits and further increase our concurrency

**Comment by sbueringer** [comment]
Given that the tests were not really stable with concurrency 10. I'll until after the EKS move. Possible next steps then:
* Increase job resources to 14 cores => re-run the tests
