### ISSUE TITLE
Update golangci-lint to v1.55.2

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#9589]
Golangci-lint has a new release - v1.55.0

The release notes are here: https://github.com/golangci/golangci-lint/releases/tag/v1.55.0

After doing an initial test it looks like there's a bunch of new findings - some of them likely spurious and better to ignore. CAPI should update to the new version when possible.

**Comment by killianmuldoon** [comment]
Note v1.55.1 has now been released.

**Comment by chiukapoor** [comment]
@adityabhatia are you working on it? If not may I take this over?

**Comment by adityabhatia** [comment]
> @adityabhatia are you working on it? If not may I take this over?

Thanks for the offer @chiukapoor, I will take care of this.

**Comment by chrischdi** [comment]
The PR got merged and this is done right?

However, there is already v1.55.2

**Comment by furkatgofurov7** [comment]
/retitle Update golangci-lint to v1.55.2

@adityabhatia do you want to take care of it again? If not, feel free to unassign, thanks!

**Comment by adityabhatia** [comment]
@furkatgofurov7 I can take this

**Comment by killianmuldoon** [comment]
/close

This should be done in #9740
