### ISSUE TITLE
Sync node version as a label in the Node object for Pod Scheduling

### ISSUE THREAD

**Issue by musaprg** [kubernetes-sigs/cluster-api#9591]
### What would you like to be added (User Story)?

As a developer/operator, I would like to have a functionality for the Machine controller to put the kubelet version in labels, something like `node.cluster.x-k8s.io/version`. This information would be useful when we want to change the configuration of Pods based on the node version.

### Detailed Description

Originally I thought it'd be good to have this functionality on the kubelet side, however, after discussions in [this thread](https://kubernetes.slack.com/archives/C0BP8PW9G/p1697993905274979), it would be better to have such functionality on the controller side.

Our team previously faced an issue in fluentd regarding log format changes during cluster upgrades from 1.23 to 1.24, and we had the motivation to schedule different fluentd pods with different configs based on the node version. I believe we will have similar motivations in the near future, and it could be worthwhile to have such information for scheduling purposes.

I'd say this could be done by implementing another controller outside of CAPI, but let me file this issue to know if it's really worthwhile to have in CAPI.

### Label(s) to be applied

/kind feature
/area machine

**Comment by killianmuldoon** [comment]
It's possible to have this done by manually setting the label in the MachineDeployment spec using [metadata propagation](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/metadata-propagation.html#machine) which I think is the best way to manage this right now - have you considered using that mechanism?

**Comment by musaprg** [comment]
> It's possible to have this done by manually setting the label in the MachineDeployment spec using [metadata propagation](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/metadata-propagation.html#machine)

Thanks. Yes, we could achieve the same goal by implementing it as part of our infrastructure provider, putting the version information of the Machine in the label of Machine or MachineDeployment.

**Comment by killianmuldoon** [comment]
You could also add this to templates when creating them for different versions. Are you happy enough with the solution to close this issue?

**Comment by musaprg** [comment]
Yes, let me try with it. Thanks!
