### ISSUE TITLE
Spec.ObjectMeta in Machine is not a valid path

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#96]
_From @karan on January 24, 2018 21:40_

Machine actuator currently looks for changes to spec.metadata [1], but that field doesn't exist [2]. So changes to `generateName` won't WAI for example.

Two possible solutions:
1. Look for machine.metadata in the actuator
2. Pull or reference the metadata block in `spec`.

[1] https://github.com/kubernetes/kube-deploy/blob/master/cluster-api-gcp/cloud/google/machineactuator.go#L471
[2] https://github.com/kubernetes/kube-deploy/blob/master/cluster-api-gcp/machines.yaml#L28

_Copied from original issue: kubernetes/kube-deploy#515_

**Comment by rsdcastro** [comment]
_From @karan on January 24, 2018 21:44_

/label cluster-api-gcp

**Comment by trawler** [comment]
This is an old issue and the links above are broken... but looking deeper into this, I can't find on first glance what might be wrong.
The issue refers to this line: https://github.com/kubernetes-sigs/cluster-api/blob/master/cloud/google/machineactuator.go#L581  but the Machine.Spec reference (https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/apis/cluster/v1alpha1/machine_types.go#L46) points to the MachineSpec struct, which has a proper objectmeta field.

**Comment by ashish-amarnath** [comment]
Discussed on slack. This issue is obsolete and can be closed.
/cc @rsdcastro  Can you please close this issue?
