### ISSUE TITLE
configuable timeoutKubeconfigReady

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/cluster-api#961]
/kind feature

**Describe the solution you'd like**
For deploying a different release of Kubernetes, e.g. ICP, the default time out for 20m may be not enough in waiting for cluster ready.

It should be better configurable by command line options.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by wanghh2000** [comment]
@xunpan You want a parameter like "--timeoutForWaitingTargetCluster 30" from Clusterctl to update timeoutKubeconfigReady in case creating a cluster is very long process. Right?

**Comment by gyliu513** [comment]
@wanghh2000 @xunpan You can post a PR like this https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/262 which was fixed by @jichenjc for OpenStack.

**Comment by wanghh2000** [comment]
@gyliu513  
Shouldn't the timeout be a common feature from `clusterctl` for all provider projects? 
Do you mean that add a timeout in each provider to handle instead of a common `clusterctl` parameter?

**Comment by jichenjc** [comment]
that's doable, It will increase a lot of options since we have a set of timeout options...
and our provider is running in container (statefulset), we need transfer that from clusterctl exec file to the container as well

**Comment by wanghh2000** [comment]
@jichenjc OK, I will reference what you did.
