### ISSUE TITLE
HA requirement for ICP Kubernetes distribution 

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/cluster-api#962]
/kind feature

**Describe the solution you'd like**
ICP is an IBM kubernetes release. It implements HA with below dependency which may need cluster-api support
1. create load balancer after control plane machines created
    Shall we have any callback mechanism in `clusterctl` to add dependencies checking for different Kubernetes distribution?
2.  wait for all control plane hosts ready before kubenetes installation
    Currently, only 1st control plane node is created by `clusterctl` in bootstrap cluster. Shall we create all control plane (with option flag control is fine) hosts instead of 1st one only by bootstrap cluster? 

cc @detiber @vincepri 
fyi @gyliu513 

**Anything else you would like to add:**

**Comment by alexeldeib** [comment]
Is this a hard dependency, e.g. there is no way to attach machines to the load balancer after creation? The natural thing to do to me is create the LB after you have 1 control plane node, pivot from bootstrap to remote, then attach the next 2 control plane nodes to the LB.

To me, this seems like a provider-specific detail which should be handled accordingly in whatever reconcile loop the provider is responsible for. 

Other providers have infrastructure dependencies between their resources as well and account for this in their reconcilers/actuators. A common example is pre-creating IP or other networking resources (ironically in the opposite order of dependency from what you describe).

**Comment by timothysc** [comment]
closing, we heading into a heavy refactor for v1alpha3 regarding CLI UX and control plane sets are going to be a 1st classed object.
