### ISSUE TITLE
Re-enable `goconst` linter for test files

### ISSUE THREAD

**Issue by adityabhatia** [kubernetes-sigs/cluster-api#9623]
In this [PR](https://github.com/kubernetes-sigs/cluster-api/pull/9622) `goconst` linter was disabled for test files - to exclude test files from creating lint issues, for a string value with > 3 occurrences. 

However most of these string values in test files enhance the readability if the respective test cases. E.g. https://github.com/kubernetes-sigs/cluster-api/blob/main/bootstrap/kubeadm/types/utils_test.go#L260

The linter should not be completely excluded for tests in the long term. 
A solution to either fix all lint issues or increase the occurrence default value should be implemented.

**Comment by killianmuldoon** [comment]
/triage accepted 

Thanks!

**Comment by killianmuldoon** [comment]
/help

First steps to figure this out are to try some of the other configuration options for `goconst` and see what the tradeoffs are.

**Comment by sbueringer** [comment]
> Increase the occurrence default value should be implemented.

Sounds reasonable

**Comment by vincepri** [comment]
fwiw, I'm fine, for tests, to have this disabled

**Comment by vincepri** [comment]
Closing this, no need to have constants in tests unless absolutely necessary.

/close
