### ISSUE TITLE
Merge finalizer tests with default quick start tests

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#9636]
https://github.com/kubernetes-sigs/cluster-api/pull/9471 introduced new tests to check that finalizers were correctly re-reconciled in Cluster API.

After a week of runs there's been no failures in this test. We should consider merging these tests with the basic CAPI e2e tests in order to reduce the total number of tests we run and the length of the `e2e-full` test run. 

Let's gather another week of data before moving ahead with this, and consider merging after Nov. 6th.

Ref: https://github.com/kubernetes-sigs/cluster-api/pull/9471#pullrequestreview-1659797987

**Comment by killianmuldoon** [comment]
/triage accepted

@adityabhatia in case you want to pick this up :slightly_smiling_face:.

**Comment by adityabhatia** [comment]
> /triage accepted
> 
> @adityabhatia in case you want to pick this up 🙂.

Sure 🙂
/assign
