### ISSUE TITLE
don't abort the cluster creation when applying addon failed

### ISSUE THREAD

**Issue by chenzhiwei** [kubernetes-sigs/cluster-api#965]
/kind feature

**Describe the solution you'd like**

Since the addon can be deployed after the Kubernetes core started and cluster-api does not do any special setting for deploying addon, so I think it is better to not abort the cluster creation when applying addon failed.

Users can correct the addon content or tweak the Kubernetes configuration, then deploy the addon.

**Anything else you would like to add:**

addon is optional and users have alternative method to install addon after cluster creation.

**Comment by vincepri** [comment]
@chenzhiwei Can you please fill out the template as described? 

I'm not sure if this actually should fail with a warning given that addons often contain networking related components (like Calico) which are required to build a cluster.

**Comment by chenzhiwei** [comment]
@vincepri Network component is optional in Kubernetes core, otherwise it will be part of Kubernetes core.

My main concern is if there is an error in the optional addon, I need to delete the whole cluster and re-deploy.  Why not just throw a warning message and let users decided they want to re-create the cluster or re-deploy addon?

**Comment by timothysc** [comment]
closing, we heading into a heavy refactor for v1alpha3 regarding CLI UX.
