### ISSUE TITLE
Add metadata labels/annotations to secrets owned by cluster api objects 

### ISSUE THREAD

**Issue by viveksyngh** [kubernetes-sigs/cluster-api#9651]
### What would you like to be added (User Story)?

As a user I would like to select secrets owned by CAPI object by custom labels or annotations.

### Detailed Description

We have a use case to select all related resources of control plane and machine deployment based on custom labels added in `spec.topology.conyrolplane.metadata.labels` and `spec.topology.workers.machineDeployments[].metadata.lables` But these labels and annotations are not added to the secrets objects owned by these related objects.  

Is it possible to add these labels and annotations on secrets ? 

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by viveksyngh** [comment]
In our case we are looking to select secrets for ca certficates, kubeconfig, bootstrap token with labels other than the cluster name (`cluster.x-k8s.io/cluster-name`)

**Comment by killianmuldoon** [comment]
I understand the request now - something like label propagation from Cluster's to all owned objects. That doesn't exist in CAPI today. The current state of metadata propagation is described here: https://cluster-api.sigs.k8s.io/developer/architecture/controllers/metadata-propagation.html


/triage accepted 

/kind feature

**Comment by enxebre** [comment]
>We have a use case to select all related resources of control plane and machine deployment based on custom labels added in spec.topology.conyrolplane.metadata.labels and spec.topology.workers.machineDeployments[].metadata.lables

@viveksyngh could you elaborate on the use case?

**Comment by enxebre** [comment]
>We have a use case to select all related resources of control plane and machine deployment based on custom labels added in spec.topology.conyrolplane.metadata.labels and spec.topology.workers.machineDeployments[].metadata.lables

@viveksyngh could you elaborate on the use case?

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

We don't have yet feedback about an actual use case for this https://github.com/kubernetes-sigs/cluster-api/issues/9651#issuecomment-1838113133, and no one else showed interest.

/close
