### ISSUE TITLE
Fix DockerMachinePool rollout flow and deletion behaviour

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#9655]
When using Docker infrastructure, when rolling out a MachinePool the underlying infrastructure is deleted straight away without allowing for any other deletion steps e.g. draining the node, deleting the node.

https://github.com/kubernetes-sigs/cluster-api/blob/a3149578a0efb49b44d7607f847b4d596d260642/test/infrastructure/docker/exp/internal/docker/nodepool.go#L92

Once the underlying infrastructure is deleted the MachinePool controller is supposed to clean up the Kubernetes `Node` as `retired`:

https://github.com/kubernetes-sigs/cluster-api/blob/051b00606dfacd61fbff687155e485040c1b0461/exp/internal/controllers/machinepool_controller_noderef.go#L120-L123

This flow seems to work fine for certain MachinePool use cases, but it means that self-hosted clusters running with MachinePools can go offline for an extended period. 

As described in https://github.com/kubernetes-sigs/cluster-api/issues/9522#issuecomment-1785542439, deleting of the underlying infrastructure can kill CAPI management components - if they're running on a DockerMachinePool backed node. The pod and node are stopped without informing Kubernetes, which waits until the `pod-eviction-timeout` has expired to bring the management components back into a working state.

This is a substantial bug in self-hosted clusters using DockerMachinePools. I'm not sure of the state in other infrastructure providers, or whether the self-hosted case is of interested and tested in other infrastructure providers for MachinePools.

The fix for this bug may include changes to the core MachinePool controller. It's not clear to me this bug is strictly in the implementation of the DockerMachinePool controller or in the design of the MachinePool rollout flow.

 
/kind bug

**Comment by CecileRobertMichon** [comment]
I believe @Jont828's PR to implement DockerMachinePool Machines (#8842) may be fixing this behavior

**Comment by CecileRobertMichon** [comment]
This was fixed by #8842 

/close
