### ISSUE TITLE
Failed to move machine from bootstrap cluster

### ISSUE THREAD

**Issue by posox** [kubernetes-sigs/cluster-api#966]
/kind bug

**Problem:**
Master machine cannot be moved from bootstrap cluster because machine cannot be force deleted from cluster. Cluster api uses the following code for force delete machine:

`clusterclient.go:`
```
 machine.SetFinalizers([]string{})
 if _, err := c.clientSet.ClusterV1alpha1().Machines(namespace).Update(machine); err != nil {
     return errors.Wrapf(err, "error removing finalizer for Machine %s/%s", namespace, name)
 }
 if err := c.clientSet.ClusterV1alpha1().Machines(namespace).Delete(name, newDeleteOptions()); err != nil {
     return errors.Wrapf(err, "error deleting Machine %s/%s", namespace, name)
 }
```

After machine update reconcile will be called and machine finalizer returns back because deletionTimestamp is not set. [code](https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/machine/machine_controller.go#L136)

**Steps to reproduce:**
1. Create cluster with one master and one node machine using `clusterctl`

**Expected result:**
Bootstrap cluster deployed and deleted after migtatinon machines to target cluster.

**Actual result:**
Master machine cannot be deleted from bootstrap cluster.

**Logs:**
```
I0529 12:13:45.747919    7042 pivot.go:373] Skipping to move deleted machine: "machine-name"
I0529 12:13:45.747950    7042 pivot.go:378] Preparing to move Machines: []
I0529 12:13:45.747985    7042 pivot.go:186] Preparing to delete MachineClasses: []
I0529 12:13:45.748005    7042 pivot.go:158] Deleting provider components from source cluster
```
**Environment:**

- Cluster-api version: master
- Minikube/KIND version: 0.3.0
- Kubernetes version: (use `kubectl version`): 1.14.2

**Comment by jichenjc** [comment]
I can create with following command:
```
 ./clusterctl create cluster --bootstrap-type kind --provider ibmcloud   -c examples/ibmcloud/out/cluster.yaml -m examples/ibmcloud/out/machines.yaml   -p examples/ibmcloud/out/provider-components.yaml
```

and delete the cluster succesfully using 
```
./clusterctl delete cluster --bootstrap-type kind  -p examples/ibmcloud/out/provider-components.yaml --bootstrap-type kind --kubeconfig kubeconfig
```

so is there pre-existing condition/error lead to the move steps error @posox ?  and which provider you are using? thanks

**Comment by detiber** [comment]
@posox which provider are you encountering this with? The pivot workflow should be scaling down the controllers before doing the force deletion, which should avoid the situation you are describing.

**Comment by posox** [comment]
@jichenjc I use openstack provider with custom patches.

**Comment by detiber** [comment]
Looking at the OpenStack provider, it seems to be using a `Deployment` instead of a `StatefulSet` for the controller deployment (https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/config/manager/deployment.yaml) and that would explain the behavior that you are seeing.

`clusterctl` could be extended to support `Deployments` or `StatefuleSets` here: https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/phases/pivot.go#L410-L431

**Comment by jichenjc** [comment]
I can take a look at this as I am working on openstack provider now

**Comment by posox** [comment]
@detiber thank you for clarification, need to switch to statefulsets in openstack provider.
