### ISSUE TITLE
Consolidate dualstack and e2e-full test jobs

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#9666]
Cluster API currently has two large e2e test runs - on main these are called  `[capi-e2e-main](https://github.com/kubernetes/test-infra/blob/b32aa0f189f4bc543753ce33f99ee88068dbfdaf/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-main.yaml#L70-L111)` and `[capi-e2e-dualstack-and-ipv6-main](https://github.com/kubernetes/test-infra/blob/b32aa0f189f4bc543753ce33f99ee88068dbfdaf/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-main.yaml#L112-L155C20)`. 

`capi-e2e-dualstack-and-ipv6-main` runs everything from capi-e2e-main and additionally runs the CAPI quickstart with IPv6 as well as quick-start with dualstack tests for dualstack IPv4 primary and dualstack IPv6 primary.

We should consider de-duplicating these tests by running the current `capi-e2e-dualstack-and-ipv6-main` config under  `capi-e2e-main` and removing the `capi-e2e-dualstack-and-ipv6-main` periodic and presubmit jobs.

Note: This can not be done before resolving https://github.com/kubernetes-sigs/cluster-api/issues/8816. That issue concerns flakes in the dualstack tests. These flakes signal that something is likely not right in our dualstack configuration.

**Comment by sbueringer** [comment]
@chrischdi @killianmuldoon  After #8816 has been fixed. Should we consider this issue again?

**Comment by sbueringer** [comment]
IIRC this would basically mean we'll use the dualstack job config for e2e-main and delete the dualstack job

**Comment by sbueringer** [comment]
Just to surface this here as well. #10135 is merged, we should be now unblocked to continue this issue

**Comment by killianmuldoon** [comment]
Started taking a look at this - do we want to remove the seperate ipv6 jobs on presubmits? Do we want to make the change for all branches? i.e. 1.5, 1.6, 1.7, main.

Getting used to the prowjob generator - great work on that @chrischdi

**Comment by sbueringer** [comment]
I would merge the ipv6 and the regular job, which IIRC basically means keeping the ipv6 job with the name of the other job.

I don't remember the exact fixes and how far we backported them. Ideally we would merge the jobs for all branches that are now stable (@chrischdi can probably provide more info on that)

**Comment by chrischdi** [comment]
The fix got cherry-picked back to 1.5, so should be on all relevant branches.

I think we can use [k8s-triage](https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*&xjob=.*-provider-.*) to compare two jobs we want to merge, to see if there errors are ~ the same or different.

* [cluster-api-e2e-main](https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-e2e-main)
* [cluster-api-e2e-dualstack-and-ipv6-main](https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-e2e-dualstack-and-ipv6-main)


Or used the combined query: https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-e2e-dualstack-and-ipv6-main%7C.*-cluster-api-e2e-main

**Comment by killianmuldoon** [comment]
https://github.com/kubernetes/test-infra/pull/32545

Should be ready for review now

**Comment by sbueringer** [comment]
Just want to want to emphasize. Thx @killianmuldoon @chrischdi for all the work on initially making IPv6 work until now getting rid of the additional IPv6 jobs!

**Comment by sbueringer** [comment]
@killianmuldoon @chrischdi I think this is done

**Comment by killianmuldoon** [comment]
Yeah this is done - closing.
