### ISSUE TITLE
Clusterctl move: Machine /: an empty namespace may not be set when a resource name is provided

### ISSUE THREAD

**Issue by Breee** [kubernetes-sigs/cluster-api#9668]
### What steps did you take and what happened?

I tried to execute clusterctl move 
code: 
```
export KUBECONFIG=./k8s-${K8S_CLUSTER}.kubeconfig
echo "### Init clusterctl"
clusterctl init --core cluster-api --bootstrap kubeadm --control-plane kubeadm --infrastructure hetzner
echo "### Move management capi objects to new cluster"
export KUBECONFIG=${HOME}/.kube/config
clusterctl move --config cluster.yaml --to-kubeconfig ./k8s-${K8S_CLUSTER}.kubeconfig
export KUBECONFIG=./k8s-${K8S_CLUSTER}.kubeconfig
```

output: 
```
### Init clusterctl
Fetching providers
Skipping installing cert-manager as it is already installed
### Move management capi objects to new cluster
Performing move...
Discovering Cluster API objects
Error: failed to get object graph: failed to check for provisioned infrastructure: action failed after 9 attempts: error reading Machine /: an empty namespace may not be set when a resource name is provided
```

### What did you expect to happen?

Move the management capabilties to the new cluster

### Cluster API version

In both clusters:  v1.5.3

$ clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"5b7c0f00d7d57d7f6fc385646bb3e79951d82c75", GitTreeState:"clean", BuildDate:"2023-10-24T16:15:39Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}

### Kubernetes version

$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.24.8+k3s1
WARNING: version difference between client (1.28) and server (1.24) exceeds the supported minor version skew of +

---------------

The cluster i move to it k8s version 1.28.3

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by killianmuldoon** [comment]
/triage accepted

Thanks for reporting this - I've seen something similar elsewhere, so there's at least a case that's not being handled correctly or possibly a more insidious bug here.

**Comment by arunmk** [comment]
We also hit this issue. Is there any further diagnosis or triage performed on this?

**Comment by arunmk** [comment]
@Breee could you tell me if the node from which you ran `clusterctl move` had any resource constraints? Could you mention the resourcing on that node.

We hit this error on a VM with 2core 4gb resources and I am wondering if that could be a cause.

**Comment by fabriziopandini** [comment]
/triage needs-information
in order to further investigate this issue we need additional information to figure out how to reproduce a use case when a machine without name/namespace enters in the set of objects to be moved (error reading Machine /).

would it be possible to reproduce the issue and run clusterctl with higher verbosity?

**Comment by arunmk** [comment]
@fabriziopandini this was a rare case that we encountered 1-2 times on a 2core4gb VM that was running with low resources (30% provisioned by default and increasing gradually on demand).

When we increased the size of the VM, we stopped hitting this. Since this was a pathological scenario for us, we did not investigate further and moved on.

**Comment by fabriziopandini** [comment]
/close
based on the comment above
we can eventually re-open if the issue happens again, but let's keep in mind the lead about resource constrained env

**Comment by Archisman-Mridha** [comment]
I'm currently facing this same issue :

```log
failed to get object graph: failed to check for provisioned infrastructure: action failed after 9 attempts: error reading Machine /: an empty namespace may not be set when a resource name is provided
```

**Comment by stefanpinterBE** [comment]
same here, what do? :(

edit:
i had this error in a test environment.
after deleting all my clusters with Openstack Magnum (with Cluster API driver) i saw that there still was an 'OpenStackMachine' that shouldn't have been there anymore.
I forcefully deleted it with kubectl/k9s - clusterctl move worked again after this

```
/usr/local/bin/clusterctl move --to-directory /home/iaas/clusterapi_backup/clusterctl_move_backup/2026-06-02_06 -n magnum-system -v 9
No default config file available
Moving to directory...
Discovering Cluster API objects
ConfigMap count=1
ClusterResourceSet count=4
KubeadmControlPlaneTemplate count=2
OpenStackMachineTemplate count=2
OpenStackClusterTemplate count=2
**OpenStackMachine count=1**
OpenStackServer count=1
KubeadmConfigTemplate count=2
Secret count=15
ClusterClass count=2
Total objects count=33
```
