### ISSUE TITLE
Add more helper func for topologymutation func

### ISSUE THREAD

**Issue by lubronzhan** [kubernetes-sigs/cluster-api#9669]
### What would you like to be added (User Story)?

More helper func in topologymutation variable 

### Detailed Description

Now the consumer needs to add helper function to unmarshal object from cluster topologymutation variable. It would be helpful to have more helper func in upstream to do it.

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by killianmuldoon** [comment]
/triage accepted 

Thanks for tackling this!
