### ISSUE TITLE
Replace `kubectl apply` in e2e test framework

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#9696]
In the CAPI e2e test framework currently the `kubectl` binary is called to apply yamls when creating Clusters. This would improve error reporting from this function which may help to debug #9688.

https://github.com/kubernetes-sigs/cluster-api/blob/2caa534c6450670e5b41a8c9d81cfbadac3b0350/test/framework/cluster_proxy.go#L248-L254

The easiest solution is to create objects in the test framework with a `client.Create` call either changing the underlying function. This is the approach in https://github.com/kubernetes-sigs/cluster-api/pull/9077. We can ignore `alreadyExists` errors to make the call retryable.

Alternatively we could use the actual rest call from `kubectl` which has the benefit of actually being an 'apply' call. The only issue with this is needing to import the `k8s.io/kubectl` library and it being [relatively complicated to implement](https://github.com/kubernetes/kubectl/blob/351ba8bb1c50284672b3cd5d78a7e3433b867f6b/pkg/cmd/apply/apply.go#L500).

**Comment by killianmuldoon** [comment]
My preference for a quick win is to just replace the `Apply` calls with `Create` calls - we can also deprecate the existing functions with call `kubectl`. 

If somebody specifically wants the apply functionality in the e2e framework it would be a good opportunity to contribute.

**Comment by killianmuldoon** [comment]
There's also a `Wait` in there which is unused and easy to remove.

**Comment by sbueringer** [comment]
A first implementation can be found here: https://github.com/kubernetes-sigs/cluster-api/pull/9695

/help

**Comment by adilGhaffarDev** [comment]
@sbueringer @killianmuldoon I can take this issue.

**Comment by sbueringer** [comment]
Thx!

/assign adilGhaffarDev

**Comment by cahillsf** [comment]
👋 @killianmuldoon touching back on this one -- should this issue still be pursued?  

i see one of the PRs to fix was closed with a comment indicating a separate PR was merged that covered this:
https://github.com/kubernetes-sigs/cluster-api/pull/9731#issuecomment-1892517224

**Comment by sbueringer** [comment]
I think if we find a good way to get rid of the os.exec with kubectl that would be good

**Comment by cahillsf** [comment]
@sbueringer 👋 i have a draft open for this (sloppy right now but want to make sure im going in the right direction)

the [current signature](https://github.com/kubernetes-sigs/cluster-api/pull/10442/files#diff-05d9572655aa068b141ab9c6b3731047b544e078e743e63e2a38073aa01f0402R254) accepts this `args ...string` parameter but the only actual arg that is in use for the e2e tests is `--selector`.   

the current logic of my update:
- parses the selector into a label matcher (defaulting to all if no selector passed)
- if the object doesn't exist `Create` it
- else, `Update` it

is this an approach that makes sense?  

if so I was thinking of updating the signature to something like:
`func (p *clusterProxy) CreateOrUpdate(ctx context.Context, resources []byte, labelSelectors ...string) error` 

is there any reason we would need to support other `kubectl` args if they are not currently in use?  any other thoughts/ideas as to how i should move forward also appreciated

**Comment by sbueringer** [comment]
Sounds good!
