### ISSUE TITLE
Use a pre-built node and master image

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#97]
_From @karan on January 24, 2018 19:18_

Currently, spinning up nodes and masters can take ~minutes. Most of this time is due to apt-get installs. We can cache these by using a pre-built image, and then simply run `kubeadm join`. This will make node startups faster.

Similar for master.

https://github.com/kubernetes/kube-deploy/blob/master/cluster-api-gcp/cloud/google/templates.go#L159

_Copied from original issue: kubernetes/kube-deploy#514_

**Comment by roberthbailey** [comment]
This issue was moved to kubernetes-sigs/cluster-api-provider-gcp#18
