### ISSUE TITLE
MD controller sync getNewMachineSet should not return nil as newMS after updating existingNewMS

### ISSUE THREAD

**Issue by chingchiaw** [kubernetes-sigs/cluster-api#970]
/kind bug

In pkg/controller/machinedeployments/sync.go `getNewMachineSet`, when there's an existing new MS, and its annotations or minReadySeconds need to be updated, the controller update the MS and return nil as new MS, and the error from r.Update as follows:

```golang
minReadySecondsNeedsUpdate := msCopy.Spec.MinReadySeconds != *d.Spec.MinReadySeconds
if annotationsUpdated || minReadySecondsNeedsUpdate {
	msCopy.Spec.MinReadySeconds = *d.Spec.MinReadySeconds
	return nil, r.Update(context.Background(), msCopy)
}
```

IMO it should not return nil, it should return the updated MS (msCopy).

https://github.com/kubernetes-sigs/cluster-api/blame/master/pkg/controller/machinedeployment/sync.go#L111

This was introduced in the major refactoring:
Oct 4 2019: Migrate to kubebuilder #494 (https://github.com/kubernetes-sigs/cluster-api/pull/494)
revision: 80129c0ca4eee12c47be0c04ea551fdd6f2cbaba

I looked up the old code before the PR and originally the line was this:
```golang
minReadySecondsNeedsUpdate := msCopy.Spec.MinReadySeconds != *d.Spec.MinReadySeconds
		if annotationsUpdated || minReadySecondsNeedsUpdate {
			msCopy.Spec.MinReadySeconds = *d.Spec.MinReadySeconds
			return dc.machineClient.ClusterV1alpha1().MachineSets(msCopy.ObjectMeta.Namespace).Update(msCopy)
	}
```

And this is the original Update method called:

```golang
// Update takes the representation of a machineSet and updates it. Returns the server's representation of the machineSet, and an error, if there is any.
func (c *machineSets) Update(machineSet *v1alpha1.MachineSet) (result *v1alpha1.MachineSet, err error) {
	result = &v1alpha1.MachineSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("machinesets").
		Name(machineSet.Name).
		Body(machineSet).
		Do().
		Into(result)
	return
}
```

So originally newMS was the updated MS.

I don't have a concrete repro of any issue resulted from this bug, but naively this seems to me an issue to fix.

**What did you expect to happen:**
The controller method should return msCopy and error from r.Update(..., msCopy) instead

**Anything else you would like to add:**
NA

**Environment:**

- Cluster-api version: all revisions after Oct 4, 2018's 80129c0ca4eee12c47be0c04ea551fdd6f2cbaba
- Minikube/KIND version: NA
- Kubernetes version: (use `kubectl version`): NA
- OS (e.g. from `/etc/os-release`): NA

**Comment by dlipovetsky** [comment]
@calebamiles and I looked at the code together. 

From the doc string of `getNewMachineSet`:
> // Returns a machine set that matches the intent of the given deployment. Returns nil if the new machine set doesn't exist yet.

Of course, L113 returns nil even though the new machine set _does_ exist. 

But none of the machine deployment tests fail because of this. So either those tests don't catch the issue, or it's not an issue (e.g. the caller of `getNewMachineSet` doesn't care that it returns a `nil` when it's supposed to return a MachineSet).

First thing to do might be to write a test for `getNewMachineSet`, and then to look at the machine deployment tests.

**Comment by calebamiles** [comment]
@detiber, maybe a short walkthrough of the code might be helpful. don't know if it makes sense to do so before or after the general cluster api code walkthrough

**Comment by calebamiles** [comment]
@dlipovetsky I got two examples of testing to look at
- https://github.com/DirectXMan12/kubebuilder/blob/docs/tutorial/test/project/controllers/cronjob_controller_test.go
- https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controller_integration_test.go

**Comment by dlipovetsky** [comment]
MachineDeployment from the CAPI book: https://cluster-api.sigs.k8s.io/common_code/machinedeployment_controller.html

**Comment by vincepri** [comment]
We'll go through some redesign/refactor of these controllers in the future #, I think it's safe to close this for now. 

Ref: https://github.com/kubernetes-sigs/cluster-api/issues/1689

/close
