### ISSUE TITLE
Request to support provisioning of managed clusters with major.minor version.

### ISSUE THREAD

**Issue by LochanRn** [kubernetes-sigs/cluster-api#9721]
### What would you like to be added (User Story)?

A user should have the ability to deploy a managed cluster with by just configuring the major and minor kubernetes version. 
Eg. k8s version = 1.26.
The cluster should be deployed with 1.26.6 if that is the latest available k8s patch version for 1.26 major minor version.

### Detailed Description

The feature is supported in some of the managed clusters like AKS. 
If the user configures the version as 1.26 the cluster will be created with 1.26.6. i.e the patch version is automatically picked by the cloud provider to be the latest available patch for the corresponding minor version. 

Currently this feature is not supported as the webhooks validate the k8s version [here](https://github.com/kubernetes-sigs/cluster-api/blob/b1b6896968686ac9fc21c0c1ef51ff5ac1e8031e/internal/webhooks/machine.go#L163) and expect a patch version.

### Label(s) to be applied

/kind feature
/area managedclusters
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by fabriziopandini** [comment]
/close

Due to lack of progress/ lacks enough active contributors to adequately respond to all issues
