### ISSUE TITLE
"gogo/protobuf" is deprecated

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes-sigs/cluster-api#9743]
### What would you like to be added (User Story)?

**cluster-api** using "github.com/gogo/protobuf" and it is announced as deprecated.
What is plan to find replacement of this library. 

### Detailed Description

"github.com/gogo/protobuf" is deprecated

### Label(s) to be applied

/kind feature

**Comment by sbueringer** [comment]
gogo/protobuf is an indirect dependency of Cluster API that we inherit mainly from etcd, k8s.io, Prometheus and viper. Until all of these projects found a replacement there is nothing that we can do.

```go
github.com/spf13/viper@v1.17.0 github.com/gogo/protobuf@v1.3.2
go.etcd.io/etcd/api/v3@v3.5.10 github.com/gogo/protobuf@v1.3.2
go.etcd.io/etcd/client/v3@v3.5.10 github.com/gogo/protobuf@v1.3.2
k8s.io/api@v0.28.3 github.com/gogo/protobuf@v1.3.2
k8s.io/apiextensions-apiserver@v0.28.3 github.com/gogo/protobuf@v1.3.2
k8s.io/apimachinery@v0.28.3 github.com/gogo/protobuf@v1.3.2
k8s.io/apiserver@v0.28.3 github.com/gogo/protobuf@v1.3.2
k8s.io/cli-runtime@v0.28.3 github.com/gogo/protobuf@v1.3.2
k8s.io/client-go@v0.28.3 github.com/gogo/protobuf@v1.3.2
k8s.io/cluster-bootstrap@v0.28.3 github.com/gogo/protobuf@v1.3.2
k8s.io/component-base@v0.28.3 github.com/gogo/protobuf@v1.3.2
k8s.io/component-helpers@v0.28.3 github.com/gogo/protobuf@v1.3.2
k8s.io/kms@v0.28.3 github.com/gogo/protobuf@v1.3.2
k8s.io/kubectl@v0.28.3 github.com/gogo/protobuf@v1.3.2
k8s.io/metrics@v0.28.3 github.com/gogo/protobuf@v1.3.2
sigs.k8s.io/controller-runtime@v0.16.3 github.com/gogo/protobuf@v1.3.2
github.com/spf13/viper@v1.7.0 github.com/gogo/protobuf@v1.2.1
github.com/prometheus/common@v0.4.0 github.com/gogo/protobuf@v1.1.1
github.com/prometheus/tsdb@v0.7.1 github.com/gogo/protobuf@v1.1.1
```

**Comment by tamilselvan1102** [comment]
Dependency is there in cluster-api as well.
https://github.com/kubernetes-sigs/cluster-api/blob/main/go.mod#L88C2-L88C2

**Comment by sbueringer** [comment]
Yes and it is a indirect dependency: `github.com/gogo/protobuf v1.3.2 // indirect`

The only way we can get rid of it by ourselves is dropping dependencies to etcd / k8s.io / controller-runtime / viper / prometheus which would make Cluster API basically useless :)
