### ISSUE TITLE
Remove occurences of conditions.WithStepCounterIf(false) 

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api#9754]
> conditions.WithStepCounterIf(false) doesn't seem to do anything as we always pass in false (?)
> If I'm right, let's get rid of all other occurences of this (ideally in a separate PR I think)

Following up from @sbueringer's comment in https://github.com/kubernetes-sigs/cluster-api/pull/9725, we should check if we can remove all occurrences of `WithStepCounterIf` when the bool parameter is hardcoded to false.

**Comment by CecileRobertMichon** [comment]
@mcbenjemaa there are a couple more occurrences of `conditions.WithStepCounterIf(false)` in the codebase, e.g. in the MachinePool controller, do you want to take a stab at removing those as well?

/reopen

**Comment by sbueringer** [comment]
@CecileRobertMichon Are you sure? I checked during review and now again and I can't find them.

**Comment by mcbenjemaa** [comment]
The hardcoded conditions are removed, but do you mean replacing the other ones?

**Comment by CecileRobertMichon** [comment]
Oh I guess it's because https://github.com/kubernetes-sigs/cluster-api/pull/9725 hasn't merged yet...

I can remove the occurrence it's adding in the PR then, all good! Thank you @mcbenjemaa 

/close
