### ISSUE TITLE
self-hosted clusters using ClusterClass, pivot test is flaky (Timed out after 180.000s.)

### ISSUE THREAD

**Issue by adilGhaffarDev** [kubernetes-sigs/cluster-api#9785]
### Which jobs are flaking?

- periodic-cluster-api-e2e-dualstack-and-ipv6-release-1-6
- periodic-cluster-api-e2e-main
- periodic-cluster-api-e2e-mink8s-release-1-6

### Which tests are flaking?

- capi-e2e [It] When  testing Cluster API working on self-hosted clusters using ClusterClass  [ClusterClass] Should pivot the bootstrap cluster to a self-hosted  cluster

- capi-e2e [It] When testing Cluster API working on self-hosted clusters using ClusterClass with a HA control plane [ClusterClass] Should pivot the bootstrap cluster to a self-hosted cluster

### Since when has it been flaking?

not sure but my guess is when this fix was merged: https://github.com/kubernetes-sigs/cluster-api/pull/8842 

### Testgrid link

https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*&xjob=.*-provider-.*#1e9db4e70dcbabb9d305

### Reason for failure (if possible)

This looks like it is just a timeout issue. Testing is failing at `Waiting for cluster self-hosted-2gvtgc/self-hosted-w6v54m to be deleted` after `clusterctl move`. Need to investigate more to give any concrete reason.

### Label(s) to be applied

/kind flake
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by fabriziopandini** [comment]
@adilGhaffarDev it seems that flakes in self-hosted tests have been addressed.
Can we close this issue?

**Comment by adilGhaffarDev** [comment]
yes, we can close this one. I am not seeing this anymore.
