### ISSUE TITLE
Fix download instructions for clusterawsadm in the quick start

### ISSUE THREAD

**Issue by vigneshp826** [kubernetes-sigs/cluster-api#9795]
### What steps did you take and what happened?

`curl.exe -L https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v2.3.0/clusterawsadm-windows-amd64 -o clusterawsadm.exe`

I tried above command in windows to install clusterawsadm & clusterctrl cli's which failed in proper software installation.

`PS C:\Program Files (x86)> clusterawsadm
Program 'clusterawsadm.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1`

### What did you expect to happen?

`PS C:\Program Files (x86)> clusterawsadm
clusterawsadm provides helpers for bootstrapping Kubernetes Cluster`

I tweaked the installation command to `curl.exe -L https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v2.3.0/clusterawsadm-windows-amd64.exe -o clusterawsadm.exe` and it worked

### Cluster API version

v1beta1

### Kubernetes version

1.21

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
@vigneshp826 Sorry what is the difference? As far as I can tell "curl.exe -L https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v2.3.0/clusterawsadm-windows-amd64 -o clusterawsadm.exe" is the same in both cases

**Comment by vigneshp826** [comment]
@sbueringer Sorry. Now edited my original comment. `.exe` seems to be missing from the download URL which gives trouble.
