### ISSUE TITLE
Make Machine Controller Pod Version Not Serial

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#98]
_From @jessicaochen on January 11, 2018 17:17_

Having a serial machine controller pod version makes parallel contribution more difficult. One needs to figure out a unique name for dev pods to avoid stepping on other contributor's toes. When pushing the official image, coordination is needed to not push the same version number. If we make the pod version based on something less serial (eg. commit hash like test-infra does), that will help with making it easier to contribute.

_Copied from original issue: kubernetes/kube-deploy#483_

**Comment by roberthbailey** [comment]
This hasn't been an issue recently. We can re-open if it comes up again.

/close
