### ISSUE TITLE
Support Managed Kubernetes Provider

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#980]
/kind feature
/kind question

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

I found that Cluster API is focusing on support infrastructure provider, like AWS, Azure, OpenStack, IBM Cloud etc. Any plan to enable Cluster API can also support hosted Kubernetes provider, like AKS, IKS, GKE etc?

/cc @vincepri @detiber

**Comment by ncdc** [comment]
@gyliu513 yes, we do hope to support this when we implement control plane lifecycle management.

**Comment by gyliu513** [comment]
@ncdc any design or document that I can refer for `control plane lifecycle management`?

**Comment by jichenjc** [comment]
+1 for some reference doc share :)

**Comment by ncdc** [comment]
They haven't been written yet. This is the most recent update I've seen: https://discuss.kubernetes.io/t/cluster-api-controlplane-lifecycle-management-workstream/5956/2?u=ncdc

**Comment by gyliu513** [comment]
@hardikdr I found that you had some words at https://discuss.kubernetes.io/t/cluster-api-controlplane-lifecycle-management-workstream/5956 for managed kuberntes, any progress for this? Thanks.

**Comment by hardikdr** [comment]
@gyliu513  Thanks for initiating the discussion.
We had started the investigation around `control-plane-lifecycle management` in-general as part of the workstreams, but there haven't been major progress after workstream-approach was stopped. 

Essentially we wanted to investigate 3 different approaches of managing the control-planes using Cluster-API  - [doc](https://docs.google.com/document/d/1hTDKdWXTHUwm_G2OSXCNoI-FO1L5E825bJpY7D_u6CM/edit#)
1. Machine-based: Dedicated master-machines for control-planes, more or less the way it is right now in ClusterAPI.
2. Pod-based: Control-planes of worker-clusters hosted in the management cluster. [proposal](https://docs.google.com/document/d/1j1mNK48lYxLEAUnNuVFYbDT9IVcmoiadYr3xgavjtj8/edit#heading=h.naa0d6ofs1l7)
3. Control-planes hosted in managed kubernetes services like GKE, EKS and so on.

I'd be more than happy to re-start the discussions and collaborate further.

**Comment by detiber** [comment]
This is going to be one of the primary discussions during the upcoming v1alpha3 planning. The starting point will be to pick up where the workstream ended

**Comment by gyliu513** [comment]
Thanks @hardikdr @detiber , let me check what is the progress and current design first provided by @hardikdr .

@hardikdr I would love to work with you for this, will go back to you after I catch up the design and proposals.

**Comment by richardcase** [comment]
Really interested in the managed kubernetes service (AKS, EKS) scenario. 

We have customers that want to adopt capi and as part of that adoption they want to be able to utilise managed services (as well as the current providers).

**Comment by huxiaoliang** [comment]
@gyliu513  @ncdc @detiber  I draft a proposal [here](https://github.com/kubernetes-sigs/cluster-api/pull/2045),  could you please show your comments and point to the right direction so that I can move on, thanks in advance.

**Comment by vincepri** [comment]
/remove-lifecycle frozen 
/kind proposal
/help

As pointed out in https://github.com/kubernetes-sigs/cluster-api/pull/2045#issuecomment-610540856 this could turn out to be a documentation issue which we can tackle separately.

**Comment by vincepri** [comment]
As per April 27th 2020 community guidelines, this project follows the process outlined in https://github.com/kubernetes-sigs/cluster-api/blob/master/CONTRIBUTING.md#proposal-process-caep for large features or changes.

Following those guidelines, I'll go ahead and close this issue for now and defer to contributors interested in pushing the proposal forward to open a collaborative document proposal instead, and follow the process as described.

/close
