### ISSUE TITLE
[question] support deployment in provider components 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api#983]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

this actually comes from https://github.com/kubernetes-sigs/cluster-api/issues/966
as @detiber pointed out, the question is openstack provider is using deployment
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/config/manager/deployment.yaml

and it's ignored by https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/phases/pivot.go#L410-L431 because cluster-api only support stateful set

so the question is whether we should add deployment support or ask proivder to mandatory use statefulset..

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by ncdc** [comment]
I believe one motivation for using StatefulSet is that it guarantees you can't have multiple replicas of the same pod running at the same time, whereas this isn't necessarily true with Deployment (am I stating that correctly, @detiber?). If this is true, I think the rationale was to avoid multiple instances of the controllers from trying to act on the same objects. As best I can tell, controller-runtime's `Manager` enables leader election by default, so maybe we could start supporting Deployments?

**Comment by detiber** [comment]
That is indeed the motivation and the reason for StatefulSets being used by default by Kubebuilder. 

While it is true that controller-runtime supports leader election, we do not currently set the options to enable it by default (either in the cluster-api common controller manager or most downstream provider controller managers).

**Comment by ncdc** [comment]
I could have sworn it was enabled by default. Maybe I misread something?

On Jun 6, 2019, at 2:25 PM, Jason DeTiberus <notifications@github.com<mailto:notifications@github.com>> wrote:


That is indeed the motivation and the reason for StatefulSets being used by default by Kubebuilder.

While it is true that controller-runtime supports leader election, we do not currently set the options to enable it by default (either in the cluster-api common controller manager or most downstream provider controller managers).

**Comment by detiber** [comment]
Based on how we currently initialize the manager: https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/manager/main.go#L52-L55 We get the default value for the Options struct, which is `false`: https://github.com/kubernetes-sigs/controller-runtime/blob/f1eaba5087d69cebb154c6a48193e6667f5b512c/pkg/manager/manager.go#L101

**Comment by jichenjc** [comment]
so because of above conclusion (the default is false for leader election) that means the best way might still be stateful set for each provider in order to avoid the concurrent issue? @detiber @ncdc , then I will change openstack provider settings...

**Comment by detiber** [comment]
I think that is probably the safest bet for now

**Comment by jichenjc** [comment]
got it , thanks for the confirm
