### ISSUE TITLE
Updating the dns imageTag causes KCP rolling update

### ISSUE THREAD

**Issue by Levi080513** [kubernetes-sigs/cluster-api#9832]
### Detailed Description
Currently we can update the coredns version by updating `KCP.Spec.KubeadmControlPlaneSpec.kubeadmConfigSpec.clusterConfiguration.DNS.imageTag`, but this will cause a rolling update of the control plane nodes.

KCP use the following method to update the coredns version, this does not require rolling updates of control plane nodes, or can we skip checking this field when checking `MachinesNeedingRollout`? 
https://github.com/kubernetes-sigs/cluster-api/blob/9d36ddcbf8381574a86cebeacdcdfc85bafa71e9/controlplane/kubeadm/internal/controllers/controller.go#L466-L469

### Label(s) to be applied

/area provider/control-plane-kubeadm

**Comment by sbueringer** [comment]
If I see correctly we can simply set the fields of both to nil before running reflect.DeepEqual: https://github.com/kubernetes-sigs/cluster-api/blob/359f92e09f29bae6ab823c978a338920041c864b/controlplane/kubeadm/internal/filters.go#L198

**Comment by Levi080513** [comment]
Perhaps it is necessary to synchronize kubeadmConfiguration to avoid configuration differences?

**Comment by sbueringer** [comment]
> Perhaps it is necessary to synchronize kubeadmConfiguration to avoid configuration differences?

Not as far as I'm aware. The configs won't be identical but the ones on the Machine will be still accurately the one the Machine was created with.

**Comment by Levi080513** [comment]
It is my fault I didn't make it clear. I mean do we need to synchronize CP Machinde kubeadmConfig CR and Machine `controlplane.cluster.x-k8s.io/kubeadm-cluster-configuration` annotation, but now it seems that is not necessary.

**Comment by sbueringer** [comment]
I think we're fine. But I take a closer look at the PR

**Comment by sbueringer** [comment]
/close

#9857 was merged (no idea why GitHub didn't close the issue automatically, PR description looks correct)
