### ISSUE TITLE
 Improve the Netlify access model

### ISSUE THREAD

**Issue by cahillsf** [kubernetes-sigs/cluster-api#9850]
Right now only limit people have access to the Netlify and for doing any thing regarding Netlify the people with access have to do some manual work. There is scope to improve this, either through more automation or more shared access.

Carryover from: https://github.com/kubernetes-sigs/cluster-api/issues/9104

**Comment by cahillsf** [comment]
@nawazkh/@furkatgofurov7 you're listed for this one, want to continue pushing this forward? also would appreciate your feedback on prioritization for the issue board 🙇

**Comment by fabriziopandini** [comment]
My two cents is to not over-engineering this but just to document the process because ultimately we need to access Netlify only one or two times a year (or even less)

**Comment by sbueringer** [comment]
Just want to mention that Netlify access is out of our control. I think you'll have to talk to sig-contribex if you want to change something how all of this works.

**Comment by cahillsf** [comment]
re the docs, for a start might be helpful to provide some direction for who currently has access (docs seem to just say "someone with access to Netlify" [src](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#ensure-the-book-for-the-new-release-is-available)).  @sbueringer @fabriziopandini any ideas for better phrasing here?  do all the maintainers have access?  

last cycle i believe Cecile helped us with this (https://github.com/kubernetes-sigs/cluster-api/issues/6017#issuecomment-1823306891) but i am aware she is taking a step back from the project

**Comment by sbueringer** [comment]
IIRC Fabrizio and me have access. Very likely @vincepri as well.

**Comment by nawazkh** [comment]
@furkatgofurov7 and I were looking into this issue earlier, and the TL;DR is that "Today there is no automation for Netlify access, however there's a handful of people to handle access / requests for "all sites" (spanning SIGs / companies / contributors - to handle redundancy). It would be awesome to build something to automate it."

Reference conversation: https://kubernetes.slack.com/archives/C8TSNPY4T/p1697826615480259?thread_ts=1697826166.088039&cid=C8TSNPY4T

**Comment by fabriziopandini** [comment]
+1 to improve the doc with the list of people having access (or just maintainers, the list ~overlaps) for now. 
/kind documentation
/triage accepted

**Comment by sbueringer** [comment]
I think neither Killian nor Christian have Netlify access. I suspect Alberto also doesn't have it.

**Comment by fabriziopandini** [comment]
Just checked
There is Cecile, Vince, Me, Stefan, Jack, Matt (Invite Pending)
We can add more by asking to ContribEx

**Comment by cahillsf** [comment]
just opened a small PR, lmk if this is sufficient
