### ISSUE TITLE
Improve k8s-triage to be able to create issues in the Cluster API repo

### ISSUE THREAD

**Issue by cahillsf** [kubernetes-sigs/cluster-api#9851]
Theoretically we can use k8s-triage to generate bug reports for flaky tests via "file bug" ([link](https://storage.googleapis.com/k8s-triage/index.html?job=periodic-cluster-api-e2e-main)). Unfortunately the issues are always filed against k/k so we have to manually copy&paste the issue text to a Cluster API repo. Let's see if we can improve k8s-triage to be able to create issues in the Cluster API repo.

Carryover from: https://github.com/kubernetes-sigs/cluster-api/issues/9104

**Comment by cahillsf** [comment]
/area release

[Sunnatillo](https://github.com/Sunnatillo) expressed interest in working on this, will bring up in release meeting (he is not part of the k8s-sigs so cannot assign directly)

**Comment by fabriziopandini** [comment]
How much frequest is this use case... might be copy paste a few time is acceptable vs having to maintain something forever

**Comment by adityabhatia** [comment]
After looking into this issue quickly and debugging the POST request that the k8s-triage page makes [here](https://github.com/kubernetes/test-infra/blob/master/triage/interactive.js#L326), the relevant repository information for the respective jobs is not available IIUC. So fixing this issue will require more effort to change request URLs and adjusting the subsequent response properties accordingly [here](https://github.com/kubernetes/test-infra/blob/master/triage/render.js#L324), with the required testing.

**Comment by sbueringer** [comment]
Also in general needs agreement with the folks maintaining k8s-triage. I would recommend opening an issue in test-infra to see if they would be open to a change

**Comment by cahillsf** [comment]
reviewed again in RT meeting today.  seems like the effort of implementing/maintaining exceeds the value (echoing Fabrizio's sentiment here: https://github.com/kubernetes-sigs/cluster-api/issues/9851#issuecomment-1900542906).

im in favor of closing this issue, WDYT @fabriziopandini / @sbueringer ?

**Comment by fabriziopandini** [comment]
Thanks for looking into this again
We can eventually reopen/create a new issue in the future if conditions change

/close

**Comment by rexagod** [comment]
This concern came up during the CI Signal call today; @lentzi90 and I were wondering if it'd make sense to do this using the "Repo" field, where a populated and well-structured "Repo" field changes the behavior of the "file bug" button to instead file the issue in the same repository, without any breaking changes surfacing in the actual test results URL itself. This also makes sense from the perspective where someone using the same field, and looking at issues from the same repository only, would ideally want the tickets to be created in that repository itself.

**Comment by sbueringer** [comment]
I would suggest to create an issue / PR in the test-infra repo where k8s-triage is located (please link here as well)
