### ISSUE TITLE
Automate parts of the release notes that are "constant" through a minor release

### ISSUE THREAD

**Issue by cahillsf** [kubernetes-sigs/cluster-api#9852]
Automate parts of the release notes that are "constant" through a minor release by reading from some file to populate the data. For example, the supported kubernetes versions can be maintained in a file on each release branch independently.

Carryover from: https://github.com/kubernetes-sigs/cluster-api/issues/9104

**Comment by mcbenjemaa** [comment]
I can take this. 
/ assign

**Comment by kperath** [comment]
Also if we have existing examples of doing this? Any direction is appreciated.

Also I do wonder how useful this is as the given example of a constant section is the "support kubernetes versions" which is a pretty small copy and paste where automating might be overkill. Just a thought to ponder :)

**Comment by chandankumar4** [comment]
@kperath  I believe automating the "constant" part will make the process easier while generating the release notes. 
So as mentioned in the issue description we can start from "supported kubernetes versions" which can be maintained in a file on each release branch independently, the release-note-tool will read the version from there while generating.

ping me if you need any help and thanks for picking this up.

**Comment by sbueringer** [comment]
I'm wondering if this is really worth the effort

**Comment by chandankumar4** [comment]
> I'm wondering if this is really worth the effort . This would add the effort of maintaining a file per release branch and add another bit of complexity (sounds like we would then have to run the release note generation on the release branch)

Yes, I agree it will add more complexity rather than help in the release process.

**Comment by fabriziopandini** [comment]
@adilGhaffarDev should we close this one?

**Comment by adilGhaffarDev** [comment]
yes, let's close this one.
