### ISSUE TITLE
 Format dependencies to exclude multiple bumps in the same set of release notes

### ISSUE THREAD

**Issue by cahillsf** [kubernetes-sigs/cluster-api#9853]
Format dependencies to exclude multiple bumps in the same set of release notes. For Go dependencies there's a discussion in this thread: https://kubernetes.slack.com/archives/C8TSNPY4T/p1686045243091189. For Github actions and other dependencies an alternative solution will have to be found.

/triage accepted
/area release
/assign @willie-yao

**Comment by chrischdi** [comment]
Is this the same as #9853 ? If no: could we have different titles?

**Comment by furkatgofurov7** [comment]
@chrischdi yes it, we can close this as duplicate. All other items have been covered already from 9104, so this should not be meant to be named differently. 

/close
