### ISSUE TITLE
Add a new section to release notes for dependency changes (diff)

### ISSUE THREAD

**Issue by cahillsf** [kubernetes-sigs/cluster-api#9854]
For Go dependencies there's a discussion in this thread: https://kubernetes.slack.com/archives/C8TSNPY4T/p1686045243091189. 
For Github actions and other dependencies an alternative solution will have to be found. 

Carryover from: https://github.com/kubernetes-sigs/cluster-api/issues/9104

/assign @willie-yao 
/area release
/triage accepted

**Comment by sbueringer** [comment]
Specifically the idea was to generate the list of dependency changes instead of relying on an aggregation of PR titles from dependabot PRs. The latter doesn't include all bumps (as some bumps lead to transitive bumps of other PRs)

**Comment by fabriziopandini** [comment]
+1 to see if we can re-use what CAPZ is already doing. Also, I don't think we should put additional effort for GitHub actions versions (they are not relevant for CAPI users/the folks that look at release notes)

**Comment by sbueringer** [comment]
@willie-yao Thank you very much for making this happen! Really appreciate it
