### ISSUE TITLE
[clusterctl] Support multiple core-provider in a management cluster

### ISSUE THREAD

**Issue by sp-yduck** [kubernetes-sigs/cluster-api#9875]
### What would you like to be added (User Story)?

Currently clusterctl is assuming there is only one core provider in a management cluster. For example `clusterctl upgrade` returns an error. It should not raise an error but should properly upgrade the provider.

## how to reproduce
when there are multiple core provider (the one in `default` namespace is manually created as `clusterctl init` is also not supporting multiple core provider)
```
k get provider -A
NAMESPACE                           NAME                    AGE     TYPE                   PROVIDER      VERSION
capi-kubeadm-bootstrap-system       bootstrap-kubeadm       3m24s   BootstrapProvider      kubeadm       v1.6.0
capi-kubeadm-control-plane-system   control-plane-kubeadm   3m23s   ControlPlaneProvider   kubeadm       v1.6.0
capi-system                         cluster-api             3m25s   CoreProvider           cluster-api   v1.6.0
default                             cluster-api             10s     CoreProvider           cluster-api   v1.6.0
```
`clusterctl upgrade` raise an error like below
```
clusterctl upgrade apply --core cluster-api:v1.2.4
Checking cert-manager version...
Deleting cert-manager Version="v1.8.2"
Installing cert-manager Version="v1.13.2"
Waiting for cert-manager to be available...
Performing upgrade...
Error: invalid management cluster: there should a core provider, found 2
```
```
clusterctl upgrade plan
Checking cert-manager version...
Cert-Manager will be upgraded from "v1.8.2" to "v1.13.2"

Checking new release availability...
Error: invalid management cluster: there should a core provider, found 2
```

### Detailed Description

We are planning to have multiple core provider in one management cluster for some reason. Our plan is that each different core provider reconciles clusters/machines in each different namespace by using `--namespace` [flag](https://github.com/kubernetes-sigs/cluster-api/blob/main/main.go#L152). I think this multiple core provider solution works well as controller perspective. But it turns out `clusterctl` is not designed for multiple core provider in a management cluster.
Maybe there are some other commands that don't support multiple core provider (e.g. `clusterctl init`). But for now, my request is making `clusterctl upgrade` support multiple core provider so that we can upgrade multiple core provider at the same time.
This is helpful for the people who is manageing multiple core provider in one management cluster. 

Assuming
1. initialize management cluster with `clusterctl init`
2. remove default core provider from `capi-system` and remove `Provider` resource
3. deploy multiple core provider to some namespaces manually and add `Provider` resource for each core provider
4. upgrade all core provider with `clusterctl upgrade`  <- currently this part does not work

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
/area clusterctl

**Comment by sbueringer** [comment]
As of today: https://cluster-api.sigs.k8s.io/tasks/multiple-providers
