### ISSUE TITLE
Timed out after 300.000s. Timed out waiting for all machines to be exist

### ISSUE THREAD

**Issue by adilGhaffarDev** [kubernetes-sigs/cluster-api#9886]
### Which jobs are failing?

Failing:
- capi-e2e-dualstack-and-ipv6-main

Flaking:
- capi-e2e-main
- capi-e2e-mink8s-main

### Which tests are failing?

capi-e2e: [It] When testing clusterctl upgrades using ClusterClass (v1.6=>current) [ClusterClass] Should create a management cluster and then upgrade all the providers

### Since when has it been failing?

this fail started happening after the merge of this PR: https://github.com/kubernetes-sigs/cluster-api/pull/9799

### Testgrid link

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-dualstack-and-ipv6-main
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-mink8s-main

### Reason for failure (if possible)

need to investigate.

### Label(s) to be applied

/kind failing-test

**Comment by killianmuldoon** [comment]
/triage accepted

Looks like this test is very very flaky, but not permafailing. Would be great to find the root cause soon.
