### ISSUE TITLE
GCE machine actuator should collect current state

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#99]
_From @jessicaochen on January 11, 2018 17:8_

The machine actuator should get current state from the actual sources (eg. kubelet version from machine, VM info from gce) instead of a cached last-applied state. This will help with cases like the state changing under the covers.

https://github.com/kubernetes/kube-deploy/blob/master/cluster-api-gcp/cloud/google/instancestatus.go#L13

_Copied from original issue: kubernetes/kube-deploy#482_

**Comment by rsdcastro** [comment]
_From @karan on January 24, 2018 21:41_

I'll start working on this, and handle updates to `spec.providerConfig` first. Specifically, `zone`, `machineType`, and `image`.

**Comment by roberthbailey** [comment]
This issue was moved to kubernetes-sigs/cluster-api-provider-gcp#20
