### ISSUE TITLE
Remove skip from Machine health check test

### ISSUE THREAD

**Issue by mcbenjemaa** [kubernetes-sigs/cluster-api#9903]
### Which jobs are failing?

The node gone away test is flaky, and needs to be fixed.

### Which tests are failing?

https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go#L978

Also once this https://github.com/kubernetes-sigs/cluster-api/pull/9774 merged, this will also include a similar test.

### Since when has it been failing?

Don't know

### Label(s) to be applied

/kind failing-test
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by fabriziopandini** [comment]
cc @kubernetes-sigs/cluster-api-release-team

**Comment by adilGhaffarDev** [comment]
@mcbenjemaa can you share testgrid link where you are seeing this flake?

**Comment by sbueringer** [comment]
This issue is not about a flake occurring in CI. It is about a test that is disabled in our code with the justification that it is flaky.

**Comment by cahillsf** [comment]
/assign cahillsf

i have a PR open for this which should fix this
