### ISSUE TITLE
Remove Deprecated Code

### ISSUE THREAD

**Issue by cahillsf** [kubernetes-sigs/cluster-api#9904]
Relates to https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#track-remove-previously-deprecated-code (part of https://github.com/kubernetes-sigs/cluster-api/issues/9800)

Here are some potential items I came up with using some basic keyword searches (excluding anything related to `v1alpha4` removal as that is being tracked separately (https://github.com/kubernetes-sigs/cluster-api/issues/8038))

Would like some feedback before moving forward.

- ~~`UseExperimentalRetryJoin` is referenced in may places but appears to have been marked as deprecated for quite awhile~~: 
  - https://github.com/kubernetes-sigs/cluster-api/blob/ec45bdb68a0c6a87e9d4e980161823c2434748f1/bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go#L103-L117
  - https://github.com/kubernetes-sigs/cluster-api/pull/2763#discussion_r397306055
- ~~`metricsBindAddr` in metrics serving config: https://github.com/kubernetes-sigs/cluster-api/blob/ec45bdb68a0c6a87e9d4e980161823c2434748f1/util/flags/diagnostics.go#L45~~
- ~~binding/ownerref funcs in `exp/addons/api/v1beta1/clusterresourcesetbinding_types.go`: https://github.com/kubernetes-sigs/cluster-api/blob/main/exp/addons/api/v1beta1/clusterresourcesetbinding_types.go#L110-L166~~

Please let me know if there are other items I might have missed as well

**Comment by sbueringer** [comment]
We can't drop code in api packages without releasing a new apiVersion (e.g. v1beta2 / v1).

For the metrics-bind-addr. I would guess we want to keep it around for a few more releases to give folks time to adjust.

**Comment by cahillsf** [comment]
ah-- that makes sense, thanks for the guidance @sbueringer

**Comment by sbueringer** [comment]
@cahillsf Checked the occurrences of "Deprecated". We don't have do remove anything for this round.

A general improvement could be that we clearly state in the Deprecated messages when something can be removed
(although I wouldn't do this for api packages and just have the general rule for them to never remove deprecated code in the API packages)

**Comment by cahillsf** [comment]
sounds good, thanks for confirming @sbueringer, will go ahead and close this out
