### ISSUE TITLE
Restrict KCP Machine deletion

### ISSUE THREAD

**Issue by Levi080513** [kubernetes-sigs/cluster-api#9919]
### What would you like to be added (User Story)?

As a user/operator, i would like that the KCP Controller can restrict KCP Machine deletion and always ensure that KCP has a healthy number of replicas.

### Detailed Description

While performing cluster operations, the CP Machine may be deleted by mistake. So I would like that there is a mechanism to prevent this from happening.

When the KCP is not in the deleted state, 
1. 1 replica KCP needs to ensure that 1 replica cannot be deleted.
2. 3 replica KCP needs to ensure that 2 copies cannot be deleted.

It also needs to be combined with the current status of the ETCD cluster.

### Label(s) to be applied

/kind feature
/area provider/control-plane-kubeadm

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

We implemented cluster.x-k8s.io/remediate-machine for allowing a controlled deletion of CP machines
/close
