### ISSUE TITLE
Improve issue templates

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#993]
/kind feature

**Describe the solution you'd like**
We should update our template issues to add more details and be more verbose.

**Anything else you would like to add:**
/cc @timothysc

**Comment by timothysc** [comment]
remember, you need to 
/assign @timothysc

**Comment by vincepri** [comment]
PR templates have been improved, the issue template seems to be ok for now, feel free to reopen if necessary.

/close
