### ISSUE TITLE
[Question] How to use cluster API to add label and taint for a node

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#995]
/kind bug
/kind question

When I set up my cluster, I want to add label and taint for my node, how can I do this via cluster api?

/cc @detiber @vincepri 

FYI @xunpan @qiujian16 @jichenjc

**Comment by jichenjc** [comment]
@gyliu513 
https://github.com/kubernetes-sigs/cluster-api/issues/493 has the info

**Comment by gyliu513** [comment]
Thanks @jichenjc , this is duplicate with #493
