### ISSUE TITLE
Rename Others tabs in the Quick-Start

### ISSUE THREAD

**Issue by SD-13** [kubernetes-sigs/cluster-api#9953]
Had a small conversation here https://kubernetes.slack.com/archives/C8TSNPY4T/p1703707530548349
In the [quickstart guide](https://cluster-api.sigs.k8s.io/user/quick-start#generating-the-cluster-configuration), for cloud providers (at least where I faced it. For me, it was Azure) we need to follow instructions from the `Others...` tab. But the name `Others...` is not much meaningful here. Any thoughts on renaming this?

**Comment by fabriziopandini** [comment]
I don't have issues with "Others..." given that those tabs are list of providers , but I'm ok in renaming it in "Other proivders..." (both two instances)
/triage accepted

**Comment by SD-13** [comment]
Thanks @fabriziopandini, "Other proivders..." sounds better to me. I can change it.
/assign
