### ISSUE TITLE
Stuck at deleting the cluster.cluster.x-k8s.io object

### ISSUE THREAD

**Issue by yuzs2** [kubernetes-sigs/cluster-api#9954]
### What steps did you take and what happened?

Hi, I've created a workload cluster based on vsphere:
```
➭ k_mgmt -n mycluster-gpu-dev get cluster,clusterclass,clusterresourceset
NAME                             PHASE      AGE   VERSION
cluster.cluster.x-k8s.io/mycluster   Provisioned   43h   v1.26.8

NAME                                                 AGE
clusterclass.cluster.x-k8s.io/clusterclass-gpu-dev   43h

NAME                                                          AGE
clusterresourceset.addons.cluster.x-k8s.io/mycluster-crs-antrea   43h
```
The workload cluster worked fine, and I want to delete the workload cluster after using, however I was stunk at deleting the cluster:
```
Status:
  Conditions:
    Last Transition Time:  2024-01-03T21:23:07Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2024-01-02T12:53:49Z
    Status:                True
    Type:                  ControlPlaneInitialized
    Last Transition Time:  2024-01-02T12:53:49Z
    Status:                True
    Type:                  ControlPlaneReady
    Last Transition Time:  2024-01-03T21:23:07Z
    Status:                True
    Type:                  InfrastructureReady
    Last Transition Time:  2024-01-02T11:04:43Z
    Status:                True
    Type:                  TopologyReconciled
  Control Plane Ready:     true
  Infrastructure Ready:    true
  Observed Generation:     4
  Phase:                   Deleting
Events:
  Type    Reason    Age   From                Message
  ----    ------    ----  ----                -------
  Normal  Deleting  50m   cluster-controller  Cluster mycluster is Deleting
```
I didn't see any error messages, am I hitting any bugs?

### What did you expect to happen?

The cluster was successfully deleted

### Cluster API version

$ clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.2", GitCommit:"7b92ce4577e36adf013dc1dfd2b239fde4c36bc4", GitTreeState:"clean", BuildDate:"2023-05-02T15:22:41Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

### Kubernetes version

v1.26.8

I've re-created the workload cluster several times, and the deletion was quite fast. The pending deletion issue suddenly happened.

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
@yuzs2 The logs of the capi controller manager Pod should provide more details what the deletion is doing / why it's not making progress

**Comment by randomvariable** [comment]
/retitle Stuck at deleting the cluster.cluster.x-k8s.io object

**Comment by fabriziopandini** [comment]
/close

due to a lack of updates. we can eventually reopen if new info are available
