### ISSUE TITLE
Automated weekly release updates

### ISSUE THREAD

**Issue by typeid** [kubernetes-sigs/cluster-api#9982]
### What would you like to be added (User Story)?

As a member of the comms release team, I don't want to perform the repetitive task of creating release notes and posting them in slack manually every week. Therefore, I would like to have this process automated.

### Detailed Description

Posting the weekly update is part of the release tasks for the comms team: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#generate-weekly-pr-updates-to-post-in-slack

This process is toilsome and should be automated.

### Label(s) to be applied

/area release

**Comment by fabriziopandini** [comment]
I would advise not over-engineering this unless there is something already available in prow, I don't think we should invest time and energy in defining a way to handle slack credentials in CI

More importantly, if we are making this an automatic and impersonal task IMO we are missing the whole point of those communications, which is to keep contributors engaged in the release process. Weekly communication is the opportunity to inform about incoming steps of the release cycle, to ask contributors/providers teams to start testing beta releases and provide feedback, and to give heads-ups when breaking changes are merged so users/providers teams can their own preparation.

Ultimately, building and growing a community needs human interactions, and IMO an important part of the responsibilities communication release team is to take care of this. Weekly email are a great opportunity to do so, let's not waste it

**Comment by typeid** [comment]
I 100% agree with the overengineering part - and if there's no easy way, we can drop this. It could be "as simple" as having a weekly prow pipeline creating the notes, which someone then copy pastes to slack. 

```
making this an automatic and impersonal task IMO we are missing the whole point of those communications
```
Respectfully, I disagree with that part. I don't see how the process documented for the comms release team of running a script every week and copy pasting the content on slack is less impersonal vs having it automated. But as I wrote above, it doesn't have to be automated the whole way.

Automating the announcement creates a static base that can be used for discussion, it shouldn't prevent it.

**Comment by fabriziopandini** [comment]
>> making this an automatic and impersonal task IMO we are missing the whole point of those communications
> 
> Respectfully, I disagree with that part.

That's ok
The most important part for me is that there is a way to add value on top which is interesting and engaging for the rest of the community, and that we don't invest to much in this automation just to safe few copy paste once every week

**Comment by typeid** [comment]
/close

I'm happy doing this manually with the latest updates to the script, now that it's just as easy as copy pasting from somewhere. There's no point automating it into a slack bot at this point.
